import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from p13_kit import *
from p13_fig import *

p = newpack("class3-social-studies", "Social Studies — Class 3", "Class 3", "histoire-geo",
    "Class 3 Social Studies: community and local government, maps and directions, Cameroon's location, regions, relief and rivers, climate, farming and products, transport and communication, symbols, laws and duties, and living together.",
    REF % "Level II (Class 3) — Social Studies", wanted="social-studies")
R = p.programRef
NOTE = "Only simple, neutral and well-established facts are used; to be reviewed by a primary teacher against the official syllabus."
REGS = [("Adamawa", "Ngaoundéré"), ("Centre", "Yaoundé"), ("East", "Bertoua"), ("Far North", "Maroua"), ("Littoral", "Douala"),
        ("North", "Garoua"), ("North-West", "Bamenda"), ("West", "Bafoussam"), ("South", "Ebolowa"), ("South-West", "Buea")]
assert len(REGS) == 10
def C(n, shape="circle", color="orange", per=5, w=300, h=120): return count(n, shape, color, per, w, h)
flag = shapes([RECT(40, 20, 60, 100, fill="green"), RECT(100, 20, 60, 100, fill="red"), RECT(160, 20, 60, 100, fill="yellow"), POLY([130, 50, 135, 66, 152, 66, 138, 76, 143, 92, 130, 82, 117, 92, 122, 76, 108, 66, 125, 66], fill="yellow"), T(130, 140, "flag of Cameroon", 13, bold=True)], 260, 155)
compass = shapes([LINE(130, 120, 130, 25, arrow="end", width=3), LINE(130, 70, 235, 70, arrow="none", width=2), LINE(25, 70, 130, 70, width=2), LINE(130, 70, 130, 120, width=2),
                  T(130, 18, "N", 18, bold=True), T(130, 142, "S", 18, bold=True), T(250, 76, "E", 18, bold=True), T(10, 76, "W", 18, bold=True), CIRCLE(130, 70, 4, fill="red")], 270, 150)

ch = p.chapter("community-government", "Community, laws and citizens", R)
lesson(ch, "community-leaders", "Our community and its leaders", ["Name local leaders and services.", "Say how citizens help the community."],
  [("definition", "Community and leaders", "A community has **leaders**. In a village there may be a **chief** (traditional ruler) and elders. A town has a **council** led by a **mayor**. The country has a **government**. Leaders help to keep order and to provide services."),
   ("retenir", "Services", "Communities need **schools**, **health centres**, **clean water**, **roads** and **markets**. People pay **taxes** to help provide them. Citizens help by obeying laws, keeping places clean and joining community work."),
   ("pieges", "Common mistakes", "- A leader serves the people.\n- Public things belong to everybody; do not damage them.\n- Citizens have rights and duties.")],
  [("Example 1", "Name two services a community needs.", ["Think of what people need every day.", "Clean water and a health centre."], "Clean water and a health centre", cards(["chief and elders", "mayor and council", "government"], 3, 400, ch=44, size=13)),
   ("Example 2", "Who leads a town council?", ["A council has a head.", "The mayor."], "The mayor", None)],
  (cards(["school", "health centre", "water", "roads", "market"], 3, 400, ch=44, size=14), "Services in a community.", "Five boxes: school, health centre, water, roads, market."),
  [("m", "A service every community needs is...", "clean water", ["loud music", "rubbish", "closed roads"], "Clean water."), ("m", "A town council is led by a...", "mayor", ["pupil", "driver", "trader"], "Mayor."), ("t", "Public things belong to everybody.", True, "Yes.")],
  [("x", "Match the leader with where they serve.", [("chief", "village"), ("mayor", "town council"), ("head teacher", "school")], "Leaders."), ("m", "A good citizen...", "obeys the law and helps the community", ["breaks rules", "dirties roads", "wastes water"], "Good citizen.")],
  ("p", "A village has 2 water points, 1 school and 1 health centre. The people repair a broken water point.", [("n", "How many services in all? (2 + 1 + 1)", 4, "4."), ("m", "Why do they repair the water point?", "everybody needs clean water", ["it is fun", "to waste water", "to block the road"], "Need.")]),
  [("Class 3 social studies community: a village leader may be the...", "chief", ["pupil", "driver", "baker"], "Chief."),
   ("Class 3 social studies community: a town council is led by a...", "mayor", ["chief only", "pupil", "farmer"], "Mayor."),
   ("People pay taxes to...", "help provide public services", ["waste money", "break roads", "stop schools"], "Services."),
   ("A good citizen...", "obeys the law", ["breaks the law", "damages roads", "wastes water"], "Law."),
   ("Which is a public service?", "a health centre", ["a private toy", "a game", "a car"], "Health centre.")],
  ["Local government terms (chief, council, mayor) are general; check with the official civics text."])

lesson(ch, "laws-duties", "Rules, laws, rights and duties", ["Say why we have laws.", "Name some rights and duties of children and citizens."],
  [("definition", "Laws", "A **law** is a rule made for everybody in a country. Laws protect people and keep order. Those who break the law may be punished in a fair way. Police and courts help to apply the law."),
   ("retenir", "Rights and duties", "Children have **rights**: to a name, to be cared for, to go to school, to be safe, to play. They have **duties**: to respect others, to obey rules, to help at home, to study, and to take care of public property. Rights and duties go together."),
   ("pieges", "Common mistakes", "- Rights do not mean we can do whatever we like.\n- Respect the rights of others.\n- Tell a trusted adult if your rights are not respected.")],
  [("Example 1", "Name one right and one duty of a child.", ["Right: to go to school.", "Duty: to respect others."], "Right: go to school; duty: respect others", cards(["rights: school, care, safety", "duties: respect, obey, help"], 2, 400, ch=44, size=14)),
   ("Example 2", "Why do we need laws?", ["People live together.", "Laws protect everyone and keep order."], "To protect people and keep order", None)],
  (cards(["law", "right", "duty", "respect"], 4, 400, ch=44, size=16), "Key words.", "Four boxes: law, right, duty, respect."),
  [("m", "A law is...", "a rule for everybody in a country", ["a game", "a story", "a toy"], "Law."), ("m", "A duty of a pupil is to...", "respect the teacher", ["fight", "steal", "lie"], "Respect."), ("t", "We can break laws if we like.", False, "No.")],
  [("x", "Match the item with right or duty.", [("go to school", "right"), ("obey rules", "duty")], "Right or duty."), ("m", "If someone breaks a school rule, a fair step is...", "the teacher talks to the pupil", ["hit the pupil", "ignore it always", "laugh at him"], "Fair.")],
  ("p", "A class makes rules: 1. Be on time. 2. Listen. 3. Keep the class clean. 4. Respect others.", [("n", "How many rules?", 4, "Four."), ("m", "Which rule keeps the class clean?", "Keep the class clean.", ["Be on time.", "Listen.", "Respect others."], "Rule 3.")]),
  [("Class 3 social studies laws: laws are made to...", "protect people and keep order", ["cause fights", "waste time", "stop school"], "Protect."),
   ("Class 3 social studies rights: a right of a child is...", "to go to school", ["to hit others", "to steal", "to lie"], "School."),
   ("A duty is...", "something we must do", ["something we may ignore", "a toy", "a gift"], "Duty."),
   ("Rights and duties...", "go together", ["are opposites", "are the same", "do not exist"], "Together."),
   ("A child who is worried about their safety should tell...", "a trusted adult", ["no one", "a stranger", "a thief"], "Adult.")],
  ["Children's rights are listed in general terms (name, care, school, safety, play); check wording with the textbook."], prereq=["class3-social-studies-community-leaders"])

ch = p.chapter("maps-cameroon", "Maps and Cameroon", R)
lesson(ch, "directions-maps", "Directions and simple maps", ["Name the four main directions.", "Read a simple map with a key."],
  [("definition", "Directions", "The four main directions are **North (N)**, **South (S)**, **East (E)** and **West (W)**. The Sun rises in the **east** and sets in the **west**. A **compass** shows the directions."),
   ("retenir", "Maps", "A **map** is a drawing of a place seen from above. A **key** explains the signs. A **title** tells what the map shows. A **compass rose** shows north. A **scale** shows how big distances are."),
   ("pieges", "Common mistakes", "- East and west are not the same.\n- North is usually at the top of the map.\n- Read the key to understand the signs.")],
  [("Example 1", "In which direction does the Sun rise?", ["Think of the morning.", "In the east."], "East", compass),
   ("Example 2", "If you face north, which direction is behind you?", ["Opposite of north.", "South."], "South", None)],
  (compass, "A compass with the four main directions.", "A cross with N at the top, S at the bottom, E on the right and W on the left."),
  [("m", "The opposite of north is...", "south", ["east", "west", "up"], "South."), ("m", "The Sun sets in the...", "west", ["east", "north", "south"], "West."), ("t", "A map shows a place from above.", True, "Yes.")],
  [("x", "Match the direction with its short sign.", [("north", "N"), ("south", "S"), ("east", "E"), ("west", "W")], "Signs."), ("m", "A key on a map...", "explains the signs", ["draws the Sun", "tells the weather", "is a lock"], "Key.")],
  ("p", "Pupils make a map of their school. The gate is in the south and the playground is in the north of the classroom block.", [("m", "In which direction from the block is the playground?", "north", ["south", "east", "west"], "North."), ("m", "A pupil walks from the gate to the block. In which direction?", "north", ["south", "east", "west"], "From south to north.")]),
  [("Class 3 social studies maps: the four main directions are...", "north, south, east and west", ["up, down, left, right", "red, green, blue, yellow", "hot, cold, wet, dry"], "NSEW."),
   ("Class 3 social studies maps: the Sun rises in the...", "east", ["west", "north", "south"], "East."),
   ("A compass helps us to find...", "directions", ["money", "food", "water"], "Directions."),
   ("A map key explains the...", "signs on the map", ["weather", "time", "price"], "Signs."),
   ("North is usually at the... of the map.", "top", ["bottom", "left side only", "middle"], "Top.")],
  ["Map conventions are standard; the drawing is schematic."])

lesson(ch, "location-neighbours", "Where is Cameroon?", ["Say where Cameroon is in Africa.", "Name Cameroon's neighbours."],
  [("definition", "Location", "Cameroon is in **Central Africa**, near the **Equator**. It has a coast on the **Atlantic Ocean** (Gulf of Guinea). It looks a little like a triangle. The capital is **Yaoundé**; the biggest city and main port is **Douala**."),
   ("retenir", "Neighbours", "Cameroon's neighbours are **Nigeria** (west), **Chad** (north-east), the **Central African Republic** (east), and the **Republic of the Congo**, **Gabon** and **Equatorial Guinea** (south). Six neighbours in all."),
   ("pieges", "Common mistakes", "- Cameroon is not in West Africa only: we say Central Africa.\n- Nigeria is to the west, not the east.\n- Count neighbouring countries: six.")],
  [("Example 1", "Which country is to the west of Cameroon?", ["Look at the neighbours list.", "Nigeria."], "Nigeria", cards(["Nigeria: west", "Chad: north-east", "C.A.R.: east", "Congo, Gabon, Eq. Guinea: south"], 2, 400, ch=40, size=11)),
   ("Example 2", "On which ocean does Cameroon have a coast?", ["Cameroon is in the Gulf of Guinea.", "The Atlantic Ocean."], "The Atlantic Ocean", None)],
  (cards(["Nigeria", "Chad", "Central African Republic", "Congo", "Gabon", "Equatorial Guinea"], 2, 400, ch=36, size=12), "Neighbours of Cameroon.", "Six boxes with the neighbours of Cameroon."),
  [("n", "How many countries share a border with Cameroon?", 6, "Six."), ("m", "A neighbour of Cameroon in the west is...", "Nigeria", ["Gabon", "Chad", "Egypt"], "Nigeria."), ("m", "Cameroon has a coast on the...", "Atlantic Ocean", ["Indian Ocean", "Red Sea", "Pacific Ocean"], "Atlantic.")],
  [("m", "Which is NOT a neighbour of Cameroon?", "Ghana", ["Chad", "Gabon", "Nigeria"], "Ghana is not."), ("x", "Match the neighbour with its direction.", [("Nigeria", "west"), ("Chad", "north-east"), ("Gabon", "south")], "Directions.")],
  ("p", "A trader drives from Douala in the Littoral to Yaoundé in the Centre.", [("m", "Which is the capital of Cameroon?", "Yaoundé", ["Douala", "Limbe", "Garoua"], "Yaoundé."), ("m", "Which is the main port?", "Douala", ["Yaoundé", "Bafoussam", "Maroua"], "Douala.")]),
  [("Class 3 social studies location: Cameroon is in...", "Central Africa", ["Europe", "Asia", "South America"], "Central Africa."),
   ("Class 3 social studies location: the capital of Cameroon is...", "Yaoundé", ["Douala", "Garoua", "Limbe"], "Yaoundé."),
   ("A neighbour of Cameroon in the south is...", "Gabon", ["Egypt", "Ghana", "Kenya"], "Gabon."),
   ("How many neighbouring countries has Cameroon?", "six", ["two", "four", "ten"], "Six."),
   ("Cameroon's main port is...", "Douala", ["Maroua", "Garoua", "Bertoua"], "Douala.")],
  ["Neighbours and directions are standard (Equatorial Guinea, Gabon and Republic of the Congo to the south). Border lengths and areas are left out."], prereq=["class3-social-studies-directions-maps"])

lesson(ch, "regions-capitals", "The ten regions and their capitals", ["Name the ten regions and their capitals.", "Group regions: north, centre, south, west."],
  [("definition", "Ten regions", "Cameroon has **ten regions**. Each has a regional capital. **Far North** (Maroua), **North** (Garoua) and **Adamawa** (Ngaoundéré) are in the north. **East** (Bertoua), **Centre** (Yaoundé) and **South** (Ebolowa) are in the centre and south."),
   ("retenir", "West and coast", "**West** (Bafoussam), **North-West** (Bamenda), **South-West** (Buea) and **Littoral** (Douala) are in the west and on the coast. The North-West and South-West regions are the two English-speaking regions; French is more widely used in the other eight."),
   ("pieges", "Common mistakes", "- Bamenda is in the North-West, Buea is in the South-West.\n- Yaoundé (Centre) is the capital of Cameroon.\n- The Littoral is the coast region, with Douala.")],
  [("Example 1", "Which region has Bafoussam as its capital?", ["Look at the list.", "The West Region."], "West", cards([r + ": " + c for r, c in REGS[:6]], 2, 400, ch=36, size=12)),
   ("Example 2", "In which region is Douala?", ["Douala is on the coast.", "Littoral."], "Littoral", None)],
  (cards([r + ": " + c for r, c in REGS], 2, 400, ch=36, size=12), "Regions and capitals.", "Ten boxes with each region and its capital."),
  [("m", "The capital of the Adamawa Region is...", "Ngaoundéré", ["Garoua", "Maroua", "Bertoua"], "Ngaoundéré."), ("m", "The capital of the South Region is...", "Ebolowa", ["Buea", "Douala", "Bafoussam"], "Ebolowa."), ("n", "How many regions are in the north? (Far North, North, Adamawa)", 3, "Three.")],
  [("x", "Match the region with its capital.", [("North-West", "Bamenda"), ("South-West", "Buea"), ("Littoral", "Douala"), ("East", "Bertoua")], "Capitals."), ("t", "Yaoundé is in the Centre Region.", True, "Yes.")],
  ("p", "A pupil lists: Maroua, Garoua, Ngaoundéré.", [("m", "These are capitals of regions in the...", "north", ["south", "west coast", "centre only"], "North."), ("n", "How many capitals are listed?", 3, "Three.")]),
  [("Class 3 social studies regions: the capital of the North Region is...", "Garoua", ["Maroua", "Buea", "Ebolowa"], "Garoua."),
   ("Class 3 social studies regions: the capital of the South-West is...", "Buea", ["Bamenda", "Bafoussam", "Douala"], "Buea."),
   ("The capital of the East Region is...", "Bertoua", ["Garoua", "Maroua", "Ebolowa"], "Bertoua."),
   ("The Littoral Region's capital is...", "Douala", ["Yaoundé", "Limbe", "Kribi"], "Douala."),
   ("How many regions has Cameroon?", "ten", ["six", "eight", "twelve"], "Ten.")],
  ["Regions, capitals and the two-region English-speaking statement are standard; wording of official language use should be checked."], prereq=["class3-social-studies-location-neighbours"])

lesson(ch, "relief-rivers", "Mountains, rivers and lakes", ["Name Mount Cameroon and some rivers and lakes.", "Say why rivers and mountains are useful."],
  [("definition", "Relief", "**Relief** means the shape of the land. Cameroon has coastal plains, plateaus, highlands and plains in the north. **Mount Cameroon** is the highest mountain in the country, near Buea in the South-West Region. It is an active volcano, about 4,000 metres high."),
   ("retenir", "Rivers and lakes", "Important rivers: the **Sanaga** (the longest river in Cameroon), the **Wouri** (near Douala), the **Benue** and the **Logone**. **Lake Chad** is in the far north, shared with other countries. **Lake Nyos** is a small crater lake in the North-West."),
   ("pieges", "Common mistakes", "- Mount Cameroon is in the South-West, not in the North.\n- Rivers can give water, fish, transport and electricity.\n- Do not swim in rivers you do not know.")],
  [("Example 1", "In which region is Mount Cameroon?", ["It is near Buea.", "The South-West Region."], "South-West", cards(["Mount Cameroon: SW", "Sanaga: river", "Wouri: Douala", "Lake Chad: far north"], 2, 400, ch=44, size=13)),
   ("Example 2", "Name two uses of a river.", ["People fish in rivers.", "Rivers give water and produce electricity."], "Water and fish (also transport, electricity)", None)],
  (cards(["Mount Cameroon", "Sanaga", "Wouri", "Lake Chad"], 4, 400, ch=44, size=11), "Some natural features.", "Four boxes: Mount Cameroon, Sanaga, Wouri, Lake Chad."),
  [("m", "The highest mountain in Cameroon is...", "Mount Cameroon", ["Mount Kenya", "Kilimanjaro", "a hill near Garoua"], "Mount Cameroon."), ("m", "The river near Douala is the...", "Wouri", ["Nile", "Congo", "Niger only"], "Wouri."), ("t", "Lake Chad is in the far north.", True, "Yes.")],
  [("x", "Match the feature with its place.", [("Mount Cameroon", "South-West Region"), ("Lake Chad", "far north"), ("River Wouri", "near Douala")], "Places."), ("m", "A use of a dam on a river is to...", "make electricity", ["make clouds", "make soil", "grow mountains"], "Electricity.")],
  ("p", "A class plans a trip: a volcano, a port river and a lake.", [("m", "Which mountain is a volcano?", "Mount Cameroon", ["Lake Nyos", "River Wouri", "Lake Chad"], "Volcano."), ("m", "Which river is near the port city?", "Wouri", ["Benue", "Logone", "Sanaga"], "Wouri.")]),
  [("Class 3 social studies relief: Mount Cameroon is in the...", "South-West Region", ["North Region", "Far North Region", "East Region"], "South-West."),
   ("Class 3 social studies rivers: the Wouri flows near...", "Douala", ["Maroua", "Bamenda", "Garoua"], "Douala."),
   ("Lake Chad is in the...", "far north", ["south", "west coast", "centre"], "Far north."),
   ("Relief means...", "the shape of the land", ["the weather", "the farm", "the town"], "Shape."),
   ("Mount Cameroon is an...", "active volcano", ["old lake", "river", "desert"], "Volcano.")],
  ["Height 'about 4,000 m' is approximate. The Sanaga is described as the longest river wholly within Cameroon in many textbooks; check wording."], prereq=["class3-social-studies-regions-capitals"])

lesson(ch, "climate-farming", "Climate, farming and products", ["Describe the hotter, drier north and the wetter south.", "Name crops and products of Cameroon."],
  [("definition", "Climate", "**Climate** is the usual weather of a place. The south and coast have a **hot and wet** climate with much rain. The north is **hotter and drier** with a long dry season. The highlands are **cooler**."),
   ("retenir", "Farming and products", "Many people are **farmers**. Food crops: cassava, maize, plantain, yams, beans, millet and sorghum (more in the north). Cash crops: **cocoa** and **coffee**, **bananas**, **oil palm**, **rubber**, **tea** (on highlands) and **cotton** (north). Cameroon also has forests, fish, petroleum and timber."),
   ("pieges", "Common mistakes", "- Cotton grows mainly in the north, cocoa in the forest zone.\n- Not every region grows every crop.\n- Cutting forests needs care and new planting.")],
  [("Example 1", "Which part of Cameroon is hotter and drier?", ["Think of the Sahel side.", "The north."], "The north", cards(["north: hot, drier", "south: hot, wet", "highlands: cooler"], 3, 400, ch=44, size=12)),
   ("Example 2", "Name a cash crop grown in the forest zone.", ["Cocoa likes warm wet forest.", "Cocoa."], "Cocoa", None)],
  (cards(["cocoa", "coffee", "banana", "oil palm", "tea", "cotton"], 3, 400, ch=44, size=15), "Some cash crops.", "Six boxes with cocoa, coffee, banana, oil palm, tea, cotton."),
  [("m", "A cash crop of the north is...", "cotton", ["cocoa", "banana", "rubber"], "Cotton."), ("m", "The south is...", "hot and wet", ["cold and dry", "snowy", "windy only"], "Hot and wet."), ("t", "Cameroon has forests, rivers and farms.", True, "Yes.")],
  [("x", "Match the crop with its use.", [("cassava", "food"), ("cocoa", "sold to make chocolate"), ("rubber", "used to make tyres")], "Uses."), ("m", "Which is a food crop?", "plantain", ["cotton", "rubber", "tea"], "Plantain.")],
  ("p", "A farmer in the West Region has 4 plots of maize and 3 plots of beans.", [("n", "How many plots? (4 + 3)", 7, "7."), ("m", "Are maize and beans food crops?", "yes", ["no", "only maize", "only beans"], "Both.")]),
  [("Class 3 social studies climate: the north is...", "hotter and drier", ["colder and wet", "snowy", "always rainy"], "North."),
   ("Class 3 social studies farming: cotton grows mainly in the...", "north", ["south coast", "east forest", "sea"], "North."),
   ("A food crop is...", "maize", ["cotton", "rubber", "timber"], "Maize."),
   ("Cocoa grows best in the...", "warm wet forest zone", ["desert", "snow", "dry plains"], "Forest."),
   ("The highlands are...", "cooler", ["hotter", "snowy always", "dry always"], "Cooler.")],
  ["Climate and crop zones are described in broad terms only; check with the textbook for regional details."], prereq=["class3-social-studies-relief-rivers"])

ch = p.chapter("symbols-transport", "Symbols, transport and living together", R)
lesson(ch, "symbols-days", "National symbols and national days", ["Describe the flag, motto and anthem.", "Name some national days."],
  [("definition", "Symbols", "The **flag** has three vertical stripes: green, red and yellow, with a yellow star on the red stripe. The **motto** is **Peace, Work, Fatherland**. The **anthem** is called **O Cameroon, Cradle of Our Forefathers** in English. We show respect to the symbols."),
   ("retenir", "National days", "**National Day** is on **20 May**. **Youth Day** is on **11 February**. **Labour Day** is on **1 May**. On these days there may be parades, sports and speeches. Schools may take part."),
   ("pieges", "Common mistakes", "- The star is on the red stripe, in the middle.\n- National Day is 20 May, Youth Day is 11 February.\n- Stand still and quiet for the flag and anthem.")],
  [("Example 1", "What is on the red stripe?", ["Look at the middle of the flag.", "A yellow star."], "A yellow star", flag),
   ("Example 2", "When is Youth Day?", ["It is in the month of February.", "11 February."], "11 February", None)],
  (flag, "The flag of Cameroon.", "A flag with green, red and yellow stripes and a yellow star on the red stripe."),
  [("m", "The motto of Cameroon is...", "Peace, Work, Fatherland", ["Hope, Joy, Light", "Unity, Land, Sea", "Learn, Play, Rest"], "Motto."), ("m", "National Day is on...", "20 May", ["11 February", "1 May", "25 December"], "20 May."), ("m", "Labour Day is on...", "1 May", ["20 May", "11 February", "1 January"], "1 May.")],
  [("x", "Match the day with the date.", [("National Day", "20 May"), ("Youth Day", "11 February"), ("Labour Day", "1 May")], "Dates."), ("t", "The star is on the green stripe.", False, "It is on the red stripe.")],
  ("p", "A school plans three events: Youth Day in February, Labour Day in May and National Day in May.", [("n", "How many events are in May?", 2, "Labour Day and National Day."), ("m", "On which day does the school take part in a parade for the whole nation?", "National Day (20 May)", ["Youth Day only", "Labour Day only", "no day"], "National Day.")]),
  [("Class 3 social studies symbols: the motto of Cameroon is...", "Peace, Work, Fatherland", ["Hope, Joy, Light", "Rest, Eat, Sleep", "Run, Jump, Play"], "Motto."),
   ("Class 3 social studies symbols: Youth Day is on...", "11 February", ["20 May", "1 May", "1 June"], "11 February."),
   ("National Day is on...", "20 May", ["11 February", "1 May", "5 June"], "20 May."),
   ("The star on the flag is...", "yellow", ["red", "green", "white"], "Yellow."),
   ("Labour Day is on...", "1 May", ["20 May", "11 February", "1 October"], "1 May.")],
  ["Dates (20 May, 11 February, 1 May) and the motto are well known; check the exact wording of the anthem title and the official calendar."], prereq=["class3-social-studies-climate-farming"])

lesson(ch, "transport-communication", "Transport and communication", ["Name means of transport and communication.", "Say why roads and phones are useful."],
  [("definition", "Transport", "**Transport** moves people and goods. By **road**: buses, taxis, lorries, motorbikes. By **rail**: trains. By **water**: boats and ships using ports like Douala. By **air**: aeroplanes from airports such as Douala and Yaoundé. Roads link villages and towns."),
   ("retenir", "Communication", "**Communication** is sending messages. Old ways: **talking drums**, **letters**. Modern ways: **telephone**, **radio**, **television**, **newspapers** and the **internet**. Good roads and networks help trade, health and schools."),
   ("pieges", "Common mistakes", "- Overloading vehicles is dangerous.\n- Wear seat belts and helmets.\n- Check news from a reliable source.")],
  [("Example 1", "Name a means of transport on water.", ["Ports are by the sea.", "A ship or boat."], "A ship or boat", cards(["road: bus", "rail: train", "water: ship", "air: plane"], 4, 400, ch=44, size=12)),
   ("Example 2", "Name two means of communication.", ["Think of sending a message.", "Telephone and radio."], "Telephone and radio", None)],
  (cards(["telephone", "radio", "television", "letters"], 4, 400, ch=44, size=13), "Means of communication.", "Four boxes with telephone, radio, television, letters."),
  [("m", "A port is a place for...", "ships", ["trains", "lorries", "bicycles"], "Ships."), ("m", "Which is a means of communication?", "radio", ["lorry", "tractor", "bicycle"], "Radio."), ("t", "Roads help to carry goods to market.", True, "Yes.")],
  [("x", "Match the transport with the place.", [("train", "rails"), ("ship", "sea"), ("plane", "air")], "Places."), ("n", "A lorry carries 120 bags of rice. 45 are unloaded at Edéa. How many are left? (120 − 45)", 75, "75.", "bags")],
  ("p", "A bus leaves Bafoussam with 45 passengers. 20 get off at Douala and 12 get on.", [("n", "How many passengers now? (45 − 20 + 12)", 37, "37."), ("m", "A safe rule for passengers is...", "use seat belts if available and do not overload", ["stand on the roof", "hang out the door", "fight"], "Safety.")]),
  [("Class 3 social studies transport: ships dock at a...", "port", ["bus stop", "airport", "station"], "Port."),
   ("Class 3 social studies communication: a means of communication is...", "the telephone", ["a lorry", "a boat", "a spade"], "Telephone."),
   ("An aeroplane uses an...", "airport", ["port", "bus station", "market"], "Airport."),
   ("Roads help us to...", "carry people and goods", ["stop trade", "block towns", "make rain"], "Transport."),
   ("A talking drum was used to...", "send messages", ["cook", "dig", "sew"], "Messages.")],
  ["Talking drums as a traditional means of communication is a common textbook example; check wording and avoid claims about a specific people."], prereq=["class3-social-studies-symbols-days"])

lesson(ch, "living-together", "Living together: cultures and respect", ["Say that Cameroon has many groups and languages.", "Show respect for other people and cultures."],
  [("definition", "Many cultures", "Cameroon has **many ethnic groups** and **many languages**, as well as English and French. People have different foods, clothes, dances and festivals. This variety is part of our country's richness."),
   ("retenir", "Respect and peace", "We live well together when we **respect** each other, **listen**, **share**, and settle disagreements **peacefully**. We do not insult or exclude others because of their language, region, religion or family. We help each other in need."),
   ("pieges", "Common mistakes", "- Do not make fun of another person's accent, food or clothes.\n- Do not say one group is better than another.\n- Say sorry and make peace after an argument.")],
  [("Example 1", "A new pupil speaks a language you do not know. What do you do?", ["Do not laugh.", "Greet her and show friendship."], "Greet her and be friendly", cards(["respect", "listen", "share", "make peace"], 4, 400, ch=44, size=14)),
   ("Example 2", "Two friends quarrel over a ball. What is a good way to settle it?", ["Do not fight.", "Talk and take turns."], "Talk and take turns", None)],
  (cards(["many languages", "many foods", "many dances", "one country"], 2, 400, ch=44, size=15), "Variety in our country.", "Four boxes about the variety in our country."),
  [("m", "In Cameroon there are...", "many cultures and languages", ["only one language", "no festivals", "no foods"], "Many."), ("m", "A good way to settle a quarrel is to...", "talk and take turns", ["fight", "shout", "hide"], "Talk."), ("t", "We should respect other people's culture.", True, "Yes.")],
  [("m", "A friend has a different accent. You should...", "listen and respect", ["laugh", "copy to tease", "ignore"], "Respect."), ("x", "Match the situation with a good response.", [("a quarrel", "talk and make peace"), ("a new pupil", "welcome her")], "Responses.")],
  ("p", "In Class 3 there are pupils who speak English, French and other local languages at home.", [("m", "How should the pupils treat each other?", "with respect", ["with insults", "by ignoring", "by fighting"], "Respect."), ("m", "Which languages are official in Cameroon?", "English and French", ["Spanish and Arabic", "German and Latin", "Only a local language"], "English and French.")]),
  [("Class 3 social studies living together: we should show...", "respect for other cultures", ["fear", "anger", "teasing"], "Respect."),
   ("Class 3 social studies living together: an argument can be settled by...", "talking peacefully", ["fighting", "shouting", "hiding"], "Peace."),
   ("Cameroon has...", "many ethnic groups and languages", ["only one group", "no languages", "no festivals"], "Many."),
   ("Insulting someone for their language is...", "wrong", ["fine", "funny", "good"], "Wrong."),
   ("Differences between people are...", "part of our richness", ["a problem", "a joke", "a danger"], "Richness.")],
  ["Written to be neutral and inclusive, with no statistics (e.g. number of languages) given; teachers may add local examples."], prereq=["class3-social-studies-transport-communication"])

lesson(ch, "natural-resources", "Our natural resources and how to protect them", ["Name natural resources of Cameroon.", "Say how to protect them."],
  [("definition", "Natural resources", "**Natural resources** come from nature. Examples in Cameroon: **forests** (timber), **water** (rivers, rain), **fertile soil** (farming), **fish**, **petroleum**, and wildlife such as elephants. People use resources to live and to earn money."),
   ("retenir", "Protecting them", "Some resources are used up if we waste them. **Protect** them: plant trees to replace those cut, keep rivers clean, do not over-fish, do not hunt protected animals, and use water and electricity carefully. National parks protect wildlife."),
   ("pieges", "Common mistakes", "- Resources belong to everybody, including future children.\n- Burning plastic and dumping oil harm water and soil.\n- Do not buy or sell protected animals.")],
  [("Example 1", "Name two natural resources.", ["Think of forests and rivers.", "Forests and water."], "Forests and water", cards(["forests", "water", "soil", "fish"], 4, 400, ch=44, size=14)),
   ("Example 2", "How can we protect forests?", ["Do not cut without planting.", "Plant new trees."], "Plant new trees", None)],
  (cards(["plant trees", "keep rivers clean", "save water", "protect animals"], 2, 400, ch=44, size=15), "Protecting resources.", "Four boxes with ways to protect resources."),
  [("m", "Which is a natural resource?", "a forest", ["a toy", "a chair", "a pencil"], "Forest."), ("m", "A way to protect forests is to...", "plant trees", ["burn them", "cut all trees", "dump rubbish"], "Plant."), ("t", "We should keep rivers clean.", True, "Yes.")],
  [("x", "Match the resource with a use.", [("forest", "timber"), ("river", "water and fish"), ("soil", "farming")], "Uses."), ("m", "National parks help to...", "protect wildlife", ["cut forests", "make noise", "build roads only"], "Protect.")],
  ("p", "A school club plants 6 trees each month for 3 months.", [("n", "How many trees in all? (6 × 3)", 18, "18."), ("m", "Why do they plant trees?", "to replace trees that are cut and to protect soil", ["to waste time", "to block the road", "for no reason"], "Protect.")]),
  [("Class 3 social studies resources: a natural resource is...", "a forest", ["a toy", "a school bag", "a calculator"], "Forest."),
   ("Class 3 social studies resources: to protect forests we...", "plant trees", ["burn them", "cut them all", "ignore them"], "Plant."),
   ("Rivers should be kept...", "clean", ["dirty", "dark", "empty"], "Clean."),
   ("Wild animals should be...", "protected", ["hunted without limit", "sold", "ignored"], "Protected."),
   ("Resources belong to...", "everybody, now and in the future", ["only one person", "nobody", "only visitors"], "Everyone.")],
  ["Petroleum and wildlife are named as resources without figures; check wording on protected species and parks."], prereq=["class3-social-studies-living-together"])

p.write()
