import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from p13_kit import *
from p13_fig import *

p = newpack("class3-maths", "Mathematics — Class 3", "Class 3", "maths",
    "Class 3 lessons: numbers to 10 000, rounding, the four operations, times tables, fractions, length, mass, capacity, perimeter, time, money and simple data.",
    REF % "Level II (Class 3) — Mathematics")
R = p.programRef
NOTE = "Number range, methods and the order in which topics appear (e.g. long division, thirds and fifths) are to be checked against the official syllabus."

# ===================================================== numbers
ch = p.chapter("numbers", "Place value and rounding", R)
lesson(ch, "place-value-10000", "Numbers to 10 000", ["Read and write numbers to 10 000.", "Give the value of each digit."],
  [("definition", "Thousands", "Ten hundreds make **one thousand**. A four-digit number has **thousands, hundreds, tens and ones**. In 3 452: 3 thousands, 4 hundreds, 5 tens, 2 ones. That is 3000 + 400 + 50 + 2."),
   ("retenir", "Place value table", "Each digit has a **place** and a **value**. In 7 081 the digit 7 is worth 7000 and the 0 is in the hundreds place (no hundreds). 10 000 is ten thousands."),
   ("pieges", "Common mistakes", "- 2 005 is not 205.\n- Keep a zero for an empty place.\n- Write a space between thousands and hundreds: 4 560.")],
  [("Example 1", "Write 6 thousands, 2 hundreds, 0 tens and 9 ones.", ["6000 + 200 + 0 + 9.", "That is 6 209."], "6 209", table_fig([["Th", "H", "T", "O"], ["6", "2", "0", "9"]], 280, 70, 34)),
   ("Example 2", "What is the value of the 5 in 3 452?", ["The 5 is in the tens place.", "5 tens is 50."], "50", None)],
  (table_fig([["Th", "H", "T", "O"], ["3", "4", "5", "2"]], 280, 70, 34), "3 452 in a place value table.", "A table with columns thousands, hundreds, tens, ones and the digits 3, 4, 5, 2."),
  [("n", "4000 + 700 + 20 + 6 = ?", 4726, "4 726."), ("n", "What is the hundreds digit of the number 5 380?", 3, "The hundreds digit is 3."), ("m", "The value of 8 in 8 140 is...", "8000", ["800", "80", "8"], "Thousands place.")],
  [("n", "One more than 4 999 is...", 5000, "5 000."), ("x", "Match.", [("2000 + 30 + 4", "2 034"), ("2000 + 300 + 4", "2 304"), ("2000 + 300 + 40", "2 340"), ("2000 + 3", "2 003")], "Watch the zeros.")],
  ("p", "A cocoa farmer near Mbalmayo sells 3 245 kg of cocoa in a season.", [("n", "How many thousands in 3 245?", 3, "3."), ("n", "He sells 755 kg more. How many kg now? (3 245 + 755)", 3245 + 755, "4 000.", "kg")]),
  [("Class 3 maths place value: in 5 321 the 5 is worth...", "5000", ["500", "50", "5"], "Thousands."),
   ("Class 3 maths place value: 2000 + 500 + 6 equals...", "2 506", ["2 056", "256", "25 006"], "2 506."),
   ("Ten hundreds make...", "one thousand", ["ten", "one hundred", "ten thousand"], "1 000."),
   ("In 9 070 the tens digit is...", "7", ["9", "0", "70"], "7 tens."),
   ("The biggest 4-digit number is...", "9 999", ["9 000", "10 000", "1 000"], "9 999.")],
  [NOTE])

lesson(ch, "compare-round", "Comparing and rounding", ["Compare numbers up to 10 000.", "Round to the nearest 10 and 100."],
  [("definition", "Rounding", "To **round** a number means to change it to a nearby easy number. To round to the nearest 10, look at the ones digit. If it is 5 or more, round **up**. If it is less than 5, round **down**."),
   ("retenir", "Examples", "63 → 60 (3 is less than 5). 67 → 70. 350 → 400 to the nearest 100 (5 tens rounds up). 349 → 300."),
   ("pieges", "Common mistakes", "- 5 rounds up, not down.\n- Rounding to 100 looks at the tens digit.\n- Rounded numbers are only close, not exact.")],
  [("Example 1", "Round 46 to the nearest 10.", ["The ones digit is 6, which is 5 or more.", "Round up: 50."], "50", numline(40, 50, [46])),
   ("Example 2", "Round 2 370 to the nearest 100.", ["The tens digit is 7, which is 5 or more.", "Round up the hundreds: 2 400."], "2 400", None)],
  (numline(40, 50, [43]), "43 is closer to 40 than to 50.", "A number line from 40 to 50 with a red dot at 43."),
  [("n", "Round 84 to the nearest 10.", 80, "4 is less than 5, down."), ("n", "Round 75 to the nearest 10.", 80, "5 rounds up."), ("n", "Round 640 to the nearest 100.", 600, "4 tens: down.")],
  [("m", "Which number is greater?", "5 408", ["5 084", "4 850", "5 048"], "Compare: thousands 5, then hundreds 4 > 0."), ("n", "Round 1 560 to the nearest 100.", 1600, "6 tens: up.")],
  ("p", "A market trader in Garoua sells 348 tomatoes in a week.", [("n", "Round 348 to the nearest 10.", 350, "8 rounds up."), ("n", "Round 348 to the nearest 100.", 300, "4 tens: down.")]),
  [("Class 3 maths rounding: 38 rounded to the nearest 10 is...", "40", ["30", "35", "50"], "8 up."),
   ("Class 3 maths rounding: 612 rounded to the nearest 100 is...", "600", ["700", "610", "620"], "1 ten: down."),
   ("When the digit is 5 or more we round...", "up", ["down", "sideways", "never"], "Up."),
   ("Which is less: 4 999 or 5 001?", "4 999", ["5 001", "equal", "none"], "4 999."),
   ("Round 95 to the nearest 10.", "100", ["90", "95", "10"], "5 up.")],
  [], prereq=["class3-maths-place-value-10000"])

# ===================================================== operations
ch = p.chapter("operations", "The four operations", R)
lesson(ch, "add-sub-3digit", "Adding and subtracting 3- and 4-digit numbers", ["Add numbers with carrying.", "Subtract numbers with borrowing."],
  [("definition", "Column method", "Write the numbers in columns: ones under ones, tens under tens, hundreds under hundreds. Add or subtract from the right. Carry a ten when ones make 10 or more."),
   ("methode", "Subtract", "Subtract from the right. If the top digit is too small, **borrow** one from the next place. 502 − 267: borrow, then 12 − 7 = 5; 9 − 6 = 3; 4 − 2 = 2; answer 235."),
   ("pieges", "Common mistakes", "- Line up the digits.\n- Do not forget carried digits.\n- Check with the opposite operation.")],
  [("Example 1", "458 + 267 = ?", ["Ones: 8 + 7 = 15. Write 5, carry 1.", "Tens: 5 + 6 + 1 = 12. Write 2, carry 1. Hundreds: 4 + 2 + 1 = 7. Answer 725."], str(458 + 267), None),
   ("Example 2", "502 − 267 = ?", ["Borrow: 502 is 4 hundreds, 10 tens, 12 ones. 12 − 7 = 5.", "Tens: 9 tens are left (one was borrowed): 9 − 6 = 3. Hundreds: 4 − 2 = 2. Answer 235."], str(502 - 267), None)],
  (cards(["458", "+ 267", "= 725"], 3, 400, ch=40), "458 + 267 = 725.", "Three boxes showing 458 plus 267 equals 725."),
  [("n", "345 + 278 = ?", 345 + 278, "623."), ("n", "812 − 345 = ?", 812 - 345, "467."), ("n", "1 250 + 750 = ?", 1250 + 750, "2 000.")],
  [("n", "4 003 − 1 998 = ?", 4003 - 1998, "2 005."), ("n", "2 689 + 1 475 = ?", 2689 + 1475, "4 164.")],
  ("p", "A school in Bamenda collects money for a library. Class 3 gives 4 250 FCFA, Class 4 gives 5 675 FCFA.", [("n", "How much altogether?", 4250 + 5675, "9 925.", "FCFA"), ("n", "A set of books costs 8 500 FCFA. How much is left after buying it?", 4250 + 5675 - 8500, "9 925 − 8 500 = 1 425.", "FCFA")]),
  [("Class 3 maths columns: 326 + 135 equals...", "461", ["451", "361", "4 511"], "461."),
   ("Class 3 maths columns: 700 − 250 equals...", "450", ["550", "950", "350"], "450."),
   ("To check 800 − 300 = 500 we add...", "500 + 300", ["800 + 300", "500 − 300", "800 − 500 only"], "800."),
   ("999 + 1 equals...", "1 000", ["990", "9 910", "100"], "1 000."),
   ("Which is the right start when adding in columns?", "ones column", ["hundreds column", "thousands column", "the biggest digit"], "Right side first.")],
  [NOTE], prereq=["class3-maths-place-value-10000"])

lesson(ch, "times-tables", "Times tables 2 to 10", ["Know the multiplication tables up to 10 × 10.", "Use patterns to learn the facts."],
  [("definition", "Tables", "A times table is repeated adding. 6 × 4 = 24 because 4 + 4 + 4 + 4 + 4 + 4 = 24. Order does not matter: 6 × 4 = 4 × 6."),
   ("retenir", "Tricks", "× 9: the digits of the answer add to 9 (9 × 4 = 36: 3 + 6 = 9). × 5: ends in 0 or 5. × 10: add a zero. × 4: double and double again."),
   ("pieges", "Common mistakes", "- 7 × 8 = 56 (say 5, 6, 7, 8: 56 = 7 × 8).\n- 6 × 6 = 36.\n- Do not mix up 8 × 8 = 64 and 8 × 7 = 56.")],
  [("Example 1", "How many days in 4 weeks?", ["A week has 7 days.", "4 × 7 = 28."], str(4 * 7), array(4, 7)),
   ("Example 2", "A box holds 9 eggs. How many in 6 boxes?", ["6 × 9.", "6 × 9 = 54 (5 + 4 = 9)."], str(6 * 9), None)],
  (table_fig([["×", "6", "7", "8", "9"], ["6", "36", "42", "48", "54"], ["7", "42", "49", "56", "63"]], 400, 70, 32), "Part of the times table.", "A table of products of 6 and 7 with 6, 7, 8, 9."),
  [("n", "6 × 7 = ?", 42, "42."), ("n", "8 × 8 = ?", 64, "64."), ("n", "9 × 9 = ?", 81, "81.")],
  [("x", "Match.", [("7 × 6", "42"), ("8 × 5", "40"), ("9 × 3", "27"), ("4 × 12", "48")], "Use the tables."), ("m", "Which is NOT in the 4 times table?", "18", ["16", "24", "36"], "4 × 4 = 16, 4 × 6 = 24, 4 × 9 = 36; 18 is not.")],
  ("p", "A trader sells oranges in heaps of 8.", [("n", "How many oranges in 7 heaps?", 56, "7 × 8 = 56."), ("n", "Each orange costs 25 FCFA. What is the price of one heap? (8 × 25)", 200, "200.", "FCFA")]),
  [("Class 3 maths tables: 7 × 7 equals...", "49", ["42", "56", "77"], "49."),
   ("Class 3 maths tables: 9 × 5 equals...", "45", ["54", "14", "95"], "45."),
   ("6 × 8 equals...", "48", ["46", "54", "42"], "48."),
   ("The digits of the answers in the 9 times table (up to 10) add up to...", "9", ["10", "18 always", "3"], "9 × 3 = 27: 2 + 7 = 9."),
   ("12 × 2 equals...", "24", ["14", "122", "10"], "24.")],
  [NOTE], prereq=["class3-maths-add-sub-3digit"])

lesson(ch, "multiply-by-1digit", "Multiplying a 2- or 3-digit number by 1 digit", ["Multiply a bigger number by a small number.", "Carry in multiplication."],
  [("definition", "Method", "To multiply 23 × 4: multiply the ones: 3 × 4 = 12. Write 2, carry 1. Multiply the tens: 2 × 4 = 8, plus 1 = 9. Answer 92."),
   ("methode", "Break apart", "Or break 23 into 20 + 3. 20 × 4 = 80 and 3 × 4 = 12. Add: 80 + 12 = 92."),
   ("pieges", "Common mistakes", "- Do not forget the carried digit.\n- Multiply every digit.\n- 0 in the middle: 105 × 3 = 315.")],
  [("Example 1", "34 × 5 = ?", ["Ones: 4 × 5 = 20. Write 0, carry 2.", "Tens: 3 × 5 = 15, plus 2 = 17. Answer 170."], str(34 * 5), None),
   ("Example 2", "126 × 3 = ?", ["100 × 3 = 300, 20 × 3 = 60, 6 × 3 = 18.", "300 + 60 + 18 = 378."], str(126 * 3), None)],
  (cards(["23 × 4", "20 × 4 = 80", "3 × 4 = 12", "80 + 12 = 92"], 2, 400, ch=40), "Break apart: 23 × 4.", "Four boxes showing 23 times 4 broken into 80 and 12."),
  [("n", "23 × 3 = ?", 23 * 3, "69."), ("n", "45 × 2 = ?", 45 * 2, "90."), ("n", "112 × 4 = ?", 112 * 4, "448.")],
  [("n", "56 × 7 = ?", 56 * 7, "392."), ("n", "208 × 3 = ?", 208 * 3, "624.")],
  ("p", "A farmer in Buea packs 36 bananas in each box.", [("n", "How many bananas in 5 boxes?", 36 * 5, "180."), ("n", "Each box sells for 1 500 FCFA. How much for 5 boxes?", 1500 * 5, "7 500.", "FCFA")]),
  [("Class 3 maths multiplying: 12 × 4 equals...", "48", ["16", "124", "46"], "48."),
   ("Class 3 maths multiplying: 30 × 5 equals...", "150", ["35", "15", "1 500"], "150."),
   ("25 × 4 equals...", "100", ["29", "80", "1 000"], "100."),
   ("When multiplying 2-digit numbers by 1 digit we start with the...", "ones", ["hundreds", "answer", "biggest"], "Ones."),
   ("101 × 5 equals...", "505", ["55", "515", "1 005"], "505.")],
  [NOTE], prereq=["class3-maths-times-tables"])

lesson(ch, "division-remainders", "Division and remainders", ["Divide by 2 to 10.", "Understand a remainder."],
  [("definition", "Division", "Division is sharing into equal groups. 24 ÷ 6 = 4 because 6 × 4 = 24. Sometimes there is something left over. This is the **remainder**."),
   ("retenir", "Remainder", "17 ÷ 5: 5 × 3 = 15 and 2 are left. So 17 ÷ 5 = 3 remainder 2 (r 2). The remainder must be smaller than the number you divide by."),
   ("pieges", "Common mistakes", "- 8 ÷ 2 is not 2 ÷ 8.\n- The remainder is smaller than the divisor.\n- Check: 3 × 5 + 2 = 17.")],
  [("Example 1", "36 ÷ 4 = ?", ["Think: 4 × 9 = 36.", "So 36 ÷ 4 = 9."], str(36 // 4), None),
   ("Example 2", "23 ÷ 5 = ?", ["5 × 4 = 20. 23 − 20 = 3.", "So 23 ÷ 5 = 4 remainder 3."], "4 r 3", None)],
  (count(23, "circle", "orange", 5, 300, 150), "23 balls in groups of 5: 4 groups and 3 left over.", "Twenty-three orange circles in rows of five."),
  [("n", "42 ÷ 6 = ?", 7, "6 × 7 = 42."), ("n", "81 ÷ 9 = ?", 9, "9 × 9 = 81."), ("n", "What is the remainder of 17 ÷ 5?", 2, "2.")],
  [("n", "What is the remainder of 29 ÷ 4?", 29 % 4, "4 × 7 = 28; 1 left."), ("n", "96 ÷ 4 = ?", 96 // 4, "24.")],
  ("p", "A teacher has 47 pencils for 5 groups.", [("n", "How many pencils does each group get?", 47 // 5, "47 ÷ 5 = 9 r 2."), ("n", "How many pencils are left over?", 47 % 5, "2.")]),
  [("Class 3 maths division: 45 ÷ 9 equals...", "5", ["4", "6", "36"], "5."),
   ("Class 3 maths division: 20 ÷ 3 gives remainder...", "2", ["0", "1", "6"], "20 = 6 × 3 + 2."),
   ("If 7 × 8 = 56, then 56 ÷ 8 =", "7", ["8", "48", "64"], "7."),
   ("A remainder is smaller than the...", "number we divide by", ["answer times 2", "biggest number", "total"], "Smaller than divisor."),
   ("63 ÷ 7 equals...", "9", ["8", "7", "56"], "9.")],
  [NOTE], prereq=["class3-maths-times-tables"])

lesson(ch, "word-problems", "Problems with all four operations", ["Choose the right operation.", "Solve problems with two steps."],
  [("methode", "Steps", "1. Read the problem two times. 2. Underline the numbers. 3. Choose + − × or ÷. 4. Work it out. 5. Write the answer with the unit. 6. Ask: is it sensible?"),
   ("retenir", "Which operation?", "Put together: **add**. Take away or compare: **subtract**. Equal groups: **multiply**. Share equally: **divide**."),
   ("pieges", "Common mistakes", "- Do not use every number just because it is there.\n- Do the steps in order.\n- Check with an estimate.")],
  [("Example 1", "A box holds 12 bottles. A shop buys 6 boxes and sells 50 bottles. How many bottles are left?", ["Bottles bought: 12 × 6 = 72.", "Left: 72 − 50 = 22."], str(12 * 6 - 50), None),
   ("Example 2", "84 pupils go on a trip. Each bus takes 30. How many buses? ", ["84 ÷ 30 = 2 remainder 24.", "24 pupils still need a bus, so we need 3 buses."], "3 buses", None)],
  (cards(["add: together", "subtract: left", "multiply: groups", "divide: share"], 2, 400, ch=38), "Which operation?", "Four boxes with clue words for the four operations."),
  [("n", "A packet has 8 biscuits. How many in 7 packets?", 56, "56."), ("n", "72 mangoes are shared by 9 women. How many each?", 8, "8."), ("n", "A girl has 235 FCFA and gets 150 FCFA. How much has she?", 385, "385.", "FCFA")],
  [("n", "Kofi buys 3 books at 450 FCFA each. How much does he pay?", 3 * 450, "1 350.", "FCFA"), ("n", "He pays with 2 000 FCFA. How much is his change?", 2000 - 3 * 450, "650.", "FCFA")],
  ("p", "A baker in Douala bakes 125 loaves each day for 4 days.", [("n", "How many loaves in 4 days?", 125 * 4, "500."), ("n", "She sells 380 loaves. How many are left?", 125 * 4 - 380, "120.")]),
  [("Class 3 maths problems: equal groups tell us to...", "multiply", ["add only", "subtract", "round"], "Multiply."),
   ("Class 3 maths problems: a total shared equally tells us to...", "divide", ["multiply", "add", "double"], "Divide."),
   ("5 bags with 20 nuts each. How many nuts?", "100", ["25", "15", "4"], "100."),
   ("150 − 75 equals...", "75", ["225", "85", "65"], "75."),
   ("At the end of a problem, we should...", "write the answer with its unit", ["write nothing", "add 10", "erase the working"], "Unit.")],
  [], prereq=["class3-maths-division-remainders", "class3-maths-multiply-by-1digit"])

# ===================================================== fractions
ch = p.chapter("fractions", "Fractions", R)
lesson(ch, "fractions-basic", "Fractions of a whole", ["Name halves, thirds, quarters and fifths.", "Read and write a fraction."],
  [("definition", "Fraction", "A **fraction** is a part of a whole. The whole is cut into **equal** parts. The bottom number (denominator) says how many equal parts. The top number (numerator) says how many parts we take. 3/4 means 3 of 4 equal parts."),
   ("retenir", "Names", "2 parts: halves. 3 parts: thirds. 4 parts: quarters. 5 parts: fifths. 1/2, 1/3, 1/4, 1/5 are **unit fractions**."),
   ("pieges", "Common mistakes", "- Parts must be equal.\n- 1/3 is bigger than 1/4.\n- The bottom number is not the number of parts we take.")],
  [("Example 1", "What fraction is coloured?", ["The bar has 5 equal parts.", "2 parts are coloured. So 2/5."], "2/5", frac_bar(5, 2)),
   ("Example 2", "A plantain is cut into 4 equal parts. Ada eats 3. What fraction did she eat?", ["The whole has 4 parts.", "She ate 3 of them: 3/4."], "3/4", frac_bar(4, 3))],
  (frac_bar(3, 1), "1/3 of the bar is coloured.", "A bar with 3 parts, one coloured."),
  [("m", "In 3/5 the bottom number is...", "5", ["3", "2", "8"], "5 equal parts."), ("m", "What fraction is shown?", "3/4", ["1/4", "4/3", "3/7"], "3 of 4 parts.", {"figure": frac_bar(4, 3)}), ("m", "Which is the bigger part: 1/2 or 1/4?", "1/2", ["1/4", "they are equal", "none"], "Fewer parts means bigger parts.")],
  [("n", "A cake is cut into 8 equal slices. You eat 3. How many slices are left?", 5, "8 − 3 = 5."), ("x", "Match the fraction with its name.", [("1/2", "a half"), ("1/3", "a third"), ("1/4", "a quarter"), ("1/5", "a fifth")], "Names of unit fractions.")],
  ("p", "Mama cuts a loaf into 6 equal pieces.", [("n", "She gives 2 pieces to Bih. What is the top number of the fraction she gave?", 2, "2/6."), ("n", "How many pieces are left?", 4, "6 − 2 = 4.")]),
  [("Class 3 maths fractions: the top number of a fraction is called the...", "numerator", ["denominator", "sum", "whole"], "Numerator."),
   ("Class 3 maths fractions: 2/3 means 2 of...", "3 equal parts", ["2 equal parts", "5 parts", "3 pieces always"], "3 equal parts."),
   ("A pizza is cut into 8 equal parts. Each part is...", "1/8", ["8/1", "1/4", "1/2"], "One eighth."),
   ("Which is the biggest: 1/2, 1/3, 1/5?", "1/2", ["1/3", "1/5", "all equal"], "Half."),
   ("The bottom number is called the...", "denominator", ["numerator", "product", "remainder"], "Denominator.")],
  ["Fractions with denominators up to 10 are assumed; check the syllabus limit."], prereq=["class3-maths-division-remainders"])

lesson(ch, "fractions-equal-compare", "Equal fractions and fractions of a number", ["Show that 1/2 = 2/4.", "Find a fraction of a number."],
  [("definition", "Equal fractions", "Different fractions can show the same amount. 1/2 = 2/4 = 3/6. Look at the bars: the coloured part is the same size."),
   ("methode", "Fraction of a number", "To find 1/4 of 20: divide by 4. 20 ÷ 4 = 5. To find 3/4 of 20: find 1/4 (5) and multiply by 3: 15."),
   ("pieges", "Common mistakes", "- 1/2 does not equal 1/4.\n- To find 3/5 of a number, divide by 5 first, then multiply by 3.\n- Same denominator: the bigger numerator is the bigger fraction.")],
  [("Example 1", "Find 1/5 of 30 mangoes.", ["Divide 30 by 5.", "30 ÷ 5 = 6."], str(30 // 5), None),
   ("Example 2", "Find 3/4 of 28.", ["1/4 of 28 is 28 ÷ 4 = 7.", "3/4 is 3 × 7 = 21."], str(28 // 4 * 3), None)],
  (shapes([RECT(10, 10, 160, 40, fill="white")] + [RECT(10, 10, 80, 40, fill="orange"), LINE(90, 10, 90, 50), T(90, 70, "1/2", 14, bold=True), RECT(10, 90, 160, 40, fill="white"), RECT(10, 90, 80, 40, fill="orange")] + [LINE(10 + 40 * i, 90, 10 + 40 * i, 130) for i in range(1, 4)] + [T(90, 150, "2/4", 14, bold=True)], 200, 160), "1/2 and 2/4 cover the same part.", "Two bars: one cut in two with one coloured half, one cut in four with two quarters coloured."),
  [("n", "1/3 of 12 = ?", 4, "12 ÷ 3."), ("n", "1/2 of 50 = ?", 25, "50 ÷ 2."), ("n", "3/5 of 20 = ?", 12, "20 ÷ 5 = 4; 4 × 3 = 12.")],
  [("m", "Which fraction equals 1/2?", "4/8", ["1/4", "2/3", "3/8"], "4/8 is half of 8."), ("n", "2/3 of 18 = ?", 12, "18 ÷ 3 = 6; × 2 = 12.")],
  ("p", "A farmer in Bafoussam has 40 chickens.", [("n", "1/4 of them are cocks. How many cocks?", 10, "40 ÷ 4."), ("n", "3/5 of them are white. How many are white?", 24, "40 ÷ 5 = 8; × 3 = 24.")]),
  [("Class 3 maths equal fractions: 1/2 is equal to...", "2/4", ["1/4", "2/3", "3/4"], "2/4."),
   ("Class 3 maths fraction of a number: 1/4 of 16 is...", "4", ["8", "12", "2"], "16 ÷ 4."),
   ("3/4 of 8 is...", "6", ["2", "4", "3"], "8 ÷ 4 = 2; 3 × 2 = 6."),
   ("Which fraction is the biggest: 3/8, 5/8, 1/8?", "5/8", ["3/8", "1/8", "equal"], "Same bottom: bigger top."),
   ("1/10 of 100 is...", "10", ["1", "100", "50"], "100 ÷ 10.")],
  [], prereq=["class3-maths-fractions-basic"])

# ===================================================== measures
ch = p.chapter("measures", "Measures", R)
lesson(ch, "length-km-m-cm", "Length: km, m, cm", ["Know km, m and cm.", "Change between them."],
  [("definition", "Units", "Short lengths: **centimetres** (cm). Longer: **metres** (m). Roads: **kilometres** (km). 1 m = 100 cm. 1 km = 1 000 m."),
   ("methode", "Changing", "m to cm: times 100. cm to m: divide by 100. km to m: times 1 000. 3 m = 300 cm. 2 km = 2 000 m."),
   ("pieges", "Common mistakes", "- Use the same unit before adding.\n- 150 cm is 1 m 50 cm.\n- A km is much longer than a m.")],
  [("Example 1", "Change 4 m to cm.", ["1 m is 100 cm.", "4 × 100 = 400."], "400 cm", None),
   ("Example 2", "Douala to Edéa is about 60 km. Change 2 km to m.", ["1 km is 1 000 m.", "2 × 1 000 = 2 000 m."], "2 000 m", None)],
  (ruler(10, 8), "A line of 8 cm.", "A ruler from 0 to 10 with an orange bar of length 8."),
  [("n", "5 m = how many cm?", 500, "5 × 100.", "cm"), ("n", "3 km = how many m?", 3000, "3 × 1 000.", "m"), ("n", "700 cm = how many m?", 7, "700 ÷ 100.", "m")],
  [("m", "Which is the longest?", "1 km", ["900 m", "50 m", "10 000 cm"], "1 km is 1 000 m. 10 000 cm is only 100 m. 900 m and 50 m are shorter."), ("n", "A rope is 2 m 30 cm long. How many cm?", 230, "200 + 30.", "cm")],
  ("p", "A boy runs 400 m to school and 400 m back.", [("n", "How far does he run in a day, in metres?", 800, "800.", "m"), ("n", "How far in 5 school days, in metres?", 4000, "4 000.", "m")]),
  [("Class 3 maths length: 1 km equals...", "1 000 m", ["100 m", "10 m", "10 000 m"], "1 000 m."),
   ("Class 3 maths length: 6 m equals...", "600 cm", ["60 cm", "6 000 cm", "16 cm"], "600 cm."),
   ("To change m to cm we...", "multiply by 100", ["divide by 100", "add 100", "do nothing"], "× 100."),
   ("The best unit for a long road is the...", "kilometre", ["centimetre", "gram", "litre"], "km."),
   ("250 cm is the same as...", "2 m 50 cm", ["25 m", "2 m 5 cm", "20 m"], "2 m 50 cm.")],
  [NOTE])

lesson(ch, "mass-capacity", "Mass and capacity: kg, g, l, ml", ["Know kg and g, litre and ml.", "Change between the units."],
  [("definition", "Mass", "**Mass** tells how heavy something is. Units: **grams** (g) and **kilograms** (kg). 1 kg = 1 000 g. A bag of rice can be 25 kg. A small pencil is a few grams."),
   ("retenir", "Capacity", "**Capacity** tells how much a container holds. Units: **litres** (l) and **millilitres** (ml). 1 l = 1 000 ml. A big bottle holds 1 or 2 litres."),
   ("pieges", "Common mistakes", "- Do not mix mass and capacity.\n- 1 kg is 1 000 g, not 100 g.\n- Use the same unit before adding.")],
  [("Example 1", "A bag has 2 kg of beans. How many grams?", ["1 kg is 1 000 g.", "2 × 1 000 = 2 000."], "2 000 g", None),
   ("Example 2", "A jug holds 3 litres. How many ml?", ["1 l is 1 000 ml.", "3 × 1 000 = 3 000."], "3 000 ml", None)],
  (cards(["1 kg = 1 000 g", "1 l = 1 000 ml", "1 m = 100 cm", "1 km = 1 000 m"], 2, 400, ch=40), "Four useful facts.", "Four boxes with unit conversions."),
  [("n", "4 kg = how many g?", 4000, "4 × 1 000.", "g"), ("n", "5 l = how many ml?", 5000, "5 × 1 000.", "ml"), ("m", "Which unit for a bucket of water?", "litres", ["grams", "cm", "FCFA"], "Capacity.")],
  [("n", "A bag of rice is 25 kg. How many kg in 4 bags?", 100, "25 × 4.", "kg"), ("n", "A bottle holds 500 ml. How many bottles fill 3 litres? (3 000 ÷ 500)", 6, "3 000 ÷ 500 = 6.")],
  ("p", "A mama in Bamenda buys 5 kg of tomatoes and 2 kg of onions.", [("n", "How many kg in all?", 7, "7.", "kg"), ("n", "How many grams is that?", 7000, "7 000.", "g")]),
  [("Class 3 maths mass: 1 kg equals...", "1 000 g", ["100 g", "10 g", "10 000 g"], "1 000 g."),
   ("Class 3 maths capacity: 1 litre equals...", "1 000 ml", ["100 ml", "10 ml", "10 l"], "1 000 ml."),
   ("Which unit measures how heavy a thing is?", "kilogram", ["litre", "metre", "hour"], "kg."),
   ("2 000 g is...", "2 kg", ["20 kg", "200 kg", "2 g"], "2 kg."),
   ("A jug holds 1 500 ml. That is...", "1 l 500 ml", ["15 l", "150 ml", "1 l 50 ml"], "1 l 500 ml.")],
  [NOTE], prereq=["class3-maths-length-km-m-cm"])

pr = rect_dim(5, 3, "5 cm", "3 cm", 30)
lesson(ch, "perimeter", "Perimeter", ["Say what perimeter is.", "Find the perimeter of squares and rectangles."],
  [("definition", "Perimeter", "The **perimeter** is the distance all the way round a shape. Add the lengths of all its sides."),
   ("formule", "Rectangle and square", "Rectangle: add the four sides. Two lengths and two widths: P = 2 × length + 2 × width. Square: 4 × side."),
   ("pieges", "Common mistakes", "- A rectangle has four sides to add, not two.\n- Use the same unit for all sides.\n- Perimeter is a length (cm), not an area.")],
  [("Example 1", "A rectangle is 5 cm long and 3 cm wide. Find its perimeter.", ["Add all sides: 5 + 3 + 5 + 3.", "= 16 cm."], "16 cm", pr),
   ("Example 2", "A square field has sides of 20 m. What is its perimeter?", ["4 × 20.", "= 80 m."], "80 m", None)],
  (pr, "Rectangle: 5 cm by 3 cm.", "A rectangle labelled 5 cm on top and 3 cm on the side."),
  [("n", "A square has sides of 6 cm. Its perimeter is...", 24, "4 × 6.", "cm"), ("n", "A rectangle is 8 cm by 2 cm. Perimeter?", 20, "8 + 2 + 8 + 2.", "cm"), ("n", "A triangle has sides 5 cm, 6 cm and 7 cm. Perimeter?", 18, "5 + 6 + 7.", "cm")],
  [("n", "A rectangular garden is 15 m long and 10 m wide. How much fence goes all round?", 50, "15 + 10 + 15 + 10.", "m"), ("n", "A square pen has a perimeter of 40 m. How long is one side?", 10, "40 ÷ 4.", "m")],
  ("p", "A school in Limbe has a rectangular football pitch 60 m long and 40 m wide.", [("n", "Find the perimeter.", 200, "60 + 40 + 60 + 40.", "m"), ("n", "Pupils run round it 3 times. How far do they run?", 600, "3 × 200.", "m")]),
  [("Class 3 maths perimeter: the perimeter is the distance...", "all round a shape", ["inside a shape", "across a shape", "up a shape"], "Round."),
   ("Class 3 maths perimeter: a square with side 5 cm has perimeter...", "20 cm", ["10 cm", "25 cm", "5 cm"], "4 × 5."),
   ("A rectangle 7 cm by 3 cm has perimeter...", "20 cm", ["10 cm", "21 cm", "14 cm"], "2 × 7 + 2 × 3."),
   ("To find the perimeter we...", "add all the sides", ["multiply two sides only", "divide", "count corners"], "Add."),
   ("Perimeter is measured in...", "cm or m", ["litres", "kg", "FCFA"], "Length.")],
  [NOTE], prereq=["class3-maths-length-km-m-cm"])

lesson(ch, "time-minutes", "Time: minutes, hours and the calendar", ["Read the time to the minute.", "Work out how long something takes."],
  [("definition", "Units of time", "60 seconds = 1 minute. 60 minutes = 1 hour. 24 hours = 1 day. 7 days = 1 week. 12 months = 1 year. The a.m. is from midnight to noon. The p.m. is from noon to midnight."),
   ("methode", "How long?", "To find how long: count on from the start time to the end time. From 8:15 to 9:45: 45 minutes to 9:00, then 45 more. Total 1 hour 30 minutes."),
   ("pieges", "Common mistakes", "- An hour has 60 minutes, not 100.\n- 1 hour 30 minutes is 90 minutes.\n- Check a.m. and p.m.")],
  [("Example 1", "School starts at 7:30 a.m. and ends at 1:30 p.m. How many hours?", ["From 7:30 to 12:30 is 5 hours.", "From 12:30 to 1:30 is 1 more hour. Total 6 hours."], "6 hours", clockface(7, 30)),
   ("Example 2", "A film lasts 90 minutes. How many hours and minutes?", ["60 minutes is 1 hour.", "90 − 60 = 30. So 1 hour 30 minutes."], "1 hour 30 minutes", None)],
  (clockface(10, 10), "10:10 on the clock.", "A clock face with the short hand just after 10 and the long hand on 2."),
  [("n", "How many minutes in 2 hours?", 120, "2 × 60.", "minutes"), ("n", "How many days in 3 weeks?", 21, "3 × 7.", "days"), ("m", "What time is shown?", "6:20", ["4:30", "6:04", "4:06"], "Short hand on 6, long hand on 4 (20 minutes).", {"figure": clockface(6, 20)})],
  [("n", "A lesson starts at 9:15 and ends at 10:00. How many minutes?", 45, "45.", "minutes"), ("n", "A bus leaves at 8:40 and arrives at 11:10. How many minutes is the journey?", 150, "2 hours 30 minutes = 150.", "minutes")],
  ("p", "A bus leaves Bamenda at 6:30 a.m. and arrives in Douala at 11:00 a.m.", [("n", "How many hours and minutes is that? Give the answer in minutes.", 270, "4 hours 30 minutes = 270.", "minutes"), ("n", "The bus waits for 30 minutes on the way. How many minutes of driving?", 240, "270 − 30 = 240.", "minutes")]),
  [("Class 3 maths time: how many minutes are in 1 hour?", "60", ["100", "30", "24"], "60."),
   ("Class 3 maths time: how many hours are in a day?", "24", ["12", "60", "7"], "24."),
   ("1 hour 15 minutes is...", "75 minutes", ["115 minutes", "100 minutes", "25 minutes"], "75."),
   ("From 4:00 p.m. to 6:30 p.m. is...", "2 hours 30 minutes", ["2 hours", "3 hours", "1 hour 30 minutes"], "2 h 30 min."),
   ("There are how many days in two weeks?", "14", ["7", "12", "24"], "14.")],
  [NOTE], prereq=["class3-maths-length-km-m-cm"])

lesson(ch, "money-bills", "Money: shopping and bills", ["Add and subtract FCFA amounts.", "Work out a shopping bill and change."],
  [("definition", "Money", "In Cameroon we use **FCFA**. A **bill** shows what each item costs and the **total**. **Change** = money paid − total cost."),
   ("methode", "Steps", "1. Multiply the price by the quantity. 2. Add all costs. 3. Subtract from the money paid to find the change."),
   ("pieges", "Common mistakes", "- Do not forget to multiply by how many.\n- Write FCFA in the answer.\n- Check that the change is less than what was paid.")],
  [("Example 1", "3 pens at 150 FCFA each. Total?", ["3 × 150.", "= 450."], "450 FCFA", None),
   ("Example 2", "Bih buys rice for 1 200 FCFA and oil for 800 FCFA. She pays 2 500 FCFA. Change?", ["Total: 1 200 + 800 = 2 000.", "Change: 2 500 − 2 000 = 500."], "500 FCFA", None)],
  (table_fig([["Item", "Price", "How many", "Cost"], ["Pen", "150", "3", "450"], ["Book", "400", "2", "800"]], 400, 100, 32), "A small shopping bill.", "A table with items, prices, quantities and cost."),
  [("n", "4 mangoes at 75 FCFA each cost...", 300, "4 × 75.", "FCFA"), ("n", "Bread costs 250 FCFA and milk 400 FCFA. Total?", 650, "250 + 400.", "FCFA"), ("n", "You pay 1 000 FCFA for a 650 FCFA item. Change?", 350, "1 000 − 650.", "FCFA")],
  [("n", "5 notebooks at 175 FCFA each. Total?", 875, "5 × 175.", "FCFA"), ("n", "A bag costs 3 500 FCFA. A shirt costs 2 250 FCFA. How much more is the bag?", 1250, "3 500 − 2 250.", "FCFA")],
  ("p", "Ngum buys 2 kg of fish at 1 500 FCFA per kg and 3 plantain bunches at 500 FCFA each. He pays with 5 000 FCFA.", [("n", "Cost of the fish?", 3000, "2 × 1 500.", "FCFA"), ("n", "Total cost of fish and plantains?", 3000 + 1500, "3 000 + 1 500.", "FCFA"), ("n", "His change?", 5000 - 4500, "5 000 − 4 500.", "FCFA")]),
  [("Class 3 maths money: 6 sweets at 25 FCFA each cost...", "150 FCFA", ["31 FCFA", "125 FCFA", "250 FCFA"], "6 × 25."),
   ("Class 3 maths money: change is found by...", "money paid minus cost", ["cost plus paid", "cost times paid", "adding the notes"], "Subtract."),
   ("A pen costs 200 FCFA and a ruler 150 FCFA. Total:", "350 FCFA", ["50 FCFA", "300 FCFA", "3 500 FCFA"], "350."),
   ("You pay 500 FCFA for a 320 FCFA item. Change?", "180 FCFA", ["820 FCFA", "280 FCFA", "220 FCFA"], "180."),
   ("A bill shows the...", "items and the total", ["colour of the shop", "name of the bus", "weather"], "Items and total.")],
  ["Prices are invented."], prereq=["class3-maths-add-sub-3digit"])

# ===================================================== data
ch = p.chapter("data", "Simple data", R)
fruit = [("Mango", 6), ("Orange", 4), ("Banana", 5)]
lesson(ch, "pictographs", "Pictographs and tally charts", ["Read a pictograph.", "Make a tally chart."],
  [("definition", "Pictograph", "A **pictograph** uses pictures or symbols to show numbers. A **key** tells what each symbol means. Here each circle stands for 2 pupils."),
   ("retenir", "Tally", "A **tally chart** counts with marks. We write one mark for each thing. We cross four marks with a fifth. 5 = a bundle of five."),
   ("pieges", "Common mistakes", "- Read the key. One symbol may stand for more than one.\n- Count each symbol.\n- Half a symbol is half the number.")],
  [("Example 1", "Each circle is 2 pupils. Mango has 6 circles. How many pupils like mango?", ["Count the circles: 6.", "6 × 2 = 12 pupils."], "12 pupils", picto([("Mango", 6), ("Orange", 4), ("Banana", 5)], key="= 2 pupils")),
   ("Example 2", "How many pupils like orange?", ["Orange has 4 circles.", "4 × 2 = 8 pupils."], "8 pupils", None)],
  (picto([("Mango", 6), ("Orange", 4), ("Banana", 5)], key="= 2 pupils"), "Favourite fruit of Class 3 pupils. Each circle is 2 pupils.", "A pictograph with rows for mango (6 circles), orange (4 circles) and banana (5 circles)."),
  [("n", "In the pictograph, how many pupils like banana?", 10, "5 circles × 2 = 10.", None, {"figure": picto([("Mango", 6), ("Orange", 4), ("Banana", 5)], key="= 2 pupils")}), ("m", "Which fruit do most pupils like?", "Mango", ["Orange", "Banana", "They are equal"], "6 circles is the most.", {"figure": picto([("Mango", 6), ("Orange", 4), ("Banana", 5)], key="= 2 pupils")}), ("n", "How many pupils in all? (12 + 8 + 10)", 30, "30.")],
  [("n", "How many more pupils like mango than orange?", 4, "12 − 8 = 4."), ("t", "A key tells us what each symbol means.", True, "True.")],
  ("p", "A teacher draws a pictograph of the pets at home. Each circle means 3 pets. Dogs: 4 circles. Cats: 3 circles. Hens: 5 circles.", [("n", "How many dogs?", 12, "4 × 3."), ("n", "How many cats?", 9, "3 × 3."), ("n", "How many more hens than cats?", 6, "15 − 9.")]),
  [("Class 3 maths pictographs: the key tells us...", "what each symbol means", ["the colour", "the day", "the title"], "Key."),
   ("Class 3 maths pictographs: if one circle means 5 and there are 3 circles, the number is...", "15", ["8", "5", "3"], "3 × 5."),
   ("A tally mark group of 5 is drawn as...", "four marks crossed by one", ["five circles", "a number five", "one tall bar"], "Bundle of 5."),
   ("A pictograph uses...", "pictures or symbols", ["only words", "only coins", "only a clock"], "Symbols."),
   ("Half a symbol that stands for 4 means...", "2", ["4", "8", "1"], "Half of 4.")],
  ["The `circle` symbol is a stand-in for a picture of a fruit/person."])

bd = [("Mon", 3), ("Tue", 5), ("Wed", 4), ("Thu", 7), ("Fri", 2)]
lesson(ch, "bar-charts", "Reading bar charts", ["Read values from a bar chart.", "Compare bars."],
  [("definition", "Bar chart", "A **bar chart** uses bars to show numbers. A taller bar means a bigger number. The labels under the bars tell what each bar is."),
   ("methode", "Read it", "1. Read the title. 2. Read the labels. 3. Look at the top of the bar and read across to the numbers. 4. Compare the bars."),
   ("pieges", "Common mistakes", "- Read the top of the bar, not the middle.\n- The tallest bar is the biggest number.\n- Look at the unit.")],
  [("Example 1", "The chart shows pupils absent each day. How many were absent on Thursday?", ["Find Thursday and look at the top of its bar.", "The bar is at 7."], "7 pupils", bars(bd + [], "pupils", 400, 240)),
   ("Example 2", "Which day had the fewest absent pupils?", ["Look for the shortest bar.", "Friday is the shortest."], "Friday", None)],
  (bars(bd, "pupils", 400, 240), "Pupils absent each day.", "A bar chart of absent pupils from Monday to Friday: 3, 5, 4, 7, 2."),
  [("n", "How many pupils were absent on Tuesday?", 5, "Read the Tuesday bar.", None, {"figure": bars(bd, "pupils")}), ("m", "Which day had the most absent pupils?", "Thursday", ["Monday", "Friday", "Wednesday"], "The tallest bar.", {"figure": bars(bd, "pupils")}), ("n", "How many pupils were absent over the whole week?", sum(v for _, v in bd), "3 + 5 + 4 + 7 + 2 = 21.")],
  [("n", "How many more were absent on Thursday than on Friday?", 5, "7 − 2.", None, {"figure": bars(bd, "pupils")}), ("t", "A taller bar shows a bigger number.", True, "True.")],
  ("p", "A Class 3 teacher counts the books each group read: Group A 12, Group B 8, Group C 15.", [("n", "How many books in all?", 35, "12 + 8 + 15."), ("n", "How many more did Group C read than Group B?", 7, "15 − 8.")]),
  [("Class 3 maths bar charts: the tallest bar shows the...", "biggest number", ["smallest number", "title", "day"], "Biggest."),
   ("Class 3 maths bar charts: we read a bar's number at its...", "top", ["bottom", "label colour", "side"], "Top."),
   ("To compare two bars we look at which is...", "taller", ["wider", "darker", "left"], "Taller."),
   ("Bars of 4 and 7: the difference is...", "3", ["11", "28", "4"], "7 − 4."),
   ("The labels under the bars tell us...", "what each bar shows", ["how tall the bar is", "the price", "nothing"], "Labels.")],
  ["Check that the bars figure has headroom above the tallest bar (7)."], prereq=["class3-maths-pictographs"])

p.write()
