import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from p45_kit import *

TAG["v"] = "Class 4 Science"
p = Pack("class4-science", "Elementary Science and Technology — Class 4", level="Class 4", subject="sciences", cursus="primary",
         description="Class 4 Elementary Science and Technology for the English-speaking primary subsystem: living things, plants, animals, the human body, food and health, soil, water and weather, matter, light, heat and sound, magnets and simple electricity. Draft lessons with worked examples, exercises and self-checks.",
         programRef="MINEDUB primary school curriculum (English-speaking subsystem), Level II (Class 4) — Elementary Science and Technology; to be checked against the official syllabus",
         wanted="elementary-science")
REF = p.programRef
HEALTH = "Health and hygiene advice is conservative and general; it must be reviewed by a health worker or a teacher before release."

# ===================================================== 1. living things
ch = p.chapter("living", "Living things", REF)

fig = table([["Living", "Non-living"], ["goat", "stone"], ["maize plant", "water"], ["child", "chair"], ["mushroom", "plastic bottle"]], [150, 150], rh=30, size=14)
build(ch, "living-things", "Living and non-living things", 25,
      ["Name the signs of life.", "Sort things into living, once living and non-living.", "Give examples from home and school."],
      [("key", "definition", "Signs of life", "A **living thing** does these things: it **feeds** (takes in food), **breathes**, **grows**, **moves** (animals move around, plants move slowly towards light), **reproduces** (makes young ones or seeds), **gets rid of waste** and **senses** what is around it. A goat, a maize plant and a child are living."),
       ("fig", fig, "Examples of living and non-living things.", "A table with two columns: living (goat, maize plant, child, mushroom) and non-living (stone, water, chair, plastic bottle)."),
       ("key", "retenir", "Non-living and once-living", "**Non-living** things never lived: stone, water, plastic, metal, air. Some things were **once living**: a dry leaf, a wooden stool (from a tree), leather shoes (from an animal). They no longer feed, breathe or grow."),
       ("key", "pieges", "Common mistakes", "- Saying that a plant is not living because it does not walk.\n- Thinking that fire or the sun is living because it moves or gives light.\n- Putting a wooden table in the living group: it is made from a tree that was once living.")],
      [("ex", "Example 1", "Is a mango tree living? Give two reasons.", ["A mango tree grows from a seed and gets taller each year.", "It also takes in water and makes fruit with seeds (it reproduces)."], "Yes: it grows and it makes seeds.", None),
       ("ex", "Example 2", "Sort: a hen, a stone, a dry leaf, a goat.", ["Hen and goat feed, breathe, grow and move: living.", "Stone never lived: non-living. A dry leaf came from a plant: once living."], "living: hen, goat; non-living: stone; once living: dry leaf.", None)],
      [M("application", "Which of these is living?", "a mushroom", ["a stone", "a spoon", "a radio"], "A mushroom grows and reproduces."),
       M("application", "Which of these is non-living?", "a plastic bottle", ["a frog", "a banana plant", "an ant"], "It never lived."),
       M("application", "What do living things need to take in?", "food", ["batteries", "paint", "plastic"], "They feed."),
       TF("approfondissement", "Plants are not living things because they do not move from place to place.", False, "Plants grow, feed, reproduce and respond to light."),
       MA("approfondissement", "Match each item with its group.", [("a goat", "living"), ("a stone", "non-living"), ("a dry leaf", "once living")], "Think of where it came from."),
       P("Neba collects things for the school science corner: a chicken egg that will hatch, a stone, a bean seed, a plastic cup and a dry stick.",
         [PM("Which of these is certainly non-living?", "a stone", ["the bean seed", "the egg that will hatch", "the dry stick"], "A stone never lived."),
          PM("Which is once living?", "the dry stick", ["the stone", "the plastic cup", "the air"], "It came from a tree."),
          PN("How many items on the list are living or have life in them (egg and seed)?", 2, "The egg that will hatch and the bean seed have life inside.", points=2)])],
      [("Which is a sign of life?", "growing", ["rusting", "melting", "breaking"], "Only living things grow."),
       ("Which of these is non-living?", "water", ["a tree", "a bird", "a worm"], "Water is not alive."),
       ("A wooden table is...", "once living", ["living", "alive now", "a plant"], "It is made of wood from a tree."),
       ("Living things reproduce, which means they...", "make young ones or seeds", ["grow bigger only", "get rid of waste only", "sleep"], "Reproduce = have offspring."),
       ("Which does a plant respond to?", "light", ["radio", "music only", "paint"], "Plants grow towards light.")],
      ["Characteristics are simplified (no MRS GREN terms)."])

# ===================================================== 2. plants and animals
ch = p.chapter("plants-animals", "Plants and animals", REF)

fig = shapes([RECT(30, 140, 340, 80, fill="lightorange"), LINE(200, 140, 200, 55, color="green", width=6),
              POLY([200, 105, 245, 80, 250, 105], fill="green"), POLY([200, 105, 155, 80, 150, 105], fill="green"), CIRCLE(200, 45, 13, fill="yellow"),
              LINE(200, 140, 165, 195, color="brown", width=3), LINE(200, 140, 200, 205, color="brown", width=3), LINE(200, 140, 235, 195, color="brown", width=3),
              T(225, 35, "flower", 13, anchor="start", bold=True), T(262, 90, "leaf", 13, anchor="start", bold=True), T(214, 125, "stem", 13, anchor="start", bold=True),
              T(250, 190, "roots", 13, anchor="start", bold=True), T(40, 175, "soil", 13, anchor="start")], 400, 230)
build(ch, "plants", "Parts of a plant and what plants need", 30,
      ["Name the parts of a flowering plant and say what each does.", "Say what plants need to grow.", "Describe how a seed germinates."],
      [("key", "definition", "Parts and jobs", "**Roots** hold the plant in the soil and take in water. The **stem** holds the plant up and carries water to the leaves. **Leaves** make food for the plant using sunlight (this is **photosynthesis**). The **flower** makes seeds, and the **fruit** holds the seeds. A **seed** can grow into a new plant."),
       ("fig", fig, "The parts of a flowering plant.", "A plant in the soil with roots below, a stem, two leaves and a flower on top, each labelled."),
       ("key", "retenir", "What plants need", "Plants need **light**, **water**, **air** (carbon dioxide), **warmth** and **soil** (for minerals and support). A seed needs **water, air and warmth** to start to grow (**germinate**); it does not need light at first. First the **root** comes out, then the **shoot** grows up towards the light."),
       ("key", "pieges", "Common mistakes", "- Thinking that plants eat soil: they take water and minerals from the soil and make their own food in the leaves.\n- Saying that leaves take in water: the **roots** take in water.\n- Thinking that a seed needs sunlight to germinate.")],
      [("ex", "Example 1", "Which part of the plant takes in water from the soil, and which part makes food?", ["Water enters through the roots.", "The leaves make food using sunlight."], "Roots take in water; leaves make food.", fig),
       ("ex", "Example 2", "Bih puts a bean seed in damp cotton wool in a dark cupboard. It germinates. What does this show?", ["The seed had water, air and warmth, but no light.", "So a seed does not need light to germinate."], "A seed does not need light to germinate.", None)],
      [M("application", "Which part of a plant holds it in the soil?", "roots", ["flower", "leaf", "fruit"], "Roots anchor the plant."),
       M("application", "Where does a plant make its food?", "in the leaves", ["in the roots", "in the soil", "in the flower only"], "Leaves make food using sunlight."),
       M("application", "Which is NOT needed by a germinating seed?", "light", ["water", "warmth", "air"], "Seeds germinate in the dark under the soil."),
       TF("approfondissement", "A plant kept in a dark cupboard for weeks will grow healthy green leaves.", False, "Plants need light to make food."),
       MA("approfondissement", "Match each plant part with its job.", [("roots", "take in water"), ("stem", "carries water up"), ("leaf", "makes food"), ("flower", "makes seeds")], "Each part has a job."),
       P("Ako plants 3 bean seeds in three cups. Cup A gets water and light. Cup B gets light but no water. Cup C gets water but is kept in a dark box. After two weeks A is green and tall, B has not grown, C is tall but pale.",
         [PM("Why did cup B not grow?", "it had no water", ["it had no soil", "it had no flowers", "it was too bright"], "Seeds need water to germinate."),
          PM("Why is the plant in cup C pale?", "it had no light", ["it had too much water", "it had no roots", "it had no soil"], "Leaves need light to be green and healthy."),
          PM("Which cup shows what plants need to grow well?", "A", ["B", "C", "B and C"], "Cup A has both water and light.", points=2)])],
      [("Which part of the plant makes seeds?", "the flower", ["the root", "the stem", "the soil"], "Flowers make seeds."),
       ("The stem of a plant...", "holds it up and carries water", ["makes seeds", "takes in sunlight only", "is under the soil"], "Support and transport."),
       ("A germinating seed needs...", "water, air and warmth", ["light only", "stones", "plastic"], "Three things."),
       ("The first part that comes out of a seed is the...", "root", ["flower", "leaf", "fruit"], "Then the shoot."),
       ("Leaves make food using...", "sunlight", ["moonlight only", "soil", "sand"], "Photosynthesis.")],
      ["Photosynthesis is named but not explained; level appropriate for Class 4 to be checked."])

fig = table([["Group", "Body cover", "Examples"], ["mammals", "hair or fur", "goat, bat, human"], ["birds", "feathers", "hen, parrot"], ["reptiles", "dry scales", "lizard, snake"], ["amphibians", "moist skin", "frog"], ["fish", "wet scales", "tilapia"], ["insects", "hard cover", "ant, bee"]], [100, 110, 140], rh=26, size=13)
build(ch, "animals", "Groups of animals", 30,
      ["Group animals as mammals, birds, reptiles, amphibians, fish and insects.", "Say what herbivores, carnivores and omnivores eat.", "Tell where some animals live (habitats)."],
      [("key", "definition", "Animal groups", "**Mammals** have hair or fur and feed their babies with **milk** (goat, cow, bat, human). **Birds** have feathers, wings and lay eggs (hen, parrot). **Reptiles** have dry scaly skin and lay eggs (lizard, snake, crocodile). **Amphibians** have moist skin and begin life in water (frog). **Fish** live in water, with gills, fins and scales. **Insects** have **6 legs** and 3 body parts (ant, bee, housefly)."),
       ("fig", fig, "Groups of animals.", "A table of six animal groups with their body cover and examples: mammals, birds, reptiles, amphibians, fish and insects."),
       ("key", "retenir", "What animals eat and where they live", "**Herbivores** eat plants (goat, cow, elephant). **Carnivores** eat other animals (lion, snake, eagle). **Omnivores** eat both (human, pig, chicken). A **habitat** is the place where an animal lives: forest, river, savanna, house. A spider has 8 legs, so it is **not** an insect."),
       ("key", "pieges", "Common mistakes", "- Calling a bat a bird: it has fur and feeds its young with milk, so it is a **mammal**.\n- Saying that a spider is an insect (6 legs; spiders have 8).\n- Calling a whale or a dolphin a fish: they are mammals.\n- Thinking that all snakes are dangerous: many are harmless, but keep away from all wild snakes.")],
      [("ex", "Example 1", "A hen has feathers and lays eggs. Which group is it?", ["Feathers and eggs are the signs of birds.", "A hen is a bird."], "Bird", None),
       ("ex", "Example 2", "Is a goat a herbivore, a carnivore or an omnivore?", ["A goat eats grass and leaves.", "It eats only plants: it is a herbivore."], "Herbivore", None)],
      [M("application", "Which animal is a mammal?", "a goat", ["a hen", "a lizard", "a tilapia"], "A goat has hair and gives milk."),
       M("application", "How many legs has an insect?", "6", ["4", "8", "10"], "Insects have six legs."),
       M("application", "Which animal eats only plants?", "a cow", ["a lion", "an eagle", "a crocodile"], "A cow is a herbivore."),
       N("approfondissement", "A group of children counts 3 ants and 2 spiders. How many legs do the 3 ants have altogether?", 18, "3 × 6 = 18 legs (spiders are not insects).", unit="legs"),
       TF("approfondissement", "A bat is a mammal.", True, "It has fur and feeds its babies milk."),
       P("An animal has dry scaly skin, lays eggs on land and has four legs and a long tail. It lives near the river.",
         [PM("Which group does this animal belong to?", "reptiles", ["mammals", "birds", "insects"], "Dry scaly skin and eggs on land."),
          PM("Which of these could it be?", "a lizard", ["a bat", "a hen", "a frog"], "A lizard is a reptile."),
          PM("What do we call the place where it lives?", "its habitat", ["its food", "its family", "its skin"], "Habitat = home of an animal.", points=2)])],
      [("A frog is a...", "amphibian", ["reptile", "bird", "insect"], "It begins life in water."),
       ("An animal that eats both plants and animals is an...", "omnivore", ["herbivore", "carnivore", "insect"], "For example a human."),
       ("A bat is a...", "mammal", ["bird", "insect", "reptile"], "It feeds its young with milk."),
       ("The place where an animal lives is its...", "habitat", ["family", "skin", "meal"], "For example a river or a forest."),
       ("Which animal lays eggs and has feathers?", "a parrot", ["a goat", "a snake", "a cow"], "Birds have feathers.")],
      ["Classification simplified; check how the textbook handles amphibians and vertebrates/invertebrates."])

# ===================================================== 3. human body and health
ch = p.chapter("body-health", "The human body and health", REF)

fig = table([["Sense", "Organ", "What it does"], ["sight", "eyes", "see colours and shapes"], ["hearing", "ears", "hear sounds"], ["smell", "nose", "smell food and smoke"], ["taste", "tongue", "taste sweet, salty, sour, bitter"], ["touch", "skin", "feel hot, cold, soft"]], [80, 90, 190], rh=28, size=13)
build(ch, "senses-skeleton", "The five senses and the skeleton", 30,
      ["Name the five senses and the organ for each.", "Say what the skeleton does.", "Give simple ways to protect eyes, ears and bones."],
      [("key", "definition", "The five senses", "We have five senses: **sight** (eyes), **hearing** (ears), **smell** (nose), **taste** (tongue) and **touch** (skin). They tell us about the world around us and warn us of danger: we smell smoke, hear a horn and feel a hot pot."),
       ("fig", fig, "The five senses.", "A table with five rows: sight and eyes, hearing and ears, smell and nose, taste and tongue, touch and skin, with what each does."),
       ("key", "definition", "The skeleton", "The **skeleton** is the frame of **bones** inside the body. It **supports** the body, **protects** soft parts (the skull protects the brain; the ribs protect the heart and lungs) and, with **muscles**, helps us **move**. Bones meet at **joints** such as the knee and elbow. An adult has about 206 bones."),
       ("key", "pieges", "Common mistakes", "- Thinking that muscles are the same as bones: muscles pull on bones to make them move.\n- Looking at the sun or using sharp objects near the eyes.\n- Using sticks or pins in the ears.\n- Forgetting that skin is also a sense organ.")],
      [("ex", "Example 1", "Which sense do you use to know that tea is too hot?", ["The skin of the lips and tongue feel the heat.", "It is the sense of touch."], "Touch", None),
       ("ex", "Example 2", "Which part of the skeleton protects the brain?", ["The brain is inside the head.", "The skull protects it."], "The skull", None)],
      [M("application", "Which organ do we use for hearing?", "ears", ["eyes", "nose", "tongue"], "Ears hear."),
       M("application", "Which sense do we use to tell that a mango is sweet?", "taste", ["sight only", "hearing", "touch only"], "The tongue tastes."),
       M("application", "What protects the heart and lungs?", "the ribs", ["the skull", "the skin", "the nails"], "The rib cage."),
       N("approfondissement", "How many senses do human beings have?", 5, "Sight, hearing, smell, taste, touch."),
       TF("approfondissement", "Muscles help bones to move.", True, "Muscles pull on bones."),
       P("Ada hears a bell, smells smoke from a cooking fire and feels the warmth of the sun on her arm. She looks at a red flower and tastes a ripe mango.",
         [PM("Which sense did Ada use for the smoke?", "smell", ["sight", "hearing", "touch"], "The nose smells."),
          PM("Which sense did Ada use for the bell?", "hearing", ["sight", "taste", "smell"], "The ears hear."),
          PN("How many different senses did Ada use?", 5, "Hearing, smell, touch, sight, taste.", points=2)])],
      [("Which organ helps us to see?", "eyes", ["ears", "nose", "skin"], "Sight."),
       ("The skeleton does NOT...", "make food for the body", ["protect organs", "support the body", "help us move"], "The digestive system handles food."),
       ("The skull protects the...", "brain", ["heart", "lungs", "stomach"], "It is a hard case."),
       ("Which sense organ is the largest?", "the skin", ["the eye", "the ear", "the nose"], "It covers the whole body."),
       ("Bones meet at...", "joints", ["muscles", "nails", "teeth"], "For example the elbow.")],
      ["206 bones for an adult is a standard figure; health advice (protect eyes and ears) to be reviewed by a health worker."])

fig = table([["Food group", "Jobs", "Examples"], ["energy foods", "give energy", "cassava, yam, rice, plantain"], ["body-building", "help us grow", "beans, fish, eggs, meat"], ["protective", "keep us healthy", "fruit, eru, okra, tomato"], ["fats and oils", "give energy", "palm oil, groundnut oil"]], [100, 100, 170], rh=30, size=12)
fig2 = flow(["mouth", "food pipe", "stomach", "small intestine", "large intestine"])
build(ch, "food-digestion", "Food groups and digestion", 35,
      ["Name the food groups and give local examples.", "Say what a balanced diet is.", "Describe the journey of food through the body."],
      [("key", "definition", "Food groups", "We eat to get **energy**, to **grow** and to stay **healthy**. **Energy foods**: cassava, yam, rice, maize, plantain. **Body-building foods** (proteins): beans, groundnuts, fish, eggs, meat. **Protective foods** (vitamins and minerals): fruits and vegetables such as eru, okra, orange and pawpaw. We also need a little **fat or oil** and plenty of **safe water**."),
       ("fig", fig, "Food groups with examples from Cameroon.", "A table of four food groups, their jobs and local examples: energy foods, body-building foods, protective foods, fats and oils."),
       ("key", "retenir", "Balanced diet and digestion", "A **balanced diet** has a little of each food group in the right amounts. **Digestion** breaks food into tiny parts that the blood can carry. Food goes from the **mouth** (teeth chew it) to the **food pipe**, **stomach**, **small intestine** (food is absorbed) and **large intestine**; waste leaves the body."),
       ("fig", fig2, "The path of food through the body.", "Five boxes joined by arrows from top to bottom: mouth, food pipe, stomach, small intestine, large intestine."),
       ("key", "pieges", "Common mistakes", "- Eating only one kind of food, such as only starch.\n- Thinking that sweets and fizzy drinks are healthy because they give energy: too much sugar harms teeth.\n- Swallowing food without chewing.\n- Forgetting to wash fruit and vegetables.")],
      [("ex", "Example 1", "Put the foods in groups: rice, beans, orange, groundnut oil.", ["Rice gives energy; beans build the body; orange protects; groundnut oil is a fat/oil.", "Match each food to its job."], "rice: energy; beans: body-building; orange: protective; groundnut oil: fats and oils.", fig),
       ("ex", "Example 2", "Where does digestion begin?", ["Food is first chewed by the teeth and mixed with saliva.", "Digestion begins in the mouth."], "In the mouth", None)],
      [M("application", "Which food gives mostly energy?", "yam", ["orange", "egg", "okra"], "Starchy foods give energy."),
       M("application", "Which food helps the body to grow?", "beans", ["cassava", "palm oil", "salt"], "Beans are rich in protein."),
       M("application", "Where does food go after the mouth?", "the food pipe", ["the large intestine", "the lungs", "the heart"], "Mouth, food pipe, stomach."),
       TF("approfondissement", "A balanced diet means eating a little of each food group.", True, "A variety of foods keeps us healthy."),
       MA("approfondissement", "Match each food to its group.", [("fish", "body-building"), ("plantain", "energy"), ("pawpaw", "protective"), ("palm oil", "fats and oils")], "Local examples."),
       P("Mama Ako's family eats a lot of cassava and plantain every day but very little fruit or beans.",
         [PM("Which groups do cassava and plantain belong to?", "energy foods", ["body-building foods", "protective foods", "fats only"], "They are starchy."),
          PM("Which foods should the family add to be healthier?", "beans and fruit", ["more sweets", "more fried snacks", "more cassava"], "Protein and vitamins."),
          PM("Which organ does food reach after the stomach?", "the small intestine", ["the mouth", "the food pipe", "the heart"], "Then the large intestine.", points=2)])],
      [("A balanced diet has...", "all the food groups", ["only sweets", "only meat", "only cassava"], "A little of each."),
       ("Digestion begins in the...", "mouth", ["stomach", "heart", "skin"], "Teeth chew food."),
       ("Oranges and eru are rich in...", "vitamins", ["only oil", "plastic", "stones"], "Protective foods."),
       ("Which is a body-building food?", "fish", ["rice", "oil", "sugar"], "Fish gives protein."),
       ("After the stomach, food goes to the...", "small intestine", ["mouth", "lungs", "brain"], "Digestion continues there.")],
      [HEALTH, "Names of food groups follow a simple 3-group model; some textbooks add fibre and water."])

fig = boxes(["Wash hands with soap and water", "Drink safe water, eat clean food", "Sleep under a mosquito net", "Keep the house and yard clean"], size=14)
build(ch, "health-hygiene", "Health and hygiene", 30,
      ["Name good habits for personal hygiene.", "Explain how to prevent malaria and tummy infections.", "Say when to ask a health worker for help."],
      [("key", "definition", "Personal hygiene", "Hygiene means keeping clean to stay healthy. **Wash your hands with soap and water** before eating and after using the toilet. **Bathe** often, **brush your teeth** twice a day, keep **nails short** and wear clean clothes. Always **drink safe water** (boiled, filtered or treated) and **wash fruit and vegetables**."),
       ("fig", fig, "Four healthy habits.", "Four boxes with healthy habits: wash hands with soap and water; drink safe water and eat clean food; sleep under a mosquito net; keep the house and yard clean."),
       ("key", "retenir", "Preventing malaria", "Malaria is spread by the **bite of a mosquito**. We can prevent it by **sleeping under a mosquito net**, **clearing stagnant water** and bushes near the house (where mosquitoes lay eggs) and covering water containers. If someone has fever, tell an adult and go to the **health centre**. Do not take medicine without a health worker's advice."),
       ("key", "pieges", "Common mistakes", "- Thinking that malaria comes from the sun, cold or eating mangoes: it comes from mosquito bites.\n- Washing hands only with water and no soap.\n- Drinking water from the stream or a pond without making it safe.\n- Treating fever by yourself instead of going to the health centre.")],
      [("ex", "Example 1", "Why must we wash our hands before eating?", ["Our hands pick up germs from things we touch.", "Washing with soap removes germs, so we do not swallow them with our food."], "To remove germs and avoid tummy infections.", None),
       ("ex", "Example 2", "A puddle has been in the yard for a week. Why is it a danger?", ["Mosquitoes lay their eggs in still water.", "More mosquitoes mean more risk of malaria: empty or drain the puddle."], "Mosquitoes breed in it, and they spread malaria.", None)],
      [M("application", "Malaria is spread by...", "mosquito bites", ["cold weather", "the sun", "sharing a pen"], "Mosquitoes carry the germ."),
       M("application", "Which helps to prevent malaria?", "sleeping under a mosquito net", ["sleeping outside", "eating more sugar", "washing only the feet"], "A net keeps mosquitoes away."),
       M("application", "When should we wash our hands?", "before eating and after using the toilet", ["only on Sundays", "never", "only when we see dirt"], "These are key times."),
       TF("approfondissement", "It is safe to drink water from any stream without treating it.", False, "Water from streams may carry germs: boil, filter or treat it."),
       MA("approfondissement", "Match each habit with its benefit.", [("brushing teeth", "healthy teeth"), ("mosquito net", "protects from malaria bites"), ("washing hands", "removes germs"), ("boiling water", "makes drinking water safer")], "Each habit protects health."),
       O("Write four sentences telling younger pupils how to keep healthy. Use the words 'soap', 'water', 'net' and 'clean'.",
         "Wash your hands with soap and water before you eat. Drink only clean water. Sleep under a mosquito net every night. Keep your house and school yard clean.",
         "Marks (4): each sentence correct and using one of the required words (1 each); answers must not give medicine advice.", tier="examen", points=4, difficulty=2)],
      [("Before eating we should...", "wash our hands with soap", ["run", "sleep", "clap"], "To remove germs."),
       ("Mosquitoes lay eggs in...", "still water", ["dry sand", "fire", "the wind"], "Stagnant water."),
       ("To stay healthy we should...", "brush our teeth and bathe", ["never wash", "eat only sweets", "sleep outside"], "Good hygiene."),
       ("If a child has a fever, we should...", "tell an adult and go to the health centre", ["wait without telling anyone", "give any tablet", "send the child to play"], "A health worker can help."),
       ("Safe drinking water is...", "boiled, filtered or treated", ["from a puddle", "from a dirty pond", "any water"], "It removes germs.")],
      [HEALTH, "No medicine names or doses are given on purpose."])

# ===================================================== 4. earth
ch = p.chapter("earth", "Soil, water and weather", REF)

fig = table([["Soil", "Grains", "Holds water", "Good for"], ["sand", "large", "very little", "building"], ["clay", "tiny, sticky", "a lot", "bricks, pots"], ["loam", "mixed + humus", "enough", "farming"]], [60, 110, 100, 100], rh=34, size=12)
build(ch, "soil", "Soil: types and uses", 30,
      ["Name the three main types of soil and describe them.", "Say what humus is and why it is useful.", "Explain what soil erosion is and how to reduce it."],
      [("key", "definition", "Types of soil", "**Sandy soil** has big grains; water runs through it quickly. **Clay soil** has tiny sticky grains; it holds a lot of water and is used for bricks and pots. **Loam** is a mix of sand, clay and **humus**, and it is the best for farming. **Humus** is made from rotted plants and animals and gives plants food."),
       ("fig", fig, "Three types of soil.", "A table with sand, clay and loam: size of grains, how much water they hold, and what they are good for."),
       ("key", "retenir", "Erosion", "**Soil erosion** is when rain or wind carries away the top layer of soil. It happens most on **bare, sloping land** after trees and plants are cut. We can reduce it by **planting trees and grass**, **covering the soil** with leaves or crops, and planting across a slope instead of down it."),
       ("key", "pieges", "Common mistakes", "- Thinking that soil is the same everywhere: different places have different soils.\n- Saying that clay is best for plants because it holds water: loam is best.\n- Cutting all trees on a hill, which leads to erosion.\n- Burning dry leaves instead of using them as compost.")],
      [("ex", "Example 1", "Ako pours 200 ml of water on sandy soil and 120 ml drips out. How much water stayed in the soil?", ["Water that stayed = water poured − water that came out.", "200 − 120 = 80."], "80 ml", None),
       ("ex", "Example 2", "Which soil would you use to make pots? Why?", ["The soil must be sticky and keep its shape when wet.", "Clay: its tiny grains stick together."], "Clay", None)],
      [M("application", "Which soil is best for growing crops?", "loam", ["sand only", "clay only", "stones"], "It has enough water and humus."),
       M("application", "Humus comes from...", "rotted plants and animals", ["stones", "plastic", "sand"], "It makes the soil rich."),
       M("application", "Which soil lets water pass through quickly?", "sand", ["clay", "loam", "humus"], "Large grains."),
       N("approfondissement", "300 ml of water is poured on clay soil and 60 ml drips out. How much water stays in the soil?", 240, "300 − 60 = 240.", unit="ml"),
       TF("approfondissement", "Planting trees helps to stop soil erosion.", True, "Roots hold the soil."),
       P("A farmer in the Western Highlands has a hill farm. After heavy rains the red soil is washed down the hill into the stream.",
         [PM("What do we call this?", "soil erosion", ["germination", "evaporation", "digestion"], "Rain carries soil away."),
          PM("What could the farmer do to reduce it?", "plant grass and trees and plant across the slope", ["cut more trees", "leave the soil bare", "plough up and down the slope"], "Roots and cover protect soil."),
          PM("Which soil gives the best crops?", "loam with humus", ["bare sand", "stones", "plastic"], "Loam holds enough water and food.", points=2)])],
      [("The best soil for farming is...", "loam", ["sand", "stones", "ice"], "A mix with humus."),
       ("Clay soil is used to make...", "pots and bricks", ["glass", "paper", "cloth"], "It is sticky."),
       ("Soil erosion is...", "the washing away of soil", ["the making of soil", "the growing of crops", "the digging of wells"], "Rain or wind carry it."),
       ("Which can reduce erosion?", "planting trees", ["cutting trees", "burning grass", "leaving the land bare"], "Roots hold soil."),
       ("Sandy soil holds...", "very little water", ["a lot of water", "no sand", "only air"], "Water drains quickly.")],
      ["Soil types simplified to three; check regional soil names (e.g. volcanic soils near Mount Cameroon)."])

fig = shapes([CIRCLE(50, 40, 20, fill="yellow"), RECT(20, 170, 170, 40, fill="lightblue"), POLY([190, 210, 190, 160, 230, 130, 270, 150, 330, 140, 380, 160, 380, 210], fill="lightgreen"),
              CIRCLE(285, 45, 18, fill="lightgrey"), CIRCLE(310, 38, 22, fill="lightgrey"), CIRCLE(337, 46, 17, fill="lightgrey"),
              LINE(90, 165, 135, 85, color="blue", width=3, arrow="end"), LINE(150, 60, 262, 50, color="grey", width=3, arrow="end"), LINE(305, 70, 305, 128, color="blue", width=3, arrow="end"),
              LINE(340, 150, 195, 195, color="blue", width=3, arrow="end"),
              T(30, 110, "evaporation", 12, anchor="start", bold=True), T(175, 40, "condensation", 12, bold=True), T(318, 105, "rain", 12, anchor="start", bold=True), T(265, 205, "run-off to river and sea", 11)], 400, 225)
build(ch, "water-cycle", "Water and the water cycle", 30,
      ["Describe the water cycle.", "Say where we get water and what we use it for.", "Explain how to make water safe to drink."],
      [("key", "definition", "The water cycle", "The Sun **heats** water in the sea, rivers and lakes and some of it becomes an invisible gas, **water vapour** (**evaporation**). Vapour rises, cools and turns into tiny drops that form **clouds** (**condensation**). When the drops get heavy they fall as **rain** (**precipitation**). Rain runs into rivers and the sea, and the cycle starts again."),
       ("fig", fig, "The water cycle.", "A diagram with the sea and the land. Arrows show evaporation going up from the sea under the sun, condensation making a cloud, rain falling on the land and water running back to rivers and the sea."),
       ("key", "retenir", "Using and cleaning water", "We use water for **drinking, cooking, washing, farming and industry**. Water sources are rain, rivers, springs, wells and boreholes. To make drinking water **safe**: let dirt settle, **filter** it through clean cloth, then **boil** it for a few minutes or use a treatment advised by a health worker. Do not waste water."),
       ("key", "pieges", "Common mistakes", "- Thinking that clouds are smoke: they are tiny drops of water.\n- Saying that water disappears when it evaporates: it becomes water vapour in the air.\n- Thinking that clear water is always safe: germs cannot be seen.\n- Throwing rubbish into rivers.")],
      [("ex", "Example 1", "Why does wet washing dry on a sunny day?", ["The Sun's heat makes the water in the cloth evaporate.", "The water turns into water vapour and goes into the air."], "The water evaporates.", None),
       ("ex", "Example 2", "What happens when water vapour rises and cools?", ["Cool air makes the vapour turn back into tiny drops.", "This is condensation and the drops make clouds."], "It condenses and forms clouds.", None)],
      [M("application", "What do we call water turning into vapour?", "evaporation", ["condensation", "freezing", "germination"], "Heat makes water evaporate."),
       M("application", "What forms when water vapour cools in the sky?", "clouds", ["stones", "sand", "wind only"], "Condensation makes clouds."),
       M("application", "Which is a way to make water safe to drink?", "boiling it", ["adding sand", "adding soil", "leaving it in the sun with rubbish"], "Boiling kills germs."),
       TF("approfondissement", "Rain, rivers and the sea are all parts of the water cycle.", True, "Water moves between them."),
       MA("approfondissement", "Match each word with its meaning.", [("evaporation", "water becomes vapour"), ("condensation", "vapour becomes drops"), ("precipitation", "rain falls"), ("run-off", "water flows into rivers")], "Follow the cycle."),
       P("Neba leaves a bowl of water in the sun. After two days the bowl is almost empty. Next to it he puts a cold glass and sees drops form on the outside.",
         [PM("Where did the water in the bowl go?", "into the air as water vapour", ["into the ground only", "into the glass", "it vanished"], "It evaporated."),
          PM("Why did drops form on the cold glass?", "water vapour in the air cooled and condensed", ["the glass leaks", "it rained", "the glass is wet inside"], "Condensation on a cold surface."),
          PM("Which part of the water cycle is this like?", "the formation of clouds", ["rain only", "rivers only", "the sea only"], "Condensation forms clouds.", points=2)])],
      [("Which part of the water cycle makes clouds?", "condensation", ["evaporation", "run-off", "digestion"], "Vapour cools into drops."),
       ("Which gives energy to the water cycle?", "the Sun", ["the Moon", "the wind only", "stones"], "Its heat evaporates water."),
       ("To make drinking water safer we...", "boil it", ["add mud", "stir it with a stick", "drink it at once"], "Boiling kills germs."),
       ("Rain is also called...", "precipitation", ["evaporation", "condensation", "erosion"], "Water falling from clouds."),
       ("Water vapour is...", "water as an invisible gas", ["smoke", "ice", "mud"], "It is in the air around us.")],
      [HEALTH, "Boiling time is not stated; a health worker can add the recommended time."])

vals = [("Jan", 15), ("Feb", 40), ("Mar", 110), ("Apr", 160), ("May", 95)]
fig = safe_bars(vals, unit="Rain (mm) at an imaginary village", w=400, h=250)
build(ch, "weather", "Weather and seasons", 30,
      ["Name the parts of the weather.", "Read a thermometer and a simple weather chart.", "Describe the dry and the rainy season in Cameroon."],
      [("key", "definition", "Weather", "**Weather** is what the air is like at a place and time: **sunny, cloudy, rainy, windy, hot or cold**. We measure the **temperature** with a **thermometer** (in degrees Celsius, °C), the **rain** with a rain gauge (in mm) and the **wind direction** with a wind vane. **Climate** is the usual weather over many years."),
       ("fig", fig, "Rain recorded in five months (an imaginary village).", "A bar chart of rain in millimetres: January 15, February 40, March 110, April 160, May 95."),
       ("key", "retenir", "Seasons in Cameroon", "Most of Cameroon has two seasons: the **dry season** (little rain, sunny, dusty Harmattan wind in the north) and the **rainy season** (clouds, heavy rain). The south has **two rainy seasons** a year, the north **one**. Weather changes the way we dress, farm and travel: umbrellas in the rain, light clothes in the heat."),
       ("key", "pieges", "Common mistakes", "- Mixing **weather** (today) with **climate** (over many years).\n- Reading a thermometer at the wrong level: read the top of the liquid.\n- Thinking that it always rains in the rainy season: it also has sunny periods.\n- Forgetting the unit °C.")],
      [("ex", "Example 1", "In the chart, which month had the most rain and how much more than January?", ["The tallest bar is April: 160 mm. January had 15 mm.", "160 − 15 = 145."], "April; 145 mm more.", fig),
       ("ex", "Example 2", "Find the average rain in the five months.", ["Add: 15 + 40 + 110 + 160 + 95 = 420.", "Divide by 5: 420 ÷ 5 = 84."], "84 mm", None)],
      [M("application", "What does a thermometer measure?", "temperature", ["rain", "wind speed", "clouds"], "In degrees Celsius."),
       M("application", "Which season has the most rain?", "the rainy season", ["the dry season", "the Harmattan", "none"], "The rainy season is the wet part of the year."),
       N("application", "A thermometer shows 31 °C at noon and 24 °C at night. How many degrees warmer is noon?", 7, "31 − 24 = 7.", unit="°C"),
       N("approfondissement", "Rain in four days was 5 mm, 12 mm, 0 mm and 7 mm. What was the total?", 24, "5 + 12 + 0 + 7 = 24.", unit="mm"),
       TF("approfondissement", "Weather and climate mean exactly the same.", False, "Weather is today's conditions; climate is the long-term pattern."),
       P("A class records the weather every day for 5 days: Monday sunny 30 °C, Tuesday cloudy 28 °C, Wednesday rainy 25 °C, Thursday rainy 24 °C, Friday sunny 29 °C.",
         [PM("Which day was the coolest?", "Thursday", ["Monday", "Tuesday", "Friday"], "24 °C is the lowest."),
          PN("What was the total of the 5 temperatures?", 30 + 28 + 25 + 24 + 29, "30 + 28 + 25 + 24 + 29 = 136.", unit="°C"),
          PN("What was the mean (average) temperature?", 136 / 5, "136 ÷ 5 = 27.2.", tol=0.01, unit="°C", points=2)])],
      [("A rain gauge measures...", "rain", ["wind", "heat", "clouds"], "In millimetres."),
       ("The usual weather of a place over many years is its...", "climate", ["storm", "season only", "wind"], "Climate is long term."),
       ("The unit for temperature is...", "degree Celsius", ["kilogram", "metre", "litre"], "°C."),
       ("The south of Cameroon has...", "two rainy seasons", ["one rainy season", "no rain", "snow"], "As in the geography lessons."),
       ("A wind vane shows...", "the direction of the wind", ["rain", "temperature", "the Sun"], "It turns with the wind.")],
      ["Rain data are imaginary. The north/south season description is simplified and should be checked with the geography lessons."])

# ===================================================== 5. matter, energy
ch = p.chapter("matter-energy", "Matter, energy and simple electricity", REF)

dots_s = [CIRCLE(30 + 22 * c, 40 + 22 * r, 8, fill="blue") for r in range(3) for c in range(4)]
dots_l = [CIRCLE(x, y, 8, fill="cyan") for x, y in [(150, 50), (176, 48), (160, 72), (190, 76), (170, 98), (146, 90), (204, 56), (140, 64)]]
dots_g = [CIRCLE(x, y, 8, fill="orange") for x, y in [(285, 30), (355, 55), (310, 95), (260, 75), (345, 100), (275, 112)]]
fig = shapes(dots_s + dots_l + dots_g + [T(60, 140, "solid", 14, bold=True), T(175, 140, "liquid", 14, bold=True), T(310, 140, "gas", 14, bold=True)], 400, 160)
build(ch, "states-of-matter", "Solids, liquids and gases", 30,
      ["Describe a solid, a liquid and a gas.", "Name changes of state: melting, freezing, evaporation, condensation.", "Give everyday examples."],
      [("key", "definition", "Three states", "**Matter** is anything that takes up space and has mass. It can be a **solid** (keeps its shape: stone, book), a **liquid** (flows and takes the shape of its container: water, oil, milk) or a **gas** (spreads to fill its container: air, steam). We cannot see most gases, but we feel moving air as wind."),
       ("fig", fig, "How the tiny parts are arranged.", "Three groups of circles: a solid with neat rows close together, a liquid with circles close but loosely placed, and a gas with circles far apart."),
       ("key", "retenir", "Changes of state", "**Melting**: solid to liquid (ice to water). **Freezing**: liquid to solid (water to ice at 0 °C). **Evaporation**: liquid to gas (wet clothes drying). **Boiling**: water changes to steam fast at 100 °C. **Condensation**: gas to liquid (drops on a cold glass). Heat makes things melt or evaporate; cooling makes them freeze or condense."),
       ("key", "pieges", "Common mistakes", "- Thinking that air is nothing: air is a gas and takes up space.\n- Saying that steam is the white cloud you see: the white is tiny water droplets; steam itself is invisible.\n- Saying that a powder (like flour) is a liquid because it can be poured: each grain is a solid.\n- Mixing melting (solid to liquid) with evaporation (liquid to gas).")],
      [("ex", "Example 1", "Ice is left in the sun and turns into water. Which change is this?", ["Ice is a solid and water is a liquid.", "Solid to liquid is melting."], "Melting", fig),
       ("ex", "Example 2", "Name the state of: milk, a stone, the air in a balloon.", ["Milk flows: liquid. A stone keeps its shape: solid.", "Air in a balloon spreads to fill it: gas."], "liquid, solid, gas.", None)],
      [M("application", "Which is a liquid?", "cooking oil", ["a stone", "a book", "the air"], "It flows."),
       M("application", "What do we call a liquid turning into a gas?", "evaporation", ["melting", "freezing", "condensing"], "Heat makes water evaporate."),
       M("application", "At what temperature does pure water freeze (at normal conditions)?", "0 °C", ["100 °C", "50 °C", "-20 °C"], "Water freezes at 0 °C."),
       N("approfondissement", "Water boils at 100 °C and freezes at 0 °C. What is the difference between the two temperatures?", 100, "100 − 0 = 100 degrees.", unit="°C"),
       TF("approfondissement", "A gas always keeps the same shape.", False, "A gas fills whatever container it is in."),
       P("Bih puts a tray of water in a freezer. Later she takes out a block of ice and leaves it on the table. After an hour it is a puddle. A cold bottle from the fridge gets drops on the outside.",
         [PM("What change happened in the freezer?", "freezing", ["melting", "evaporation", "condensation"], "Liquid to solid."),
          PM("What change made the puddle?", "melting", ["freezing", "boiling", "condensation"], "Solid to liquid."),
          PM("What caused the drops on the cold bottle?", "condensation of water vapour", ["the bottle leaking", "boiling", "melting of glass"], "Vapour in the air cooled.", points=2)])],
      [("A solid...", "keeps its shape", ["flows", "fills all space", "cannot be touched"], "Stone, book."),
       ("Water becomes ice by...", "freezing", ["melting", "boiling", "evaporating"], "Liquid to solid."),
       ("Air is a...", "gas", ["solid", "liquid", "plant"], "It takes up space."),
       ("Which change needs cooling?", "condensation", ["melting", "evaporation", "boiling"], "Gas to liquid."),
       ("Steam is...", "water as a gas", ["ice", "smoke", "sand"], "It is hot water vapour.")],
      ["Particle diagram is schematic; the temperature values assume normal pressure; boiling point near 100 °C only at sea level (not stated in the lesson)."])

fig = shapes([CIRCLE(40, 90, 14, fill="yellow"), LINE(60, 90, 160, 90, color="orange", width=2, arrow="end"), RECT(160, 60, 30, 60, fill="brown"),
              LINE(190, 90, 340, 90, color="grey", width=2, dash=True), RECT(300, 80, 80, 20, fill="lightgrey"),
              T(40, 55, "light source", 12, bold=True), T(175, 50, "opaque object", 12, bold=True), T(340, 130, "shadow", 12, bold=True), T(110, 75, "light travels in a straight line", 11)], 400, 150)
build(ch, "light-heat-sound", "Light, heat and sound", 35,
      ["Say how light travels and how shadows form.", "Tell conductors and insulators of heat apart.", "Say that sound is made by vibrations."],
      [("key", "definition", "Light", "**Light** comes from **sources** such as the Sun, a fire and a lamp. It travels in **straight lines**. **Transparent** materials let light through (clear glass), **translucent** ones let some through (frosted glass) and **opaque** ones let none through (wood, metal). A **shadow** forms when an opaque object blocks the light."),
       ("fig", fig, "How a shadow forms.", "A light source on the left, an opaque object in the middle blocking the light and a shadow on the right. A note says that light travels in a straight line."),
       ("key", "retenir", "Heat and sound", "**Heat** flows from hot things to cold things. **Metals** are good **conductors** of heat (a metal spoon in hot soup gets hot). **Wood, plastic and cloth** are **insulators**: pot handles and oven gloves are made of them. **Sound** is made when things **vibrate** (a drum skin, a guitar string). It travels through air, water and solids, but **not through empty space**. Loud sounds can hurt the ears."),
       ("key", "pieges", "Common mistakes", "- Thinking that a shadow is made of light: it is a place where light is blocked.\n- Touching a hot pot without a holder.\n- Thinking that sound needs no material: it needs something to travel through.\n- Playing loud music or shouting right next to a person's ear.")],
      [("ex", "Example 1", "Why is the handle of a metal pot made of wood or plastic?", ["Metal conducts heat, so a metal handle would burn the hand.", "Wood and plastic are insulators."], "They do not conduct heat, so the handle stays cool.", None),
       ("ex", "Example 2", "A child stands in the sun and has a shadow behind her. Where is the Sun?", ["A shadow forms on the side away from the light.", "The Sun is in front of her, opposite the shadow."], "In front of her (opposite the shadow).", None)],
      [M("application", "Which material is opaque?", "wood", ["clear glass", "clear plastic", "air"], "It blocks light."),
       M("application", "Which is a good conductor of heat?", "metal", ["wood", "plastic", "cloth"], "Metals conduct heat."),
       M("application", "What makes sound?", "vibrations", ["colours", "shadows", "magnets"], "A vibrating object makes sound."),
       TF("approfondissement", "Light travels in curved lines around objects.", False, "Light travels in straight lines, which is why shadows form."),
       MA("approfondissement", "Match each material with its type.", [("clear glass", "transparent"), ("frosted glass", "translucent"), ("a wooden door", "opaque"), ("a metal spoon", "good conductor of heat")], "Light and heat properties."),
       P("Ako holds a torch behind a book on a table and sees a shadow of the book on the wall. He then moves the book closer to the torch.",
         [PM("Why is there a shadow?", "the book blocks the light", ["light goes round the book", "the wall makes light", "the torch is off"], "An opaque object blocks light."),
          PM("What happens to the shadow if the book moves closer to the torch?", "it gets bigger", ["it disappears", "it gets smaller", "it turns red"], "A closer object blocks more light."),
          PM("Which material would give no shadow at all?", "clear glass", ["wood", "metal", "a book"], "Transparent materials let light through, so there is hardly any shadow.", points=2)])],
      [("Light travels in...", "straight lines", ["circles", "zigzags", "waves of mud"], "That is why shadows form."),
       ("A material that lets no light through is...", "opaque", ["transparent", "translucent", "clear"], "Opaque blocks light."),
       ("Sound is made by...", "vibrations", ["shadows", "heat only", "colours"], "Things shaking."),
       ("An oven glove is made of an...", "insulator", ["conductor", "magnet", "mirror"], "It stops heat reaching the hand."),
       ("Heat flows from...", "hot things to cold things", ["cold to hot", "nowhere", "only to water"], "Always from hot to cold.")],
      ["Light and sound statements are standard; keep demonstrations safe (never look at the Sun)."])

fig = shapes([RECT(60, 100, 40, 30, fill="lightyellow"), T(80, 150, "cell (battery)", 12, bold=True),
              CIRCLE(300, 110, 20, fill="yellow"), T(300, 160, "bulb", 12, bold=True),
              LINE(100, 115, 100, 50, width=3), LINE(100, 50, 195, 50, width=3), LINE(195, 50, 215, 35, width=3), LINE(235, 50, 300, 50, width=3), LINE(300, 50, 300, 90, width=3),
              LINE(300, 130, 300, 175, width=3), LINE(300, 175, 80, 175, width=3), LINE(80, 175, 80, 130, width=3), T(215, 28, "switch", 12, bold=True),
              T(210, 100, "closed circuit: the bulb lights", 12)], 400, 195)
build(ch, "magnets-electricity", "Magnets and simple electric circuits", 35,
      ["Say what a magnet attracts and what poles do.", "Make a simple circuit with a cell, a bulb, a switch and wires.", "Name safety rules for electricity."],
      [("key", "definition", "Magnets", "A **magnet** attracts objects made of **iron or steel** (nails, pins). It does not attract wood, plastic, glass or copper. Every magnet has two **poles**, north and south. **Unlike poles attract** (N and S), **like poles repel** (N and N, or S and S). A magnet is strongest at its poles."),
       ("key", "definition", "A simple circuit", "A bulb lights when it is part of a **closed circuit**: a **cell**, **wires**, a **bulb** and a **switch** joined in a loop. If there is a gap (the switch is open) or a broken wire, the circuit is open and the bulb does not light. **Conductors** (copper, iron) let electricity pass; **insulators** (plastic, rubber, wood) do not."),
       ("fig", fig, "A closed circuit with a cell, a switch and a bulb.", "A rectangle loop of wires with a cell on the left, a switch at the top and a bulb on the right. The note says closed circuit: the bulb lights."),
       ("key", "attention", "Electrical safety", "**Never** touch bare wires, sockets or switches with wet hands. **Never** put fingers or objects into a socket. Keep away from fallen power lines and tell an adult. Do **not** use mains electricity for experiments: only use **small cells** (batteries) at school, with a teacher."),
       ("key", "pieges", "Common mistakes", "- Thinking that a magnet attracts all metals: only iron, steel and a few others.\n- Believing that like poles attract.\n- Connecting a bulb with a gap in the circuit and expecting it to light.\n- Playing with sockets or flying kites near power lines.")],
      [("ex", "Example 1", "A magnet is held near: a nail, a coin of copper, a wooden ruler. Which does it attract?", ["Iron and steel are attracted.", "A nail is iron or steel: attracted. Copper and wood are not."], "Only the nail.", None),
       ("ex", "Example 2", "Why does a bulb not light when the switch is open?", ["An open switch makes a gap in the circuit.", "Electricity cannot flow round the loop."], "The circuit is open, so no electricity flows.", None)],
      [M("application", "Which object will a magnet attract?", "an iron nail", ["a plastic spoon", "a wooden pencil", "a glass marble"], "Iron is magnetic."),
       M("application", "What do two north poles do when they meet?", "repel each other", ["attract each other", "join together", "disappear"], "Like poles repel."),
       M("application", "Which is an insulator?", "plastic", ["copper wire", "iron nail", "a metal spoon"], "It does not let electricity pass."),
       TF("approfondissement", "A bulb lights in an open circuit.", False, "The circuit must be closed."),
       MA("approfondissement", "Match each material with its type.", [("copper wire", "conductor"), ("rubber", "insulator"), ("iron nail", "magnetic"), ("plastic spoon", "not magnetic")], "Conduction and magnetism are different properties."),
       P("In a science lesson Ako connects a cell, a bulb and wires but the bulb does not light. The teacher checks and finds that one wire has come off the bulb holder.",
         [PM("Why does the bulb not light?", "the circuit is open", ["the cell is too heavy", "the bulb is too big", "wires do not conduct"], "A loose wire makes a gap."),
          PM("What should Ako do?", "reconnect the wire to make a closed circuit", ["use a bigger cell with wet hands", "throw away the bulb", "touch a socket"], "Close the circuit safely."),
          PM("Which rule must always be followed?", "never use mains electricity for experiments", ["touch sockets to test them", "use wet hands", "poke wires in sockets"], "Use small cells only.", points=2)])],
      [("Unlike poles of two magnets...", "attract", ["repel", "disappear", "melt"], "N and S attract."),
       ("A circuit must be...", "closed", ["open", "broken", "empty"], "A complete loop."),
       ("Which is a conductor of electricity?", "copper", ["rubber", "wood", "plastic"], "Metals conduct."),
       ("A magnet attracts...", "iron", ["wood", "paper", "plastic"], "Magnetic materials."),
       ("Which is a safety rule?", "do not touch sockets with wet hands", ["fly kites near power lines", "poke wires in sockets", "use mains for experiments"], "Water and electricity are dangerous together.")],
      ["Electrical safety and the science experiments must be supervised by a teacher; the circuit diagram is schematic (no standard symbols)."])

p.write()
