import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from p45_kit import *

TAG["v"] = "Class 5 Science"
p = Pack("class5-science", "Elementary Science and Technology — Class 5", level="Class 5", subject="sciences", cursus="primary",
         description="Class 5 Elementary Science and Technology for the English-speaking primary subsystem: plant and animal life, the human body (breathing and circulation), food, disease prevention, soil and water, weather, matter, energy, electricity, forces and simple machines, the environment and technology. Draft lessons with worked examples, exercises and self-checks.",
         programRef="MINEDUB primary school curriculum (English-speaking subsystem), Level III (Class 5) — Elementary Science and Technology; to be checked against the official syllabus",
         wanted="elementary-science")
REF = p.programRef
HEALTH = "Health and hygiene content is conservative and general; it must be reviewed by a health worker or a teacher before release."

# ===================================================== 1. living things
ch = p.chapter("living", "Plants and animals", REF)

fig = flow(["seed", "seedling", "plant", "flower", "fruit"], size=11, vertical=False)
build(ch, "plant-reproduction", "Plants: making food, pollination and seed dispersal", 35,
      ["Explain how leaves make food (photosynthesis).", "Describe pollination and how seeds are spread.", "Put the stages of a plant's life cycle in order."],
      [("key", "definition", "Making food", "Green leaves contain **chlorophyll**, which gives them their colour. Using **sunlight**, leaves turn **carbon dioxide** (from the air) and **water** (from the soil) into **food** (sugar) and give out **oxygen**. This is **photosynthesis**. The food is used for growth and stored in roots, stems, fruits and seeds, for example in cassava and yam."),
       ("fig", fig, "Life cycle of a flowering plant.", "Five boxes joined by arrows: seed, seedling, plant, flower, fruit."),
       ("key", "retenir", "Pollination and seeds", "**Pollination** is the moving of **pollen** from one flower to the **stigma** of a flower of the same kind, by **insects** (bees, butterflies) or by the **wind**. After pollination the flower can make **seeds** inside a **fruit**. Seeds are spread (**dispersed**) by **wind** (light, winged or fluffy seeds), **water** (coconut), **animals** (sticky burrs, fruit eaten and dropped) or by the **pod bursting open** (beans)."),
       ("key", "pieges", "Common mistakes", "- Saying that plants take in oxygen to make food: they take in **carbon dioxide** (they also breathe like all living things).\n- Thinking that soil is the plant's food: the food is made in the leaves.\n- Thinking that pollination and seed dispersal are the same.\n- Forgetting that seeds are spread so that new plants do not crowd the parent.")],
      [("ex", "Example 1", "Name three things a leaf needs to make food and one thing it gives out.", ["It needs sunlight, water and carbon dioxide.", "It gives out oxygen."], "Needs sunlight, water, carbon dioxide; gives out oxygen.", None),
       ("ex", "Example 2", "A coconut falls into a river and lands on a beach far away. How was the seed dispersed?", ["The seed floated and was carried by the water.", "This is dispersal by water."], "By water", None)],
      [M("application", "What gives leaves their green colour?", "chlorophyll", ["pollen", "oxygen", "soil"], "Chlorophyll is the green substance."),
       M("application", "What do plants give out during photosynthesis?", "oxygen", ["carbon dioxide", "pollen", "smoke"], "They release oxygen."),
       M("application", "Which animals help with pollination?", "bees", ["fish", "snakes", "crabs"], "Insects carry pollen."),
       TF("approfondissement", "Light fluffy seeds are often spread by the wind.", True, "The wind carries them far."),
       MA("approfondissement", "Match each seed with the way it is spread.", [("a coconut", "water"), ("a seed with wings or fluff", "wind"), ("a sticky burr", "animals"), ("a bean pod that bursts", "the pod bursting")], "Look at the seed's shape."),
       P("Ako covers one leaf of a plant with black paper for one week while the rest of the plant gets sunlight. The covered leaf turns pale and weak.",
         [PM("Why does the covered leaf turn pale?", "it gets no light to make food", ["it gets too much water", "it is too cold", "it has no roots"], "Photosynthesis needs light."),
          PM("Which part of the plant makes the food?", "the green leaves", ["the roots", "the soil", "the flower only"], "Leaves contain chlorophyll."),
          PM("Which gas do the uncovered leaves take in?", "carbon dioxide", ["oxygen only", "smoke", "nitrogen only"], "It is needed for photosynthesis.", points=2)])],
      [("Photosynthesis needs...", "sunlight, water and carbon dioxide", ["only soil", "only oxygen", "stones"], "Three raw materials."),
       ("Pollination is moving...", "pollen to the stigma", ["seeds to the soil", "water to leaves", "roots to the ground"], "Insects and wind do it."),
       ("Which seed is dispersed by water?", "a coconut", ["a burr", "a bean", "a fluffy seed"], "It floats."),
       ("A seed grows first into a...", "seedling", ["fruit", "flower", "pod"], "Then a plant."),
       ("Which gas does a plant give out in the light?", "oxygen", ["carbon dioxide", "smoke", "nitrogen only"], "A product of photosynthesis.")],
      ["Photosynthesis described at the simple level; check whether chlorophyll and pollination are expected in Class 5."])

fig = flow(["maize", "rat", "snake", "eagle"], size=13, vertical=False)
build(ch, "food-chains", "Food chains and adaptation", 30,
      ["Build a food chain and name producers and consumers.", "Say where energy in a food chain comes from.", "Give examples of how animals are adapted to their habitats."],
      [("key", "definition", "Food chains", "A **food chain** shows who eats whom. **Plants** are **producers**: they make their own food using sunlight. Animals are **consumers**: **herbivores** (primary consumers) eat plants; **carnivores** (secondary consumers) eat other animals. The arrow means 'is eaten by'. **Decomposers** (bacteria, fungi, some insects) break down dead plants and animals."),
       ("fig", fig, "A food chain: maize, rat, snake, eagle.", "Four boxes joined by arrows: maize, rat, snake, eagle."),
       ("key", "retenir", "Energy and adaptation", "The **Sun** is the first source of energy: plants capture it and pass it on along the chain. An **adaptation** is a feature that helps an animal to live in its habitat: a **fish** has gills and fins for water; a **bird** has wings and light bones to fly; a **chameleon** changes colour to hide; a **lion** has sharp teeth for eating meat. A **food web** joins many food chains."),
       ("key", "pieges", "Common mistakes", "- Drawing the arrow the wrong way: the arrow goes **from the food to the eater** (maize → rat).\n- Forgetting that every food chain starts with a plant.\n- Thinking that animals choose to change their bodies: adaptations develop over many generations.\n- Putting a herbivore after a carnivore in a chain.")],
      [("ex", "Example 1", "In the chain grass → grasshopper → bird → hawk, name the producer and the top consumer.", ["The producer is the plant that makes food: grass.", "The last animal in the chain is the hawk."], "Producer: grass; top consumer: hawk.", None),
       ("ex", "Example 2", "What happens to the rats if all the snakes in a field are killed?", ["Fewer animals eat the rats, so the rat numbers may increase.", "They may then eat too much of the maize."], "The number of rats may grow and damage the crops.", None)],
      [M("application", "In a food chain, what is a producer?", "a green plant", ["a hawk", "a rat", "a snake"], "Plants make their own food."),
       M("application", "Which animal is a herbivore?", "a goat", ["a lion", "an eagle", "a snake"], "A goat eats plants."),
       M("application", "What does the arrow in a food chain mean?", "is eaten by", ["is faster than", "sleeps with", "lives near"], "From food to eater."),
       TF("approfondissement", "The first source of energy for a food chain is the Sun.", True, "Plants capture the Sun's energy."),
       MA("approfondissement", "Match each animal with an adaptation.", [("fish", "gills for breathing in water"), ("bird", "wings for flying"), ("chameleon", "colour change to hide"), ("lion", "sharp teeth for meat")], "Adaptations fit the habitat."),
       P("A food chain in a farm in the Western Highlands: maize → grasshopper → lizard → hawk.",
         [PM("Which one is the producer?", "maize", ["grasshopper", "lizard", "hawk"], "It is a plant."),
          PM("Which one is a secondary consumer (a carnivore eating a herbivore)?", "lizard", ["maize", "grasshopper", "the Sun"], "It eats the grasshopper, a herbivore."),
          PN("How many living things are there in the chain?", 4, "Maize, grasshopper, lizard and hawk.", points=2)])],
      [("A producer is a...", "plant", ["lion", "snake", "hawk"], "It makes its own food."),
       ("An animal that eats only plants is a...", "herbivore", ["carnivore", "producer", "decomposer"], "Herbivore."),
       ("Decomposers...", "break down dead plants and animals", ["make sunlight", "fly", "produce rain"], "Bacteria and fungi."),
       ("Which is an adaptation of a fish?", "gills", ["feathers", "fur", "legs"], "To breathe in water."),
       ("Every food chain begins with...", "a plant", ["a lion", "a snake", "a decomposer"], "Producers come first.")],
      ["The chain examples are generic and not claimed as exact Cameroon food webs."])

# ===================================================== 2. human body
ch = p.chapter("body", "The human body and health", REF)

fig = flow(["nose / mouth", "windpipe", "lungs", "blood"], size=11, vertical=False)
assert 18 * 4 == 72
build(ch, "breathing-circulation", "Breathing and circulation", 35,
      ["Describe the path of air into the lungs.", "Say what the heart and blood do.", "Take a pulse and work out heartbeats per minute."],
      [("key", "definition", "Breathing", "We breathe in air through the **nose or mouth**. It goes down the **windpipe** into the **lungs**. In the lungs **oxygen** passes into the **blood** and **carbon dioxide** (a waste gas) passes out, so we breathe out air with more carbon dioxide. About one-fifth of the air is oxygen."),
       ("fig", fig, "How oxygen reaches the blood.", "Four boxes joined by arrows: nose or mouth, windpipe, lungs, blood."),
       ("key", "definition", "Circulation", "The **heart** is a muscle about the size of your fist. It **pumps blood** round the body through tubes called **blood vessels**. Blood carries **oxygen and food** to every part and takes away waste. You can feel the heart beat as your **pulse** at the wrist or neck. Exercise makes the heart beat faster. A resting adult has roughly 60 to 100 beats a minute."),
       ("key", "pieges", "Common mistakes", "- Saying that the lungs make oxygen: they take it from the air.\n- Thinking that the heart is on the left side only: it is in the middle of the chest, slightly to the left.\n- Counting pulse for too short a time: count for 15 seconds and multiply by 4.\n- Thinking that smoke is harmless: tobacco smoke damages the lungs.")],
      [("ex", "Example 1", "Ako counts 18 pulse beats in 15 seconds. How many beats per minute is that?", ["There are four 15-second periods in a minute.", "18 × 4 = 72."], "72 beats per minute.", None),
       ("ex", "Example 2", "Why does your heart beat faster after running?", ["Your muscles need more oxygen and food when you run.", "The heart pumps faster to carry more blood to them."], "The muscles need more oxygen, so the heart pumps faster.", None)],
      [M("application", "Which organs do we use to breathe?", "lungs", ["stomach", "kidneys", "brain"], "Air goes into the lungs."),
       M("application", "What does the heart do?", "pumps blood", ["makes oxygen", "digests food", "makes bones"], "It is a muscle pump."),
       N("application", "12 pulse beats are counted in 10 seconds. How many beats in a minute?", 72, "12 × 6 = 72.", unit="beats"),
       TF("approfondissement", "We breathe out more carbon dioxide than we breathe in.", True, "Blood gives carbon dioxide to the lungs."),
       MA("approfondissement", "Match each organ with its job.", [("lungs", "take oxygen from the air"), ("heart", "pumps blood"), ("blood vessels", "carry blood round the body"), ("windpipe", "air passage to the lungs")], "Learn the roles."),
       P("Neba counts his pulse: 20 beats in 15 seconds while he rests. After 2 minutes of running on the spot he counts 33 beats in 15 seconds.",
         [PN("What is his resting pulse per minute?", 80, "20 × 4 = 80.", unit="beats"),
          PN("What is his pulse after running per minute?", 132, "33 × 4 = 132.", unit="beats"),
          PM("What does the change show?", "exercise makes the heart beat faster", ["the heart stops", "running slows the heart", "nothing changes"], "More oxygen is needed.", points=2)])],
      [("Oxygen passes into the blood in the...", "lungs", ["stomach", "ears", "skin"], "Gas exchange."),
       ("The pulse is...", "the heart beat felt at the wrist", ["a sound of the stomach", "a breath", "a bone"], "Press gently with two fingers."),
       ("Blood carries...", "oxygen and food", ["only air", "only water", "stones"], "And takes away waste."),
       ("Smoking is harmful because smoke damages the...", "lungs", ["toes", "nails", "hair only"], "Do not smoke."),
       ("The air we breathe out has more...", "carbon dioxide", ["oxygen", "dust only", "water only"], "Compared with the air we breathe in.")],
      [HEALTH, "Resting heart rates are approximate; do not use them for any medical judgement."])

fig = table([["Method", "How it works", "Example"], ["drying", "removes water", "dried fish, maize"], ["smoking", "smoke and heat", "smoked fish, meat"], ["salting", "salt draws out water", "salted fish"], ["cooling", "slows germs", "fridge"], ["canning", "sealed and heated", "tinned tomatoes"]], [90, 140, 130], rh=28, size=13)
build(ch, "diet-preservation", "A healthy diet and keeping food safe", 30,
      ["Say why we need each food group and water.", "Explain why food goes bad.", "Name ways of preserving food."],
      [("key", "definition", "A healthy diet", "We need **carbohydrates** for energy (cassava, rice, yam), **proteins** for growth and repair (beans, fish, eggs), **vitamins and minerals** for health (fruit, vegetables), a little **fat** and **plenty of water**. Eating too little protein or too few fruits and vegetables for a long time can cause **deficiency diseases**. A **balanced diet** has all groups in the right amounts."),
       ("key", "definition", "Why food goes bad", "Food goes bad when **germs** such as **bacteria and moulds** grow on it. They grow best in **warm, wet** conditions. Bad food can cause stomach pains, diarrhoea and vomiting. We **preserve** food by removing water, adding salt or smoke, cooling, or sealing it in tins."),
       ("fig", fig, "Ways of keeping food safe.", "A table of preservation methods: drying removes water, smoking, salting draws out water, cooling slows germs and canning seals food; examples are dried fish, smoked fish, salted fish, fridge and tinned tomatoes."),
       ("key", "pieges", "Common mistakes", "- Eating food that smells bad because it still looks fine.\n- Leaving cooked food in the heat for hours.\n- Keeping raw and cooked food together.\n- Thinking that a food kept in the fridge never goes bad: it only lasts longer.")],
      [("ex", "Example 1", "Why is fish smoked or dried in many villages?", ["Smoking and drying remove water, and germs cannot grow without water.", "So the fish can be kept for days or weeks."], "It removes water, so germs cannot grow and the fish keeps longer.", fig),
       ("ex", "Example 2", "Why should cooked food be covered?", ["Flies carry germs from dirty places.", "Covering keeps flies and dust away."], "To keep flies and germs off the food.", None)],
      [M("application", "Which food group helps the body to grow and repair?", "protein", ["only oil", "only salt", "only sugar"], "Beans, fish and eggs."),
       M("application", "Which of these is a way to preserve fish?", "smoking", ["washing with soap", "painting", "burying in the wet soil"], "Smoke and heat remove water."),
       M("application", "Food goes bad because...", "germs grow on it", ["it becomes shy", "it gets too heavy", "it gets too cold"], "Bacteria and moulds."),
       TF("approfondissement", "Germs grow best in warm, wet conditions.", True, "That is why we dry and cool food."),
       MA("approfondissement", "Match each food with the way it can be kept.", [("fish", "smoking or drying"), ("tomato puree", "canning"), ("milk", "cooling in a fridge"), ("meat", "salting or drying")], "Many foods can be kept in several ways."),
       P("Mama Bih cooks a big pot of soup at noon and leaves it uncovered on the table in a warm kitchen. At night the soup smells sour.",
         [PM("Why did the soup go bad?", "germs grew in it", ["it became cold", "it was too salty", "it was too thick"], "Warm, wet, uncovered food."),
          PM("How could she have kept it safe?", "cover it and keep it cool or reheat it well", ["leave it open", "add water", "give it to the cat"], "Cover and cool."),
          PM("Which group does soup with beans and fish belong to?", "body-building food", ["only fat", "only vitamins", "only sugar"], "They are rich in protein.", points=2)])],
      [("Proteins help the body to...", "grow and repair", ["only hide", "only sleep", "only run"], "Beans, fish."),
       ("Germs grow fastest in...", "warm, wet food", ["dry, cold food", "frozen food", "dry maize only"], "That is why we dry and cool."),
       ("Which food is preserved by drying?", "dried fish", ["fresh fish", "fresh banana", "fresh egg"], "Drying removes water."),
       ("Cooked food should be...", "covered", ["left in the sun", "left open", "mixed with raw meat"], "To protect it."),
       ("Preserving food means...", "keeping it from going bad", ["making it bad", "cooking it only", "burying it"], "Preservation.")],
      [HEALTH, "Safe-keeping times and temperatures are not given; a food-safety expert may add them."])

fig = table([["Disease", "Spread by", "Prevention"], ["malaria", "mosquito bite", "nets, no stagnant water"], ["cholera", "dirty water and food", "safe water, clean toilets"], ["typhoid", "dirty food or water", "hygiene, safe food"], ["common cold", "germs in the air", "cover cough, wash hands"]], [90, 140, 150], rh=30, size=12)
build(ch, "disease-prevention", "Germs, disease prevention and simple first aid", 35,
      ["Say what germs are and how they spread.", "Name ways of preventing common diseases.", "Know the basic first aid for a small cut or a burn and when to call an adult."],
      [("key", "definition", "Germs and disease", "**Germs** are tiny living things (bacteria, viruses and other parasites) that can make us ill. They spread through **dirty water and food**, the **air** (coughs and sneezes), **touching** and **insect bites**. **Malaria** is spread by mosquitoes; **cholera and typhoid** by dirty water and food; the **common cold** by coughs and sneezes."),
       ("fig", fig, "Some diseases and how to prevent them.", "A table with four diseases: malaria spread by mosquito bite; cholera spread by dirty water and food; typhoid spread by dirty food or water; the common cold spread by germs in the air, with the prevention of each."),
       ("key", "retenir", "Prevention", "**Wash hands** with soap, drink **safe water**, **cover coughs**, use a **toilet or latrine** and keep it clean, sleep under a **mosquito net**, remove **stagnant water**, and keep **vaccination** appointments (vaccines protect against several diseases, as advised by health workers). A healthy diet and sleep help the body to fight germs."),
       ("key", "attention", "Basic first aid", "For a **small cut**: wash your hands, rinse the cut with clean water and cover it with a clean cloth or plaster. For a **burn**: put the burnt area under **cool running water** for a few minutes; do not put oil or toothpaste on it. For anything serious (heavy bleeding, a broken bone, a bad burn, a snake bite) **call an adult and take the person to a health centre at once**."),
       ("key", "pieges", "Common mistakes", "- Thinking that diseases are caused by a curse or by the weather alone.\n- Treating a serious injury at home instead of going to a health worker.\n- Sharing cups and plates with a sick person.\n- Stopping a vaccination programme because the child feels well.")],
      [("ex", "Example 1", "A family has diarrhoea after drinking water from a stream. What is the likely cause and what should they do?", ["Stream water may carry germs such as those of cholera or typhoid.", "They should go to a health centre and, in future, boil, filter or treat the water."], "Germs in the unsafe water; seek health care and use only safe water.", None),
       ("ex", "Example 2", "Name two ways of preventing malaria.", ["Mosquitoes carry malaria, so keep them away from people.", "Sleep under a net and remove stagnant water."], "Sleep under a mosquito net; remove stagnant water.", None)],
      [M("application", "Cholera is spread by...", "dirty water and food", ["a mosquito bite", "the Sun", "the wind only"], "Poor hygiene."),
       M("application", "What should you do first for a small cut?", "rinse it with clean water", ["rub it with soil", "put oil on it", "leave it open and dirty"], "Clean it first."),
       M("application", "Which helps to prevent the common cold from spreading?", "covering your cough", ["sharing handkerchiefs", "spitting on the floor", "eating mango"], "It stops germs in the air."),
       TF("approfondissement", "You should put oil on a burn.", False, "Use cool running water and seek help for a bad burn."),
       MA("approfondissement", "Match each disease with a way to prevent it.", [("malaria", "sleep under a mosquito net"), ("cholera", "drink safe water"), ("typhoid", "wash hands and food"), ("common cold", "cover coughs and sneezes")], "Prevention depends on how germs spread."),
       O("A younger pupil cuts his finger on a tin at school. Explain in 4 sentences what you would do and who you would tell.",
         "I would tell the teacher at once. I would wash my hands and rinse the cut with clean water. Then I would cover it with a clean cloth or plaster. If the cut is deep or keeps bleeding, the teacher should take him to the health centre.",
         "Marks (4): tells an adult (1); washes with clean water (1); covers the cut (1); goes to a health worker if it is serious (1). No unsafe advice such as soil, oil or spit.", tier="examen", points=4, difficulty=2)],
      [("Malaria is spread by...", "mosquitoes", ["flies only", "shoes", "wind"], "The bite of an infected mosquito."),
       ("To prevent cholera, we should...", "drink safe water and wash hands", ["drink from the stream", "share dirty cups", "leave rubbish near the well"], "Hygiene."),
       ("A burn should be put under...", "cool running water", ["hot oil", "toothpaste", "soil"], "To cool it."),
       ("Vaccines are given to...", "protect us from diseases", ["make us sick", "give energy", "grow taller"], "As advised by health workers."),
       ("The common cold is spread by...", "germs in coughs and sneezes", ["mosquitoes", "rain only", "sunlight"], "So cover your cough.")],
      [HEALTH, "First aid advice (cool water for a burn, rinse a cut) is the standard conservative advice and must be confirmed by a first aider; no medicines are named."])

# ===================================================== 3. soil, water, weather
ch = p.chapter("earth", "Soil, water and weather", REF)

fig = table([["Method", "What it does"], ["planting trees and grass", "roots hold the soil"], ["terraces, planting across", "slow the water down"], ["mulching with leaves", "covers the soil"], ["manure and compost", "add humus and food"], ["crop rotation and fallow", "let the soil recover"]], [200, 180], rh=28, size=12)
build(ch, "soil-conservation", "Soil fertility and conservation", 30,
      ["Say what makes soil fertile.", "Explain how farmers improve soil.", "Describe ways of stopping erosion."],
      [("key", "definition", "Fertile soil", "A **fertile** soil has plenty of **humus** (from rotted plants and animals), the right amount of water and air, and **minerals**. Earthworms and other small animals help to mix the soil. Farming without care can make the soil **poor**: crops use up minerals and rain washes away the top soil."),
       ("fig", fig, "Ways of conserving soil.", "A table listing five ways of conserving soil: planting trees and grass, terraces and planting across, mulching with leaves, manure and compost, crop rotation and fallow, with what each does."),
       ("key", "retenir", "Looking after soil", "Farmers improve soil with **manure** and **compost** (rotted plant waste). **Crop rotation** means growing different crops in turn, such as maize then beans. **Fallow** means letting land rest. **Mulching** covers the soil with leaves. **Terraces** on hills and planting **across** a slope slow the water. Chemical fertilisers can help, but they must be used carefully."),
       ("key", "pieges", "Common mistakes", "- Burning the land every year: it kills the small animals and removes humus.\n- Planting the same crop on the same land for years.\n- Ploughing straight down a slope.\n- Thinking that fertiliser is a replacement for taking care of the soil.")],
      [("ex", "Example 1", "Why do farmers grow beans after maize on the same field?", ["Different crops use different minerals; beans also help to put nitrogen back in the soil.", "This is crop rotation, and it keeps the soil fertile."], "Crop rotation keeps the soil fertile.", None),
       ("ex", "Example 2", "A farmer in the Bamenda highlands ploughs down the slope and soil is washed away. What should he do?", ["He should plant across the slope or make terraces.", "He can also plant grass and trees on the steepest parts."], "Plant across the slope or build terraces, and cover the soil.", None)],
      [M("application", "What is humus?", "rotted plants and animals in the soil", ["sand", "stones", "plastic"], "It makes soil rich."),
       M("application", "Which helps to keep the soil fertile?", "compost", ["burning every year", "cutting all trees", "ploughing down the slope"], "Compost adds humus."),
       M("application", "Crop rotation means...", "growing different crops in turn", ["growing the same crop every year", "leaving no crop", "cutting trees"], "Maize, then beans."),
       TF("approfondissement", "Mulching protects the soil from heavy rain.", True, "Leaves cover the ground."),
       MA("approfondissement", "Match each method with its purpose.", [("terraces", "slow down running water"), ("compost", "add food and humus"), ("fallow", "let the land rest"), ("trees", "roots hold the soil")], "Each method protects the soil."),
       P("A family farms a hill. For years they planted maize only, burned the stalks and ploughed down the slope. Now the crops are small and the soil is washed into the stream.",
         [PM("Which practice makes the soil poor?", "growing only maize and burning the stalks", ["adding compost", "mulching", "crop rotation"], "It uses up and loses humus."),
          PM("Which change would help most?", "terraces, compost and rotating crops", ["more burning", "ploughing down the slope", "cutting remaining trees"], "They protect and feed the soil."),
          PM("What is happening to the soil on the slope?", "erosion", ["germination", "condensation", "evaporation"], "Rain carries it away.", points=2)])],
      [("Fertile soil has plenty of...", "humus", ["plastic", "salt only", "stones only"], "Rotted plants and animals."),
       ("Fallow means...", "resting the land", ["burning the land", "planting twice", "watering daily"], "To let the soil recover."),
       ("A way to cover the soil is...", "mulching", ["burning", "ploughing downhill", "cutting trees"], "Leaves cover and protect."),
       ("Crop rotation helps by...", "using different minerals each year", ["using the same minerals", "causing erosion", "removing humus"], "Different crops take different things."),
       ("Terraces are used on...", "slopes", ["flat deserts", "the sea", "roofs"], "They slow water on hills.")],
      ["Nitrogen fixing by beans is only hinted; check the level of detail expected in Class 5."])

fig = flow(["dirty water", "let it settle", "filter it", "boil or treat it", "safe water"], size=12)
build(ch, "water-pollution", "Clean water, pollution and purification", 30,
      ["Name causes and effects of water pollution.", "Describe the steps for making water safe.", "Explain why we must protect water sources."],
      [("key", "definition", "Water pollution", "Water is **polluted** when harmful things get into it: **rubbish**, **human and animal waste**, **chemicals** from factories and farms, and **oil**. Polluted water can carry germs that cause **cholera, typhoid and diarrhoea**, kills fish and plants and makes water useless for drinking."),
       ("fig", fig, "Steps for making water safe.", "Five boxes joined by arrows from top to bottom: dirty water, let it settle, filter it, boil or treat it, safe water."),
       ("key", "methode", "Making water safe", "1. **Settle**: leave the water in a container so heavy dirt sinks (**sedimentation**).\n2. **Filter**: pour it through clean cloth or a sand filter to remove small dirt.\n3. **Boil** it, or use a water-treatment method recommended by health workers, to kill germs. Keep treated water in a **clean, covered** container."),
       ("key", "pieges", "Common mistakes", "- Thinking that clear water is safe: germs are too small to see.\n- Using the same bucket for dirty things and for drinking water.\n- Washing clothes or throwing rubbish where people draw their drinking water.\n- Boiling dirty water and then pouring it back into a dirty container.")],
      [("ex", "Example 1", "Put in order: boil the water, let the dirt settle, filter it.", ["First let heavy dirt settle, then filter out smaller dirt.", "Boil last to kill the germs."], "Settle, filter, boil.", fig),
       ("ex", "Example 2", "A stream is used by a village for drinking and for washing clothes. Suggest a way to protect it.", ["Wash clothes and animals downstream or away from the stream.", "Keep rubbish away and protect the spring."], "Wash away from the drinking place, keep rubbish out, and protect the source.", None)],
      [M("application", "Which is a cause of water pollution?", "throwing rubbish in a river", ["planting trees by the river", "boiling water", "covering a well"], "Rubbish pollutes."),
       M("application", "Which step comes first when purifying water?", "letting the dirt settle", ["boiling", "drinking", "freezing"], "Sedimentation first."),
       M("application", "Boiling water helps because it...", "kills germs", ["adds salt", "makes it cold", "makes it dirty"], "Heat kills germs."),
       TF("approfondissement", "Clear water from a river is always safe to drink.", False, "It can still carry germs."),
       MA("approfondissement", "Match each step with its purpose.", [("settle", "heavy dirt sinks"), ("filter", "removes small dirt"), ("boil", "kills germs"), ("cover the container", "keeps the water clean")], "Each step has a purpose."),
       P("A school gets its water from a stream. During the rains the water becomes brown and many pupils have diarrhoea.",
         [PM("What is the likely reason for the diarrhoea?", "germs in polluted water", ["too much sun", "lack of exercise", "bad spelling"], "Brown, polluted water carries germs."),
          PM("What should the school do before pupils drink the water?", "settle, filter and boil it", ["drink it at once", "add rubbish", "add more mud"], "Make it safe."),
          PM("Which action protects the stream?", "keeping rubbish and toilets away from it", ["washing clothes in the stream", "throwing waste in", "cutting trees on the bank"], "Prevent pollution.", points=2)])],
      [("Polluted water can carry germs causing...", "cholera", ["spelling", "football", "sunshine"], "And typhoid."),
       ("Sedimentation means...", "dirt sinks to the bottom", ["water boils", "water evaporates", "water freezes"], "Heavy particles settle."),
       ("A filter...", "removes small dirt", ["kills all germs by itself", "makes the water hot", "adds taste"], "Filters do not always remove germs."),
       ("After treating water, we should keep it in...", "a clean covered container", ["an open dirty bucket", "a muddy hole", "the sun with rubbish"], "To keep it safe."),
       ("Which is not a good thing to put in a river?", "rubbish", ["rain", "clean fish", "stones from the bed"], "It pollutes.")],
      [HEALTH, "Boiling time and treatment products are not specified; a health worker should add the official advice."])

pts = [(6, 22), (9, 25), (12, 30), (15, 31), (18, 27)]
fig = plot(5, 19, 18, 34, curves=[], points=[(x, y, str(y), "red") for x, y in pts],
           segments=[(pts[i][0], pts[i][1], pts[i + 1][0], pts[i + 1][1], "red", False) for i in range(len(pts) - 1)], grid=2, xlabel="hour (24 h clock)", ylabel="°C", w=400, h=260)
assert sum(y for _, y in pts) / len(pts) == 27
build(ch, "weather-instruments", "Weather instruments and weather records", 30,
      ["Name and use simple weather instruments.", "Record and read a temperature graph.", "Tell weather from climate."],
      [("key", "definition", "Weather instruments", "A **thermometer** measures temperature in °C. A **rain gauge** (a container with a scale) measures rain in **millimetres**. A **wind vane** shows wind direction. An **anemometer** measures wind speed. A **barometer** measures air pressure. Put a thermometer in the **shade**, not in direct sunlight, so that it measures the air."),
       ("fig", fig, "Temperature at five times during one day.", "A graph of temperature against the hour: 22 degrees at 6, 25 at 9, 30 at 12, 31 at 15 and 27 at 18, joined by lines."),
       ("key", "retenir", "Weather and climate", "**Weather** changes from hour to hour. **Climate** is the average weather over many years. By recording the weather every day at the same time, pupils can find the **mean temperature**, the **total rainfall** and the **most common type of weather**. A table or graph makes the pattern easy to see."),
       ("key", "pieges", "Common mistakes", "- Putting the thermometer in the Sun.\n- Reading the rain gauge while it is tilted.\n- Saying that one rainy day is a rainy climate.\n- Forgetting the units: °C and mm.")],
      [("ex", "Example 1", "From the graph: what was the highest temperature and at what time?", ["Find the highest point of the line: 31 °C.", "It is at the 15 hour mark (3 p.m.)."], "31 °C at 15:00", fig),
       ("ex", "Example 2", "Find the mean of the five temperatures: 22, 25, 30, 31, 27.", ["Add: 22 + 25 + 30 + 31 + 27 = 135.", "Divide by 5: 135 ÷ 5 = 27."], "27 °C", None)],
      [M("application", "Which instrument measures rain?", "a rain gauge", ["a thermometer", "a wind vane", "a ruler"], "In millimetres."),
       M("application", "Which instrument shows wind direction?", "a wind vane", ["a thermometer", "a rain gauge", "a clock"], "It points into the wind."),
       N("application", "Rain in three days was 12 mm, 8 mm and 10 mm. What is the mean rain per day?", 10, "(12 + 8 + 10) ÷ 3 = 10.", unit="mm"),
       TF("approfondissement", "A thermometer should be put in direct sunlight to measure the air temperature.", False, "Put it in the shade."),
       N("approfondissement", "At noon it was 30 °C and at 6 a.m. 22 °C. What was the rise?", 8, "30 − 22 = 8.", unit="°C"),
       P("A class records the temperature at noon each day for a week: 29, 31, 30, 28, 32, 31, 29 degrees Celsius.",
         [PN("What is the total?", 29 + 31 + 30 + 28 + 32 + 31 + 29, "The sum of the 7 values is 210.", unit="°C"),
          PN("What is the mean temperature?", 30, "210 ÷ 7 = 30.", unit="°C"),
          PN("What is the range (highest minus lowest)?", 4, "32 − 28 = 4.", unit="°C", points=2)])],
      [("A thermometer measures...", "temperature", ["rain", "wind speed", "air pressure only"], "In °C."),
       ("Rain is measured in...", "millimetres", ["litres only", "grams", "degrees"], "A rain gauge scale."),
       ("A wind vane shows...", "wind direction", ["rain amount", "the temperature", "the time"], "It turns with the wind."),
       ("The weather over many years is the...", "climate", ["storm", "forecast", "shadow"], "Long-term pattern."),
       ("The mean of 20, 30 and 40 is...", "30", ["90", "20", "40"], "90 ÷ 3.")],
      ["Temperature data for the graph is invented for teaching."])

# ===================================================== 4. matter and energy
ch = p.chapter("matter-energy", "Matter, energy, electricity and forces", REF)

fig = table([["Method", "Separates", "Example"], ["sieving", "big from small pieces", "stones from rice"], ["filtering", "solid from liquid", "sand from water"], ["evaporation", "dissolved solid from a liquid", "salt from sea water"], ["magnet", "iron from other things", "nails from sand"], ["decanting", "liquid from settled solid", "clear water from mud"]], [90, 150, 140], rh=28, size=12)
build(ch, "mixtures-changes", "Mixtures, solutions and changes in materials", 35,
      ["Say what a mixture and a solution are.", "Choose a way of separating a mixture.", "Tell physical changes from chemical changes."],
      [("key", "definition", "Mixtures and solutions", "A **mixture** has two or more materials together that are not joined chemically (sand and water, rice and stones). A **solution** forms when a **solute** dissolves in a **solvent**: sugar (solute) dissolves in water (solvent) to make a sugar solution. A dissolved solid cannot be seen but is still there: taste the water or let it evaporate."),
       ("fig", fig, "Ways of separating mixtures.", "A table of methods: sieving separates big from small pieces; filtering separates solid from liquid; evaporation separates a dissolved solid from a liquid; a magnet separates iron; decanting separates a liquid from a settled solid; each with an example."),
       ("key", "retenir", "Changes", "In a **physical change** no new substance is made and it can often be reversed: melting ice, dissolving sugar, cutting paper. In a **chemical change** a **new substance** is formed and it cannot be easily reversed: **burning wood, rusting iron, cooking an egg, baking bread, milk going sour**."),
       ("key", "pieges", "Common mistakes", "- Thinking that sugar disappears when it dissolves.\n- Using filtering to separate salt that is dissolved in water: the salt passes through the filter.\n- Thinking that all changes can be reversed.\n- Confusing melting with dissolving.")],
      [("ex", "Example 1", "How can you get salt from sea water?", ["The salt is dissolved, so a filter cannot remove it.", "Heat the water so that it evaporates: the salt is left behind."], "By evaporating the water.", fig),
       ("ex", "Example 2", "Is burning a piece of wood a physical or a chemical change? Why?", ["Burning makes new substances (ash, smoke) and the wood cannot be got back.", "So it is a chemical change."], "A chemical change: new substances are formed.", None)],
      [M("application", "How can you separate stones from rice?", "sieving or picking", ["boiling", "freezing", "evaporating"], "The pieces have different sizes."),
       M("application", "Which is a chemical change?", "an egg being cooked", ["ice melting", "sugar dissolving", "paper being cut"], "A new substance forms."),
       M("application", "In a sugar solution, the sugar is the...", "solute", ["solvent", "filter", "gas"], "It dissolves in the water."),
       TF("approfondissement", "Dissolving sugar in water is a physical change.", True, "The sugar can be got back by evaporation."),
       MA("approfondissement", "Match each mixture with the best separating method.", [("sand and water", "filtering"), ("iron nails and sand", "a magnet"), ("salt dissolved in water", "evaporation"), ("pebbles and flour", "sieving")], "Choose by the properties."),
       P("Ako has a bowl of muddy water with a spoonful of salt dissolved in it. He wants clean water and salt.",
         [PM("Which method removes the mud?", "settling and filtering", ["evaporating", "magnet", "boiling first"], "Mud is undissolved."),
          PM("Which method then gets the salt?", "evaporating the clear water", ["filtering again", "sieving", "decanting"], "Salt is dissolved."),
          PM("Is evaporation a physical change?", "yes", ["no, it is chemical", "it is burning", "it is rusting"], "No new substance forms.", points=2)])],
      [("A mixture is...", "two or more materials together", ["a single material", "a new gas only", "a magnet"], "Sand and water."),
       ("The substance that dissolves is the...", "solute", ["solvent", "filter", "sieve"], "Sugar in water."),
       ("Rusting is a...", "chemical change", ["physical change", "melting", "freezing"], "A new substance forms."),
       ("Which separates iron from sand?", "a magnet", ["a thermometer", "boiling", "a mirror"], "Iron is magnetic."),
       ("To get salt from sea water we...", "evaporate the water", ["filter it", "freeze it", "stir it"], "Salt remains.")],
      ["Chemical vs physical change is introduced with everyday examples only."])

fig = table([["Form of energy", "Example"], ["heat", "a cooking fire"], ["light", "the Sun, a torch"], ["sound", "a drum"], ["electrical", "mains, cells"], ["chemical (stored)", "food, firewood, fuel"], ["movement", "a running child, wind"]], [150, 200], rh=28, size=13)
build(ch, "energy", "Energy: forms, sources and changes", 30,
      ["Name forms of energy.", "Separate renewable and non-renewable sources.", "Describe simple energy changes."],
      [("key", "definition", "Energy", "**Energy** is what makes things happen: it lets us **work, move, heat and light**. It comes in many **forms**: heat, light, sound, electrical, chemical (stored in food, firewood and fuel) and movement. Energy is never made or lost: it is **changed** from one form into another."),
       ("fig", fig, "Forms of energy and examples.", "A table with forms of energy: heat, light, sound, electrical, chemical stored in food and fuel, and movement, each with an example."),
       ("key", "retenir", "Sources and changes", "**Renewable** sources do not run out: the **Sun**, **wind**, **flowing water** (hydroelectric power from dams) and wood if trees are replanted. **Non-renewable** sources run out one day: **petroleum**, **coal** and **gas**. Energy changes: in a torch, **chemical** energy in the cell becomes **electrical** and then **light** and a little **heat**; our body changes the chemical energy of food into **movement** and **heat**."),
       ("key", "pieges", "Common mistakes", "- Saying that energy is used up: it changes form.\n- Thinking that firewood is a never-ending source if forests are not replanted.\n- Saying that the Sun is non-renewable.\n- Wasting energy by leaving lights and appliances on.")],
      [("ex", "Example 1", "Name the energy changes in a bulb that is lit by a cell.", ["The cell has chemical energy which becomes electrical energy.", "The bulb changes it into light and some heat."], "chemical → electrical → light and heat.", None),
       ("ex", "Example 2", "Is petroleum a renewable source? Give a reason.", ["Petroleum took millions of years to form.", "We use it much faster than nature can make it, so it will run out."], "No: it is non-renewable, because it will run out.", None)],
      [M("application", "Which is a renewable source of energy?", "the Sun", ["petroleum", "coal", "natural gas"], "The Sun keeps shining."),
       M("application", "Food stores which form of energy?", "chemical energy", ["sound energy", "light energy", "none"], "We get energy from it."),
       M("application", "What energy change happens in a radio on a battery?", "electrical to sound", ["sound to light", "light to heat", "heat to chemical"], "A speaker makes sound."),
       TF("approfondissement", "Energy can be changed from one form to another.", True, "It is never lost, only changed."),
       MA("approfondissement", "Match each source with its type.", [("sunlight", "renewable: shines every day"), ("wind", "renewable: blows again and again"), ("petroleum", "non-renewable: will run out"), ("coal", "non-renewable: took millions of years to form")], "Renewable sources do not run out."),
       P("A village gets electricity from a small dam on a river. The water turns a machine that makes electricity. In the evening a family uses it to light a bulb and listen to a radio.",
         [PM("What type of source is flowing water?", "renewable", ["non-renewable", "chemical", "none"], "The rain keeps filling the river."),
          PM("Into which form does the electricity change in the bulb?", "light (and some heat)", ["sound", "chemical", "movement only"], "The bulb lights."),
          PM("Which form is produced by the radio?", "sound", ["light", "heat only", "chemical"], "The speaker vibrates.", points=2)])],
      [("A renewable source of energy is...", "wind", ["coal", "petroleum", "gas"], "It does not run out."),
       ("Energy is...", "changed from one form to another", ["destroyed when used", "only made by cells", "never moves"], "Conservation of energy."),
       ("Stored energy in food is...", "chemical energy", ["sound", "wind", "light"], "It is released in the body."),
       ("A non-renewable source is...", "petroleum", ["the Sun", "wind", "water power"], "It will run out."),
       ("A way to save energy is to...", "switch off lights not in use", ["leave lights on", "open the fridge for long", "waste water"], "Reduce waste.")],
      ["Energy forms listed in a simple way; check the terms used in the official syllabus."])

fig = table([["Heat moves by", "In", "Example"], ["conduction", "solids", "metal spoon in hot soup"], ["convection", "liquids and gases", "warm air rises, water boils"], ["radiation", "through space", "the Sun warms the Earth"]], [100, 110, 170], rh=34, size=12)
fig2 = shapes([LINE(20, 150, 380, 150, width=3), LINE(60, 40, 200, 150, color="orange", width=3, arrow="end"), LINE(200, 150, 340, 40, color="orange", width=3, arrow="end"), LINE(200, 150, 200, 55, dash=True, color="grey"),
               T(130, 80, "light in", 12, bold=True, anchor="end"), T(280, 80, "light out", 12, bold=True, anchor="start"), T(200, 175, "mirror", 13, bold=True), T(210, 50, "normal", 11, anchor="start")], 400, 195)
build(ch, "heat-light", "Heat transfer, mirrors and light", 35,
      ["Name the three ways in which heat moves.", "Say how a mirror reflects light.", "Say what happens when white light passes through water drops."],
      [("key", "definition", "Heat transfer", "**Conduction**: heat passes through **solids**, especially metals (a metal spoon in hot soup). **Convection**: heat moves in **liquids and gases** because warm liquid or air **rises** and cool liquid or air sinks (boiling water, a rising smoke). **Radiation**: heat travels from the **Sun** through empty space. **Insulators** such as wood, plastic, air and wool slow down heat flow."),
       ("fig", fig, "How heat moves.", "A table with conduction in solids, convection in liquids and gases, and radiation through space, with examples."),
       ("key", "definition", "Reflection and colours", "A **mirror reflects** light: the angle at which light **hits** the mirror equals the angle at which it **bounces off**. **White light** is a mixture of colours: a **rainbow** forms when sunlight passes through raindrops and splits into the colours red, orange, yellow, green, blue, indigo and violet."),
       ("fig", fig2, "Light reflecting from a mirror.", "A flat mirror at the bottom. A ray comes down from the upper left and bounces up to the upper right at the same angle on the other side of the normal line."),
       ("key", "pieges", "Common mistakes", "- Saying that cold flows into a thing: heat flows **out** of hot things.\n- Thinking that a woollen jumper makes heat: it keeps in the body's heat.\n- Looking at the Sun or reflecting sunlight into someone's eyes.\n- Thinking that the rainbow is an object: it is an effect of light and water.")],
      [("ex", "Example 1", "Why does a metal spoon get hot at the end when it stands in a hot pot?", ["Metals conduct heat well.", "Heat passes along the spoon from the hot soup to the handle."], "By conduction.", None),
       ("ex", "Example 2", "A ray of light hits a mirror at an angle of 40° to the normal. What is the angle of the reflected ray?", ["The angle of reflection equals the angle of incidence.", "So the reflected ray makes 40° with the normal."], "40°", fig2)],
      [M("application", "How does heat travel from the Sun to the Earth?", "radiation", ["conduction", "convection", "reflection"], "Through space."),
       M("application", "Which is a good insulator?", "wool", ["copper", "iron", "aluminium"], "It traps air."),
       N("application", "The angle of incidence of a ray is 35° to the normal. What is the angle of the reflected ray?", 35, "They are equal.", unit="°"),
       TF("approfondissement", "Warm air rises.", True, "This is convection."),
       MA("approfondissement", "Match each example with the way heat moves.", [("a metal spoon in a hot pot", "conduction"), ("warm air rising from a fire", "convection"), ("heat from the Sun", "radiation"), ("a wool blanket", "insulation")], "Think about the material."),
       P("In a kitchen in Garoua, a pot of water boils on a fire. The metal handle is too hot to touch and warm air rises above the pot.",
         [PM("Why is the handle hot?", "metal conducts heat", ["metal radiates cold", "air is cold", "water is hot only"], "Conduction along the metal."),
          PM("What moves the warm air upward?", "convection", ["conduction", "reflection", "magnetism"], "Warm air rises."),
          PM("How can the cook hold the pot safely?", "use a cloth or an insulating handle", ["use bare hands", "pour water on it", "use a metal spoon"], "Insulators protect the hand.", points=2)])],
      [("Heat moves through solids by...", "conduction", ["convection", "radiation", "reflection"], "Metals are good conductors."),
       ("In reflection, the angle of incidence...", "equals the angle of reflection", ["is double it", "is smaller always", "is not related"], "Law of reflection."),
       ("A rainbow shows that white light is...", "a mixture of colours", ["only red", "dark", "a sound"], "It splits into colours."),
       ("A good insulator is...", "wood", ["copper", "iron", "silver"], "It slows heat flow."),
       ("Warm air...", "rises", ["sinks always", "turns into water", "stays still"], "It is lighter than cool air.")],
      ["Light and heat statements are standard; angle values are invented examples."])

fig = shapes([RECT(40, 100, 30, 40, fill="lightyellow"), T(55, 160, "cell", 12, bold=True), CIRCLE(190, 40, 18, fill="yellow"), CIRCLE(280, 40, 18, fill="yellow"), T(190, 15, "bulb 1", 12, bold=True), T(280, 15, "bulb 2", 12, bold=True),
              LINE(55, 100, 55, 40, width=3), LINE(55, 40, 172, 40, width=3), LINE(208, 40, 262, 40, width=3), LINE(298, 40, 360, 40, width=3), LINE(360, 40, 360, 140, width=3),
              LINE(360, 140, 55, 140, width=3), T(210, 120, "series circuit: one loop", 12, bold=True)], 400, 175)
build(ch, "electricity", "Electricity: series circuits, conductors and safety", 35,
      ["Build and describe a series circuit.", "Say what happens when more bulbs are added.", "Know where electricity comes from and how to be safe."],
      [("key", "definition", "Circuits", "A **circuit** is a complete loop through which electricity flows. In a **series circuit** the parts (cell, switch, bulbs) are in **one loop**. If one bulb breaks, the loop is broken and **all the bulbs go out**. If you add more bulbs to one cell, each bulb is **dimmer**. A **switch** opens or closes the circuit."),
       ("fig", fig, "A series circuit with a cell and two bulbs.", "A single loop of wire with a cell on the left and two bulbs in a row at the top. The note says series circuit: one loop."),
       ("key", "retenir", "Conductors and sources", "**Conductors** (copper, iron, aluminium, graphite) let electricity pass; **insulators** (plastic, rubber, glass, dry wood) do not. Wires are copper covered with plastic for safety. Electricity can come from **cells**, from **generators**, from **solar panels** and from **dams** on rivers such as the Sanaga that drive generators."),
       ("key", "attention", "Safety", "**Never** touch bare wires or sockets. **Never** use electrical things with wet hands or near water. Do not pull a plug by its cable. Keep away from fallen cables and **tell an adult**. At school use only **small cells** and a teacher present, never the mains."),
       ("key", "pieges", "Common mistakes", "- Thinking that electricity is 'used up' by a bulb: the energy changes into light and heat, the current goes round.\n- Believing that more cells always means a dimmer bulb: more cells make it brighter, more bulbs make each dimmer.\n- Using a wet hand to switch on a light.\n- Thinking that all metals are safe to touch near power lines.")],
      [("ex", "Example 1", "In a series circuit with two bulbs, one bulb breaks. What happens to the other one?", ["The break stops the flow round the single loop.", "The other bulb also goes out."], "It goes out, because the circuit is broken.", None),
       ("ex", "Example 2", "A circuit with one cell and one bulb has a second bulb added in series. What happens to the brightness?", ["The same energy from the cell now lights two bulbs.", "Each bulb is dimmer."], "Each bulb is dimmer.", fig)],
      [M("application", "Which material is a good conductor of electricity?", "copper", ["rubber", "plastic", "dry wood"], "Metals conduct."),
       M("application", "What does a switch do?", "opens or closes the circuit", ["makes electricity", "makes light only", "cools the wire"], "It controls the flow."),
       M("application", "Why are wires covered in plastic?", "plastic is an insulator, so it is safe", ["plastic makes the wire hotter", "plastic is a conductor", "it makes the cell stronger"], "Insulation protects people."),
       TF("approfondissement", "In a series circuit, if one bulb breaks all the bulbs go out.", True, "The loop is broken."),
       MA("approfondissement", "Match each material with a type.", [("copper", "conductor"), ("rubber", "insulator"), ("sunlight on a panel", "a source of electricity (solar)"), ("a dam", "a source of electricity (water power)")], "Properties and sources."),
       P("Neba builds a series circuit with one cell and three bulbs. The bulbs are dim. His sister says he should use mains electricity to make them brighter.",
         [PM("Why are the bulbs dim?", "three bulbs share the energy of one cell", ["the wire is too long", "the bulbs are cold", "the cell is full"], "More bulbs mean dimmer bulbs."),
          PM("How can Neba make them brighter safely?", "use fewer bulbs or add another small cell", ["connect them to the mains", "use a wet hand", "use a bare wire in a socket"], "Safe changes only."),
          PM("Why is her idea dangerous?", "mains electricity can hurt or kill", ["mains is cold", "it is slow", "it does not light bulbs"], "Never use mains for experiments.", points=2)])],
      [("A series circuit has...", "one loop", ["two loops", "no wires", "no cell"], "All parts in a single loop."),
       ("An insulator...", "does not let electricity pass", ["lets electricity pass", "makes electricity", "is always metal"], "Plastic, rubber."),
       ("Which is an electricity source?", "a cell", ["a stone", "a stick", "a cloth"], "Also generators and solar panels."),
       ("Which is a safety rule?", "never touch sockets with wet hands", ["touch bare wires", "pull plugs by the cable", "use mains for experiments"], "Water and electricity are dangerous."),
       ("If a bulb breaks in a series circuit, the other bulbs...", "go out", ["shine brighter", "stay the same", "turn blue"], "The loop is broken.")],
      ["Safety rules and experiments must be supervised by a teacher; a parallel circuit is not covered."])

fig = shapes([POLY([180, 150, 210, 150, 195, 125], fill="brown"), RECT(60, 115, 280, 10, fill="lightorange", width=2), RECT(70, 85, 40, 30, fill="grey"), T(90, 70, "load", 13, bold=True),
              LINE(320, 60, 320, 108, color="red", width=3, arrow="end"), T(320, 45, "effort", 13, bold=True, color="red"), T(195, 175, "fulcrum", 13, bold=True)], 400, 195)
build(ch, "forces-machines", "Forces and simple machines", 35,
      ["Say what a force is, and give examples of friction and gravity.", "Name the simple machines and their uses.", "Say how a lever makes work easier."],
      [("key", "definition", "Forces", "A **force** is a **push or a pull**. It can start or stop movement, change speed or direction, or change shape. Forces are measured in **newtons (N)**. **Friction** is a force that **slows** things down where surfaces rub together; rough surfaces have more friction than smooth ones. **Gravity** pulls everything **down** towards the Earth and gives things their **weight**."),
       ("key", "definition", "Simple machines", "A **machine** makes a job easier. **Simple machines** are the **lever** (see-saw, wheelbarrow, scissors, a spade), **pulley** (raising a bucket or a flag), **inclined plane** (a ramp), **wheel and axle** (a bicycle wheel), **screw** and **wedge** (an axe, a knife). They let us use a **smaller force** over a **longer distance**, or change its direction."),
       ("fig", fig, "A lever: effort, fulcrum and load.", "A beam resting on a triangular pivot called the fulcrum. A heavy load is on the left and a downward arrow for the effort is on the right."),
       ("key", "pieges", "Common mistakes", "- Thinking that heavier objects always fall faster: without air resistance they fall together.\n- Thinking that a machine reduces the total work: it only makes the force smaller or changes its direction.\n- Confusing mass (kg) with weight (a force in N).\n- Thinking that friction is always bad: without it we could not walk or stop a bicycle.")],
      [("ex", "Example 1", "Why do we put oil on a bicycle chain?", ["Oil makes the surfaces smoother.", "So friction is smaller and the chain moves easily."], "To reduce friction.", None),
       ("ex", "Example 2", "A heavy drum must be put on a lorry 1 m high. Which simple machine helps?", ["A ramp lets the drum be pushed up gradually.", "It is an inclined plane."], "An inclined plane (a ramp).", None)],
      [M("application", "A force is a...", "push or a pull", ["colour", "sound only", "shadow"], "Forces push or pull."),
       M("application", "Which is a lever?", "a see-saw", ["a ramp", "a screw", "a wheel only"], "It turns on a fulcrum."),
       M("application", "Which force pulls things down to the Earth?", "gravity", ["friction", "magnetism only", "heat"], "It gives weight."),
       TF("approfondissement", "A smooth surface has more friction than a rough surface.", False, "A rough surface has more friction."),
       MA("approfondissement", "Match each tool with its simple machine.", [("wheelbarrow", "lever"), ("ramp", "inclined plane"), ("flag rope", "pulley"), ("axe", "wedge")], "Learn the machine types."),
       P("Bih has to lift a heavy sack onto a platform that is 1 metre high. She tries lifting it by hand but it is too heavy. Then she lays a long plank as a ramp and pushes the sack up it.",
         [PM("Which simple machine is the plank?", "an inclined plane", ["a pulley", "a lever", "a screw"], "A slope."),
          PM("What does the ramp do?", "makes the force smaller over a longer distance", ["makes the sack lighter", "makes the work disappear", "adds gravity"], "A longer distance, a smaller push."),
          PM("What force makes the sack hard to push on a rough plank?", "friction", ["gravity only", "magnetism", "sound"], "Rough surfaces rub.", points=2)])],
      [("Forces are measured in...", "newtons", ["metres", "litres", "seconds"], "Symbol N."),
       ("Gravity pulls things...", "downwards", ["upwards", "sideways", "nowhere"], "Towards the Earth."),
       ("A wheelbarrow is an example of a...", "lever", ["pulley", "screw", "wedge"], "It has a fulcrum at the wheel."),
       ("Friction...", "slows things down", ["speeds them up always", "makes sound only", "does not exist"], "It acts where surfaces rub."),
       ("A ramp is an...", "inclined plane", ["pulley", "lever", "axle"], "A sloping surface.")],
      ["Mass and weight are only mentioned briefly; whether the newton is taught at Class 5 is to be checked."])

# ===================================================== 5. environment and technology
ch = p.chapter("environment", "Environment and technology", REF)

fig = boxes(["Reduce: use less, waste less", "Reuse: use things again", "Recycle: make new things from old ones", "Rot: compost plant waste"], size=14)
build(ch, "environment", "Protecting the environment", 30,
      ["Name human activities that harm the environment.", "Explain reduce, reuse and recycle.", "Say why forests and wildlife must be protected."],
      [("key", "definition", "Harm to the environment", "The **environment** is everything around us: air, water, soil, plants and animals. People can harm it by **cutting forests** without replanting (**deforestation**), by **burning** rubbish and forests, by **dumping rubbish** and plastic, by **polluting** water and air, and by **over-hunting and over-fishing**. Plastic bags block drains and take a very long time to rot."),
       ("fig", fig, "Four ways to look after the environment.", "Four boxes: reduce, reuse, recycle and compost (rot), each with a short meaning."),
       ("key", "retenir", "What we can do", "**Reduce** the waste we make; **reuse** bottles, bags and tins; **recycle** paper, glass, metal and some plastics; **compost** plant waste. **Plant trees** for shade, rain, fuel and homes for animals. Keep **forests and parks** safe because they shelter wildlife such as birds, monkeys and elephants and help to keep rain and soil. Obey rules about hunting and about **protected areas**."),
       ("key", "pieges", "Common mistakes", "- Throwing rubbish in drains or rivers.\n- Cutting trees without planting new ones.\n- Thinking that one person's small rubbish does not matter.\n- Burning plastic: the smoke is harmful to people.")],
      [("ex", "Example 1", "Give two ways to reuse an old plastic bottle.", ["Think of safe, useful ideas.", "Use it as a flower pot or to store dry beans (cleaned first)."], "As a plant pot or for storing dry goods.", None),
       ("ex", "Example 2", "Why is deforestation a problem?", ["Trees give shelter to animals, hold the soil and give us rain and shade.", "When forests are cut, animals lose homes and soil is washed away."], "Animals lose their homes and soil is eroded.", None)],
      [M("application", "What does 'reuse' mean?", "to use something again", ["to throw it away", "to burn it", "to bury it"], "Use again."),
       M("application", "Which harms the environment?", "throwing rubbish in a river", ["planting trees", "composting", "recycling paper"], "It pollutes."),
       M("application", "Which can be made into new paper?", "old paper", ["glass bottles", "stones", "clean water"], "Recycling."),
       TF("approfondissement", "Planting trees helps the environment.", True, "Trees give shade, hold soil and shelter animals."),
       MA("approfondissement", "Match each action with the 3 R's.", [("using a bottle again", "reuse"), ("making less rubbish", "reduce"), ("turning old paper into new paper", "recycle"), ("planting a tree", "protecting the forest")], "Reduce, reuse, recycle."),
       O("Write four sentences telling your class what each pupil can do to keep the school compound clean.",
         "Put rubbish in the bins and never on the ground. Reuse paper and bottles when you can. Plant a flower or a tree in the compound. Tell your friends not to burn plastic.",
         "Marks (4): four practical, correct ideas (1 each); no unsafe suggestions (e.g. burning plastic).", tier="examen", points=4, difficulty=2)],
      [("Deforestation is...", "cutting down forests", ["planting forests", "making rain", "building roads only"], "Large-scale tree cutting."),
       ("The 3 R's are reduce, reuse and...", "recycle", ["rest", "run", "rip"], "Make new things from old."),
       ("Plastic bags are harmful because they...", "block drains and take long to rot", ["feed plants", "make rain", "cool rivers"], "They stay long."),
       ("Which is a good habit?", "putting rubbish in a bin", ["burning plastic", "dumping in rivers", "cutting every tree"], "Keep the place clean."),
       ("Compost is made from...", "rotted plant waste", ["plastic", "glass", "metal"], "It feeds the soil.")],
      ["Environmental facts are general; local examples (protected areas, specific species) should be added by the teacher."])

fig = flow(["Find a need", "Plan and draw", "Make it", "Test it", "Improve it"], size=12)
fig2 = table([["Material", "Properties", "Used for"], ["wood", "strong, burns", "tables, houses"], ["metal", "strong, conducts", "tools, pots, wires"], ["plastic", "light, insulator", "buckets, cables"], ["glass", "see-through, breaks", "windows, bottles"], ["cotton", "soft, absorbs", "clothes, cloth"]], [90, 130, 140], rh=28, size=12)
build(ch, "technology", "Materials and the technology design process", 35,
      ["Choose the right material for a job.", "Name the steps of the design process.", "Plan and evaluate a simple model."],
      [("key", "definition", "Materials", "People choose a material because of its **properties**: wood is strong, metal is strong and conducts heat and electricity, plastic is light and does not conduct, glass is see-through but breaks, cotton is soft and absorbs water. **Technology** is using knowledge and tools to **solve problems**: a water filter, a solar lamp, a charcoal-saving stove, a bicycle."),
       ("fig", fig2, "Materials, their properties and uses.", "A table of five materials: wood, metal, plastic, glass and cotton, with their properties and what each is used for."),
       ("key", "methode", "The design process", "1. **Find a need** (for example: a rainwater collector).\n2. **Plan and draw** a design, and list the materials.\n3. **Make** a model with care and safety.\n4. **Test** it: does it work?\n5. **Improve** it. Always use tools **safely**: have an adult with you for sharp or hot tools."),
       ("fig", fig, "The design process.", "Five boxes joined by arrows from top to bottom: find a need, plan and draw, make it, test it, improve it."),
       ("key", "pieges", "Common mistakes", "- Starting to make without a plan.\n- Choosing a material because it is pretty, not because it fits the job.\n- Skipping the test.\n- Using sharp tools without an adult.")],
      [("ex", "Example 1", "Which material is best for the handle of a cooking pot: metal or wood? Why?", ["The handle must not get too hot to touch.", "Wood does not conduct heat well, so it is best."], "Wood (or plastic): it is an insulator.", None),
       ("ex", "Example 2", "A class wants a model rainwater collector. Put the steps in order: test it, make it, plan it, find the need.", ["Start with the need, then plan, then make.", "Test it at the end (and then improve it)."], "Find the need, plan it, make it, test it.", fig)],
      [M("application", "Which material is see-through?", "glass", ["wood", "metal", "cotton"], "It lets light through."),
       M("application", "Which material is a good conductor of electricity?", "metal", ["plastic", "wood", "cotton"], "Wires are copper."),
       M("application", "What is the first step of the design process?", "find a need", ["test", "improve", "sell"], "Know the problem first."),
       TF("approfondissement", "We should test our model before saying it works.", True, "Testing shows the faults."),
       MA("approfondissement", "Match each material with a use.", [("glass", "windows"), ("cotton", "clothes"), ("metal", "cooking pots"), ("plastic", "buckets")], "Match the property to the job."),
       P("A group of pupils wants to build a model water filter using a plastic bottle, sand, gravel and cloth.",
         [PM("What is the need?", "to clean dirty water", ["to make music", "to paint the wall", "to grow plants"], "A filter removes dirt."),
          PM("Why do they choose a clear plastic bottle?", "they can see inside and it is cheap and light", ["it is heavy", "it conducts electricity", "it is dangerous"], "Properties of plastic."),
          PM("What must they do after building the filter?", "test it with muddy water and improve it", ["drink the water at once", "throw it away", "sell it"], "Test and improve; the water must not be drunk without boiling.", points=2)])],
      [("Technology is...", "using knowledge and tools to solve problems", ["a kind of food", "a sport", "a language"], "Making life easier."),
       ("The best material for a window is...", "glass", ["wood", "cotton", "clay"], "See-through."),
       ("In the design process, we test...", "after making it", ["before the plan", "never", "before finding the need"], "Check that it works."),
       ("A plan helps us to...", "know what to make and which materials to use", ["skip the test", "avoid drawing", "waste time"], "Plan first."),
       ("Which should an adult supervise?", "using sharp tools", ["drawing a plan", "writing a list", "reading a book"], "Safety first.")],
      ["Technology examples are suggestions; use locally available materials and keep safety first."])

p.write()
