import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from p13_kit import *
from p13_fig import *

p = newpack("class3-english", "English Language — Class 3", "Class 3", "english",
    "Class 3 English: nouns, verbs and tenses, adjectives, pronouns, adverbs, prepositions, joining words, punctuation, opposites and synonyms, spelling, reading, writing and speaking.",
    REF % "Level II (Class 3) — English Language")
R = p.programRef
NOTE = "Grammar terms and the amount of grammar expected at Class 3 are to be checked against the official syllabus; British spelling is used."

ch = p.chapter("nouns-pronouns", "Nouns and pronouns", R)
lesson(ch, "common-proper-nouns", "Common and proper nouns", ["Tell common and proper nouns apart.", "Write proper nouns with capital letters."],
  [("definition", "Two kinds of noun", "A **common noun** names any person, place or thing: girl, town, river. A **proper noun** names one special person, place or thing: **Ada**, **Douala**, **River Wouri**. A proper noun starts with a **capital letter**."),
   ("retenir", "Days and months", "Days of the week, months and names of countries and languages are proper nouns too: **Monday**, **March**, **Cameroon**, **English**."),
   ("pieges", "Common mistakes", "- Write *Bamenda*, not *bamenda*.\n- Do not use a capital for common nouns in the middle of a sentence: *the town*.\n- *Monday* needs a capital letter.")],
  [("Example 1", "Find the proper noun: The girl lives in Limbe.", ["Girl is a common noun.", "Limbe is a special place. It is a proper noun."], "Limbe", cards(["common: town", "proper: Bamenda", "common: girl", "proper: Ada"], 2, 400, ch=44, size=16)),
   ("Example 2", "Write correctly: we go to church on sunday.", ["Sunday is a day, a proper noun.", "We go to church on Sunday."], "Sunday", None)],
  (cards(["common: river", "proper: River Sanaga", "common: boy", "proper: Kofi"], 2, 400, ch=44, size=16), "Common and proper nouns.", "Four boxes with common and proper nouns."),
  [("m", "Which is a proper noun?", "Yaoundé", ["city", "market", "road"], "Special name."), ("m", "Which is a common noun?", "teacher", ["Ada", "Monday", "Cameroon"], "Any teacher."), ("m", "In the sentence: ada lives in kumba. Which words need capital letters?", "Ada and Kumba", ["lives and in", "Ada only", "no word"], "A name of a person and a town need capitals (and the first word of a sentence).")],
  [("x", "Match each proper noun with its kind.", [("Kofi", "person"), ("Garoua", "town"), ("April", "month")], "Think who or what it names."), ("t", "The word school is a proper noun.", False, "School is a common noun, unless it is a name like St Joseph's School.")],
  ("p", "Read: On Friday Ada and her mother travel from Kumba to Douala by bus.", [("m", "Which word names a day?", "Friday", ["Ada", "bus", "mother"], "Friday."), ("m", "Which two words are towns?", "Kumba and Douala", ["Ada and mother", "bus and travel", "Friday and Ada"], "Kumba and Douala.")]),
  [("Class 3 English proper nouns: which word needs a capital letter?", "Wouri", ["river", "water", "boat"], "River Wouri is a name."),
   ("Class 3 English proper nouns: a common noun names...", "any person, place or thing", ["one special place only", "an action", "a colour"], "Common."),
   ("Which is a proper noun?", "Cameroon", ["country", "people", "flag"], "Cameroon."),
   ("Months of the year start with...", "a capital letter", ["a small letter", "a full stop", "a number"], "Capital."),
   ("Which is common noun?", "village", ["Bali", "Ngum", "May"], "Village.")],
  [NOTE])

lesson(ch, "plurals-collective", "Plural nouns and spelling rules", ["Make plurals with s, es and ies.", "Know some special plurals."],
  [("definition", "Rules", "Most nouns add **s**: book → books. Nouns ending in s, x, ch, sh add **es**: bus → buses, box → boxes, church → churches. Nouns ending in **consonant + y** change y to **ies**: baby → babies, story → stories."),
   ("retenir", "Special plurals", "child → children, man → men, woman → women, foot → feet, tooth → teeth, mouse → mice. Some words do not change: sheep, fish."),
   ("pieges", "Common mistakes", "- *babys* is wrong; write *babies*.\n- Vowel + y just adds s: boy → boys, day → days.\n- *childs* is wrong.")],
  [("Example 1", "Write the plural of baby.", ["Baby ends in consonant + y.", "Change y to ies: babies."], "babies", cards(["baby → babies", "boy → boys", "box → boxes", "child → children"], 2, 400, ch=44, size=16)),
   ("Example 2", "Write the plural of tooth.", ["This is a special plural.", "teeth."], "teeth", None)],
  (cards(["story → stories", "day → days", "dish → dishes", "foot → feet"], 2, 400, ch=44, size=16), "Plural spelling.", "Four boxes with singular and plural words."),
  [("m", "The plural of city is...", "cities", ["citys", "cityes", "city"], "ies."), ("m", "The plural of day is...", "days", ["daies", "dayes", "dies"], "Vowel + y: add s."), ("m", "The plural of woman is...", "women", ["womans", "womens", "womanes"], "Special plural.")],
  [("x", "Match singular and plural.", [("box", "boxes"), ("lorry", "lorries"), ("mouse", "mice")], "Use the rules."), ("t", "The plural of sheep is sheeps.", False, "Sheep stays sheep.")],
  ("p", "A teacher writes on the board: one story, two ___; one dish, two ___.", [("m", "Plural of story:", "stories", ["storys", "storyes", "story"], "ies."), ("m", "Plural of dish:", "dishes", ["dishs", "dishies", "dish"], "es.")]),
  [("Class 3 English plurals: the plural of baby is...", "babies", ["babys", "babyes", "babyies"], "ies."),
   ("Class 3 English plurals: the plural of bus is...", "buses", ["buss", "busies", "bus"], "es."),
   ("The plural of toy is...", "toys", ["toies", "toyes", "tois"], "Vowel + y."),
   ("The plural of foot is...", "feet", ["foots", "feets", "footes"], "feet."),
   ("Which word has the same singular and plural?", "sheep", ["dog", "child", "tooth"], "Sheep.")],
  [NOTE], prereq=["class3-english-common-proper-nouns"])

lesson(ch, "pronouns", "Pronouns", ["Use subject pronouns (I, he, she, it, we, they).", "Use object pronouns (me, him, her, us, them)."],
  [("definition", "Pronouns", "A **pronoun** is used instead of a noun. Subject pronouns come before the verb: **I, you, he, she, it, we, they**. Example: **She** sings."),
   ("retenir", "Object pronouns", "Object pronouns come after the verb or a word like to: **me, you, him, her, it, us, them**. Mama calls **me**. Give the book to **her**. Ada helps **them**."),
   ("pieges", "Common mistakes", "- *Me and Ada go* is wrong; say *Ada and I go*.\n- Use *him* for a boy and *her* for a girl.\n- *Them* is not a subject: say *They run*.")],
  [("Example 1", "Fill the gap: Kofi is tall. ___ plays football. (He / Him)", ["Kofi is the doer.", "Use the subject pronoun He."], "He", cards(["I → me", "he → him", "she → her", "they → them"], 4, 400, ch=44, size=15)),
   ("Example 2", "Fill the gap: Mama calls ___. (I / me)", ["Me is the one called.", "Use the object pronoun me."], "me", None)],
  (cards(["I – me", "he – him", "she – her", "we – us", "they – them"], 3, 400, ch=44, size=18), "Subject and object pronouns.", "Five boxes with pairs of pronouns."),
  [("m", "Ada is my friend. I like ___.", "her", ["she", "he", "they"], "Object: her."), ("m", "The boys are late. ___ run fast.", "They", ["Them", "Her", "Him"], "Subject: They."), ("m", "The teacher helps ___ (me and my friends).", "us", ["we", "I", "they"], "Object: us.")],
  [("x", "Match the subject pronoun with its object pronoun.", [("he", "him"), ("we", "us"), ("they", "them")], "Pairs."), ("t", "We say: Him sings well.", False, "We say: He sings well.")],
  ("p", "Bih and Ngu are friends. Bih says: Ngu and ___ share a desk. ___ help each other.", [("m", "Which fits the first gap?", "I", ["me", "him", "us"], "Ngu and I share (subject)."), ("m", "Which fits the second gap?", "We", ["Us", "Them", "Him"], "We help.")]),
  [("Class 3 English pronouns: Ngu is a boy. I like ___.", "him", ["he", "she", "they"], "Him."),
   ("Class 3 English pronouns: the girls sing. ___ sing well.", "They", ["Them", "Her", "Us"], "They."),
   ("Mama gives a book to ___ (Ada).", "her", ["she", "him", "he"], "Her."),
   ("Which is a subject pronoun?", "we", ["us", "me", "him"], "We."),
   ("Which is an object pronoun?", "them", ["they", "she", "I"], "Them.")],
  [NOTE], prereq=["class3-english-plurals-collective"])

ch = p.chapter("verbs-adjectives", "Verbs, adjectives and adverbs", R)
lesson(ch, "tenses", "Verbs: past, present and future", ["Use the simple present, past and future.", "Change the tense of a sentence."],
  [("definition", "Tenses", "**Present**: what happens now or always: *Ada walks to school.* **Past**: what already happened: *Ada walked to school yesterday.* **Future**: what will happen: *Ada will walk to school tomorrow.*"),
   ("retenir", "Making them", "Present: base verb, add s for he, she, it (walks). Past: add -ed (walked) or a special word (go → went, see → saw, eat → ate, run → ran). Future: **will** + verb (will walk)."),
   ("pieges", "Common mistakes", "- *went*, not *goed*.\n- Do not use -ed after will: *will walk*, not *will walked*.\n- He **walks**, but they **walk**.")],
  [("Example 1", "Put in the past: I eat rice.", ["Eat changes to ate.", "I ate rice."], "I ate rice.", table_fig([["Present", "Past", "Future"], ["walk", "walked", "will walk"], ["go", "went", "will go"]], 400, 120, 32)),
   ("Example 2", "Put in the future: She sings.", ["Use will with the base verb.", "She will sing."], "She will sing.", None)],
  (table_fig([["Present", "Past", "Future"], ["play", "played", "will play"], ["eat", "ate", "will eat"], ["see", "saw", "will see"]], 400, 120, 32), "Three tenses.", "A table with present, past and future of play, eat and see."),
  [("m", "Yesterday we ___ to Limbe. (go)", "went", ["go", "goed", "gone"], "Went."), ("m", "Tomorrow he ___ come. (will)", "will", ["did", "was", "has"], "Future: will."), ("m", "Every day she ___ water. (fetch)", "fetches", ["fetch", "fetched", "fetching"], "Present with she.")],
  [("x", "Match the present with the past.", [("run", "ran"), ("see", "saw"), ("buy", "bought")], "Special pasts."), ("t", "I will walked home tomorrow.", False, "Will + base verb: I will walk home.")],
  ("p", "Read: Last Saturday Neba walked to the market. He bought yams. Next Saturday he will buy fish.", [("m", "Which word is the past of buy?", "bought", ["buyed", "buy", "buys"], "Bought."), ("m", "Which word shows the future?", "will buy", ["bought", "walked", "bought yams"], "Will buy.")]),
  [("Class 3 English tenses: which sentence is in the past?", "Ada played football.", ["Ada plays football.", "Ada will play football.", "Ada playing football."], "-ed."),
   ("Class 3 English tenses: the future of 'I help' is...", "I will help", ["I helped", "I helps", "I helping"], "Will."),
   ("The past of go is...", "went", ["goed", "gone", "goes"], "Went."),
   ("The past of sing is...", "sang", ["singed", "sung", "sings"], "Sang."),
   ("We use will to talk about the...", "future", ["past", "now only", "colour"], "Future.")],
  [NOTE], prereq=["class3-english-pronouns"])

lesson(ch, "adjectives-comparing", "Adjectives and comparing", ["Use adjectives to describe.", "Use -er and -est to compare."],
  [("definition", "Adjectives", "An **adjective** describes a noun: a **tall** boy, a **sweet** mango, **five** hens. Adjectives tell size, colour, number, taste and feeling."),
   ("retenir", "Comparing", "To compare two things add **-er**: tall → taller. To compare three or more add **-est**: tall → tallest. Ada is taller than Bih. Neba is the tallest. Some words are special: good → better → best."),
   ("pieges", "Common mistakes", "- Not *more taller*. Say *taller*.\n- big → bigger → biggest (double the g).\n- good → better → best, not *gooder*.")],
  [("Example 1", "Complete: Mount Cameroon is ___ than a hill. (high)", ["We compare two things.", "Add -er: higher."], "higher", cards(["tall", "taller", "tallest"], 3, 400, ch=44, size=18)),
   ("Example 2", "Complete: Ada is the ___ girl in the class. (small)", ["We compare many girls.", "Add -est: smallest."], "smallest", None)],
  (cards(["big, bigger, biggest", "long, longer, longest", "good, better, best"], 1, 400, ch=40, size=18), "Comparing adjectives.", "Three boxes showing adjectives and their comparisons."),
  [("m", "A goat is ___ than a hen. (big)", "bigger", ["biggest", "more big", "bigest"], "Two things: -er."), ("m", "This is the ___ road in town. (long)", "longest", ["longer", "more long", "long"], "Many: -est."), ("m", "Which is the right form of good (compare two)?", "better", ["gooder", "more good", "best"], "Better.")],
  [("x", "Match the adjective with its -est form.", [("tall", "tallest"), ("small", "smallest"), ("good", "best")], "Rules."), ("t", "More taller is correct English.", False, "Say taller.")],
  ("p", "Three boys: Ngu is 120 cm, Tabi is 130 cm and Eko is 125 cm tall.", [("m", "Who is the tallest?", "Tabi", ["Ngu", "Eko", "all same"], "130 cm."), ("m", "Ngu is ___ than Eko. (short)", "shorter", ["shortest", "more short", "short"], "Shorter.")]),
  [("Class 3 English adjectives: the form to compare two things is...", "-er", ["-est", "-ing", "-ed"], "-er."),
   ("Class 3 English adjectives: Mary is the ___ girl in class. (clever)", "cleverest", ["cleverer", "most clever girl", "clever"], "Cleverest."),
   ("The best word: A lion is ___ than a goat. (strong)", "stronger", ["strongest", "strong", "more strong"], "Stronger."),
   ("The comparison of good is...", "better, best", ["gooder, goodest", "more good", "well, best"], "Special."),
   ("Which word is an adjective?", "sweet", ["sing", "slowly", "she"], "Sweet.")],
  [NOTE], prereq=["class3-english-tenses"])

lesson(ch, "adverbs", "Adverbs: how, when and where", ["Say what an adverb is.", "Use adverbs of manner, time and place."],
  [("definition", "Adverbs", "An **adverb** tells more about a verb. It says **how**, **when** or **where**. She walks **slowly**. He comes **today**. The bird flies **high**."),
   ("retenir", "Making adverbs", "Many adverbs end in **-ly**: slow → slowly, quick → quickly, loud → loudly, kind → kindly. Some are special: fast, hard, well."),
   ("pieges", "Common mistakes", "- *Run quick* is wrong; say *run quickly*.\n- Good is an adjective; well is an adverb: *She sings well*.\n- Adverbs tell about verbs; adjectives tell about nouns.")],
  [("Example 1", "Find the adverb: The baby sleeps quietly.", ["Sleeps is the verb.", "Quietly tells how: it is the adverb."], "quietly", cards(["how: slowly", "when: today", "where: here"], 3, 400, ch=44, size=16)),
   ("Example 2", "Make an adverb from quick.", ["Add -ly.", "quickly."], "quickly", None)],
  (cards(["slowly", "quickly", "loudly", "kindly"], 4, 400, ch=44, size=15), "Adverbs of manner.", "Four boxes with slowly, quickly, loudly and kindly."),
  [("m", "Find the adverb: She speaks softly.", "softly", ["She", "speaks", "none"], "Softly."), ("m", "Choose the right word: The boy runs ___.", "fast", ["quick", "slow", "more"], "Fast is an adverb here."), ("m", "Choose the right word: Ada sings ___.", "well", ["good", "gooder", "best"], "Well.")],
  [("x", "Match the adjective with its adverb.", [("slow", "slowly"), ("quick", "quickly"), ("loud", "loudly")], "Add -ly."), ("t", "An adverb tells more about a verb.", True, "Yes.")],
  ("p", "Read: The pupils sit quietly. The teacher comes early.", [("m", "Which word tells how?", "quietly", ["pupils", "teacher", "sit"], "Quietly."), ("m", "Which word tells when?", "early", ["quietly", "sit", "comes"], "Early.")]),
  [("Class 3 English adverbs: which word is an adverb?", "slowly", ["slow man", "walk", "book"], "Slowly."),
   ("Class 3 English adverbs: the adverb of 'careful' is...", "carefully", ["carefuly", "careful", "carefulness"], "Carefully."),
   ("An adverb tells more about a...", "verb", ["noun only", "number", "town"], "Verb."),
   ("She dances ___. (well / good)", "well", ["good", "gooder", "best"], "Well."),
   ("Which adverb tells where?", "here", ["slowly", "loudly", "kindly"], "Here.")],
  [NOTE], prereq=["class3-english-adjectives-comparing"])

ch = p.chapter("sentence-skills", "Sentences and word skills", R)
lesson(ch, "prepositions-conjunctions", "Prepositions and joining words", ["Use prepositions of place and time.", "Join sentences with and, but, because, so."],
  [("definition", "Prepositions", "A **preposition** tells where or when: **in** the box, **on** the table, **under** the tree, **between** two houses, **at** school, **on** Monday, **in** May."),
   ("retenir", "Joining words", "**and** adds: I like rice and beans. **but** shows a difference: I am small but strong. **because** gives a reason: I eat because I am hungry. **so** gives a result: It rained, so we stayed home."),
   ("pieges", "Common mistakes", "- *on Monday*, *in May*, *at 3 o'clock*.\n- Do not start with *because* alone: it needs the other part.\n- Use a comma before *but* in longer sentences.")],
  [("Example 1", "Join: I was hungry. I ate rice. (so)", ["The first sentence gives the reason.", "I was hungry, so I ate rice."], "I was hungry, so I ate rice.", cards(["and", "but", "because", "so"], 4, 400, ch=44, size=16)),
   ("Example 2", "Fill the gap: We have school ___ Monday. (on / in)", ["Days use on.", "on Monday."], "on", None)],
  (cards(["on Monday", "in May", "at school", "under the tree"], 2, 400, ch=44, size=16), "Prepositions.", "Four boxes with on Monday, in May, at school, under the tree."),
  [("m", "The cat sleeps ___ the table. (below)", "under", ["on", "in", "at"], "Under."), ("m", "I was tired ___ I went to bed early.", "so", ["but", "because", "or"], "Result: so."), ("m", "I did not go ___ it rained.", "because", ["so", "and", "but"], "Reason: because.")],
  [("x", "Match the joining word with its job.", [("and", "adds"), ("but", "shows a difference"), ("because", "gives a reason")], "Jobs of joining words."), ("m", "Choose the right word: He is slow ___ he is careful.", "but", ["so", "because", "and"], "A difference.")],
  ("p", "Ada says: I like mango ___ orange. I do not like pawpaw ___ it is too soft.", [("m", "Which word joins mango and orange?", "and", ["but", "so", "because"], "And."), ("m", "Which word gives the reason about pawpaw?", "because", ["and", "but", "so"], "Because.")]),
  [("Class 3 English joining words: 'because' gives a...", "reason", ["result", "place", "time"], "Reason."),
   ("Class 3 English prepositions: we meet ___ Friday.", "on", ["in", "at", "under"], "On Friday."),
   ("I am happy ___ it is Saturday.", "because", ["but", "so", "or"], "Because."),
   ("The word 'but' shows a...", "difference", ["time", "place", "number"], "Difference."),
   ("We say 'in ___'.", "May", ["Monday", "Friday", "Sunday"], "In May.")],
  [NOTE], prereq=["class3-english-adverbs"])

lesson(ch, "punctuation", "Punctuation: . , ? !", ["Use full stops, question marks and exclamation marks.", "Use commas in lists."],
  [("definition", "Punctuation marks", "A **full stop** (.) ends a statement. A **question mark** (?) ends a question. An **exclamation mark** (!) shows surprise or a strong feeling: *What a big fish!*"),
   ("retenir", "Commas", "A **comma** (,) separates things in a list: *I bought yams, plantains, fish and salt.* Put **and** before the last item. We also use commas after greetings: *Dear Ada,*"),
   ("pieges", "Common mistakes", "- No comma before the last *and* in a simple list.\n- A question needs a question mark.\n- Do not use too many exclamation marks.")],
  [("Example 1", "Add the right mark: What time is it", ["It asks something.", "What time is it?"], "?", cards(["full stop .", "question mark ?", "exclamation mark !", "comma ,"], 2, 400, ch=44, size=16)),
   ("Example 2", "Add commas: Mama sells rice beans oil and salt.", ["Separate the first items.", "Mama sells rice, beans, oil and salt."], "rice, beans, oil and salt", None)],
  (cards(["Where is Ada?", "Ada is here.", "Hurray!", "mangoes, pears and figs"], 2, 400, ch=44, size=15), "Punctuation in use.", "Four boxes with examples of punctuation."),
  [("m", "Which mark ends a question?", "?", [".", "!", ","], "Question mark."), ("m", "Which sentence has the right mark?", "How are you?", ["How are you.", "How are you,", "How are you"], "?"), ("m", "Which shows surprise?", "What a big goat!", ["I see a goat.", "Where is the goat?", "The goat is here."], "!")],
  [("m", "Choose the list written right.", "I like mango, orange and banana.", ["I like, mango orange and banana.", "I like mango orange, and banana.", "I like mango orange and, banana."], "Commas between items."), ("t", "A comma ends a sentence.", False, "A full stop ends it.")],
  ("p", "Teacher writes: wow what a lovely day it is", [("m", "Which mark follows Wow?", "an exclamation mark", ["a full stop", "a comma only", "nothing"], "Strong feeling."), ("m", "Which mark ends the whole sentence?", "an exclamation mark", ["a question mark", "a comma", "a full stop only"], "Strong feeling: !.")]),
  [("Class 3 English punctuation: a question ends with...", "a question mark", ["a full stop", "a comma", "a dash"], "?"),
   ("Class 3 English punctuation: which sentence shows surprise?", "What a tall tree!", ["It is a tree.", "Is it a tree?", "The tree is here."], "!"),
   ("A comma is used in a...", "list", ["question", "title only", "number"], "List."),
   ("A statement ends with...", "a full stop", ["a comma", "a question mark", "nothing"], "Full stop."),
   ("In a list we put 'and' before the...", "last item", ["first item", "comma", "title"], "Last.")],
  [NOTE], prereq=["class3-english-prepositions-conjunctions"])

lesson(ch, "opposites-synonyms", "Opposites and words with the same meaning", ["Say opposites (antonyms).", "Say words with similar meaning (synonyms)."],
  [("definition", "Opposites", "**Opposites** (antonyms) have the reverse meaning: hot – cold, early – late, strong – weak, wide – narrow, rich – poor, success – failure."),
   ("retenir", "Synonyms", "**Synonyms** have almost the same meaning: big – large, begin – start, glad – happy, quick – fast, little – small. Use them to make writing more interesting."),
   ("pieges", "Common mistakes", "- Synonyms are not always exactly the same.\n- Do not mix: *happy – glad* is similar, *happy – sad* is the opposite.\n- Check the meaning in a sentence.")],
  [("Example 1", "Give the opposite of early.", ["Think of the time we arrive.", "Late."], "late", cards(["hot - cold", "early - late", "strong - weak"], 3, 400, ch=44, size=16)),
   ("Example 2", "Give a word like begin.", ["It means the same.", "Start."], "start", None)],
  (cards(["big = large", "glad = happy", "quick = fast", "begin = start"], 2, 400, ch=44, size=16), "Words with the same meaning.", "Four boxes with pairs of synonyms."),
  [("m", "The opposite of strong is...", "weak", ["hard", "tall", "big"], "Weak."), ("m", "A word like happy is...", "glad", ["sad", "angry", "tired"], "Glad."), ("m", "The opposite of narrow is...", "wide", ["thin", "long", "short"], "Wide.")],
  [("x", "Match the opposites.", [("rich", "poor"), ("early", "late"), ("success", "failure")], "Reverse meanings."), ("x", "Match the synonyms.", [("quick", "fast"), ("little", "small"), ("start", "begin")], "Similar meanings.")],
  ("p", "Read: The old man is strong but the young boy is weak.", [("m", "Which word is the opposite of strong?", "weak", ["old", "young", "man"], "Weak."), ("m", "Which word is the opposite of old?", "young", ["strong", "weak", "man"], "Young.")]),
  [("Class 3 English opposites: the opposite of rich is...", "poor", ["wealthy", "tall", "big"], "Poor."),
   ("Class 3 English synonyms: a word that means the same as large is...", "big", ["small", "thin", "short"], "Big."),
   ("The opposite of success is...", "failure", ["victory", "luck", "help"], "Failure."),
   ("A word that means the same as start is...", "begin", ["stop", "end", "finish"], "Begin."),
   ("Opposites are also called...", "antonyms", ["synonyms", "nouns", "verbs"], "Antonyms.")],
  [NOTE], prereq=["class3-english-punctuation"])

lesson(ch, "spelling-ing-ed", "Spelling: adding -ing and -ed", ["Add -ing and -ed to verbs.", "Know the doubling and dropping e rules."],
  [("definition", "Rule 1", "For most verbs just add **-ing** or **-ed**: play → playing, played. For verbs that end in **e**, drop the e: make → making, like → liked."),
   ("retenir", "Rule 2: doubling", "For short verbs with one vowel and one consonant at the end, double the last letter: run → running, stop → stopped, hop → hopped, sit → sitting."),
   ("pieges", "Common mistakes", "- *makeing* is wrong; write *making*.\n- Do not double w, x or y: playing, fixing.\n- *runing* is wrong; write *running*.")],
  [("Example 1", "Add -ing to run.", ["Run is a short word with one vowel and one consonant at the end.", "Double the n: running."], "running", cards(["make → making", "stop → stopped", "play → playing", "run → running"], 2, 400, ch=44, size=16)),
   ("Example 2", "Add -ed to like.", ["Like ends in e.", "Drop the e and add -ed: liked."], "liked", None)],
  (cards(["hop → hopping", "write → writing", "jump → jumped", "sit → sitting"], 2, 400, ch=44, size=16), "Adding -ing and -ed.", "Four boxes with verbs and their -ing or -ed forms."),
  [("m", "Add -ing to make.", "making", ["makeing", "makking", "maken"], "Drop e."), ("m", "Add -ed to stop.", "stopped", ["stoped", "stoping", "stopd"], "Double p."), ("m", "Add -ing to play.", "playing", ["plaing", "playying", "plays"], "Just add -ing.")],
  [("x", "Match the verb with its -ing form.", [("sit", "sitting"), ("write", "writing"), ("jump", "jumping")], "Rules."), ("t", "The -ing form of run is runing.", False, "Double the n: running.")],
  ("p", "Teacher writes: Ada is (write) a letter. Yesterday she (stop) at the shop.", [("m", "Which is right for write?", "writing", ["writeing", "writting", "writed"], "writing."), ("m", "Which is right for stop?", "stopped", ["stoped", "stopping", "stopt"], "stopped.")]),
  [("Class 3 English spelling: dance with -ing is...", "dancing", ["danceing", "dancking", "dancng"], "Drop e."),
   ("Class 3 English spelling: hop with -ed is...", "hopped", ["hoped", "hoping", "hopt"], "Double p."),
   ("Which is the right -ing form of run?", "running", ["runing", "runnng", "runningg"], "Double n."),
   ("Which is the right -ing form of like?", "liking", ["likeing", "likking", "likeng"], "Drop e."),
   ("We do not double the letter in...", "playing", ["running", "sitting", "stopping"], "y is not doubled.")],
  [NOTE], prereq=["class3-english-tenses"])

ch = p.chapter("reading-writing", "Reading, writing and speaking", R)
st1 = "Nkeng lives in a village near Bamenda. Every morning she wakes up early and fetches water from the stream. Then she washes her face and eats corn porridge. After that she walks to school with her friends. In class she likes to read. Her favourite book is about a clever tortoise. One day she wants to be a teacher."
st2 = "Last Saturday the people of the village cleaned the road. Men cut the grass with machetes. Women and children carried the dry leaves to a big pit. The chief thanked everyone. By noon the road was clean. Then they shared food and sat together under a mango tree."
assert len(st1) < 650 and len(st2) < 650
lesson(ch, "comprehension-1", "Reading: Nkeng's Morning", ["Read a short story.", "Answer questions using the story."],
  [("definition", "The story", st1),
   ("methode", "How to answer", "1. Read the story. 2. Read the question. 3. Find the part of the story that answers it. 4. Write the answer in a full sentence."),
   ("pieges", "Common mistakes", "- Do not guess. Check the story.\n- Answer only what is asked.\n- Use words from the question in your answer.")],
  [("Example 1", "Where does Nkeng get water?", ["Look for water in the story.", "She fetches it from the stream."], "From the stream", cards(["wakes up early", "fetches water", "goes to school"], 3, 400, ch=44, size=14)),
   ("Example 2", "What does Nkeng want to be one day?", ["Look at the last sentence.", "A teacher."], "A teacher", None)],
  (cards(["wake up", "fetch water", "eat porridge", "walk to school"], 4, 400, ch=44, size=13), "Nkeng's morning, in order.", "Four boxes showing wake up, fetch water, eat porridge and walk to school."),
  [("m", "In the story, what does Nkeng eat in the morning?", "corn porridge", ["rice", "bread", "plantain"], "Corn porridge."), ("m", "In the story, her favourite book is about...", "a clever tortoise", ["a lion", "a hen", "a school"], "A clever tortoise."), ("m", "She walks to school with...", "her friends", ["her teacher", "her uncle", "her dog"], "Her friends.")],
  [("t", "Nkeng wakes up late in the story.", False, "She wakes up early."), ("m", "Which sentence comes first in her morning?", "She fetches water.", ["She walks to school.", "She reads in class.", "She eats porridge."], "Fetches water, then washes and eats.")],
  ("p", "Read the story about Nkeng's morning in the lesson.", [("m", "Where does Nkeng live?", "near Bamenda", ["in Douala", "in Limbe", "in Garoua"], "Near Bamenda."), ("m", "Which word best describes the tortoise?", "clever", ["slow", "big", "angry"], "The story says clever.")]),
  [("Class 3 English reading: Nkeng gets water from the...", "stream", ["well", "river Wouri", "pump"], "Stream."),
   ("Class 3 English reading: she likes to...", "read", ["swim", "sing", "sleep"], "Read."),
   ("In Nkeng's story, she wants to be a...", "teacher", ["driver", "farmer", "nurse"], "Teacher."),
   ("To answer a question about a story we...", "look back at the story", ["guess", "draw a car", "stop"], "Look back."),
   ("Nkeng's morning begins when she...", "wakes up early", ["goes to bed", "eats lunch", "reads a book"], "Wakes up.")],
  ["Story is original; reading level and length for Class 3 to be checked."], prereq=["class3-english-opposites-synonyms"])

lesson(ch, "comprehension-2", "Reading: The Clean Road", ["Read a short report about a village.", "Say what happened and in what order."],
  [("definition", "The story", st2),
   ("methode", "Sequence", "Words like **first, then, after that, by noon, last** tell us the order of events. Put the events in order to retell a story."),
   ("pieges", "Common mistakes", "- Do not change the order of events.\n- Do not add facts that are not in the text.\n- Say who did what.")],
  [("Example 1", "Who thanked everyone?", ["Look for the word thanked.", "The chief."], "The chief", cards(["cut grass", "carried leaves", "chief thanks", "share food"], 2, 400, ch=44, size=15)),
   ("Example 2", "What did they do after the road was clean?", ["Look at the last sentence.", "They shared food under a mango tree."], "They shared food", None)],
  (cards(["1. cut the grass", "2. carried the leaves", "3. the chief thanked them", "4. shared food"], 2, 400, ch=44, size=14), "What happened in order.", "Four boxes with the events of the road cleaning in order."),
  [("m", "What did men cut with?", "machetes", ["knives only", "saws", "scissors"], "Machetes."), ("m", "Who carried the dry leaves?", "women and children", ["men only", "the chief", "nobody"], "Women and children."), ("m", "When was the road clean?", "by noon", ["at night", "on Monday", "next week"], "By noon.")],
  [("t", "The people sat under a mango tree.", True, "True."), ("m", "What happened last?", "They shared food and sat together.", ["The men cut the grass.", "The road was clean.", "The chief thanked everyone."], "Last event.")],
  ("p", "Read the story of the clean road.", [("m", "On which day was the road cleaned?", "Saturday", ["Monday", "Friday", "Sunday"], "Last Saturday."), ("m", "What was the result of everyone's work?", "the road was clean", ["the road was closed", "the grass grew", "the chief left"], "By noon the road was clean.")]),
  [("Class 3 English reading: in the clean road story, women and children...", "carried the leaves", ["cut the grass", "thanked everyone", "sold food"], "Carried leaves."),
   ("Class 3 English reading: the people cleaned the...", "road", ["school", "market", "river"], "Road."),
   ("Who thanked everyone?", "the chief", ["the teacher", "a child", "the driver"], "Chief."),
   ("The word 'then' tells us about...", "order of events", ["colour", "size", "price"], "Order."),
   ("They sat together under a...", "mango tree", ["bridge", "house", "bus"], "Mango tree.")],
  ["Story is original; the 'clean road' idea is a common community activity, no real place or event is named."], prereq=["class3-english-comprehension-1"])

lesson(ch, "writing-paragraph", "Writing a paragraph and a short letter", ["Write a paragraph of 4 to 5 sentences.", "Write a short friendly letter."],
  [("definition", "Paragraph", "A **paragraph** is a group of sentences about one idea. Start with a **topic sentence**. Add sentences with details. End with a closing sentence. Example topic: *My school is a happy place.*"),
   ("methode", "Letter", "A friendly letter has: the **address and date** at the top right, a **greeting** (Dear Ada,), the **message**, and an **ending** (Yours, Bih). Put a comma after the greeting."),
   ("pieges", "Common mistakes", "- Keep to one idea in a paragraph.\n- Begin each sentence with a capital letter.\n- Use *Yours* with a capital Y and a comma.")],
  [("Example 1", "Write a topic sentence about your favourite fruit.", ["Name the fruit and say what you think.", "My favourite fruit is the mango because it is sweet."], "My favourite fruit is the mango because it is sweet.", cards(["Dear Ada,", "I am well.", "Yours, Bih"], 1, 300, ch=44, size=18)),
   ("Example 2", "How do we begin a letter to a friend named Ngu?", ["We use a greeting.", "Dear Ngu,"], "Dear Ngu,", None)],
  (cards(["Dear Ada,", "I hope you are well.", "Yours, Bih"], 1, 400, ch=40, size=18), "Parts of a friendly letter.", "Three boxes with the greeting, a message and an ending."),
  [("m", "Which is a good greeting in a letter?", "Dear Ngu,", ["hello ngu", "Ngu", "Dear ngu."], "Dear Ngu, with a comma."), ("m", "A paragraph is about...", "one idea", ["many ideas", "a word", "a letter"], "One idea."), ("m", "Which is a good ending?", "Yours, Bih", ["bye bih", "Yours Bih.", "yours bih"], "Yours, Bih.")],
  [("m", "Which sentence could be a topic sentence?", "My school is a happy place.", ["Because it is big.", "Happy.", "In the morning."], "A full idea."), ("t", "A friendly letter has a greeting.", True, "True.")],
  ("p", "Bih writes a letter to her cousin Ada.", [("m", "How should the letter begin?", "Dear Ada,", ["Ada", "dear ada", "To Ada."], "Greeting."), ("m", "Which ends the letter best?", "Yours, Bih", ["bye", "Bih Bih", "From."], "Ending.")]),
  [("Class 3 English writing: a paragraph is a group of sentences about...", "one idea", ["ten ideas", "no idea", "a name"], "One idea."),
   ("Class 3 English writing: a friendly letter begins with...", "a greeting", ["a full stop", "a number", "a poem"], "Greeting."),
   ("The first sentence of a paragraph is the...", "topic sentence", ["last sentence", "title", "address"], "Topic sentence."),
   ("A letter to a friend can end with...", "Yours, Bih", ["Dear Bih", "Hello", "The end"], "Yours."),
   ("After the greeting we put a...", "comma", ["full stop", "question mark", "star"], "Comma.")],
  ["Letter layout conventions vary slightly; check against the textbook."], prereq=["class3-english-comprehension-2"])

lesson(ch, "speaking-dictionary", "Speaking, listening and using a dictionary", ["Give a short talk clearly.", "Use alphabetical order to find a word."],
  [("definition", "Speaking", "When you give a short talk: stand up, speak clearly, look at your listeners, speak in full sentences, and say **thank you** at the end. Listeners: look, keep quiet and think. Ask a question at the end."),
   ("methode", "Alphabetical order", "A dictionary lists words in **alphabetical order**. Look at the first letter. If it is the same, look at the second letter: **ant, apple, bag, bed, cat**. *ant* comes before *apple* because n comes before p."),
   ("pieges", "Common mistakes", "- Look at the second letter if the first letters are the same.\n- Do not speak too fast.\n- Do not talk while others speak.")],
  [("Example 1", "Put in alphabetical order: dog, cat, ant.", ["First letters: d, c, a.", "a, c, d: ant, cat, dog."], "ant, cat, dog", cards(["ant", "bag", "cat", "dog"], 4, 400, ch=44, size=18)),
   ("Example 2", "Which comes first: bed or bag?", ["Both start with b. Look at the second letter: e and a.", "a comes before e. So bag comes first."], "bag", None)],
  (cards(["ant", "apple", "bag", "bed"], 4, 400, ch=44, size=16), "Words in alphabetical order.", "Four boxes with ant, apple, bag, bed."),
  [("m", "Which word comes first in the dictionary?", "ant", ["cat", "dog", "bed"], "A is first."), ("m", "Which list is in alphabetical order?", "bag, bed, cat", ["cat, bed, bag", "bed, bag, cat", "cat, bag, bed"], "b, b, c with a before e."), ("t", "In a talk we should speak clearly.", True, "Yes.")],
  [("m", "Which word comes first: mango or maize?", "maize", ["mango", "both are the same", "none"], "ai comes before an."), ("m", "Which is the best way to end a talk?", "Say thank you.", ["Run away.", "Say nothing.", "Shout."], "Thank the listeners.")],
  ("p", "Pupils make a class list: Tabi, Ada, Neba, Kofi.", [("m", "Which name is first in alphabetical order?", "Ada", ["Kofi", "Neba", "Tabi"], "A."), ("m", "Which name is last?", "Tabi", ["Ada", "Kofi", "Neba"], "T.")]),
  [("Class 3 English dictionary: which word comes first in a dictionary?", "apple", ["bag", "cat", "egg"], "A."),
   ("Class 3 English speaking: when giving a talk we should...", "speak clearly", ["whisper", "shout", "turn our back"], "Clearly."),
   ("Which word comes first: bat or bag?", "bag", ["bat", "same", "none"], "g before t."),
   ("A dictionary has words in...", "alphabetical order", ["number order", "colour order", "size order"], "Alphabetical."),
   ("A good listener...", "keeps quiet and thinks", ["talks loudly", "leaves", "sleeps"], "Listens.")],
  ["Speaking and listening need a teacher to assess."], prereq=["class3-english-writing-paragraph"])

p.write()
