import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from p13_kit import *
from p13_fig import *

p = newpack("class3-science", "Elementary Science — Class 3", "Class 3", "sciences",
    "Class 3 science: life processes, life cycles, plants, animals, the human body, food and health, water and matter, forces, light, magnets, soil and caring for the environment.",
    REF % "Level II (Class 3) — Elementary Science")
R = p.programRef
NOTE = "Elementary science content is kept to simple, textbook-level facts; to be reviewed by a primary teacher."
HNOTE = "Health content is conservative and general; to be reviewed by a health worker or nurse. It never replaces advice from a nurse or a doctor."
def C(n, shape="circle", color="orange", per=5, w=300, h=120): return count(n, shape, color, per, w, h)

ch = p.chapter("life", "Life processes and life cycles", R)
lesson(ch, "life-processes", "Characteristics of living things", ["Name the seven life processes.", "Use them to tell living from non-living things."],
  [("definition", "Life processes", "All living things do seven things: they **move**, **respire** (breathe and release energy), **sense** the world, **grow**, **reproduce** (make young), **excrete** (get rid of waste) and **nourish** themselves (feed)."),
   ("retenir", "Plants too", "Plants are alive. They grow, make seeds, sense light and move slowly towards it. They need water, air and light. Non-living things like stones and cars do not carry out all seven processes."),
   ("pieges", "Common mistakes", "- A car moves and uses fuel, but it does not grow or reproduce.\n- A seed looks still but is alive.\n- To decide, check all the signs, not only one.")],
  [("Example 1", "Is a mango tree living? Give two reasons.", ["It grows taller each year.", "It makes seeds in its fruit."], "Yes: it grows and reproduces", cards(["move", "respire", "sense", "grow", "reproduce", "excrete", "nourish"], 4, 400, ch=40, size=13)),
   ("Example 2", "A toy car moves. Is it living?", ["Moving is one sign only.", "It does not grow, breathe or reproduce. It is non-living."], "No", None)],
  (cards(["move", "respire", "sense", "grow", "reproduce", "excrete", "nourish"], 4, 400, ch=40, size=13), "The seven life processes.", "Seven boxes naming the life processes."),
  [("n", "How many life processes do living things carry out?", 7, "Seven."), ("m", "Which is a living thing?", "a mushroom", ["a coin", "a tin", "a chair"], "A mushroom is alive."), ("m", "To reproduce means to...", "make young", ["move", "eat", "breathe"], "Make young.")],
  [("x", "Match the life process with its meaning.", [("grow", "get bigger"), ("sense", "feel the world"), ("nourish", "take in food")], "Meanings."), ("t", "A seed is a living thing.", True, "A seed is alive.")],
  ("p", "A teacher shows: a goat, a tree, a rock, a bicycle.", [("n", "How many things are living?", 2, "Goat and tree."), ("m", "Why is the bicycle non-living?", "it does not grow or reproduce", ["it is made of metal only", "it is red", "it is small"], "Not all processes.")]),
  [("Class 3 science life processes: how many life processes are there?", "seven", ["three", "ten", "five"], "Seven."),
   ("Class 3 science life processes: which is a non-living thing?", "a motorbike", ["a hen", "a seed", "a moss"], "Non-living."),
   ("Respiration means...", "breathing and releasing energy", ["growing taller", "making noise", "sleeping"], "Respiration."),
   ("Excretion is...", "getting rid of waste", ["making young", "taking in food", "moving"], "Waste."),
   ("Plants...", "grow and make seeds", ["never grow", "walk", "talk"], "Alive.")],
  ["Seven life processes follow the usual mnemonic (MRS GREN); wording for Class 3 to be checked."])

lesson(ch, "life-cycles", "Life cycles", ["Describe the life cycle of a hen, a frog and a plant.", "Put the stages in order."],
  [("definition", "Life cycle", "A **life cycle** shows the stages of life of a living thing. Each living thing is born or hatched, grows, becomes an adult, has young and finally dies."),
   ("retenir", "Examples", "**Hen**: egg → chick → adult hen. **Frog**: egg → tadpole → young frog → adult frog. **Butterfly**: egg → caterpillar → pupa → butterfly. **Plant**: seed → seedling → adult plant → flowers → fruits with seeds."),
   ("pieges", "Common mistakes", "- A tadpole is not a small fish.\n- A caterpillar is the young of a butterfly, not another animal.\n- The cycle goes round: the adult makes eggs or seeds again.")],
  [("Example 1", "Put in order: tadpole, egg, adult frog, young frog.", ["It starts as an egg.", "egg, tadpole, young frog, adult frog."], "egg, tadpole, young frog, adult frog", cards(["egg", "tadpole", "young frog", "adult frog"], 4, 400, ch=44, size=13)),
   ("Example 2", "What does a caterpillar become?", ["It makes a pupa.", "A butterfly."], "A butterfly", None)],
  (cards(["seed", "seedling", "plant", "flower and fruit"], 4, 400, ch=44, size=12), "Life cycle of a plant.", "Four boxes: seed, seedling, plant, flower and fruit."),
  [("m", "A baby hen hatches from an...", "egg", ["seed", "tadpole", "pupa"], "Egg."), ("m", "A young frog starts as a...", "tadpole", ["chick", "caterpillar", "calf"], "Tadpole."), ("m", "A caterpillar becomes a...", "butterfly", ["frog", "hen", "bee only"], "Butterfly.")],
  [("x", "Match the young with the adult.", [("chick", "hen"), ("tadpole", "frog"), ("caterpillar", "butterfly")], "Young and adult."), ("t", "A life cycle starts again when an adult makes eggs or seeds.", True, "Yes.")],
  ("p", "A hen sits on 8 eggs. 6 chicks hatch.", [("n", "How many eggs did not hatch?", 2, "8 − 6 = 2."), ("m", "What will the chicks become?", "adult hens and cocks", ["frogs", "ducks only", "butterflies"], "Adults.")]),
  [("Class 3 science life cycle: the stage before a chick is the...", "egg", ["seed", "tadpole", "adult"], "Egg."),
   ("Class 3 science life cycle: the stage after the tadpole is the...", "young frog", ["egg", "caterpillar", "seed"], "Young frog."),
   ("A plant life cycle starts with a...", "seed", ["tadpole", "chick", "calf"], "Seed."),
   ("A pupa is part of the life cycle of a...", "butterfly", ["frog", "hen", "goat"], "Butterfly."),
   ("A life cycle is the...", "stages of life", ["colours of a thing", "price", "home of a bird"], "Stages.")],
  [NOTE], prereq=["class3-science-life-processes"])

lesson(ch, "plants-parts-food", "Plants: parts and how they make food", ["Say the job of each plant part.", "Say how a plant makes its food."],
  [("definition", "Parts and jobs", "**Roots** take in water and minerals and hold the plant in the soil. The **stem** holds the plant up and carries water and food. **Leaves** make food. **Flowers** make seeds and fruits."),
   ("retenir", "Making food", "Green leaves use **sunlight**, **water** and **carbon dioxide** from the air to make food (sugar). This is called **photosynthesis**. The plant also gives out **oxygen**, which people and animals breathe."),
   ("pieges", "Common mistakes", "- Plants do not take in food from the soil. They make their own.\n- Plants also respire (breathe) day and night.\n- Without light, leaves turn pale.")],
  [("Example 1", "Which part of the plant makes food?", ["Green leaves have the green colour.", "The leaves."], "The leaves", cards(["roots: water", "stem: support", "leaves: food", "flower: seeds"], 2, 400, ch=44, size=14)),
   ("Example 2", "Name three things a leaf needs to make food.", ["Light and water.", "And carbon dioxide from the air."], "Sunlight, water and carbon dioxide", None)],
  (cards(["sunlight", "water", "carbon dioxide", "food + oxygen"], 4, 400, ch=44, size=11), "Photosynthesis in short.", "Four boxes: sunlight, water, carbon dioxide, and food plus oxygen."),
  [("m", "Roots take in...", "water", ["light", "sound", "heat"], "Water."), ("m", "Leaves make food using...", "sunlight", ["moonlight only", "sand", "noise"], "Sunlight."), ("m", "A plant gives out...", "oxygen", ["smoke", "plastic", "oil"], "Oxygen.")],
  [("x", "Match the plant part with its job.", [("roots", "take in water"), ("stem", "holds the plant up"), ("flower", "makes seeds")], "Jobs."), ("t", "Plants take their food from the soil.", False, "They make food in the leaves.")],
  ("p", "A pupil keeps a plant in a dark cupboard for a week.", [("m", "What will happen to its leaves?", "they turn pale", ["they turn blue", "they grow bigger", "nothing"], "No light."), ("m", "Why?", "leaves need light to make food", ["leaves need noise", "roots need sand", "stems need sweets"], "Photosynthesis.")]),
  [("Class 3 science plants: leaves make food using...", "sunlight, water and air", ["noise and sand", "plastic and oil", "paint"], "Photosynthesis."),
   ("Class 3 science plants: the stem...", "holds the plant up", ["makes seeds", "sings", "makes rain"], "Support."),
   ("The process of making food in leaves is called...", "photosynthesis", ["digestion", "evaporation", "excretion"], "Photosynthesis."),
   ("Which gas do plants give out?", "oxygen", ["smoke", "chlorine", "gas for cooking"], "Oxygen."),
   ("Flowers make...", "seeds and fruits", ["roots", "soil", "water"], "Seeds.")],
  ["Photosynthesis and carbon dioxide/oxygen are standard at upper primary but may be taught later; confirm that Class 3 level is right."], prereq=["class3-science-life-cycles"])

ch = p.chapter("animals-body", "Animals and the human body", R)
lesson(ch, "animal-groups-diet", "Animal groups and what animals eat", ["Name the main animal groups.", "Say herbivore, carnivore and omnivore."],
  [("definition", "Groups", "**Mammals** have hair and feed young with milk. **Birds** have feathers and lay eggs. **Reptiles** have dry scales (snake, lizard, crocodile). **Amphibians** live on land and in water (frog). **Fish** have gills and scales. **Insects** have 6 legs."),
   ("retenir", "Diets", "**Herbivores** eat plants (goat, cow, rabbit). **Carnivores** eat other animals (lion, crocodile). **Omnivores** eat both (pig, chimpanzee, people). Animals that have a backbone are **vertebrates**. Insects have no backbone."),
   ("pieges", "Common mistakes", "- A frog is an amphibian, not a reptile.\n- A bat is a mammal.\n- A spider is not an insect: it has 8 legs.")],
  [("Example 1", "Is a crocodile a reptile or a mammal?", ["It has dry scales and lays eggs.", "It is a reptile."], "A reptile", cards(["mammal: goat", "bird: hen", "reptile: lizard", "amphibian: frog", "fish: tilapia", "insect: ant"], 3, 400, ch=44, size=13)),
   ("Example 2", "A goat eats grass only. What is it?", ["It eats plants only.", "A herbivore."], "A herbivore", None)],
  (cards(["herbivore", "carnivore", "omnivore"], 3, 400, ch=44, size=16), "Three diets.", "Three boxes: herbivore, carnivore, omnivore."),
  [("m", "Which is a reptile?", "a snake", ["a frog", "a hen", "a dog"], "Snake."), ("m", "An animal that eats only plants is a...", "herbivore", ["carnivore", "omnivore", "reptile"], "Herbivore."), ("m", "A frog is an...", "amphibian", ["insect", "mammal", "reptile"], "Amphibian.")],
  [("x", "Match the animal with its group.", [("bat", "mammal"), ("lizard", "reptile"), ("parrot", "bird")], "Groups."), ("t", "A spider is an insect.", False, "It has 8 legs.")],
  ("p", "A zoo has 3 lions, 5 monkeys, 2 snakes and 4 parrots.", [("n", "How many mammals? (lions and monkeys)", 8, "3 + 5 = 8."), ("n", "How many animals in all?", 14, "3 + 5 + 2 + 4 = 14.")]),
  [("Class 3 science animals: a snake is a...", "reptile", ["mammal", "insect", "bird"], "Reptile."),
   ("Class 3 science animals: a lion eating meat is a...", "carnivore", ["herbivore", "omnivore", "plant"], "Carnivore."),
   ("Animals that live on land and in water as adults are...", "amphibians", ["mammals", "reptiles only", "birds"], "Amphibians."),
   ("An insect has how many legs?", "6", ["4", "8", "10"], "Six."),
   ("People are...", "omnivores", ["only herbivores", "only carnivores", "insects"], "Omnivores.")],
  [NOTE], prereq=["class3-science-plants-parts-food"])

lesson(ch, "human-body", "Our body: skeleton, muscles, heart and lungs", ["Say what the skeleton and muscles do.", "Say what the heart and lungs do."],
  [("definition", "Skeleton and muscles", "The **skeleton** is made of **bones**. It holds the body up, protects organs (the skull protects the brain) and helps us move. **Muscles** pull on bones to make us move."),
   ("retenir", "Heart and lungs", "The **heart** pumps blood round the body. The **lungs** take in air when we breathe in. Oxygen from the air goes into the blood. When we run, our heart beats faster and we breathe faster."),
   ("pieges", "Common mistakes", "- Bones are alive and grow.\n- The heart is not on the right side of the chest only; it is in the middle, slightly left.\n- Keep your body active.")],
  [("Example 1", "What protects the brain?", ["The skull is a hard bone.", "The skull."], "The skull", cards(["skull: protects brain", "ribs: protect heart and lungs", "muscles: move bones"], 1, 400, ch=40, size=14)),
   ("Example 2", "Why does your heart beat faster when you run?", ["Muscles need more oxygen.", "The heart pumps blood faster to bring it."], "Muscles need more oxygen", None)],
  (cards(["heart: pumps blood", "lungs: take in air", "bones: support", "muscles: movement"], 2, 400, ch=44, size=15), "Parts of the body and their jobs.", "Four boxes about the heart, lungs, bones and muscles."),
  [("m", "The heart...", "pumps blood", ["digests food", "hears sounds", "grows hair"], "Pumps blood."), ("m", "We breathe air into our...", "lungs", ["stomach", "heart", "knees"], "Lungs."), ("t", "Muscles help us to move.", True, "Yes.")],
  [("x", "Match the body part with its job.", [("lungs", "take in air"), ("heart", "pumps blood"), ("skull", "protects the brain")], "Jobs."), ("m", "When we run, we breathe...", "faster", ["slower", "not at all", "only through the ears"], "Faster.")],
  ("p", "Ngum counts his pulse: 20 beats in 15 seconds.", [("n", "How many beats in 1 minute (60 seconds)? (20 × 4)", 80, "15 seconds × 4 = 60 seconds, so 20 × 4 = 80.", "beats"), ("m", "After running, his pulse will be...", "faster", ["slower", "zero", "the same always"], "Faster.")]),
  [("Class 3 science body: the skeleton is made of...", "bones", ["muscles", "skin", "blood"], "Bones."),
   ("Class 3 science body: which organ pumps blood?", "the heart", ["the lungs", "the skull", "the stomach"], "Heart."),
   ("We use our lungs to...", "breathe", ["digest food", "see", "hear"], "Breathe."),
   ("Muscles pull on bones to...", "make us move", ["make us tall only", "make us hear", "make us taste"], "Movement."),
   ("The skull protects the...", "brain", ["heart", "lungs", "stomach"], "Brain.")],
  ["Pulse of about 80 beats per minute is only an example; a typical resting range for children is wider (to be checked); no health claims."], prereq=["class3-science-animal-groups-diet"])

lesson(ch, "teeth-senses", "Teeth and the senses", ["Name kinds of teeth and how to care for them.", "Say which organ gives which sense."],
  [("definition", "Teeth", "Children have 20 first (milk) teeth. Adults usually have up to 32 teeth. **Incisors** cut, **canines** tear, **molars** grind food. Teeth are covered with hard enamel."),
   ("retenir", "Care for teeth", "Brush your teeth in the morning and at night. Eat fewer sweets. Do not open bottles with your teeth. Visit a dentist or health worker if a tooth hurts."),
   ("pieges", "Common mistakes", "- Brushing helps, but sweet snacks all day cause decay.\n- Do not share toothbrushes.\n- First teeth fall out; new teeth grow in.")],
  [("Example 1", "Which teeth grind food?", ["Molars are at the back.", "They are flat and strong for grinding."], "Molars", cards(["incisors: cut", "canines: tear", "molars: grind"], 3, 400, ch=44, size=14)),
   ("Example 2", "Which organ lets you taste?", ["The tongue has taste buds.", "The tongue."], "The tongue", None)],
  (cards(["eyes: sight", "ears: hearing", "nose: smell", "tongue: taste", "skin: touch"], 3, 400, ch=44, size=14), "The five senses.", "Five boxes: eyes sight, ears hearing, nose smell, tongue taste, skin touch."),
  [("m", "Which teeth cut food?", "incisors", ["molars", "canines", "gums"], "Incisors."), ("n", "How many first (milk) teeth do children have?", 20, "Twenty."), ("m", "We feel hot and cold with the...", "skin", ["tongue", "ears", "eyes"], "Skin.")],
  [("x", "Match the teeth with their job.", [("incisors", "cut"), ("canines", "tear"), ("molars", "grind")], "Jobs."), ("t", "Brushing teeth twice a day helps to keep them healthy.", True, "Yes.")],
  ("p", "A child has lost 2 milk teeth.", [("n", "How many milk teeth are left if she had 20? (20 − 2)", 18, "18."), ("m", "What will grow in their place?", "new teeth", ["nothing", "bones of a goat", "stones"], "Second teeth.")]),
  [("Class 3 science teeth: teeth for grinding are the...", "molars", ["incisors", "canines", "lips"], "Molars."),
   ("Class 3 science senses: we taste with the...", "tongue", ["nose", "ears", "hair"], "Tongue."),
   ("How many milk teeth do children have?", "20", ["10", "32", "40"], "Twenty."),
   ("To keep teeth healthy we...", "brush them and eat fewer sweets", ["never brush", "open bottles with them", "share brushes"], "Care."),
   ("Our ears give us the sense of...", "hearing", ["sight", "taste", "smell"], "Hearing.")],
  [HNOTE + " Number of adult teeth (usually 32, including wisdom teeth) to be checked."], prereq=["class3-science-human-body"])

ch = p.chapter("food-health", "Food, health and disease", R)
lesson(ch, "balanced-diet", "A balanced diet", ["Name the food groups and what they do.", "Make a simple balanced meal."],
  [("definition", "Nutrients", "Food has **nutrients**. **Carbohydrates** (rice, yam, cassava, plantain) give **energy**. **Proteins** (beans, fish, eggs, meat) help us **grow and repair**. **Fats** (oil, groundnuts) give energy and keep us warm. **Vitamins and minerals** (fruit, vegetables) protect us. **Water** is also needed."),
   ("retenir", "Balanced diet", "A **balanced diet** has a little of each group in the right amounts. Eat plenty of vegetables and fruit, some protein, and enough energy food. Eat less sugar and less salt."),
   ("pieges", "Common mistakes", "- Too little food or only one kind of food can cause poor health.\n- Do not eat only sweets or fried food.\n- Wash fruit and vegetables.")],
  [("Example 1", "Which nutrient helps us grow and repair?", ["It is found in beans and fish.", "Protein."], "Protein", cards(["energy: carbohydrates", "grow: proteins", "protect: vitamins", "water"], 2, 400, ch=44, size=14)),
   ("Example 2", "Make a balanced meal from plantain, fish, eru and an orange.", ["Plantain gives energy; fish gives protein.", "Eru and orange give vitamins. This is balanced."], "Plantain, fish, eru and an orange", None)],
  (cards(["carbohydrates", "proteins", "fats", "vitamins and minerals", "water"], 3, 400, ch=44, size=13), "Parts of a balanced diet.", "Five boxes for the nutrients."),
  [("m", "Which gives energy?", "cassava", ["eru", "water", "an orange"], "Carbohydrate."), ("m", "Which is rich in protein?", "beans", ["rice", "sugar", "oil"], "Beans."), ("t", "A balanced diet includes fruit and vegetables.", True, "Yes.")],
  [("x", "Match the food with its nutrient.", [("rice", "carbohydrate"), ("fish", "protein"), ("orange", "vitamin")], "Nutrients."), ("m", "Which meal is the most balanced?", "plantain, fish, eru and an orange", ["only sweets", "only rice", "only soda"], "Variety.")],
  ("p", "A school meal: rice, beans, spinach and a banana.", [("m", "Which gives most energy?", "rice", ["spinach", "banana", "beans"], "Rice."), ("m", "Which helps growth and repair?", "beans", ["rice", "spinach", "banana"], "Beans.")]),
  [("Class 3 science diet: foods that help us grow and repair are...", "proteins", ["carbohydrates only", "salt", "sugar"], "Protein."),
   ("Class 3 science diet: a balanced diet has...", "different kinds of food", ["only sweets", "only rice", "nothing"], "Variety."),
   ("Vitamins and minerals are found in...", "fruit and vegetables", ["sugar only", "plastic", "salt only"], "Fruit."),
   ("Yam and cassava give mainly...", "energy", ["proteins", "water", "vitamins only"], "Energy."),
   ("We should eat less...", "sugar", ["vegetables", "fruit", "beans"], "Sugar.")],
  [HNOTE + " Nutrient groups follow the common school classification; foods are examples only."], prereq=["class3-science-teeth-senses"])

lesson(ch, "disease-prevention", "Germs and staying healthy", ["Say what germs are.", "Name ways to prevent malaria and diarrhoea."],
  [("definition", "Germs", "**Germs** are tiny living things that can make us ill. We cannot see them without a microscope. They spread through dirty hands, dirty water, unclean food, coughs and some insects."),
   ("retenir", "Malaria and diarrhoea", "**Malaria** is spread by the bite of some mosquitoes. Prevent it: sleep under a mosquito net, remove stagnant water, and see a health worker quickly for a fever. **Diarrhoea** can come from dirty water and food. Prevent it: wash hands, drink safe water, cover food, use a clean toilet."),
   ("pieges", "Common mistakes", "- Do not use medicine without a health worker.\n- Hand washing with soap really works.\n- Vaccines at the clinic protect children from some diseases.")],
  [("Example 1", "How can a family prevent malaria?", ["Mosquitoes bite at night.", "Sleep under a net and remove stagnant water."], "Use nets and remove stagnant water", cards(["net", "clean water", "wash hands", "vaccines"], 4, 400, ch=44, size=14)),
   ("Example 2", "Name two ways germs can spread.", ["Dirty hands carry germs.", "Dirty water also spreads them."], "Dirty hands and dirty water", None)],
  (cards(["wash hands with soap", "safe drinking water", "cover food", "sleep under a net"], 2, 400, ch=44, size=14), "Ways to prevent disease.", "Four boxes with ways to prevent disease."),
  [("m", "Malaria is spread by...", "mosquito bites", ["dirty shoes", "noise", "sunlight"], "Mosquitoes."), ("m", "Which helps prevent diarrhoea?", "washing hands with soap", ["eating in the dark", "drinking dirty water", "sharing cups"], "Soap."), ("t", "Germs are tiny living things.", True, "Yes.")],
  [("m", "A child has a fever. A parent should...", "take the child to a health worker", ["wait a week", "hide it", "give any medicine"], "Health worker."), ("x", "Match the disease with a way to prevent it.", [("malaria", "mosquito net"), ("diarrhoea", "safe water")], "Prevention.")],
  ("p", "A village health talk: 3 families use nets and 2 do not.", [("n", "How many families in all?", 5, "3 + 2 = 5."), ("m", "What should the 2 families do?", "use mosquito nets", ["avoid water", "sleep outside", "do nothing"], "Nets.")]),
  [("Class 3 science health: which prevents diarrhoea?", "washing hands with soap", ["not washing", "drinking dirty water", "sharing cups"], "Soap."),
   ("Class 3 science health: malaria is carried by...", "mosquitoes", ["ants", "dogs", "birds"], "Mosquitoes."),
   ("We can protect ourselves from malaria by sleeping...", "under a mosquito net", ["outside", "in the rain", "with no cover"], "Net."),
   ("Germs are...", "very small living things", ["big animals", "rocks", "clouds"], "Tiny."),
   ("Medicine should be taken...", "only as advised by a health worker", ["by guessing", "from friends", "with no advice"], "Health worker.")],
  [HNOTE + " Disease facts are general; Cameroon's health guidance (nets, vaccination schedule) to be checked."], prereq=["class3-science-balanced-diet"])

ch = p.chapter("matter-energy", "Water, matter and energy", R)
lesson(ch, "water-cycle", "The water cycle", ["Describe the water cycle.", "Name evaporation, condensation and rain."],
  [("definition", "Water cycle", "Water moves in a **cycle**. The Sun warms water in seas, rivers and lakes. Water turns into a gas called **water vapour**: this is **evaporation**. The vapour rises, cools and turns into tiny drops that make **clouds**: this is **condensation**."),
   ("retenir", "Rain", "When the drops in clouds get big and heavy, they fall as **rain**. Rain runs into streams and rivers and goes back to the sea. Then the cycle starts again."),
   ("pieges", "Common mistakes", "- Evaporation needs heat from the Sun.\n- Clouds are made of tiny drops of water, not smoke.\n- The water does not get used up; it moves round.")],
  [("Example 1", "What happens to sea water when the Sun warms it?", ["It becomes a gas.", "It evaporates."], "It evaporates", cards(["Sun warms water", "evaporation", "condensation: cloud", "rain"], 4, 400, ch=44, size=12)),
   ("Example 2", "What forms when water vapour cools?", ["It turns into drops.", "Clouds form."], "Clouds", None)],
  (cards(["evaporation", "condensation", "rain", "rivers to the sea"], 2, 400, ch=44, size=15), "Steps of the water cycle.", "Four boxes: evaporation, condensation, rain, rivers to the sea."),
  [("m", "Water turns to vapour by...", "evaporation", ["condensation", "freezing", "melting"], "Evaporation."), ("m", "Clouds form by...", "condensation", ["evaporation", "digestion", "growth"], "Condensation."), ("t", "The Sun helps water to evaporate.", True, "Yes.")],
  [("x", "Match the word with its meaning.", [("evaporation", "water becomes vapour"), ("condensation", "vapour becomes drops"), ("rain", "drops fall from clouds")], "Meanings."), ("m", "After rain, water flows into...", "rivers and the sea", ["the clouds first", "the Sun", "the moon"], "Rivers.")],
  ("p", "A pupil puts wet cloth in the sun. After an hour it is dry.", [("m", "Where did the water go?", "it evaporated into the air", ["it disappeared forever", "it went into the cloth", "it froze"], "Evaporation."), ("m", "What helped?", "heat from the Sun", ["cold", "darkness", "noise"], "Heat.")]),
  [("Class 3 science water cycle: water becomes vapour by...", "evaporation", ["condensation", "freezing", "growing"], "Evaporation."),
   ("Class 3 science water cycle: clouds are made of...", "tiny drops of water", ["smoke", "cotton", "dust only"], "Water drops."),
   ("What heats the water to make it evaporate?", "the Sun", ["the Moon", "the wind only", "the stars"], "Sun."),
   ("Rain falls from...", "clouds", ["the Moon", "trees", "rivers"], "Clouds."),
   ("The water cycle...", "goes round and round", ["happens once", "stops forever", "makes salt"], "Cycle.")],
  [NOTE], prereq=["class3-science-disease-prevention"])

lesson(ch, "states-of-matter", "Solids, liquids and gases", ["Name the three states of matter.", "Say how water changes state."],
  [("definition", "States of matter", "Everything is made of **matter**. Matter can be a **solid**, a **liquid** or a **gas**. A solid keeps its shape (stone, wood). A liquid flows and takes the shape of its container (water, oil). A gas spreads out to fill space (air, steam)."),
   ("retenir", "Changes", "**Melting**: solid → liquid (ice melts). **Freezing**: liquid → solid (water freezes at 0 degrees Celsius). **Evaporating** or **boiling**: liquid → gas (water boils at 100 degrees Celsius). **Condensing**: gas → liquid."),
   ("pieges", "Common mistakes", "- Steam is a gas (water vapour); the white cloud we see is tiny drops.\n- Air is matter too: it takes up space.\n- Be careful with hot water and boiling liquids.")],
  [("Example 1", "Ice melts in the sun. What state change is this?", ["Ice is a solid.", "It becomes water, a liquid: melting."], "Melting", cards(["solid: ice", "liquid: water", "gas: steam"], 3, 400, ch=44, size=14)),
   ("Example 2", "Is oil a solid, a liquid or a gas?", ["Oil flows.", "It is a liquid."], "A liquid", None)],
  (cards(["melting", "freezing", "boiling", "condensing"], 4, 400, ch=44, size=13), "Changes of state.", "Four boxes: melting, freezing, boiling, condensing."),
  [("m", "Which is a solid?", "a stone", ["water", "air", "oil"], "Stone."), ("m", "Water changes to ice by...", "freezing", ["melting", "boiling", "growing"], "Freezing."), ("n", "At how many degrees Celsius does water boil (at sea level)?", 100, "100.", "degrees Celsius")],
  [("x", "Match the state with an example.", [("solid", "wood"), ("liquid", "milk"), ("gas", "air")], "States."), ("t", "A liquid takes the shape of its container.", True, "Yes.")],
  ("p", "A pupil heats ice in a pan (with an adult). It melts, then the water warms up.", [("m", "What is the first change?", "melting", ["boiling", "freezing", "condensing"], "Melting."), ("n", "Water freezes at how many degrees Celsius?", 0, "0.", "degrees Celsius")]),
  [("Class 3 science matter: a liquid...", "flows", ["keeps its shape always", "cannot be poured", "is always hard"], "Flows."),
   ("Class 3 science matter: ice melting is a change from...", "solid to liquid", ["gas to liquid", "liquid to gas", "solid to gas"], "Melting."),
   ("Air is a...", "gas", ["solid", "liquid", "stone"], "Gas."),
   ("Water boils at about...", "100 degrees Celsius", ["10 degrees Celsius", "0 degrees Celsius", "1000 degrees Celsius"], "100."),
   ("Which is a solid?", "wood", ["milk", "air", "oil"], "Wood.")],
  ["Boiling point 100 degrees Celsius and freezing point 0 are for pure water at sea level; kept simple."], prereq=["class3-science-water-cycle"])

lesson(ch, "forces", "Forces: push, pull and friction", ["Say that a force is a push or a pull.", "Say what friction does."],
  [("definition", "Forces", "A **force** is a **push** or a **pull**. Forces can make things start to move, stop, go faster or slower, or change direction. We measure force in **newtons** (you do not need to learn this yet)."),
   ("retenir", "Friction and gravity", "**Friction** is a force when two things rub together. It slows things down. Rough surfaces have more friction than smooth ones. **Gravity** pulls things down towards the Earth. That is why a dropped ball falls."),
   ("pieges", "Common mistakes", "- Friction is not always bad: it stops our shoes from slipping.\n- Heavier things are pulled down by gravity with a bigger force, but all things fall to the ground.\n- Pushing and pulling are both forces.")],
  [("Example 1", "You open a door by pulling the handle. What force is it?", ["You bring the door towards you.", "A pull."], "A pull", cards(["push", "pull", "friction", "gravity"], 4, 400, ch=44, size=14)),
   ("Example 2", "Why does a ball roll further on a smooth floor than on grass?", ["There is less friction on a smooth floor.", "It slows down less."], "Less friction", None)],
  (cards(["push: start", "pull: bring", "friction: slows", "gravity: pulls down"], 2, 400, ch=44, size=14), "Forces.", "Four boxes about push, pull, friction and gravity."),
  [("m", "A force is a...", "push or a pull", ["colour", "sound", "smell"], "Push or pull."), ("m", "Gravity pulls things...", "down towards the Earth", ["up to the sky", "sideways only", "to the Moon"], "Down."), ("t", "Friction slows moving things.", True, "Yes.")],
  [("x", "Match each action with the force.", [("kicking a ball", "push"), ("opening a drawer", "pull"), ("a dropped coin falling", "gravity")], "Forces."), ("m", "Which surface has the most friction?", "rough ground", ["ice", "polished floor", "wet tile"], "Rough.")],
  ("p", "Pupils slide a book on a table, then on a rough mat.", [("m", "On which surface does the book stop sooner?", "the rough mat", ["the smooth table", "both the same", "neither"], "More friction."), ("m", "Why?", "there is more friction", ["there is less friction", "gravity stops", "air is heavy"], "Friction.")]),
  [("Class 3 science forces: pushing and pulling are...", "forces", ["colours", "sounds", "smells"], "Forces."),
   ("Class 3 science forces: friction...", "slows things down", ["speeds all things", "makes light", "makes sound"], "Slows."),
   ("A dropped mango falls because of...", "gravity", ["magnetism", "friction", "light"], "Gravity."),
   ("Which has the least friction?", "ice", ["sand", "grass", "rough mat"], "Ice."),
   ("Kicking a ball is a...", "push", ["pull", "light", "sound"], "Push.")],
  ["Newtons are mentioned only in passing; remove if not in the syllabus."], prereq=["class3-science-states-of-matter"])

lesson(ch, "light-shadows", "Light and shadows", ["Say where light comes from.", "Explain how a shadow is made."],
  [("definition", "Light", "**Light** lets us see. Sources of light: the **Sun**, a **fire**, a **lamp**, a **torch**. The Moon does not make light: it reflects the Sun's light. Light travels in **straight lines**."),
   ("retenir", "Shadows", "A **shadow** forms when an **opaque** object (one that light cannot pass through) blocks light. **Transparent** things (glass) let light through. **Translucent** things (tracing paper) let some through. Shadows are longest in the early morning and late afternoon, and shortest at midday."),
   ("pieges", "Common mistakes", "- A shadow is not an object; it is the absence of light.\n- Never look straight at the Sun.\n- Shadows point away from the light.")],
  [("Example 1", "Which of these makes a shadow: a wooden board or clear glass?", ["Wood blocks light.", "The wooden board makes a shadow."], "The wooden board", shapes([CIRCLE(40, 70, 22, fill="yellow"), RECT(150, 40, 20, 60, fill="orange"), RECT(190, 90, 100, 10, fill="grey"), T(40, 115, "light", 13, bold=True), T(160, 120, "object", 13, bold=True), T(240, 120, "shadow", 13, bold=True)], 330, 140)),
   ("Example 2", "At what time of day is a shadow shortest?", ["The Sun is high in the sky.", "Around midday."], "Midday", None)],
  (shapes([CIRCLE(40, 70, 22, fill="yellow"), RECT(150, 40, 20, 60, fill="orange"), RECT(190, 90, 100, 10, fill="grey"), T(40, 115, "light", 13, bold=True), T(160, 120, "object", 13, bold=True), T(240, 120, "shadow", 13, bold=True)], 330, 140), "A shadow forms behind an object.", "A yellow light, an orange object and a grey shadow behind it."),
  [("m", "Which is a source of light?", "a torch", ["the Moon", "a mirror", "a stone"], "Torch."), ("m", "Which material is transparent?", "clear glass", ["wood", "metal", "a brick"], "Glass."), ("t", "Light travels in straight lines.", True, "Yes.")],
  [("x", "Match the word with its meaning.", [("opaque", "no light passes"), ("transparent", "all light passes"), ("translucent", "some light passes")], "Words."), ("m", "A shadow is shortest at...", "midday", ["sunrise", "sunset", "midnight"], "Midday.")],
  ("p", "A pupil holds a book between a torch and a wall.", [("m", "What appears on the wall?", "a shadow", ["a colour", "a sound", "nothing"], "A shadow."), ("m", "The book is...", "opaque", ["transparent", "translucent", "a source of light"], "Opaque.")]),
  [("Class 3 science light: shadows are made when light is...", "blocked", ["made", "heard", "smelled"], "Blocked."),
   ("Class 3 science light: the Moon...", "reflects light", ["makes light", "is a lamp", "is a fire"], "Reflects."),
   ("Which material lets light pass through?", "clear glass", ["wood", "brick", "metal"], "Glass."),
   ("A source of light is...", "the Sun", ["a mirror", "the Moon", "a stone"], "Sun."),
   ("Shadows are longest in the...", "early morning", ["midday", "never", "at noon sharp"], "Morning.")],
  ["Shadow length claim: long when the Sun is low, short when high (in the tropics near noon the shadow is very short)."], prereq=["class3-science-forces"])

lesson(ch, "magnets", "Magnets", ["Say what a magnet attracts.", "Name the poles."],
  [("definition", "Magnets", "A **magnet** attracts things made of **iron** or **steel**, such as nails, pins and paper clips. It does not attract wood, plastic, glass or paper. Magnets can be bar-shaped, horseshoe-shaped or round."),
   ("retenir", "Poles", "A magnet has two **poles**: **north** and **south**. **Opposite poles attract** (N and S). **Like poles repel** (N and N, or S and S). A magnet pulls strongest at its poles."),
   ("pieges", "Common mistakes", "- Magnets do not attract all metals. Aluminium, copper and gold are not attracted.\n- Keep magnets away from phones, cards and screens.\n- Like poles push apart.")],
  [("Example 1", "Will a magnet pick up a plastic ruler?", ["Plastic is not iron.", "No."], "No", cards(["attracts: nail", "attracts: pin", "no: wood", "no: plastic"], 2, 400, ch=44, size=14)),
   ("Example 2", "Two north poles are brought together. What happens?", ["Like poles repel.", "They push apart."], "They repel", None)],
  (shapes([RECT(50, 40, 70, 30, fill="red"), RECT(120, 40, 70, 30, fill="blue"), T(85, 60, "N", 16, bold=True, color="white"), T(155, 60, "S", 16, bold=True, color="white"), T(120, 100, "a bar magnet", 13, bold=True)], 240, 120), "A bar magnet with N and S poles.", "A bar magnet with a red north end and a blue south end."),
  [("m", "A magnet attracts...", "an iron nail", ["a wooden spoon", "a plastic pen", "a glass cup"], "Iron."), ("m", "Opposite poles...", "attract", ["repel", "melt", "grow"], "Attract."), ("t", "Like poles repel.", True, "Yes.")],
  [("x", "Match the object with whether a magnet attracts it.", [("steel pin", "attracted"), ("wooden stick", "not attracted")], "Test."), ("m", "A magnet pulls strongest at its...", "poles", ["middle", "colour", "label"], "Poles.")],
  ("p", "Neba tests 6 things with a magnet: a nail, a coin of copper, a pin, a plastic cup, a paper clip and a key of steel.", [("n", "How many of these contain iron or steel (nail, pin, paper clip, steel key)?", 4, "Four.", None), ("m", "Will the plastic cup be attracted?", "no", ["yes", "only at night", "only wet"], "Plastic is not magnetic.")]),
  [("Class 3 science magnets: a magnet attracts...", "iron and steel", ["wood", "plastic", "paper"], "Iron."),
   ("Class 3 science magnets: opposite poles...", "attract", ["repel", "melt", "float"], "Attract."),
   ("A magnet has how many poles?", "2", ["1", "3", "10"], "Two."),
   ("Like poles...", "repel", ["attract", "melt", "break"], "Repel."),
   ("Which is NOT attracted?", "a plastic pen", ["a steel nail", "an iron pin", "a steel key"], "Plastic.")],
  ["Which coins are magnetic varies; the lesson avoids stating anything about FCFA coins."], prereq=["class3-science-light-shadows"])

ch = p.chapter("environment", "Soil and the environment", R)
lesson(ch, "soil", "Soil", ["Name kinds of soil.", "Say why soil is important."],
  [("definition", "Soil", "**Soil** is the top layer of the ground. It is made of tiny pieces of rock, **humus** (rotted plants and animals), water and air. Plants grow in soil and take water from it."),
   ("retenir", "Kinds of soil", "**Sandy soil** has big grains, drains water quickly. **Clay soil** has tiny grains, holds water and gets sticky. **Loam** is a mix with much humus; it is good for growing crops. In much of Cameroon, red and dark volcanic soils are good for farming (for example near Mount Cameroon)."),
   ("pieges", "Common mistakes", "- Soil is not just dirt; it is full of living things such as earthworms.\n- Heavy rain can wash soil away (erosion).\n- Planting trees and grass holds the soil.")],
  [("Example 1", "Which soil drains water fastest?", ["The grains are big.", "Sandy soil."], "Sandy soil", cards(["sand: drains fast", "clay: holds water", "loam: best for crops"], 3, 400, ch=44, size=12)),
   ("Example 2", "How can we stop rain from washing soil away?", ["Plant trees and grass.", "Roots hold the soil."], "Plant trees and grass", None)],
  (cards(["sandy", "clay", "loam"], 3, 400, ch=44, size=18), "Kinds of soil.", "Three boxes: sandy, clay, loam."),
  [("m", "Which soil is best for growing crops?", "loam", ["pure sand", "pure clay", "gravel"], "Loam."), ("m", "Humus is made of...", "rotted plants and animals", ["stones", "plastic", "metal"], "Rotted matter."), ("t", "Plants take water from soil.", True, "Yes.")],
  [("x", "Match the soil with a property.", [("sandy", "drains fast"), ("clay", "holds water"), ("loam", "rich in humus")], "Properties."), ("m", "Washing away of soil by rain is called...", "erosion", ["evaporation", "melting", "growth"], "Erosion.")],
  ("p", "A farmer has 3 plots: sandy, clay and loam. She grows beans on the plot that holds water well and drains well.", [("m", "Which plot is best?", "loam", ["sandy", "clay", "none"], "Loam."), ("m", "What can she plant to stop erosion on a slope?", "trees or grass", ["nothing", "plastic bags", "stones only"], "Plants hold soil.")]),
  [("Class 3 science soil: the best soil for crops is...", "loam", ["sand only", "clay only", "gravel"], "Loam."),
   ("Class 3 science soil: soil that holds water and is sticky is...", "clay", ["sand", "loam", "gravel"], "Clay."),
   ("Humus comes from...", "rotted plants and animals", ["rocks only", "plastic", "paint"], "Humus."),
   ("Erosion is...", "washing away of soil", ["growing of soil", "making rain", "melting"], "Erosion."),
   ("Which holds soil together?", "roots of plants", ["plastic", "wind", "noise"], "Roots.")],
  ["Soil types are textbook-level; the remark about volcanic soils near Mount Cameroon is a common geography fact; check wording."], prereq=["class3-science-magnets"])

lesson(ch, "environment-care", "Caring for the environment", ["Say why we protect forests, water and air.", "Say what each person can do."],
  [("definition", "Our environment", "Our **environment** is the land, water, air, plants and animals around us. People need a clean environment to stay healthy. Forests give wood, food and medicine plants, shelter for animals, and help to keep the air clean."),
   ("retenir", "Problems and solutions", "**Problems**: litter, burning plastic, cutting too many trees, dirty rivers, soil erosion. **What we can do**: put rubbish in a bin, plant trees, save water, reuse and recycle where possible, take care of school gardens."),
   ("pieges", "Common mistakes", "- Burning plastic makes harmful smoke.\n- Cutting a tree needs a new tree to be planted.\n- Small actions by everybody make a big difference.")],
  [("Example 1", "Name two things you can do to look after your school.", ["Put litter in a bin.", "Plant a tree or flowers."], "Use bins and plant trees", cards(["use bins", "plant trees", "save water", "reuse"], 4, 400, ch=44, size=13)),
   ("Example 2", "Why should we not throw rubbish in a river?", ["It makes the water dirty.", "Fish and people are harmed."], "It makes the water dirty", None)],
  (cards(["problem: litter", "problem: cutting trees", "action: plant trees", "action: use bins"], 2, 400, ch=44, size=14), "Problems and actions.", "Four boxes with problems and actions."),
  [("m", "A good thing to do for the environment is to...", "plant trees", ["burn plastic", "throw litter", "waste water"], "Plant trees."), ("t", "Burning plastic is safe.", False, "It makes harmful smoke."), ("m", "Forests give...", "wood and shelter for animals", ["only noise", "plastic", "metal only"], "Forests.")],
  [("m", "Which is a problem for the environment?", "litter", ["a bin", "a tree", "a clean river"], "Litter."), ("x", "Match the problem with a good action.", [("litter", "use a bin"), ("cut trees", "plant new trees")], "Actions.")],
  ("p", "A school club plants 5 trees each month.", [("n", "How many trees after 4 months?", 20, "5 × 4 = 20."), ("n", "If 2 trees do not grow, how many survive? (20 − 2)", 18, "18.")]),
  [("Class 3 science environment: we can help by...", "using a bin", ["throwing litter", "burning plastic", "wasting water"], "Bin."),
   ("Class 3 science environment: forests help to...", "keep the air clean", ["make noise", "dirty rivers", "melt ice"], "Air."),
   ("Burning plastic...", "makes harmful smoke", ["is good for plants", "makes rain", "is safe"], "Harmful."),
   ("Which is a good habit?", "saving water", ["wasting water", "spilling oil", "littering"], "Save."),
   ("The environment means...", "the land, water, air, plants and animals around us", ["only our house", "only the sky", "only a bin"], "Around us.")],
  ["Environmental advice is general; check local rules and what recycling exists."], prereq=["class3-science-soil"])

p.write()
