import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from p13_kit import *
from p13_fig import *

p = newpack("class2-english", "English Language — Class 2", "Class 2", "english",
    "Class 2 English: sounds (sh, ch, th, magic e), nouns, verbs, adjectives, pronouns, prepositions, opposites, questions, reading, simple writing and speaking.",
    REF % "Level I (Class 2) — English Language")
R = p.programRef
NOTE = "Word lists and grammar terms used at this level are to be checked against the official syllabus; British spelling is used."

ch = p.chapter("sounds-spelling", "Sounds and spelling", R)
lesson(ch, "digraphs", "Sounds sh, ch and th", ["Read words with sh, ch and th.", "Spell simple words with these sounds."],
  [("definition", "Two letters, one sound", "Sometimes two letters make one sound. **sh** says shh: **ship, fish, shop**. **ch** says chh: **chin, chair, chop**. **th** says th: **this, thin, bath**."),
   ("retenir", "Where to find them", "At the start: shop, chair, thumb. At the end: fish, much, bath. Say the sound, then the whole word."),
   ("pieges", "Common mistakes", "- sh is not s. Say *ship*, not *sip*.\n- ch is not c. Say *chin*, not *cin*.\n- th has two letters, so write both.")],
  [("Example 1", "Which two letters make the first sound in ship?", ["Say ship slowly: sh-i-p.", "The first sound is sh."], "sh", cards(["sh: ship", "ch: chair", "th: thumb"], 3, 400, ch=50, size=16)),
   ("Example 2", "Fill the gap: fi___ (a pet in water).", ["The word is fish.", "It ends with sh."], "sh", None)],
  (cards(["ship", "fish", "chair", "chin", "thumb", "bath"], 3, 400, ch=46, size=18), "Words with sh, ch and th.", "Six boxes with the words ship, fish, chair, chin, thumb and bath."),
  [("m", "Which word has the sound sh?", "shop", ["top", "chop", "stop"], "sh-o-p."), ("m", "Which word has the sound ch?", "chair", ["hair", "share", "stair"], "ch-air."), ("m", "Which word has the sound th?", "bath", ["bat", "back", "bash"], "ba-th.")],
  [("x", "Match the word with its sound.", [("ship", "sh"), ("chin", "ch"), ("thin", "th")], "Listen to the first sound."), ("t", "The word fish ends with the sound sh.", True, "fi-sh.")],
  ("p", "Read: The fish is in the dish. Ngu has a thin chain.", [("m", "Which word has sh?", "fish", ["thin", "chain", "Ngu"], "fi-sh."), ("m", "Which word has th?", "thin", ["fish", "chain", "dish"], "th-in.")]),
  [("Class 2 English digraphs: which word has the sound sh?", "wish", ["with", "witch", "wit"], "wi-sh."),
   ("Class 2 English digraphs: which word has the sound ch?", "much", ["mush", "muff", "mug"], "mu-ch."),
   ("Which word begins with th?", "thumb", ["tomb", "sum", "chum"], "th-umb."),
   ("Two letters that make one sound are called a...", "digraph", ["noun", "verb", "capital"], "Digraph."),
   ("Which word has sh at the end?", "dish", ["chin", "this", "chop"], "di-sh.")],
  [NOTE])

lesson(ch, "magic-e", "The magic e: long vowel sounds", ["Read words with magic e.", "Change a short vowel word to a long vowel word."],
  [("definition", "Magic e", "A silent **e** at the end of a word can change the vowel sound. **cap** becomes **cape**. **pin** becomes **pine**. **hop** becomes **hope**. The vowel says its name."),
   ("retenir", "Pairs", "a-e: cap, cape; mat, mate. i-e: kit, kite; bit, bite. o-e: hop, hope; not, note. u-e: cub, cube; tub, tube."),
   ("pieges", "Common mistakes", "- The e at the end is silent. Do not say it.\n- Magic e works on the vowel before it.\n- Not all words follow the rule, e.g. *have*.")],
  [("Example 1", "Add magic e to kit. What is the new word?", ["Kit becomes kite.", "The i now says its name."], "kite", cards(["cap → cape", "kit → kite", "hop → hope"], 3, 400, ch=50, size=16)),
   ("Example 2", "Which word has a silent e: cake or cat?", ["Cake ends with e.", "The e is silent. The a says its name."], "cake", None)],
  (cards(["cap → cape", "pin → pine", "tub → tube", "not → note"], 2, 400, ch=44, size=18), "Magic e changes the word.", "Four boxes showing words and their magic e partners."),
  [("m", "Add magic e to hop.", "hope", ["hoop", "hopp", "hep"], "hop → hope."), ("m", "Which word has the magic e?", "bike", ["bit", "big", "bin"], "bike."), ("m", "Which word has the long a sound?", "cake", ["cat", "cap", "can"], "cake.")],
  [("x", "Match the short word with its magic e word.", [("mat", "mate"), ("pin", "pine"), ("cub", "cube")], "Add e."), ("t", "The e at the end of cake is said out loud.", False, "It is silent.")],
  ("p", "Read the words in Bih's list: kite, home, cube, plate.", [("m", "Which word has the long o sound?", "home", ["kite", "cube", "plate"], "h-o-me."), ("m", "Which word has the long u sound?", "cube", ["kite", "home", "plate"], "c-u-be.")]),
  [("Class 2 English magic e: kit with magic e is...", "kite", ["kitt", "keat", "kiet"], "kite."),
   ("Class 2 English magic e: which word has a long vowel?", "note", ["not", "nod", "net"], "note."),
   ("Which word has the long i sound?", "time", ["tin", "tip", "tap"], "time."),
   ("The e in the word cake is...", "silent", ["loud", "a capital", "a number"], "Silent."),
   ("Tub with magic e is...", "tube", ["tubb", "tuub", "teb"], "tube.")],
  [NOTE], prereq=["class2-english-digraphs"])

lesson(ch, "blends-spelling", "Blends and spelling words", ["Read words that begin with two consonants.", "Spell a few common words."],
  [("definition", "Blends", "A **blend** has two consonant sounds said together. **bl**: black, blue. **st**: stop, star. **tr**: tree, train. **gr**: green, grass. **pl**: plant, play. Say both sounds."),
   ("methode", "Spell it", "1. Say the word slowly. 2. Write each sound. 3. Look at the word. Does it look right? 4. Check in a book. Practice: look, say, cover, write, check."),
   ("pieges", "Common mistakes", "- Do not drop a letter: *stop*, not *sop*.\n- Say both sounds in a blend.\n- Double letters: *egg, doll, hill*.")],
  [("Example 1", "Which blend starts the word tree?", ["Say tree slowly: t-r-ee.", "The blend is tr."], "tr", cards(["bl: blue", "st: star", "tr: tree", "gr: green"], 2, 400, ch=44, size=18)),
   ("Example 2", "Spell the word that names the colour of grass.", ["Grass is green.", "g-r-e-e-n."], "green", None)],
  (cards(["black", "stop", "tree", "green", "plant", "frog"], 3, 400, ch=44, size=18), "Words with blends.", "Six boxes with black, stop, tree, green, plant and frog."),
  [("m", "Which word starts with the blend st?", "star", ["sun", "tar", "sat"], "st-ar."), ("m", "Which word starts with the blend gr?", "grass", ["girl", "rag", "got"], "gr-ass."), ("m", "Which is spelt right?", "frog", ["forg", "frgo", "fogr"], "f-r-o-g.")],
  [("x", "Match the blend to a word.", [("bl", "blue"), ("tr", "train"), ("pl", "plate")], "First two sounds."), ("t", "The word stop starts with the blend st.", True, "st-op.")],
  ("p", "Teacher spells with the class.", [("m", "Which word has the blend fl?", "flag", ["fag", "lag", "gag"], "fl-ag."), ("m", "Which word is spelt right?", "train", ["trian", "tran", "tarin"], "t-r-ai-n.")]),
  [("Class 2 English blends: the first two sounds of black are...", "bl", ["ck", "ac", "lk"], "bl."),
   ("Class 2 English blends: which word starts with tr?", "truck", ["tuck", "rock", "ruck"], "tr-uck."),
   ("Which is spelt right?", "green", ["gren", "gree", "grene"], "green."),
   ("Which word has a double letter?", "doll", ["dog", "dot", "dig"], "ll."),
   ("A blend has...", "two consonant sounds said together", ["one vowel", "no sound", "two vowels only"], "Two consonants.")],
  [NOTE], prereq=["class2-english-digraphs"])

ch = p.chapter("grammar", "Words and grammar", R)
lesson(ch, "singular-plural", "One and many: singular and plural", ["Say if a noun is one or many.", "Make plurals with s and es."],
  [("definition", "Singular and plural", "**Singular** means one: a book. **Plural** means more than one: books. Most nouns add **s**: dog → dogs, mango → mangoes (add es after o in some words)."),
   ("retenir", "Add es", "Words that end in **s, x, sh, ch** add **es**: bus → buses, box → boxes, dish → dishes, church → churches."),
   ("pieges", "Common mistakes", "- Some plurals are different: child → children, man → men, foot → feet.\n- Do not add s to a plural twice.\n- *Fish* can be one or many.")],
  [("Example 1", "Write the plural of cat.", ["Add s.", "cats."], "cats", cards(["one cat", "two cats"], 2, 300, ch=44, size=18)),
   ("Example 2", "Write the plural of box.", ["Box ends with x.", "Add es: boxes."], "boxes", None)],
  (cards(["one pen → pens", "one bus → buses", "one dish → dishes", "one child → children"], 2, 400, ch=44, size=15), "Singular and plural.", "Four boxes with singular and plural words."),
  [("m", "The plural of pen is...", "pens", ["pen", "penes", "pen's"], "Add s."), ("m", "The plural of bus is...", "buses", ["buss", "buss'", "bus"], "Add es."), ("m", "The plural of child is...", "children", ["childs", "childes", "childen"], "Irregular.")],
  [("x", "Match the singular and the plural.", [("man", "men"), ("foot", "feet"), ("tooth", "teeth")], "Special plurals."), ("t", "The plural of dish is dishs.", False, "dish → dishes.")],
  ("p", "Ada counts things in the classroom: one desk, four chairs, one box, three books.", [("m", "Which word is plural?", "chairs", ["desk", "box", "one"], "Chairs is more than one."), ("m", "Write the plural of box.", "boxes", ["boxs", "box", "boxies"], "boxes.")]),
  [("Class 2 English plurals: the plural of book is...", "books", ["bookes", "book", "bookies"], "Add s."),
   ("Class 2 English plurals: the plural of church is...", "churches", ["churchs", "church", "churchies"], "Add es."),
   ("Singular means...", "one", ["many", "none", "big"], "One."),
   ("The plural of man is...", "men", ["mans", "manes", "mens"], "Irregular."),
   ("The plural of fox is...", "foxes", ["foxs", "fox", "foxies"], "Add es.")],
  [NOTE], prereq=["class2-english-blends-spelling"])

lesson(ch, "verbs-present-past", "Verbs: now and before", ["Use is, am and are.", "Add -ed to talk about the past."],
  [("definition", "Verbs now", "Use **am** with I, **is** with one person or thing, and **are** with more than one: I am, she is, they are. We say *Ada plays* now."),
   ("retenir", "Verbs before", "To talk about something that is finished, many verbs add **-ed**: play → played, walk → walked, jump → jumped. Some verbs change: go → went, eat → ate, see → saw."),
   ("pieges", "Common mistakes", "- *I am*, not *I is*.\n- *went*, not *goed*.\n- Words that end in e just add d: like → liked.")],
  [("Example 1", "Change to the past: I walk to school.", ["Add -ed to walk.", "I walked to school."], "I walked to school.", cards(["walk → walked", "play → played", "go → went", "eat → ate"], 2, 400, ch=44, size=18)),
   ("Example 2", "Fill the gap: The girls ___ happy. (is / are)", ["Girls is more than one.", "Use are."], "are", None)],
  (cards(["I am", "he is", "she is", "they are"], 4, 400, ch=44, size=16), "Am, is and are.", "Four boxes: I am, he is, she is, they are."),
  [("m", "We ___ at school.", "are", ["is", "am", "be"], "We are."), ("m", "Yesterday I ___ football. (play)", "played", ["play", "plays", "playing"], "Past: played."), ("m", "Yesterday she ___ to market. (go)", "went", ["goed", "go", "goes"], "went.")],
  [("x", "Match the verb with its past.", [("walk", "walked"), ("go", "went"), ("eat", "ate")], "Past forms."), ("t", "We say: I is a pupil.", False, "I am a pupil.")],
  ("p", "Neba tells about yesterday: I (walk) to the market and I (see) my aunt.", [("m", "Past of walk:", "walked", ["walks", "walk", "walking"], "walked."), ("m", "Past of see:", "saw", ["seed", "seen", "sees"], "saw.")]),
  [("Class 2 English verbs: they ___ my friends.", "are", ["is", "am", "be"], "They are."),
   ("Class 2 English verbs: the past of jump is...", "jumped", ["jumps", "jumpen", "jump"], "jumped."),
   ("The past of eat is...", "ate", ["eated", "eats", "eating"], "ate."),
   ("Which is right?", "She is tall.", ["She am tall.", "She are tall.", "She be tall."], "She is."),
   ("The past of like is...", "liked", ["likeed", "liking", "likes"], "liked.")],
  [NOTE], prereq=["class2-english-singular-plural"])

lesson(ch, "adjectives-pronouns", "Describing words and pronouns", ["Use adjectives to describe.", "Use he, she, it, they."],
  [("definition", "Adjectives", "An **adjective** describes a noun: a **big** goat, a **sweet** mango, **three** hens. It tells size, colour, feel, taste or number."),
   ("retenir", "Pronouns", "A **pronoun** takes the place of a noun. Ada → **she**. Kofi → **he**. The dog → **it**. Ada and Kofi → **they**. Me and my friend → **we**."),
   ("pieges", "Common mistakes", "- Do not repeat the name again and again: *Ada is tall. She is kind.*\n- *he* is for a boy or man, *she* for a girl or woman.\n- *they* is for more than one.")],
  [("Example 1", "Replace the name: Ada is kind. ___ helps her mother.", ["Ada is a girl.", "Use she: She helps her mother."], "She", cards(["Ada → she", "Kofi → he", "dog → it", "boys → they"], 2, 400, ch=44, size=18)),
   ("Example 2", "Find the adjective: a juicy orange.", ["Orange is the noun.", "Juicy describes it."], "juicy", None)],
  (cards(["he", "she", "it", "they", "we", "I"], 3, 400, ch=44, size=22), "Some pronouns.", "Six boxes with he, she, it, they, we, I."),
  [("m", "Kofi is my brother. ___ is ten.", "He", ["She", "It", "They"], "Boy: he."), ("m", "The hens are in the yard. ___ eat corn.", "They", ["She", "He", "It"], "More than one: they."), ("m", "Find the adjective: a cold drink.", "cold", ["a", "drink", "none"], "Cold.")],
  [("x", "Match the noun with the pronoun.", [("my mother", "she"), ("my father", "he"), ("the goats", "they")], "Choose the pronoun."), ("t", "It is used for a boy.", False, "He is for a boy.")],
  ("p", "Read: Nkeng has a small dog. It is black. It likes bones.", [("m", "Which word is an adjective?", "small", ["dog", "likes", "bones"], "small."), ("m", "What does It mean?", "the dog", ["Nkeng", "the bones", "the house"], "It = the dog.")]),
  [("Class 2 English pronouns: Ada is a girl. ___ is clever.", "She", ["He", "It", "They"], "She."),
   ("Class 2 English adjectives: which word describes a noun?", "red", ["run", "and", "at"], "Red."),
   ("Mama and I go to market. ___ buy yams.", "We", ["He", "She", "It"], "We."),
   ("A pronoun takes the place of a...", "noun", ["verb", "full stop", "letter"], "Noun."),
   ("The pupils sing. ___ are happy.", "They", ["She", "He", "It"], "They.")],
  [NOTE], prereq=["class2-english-verbs-present-past"])

lesson(ch, "prepositions-opposites", "Position words and opposites", ["Use in, on, under, behind, between.", "Say the opposite of a word."],
  [("definition", "Position words", "**Prepositions** tell where something is: The book is **on** the desk. The cat is **under** the chair. The ball is **in** the box. The tree is **behind** the house."),
   ("retenir", "Opposites", "Opposites mean the reverse. big – small. hot – cold. up – down. open – close. happy – sad. day – night. full – empty. old – new."),
   ("pieges", "Common mistakes", "- *in* is inside; *on* is on top.\n- The opposite of big is small, not little (that is almost the same).\n- Look at the picture to choose the word.")],
  [("Example 1", "Where is the ball? It is in a box.", ["The ball is inside the box.", "The word is in."], "in", shapes([RECT(40, 50, 100, 60, fill="lightyellow"), CIRCLE(90, 80, 16, fill="orange"), T(90, 130, "in", 14, bold=True), RECT(210, 70, 100, 40, fill="lightyellow"), CIRCLE(260, 52, 16, fill="orange"), T(260, 130, "on", 14, bold=True)], 360, 150)),
   ("Example 2", "Say the opposite of hot.", ["Think of ice.", "The opposite is cold."], "cold", None)],
  (shapes([RECT(40, 50, 100, 60, fill="lightyellow"), CIRCLE(90, 80, 16, fill="orange"), T(90, 130, "in", 14, bold=True), RECT(210, 70, 100, 40, fill="lightyellow"), CIRCLE(260, 52, 16, fill="orange"), T(260, 130, "on", 14, bold=True)], 360, 150), "A ball in a box and a ball on a table.", "A ball inside a box and a ball on top of a table."),
  [("m", "The cat sleeps ___ the bed. (below the bed)", "under", ["on", "in", "at"], "Under."), ("m", "The opposite of big is...", "small", ["tall", "long", "wide"], "Small."), ("m", "The opposite of day is...", "night", ["noon", "evening", "morning"], "Night.")],
  [("x", "Match the opposites.", [("hot", "cold"), ("up", "down"), ("open", "close"), ("happy", "sad")], "Reverse."), ("t", "The opposite of full is empty.", True, "Yes.")],
  ("p", "Ada says: The pen is ___ the desk and the bag is ___ the desk.", [("m", "The pen is on top of the desk. Which word fits?", "on", ["under", "in", "behind"], "On."), ("m", "The bag is below the desk. Which word fits?", "under", ["on", "in", "at"], "Under.")]),
  [("Class 2 English position words: the cup is ___ the table (on top).", "on", ["under", "behind", "in"], "On."),
   ("Class 2 English opposites: the opposite of old is...", "new", ["big", "fast", "sad"], "New."),
   ("The opposite of up is...", "down", ["over", "high", "top"], "Down."),
   ("The fish are ___ the water.", "in", ["on", "up", "over"], "In."),
   ("The opposite of empty is...", "full", ["small", "tall", "short"], "Full.")],
  [NOTE], prereq=["class2-english-adjectives-pronouns"])

ch = p.chapter("sentences-reading", "Sentences, reading and speaking", R)
lesson(ch, "questions-sentences", "Sentences and questions", ["Use capital letters, full stops and question marks.", "Ask questions with who, what, where, when."],
  [("definition", "Kinds of sentences", "A **statement** tells something and ends with a full stop (.). A **question** asks something and ends with a **question mark** (?). Example: *Where is my book?*"),
   ("retenir", "Question words", "**Who** asks about a person. **What** asks about a thing. **Where** asks about a place. **When** asks about time. Who is at the door? Where is Mama?"),
   ("pieges", "Common mistakes", "- Do not use a full stop after a question.\n- Start every sentence with a capital letter.\n- Names always have a capital letter.")],
  [("Example 1", "Add the right mark: Where is the market", ["It asks something.", "Where is the market?"], "?", cards(["Where is Mama?", "Mama is here."], 1, 300, ch=44, size=18)),
   ("Example 2", "Which question word asks about a person?", ["We want a person.", "Who."], "Who", None)],
  (cards(["Who is that?", "What is this?", "Where is Ada?", "When is break?"], 2, 400, ch=44, size=18), "Question words.", "Four boxes with questions: Who, What, Where, When."),
  [("m", "A question ends with a...", "question mark", ["full stop", "comma", "capital letter"], "?"), ("m", "Which asks about a place?", "Where is the school?", ["Who is the teacher?", "What is this?", "When is lunch?"], "Where = place."), ("m", "Which is a statement?", "Mama cooks rice.", ["Is Mama here?", "Who is Mama?", "Where is rice?"], "It tells something.")],
  [("x", "Match the question word with what it asks.", [("Who", "a person"), ("Where", "a place"), ("When", "a time")], "Question words."), ("t", "A question ends with a full stop.", False, "It ends with a question mark.")],
  ("p", "Neba writes: where is my pen", [("m", "What must be added at the start?", "a capital letter", ["a number", "a comma", "nothing"], "W capital."), ("m", "What must be added at the end?", "a question mark", ["a full stop", "a comma", "nothing"], "?")]),
  [("Class 2 English questions: which question word asks about a time?", "When", ["Who", "Where", "What"], "When."),
   ("Class 2 English questions: which sentence is a question?", "Where is the cat?", ["The cat is here.", "I see the cat.", "The cat sleeps."], "?"),
   ("What mark is at the end of a statement?", "a full stop", ["a question mark", "a comma", "a star"], "Full stop."),
   ("Who asks about a...", "person", ["place", "time", "colour"], "Person."),
   ("Every sentence starts with a...", "capital letter", ["small letter", "number", "comma"], "Capital.")],
  [NOTE], prereq=["class2-english-prepositions-opposites"])

story2 = "On Saturday Ngum goes to the market with his mother in Bamenda. They buy yams, tomatoes and fish. Ngum carries the small bag. A kind woman gives him a mango. He says thank you. They go home happy."
assert len(story2) < 650
lesson(ch, "reading-story", "Reading: A Day at the Market", ["Read a short story.", "Answer questions about the story."],
  [("definition", "The story", story2),
   ("retenir", "Read with care", "Who is in the story? Where are they? What happens? Look back at the words to find the answer. Answer with a full sentence."),
   ("pieges", "Common mistakes", "- Do not guess. Look at the story.\n- Read the question twice.\n- Answer the question that is asked.")],
  [("Example 1", "Where does Ngum go on Saturday?", ["Look at the first sentence.", "He goes to the market."], "To the market", cards(["Ngum goes to the market."], 1, 350, ch=44, size=16)),
   ("Example 2", "What does the kind woman give him?", ["Look for the word gives.", "A mango."], "A mango", None)],
  (cards(["They buy yams, tomatoes and fish.", "A woman gives him a mango."], 1, 400, ch=44, size=15), "Two lines from the story.", "Two boxes with lines from the market story."),
  [("m", "In the story, who goes to the market with Ngum?", "his mother", ["his teacher", "his brother", "his friend"], "His mother."), ("m", "What do they NOT buy in the story?", "rice", ["yams", "tomatoes", "fish"], "They buy yams, tomatoes and fish."), ("m", "How do they go home?", "happy", ["sad", "angry", "late"], "Happy.")],
  [("t", "Ngum carries the big bag.", False, "He carries the small bag."), ("m", "What does Ngum say to the woman?", "thank you", ["sorry", "go away", "hello"], "Thank you.")],
  ("p", "Read: On Saturday Ngum goes to the market with his mother in Bamenda. A kind woman gives him a mango.", [("m", "In which town is the market?", "Bamenda", ["Douala", "Limbe", "Buea"], "Bamenda."), ("m", "Which word describes the woman?", "kind", ["small", "red", "tall"], "Kind.")]),
  [("Class 2 English reading: in the market story, Ngum goes with...", "his mother", ["his father", "his teacher", "no one"], "Mother."),
   ("Class 2 English reading: the woman gives Ngum...", "a mango", ["a hen", "a book", "a pen"], "A mango."),
   ("The story happens on...", "Saturday", ["Monday", "Friday", "Sunday"], "Saturday."),
   ("The word 'kind' describes the...", "woman", ["bag", "market", "fish"], "Woman."),
   ("To answer a question about a story we should...", "look back at the story", ["guess", "draw", "sleep"], "Look back.")],
  ["Story is original; reading level for Class 2 to be checked."], prereq=["class2-english-questions-sentences"])

lesson(ch, "writing-spelling", "Writing simple sentences", ["Write three sentences about yourself.", "Use capital letters and full stops."],
  [("methode", "Steps to write", "1. Think about what to say. 2. Say it aloud. 3. Write it. Start with a capital letter. 4. End with a full stop. 5. Read it again and check the spelling."),
   ("retenir", "A model", "My name is Ada. I live in Kumba. I like to read books. I am seven years old."),
   ("pieges", "Common mistakes", "- Write I as a capital letter.\n- Use a capital letter for names of towns.\n- Leave a space between words.")],
  [("Example 1", "Complete: My name ___ Ada.", ["Use is with name.", "My name is Ada."], "is", cards(["My name is Ada.", "I live in Kumba."], 1, 400, ch=44, size=18)),
   ("Example 2", "What is wrong: i live in buea.", ["i and buea need capital letters.", "There is no full stop. Write: I live in Buea."], "capital letters and a full stop", None)],
  (cards(["My name is Ada.", "I live in Kumba.", "I like books."], 1, 400, ch=40, size=18), "A model of three sentences.", "Three boxes with the sentences My name is Ada, I live in Kumba, I like books."),
  [("m", "Which is written right?", "I live in Douala.", ["I live in douala", "live I in Douala.", "I Douala in live."], "Capital letters, right order and full stop."), ("m", "Which word needs a capital letter?", "Yaoundé", ["table", "run", "green"], "Names of towns."), ("t", "We leave a space between words.", True, "Yes.")],
  [("m", "Put in order: school / I / go / to.", "I go to school.", ["Go I school to.", "To school go I.", "School to I go."], "I go to school."), ("m", "What do we put at the end of My name is Ngu?", "a full stop", ["a question mark", "a comma", "nothing"], "Full stop.")],
  ("p", "Bih writes: my friend is nkem she lives in limbe", [("m", "What kind of letter should the first word start with?", "a capital letter", ["a small letter", "a number", "a dot"], "My."), ("m", "Which names need a capital letter?", "Nkem and Limbe", ["friend and lives", "she and is", "none"], "Nkem and Limbe.")]),
  [("Class 2 English writing: a sentence begins with...", "a capital letter", ["a full stop", "a number", "a comma"], "Capital."),
   ("Class 2 English writing: which is right?", "I like mangoes.", ["i like mangoes", "I mangoes like.", "like mangoes I."], "Right capital and stop."),
   ("A town name such as Buea begins with...", "a capital letter", ["a small letter", "a full stop", "a number"], "Capital."),
   ("We write the word I as...", "a capital letter", ["a small letter", "a number", "two letters"], "I."),
   ("After writing, we should...", "read it again and check", ["tear the page", "forget it", "run"], "Check.")],
  [NOTE], prereq=["class2-english-questions-sentences"])

lesson(ch, "speaking-listening", "Listening and speaking", ["Follow spoken instructions.", "Ask and answer simple questions."],
  [("definition", "Listening", "Good listeners look at the speaker, keep quiet and think about the words. Listen to the whole instruction before you act."),
   ("retenir", "Speaking", "Speak clearly and not too fast. Use full sentences: *My name is Ada.* Ask: *May I have a pencil, please?* Say *thank you*."),
   ("pieges", "Common mistakes", "- Do not talk when others are speaking.\n- Wait for your turn.\n- Use polite words.")],
  [("Example 1", "The teacher says: Stand up and clap two times. What do you do first?", ["Listen to the whole instruction.", "First stand up, then clap two times."], "Stand up", cards(["Listen", "Think", "Speak", "Thank you"], 4, 400, ch=44, size=16)),
   ("Example 2", "You need a ruler. What do you say?", ["Be polite.", "May I have a ruler, please?"], "May I have a ruler, please?", None)],
  (cards(["Look at the speaker", "Keep quiet", "Wait your turn", "Say thank you"], 2, 400, ch=44, size=15), "Being a good listener.", "Four boxes with tips for good listening."),
  [("m", "When someone is speaking, you should...", "listen", ["shout", "run", "sleep"], "Listen."), ("m", "You want a pencil. You say:", "May I have a pencil, please?", ["Give me!", "Pencil!", "Hey you!"], "Polite."), ("t", "We should wait for our turn to speak.", True, "Yes.")],
  [("m", "The teacher says: Open your book, then read page 5. What do you do second?", "read page 5", ["open your book", "close your book", "sing"], "Second: read page 5."), ("m", "Which is a full sentence?", "My name is Ngu.", ["Ngu.", "name Ngu", "my"], "A full sentence.")],
  ("p", "A visitor comes to Class 2.", [("m", "What do you say in the morning?", "Good morning, welcome.", ["Go away.", "Who?", "Nothing"], "Greet politely."), ("m", "The visitor asks your name. What do you say?", "My name is Ada.", ["Ada", "no", "I do not know"], "A full sentence.")]),
  [("Class 2 English listening: a good listener...", "keeps quiet and thinks", ["talks all the time", "runs away", "sleeps"], "Listens."),
   ("Class 2 English speaking: to ask for something politely we say...", "please", ["now", "give", "hey"], "Please."),
   ("Listen to the whole instruction before you...", "act", ["sleep", "sing", "shout"], "Act."),
   ("We speak...", "clearly", ["very fast", "in a whisper only", "without words"], "Clearly."),
   ("Which is polite?", "Thank you, teacher.", ["Give me that.", "Be quiet.", "Go away."], "Polite.")],
  ["Speaking and listening need a teacher to assess; the quiz covers only manners."], prereq=["class2-english-questions-sentences"])

lesson(p.chapters[0], "common-words", "Common words: have, has, was, were, said", ["Read and use common words.", "Use have and has, was and were correctly."],
  [("definition", "Have and has", "Use **has** with one person or thing: She **has** a book. Use **have** with I, you, we and they: I **have** a pen. They **have** two goats."),
   ("retenir", "Was and were", "Use **was** for one in the past: He **was** at school. Use **were** for more than one, and with you: They **were** at the market. You **were** early."),
   ("pieges", "Common mistakes", "- *She has*, not *she have*.\n- *They were*, not *they was*.\n- The word **said** is the past of say.")],
  [("Example 1", "Fill the gap: Mama ___ a basket. (have / has)", ["Mama is one person.", "Use has."], "has", cards(["I have", "she has", "he was", "they were"], 4, 400, ch=44, size=16)),
   ("Example 2", "Fill the gap: The girls ___ at home. (was / were)", ["Girls is more than one.", "Use were."], "were", None)],
  (cards(["I have", "she has", "he was", "they were"], 4, 400, ch=44, size=16), "Have, has, was, were.", "Four boxes: I have, she has, he was, they were."),
  [("m", "We ___ two books.", "have", ["has", "is", "was"], "We have."), ("m", "He ___ happy yesterday.", "was", ["were", "are", "have"], "He was."), ("m", "The boys ___ in the yard.", "were", ["was", "has", "is"], "Boys: were.")],
  [("x", "Match.", [("she", "has"), ("they", "have"), ("it", "was")], "Choose the word that goes with each."), ("t", "We say: They was happy.", False, "They were happy.")],
  ("p", "Read: Bih has a red bag. Her friends were at the gate. They said hello.", [("m", "Which word shows many people in the past?", "were", ["has", "was", "is"], "Were."), ("m", "What is the past of say?", "said", ["says", "sayed", "saying"], "Said.")]),
  [("Class 2 English common words: Nkem ___ a pen.", "has", ["have", "were", "am"], "Nkem has."),
   ("Class 2 English common words: they ___ at school yesterday.", "were", ["was", "has", "is"], "They were."),
   ("I ___ a new bag.", "have", ["has", "were", "is"], "I have."),
   ("The past of say is...", "said", ["sayed", "says", "saying"], "Said."),
   ("She ___ in the garden.", "was", ["were", "have", "are"], "She was.")],
  [NOTE], prereq=["class2-english-blends-spelling"])

p.write()
