import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from p13_kit import *
from p13_fig import *

p = newpack("class1-english", "English Language — Class 1", "Class 1", "english",
    "First English lessons: the alphabet, sounds, simple words, naming, action and describing words, short sentences, rhymes, a short story and polite speaking.",
    REF % "Level I (Class 1) — English Language")
R = p.programRef
NOTE = "Word lists, sight words and the order in which sounds are taught are to be checked against the official syllabus; British spelling and a Cameroon English pronunciation are assumed."

ch = p.chapter("letters-sounds", "Letters and sounds", R)
lesson(ch, "alphabet-order", "The alphabet in order", ["Say the 26 letters in order.", "Say which letter comes before or after."],
  [("definition", "The alphabet", "The English alphabet has **26 letters**. They are: A B C D E F G H I J K L M N O P Q R S T U V W X Y Z. We say them in order."),
   ("retenir", "Before and after", "Before B comes A. After B comes C. A is the first letter. Z is the last letter."),
   ("pieges", "Common mistakes", "- Do not skip a letter.\n- M and N are next to each other.\n- Take your time with P, Q, R.")],
  [("Example 1", "Which letter comes after D?", ["Say the letters: A, B, C, D.", "After D comes E."], "E", cards(["C", "D", "E", "F"], 4, 400, ch=50, size=24)),
   ("Example 2", "Which letter comes before K?", ["Say: I, J, K.", "Before K is J."], "J", None)],
  (cards(["A B C D E", "F G H I J", "K L M N O", "P Q R S T", "U V W X Y", "Z"], 2, 400, ch=40, size=20), "The alphabet in rows.", "Six boxes showing the 26 letters in order."),
  [("m", "Which letter comes after B?", "C", ["A", "D", "Z"], "After B comes C."), ("m", "Which letter comes before M?", "L", ["N", "K", "O"], "Before M is L."), ("n", "How many letters are in the English alphabet?", 26, "There are 26 letters.")],
  [("m", "Which is the first letter of the alphabet?", "A", ["B", "Z", "M"], "A is first."), ("m", "Which letter is last?", "Z", ["Y", "A", "X"], "Z is last.")],
  ("p", "Ada says the alphabet at school.", [("m", "Which letter comes after R?", "S", ["Q", "T", "P"], "After R is S."), ("m", "Which letter comes between H and J?", "I", ["G", "K", "L"], "H, I, J.")]),
  [("Class 1 English alphabet: how many letters are in the alphabet?", "26", ["20", "30", "10"], "26 letters."),
   ("Class 1 English alphabet: which letter comes after E?", "F", ["D", "G", "H"], "F."),
   ("Which letter comes before T?", "S", ["U", "R", "V"], "S."),
   ("Which is the last letter?", "Z", ["A", "Y", "X"], "Z."),
   ("The letter between O and Q is...", "P", ["N", "R", "S"], "P.")],
  [NOTE])

lesson(ch, "capital-small", "Capital letters and small letters", ["Match capital and small letters.", "Know when to use a capital letter."],
  [("definition", "Two kinds of letters", "Each letter has a **capital** (big) letter and a **small** letter. A is a. B is b. We write names and the first word of a sentence with a capital letter."),
   ("retenir", "Use a capital letter", "Use a capital letter for: the first letter of a name (Ada, Douala), the first word of a sentence, the word I."),
   ("pieges", "Common mistakes", "- b and d look the same. b has the belly on the right.\n- Do not write a capital letter in the middle of a word.\n- Write the word I as a capital letter.")],
  [("Example 1", "Write the small letter for G.", ["G is a capital letter.", "The small letter is g."], "g", cards(["A a", "B b", "G g", "M m"], 4, 400, ch=50, size=22)),
   ("Example 2", "Which word needs a capital letter: cameroon?", ["Cameroon is the name of a country.", "Write it Cameroon."], "Cameroon", None)],
  (cards(["A a", "B b", "C c", "D d", "E e", "F f"], 3, 400, ch=50, size=22), "Capital and small letters.", "Six boxes showing letter pairs A a up to F f."),
  [("x", "Match the capital letter with the small letter.", [("A", "a"), ("D", "d"), ("M", "m"), ("R", "r")], "Each capital has its small letter."), ("m", "Which is the capital letter for k?", "K", ["H", "X", "M"], "K is the capital."), ("t", "We write a name with a capital letter.", True, "Names start with a capital letter.")],
  [("m", "Which word needs a capital letter?", "Bamenda", ["goat", "table", "school"], "The name of a town starts with a capital letter."), ("m", "Which word must always be written with a capital letter?", "I", ["am", "we", "you"], "The word I is always a capital.")],
  ("p", "Teacher writes on the board.", [("m", "Which sentence is written right?", "Ada is my friend.", ["Ada is my friend", "Is friend my Ada.", "my Ada friend is."], "Capital letter, right order and a full stop."), ("t", "A sentence starts with a capital letter.", True, "Yes.")]),
  [("Class 1 English letters: the small letter for B is...", "b", ["d", "p", "q"], "b."),
   ("Class 1 English letters: a name starts with...", "a capital letter", ["a small letter", "a number", "a full stop"], "Capital."),
   ("Which is a capital letter?", "T", ["f", "j", "r"], "T."),
   ("The capital letter for m is...", "M", ["W", "N", "H"], "M."),
   ("The first word of a sentence starts with...", "a capital letter", ["a full stop", "a small letter", "a number"], "Capital letter.")],
  [NOTE], prereq=["class1-english-alphabet-order"])

lesson(ch, "vowels-consonants", "Vowels and consonants", ["Name the five vowels.", "Tell vowels from consonants."],
  [("definition", "Vowels", "The letters **a, e, i, o, u** are **vowels**. Every word has at least one vowel sound."),
   ("retenir", "Consonants", "All the other letters are **consonants**: b, c, d, f, g, h, j, k, l, m, n, p, q, r, s, t, v, w, x, y, z. There are 21 consonants."),
   ("pieges", "Common mistakes", "- The letter y can sound like a vowel in words like *my*, but we call it a consonant.\n- There are 5 vowels, not 6.\n- A vowel makes the open sound.")],
  [("Example 1", "Is the letter e a vowel or a consonant?", ["The vowels are a, e, i, o, u.", "e is in the list. It is a vowel."], "A vowel", cards(["a", "e", "i", "o", "u"], 5, 400, cw=70, ch=60, size=30)),
   ("Example 2", "Find the vowel in the word cat.", ["The letters are c, a, t.", "The vowel is a."], "a", None)],
  (cards(["a", "e", "i", "o", "u"], 5, 400, cw=70, ch=60, size=30), "The five vowels.", "Five boxes with the vowels a, e, i, o and u."),
  [("n", "How many vowels are in the alphabet?", 5, "a, e, i, o, u."), ("m", "Which letter is a vowel?", "o", ["b", "m", "t"], "o is a vowel."), ("m", "Which letter is a consonant?", "d", ["a", "e", "i"], "d is a consonant.")],
  [("m", "Find the vowel in the word dog.", "o", ["d", "g", "no vowel"], "d-o-g: o is the vowel."), ("m", "Which word has the vowel u?", "sun", ["pig", "dog", "hen"], "s-u-n.")],
  ("p", "Pupils look at the word bed.", [("m", "Which letter is the vowel?", "e", ["b", "d", "none"], "b-e-d."), ("n", "How many consonants are in bed?", 2, "b and d.")]),
  [("Class 1 English vowels: which letter is a vowel?", "u", ["k", "p", "z"], "u."),
   ("Class 1 English vowels: how many vowels are there?", "5", ["3", "10", "21"], "5."),
   ("Which word has the vowel i?", "pin", ["pot", "pen", "pup"], "p-i-n."),
   ("Which is a consonant?", "s", ["a", "e", "o"], "s."),
   ("The vowels are...", "a, e, i, o, u", ["a, b, c, d, e", "x, y, z", "m, n, o, p, q"], "a, e, i, o, u.")],
  [NOTE], prereq=["class1-english-capital-small"])

lesson(ch, "sounds-a-e", "Sounds of a and e", ["Read short words with a and e.", "Say the sounds a and e."],
  [("definition", "Short a", "The letter **a** says a short sound as in **cat, bat, map, hat, bag**. Say a-a-a. c-a-t. Cat."),
   ("retenir", "Short e", "The letter **e** says a short sound as in **hen, pen, bed, red, ten**. Say e-e-e. h-e-n. Hen."),
   ("pieges", "Common mistakes", "- Do not say hen like hin.\n- Say each sound slowly, then join them.\n- Mix up: cat has a, pen has e.")],
  [("Example 1", "Read the word hen.", ["Say the sounds: h, e, n.", "Join them: hen."], "hen", cards(["h-e-n", "hen"], 2, 300, ch=50, size=22)),
   ("Example 2", "Which vowel is in the word map?", ["Sounds: m, a, p.", "The vowel is a."], "a", None)],
  (cards(["cat", "bat", "pen", "hen", "bed", "map"], 3, 400, ch=50, size=22), "Words with a and e.", "Six boxes with the words cat, bat, pen, hen, bed and map."),
  [("m", "Which word has the sound a?", "bag", ["bed", "pen", "ten"], "b-a-g."), ("m", "Which word has the sound e?", "red", ["rat", "hat", "map"], "r-e-d."), ("m", "Which word rhymes with cat?", "hat", ["hen", "bed", "pen"], "cat, hat.")],
  [("x", "Match the rhyming words.", [("cat", "hat"), ("pen", "hen"), ("bed", "red"), ("bag", "tag")], "Same ending sound."), ("t", "The word bed has the vowel e.", True, "b-e-d.")],
  ("p", "Ngu reads a list: cat, hen, bat, red.", [("m", "Which two words have the sound a?", "cat and bat", ["hen and red", "cat and red", "hen and bat"], "cat, bat."), ("m", "Which two words have the sound e?", "hen and red", ["cat and bat", "cat and hen", "bat and red"], "hen, red.")]),
  [("Class 1 English phonics: which word has the short sound a?", "mat", ["met", "men", "net"], "m-a-t."),
   ("Class 1 English phonics: which word has the short sound e?", "net", ["nap", "mat", "cat"], "n-e-t."),
   ("The word that rhymes with bed is...", "red", ["bad", "bag", "bat"], "bed, red."),
   ("c-a-t spells...", "cat", ["cut", "cot", "kit"], "cat."),
   ("The animal that says cluck is a...", "hen", ["cat", "bat", "pig"], "hen.")],
  [NOTE], prereq=["class1-english-vowels-consonants"])

lesson(ch, "sounds-i-o-u", "Sounds of i, o and u", ["Read short words with i, o and u.", "Hear the middle sound in a word."],
  [("definition", "Short i", "The letter **i** says a short sound as in **pin, sit, big, fish, lip**."),
   ("retenir", "Short o and u", "The letter **o** says a short sound as in **dog, pot, top, hot, box**. The letter **u** says a short sound as in **sun, cup, bus, mud, nut**."),
   ("pieges", "Common mistakes", "- pin has i, pen has e: listen carefully.\n- cup and cap are different words.\n- Say each sound, then join: s-u-n, sun.")],
  [("Example 1", "Read the word dog.", ["Say the sounds: d, o, g.", "Join them: dog."], "dog", cards(["d-o-g", "dog"], 2, 300, ch=50, size=22)),
   ("Example 2", "Which vowel is in the word sun?", ["Sounds: s, u, n.", "The vowel is u."], "u", None)],
  (cards(["pin", "sit", "dog", "pot", "sun", "cup"], 3, 400, ch=50, size=22), "Words with i, o and u.", "Six boxes with the words pin, sit, dog, pot, sun and cup."),
  [("m", "Which word has the sound i?", "pig", ["pot", "pup", "pan"], "p-i-g."), ("m", "Which word has the sound o?", "top", ["tip", "tap", "tub"], "t-o-p."), ("m", "Which word has the sound u?", "bus", ["bin", "box", "bat"], "b-u-s.")],
  [("x", "Match the word with its vowel.", [("pig", "i"), ("hot", "o"), ("mud", "u")], "Find the vowel."), ("m", "Which word rhymes with sun?", "run", ["sit", "sip", "sad"], "sun, run.")],
  ("p", "Nkem reads: pig, dog, cup, sit.", [("m", "Which word has u?", "cup", ["pig", "dog", "sit"], "c-u-p."), ("m", "Which word has o?", "dog", ["pig", "cup", "sit"], "d-o-g.")]),
  [("Class 1 English phonics: which word has the sound i?", "lip", ["lap", "lop", "lug"], "l-i-p."),
   ("Class 1 English phonics: which word has the sound o?", "hot", ["hit", "hut", "hat"], "h-o-t."),
   ("Which word has the sound u?", "nut", ["net", "not", "nit"], "n-u-t."),
   ("A word that rhymes with pot is...", "hot", ["pit", "pat", "pet"], "pot, hot."),
   ("An animal that barks is a...", "dog", ["pig", "hen", "cat"], "dog.")],
  [NOTE], prereq=["class1-english-sounds-a-e"])

lesson(ch, "first-sounds", "First sounds of words", ["Hear the first sound of a word.", "Match words to their first letter."],
  [("definition", "First sound", "Every word starts with a sound. The word **ball** starts with the sound **b**. The word **sun** starts with **s**. We write the first sound with a letter."),
   ("retenir", "Sound pictures", "b: ball, banana, book. m: mango, mat, moon. s: sun, sock, sit. t: tree, tap, ten. p: pen, pot, pig."),
   ("pieges", "Common mistakes", "- cat and kite both start with the sound k.\n- Listen to the sound, not to the name of the letter.\n- A word can start with a vowel: apple starts with a.")],
  [("Example 1", "What is the first letter of mango?", ["Say mango slowly: m-a-n-go.", "It starts with m."], "m", cards(["m", "mango"], 2, 300, ch=50, size=22)),
   ("Example 2", "Which word starts with b: ball or sun?", ["Ball starts with b.", "Sun starts with s."], "ball", None)],
  (cards(["b - ball", "m - mango", "s - sun", "t - tree", "p - pig", "d - dog"], 2, 400, ch=40, size=18), "Letters and words.", "Six boxes: b ball, m mango, s sun, t tree, p pig, d dog."),
  [("m", "What is the first letter of pig?", "p", ["g", "i", "b"], "p-i-g."), ("m", "Which word starts with t?", "tree", ["bee", "sun", "mat"], "t-ree."), ("m", "What is the first sound of dog?", "d", ["g", "o", "t"], "d-o-g.")],
  [("x", "Match the word to its first letter.", [("sun", "s"), ("ball", "b"), ("moon", "m"), ("tap", "t")], "Say each word slowly."), ("t", "The word apple starts with a vowel.", True, "a is a vowel.")],
  ("p", "A teacher says words at the market game.", [("m", "Which word starts with m?", "mango", ["banana", "orange", "pawpaw"], "m-ango."), ("m", "Which word starts with p?", "pawpaw", ["mango", "banana", "orange"], "p-awpaw.")]),
  [("Class 1 English first sounds: the word sun starts with...", "s", ["n", "u", "t"], "s."),
   ("Class 1 English first sounds: which word starts with b?", "book", ["cook", "look", "hook"], "b-ook."),
   ("The word mat starts with the letter...", "m", ["t", "a", "n"], "m."),
   ("Which word starts with the same sound as ten?", "tap", ["pen", "net", "man"], "t."),
   ("The word apple starts with...", "a", ["p", "l", "e"], "a.")],
  [NOTE], prereq=["class1-english-sounds-i-o-u"])

# ===================================================== words
ch = p.chapter("words", "Words we use", R)
lesson(ch, "sight-words", "Words we know by sight", ["Read common words quickly.", "Use them in a sentence."],
  [("definition", "Sight words", "Some words are in almost every sentence. We learn to read them at a glance. Some are: **the, a, is, and, to, I, you, he, she, we, it, my, am, are**."),
   ("retenir", "Read and use", "I am Ada. You are my friend. He is tall. She is kind. We are at school. It is a dog."),
   ("pieges", "Common mistakes", "- *I am*, not *I is*.\n- *You are*, not *you is*.\n- he and she are different words.")],
  [("Example 1", "Fill the gap: I ___ a girl.", ["Use am with I.", "I am a girl."], "am", cards(["I am", "you are", "he is", "she is"], 2, 300, ch=44, size=20)),
   ("Example 2", "Fill the gap: She ___ my mother.", ["Use is with she.", "She is my mother."], "is", None)],
  (cards(["the", "is", "and", "to", "you", "my"], 3, 400, ch=50, size=22), "Some sight words.", "Six boxes with sight words."),
  [("m", "I ___ at school.", "am", ["is", "are", "be"], "I am."), ("m", "We ___ happy.", "are", ["am", "is", "be"], "We are."), ("m", "He ___ a boy.", "is", ["am", "are", "be"], "He is.")],
  [("x", "Match the words.", [("I", "am"), ("you", "are"), ("she", "is")], "Which word follows?"), ("t", "We say: I is happy.", False, "We say: I am happy.")],
  ("p", "Bih talks about her family.", [("m", "___ am Bih.", "I", ["He", "She", "It"], "I am Bih."), ("m", "My mother ___ kind.", "is", ["am", "are", "be"], "My mother is kind.")]),
  [("Class 1 English sight words: which word is correct: I ___ six?", "am", ["is", "are", "be"], "I am."),
   ("Class 1 English sight words: you ___ my friend.", "are", ["is", "am", "be"], "You are."),
   ("She ___ a teacher.", "is", ["am", "are", "be"], "She is."),
   ("Which word means the same as 'me and others'?", "we", ["he", "it", "a"], "We."),
   ("Which is a sight word?", "the", ["xylophone", "rhinoceros", "zebra"], "The is a very common word.")],
  ["Word list is a typical early list; check against the official syllabus."], prereq=["class1-english-first-sounds"])

lesson(ch, "naming-words", "Naming words (nouns)", ["Say what a noun is.", "Find nouns in a sentence."],
  [("definition", "Nouns", "A **noun** is a **naming word**. It names a person, an animal, a place or a thing. Examples: **girl, dog, school, mango, Douala**."),
   ("retenir", "Four kinds", "Person: teacher, mother. Animal: goat, hen. Place: market, church. Thing: book, chair. Names like Ada and Buea start with a capital letter."),
   ("pieges", "Common mistakes", "- Run is not a noun. It is an action word.\n- Names of people and places need a capital letter.\n- Words like big and red tell more about a noun. They are not nouns.")],
  [("Example 1", "Find the noun: The goat eats grass.", ["Goat names an animal.", "Grass names a thing. Both are nouns."], "goat, grass", cards(["person", "animal", "place", "thing"], 4, 400, ch=44, size=16)),
   ("Example 2", "Is market a noun?", ["A market is a place.", "Yes, it is a noun."], "Yes", None)],
  (cards(["girl", "dog", "school", "mango"], 4, 400, ch=44, size=18), "Four nouns.", "Four boxes with the nouns girl, dog, school and mango."),
  [("m", "Which word is a noun?", "teacher", ["jump", "big", "run"], "A teacher is a person."), ("m", "Which word names an animal?", "goat", ["table", "Buea", "book"], "A goat is an animal."), ("m", "Which word names a place?", "market", ["pencil", "hen", "mother"], "Market is a place.")],
  [("x", "Match the noun with its kind.", [("Ada", "person"), ("hen", "animal"), ("Limbe", "place"), ("cup", "thing")], "Think who or what."), ("t", "Run is a naming word.", False, "Run is an action word.")],
  ("p", "Read: Mama sells mangoes at the market.", [("m", "Which word names a person?", "Mama", ["sells", "at", "the"], "Mama."), ("m", "Which word names a thing?", "mangoes", ["sells", "at", "the"], "Mangoes.")]),
  [("Class 1 English nouns: a noun is a...", "naming word", ["doing word", "joining word", "full stop"], "Naming word."),
   ("Class 1 English nouns: which is a noun?", "chair", ["sit", "red", "run"], "Chair."),
   ("Which word names a place?", "school", ["Ada", "sing", "happy"], "School."),
   ("Which word names an animal?", "pig", ["pen", "bed", "desk"], "Pig."),
   ("Names of people begin with...", "a capital letter", ["a number", "a small letter", "a full stop"], "Capital.")],
  [NOTE], prereq=["class1-english-sight-words"])

lesson(ch, "action-words", "Action words (verbs)", ["Say what a verb is.", "Find the action word in a sentence."],
  [("definition", "Verbs", "A **verb** is an **action word**. It tells what someone or something does. Examples: **run, jump, eat, sing, write, sleep**."),
   ("retenir", "Find the verb", "Ask: What is the person doing? Ada **sings**. The boy **runs**. The hen **eats**. The verb is the doing word."),
   ("pieges", "Common mistakes", "- Do not mix it with the noun. In *Ada sings*, Ada is the noun and sings is the verb.\n- Some verbs do not move: sleep, sit.\n- The verb can end with s when one person does it: she runs.")],
  [("Example 1", "Find the verb: The boy runs.", ["What does the boy do?", "He runs. The verb is runs."], "runs", cards(["run", "jump", "eat", "sing"], 4, 400, ch=44, size=18)),
   ("Example 2", "Find the verb: Mama cooks rice.", ["What does Mama do?", "She cooks. The verb is cooks."], "cooks", None)],
  (cards(["run", "jump", "eat", "write"], 4, 400, ch=44, size=18), "Four action words.", "Four boxes with the verbs run, jump, eat and write."),
  [("m", "Which word is an action word?", "jump", ["tree", "red", "book"], "Jump is an action."), ("m", "Find the verb: The cat sleeps.", "sleeps", ["The", "cat", "none"], "Sleeps."), ("m", "Find the verb: Ngu writes a letter.", "writes", ["Ngu", "a", "letter"], "Writes.")],
  [("x", "Match the action with the picture word.", [("a bird", "flies"), ("a fish", "swims"), ("a girl", "sings"), ("a dog", "barks")], "Think of the sound or move."), ("t", "Sing is a doing word.", True, "Yes.")],
  ("p", "Read: The pupils read and write at school.", [("m", "Which word is a verb?", "read", ["pupils", "school", "at"], "Read."), ("m", "Which other word is a verb?", "write", ["The", "school", "pupils"], "Write.")]),
  [("Class 1 English verbs: a verb is an...", "action word", ["naming word", "colour word", "number"], "Action."),
   ("Class 1 English verbs: which word is a verb?", "eat", ["egg", "ear", "end"], "Eat."),
   ("Find the verb: The baby cries.", "cries", ["baby", "The", "a"], "Cries."),
   ("Which word tells what a bird does?", "flies", ["tree", "red", "nest"], "Flies."),
   ("Find the verb: Mama sells fish.", "sells", ["Mama", "fish", "none"], "Sells.")],
  [NOTE], prereq=["class1-english-naming-words"])

lesson(ch, "describing-words", "Describing words (adjectives)", ["Say what an adjective is.", "Use describing words."],
  [("definition", "Adjectives", "A **describing word** (adjective) tells more about a noun. It tells the colour, size, or how it feels. Examples: **big, small, red, hot, soft, tall**."),
   ("retenir", "In a sentence", "A **big** dog. A **red** ball. The water is **cold**. The describing word goes before the noun or after is."),
   ("pieges", "Common mistakes", "- A describing word is not a noun.\n- Big describes a thing; run is an action.\n- We say a red ball, not a ball red.")],
  [("Example 1", "Find the describing word: a tall tree.", ["Tree is a thing.", "Tall tells about the tree."], "tall", cards(["big", "small", "tall", "short"], 4, 400, ch=44, size=18)),
   ("Example 2", "Fill the gap: The sun is ___. (hot / run)", ["Run is an action.", "Hot describes the sun."], "hot", None)],
  (cards(["a red ball", "a big dog", "a small cup", "a tall tree"], 2, 400, ch=44, size=18), "Describing words.", "Four boxes with phrases: a red ball, a big dog, a small cup, a tall tree."),
  [("m", "Which is a describing word?", "soft", ["jump", "table", "Ada"], "Soft."), ("m", "Find the describing word: a yellow banana.", "yellow", ["a", "banana", "none"], "Yellow."), ("m", "The ice is ___.", "cold", ["run", "dog", "eat"], "Cold.")],
  [("x", "Match the thing with its describing word.", [("sun", "hot"), ("ice", "cold"), ("elephant", "big"), ("ant", "small")], "Think about each thing."), ("t", "Big is a describing word.", True, "Yes.")],
  ("p", "Read: The small boy has a red cap.", [("m", "Which word describes the boy?", "small", ["red", "has", "cap"], "Small."), ("m", "Which word describes the cap?", "red", ["small", "boy", "has"], "Red.")]),
  [("Class 1 English adjectives: a describing word tells more about a...", "noun", ["number", "full stop", "letter"], "Noun."),
   ("Class 1 English adjectives: which is a describing word?", "tall", ["tree", "grow", "root"], "Tall."),
   ("A mango can be...", "sweet", ["swim", "jump", "write"], "Sweet."),
   ("Find the describing word: a hot day.", "hot", ["a", "day", "none"], "Hot."),
   ("The opposite of big is...", "small", ["tall", "red", "new"], "Small.")],
  [NOTE], prereq=["class1-english-action-words"])

lesson(ch, "a-an", "Using a and an", ["Use a before a consonant sound.", "Use an before a vowel sound."],
  [("definition", "A and an", "We use **a** before a word that starts with a consonant sound: **a** dog, **a** book. We use **an** before a word that starts with a vowel sound: **an** egg, **an** apple."),
   ("retenir", "Easy rule", "Vowel sounds: a, e, i, o, u. an apple, an egg, an ink pot, an orange, an umbrella. Other sounds: a mango, a pen, a girl."),
   ("pieges", "Common mistakes", "- Not *a apple*. Say *an apple*.\n- Not *an dog*. Say *a dog*.\n- Listen to the first sound.")],
  [("Example 1", "Fill the gap: ___ egg.", ["Egg starts with the vowel e.", "Use an: an egg."], "an", cards(["an egg", "an apple", "an orange"], 3, 400, ch=44, size=18)),
   ("Example 2", "Fill the gap: ___ mango.", ["Mango starts with m, a consonant.", "Use a: a mango."], "a", None)],
  (cards(["a dog", "a book", "an egg", "an apple"], 2, 400, ch=44, size=20), "A or an?", "Four boxes: a dog, a book, an egg, an apple."),
  [("m", "___ orange", "an", ["a", "the", "and"], "O is a vowel."), ("m", "___ pen", "a", ["an", "the", "and"], "P is a consonant."), ("m", "___ umbrella", "an", ["a", "the", "to"], "U is a vowel.")],
  [("m", "Which is right?", "an egg", ["a egg", "an goat", "a apple"], "Egg starts with a vowel."), ("t", "We say: a dog.", True, "Dog starts with d.")],
  ("p", "Ada packs her bag: ___ book, ___ apple, ___ pencil.", [("m", "___ book", "a", ["an", "the", "or"], "B is a consonant."), ("m", "___ apple", "an", ["a", "the", "or"], "A is a vowel.")]),
  [("Class 1 English a/an: which is right?", "an apple", ["a apple", "an pen", "a umbrella"], "an apple."),
   ("Class 1 English a/an: which is right?", "a goat", ["an goat", "a egg", "an table"], "a goat."),
   ("___ ant is small.", "An", ["A", "The", "And"], "An ant."),
   ("___ boy runs.", "A", ["An", "Or", "In"], "A boy."),
   ("We use an before words that start with...", "a vowel sound", ["a consonant sound", "a number", "a full stop"], "Vowel.")],
  [NOTE], prereq=["class1-english-vowels-consonants", "class1-english-naming-words"])

# ===================================================== sentences
ch = p.chapter("sentences", "Sentences and rhymes", R)
lesson(ch, "simple-sentences", "Simple sentences", ["Say what a sentence is.", "Start with a capital letter and end with a full stop."],
  [("definition", "Sentence", "A **sentence** tells a whole idea. It starts with a **capital letter**. It ends with a **full stop** (.). Example: **The dog runs.**"),
   ("methode", "Make a sentence", "1. Think of who or what. 2. Add what they do. 3. Start with a capital letter. 4. End with a full stop. Ada sings."),
   ("pieges", "Common mistakes", "- A sentence needs a verb.\n- Do not forget the full stop.\n- The words must be in order: *The cat sat.* Not *sat cat the.*")],
  [("Example 1", "Put the words in order: runs / The / dog.", ["Start with The.", "The dog runs."], "The dog runs.", cards(["The dog runs."], 1, 300, ch=50, size=20)),
   ("Example 2", "What is missing: the boy eats rice", ["It does not start with a capital letter.", "It has no full stop. Write: The boy eats rice."], "A capital T and a full stop", None)],
  (cards(["The hen lays an egg.", "Ada has a red cap."], 1, 400, ch=44, size=18), "Two sentences.", "Two boxes with the sentences The hen lays an egg and Ada has a red cap."),
  [("m", "Which is a sentence?", "The cat sleeps.", ["the cat", "sleeps the", "cat the"], "It tells a whole idea."), ("m", "A sentence ends with a...", "full stop", ["comma", "number", "capital"], "Full stop."), ("m", "A sentence starts with a...", "capital letter", ["full stop", "number", "small letter"], "Capital.")],
  [("m", "Which is written right?", "Mama cooks rice.", ["Mama cooks rice", "Mama rice cooks.", "mama, cooks rice"], "Capital, right order and full stop."), ("t", "We can end a sentence without a full stop.", False, "A sentence ends with a full stop (or ? or !).")],
  ("p", "Teacher writes: i see a bird", [("m", "What must we change at the start?", "write I with a capital", ["add a number", "nothing", "write it small"], "I needs a capital."), ("m", "What must we add at the end?", "a full stop", ["a comma", "a number", "nothing"], "Full stop.")]),
  [("Class 1 English sentences: a sentence starts with...", "a capital letter", ["a full stop", "a number", "a space"], "Capital."),
   ("Class 1 English sentences: which is a sentence?", "I like mangoes.", ["like mangoes", "mangoes I", "I like"], "Whole idea."),
   ("Put in order: sits / The / cat.", "The cat sits.", ["Sits the cat.", "Cat sits the.", "The sits cat."], "The cat sits."),
   ("A full stop is a small...", "dot", ["line", "star", "circle only"], "Dot."),
   ("What is missing: Ada has a book", "a full stop", ["a number", "a picture", "a drum"], "Full stop.")],
  [NOTE], prereq=["class1-english-action-words", "class1-english-capital-small"])

lesson(ch, "rhymes", "Rhyming words", ["Hear words that rhyme.", "Say a short rhyme."],
  [("definition", "Rhyme", "Words that **rhyme** have the same ending sound. **cat** and **hat** rhyme. **bed** and **red** rhyme. **sun** and **run** rhyme."),
   ("retenir", "Rhyming families", "-at: cat, hat, bat, mat. -en: hen, pen, ten. -ug: bug, mug, jug. -ig: pig, big, dig."),
   ("pieges", "Common mistakes", "- Rhyming words sound the same at the end, not the start.\n- cat and cap start the same, but do not rhyme.\n- They may be spelt differently, but listen.")],
  [("Example 1", "Which word rhymes with pig: big or pen?", ["pig ends with ig.", "big ends with ig. So big rhymes with pig."], "big", cards(["cat - hat", "hen - pen", "pig - big"], 3, 400, ch=44, size=16)),
   ("Example 2", "Complete: The cat sat on the ___. (mat / dog)", ["Sat and mat end with at.", "The cat sat on the mat."], "mat", None)],
  (cards(["cat - hat", "bed - red", "sun - run", "pig - big"], 2, 400, ch=44, size=18), "Rhyming pairs.", "Four boxes with rhyming pairs."),
  [("m", "Which word rhymes with hat?", "bat", ["bed", "pig", "sun"], "hat, bat."), ("m", "Which word rhymes with run?", "sun", ["rat", "red", "rug"], "run, sun."), ("m", "Which word rhymes with pen?", "ten", ["pan", "pin", "pot"], "pen, ten.")],
  [("x", "Match the rhyming words.", [("cat", "mat"), ("pig", "big"), ("hen", "ten"), ("bug", "mug")], "Same ending."), ("t", "Cat and cup rhyme.", False, "They start the same but end differently.")],
  ("p", "A rhyme: The hen is in the ___. The pig is ___.", [("m", "Which word rhymes with hen?", "pen", ["pig", "cup", "sun"], "hen, pen."), ("m", "Which word rhymes with pig?", "big", ["pen", "cup", "sun"], "pig, big.")]),
  [("Class 1 English rhymes: which word rhymes with cat?", "rat", ["cup", "dog", "bed"], "cat, rat."),
   ("Class 1 English rhymes: which word rhymes with bed?", "red", ["bad", "bid", "bud"], "bed, red."),
   ("Words that rhyme have the same...", "ending sound", ["first letter", "colour", "number"], "Ending."),
   ("Which pair rhymes?", "mug - jug", ["mug - mat", "jug - pig", "bug - bag"], "mug, jug."),
   ("Which word rhymes with sun?", "fun", ["fan", "fin", "fit"], "sun, fun.")],
  ["Rhymes assume common English pronunciation."], prereq=["class1-english-sounds-i-o-u"])

# ===================================================== reading & speaking
ch = p.chapter("reading-speaking", "Reading, speaking and listening", R)
story = "Ada has a hen. The hen is red. The hen sits in a box. Ada gives the hen rice. The hen eats the rice."
assert len(story) < 650
lesson(ch, "short-story", "Reading a short story", ["Read a very short story.", "Answer questions about it."],
  [("definition", "Read well", "Read the story slowly. Point to each word. Think about who is in the story and what happens."),
   ("retenir", "The story", story),
   ("pieges", "Common mistakes", "- Do not guess. Look back at the story.\n- Read the whole story before you answer.\n- Answer with a full sentence.")],
  [("Example 1", "Who has a hen?", ["Look at the first sentence.", "Ada has a hen."], "Ada", cards(["Ada has a hen."], 1, 300, ch=50, size=20)),
   ("Example 2", "What colour is the hen?", ["Look at the second sentence.", "The hen is red."], "Red", None)],
  (cards(["Ada has a hen.", "The hen is red.", "The hen eats rice."], 1, 400, ch=40, size=18), "Three lines from the story.", "Three boxes with sentences from the story about Ada and her hen."),
  [("m", "Story: Ada has a hen. The hen is red. What colour is the hen?", "red", ["blue", "black", "green"], "The hen is red."), ("m", "Story: The hen sits in a box. Where does the hen sit?", "in a box", ["on a tree", "in a bag", "in a car"], "In a box."), ("m", "Story: Ada gives the hen rice. What does Ada give the hen?", "rice", ["water", "bread", "beans"], "Rice.")],
  [("t", "Ada has a dog in the story.", False, "Ada has a hen."), ("m", "Who eats the rice?", "the hen", ["Ada", "the dog", "the box"], "The hen eats the rice.")],
  ("p", "Read: Ada has a hen. The hen is red. The hen sits in a box.", [("m", "Who is the story about?", "Ada and her hen", ["a dog", "a car", "a bus"], "Ada and the hen."), ("m", "How many sentences are in the story above?", "3", ["1", "2", "5"], "Three.")]),
  [("Class 1 English reading: in the story Ada has a...", "hen", ["cat", "goat", "dog"], "Hen."),
   ("Class 1 English reading: the hen sits in a...", "box", ["bag", "tree", "bed"], "Box."),
   ("Ada gives the hen...", "rice", ["milk", "meat", "cake"], "Rice."),
   ("When we read, we should look back at the story to...", "check the answer", ["draw a car", "sleep", "run"], "Check."),
   ("A story has...", "a person or animal and what happens", ["only numbers", "only dots", "no words"], "Characters and events.")],
  ["The story is original and very short; check reading level for Class 1."], prereq=["class1-english-simple-sentences"])

lesson(ch, "speaking-listening", "Greetings and polite words", ["Greet people politely.", "Use please, thank you and sorry."],
  [("definition", "Greetings", "We greet people politely. In the morning we say **Good morning**. In the afternoon we say **Good afternoon**. In the evening we say **Good evening**. At night, before sleep, we say **Good night**."),
   ("retenir", "Polite words", "Say **please** when you ask. Say **thank you** when you get something. Say **sorry** when you make a mistake. Say **excuse me** to get past. Listen when others speak."),
   ("pieges", "Common mistakes", "- Do not shout when you speak.\n- Look at the person who is speaking.\n- Wait for your turn.")],
  [("Example 1", "It is 8 o'clock in the morning. What do you say to your teacher?", ["It is morning.", "Say: Good morning, teacher."], "Good morning", cards(["Good morning", "Good afternoon", "Good evening", "Good night"], 2, 400, ch=44, size=18)),
   ("Example 2", "A friend gives you a pencil. What do you say?", ["You received something.", "Say: Thank you."], "Thank you", None)],
  (cards(["please", "thank you", "sorry", "excuse me"], 2, 400, ch=44, size=20), "Polite words.", "Four boxes with please, thank you, sorry and excuse me."),
  [("m", "It is morning. You say:", "Good morning", ["Good night", "Good evening", "Goodbye only"], "Morning."), ("m", "You want to ask for water. You say:", "Water, please.", ["Give me!", "Water now!", "Nothing"], "Please."), ("m", "You step on a friend's foot by mistake. You say:", "Sorry", ["Hello", "Thank you", "Please"], "Sorry.")],
  [("x", "Match the time to the greeting.", [("morning", "Good morning"), ("afternoon", "Good afternoon"), ("evening", "Good evening"), ("going to bed", "Good night")], "Match the time."), ("t", "We say thank you when someone helps us.", True, "True.")],
  ("p", "Mama gives Ada a mango at the market.", [("m", "What does Ada say?", "Thank you, Mama.", ["Give me more!", "No!", "Go away."], "Thank you."), ("m", "Ada wants to pass people in a crowd. What does she say?", "Excuse me, please.", ["Move!", "Out!", "Nothing"], "Excuse me.")]),
  [("Class 1 English speaking: in the afternoon we say...", "Good afternoon", ["Good morning", "Good night", "Good evening"], "Afternoon."),
   ("Class 1 English speaking: when we get a gift we say...", "thank you", ["go away", "no", "sorry"], "Thank you."),
   ("When we ask for something we say...", "please", ["now", "give", "me"], "Please."),
   ("If we hurt someone by mistake, we say...", "sorry", ["well done", "goodbye", "hurray"], "Sorry."),
   ("When someone is speaking, we should...", "listen", ["shout", "run", "sleep"], "Listen.")],
  ["Greeting times (e.g. when 'afternoon' begins) are by common usage."], prereq=["class1-english-simple-sentences"])

p.write()
