import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from p13_kit import *
from p13_fig import *

p = newpack("class2-science", "Elementary Science — Class 2", "Class 2", "sciences",
    "Class 2 science: what living things need, growing, seeds and plants, animal groups, food groups, health and hygiene, water, weather and seasons, materials, the Sun and Moon, safety and waste.",
    REF % "Level I (Class 2) — Elementary Science")
R = p.programRef
NOTE = "Elementary science content is kept to simple, well-known facts; to be reviewed by a primary teacher."
HNOTE = "Health and hygiene advice is conservative and general; to be reviewed by a health worker or nurse. It never replaces seeing a nurse or a doctor."
def C(n, shape="circle", color="orange", per=5, w=300, h=120): return count(n, shape, color, per, w, h)

ch = p.chapter("living-things", "Living things", R)
lesson(ch, "needs-of-living", "What living things need", ["Say what living things need.", "Compare living and non-living things."],
  [("definition", "Needs", "All living things need **food**, **water** and **air**. Animals also need **shelter**. Plants need **light** to make their food. A living thing that does not get what it needs may die."),
   ("retenir", "Seven signs of life", "Living things **move**, **breathe**, **feed**, **grow**, **have young**, **sense** the world and **get rid of waste**. Non-living things do none of these."),
   ("pieges", "Common mistakes", "- Plants move too, but slowly (they grow towards light).\n- A seed is alive.\n- Fire seems to grow and move, but it is not alive.")],
  [("Example 1", "Name three needs of an animal.", ["Animals need food and water.", "They also need air."], "Food, water and air", cards(["food", "water", "air", "shelter"], 4, 400, ch=44, size=16)),
   ("Example 2", "Is a candle flame alive?", ["It moves and seems to grow.", "But it does not eat or have young. It is not alive."], "No", None)],
  (cards(["move", "breathe", "feed", "grow", "have young", "sense"], 3, 400, ch=44, size=15), "Signs of life.", "Six boxes: move, breathe, feed, grow, have young, sense."),
  [("m", "Which is a need of all living things?", "water", ["toys", "money", "paint"], "Water."), ("t", "A plant is a living thing.", True, "Yes."), ("m", "Which is NOT living?", "a stone", ["a tree", "a fish", "a baby"], "Stone.")],
  [("x", "Match the living thing with what it needs.", [("fish", "water to swim in"), ("plant", "light"), ("dog", "food")], "Think about each."), ("m", "Which does a hen NOT need?", "a motorbike", ["food", "water", "air"], "Not a motorbike.")],
  ("p", "A teacher shows a goat, a mango tree, a stone and a toy car.", [("n", "How many are living?", 2, "Goat and mango tree."), ("m", "Why is the toy car non-living?", "it does not grow or breathe", ["it is red", "it is small", "it is new"], "No life signs.")]),
  [("Class 2 science living things: all living things need...", "food, water and air", ["toys only", "paint only", "cars"], "Needs."),
   ("Class 2 science living things: which is a sign of life?", "growing", ["rolling", "burning", "melting"], "Growing."),
   ("Which does a plant need to make food?", "light", ["plastic", "noise", "toys"], "Light."),
   ("A living thing that gets no food and water may...", "die", ["fly", "float", "sing"], "Die."),
   ("Which is non-living?", "a pencil", ["a bird", "a seed", "an ant"], "Pencil.")],
  [NOTE])

lesson(ch, "growing-up", "Growing and changing", ["Say how babies grow into adults.", "Name animal babies."],
  [("definition", "Growing", "Living things **grow** and **change**. A baby grows into a child, then a teenager and then an adult. Growing needs good food, clean water, sleep and exercise."),
   ("retenir", "Animal babies", "A hen's baby is a **chick**. A cow's baby is a **calf**. A dog's baby is a **puppy**. A goat's baby is a **kid**. A cat's baby is a **kitten**. A frog starts as an egg, then a **tadpole**."),
   ("pieges", "Common mistakes", "- Growing does not mean getting fat only.\n- A tadpole is not a fish; it becomes a frog.\n- Each animal has its own baby name.")],
  [("Example 1", "What is a baby hen called?", ["A hen lays eggs.", "The baby is a chick."], "A chick", cards(["hen → chick", "cow → calf", "dog → puppy", "cat → kitten"], 2, 400, ch=44, size=16)),
   ("Example 2", "What do children need to grow well?", ["Good food and clean water.", "Also sleep and play."], "Good food, clean water, sleep", None)],
  (cards(["baby", "child", "teenager", "adult"], 4, 400, ch=44, size=16), "How people grow.", "Four boxes: baby, child, teenager, adult."),
  [("m", "A baby dog is a...", "puppy", ["kitten", "calf", "chick"], "Puppy."), ("m", "A baby cow is a...", "calf", ["kid", "puppy", "chick"], "Calf."), ("t", "A baby grows into a child.", True, "Yes.")],
  [("x", "Match the animal with its baby.", [("goat", "kid"), ("cat", "kitten"), ("hen", "chick")], "Baby names."), ("m", "A frog begins life as a...", "tadpole", ["puppy", "chick", "calf"], "Tadpole (after the egg).")],
  ("p", "A farmer near Bafoussam has a hen with 6 chicks and a cow with 1 calf.", [("n", "How many baby animals?", 7, "6 + 1 = 7."), ("m", "What helps the chicks grow?", "food and water", ["toys", "paint", "stones"], "Food and water.")]),
  [("Class 2 science growing: a baby goat is a...", "kid", ["calf", "kitten", "chick"], "Kid."),
   ("Class 2 science growing: a baby cat is a...", "kitten", ["puppy", "kid", "calf"], "Kitten."),
   ("People grow from a baby to a...", "child", ["seed", "tadpole", "chick"], "Child."),
   ("To grow well we need...", "good food and rest", ["only sweets", "no sleep", "no water"], "Good food."),
   ("A tadpole becomes a...", "frog", ["fish", "bird", "snake"], "Frog.")],
  [HNOTE], prereq=["class2-science-needs-of-living"])

lesson(ch, "seeds-plants", "From seed to plant", ["Describe how a seed grows.", "Say what a seed needs."],
  [("definition", "Germination", "A seed grows into a new plant when it has **water**, **warmth** and **air**. First the seed takes in water. Then a small **root** grows down. Then a **shoot** grows up and makes leaves."),
   ("retenir", "Where seeds come from", "Flowers make fruits. Fruits have **seeds** inside. Beans, maize and groundnuts are seeds. Some seeds travel by wind, water or animals."),
   ("pieges", "Common mistakes", "- A seed does not need light to start growing, but the young plant does.\n- Do not plant seeds too deep.\n- A dry seed will not grow.")],
  [("Example 1", "Put the steps in order: leaves, seed, root.", ["First the seed. Then the root grows.", "Then the shoot and leaves: seed, root, leaves."], "seed, root, leaves", cards(["1 seed", "2 root", "3 shoot", "4 leaves"], 4, 400, ch=44, size=15)),
   ("Example 2", "Name three things a seed needs to grow.", ["It needs water.", "It also needs warmth and air."], "Water, warmth and air", None)],
  (cards(["seed", "root grows", "shoot grows", "leaves"], 4, 400, ch=44, size=14), "From seed to plant.", "Four boxes showing the growth of a plant."),
  [("m", "A seed needs water and...", "warmth", ["paint", "sand only", "plastic"], "Warmth."), ("m", "Which grows first from a bean seed?", "the root", ["the flower", "the fruit", "the leaf"], "The root."), ("t", "Maize is a seed.", True, "Yes.")],
  [("x", "Match the step with the order.", [("1", "seed"), ("2", "root"), ("3", "shoot")], "Order of growth."), ("m", "A dry seed will...", "not grow well", ["grow fast", "sing", "melt"], "It needs water.")],
  ("p", "Ngum plants 10 bean seeds. 7 grow into plants.", [("n", "How many do not grow?", 3, "10 − 7 = 3."), ("m", "What could help the other seeds to grow?", "enough water", ["more stones", "no water", "paper"], "Water.")]),
  [("Class 2 science seeds: a seed needs...", "water, warmth and air", ["paint and glue", "plastic", "toys"], "Needs."),
   ("Class 2 science seeds: fruits have...", "seeds inside", ["bones inside", "eggs", "stones always"], "Seeds."),
   ("What grows first from a seed?", "the root", ["the flower", "the fruit", "the bark"], "Root."),
   ("Which is a seed?", "a bean", ["a pencil", "a stone", "a coin"], "A bean."),
   ("Seeds can travel by...", "wind or animals", ["magic", "motorbikes only", "paper"], "Wind and animals.")],
  [NOTE], prereq=["class2-science-growing-up"])

lesson(ch, "plant-needs", "What plants need", ["Say what plants need to grow.", "Describe a simple plant experiment."],
  [("definition", "Plants need", "Plants need **light**, **water**, **air** and **soil** (or something to hold the roots). With light, water and air the green leaves make **food** for the plant."),
   ("methode", "A fair test", "Take two plants. Give one water and light. Give the other no water. Keep everything else the same. After a few days look at both. This is a **fair test**: we change only one thing."),
   ("pieges", "Common mistakes", "- Too much water is not good either.\n- A plant in a dark cupboard will turn pale and weak.\n- Change only ONE thing in a test.")],
  [("Example 1", "Plant A gets water. Plant B gets none. Which plant grows better?", ["Plants need water.", "Plant A grows better."], "Plant A", cards(["Plant A: water", "Plant B: no water"], 2, 400, ch=44, size=16)),
   ("Example 2", "Why do we keep light the same in the test?", ["Only one thing must change.", "If light also changed, we would not know the cause."], "To make it a fair test", None)],
  (cards(["light", "water", "air", "soil"], 4, 400, ch=44, size=16), "What plants need.", "Four boxes: light, water, air, soil."),
  [("m", "Which is a need of a plant?", "water", ["sweets", "oil", "paint"], "Water."), ("t", "Plants need light.", True, "Yes."), ("m", "In a fair test we change...", "one thing only", ["everything", "nothing", "five things"], "One thing.")],
  [("m", "A plant is kept in a dark cupboard for a week. It will probably...", "become pale and weak", ["grow very strong", "turn blue", "make fruit"], "Light is needed."), ("t", "Too much water is always good.", False, "Too much can harm the roots.")],
  ("p", "Pupils test two bean plants: one on a sunny window, one in a dark box. Both get water.", [("m", "What is changed in the test?", "the light", ["the water", "the beans", "the day"], "Light."), ("m", "Which plant grows better?", "the one in the light", ["the one in the box", "both are same", "neither"], "Light.")]),
  [("Class 2 science plants: which is NOT a need of a plant?", "plastic toys", ["light", "water", "air"], "Not toys."),
   ("Class 2 science plants: leaves make food using...", "light", ["noise", "paint", "plastic"], "Light."),
   ("In a fair test we change...", "only one thing", ["many things", "nothing", "all things"], "One."),
   ("A plant without water will...", "wilt", ["grow faster", "sing", "fly"], "Wilt."),
   ("Roots are held in...", "soil", ["air only", "paper", "plastic only"], "Soil.")],
  ["Photosynthesis is not named in Class 2; the text keeps to 'leaves make food using light'."], prereq=["class2-science-seeds-plants"])

ch = p.chapter("animals-body", "Animals and our body", R)
lesson(ch, "animal-groups", "Groups of animals", ["Name animal groups: mammals, birds, fish and insects.", "Say what is special about each."],
  [("definition", "Mammals and birds", "**Mammals** have hair or fur and feed their babies with milk: goat, dog, cow, monkey, bat, whale. **Birds** have feathers, wings and two legs, and lay eggs: hen, duck, parrot."),
   ("retenir", "Fish and insects", "**Fish** live in water, have scales and breathe with gills. **Insects** have **6 legs**: ant, bee, mosquito, butterfly. A spider has 8 legs, so it is not an insect."),
   ("pieges", "Common mistakes", "- A bat is a mammal, not a bird.\n- A whale lives in water but is a mammal.\n- Spiders have 8 legs, not 6.")],
  [("Example 1", "Is a goat a mammal or a bird?", ["A goat has hair and gives milk.", "It is a mammal."], "A mammal", cards(["mammal: hair, milk", "bird: feathers, eggs", "fish: scales, gills", "insect: 6 legs"], 2, 400, ch=44, size=14)),
   ("Example 2", "How many legs has an ant?", ["An ant is an insect.", "Insects have 6 legs."], "6 legs", C(6, "circle", "brown", 6, 300, 60))],
  (cards(["goat: mammal", "hen: bird", "tilapia: fish", "ant: insect"], 2, 400, ch=44, size=16), "Examples of each group.", "Four boxes with a mammal, a bird, a fish and an insect."),
  [("m", "Which is a bird?", "a duck", ["a goat", "a fish", "an ant"], "Duck."), ("n", "How many legs has an insect?", 6, "Six.", None, {"figure": C(6, "circle", "brown", 6, 300, 60)}), ("m", "Which animal feeds its babies with milk?", "a cow", ["a hen", "a fish", "an ant"], "Cow.")],
  [("x", "Match the animal with its group.", [("monkey", "mammal"), ("parrot", "bird"), ("bee", "insect")], "Groups."), ("t", "A bat is a bird.", False, "A bat is a mammal.")],
  ("p", "A pond has 5 fish, 3 frogs and 2 ducks. A farm has 4 hens.", [("n", "How many birds in all? (ducks and hens)", 6, "2 + 4 = 6."), ("n", "How many animals are in the pond? (fish, frogs, ducks)", 10, "5 + 3 + 2 = 10.")]),
  [("Class 2 science animal groups: an animal with feathers is a...", "bird", ["fish", "insect", "mammal"], "Bird."),
   ("Class 2 science animal groups: an animal with 6 legs is an...", "insect", ["bird", "fish", "mammal"], "Insect."),
   ("Fish breathe with...", "gills", ["lungs only", "wings", "feathers"], "Gills."),
   ("A dog is a...", "mammal", ["bird", "insect", "fish"], "Mammal."),
   ("Which has 8 legs?", "a spider", ["an ant", "a bee", "a fly"], "Spider.")],
  ["Only simple groups; reptiles and amphibians come later."], prereq=["class2-science-growing-up"])

lesson(ch, "animal-homes", "Animal homes and food", ["Match animals with their homes.", "Say what animals eat."],
  [("definition", "Homes", "Animals live in homes called **habitats**. A bird lives in a **nest**. A bee lives in a **hive**. A fish lives in **water**. A dog may live in a **kennel**. A hen lives in a **coop**."),
   ("retenir", "What animals eat", "**Herbivores** eat plants only: goat, cow, rabbit. **Carnivores** eat meat: lion, crocodile. **Omnivores** eat plants and meat: pig, chicken, people."),
   ("pieges", "Common mistakes", "- A goat is a herbivore, not a carnivore.\n- Many animals are omnivores.\n- Do not disturb wild animals in their homes.")],
  [("Example 1", "Where does a bee live?", ["Bees make honey.", "They live in a hive."], "In a hive", cards(["bird: nest", "bee: hive", "fish: water", "hen: coop"], 2, 400, ch=44, size=16)),
   ("Example 2", "A cow eats grass. Is it a herbivore or a carnivore?", ["It eats plants only.", "It is a herbivore."], "A herbivore", None)],
  (cards(["herbivore: plants", "carnivore: meat", "omnivore: both"], 3, 400, ch=44, size=14), "What animals eat.", "Three boxes: herbivore plants, carnivore meat, omnivore both."),
  [("m", "A bird lives in a...", "nest", ["hive", "kennel", "pond"], "Nest."), ("m", "A herbivore eats...", "plants", ["meat only", "stones", "plastic"], "Plants."), ("m", "A lion is a...", "carnivore", ["herbivore", "omnivore", "insect"], "Carnivore.")],
  [("x", "Match the animal with its home.", [("bee", "hive"), ("hen", "coop"), ("fish", "water")], "Homes."), ("t", "A goat eats meat only.", False, "A goat is a herbivore.")],
  ("p", "A farmer keeps goats, hens and pigs.", [("m", "Which animal is a herbivore?", "a goat", ["a lion", "a crocodile", "a snake"], "Goat."), ("m", "Which animal is an omnivore?", "a pig", ["a goat", "a cow", "a rabbit"], "Pig.")]),
  [("Class 2 science animal homes: a bee lives in a...", "hive", ["nest", "pond", "kennel"], "Hive."),
   ("Class 2 science animal food: an animal that eats only plants is a...", "herbivore", ["carnivore", "omnivore", "insect"], "Herbivore."),
   ("A hen lives in a...", "coop", ["hive", "nest in water", "pond"], "Coop."),
   ("A crocodile is a...", "carnivore", ["herbivore", "omnivore", "plant"], "Carnivore."),
   ("People are...", "omnivores", ["herbivores only", "carnivores only", "insects"], "Omnivores.")],
  [NOTE], prereq=["class2-science-animal-groups"])

lesson(ch, "food-groups", "Food groups", ["Name the three food groups.", "Plan a simple healthy meal."],
  [("definition", "Three groups", "**Energy foods** give us energy: yam, cassava, plantain, rice, maize, bread. **Body-building foods** help us grow: beans, fish, eggs, meat, groundnuts, milk. **Protective foods** keep us healthy: fruits and vegetables like mango, orange, pawpaw, eru, spinach."),
   ("retenir", "A good meal", "A healthy meal has a food from each group. For example: plantain, fish and green vegetables, and a fruit. Drink clean water. Do not eat too many sweets."),
   ("pieges", "Common mistakes", "- Sweets give energy but they are not a full meal.\n- Do not skip meals.\n- Wash fruits and vegetables.")],
  [("Example 1", "Which group is beans in?", ["Beans help us grow.", "Body-building food."], "Body-building", cards(["energy: yam", "building: beans", "protective: mango"], 3, 400, ch=44, size=14)),
   ("Example 2", "Name a protective food.", ["Fruits and vegetables protect us.", "Orange."], "Orange", None)],
  (cards(["energy: rice, yam", "building: fish, eggs", "protective: fruit, eru"], 1, 400, ch=40, size=15), "Three food groups.", "Three boxes with the three food groups and examples."),
  [("m", "Which is an energy food?", "cassava", ["fish", "eru", "egg"], "Cassava."), ("m", "Which is a body-building food?", "fish", ["rice", "yam", "bread"], "Fish."), ("m", "Which is a protective food?", "pawpaw", ["rice", "oil", "sugar"], "Pawpaw.")],
  [("x", "Match the food with its group.", [("yam", "energy"), ("beans", "body-building"), ("orange", "protective")], "Three groups."), ("t", "A healthy meal has foods from every group.", True, "Yes.")],
  ("p", "Mama cooks plantain, fish and eru (a green vegetable). Ada eats an orange afterwards.", [("m", "Which food gives energy?", "plantain", ["fish", "eru", "orange"], "Plantain."), ("m", "Which food helps the body to grow?", "fish", ["plantain", "eru", "orange"], "Fish.")]),
  [("Class 2 science food groups: foods that give energy are...", "yam and rice", ["fish and eggs", "water", "salt"], "Energy foods."),
   ("Class 2 science food groups: foods that help us grow are...", "beans and fish", ["sweets", "sand", "soap"], "Body-building."),
   ("Fruits and vegetables are...", "protective foods", ["energy foods only", "not food", "poison"], "Protective."),
   ("A healthy meal has...", "different kinds of food", ["only sweets", "only salt", "no water"], "Variety."),
   ("Which should we eat less of?", "sweets", ["vegetables", "fruit", "beans"], "Sweets.")],
  ["The three groups (energy, body-building, protective) follow a common primary-school way of teaching; check with the textbook. " + HNOTE], prereq=["class2-science-animal-homes"])

lesson(ch, "health-hygiene", "Staying healthy", ["Say ways to stay healthy.", "Know how to avoid mosquito bites."],
  [("definition", "Healthy habits", "To stay healthy: wash your hands with soap, eat different foods, drink clean water, sleep enough, play outside, and keep your home clean. Go to the clinic when you are ill."),
   ("retenir", "Mosquitoes", "Some mosquitoes carry **malaria**. Sleep under a **mosquito net**. Do not leave stagnant water near the house, because mosquitoes lay eggs in it. If you have a fever, tell an adult so you can go to a health centre."),
   ("pieges", "Common mistakes", "- Do not treat yourself with medicine you do not know.\n- A fever needs an adult and a health worker.\n- Empty old tins and pots that hold rainwater.")],
  [("Example 1", "How can a family avoid malaria?", ["Sleep under a mosquito net.", "Also clear places where water stays."], "Use a net and clear stagnant water", cards(["mosquito net", "no stagnant water", "see a nurse if ill"], 3, 400, ch=44, size=13)),
   ("Example 2", "When must you wash your hands?", ["Before eating and after the toilet.", "Also when they are dirty."], "Before eating, after the toilet", None)],
  (cards(["wash hands", "mosquito net", "clean water", "enough sleep"], 2, 400, ch=44, size=16), "Healthy habits.", "Four boxes: wash hands, mosquito net, clean water, enough sleep."),
  [("m", "A mosquito net helps to avoid...", "mosquito bites", ["rain", "noise", "sunlight"], "It keeps mosquitoes away."), ("t", "We should drink clean water.", True, "Yes."), ("m", "If you have a fever you should...", "tell an adult", ["hide it", "take any medicine", "wait a month"], "Tell an adult.")],
  [("m", "Mosquitoes lay eggs in...", "stagnant water", ["a dry cup", "a hot pan", "sand only"], "Water that stays."), ("t", "It is safe to take any medicine we find.", False, "Never.")],
  ("p", "Neba's village has many mosquitoes in the rainy season.", [("m", "What can the family do at night?", "sleep under nets", ["leave windows wide", "sit in the dark", "play outside late"], "Nets."), ("m", "What should they do with old tins that fill with rain?", "empty them", ["leave them full", "add more water", "hide them"], "Empty.")]),
  [("Class 2 science health: to stay healthy we should...", "wash our hands", ["share cups", "never sleep", "eat soil"], "Wash."),
   ("Class 2 science health: a mosquito net helps against...", "mosquito bites", ["noise", "cold", "rain"], "Mosquito."),
   ("When ill we should...", "see a nurse or doctor", ["hide it", "do nothing", "take pills of friends"], "Health worker."),
   ("Stagnant water near the house...", "should be emptied", ["should be kept", "is good for health", "cleans mosquitoes"], "Empty."),
   ("Which is a healthy habit?", "drinking clean water", ["skipping sleep", "never washing", "eating only sweets"], "Clean water.")],
  [HNOTE + " Malaria advice is general; local health-ministry guidance applies."], prereq=["class2-science-food-groups"])

ch = p.chapter("earth-materials", "Water, weather, materials and the sky", R)
lesson(ch, "water-sources", "Where water comes from", ["Name sources of water.", "Say how to make water safe."],
  [("definition", "Sources", "Water comes from **rain**, **rivers**, **springs**, **wells**, **boreholes** and **taps**. Some water is clean, and some is not safe to drink."),
   ("retenir", "Safe water", "Water that is safe to drink is clear, has no bad smell, and has been treated. An adult can **boil** water for a few minutes, or use a **filter** or treatment tablets. Keep it in a clean, covered container."),
   ("pieges", "Common mistakes", "- Clear water can still carry germs.\n- Do not drink water from a dirty pond.\n- Boiled water must be kept covered.")],
  [("Example 1", "Name two sources of water.", ["Rain falls from clouds.", "Rivers and wells also give water."], "Rain and rivers", cards(["rain", "river", "well", "tap"], 4, 400, ch=44, size=16)),
   ("Example 2", "How can an adult make water safer?", ["Boil it.", "Then keep it covered."], "Boil it", None)],
  (cards(["rain", "river", "spring", "well", "borehole", "tap"], 3, 400, ch=44, size=16), "Sources of water.", "Six boxes with rain, river, spring, well, borehole, tap."),
  [("m", "Which is a source of water?", "a river", ["a stone", "a pencil", "a shoe"], "River."), ("m", "How can we make water safer?", "boil it", ["add sand", "shake it", "paint it"], "Boil."), ("t", "Clear water is always safe.", False, "It may still have germs.")],
  [("m", "Where should we keep drinking water?", "in a covered clean container", ["in an open bucket", "in a dirty tin", "on the ground"], "Covered."), ("x", "Match the source with a place.", [("well", "dug in the ground"), ("tap", "in pipes"), ("rain", "falls from clouds")], "Where does it come from?")],
  ("p", "A family in a village uses water from a stream. An adult boils the water and stores it.", [("m", "Why does the adult boil it?", "to make it safer to drink", ["to make it cold", "to colour it", "to make it taste of salt"], "Safer."), ("m", "How should the boiled water be stored?", "covered", ["open", "in the sun uncovered", "on the floor"], "Covered.")]),
  [("Class 2 science water: a source of water is...", "rain", ["sand", "a rock", "a spoon"], "Rain."),
   ("Class 2 science water: to make drinking water safer an adult can...", "boil it", ["stir it", "freeze it for fun", "add dirt"], "Boil."),
   ("Water for drinking should be kept...", "covered", ["open", "dirty", "in a hot tin"], "Covered."),
   ("Which gives water from the ground?", "a well", ["a cloud", "a bus", "a tree house"], "Well."),
   ("Dirty pond water is...", "not safe to drink", ["safe to drink", "good for babies", "healthy"], "Unsafe.")],
  [HNOTE + " Water treatment advice to be checked by a health worker."], prereq=["class2-science-health-hygiene"])

lesson(ch, "weather-seasons", "Weather and seasons", ["Describe types of weather.", "Name the dry and rainy seasons."],
  [("definition", "Weather", "Weather can be **sunny**, **cloudy**, **rainy**, **windy** or **stormy**. We can measure rain in a **rain gauge** and heat with a **thermometer**."),
   ("retenir", "Seasons in Cameroon", "In much of Cameroon there is a **dry season** (little rain) and a **rainy season** (a lot of rain). The time of the seasons is different in the north, the centre and the coast. Farmers plant at the start of the rains."),
   ("pieges", "Common mistakes", "- Do not shelter under a tree in a thunderstorm.\n- Do not walk in flood water.\n- The seasons differ in different regions.")],
  [("Example 1", "In which season do farmers plant seeds?", ["Seeds need water.", "At the start of the rainy season."], "The rainy season", cards(["dry season", "rainy season"], 2, 400, ch=44, size=18)),
   ("Example 2", "Which tool measures how hot it is?", ["It has a thin tube.", "A thermometer."], "A thermometer", None)],
  (cards(["sunny", "cloudy", "rainy", "windy", "stormy"], 3, 400, ch=44, size=18), "Weather words.", "Five boxes: sunny, cloudy, rainy, windy, stormy."),
  [("m", "A thermometer measures...", "how hot or cold it is", ["the wind", "the rain", "the time"], "Heat."), ("m", "A season with a lot of rain is the...", "rainy season", ["dry season", "harvest day", "night"], "Rainy."), ("t", "Seasons are exactly the same in every region.", False, "They differ.")],
  [("m", "In a thunderstorm we should...", "stay indoors", ["shelter under a tree", "play outside", "swim"], "Indoors."), ("x", "Match the tool with what it measures.", [("thermometer", "heat"), ("rain gauge", "rain")], "Tools.")],
  ("p", "A pupil records the rain each day for 5 days: 0, 12, 5, 0, 8 millimetres.", [("n", "How much rain fell in all (millimetres)?", 0 + 12 + 5 + 0 + 8, "25 mm.", "mm"), ("n", "On how many days did it not rain?", 2, "Two days: 0 and 0.")]),
  [("Class 2 science weather: the season with little rain is the...", "dry season", ["rainy season", "play season", "night"], "Dry."),
   ("Class 2 science weather: a rain gauge measures...", "rain", ["heat", "wind", "light"], "Rain."),
   ("A thermometer is used to measure...", "temperature", ["rain", "weight", "length"], "Temperature."),
   ("In a storm it is safest to...", "stay indoors", ["climb trees", "play in the open", "swim"], "Indoors."),
   ("Farmers plant seeds when...", "the rains start", ["the river is dry", "it is the middle of the night", "there is no water"], "Rains.")],
  ["Seasons: the dry/rainy pattern differs a lot across Cameroon; keep wording general and check against the textbook."], prereq=["class2-science-water-sources"])

lesson(ch, "materials-properties", "Properties of materials", ["Describe materials as hard, soft, rough, smooth, stretchy.", "Say which materials float or sink."],
  [("definition", "Properties", "A **property** tells what a material is like. It can be **hard** or **soft**, **rough** or **smooth**, **stretchy** or **stiff**, **waterproof** or not. We choose a material for a job by its properties."),
   ("retenir", "Float or sink", "Some materials **float** on water: wood, a plastic bottle, a cork. Some **sink**: a stone, a coin, a key. Rubber is stretchy and waterproof: so boots are made of rubber."),
   ("pieges", "Common mistakes", "- A big thing can float and a small thing can sink (a small coin sinks, a big log floats).\n- Do not test with sharp or dangerous things.\n- Ask an adult to help.")],
  [("Example 1", "Which will float: a stone or a piece of wood?", ["Wood floats on water.", "A stone sinks."], "The wood", cards(["float: wood", "float: bottle", "sink: stone", "sink: coin"], 2, 400, ch=44, size=16)),
   ("Example 2", "Why are boots made of rubber?", ["Rubber keeps water out.", "It is waterproof."], "It is waterproof", None)],
  (cards(["hard: stone", "soft: cloth", "stretchy: rubber", "waterproof: plastic"], 2, 400, ch=44, size=15), "Properties.", "Four boxes with properties and example materials."),
  [("m", "Which material is stretchy?", "rubber", ["stone", "glass", "wood"], "Rubber."), ("m", "Which will sink?", "a coin", ["a cork", "a plastic bottle", "a dry leaf"], "Coin."), ("t", "Wood is hard.", True, "Yes.")],
  [("x", "Match the material with a property.", [("cloth", "soft"), ("stone", "hard"), ("rubber", "stretchy")], "Properties."), ("m", "A raincoat should be...", "waterproof", ["heavy", "very hard", "see through only"], "Waterproof.")],
  ("p", "Pupils drop 5 things in water: a stone, a coin, a cork, a bottle, a key.", [("n", "How many of these sink? (stone, coin, key)", 3, "Stone, coin and key."), ("n", "How many float? (cork, bottle)", 2, "Cork and bottle.")]),
  [("Class 2 science materials: a material that lets no water through is...", "waterproof", ["stretchy", "rough", "heavy"], "Waterproof."),
   ("Class 2 science materials: which one floats?", "wood", ["a stone", "a key", "a coin"], "Wood."),
   ("A property tells us...", "what a material is like", ["its price", "its colour only", "its name only"], "Properties."),
   ("Rubber is...", "stretchy", ["very hard", "brittle", "heavy"], "Stretchy."),
   ("A material that is not smooth is...", "rough", ["soft", "wet", "clear"], "Rough.")],
  ["Floating of a bottle depends on if it is empty/closed; the text assumes a closed empty bottle."], prereq=["class2-science-weather-seasons"])

lesson(ch, "sun-moon-stars", "The Sun, the Moon and the stars", ["Say that the Sun is a star that gives light and heat.", "Say that the Moon goes round the Earth."],
  [("definition", "The Sun", "The **Sun** is a star. It gives us **light** and **heat**. We see it in the day. It looks big because it is much nearer to us than the other stars."),
   ("retenir", "Moon and stars", "The **Moon** goes round the **Earth**. It shines because it reflects light from the Sun. Its shape seems to change during the month. At night we see **stars**. They are very far away."),
   ("pieges", "Common mistakes", "- Never look straight at the Sun.\n- The Moon does not make its own light.\n- The Sun does not go round the Earth. The Earth turns, so we have day and night.")],
  [("Example 1", "What gives us light and heat in the day?", ["It is a star.", "The Sun."], "The Sun", cards(["Sun: light, heat", "Moon: reflects light", "stars: far away"], 3, 400, ch=44, size=13)),
   ("Example 2", "Why does the Moon shine?", ["It has no light of its own.", "It reflects light from the Sun."], "It reflects sunlight", None)],
  (shapes([CIRCLE(70, 70, 40, fill="yellow"), T(70, 135, "Sun", 14, bold=True), CIRCLE(210, 70, 22, fill="lightblue"), T(210, 115, "Earth", 14, bold=True), CIRCLE(270, 70, 9, fill="grey"), T(300, 75, "Moon", 14, anchor="start", bold=True)], 380, 150), "The Sun, the Earth and the Moon (not to scale).", "A big yellow Sun, a smaller blue Earth and a small grey Moon."),
  [("m", "The Sun is a...", "star", ["planet", "cloud", "moon"], "The Sun is a star."), ("m", "The Moon shines because it...", "reflects sunlight", ["makes its own light", "burns", "is hot"], "Reflects."), ("t", "We should look straight at the Sun.", False, "Never.")],
  [("m", "What goes round the Earth?", "the Moon", ["the Sun", "a cloud", "the wind"], "The Moon."), ("m", "We have day and night because the Earth...", "turns", ["stops", "shrinks", "melts"], "Turns.")],
  ("p", "Ada looks at the sky in the evening.", [("m", "What can she see in the night sky?", "the Moon and stars", ["only the Sun", "the sea", "a rainbow always"], "Moon and stars."), ("m", "Why can she not see the Sun at night?", "that side of the Earth faces away from it", ["the Sun is switched off", "the Sun is behind a hill", "the Sun is tired"], "Earth turns.")]),
  [("Class 2 science sky: the Sun gives us...", "light and heat", ["only noise", "only cold", "water"], "Light and heat."),
   ("Class 2 science sky: the Moon goes round the...", "Earth", ["Sun only", "cloud", "star"], "Earth."),
   ("Stars are...", "very far away", ["near our house", "small lamps", "birds"], "Far."),
   ("Day and night happen because the Earth...", "turns", ["stops", "flies", "shrinks"], "Turns."),
   ("The Moon...", "reflects light from the Sun", ["is a star", "makes heat", "is a cloud"], "Reflects.")],
  ["Simple astronomy; check wording ('goes round the Earth' / 'Earth turns') with the textbook."], prereq=["class2-science-materials-properties"])

lesson(ch, "safety-waste", "Safety and looking after our surroundings", ["Say how to stay safe at home and school.", "Reduce, reuse and put waste in the right place."],
  [("definition", "Safety", "Keep away from fire, hot water, electricity, sharp tools and chemicals. Never touch a dead wire. Keep medicines and chemicals away from small children. Tell a trusted adult if something is dangerous."),
   ("retenir", "Waste", "We make waste every day. **Reduce** waste: use only what you need. **Reuse**: use a bottle again. Put rubbish in a bin. Food waste can go to a compost heap. Do not burn plastic or throw it in rivers."),
   ("pieges", "Common mistakes", "- Do not play near the road, fire or deep water.\n- Do not burn plastic: the smoke is harmful.\n- Wash your hands after touching rubbish.")],
  [("Example 1", "What can you do with an empty plastic bottle?", ["Reuse it to store water.", "Or put it in a bin if it is broken."], "Reuse it", cards(["reduce", "reuse", "bin it", "compost"], 4, 400, ch=44, size=15)),
   ("Example 2", "You see a fallen electric wire. What do you do?", ["Do not touch it.", "Keep away and tell an adult."], "Keep away and tell an adult", None)],
  (cards(["reduce", "reuse", "recycle where possible"], 3, 400, ch=44, size=14), "Looking after our surroundings.", "Three boxes: reduce, reuse, recycle where possible."),
  [("m", "Where should rubbish go?", "in a bin", ["in a river", "under a bed", "on the road"], "Bin."), ("m", "Reuse means to...", "use a thing again", ["throw it away", "burn it", "hide it"], "Use again."), ("t", "It is safe to touch a dead wire.", False, "Never.")],
  [("t", "Food waste can go to a compost heap.", True, "Yes."), ("m", "Which is dangerous?", "burning plastic", ["sweeping", "planting a tree", "using a bin"], "Harmful smoke.")],
  ("p", "A class collects 12 plastic bottles and 8 paper bags for reuse.", [("n", "How many things are collected?", 20, "12 + 8 = 20."), ("n", "Pupils reuse 9 bottles. How many bottles are left?", 3, "12 − 9 = 3.")]),
  [("Class 2 science waste: 'reuse' means to...", "use something again", ["throw it away", "burn it", "break it"], "Use again."),
   ("Class 2 science safety: if you see a fallen electric wire you should...", "keep away and tell an adult", ["touch it", "play with it", "pull it"], "Keep away."),
   ("Rubbish should be put...", "in a bin", ["in a river", "on the road", "in a well"], "Bin."),
   ("Which helps the environment?", "planting trees", ["burning plastic", "spilling oil", "cutting everything"], "Plant trees."),
   ("To reduce waste we...", "use only what we need", ["buy more", "throw food", "break things"], "Reduce.")],
  ["Safety advice is general; check local guidance. Recycling facilities may not exist in all places."], prereq=["class2-science-sun-moon-stars"])

p.write()
