import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from p13_kit import *
from p13_fig import *

p = newpack("class1-science", "Elementary Science — Class 1", "Class 1", "sciences",
    "First science lessons: living and non-living things, my body and senses, plants, animals, food, keeping clean, water, weather, the sun, materials, safety and caring for the environment.",
    REF % "Level I (Class 1) — Elementary Science", wanted=None)
R = p.programRef
NOTE = "Elementary science content is kept to very simple, well-known facts; to be reviewed by a primary teacher."
HNOTE = "Health and hygiene advice is conservative and general; to be reviewed by a health worker or nurse. It never replaces seeing a nurse or a doctor."
def C(n, shape="circle", color="orange", per=5, w=300, h=120): return count(n, shape, color, per, w, h)

ch = p.chapter("living-things", "Living things", R)
lesson(ch, "living-nonliving", "Living and non-living things", ["Tell living things from non-living things.", "Name what living things do."],
  [("definition", "Living things", "**Living things** grow, eat or drink, move and have babies. People, animals and plants are living things."),
   ("retenir", "Non-living things", "**Non-living things** do not grow or eat. A stone, a table, a cup and water are non-living things. A dead leaf is not alive any more."),
   ("pieges", "Common mistakes", "- A tree is alive, even if it does not walk.\n- A car moves, but it is not alive.\n- Seeds are alive and can grow.")],
  [("Example 1", "Is a goat living or non-living?", ["A goat eats and grows.", "It is a living thing."], "Living", cards(["goat: living", "stone: non-living", "tree: living", "cup: non-living"], 2, 400, ch=44, size=16)),
   ("Example 2", "Is a stone living or non-living?", ["A stone does not eat or grow.", "It is non-living."], "Non-living", None)],
  (cards(["living: boy", "living: hen", "living: mango tree", "non-living: chair", "non-living: stone", "non-living: ball"], 3, 400, ch=46, size=13), "Living and non-living things.", "Six boxes: boy, hen, mango tree as living; chair, stone, ball as non-living."),
  [("m", "Which is a living thing?", "a hen", ["a chair", "a stone", "a cup"], "A hen eats and grows."), ("m", "Which is non-living?", "a table", ["a dog", "a tree", "a baby"], "A table is non-living."), ("t", "A tree is a living thing.", True, "Trees grow.")],
  [("x", "Match the thing with living or non-living.", [("cat", "living"), ("book", "non-living")], "Think: does it grow?"), ("m", "Which thing grows?", "a plant", ["a rock", "a pencil", "a bucket"], "Plants grow.")],
  ("p", "Pupils look around the school yard: a tree, a bench, a goat, a ball.", [("n", "How many of the four things are living? (tree and goat)", 2, "The tree and the goat are living."), ("n", "How many are non-living? (bench and ball)", 2, "The bench and the ball are non-living.")]),
  [("Class 1 science living things: which is living?", "a fish", ["a rock", "a ball", "a spoon"], "A fish."),
   ("Class 1 science living things: which is non-living?", "a stone", ["a goat", "a mango tree", "a child"], "A stone."),
   ("Living things can...", "grow", ["stay the same always", "never eat", "never move"], "Grow."),
   ("Is a plant living?", "yes", ["no", "only on Sunday", "only a big one"], "Yes."),
   ("Which does NOT need food?", "a chair", ["a cat", "a baby", "a bird"], "A chair.")],
  [NOTE])

lesson(ch, "my-body", "My body", ["Name main parts of the body.", "Say what each part does."],
  [("definition", "Parts of the body", "The head has the eyes, ears, nose and mouth. We have two arms, two hands, two legs and two feet. We have 10 fingers and 10 toes."),
   ("retenir", "What parts do", "Eyes see. Ears hear. The nose smells. The mouth eats and speaks. Hands hold things. Legs help us walk and run."),
   ("pieges", "Common mistakes", "- We see with eyes, not with ears.\n- Each hand has 5 fingers.\n- Take care of every part of the body.")],
  [("Example 1", "How many fingers on two hands?", ["Each hand has 5 fingers.", "5 + 5 = 10."], "10 fingers", C(10, "circle", "orange", 5, 300, 90)),
   ("Example 2", "Which part do we use to hear?", ["The ears are on the sides of the head.", "We hear with our ears."], "Ears", None)],
  (cards(["eyes see", "ears hear", "nose smells", "mouth eats"], 2, 400, ch=44, size=18), "What the body parts do.", "Four boxes: eyes see, ears hear, nose smells, mouth eats."),
  [("m", "We see with our...", "eyes", ["ears", "feet", "hands"], "Eyes."), ("m", "We walk with our...", "legs", ["arms", "ears", "eyes"], "Legs."), ("n", "How many hands do you have?", 2, "Two hands.")],
  [("x", "Match the body part with its job.", [("eyes", "see"), ("ears", "hear"), ("nose", "smell")], "Think of each job."), ("n", "How many toes on two feet?", 10, "5 + 5 = 10.")],
  ("p", "Kofi counts parts of his body.", [("n", "He has 2 eyes and 2 ears. How many in all?", 4, "2 + 2 = 4."), ("n", "He has 2 hands. Each hand has 5 fingers. How many fingers?", 10, "5 + 5 = 10.")]),
  [("Class 1 science body: we hear with our...", "ears", ["eyes", "knees", "teeth"], "Ears."),
   ("Class 1 science body: how many eyes do we have?", "2", ["1", "3", "10"], "Two."),
   ("We smell with our...", "nose", ["hands", "feet", "hair"], "Nose."),
   ("How many fingers are on one hand?", "5", ["2", "10", "3"], "Five."),
   ("Our legs help us to...", "walk and run", ["see", "smell", "hear"], "Walk.")],
  [NOTE], prereq=["class1-science-living-nonliving"])

lesson(ch, "five-senses", "My five senses", ["Name the five senses.", "Match each sense to its body part."],
  [("definition", "Senses", "We have **five senses**: **sight** (eyes), **hearing** (ears), **smell** (nose), **taste** (tongue) and **touch** (skin)."),
   ("retenir", "Use them", "We see a colour. We hear a drum. We smell a flower. We taste a sweet mango. We feel that ice is cold."),
   ("pieges", "Common mistakes", "- Do not taste things that you do not know.\n- Never smell strong chemicals.\n- Touch only safe things, not hot things or sharp things.")],
  [("Example 1", "Which sense do we use to listen to music?", ["We listen with our ears.", "It is hearing."], "Hearing", cards(["sight: eyes", "hearing: ears", "smell: nose", "taste: tongue", "touch: skin"], 3, 400, ch=44, size=14)),
   ("Example 2", "Which sense tells us that a mango is sweet?", ["The tongue tastes.", "It is the sense of taste."], "Taste", None)],
  (C(5, "star", "yellow", 5, 300, 70), "Five senses.", "Five yellow stars for the five senses."),
  [("n", "How many senses do we have?", 5, "Five."), ("m", "We taste with our...", "tongue", ["nose", "eyes", "ears"], "Tongue."), ("m", "We feel hot and cold with our...", "skin", ["eyes", "nose", "ears"], "Skin.")],
  [("x", "Match the sense with the body part.", [("sight", "eyes"), ("hearing", "ears"), ("smell", "nose")], "Match."), ("m", "Which sense do you use to smell a flower?", "smell", ["sight", "hearing", "touch"], "Smell.")],
  ("p", "Mama cooks ndolé. Ada is near the kitchen.", [("m", "Which sense tells Ada the food smells nice?", "smell", ["hearing", "sight", "touch"], "Nose."), ("m", "Which sense helps her see the green leaves?", "sight", ["smell", "taste", "touch"], "Eyes.")]),
  [("Class 1 science senses: which sense uses the ears?", "hearing", ["sight", "taste", "smell"], "Hearing."),
   ("Class 1 science senses: which sense uses the eyes?", "sight", ["taste", "touch", "hearing"], "Sight."),
   ("Which part of the body helps us taste?", "tongue", ["nose", "ear", "elbow"], "Tongue."),
   ("The sense of touch is felt with the...", "skin", ["eyes", "ears", "teeth"], "Skin."),
   ("How many senses do people have?", "five", ["three", "ten", "two"], "Five.")],
  ["The five senses are the traditional primary-school list."], prereq=["class1-science-my-body"])

lesson(ch, "plants", "Plants and their parts", ["Name the parts of a plant.", "Say what each part does."],
  [("definition", "Parts of a plant", "A plant has **roots**, a **stem**, **leaves** and often **flowers**. Roots are in the soil. The stem holds the plant up. The leaves are green."),
   ("retenir", "Jobs", "Roots take in water from the soil. The stem carries water up. Leaves help the plant make food from light. Flowers can turn into fruits with seeds."),
   ("pieges", "Common mistakes", "- Roots are usually under the ground.\n- Not all plants have flowers all year.\n- A plant needs water to live.")],
  [("Example 1", "Which part of a plant is in the soil?", ["The plant takes water from the soil.", "The roots are in the soil."], "The roots", shapes([LINE(100, 40, 100, 110, width=6, color="green"), POLY([100, 70, 60, 50, 85, 80], fill="lightgreen"), POLY([100, 80, 140, 60, 115, 95], fill="lightgreen"), CIRCLE(100, 30, 14, fill="pink"), RECT(20, 110, 160, 40, fill="orange"), LINE(100, 110, 70, 140, color="brown"), LINE(100, 110, 130, 140, color="brown"), T(190, 35, "flower", 13, anchor="start"), T(190, 70, "leaf", 13, anchor="start"), T(190, 100, "stem", 13, anchor="start"), T(190, 138, "roots", 13, anchor="start")], 260, 160)),
   ("Example 2", "Which part is usually green?", ["Leaves make food.", "They are green."], "The leaves", None)],
  (shapes([LINE(100, 40, 100, 110, width=6, color="green"), POLY([100, 70, 60, 50, 85, 80], fill="lightgreen"), POLY([100, 80, 140, 60, 115, 95], fill="lightgreen"), CIRCLE(100, 30, 14, fill="pink"), RECT(20, 110, 160, 40, fill="orange"), LINE(100, 110, 70, 140, color="brown"), LINE(100, 110, 130, 140, color="brown"), T(190, 35, "flower", 13, anchor="start"), T(190, 70, "leaf", 13, anchor="start"), T(190, 100, "stem", 13, anchor="start"), T(190, 138, "roots", 13, anchor="start")], 260, 160), "A simple plant.", "A plant with a flower, leaves, a stem and roots in the soil."),
  [("m", "Which part takes water from the soil?", "roots", ["leaves", "flowers", "fruit"], "Roots."), ("m", "Which part holds the plant up?", "stem", ["root", "seed", "fruit"], "Stem."), ("t", "Leaves are usually green.", True, "Yes.")],
  [("x", "Match the plant part with its job.", [("roots", "take in water"), ("stem", "holds the plant up"), ("leaves", "make food")], "Think about the job."), ("m", "A seed can grow into a...", "new plant", ["stone", "table", "cloud"], "A plant.")],
  ("p", "Ngum plants a bean seed in school.", [("m", "What does the seed need to grow?", "water", ["stones", "plastic", "paper"], "Water."), ("m", "Which part grows down into the soil first?", "the root", ["the flower", "the leaf", "the fruit"], "The root.")]),
  [("Class 1 science plants: roots are found...", "in the soil", ["in the sky", "on top of flowers", "in a cup only"], "Soil."),
   ("Class 1 science plants: which part is green and flat?", "leaf", ["root", "seed", "stem"], "Leaf."),
   ("A plant needs...", "water", ["plastic", "sweets", "stone"], "Water."),
   ("Which part can become a fruit?", "flower", ["root", "stone", "soil"], "Flower."),
   ("The stem...", "holds the plant up", ["hears", "sings", "swims"], "Holds up.")],
  [NOTE], prereq=["class1-science-living-nonliving"])

lesson(ch, "animals", "Animals around us", ["Name pets, farm animals and wild animals.", "Say how animals move and where they live."],
  [("definition", "Kinds of animals", "**Pets** live with us: a dog, a cat. **Farm animals** give us food: a hen, a goat, a cow. **Wild animals** live in the forest or bush: a monkey, an elephant, a lion."),
   ("retenir", "How animals move", "Birds **fly**. Fish **swim**. Snakes **crawl**. Dogs and goats **walk and run**. Frogs **hop** and swim."),
   ("pieges", "Common mistakes", "- Do not touch wild animals.\n- Animals need food, water and a home.\n- A bat can fly, but it is not a bird.")],
  [("Example 1", "Name a farm animal that gives eggs.", ["Eggs come from a hen.", "A hen is a farm animal."], "A hen", cards(["hen: lays eggs", "goat: gives milk", "cow: gives milk"], 3, 400, ch=44, size=14)),
   ("Example 2", "How does a fish move?", ["Fish live in water.", "They swim."], "It swims", None)],
  (cards(["bird: fly", "fish: swim", "snake: crawl", "dog: run"], 2, 400, ch=44, size=18), "How animals move.", "Four boxes: bird flies, fish swims, snake crawls, dog runs."),
  [("m", "Which animal can fly?", "a bird", ["a fish", "a snake", "a goat"], "A bird."), ("m", "Which animal lives in water?", "a fish", ["a hen", "a goat", "a dog"], "A fish."), ("m", "Which is a pet?", "a cat", ["a lion", "an elephant", "a monkey"], "A cat.")],
  [("x", "Match the animal with how it moves.", [("bird", "flies"), ("fish", "swims"), ("snake", "crawls")], "Match."), ("t", "A lion is a farm animal.", False, "A lion is a wild animal.")],
  ("p", "On a farm near Bafoussam there are 4 hens, 3 goats and 2 cows.", [("n", "How many animals in all?", 9, "4 + 3 + 2 = 9."), ("n", "How many animals have two legs? (hens)", 4, "Hens have two legs; there are 4 hens.")]),
  [("Class 1 science animals: which animal gives us eggs?", "a hen", ["a goat", "a dog", "a cow"], "Hen."),
   ("Class 1 science animals: which animal swims?", "a fish", ["a bird", "a snake", "a monkey"], "Fish."),
   ("A wild animal is a...", "monkey", ["hen", "goat", "pet dog"], "Monkey."),
   ("A bird moves by...", "flying", ["swimming", "crawling", "rolling"], "Flying."),
   ("Animals need...", "food and water", ["only toys", "only paper", "only stones"], "Food and water.")],
  [NOTE], prereq=["class1-science-plants"])

ch = p.chapter("food-health", "Food, health and water", R)
lesson(ch, "food", "Food we eat", ["Name foods that come from plants and from animals.", "Say that we need different foods to grow."],
  [("definition", "Food", "We eat food to **grow**, to have **energy** and to stay **well**. Food comes from **plants** and from **animals**."),
   ("retenir", "Some foods", "From plants: yam, cassava, plantain, maize, beans, mango, orange, groundnuts. From animals: fish, eggs, meat, milk. We should eat many kinds of food."),
   ("pieges", "Common mistakes", "- Do not eat only sweets.\n- Wash fruits before you eat them.\n- Drink clean water every day.")],
  [("Example 1", "Does a mango come from a plant or an animal?", ["A mango grows on a tree.", "It comes from a plant."], "A plant", cards(["plant: mango", "plant: yam", "animal: egg", "animal: fish"], 2, 400, ch=44, size=16)),
   ("Example 2", "Does an egg come from a plant or an animal?", ["A hen lays an egg.", "It comes from an animal."], "An animal", None)],
  (cards(["yam", "plantain", "beans", "fish", "egg", "mango"], 3, 400, ch=44, size=18), "Foods we eat.", "Six boxes with yam, plantain, beans, fish, egg and mango."),
  [("m", "Which food comes from a plant?", "plantain", ["egg", "fish", "milk"], "Plantain."), ("m", "Which food comes from an animal?", "fish", ["yam", "beans", "mango"], "Fish."), ("t", "We should eat many kinds of food.", True, "Yes.")],
  [("x", "Match the food with where it comes from.", [("mango", "a tree"), ("egg", "a hen"), ("fish", "water")], "Think of the source."), ("m", "Which drink is best for the body?", "clean water", ["only sweet drinks", "only soda", "only tea"], "Clean water.")],
  ("p", "Ada's mother cooks beans, plantain and fish.", [("m", "Which of these come from plants?", "beans and plantain", ["fish only", "fish and beans", "plantain and fish"], "Beans and plantain."), ("m", "Which of these comes from an animal?", "fish", ["beans", "plantain", "none"], "Fish.")]),
  [("Class 1 science food: which food comes from a hen?", "an egg", ["a yam", "a mango", "beans"], "Egg."),
   ("Class 1 science food: which food grows on a tree?", "a mango", ["an egg", "fish", "milk"], "Mango."),
   ("We eat food to...", "grow and have energy", ["be sad", "break things", "get tired"], "Grow."),
   ("Which drink should we have each day?", "clean water", ["only sweets", "paint", "soap"], "Water."),
   ("Fish is food from...", "an animal", ["a tree", "a stone", "a cloud"], "Animal.")],
  [HNOTE], prereq=["class1-science-animals"])

lesson(ch, "keeping-clean", "Keeping clean", ["Say how to keep the body clean.", "Wash hands at the right times."],
  [("definition", "Keeping clean", "We keep clean to stay **healthy**. We **bath** every day. We **brush our teeth** in the morning and before sleep. We wear **clean clothes**."),
   ("retenir", "Wash your hands", "Wash your hands with **soap and clean water** before you eat, after you use the toilet, and when they are dirty. Rub for as long as you sing a short song. Then dry them."),
   ("pieges", "Common mistakes", "- Water alone does not clean as well as soap and water.\n- Do not share towels or toothbrushes.\n- Keep your nails short and clean.")],
  [("Example 1", "When should you wash your hands?", ["Before you eat, because food goes to your mouth.", "Also after the toilet."], "Before eating and after the toilet", cards(["before eating", "after the toilet", "when dirty"], 3, 400, ch=44, size=14)),
   ("Example 2", "What do you need to wash your hands well?", ["Water that is clean.", "And soap."], "Soap and clean water", None)],
  (cards(["wash hands", "brush teeth", "take a bath", "clean clothes"], 2, 400, ch=44, size=18), "Keeping clean.", "Four boxes: wash hands, brush teeth, take a bath, clean clothes."),
  [("m", "We wash our hands with...", "soap and water", ["only sand", "mud", "leaves only"], "Soap and water."), ("m", "We brush our teeth with a...", "toothbrush", ["spoon", "comb", "cup"], "Toothbrush."), ("t", "We should wash our hands before we eat.", True, "Yes.")],
  [("m", "When must you wash your hands?", "after using the toilet", ["when you are asleep", "when you see a bird", "never"], "After the toilet."), ("t", "We can share a toothbrush.", False, "Each person has own toothbrush.")],
  ("p", "Ngu comes home from play with dirty hands.", [("m", "What should he do before eating?", "wash his hands with soap", ["eat at once", "wipe on his shirt", "do nothing"], "Wash with soap."), ("m", "When should Ngu brush his teeth?", "in the morning and before sleep", ["only on Sunday", "never", "only after sweets"], "Morning and night.")]),
  [("Class 1 science hygiene: we wash our hands with...", "soap and clean water", ["mud", "sand", "dust"], "Soap."),
   ("Class 1 science hygiene: we brush our teeth...", "morning and night", ["once a year", "only on Monday", "never"], "Twice a day."),
   ("Before eating, we should...", "wash our hands", ["run", "jump", "sleep"], "Wash."),
   ("Which keeps us healthy?", "taking a bath each day", ["never washing", "eating dirt", "sharing towels"], "Bath."),
   ("Our nails should be...", "short and clean", ["very long", "dirty", "painted with mud"], "Short and clean.")],
  [HNOTE], prereq=["class1-science-food"])

lesson(ch, "water", "Water", ["Say why we need water.", "Know how to keep water clean."],
  [("definition", "Water", "All living things need **water**. We drink water. We wash with water. We cook with water. Plants need water to grow."),
   ("retenir", "Clean water", "Drink only **clean water**. Water from a tap or a well can be clean. If you are not sure, an adult can boil it or treat it. Keep water in a covered container. Do not waste water."),
   ("pieges", "Common mistakes", "- Water that looks clear can still be unsafe.\n- Do not drink from a dirty stream.\n- Close the tap when you are not using it.")],
  [("Example 1", "Name two uses of water.", ["We drink it.", "We also wash with it."], "Drinking and washing", cards(["drink", "wash", "cook", "water plants"], 2, 400, ch=44, size=18)),
   ("Example 2", "Why do we cover our water pot?", ["Dust and insects can fall in.", "A cover keeps the water clean."], "To keep it clean", None)],
  (cards(["drink", "wash", "cook", "plants"], 4, 400, ch=44, size=16), "What we use water for.", "Four boxes: drink, wash, cook, plants."),
  [("m", "We need water to...", "drink", ["break", "burn", "hide"], "Drink."), ("t", "Plants need water.", True, "Yes."), ("m", "Which water is best to drink?", "clean water", ["muddy water", "dirty water", "water with rubbish"], "Clean water.")],
  [("m", "A good way to keep water clean is to...", "cover it", ["leave it open", "put dirt in it", "throw rubbish in"], "Cover."), ("t", "We should leave the tap open all day.", False, "We should not waste water.")],
  ("p", "Mama fills a bucket with water at the tap.", [("m", "She covers the bucket. Why?", "to keep the water clean", ["to make it hot", "to hide it", "for fun"], "Clean."), ("m", "Which of these is NOT a use of water?", "eating stones", ["drinking", "washing", "cooking"], "Not eating stones.")]),
  [("Class 1 science water: which water is safe to drink?", "clean water", ["dirty water", "muddy water", "water with soap"], "Clean."),
   ("Class 1 science water: plants need...", "water", ["plastic", "metal", "paper"], "Water."),
   ("We should keep our drinking water...", "covered", ["open", "dirty", "hot always"], "Covered."),
   ("We use water to...", "wash", ["cut wood", "make a stone", "build a house alone"], "Wash."),
   ("We should not...", "waste water", ["drink water", "wash hands", "cook"], "Waste.")],
  [HNOTE + " Water treatment (boiling, filters) to be checked by a health worker."], prereq=["class1-science-keeping-clean"])

ch = p.chapter("world-around", "The world around us", R)
lesson(ch, "weather", "Weather", ["Name kinds of weather.", "Say what to wear for each."],
  [("definition", "Weather", "Weather tells us how it is outside. It can be **sunny**, **rainy**, **cloudy** or **windy**. It can be hot or cold."),
   ("retenir", "What to wear", "In the sun wear a hat. In the rain take an umbrella or a raincoat. In cold weather wear a sweater. Drink water when it is hot."),
   ("pieges", "Common mistakes", "- Do not stand under a tree in a storm.\n- Do not look at the sun directly.\n- Weather changes from day to day.")],
  [("Example 1", "It is raining. What can you take?", ["An umbrella keeps off rain.", "Take an umbrella."], "An umbrella", cards(["sunny", "rainy", "cloudy", "windy"], 4, 400, ch=44, size=16)),
   ("Example 2", "What weather has a bright sun?", ["The sun shines.", "It is sunny."], "Sunny", None)],
  (cards(["sunny: hat", "rainy: umbrella", "cloudy", "windy"], 2, 400, ch=44, size=16), "Weather words.", "Four boxes with sunny, rainy, cloudy and windy."),
  [("m", "In the rain we use an...", "umbrella", ["hat only", "ice", "fan"], "Umbrella."), ("m", "The sun is shining. The weather is...", "sunny", ["rainy", "cloudy", "windy"], "Sunny."), ("t", "Clouds can bring rain.", True, "Often.")],
  [("x", "Match the weather with what we wear or use.", [("sunny", "hat"), ("rainy", "umbrella"), ("cold", "sweater")], "Choose."), ("m", "When it is very hot, we should...", "drink water", ["stay in the sun", "run all day", "wear a coat"], "Drink water.")],
  ("p", "Pupils make a weather chart for 5 days: 2 sunny days, 2 rainy days, 1 cloudy day.", [("n", "How many sunny days?", 2, "2."), ("n", "How many days were NOT rainy? (5 − 2)", 3, "3.")]),
  [("Class 1 science weather: when it rains we may use...", "an umbrella", ["a fan", "ice cream", "a drum"], "Umbrella."),
   ("Class 1 science weather: a day with a bright sun is...", "sunny", ["rainy", "windy", "cloudy"], "Sunny."),
   ("Many clouds in the sky means it is...", "cloudy", ["sunny", "dry", "night"], "Cloudy."),
   ("Strong air moving is called...", "wind", ["sun", "rain", "moon"], "Wind."),
   ("In hot weather we should...", "drink water", ["run in the sun", "wear a thick coat", "stay without water"], "Drink.")],
  ["Weather terms only; seasons (rainy/dry) come in Class 2."], prereq=["class1-science-water"])

lesson(ch, "day-night-sun", "Day, night and the Sun", ["Tell day from night.", "Say that the Sun gives us light and heat."],
  [("definition", "Day and night", "In the **day** it is light because of the **Sun**. At **night** it is dark. We see the **moon** and **stars** in the night sky."),
   ("retenir", "The Sun", "The Sun gives us **light** and **heat**. It helps plants grow. We must never look straight at the Sun. It can hurt our eyes."),
   ("pieges", "Common mistakes", "- Never look straight at the Sun.\n- The Sun is far away.\n- The moon does not make its own light.")],
  [("Example 1", "When do we see the stars?", ["Stars shine in the night sky.", "At night."], "At night", shapes([CIRCLE(70, 60, 36, fill="yellow"), T(70, 115, "day: the Sun", 13, bold=True), RECT(170, 20, 200, 120, fill="blue"), CIRCLE(200, 50, 14, fill="white"), CIRCLE(260, 80, 4, fill="yellow"), CIRCLE(310, 45, 4, fill="yellow"), CIRCLE(340, 100, 4, fill="yellow"), T(270, 155, "night: moon and stars", 13, bold=True)], 400, 170)),
   ("Example 2", "What gives us light in the day?", ["Light comes from the Sun.", "The Sun."], "The Sun", None)],
  (shapes([CIRCLE(70, 60, 36, fill="yellow"), T(70, 115, "day: the Sun", 13, bold=True), RECT(170, 20, 200, 120, fill="blue"), CIRCLE(200, 50, 14, fill="white"), CIRCLE(260, 80, 4, fill="yellow"), CIRCLE(310, 45, 4, fill="yellow"), CIRCLE(340, 100, 4, fill="yellow"), T(270, 155, "night: moon and stars", 13, bold=True)], 400, 170), "Day and night.", "A yellow sun for day and a dark blue sky with moon and stars for night."),
  [("m", "What gives us light in the day?", "the Sun", ["a star at night", "a lamp only", "the rain"], "The Sun."), ("m", "When do we see the moon best?", "at night", ["at noon", "at breakfast", "in a cave only"], "Night."), ("t", "We should look straight at the Sun.", False, "Never; it can hurt our eyes.")],
  [("x", "Match.", [("day", "the Sun shines"), ("night", "we see stars")], "Think of the sky."), ("m", "The Sun gives us light and...", "heat", ["cold", "noise", "water only"], "Heat.")],
  ("p", "Neba plays outside at noon and goes to bed at night.", [("m", "Is it light or dark at noon?", "light", ["dark", "cold only", "rainy always"], "Light."), ("m", "What can he see in the sky at night?", "the moon and stars", ["the Sun", "a rainbow", "nothing ever"], "Moon and stars.")]),
  [("Class 1 science Sun: the Sun gives us...", "light and heat", ["only sound", "only water", "only cold"], "Light and heat."),
   ("Class 1 science night: what can we see in the night sky?", "stars", ["the Sun", "a rainbow", "a school"], "Stars."),
   ("It is dark at...", "night", ["noon", "midday", "morning always"], "Night."),
   ("Should we look at the Sun?", "no, never straight at it", ["yes, a long time", "yes, with no hat", "only at noon"], "Never."),
   ("Plants need the Sun to...", "grow well", ["fly", "sing", "walk"], "Grow.")],
  ["Only simple facts: the Sun is a star, but Class 1 text does not need that."], prereq=["class1-science-weather"])

ch = p.chapter("materials-safety", "Materials, safety and our environment", R)
lesson(ch, "materials", "Things around us are made of materials", ["Name some materials.", "Say what a thing is made of."],
  [("definition", "Materials", "Things are made of **materials**. A chair can be made of **wood**. A spoon can be made of **metal**. A bucket can be made of **plastic**. A shirt is made of **cloth**."),
   ("retenir", "Look and feel", "Wood is hard. Metal is hard and shiny. Plastic can be light. Cloth is soft. Glass is hard and clear, but it can break."),
   ("pieges", "Common mistakes", "- Do not touch broken glass.\n- Some things are made of more than one material.\n- Use the right material for a job: cloth for clothes, not stone.")],
  [("Example 1", "What is a wooden table made of?", ["Wood comes from trees.", "It is made of wood."], "Wood", cards(["wood: table", "metal: pot", "plastic: bucket", "cloth: shirt"], 2, 400, ch=44, size=16)),
   ("Example 2", "Which material is soft: cloth or stone?", ["Touch cloth. It is soft.", "Stone is hard."], "Cloth", None)],
  (cards(["wood", "metal", "plastic", "cloth", "glass", "paper"], 3, 400, ch=44, size=18), "Some materials.", "Six boxes with wood, metal, plastic, cloth, glass and paper."),
  [("m", "A shirt is made of...", "cloth", ["metal", "wood", "stone"], "Cloth."), ("m", "A cooking pot is often made of...", "metal", ["paper", "cloth", "wax"], "Metal."), ("m", "Which is soft?", "cloth", ["stone", "metal", "wood"], "Cloth.")],
  [("x", "Match the thing with its material.", [("chair", "wood"), ("bucket", "plastic"), ("knife", "metal")], "Think about the thing."), ("t", "Glass is soft and cannot break.", False, "Glass is hard and can break.")],
  ("p", "A school has 6 wooden desks and 4 metal chairs.", [("n", "How many things in all?", 10, "6 + 4 = 10."), ("n", "How many things are made of wood?", 6, "6 desks.")]),
  [("Class 1 science materials: a plastic bucket is made of...", "plastic", ["wood", "cloth", "glass"], "Plastic."),
   ("Class 1 science materials: which is hard and shiny?", "metal", ["cloth", "paper", "wool"], "Metal."),
   ("Clothes are made of...", "cloth", ["stone", "glass", "metal"], "Cloth."),
   ("Wood comes from...", "trees", ["stones", "clouds", "water"], "Trees."),
   ("Broken glass is...", "dangerous", ["safe", "soft", "good to play"], "Dangerous.")],
  [NOTE], prereq=["class1-science-day-night-sun"])

lesson(ch, "safety", "Staying safe", ["Name some dangers at home and on the road.", "Know what to do to stay safe."],
  [("definition", "Safety", "**Safety** means keeping away from danger. Some things are dangerous: fire, hot water, sharp knives, electric sockets, medicine and chemicals. Do not play with them."),
   ("retenir", "On the road", "Look **left and right** before you cross. Walk on the side of the road. Hold an adult's hand. Do not play on the road. If you are lost, tell a trusted adult such as a teacher."),
   ("pieges", "Common mistakes", "- Do not run across the road.\n- Never take medicine by yourself.\n- Tell an adult at once if you or a friend is hurt.")],
  [("Example 1", "What do you do before you cross the road?", ["Stop at the side of the road.", "Look left and right."], "Look left and right", cards(["stop", "look left", "look right", "cross with care"], 4, 400, ch=44, size=14)),
   ("Example 2", "You see a hot pot on the fire. What do you do?", ["Do not touch it.", "Keep away and tell an adult."], "Keep away", None)],
  (cards(["no fire play", "no sharp knives", "look left and right", "tell an adult"], 2, 400, ch=44, size=15), "Safety rules.", "Four boxes with safety rules."),
  [("m", "Before crossing the road we...", "look left and right", ["close our eyes", "run fast", "play"], "Look."), ("m", "Which is dangerous to play with?", "fire", ["a ball", "a book", "a hat"], "Fire."), ("t", "We should tell an adult if a friend is hurt.", True, "Yes.")],
  [("m", "You find some medicine on the floor. What do you do?", "tell an adult", ["taste it", "give it to a friend", "hide it"], "Tell an adult."), ("t", "We can play on the road.", False, "Never.")],
  ("p", "Ada walks to school in Bamenda with her brother.", [("m", "Where should they walk?", "on the side of the road", ["in the middle of the road", "behind a car", "under a truck"], "Side of the road."), ("m", "A car is coming. What do they do?", "wait", ["run across", "close their eyes", "play"], "Wait.")]),
  [("Class 1 science safety: before we cross a road we...", "look both ways", ["close our eyes", "run", "call a friend"], "Look."),
   ("Class 1 science safety: which is dangerous?", "a sharp knife", ["a ball", "a cup", "a book"], "Knife."),
   ("If a friend is hurt, we...", "tell an adult", ["laugh", "run away", "hide"], "Tell."),
   ("We should not play with...", "fire", ["a ball", "sand", "a kite"], "Fire."),
   ("When we are lost, we tell...", "a trusted adult", ["no one", "a stranger who offers sweets", "a dog"], "Trusted adult.")],
  ["Safety advice is general; check wording with the school and local road-safety guidance."], prereq=["class1-science-materials"])

lesson(ch, "environment", "Caring for our environment", ["Say why we keep our surroundings clean.", "Put rubbish in a bin."],
  [("definition", "Environment", "Our **environment** is everything around us: the soil, water, air, plants and animals. We must take care of it."),
   ("retenir", "What we can do", "Put rubbish in a **bin**. Do not throw rubbish in the river. Sweep the yard. Plant a tree. Do not waste water."),
   ("pieges", "Common mistakes", "- Rubbish on the ground can make us ill and hurt animals.\n- Do not burn plastic.\n- Wash your hands after you touch rubbish.")],
  [("Example 1", "Where do we put rubbish?", ["We want a clean place.", "In a bin."], "In a bin", cards(["use a bin", "sweep the yard", "plant a tree", "save water"], 2, 400, ch=44, size=16)),
   ("Example 2", "Name one thing you can do to help the environment.", ["Plant a tree.", "Trees give shade and clean air."], "Plant a tree", None)],
  (cards(["rubbish in the bin", "plant a tree", "sweep", "save water"], 2, 400, ch=44, size=16), "Caring for the environment.", "Four boxes with ways to care for the environment."),
  [("m", "Where should we put rubbish?", "in a bin", ["in the river", "on the road", "in a well"], "A bin."), ("m", "A way to help the environment is to...", "plant a tree", ["cut all trees", "break bottles", "spill oil"], "Plant."), ("t", "We should throw rubbish in the river.", False, "Never.")],
  [("t", "Sweeping the yard keeps it clean.", True, "Yes."), ("m", "Which helps our school stay clean?", "using the bin", ["dropping paper", "spitting", "breaking desks"], "Bin.")],
  ("p", "A class has 10 pupils in the cleaning club. 4 sweep, 3 plant flowers and the rest pick up paper.", [("n", "How many pick up paper? (10 − 4 − 3)", 3, "10 − 7 = 3."), ("n", "How many pupils sweep or plant? (4 + 3)", 7, "4 + 3 = 7.")]),
  [("Class 1 science environment: rubbish should go in...", "a bin", ["the river", "the road", "the well"], "Bin."),
   ("Class 1 science environment: to help nature we can...", "plant trees", ["cut all trees", "throw plastic", "waste water"], "Plant trees."),
   ("Our environment is...", "everything around us", ["only our house", "only the sky", "only a book"], "Around us."),
   ("We should not...", "throw rubbish in the river", ["sweep", "plant a tree", "save water"], "No."),
   ("Sweeping the yard helps to keep it...", "clean", ["dirty", "dark", "loud"], "Clean.")],
  [NOTE], prereq=["class1-science-safety"])

p.write()
