import sys
sys.path.insert(0, "/home/user/CastBridge/tools/learn-authoring/anglophone")
from fg_kit import *

p = mk_pack("form3-geography", "Geography — Form 3", "Form 3", "Geography", "geography",
    "Third-year Geography: coasts, population, towns and urban growth, farming systems and crops, industry and energy, and further map skills (bearings, six-figure references, area).",
    "Cameroon anglophone secondary Geography syllabus, Form 3 — to be checked against the official text", GEO_NOTE)

# ------------------------------------------------------------ CH1 coasts
c = p.chapter("coasts", "Coasts")
L = LS(c, "coastal-features", "Waves, coastal erosion and deposition",
    ["Describe how waves erode and deposit", "Explain the formation of cliffs, caves, arches and stacks", "Describe beaches, spits and mangrove coasts", "Name ways of protecting a coast"],
    [("text", "Waves are made by wind blowing over the sea. Where waves reach the coast they can **erode** (wear away) or **deposit** (lay down) material. **Destructive waves** are high and steep and pull material away from the beach; **constructive waves** are low and gentle and build up the beach. Waves erode by **hydraulic action** (the force of water in cracks), **abrasion** (rocks thrown against the cliff), **attrition** (pebbles wearing each other smaller) and **solution** (dissolving)."),
     ("key", "retenir", "From cliff to stack", "Waves attack a headland of hard rock along a crack and enlarge it into a **cave**. When two caves meet, an **arch** forms. When the roof falls, a column of rock stands apart: a **stack**. Later the stack wears down to a **stump**. At the foot of a cliff, the wearing back leaves a flat **wave-cut platform**."),
     ("key", "retenir", "Deposition", "Where waves lose energy, sand and shingle are deposited to form **beaches**. A **spit** is a long ridge of sand joined to the land at one end and sticking out into the sea. A **sand bar** closes a bay. In muddy tropical estuaries, **mangrove** trees with stilt roots trap mud and protect the shore; the Cameroon coast near Douala, Limbe and Kribi has beaches, cliffs, estuaries and mangroves."),
     ("text", "**Coastal protection** is needed where the sea eats away land or threatens towns. Methods: **sea walls** that reflect waves, **groynes** (low walls across the beach to hold sand), **rock armour** (big boulders at the cliff foot), **beach feeding** with new sand, and planting **mangroves**. People also build away from the edge and avoid removing mangroves for firewood."),
     ("key", "pieges", "Common mistakes", "- Erosion wears material away; deposition lays it down. Do not use them as if they were the same.\n- A stack stands in the sea, away from the headland; an arch is still joined to land on both sides.\n- Groynes run across the beach; sea walls run along the shore.")],
    [("Example 1: order of features", "Put these in order of formation: stack, cave, arch, crack.", ["The sea first widens a crack in the cliff.", "The crack becomes a cave; two caves meet to form an arch.", "When the arch roof collapses, a stack remains."], "Crack, cave, arch, stack."),
     ("Example 2: protecting a beach", "A beach is losing sand because the waves carry it along the shore. Suggest one method of protection and explain it.", ["Sand moves along the coast in the direction of the waves.", "Groynes built across the beach stop the sand moving.", "So groynes hold sand and protect the beach."], "Groynes, which trap moving sand.")],
    F(flow("Features of erosion", ["Crack|in cliff", "Cave", "Arch", "Stack and|stump"], per_row=4), "From a crack to a stack", "Four boxes showing the stages from a crack to a cave, an arch and a stack."),
    [MCQ("In Form 3 geography, rocks hurled by waves against a cliff cause erosion by", "abrasion", ["attrition", "deposition", "weathering only"], "Abrasion is the grinding by rock fragments."),
     TF("A spit is a ridge of sand joined to the land at one end.", True, "It extends out into the sea or across a bay."),
     MATCH("Match each coastal feature with its description.", [("Stack", "Column of rock standing in the sea"), ("Arch", "Opening through a headland"), ("Groyne", "Wall across a beach to trap sand")], "Erosion features and a defence."),
     MCQ("Why are mangroves valuable on a tropical coast?", "Their roots trap mud and protect the shore", ["They make waves bigger", "They produce salt only", "They remove all fish"], "They hold the soil and shelter young fish.", tier="approfondissement"),
     OPEN("Describe how an arch forms on a headland.", "Waves attack a crack in the hard rock of a headland using hydraulic action and abrasion, widening it into a cave. Caves from both sides meet to form an opening, the arch.", "1 mark: waves attack cracks; 1 mark: cave; 1 mark: joined to form arch.", points=3, tier="approfondissement"),
     PROB("A coastal town in the Gulf of Guinea loses beach sand every year.",
          [("mcq", "Waves that build up a beach are", "constructive", ["destructive", "tsunami", "tidal"], "Low gentle waves deposit material.", {}),
           ("tf", "Groynes can reduce the loss of sand.", True, "They trap sand moving along the shore.", {}),
           ("mcq", "Which action would harm the coast?", "cutting mangroves for building poles", ["planting mangroves", "building a sea wall", "feeding the beach with sand"], "Mangrove loss exposes the coast.", {}),
           ("open", "Give two other ways of protecting a coast.", "Sea walls, rock armour, beach feeding, planting mangroves, controlled building.", "1 mark per way.", {})])],
    [("Wearing away of the coast by the sea is", "erosion", ["deposition", "evaporation", "irrigation"], "Erosion removes material."),
     ("Destructive waves are", "high and steep", ["low and gentle", "non-existent", "always on lakes"], "They remove material from the beach."),
     ("A wave-cut platform is found", "at the foot of a cliff", ["on a mountain peak", "in a desert", "inside a volcano"], "Waves cut it as the cliff retreats."),
     ("A long ridge of sand sticking out into the sea is a", "spit", ["stack", "cave", "arch"], "Spits form by deposition."),
     ("Mangrove trees grow best in", "muddy tropical estuaries", ["dry deserts", "cold mountains", "polar ice"], "They have stilt roots in salt water.")],
    ["Teacher to verify the sequence and terms (hydraulic action, abrasion, attrition, solution) against the syllabus and the use of Cameroonian coastal examples."], tag="Form 3 coasts")

# ------------------------------------------------------------ CH2 population
c = p.chapter("population", "Population")
L = LS(c, "population-density", "Population distribution, density and growth",
    ["Define population density and calculate it", "Explain the factors affecting population distribution", "Calculate natural increase from birth and death rates", "Explain causes and effects of migration"],
    [("text", "**Population distribution** shows how people are spread over an area. Some places are crowded and others almost empty. **Population density** is the average number of people living in one square kilometre: density = **population ÷ area (km²)**. Density is only an average: a region may have a crowded town and empty countryside."),
     ("key", "retenir", "Factors of distribution", "People crowd where there is: **fertile soil and enough rain** for farming, **gentle relief**, **water supply**, **jobs** (ports, industries, plantations, administration), good **transport**, and **safety**. Few people live in thick forest, steep mountains, deserts or swamps. In Cameroon the cities of Douala and Yaoundé, the Western Highlands and parts of the north are densely settled; large areas of the forest in the south-east have few people."),
     ("key", "formule", "Birth rate, death rate and natural increase", "**Birth rate** = births per 1000 people per year; **death rate** = deaths per 1000 per year. **Natural increase** = birth rate − death rate (per 1000). To change it to a percentage, divide by 10. Example: birth rate 38, death rate 12: natural increase = 26 per 1000 = 2.6 % a year."),
     ("text", "**Migration** is the movement of people from one place to another to live. **Rural–urban migration** means moving from villages to towns. **Push factors** make people leave (poor land, few jobs and services); **pull factors** attract them (jobs, schools, hospitals, a better life). Effects: towns grow fast and become crowded, villages lose young workers, and money is sent home by migrants."),
     ("key", "attention", "Be careful", "- Density uses area, not the number of towns; always check the unit: people per km².\n- A high birth rate does not by itself give a fast rise: look at the death rate too.\n- Do not call all migration bad: it can bring skills and income as well as problems.")],
    [("Example 1: density", "A division has 240 000 people and an area of 800 km². Find its population density.", ["Density = population ÷ area.", "240 000 ÷ 800 = 300.", "Unit: people per km²."], "300 people per km²."),
     ("Example 2: natural increase", "A country has a birth rate of 35 per 1000 and a death rate of 9 per 1000. Find the natural increase as a percentage.", ["Natural increase = 35 − 9 = 26 per 1000.", "26 ÷ 10 = 2.6 per cent.", "The population is growing by 2.6 % a year from natural causes."], "2.6 % a year.")],
    F(bars([("Zone A", 30, "green"), ("Zone B", 60, "orange"), ("Zone C", 90, "red")], unit="people/km² (invented figures)", h=260), "Illustrative population densities", "Bar chart showing three zones with densities of 30, 60 and 90 people per square kilometre; invented figures."),
    [MCQ("Population density is measured in", "people per km²", ["km per person", "persons per tonne", "degrees"], "Density = population ÷ area."),
     TF("Rural–urban migration means moving from villages to towns.", True, "That is the definition."),
     NUM("A town has 150 000 people living in an area of 50 km². What is its density in people per km²?", 3000, "150 000 ÷ 50 = 3000.", unit="people per km²"),
     NUM("Birth rate 32 per 1000 and death rate 14 per 1000. What is the natural increase per cent per year?", 1.8, "32 − 14 = 18 per 1000 = 1.8 %.", tol=0.01, unit="%", tier="approfondissement"),
     OPEN("Explain three push or pull factors that lead young people from villages to the cities.", "Push: shortage of jobs and poor services in the village, tired farmland. Pull: jobs and business in the city, schools, hospitals and electricity, hope of a better income.", "1 mark per well-explained factor.", points=3, tier="approfondissement"),
     PROB("Division X has 450 000 people in 900 km². Division Y has 120 000 people in 1200 km².",
          [("num", "Find the density of X (people per km²).", 500, "450 000 ÷ 900 = 500.", 0, "people/km²", {}),
           ("num", "Find the density of Y (people per km²).", 100, "120 000 ÷ 1200 = 100.", 0, "people/km²", {}),
           ("mcq", "Which division is more densely populated?", "X", ["Y", "They are equal", "Cannot be known"], "500 is greater than 100.", {}),
           ("open", "Suggest two reasons why X might be more crowded than Y.", "It may have a big town or port, fertile land, plantations or industries, good roads and services, while Y may be forest, mountain or swamp.", "1 mark per reason.", {})])],
    [("Birth rate is the number of births", "per 1000 people per year", ["in total", "per km²", "per household"], "It is a rate per 1000."),
     ("The formula for population density is", "population ÷ area", ["area ÷ population", "population × area", "births − deaths"], "People per square kilometre."),
     ("A pull factor for a town is", "job opportunities", ["drought", "lack of schools", "poor roads"], "Jobs attract migrants."),
     ("Natural increase equals", "birth rate − death rate", ["birth rate + death rate", "death rate − birth rate", "density × area"], "It is the difference between births and deaths."),
     ("Which area usually has the lowest density?", "thick forest or desert", ["a port city", "a market town", "a fertile plain with jobs"], "Hard environments attract fewer people.")],
    ["Teacher to verify that the syllabus uses the same definitions; no real population statistics are given on purpose (use the latest census figures when the teacher adds them)."], tag="Form 3 population")

# ------------------------------------------------------------ CH3 urban
c = p.chapter("urban", "Towns and urban growth")
zones = shapes([CIRCLE(190, 110, 95, fill="lightgreen"), CIRCLE(190, 110, 68, fill="lightyellow"), CIRCLE(190, 110, 38, fill="lightorange"), T(190, 115, "CBD", size=12, bold=True),
                T(190, 86, "Inner zone", size=11), T(190, 52, "Suburbs", size=11), T(190, 20, "Rural-urban fringe", size=11), T(340, 70, "Offices, shops,", size=11, anchor="start"), T(340, 86, "banks, market", size=11, anchor="start")], 440, 220)
L = LS(c, "urban-growth", "Land use and problems of towns",
    ["Describe the land-use zones of a town", "Explain why towns grow", "Describe urban problems and possible solutions", "Compare urban and rural life"],
    [("text", "A town is not made of one kind of land use. The **Central Business District (CBD)** is the busy centre with offices, banks, shops and markets, where land is very expensive and buildings are tall. Around it are older **inner zone** houses, often crowded, then **suburbs** with newer homes and more space, and at the edge the **rural–urban fringe** where farms meet houses. **Industries** are often located along main roads, railways or ports."),
     ("key", "retenir", "Why towns grow", "Towns grow through **natural increase** and, above all, through **migration** from villages. They also grow when the town offers work in administration, ports, trade and industry, or when a main road or railway brings new activity. Douala (port and industry) and Yaoundé (capital) have grown very fast; Bamenda, Bafoussam and Garoua also attract many people."),
     ("key", "retenir", "Urban problems", "- **Housing shortage** and unplanned neighbourhoods.\n- **Traffic jams** and accidents.\n- Pressure on **water, electricity and sanitation**; floods where drains are blocked.\n- **Unemployment** and street trading in crowded spaces.\n- **Pollution** and waste."),
     ("text", "**Solutions** include town planning (marking land for homes, roads and parks), building affordable housing, widening and repairing roads and drains, improving public transport, waste collection and recycling, creating jobs and services in rural areas to slow migration, and involving the community through councils. **Urban life** offers jobs, schools and hospitals but brings noise, crowding and a high cost of living; **rural life** is quieter but has fewer services."),
     ("key", "attention", "Be careful", "- The CBD is not the same as the whole town: it is only the central business area.\n- Land use depends on cost, accessibility and history, not on one rule.\n- Avoid one-sided answers: always say both advantages and disadvantages of urban life.")],
    [("Example 1: land use", "Why are tall office buildings found in the CBD and not on the edge of town?", ["Land in the centre is very expensive and the most accessible.", "Building upwards uses limited space well.", "So firms pay for the centre and build tall."], "Because land is costly and accessible in the centre, so buildings go up."),
     ("Example 2: solution", "Floods occur in a neighbourhood after every heavy storm because drains are blocked. Suggest two solutions.", ["Clean and repair the drains regularly.", "Stop dumping waste in channels and build new drains with the council.", "These steps let water flow away."], "Clear and repair drains; stop dumping waste (community action).")],
    F(zones, "Zones of a town", "Concentric rings from the CBD at the centre to suburbs and the rural-urban fringe."),
    [MCQ("The centre of a town with shops, banks and offices is the", "CBD", ["suburb", "fringe", "dormitory village"], "CBD means Central Business District."),
     TF("Housing shortage is a problem of fast-growing towns.", True, "Many people arrive quickly."),
     MATCH("Match each urban problem with a possible solution.", [("Traffic jams", "Better public transport and roads"), ("Blocked drains", "Regular cleaning and new drains"), ("Uncontrolled housing", "Town planning")], "Solutions should fit the problem."),
     MCQ("Rural–urban migration slows when", "villages get jobs, schools and clinics", ["towns have more problems", "roads close", "rain stops"], "Improving rural life reduces push factors.", tier="approfondissement"),
     OPEN("Discuss two advantages and two disadvantages of living in a large town in Cameroon.", "Advantages: jobs and markets, schools and hospitals. Disadvantages: crowding and traffic, high cost of living, pollution and floods in poor drains.", "1 mark per correct point, up to 4.", points=4, tier="approfondissement"),
     PROB("A town planner studies a fast-growing town near Bafoussam.",
          [("mcq", "Land with the highest price is usually in the", "CBD", ["fringe", "farmland", "forest"], "The centre is most accessible.", {}),
           ("tf", "Unplanned houses may block roads and drains.", True, "Planning prevents this.", {}),
           ("mcq", "Which action would reduce traffic jams?", "better public transport", ["more private cars", "closing bus stations", "parking on roads"], "Public transport carries many people.", {}),
           ("open", "Give two ways the council can reduce pollution from waste.", "Organise regular waste collection, provide bins and dumps, encourage recycling and composting, and fine illegal dumping.", "1 mark per way.", {})])],
    [("The rural–urban fringe is the", "edge of town where houses meet farms", ["centre of town", "harbour", "industrial park only"], "It lies between town and countryside."),
     ("One reason towns grow is", "migration from villages", ["fewer jobs", "closed schools", "less transport"], "People move to towns."),
     ("Town planning means", "deciding how land is used", ["destroying houses", "stopping all building", "printing maps"], "Planners organise homes, roads and parks."),
     ("A common problem of fast urban growth is", "pressure on water and electricity", ["too many farms", "too few people", "no traffic"], "Services cannot keep pace."),
     ("Douala is a major town mainly because of its", "port and industries", ["mountains", "desert", "ice"], "It handles most of the country's trade.")],
    ["Teacher to verify the land-use zone model taught (concentric zones) and its fit with Cameroonian towns; the town examples are general."], tag="Form 3 towns")

# ------------------------------------------------------------ CH4 farming
c = p.chapter("farming", "Farming")
L = LS(c, "farming-systems", "Farming systems and crops of Cameroon",
    ["Distinguish subsistence and commercial farming", "Describe shifting cultivation, plantation farming and livestock rearing", "Name the main food and cash crops and where they grow", "Describe problems of farmers and possible solutions"],
    [("text", "**Subsistence farming** grows food mainly for the farmer's own family, usually on small plots with simple tools such as the hoe and machete. **Commercial farming** grows crops or raises animals mainly **to sell**, often on large farms with machines, fertilisers and paid workers. In **shifting cultivation** (bush fallowing) farmers clear a plot, cultivate it for a few years, then leave it to rest and clear a new one so the soil can recover."),
     ("key", "retenir", "Plantation farming", "A **plantation** is a large farm growing one cash crop on a large scale, with many workers and processing on the spot. In Cameroon plantations produce **bananas**, **rubber**, **oil palm** and **tea** in the South-West, Littoral and the slopes of Mount Cameroon. Smallholders also grow **cocoa** (Centre, South, South-West), **coffee** (West and North-West highlands, and the forest zone) and **cotton** (North)."),
     ("key", "retenir", "Food crops and livestock", "Common food crops: **cassava, plantain, cocoyam, yams, maize, groundnuts, beans** in the south and highlands; **millet, sorghum, maize and rice** in the north. **Cattle, goats and sheep** are reared on the grasslands of the Adamawa, the North-West and the north; poultry and pigs are kept in many areas."),
     ("text", "**Problems of farmers:** poor roads that make transport difficult and expensive, pests and diseases, falling prices of cash crops, lack of money and fertilisers, **bush fires**, soil exhaustion and climate change (late or irregular rain), and difficulty in storing and selling produce. **Solutions:** better rural roads, advice and training, **cooperatives** to sell together, improved seeds, fertiliser and irrigation, storage and processing, and fair prices."),
     ("key", "pieges", "Common mistakes", "- A cash crop is grown mainly for sale; a food crop is mainly for eating. A crop can be both (maize).\n- Shifting cultivation is not the same as a nomad's life: farmers stay in the village and rotate plots.\n- Do not place all crops everywhere: climate and soil decide where each grows well.")],
    [("Example 1: type of farming", "A family clears a plot in the forest, grows cassava and plantain for six years and then moves to a new plot. What is this system?", ["The family grows food for itself.", "It leaves the old plot to rest.", "This is shifting cultivation, a subsistence system."], "Shifting cultivation (subsistence)."),
     ("Example 2: crop and region", "Which crop would you expect to see in large plantations on the slopes of Mount Cameroon, and why?", ["The volcanic soil is fertile and rainfall is high.", "Warm, wet conditions suit bananas, oil palm, rubber and tea.", "For example, bananas."], "Bananas (or rubber, oil palm, tea), because the volcanic soil and wet climate suit them.")],
    F(cols("Where crops grow", [("South / coast", ["Cocoa", "Oil palm", "Banana", "Rubber"]), ("Highlands", ["Coffee", "Tea", "Maize", "Beans"]), ("North", ["Cotton", "Millet", "Sorghum", "Rice"])], w=440), "Crops by zone", "Three columns listing typical crops of the south and coast, the highlands and the north."),
    [MCQ("In Form 3 geography, farming mainly to sell the produce is", "commercial farming", ["subsistence farming", "nomadism", "fallowing"], "Commercial farming aims at profit."),
     TF("Cotton is mainly grown in the north of Cameroon.", True, "The drier north suits cotton."),
     MATCH("Match each crop to a typical Cameroonian area.", [("Cotton", "North"), ("Cocoa", "Centre and South"), ("Coffee", "Highlands of the West")], "Crops follow climate and soil."),
     MCQ("Which is a solution to soil exhaustion in farming?", "crop rotation and manure", ["burning all farmland", "never fallowing", "planting only one crop forever"], "These practices restore fertility.", tier="approfondissement"),
     OPEN("Describe three problems faced by farmers in Cameroon and suggest a solution for each.", "Poor roads: repair feeder roads. Low cash-crop prices: join cooperatives and process crops. Pests and soil exhaustion: advice, improved seeds, fertiliser and manure.", "1 mark per problem with a matching solution.", points=3, tier="approfondissement"),
     PROB("Mr Fon grows cocoa on a small farm near Kumba and sells it to a buyer in town.",
          [("mcq", "Cocoa is mostly a", "cash crop", ["food crop only", "pasture", "weed"], "It is grown for sale.", {}),
           ("tf", "Cooperatives help farmers to sell their crops together.", True, "They can bargain for better prices.", {}),
           ("mcq", "Which factor would improve his income?", "better feeder roads to the buyer", ["more bush fires", "less rain always", "no advice"], "Roads lower transport cost.", {}),
           ("open", "Give two ways to protect the forest soil on a cocoa farm.", "Keep shade trees, use mulch and manure, avoid burning, plant on contour on slopes.", "1 mark per way.", {})])],
    [("A plantation is a", "large farm growing one cash crop", ["small family garden", "fishing camp", "market"], "Plantations are large, specialised farms."),
     ("Which of these is a food crop?", "cassava", ["rubber", "cotton", "tea"], "Cassava is a staple food."),
     ("Cattle rearing is common in the", "Adamawa and North-West grasslands", ["mangrove swamps", "city centres", "rainforest floors"], "Grasslands feed cattle."),
     ("Shifting cultivation lets the soil", "recover during fallow", ["become barren", "turn into rock", "become sea"], "The plot is rested."),
     ("A cooperative helps farmers to", "sell and buy together", ["fight each other", "stop farming", "destroy crops"], "Group action reduces costs.")],
    ["Teacher to verify crop-zone statements (cocoa, coffee, cotton, banana, tea, rubber, oil palm) and the livestock areas, with the most recent agricultural data if the teacher adds production figures."], tag="Form 3 farming")

# ------------------------------------------------------------ CH5 industry
c = p.chapter("industry", "Industry and energy")
L = LS(c, "industry-energy", "Industries, power and where factories are located",
    ["Classify economic activities as primary, secondary and tertiary", "Explain the factors for locating industries", "Describe industries of Cameroon", "Describe sources of energy and hydroelectric power"],
    [("text", "Economic activities are grouped in three levels. **Primary** activities take raw materials from nature (farming, fishing, logging, mining). **Secondary** activities turn them into finished goods (manufacturing, food processing, construction). **Tertiary** activities provide services (trade, transport, banking, teaching, health). **Industry** is mainly the secondary sector, where raw materials gain value."),
     ("key", "retenir", "Factors of industrial location", "A factory is placed where costs are low and sales are high: near **raw materials**, **power** (electricity, fuel), **water**, a **market** of buyers, **labour**, **transport** (roads, railway, port), **capital** and a **government** policy that allows it. Industries using heavy raw materials locate near them; others locate close to markets."),
     ("key", "retenir", "Industries and power in Cameroon", "Examples: food and drink processing (sugar, beer, flour, palm oil, cocoa), **timber** and wood products, **cement**, **aluminium** smelting at Edéa, **oil refining** at Limbe, textiles and cotton ginning in the north. Electricity comes mostly from **hydroelectric power** on the Sanaga (Edéa, Song-Loulou) and the Benue (Lagdo), and also from thermal (oil or gas) plants and growing solar projects."),
     ("text", "**Hydroelectric power (HEP)** uses falling water: a dam stores water in a reservoir, the water runs through pipes to turn **turbines**, and the turbines drive **generators** that produce electricity. HEP needs a river with a good flow and a drop, and is clean and cheap to run but costly to build; dams may flood land and need resettlement. Other energy: **fuelwood**, **petroleum**, **gas**, **solar** and **wind**."),
     ("key", "attention", "Be careful", "- Primary activities give raw materials; they do not make finished goods.\n- Cheap power alone does not decide location: you also need market, labour and transport.\n- Renewable energy (water, sun, wind) is not used up; fuelwood is renewable only if trees are replanted.")],
    [("Example 1: classify", "Classify these as primary, secondary or tertiary: cocoa farming, chocolate making, selling chocolate.", ["Growing cocoa takes from nature: primary.", "Making chocolate processes it: secondary.", "Selling is a service: tertiary."], "Primary, secondary, tertiary."),
     ("Example 2: location", "Why might a cement factory be built close to limestone deposits?", ["Limestone is heavy and bulky to carry.", "Carrying it far would raise costs.", "So a site near the raw material saves transport costs."], "To reduce the transport cost of heavy raw materials.")],
    F(flow("Hydroelectric power", ["Dam and|reservoir", "Water through|pipes", "Turbine|turns", "Generator|makes power"], per_row=4), "From water to electricity", "Four boxes showing the steps of hydroelectric power."),
    [MCQ("Teaching in a school is a", "tertiary activity", ["primary activity", "secondary activity", "mining activity"], "Services belong to the tertiary sector."),
     TF("Aluminium smelting in Cameroon is mainly done at Edéa.", True, "Edéa is the site of the aluminium smelter."),
     MATCH("Match each activity with its sector.", [("Logging", "Primary"), ("Making furniture", "Secondary"), ("Banking", "Tertiary")], "Sectors by type of work."),
     MCQ("Hydroelectric power needs", "a river with a good flow and a drop", ["a desert", "a flat dry plain", "no water"], "Falling water turns turbines.", tier="approfondissement"),
     OPEN("Explain three factors which a company would consider before building a factory.", "Nearness to raw materials to cut transport costs, power and water supply, a market for the products, labour and good roads or port links.", "1 mark per factor with a reason.", points=3, tier="approfondissement"),
     PROB("A company plans a factory to process cassava into flour near a market town.",
          [("mcq", "Cassava growing is", "a primary activity", ["a secondary activity", "a tertiary activity", "a service"], "It takes from nature.", {}),
           ("mcq", "Making flour is", "a secondary activity", ["a primary activity", "a tertiary activity", "farming"], "It processes cassava.", {}),
           ("tf", "A nearby market reduces transport costs for finished flour.", True, "Short distances cut costs.", {}),
           ("open", "Give two advantages of HEP over burning fuelwood.", "It is renewable and clean, does not cut trees and gives steady power for homes and industry.", "1 mark per advantage.", {})])],
    [("Farming and fishing are", "primary activities", ["secondary activities", "tertiary activities", "service activities"], "They use natural resources directly."),
     ("An example of a secondary activity is", "processing palm oil", ["picking palm fruit", "selling bottles", "banking"], "It changes raw materials into goods."),
     ("Which energy source is renewable?", "falling water", ["coal", "petrol", "gas"], "Water keeps flowing."),
     ("A dam stores water in a", "reservoir", ["generator", "turbine", "pipe"], "The reservoir holds the water."),
     ("A factor of industrial location is", "a market for the product", ["no workers", "no transport", "no roads"], "Industries need buyers.")],
    ["Teacher to verify industrial examples (aluminium at Edéa, refinery at Limbe, cement, sugar, textiles) and hydroelectric sites (Edéa, Song-Loulou on the Sanaga, Lagdo on the Benue); their current status should be checked."], tag="Form 3 industry")

# ------------------------------------------------------------ CH6 map skills
c = p.chapter("map-skills", "Map skills")
brg = shapes([LINE(150, 100, 150, 25, arrow="end", width=3), T(150, 18, "N 000°", size=12), LINE(150, 100, 225, 100, arrow="end", color="grey"), T(262, 104, "E 090°", size=12),
              LINE(150, 100, 150, 175, color="grey", arrow="end"), T(150, 192, "S 180°", size=12), LINE(150, 100, 75, 100, color="grey", arrow="end"), T(40, 104, "W 270°", size=12),
              LINE(150, 100, 203, 47, color="red", width=3, arrow="end"), T(220, 38, "A: 045°", size=12, color="red")], 320, 205)
L = LS(c, "bearings-grid", "Bearings, six-figure references and area",
    ["Give and use compass bearings", "Give a six-figure grid reference", "Estimate distance and area from a map", "Describe a place from map evidence"],
    [("text", "A **bearing** gives direction as an angle measured **clockwise from North**, with three figures: north is 000°, east 090°, south 180°, west 270°, and north-east 045°. To find the bearing from A to B, place the protractor at A, join to B and measure the angle clockwise from the north line. The **back bearing** (from B to A) is the bearing plus or minus 180°."),
     ("key", "methode", "Six-figure reference", "A grid square is divided into **tenths** in each direction. Give the **easting** first: the two-figure line number then the tenths, and then the **northing**. For a point 5 tenths along from line 34 and 2 tenths up from line 27 the reference is **345 272**. Always: eastings (along) first, northings (up) second."),
     ("key", "methode", "Distance and area", "- **Straight distance**: measure with a ruler and apply the scale.\n- **Winding distance**: lay a thread or the edge of paper along the road, mark, then measure it against the scale.\n- **Area**: count whole grid squares and combine part squares; if each square is 1 km × 1 km (1 km²), twelve squares make 12 km²."),
     ("text", "**Describing a place.** When asked to describe relief, drainage or settlement from a map, give evidence: quote contour heights, say where the land is steep or flat, name rivers and the direction they flow, describe roads, railways and settlement patterns, and mention land use symbols. Use grid references to point to places and compass directions to describe where things are."),
     ("key", "pieges", "Common mistakes", "- Bearings are clockwise from north, never from east.\n- The back bearing must stay between 000° and 360°: for 270° the back bearing is 090°.\n- Do not give a six-figure reference with northing first.")],
    [("Example 1: back bearing", "The bearing of a hill from a school is 060°. What is the bearing of the school from the hill?", ["The back bearing differs by 180°.", "060° + 180° = 240°.", "240° is between 0° and 360°, so it is acceptable."], "240°."),
     ("Example 2: area", "On a 1 km grid, a lake covers 7 whole squares and 6 half squares. Estimate its area.", ["Half squares count as 3 whole squares (6 ÷ 2).", "Total = 7 + 3 = 10 squares.", "Each square is 1 km², so the area is 10 km²."], "About 10 km².")],
    F(brg, "Bearings from North", "A compass with bearings for north, east, south and west and a red arrow at 045 degrees."),
    [MCQ("The bearing of due east is", "090°", ["000°", "180°", "270°"], "East is a quarter turn from north."),
     TF("Bearings are measured clockwise from north.", True, "That is the convention."),
     NUM("The bearing of B from A is 110°. What is the bearing of A from B?", 290, "110° + 180° = 290°.", unit="°"),
     NUM("A lake covers 9 whole squares and 8 half squares on a 1 km grid. What is its estimated area in km²?", 13, "8 half squares = 4 squares; 9 + 4 = 13.", unit="km²", tier="approfondissement"),
     OPEN("Describe the steps for giving a six-figure grid reference.", "Read the easting line number to the left of the point and estimate tenths along; then read the northing line below the point and estimate tenths up; write the eastings first and the northings second to form six figures.", "1 mark: easting first; 1 mark: tenths; 1 mark: northing.", points=3, tier="approfondissement"),
     PROB("On a map of scale 1 : 50 000 (1 cm = 0.5 km), a school is at A and a market at B, 7 cm apart. The bearing of B from A is 135°.",
          [("num", "What is the ground distance from A to B in km?", 3.5, "7 × 0.5 = 3.5 km.", 0.01, "km", {}),
           ("num", "What is the bearing of A from B?", 315, "135° + 180° = 315°.", 0, "°", {}),
           ("mcq", "The direction of B from A (135°) is closest to", "south-east", ["north-west", "north-east", "south-west"], "135° lies between east (090°) and south (180°).", {}),
           ("tf", "A winding road can be measured with a thread.", True, "Mark the thread along the road, then straighten it.", {})])],
    [("The bearing of south-west is", "225°", ["045°", "135°", "315°"], "Between south 180° and west 270°."),
     ("In a six-figure grid reference the first three figures give the", "easting", ["northing", "scale", "height"], "Eastings come first."),
     ("To measure a winding road on a map you use", "a piece of thread", ["a compass rose", "a barometer", "a protractor only"], "Thread follows the curves."),
     ("The back bearing of 200° is", "020°", ["100°", "380°", "290°"], "200° − 180° = 020°."),
     ("If one grid square is 1 km² then 15 squares cover", "15 km²", ["1.5 km²", "150 km²", "5 km²"], "Add whole squares.")],
    ["Teacher to verify whether Form 3 uses six-figure references and protractor bearings in the syllabus and the conventions of the local topographic maps."], tag="Form 3 map skills")

p.write()
