import sys
sys.path.insert(0, "/home/user/CastBridge/tools/learn-authoring/anglophone")
from fg_kit import *

p = mk_pack("form1-geography", "Geography — Form 1", "Form 1", "Geography", "geography",
    "First-year Geography: the Earth in space, map reading (direction, scale, symbols, grid references), weather elements, rocks and soils, the location and relief of Cameroon, and people and settlements.",
    "Cameroon anglophone secondary Geography syllabus, Form 1 — to be checked against the official text", GEO_NOTE)

# ---------------------------------------------------------------- CH1 Earth
c = p.chapter("earth", "The Earth in space")
L = LS(c, "rotation-revolution", "Rotation, revolution and the seasons",
    ["Describe the shape of the Earth and name the main imaginary lines", "Explain day and night as an effect of rotation", "Explain the year and the seasons as effects of revolution and the tilt of the axis"],
    [("text", "The Earth is almost a **sphere**, slightly flattened at the poles. It turns on an imaginary line called its **axis**, which joins the North Pole and the South Pole. The **Equator** is the imaginary line halfway between the poles. It divides the Earth into the Northern and Southern **Hemispheres**. The **Tropic of Cancer** (about 23½° N) and the **Tropic of Capricorn** (about 23½° S) mark the limits of the tropics."),
     ("key", "definition", "Rotation", "**Rotation** is the spinning of the Earth on its axis. One rotation takes about **24 hours**, which is one day. The Earth turns from west to east, so the Sun seems to rise in the east and set in the west. At any time half of the Earth faces the Sun (day) and half faces away (night)."),
     ("key", "definition", "Revolution", "**Revolution** is the movement of the Earth around the Sun. One revolution takes about **365¼ days**, which is one year. We add one extra day to February every four years to make a **leap year** of 366 days. The Earth's axis is **tilted** (about 23½°) and always points the same way in space."),
     ("text", "Because of the tilt, the two hemispheres receive different amounts of sunlight during the year. This causes the **seasons** in places far from the Equator: when the Northern Hemisphere leans towards the Sun it has summer, while the Southern Hemisphere has winter. Near the Equator, as in most of Cameroon, the length of day changes very little, and the main seasons are the **rainy season** and the **dry season**."),
     ("key", "pieges", "Common mistakes", "- Rotation gives day and night; revolution gives the year. Do not swap them.\n- The seasons are caused by the **tilt** of the axis, not by the Earth being closer to the Sun.\n- The Sun does not move round the Earth: it only seems to, because the Earth rotates.")],
    [("Example 1: night in Yaoundé", "It is noon in Yaoundé. Is it day or night on the opposite side of the Earth, and why?", ["Half of the Earth faces the Sun at any time.", "The opposite side faces away from the Sun.", "So it is night there, because of rotation."], "It is night, because that side is turned away from the Sun."),
     ("Example 2: leap years", "How many days are there in four ordinary years plus one extra leap day, if each ordinary year has 365 days?", ["Four ordinary years: 4 × 365 = 1460 days.", "Add the extra leap day: 1460 + 1 = 1461.", "This is why the real year is about 365¼ days."], "1461 days.")],
    F(flow("Earth movements", ["Rotation|24 hours", "Day and|night", "Revolution|365¼ days", "Year and|seasons"], per_row=4), "Rotation and revolution and what they cause", "Four boxes joined by arrows linking rotation to day and night and revolution to the year and seasons."),
    [MCQ("In Form 1 geography, the spinning of the Earth on its axis is called", "rotation", ["revolution", "erosion", "migration"], "Rotation is the spin on the axis; revolution is the path around the Sun."),
     TF("Day and night happen because the Earth rotates (Form 1 geography).", True, "Rotation turns each place into and out of sunlight."),
     NUM("The Earth takes about 24 hours for one rotation. How many rotations does it make in one week of 7 days?", 7, "One rotation per day gives 7 rotations in 7 days.", unit="rotations"),
     MCQ("The seasons of the temperate lands are caused mainly by", "the tilt of the Earth's axis during its revolution", ["the Moon's pull", "the Earth being nearer to the Sun in summer", "the speed of rotation"], "The tilt changes the amount of sunlight each hemisphere gets.", tier="approfondissement"),
     OPEN("Explain, in your own words, why Cameroon's main seasons are 'rainy' and 'dry' rather than summer and winter.", "Cameroon is near the Equator, where day length and sunshine change little through the year, so temperature stays fairly high. The big change is in rainfall, so people speak of a rainy season and a dry season.", "1 mark: near the Equator; 1 mark: little change in temperature/day length; 1 mark: change in rainfall gives rainy/dry seasons.", points=3, tier="approfondissement"),
     PROB("Ebot studies the Earth's movements for his Form 1 geography class.",
          [("mcq", "Which movement takes about one year?", "Revolution round the Sun", ["Rotation on the axis", "Movement of the Moon", "Wind circulation"], "Revolution takes about 365¼ days.", {}),
           ("num", "How many days are in a leap year?", 366, "A leap year has one extra day in February.", 0, "days", {}),
           ("tf", "The Earth's axis is tilted by about 23½°.", True, "This tilt explains the seasons.", {}),
           ("open", "State one effect of rotation and one effect of revolution.", "Rotation causes day and night; revolution causes the year (and, with the tilt, the seasons).", "1 mark for each effect.", {})])],
    [("The imaginary line halfway between the North and South Poles is the", "Equator", ["Axis", "Tropic of Cancer", "Meridian of the pole"], "The Equator divides the Earth into two hemispheres."),
     ("One rotation of the Earth takes about", "24 hours", ["12 hours", "7 days", "365 days"], "A day is one rotation."),
     ("A leap year has", "366 days", ["365 days", "364 days", "360 days"], "An extra day is added to February."),
     ("The shape of the Earth is best described as", "a nearly round sphere flattened a little at the poles", ["a flat disc", "a perfect cube", "a long cylinder"], "The Earth is an oblate sphere."),
     ("The Earth turns on its axis from", "west to east", ["east to west", "north to south", "south to north"], "That is why the Sun seems to rise in the east.")],
    ["Teacher to verify the tropics' latitudes (about 23½°) and the wording of the syllabus on seasons; the lesson does not treat equinoxes and solstices."], tag="Form 1 geography, Earth movements")

c = p.chapter("maps", "Map reading")
L = LS(c, "direction-scale", "Direction, scale and map symbols",
    ["Give directions with the eight points of the compass", "Use a scale to turn a map distance into a ground distance", "Read conventional signs and a key", "Give a four-figure grid reference"],
    [("text", "A **map** is a drawing of an area seen from above, on a smaller size. Maps show direction using the **compass**: the four main points are North, East, South and West, and between them are North-East, South-East, South-West and North-West. On most maps North is at the top. A **key** (or legend) explains the signs used for roads, rivers, schools and so on."),
     ("key", "definition", "Scale", "The **scale** tells how much smaller the map is than the real ground. It can be a statement (1 cm to 1 km), a line scale, or a **representative fraction** such as **1 : 50 000**, which means 1 cm on the map is 50 000 cm = **0.5 km** on the ground. A larger number after the colon means a smaller scale and less detail."),
     ("key", "methode", "Measuring a ground distance", "1. Measure the distance on the map with a ruler, in cm.\n2. Find what 1 cm stands for on the ground (use the scale).\n3. Multiply the two numbers.\n4. Give the answer in the right unit (m or km).\nExample: 1 : 50 000 means 1 cm = 0.5 km, so 6 cm on the map = 6 × 0.5 = 3 km."),
     ("text", "**Grid references.** Maps are covered by a grid of numbered vertical lines (eastings) and horizontal lines (northings). To give a **four-figure grid reference** of a square, read the number of the vertical line on its left first, then the number of the horizontal line at its bottom: first **along** the corridor, then **up** the stairs. For example, 3 then 5 gives the reference 3 5 (written 0305 or 3 5 depending on the map)."),
     ("key", "pieges", "Common mistakes", "- Never give the northing before the easting.\n- Do not forget to convert cm on the map into km on the ground.\n- Use the key: the same colour or symbol can mean different things on different maps.")],
    [("Example 1: a road distance", "On a map of scale 1 : 50 000 the road from a school to a market measures 8 cm. How long is the real road?", ["1 cm on the map is 50 000 cm on the ground = 0.5 km.", "8 cm × 0.5 km = 4 km.", "The unit is kilometres."], "4 km."),
     ("Example 2: a direction", "A hospital is north-east of a church. In which direction is the church from the hospital?", ["Directions are opposite when we reverse the viewpoint.", "The opposite of north-east is south-west.", "So the church lies south-west of the hospital."], "South-west.")],
    F(compass("The eight compass points"), "The compass rose", "A compass rose with arrows to the north, south, east and west and the four in-between points."),
    [MCQ("On a map with scale 1 : 50 000, 1 cm represents", "0.5 km", ["5 km", "50 m", "500 km"], "50 000 cm is 500 m = 0.5 km."),
     TF("On a grid reference you give the northing before the easting.", False, "Always give the easting (along) first, then the northing (up)."),
     NUM("On a map of scale 1 : 50 000, a path is 6 cm long. How long is the real path in km?", 3, "6 × 0.5 km = 3 km.", unit="km"),
     NUM("On a map of scale 1 : 25 000, 1 cm is 250 m. A river bend is 10 cm long on the map. What is its length in km?", 2.5, "10 × 250 m = 2500 m = 2.5 km.", tol=0.01, unit="km", tier="approfondissement"),
     OPEN("Explain why a map of scale 1 : 10 000 shows more detail than a map of scale 1 : 1 000 000 for the same area.", "At 1 : 10 000 one centimetre stands for a short ground distance (100 m), so the area is shown larger and small features such as houses and paths fit on the map; at 1 : 1 000 000 one centimetre stands for 10 km and only big features can be drawn.", "1 mark: compare what 1 cm stands for; 1 mark: larger-scale map shows the area bigger; 1 mark: more detail possible.", points=3, tier="approfondissement"),
     PROB("A Form 1 class studies a sketch map of the area around their school, scale 1 : 20 000 (1 cm = 0.2 km).",
          [("num", "The school is 5 cm from the market on the map. How far is it in km?", 1, "5 × 0.2 = 1 km.", 0, "km", {}),
           ("mcq", "The clinic is south-west of the school. The school is ... of the clinic.", "north-east", ["south-east", "north-west", "west"], "The opposite of south-west is north-east.", {}),
           ("tf", "A key explains the symbols on the map.", True, "That is the purpose of a key.", {}),
           ("open", "Describe the three steps you use to find a real distance from a map.", "Measure the map distance with a ruler, use the scale to know what 1 cm stands for, then multiply and give the answer in km or m.", "1 mark per step.", {})])],
    [("The eight points of the compass include", "North-East", ["Upper-left", "Front", "Sunset"], "North-East lies between north and east."),
     ("A key on a map is used to", "explain the symbols", ["measure the scale", "find the north", "show the date"], "It lists what each sign means."),
     ("A representative fraction is written like", "1 : 50 000", ["50 000 km", "North 50", "1 + 50 000"], "It compares map and ground distances."),
     ("In a four-figure grid reference, the first number is the", "easting (along)", ["northing (up)", "scale", "height"], "Along the corridor first, then up the stairs."),
     ("If 1 cm stands for 1 km, 4 cm on the map is", "4 km", ["0.4 km", "40 km", "400 km"], "4 × 1 km = 4 km.")],
    ["Teacher to confirm the grid-reference convention used with the local topographic maps (some use six figures in Form 1) and the scale wording in the syllabus."], tag="Form 1 map reading")

# ---------------------------------------------------------------- CH3 weather
c = p.chapter("weather", "Weather")
L = LS(c, "weather-elements", "Weather elements and instruments",
    ["Name the main elements of weather", "Match each element to its instrument and unit", "Distinguish weather from climate", "Calculate a mean temperature"],
    [("text", "**Weather** is the state of the atmosphere at a place over a short time: today, this morning, this week. **Climate** is the average weather of a place over many years (often 30 or more). The main elements of weather are **temperature**, **rainfall**, **atmospheric pressure**, **wind**, **humidity**, **sunshine** and **cloud**."),
     ("key", "retenir", "Instruments", "- **Temperature**: thermometer (°C); the maximum-minimum thermometer records the highest and lowest values.\n- **Rainfall**: rain gauge (mm).\n- **Pressure**: barometer (millibars or hPa).\n- **Wind**: wind vane for direction, anemometer for speed.\n- **Humidity**: hygrometer.\n- **Sunshine**: sunshine recorder (hours)."),
     ("text", "Instruments are kept in a **weather station**. Thermometers are placed in a white, wooden box with slatted sides called a **Stevenson screen**, standing about 1.25 m above short grass in an open place, so that the air can flow and the sun does not heat the instruments directly. The rain gauge is placed in the open, away from trees and buildings."),
     ("key", "methode", "Mean temperature", "The **mean daily temperature** is half the sum of the highest (maximum) and the lowest (minimum) temperature of the day: (max + min) ÷ 2. The **daily range** is max − min. A **monthly mean** is the average of the daily means. Always give the unit, °C."),
     ("key", "pieges", "Common mistakes", "- A wind is named after the direction **from** which it blows: a south-west wind comes from the south-west.\n- Weather is not climate: 'it rained yesterday' is weather; 'Douala has a long rainy season' is climate.\n- Do not put a rain gauge under a tree.")],
    [("Example 1: mean temperature", "In Buea one day the maximum is 27 °C and the minimum is 17 °C. Find the mean temperature and the daily range.", ["Mean = (27 + 17) ÷ 2 = 44 ÷ 2 = 22.", "Range = 27 − 17 = 10.", "Both are in degrees Celsius."], "Mean 22 °C; range 10 °C."),
     ("Example 2: choose the instrument", "Which instrument would a school weather club use to measure the rain that fell during a storm, and in which unit?", ["Rain is collected in a rain gauge.", "The depth of water is measured in millimetres.", "So the instrument is the rain gauge and the unit is mm."], "Rain gauge, in mm.")],
    F(cols("Weather station", [("Element", ["Temperature", "Rainfall", "Wind speed", "Pressure"]), ("Instrument", ["Thermometer", "Rain gauge", "Anemometer", "Barometer"])], w=360), "Elements of weather and their instruments", "Two columns listing temperature, rainfall, wind speed and pressure with their instruments."),
    [MCQ("The instrument used to measure wind speed is the", "anemometer", ["barometer", "hygrometer", "rain gauge"], "An anemometer measures speed; a wind vane shows direction."),
     TF("A wind from the north-east blows towards the north-east.", False, "Winds are named by the direction they come from."),
     MATCH("Match each weather element to its instrument.", [("Rainfall", "Rain gauge"), ("Air pressure", "Barometer"), ("Humidity", "Hygrometer")], "Each instrument measures a particular element."),
     NUM("A day in Bamenda has a maximum of 28 °C and a minimum of 14 °C. What is the daily range?", 14, "28 − 14 = 14 °C.", unit="°C", tier="approfondissement"),
     OPEN("Explain the difference between weather and climate, with one Cameroonian example of each.", "Weather is the condition of the atmosphere over a short time, e.g. a thunderstorm in Limbe this afternoon. Climate is the average weather over many years, e.g. Limbe has a hot and very wet climate with a long rainy season.", "1 mark: weather = short term; 1 mark: climate = long-term average; 1 mark: suitable examples.", points=3, tier="approfondissement"),
     PROB("A school weather club in Kumba records the following for one day: maximum 30 °C, minimum 20 °C, rain 12 mm.",
          [("num", "What is the mean temperature of the day, in °C?", 25, "(30 + 20) ÷ 2 = 25.", 0, "°C", {}),
           ("mcq", "Which instrument measured the 12 mm of rain?", "rain gauge", ["thermometer", "anemometer", "barometer"], "Rain depth is read in a rain gauge.", {}),
           ("tf", "The thermometers should be placed inside a Stevenson screen.", True, "It protects them from direct sun and rain while letting air flow.", {}),
           ("open", "Give two rules for placing a rain gauge.", "Put it in an open place away from trees and buildings, with its rim level and above the ground so that splashes do not enter.", "1 mark per rule.", {})])],
    [("The average weather of a place over many years is its", "climate", ["wind", "pressure", "season only"], "Climate is the long-term average."),
     ("A rain gauge measures rainfall in", "millimetres", ["litres per second", "degrees", "hours"], "Depth of rain is measured in mm."),
     ("A Stevenson screen is used to", "shelter thermometers", ["collect rain", "measure wind", "make clouds"], "It is a white louvred box."),
     ("A barometer measures", "air pressure", ["humidity", "rainfall", "cloud type"], "Pressure is measured in millibars or hPa."),
     ("The mean of a maximum of 32 °C and a minimum of 22 °C is", "27 °C", ["54 °C", "10 °C", "22 °C"], "(32 + 22) ÷ 2 = 27.")],
    ["Teacher to verify the instrument height and site rules (about 1.25 m above ground is the usual textbook value) and the 30-year convention for climate."], tag="Form 1 weather elements")

# ---------------------------------------------------------------- CH4 rocks
c = p.chapter("rocks", "Rocks and soils")
L = LS(c, "rocks-weathering", "Rocks, weathering and soils",
    ["Name and describe the three types of rock", "Explain physical, chemical and biological weathering", "Describe the soil profile and the main soil types"],
    [("text", "**Rocks** make up the Earth's crust. There are three main types. **Igneous** rocks form when hot liquid rock (magma, or lava at the surface) cools and hardens, for example **granite** and **basalt**. **Sedimentary** rocks form when sand, mud and shells are laid down in layers and pressed together, for example **sandstone** and **limestone**. **Metamorphic** rocks are older rocks changed by great heat or pressure, for example **marble** (from limestone) and **slate** (from shale)."),
     ("key", "retenir", "Weathering", "**Weathering** is the breaking down of rocks where they lie, without movement by water or wind. **Physical** weathering: heating by day and cooling at night makes the rock crack and flake. **Chemical** weathering: rain water, which is slightly acid, slowly changes minerals; limestone dissolves. **Biological** weathering: roots grow into cracks and widen them."),
     ("text", "Weathered rock, mixed with dead plants and animals (**humus**), forms **soil**. A vertical cut through the soil is a **soil profile**. At the top is the dark **topsoil** rich in humus; below is the **subsoil**; then partly weathered rock; at the bottom is solid **bedrock**. Soil particles are **sand** (large), **silt** and **clay** (very small). A mixture of the three, called **loam**, is good for farming."),
     ("key", "retenir", "Soils near us", "Around **Mount Cameroon** the soils come from volcanic rock and are fertile, which is why bananas, oil palm and rubber are grown there. In many tropical lands heavy rain washes out plant foods and leaves a red soil rich in iron, often called **laterite**; it can be poor for crops unless it is well managed."),
     ("key", "attention", "Be careful", "- Weathering is not erosion: in weathering the rock breaks where it is; in erosion the pieces are carried away.\n- Marble and slate are metamorphic, not igneous.\n- Fertile soil is not only a matter of colour: it needs humus, minerals and water.")],
    [("Example 1: classify the rock", "A rock is made of tiny shells pressed into layers and contains fossils. What type is it, and what could it be called?", ["Layers and fossils show a sedimentary rock.", "Rock made of shells is limestone.", "So it is a sedimentary rock such as limestone."], "Sedimentary (for example limestone)."),
     ("Example 2: the type of weathering", "In a dry region a rock splits after many hot days and cold nights. Which type of weathering is this, and why?", ["The rock heats by day and cools by night.", "The change makes the surface expand and contract and crack.", "That is physical weathering."], "Physical weathering by temperature change.")],
    F(stack("Soil profile", ["Topsoil (dark, with humus)", "Subsoil (lighter, few roots)", "Weathered rock (broken pieces)", "Bedrock (solid rock)"]), "A soil profile", "Four horizontal layers from topsoil down to bedrock."),
    [MCQ("Granite is an example of an", "igneous rock", ["sedimentary rock", "metamorphic rock", "soil"], "Granite forms from cooled magma."),
     TF("Limestone is changed by heat and pressure to form marble.", True, "Marble is metamorphic, formed from limestone."),
     MATCH("Match each rock with its type.", [("Basalt", "Igneous"), ("Sandstone", "Sedimentary"), ("Slate", "Metamorphic")], "Basalt cools from lava, sandstone is layered grains, slate is changed shale."),
     MCQ("Tree roots splitting a rock is an example of", "biological weathering", ["chemical weathering", "deposition", "volcanic eruption"], "Living things break the rock.", tier="approfondissement"),
     OPEN("Describe the soil profile and say why topsoil is important to farmers.", "From the top: topsoil with humus, subsoil, weathered rock, bedrock. Topsoil holds humus, minerals and water and supports the roots of crops, so it is the most fertile layer.", "2 marks for naming layers in order; 1 mark for the role of topsoil.", points=3, tier="approfondissement"),
     PROB("Near Buea, farmers grow bananas on a dark soil formed from volcanic rock.",
          [("mcq", "Volcanic rock is", "igneous", ["sedimentary", "metamorphic", "organic"], "Volcanic rock forms from cooled lava.", {}),
           ("tf", "Soils from volcanic rock are often fertile.", True, "They contain many minerals useful to plants.", {}),
           ("mcq", "Which layer of the soil profile contains most humus?", "topsoil", ["bedrock", "subsoil", "weathered rock"], "Humus is concentrated at the surface.", {}),
           ("open", "Give two ways to keep a soil fertile.", "Add manure or compost, rotate crops, plant cover crops and avoid bare soil; also use terraces on slopes.", "1 mark per way.", {})])],
    [("A rock formed from cooled lava is", "igneous", ["sedimentary", "metamorphic", "sandy"], "Igneous rocks cool from magma or lava."),
     ("Fossils are most often found in", "sedimentary rocks", ["granite", "basalt", "magma"], "Layers can preserve remains of living things."),
     ("Humus is", "decayed plant and animal matter", ["a kind of rock", "a mineral", "sand"], "It makes the soil fertile."),
     ("The solid rock at the bottom of a soil profile is called", "bedrock", ["topsoil", "humus", "loam"], "Bedrock lies below weathered rock."),
     ("The breaking down of rock where it lies is", "weathering", ["erosion", "transport", "deposition"], "No movement is involved in weathering.")],
    ["Teacher to verify rock examples and the local soil statements (volcanic soils near Mount Cameroon; laterite in the tropics) against the syllabus."], tag="Form 1 rocks and soils")

# ---------------------------------------------------------------- CH5 Cameroon
c = p.chapter("cameroon", "Cameroon: location and relief")
L = LS(c, "cameroon-location", "Location, neighbours and regions of Cameroon",
    ["Describe the location of Cameroon in Africa", "Name its neighbours and the ten regions", "Describe the main relief regions", "Name the highest mountain"],
    [("text", "Cameroon lies in **Central and West Africa**, at the top of the Gulf of Guinea, where the coast bends. It has a coast on the **Atlantic Ocean**. Its neighbours are **Nigeria** (west), **Chad** (north-east, with Lake Chad), the **Central African Republic** (east), and **Congo**, **Gabon** and **Equatorial Guinea** (south). Its capital is **Yaoundé** and its largest city and main port is **Douala**."),
     ("key", "retenir", "Ten regions", "Cameroon has ten regions: **Far North, North, Adamawa, East, Centre, South, Littoral, South-West, North-West** and **West**. The two English-speaking regions are the North-West (capital Bamenda) and the South-West (capital Buea). The Littoral's capital is Douala. The Centre's capital is Yaoundé."),
     ("key", "retenir", "Relief", "- **Coastal plain**: low and hot, near Douala and Limbe.\n- **Southern plateau**: forested, about 600–700 m high.\n- **Western Highlands**: volcanic mountains and the Grassfields (Bamenda, Bafoussam).\n- **Adamawa Plateau**: high grassland, about 1000 m.\n- **Northern plains**: the Benue lowland and the Lake Chad basin.\n- **Mount Cameroon** (about 4000 m) is the highest peak and an active volcano."),
     ("text", "Cameroon is often called **'Africa in miniature'**, because it has most of the continent's natural environments in one country: coast, rainforest, savanna, mountains and semi-desert. This variety of relief and climate allows many different crops, animals and ways of life, from fishing at Kribi to herding in the north."),
     ("key", "pieges", "Common mistakes", "- Do not confuse a region (a large administrative area) with a division or a town.\n- Mount Cameroon is in the South-West Region, not in the North-West.\n- Cameroon is not landlocked: it has a coast on the Atlantic Ocean.")],
    [("Example 1: neighbours", "Which neighbour of Cameroon lies to the west, and which lie to the south?", ["On a map, the long western border is shared with Nigeria.", "To the south we find Equatorial Guinea, Gabon and Congo.", "So Nigeria is west; Equatorial Guinea, Gabon and Congo are south."], "West: Nigeria. South: Equatorial Guinea, Gabon and Congo."),
     ("Example 2: relief region", "You are travelling from Douala to Bamenda. In which direction does the land rise, and into which relief region do you enter?", ["Douala is on the low coastal plain.", "Bamenda lies inland and north in the Western Highlands.", "The land rises as you enter the highlands."], "The land rises; you enter the Western Highlands (Grassfields).")],
    F(tilemap(), "The ten regions (schematic)", "A schematic tile map placing the ten regional names roughly where they lie."),
    [MCQ("The capital city of Cameroon is", "Yaoundé", ["Douala", "Bamenda", "Garoua"], "Douala is the economic capital and main port."),
     TF("Cameroon has no coast on the Atlantic Ocean.", False, "It has a coast on the Gulf of Guinea, part of the Atlantic."),
     MATCH("Match each region with its capital.", [("North-West", "Bamenda"), ("South-West", "Buea"), ("Littoral", "Douala")], "These capitals are well known."),
     MCQ("The highest mountain in Cameroon is", "Mount Cameroon", ["Mount Kenya", "Mount Oku", "Mount Manengouba"], "Mount Cameroon is about 4000 m high.", tier="approfondissement"),
     OPEN("Explain why Cameroon is called 'Africa in miniature'.", "It has coastal plains, rainforest, savanna, highlands and semi-desert, so it contains most of the continent's natural environments within one country.", "1 mark for variety of environments; 2 marks for naming three or more.", points=3, tier="approfondissement"),
     PROB("Study the neighbours and regions of Cameroon.",
          [("mcq", "Which country borders Cameroon to the west?", "Nigeria", ["Gabon", "Chad", "Congo"], "Nigeria shares the western border.", {}),
           ("num", "How many regions does Cameroon have?", 10, "There are ten regions.", 0, None, {}),
           ("tf", "Lake Chad is in the north of Cameroon's neighbourhood.", True, "Cameroon, Chad, Nigeria and Niger share Lake Chad.", {}),
           ("open", "Name two relief regions of Cameroon and give a town in each.", "The coastal plain (Douala or Limbe) and the Western Highlands (Bamenda or Bafoussam); also the Adamawa Plateau (Ngaoundéré).", "1 mark per relief region with a correct town.", {})])],
    [("Which of these is a neighbour of Cameroon?", "Gabon", ["Ghana", "Kenya", "Senegal"], "Gabon lies south of Cameroon."),
     ("The main port of Cameroon is", "Douala", ["Garoua", "Bamenda", "Maroua"], "Douala is on the Wouri estuary."),
     ("Buea is the capital of the", "South-West Region", ["North-West Region", "West Region", "East Region"], "Buea lies on the slopes of Mount Cameroon."),
     ("Cameroon is called 'Africa in miniature' because of its", "variety of environments", ["small size", "single climate", "few people"], "It combines many African landscapes."),
     ("How many regions does Cameroon have in total?", "10", ["8", "12", "6"], "There are ten regions.")],
    ["Teacher to verify: height of Mount Cameroon (about 4000 m; commonly 4095 m), plateau heights, regional capitals, and the list of neighbours with the current names of the regions (the tile map is schematic and not to scale)."], tag="Form 1 Cameroon")

# ---------------------------------------------------------------- CH6 settlements
c = p.chapter("people", "People and settlements")
L = LS(c, "settlement", "Why and where people settle",
    ["Define settlement, site and situation", "Describe rural and urban settlements", "Describe nucleated, linear and dispersed patterns", "Explain the functions of towns"],
    [("text", "A **settlement** is a place where people live and work, from a small hamlet to a big city. The **site** is the actual land on which the settlement is built; the **situation** is its position in relation to the land around it (roads, rivers, other towns). People choose sites with a **water supply**, **flat or gently sloping land**, **fertile soil**, safety from floods and enemies, building materials, and good routes."),
     ("key", "retenir", "Rural and urban", "**Rural** settlements (villages, hamlets) are small, with most people farming, fishing or herding. **Urban** settlements (towns, cities) are large, with most people working in trade, services, offices and industries, and with many services such as hospitals, schools and markets."),
     ("key", "retenir", "Patterns", "- **Nucleated**: houses grouped closely round a centre such as a market or a spring.\n- **Linear**: houses in a line along a road, river or coast.\n- **Dispersed**: houses far apart, scattered, often among farms."),
     ("text", "Towns have **functions**, the main jobs they do. **Douala** is a port and commercial centre. **Yaoundé** is the capital, with government offices and universities. **Garoua** is a river port on the Benue and a regional centre in the north. **Limbe** is a coastal town with a port, tourism and an oil refinery. Many towns have a mixture of functions. Settlements often grow along main roads and at river crossings."),
     ("key", "attention", "Be careful", "- Site and situation are different: site = the land itself; situation = relationship to surroundings.\n- A big village is still rural if people mostly farm; size is not the only difference.\n- Settlement patterns are general descriptions: real places often mix them.")],
    [("Example 1: site factors", "A new village is planned near a stream on a gentle slope with good soil. Give two reasons why this is a good site.", ["The stream gives a water supply for drinking and farming.", "A gentle slope avoids flooding and is easy to build on.", "Good soil allows farming nearby."], "Water supply and gentle, well-drained land (and fertile soil)."),
     ("Example 2: pattern", "Houses stand one after another along the main road from Kumba towards Mamfe, with farms behind them. Which pattern is this?", ["The houses follow a single line.", "The line is controlled by the road.", "This is a linear settlement."], "Linear.")],
    F(shapes([T(70, 20, "Nucleated", bold=True, size=13), T(210, 20, "Linear", bold=True, size=13), T(350, 20, "Dispersed", bold=True, size=13)] +
             [RECT(45 + 18 * i, 60 + 18 * j, 12, 12, fill="lightorange") for i in range(3) for j in range(3)] +
             [LINE(150, 120, 270, 60, color="grey", width=3)] + [RECT(150 + 24 * i, 108 - 10 * i, 12, 12, fill="lightorange") for i in range(5)] +
             [RECT(x, y, 12, 12, fill="lightorange") for x, y in [(310, 50), (370, 70), (330, 110), (385, 130), (300, 140)]], 420, 170),
         "Three settlement patterns", "Three small diagrams of houses: grouped together, in a line along a road, and scattered apart."),
    [MCQ("The actual land on which a village is built is its", "site", ["situation", "function", "pattern"], "Site means the actual ground."),
     TF("Most people in rural settlements work in farming, fishing or herding.", True, "These are the main rural activities."),
     MATCH("Match each pattern with its description.", [("Nucleated", "Houses grouped round a centre"), ("Linear", "Houses along a road"), ("Dispersed", "Houses far apart")], "Patterns describe how houses are arranged."),
     MCQ("Which function best fits Douala?", "port and commercial centre", ["fishing hamlet only", "mountain resort", "military camp only"], "Douala has Cameroon's main port.", tier="approfondissement"),
     OPEN("Explain three factors people consider when choosing the site of a settlement.", "Water supply for drinking and farming; flat or gentle, well-drained land and safety from floods; fertile soil, building materials and good routes for trade.", "1 mark per factor with a reason.", points=3, tier="approfondissement"),
     PROB("A new market town grows where a road crosses the river near Bamenda.",
          [("mcq", "A town growing at a river crossing is an example of the importance of", "situation (routes)", ["colour of the soil", "the Moon", "the equator"], "Crossings bring routes together.", {}),
           ("tf", "Towns have services such as hospitals and schools that villages often lack.", True, "Services concentrate in towns.", {}),
           ("mcq", "Houses scattered over a wide farming area form a ... settlement.", "dispersed", ["nucleated", "linear", "port"], "Dispersed means spread out.", {}),
           ("open", "Give two problems that may result when a town grows quickly.", "Overcrowding and shortage of housing, traffic jams, pressure on water, waste and electricity, unemployment.", "1 mark per problem.", {})])],
    [("A settlement where houses stand along a road is", "linear", ["dispersed", "nucleated", "rural only"], "Linear patterns follow roads or rivers."),
     ("A hamlet is a", "very small rural settlement", ["big port", "capital city", "industrial town"], "Hamlets have few houses."),
     ("The function of a capital city includes", "government and administration", ["only fishing", "only farming", "only mining"], "Capitals host government offices."),
     ("A good settlement site has", "a water supply", ["no water", "steep cliffs only", "flooded land"], "Water is essential."),
     ("Which place is a river port in northern Cameroon?", "Garoua", ["Limbe", "Kribi", "Buea"], "Garoua lies on the River Benue.")],
    ["Teacher to verify the functions given to Cameroonian towns and the example distances; the Kumba–Mamfe road example is a general illustration only."], tag="Form 1 settlements")

p.write()
