import sys
sys.path.insert(0, "/home/user/CastBridge/tools/learn-authoring/anglophone")
from fe_kit import *

p = english_pack("form1-english", 1,
    "A first-year secondary English course: nouns, pronouns, present and past tenses, adjectives and adverbs, prepositions and conjunctions, punctuation, word building, a first reading comprehension, an informal letter and oral English, with Cameroonian examples and original exercises.",
    "Cameroon secondary school English Language, Form 1 (anglophone sub-system) — scope and order to be checked against the official programme and the class textbook")

REF = "Form 1 English Language (to be checked against the official programme)"

# ===================================================================== grammar
g = p.chapter("ch-grammar", "Grammar: nouns, pronouns, verbs and describing words", REF)

LS(g, "nouns-articles", "Nouns, plurals and articles", 24,
   ["Name the main kinds of noun.", "Form regular and common irregular plurals.", "Choose a, an or the correctly."],
   [tx("A **noun** names a person, place, thing, animal or idea. Every sentence about Cameroon is full of nouns: *Nana, Douala, a mango, hunger, the market*. Knowing the kind of noun helps you to choose capital letters, plurals and articles correctly."),
    ky("definition", "Kinds of noun",
       "- **Common noun:** a general name (*girl, town, river*).\n- **Proper noun:** the special name of one person or place; it begins with a **capital letter** (*Ngu, Buea, River Wouri*).\n- **Abstract noun:** an idea or feeling we cannot touch (*joy, hunger, honesty*).\n- **Collective noun:** a group (*a class, a team, a flock*).\n- **Countable** nouns can be counted (*two eggs*); **uncountable** ones cannot (*rice, water, advice*)."),
    fg(tree("Kinds of noun", "Noun", [("common", "girl, town"), ("proper", "Buea, Ngu"), ("abstract", "joy, hunger")], h=185),
       "Ask: is it a general name, a special name, or an idea?", "A diagram with the word Noun at the top and three arrows to common (girl, town), proper (Buea, Ngu) and abstract (joy, hunger)."),
    ky("methode", "Plurals and articles",
       "- Most nouns add **-s**: *book, books*.\n- After **s, x, ch, sh** add **-es**: *box, boxes; church, churches*.\n- Consonant + **y** becomes **-ies**: *baby, babies*.\n- Irregular: *man, men; child, children; woman, women; tooth, teeth; foot, feet*.\n- Use **a** before a consonant **sound** (*a goat, a university*), **an** before a vowel sound (*an egg, an hour*), **the** for something already known (*the goat we bought*)."),
    ky("pieges", "Common mistakes",
       "- *Childrens, mans* are wrong: the plural of child is **children**.\n- Uncountable nouns have no plural: say *some advice*, not *advices*; *some information*, not *informations*.\n- Do not forget capital letters for proper nouns: *Bamenda*, not *bamenda*.\n- Choose a / an by the **sound**, not the spelling: *an honest man, a European*."),
    exm("Example 1: a plural", "Write the plural of *church*, *baby* and *child*.",
        ["*church* ends in **ch**, so add **-es**: *churches*.", "*baby* is consonant + y: change y to **ies**: *babies*.", "*child* is irregular: *children*."], "churches, babies, children"),
    exm("Example 2: a or an?", "Complete: *I bought ___ orange and ___ pineapple at the market.*",
        ["*orange* starts with a vowel sound, so use **an**.", "*pineapple* starts with a consonant sound, so use **a**."], "an orange and a pineapple")],
   [m("Which word is a proper noun?", "Limbe", ["town", "beach", "happiness"], "Limbe is the special name of one town, so it is a proper noun."),
    m("What is the plural of *box*?", "boxes", ["boxs", "boxen", "boxies"], "Nouns ending in x take -es."),
    t("*Advice* is an uncountable noun, so we say *some advice*.", True, "Uncountable nouns have no plural form and take *some*."),
    m("Choose the correct sentence.", "The children ate an egg each.", ["The childs ate a egg each.", "The childrens ate an egg each.", "The children ate a egg each."], "Children is the plural of child and egg begins with a vowel sound, so *an*."),
    mt("Match each noun to its kind.", [["Yaoundé", "proper noun"], ["honesty", "abstract noun"], ["team", "collective noun"], ["river", "common noun"]], "Yaoundé names one place; honesty is an idea; team is a group; river is a general name."),
    o("Write four sentences about your family or your street. Use one proper noun, one abstract noun, one plural noun and the article *an* correctly.",
      "My cousin Nana lives in Bamenda. Her kindness makes everyone happy. She keeps three goats and two hens. Every morning she eats an orange.",
      ["1 mark: a proper noun with a capital letter.", "1 mark: an abstract noun used correctly.", "1 mark: a correct plural.", "1 mark: *an* used before a vowel sound."])],
   [sc("A noun that names an idea, such as *courage*, is called a(n)...", "abstract noun", ["proper noun", "collective noun", "plural noun"], "Courage cannot be touched: it is an abstract noun."),
    sc("Which is the correct plural of *woman*?", "women", ["womans", "womens", "womanes"], "Woman is irregular: women."),
    sc("Which sentence uses an article correctly?", "She waited for an hour.", ["She waited for a hour.", "She waited for an hours.", "She waited for hour."], "The h in hour is silent, so the word starts with a vowel sound."),
    sc("A flock of sheep: *flock* is a...", "collective noun", ["proper noun", "abstract noun", "verb"], "A flock is a group of animals."),
    sc("Which noun is uncountable?", "rice", ["egg", "book", "goat"], "We say some rice, not two rices.")])

LS(g, "pronouns-determiners", "Pronouns and words that point to nouns", 24,
   ["Use subject, object and possessive pronouns correctly.", "Use this, that, these and those.", "Avoid repeating nouns clumsily."],
   [tx("A **pronoun** takes the place of a noun so that we do not repeat it. Compare: *Ngum took Ngum's bag and Ngum went home* with *Ngum took his bag and he went home*. Pronouns change their form depending on their job in the sentence."),
    ky("definition", "Pronoun forms",
       "- **Subject:** I, you, he, she, it, we, they (they do the action).\n- **Object:** me, you, him, her, it, us, them (they receive the action).\n- **Possessive adjective** (before a noun): my, your, his, her, its, our, their.\n- **Possessive pronoun** (alone): mine, yours, his, hers, ours, theirs.\n*She gave me her book. The book is hers.*"),
    ky("definition", "Pointing words",
       "**This / these** point to things that are **near**; **that / those** point to things that are **far**. *This mango (in my hand) is sweet; that mango (on the tree) is not ripe.* **This** and **that** are singular, **these** and **those** are plural."),
    fg(cols("Subject and object", ["Subject", "Object", "Possessive"], [["I", "me", "my / mine"], ["he", "him", "his"], ["she", "her", "her / hers"], ["we", "us", "our / ours"], ["they", "them", "their / theirs"]]),
       "The same person, three forms.", "A table with three columns, subject, object and possessive, listing I me my mine, he him his, she her hers, we us ours and they them theirs."),
    ky("pieges", "Common mistakes",
       "- *Me and Ada went to school* is wrong: use **Ada and I went** (subject). After a verb or preposition use the object form: *She gave it to Ada and me.*\n- *It's* means *it is*; **its** shows ownership (*the dog wagged its tail*).\n- *Their* (belonging to them), *there* (place), *they're* (they are) are different words."),
    exm("Example 1: subject or object?", "Choose the right word: *Mama called Ada and (I / me) to the kitchen.*",
        ["*Ada and ___* are the **objects** of called (Mama did the calling).", "Take Ada away: *Mama called me.* So the correct word is **me**."], "Mama called Ada and me."),
    exm("Example 2: replace the nouns", "Rewrite using pronouns: *Nkem lost Nkem's pen, so Nkem asked Tabi and Tabi's sister to look for the pen.*",
        ["Replace repeated names: Nkem becomes **he or she**, Nkem's becomes **his or her**.", "*Tabi and Tabi's sister* becomes **them**, and *the pen* becomes **it**."], "Nkem lost her pen, so she asked them to look for it.")],
   [m("Choose the correct pronoun: *The teacher gave ___ a prize.*", "us", ["we", "our", "ours"], "After a verb we need the object form: us."),
    m("Complete: *___ books on the shelf (far away) are mine.*", "Those", ["This", "That", "These"], "Far away and plural: those."),
    t("*Its* with an apostrophe (*it's*) is the possessive form.", False, "It's means it is. The possessive is its (no apostrophe)."),
    m("Which sentence is correct?", "Ada and I fetched the water.", ["Me and Ada fetched the water.", "Ada and me fetched the water.", "Ada and myself fetched I water."], "Ada and I are the subjects: use I."),
    mt("Match each word to its use.", [["mine", "possessive pronoun"], ["them", "object pronoun"], ["our", "possessive adjective"], ["she", "subject pronoun"]], "Mine stands alone; them receives an action; our is before a noun; she does the action."),
    o("Rewrite so that nothing is repeated clumsily: *Mbah and Mbah's cousin went to the stream. Mbah and Mbah's cousin carried Mbah's and Mbah's cousin's buckets back home.*",
      "Mbah and his cousin went to the stream. They carried their buckets back home.",
      ["1 mark: *his cousin* instead of repeating the name.", "1 mark: *they* as subject.", "1 mark: *their buckets*.", "1 mark: meaning kept, punctuation correct."])],
   [sc("In *The prize is hers*, the word *hers* is a...", "possessive pronoun", ["subject pronoun", "object pronoun", "noun"], "It stands alone and shows ownership."),
    sc("Which word means *they are*?", "they're", ["their", "there", "theirs"], "They're is the short form of they are."),
    sc("We use *these* for things that are...", "plural and near", ["singular and far", "plural and far", "singular and near"], "These = plural, near."),
    sc("Choose the right form: *Please send the letter to Ngu and ___.*", "me", ["I", "my", "mine"], "After to we use the object pronoun."),
    sc("Which pair are both subject pronouns?", "we, they", ["us, them", "me, him", "my, our"], "We and they do the action.")])

LS(g, "present-tenses", "Present simple and present continuous", 26,
   ["Use the present simple for habits and facts.", "Use the present continuous for actions happening now.", "Make the verb agree with its subject (he/she/it + s)."],
   [tx("We use the **present simple** for things that are always true or happen regularly, and the **present continuous** for things happening **now** or around now. *Kumba sells fish every Monday* (habit). *She is selling fish at this moment* (now)."),
    ky("definition", "Present simple",
       "Use the base verb; add **-s / -es** after *he, she, it* and singular nouns.\n- *I walk to school. Mary walks to school.*\n- **Questions and negatives** use **do / does**: *Does she walk? She does not walk.* After *does* the verb has **no -s**.\n- Signal words: *always, usually, every day, often, never, on Sundays.*"),
    ky("definition", "Present continuous",
       "Form: **am / is / are + verb-ing**. *I am reading. He is cooking. They are playing.* Questions: *Are they playing?* Negative: *He is not cooking.*\nSignal words: *now, at the moment, today, these days, look!*\nStative verbs (*know, like, want, understand*) are normally **not** used in the continuous: say *I know the answer*, not *I am knowing*."),
    fg(cols("Two present tenses", ["Tense", "Use", "Example"], [["simple", "habit, fact", "She sells fish."], ["continuous", "happening now", "She is selling."]], w=440),
       "Habit or action in progress? Choose the tense by the meaning.", "A table comparing the present simple, used for habits and facts, for example She sells fish, with the present continuous, used for actions happening now, for example She is selling."),
    ky("pieges", "Common mistakes",
       "- *He go to school* → **He goes** to school (add -es).\n- *Does she goes?* → **Does she go?** (no -s after does).\n- *I am know* → **I know** (stative verb).\n- *She is cook now* → **She is cooking** (do not forget -ing).\n- Spelling: *run → running, make → making, study → studying*."),
    exm("Example 1: choose the tense", "Complete: *Every morning Ngwa (wash / is washing) his face, but look! He (wash / is washing) the car now.*",
        ["*Every morning* shows a habit: present simple, **washes**.", "*Look!* and *now* show an action in progress: **is washing**."], "washes ... is washing"),
    exm("Example 2: make a question", "Turn into a question: *Tabi plays football on Saturdays.*",
        ["The verb is in the present simple, so we use **does** (Tabi = he).", "After *does* the main verb loses its -s: *Does Tabi play football on Saturdays?*"], "Does Tabi play football on Saturdays?")],
   [m("Choose the correct sentence.", "My mother sells plantain every day.", ["My mother sell plantain every day.", "My mother is sell plantain every day.", "My mother selling plantain every day."], "Habit with a singular subject: sells."),
    m("*Listen! The baby ___.*", "is crying", ["cries every night", "cry", "does crying"], "Listen! points to an action happening now."),
    t("We say *Does she goes to church?*", False, "After does the verb has no -s: Does she go?"),
    m("Which verb is not normally used in the continuous?", "know", ["run", "cook", "write"], "Know is a stative verb."),
    m("Give the -ing form of *make*.", "making", ["makeing", "makking", "makeng"], "Drop the silent e and add -ing."),
    o("Write four sentences: two about what you do every week (present simple) and two about what is happening around you now (present continuous).",
      "I go to the market on Saturdays. My sister helps me carry the bags. Now I am sitting in the classroom. The teacher is writing on the board.",
      ["1 mark: two correct present simple sentences.", "1 mark: two correct present continuous sentences (am/is/are + -ing).", "1 mark: correct agreement (goes, helps).", "1 mark: signal words or meaning clearly right."])],
   [sc("The present continuous is formed with...", "am/is/are + verb-ing", ["do/does + verb", "have + verb", "will + verb"], "Be + -ing."),
    sc("*She ___ to school by bus every day.*", "goes", ["go", "is go", "going"], "Habit, singular subject: goes."),
    sc("Which signal word suggests the present continuous?", "at the moment", ["always", "every day", "never"], "At the moment shows an action in progress."),
    sc("Choose the correct negative: *He ___ like cassava.*", "does not", ["do not", "is not", "not"], "Present simple negative with he: does not."),
    sc("The -ing form of *run* is...", "running", ["runing", "runeing", "runningg"], "Double the final consonant after a short vowel.")])

LS(g, "past-tenses", "The simple past tense", 26,
   ["Form the simple past of regular and irregular verbs.", "Make past questions and negatives with did.", "Use time expressions such as yesterday and last year."],
   [tx("The **simple past** tells us about actions that finished at a definite time before now: *Yesterday we visited my grandfather in Bafoussam. We ate achu and returned in the evening.*"),
    ky("definition", "Forming the simple past",
       "- **Regular verbs** add **-ed**: *walk → walked; play → played*. If the verb ends in e add **-d** (*live → lived*); consonant + y becomes **-ied** (*carry → carried*).\n- **Irregular verbs** change form: *go → went, eat → ate, see → saw, buy → bought, come → came, write → wrote, have → had, bring → brought*.\n- Time words: *yesterday, last week, in 2019, two days ago.*"),
    ky("definition", "Questions and negatives",
       "Use **did** (for every subject) and the **base verb**:\n- *Did you go to the match? No, I did not (didn't) go.*\n- *She did not buy any fish.*\nThe past form shows only **once**: *did + go*, never *did + went*."),
    fg(flow("Forming the simple past", ["Is the action finished?", "Regular verb: add -ed", "Irregular verb: learn the form", "Question or negative: did + base verb"]),
       "Four quick decisions.", "A flowchart of four boxes: is the action finished, regular verb add ed, irregular verb learn the form, and question or negative use did plus the base verb."),
    ky("pieges", "Common mistakes",
       "- *Did he went?* → **Did he go?**\n- *I buyed a dress* → **I bought** a dress.\n- *She didn't saw me* → **She didn't see me.**\n- Do not mix tenses in one story: if you begin with *went*, continue with *saw, bought, came*.\n- Spelling: *stop → stopped, plan → planned*."),
    exm("Example 1: put in the past", "Rewrite in the past: *Ada goes to Limbe and buys fish.*",
        ["Add a time word: *Last Sunday*.", "*goes → went, buys → bought*."], "Last Sunday Ada went to Limbe and bought fish."),
    exm("Example 2: negative", "Make negative: *They watched the match.*",
        ["Use **did not** and the base form: *watch*.", "Do not keep the -ed: *did not watched* is wrong."], "They did not watch the match.")],
   [m("What is the past tense of *bring*?", "brought", ["bringed", "braught", "brang"], "Bring is irregular: brought."),
    m("Choose the correct question.", "Did Nkeng go to church?", ["Did Nkeng went to church?", "Does Nkeng went to church?", "Nkeng did went to church?"], "Did + base verb."),
    t("*She didn't saw the accident* is correct.", False, "After didn't use the base verb: She didn't see the accident."),
    m("The past tense of *carry* is...", "carried", ["carryed", "carred", "carrid"], "Consonant + y changes to -ied."),
    m("Which time expression goes with the simple past?", "two days ago", ["at the moment", "every morning", "tomorrow"], "Ago refers to a finished time in the past."),
    o("Write a paragraph of five sentences in the simple past about a visit to a market, a farm or a relative. Use at least two irregular verbs.",
      "Last Saturday I went to the market in Kumba with my mother. We bought tomatoes and onions. A woman gave me a small piece of sugarcane. I ate it on the way home. We came back before it rained.",
      ["1 mark: all verbs in the simple past.", "1 mark: at least two correct irregular verbs.", "1 mark: a time expression.", "1 mark: clear sentences with capital letters and full stops."])],
   [sc("The past tense of *eat* is...", "ate", ["eated", "eaten", "eating"], "Eat is irregular: ate."),
    sc("After *did* we use...", "the base verb", ["the past form", "the -ing form", "the -s form"], "Did + go, not did + went."),
    sc("*Yesterday, I ___ a letter.*", "wrote", ["write", "writed", "written"], "Irregular past of write."),
    sc("Which is the correct past of *study*?", "studied", ["studyed", "studed", "studing"], "y becomes ied after a consonant."),
    sc("Which sentence is in the simple past?", "We visited Buea last year.", ["We visit Buea every year.", "We are visiting Buea.", "We will visit Buea."], "Visited with last year.")])

LS(g, "adjectives-adverbs", "Adjectives, adverbs and comparison", 24,
   ["Tell adjectives from adverbs.", "Form comparative and superlative adjectives.", "Use good/well and fast/hard correctly."],
   [tx("An **adjective** describes a noun (*a heavy bag, the red soil*). An **adverb** describes a verb, an adjective or another adverb and often answers *how, when, where*: *She walked slowly. He arrived early.* Many adverbs of manner end in **-ly**."),
    ky("definition", "Comparing things",
       "- Short adjectives: **-er / -est**: *tall, taller, tallest*; *big, bigger, biggest*; *happy, happier, happiest*.\n- Long adjectives: **more / most**: *beautiful, more beautiful, the most beautiful*.\n- Irregular: *good, better, best; bad, worse, worst; far, farther, farthest*.\nUse **than** to compare two things: *Mount Cameroon is higher than the hill near our school.*"),
    ky("definition", "Making adverbs",
       "Add **-ly** to an adjective: *quick → quickly; careful → carefully; happy → happily*. Some adverbs keep the same form: *fast, hard, late, early*. **Good** is an adjective, **well** is an adverb: *She is a good singer. She sings well.*"),
    fg(cols("Comparison", ["Base", "Comparative", "Superlative"], [["tall", "taller", "tallest"], ["good", "better", "best"], ["bad", "worse", "worst"], ["important", "more important", "most important"]], w=440),
       "Learn the irregular rows by heart.", "A table with base, comparative and superlative forms: tall taller tallest, good better best, bad worse worst, important more important most important."),
    ky("pieges", "Common mistakes",
       "- *more taller, most best* (double comparison) → **taller**, **best**.\n- *He runs quick* → **He runs quickly.**\n- *She speaks good English* → **She speaks English well** (or *good English* as a noun phrase: *She has good English*).\n- *Ada is more tall than Ngu* → **taller than**.\n- Use **than**, not *then*, after a comparative."),
    exm("Example 1: comparative", "Complete: *This plantain is ___ (big) than that one, but the pineapple is the ___ (heavy) fruit in the basket.*",
        ["Comparing two things: *big → bigger* (double the g).", "Comparing many: *heavy → the heaviest* (y becomes i)."], "bigger ... heaviest"),
    exm("Example 2: adjective or adverb?", "Choose: *The students listened (careful / carefully) to the careful (teacher / teaching).*",
        ["*listened* is a verb, so we need an adverb: **carefully**.", "*careful* is an adjective describing a noun."], "carefully")],
   [m("What is the comparative of *happy*?", "happier", ["more happy", "happyer", "happiest"], "Short adjective ending in y: happier."),
    m("Choose the correct sentence.", "She sings well.", ["She sings good.", "She sing good.", "She is singing goodly."], "Well is the adverb that describes sings."),
    t("*Most best* is a correct superlative.", False, "Best is already a superlative. Do not add most."),
    m("Which word is an adverb?", "slowly", ["slow", "slower", "slowest"], "Slowly ends in -ly and describes a verb."),
    mt("Match the adjective to its superlative.", [["good", "best"], ["bad", "worst"], ["far", "farthest"], ["interesting", "most interesting"]], "Irregular adjectives change form; long ones take most."),
    o("Write four sentences comparing two things you know in Cameroon (for example two towns, two foods or two animals). Use one comparative with *-er*, one with *more*, one superlative and one adverb of manner.",
      "Douala is bigger than Limbe. Plantain is more filling than rice. Mount Cameroon is the highest mountain I know. The farmers worked quickly before the rain.",
      ["1 mark: a correct -er comparative with than.", "1 mark: a correct more + adjective comparative.", "1 mark: a correct superlative with the.", "1 mark: a correct adverb of manner."])],
   [sc("The superlative of *good* is...", "best", ["gooder", "most good", "better"], "Good, better, best."),
    sc("Which word describes a noun?", "adjective", ["adverb", "verb", "pronoun"], "An adjective describes a noun."),
    sc("*He drove ___.*", "carefully", ["careful", "care", "carefulness"], "An adverb is needed to describe drove."),
    sc("Choose the correct comparison.", "Ngu is taller than Tabi.", ["Ngu is more tall than Tabi.", "Ngu is tallest than Tabi.", "Ngu is tall than Tabi."], "Tall takes -er and than."),
    sc("The adverb from *quick* is...", "quickly", ["quickness", "quicker", "quicky"], "Add -ly.")])

LS(g, "prepositions-conjunctions", "Prepositions and linking words", 24,
   ["Use prepositions of place, time and movement.", "Join short sentences with and, but, or, so and because.", "Avoid common preposition errors."],
   [tx("A **preposition** shows the relation between a noun or pronoun and another word: *The book is **on** the table. We arrive **at** noon.* A **conjunction** joins words or sentences: *I like rice **and** beans, **but** I do not like okra.*"),
    ky("definition", "Common prepositions",
       "- **Place:** *in* (inside a space: *in the room, in Douala*), *on* (a surface: *on the desk*), *at* (a point: *at the gate, at school*), *under, behind, between, beside, near.*\n- **Time:** *at* (clock times: *at six o'clock*), *on* (days and dates: *on Monday, on 11 February*), *in* (months, years, parts of the day: *in May, in 2024, in the morning*).\n- **Movement:** *to, from, into, across, through, along, up, down.*"),
    ky("definition", "Linking words",
       "- **and** adds an idea; **but** shows contrast; **or** gives a choice; **so** gives a result; **because** gives a reason.\n*I was hungry, so I bought puff-puff.* / *I bought puff-puff because I was hungry.*\nPut a comma before *but, so* when they join two full clauses."),
    fg(cols("Time prepositions", ["at", "on", "in"], [["6 o'clock", "Monday", "May"], ["noon", "my birthday", "2024"], ["night", "Friday morning", "the evening"]]),
       "At = a point, on = a day, in = a longer period.", "A table of time prepositions: at with six o'clock, noon and night; on with Monday, my birthday and Friday morning; in with May, 2024 and the evening."),
    ky("pieges", "Common mistakes",
       "- *I will meet you in Monday* → **on** Monday.\n- *She is good in English* → **good at** English.\n- *He is afraid from dogs* → **afraid of** dogs.\n- *We discussed about the problem* → **discussed the problem** (no about).\n- Do not write *because* and *so* together: *Because it rained, so we stayed home* → choose one."),
    exm("Example 1: choose the preposition", "Fill in at, on or in: *The match starts ___ Saturday ___ 3 p.m. ___ Buea.*",
        ["A day takes **on**: *on Saturday*.", "A clock time takes **at**: *at 3 p.m.*; a town takes **in**: *in Buea*."], "on Saturday at 3 p.m. in Buea"),
    exm("Example 2: join with a linking word", "Join with *so*: *The road was flooded. We took another way.*",
        ["*so* gives a **result**: the flooding is the cause.", "Put a comma before so: *The road was flooded, so we took another way.*"], "The road was flooded, so we took another way.")],
   [m("*The school bell rings ___ half past seven.*", "at", ["on", "in", "to"], "Clock time takes at."),
    m("Which sentence is correct?", "She is afraid of snakes.", ["She is afraid from snakes.", "She is afraid with snakes.", "She is afraid in snakes."], "Afraid of."),
    t("We say *on Friday* and *in May*.", True, "Days take on; months take in."),
    m("Which linking word shows a contrast?", "but", ["so", "and", "because"], "But contrasts two ideas."),
    m("Join: *It was late. We hurried.* ", "It was late, so we hurried.", ["It was late, because we hurried.", "It was late but, so we hurried.", "It was late so because we hurried."], "So shows the result."),
    o("Write a short note (4–5 sentences) telling a friend about a plan for next Saturday. Use at least three prepositions and the linking words *but* and *because*.",
      "On Saturday I will go to the farm with my uncle. We will leave at six o'clock in the morning. I want to go because I like picking oranges. I would stay longer, but I must return before dark.",
      ["1 mark: three prepositions used correctly.", "1 mark: *but* used correctly.", "1 mark: *because* used correctly.", "1 mark: clear meaning and punctuation."])],
   [sc("Which word is a preposition?", "between", ["quickly", "happy", "and"], "Between links nouns."),
    sc("*She is good ___ mathematics.*", "at", ["in", "on", "for"], "Good at."),
    sc("Which conjunction gives a reason?", "because", ["but", "or", "so"], "Because gives the reason."),
    sc("Choose the correct sentence.", "We arrived at the market in the morning.", ["We arrived in the market at the morning.", "We arrived on the market at morning.", "We arrived at the market on the morning."], "At the market; in the morning."),
    sc("*Do you want tea ___ coffee?*", "or", ["but", "so", "because"], "Or offers a choice.")])

# ===================================================================== sentences and words
s = p.chapter("ch-sentences", "Sentences, punctuation and vocabulary", REF)

LS(s, "sentences-punctuation", "Sentences and basic punctuation", 24,
   ["Recognise a complete sentence.", "Use capital letters, full stops, question marks, commas and apostrophes.", "Correct run-on sentences."],
   [tx("A **sentence** is a group of words that makes complete sense. It has a **subject** (who or what) and a **verb** (what happens). *The children sing.* is a sentence; *the children in the yard* is not, because it says nothing about what they do."),
    ky("definition", "The basic marks",
       "- **Capital letter:** first word of a sentence, names (*Ngu, Kumba*), the word *I*, days and months.\n- **Full stop (.)** ends a statement; **question mark (?)** ends a question; **exclamation mark (!)** shows strong feeling.\n- **Comma (,)** separates items in a list and follows an opening word or phrase: *We bought yams, beans, rice and oil.*\n- **Apostrophe (')** shows ownership (*Ada's bag, the girls' room*) or missing letters (*don't, it's*)."),
    fg(flow("Checking a sentence", ["Does it begin with a capital letter?", "Has it a subject and a verb?", "Does it make complete sense?", "Does it end with . ? or !"]),
       "Run through these four checks before you hand in your work.", "A flowchart with four boxes: capital letter at the start, a subject and a verb, complete sense, and an ending mark."),
    ky("pieges", "Common mistakes",
       "- **Run-on sentence:** *I went to the market I bought fish.* → *I went to the market. I bought fish.* (or join with *and*).\n- **Fragment:** *Because it was late.* needs a main clause.\n- Apostrophe in plurals: *two mango's* is wrong → *two mangoes*.\n- No comma before **and** between only two items: *rice and beans*."),
    exm("Example 1: punctuate", "Punctuate: *where is the book that nana bought on monday*",
        ["Capital letters: *Where*, *Nana*, *Monday*.", "It is a question, so end with a question mark."], "Where is the book that Nana bought on Monday?"),
    exm("Example 2: the apostrophe", "Write correctly: *the bag belonging to Ada* and *do not*.",
        ["Ownership: add 's to the owner: *Ada's bag*.", "Missing letter: *do not → don't*."], "Ada's bag; don't")],
   [m("Which is a complete sentence?", "The farmer sells cocoa.", ["The farmer in the field.", "Selling cocoa in Kumba.", "Because the farmer sells."], "It has a subject and a verb and makes sense."),
    m("Choose the correct punctuation.", "We need eggs, flour, sugar and oil.", ["We need eggs flour sugar and oil", "We need, eggs, flour, sugar, and, oil.", "We need eggs; flour; sugar and oil."], "Commas in a list, full stop at the end."),
    t("An apostrophe is used to make plurals, as in *two cat's*.", False, "Plurals take -s with no apostrophe: two cats."),
    m("*The girls room is tidy.* Where does the apostrophe go if the room belongs to several girls?", "girls'", ["girl's", "girls's", "gir'ls"], "Plural owner ending in s: add the apostrophe after the s."),
    m("Which sentence needs a question mark?", "What time does the market open", ["Please open the door", "The market opens at six", "How lovely this is"], "It asks a question."),
    o("Rewrite with correct capital letters and punctuation: *on saturday ada and i went to bamenda we bought shoes bags and a hat did you go to the market too*",
      "On Saturday Ada and I went to Bamenda. We bought shoes, bags and a hat. Did you go to the market too?",
      ["1 mark: capital letters for On, Saturday, Ada, I, Bamenda, We, Did.", "1 mark: full stops separate the sentences.", "1 mark: commas in the list.", "1 mark: question mark at the end."])],
   [sc("A sentence must have...", "a subject and a verb", ["a comma", "three words", "an exclamation mark"], "That is the minimum."),
    sc("Which word needs a capital letter?", "Wouri", ["river", "water", "bridge"], "Wouri is a proper name."),
    sc("*don't* is a short form of...", "do not", ["does not", "did not", "done not"], "The apostrophe replaces o."),
    sc("A comma is used in a sentence to...", "separate items in a list", ["end a sentence", "ask a question", "show strong feeling"], "Commas separate list items."),
    sc("*I like mangoes I like pawpaw* is a...", "run-on sentence", ["question", "list", "complete sentence"], "Two sentences run together without punctuation.")])

LS(s, "vocabulary-word-building", "Building your vocabulary", 24,
   ["Use prefixes and suffixes to build and understand words.", "Find synonyms and antonyms.", "Use a dictionary and context to learn new words."],
   [tx("A strong vocabulary makes reading easier and writing richer. You can grow it quickly by learning **word families**: many English words are made of a **root** with a **prefix** at the front or a **suffix** at the end. *happy → unhappy → unhappiness.*"),
    ky("definition", "Prefixes and suffixes",
       "- **Prefix** changes the meaning: *un-* (not: *unfair*), *dis-* (opposite: *disagree*), *re-* (again: *rewrite*), *pre-* (before: *prepare*), *mis-* (wrongly: *misunderstand*), *im-/in-* (not: *impossible, incorrect*).\n- **Suffix** often changes the word class: *-ful, -less* (*careful, careless*), *-ness, -ment, -tion* (nouns: *kindness, enjoyment, education*), *-ly* (adverbs), *-er* (a person: *teacher, farmer*)."),
    fg(tree("Word family of care", "care", [("care + ful", "careful"), ("care + less", "careless"), ("care + lessly", "carelessly")], h=185),
       "One root can give many words.", "A diagram with the root care and three arrows to careful, careless and carelessly."),
    ky("definition", "Synonyms, antonyms and context",
       "A **synonym** has nearly the same meaning (*big, large*); an **antonym** has the opposite meaning (*hot, cold*). No two synonyms are exactly alike: *thin* and *slim* are kind, *skinny* is not. If you meet an unknown word, read the **sentence around it**, guess, then check in a dictionary and note the part of speech."),
    ky("pieges", "Common mistakes",
       "- *Unpossible, imfair* → **impossible, unfair** (the prefix depends on the word).\n- Choosing a synonym that does not fit the tone: *the child was dead tired* is informal.\n- Learning a word without a sentence: always write an example with it.\n- Confusing words that sound alike: *accept / except, advice (noun) / advise (verb)*."),
    exm("Example 1: build words", "Add a prefix or suffix to make the opposite or the new word: *happy*, *agree*, *care* (without care).",
        ["*happy* + *un-* gives **unhappy** (not happy).", "*agree* + *dis-* gives **disagree**; *care* + *-less* gives **careless**."], "unhappy, disagree, careless"),
    exm("Example 2: meaning from context", "*The farmer was **jubilant** when the rain finally came and saved his maize.* What does jubilant mean?",
        ["The rain saved the maize: this is good news for the farmer.", "So *jubilant* must mean very happy and joyful."], "very happy")],
   [m("What does the prefix *re-* usually mean?", "again", ["not", "before", "wrongly"], "Rewrite means write again."),
    m("The antonym of *generous* is...", "mean", ["kind", "rich", "friendly"], "Generous gives freely; mean is the opposite."),
    t("The suffix *-less* means *without*.", True, "Careless = without care."),
    m("Which word is a synonym of *begin*?", "start", ["finish", "stop", "end"], "Begin and start mean the same."),
    mt("Match each word to its meaning.", [["unkind", "not kind"], ["rebuild", "build again"], ["misread", "read wrongly"], ["hopeless", "without hope"]], "Un-, re-, mis- and -less each add a clear meaning."),
    o("Choose three words from this list: *kind, agree, like, possible, tidy*. Add a prefix or suffix to each to make a new word, then use each new word in a sentence about school life.",
      "unkind: It is unkind to laugh at a classmate. disagree: I disagree with the idea of leaving early. impossible: It is impossible to finish all this work in ten minutes.",
      ["1 mark: three correct new words.", "1 mark: each used in a sentence.", "1 mark: sentences fit the meaning.", "1 mark: spelling and punctuation correct."])],
   [sc("The prefix in *disagree* is...", "dis-", ["agree", "-ee", "re-"], "Dis- means the opposite."),
    sc("A word with the same meaning is a...", "synonym", ["antonym", "prefix", "suffix"], "Synonym."),
    sc("*Careful* is formed by adding...", "the suffix -ful to care", ["the prefix un- to care", "the prefix re- to care", "-ly to care"], "-ful means full of."),
    sc("The opposite of *possible* is...", "impossible", ["unpossible", "dispossible", "mispossible"], "The correct opposite is impossible."),
    sc("If you meet an unknown word, a good first step is to...", "read the words around it", ["skip the whole sentence", "stop reading", "ask for the translation only"], "Context clues help you guess the meaning.")])

# ===================================================================== reading
r = p.chapter("ch-reading", "Reading comprehension", REF)

LS(r, "comprehension-first", "Reading and understanding a passage", 28,
   ["Read a short passage in three steps.", "Answer literal, vocabulary and own-words questions.", "Write answers in complete sentences with evidence from the text."],
   [tx("**Saturday at the Market**\nEvery Saturday, Mama Ngum wakes before the cock crows. She packs her tomatoes, onions and a basket of ripe pawpaw into two baskets and walks to the market in Bafoussam with her daughter Ada. The paths are busy and the air smells of roasting corn. By nine o'clock Mama Ngum has found her small stall between a fish seller and a man who repairs shoes. \"Fresh tomatoes!\" she calls. Ada counts the money carefully, because she wants to buy a new exercise book."),
    ky("methode", "Three steps for a passage",
       "1. **Skim** the passage once for the general idea (who? where? what?).\n2. **Read the questions**, then read the passage again slowly, underlining the answer.\n3. **Write** in a **full sentence**, beginning with words from the question, and keep to the number of marks.\nQuestion types: **literal** (the answer is in the text), **vocabulary** (meaning of a word in context), **own words** (explain without copying) and **inference** (read between the lines)."),
    fg(flow("Answering a comprehension question", ["Read the question carefully", "Find the lines that answer it", "Write a full sentence in your words", "Check spelling and the marks"]),
       "The same four steps work for every question.", "A flowchart: read the question, find the lines, write a full sentence in your own words, check spelling and marks."),
    ky("pieges", "Common mistakes",
       "- Copying a whole paragraph instead of the **lines needed**.\n- Answering with a single word when the question says *explain*.\n- Giving your own opinion when the question asks *according to the passage*.\n- Not using the words of the question: *Why does Ada count the money carefully?* → *Ada counts the money carefully because she wants to buy a new exercise book.*"),
    exm("Example 1: a literal question", "According to the passage, where is Mama Ngum's stall?",
        ["Find the line about the stall: *between a fish seller and a man who repairs shoes*.", "Use the words of the question in a full sentence."], "Mama Ngum's stall is between a fish seller and a man who repairs shoes."),
    exm("Example 2: a vocabulary question", "What does the word *ripe* mean in the passage? (*a basket of ripe pawpaw*)",
        ["Ask what is true of fruit ready to sell and eat.", "Ripe means fully grown and ready to eat."], "ready to be eaten")],
   [m("Where does Mama Ngum walk to every Saturday?", "the market in Bafoussam", ["a school in Buea", "a farm in Kumba", "a church in Limbe"], "The passage says she walks to the market in Bafoussam."),
    m("According to the passage, why does Ada count the money carefully?", "She wants to buy an exercise book.", ["She is afraid of thieves.", "Her mother is ill.", "She sells shoes."], "The last sentence gives the reason."),
    t("The passage says that Mama Ngum sells fish.", False, "She sells tomatoes, onions and pawpaw; the fish seller is her neighbour."),
    m("The words *wakes before the cock crows* suggest that Mama Ngum...", "starts her day very early", ["is lazy", "dislikes the market", "keeps chickens only"], "The cock crows at dawn, so she wakes up very early."),
    m("In the passage, *stall* means...", "a small table or booth where goods are sold", ["a school desk", "a type of fruit", "a sound"], "A stall is a market place for selling."),
    o("Read: *The paths are busy and the air smells of roasting corn.* In two sentences, say what this tells you about the market. Use your own words.",
      "The market is crowded because many people are using the paths. It also seems lively and pleasant, since food such as corn is being cooked and its smell fills the air.",
      ["1 mark: crowded or busy.", "1 mark: food or roasting corn mentioned.", "1 mark: lively or pleasant atmosphere (inference).", "1 mark: own words, full sentences."])],
   [sc("Skimming a passage means...", "reading quickly for the main idea", ["copying every word", "reading only the title", "reading backwards"], "Skimming gives the general idea."),
    sc("A vocabulary question asks you to...", "explain the meaning of a word in context", ["copy a paragraph", "give your opinion", "retell the whole story"], "Use the context."),
    sc("A good comprehension answer is usually...", "a full sentence using the question's words", ["a single letter", "a copy of the whole passage", "a drawing"], "Full sentences show understanding."),
    sc("An inference question asks you to...", "read between the lines", ["copy the first line", "count the words", "name the author"], "The answer is suggested, not stated."),
    sc("Before you answer, you should...", "read the question carefully", ["write at once", "close the book", "skip the passage"], "A careful reading avoids mistakes.")])

# ===================================================================== writing
w = p.chapter("ch-writing", "Writing and speaking", REF)

LS(w, "informal-letter", "Writing an informal letter", 28,
   ["Set out an informal (friendly) letter correctly.", "Plan the opening, body and closing.", "Use a friendly but correct style."],
   [tx("An **informal letter** is written to a friend or relative. The tone is warm and natural, but the English must still be correct. Examiners look at **layout**, **content** and **language**."),
    ky("definition", "The layout",
       "1. **Your address** (top right), without your name.\n2. **The date** under it: *12 March 2026*.\n3. **Greeting** at the left: *Dear Ndi,* (comma).\n4. **Body**: short paragraphs.\n5. **Closing** at the bottom right: *Your friend, / Yours lovingly,* then your **first name**.\nNo need for the receiver's address in an informal letter."),
    fg(shapes([RECT(20, 20, 380, 240, stroke="grey", width=2), T(300, 44, "P.O. Box 12, Buea", 13), T(300, 62, "12 March 2026", 13),
               T(32, 92, "Dear Ndi,", 13, anchor="start"), T(210, 140, "Opening, news, question, closing remark", 13),
               T(210, 160, "(2 or 3 short paragraphs)", 13), T(300, 218, "Your friend,", 13), T(300, 240, "Ada", 13, bold=True)], 420, 275),
       "The layout of an informal letter.", "A sketch of a letter: address and date at top right, Dear Ndi at the left, body paragraphs in the middle, Your friend and the name at the bottom right."),
    ky("methode", "Plan the content",
       "- **Opening:** thank your friend for the letter, ask how he or she is, give the reason for writing.\n- **Body:** give the news or answer the instruction point by point, one paragraph for each point.\n- **Closing:** send greetings to the family, say when you hope to hear back.\nUse contractions (*I'm, we've*) sparingly; avoid slang and text-message spelling."),
    ky("pieges", "Common mistakes",
       "- Writing the receiver's address or *Sir/Madam* (that is a formal letter).\n- Forgetting the date or putting your full name in the address.\n- Closing with *Yours faithfully* (formal only).\n- One long paragraph with no news in order.\n- Mixing tenses and errors from SMS language (*u, 2day*)."),
    exm("Example 1: the opening", "You are Ada. Write the opening paragraph of a letter to your friend Ndi who lives in Garoua. You want to tell her about your school trip.",
        ["Greet and thank: *Dear Ndi, Thank you for your last letter...*", "Give the reason for writing: *I am writing to tell you about our school trip to Limbe.*"], "Dear Ndi, Thank you for your last letter. I hope you and your family are well. I am writing to tell you about our school trip to Limbe."),
    exm("Example 2: the closing", "Write a suitable closing for a letter to a friend, from a girl called Ada.",
        ["Add greetings and a hope: *Please greet your parents. Write soon.*", "Close with *Your friend,* and her first name on a new line."], "Please greet your parents and write soon. Your friend, Ada")],
   [m("Which greeting suits an informal letter?", "Dear Ndi,", ["Dear Sir,", "To whom it may concern,", "Respected Principal,"], "A friend is greeted by name."),
    m("Where does the date go in an informal letter?", "under your address, at the top right", ["at the bottom left", "after the closing", "in the middle"], "Address then date, top right."),
    t("An informal letter needs the receiver's full address.", False, "Only your own address is written in a friendly letter."),
    m("Which closing is suitable?", "Your friend,", ["Yours faithfully,", "Yours truly, Sir,", "Respectfully yours,"], "Your friend is informal."),
    m("Which opening sentence is best for a letter to a friend?", "Thank you for your last letter; I hope you are well.", ["I write in respect of your letter.", "Hey u! Wassup?", "Sir, I am writing to apply."], "Warm but correct."),
    o("Write a letter of about 120 words to a friend in another town, describing your last weekend. Set it out correctly: address, date, greeting, two paragraphs, closing.",
      "P.O. Box 45, Bamenda\n3 May 2026\nDear Fon,\nThank you for your letter. I hope you are well. Last weekend I went to my grandmother's village near Bafut. We harvested maize and cooked fufu corn with njama njama. In the evening my cousins told us stories by the fire.\nOn Sunday we returned to town. I was tired but happy. Please write and tell me about your football match. Greet your parents for me.\nYour friend,\nTabi",
      ["2 marks: layout (address, date, greeting, closing, first name).", "2 marks: content (opening, news about the weekend, closing remark).", "2 marks: language (tenses, spelling, punctuation).", "1 mark: friendly but correct tone."])],
   [sc("Which closing is for an informal letter?", "Yours lovingly,", ["Yours faithfully,", "Yours obediently,", "Your humble servant,"], "Yours lovingly is for family or close friends."),
    sc("In an informal letter the greeting is followed by...", "a comma", ["a full stop", "a colon and dash", "nothing"], "Dear Ndi, with a comma."),
    sc("An informal letter has how many addresses?", "one (the sender's)", ["two", "none", "three"], "Only the writer's address."),
    sc("The best tone for a letter to a friend is...", "warm and natural but correct", ["very formal", "rude", "full of text-message spelling"], "Natural but correct."),
    sc("The reason for writing is usually given...", "in the opening paragraph", ["after the closing", "in the date", "nowhere"], "The reader should know why you are writing.")])

LS(w, "descriptive-paragraph", "Writing a descriptive paragraph", 26,
   ["Plan a paragraph with a topic sentence.", "Use the five senses and precise adjectives.", "Organise details in a clear order."],
   [tx("A **paragraph** deals with one idea. A **descriptive paragraph** helps the reader to see, hear, smell, taste and feel a person, place or thing. Instead of saying *the market is nice*, show *why*."),
    ky("definition", "Parts of a paragraph",
       "- **Topic sentence:** states the main idea (*Our village market is the liveliest place I know.*).\n- **Supporting sentences:** give details, examples and senses.\n- **Concluding sentence:** closes the idea or gives a feeling.\nOrder details in a plan: **near to far**, **left to right**, **morning to evening**."),
    fg(cols("The five senses", ["Sense", "Detail"], [["sight", "red tomatoes in heaps"], ["sound", "sellers shouting prices"], ["smell", "roasting corn"], ["taste", "sweet ripe mango"], ["touch", "rough sacks"]], w=430),
       "Use at least three senses.", "A table listing the five senses with an example detail for each: sight, sound, smell, taste and touch."),
    ky("methode", "Making descriptions vivid",
       "- Use **precise nouns and adjectives**: *a glittering tin roof*, not *a nice roof*.\n- Use **comparisons**: *the dust rose like smoke*.\n- Choose **strong verbs**: *stroll, hurry, drag* instead of *go*.\n- Keep **one tense** (usually the present or the past)."),
    ky("pieges", "Common mistakes",
       "- Listing too many ideas in one paragraph.\n- Using vague words (*nice, good, beautiful, things*).\n- Repeating *and then... and then...*.\n- Writing a story (events) instead of a **picture** of the place.\n- Forgetting the topic sentence."),
    exm("Example 1: a topic sentence", "Write a topic sentence for a paragraph describing your school compound at break time.",
        ["Name the place and a strong impression.", "*At break time our school compound turns into a noisy, colourful playground.*"], "At break time our school compound turns into a noisy, colourful playground."),
    exm("Example 2: improve a sentence", "Improve: *The kitchen is nice.* Use two senses.",
        ["Replace *nice* with a precise picture (smell and sight).", "*The warm kitchen smells of fried plantain, and the blackened pot glows on the fire.*"], "The warm kitchen smells of fried plantain, and the blackened pot glows on the fire.")],
   [m("The sentence that states the main idea of a paragraph is the...", "topic sentence", ["title", "last word", "caption"], "It introduces the main idea."),
    m("Which phrase is the most descriptive?", "a glittering tin roof", ["a nice roof", "a good roof", "a roof thing"], "It is precise and visual."),
    t("A descriptive paragraph should use only one sense.", False, "Using several senses makes it richer."),
    m("Which verb is the strongest choice for a tired child walking home?", "dragged", ["went", "did", "was"], "It shows how he walked."),
    m("A paragraph usually has...", "one main idea", ["five unrelated ideas", "no sentences", "only questions"], "One idea per paragraph."),
    o("Write a descriptive paragraph (6–8 sentences) about a place you know well in your town or village: a market, a river, a football field or a kitchen. Begin with a topic sentence and use at least three senses.",
      "Our river is the coolest place in the village on a hot afternoon. The water is clear and slides over smooth stones. Women sing as they wash clothes and the sound mixes with the shouts of swimming children. The air smells of wet soil and soap. Over my head the palm leaves rattle softly in the wind. At sunset the water turns golden. I always leave the river clean, calm and happy.",
      ["2 marks: topic sentence and a clear plan.", "2 marks: at least three senses and precise words.", "2 marks: correct grammar, spelling and punctuation.", "1 mark: concluding sentence."])],
   [sc("A topic sentence...", "states the main idea of the paragraph", ["ends the letter", "asks a question", "lists the senses"], "It sets up the paragraph."),
    sc("Which is a sense detail of smell?", "roasting corn", ["a red door", "a loud drum", "a rough sack"], "Roasting corn has a smell."),
    sc("Which word is vague?", "nice", ["glittering", "drizzling", "crowded"], "Nice says little."),
    sc("A good order for a description is...", "near to far", ["random order", "alphabetical order", "reverse order of the words"], "A clear order helps the reader."),
    sc("A descriptive paragraph mainly...", "paints a picture in words", ["tells a long story", "asks the reader to vote", "lists rules"], "It describes.")])

LS(w, "oral-english-basics", "Oral English: clear sounds and polite speech", 24,
   ["Pronounce short and long vowel sounds in common word pairs.", "Place stress on the right syllable in common words.", "Use polite greetings, introductions and requests."],
   [tx("Oral English means speaking and listening. Clear pronunciation and polite expressions help people to understand you. In class and in the exam you may be asked to tell sounds apart or to find the stressed syllable of a word. English spelling is not a safe guide to sound, so listen and practise aloud."),
    ky("definition", "Vowel sounds: short and long",
       "Many pairs differ only by length:\n- **ship** (short) / **sheep** (long)\n- **bit** / **beat**\n- **full** / **fool**\n- **pull** / **pool**\nThe long vowel is held longer. Practise pairs aloud and record yourself on a phone. Words are in the same *sound family* when their vowel sound is the same even if the spelling differs: *meet, meat, field*."),
    fg(cols("Short and long vowels", ["Short", "Long"], [["ship", "sheep"], ["bit", "beat"], ["full", "fool"], ["pull", "pool"]], w=420),
       "Say each pair aloud and feel the length change.", "A table with short vowel words on the left, ship, bit, full and pull, and long vowel words on the right, sheep, beat, fool and pool."),
    ky("definition", "Word stress and polite English",
       "In words of two or more syllables **one syllable is stressed** (said louder, longer). *TEAcher, beGIN, PHOtograph, phoTOgrapher.* Stress is shown in capitals. **Politeness:** greet (*Good morning, Madam*), introduce (*Let me introduce my friend Tabi*), ask (*Could you help me, please?*) and thank (*Thank you very much*). Use *please* and a rising voice for requests."),
    ky("pieges", "Common mistakes",
       "- Saying every syllable with equal strength: stress makes English rhythm.\n- Treating spelling as a guide: *been* (bin), *bomb* (the b is silent), *one* (wun).\n- Giving orders (*Give me water!*) instead of polite requests (*May I have some water, please?*).\n- Speaking too fast: clear and slow is better than quick and unclear."),
    exm("Example 1: find the stress", "Mark the stressed syllable of *teacher*, *begin* and *banana*.",
        ["Two-syllable nouns are usually stressed on the **first** syllable: **TEA**-cher.", "*begin* is stressed on the second: be-**GIN**; *banana* on the second: ba-**NA**-na."], "TEAcher, beGIN, baNAna"),
    exm("Example 2: polite request", "Make the request polite: *Give me your pen.*",
        ["Use a modal verb and *please*.", "*Could you lend me your pen, please?*"], "Could you lend me your pen, please?")],
   [m("Which word has a long vowel sound?", "sheep", ["ship", "bit", "full"], "Sheep has the long ee sound."),
    m("Which pair has the SAME vowel sound?", "meet / meat", ["ship / sheep", "full / fool", "pull / pool"], "Meet and meat have the same long ee sound."),
    t("In *teacher*, the stress is on the first syllable.", True, "TEA-cher."),
    m("Which is the most polite request?", "Could you help me, please?", ["Help me!", "You must help me.", "Help me now."], "Modal verb plus please."),
    m("In *begin*, the stress falls on...", "the second syllable", ["the first syllable", "both equally", "neither"], "be-GIN."),
    o("You meet your new teacher for the first time and want to introduce your friend Ngu to her. Write, as a short dialogue, how you would greet her, introduce Ngu, and politely ask her a question about the school clubs.",
      "Me: Good morning, Madam. Teacher: Good morning. Me: Madam, let me introduce my friend Ngu. He is also in Form 1. Teacher: Nice to meet you, Ngu. Ngu: Nice to meet you too, Madam. Me: Excuse me, Madam, could you tell us about the school clubs, please?",
      ["1 mark: a polite greeting with a title.", "1 mark: a correct introduction.", "1 mark: a polite question with please or could.", "1 mark: correct grammar and punctuation."])],
   [sc("A stressed syllable is said...", "louder and longer", ["more softly", "silently", "backwards"], "That is what stress means."),
    sc("Which word pair differs by vowel length?", "bit / beat", ["cat / mat", "big / pig", "net / not"], "Bit has a short vowel; beat a long one."),
    sc("A polite way to ask for a pen is...", "Could you lend me a pen, please?", ["Give me a pen!", "I want your pen.", "Pen!"], "Polite request with could and please."),
    sc("The silent letter in *knife* is...", "k", ["n", "f", "i"], "The k is not pronounced."),
    sc("A good greeting for a teacher in the morning is...", "Good morning, Madam", ["Hey you", "What's up?", "Bye"], "Polite greeting with a title.")])

p.write()
