import sys, math
sys.path.insert(0, "/home/user/CastBridge/tools/learn-authoring/anglophone")
from fg_kit import *

p = mk_pack("form2-citizenship", "Citizenship Education — Form 2", "Form 2", "Citizenship", "citizenship",
    "Second-year Citizenship Education: local government and traditional authorities, nationality and identity documents, democracy in school, unity, diversity and bilingualism, the environment, and road safety.",
    "Cameroon anglophone secondary Citizenship Education syllabus, Form 2 — to be checked against the official text", CIT_NOTE)

def octagon(cx, cy, r):
    pts = []
    for i in range(8):
        a = math.pi / 8 + i * math.pi / 4
        pts += [round(cx + r * math.cos(a), 1), round(cy + r * math.sin(a), 1)]
    return pts

# ------------------------------------------------------------ CH1 local government
c = p.chapter("local", "Local government and identity")
L = LS(c, "local-government", "Local government and traditional authorities",
    ["Define local government and traditional authority", "Name the main services of a council", "Explain how citizens take part in local affairs", "Explain how councils are funded"],
    [("text", "A country is governed at several levels: the **national** government, **regional** bodies and **local** government. In Cameroon, **local government** is carried out by **councils** (communes) led by a **mayor** and councillors elected by the people of the area. The councils look after local needs and are closest to the citizens. Besides these elected bodies there are **traditional authorities** such as chiefs, Fons and Lamibe."),
     ("key", "retenir", "Services of a council", "Councils help to provide and maintain **local roads**, **markets**, **water points**, **street lighting**, **waste collection**, **primary school buildings** and **health centres**, and keep **civil registers** such as birth, marriage and death records. They also issue some local permits and promote local development, working with the central government under the laws on decentralisation."),
     ("key", "retenir", "Traditional authorities", "Chiefs and Fons lead communities according to **customs and traditions**, settle small disputes, keep order, represent the community and help to preserve culture. They work with the administration and councils. They must respect the law and the rights of citizens. Traditional rulers are important for community development and unity."),
     ("text", "**Taking part.** Citizens take part in local affairs by voting in council elections, attending community meetings, paying taxes and local levies, joining development associations and common initiative groups, reporting problems (such as broken water taps), and helping with communal work. Councils get their **funds** from local taxes and fees, shares of central taxes, and grants for projects. Money must be used for the public good: citizens are entitled to ask how it is used."),
     ("key", "attention", "Be careful", "- Traditional authorities and elected councils are different institutions; each has its own role.\n- A mayor is elected locally; a chief is chosen under local custom.\n- Local services need money: avoid damaging them, and support payment of taxes.")],
    [("Example 1: who does what?", "A village needs a new water point. Which local body would you ask, and what could the villagers contribute?", ["The council is responsible for many local water points.", "The villagers can help with labour and small contributions.", "Dialogue with the chief and the council helps."], "The council (with the chief); villagers give labour and contributions."),
     ("Example 2: birth certificate", "Which local office registers births?", ["Civil status registers are kept by councils.", "Parents should declare births there.", "So the council civil status office."], "The council's civil status office.")],
    F(stack("Levels of government", ["National government", "Regions and divisions", "Councils (communes) and mayors", "Villages, chiefs and community groups"], w=440), "From national to local", "Four layers from the national government to villages and community groups."),
    [MCQ("In Form 2 citizenship, a council is led by", "a mayor", ["a prefect only", "a principal", "a teacher"], "Mayors lead councils."),
     TF("Traditional authorities help to preserve culture and settle small disputes.", True, "They have an important community role."),
     MATCH("Match each local body with its role.", [("Council", "Provides local services"), ("Chief or Fon", "Leads according to custom"), ("Development association", "Community self-help projects")], "Local actors."),
     MCQ("Which is a source of council funds?", "local taxes and fees", ["lottery of the school", "gifts from enemies only", "fines on nobody"], "Councils depend on taxes.", tier="approfondissement"),
     OPEN("Explain two ways citizens can take part in local government.", "By voting in council elections, attending community meetings, paying taxes and levies, joining development associations, reporting problems, and joining communal work.", "1 mark per way with an example.", points=3, tier="approfondissement"),
     PROB("The market of a small town is dirty and the road to it is full of holes.",
          [("mcq", "Which institution is most responsible for the market and local roads?", "the council", ["the national football team", "a private bank", "a foreign embassy"], "Councils maintain markets and local roads.", {}),
           ("tf", "Citizens may ask the council how its money is spent.", True, "Public money is for the public good.", {}),
           ("mcq", "What should the traders do?", "dialogue with the council and help keep the market clean", ["burn the market", "stop paying all fees", "block the road"], "Cooperation is best.", {}),
           ("open", "Give two things the council can do to improve the market.", "Repair roads, install drains and lighting, organise waste collection, build stalls and toilets.", "1 mark per action.", {})])],
    [("The head of a council is the", "mayor", ["pharaoh", "chancellor", "inspector"], "Mayors lead councils."),
     ("Councils keep registers of", "births, marriages and deaths", ["rainfall", "football scores", "prices of cars"], "Civil status registers."),
     ("A traditional ruler in the North-West is called a", "Fon", ["Mansa", "mayor", "senator"], "Fon is the usual term."),
     ("A local development group is an example of", "citizen participation", ["a crime", "a tax", "an army"], "People help to improve the area."),
     ("Decentralisation means", "giving more responsibility to local authorities", ["removing all councils", "centralising all power", "stopping elections"], "It aims to bring government closer to the people.")],
    ["Teacher to verify: titles (mayor, council, commune), the services of councils and the status of traditional authorities under current law; the decentralisation description is general."], tag="Form 2 citizenship local government")

L = LS(c, "nationality-identity", "Nationality, identity and identity documents",
    ["Define nationality and citizenship", "Explain how nationality is acquired in general terms", "Describe important identity documents and their uses", "Explain the duty to declare births and protect documents"],
    [("text", "**Nationality** is the legal link between a person and a state. A person who has the nationality of a country is a **citizen** with rights and duties. Nationality is normally acquired **by birth to a citizen parent**, in some cases **by birth in the country**, by **marriage**, or by **naturalisation** (a legal process for foreigners who fulfil conditions). The exact rules are set by the **nationality law** of each country."),
     ("key", "retenir", "Identity documents", "- **Birth certificate**: proves name, date and place of birth and parentage; needed for school, exams and later documents.\n- **National identity card**: proves identity and nationality of an adult.\n- **Passport**: for travel abroad.\n- **School ID card**: shows a pupil's school.\n- Other documents: marriage certificate, driving licence and voter's card."),
     ("text", "**Why a birth certificate matters.** A child without a birth certificate may find it hard to be registered for national exams, to obtain an identity card or a passport, and to prove nationality. Parents have a **duty to declare births** to the civil status authorities soon after birth. **Late registration** is possible but more complicated. Children have a **right to a name and nationality**."),
     ("key", "attention", "Be careful", "- Keep documents safe and never lend them or sell them: identity theft and fraud are crimes.\n- Never use false documents: forgery is a serious offence.\n- Lost documents must be reported and replaced through the proper authorities."),
     ("key", "pieges", "Common mistakes", "- Nationality is not the same as ethnic group or religion.\n- A citizen is not only someone who votes: children are citizens too.\n- Rules on acquiring nationality differ by country; do not assume the rules of another country apply here.")],
    [("Example 1: which document?", "A pupil needs to prove her date of birth to register for an exam. Which document is most useful?", ["Date of birth is recorded at birth.", "The birth certificate shows it.", "So the birth certificate."], "The birth certificate."),
     ("Example 2: lost document", "A man loses his identity card. What should he do?", ["He should report the loss to the police.", "He should apply for a replacement.", "He should not let others use it."], "Report the loss and apply for a replacement.")],
    F(cols("Identity documents", [("Child", ["Birth certificate", "School ID"]), ("Adult", ["Identity card", "Passport", "Voter's card"])], w=420), "Common documents", "Two columns of documents for a child and an adult."),
    [MCQ("In Form 2 citizenship, the legal link between a person and a state is", "nationality", ["ethnicity", "religion", "age"], "Nationality is legal."),
     TF("A birth certificate helps a child to prove name and parentage.", True, "It is basic evidence."),
     MATCH("Match each document with its use.", [("Passport", "Travel abroad"), ("Birth certificate", "Proves date and place of birth"), ("Voter's card", "Taking part in elections")], "Documents and uses."),
     MCQ("Which is an offence?", "using a forged identity document", ["reporting a lost card", "keeping a copy safe", "declaring a birth"], "Forgery is a crime.", tier="approfondissement"),
     OPEN("Explain why parents should declare the birth of a child promptly.", "A birth certificate proves the child's identity, age, parents and nationality; it is needed for school, exams, an identity card and a passport; it protects the child's right to a name and nationality.", "1 mark per reason, up to 3.", points=3, tier="approfondissement"),
     PROB("A pupil has no birth certificate and wants to sit a public exam.",
          [("mcq", "What is the first step?", "ask parents or guardians to apply through the civil status office", ["use a friend's certificate", "forge a paper", "ignore the exam"], "Use the legal procedure.", {}),
           ("tf", "A late registration may need extra steps and time.", True, "Early declaration is easier.", {}),
           ("mcq", "Who is responsible for declaring a child's birth?", "parents or guardians", ["the neighbour only", "the football club", "the bank"], "It is the family's duty.", {}),
           ("open", "Give two risks of having false documents.", "Legal punishment, loss of the right to exams and jobs, risk of being used for fraud, and loss of trust.", "1 mark per risk.", {})])],
    [("A birth certificate proves", "identity and parentage", ["wealth", "religion only", "football skill"], "It records birth details."),
     ("Naturalisation is", "a legal process for foreigners to obtain nationality", ["a type of school", "a sport", "a form of tax"], "It follows conditions in law."),
     ("A passport is needed for", "international travel", ["local school", "market visits", "voting in class"], "It is a travel document."),
     ("A citizen is", "a member of a state with rights and duties", ["a foreign visitor only", "someone without rights", "a ruler only"], "That is the definition."),
     ("The duty to declare births belongs to", "parents or guardians", ["strangers", "shopkeepers", "only the president"], "They must register the child.")],
    ["Teacher to verify the nationality law, the current identity documents, ages and procedures (late registration, identity card issuance); the lesson is deliberately general and avoids specific legal details."], tag="Form 2 citizenship nationality")

# ------------------------------------------------------------ CH2 democracy and unity
c = p.chapter("democracy-unity", "Democracy and unity")
L = LS(c, "school-democracy", "Democracy in school and in the classroom",
    ["Define democracy and its basic principles", "Describe how class and school elections work", "Explain majority rule and respect for minorities", "Explain the role of student councils"],
    [("text", "**Democracy** means 'rule by the people'. Its key principles are **equality** of all citizens, **freedom** to speak and take part, **free and fair elections**, **majority rule** with **respect for minorities**, and the **rule of law**. We learn democracy first in small groups: class, school clubs and student councils."),
     ("key", "methode", "A class election", "1. **Call for candidates**: pupils who want to be class prefect put forward their names.\n2. **Campaign**: candidates explain their plans politely and fairly.\n3. **Secret ballot**: each pupil votes once on a slip of paper.\n4. **Count** in public with witnesses.\n5. **Announce** the winner, who gets the most votes, and the loser accepts the result."),
     ("text", "**Majority rule** means that the option with most votes wins. But a democracy must also **protect minorities**: the winners should listen to those who lost and not treat them unfairly. After an election all should work together. In a **student council** pupils elect representatives who bring pupils' ideas to the school authorities; the council helps with discipline, activities and community projects."),
     ("key", "retenir", "Good democratic habits", "Listen to different opinions, speak in turn, disagree without insulting, accept the result of a fair vote, respect the rules, and take responsibility. Cheating in elections, buying votes, threatening voters or refusing to accept a fair result is **undemocratic**."),
     ("key", "pieges", "Common mistakes", "- Democracy is not only voting: it also needs freedom to speak and respect for others.\n- A secret ballot protects voters: do not force anyone to say how they voted.\n- The majority cannot decide to take away the rights of the minority.")],
    [("Example 1: counting", "In a class of 40 pupils, candidate A gets 18 votes, B gets 14 and C gets 8. Who wins, and does the winner have more than half of the votes?", ["Add: 18 + 14 + 8 = 40.", "A has the most votes: 18.", "Half of 40 is 20; 18 is less than 20, so A wins with a plurality, not a majority of all."], "A wins with the most votes (18), but not more than half."),
     ("Example 2: respect for the loser", "After the election, candidate B is upset. What should the winner do?", ["The winner should be gracious and respectful.", "Invite B to help in the class committee.", "This builds unity."], "Be respectful and involve B in the work.")],
    F(flow("Class election", ["Candidates|stand", "Campaign|politely", "Secret|ballot", "Count and|announce"], per_row=4), "Steps of a class election", "Four boxes showing candidates, campaign, secret ballot and count."),
    [MCQ("In Form 2 citizenship, 'democracy' means", "rule by the people", ["rule by one person", "rule by soldiers", "no rules"], "It comes from Greek words for people and power."),
     TF("In a secret ballot nobody should be forced to say how they voted.", True, "Secrecy protects free choice."),
     MATCH("Match each term with its meaning.", [("Candidate", "Person who stands for election"), ("Ballot", "Vote cast in secret"), ("Minority", "Group with fewer votes or members")], "Election vocabulary."),
     NUM("In a class of 36 pupils, a candidate wins 19 votes. How many more votes than half of the class is that?", 1, "Half of 36 is 18; 19 − 18 = 1.", unit="votes", tier="approfondissement"),
     OPEN("Explain why a democracy must protect the rights of minorities.", "The majority could otherwise take away the rights of smaller groups; protecting minorities gives equality, avoids injustice and conflict, and lets different ideas be heard.", "1 mark per point, up to 3.", points=3, tier="approfondissement"),
     PROB("A school holds elections for the head prefect. Candidates: X, Y and Z. Total pupils voting: 100. X gets 45 votes, Y 35 and Z 20.",
          [("num", "How many votes did Y and Z receive together?", 55, "35 + 20 = 55.", 0, "votes", {}),
           ("mcq", "Who has the most votes?", "X", ["Y", "Z", "All the same"], "45 is the largest.", {}),
           ("tf", "X has more than half of all votes cast.", False, "Half of 100 is 50; X has 45.", {}),
           ("open", "Suggest two ways to make the election fair.", "Use a secret ballot, count in public with witnesses, give every candidate equal time to speak, and forbid bribery and threats.", "1 mark per way.", {})])],
    [("A secret ballot means", "voters choose privately", ["voters shout their choices", "the winner is chosen by the teacher", "no one votes"], "Privacy protects freedom."),
     ("A person who stands for election is a", "candidate", ["monitor only", "senator", "referee"], "Candidates seek votes."),
     ("Majority rule means", "the option with the most support wins", ["the teacher always wins", "everyone must agree", "the loser decides"], "It is the democratic method."),
     ("A student council represents", "pupils' ideas and needs", ["parents only", "teachers' salaries", "the police"], "It speaks for pupils."),
     ("An undemocratic act in elections is", "buying votes", ["voting in secret", "counting in public", "accepting a fair result"], "Vote-buying is illegal and unfair.")],
    ["Teacher to adapt voting procedures to the school's own rules for student leadership; no real elections or parties are discussed."], tag="Form 2 citizenship school democracy")

L = LS(c, "unity-diversity", "Unity in diversity and bilingualism",
    ["Describe the diversity of Cameroon", "Explain the meaning and benefits of national unity", "Explain bilingualism and its importance", "Describe attitudes that harm unity and ways to promote it"],
    [("text", "Cameroon has a very **diverse** population: more than two hundred languages are spoken, and the people practise different religions and belong to many ethnic groups and cultures. There are many traditional foods, dances, dress styles and festivals. This diversity is a **richness** of the nation. **National unity** means that all citizens, in spite of differences, feel they belong to one country and work together for its progress."),
     ("key", "retenir", "Official languages", "Cameroon has **two official languages**, **English** and **French**, which have equal status. **Bilingualism** is the ability to use two languages. It helps communication across regions, access to education and jobs, trade and relations with the world, and supports national unity. The government and schools promote bilingual education and the use of both languages."),
     ("key", "retenir", "Promoting unity", "Learn about other regions and languages; take part in national events and school exchanges; respect and greet people from other regions; marry, trade and work across regions; avoid insulting jokes about other groups; support sports teams and symbols that bring Cameroonians together; and speak out peacefully against discrimination."),
     ("text", "Attitudes that harm unity include **tribalism** (favouring one's own group unfairly), **discrimination**, **hate speech**, **stereotypes** (unfair general ideas about groups), rumours and violence. Many people in Cameroon also speak local languages, Pidgin English, or other languages in addition to English or French; these languages are part of the national heritage."),
     ("key", "attention", "Be careful", "- Diversity is not a cause of conflict by itself: conflict comes from injustice and intolerance.\n- Respecting my language does not mean looking down on others.\n- Do not repeat stereotypes about regions or ethnic groups; judge people by their actions.")],
    [("Example 1: benefits of bilingualism", "Give two benefits of being able to speak both English and French in Cameroon.", ["You can talk to more Cameroonians.", "You have more opportunities for study and work.", "So communication and opportunities."], "Wider communication and more opportunities."),
     ("Example 2: unity", "Give two actions that help to build unity at school.", ["Welcome pupils from other regions.", "Take part in cultural days to share each other's foods and dances.", "Reject insulting jokes about other groups."], "Welcome pupils from other regions; join cultural days.")],
    F(cols("Unity in diversity", [("Diversity", ["Languages", "Cultures", "Religions"]), ("Unity", ["One nation", "Shared symbols", "Two languages"])], w=420), "Differences and common ground", "Two columns showing diversity and unity."),
    [MCQ("In Form 2 citizenship, Cameroon's two official languages are", "English and French", ["Duala and Bamum", "Hausa and Arabic", "German and Latin"], "Both have equal status."),
     TF("Tribalism means unfairly favouring people of one's own ethnic group.", True, "It damages unity."),
     MATCH("Match each term with its meaning.", [("Bilingualism", "Ability to use two languages"), ("Stereotype", "Unfair general idea about a group"), ("Diversity", "Variety of people and cultures")], "Key terms."),
     MCQ("Which action helps national unity?", "learning about other regions and languages", ["insulting other groups", "refusing to talk to others", "spreading rumours"], "Learning builds understanding.", tier="approfondissement"),
     OPEN("Explain three benefits of bilingualism for Cameroon.", "It helps communication between regions; it opens education and jobs in both language areas; it supports national unity and international contacts, trade and diplomacy.", "1 mark per benefit.", points=3, tier="approfondissement"),
     PROB("A new pupil from another region joins your class and speaks with a different accent.",
          [("mcq", "The best way to welcome the pupil is to", "include them and learn about their region", ["mock the accent", "avoid them", "give them a nickname about their tribe"], "Inclusion builds unity.", {}),
           ("tf", "Making fun of someone's accent is respectful.", False, "It can hurt and divide.", {}),
           ("mcq", "Which attitude harms unity?", "tribalism", ["tolerance", "respect", "friendship"], "Tribalism favours one group.", {}),
           ("open", "Give two things a school can do to promote unity.", "Hold cultural days, mix pupils from different regions in teams, teach both official languages, and discipline discrimination and hate speech.", "1 mark per thing.", {})])],
    [("National unity means", "all citizens feel part of one nation", ["everyone is the same", "only one language is allowed", "no differences exist"], "It means belonging together despite differences."),
     ("Pidgin English is", "widely spoken in parts of Cameroon", ["only used in Germany", "an extinct language", "banned by all schools"], "It is a common language of communication in several regions."),
     ("Discrimination means", "treating people unfairly because of who they are", ["treating everyone fairly", "helping others", "sharing"], "It is unjust."),
     ("Cultural days at school help to", "share and respect different cultures", ["close the school", "insult others", "stop lessons for ever"], "They build understanding."),
     ("A stereotype is", "an unfair fixed idea about a group", ["a true scientific fact", "a school rule", "a type of food"], "Stereotypes should be challenged.")],
    ["Teacher to verify: the number of languages ('more than two hundred' is an approximate figure), the status of English and French, and the role of Pidgin English in the syllabus; the tone must remain respectful and non-political."], tag="Form 2 citizenship unity")

# ------------------------------------------------------------ CH3 environment & road
c = p.chapter("responsibility", "Environment and road safety")
L = LS(c, "environment-community", "Protecting the environment in our community",
    ["Define environment and name its parts", "Describe local environmental problems", "Explain why we must protect the environment", "Describe what pupils and communities can do"],
    [("text", "The **environment** is everything around us: air, water, soil, plants, animals, buildings and people. We depend on it for food, water, air, shelter, medicine and income. Environmental problems in many Cameroonian communities include **waste and plastic litter**, **blocked drains and floods**, **polluted streams and wells**, **cutting of trees**, **bush burning**, **soil erosion** and **noise and smoke** from vehicles and burning."),
     ("key", "retenir", "Causes and effects", "- **Waste dumped in streets**: blocks drains, causes floods, breeds flies and mosquitoes and spreads disease.\n- **Cutting trees** without replanting: erosion, loss of shade, less rain and loss of animal homes.\n- **Bush burning**: destroys soil life, causes smoke and can burn farms and houses.\n- **Polluted water**: causes diarrhoea, typhoid and other diseases."),
     ("key", "retenir", "What we can do", "Put waste in bins or approved dumps; **reduce, reuse and recycle** (reuse bottles and bags, avoid single-use plastic); plant and care for trees; keep drains clear; protect streams; avoid bush burning; use water carefully; and join clean-up days, school clubs and tree-planting campaigns. Councils should collect waste and enforce rules, and everyone should obey them."),
     ("text", "Why protect the environment? It keeps people **healthy**, protects **farms and food supply**, preserves **wildlife** and beauty, and ensures that **future generations** will have resources. Protecting the environment is both a **right** (to a healthy environment) and a **duty** of every citizen. Small daily acts, repeated by many people, make a great difference."),
     ("key", "pieges", "Common mistakes", "- Burning rubbish is not a good solution: it pollutes the air and may release toxic fumes.\n- Planting a tree is good, but trees must also be watered and protected.\n- Environmental protection is not only the government's job: it is the duty of everybody.")],
    [("Example 1: cause and effect", "Rubbish is thrown into a roadside drain in Douala. What may happen in the rainy season?", ["Rubbish blocks the drain.", "Rain water cannot flow away.", "Floods may result and breed disease."], "The drain blocks and flooding may follow."),
     ("Example 2: reduce, reuse, recycle", "Give an example of each: reduce, reuse, recycle.", ["Reduce: use fewer plastic bags.", "Reuse: refill a bottle with water.", "Recycle: give plastic to a collection point."], "Fewer bags; refill bottles; collect for recycling.")],
    F(flow("Reduce, reuse, recycle", ["Reduce|waste", "Reuse|items", "Recycle|materials", "Cleaner|community"], per_row=4), "The three Rs", "Four boxes showing reduce, reuse, recycle and a cleaner community."),
    [MCQ("In Form 2 citizenship, one effect of throwing rubbish in drains is", "flooding", ["more rain", "faster growth of trees", "better health"], "Blocked drains cause floods."),
     TF("Protecting the environment is a duty of every citizen.", True, "Everyone must take part."),
     MATCH("Match each problem with a solution.", [("Plastic litter", "Reduce use and collect for recycling"), ("Bush burning", "Use other methods of clearing land"), ("Tree cutting", "Replant and protect trees")], "Problems and solutions."),
     MCQ("Which is the best way to deal with household waste?", "put it in bins or approved dumps", ["burn it near the house", "throw it in the river", "leave it in the street"], "Safe disposal protects health.", tier="approfondissement"),
     OPEN("Describe a school project to improve the environment and explain its steps.", "Plant trees: choose a site and suitable trees, get permission and tools, plant and label them, water and protect them, and assign pupils to look after them each week.", "1 mark for aim; 1 for steps; 1 for follow-up.", points=3, tier="approfondissement"),
     PROB("A stream near a village is dirty because people wash clothes and dump waste in it.",
          [("mcq", "A likely effect on villagers is", "water-borne diseases", ["better crops", "colder weather", "more fish always"], "Dirty water spreads disease.", {}),
           ("tf", "The village can agree rules on waste and washing.", True, "Community rules help.", {}),
           ("mcq", "One solution is", "provide washing areas away from the stream", ["dump more waste", "block the stream", "ignore the problem"], "Separate washing places reduce pollution.", {}),
           ("open", "Give two other solutions for the village.", "Clean the stream regularly, build latrines and waste pits, teach hygiene, and plant trees on the banks.", "1 mark per solution.", {})])],
    [("The environment includes", "air, water, soil, plants and animals", ["only buildings", "only people", "only money"], "It is everything around us."),
     ("Recycling means", "making waste materials into new products", ["burning waste", "burying plastic everywhere", "wasting resources"], "It saves resources."),
     ("Bush burning can", "destroy soil life and cause smoke", ["improve all soils", "cure diseases", "make rain"], "It is harmful."),
     ("A way to reduce plastic waste is to", "use reusable bags and bottles", ["throw bottles in rivers", "burn plastics", "buy more bags"], "Reuse reduces waste."),
     ("Blocked drains in towns can cause", "floods", ["droughts", "snow", "earthquakes"], "Water cannot flow away.")],
    ["Teacher to verify local environmental laws and waste-collection systems in the school's area; the lesson is general and conservative."], tag="Form 2 citizenship environment")

signs = shapes([POLY(octagon(60, 70, 42), fill="red", stroke="ink"), T(60, 75, "STOP", size=14, bold=True, color="ink"),
                POLY([150, 35, 110, 105, 190, 105], fill="yellow", stroke="red", width=4), T(150, 95, "!", size=22, bold=True),
                CIRCLE(250, 70, 36, fill="lightblue", stroke="blue", width=4), T(250, 76, "→", size=22, bold=True),
                T(60, 130, "Stop", size=12), T(150, 130, "Warning", size=12), T(250, 130, "Obey (blue)", size=12)], 330, 150)
L = LS(c, "road-safety", "Road safety for pedestrians, cyclists and passengers",
    ["Describe safe behaviour for pedestrians and passengers", "Identify common road signs and signals", "Explain the danger of motorbike travel without a helmet and of speeding", "Explain what to do after an accident"],
    [("text", "Road accidents injure and kill many people, especially children and young people. Most accidents can be prevented. **Pedestrians** should walk on the pavement or, where there is none, on the side facing traffic; use **pedestrian crossings**; look **left, right and left again** before crossing; never cross while using a phone or playing; and wear light-coloured clothing or reflective items at night."),
     ("key", "retenir", "Passengers and riders", "Always wear a **seat belt** in a car. On a motorbike (including taxis) the rider and passenger should wear a **crash helmet**: it greatly reduces head injuries. Do not travel in an **overloaded** vehicle, in a vehicle with a **drunk or reckless** driver, or on the roof or step of a vehicle. Cyclists should keep to the side, use lights at night and obey signals."),
     ("key", "retenir", "Road signs", "**Regulatory signs** (usually round, with a red edge) forbid or command something, such as **'Stop'** (octagon), **speed limit** or **no entry**. **Warning signs** (usually triangular, with a red border) warn of danger ahead, such as a school, a bend or a junction. **Information signs** (often blue or rectangular) give directions and services. **Traffic lights**: red means stop, amber means prepare to stop, green means go when it is safe."),
     ("text", "**After an accident:** stay calm, make the scene safe, call for help from the police or emergency services, and do not move seriously injured people unless there is danger such as fire. Do what you can to help, such as stopping bleeding with clean cloth, but leave medical care to trained people. Be honest when giving information. Laws set penalties for drunk driving, speeding and driving without a licence or insurance."),
     ("key", "pieges", "Common mistakes", "- Do not run across the road: look first, then walk.\n- A helmet must be worn properly (fastened); a loose helmet gives little protection.\n- Do not argue that 'a short trip is safe': many accidents happen near home.")],
    [("Example 1: crossing", "List the steps for crossing a busy road safely.", ["Stop at the kerb and look left, right and left again.", "Use a crossing if there is one.", "Cross when clear, walking and watching."], "Stop, look left-right-left, use a crossing, cross when clear."),
     ("Example 2: motorbike taxi", "Why should a passenger on a motorbike taxi wear a helmet?", ["Falls often cause head injuries.", "A helmet absorbs shocks.", "So it can save life."], "To protect the head and reduce serious injury.")],
    F(signs, "Three kinds of road signs (simple drawings)", "A red octagon STOP sign, a yellow warning triangle and a blue circular sign."),
    [MCQ("In Form 2 citizenship, the shape of the 'Stop' sign is", "octagon", ["triangle", "square", "circle"], "It is an eight-sided red sign."),
     TF("A motorbike passenger should wear a helmet.", True, "It reduces head injury."),
     MATCH("Match each sign type with its meaning.", [("Triangular sign", "Warning of danger ahead"), ("Stop sign", "Stop completely"), ("Red traffic light", "Stop")], "Common signs."),
     MCQ("Which behaviour is dangerous?", "crossing the road while using a phone", ["using a pedestrian crossing", "wearing reflective clothes at night", "looking left and right"], "Distraction causes accidents.", tier="approfondissement"),
     OPEN("Explain three causes of road accidents in Cameroon and one way to reduce each.", "Speeding: enforce limits; poor vehicle condition: regular inspection; poor roads: repair them; drunk driving: tests and penalties; overloading: enforce rules.", "1 mark per cause with a solution.", points=3, tier="approfondissement"),
     PROB("A school is next to a busy road. Pupils cross in groups without looking.",
          [("mcq", "A safe measure would be", "a pedestrian crossing and a speed bump", ["no signs", "faster traffic", "closing the road at night only"], "Crossings slow traffic and guide pedestrians.", {}),
           ("tf", "Pupils should look left, right and left again before crossing.", True, "That is the safe habit.", {}),
           ("mcq", "Who can help pupils cross safely?", "a trained crossing guard or teacher", ["a stranger driver", "nobody", "the youngest pupil"], "Supervision protects children.", {}),
           ("open", "Give two rules for pupils near the road.", "Do not run or play near the road, use the crossing, wait for a clear gap, never cross between parked vehicles, and obey the guard.", "1 mark per rule.", {})])],
    [("A red traffic light means", "stop", ["go", "speed up", "turn left only"], "Red means stop."),
     ("A triangular sign with a red border usually warns of", "danger ahead", ["a restaurant", "a market", "a hotel"], "Warning signs are triangular."),
     ("The safest place to walk when there is a pavement is", "on the pavement", ["in the middle of the road", "on the white line", "on the bridge rail"], "Pavements are for pedestrians."),
     ("A seat belt should be worn", "by every car passenger", ["only by the driver", "only on motorways", "never"], "Seat belts save lives."),
     ("After an accident you should first", "stay calm and call for help", ["run away", "move all victims immediately", "argue"], "Safety and help come first.")],
    ["Health and safety content to be verified against the current Highway Code of Cameroon (helmet and seat-belt rules, sign shapes and colours, penalties); first-aid advice is minimal and must be reviewed by a trained instructor."], tag="Form 2 citizenship road safety")

p.write()
