"""Generates form1-computer and form2-computer (run: python3 form1-computer.py)."""
import sys
sys.path.insert(0, "/home/user/CastBridge/tools/learn-authoring/anglophone")
from _cs import *

SRC = "Original exercise written for CastBridge, in the style of the curriculum"
def mkpack(pid, title, level, ref, desc):
    return Pack(pid, title, level=level, subject="sciences", cursus="secondary", wanted="computer-science", programRef=ref, description=desc)

# =========================================================================== FORM 1
REF1 = "Cameroon secondary (general education) Computer Studies / ICT programme, Form 1 — to be checked against the official programme"
p = mkpack("form1-computer", "Computer Studies — Form 1", "Form 1", REF1,
           "First steps in Computer Studies: the parts of a computer, safe use, keyboard and mouse, files and folders, and word processing basics.")
c = p.chapter("start", "Getting started with computers", REF1)

lesson(c, "parts-of-computer", "The parts of a computer",
  ["Name the main parts of a desktop computer", "Say what each part does", "Tell input devices from output devices", "Explain what hardware and software are"],
  [("definition", "What is a computer?", "A **computer** is an electronic machine. It takes in data (**input**), works on it (**processing**), shows the result (**output**) and can keep it (**storage**). Computers follow instructions called **programs**."),
   ("retenir", "Main parts", "- **Monitor**: shows pictures and text (output).\n- **Keyboard** and **mouse**: send data in (input).\n- **System unit**: the box that holds the CPU, memory and disk.\n- **CPU**: the 'brain' that carries out instructions.\n- **Printer** and **speakers**: output devices."),
   ("retenir", "Hardware and software", "**Hardware** is the part you can touch. **Software** is the programs that tell the hardware what to do. A word processor is software. A mouse is hardware."),
   ("pieges", "Be careful", "- The monitor is **not** the computer; the system unit does the processing.\n- Do not call a file 'hardware'. A file is data.\n- A mouse is an input device, not an output device.")],
  ("Parts", cols("Main parts and jobs", ["Part", "Job"], [["Monitor", "Shows output"], ["Keyboard", "Types input"], ["Mouse", "Points and clicks"], ["System unit", "Holds CPU, disk"]]),
   "A table of four computer parts and the job of each.", "Table: monitor shows output, keyboard types input, mouse points and clicks, system unit holds the CPU and disk."),
  [("Example 1", "Sort these into input or output: keyboard, monitor, mouse, printer.", ["Input sends data into the computer: keyboard, mouse.", "Output shows results: monitor, printer."], "Input: keyboard, mouse. Output: monitor, printer."),
   ("Example 2", "A student types a letter, sees it on the screen and prints it. Name the device used at each step.", ["Typing uses the keyboard (input).", "Seeing uses the monitor and printing uses the printer (output)."], "Keyboard, monitor, printer.")],
  [M("Which part is the 'brain' of the computer?", "The CPU", ["The monitor", "The mouse", "The speaker"], "The CPU carries out the instructions."),
   M("Which is an input device?", "Keyboard", ["Monitor", "Printer", "Speaker"], "The keyboard sends data in."),
   TF("Software is the part of the computer you can touch.", False, "Hardware can be touched. Software is programs.")],
  [MT("Match each part to its job.", [("Monitor", "Shows pictures and text"), ("Mouse", "Points and clicks"), ("Printer", "Puts output on paper"), ("Keyboard", "Types letters and numbers")], "Each device has one main job."),
   O("Explain the difference between hardware and software. Give one example of each.", "Hardware is the physical parts of a computer, for example the monitor. Software is the programs that tell the computer what to do, for example a word processor.", "1 mark hardware, 1 mark software, 1 mark for one correct example each.")],
  P("A school computer room in Buea has 20 computers, each with a monitor, keyboard, mouse and system unit.",
    [pm("Which part holds the CPU?", "System unit", ["Monitor", "Mouse", "Keyboard"], "The CPU is inside the system unit."),
     pn("How many monitors are there in the room?", 20, "One monitor for each of the 20 computers."),
     po("Name one output device and one input device.", "Output: monitor. Input: keyboard (or mouse).", "1 mark each.")]),
  [("A computer takes in data. This is called", "input", ["output", "storage", "printing"], "Input is data going in."),
   ("The mouse is used to", "point and click", ["print paper", "show pictures", "play sound only"], "It is a pointing device."),
   ("Programs for a computer are called", "software", ["hardware", "cables", "screens"], "Software."),
   ("Which shows the result on a screen?", "Monitor", ["Mouse", "Keyboard", "Scanner"], "The monitor displays output."),
   ("Which one is hardware?", "Printer", ["Word processor", "Game program", "Browser"], "The printer is a physical device.")],
  notes=["Very basic wording for Form 1; check the sequence of topics against the official programme."], minutes=20)

lesson(c, "safe-use", "Using computers safely",
  ["Follow computer room rules", "Protect yourself from health problems", "Care for equipment", "Start and shut down a computer correctly"],
  [("retenir", "Computer room rules", "- Do not eat or drink near computers.\n- Keep bags and liquids away from cables.\n- Do not unplug cables or open the system unit.\n- Report faults to the teacher.\n- Use only your own account and keep your password secret."),
   ("methode", "Healthy use", "Sit with your back straight, feet flat on the floor and the screen at eye level. Take a short break every 30 to 60 minutes. Look away from the screen to rest your eyes. Good posture helps prevent back and neck pain."),
   ("methode", "Starting and shutting down", "Switch on the monitor and the computer. Log in. When you finish, **save your work**, close programs, then use **Shut down** from the menu. Do not just switch off at the socket: this can damage files."),
   ("attention", "Important", "- Electricity can be dangerous: never touch bare wires with wet hands.\n- Power cuts can erase unsaved work: save often.\n- A strong password is long and mixed; never write it on the desk.")],
  ("Posture", shapes([T(210, 22, "Sitting at a computer", 15, bold=True), RECT(250, 110, 100, 60, fill="lightblue", radius=4), T(300, 145, "Screen", 13),
     LINE(60, 170, 350, 170, width=3), RECT(60, 100, 22, 22, fill="lightyellow"), T(71, 140, "Head", 12), LINE(71, 122, 71, 165, width=3), T(150, 190, "Feet flat, back straight", 12),
     LINE(85, 111, 245, 125, dash=True, color="grey"), T(165, 100, "eyes level with screen", 12)], 420, 210),
   "A person sits upright facing a screen at eye level.", "Diagram of a person sitting straight in front of a screen at eye level."),
  [("Example 1", "A pupil brings a bottle of water to the computer room. What should the teacher say and why?", ["Liquids must stay away from computers.", "A spill can short-circuit equipment and may cause an electric shock."], "Leave the water outside the room."),
   ("Example 2", "Put the shutdown steps in order: switch off the monitor, save your work, choose Shut down, close programs.", ["First save, then close programs.", "Then choose Shut down; switch off the monitor last."], "Save, close programs, Shut down, switch off the monitor.")],
  [M("Which is a computer room rule?", "Do not eat or drink near computers", ["Share your password", "Pull out cables to move a PC", "Open the system unit"], "Food and drink can damage equipment."),
   TF("You should save your work before shutting down.", True, "Saving prevents loss of work."),
   M("How often should you rest your eyes?", "Take regular short breaks", ["Never", "Only at night", "Only on Sundays"], "Regular breaks reduce eye strain.")],
  [M("Switching off a computer by pulling the plug can", "damage files", ["make it faster", "clean the screen", "save your work"], "Always shut down properly."),
   O("Give three ways to avoid health problems when using a computer for a long time.", "Sit with a straight back; keep the screen at eye level; take breaks; rest the eyes by looking far away.", "1 mark each, up to 3.")],
  P("Ngwa sits very close to a screen for three hours without a break.",
    [pm("Which problem can this cause?", "Tired eyes and back pain", ["Faster typing", "A virus", "More memory"], "Long use without breaks causes strain."),
     pt("Ngwa should take regular breaks.", True, "Breaks are healthy."),
     po("Give two pieces of advice for Ngwa.", "Sit straight with the screen at eye level; take a break every hour.", "1 mark each.")]),
  [("Food and drink in the computer room are", "not allowed", ["encouraged", "required", "free"], "They can cause damage."),
   ("Before shutting down you should", "save your work", ["unplug the cable", "open the system unit", "share your password"], "Saving prevents loss."),
   ("A good sitting position has", "a straight back", ["a bent neck", "a very close screen", "no support"], "Posture matters."),
   ("You should keep your password", "secret", ["written on the desk", "shared with friends", "very short"], "Passwords are private."),
   ("Report a computer fault to", "the teacher", ["a classmate only", "nobody", "the janitor only"], "The teacher can act.")],
  notes=["Health advice is general; a health professional may review. Check the school's own computer-room rules."], minutes=20)

lesson(c, "keyboard-mouse", "Keyboard and mouse skills",
  ["Name the main zones of the keyboard", "Use Shift, Enter, Backspace, Delete and Space", "Use the mouse: click, double-click, right-click, drag", "Type with good finger positions"],
  [("definition", "Keyboard zones", "The keyboard has **letter keys** (QWERTY layout), a row of **number keys**, **function keys** (F1 to F12), **arrow keys**, and often a **numeric keypad**. **Shift** types capital letters. **Caps Lock** keeps capitals on. **Enter** starts a new line. **Space bar** adds a space."),
   ("retenir", "Editing keys", "**Backspace** deletes the character before the cursor. **Delete** removes the character after it. **Tab** moves along. **Esc** cancels. Useful shortcuts: **Ctrl + C** copy, **Ctrl + V** paste, **Ctrl + X** cut, **Ctrl + Z** undo, **Ctrl + S** save."),
   ("methode", "The mouse", "**Click** (left button) selects. **Double-click** opens. **Right-click** shows a menu. **Drag** means hold the left button and move. The scroll wheel moves a page up and down. Keep your wrist straight and rest your hand lightly."),
   ("pieges", "Common mistakes", "- Using Caps Lock for one capital letter; use Shift instead.\n- Mixing up Backspace (before) and Delete (after).\n- Two fast clicks that are too slow count as two single clicks, not a double-click.")],
  ("Keyboard zones", shapes([T(210, 22, "Keyboard zones", 15, bold=True), RECT(10, 40, 250, 40, fill="lightyellow"), T(135, 65, "Function keys F1-F12", 12),
     RECT(10, 85, 250, 90, fill="lightblue"), T(135, 135, "Letter and number keys", 13), RECT(270, 85, 60, 90, fill="lightgreen"), T(300, 135, "Arrows", 12), RECT(340, 85, 70, 90, fill="lightorange"), T(375, 135, "Keypad", 12)], 420, 190),
   "A sketch of the keyboard with function keys, letter keys, arrow keys and a numeric keypad.", "Keyboard diagram showing four zones: function keys, letter and number keys, arrow keys and keypad."),
  [("Example 1", "You typed 'Camroon'. Fix it to 'Cameroon' using the keyboard.", ["Move the cursor after 'Cam' using the arrow keys.", "Type the missing letter 'e' to get Cameroon."], "Cameroon"),
   ("Example 2", "Copy a sentence and paste it below. Give the shortcut keys.", ["Select the sentence, then press Ctrl + C to copy.", "Move to a new line and press Ctrl + V to paste."], "Ctrl + C, then Ctrl + V")],
  [M("Which key makes one capital letter?", "Shift", ["Tab", "Esc", "Delete"], "Hold Shift and press the letter."),
   M("The shortcut to save is", "Ctrl + S", ["Ctrl + P", "Ctrl + Q", "Ctrl + Z"], "S for save."),
   TF("Right-click usually shows a menu of options.", True, "Right-click opens a context menu.")],
  [M("Which key removes the character to the left of the cursor?", "Backspace", ["Delete", "Enter", "Tab"], "Backspace deletes backwards."),
   O("Explain the difference between Backspace and Delete.", "Backspace removes the character before (to the left of) the cursor. Delete removes the character after (to the right of) the cursor.", "1 mark each description, 1 mark contrast.")],
  P("A student is typing the title 'My School in Limbe'.",
    [pm("Which key gives a capital M?", "Shift + m", ["Tab + m", "Ctrl + m", "Esc + m"], "Shift gives capitals."),
     pm("Which key adds the spaces between the words?", "Space bar", ["Enter", "Delete", "Esc"], "Space bar."),
     po("The student typed 'Limbee'. How can it be corrected?", "Press Backspace once to remove the extra 'e'.", "1 mark Backspace, 1 mark correct position.")]),
  [("The key that starts a new line is", "Enter", ["Esc", "Shift", "Delete"], "Enter."),
   ("To open a file or program you usually", "double-click it", ["right-click only", "drag it away", "press Esc"], "Double-click opens."),
   ("Ctrl + Z does", "undo", ["print", "save", "close the computer"], "Undo last action."),
   ("Caps Lock", "keeps capital letters on", ["deletes text", "saves files", "prints"], "Toggle capitals."),
   ("The arrow keys", "move the cursor", ["print", "save", "shut down"], "Navigation.")],
  notes=["Shortcuts shown are the common Windows/Linux ones."], minutes=20)

lesson(c, "files-folders", "Files and folders",
  ["Explain what a file and a folder are", "Create, rename, copy, move and delete files", "Use file names and extensions", "Save work in the right place"],
  [("definition", "File and folder", "A **file** is a named piece of data stored on a disk: a letter, a picture, a song, a program. A **folder** is like a drawer: it holds files and other folders. Folders keep your work in order."),
   ("retenir", "File names", "A file name has two parts: the **name** and the **extension** after a dot, e.g. letter.docx. The extension shows the file type: .docx (document), .jpg (photo), .mp3 (sound), .txt (plain text). Choose clear names like Maths_Homework.docx."),
   ("methode", "Managing files", "Right-click a file or folder to find **Copy**, **Cut**, **Paste**, **Rename** and **Delete**. Copy leaves the original. Cut moves it. Deleted files often go to the **Recycle Bin**, where you can restore them. Save with **Save As** to choose the folder and the name."),
   ("pieges", "Mistakes", "- Do not use names like 'new1' that you will forget.\n- Do not delete files you did not create.\n- Keep copies of important files on a flash drive.")],
  ("Folders", shapes([T(210, 22, "Folders and files", 15, bold=True), RECT(150, 40, 120, 30, fill="lightblue", radius=4), T(210, 60, "My Documents", 12),
     LINE(180, 70, 100, 105, arrow="end"), LINE(240, 70, 320, 105, arrow="end"), RECT(40, 105, 120, 30, fill="lightgreen", radius=4), T(100, 125, "Maths", 13), RECT(260, 105, 120, 30, fill="lightgreen", radius=4), T(320, 125, "English", 13),
     LINE(100, 135, 100, 160, arrow="end"), RECT(40, 160, 120, 28, fill="lightyellow", radius=4), T(100, 179, "homework.docx", 11)], 420, 200),
   "A folder My Documents with sub-folders Maths and English; Maths holds homework.docx.", "Folder tree: My Documents contains Maths and English; Maths contains the file homework.docx."),
  [("Example 1", "What is the extension in the file name story.txt and what does it show?", ["The extension is the part after the dot: txt.", "It shows the file is plain text."], ".txt - a plain text file"),
   ("Example 2", "You saved photo.jpg in the wrong folder. How do you move it to the folder Pictures?", ["Right-click photo.jpg and choose Cut.", "Open the folder Pictures, right-click and choose Paste."], "Cut then Paste into Pictures.")],
  [M("A folder is used to", "keep files in order", ["print files", "type text", "show colour"], "Folders organise files."),
   M("The extension of music.mp3 is", ".mp3", ["music", ".music", "mp"], "The part after the dot."),
   TF("Copy leaves the original file in its place.", True, "Cut moves; copy duplicates.")],
  [M("Which file name is the best?", "Maths_Homework_Term1.docx", ["file.docx", "asdf.docx", "new1.docx"], "Clear names help you find files."),
   O("Explain why it is useful to keep a copy of important files on a flash drive.", "If the computer is damaged, stolen or loses power, the copy on the flash drive is still safe, so the work is not lost.", "1 mark for a risk, 1 mark for the copy as protection.")],
  P("Amina has a folder School. She wants Maths and Science folders inside it.",
    [pm("What do we call a folder inside another folder?", "A subfolder", ["An extension", "A program", "A cable"], "Subfolder."),
     pt("Amina can have the same file name in two different folders.", True, "Folders keep the files apart."),
     po("Suggest a good name for her Maths homework file for week 3.", "Maths_Homework_Week3.docx (clear name with subject and week).", "1 mark clear name, 1 mark extension.")]),
  [("A file is", "a named piece of stored data", ["a cable", "a printer", "a keyboard"], "Files store data."),
   ("The Recycle Bin", "holds deleted files that can be restored", ["prints files", "types letters", "adds colour"], "Safe deleted files."),
   ("To keep the original and make another copy, use", "Copy and Paste", ["Cut and Paste", "Delete", "Rename"], "Copy keeps the original."),
   ("The extension .jpg usually means a", "picture", ["song", "spreadsheet", "program"], "JPEG image."),
   ("Save As lets you choose", "the folder and the name", ["only the screen colour", "the printer speed", "the mouse"], "Where and what.")],
  notes=["Recycle Bin behaviour depends on the system; keep wording general."], minutes=20)

lesson(c, "word-processing-basics", "Word processing basics",
  ["Open a word processor and type a short document", "Format text: bold, italic, underline, size, font", "Align text and use bullets", "Save and print a document"],
  [("definition", "Word processor", "A **word processor** is a program for writing documents such as letters, essays and notices. You can type, correct mistakes, change how the text looks (**formatting**), save the file and print it."),
   ("methode", "Formatting", "Select the text first (drag the mouse over it). Then use the toolbar: **B** for bold, **I** for italic, **U** for underline. Change the **font** and the **font size**. **Alignment** can be left, centre, right or justified. Use **bullets** or **numbers** for lists."),
   ("methode", "Save and print", "Click **File** then **Save As**, choose a folder, type a name and click Save. Use **Ctrl + S** to save again as you work. Choose **Print Preview** before printing to check the page. Press **Ctrl + P** to print."),
   ("pieges", "Mistakes", "- Formatting does nothing unless the text is **selected** first.\n- Do not press Enter at the end of every line; the text wraps by itself.\n- Spell checking does not catch every error: read the text yourself.")],
  ("Alignment", shapes([T(210, 22, "Text alignment", 15, bold=True)] + [x for i, (lab, xs) in enumerate([("Left", 30), ("Centre", 150), ("Right", 270)]) for x in (RECT(xs, 50, 120, 90, fill="lightyellow", stroke="grey", width=1), T(xs + 60, 40, lab, 12, bold=True),
        LINE(xs + (10 if lab == "Left" else (30 if lab == "Centre" else 60)), 70, xs + (100 if lab == "Left" else (90 if lab == "Centre" else 110)), 70, width=3),
        LINE(xs + (10 if lab == "Left" else (45 if lab == "Centre" else 40)), 95, xs + (80 if lab == "Left" else (75 if lab == "Centre" else 110)), 95, width=3),
        LINE(xs + (10 if lab == "Left" else (35 if lab == "Centre" else 70)), 120, xs + (60 if lab == "Left" else (85 if lab == "Centre" else 110)), 120, width=3))], 420, 160),
   "Three boxes showing text lines aligned to the left, centre and right.", "Three small page sketches with lines of text aligned left, centre and right."),
  [("Example 1", "Make the title 'MY SCHOOL' bold, centred and size 20. Give the steps.", ["Select the title with the mouse.", "Click Bold (B), then Centre, then set the font size to 20."], "Select, then Bold, Centre, size 20."),
   ("Example 2", "You typed a list of items on separate lines. How do you turn it into a bullet list?", ["Select all the lines of the list.", "Click the Bullets button on the toolbar."], "Select the lines, click Bullets.")],
  [M("Before changing the font of a word you must", "select it", ["delete it", "print it", "save it"], "Select first, then format."),
   M("The button 'B' makes text", "bold", ["blue", "bigger", "back"], "Bold."),
   TF("You should press Enter at the end of every line while typing a paragraph.", False, "Text wraps automatically; press Enter at the end of a paragraph.")],
  [M("Which alignment puts text in the middle of the page?", "Centre", ["Left", "Right", "Justified"], "Centre alignment."),
   O("List three steps to save a new document and print it.", "File - Save As; choose a folder and a name; click Save; then File - Print (or Ctrl + P) after checking Print Preview.", "1 mark each step.")],
  P("Chiara is typing a notice for a school fair in Bamenda.",
    [pm("Which feature checks spelling mistakes?", "Spell check", ["Print Preview", "Bullets", "Alignment"], "Spell check finds possible mistakes."),
     pm("Which feature should she use to show the date in the middle of the page?", "Centre alignment", ["Left alignment", "Underline only", "Shut down"], "Centre."),
     po("Why is Print Preview useful?", "It shows how the page will look so mistakes can be fixed before printing and paper is not wasted.", "1 mark each reason.")]),
  [("A word processor is used to", "write documents", ["play music only", "calculate with a ruler", "print photos"], "Documents."),
   ("I stands for", "italic", ["image", "input", "icon"], "I is italic."),
   ("To make a bullet list click", "Bullets", ["Print", "Shut down", "Delete"], "Bullets."),
   ("Ctrl + S is used to", "save", ["print", "close", "undo"], "Save."),
   ("The font size changes", "how big the letters are", ["the file name", "the screen", "the folder"], "Size.")],
  notes=["Button names vary slightly between programs."], minutes=20)
write(p)

# =========================================================================== FORM 2
REF2 = "Cameroon secondary (general education) Computer Studies / ICT programme, Form 2 — to be checked against the official programme"
p = mkpack("form2-computer", "Computer Studies — Form 2", "Form 2", REF2,
           "Spreadsheet basics, the Internet and email, presentations and binary numbers for Form 2.")
c = p.chapter("tools", "Spreadsheets, the Internet and presentations", REF2)
assert 7 + 5 == 12

lesson(c, "spreadsheet-basics", "Spreadsheet basics",
  ["Name rows, columns and cells", "Enter data and simple formulas", "Use SUM and AVERAGE", "Make a simple chart"],
  [("definition", "Spreadsheet", "A **spreadsheet** is a program that arranges data in **rows** (numbers 1, 2, 3...) and **columns** (letters A, B, C...). Each box is a **cell**. B3 means column B, row 3. A spreadsheet can calculate automatically."),
   ("methode", "Formulas", "Start a formula with **=**. Examples: =A1+A2, =B2*C2, =SUM(B2:B5) (adds B2 to B5), =AVERAGE(B2:B5). Press Enter. If you change a number, the answer changes by itself. Use + - * / for add, subtract, multiply, divide."),
   ("retenir", "Charts", "A **bar chart** compares amounts. A **line chart** shows change over time. A **pie chart** shows parts of a total. Always give a chart a title and label the axes."),
   ("pieges", "Mistakes", "- No = sign: the cell shows text instead of a result.\n- Typing the answer by hand: it will not update.\n- Writing the cell reference as 3B instead of B3.")],
  ("Mini table", cols("Spreadsheet of fruit sales", ["A: Fruit", "B: Kg", "C: Price"], [["Mango", "10", "500"], ["Pineapple", "6", "700"], ["Banana", "8", "300"]]),
   "A spreadsheet table with three fruits, kilograms sold and price per kilogram.", "Table: mango 10 kg at 500, pineapple 6 kg at 700, banana 8 kg at 300."),
  [("Example 1", "In the sheet above, write a formula for the income from mango (kg in B2, price in C2) and compute it.", ["Income = kg x price, so D2 = B2*C2.", "10 x 500 = 5000 FCFA."], "=B2*C2 = 5000"),
   ("Example 2", "Total kilograms sold: B2=10, B3=6, B4=8. Write the formula and compute it.", ["Use SUM over the range: =SUM(B2:B4).", "10 + 6 + 8 = 24."], "=SUM(B2:B4) = 24")],
  [M("The cell in column D, row 4 is", "D4", ["4D", "D-4", "DD4"], "Column then row."),
   N("What does =A1+A2 give if A1 = 7 and A2 = 5?", 12, "7 + 5 = 12."),
   TF("A formula begins with the = sign.", True, "Yes.")],
  [N("=AVERAGE(B2:B4) when B2=10, B3=6, B4=8 equals", 8, "(10+6+8)/3 = 24/3 = 8."),
   M("Which chart shows how a total is shared in parts?", "Pie chart", ["Line chart of years", "No chart", "Bar chart only"], "Pie = parts of a whole.")],
  P("Prices: Rice 600, Oil 1500, Sugar 800 FCFA are in C2:C4.",
    [pn("Value of =SUM(C2:C4)", 2900, "600 + 1500 + 800 = 2900."),
     pn("Value of =MAX(C2:C4)", 1500, "Largest price: 1500."),
     pm("To find the mean price use", "=AVERAGE(C2:C4)", ["=ADD(C2:C4)", "=C2:C4", "AVERAGE C2"], "AVERAGE gives the mean.")]),
  [("A box in a spreadsheet is called a", "cell", ["file", "folder", "icon"], "Cell."),
   ("=SUM(A1:A3) adds", "the cells A1, A2 and A3", ["only A1", "only A3", "nothing"], "Range sum."),
   ("Columns are named by", "letters", ["numbers", "colours", "symbols"], "A, B, C..."),
   ("If a number used by a formula changes, the answer", "updates automatically", ["stays the same", "disappears", "turns into text"], "Automatic."),
   ("A bar chart is best for", "comparing amounts", ["typing letters", "printing", "storing files"], "Compare.")],
  notes=["Function names are English (SUM, AVERAGE, MAX)."], minutes=20)

lesson(c, "internet-email", "The Internet and email basics",
  ["Explain what the Internet and the web are", "Use a browser and a search engine", "Send and receive email", "Stay safe online"],
  [("definition", "Internet and web", "The **Internet** is a worldwide network of computers. The **World Wide Web** is the pages you view on it. A **browser** shows web pages. A **search engine** finds pages for words you type. A **website address** (URL) is like www.example.com."),
   ("methode", "Searching well", "Use clear key words, e.g. 'rainfall Douala'. Check who made the page. Compare two sources. Not everything online is true. Copying a text word for word without saying where it came from is not honest."),
   ("methode", "Email", "An **email address** looks like name@example.com. To send: click New message, type the address in **To**, a **Subject**, the message, and click Send. You can add an **attachment**. **Reply** answers a message. **Inbox** holds received mail."),
   ("pieges", "Safety", "- Never share your password.\n- Do not open attachments from people you do not know.\n- Do not give personal details to strangers.\n- A message promising a prize may be a trick (phishing).")],
  ("Email layout", shapes([T(210, 22, "Parts of an email", 15, bold=True), RECT(20, 40, 380, 28, fill="lightblue"), T(60, 59, "To:", 13, anchor="start"), T(130, 59, "friend@example.com", 13, anchor="start"),
     RECT(20, 70, 380, 28, fill="lightgreen"), T(60, 89, "Subject:", 13, anchor="start"), T(150, 89, "School trip", 13, anchor="start"),
     RECT(20, 100, 380, 60, fill="lightyellow"), T(210, 135, "Message text", 13), RECT(20, 165, 90, 28, fill="lightorange", radius=6), T(65, 184, "Send", 13)], 420, 205),
   "An email with the To box, Subject box, message area and Send button.", "Email window with To, Subject, message text and Send."),
  [("Example 1", "Why is 'prize@free-win.example' in an unknown email a warning sign?", ["It offers something for nothing from an unknown sender.", "Prize messages often ask for personal data: a phishing sign."], "Do not open or reply; delete it."),
   ("Example 2", "List the steps to email a homework file to your teacher.", ["Open your email, click New message, type the teacher's address and a subject.", "Click Attach, choose the file, then Send."], "New message, address, subject, attach, send")],
  [M("Which program shows web pages?", "A browser", ["A spreadsheet", "A printer", "A scanner"], "Browser."),
   M("An email address contains the symbol", "@", ["#", "%", "&"], "Name@domain."),
   TF("Everything on the Internet is true.", False, "Always check sources.")],
  [M("Which is a strong sign of a phishing email?", "It asks for your password", ["It is from your teacher by name", "It has your homework", "It has no attachment"], "No real service asks for passwords by email."),
   O("Give three rules for safe use of the Internet.", "Keep passwords secret; do not give personal details to strangers; do not open unknown attachments or links; tell an adult if something is wrong.", "1 mark each, up to 3.")],
  P("Eko wants to find information about Mount Cameroon for a project.",
    [pm("Which tool helps him find pages?", "A search engine", ["A printer", "A scanner", "A speaker"], "Search engine."),
     pt("He should copy a whole page into his project without saying where it came from.", False, "Copying without credit is not honest."),
     po("Suggest two key words he could type.", "Mount Cameroon height; Mount Cameroon volcano.", "1 mark each reasonable key words.")]),
  [("An ISP gives you", "access to the Internet", ["a printer", "a screen", "a mouse"], "Internet Service Provider."),
   ("The subject of an email is", "a short title for the message", ["the attachment", "the address", "the password"], "Title."),
   ("A URL is", "a web address", ["a virus", "a mouse", "a memory chip"], "Address."),
   ("Attachments from unknown senders should", "not be opened", ["always be opened", "be printed", "be forwarded"], "May contain viruses."),
   ("The Inbox holds", "received messages", ["sent messages only", "deleted pictures", "passwords"], "Inbox.")],
  notes=["Use example.com style addresses only; no real addresses."], minutes=20)

lesson(c, "presentations", "Presentation software",
  ["Say what a presentation program is for", "Create slides with titles, text and pictures", "Apply simple design rules", "Present clearly"],
  [("definition", "Slides", "A **presentation program** lets you make a series of **slides** to show an audience. Each slide can have a title, short text, pictures, charts and sound. You can add **transitions** between slides and **animations** to objects."),
   ("methode", "Good design", "- One main idea per slide.\n- Short points, not long sentences (about 6 lines at most).\n- Large text (at least 24 points) in a clear font.\n- Strong contrast between text and background.\n- Use pictures that help, not decorate."),
   ("methode", "Making a presentation", "Choose a layout (Title slide, Title and content). Click to add the title and text. Use Insert to add a picture or table. Use **Slide Show** to run it. Practise what you will say. Do not read every word from the slide."),
   ("pieges", "Mistakes", "- Too much text on a slide.\n- Dark text on a dark background.\n- Too many animations, which distract the audience.")],
  ("Slide layout", shapes([T(210, 20, "A good slide", 15, bold=True), RECT(40, 35, 340, 150, fill="white", stroke="ink", width=2), RECT(60, 45, 300, 28, fill="lightblue"), T(210, 65, "Title of the slide", 14, bold=True),
     T(70, 100, "- First short point", 13, anchor="start"), T(70, 124, "- Second short point", 13, anchor="start"), T(70, 148, "- Third short point", 13, anchor="start")], 420, 195),
   "A slide with a title and three short bullet points.", "Slide with a title bar and three short bullet points."),
  [("Example 1", "A slide has 12 long sentences. How would you improve it?", ["Too much text; split it across several slides.", "Keep three to five short bullets per slide and enlarge the text."], "Split the slide and shorten the text."),
   ("Example 2", "Choose the better colour pair for a projector: yellow text on white or dark blue text on white.", ["Contrast matters: yellow on white is hard to read.", "Dark blue on white gives strong contrast."], "Dark blue on white")],
  [M("A single page in a presentation is a", "slide", ["cell", "record", "folder"], "Slide."),
   TF("A slide should contain a lot of small text.", False, "Keep text short and large."),
   M("Which makes text easy to read?", "Strong contrast with the background", ["Very small letters", "Many colours", "Long paragraphs"], "Contrast.")],
  [M("Moving from one slide to the next with an effect is a", "transition", ["field", "extension", "query"], "Transition."),
   O("Give three rules for designing a good slide.", "One idea per slide; short points; large clear text; good contrast; useful pictures.", "1 mark each, up to 3.")],
  P("Rose will present 'Water in Cameroon' to Form 2 using five slides.",
    [pm("What should the first slide show?", "The title and her name", ["All the facts", "Only a picture", "A blank page"], "Title slide."),
     pt("She should read every word from the slide.", False, "She should explain in her own words."),
     po("Suggest two things to put on a slide about water.", "A title; two or three short points; a picture of a river such as the Wouri.", "1 mark each.")]),
  [("The best amount of text for a slide is", "a few short points", ["a full page", "none at all", "a story"], "Short."),
   ("Slides are shown with", "Slide Show", ["Print Only", "Shut Down", "Save As"], "Slide Show view."),
   ("Animations should be", "used sparingly", ["on every word", "very loud", "never read"], "Avoid distraction."),
   ("Which is a presentation program task?", "Make slides", ["Add up numbers", "Store records", "Install a network"], "Slides."),
   ("Large clear text", "helps the audience read", ["hides the message", "is not allowed", "saves paper"], "Readable.")],
  notes=["Font size guidance (24 pt) is a common rule of thumb, not an official rule."], minutes=20)


lesson(c, "word-processing-layout", "Word processing: tables, pictures and page layout",
  ["Insert and format a table", "Insert a picture and wrap text around it", "Set margins, page numbers, headers and footers", "Use find and replace and a spell check"],
  [("methode", "Tables", "A **table** has rows and columns of cells. Use Insert then Table and choose the number of rows and columns. Tables are good for timetables, price lists and class lists. You can add or delete rows and columns, merge cells and add borders."),
   ("methode", "Pictures and layout", "Use Insert then Picture to add an image. Drag a corner handle to resize it **without distortion**. **Text wrapping** decides how the text flows around the picture. **Margins** are the empty spaces at the page edges. **Orientation** can be portrait (tall) or landscape (wide)."),
   ("retenir", "Headers, footers and tools", "A **header** is text at the top of every page; a **footer** is at the bottom. Page numbers are often placed in the footer. **Find and Replace** changes every copy of a word at once. **Spell check** underlines possible mistakes; always read your text yourself too."),
   ("pieges", "Mistakes", "- Pulling a side handle of a picture stretches it; use a corner handle.\n- Very large pictures make the file big.\n- Do not use spaces to line up columns; use a table or tab stops.")],
  ("Table", cols("Class timetable (part)", ["Time", "Monday", "Tuesday"], [["8:00", "Maths", "English"], ["9:00", "Science", "ICT"], ["10:00", "Break", "Break"]]),
   "A table with times and subjects for Monday and Tuesday.", "Timetable table with columns for time, Monday and Tuesday."),
  [("Example 1", "How many cells are in a table with 5 rows and 4 columns?", ["Cells = rows x columns.", "5 x 4 = 20."], "20 cells"),
   ("Example 2", "A school name appears 12 times as 'GBHS' but must be 'GBPHS'. What tool changes all at once?", ["Open Find and Replace.", "Find: GBHS. Replace with: GBPHS. Choose Replace All."], "Find and Replace (Replace All)")],
  [N("How many cells does a table with 3 rows and 6 columns have?", 18, "3 x 6 = 18."),
   M("Text that appears at the top of every page is a", "header", ["footer", "margin", "border"], "Header."),
   TF("Dragging a corner handle resizes a picture without stretching it.", True, "Corner handles keep proportions.")],
  [M("Which view is wider than it is tall?", "Landscape", ["Portrait", "Margin", "Header"], "Landscape orientation."),
   O("Explain two good uses of a table in a document.", "To show a timetable or price list in neat rows and columns; to line up data so it is easy to compare.", "1 mark each use.")],
  P("Ada makes a price list: item, quantity, price for 4 items plus a title row.",
    [pn("How many rows does her table need (title row plus 4 items)?", 5, "1 + 4 = 5 rows."),
     pn("It has 3 columns. How many cells in all?", 15, "5 x 3 = 15."),
     pm("Where would she put page numbers?", "In the footer", ["In the margin only", "In the cell", "In the file name"], "Page numbers usually go in the footer.")]),
  [("Margins are", "empty spaces at the page edges", ["pictures", "tables", "headers"], "Margins."),
   ("A footer is at the", "bottom of the page", ["top of the page", "side of the screen", "inside RAM"], "Footer."),
   ("Find and Replace helps to", "change a word everywhere", ["print", "shut down", "draw"], "Replace All."),
   ("Portrait means", "tall page", ["wide page", "no page", "colour page"], "Portrait."),
   ("Cells in a table are found at", "rows and columns crossing", ["only the corners", "the footer", "the title"], "Cells.")],
  notes=["Menu names differ between word processors."], minutes=20)

lesson(c, "binary-basics", "Binary numbers: the basics",
  ["Explain why computers use 0 and 1", "Count in binary", "Convert small binary numbers to denary and back", "Know bit, byte and the storage units"],
  [("definition", "Binary", "Computers use **binary**: only the digits 0 and 1. A **bit** is one binary digit. **8 bits make 1 byte**. Binary matches the two states of electronic switches: off (0) and on (1)."),
   ("methode", "Place values", "Binary place values double from the right: 1, 2, 4, 8, 16, 32, 64, 128. To convert binary to **denary** (ordinary numbers), add the place values where there is a 1. Example: 1011 = 8 + 2 + 1 = 11."),
   ("methode", "Denary to binary", "Find the largest place value that fits, write 1 there and subtract. Continue to the right. Example: 13 = 8 + 4 + 1, so 13 = 1101 (place 2 is 0)."),
   ("retenir", "Storage units", "1 byte = 8 bits. 1 KB (kilobyte) = 1024 bytes, 1 MB = 1024 KB, 1 GB = 1024 MB (the usual school convention).")],
  ("Place values", boxrow("Place values of 1101 (13)", ["8", "4", "2", "1"], sub=["1", "1", "0", "1"], colors=["lightgreen", "lightgreen", "lightgrey", "lightgreen"], bw=60),
   "Four boxes with place values 8, 4, 2, 1 and the bits 1101.", "Row of boxes 8, 4, 2, 1 with bits 1, 1, 0, 1 under them."),
  [("Example 1", "Convert 1011 from binary to denary.", ["Place values: 8, 4, 2, 1 for bits 1, 0, 1, 1.", "Add: 8 + 2 + 1 = 11."], "11"),
   ("Example 2", "Convert 13 to binary.", ["13 = 8 + 4 + 1. Bits for 8, 4, 2, 1: 1, 1, 0, 1.", "So 13 = 1101."], "1101")],
  [N("Convert 101 (binary) to denary.", 5, "4 + 1 = 5."),
   M("A bit is", "a single 0 or 1", ["8 bytes", "a type of file", "a printer"], "One binary digit."),
   N("How many bits are there in 2 bytes?", 16, "2 x 8 = 16.")],
  [M("Binary 1000 in denary is", "8", ["4", "10", "16"], "Place value 8."),
   N("Convert 9 to binary and give the number of 1s in it.", 2, "9 = 1001, which has two 1s.")],
  P("Binary numbers: 110 and 111.",
    [pn("110 in denary", 6, "4 + 2 = 6."),
     pn("111 in denary", 7, "4 + 2 + 1 = 7."),
     po("Which is bigger, and by how much?", "111 (7) is bigger than 110 (6) by 1.", "1 mark bigger, 1 mark difference.")]),
  [("The digits of binary are", "0 and 1", ["0 to 9", "1 to 8", "A to F"], "Base 2."),
   ("1 byte equals", "8 bits", ["2 bits", "16 bits", "1024 bits"], "8 bits."),
   ("Binary 11 in denary is", "3", ["2", "4", "11"], "2 + 1."),
   ("The place values in binary (from the right) are", "1, 2, 4, 8", ["1, 3, 5, 7", "1, 10, 100", "2, 4, 6, 8"], "Powers of 2."),
   ("1 KB is about", "1024 bytes", ["8 bytes", "1 bit", "1 GB"], "School convention.")],
  notes=["1024 vs 1000 convention to be agreed with the teacher."], minutes=20)
for i in range(16): assert int(format(i, "b"), 2) == i
assert int("1011", 2) == 11 and int("1101", 2) == 13 and format(9, "b") == "1001" and 24 == 10 + 6 + 8 and (10+6+8)//3 == 8 and 600+1500+800 == 2900
write(p)
