import sys
sys.path.insert(0, "/home/user/CastBridge/tools/learn-authoring/anglophone")
from fg_kit import *

p = mk_pack("form2-geography", "Geography — Form 2", "Form 2", "Geography", "geography",
    "Second-year Geography: latitude, longitude and time, the factors and types of climate, vegetation zones, rivers and the water cycle, volcanoes and earthquakes, and contour maps.",
    "Cameroon anglophone secondary Geography syllabus, Form 2 — to be checked against the official text", GEO_NOTE)

# ------------------------------------------------------------ CH1 latitude / longitude / time
c = p.chapter("position", "Position and time on the Earth")
globe = shapes([CIRCLE(150, 105, 80, stroke="ink"), LINE(70, 105, 230, 105, color="blue", width=3), T(255, 108, "Equator 0°", size=12, anchor="start", color="blue"),
                LINE(150, 25, 150, 185, color="red", width=3), T(150, 18, "Prime Meridian 0°", size=12, color="red"),
                LINE(82, 65, 218, 65, color="grey", width=1), LINE(82, 145, 218, 145, color="grey", width=1), T(255, 68, "Latitude 30° N", size=11, anchor="start"), T(255, 148, "Latitude 30° S", size=11, anchor="start"),
                LINE(205, 40, 205, 170, color="grey", width=1, dash=True), T(150, 202, "Longitude lines run pole to pole", size=11)], 420, 215)
L = LS(c, "lat-long-time", "Latitude, longitude and time",
    ["Define latitude and longitude and give the position of a place", "Explain why the Earth is divided into time zones", "Calculate the time difference from the difference in longitude"],
    [("text", "To find a place on the globe we use a network of imaginary lines. **Parallels of latitude** are circles round the Earth parallel to the Equator. The Equator is **0°**; the poles are **90° N** and **90° S**. **Meridians of longitude** are half-circles from pole to pole. The **Prime Meridian** (0°) passes through Greenwich, London. Longitude is measured east or west of it, up to **180°**."),
     ("key", "definition", "Latitude and longitude", "**Latitude** is the angle north or south of the Equator. **Longitude** is the angle east or west of the Prime Meridian. A position is written with latitude first, then longitude, for example **4° N, 9° E**. Cameroon lies roughly between **2° N and 13° N** and between **8° E and 16° E**."),
     ("key", "formule", "Time and longitude", "The Earth turns 360° in 24 hours, so it turns **15° in one hour** (360 ÷ 24), or **1° in 4 minutes**. Places to the **east** have the Sun earlier, so their time is **ahead**; places to the west are **behind**. Time difference (hours) = difference in longitude ÷ 15."),
     ("text", "**Local time** is set by the Sun: it is noon when the Sun is highest. Because local time changes from place to place, countries use **standard time**, based on a chosen meridian. The world is divided into **time zones**, about 15° wide. Cameroon uses one standard time for the whole country, which is one hour ahead of Greenwich Mean Time (GMT)."),
     ("key", "pieges", "Common mistakes", "- Latitude (parallels) measures north–south; longitude (meridians) measures east–west.\n- Going east, add time; going west, subtract time.\n- Do not multiply by 15 when you should divide: 30° of longitude is 30 ÷ 15 = 2 hours, not 450 hours.")],
    [("Example 1: time difference", "Town A is at 0° and town B is at 45° E. When it is 12 noon at A, what is the time at B?", ["Difference in longitude = 45°.", "Time difference = 45 ÷ 15 = 3 hours.", "B is east, so it is ahead: 12:00 + 3 h = 15:00."], "15:00 (3 p.m.)."),
     ("Example 2: going west", "A place is at 30° W. When it is 10 a.m. at the Prime Meridian, what is the time there?", ["Difference = 30°, so 30 ÷ 15 = 2 hours.", "West means behind.", "10:00 − 2 h = 08:00."], "08:00 (8 a.m.).")],
    F(globe, "Equator, Prime Meridian and some lines", "A circle with the Equator, the Prime Meridian and parallels drawn on it."),
    [MCQ("In Form 2 geography, lines of latitude are called", "parallels", ["meridians", "contours", "isobars"], "Parallels run east-west, parallel to the Equator."),
     TF("The Prime Meridian passes through Greenwich.", True, "It is 0° longitude."),
     NUM("How many degrees of longitude does the Earth turn in 3 hours?", 45, "15° per hour × 3 = 45°.", unit="°"),
     NUM("Two towns are 60° of longitude apart. What is the time difference, in hours?", 4, "60 ÷ 15 = 4 hours.", unit="hours", tier="approfondissement"),
     OPEN("Explain why places to the east of Cameroon, such as towns in East Africa, see the sunrise earlier than Cameroon does.", "The Earth rotates from west to east, so places further east turn into the sunlight before places further west; this is why their time is ahead.", "1 mark: rotation west to east; 1 mark: east sees the Sun first; 1 mark: time ahead.", points=3, tier="approfondissement"),
     PROB("It is 14:00 GMT at the Prime Meridian.",
          [("num", "What is the time at 75° E, in 24-hour clock hours?", 19, "75 ÷ 15 = 5 hours ahead; 14 + 5 = 19.", 0, "h", {}),
           ("num", "What is the hour at 45° W? (24-hour clock)", 11, "45 ÷ 15 = 3 hours behind; 14 − 3 = 11.", 0, "h", {}),
           ("mcq", "Cameroon's standard time is", "GMT + 1", ["GMT − 1", "GMT + 5", "the same as New York"], "Cameroon is one hour ahead of GMT.", {}),
           ("tf", "Places east of the Prime Meridian are ahead of GMT.", True, "They see the Sun earlier.", {})])],
    [("Latitude is measured from the", "Equator", ["Prime Meridian", "North Pole only", "Tropic of Cancer only"], "0° latitude is the Equator."),
     ("The time zone difference for each 15° of longitude is", "1 hour", ["15 hours", "4 hours", "1 minute"], "360° ÷ 24 h = 15° per hour."),
     ("Longitude is measured east and west up to", "180°", ["90°", "360°", "23½°"], "Longitude ranges from 0° to 180° E or W."),
     ("Places east of Greenwich have a time that is", "ahead of GMT", ["behind GMT", "always the same", "unrelated to the Sun"], "East means earlier Sun and later clock."),
     ("A position is written as", "latitude then longitude", ["longitude then latitude", "height then depth", "scale then key"], "For example 4° N, 9° E.")],
    ["Teacher to verify Cameroon's latitude/longitude limits (approximate), the use of GMT+1 as the national time, and the syllabus handling of local versus standard time."], tag="Form 2 position and time")

# ------------------------------------------------------------ CH2 climate
c = p.chapter("climate", "Climate and vegetation")
rel = shapes([POLY([40, 150, 140, 50, 210, 150], fill="lightgreen"), POLY([210, 150, 300, 110, 390, 150], fill="lightyellow"), RECT(10, 150, 400, 12, fill="lightblue", stroke="blue"),
              LINE(10, 90, 100, 80, color="blue", width=3, arrow="end"), T(55, 70, "Moist wind", size=12), T(95, 175, "Windward: heavy rain", size=12), T(310, 175, "Leeward: dry (rain shadow)", size=12), T(140, 40, "Mountain", size=12)], 420, 190)
L = LS(c, "climate-factors", "Factors that affect climate",
    ["Name the main factors influencing temperature and rainfall", "Explain relief rainfall and the rain shadow", "Calculate the fall of temperature with height", "Describe the climate types of Cameroon"],
    [("text", "The climate of a place depends on several factors. **Latitude**: places near the Equator receive more direct sunlight and are warmer than places near the poles. **Altitude**: temperature falls as we go higher. **Distance from the sea**: the sea warms and cools slowly, so coasts have smaller temperature ranges than inland places. **Ocean currents**, **winds** and **relief** also matter."),
     ("key", "formule", "Temperature and height", "Air gets colder with height by about **6.5 °C for every 1000 m** (about 1 °C per 150 m). If the temperature at sea level is 28 °C, the temperature at 1000 m is about 28 − 6.5 = 21.5 °C. This explains why the Grassfields around Bamenda are cooler than the coast at Limbe."),
     ("key", "retenir", "Relief rainfall", "Moist wind from the sea is forced to rise over mountains. It cools, water vapour condenses into cloud and **rain falls on the windward slope**. The air then descends on the other side, warms and is dry: the **leeward** side is a **rain shadow**. Mount Cameroon's windward coast is among the wettest places in Africa."),
     ("text", "**Climates of Cameroon.** The **south** has an equatorial climate: hot all year, with heavy rain and two rainy seasons. The **coast** is very wet, mostly from the monsoon wind from the south-west Atlantic, with a long rainy season. The **Adamawa and highlands** are cooler. The **north** has a tropical climate with one long dry season and one rainy season, and the **Far North** is drier, near the Sahel."),
     ("key", "pieges", "Common mistakes", "- It is not true that every hot place is dry: equatorial lands are hot and very wet.\n- Temperature falls with height, so it does not rise on mountains.\n- The windward side gets the rain; the leeward side is drier. Do not mix them up.")],
    [("Example 1: temperature on a hill", "At sea level the temperature is 30 °C. What is the temperature at a place 2000 m high, using 6.5 °C per 1000 m?", ["Fall for 2000 m = 2 × 6.5 = 13 °C.", "Temperature = 30 − 13 = 17 °C.", "The result is in degrees Celsius."], "17 °C."),
     ("Example 2: explain a rain shadow", "Why is the leeward side of a mountain range often dry?", ["Moist air rises on the windward side and loses its water as rain.", "When it descends on the leeward side it is warmed and has little moisture left.", "So the leeward side receives little rain."], "Because the air has lost its moisture on the windward side.")],
    F(rel, "Relief rainfall and rain shadow", "A mountain with a wind arrow on its windward side, rain there and a dry side beyond."),
    [MCQ("The side of a mountain facing the rain-bearing wind is the", "windward side", ["leeward side", "shadow side only", "river side"], "It receives relief rainfall."),
     TF("Temperature falls as altitude increases.", True, "About 6.5 °C per 1000 m."),
     NUM("The temperature at sea level is 26 °C. What is it at 1000 m (use 6.5 °C per 1000 m)? Give the answer in °C.", 19.5, "26 − 6.5 = 19.5.", tol=0.01, unit="°C"),
     NUM("At the coast, the temperature is 29 °C. What is it at 1500 m, with a fall of 6.5 °C per 1000 m?", 19.25, "1500 m: fall = 1.5 × 6.5 = 9.75; 29 − 9.75 = 19.25.", tol=0.05, unit="°C", tier="approfondissement"),
     OPEN("Explain why Bamenda is cooler than Douala, although both are in Cameroon.", "Bamenda is much higher above sea level, and temperature falls with height (about 6.5 °C per 1000 m), while Douala is on the low coast.", "1 mark: altitude; 1 mark: fall with height; 1 mark: coast is low and hotter.", points=3, tier="approfondissement"),
     PROB("A mountain range in a tropical country has sea on its south side and the rain-bearing wind comes from the south.",
          [("mcq", "Which side gets the heavy rain?", "the south (windward) slopes", ["the north (leeward) slopes", "both equally", "neither"], "The wind meets the mountain from the south.", {}),
           ("tf", "The north side is in the rain shadow.", True, "Leeward slopes are drier.", {}),
           ("num", "A town at 1300 m with sea-level temperature 28 °C: what is its temperature (6.5 °C per 1000 m)? Answer to 1 decimal place.", 19.6, "1.3 × 6.5 = 8.45; 28 − 8.45 = 19.55 ≈ 19.6.", 0.1, "°C", {}),
           ("open", "Name two factors besides altitude that affect temperature.", "Latitude, distance from the sea, ocean currents, winds and cloud cover.", "1 mark per factor.", {})])],
    [("Which factor makes the Equator hotter than the poles?", "latitude", ["longitude", "grid reference", "map scale"], "Direct sunlight is stronger near the Equator."),
     ("A rain shadow is found on the", "leeward side of mountains", ["windward side", "sea side", "equator only"], "Descending air is dry."),
     ("The temperature drop with height is about", "6.5 °C per 1000 m", ["65 °C per 100 m", "0 °C per 1000 m", "2 °C per metre"], "This is the usual rule of thumb."),
     ("The climate of southern Cameroon is mainly", "equatorial", ["desert", "polar", "Mediterranean"], "Hot and wet with two rainy seasons."),
     ("The Far North of Cameroon is generally", "drier than the south", ["wetter than the coast", "polar", "always flooded"], "It is near the Sahel.")],
    ["Teacher to verify the lapse rate used in the syllabus (6.5 °C per 1000 m or 1 °C per 150 m), the description of the climate zones of Cameroon (number of rainy seasons) and the monsoon wording."], tag="Form 2 climate")

L = LS(c, "vegetation", "Vegetation zones of Africa and Cameroon",
    ["Define natural vegetation", "Describe equatorial forest, savanna and desert vegetation", "Relate vegetation to climate", "Locate the vegetation belts in Cameroon"],
    [("text", "**Natural vegetation** is the plant cover that grows without being planted by people. It depends mainly on **climate** (temperature and rainfall) and **soil**. In Africa the vegetation forms rough belts on either side of the Equator: **equatorial forest** near the Equator, then **savanna** (tropical grassland), then **semi-desert** and **desert**, like the Sahara in the north."),
     ("key", "retenir", "Equatorial rainforest", "Hot and wet all year. Trees are tall, evergreen and close together, forming **layers**: tall emergent trees, the closed canopy, smaller trees and shrubs, and a dark forest floor. Many kinds of trees grow (mahogany, iroko, ebony). It is found in the south and east of Cameroon and in the Congo Basin."),
     ("key", "retenir", "Savanna and desert", "**Savanna**: a long dry season and a wet season. Tall grasses with scattered, flat-topped trees such as acacia and baobab; grass dries and is often burnt in the dry season. **Semi-desert and desert**: very low rain, bare ground, thorny shrubs and succulents with small leaves or thick stems to save water."),
     ("text", "In **Cameroon**, the forest covers much of the south; the **Adamawa** plateau and the northern lowlands have savanna; the **Far North** is Sahel-type steppe with thorny trees; and the **highlands** have mountain grassland and forests that change with height. The **coast** has mangrove swamps in river estuaries."),
     ("key", "attention", "Be careful", "- Savanna is not forest: grass dominates, with only scattered trees.\n- Plants in dry areas are adapted to save water (thick stems, small leaves, deep or wide roots).\n- Human activities such as farming, burning and logging have changed much natural vegetation.")],
    [("Example 1: match vegetation to climate", "A region is hot all year with over 2000 mm of rain spread through the year. Which vegetation is likely?", ["Hot and constantly wet conditions suit large trees.", "These conditions occur near the Equator.", "The vegetation is equatorial rainforest."], "Equatorial rainforest."),
     ("Example 2: adaptation", "Why do many desert plants have thick stems and small or no leaves?", ["Water is scarce in deserts.", "Thick stems store water and small leaves lose less water.", "These features are adaptations to drought."], "To store water and reduce water loss.")],
    F(cols("Vegetation belts", [("Rainforest", ["Very wet", "Tall trees", "Layers"]), ("Savanna", ["Wet + dry", "Tall grass", "Few trees"]), ("Desert", ["Very dry", "Shrubs", "Bare soil"])], w=420), "Three belts of vegetation", "Three columns describing rainforest, savanna and desert."),
    [MCQ("Which vegetation has tall grass and scattered flat-topped trees?", "savanna", ["mangrove", "equatorial rainforest", "ice cap"], "Savanna is tropical grassland."),
     TF("Mangroves grow in muddy coastal swamps in the tropics.", True, "They are found in estuaries such as the Wouri."),
     MATCH("Match each vegetation type to a typical area of Cameroon.", [("Rainforest", "South and East"), ("Savanna", "Adamawa and North"), ("Mangrove", "Coast")], "Vegetation follows climate."),
     MCQ("An adaptation of a desert plant is", "storing water in thick stems", ["growing very tall leaves", "needing constant rain", "shedding all roots"], "Water saving is key.", tier="approfondissement"),
     OPEN("Describe the layers of the equatorial rainforest and explain why the forest floor is dark.", "Emergent trees, the closed canopy, a lower layer of small trees and shrubs, and the ground. The thick canopy blocks most sunlight so little reaches the floor.", "2 marks for layers; 1 mark for the canopy blocking light.", points=3, tier="approfondissement"),
     PROB("A student compares two places: Place X (hot, rain all year) and Place Y (hot, one long dry season).",
          [("mcq", "Which vegetation is likely in X?", "rainforest", ["savanna", "desert", "tundra"], "Constant rain suits forest.", {}),
           ("mcq", "Which vegetation is likely in Y?", "savanna", ["rainforest", "polar", "tundra"], "A dry season favours grass.", {}),
           ("tf", "Grass fires are common in the dry season in savanna.", True, "Dry grass burns easily.", {}),
           ("open", "Name two ways people have changed natural vegetation in Cameroon.", "Clearing forest for farms and plantations, logging, bush burning, grazing, building roads and towns.", "1 mark per way.", {})])],
    [("Natural vegetation depends mainly on", "climate and soil", ["names of towns", "map scale", "time zones"], "Climate and soil control plant growth."),
     ("The emergent layer of the rainforest consists of", "the tallest trees", ["grass", "mosses only", "crops"], "They rise above the canopy."),
     ("The Sahara is a", "desert", ["rainforest", "mangrove coast", "wet savanna"], "It is the large desert in northern Africa."),
     ("Baobab and acacia are typical of", "savanna", ["polar regions", "mangrove coasts", "deep sea"], "They suit the dry-wet climate."),
     ("The vegetation of Cameroon's Far North is mainly", "dry steppe with thorny trees", ["thick rainforest", "ice", "mangrove only"], "It is near the Sahel.")],
    ["Teacher to verify the tree species named (mahogany, iroko, ebony), the extent of each vegetation zone in Cameroon and the syllabus wording (Sahel/Sudan/Guinea savanna)."], tag="Form 2 vegetation")

# ------------------------------------------------------------ CH3 rivers
c = p.chapter("rivers", "Rivers and the water cycle")
cyc = flow("The water cycle", ["Evaporation|from the sea", "Condensation|clouds form", "Precipitation|rain falls", "Run-off|to the sea"], per_row=4)
L = LS(c, "water-rivers", "The water cycle and the course of a river",
    ["Describe the water cycle", "Name the parts of a river system", "Describe the upper, middle and lower courses", "Name the main rivers of Cameroon"],
    [("text", "Water moves continually between the sea, the air and the land: the **water cycle**. The Sun heats water in seas, rivers and lakes and it **evaporates**; plants also release water vapour (**transpiration**). The vapour rises, cools and **condenses** into clouds. It falls as **precipitation** (rain, hail). Part of it sinks into the ground (**infiltration**), and part flows over the surface as **run-off** into streams and rivers, returning to the sea."),
     ("key", "definition", "River terms", "The **source** is where a river begins. A **tributary** is a smaller river that joins a bigger one; the meeting point is a **confluence**. The **mouth** is where the river enters the sea or a lake. A **watershed** is the high ground that separates one river basin from another. The **drainage basin** is the area drained by a river and its tributaries."),
     ("key", "retenir", "The three courses", "- **Upper course**: steep, fast; the river cuts a narrow V-shaped valley with rapids and waterfalls.\n- **Middle course**: gentler; the valley widens and the river begins to swing from side to side.\n- **Lower course**: very gentle and wide; the river forms **meanders** and a **floodplain**, and ends at a **delta** or **estuary**."),
     ("text", "**Rivers of Cameroon.** The **Sanaga**, the largest river in the country, flows to the Atlantic near Edéa. The **Wouri** enters the sea at Douala. The **Nyong** and the **Ntem** flow through the south. The **Mungo** is in the west. The **Benue** flows towards Nigeria and the Niger; the **Logone** flows to Lake Chad; and the **Cross River** crosses the South-West into Nigeria. Rivers give water, fish and transport, and some produce electricity at dams."),
     ("key", "pieges", "Common mistakes", "- Rivers do not start at the sea: the source is in the highlands.\n- A tributary joins a river; a distributary leaves it (as in a delta).\n- A waterfall belongs to the steep upper course, a floodplain to the lower course.")],
    [("Example 1: find the course", "A river flows slowly over a wide flat plain and bends in large loops. In which course is it?", ["Slow flow, wide plain and loops are signs of gentle slope.", "Meanders form in the lower course.", "So it is in the lower course."], "The lower course."),
     ("Example 2: the water cycle", "Explain how water from the Atlantic can fall as rain on Mount Cameroon.", ["Sea water evaporates in the heat and the vapour is carried inland by the wind.", "Rising over the mountain, it cools and condenses into cloud.", "Then it falls as rain on the slopes."], "Evaporation, wind transport, condensation and precipitation.")],
    F(cyc, "The water cycle", "Four boxes showing evaporation, condensation, precipitation and run-off."),
    [MCQ("The point where two rivers meet is a", "confluence", ["watershed", "delta", "mouth"], "A tributary joins the main river at a confluence."),
     TF("A V-shaped valley is typical of the upper course of a river.", True, "The steep river cuts down."),
     MATCH("Match each term with its meaning.", [("Source", "Where a river begins"), ("Mouth", "Where it enters the sea"), ("Tributary", "A smaller river joining a bigger one")], "River vocabulary."),
     MCQ("Which of these features belongs to the lower course?", "meanders and floodplain", ["waterfalls", "V-shaped valley", "rapids only"], "The lower course is wide and gentle.", tier="approfondissement"),
     OPEN("Describe the changes in a river from the upper to the lower course.", "In the upper course the river is steep and narrow with a V-shaped valley, rapids and waterfalls; in the middle course the valley widens; in the lower course the river is slow and wide, with meanders, a floodplain and a delta or estuary.", "1 mark per course described.", points=3, tier="approfondissement"),
     PROB("A river rises in the highlands near Bamenda and flows to the sea.",
          [("mcq", "The place where it begins is its", "source", ["mouth", "delta", "watershed"], "Source is the start.", {}),
           ("tf", "A waterfall is most likely in the upper course.", True, "Steep slope, hard rock.", {}),
           ("mcq", "Which river enters the sea at Douala?", "Wouri", ["Benue", "Logone", "Nile"], "The Wouri estuary.", {}),
           ("open", "Give two uses of rivers to people in Cameroon.", "Drinking and farming water, fishing, transport, hydroelectric power, sand and gravel.", "1 mark per use.", {})])],
    [("Water changing from liquid to vapour is", "evaporation", ["condensation", "precipitation", "infiltration"], "Heat evaporates water."),
     ("The Benue flows towards", "Nigeria", ["Gabon", "Congo", "Chad's capital"], "It joins the Niger system."),
     ("A drainage basin is", "the area drained by a river and its tributaries", ["the sea", "a type of rain", "a hill"], "Water runs towards one river."),
     ("The stage in which a river is wide and gentle with a floodplain is the", "lower course", ["upper course", "source", "watershed"], "Meanders and deposition are typical."),
     ("A delta forms at", "a river mouth", ["the source", "a waterfall", "a mountain peak"], "The river deposits sediment there.")],
    ["Teacher to verify the names and directions of flow of Cameroon's rivers (Sanaga near Edéa, Wouri at Douala, Benue to Nigeria, Logone to Lake Chad) and the 'largest river' statement."], tag="Form 2 rivers")

# ------------------------------------------------------------ CH4 volcanoes
c = p.chapter("earth-forces", "Volcanoes and earthquakes")
vol = shapes([POLY([60, 170, 170, 70, 190, 70, 300, 170], fill="lightorange"), RECT(170, 60, 20, 12, fill="red", stroke="red"), T(180, 50, "Crater", size=12),
              LINE(180, 170, 180, 90, color="red", width=4), T(250, 125, "Cone", size=12), T(215, 150, "Vent", size=12, anchor="start"), CIRCLE(180, 190, 22, fill="red", stroke="red"), T(250, 195, "Magma chamber", size=12, anchor="start")], 340, 225)
L = LS(c, "volcanoes-earthquakes", "Volcanoes, earthquakes and the Earth's structure",
    ["Describe the layers of the Earth", "Explain how a volcano erupts and name its parts", "Describe the causes and effects of earthquakes", "Give examples in Cameroon and Africa"],
    [("text", "The Earth has three main layers. The thin outer **crust** is solid rock. Below it is the **mantle**, very hot and partly molten. At the centre is the **core**, made mostly of iron and nickel. The crust is broken into large pieces called **plates** that move very slowly. Where plates meet, collide or separate, we find most **volcanoes**, **earthquakes** and **fold mountains**."),
     ("key", "retenir", "Volcano", "A **volcano** is an opening in the crust through which **magma** (called **lava** when it reaches the surface), gas and ash escape. Magma rises from the **magma chamber** through the **vent** and leaves by the **crater**. Layers of lava and ash build up a **cone**. A volcano can be **active**, **dormant** (asleep) or **extinct** (dead)."),
     ("key", "retenir", "Earthquake", "An **earthquake** is a shaking of the ground caused by sudden movement of rocks along cracks called faults. The point underground where it starts is the **focus**; the point on the surface above it is the **epicentre**. A **seismograph** records the waves. Effects: collapsed buildings, landslides, fires and, at sea, huge waves called **tsunamis**."),
     ("text", "**Cameroon.** Mount Cameroon, in the South-West, is an active volcano that has erupted several times in modern times. It belongs to the **Cameroon Volcanic Line**, a chain that includes Mount Manengouba, the Bamboutos and Mount Oku. In 1986 a huge release of carbon dioxide gas from the crater **Lake Nyos** killed many people, a reminder that volcanic regions bring hazards as well as fertile soils and beautiful scenery."),
     ("key", "attention", "Be careful", "- Magma is underground; lava is magma on the surface.\n- The focus is under the ground; the epicentre is on the surface.\n- A volcano that is quiet is not always extinct: dormant volcanoes can erupt again.")],
    [("Example 1: focus and epicentre", "An earthquake starts 10 km below the surface. What is the point on the surface directly above called?", ["The origin underground is the focus.", "The place directly above it on the surface is where shaking is strongest.", "That point is the epicentre."], "The epicentre."),
     ("Example 2: advantages and risks", "Give one benefit and one risk of living near a volcano.", ["Volcanic rock weathers into fertile soil.", "An eruption can send lava, ash and gas over farms and homes.", "So the benefit is fertile soil and the risk is eruption."], "Benefit: fertile soil. Risk: eruption.")],
    F(vol, "A volcano in cross-section", "A cone-shaped volcano with a crater, a vent leading down to a magma chamber."),
    [MCQ("The thin, solid outer layer of the Earth is the", "crust", ["mantle", "core", "atmosphere"], "The crust is only a few tens of kilometres thick."),
     TF("The epicentre of an earthquake is on the surface of the Earth.", True, "It lies directly above the focus."),
     MATCH("Match each term with its meaning.", [("Crater", "Bowl-shaped opening at the top of a volcano"), ("Seismograph", "Instrument that records earthquakes"), ("Lava", "Magma on the surface")], "Volcano and earthquake vocabulary."),
     MCQ("Which Cameroonian mountain is an active volcano?", "Mount Cameroon", ["Mount Oku", "Mount Kala", "Adamawa Plateau"], "Mount Cameroon has erupted in modern times.", tier="approfondissement"),
     OPEN("Explain two effects of a volcanic eruption on people and the environment.", "Lava and ash can destroy houses, farms and roads and may kill people and animals; gases can pollute the air. Later the ash weathers into fertile soils that support farming.", "1 mark per effect, 1 mark for one positive and one negative effect.", points=3, tier="approfondissement"),
     PROB("A class studies the structure of a volcano and of the Earth.",
          [("mcq", "Magma rises through the", "vent", ["cone", "crust only", "river"], "The vent is the pipe.", {}),
           ("tf", "A dormant volcano may erupt again.", True, "Dormant means temporarily quiet.", {}),
           ("mcq", "Which layer of the Earth is mostly iron and nickel?", "core", ["crust", "mantle", "soil"], "The core is metallic.", {}),
           ("open", "Describe two precautions for people living in an earthquake zone.", "Build strong buildings, know safe places and escape routes, teach drills at school, and stay away from windows and buildings during shaking.", "1 mark per precaution.", {})])],
    [("Molten rock below the surface is called", "magma", ["lava", "ash", "granite"], "It becomes lava on the surface."),
     ("The layer between crust and core is the", "mantle", ["soil", "atmosphere", "magma chamber"], "The mantle is hot and thick."),
     ("A volcano that has not erupted for a long time but could do so again is", "dormant", ["extinct", "active forever", "young"], "Dormant volcanoes are asleep."),
     ("Giant sea waves caused by earthquakes are", "tsunamis", ["tides", "monsoons", "meanders"], "Tsunamis follow undersea quakes."),
     ("Lake Nyos is a", "crater lake", ["river mouth", "desert", "dam only"], "It lies in a volcanic crater in the North-West.")],
    ["Teacher to verify the 1986 Lake Nyos event details (gas release; casualty figures deliberately not given), the list of mountains on the Cameroon Volcanic Line and the eruption history of Mount Cameroon."], tag="Form 2 volcanoes")

# ------------------------------------------------------------ CH5 contours
c = p.chapter("relief-maps", "Relief on maps")
cont = shapes([CIRCLE(190, 105, 85, stroke="brown"), CIRCLE(170, 105, 55, stroke="brown"), CIRCLE(150, 105, 25, stroke="brown"), T(190, 25, "100 m", size=11), T(196, 52, "200 m", size=11), T(190, 175, "100 m", size=11),
               T(172, 78, "300 m", size=11), T(150, 109, "400 m", size=11), T(310, 60, "Gentle slope: lines far apart", size=11), T(60, 40, "Steep:", size=11), T(60, 55, "lines close", size=11), T(310, 175, "East side", size=11)], 420, 200)
L = LS(c, "contours", "Contours, slopes and gradient",
    ["Define a contour line and contour interval", "Recognise steep and gentle slopes, hills, valleys and spurs on a map", "Calculate the gradient between two points"],
    [("text", "A **contour line** is a line on a map joining all places of the **same height** above sea level. The **contour interval** is the vertical distance between two neighbouring contours, for example 20 m. A **spot height** gives the height of a single point, and a **trigonometrical point** is a surveyed point on high ground."),
     ("key", "retenir", "Reading contours", "- Lines **close together**: a **steep** slope. Lines **far apart**: a **gentle** slope.\n- Closed circles with rising numbers: a **hill** or peak.\n- **V-shapes pointing uphill**: a **valley** (a river often flows in it); V-shapes pointing downhill: a **spur**.\n- Evenly spaced lines: a **uniform** slope."),
     ("key", "formule", "Gradient", "**Gradient** = vertical interval ÷ horizontal distance, with both in the same unit. If a road rises 50 m over a horizontal distance of 1000 m, the gradient is 50 ÷ 1000 = 1 in 20 (1 : 20). Use the scale of the map to convert the map distance into metres."),
     ("text", "A **cross-section** (profile) shows the shape of the land along a line: draw the line on the map, mark where it crosses each contour, then plot the heights on a graph. **Intervisibility** asks whether you can see from one point to another: if a hill is higher than the line of sight between them, you cannot."),
     ("key", "pieges", "Common mistakes", "- Do not read the interval from the number of lines: use the numbers written on them.\n- Convert units before dividing (all in metres).\n- A gradient of 1 in 20 is gentler than 1 in 5.")],
    [("Example 1: gradient", "A path climbs 40 m over a horizontal distance of 800 m. Find the gradient as 1 in n.", ["Gradient = 40 ÷ 800 = 1/20.", "That means a rise of 1 m for every 20 m along.", "So the gradient is 1 in 20."], "1 in 20."),
     ("Example 2: which slope is steeper?", "Slope A has contours 1 mm apart; slope B has contours 5 mm apart (same map, same interval). Which is steeper?", ["Closer contours mean the height changes over a shorter distance.", "A has the closer contours.", "So A is steeper."], "Slope A.")],
    F(cont, "Contours of a hill", "Concentric contour rings with the closest lines on the west side."),
    [MCQ("A line on a map joining points of equal height is a", "contour", ["meridian", "river", "route"], "Contours show relief."),
     TF("Contours that are very close together show a steep slope.", True, "The height changes quickly."),
     NUM("A road climbs 60 m in a horizontal distance of 1200 m. What is n in the gradient 1 in n?", 20, "1200 ÷ 60 = 20.", unit=None),
     NUM("A map has scale 1 : 50 000 and 2 cm separate two points on the map. How far apart are they on the ground, in metres?", 1000, "2 cm × 500 m per cm = 1000 m.", unit="m", tier="approfondissement"),
     OPEN("Explain how to recognise a valley on a contour map.", "The contour lines form V-shapes or U-shapes whose points face uphill, towards higher ground, and a stream usually runs along the middle of the V.", "1 mark: V-shape; 1 mark: points uphill; 1 mark: river.", points=3, tier="approfondissement"),
     PROB("A hill has contours at 100 m, 200 m and 300 m. A path from the 100 m contour to the 300 m contour is 2 km long on the ground.",
          [("num", "How many metres does the path climb?", 200, "300 − 100 = 200 m.", 0, "m", {}),
           ("num", "Give the gradient as 1 in n (use metres).", 10, "2 km = 2000 m; 2000 ÷ 200 = 10, so the gradient is 1 in 10.", 0, None, {}),
           ("mcq", "If the contours were twice as close together, the slope would be", "steeper", ["gentler", "flat", "unchanged"], "Closer contours mean a steeper slope.", {}),
           ("tf", "A spot height is a number that gives the height of a point.", True, "Spot heights mark exact points.", {})])],
    [("The vertical distance between two contours is the", "contour interval", ["scale", "grid", "key"], "It is usually the same across a map."),
     ("A gentle slope is shown by contours that are", "far apart", ["close together", "red", "broken"], "Gentle slopes spread the lines out."),
     ("The gradient 1 in 10 means", "a rise of 1 m for every 10 m", ["a rise of 10 m for every 1 m", "no rise", "a fall of 10 m"], "It compares rise to horizontal distance."),
     ("A cross-section shows", "the shape of the land along a line", ["the climate", "the population", "the route of rivers"], "It is a side view of the relief."),
     ("V-shaped contours pointing uphill show", "a valley", ["a peak", "a lake", "a road"], "Contours bend up valleys.")],
    ["Teacher to verify the exact conventions used in the Form 2 syllabus (V-shaped contours for valleys and spurs, intervisibility) and the worked gradient examples."], tag="Form 2 contours")

p.write()
