import sys
sys.path.insert(0, "/home/user/CastBridge/tools/learn-authoring/anglophone")
from fe_kit import *

p = english_pack("form4-english", 4,
    "A fourth-year secondary English course preparing for the O Level cycle: error correction, sentence transformation, gerunds and infinitives, advanced comprehension, summary practice, word formation and proverbs, discursive essays, articles and letters to the editor, complaint letters, narrative writing and listening, with Cameroonian examples and original exercises.",
    "Cameroon secondary school English Language, Form 4 (anglophone sub-system) — scope and order to be checked against the official programme and the class textbook")
REF = "Form 4 English Language (to be checked against the official programme)"

g = p.chapter("ch-grammar", "Grammar: accuracy and sentence transformation", REF)

LS(g, "error-correction", "Correcting common errors", 26,
   ["Recognise the commonest grammar and usage errors in Cameroonian English writing.", "Correct errors of tense, agreement, articles, prepositions and word choice.", "Proofread your own work with a checklist."],
   [tx("Most marks lost in composition and grammar are lost through **a small number of repeated errors**. Learn to spot them and your accuracy will improve quickly. This lesson collects the errors that teachers meet most often and gives you a **proofreading checklist**."),
    ky("definition", "Frequent errors and their corrections",
       "- **Agreement:** *The list of names are on the board* → **is**.\n- **Tense:** *Yesterday I go to the market* → **went**.\n- **Article:** *She is teacher* → **a teacher**; *I went to the church* (to worship) → *to church*.\n- **Preposition:** *discuss about* → **discuss**; *married with* → **married to**; *depend of* → **depend on**.\n- **Plural/uncountable:** *advices, informations, furnitures* → **advice, information, furniture**.\n- **Word order:** *She asked where was I* → **where I was**."),
    ky("definition", "Words that are often confused",
       "- **advice** (noun) / **advise** (verb)\n- **accept** (receive) / **except** (apart from)\n- **affect** (verb, influence) / **effect** (noun, result)\n- **lose** (verb) / **loose** (not tight)\n- **its** (belongs to it) / **it's** (it is)\n- **who's** (who is) / **whose** (belonging to whom)\n- **principal** (head of a school, chief) / **principle** (a rule)\n- **practice** (noun) / **practise** (verb, British spelling)."),
    fg(flow("A proofreading checklist", ["Verbs: tense and agreement", "Nouns: plurals, articles", "Prepositions and word order", "Spelling, capitals, punctuation"]),
       "Read your work four times, once for each point.", "A flowchart of four checks for proofreading: verbs, nouns, prepositions and word order, and spelling capitals and punctuation."),
    ky("pieges", "Common mistakes when correcting",
       "- Changing the meaning while correcting.\n- Correcting the wrong word and leaving the real error.\n- Introducing a new mistake while correcting (for example, writing *a advice* for *an advice*).\n- Forgetting that a sentence may have more than one error.\n- Not reading the sentence aloud: your ear often detects the mistake."),
    exm("Example 1: one error", "Correct: *The principal gave us many advices about the exams.*",
        ["*Advice* is uncountable: no plural and no *many*.", "Use *a lot of / some advice*."], "The principal gave us a lot of advice about the exams."),
    exm("Example 2: two errors", "Correct: *She asked me where was the station and discussed about the road.*",
        ["Reported question: statement order: *where the station was*.", "*Discuss* takes no preposition: *discussed the road*."], "She asked me where the station was and discussed the road.")],
   [m("Choose the correct sentence.", "He gave me some useful information.", ["He gave me some useful informations.", "He gave me many useful information.", "He gave me an useful informations."], "Information is uncountable."),
    m("Which word completes: *The new rule will ___ all pupils.*", "affect", ["effect", "accept", "except"], "Affect is the verb meaning influence."),
    t("*We discussed about the problem* is correct English.", False, "Discuss does not take a preposition."),
    m("Choose the correct sentence.", "She is married to a teacher.", ["She is married with a teacher.", "She is marry to a teacher.", "She is married at a teacher."], "Married to."),
    m("*___ your book on the table?* Choose the correct word.", "Whose", ["Who's", "Whos", "Who is it"], "Whose = belonging to whom; Who's = who is."),
    o("Correct all the errors in this paragraph and rewrite it:\n*Yesterday I go to the market with my mother. We buyed many fishes and some vegetable. The seller give us advices about cooking. Me and my sister was very happy.*",
      "Yesterday I went to the market with my mother. We bought some fish and some vegetables. The seller gave us some advice about cooking. My sister and I were very happy.",
      ["1 mark: went.", "1 mark: bought / fish / vegetables.", "1 mark: gave / advice.", "1 mark: My sister and I were."])],
   [sc("*Information* is...", "uncountable", ["always plural", "a verb", "an adverb"], "No plural."),
    sc("Which is the correct preposition? *depend ___ the weather*", "on", ["of", "from", "to"], "Depend on."),
    sc("*Its* means...", "belonging to it", ["it is", "it has not", "it were"], "Possessive."),
    sc("The verb meaning *to give counsel* is...", "advise", ["advice", "advices", "advisor"], "Advice (noun), advise (verb)."),
    sc("Before you hand in your work you should...", "proofread it", ["close the exam book", "rewrite the title", "shout"], "Proofreading catches errors.")])

LS(g, "sentence-transformation", "Sentence transformation", 28,
   ["Rewrite sentences with the same meaning using a given structure.", "Use too...to, enough, so...that, despite, unless and inversion.", "Keep the meaning and grammar correct."],
   [tx("In a **sentence transformation** you rewrite a sentence in a different way without changing its meaning, often beginning with words you are given. These exercises test your control of grammar. Do not change the meaning, and keep the **tense** the same."),
    ky("definition", "Common patterns",
       "- **too ... to:** *He is too tired to walk* = *He is so tired that he cannot walk.*\n- **enough:** *She is old enough to vote.* = *She is so old that she can vote.*\n- **so ... that / such ... that:** *It was such a long road that we rested twice.*\n- **despite / in spite of + noun or -ing:** *Despite the rain, we played.* = *Although it rained, we played.*\n- **unless = if not:** *Unless you study, you will fail* = *If you do not study, you will fail.*"),
    ky("definition", "Inversion for emphasis",
       "After certain negative adverbs the **verb comes before the subject**:\n- **No sooner ... than:** *No sooner had he sat down than the bell rang.*\n- **Hardly ... when:** *Hardly had we arrived when it began to rain.*\n- **Not only ... but also:** *Not only did she win, but she also broke the record.*\n- **Never / Rarely:** *Rarely does it snow in Douala.*\nThese forms are formal; use them to vary your writing."),
    fg(cols("Equivalent structures", ["Original", "Transformed"], [["too tired to walk", "so tired that he could not"], ["Despite the rain", "Although it rained"], ["Unless you run", "If you do not run"], ["No sooner had...", "...than"]], w=450),
       "Different structure, same meaning.", "A table showing equivalent structures: too tired to walk and so tired that he could not; despite the rain and although it rained; unless you run and if you do not run; no sooner had followed by than."),
    ky("pieges", "Common mistakes",
       "- Changing the meaning: *He is too tired to walk* ≠ *He is tired but can walk*.\n- Keeping *but* after *although*: *Although it rained, but we played* is wrong.\n- Forgetting inversion: *No sooner he arrived than* → **No sooner had he arrived than**.\n- Using *despite of* (the correct forms are *despite* or *in spite of*).\n- Changing the tense of the verb."),
    exm("Example 1: too...to", "Rewrite with *so...that*: *The soup is too hot to drink.*",
        ["*too hot to drink* means *so hot that it cannot be drunk / that we cannot drink it*.", "Keep the same tense (present)."], "The soup is so hot that we cannot drink it."),
    exm("Example 2: despite", "Rewrite with *despite*: *Although he was ill, he came to school.*",
        ["*Despite* is followed by a noun or -ing.", "*he was ill* → *his illness* or *being ill*."], "Despite his illness, he came to school.")],
   [m("*She is too young to vote* means...", "She is so young that she cannot vote.", ["She is old enough to vote.", "She is young but votes.", "She votes because she is young."], "Too ... to is negative."),
    m("Which is equivalent to *Unless you hurry, you will be late*?", "If you do not hurry, you will be late.", ["If you hurry, you will be late.", "Because you hurry, you will be late.", "Although you hurry, you will be late."], "Unless = if not."),
    t("*Despite of the rain* is correct.", False, "Use despite or in spite of."),
    m("Complete: *No sooner ___ he arrived than it began to rain.*", "had", ["has", "did", "was"], "No sooner had he arrived."),
    m("Choose the correct sentence.", "Not only did she win, but she also broke the record.", ["Not only she won but she also broke the record.", "Not only she did win, but also she broke the record.", "Not only won she, she broke the record."], "Inversion after not only."),
    o("Rewrite each sentence so that it means the same:\n1. The bag is too heavy for me to carry. (so ... that)\n2. Although it was raining, they continued the match. (Despite)\n3. If you do not revise, you will fail. (Unless)\n4. As soon as the teacher entered, the pupils stood up. (No sooner)",
      "1. The bag is so heavy that I cannot carry it. 2. Despite the rain, they continued the match. 3. Unless you revise, you will fail. 4. No sooner had the teacher entered than the pupils stood up.",
      ["1 mark each: correct structure and unchanged meaning.", "Sentence 4: inversion with had and than."])],
   [sc("*Unless* means...", "if not", ["because", "although", "when"], "Unless = if not."),
    sc("*Despite* is followed by...", "a noun or -ing form", ["a full clause", "a verb in the past", "that"], "Despite + noun or -ing."),
    sc("*too ... to* has a...", "negative meaning (cannot)", ["positive meaning", "question meaning", "plural meaning"], "Too to implies cannot."),
    sc("*Hardly had we arrived when...* shows...", "inversion", ["a question", "passive voice", "reported speech"], "Verb before subject."),
    sc("In a transformation exercise you must keep...", "the same meaning", ["a different meaning", "no verbs", "the same length"], "Same meaning.")])

LS(g, "gerunds-infinitives", "Gerunds, infinitives and participles", 26,
   ["Choose the gerund (-ing) or the infinitive after common verbs.", "Use participle phrases to join sentences.", "Avoid dangling participles."],
   [tx("Some verbs are followed by an **-ing form** (the **gerund**) and others by the **infinitive** (*to + verb*). Choosing wrongly is a very common error. This lesson also looks at **participle phrases** which make writing more compact."),
    ky("definition", "Which form follows?",
       "- **Verb + -ing:** *enjoy, avoid, finish, mind, suggest, practise, keep, deny, admit, consider*: *She enjoys singing. We finished cooking.*\n- **Verb + to-infinitive:** *want, decide, hope, promise, manage, refuse, agree, plan, learn, afford*: *He decided to leave. She promised to help.*\n- **Prepositions** are followed by -ing: *interested in learning, good at swimming, look forward to meeting you.*\n- **Modals** take the bare infinitive: *can swim, must go.*"),
    ky("definition", "Verbs that can take both",
       "Some verbs change meaning:\n- **stop doing** (end the action) / **stop to do** (pause in order to): *He stopped smoking. He stopped to buy water.*\n- **remember doing** (recall the past) / **remember to do** (not forget a task): *I remember locking the door. Remember to lock the door.*\n- **try doing** (experiment) / **try to do** (make an effort)."),
    fg(cols("Gerund or infinitive?", ["-ing form", "to + verb"], [["enjoy", "want"], ["avoid", "decide"], ["finish", "promise"], ["suggest", "manage"]], w=420),
       "Learn the common verbs in each column.", "A table with verbs followed by the -ing form on the left, enjoy, avoid, finish and suggest, and verbs followed by to plus verb on the right, want, decide, promise and manage."),
    ky("pieges", "Common mistakes",
       "- *She enjoys to sing* → **enjoys singing**.\n- *He wants going* → **wants to go**.\n- *I look forward to meet you* → **to meeting** (to is a preposition here).\n- **Dangling participle:** *Walking along the road, the rain began.* (who was walking?) → *Walking along the road, we felt the rain begin.*\n- *Suggest to go* → **suggest going**."),
    exm("Example 1: gerund or infinitive", "Complete: *Ndi decided (go / to go / going) to Limbe and enjoys (swim / to swim / swimming) there.*",
        ["*decide* is followed by the infinitive: **to go**.", "*enjoy* is followed by the gerund: **swimming**."], "decided to go ... enjoys swimming"),
    exm("Example 2: a participle phrase", "Join: *Mama Ngum walked to the market. She carried a heavy basket.*",
        ["Use a participle phrase for the second action done at the same time.", "*Carrying a heavy basket, Mama Ngum walked to the market.*"], "Carrying a heavy basket, Mama Ngum walked to the market.")],
   [m("Choose the correct sentence.", "She enjoys singing.", ["She enjoys to sing.", "She enjoys sing.", "She enjoys to singing."], "Enjoy + -ing."),
    m("Choose the correct sentence.", "He decided to leave.", ["He decided leaving.", "He decided leave.", "He decided for leave."], "Decide + to-infinitive."),
    t("*I look forward to meeting you* is correct.", True, "To is a preposition: meeting."),
    m("*He stopped ___ water because he was thirsty.* (he paused in order to buy)", "to buy", ["buying", "buy", "bought"], "Stop to do = pause in order to do."),
    m("Which is a correct participle phrase sentence?", "Walking home, we saw a snake.", ["Walking home, a snake was seen.", "Walking home, the snake crawled.", "Walking home, it was a snake."], "The doer of walking (we) is the subject."),
    o("Complete each sentence with the gerund or infinitive of the verb in brackets, then write one sentence of your own using a participle phrase:\n1. She avoids (eat) fried food.\n2. They promised (visit) us.\n3. We are interested in (learn) French.\n4. I remember (lock) the door.",
      "1. eating 2. to visit 3. learning 4. locking. Own sentence: Standing on the bridge, I watched the river flow.",
      ["1 mark each for four correct forms.", "1 mark: a correct participle phrase whose doer is the subject."])],
   [sc("After *enjoy* we use...", "the -ing form", ["to + verb", "the past", "the plain verb"], "Enjoy + -ing."),
    sc("After a preposition we use...", "the -ing form", ["to + verb", "the infinitive only", "the past participle"], "Prepositions take -ing."),
    sc("*Promise* is followed by...", "to + verb", ["verb + -ing", "that only", "an adjective"], "Promise to do."),
    sc("A dangling participle is a...", "participle with no clear doer", ["correct form", "type of noun", "a question"], "It is an error."),
    sc("*Stop doing* means...", "end an action", ["pause to do something", "start", "try"], "Stop doing = end.")])

s = p.chapter("ch-reading", "Reading, summary and vocabulary", REF)

LS(s, "comprehension-advanced", "Advanced comprehension: attitude, style and purpose", 28,
   ["Identify the writer's attitude and purpose.", "Comment on style: diction, sentence length and imagery.", "Answer inference and own-words questions with evidence."],
   [tx("**The Last Bus from Bamenda**\nThe bus left at dusk, already carrying more passengers than it had been built for. A woman held a live hen on her lap; a boy slept with his head on a sack of cocoyams. The driver, whistling, steered round every pothole as if each one were an old friend. Beside the window an elderly teacher watched the lights of the town shrink behind him. He had come to this town forty years ago with one suitcase and a head full of plans. Now he carried a smaller suitcase, a larger silence, and the quiet certainty that he had spent his life well."),
    ky("definition", "Attitude, purpose and style",
       "- **Purpose:** why the writer writes (to inform, describe, entertain, persuade, reflect).\n- **Attitude/tone:** *affectionate, nostalgic, humorous, critical*. Here the tone is **gentle and reflective**.\n- **Style:** how the writer writes: **diction** (*dusk, silence, certainty*), **sentence length** (a long sentence of observation, then a short, calm one), **imagery** (*as if each one were an old friend*, a simile that makes the driver warm and the journey familiar).\nQuote, name the feature, **explain the effect**."),
    fg(tree("Commenting on style", "Style", [("Diction", "word choice"), ("Sentences", "length, rhythm"), ("Imagery", "simile, metaphor")], h=185),
       "Quote the words, then explain what they make the reader feel or think.", "A diagram with Style at the top and three arrows to Diction (word choice), Sentences (length, rhythm) and Imagery (simile, metaphor)."),
    ky("methode", "Answering 'explain the effect'",
       "1. **Quote** the key words (short).\n2. **Name** the technique (simile, contrast, short sentence...).\n3. **Explain** the effect on the reader: *The contrast between the smaller suitcase and the larger silence suggests that the teacher has lost things but gained peace.*\nDo not just say *it makes the passage interesting*."),
    ky("pieges", "Common mistakes",
       "- Retelling the passage when asked about style.\n- Naming a technique without explaining its effect.\n- Missing the **irony or contrast**.\n- Confusing the **narrator's** attitude with the character's.\n- Over-long quotations: use two or three key words."),
    exm("Example 1: the writer's attitude", "What attitude to the teacher does the writer show? Support your answer.",
        ["Clue: the writer describes him quietly: *the lights of the town shrink behind him; a larger silence; certainty that he had spent his life well*.", "Conclusion: respect and gentle admiration, with a little sadness."], "The writer is respectful and gently admiring, with a touch of sadness."),
    exm("Example 2: explain the effect", "Explain the effect of *a smaller suitcase, a larger silence*.",
        ["Figure: **contrast** (smaller/larger) with parallel structure.", "Effect: shows that he has fewer possessions but more inner peace and reflection."], "The contrast suggests he now owns less but has gained a deep, calm reflection.")],
   [m("The overall tone of the passage is...", "gentle and reflective", ["angry", "comic", "fearful"], "The teacher quietly looks back on his life."),
    m("*As if each one were an old friend* is a...", "simile", ["metaphor", "hyperbole", "pun"], "As if is a comparison, a simile."),
    t("The passage suggests that the teacher regrets his life.", False, "He has the quiet certainty that he spent it well."),
    m("What does the phrase *a larger silence* suggest?", "He is now more reflective and quiet.", ["The bus is noisy.", "He is angry.", "He lost his suitcase."], "It contrasts with the smaller suitcase."),
    m("The detail of the hen and the sleeping boy mainly shows that...", "the bus is crowded and everyday", ["the passengers are rich", "the bus is new", "the journey is short"], "It paints the busy, ordinary scene."),
    o("In four or five sentences, comment on the writer's use of *the driver, whistling, steered round every pothole as if each one were an old friend*. Say what it shows about the driver and the mood of the passage.",
      "The simile *as if each one were an old friend* shows that the driver knows the road perfectly, treating even its potholes with affection. The whistling adds a cheerful, relaxed note. It makes the journey seem familiar and warm, and contrasts gently with the teacher's quiet reflection, so the mood is calm and affectionate.",
      ["1 mark: simile identified.", "1 mark: what it shows about the driver (skill, familiarity).", "1 mark: mood explained (warm, relaxed).", "1 mark: own words, quotation, clear writing."])],
   [sc("The purpose of a passage means...", "why the writer wrote it", ["how long it is", "its title", "its rhyme"], "Purpose."),
    sc("A good comment on style names the feature and...", "explains its effect", ["lists its length", "repeats the story", "gives your name"], "Always explain effect."),
    sc("Diction means...", "choice of words", ["number of lines", "rhyme", "plot"], "Diction."),
    sc("A contrast is...", "a pairing of opposite ideas", ["a repeated word", "a rhyme", "a question"], "Contrast."),
    sc("Short quotations are better than...", "copying a whole paragraph", ["quoting two words", "using your own words", "naming the technique"], "Quote precisely.")])

LS(s, "summary-practice", "Summary practice: selecting and linking points", 28,
   ["Select main points under a specific question.", "Paraphrase and link points in continuous prose.", "Meet word limits and avoid copying."],
   [tx("In Form 4 summary tasks are more demanding: the question asks for **specific** information (*Summarise the reasons given for...*) and a **word limit** (for example 80 words). Only points **relevant to the question** earn marks. This lesson shows a method for choosing and linking the points."),
    ky("methode", "Method",
       "1. Read the question: underline the **key words** (*reasons, problems, effects, advice*).\n2. Mark the passage with a **number** each time you find a relevant point.\n3. **Rewrite** each point in **fewer** words, using your own vocabulary (*numerous* for *a great number of*).\n4. **Join** the points with linking words (*because, so, however, also, as a result*).\n5. **Count** your words; remove adjectives, examples and repeated ideas."),
    fg(flow("From passage to summary", ["Underline key words in the question", "Number the relevant points", "Paraphrase and shorten each point", "Link in one paragraph; count words"]),
       "Only points that answer the question earn marks.", "A flowchart of four steps: underline key words in the question, number the relevant points, paraphrase and shorten each point, then link them in one paragraph and count the words."),
    ky("methode", "Shortening techniques",
       "- Replace a phrase by a word: *at the present time* → *now*; *in the event that* → *if*; *a large number of* → *many*.\n- Use one **verb** instead of a noun phrase: *make a decision* → *decide*.\n- Remove **examples and comparisons**.\n- Combine two points in one sentence with *and* or a participle."),
    ky("pieges", "Common mistakes",
       "- Writing about the passage in general instead of the **specific question**.\n- **Lifting** sentences and phrases.\n- Exceeding the word limit (the examiner stops counting).\n- Using bullet points.\n- Including your own comments or an introduction like *The writer says that...*."),
    exm("Example 1: shorten", "Shorten: *At the present time, a large number of people living in towns make a decision to grow vegetables in their back yards.*",
        ["*At the present time* → *now*; *a large number of* → *many*; *make a decision* → *decide*.", "Remove *living in towns* only if not needed; keep core meaning."], "Many town dwellers now decide to grow vegetables in their yards."),
    exm("Example 2: choose the points", "Question: *Summarise the problems caused by the broken bridge.* Passage: *The bridge broke after the rains. Farmers could not sell cocoa. Children missed school. The bridge was built in 1980 by the council. The nurse could not visit the village.* Which points count?",
        ["Relevant: farmers could not sell, children missed school, nurse could not visit (problems).", "Not relevant: when and by whom the bridge was built."], "farmers could not sell cocoa; children missed school; the nurse could not visit")],
   [m("The first step in a summary is to...", "read the question and underline key words", ["count the words", "copy the first line", "write the conclusion"], "Know what is asked."),
    m("Which is the best shortening of *a large number of*?", "many", ["a great deal", "few", "some of"], "Many has the same meaning."),
    t("Examples and comparisons should normally be left out of a summary.", True, "They are not main points."),
    m("A good summary is written as...", "one continuous paragraph", ["a list of bullets", "a table", "a dialogue"], "Continuous prose."),
    m("Which phrase should NOT begin a summary?", "The writer says that...", ["Many people...", "The main causes were...", "Firstly,"], "It wastes words."),
    o("Summarise in about 40 words the problems caused by traffic jams in Douala according to this paragraph: *Traffic jams in Douala make people late for work. Drivers waste fuel and money. The air is polluted by smoke, so many people cough. Accidents increase because drivers are impatient. Last year the city council promised more roads.*",
      "Traffic jams in Douala make people late and waste drivers' fuel and money. Smoke pollutes the air and causes coughing, while impatient drivers cause more accidents.",
      ["1 mark: late for work.", "1 mark: waste of fuel/money.", "1 mark: pollution and coughing.", "1 mark: more accidents; own words, within limit; council promise left out."])],
   [sc("The key words of a summary question show...", "what to include", ["what to copy", "the title", "the length"], "Select relevant points."),
    sc("A summary should NOT contain...", "your own opinion", ["main points", "linking words", "paraphrase"], "Keep to the text."),
    sc("*Make a decision* can be shortened to...", "decide", ["decision making", "to make decide", "decided on"], "Use one verb."),
    sc("Linking words in a summary help to...", "connect points smoothly", ["add examples", "repeat points", "increase the word count"], "Continuous prose."),
    sc("If the word limit is 80 you should...", "stay at or below 80 words", ["write 200 words", "write 10 words", "ignore it"], "Respect the limit.")])

LS(s, "word-formation-proverbs", "Word formation, proverbs and idioms", 24,
   ["Form nouns, adjectives, verbs and adverbs from one root.", "Use proverbs and idioms with understanding.", "Avoid common spelling errors in derived words."],
   [tx("Many English words belong to a **family**. If you know the root and the patterns, you can make the noun, verb, adjective or adverb you need, a skill often tested in grammar and vocabulary exercises. This lesson also revises **proverbs and idioms**, which add colour to writing and speech."),
    ky("definition", "Word families",
       "- **Noun**: *decision, beauty, kindness, growth, success*.\n- **Verb**: *decide, beautify, grow, succeed*.\n- **Adjective**: *decisive, beautiful, kind, successful*.\n- **Adverb**: *decisively, beautifully, kindly, successfully*.\nPatterns: *-tion / -sion* (nouns: *educate → education*), *-ment* (*agree → agreement*), *-ness* (*happy → happiness*), *-able / -ible* (adjectives: *comfort → comfortable*), *-ous* (*danger → dangerous*), *-ly* (adverbs)."),
    ky("definition", "Proverbs and idioms",
       "- *A stitch in time saves nine* (act early to prevent bigger problems).\n- *Too many cooks spoil the broth* (too many people spoil the work).\n- *Every cloud has a silver lining* (good can come from bad).\n- *Actions speak louder than words* (what you do matters more than what you say).\n- *Practice makes perfect* (repeat to improve).\nUse them to **support a point** in an essay, but only when they fit."),
    fg(tree("The word family of success", "succeed", [("success", "noun"), ("successful", "adjective"), ("successfully", "adverb")], h=185),
       "One root, four forms.", "A diagram with the verb succeed at the top and three arrows to success (noun), successful (adjective) and successfully (adverb)."),
    ky("pieges", "Common mistakes",
       "- *He is a very success man* → **successful**.\n- *She dances beautiful* → **beautifully**.\n- *The agreeement was signed* — spelling: **agreement** (one e before ment).\n- Misusing a proverb because you misunderstand it.\n- Dropping or doubling letters wrongly: *beginning, occurrence, necessary, separate*."),
    exm("Example 1: choose the form", "Complete with the correct form of the word in brackets: *The ___ (decide) was taken ___ (quick) and the team acted ___ (decide).*",
        ["First blank needs a noun: **decision**; second an adverb: **quickly**.", "Third an adverb: **decisively**."], "decision ... quickly ... decisively"),
    exm("Example 2: a proverb", "Which proverb fits: *The roof leaked a little, but Papa waited until the rainy season to repair it, and the whole room was flooded.*",
        ["The problem was small at first and became big because action was late.", "*A stitch in time saves nine.*"], "A stitch in time saves nine.")],
   [m("The noun from *decide* is...", "decision", ["decisive", "decisively", "decider"], "Decision."),
    m("Choose the correct form: *She sang ___.*", "beautifully", ["beautiful", "beauty", "beautify"], "An adverb describes sang."),
    t("*Every cloud has a silver lining* means that something good can come out of a bad situation.", True, "That is its meaning."),
    m("The adjective from *danger* is...", "dangerous", ["dangerly", "dangering", "dangerful"], "Add -ous."),
    mt("Match each proverb to its meaning.", [["A stitch in time saves nine", "act early"], ["Too many cooks spoil the broth", "too many people spoil a task"], ["Actions speak louder than words", "deeds matter more than promises"], ["Practice makes perfect", "repetition improves skill"]], "Learn proverbs as wholes."),
    o("Write the correct form of each word in brackets: 1. His ___ (kind) touched everyone. 2. She is a very ___ (success) businesswoman. 3. They answered ___ (polite). 4. The ___ (agree) was signed yesterday. Then write a short paragraph (3–4 sentences) using a proverb to support an argument about doing homework regularly.",
      "1. kindness 2. successful 3. politely 4. agreement. Paragraph: Pupils should do their homework every day. Practice makes perfect, and regular exercises help us remember what we learn. A pupil who studies a little every day will perform better than one who waits until the exam.",
      ["1 mark: four correct forms.", "1 mark: proverb used correctly.", "1 mark: it supports the point.", "1 mark: language and punctuation."])],
   [sc("Which suffix forms adverbs?", "-ly", ["-ness", "-tion", "-able"], "Adverbs often end in -ly."),
    sc("The noun from *happy* is...", "happiness", ["happily", "happier", "happify"], "-ness."),
    sc("*Practice makes perfect* means...", "repetition leads to improvement", ["perfect people never practise", "practice is difficult", "never repeat"], "Proverb."),
    sc("Which is spelt correctly?", "necessary", ["neccessary", "necesary", "neccesary"], "One c, two s."),
    sc("A proverb in an essay should...", "support your point", ["replace your argument", "be invented", "be a joke only"], "Use it to support.")])

w = p.chapter("ch-writing", "Writing and speaking", REF)

LS(w, "discursive-essay", "The discursive essay: weighing both sides", 28,
   ["Plan a discursive essay giving both sides of an issue.", "Use discourse markers to organise arguments.", "End with a reasoned personal view."],
   [tx("A **discursive essay** discusses a question from several points of view. A typical task: *Discuss the advantages and disadvantages of living in towns.* Unlike an argumentative essay, it does not only defend one side: it **weighs** the arguments and gives a **balanced** conclusion."),
    ky("methode", "Structure",
       "1. **Introduction:** present the issue in two or three sentences.\n2. **Paragraphs for side A:** 2 or 3 points, each with an explanation and example.\n3. **Paragraphs for side B:** the other side, treated equally.\n4. **Conclusion:** summarise both sides, and give your **own reasoned opinion**.\nWrite about **300 to 350 words** (to be checked against the exam instructions)."),
    fg(flow("Plan of a discursive essay", ["Introduction: the issue", "Side A: points with examples", "Side B: points with examples", "Conclusion: weigh up; own view"]),
       "Give both sides a fair hearing before you decide.", "A flowchart: introduction presenting the issue, side A with points and examples, side B with points and examples, and a conclusion that weighs both and gives an opinion."),
    ky("methode", "Discourse markers",
       "- **Adding:** *Moreover, In addition, Furthermore.*\n- **Contrast:** *However, On the other hand, Nevertheless, Although.*\n- **Result:** *Therefore, As a result, Consequently.*\n- **Example:** *For instance, For example.*\n- **Concluding:** *In conclusion, To sum up, All things considered.*\nVary them: do not begin every paragraph with *Firstly*."),
    ky("pieges", "Common mistakes",
       "- Writing only one side.\n- Listing points without explanations or examples.\n- Over-using the same markers (*Also... Also...*).\n- A conclusion with no opinion, or a sudden new topic.\n- Informal language and slang; contractions."),
    exm("Example 1: a balanced opening", "Write an introduction for *Discuss the advantages and disadvantages of living in a big city such as Douala.*",
        ["Present the issue neutrally and announce both sides.", "*Every year thousands of Cameroonians move to cities like Douala. While city life offers jobs and services, it also brings crowding and high costs. This essay considers both sides.*"], "Every year thousands of Cameroonians move to cities like Douala. While city life offers jobs and services, it also brings crowding and high costs. This essay considers both sides."),
    exm("Example 2: a paragraph", "Write a paragraph on one disadvantage.",
        ["Point, explanation, example.", "Use a discourse marker for contrast."], "On the other hand, living costs are high. Rent, food and transport take a large share of a family's income, so many workers live in crowded rooms far from their jobs.")],
   [m("A discursive essay...", "considers both sides of an issue", ["defends only one side", "tells a story", "describes a picture"], "Balanced."),
    m("Which linking phrase introduces a contrast?", "On the other hand", ["Moreover", "In addition", "Furthermore"], "Contrast."),
    t("A discursive essay should have no personal opinion at all.", False, "A reasoned opinion is given in the conclusion."),
    m("Which is the best conclusion starter?", "All things considered,", ["Firstly,", "Once upon a time,", "Suddenly,"], "Concluding marker."),
    m("Each paragraph should contain...", "a point with explanation and example", ["only a title", "a list of words", "a long quotation"], "Develop the point."),
    o("Write a plan for *Discuss the advantages and disadvantages of using mobile phones among teenagers.* Give the introduction idea, two advantages, two disadvantages (each with an example) and the conclusion with your view.",
      "Introduction: phones are everywhere. Advantages: (1) communication with family (a pupil can call parents), (2) learning (dictionary, videos). Disadvantages: (1) distraction (pupils play games in class), (2) cost and risks (money spent on credit, dangerous content). Conclusion: phones are useful if used responsibly; schools and parents should set limits.",
      ["1 mark: introduction.", "2 marks: two advantages with examples.", "2 marks: two disadvantages with examples.", "1 mark: balanced conclusion with own view."])],
   [sc("A discursive essay ends with...", "a reasoned view", ["a joke", "a new argument only", "a copy of the introduction"], "Reasoned view."),
    sc("*However* is used to...", "show contrast", ["add", "give examples", "conclude"], "Contrast."),
    sc("Both sides should be...", "treated fairly", ["ignored", "mocked", "hidden"], "Balanced."),
    sc("*For instance* introduces...", "an example", ["a contrast", "a conclusion", "a question"], "Example."),
    sc("The introduction should...", "present the issue", ["list all arguments", "end the essay", "tell a joke"], "Present the issue.")])

LS(w, "article-letter-editor", "Articles and letters to the editor", 28,
   ["Write a newspaper or school-magazine article with a headline and a byline.", "Write a letter to the editor giving an opinion on a public issue.", "Choose the right register and persuasive devices."],
   [tx("An **article** informs, describes or persuades a wide audience in a newspaper or school magazine. A **letter to the editor** is a formal letter that gives your opinion on an issue the newspaper has covered. Both need a clear purpose, a catchy opening and a confident, correct style."),
    ky("definition", "Layout of an article",
       "1. **Headline:** short, catchy: *RUBBISH: OUR SHARED SHAME*.\n2. **Byline:** *By Ngu Tabi, Form 4*.\n3. **Opening paragraph:** the main idea or a striking fact or question.\n4. **Body:** short paragraphs with facts, examples, quotations (invented quotations should be avoided in real life; in exams they may be allowed).\n5. **Ending:** a strong closing sentence or call to action.\nUse **headings or subheadings** in a longer article."),
    ky("definition", "Letter to the editor",
       "Use the formal layout (your address, date, *The Editor, [name of newspaper]*, *Dear Sir/Madam,*), a **subject line** (*RE: THE STATE OF OUR ROADS*), a first sentence that tells **which article or issue** you refer to, then **reasons and suggestions**, and end *Yours faithfully,*. Keep it **brief** (about 150 to 200 words)."),
    fg(cols("Article or letter?", ["Feature", "Article", "Letter"], [["Opening", "headline", "Dear Sir"], ["Writer", "byline", "signature"], ["Tone", "lively", "formal"], ["Ending", "call to action", "Yours faithfully"]], w=450),
       "Check the features of the form you are asked to write.", "A table comparing an article and a letter to the editor: opening is a headline or Dear Sir, the writer is shown by a byline or signature, the tone is lively or formal, and the ending is a call to action or Yours faithfully."),
    ky("pieges", "Common mistakes",
       "- Writing an article with the layout of a letter, or the reverse.\n- No headline or byline.\n- A boring or vague opening.\n- Insulting people or naming and shaming real private individuals.\n- Facts that are exaggerated or invented in a way that could mislead.\n- Slang in a letter to the editor."),
    exm("Example 1: headline and opening", "Write a headline and opening for an article on the need for a school library.",
        ["A headline: short, striking.", "Opening: question or fact + the topic."], "A SCHOOL WITHOUT BOOKS?\nBy Ada Nkeng, Form 4\nHow can pupils succeed if they have nothing to read? Our school has 800 pupils but only one small shelf of books."),
    exm("Example 2: letter opening", "Write the opening paragraph of a letter to the editor of *The Daily Bridge* responding to an article on road accidents published on 5 May.",
        ["Mention the article and your purpose.", "State your view briefly."], "I am writing in reply to your article of 5 May on road accidents in our region. I agree that action is urgent and I would like to suggest three measures.")],
   [m("An article normally begins with...", "a headline", ["Dear Sir", "Yours faithfully", "the date only"], "Headline."),
    m("A letter to the editor ends with...", "Yours faithfully,", ["Yours lovingly,", "Bye,", "Thank you very much!!!"], "Formal ending."),
    t("A letter to the editor should say which article or issue it responds to.", True, "That is the first sentence's job."),
    m("Which is a suitable headline?", "ROADS THAT SWALLOW OUR TYRES", ["I am writing to say that", "Dear Madam", "Here is a long essay about roads in several parts"], "Short and catchy."),
    m("A byline tells the reader...", "who wrote the article", ["when it was printed", "what it is about", "how long it is"], "Writer's name."),
    o("Write a letter to the editor of *The Mountain Echo* (about 150 words) giving your opinion on the problem of rubbish in your town and suggesting two solutions. Use formal layout.",
      "Ngu Tabi, P.O. Box 12, Buea, 3 June 2026\nThe Editor, The Mountain Echo\nDear Sir,\nRE: RUBBISH IN OUR TOWN\nI am writing to express my concern about the rubbish that fills the streets and drains of our town.\nHeaps of plastic block the gutters, and when it rains the water floods the roads. Children play near these heaps, which is dangerous to their health.\nI suggest two solutions. Firstly, the council should place more bins and collect them regularly. Secondly, schools and churches should organise monthly clean-up days.\nI hope that your readers will support these measures.\nYours faithfully,\nNgu Tabi",
      ["2 marks: layout.", "3 marks: content (concern, two solutions).", "2 marks: formal language and persuasive style."])],
   [sc("A headline should be...", "short and catchy", ["very long", "boring", "informal and rude"], "Catchy."),
    sc("A byline shows...", "the writer's name", ["the date", "the price", "the editor's address"], "Writer."),
    sc("A letter to the editor is addressed to...", "the editor", ["the principal", "a friend", "the police"], "The Editor."),
    sc("An article may end with...", "a call to action", ["a greeting", "an address", "a subject line"], "Call to action."),
    sc("The register of a letter to the editor is...", "formal", ["slang", "texting style", "humorous only"], "Formal.")])

LS(w, "complaint-letter", "Letters of complaint and request", 26,
   ["Write a firm but polite letter of complaint.", "State the problem, the facts and the action you expect.", "Use formal vocabulary and the correct closing."],
   [tx("A **letter of complaint** is a formal letter that tells a person or organisation about a problem and asks for something to be done. It is firm but **polite**: anger and insults weaken your case. Example: *Write to the manager of a bus company about a lost parcel.*"),
    ky("methode", "Structure",
       "1. **Layout:** formal, with a **subject line** (*COMPLAINT ABOUT A LOST PARCEL*).\n2. **Paragraph 1:** the purpose: *I am writing to complain about...*.\n3. **Paragraph 2:** the **facts**: what happened, when, where (dates, times, reference numbers).\n4. **Paragraph 3:** the **effect on you** (cost, inconvenience).\n5. **Paragraph 4:** the **action you expect** and a deadline; polite closing, *Yours faithfully*."),
    fg(flow("Structure of a complaint", ["Purpose: what you complain about", "Facts: what, when, where", "Effect: cost and inconvenience", "Action expected and polite close"]),
       "Facts first, feelings second, request last.", "A flowchart: purpose of the complaint, facts of what, when and where, the effect on you, and the action expected with a polite close."),
    ky("methode", "Useful phrases",
       "*I am writing to complain about... / I was disappointed to find that... / I would be grateful if you could... / I look forward to your reply and hope the matter will be settled by... / Please accept my apologies if this is not your department.* Avoid: *You are useless; I will report you to the police.*"),
    ky("pieges", "Common mistakes",
       "- Rude or threatening language.\n- Telling a long story without dates and facts.\n- No clear request for action.\n- Informal tone or contractions.\n- Writing *Yours sincerely* with *Dear Sir/Madam*."),
    exm("Example 1: the purpose", "Write the first paragraph of a complaint to a bus company about a parcel not delivered.",
        ["State the purpose and give the key fact (what, when).", "*I am writing to complain that a parcel I sent with your company from Bamenda to Douala on 12 May has not yet arrived.*"], "I am writing to complain that a parcel I sent with your company from Bamenda to Douala on 12 May has not yet arrived."),
    exm("Example 2: the request", "Write the final paragraph asking for action politely.",
        ["Say what you expect and by when.", "*I would be grateful if you could trace the parcel and inform me before Friday 24 May. I look forward to your reply.*"], "I would be grateful if you could trace the parcel and inform me before Friday 24 May. I look forward to your reply.")],
   [m("A letter of complaint should be...", "firm but polite", ["rude", "funny", "very short"], "Firm but polite."),
    m("Which phrase begins a complaint politely?", "I am writing to complain about...", ["You are useless!", "Listen to me!", "I hate your company"], "Formal and clear."),
    t("A letter of complaint should include facts such as dates and places.", True, "Facts make the complaint credible."),
    m("The last paragraph should...", "state the action you expect", ["insult the reader", "introduce a new problem", "repeat the address"], "Request action."),
    m("Which closing is correct for *Dear Madam*?", "Yours faithfully,", ["Yours sincerely,", "Love,", "Best wishes,"], "Faithfully."),
    o("You bought a pair of shoes from *Fine Steps Shop* in Bafoussam on 3 June for 12 000 FCFA. After one week the sole came off. Write a letter (about 150 words) to the manager. State the problem, the facts, the effect and what you want.",
      "Nkem Fon, P.O. Box 20, Bafoussam, 12 June 2026\nThe Manager, Fine Steps Shop, Bafoussam\nDear Sir,\nCOMPLAINT ABOUT DEFECTIVE SHOES\nI am writing to complain about a pair of shoes I bought from your shop on 3 June for 12 000 FCFA.\nAfter one week of normal use the sole came off. I had to buy another pair, which has caused me inconvenience and extra expense.\nI would be grateful if you could replace the shoes or refund my money by 19 June. I have kept the receipt and can bring the shoes to your shop at any time.\nI look forward to your reply.\nYours faithfully,\nNkem Fon",
      ["2 marks: layout and closing.", "3 marks: facts, effect and request.", "2 marks: polite formal language and correctness."])],
   [sc("A subject line is...", "a short title for the letter", ["a greeting", "a joke", "a signature"], "Subject line."),
    sc("Facts in a complaint include...", "dates, places and amounts", ["only feelings", "threats", "jokes"], "Facts."),
    sc("The tone should be...", "polite and firm", ["rude", "begging", "silly"], "Polite and firm."),
    sc("You should end by...", "stating the action you expect", ["apologising for complaining", "threatening", "asking for a gift"], "Action."),
    sc("Contractions in a formal letter are...", "avoided", ["required", "the best style", "compulsory"], "Avoid them.")])

LS(w, "narrative-advanced", "Narrative writing: voice, tension and structure", 28,
   ["Plan a narrative with a clear structure and a sense of tension.", "Use description, dialogue and reflection to develop characters.", "Control tenses and paragraphing."],
   [tx("At Form 4 level a narrative must do more than relate events. It should have **atmosphere**, **believable characters** and a **meaningful ending**. A typical title: *The night the lights went out* or *A promise I kept*. The examiner looks for creativity and **control** of language."),
    ky("methode", "Building tension",
       "- **Slow down** the key moment with details of what the character sees, hears and feels.\n- Use **short sentences** at moments of danger or surprise.\n- Use **contrast**: calm before the storm.\n- Withhold information: let the reader **wonder**.\n- End with **a change**: the character learns something or the situation is resolved."),
    fg(flow("Structure of a narrative", ["Opening: scene, character, hook", "Problem: something goes wrong", "Climax: the key moment, slowed down", "Ending: result and reflection"]),
       "A strong middle (the climax) matters more than a long opening.", "A flowchart: opening with scene character and hook, problem, climax slowed down, and ending with result and reflection."),
    ky("methode", "Language and technique",
       "- **Show feelings** through action and body language.\n- Use **dialogue** to reveal character, with correct punctuation.\n- Use **figures of speech** sparingly: *the silence was a thick curtain*.\n- Keep to **one tense** (past) and one **point of view** (first or third person).\n- Use **paragraphs**: new time, place or speaker."),
    ky("pieges", "Common mistakes",
       "- Starting with *My name is...* or *One day*.\n- A long opening with the climax rushed in the last lines.\n- *It was all a dream* endings.\n- Unnatural dialogue with no punctuation.\n- Spelling and tense errors in a hurry: reserve five minutes for checking."),
    exm("Example 1: show tension", "Rewrite to build tension: *I heard a noise outside and was scared.*",
        ["Add senses and body: sound, silence, heartbeat.", "Use a short sentence."], "A faint scraping came from the yard. I froze. My heart thudded so loudly I was sure the whole house could hear it."),
    exm("Example 2: a meaningful ending", "Write the final sentence of the story *A promise I kept*, in which a boy promised his grandfather to finish school.",
        ["Link to the promise and show a change.", "End with a reflective image."], "Years later, holding my certificate, I whispered to the empty chair beside me: \"I kept it, Grandpa.\"")],
   [m("Which opening creates a hook?", "The generator coughed once, then died, and the whole street fell dark.", ["My name is Ngu.", "One day I woke up.", "This is a story."], "It starts with action."),
    m("Short sentences are most useful at moments of...", "danger or surprise", ["calm explanation", "long description", "listing facts"], "They quicken the pace."),
    t("A good ending should have no connection to the rest of the story.", False, "The ending resolves the story."),
    m("Which shows fear rather than telling it?", "My knees shook and I could not speak.", ["I was afraid.", "It was scary.", "I felt bad."], "It shows through action."),
    m("A new paragraph should begin...", "when the time, place or speaker changes", ["for every sentence", "never", "only at the title"], "Paragraphing."),
    o("Write a narrative of about 300 words on *The night the lights went out*. Plan first. Use at least one piece of dialogue, one simile or metaphor, and build tension before the climax.",
      "The generator coughed once, then died, and the whole street fell dark. I froze at the kitchen door.\n\n\"Mama?\" I called. No answer. Outside, a dog barked, then stopped. My heart thudded.\n\nA scraping sound came from the yard. I reached for the matchbox and my fingers shook so much that the first three matches broke. The fourth caught. In the small yellow light I saw a shape by the door.\n\n\"It is only me,\" said my brother Tabi, holding his bicycle. \"The road is blocked, so I walked.\"\n\nI laughed so hard that the flame went out. In the dark we sat together and waited for the light to return. I learned that night that fear is smaller when it is shared.",
      ["3 marks: plot, structure and tension.", "3 marks: language, figures and dialogue.", "3 marks: accuracy (tenses, spelling, punctuation).", "1 mark: paragraphing and length."])],
   [sc("Tension is built by...", "slowing the key moment with details", ["rushing the climax", "skipping the problem", "using no details"], "Details slow down."),
    sc("A hook is...", "a striking opening", ["a long paragraph", "a grammar rule", "a title"], "Hook."),
    sc("Which is a cliché ending to avoid?", "It was all a dream.", ["She finally understood.", "He returned home.", "The door opened."], "Overused."),
    sc("The tense of a narrative is usually...", "past", ["future", "conditional", "imperative"], "Past tense."),
    sc("Dialogue in a story reveals...", "character and moves the plot", ["spelling", "the word limit", "the marks"], "Dialogue.")])

o_ch = p.chapter("ch-oral", "Oral English", REF)

LS(o_ch, "oral-sounds-listening", "Oral English: sounds, sentence stress and listening", 26,
   ["Distinguish common sound contrasts in minimal pairs.", "Place sentence stress on the content words.", "Listen for the main idea and details and note them."],
   [tx("Oral English at O Level tests your ability to **recognise sounds**, **stress** and **intonation** and to **listen** for information. The skills can be improved by regular practice: listen to the radio, read aloud, record yourself and compare."),
    ky("definition", "Sound contrasts",
       "Pairs of words that differ by one sound (minimal pairs):\n- **think / sink** and **thin / tin**: the *th* sound needs the tongue between the teeth.\n- **ship / chip**; **share / chair**.\n- **bad / bed**; **bat / bet**.\n- **light / right**: do not confuse *l* and *r*.\nWords that sound alike in part: **rhyme** (*cake, make*) and words with the **same vowel sound** (*meet, field, key*). Silent letters: *knee, write, honest, castle, island*."),
    ky("definition", "Sentence stress and listening",
       "In a sentence we stress the **content words** (nouns, verbs, adjectives, adverbs) and say the small **function words** (a, the, of, to) weakly: *I'll SEE you at the STAtion toMORrow.* For **listening**:\n1. Read the questions before you listen.\n2. Listen for the **main idea** the first time, for **details** the second time.\n3. Write **short notes** (numbers, names, places).\n4. Use stress and intonation clues: the stressed word is usually the key one."),
    fg(cols("Minimal pairs", ["Word 1", "Word 2"], [["think", "sink"], ["ship", "chip"], ["bad", "bed"], ["light", "right"]], w=420),
       "Say each pair aloud; the difference is small but important.", "A table of minimal pairs: think and sink, ship and chip, bad and bed, light and right."),
    ky("pieges", "Common mistakes",
       "- Judging sounds by spelling: *queue* has the sound of **q**, *knee* starts with **n**.\n- Stressing every word: English is stress-timed.\n- Writing too much while listening and missing the next point.\n- Not reading the questions before listening.\n- Forgetting to check the numbers and units you noted."),
    exm("Example 1: odd one out", "Which word has a different vowel sound: *meet*, *field*, *key*, *head*?",
        ["*meet, field, key* share the long **ee** sound.", "*head* has the short **e** sound."], "head"),
    exm("Example 2: sentence stress", "Underline the words that are normally stressed: *The bus to Buea leaves at seven.*",
        ["Stress the content words: *bus, Buea, leaves, seven*.", "Weak words: *the, to, at*."], "bus, Buea, leaves, seven")],
   [m("Which word has a silent first letter?", "knee", ["tree", "bee", "sea"], "The k in knee is silent."),
    m("Which pair is a minimal pair?", "bad / bed", ["cat / dog", "tree / river", "go / run"], "They differ by one sound."),
    t("In *I'll SEE you at the STAtion*, the stressed words are the content words.", True, "Stress falls on see and station."),
    m("Which word rhymes with *cake*?", "make", ["cook", "keep", "kick"], "Cake and make rhyme."),
    m("Before you listen to a passage you should...", "read the questions", ["close your eyes", "write the answers", "talk to a friend"], "Know what to listen for."),
    o("Your teacher reads: *The meeting is on Thursday at half past four in the school hall. Bring a pen, a notebook and your reports.* Write short notes to answer: when, where, what to bring. Then say which words in the message carry the main stress and why.",
      "When: Thursday, 4.30 p.m.; Where: school hall; Bring: pen, notebook, reports. Stressed words: Thursday, half past four, school hall, pen, notebook, reports, because they are content words that carry the information.",
      ["1 mark: day and time.", "1 mark: place.", "1 mark: three items.", "1 mark: stress explanation."])],
   [sc("Content words include...", "nouns and verbs", ["the and of", "to and at", "a and an"], "Nouns, verbs, adjectives, adverbs."),
    sc("A minimal pair differs by...", "one sound", ["one letter in the middle only", "the meaning only", "the stress"], "One sound."),
    sc("The first time you listen, concentrate on...", "the main idea", ["every number", "the spelling", "the speaker's name"], "Main idea."),
    sc("Which letter is silent in *write*?", "w", ["r", "t", "e"], "The w is silent."),
    sc("Good notes while listening are...", "short and focused", ["very long", "in a story form", "copied from the question"], "Short notes.")])

p.write()
