import sys, math
sys.path.insert(0, "/home/user/CastBridge/tools/learn-authoring/anglophone")
from fg_kit import *

p = mk_pack("form1-citizenship", "Citizenship Education — Form 1", "Form 1", "Citizenship", "citizenship",
    "First-year Citizenship Education: the family and community, life and rules at school, values and character, the national symbols of Cameroon, the rights and duties of the child, and personal and community health.",
    "Cameroon anglophone secondary Citizenship Education syllabus, Form 1 — to be checked against the official text", CIT_NOTE)

def star(cx, cy, r):
    pts = []
    for i in range(10):
        ang = -math.pi / 2 + i * math.pi / 5
        rr = r if i % 2 == 0 else r * 0.42
        pts += [round(cx + rr * math.cos(ang), 1), round(cy + rr * math.sin(ang), 1)]
    return pts

# ------------------------------------------------------------ CH1 family & community
c = p.chapter("community", "Family, school and community")
L = LS(c, "family-community", "The family and the community",
    ["Describe different kinds of family and the roles of family members", "Explain why respect and cooperation matter at home", "Describe the community and the services it provides", "Explain how pupils can help in the family and the community"],
    [("text", "A **family** is a group of people who live together or are linked by blood, marriage or adoption, and who care for each other. Some families are **nuclear** (parents and children); others are **extended** (also grandparents, uncles, aunts and cousins), or have one parent. In every kind of family, members have **roles**: parents provide food, shelter, love and guidance; children learn, help and show respect."),
     ("key", "retenir", "Respect and cooperation", "Good family life depends on **respect** (for parents, elders and each other), **honesty**, **sharing household tasks** (fetching water, cooking, sweeping, washing), **listening** to each other, and settling quarrels peacefully. Children also have a duty to study hard and keep themselves clean. Families that cooperate are stronger and happier."),
     ("text", "Several families living near each other make a **community** (a village, a quarter or a neighbourhood). People in a community share a place, services and often customs. Community **services** include schools, health centres, markets, wells and water points, roads, churches and mosques, and the council. Good neighbours greet each other, help in difficulty (illness, funerals, building) and keep the surroundings clean."),
     ("key", "retenir", "How a pupil helps", "At home: do chores, respect rules, care for younger children. In the community: keep the compound and streets clean, avoid noise, help old people, take part in communal work such as cleaning the market or clearing a path, and protect public property such as water taps and benches."),
     ("key", "pieges", "Common mistakes", "- A family is not defined only by the 'father, mother and children' model; many types exist and all deserve respect.\n- Rights come with duties: a child has a right to care and a duty to help.\n- 'Community' does not mean only one's own ethnic group: it means everyone who shares the place.")],
    [("Example 1: type of family", "Mary lives with her mother, her grandmother and her two brothers in Kumba. What type of family is this?", ["More than one generation lives together.", "The grandmother is part of the household.", "So it is an extended family."], "An extended family."),
     ("Example 2: roles", "Give two duties a child has at home and two duties a parent has.", ["Child: help with chores and respect parents.", "Parent: provide food and shelter, and guide the child.", "Each side has duties."], "Child: chores, respect. Parent: care and guidance.")],
    F(shapes([CIRCLE(210, 100, 80, fill="lightyellow"), CIRCLE(210, 100, 48, fill="lightorange"), CIRCLE(210, 100, 20, fill="lightgreen"), T(210, 105, "Me", size=12, bold=True), T(210, 74, "Family", size=12), T(210, 40, "Community", size=12), T(210, 12, "Country", size=12)], 420, 195),
         "From me to the country", "Circles from me to the family, the community and the country."),
    [MCQ("In Form 1 citizenship, a family that also includes grandparents and uncles is", "an extended family", ["a nuclear family only", "a school class", "a political party"], "Extended families are wider."),
     TF("Pupils have no duties at home because they are children.", False, "Children share household tasks and show respect."),
     MATCH("Match each service with its use for the community.", [("Health centre", "Care for the sick"), ("Water point", "Drinking water"), ("Market", "Buying and selling food")], "Community services."),
     MCQ("Which action shows good neighbourliness?", "helping an elderly neighbour carry water", ["throwing rubbish in the street", "playing loud music at night", "damaging a public tap"], "Helping shows care.", tier="approfondissement"),
     OPEN("Explain three ways in which a pupil can help to keep the community clean.", "Put waste in bins or pits; take part in clean-up days; do not throw plastic in drains and streams; sweep around the home; remind friends to respect the environment.", "1 mark per way with a reason.", points=3, tier="approfondissement"),
     PROB("A community near Buea organises a communal clean-up of the water point every month.",
          [("mcq", "Taking part is an example of", "good citizenship", ["a crime", "a tax only", "a holiday"], "Citizens help the common good.", {}),
           ("tf", "Everyone in the community benefits from a clean water point.", True, "Clean water protects health.", {}),
           ("mcq", "A pupil who refuses to help because 'it is not my business' is", "neglecting a duty to the community", ["respecting rules", "protecting the water", "a good neighbour"], "Everyone has a share.", {}),
           ("open", "Give two other community tasks pupils can help with.", "Cleaning the market or the school compound, planting trees, helping the elderly, clearing drains.", "1 mark per task.", {})])],
    [("A group of people linked by blood or marriage who care for each other is a", "family", ["market", "council", "company"], "That is a family."),
     ("The community is", "people living near each other and sharing services", ["only one's cousins", "only the school", "only the police"], "It is local."),
     ("A duty of a child at home is to", "help with household tasks", ["destroy the house", "ignore parents", "steal money"], "Children should help."),
     ("Which is a community service?", "a health centre", ["a private diary", "a quarrel", "a rumour"], "It serves everyone."),
     ("Respect for elders is", "a value in many Cameroonian communities", ["a crime", "a tax", "forbidden"], "Respect is widely valued.")],
    ["Teacher to verify the definitions of family types in the syllabus and to adapt the examples to the pupils' home settings with sensitivity (single-parent families, orphans, foster homes)."], tag="Form 1 citizenship family")

L = LS(c, "school-life", "Life and rules at school",
    ["Explain why schools have rules", "State rights and duties of pupils", "Explain the roles of staff and prefects", "Describe bullying and how to deal with it"],
    [("text", "A **school** is a community where pupils learn knowledge, skills and values. To work well it needs **rules**: about punctuality, uniform, behaviour, respect for teachers and property, and safety. Rules protect everyone's right to learn and make fair treatment possible. Rules are made by the school authorities, often with views from teachers, parents and pupils."),
     ("key", "retenir", "People in a school", "The **principal** (head of the school) leads. **Vice principals** and **discipline masters** help to keep order. **Teachers** teach and guide. **Prefects** and class monitors help with order and are leaders among pupils. **Support staff** keep the school running. The **Parent–Teacher Association (PTA)** links families and school."),
     ("key", "retenir", "Rights and duties of a pupil", "**Rights**: to be taught, to be treated with respect, to be protected from violence, to be heard and to take part in school activities. **Duties**: to attend regularly and arrive on time, to study, to obey school rules, to respect others, to keep the school clean and to take care of school property."),
     ("text", "**Bullying** means repeatedly hurting or frightening someone weaker, by hitting, insults, threats, spreading rumours or leaving them out. It is wrong and harms both victims and bullies. What to do: **tell** a trusted adult, stay with friends, never take revenge or join in, and support a victim. Schools should have clear rules and fair sanctions; all pupils should help create a safe school."),
     ("key", "attention", "Be careful", "- Obeying rules does not mean being silent when something is wrong: pupils may report problems politely to teachers.\n- Prefects have authority but must be fair and respectful.\n- Joking can become bullying if it hurts someone who asks you to stop.")],
    [("Example 1: why a rule", "A school has a rule that pupils must arrive before 7:30 a.m. Give two reasons for this rule.", ["Lessons start at a fixed time.", "Late arrivals disturb the class.", "So the rule protects learning time and order."], "To start on time and avoid disturbing others."),
     ("Example 2: bullying", "A boy in your class is often insulted and isolated. What should you do?", ["Do not join in the insults.", "Tell a teacher or another trusted adult.", "Befriend and support the boy."], "Refuse to join in, report to a teacher and support the boy.")],
    F(flow("Reporting a problem", ["See or hear|a problem", "Stay calm|and safe", "Tell a trusted|adult", "School acts|and helps"], per_row=4), "What to do about bullying", "Four boxes showing the steps from seeing a problem to the school acting."),
    [MCQ("In Form 1 citizenship, school rules exist mainly to", "protect everyone's right to learn", ["punish teachers", "stop learning", "close the school"], "Rules give order and safety."),
     TF("A pupil has a duty to respect school property.", True, "Property is shared."),
     MATCH("Match each person with a role.", [("Principal", "Leads the school"), ("Prefect", "Helps keep order among pupils"), ("Teacher", "Teaches and guides pupils")], "School roles."),
     MCQ("Which is a form of bullying?", "spreading rumours to hurt someone", ["helping a friend", "sharing a book", "asking a teacher a question"], "Hurting others repeatedly is bullying.", tier="approfondissement"),
     OPEN("Explain how a school can stop bullying.", "Make clear rules and sanctions, encourage pupils to report safely, supervise playgrounds, teach respect and empathy in lessons, and support victims and help bullies change.", "1 mark per measure, up to 3.", points=3, tier="approfondissement"),
     PROB("Mark's class is noisy because the teacher is late. A pupil hides another pupil's bag as a joke.",
          [("mcq", "Hiding the bag is", "disrespectful to the owner's property", ["a duty", "a school rule", "a helpful act"], "It disturbs the owner.", {}),
           ("tf", "The pupil whose bag was hidden has the right to be treated with respect.", True, "Everyone has this right.", {}),
           ("mcq", "The best thing the class can do is", "keep order and tell the monitor", ["fight", "break desks", "leave the school"], "Order protects learning.", {}),
           ("open", "Name two duties of the class monitor.", "Keep order in the teacher's absence, take the register or report names, and help with cleaning and distributing materials.", "1 mark per duty.", {})])],
    [("A rule that pupils must wear a uniform helps to", "give a sense of belonging and equality", ["raise fees", "hide mistakes", "stop reading"], "Uniform shows unity."),
     ("The head of a secondary school is the", "principal", ["prefect", "monitor", "driver"], "He or she leads."),
     ("Reporting bullying to a teacher is", "a responsible action", ["telling lies", "a crime", "dangerous for everyone"], "It helps to stop harm."),
     ("The PTA connects", "parents and teachers", ["pupils and police", "ministers and ministers", "banks and markets"], "Parents and teachers cooperate."),
     ("A duty of a pupil is to", "attend school regularly", ["skip lessons", "destroy books", "insult teachers"], "Regular attendance helps learning.")],
    ["Teacher to verify school structures and titles as used in anglophone secondary schools (principal, discipline master, PTA) and local rules for sanctions; the lesson does not describe any specific school's regulations."], tag="Form 1 citizenship school")

# ------------------------------------------------------------ CH2 values & symbols
c = p.chapter("values", "Values, symbols and rights")
L = LS(c, "values-character", "Values and good character",
    ["Define values and name important moral values", "Explain honesty, respect, responsibility, tolerance and hard work", "Explain self-discipline and the effect of bad habits", "Apply values to everyday situations"],
    [("text", "**Values** are beliefs about what is right and good that guide behaviour. **Moral values** help people to live together peacefully. Important values include **honesty** (telling the truth, not stealing or cheating), **respect** (for people, their beliefs and property), **responsibility** (doing your duties), **tolerance** (accepting people who are different), **hard work**, **fairness**, **courage** and **solidarity** (helping each other)."),
     ("key", "retenir", "Applying values", "- **Honesty**: do your own exam work; return lost money or books.\n- **Respect**: greet elders, listen when others speak.\n- **Responsibility**: do homework, keep promises, take care of younger ones.\n- **Tolerance**: accept different languages, religions and customs.\n- **Hard work**: study regularly, do not look for shortcuts."),
     ("text", "**Self-discipline** means controlling your own behaviour and feelings and working towards goals. It helps you to study, to avoid bad company and to resist harmful habits such as lying, stealing, drug use or truancy. Good character is formed gradually in the family, at school, in the church or mosque and among friends. **Role models** — a respected parent, teacher or community member — show values in action."),
     ("key", "pieges", "Common mistakes", "- Being honest is not the same as being rude: tell the truth with respect.\n- Tolerance does not mean accepting harm to others; it means respecting differences peacefully.\n- Values are not only taught in lessons: they are learned by practice every day.")],
    [("Example 1: which value?", "A pupil finds 500 FCFA in the classroom and gives it to the teacher. Which value does this show?", ["She does not keep what is not hers.", "She tells the truth about the find.", "This is honesty."], "Honesty."),
     ("Example 2: tolerance", "Two pupils speak different home languages and have different religions. How can they show tolerance?", ["They respect each other's customs and beliefs.", "They work together without mocking.", "They share and learn about each other."], "By respecting and working together.")],
    F(cols("Some values", [("Honesty", ["Tell truth", "Do not cheat"]), ("Respect", ["Greet elders", "Listen"]), ("Responsibility", ["Do homework", "Keep promises"])], w=450), "Three important values", "Three columns describing honesty, respect and responsibility."),
    [MCQ("In Form 1 citizenship, telling the truth and not stealing is called", "honesty", ["tolerance", "pride", "courage"], "Honesty means being truthful."),
     TF("Tolerance means respecting people who are different from us.", True, "It is a key value."),
     MATCH("Match each situation with the value.", [("Returning a lost book to its owner", "Honesty"), ("Greeting the principal politely", "Respect"), ("Completing homework on time", "Responsibility")], "Values in daily life."),
     MCQ("Which habit shows self-discipline?", "preparing for exams in advance", ["copying in the exam hall", "missing lessons often", "ignoring all advice"], "Planning shows discipline.", tier="approfondissement"),
     OPEN("Explain how honesty helps a school community.", "It builds trust between pupils and teachers, avoids cheating and theft, makes fair results possible and creates a peaceful environment.", "1 mark per reason, up to 3.", points=3, tier="approfondissement"),
     PROB("Ngum is tempted to copy answers from a friend during a test.",
          [("mcq", "Copying is a lack of", "honesty", ["tolerance", "courage in sports", "hunger"], "It is cheating.", {}),
           ("tf", "Cheating is fair to other pupils who worked hard.", False, "It treats others unfairly.", {}),
           ("mcq", "A better choice is to", "revise and do his own best", ["bribe the teacher", "stay away", "threaten the friend"], "Honest effort is best.", {}),
           ("open", "Give two consequences of cheating in exams.", "Loss of trust and sanctions, weak knowledge and later failure, unfair results and a poor reputation.", "1 mark per consequence.", {})])],
    [("A moral value is", "a belief about what is right", ["a coin", "a food", "a map"], "Values guide behaviour."),
     ("Respect includes", "listening and showing courtesy", ["insulting others", "mocking", "stealing"], "Respect shows care."),
     ("Self-discipline means", "controlling your own behaviour", ["doing whatever you like", "following bad friends", "being lazy"], "It helps achieve goals."),
     ("Which is a role model for children?", "a person who shows good values", ["a thief", "a liar", "a bully"], "Role models show good behaviour."),
     ("Solidarity means", "helping each other", ["working alone only", "fighting", "ignoring others"], "It is mutual support.")],
    ["Teacher to verify the list of values in the official syllabus; examples use local situations and FCFA amounts for realism only."], tag="Form 1 citizenship values")

symb = shapes([RECT(40, 20, 60, 100, fill="green", stroke="ink"), RECT(100, 20, 60, 100, fill="red", stroke="ink"), RECT(160, 20, 60, 100, fill="yellow", stroke="ink"), POLY(star(130, 70, 22), fill="yellow", stroke="ink", width=1), T(130, 145, "National flag (simple drawing)", size=12)], 260, 160)
L = LS(c, "national-symbols", "National symbols of Cameroon",
    ["Describe the flag, the motto and the anthem of Cameroon", "Name the capital and National Day", "Explain why symbols deserve respect", "Behave correctly when the flag is raised or the anthem is sung"],
    [("text", "A **national symbol** represents a country and unites its people. The most important symbols of Cameroon are the **flag**, the **coat of arms**, the **motto** and the **national anthem**. The **capital** is Yaoundé. The **National Day** is **20 May**. Another important date in the school calendar is **11 February**, Youth Day."),
     ("key", "retenir", "The flag and motto", "The **flag** has three vertical bands: **green**, **red** and **yellow** from left to right, with a **yellow star** in the middle of the red band. The **motto** is **'Peace – Work – Fatherland'**. These symbols stand for the unity of the nation and the ideals of its people."),
     ("text", "The **national anthem** is a song for solemn occasions, such as raising the flag, national celebrations and school ceremonies. Its title is **'O Cameroon, Cradle of our Forefathers'**. When the flag is raised or the anthem is played we **stand still, stay silent, face the flag** and show respect. Pupils learn the words and sing them properly."),
     ("key", "retenir", "Why respect symbols?", "Symbols remind people that they belong to one country, whatever their language, religion or region. Respecting them shows love for the country and for fellow citizens. Damaging, mocking or dishonouring them is disrespectful and may be punished by law. Flags are never allowed to touch the ground."),
     ("key", "pieges", "Common mistakes", "- Learn the order of the colours: green, red, yellow (left to right); the star is on the red band.\n- The motto has three words: Peace, Work, Fatherland.\n- National Day (20 May) is not the same as Youth Day (11 February) or reunification day (1 October).")],
    [("Example 1: describe the flag", "Describe the flag of Cameroon in one sentence.", ["Three vertical bands.", "Green, red and yellow from left to right.", "A yellow star on the red band."], "Three vertical bands, green, red, yellow, with a yellow star on the red band.", symb),
     ("Example 2: respect", "What should a pupil do when the national anthem is played at a ceremony?", ["Stand still and face the flag.", "Stay silent or sing correctly.", "Show respect until the anthem ends."], "Stand still, be silent or sing, and show respect.")],
    F(symb, "The flag of Cameroon", "The flag with vertical bands of green, red and yellow and a yellow star on the red band."),
    [MCQ("The capital of Cameroon is", "Yaoundé", ["Douala", "Bamenda", "Buea"], "Yaoundé is the political capital."),
     TF("The star on the Cameroonian flag is on the red band.", True, "It is in the middle of the red band."),
     MATCH("Match each symbol with its description.", [("Flag", "Green, red and yellow with a star"), ("Motto", "Peace – Work – Fatherland"), ("National Day", "20 May")], "Symbols of the nation."),
     MCQ("When the anthem is played at school you should", "stand still and show respect", ["run around", "talk loudly", "laugh"], "The anthem is a solemn song.", tier="approfondissement"),
     OPEN("Explain why national symbols are important to a country.", "They represent the unity and identity of the nation and its history, remind citizens that they belong together despite differences, and inspire patriotism and respect.", "1 mark per reason, up to 3.", points=3, tier="approfondissement"),
     PROB("A school prepares for the National Day parade.",
          [("mcq", "National Day is celebrated on", "20 May", ["1 January", "1 October", "11 February"], "20 May is National Day.", {}),
           ("mcq", "Which colour is the middle band of the flag?", "red", ["green", "yellow", "blue"], "Green, red, yellow.", {}),
           ("tf", "The motto has three words.", True, "Peace, Work, Fatherland.", {}),
           ("open", "State two ways pupils can show patriotism.", "Respect the symbols, obey laws, work hard, protect public property, and help others in the community.", "1 mark per way.", {})])],
    [("The motto of Cameroon is", "Peace – Work – Fatherland", ["Liberty – Equality – Fraternity", "Unity – Faith – Progress", "One People – One Nation"], "That is the national motto."),
     ("The flag has", "three vertical bands", ["three horizontal bands", "two bands only", "no bands"], "Bands are vertical."),
     ("Youth Day is celebrated on", "11 February", ["20 May", "1 October", "1 May"], "It is Youth Day."),
     ("The national anthem is sung on", "formal national occasions", ["only at football matches", "never", "only at funerals"], "It is a solemn song."),
     ("A symbol of a country", "represents the whole nation", ["belongs to one person", "belongs to one village", "is only decoration"], "It unites the people.")],
    ["Teacher to verify: flag description, motto wording, anthem title, National Day (20 May), Youth Day (11 February) and the rules of respect for symbols as published in official texts."], tag="Form 1 citizenship symbols")

L = LS(c, "child-rights", "Rights and duties of the child",
    ["State the main rights of the child", "State the main duties of the child", "Explain the idea that rights and duties go together", "Name the international document protecting children's rights"],
    [("text", "Every child has **rights**: things they are entitled to so that they can grow up healthy, safe and educated. In 1989 the United Nations adopted the **Convention on the Rights of the Child**, an international agreement which many countries, including Cameroon, have accepted. Its main ideas are survival, development, protection and participation."),
     ("key", "retenir", "Main rights of a child", "- To a **name** and a **nationality** (a birth certificate helps).\n- To **life, food, shelter and health care**.\n- To **education**.\n- To **protection** from violence, abuse, exploitation and harmful child labour.\n- To **play and rest**.\n- To **express opinions** and be heard, according to age and maturity.\n- To be cared for by parents, or to receive protection if there is no family."),
     ("key", "retenir", "Duties of a child", "Respect parents, teachers and others; obey rules; study and attend school; help with household tasks; take care of property; protect the environment; and respect the rights of others. A child cannot demand rights while denying duties: each right is matched by responsibility, and the rights of others set limits on my own."),
     ("text", "**Who protects children?** Parents and guardians first, then the school, the community, religious leaders, the health services, the police and courts, and government bodies, assisted by organisations such as UNICEF. A child who is hurt or abused should tell a trusted adult. Children should avoid dangers such as strangers who offer money or gifts, and should not be forced into marriage or dangerous work."),
     ("key", "attention", "Be careful", "- Having rights does not mean doing whatever you like.\n- Discipline by parents must respect the child's dignity: abuse and cruelty are never acceptable.\n- Rights apply to every child, whether girl or boy, rich or poor, disabled or not.")],
    [("Example 1: right or duty?", "Classify: A) going to school; B) obeying school rules; C) receiving health care; D) helping at home.", ["Education and health care are entitlements: rights.", "Obeying rules and helping at home are responsibilities: duties.", "So A and C are rights; B and D are duties."], "A and C rights; B and D duties."),
     ("Example 2: protection", "A child is beaten at home and is afraid. Whom can the child tell?", ["The child can tell a trusted adult: a teacher, relative or religious leader.", "Social services or the police can also help.", "Telling is the first step towards protection."], "A trusted adult such as a teacher, a relative or social services.")],
    F(cols("Rights and duties of the child", [("Rights", ["Education", "Health care", "Protection", "Play and rest"]), ("Duties", ["Respect others", "Study", "Help at home", "Obey rules"])], w=420), "Rights and duties", "Two columns of rights and duties of a child."),
    [MCQ("In Form 1 citizenship, the international agreement on children's rights adopted by the UN in 1989 is the", "Convention on the Rights of the Child", ["Treaty of Versailles", "Berlin Act", "Highway Code"], "It was adopted in 1989."),
     TF("The right to education applies to every child, girls and boys.", True, "Rights are universal."),
     MATCH("Match each right with an example.", [("Right to health", "Vaccination and treatment"), ("Right to education", "Going to school"), ("Right to protection", "Safety from abuse")], "Children's rights."),
     MCQ("Which is a duty of a child?", "respecting others' rights", ["demanding gifts always", "dropping out of school", "insulting elders"], "Duties accompany rights.", tier="approfondissement"),
     OPEN("Explain why a child's rights should be accompanied by duties.", "Rights depend on others respecting them, so everyone must also respect the rights of others; duties such as studying and respecting rules help the child and the community and prevent selfishness.", "1 mark per point, up to 3.", points=3, tier="approfondissement"),
     PROB("A twelve-year-old girl is kept at home to sell goods every day and cannot go to school.",
          [("mcq", "Which right is being denied?", "the right to education", ["the right to vote", "the right to drive", "the right to own a shop"], "She is being kept from school.", {}),
           ("tf", "Harmful child labour is allowed if the family needs money.", False, "Children must be protected from harmful work.", {}),
           ("mcq", "Who can help?", "a teacher, community leader or social services", ["nobody", "only strangers", "only the girl"], "Several people can help.", {}),
           ("open", "Suggest two ways to help families keep children in school.", "Offer scholarships or reduced fees, community awareness, flexible school times and income support for poor families.", "1 mark per way.", {})])],
    [("A child's right to a name and nationality is helped by", "a birth certificate", ["a driving licence", "a bank card", "a ticket"], "It proves identity."),
     ("A duty of a child is to", "respect parents and teachers", ["fight with everyone", "skip school", "damage property"], "Duties include respect."),
     ("The year of the UN Convention on the Rights of the Child is", "1989", ["1884", "1914", "1960"], "It was adopted in 1989."),
     ("A child who is abused should", "tell a trusted adult", ["keep silent", "blame himself", "run away alone"], "Telling brings help."),
     ("The right to play and rest is", "part of children's rights", ["a punishment", "illegal", "a crime"], "Children need play and rest.")],
    ["Teacher to verify: year of the Convention (1989), Cameroon's acceptance, and the list of rights; the lesson presents them in simplified form. Handle abuse topics sensitively and know local child-protection contacts."], tag="Form 1 citizenship child rights")

# ------------------------------------------------------------ CH3 health
c = p.chapter("health", "Health and hygiene")
L = LS(c, "health-hygiene", "Personal hygiene, water and health",
    ["Describe good personal hygiene habits", "Explain how to keep water and food safe", "Describe how malaria is prevented", "Name the parts of a balanced diet"],
    [("text", "**Hygiene** means the practices that keep us clean and prevent disease. **Personal hygiene**: bathe regularly, wash hands with soap and clean water, brush teeth, keep nails short, wear clean clothes and cover the mouth when coughing or sneezing. Washing hands before eating and cooking, and after using the toilet, prevents many illnesses such as diarrhoea."),
     ("key", "methode", "Hand washing steps", "1. Wet hands with clean water.\n2. Apply soap and rub palms, backs of hands, between fingers and under nails for at least 20 seconds.\n3. Rinse with clean water.\n4. Dry with a clean cloth or air dry.\nIf there is no soap, use clean water and ash or another safe method, but soap is better."),
     ("key", "retenir", "Water, food and surroundings", "Drink **safe water**: from a protected source, or boiled or treated. Store it in clean, covered containers. Wash fruit and vegetables, cook food well and keep it covered from flies. Use latrines or toilets; never defecate near water sources. Dispose of waste properly and drain stagnant water."),
     ("text", "**Malaria** is a disease spread by the bite of infected female *Anopheles* mosquitoes. Symptoms often include fever, chills, headache and weakness. To prevent it: **sleep under a treated mosquito net**, clear stagnant water and bushes around the house, cover water containers, use window screens and protective clothing. Anyone with fever should go quickly to a health centre for a test and treatment; do not rely on guesses."),
     ("key", "retenir", "A balanced diet", "A balanced diet contains **energy foods** (cassava, rice, yam, bread), **body-building foods** (beans, fish, eggs, meat, groundnuts), and **protective foods** (fruits and vegetables, which give vitamins and minerals), plus water. Eating many different foods, in good quantity, helps children grow, learn and fight disease."),
     ("key", "pieges", "Common mistakes", "- Clear water is not always safe: it may still carry germs.\n- Taking medicine without a test or advice can be dangerous.\n- One food group alone does not make a balanced diet.")],
    [("Example 1: malaria prevention", "Give two ways a family can protect itself from malaria.", ["Sleep under a treated mosquito net.", "Remove standing water where mosquitoes breed.", "These reduce bites and breeding."], "Use treated nets and remove stagnant water."),
     ("Example 2: a balanced meal", "Is a meal of only cassava a balanced diet? Explain.", ["Cassava gives mainly energy.", "A balanced meal also needs protein and fruits or vegetables.", "So it is not balanced; add beans or fish and vegetables."], "No; it needs body-building and protective foods too.")],
    F(flow("Washing hands", ["Wet|hands", "Soap and|rub 20 s", "Rinse|with water", "Dry with|clean cloth"], per_row=4), "Four steps to wash hands", "Four boxes showing wet, soap and rub, rinse and dry."),
    [MCQ("In Form 1 citizenship, protection from malaria includes", "sleeping under a treated net", ["drinking more soda", "closing windows only in the day", "staying indoors always"], "Nets prevent bites."),
     TF("Washing hands with soap helps to prevent diarrhoea.", True, "It removes germs."),
     MATCH("Match each food with its function.", [("Rice and yam", "Energy"), ("Beans and fish", "Body-building"), ("Oranges and vegetables", "Protection")], "A balanced diet needs all three."),
     MCQ("Which is a safe way to treat drinking water if the source is doubtful?", "boiling it", ["adding sugar", "adding salt", "letting flies land on it"], "Boiling kills germs.", tier="approfondissement"),
     OPEN("Explain how a family can improve hygiene around the house to prevent disease.", "Wash hands with soap, keep water covered, use latrines, dispose of waste and drain stagnant water, keep food covered and clean the compound.", "1 mark per measure, up to 3.", points=3, tier="approfondissement"),
     PROB("A family in a town has frequent diarrhoea and fever in the rainy season.",
          [("mcq", "A likely hygiene problem is", "unsafe water and dirty hands", ["too much homework", "wearing shoes", "reading books"], "Water and hands carry germs.", {}),
           ("tf", "A child with fever should be taken to a health centre.", True, "A test and advice are needed.", {}),
           ("mcq", "Which action would reduce mosquito breeding?", "removing stagnant water", ["leaving buckets open", "collecting rubbish near the house", "closing the gate"], "Mosquitoes breed in standing water.", {}),
           ("open", "Give two ways to keep drinking water safe.", "Collect it from a protected source, boil or treat it, store it in a clean covered container, and use a clean cup to draw it.", "1 mark per way.", {})])],
    [("Malaria is spread by", "female Anopheles mosquitoes", ["flies", "dogs", "cold air"], "Mosquito bites spread it."),
     ("Washing hands is most important before", "eating and cooking", ["sleeping only", "watching TV", "writing"], "It prevents germs entering the body."),
     ("Fruits and vegetables are", "protective foods", ["energy foods only", "body-building foods only", "poisonous"], "They give vitamins and minerals."),
     ("Safe drinking water can be", "boiled or treated", ["left dirty", "stored uncovered", "shared with animals"], "Treated water is safer."),
     ("A latrine should be", "away from water sources", ["next to the well", "in the kitchen", "near the market"], "It prevents pollution.")],
    ["Health content is general and conservative; to be reviewed by a health worker (hand-washing, water treatment, malaria prevention, diet groups). The lesson avoids dosages and treatments."], tag="Form 1 citizenship health")

p.write()
