import sys
sys.path.insert(0, "/home/user/CastBridge/tools/learn-authoring/anglophone")
from fg_kit import *

p = mk_pack("form4-geography", "Geography — Form 4", "Form 4", "Geography", "geography",
    "Fourth-year Geography, leading into Form 5: transport, trade and regional groupings, tourism and wildlife, the physical geography and resources of Africa, environmental problems, and graphs and data skills.",
    "Cameroon anglophone secondary Geography syllabus, Form 4 — to be checked against the official text", GEO_NOTE)

# ------------------------------------------------------------ CH1 transport
c = p.chapter("transport", "Transport and trade")
L = LS(c, "transport", "Transport in Cameroon",
    ["Name the modes of transport and compare their advantages", "Describe the main transport links of Cameroon", "Explain problems of transport and possible solutions"],
    [("text", "**Transport** is the movement of people and goods from one place to another. It links farms to markets, factories to ports and people to services. The main modes are **road**, **rail**, **water** (sea, river, lake) and **air**, plus pipelines for oil and gas. Good transport lowers costs and helps trade and national unity."),
     ("key", "retenir", "Comparing modes", "- **Road**: flexible, door to door, good for short and medium distances; accidents and bad roads are problems.\n- **Rail**: cheap for heavy goods over long distances; fixed routes.\n- **Water**: very cheap for bulky goods; slow; needs ports.\n- **Air**: fastest, for people and valuable or perishable goods; very expensive."),
     ("text", "**Transport in Cameroon.** Roads carry most passengers and goods; main roads link Douala, Yaoundé, Bafoussam, Bamenda and the north, while many rural roads become muddy in the rainy season. The **railway** runs from Douala to Yaoundé and on to Ngaoundéré, carrying passengers and goods such as fuel, timber and cattle. **Douala** is the main seaport, serving also landlocked neighbours such as Chad and the Central African Republic. There are international airports at **Douala** and **Yaoundé**, plus others in regional centres."),
     ("key", "retenir", "Problems and solutions", "**Problems**: poor and unpaved roads, potholes and floods, road accidents, congestion in cities, high fuel and fares, old vehicles. **Solutions**: building and maintaining roads and bridges, enforcing traffic rules, public transport (buses), developing railways and river transport, improving ports and airports, and local councils maintaining feeder roads. Better roads lower the price of food in towns and raise farmers' income."),
     ("key", "attention", "Be careful", "- 'Best' mode depends on goods, distance and cost: no mode is always best.\n- Landlocked countries depend on ports of neighbours; Cameroon is not landlocked.\n- Do not mix up transport (movement) with communication (messages by phone and radio).")],
    [("Example 1: choose a mode", "A company must send 500 tonnes of timber from Douala port to Europe. Which mode is best, and why?", ["The goods are bulky and heavy and distance is great.", "Water transport is cheapest for bulky goods over long distances.", "So sea transport."], "Sea transport, because it is cheapest for bulky cargo."),
     ("Example 2: perishable goods", "Fresh flowers must reach another continent within one day. Which mode is used and why?", ["The goods spoil quickly, so speed matters more than cost.", "Air is the fastest mode.", "So air transport is used."], "Air transport, because it is fastest.")],
    F(cols("Modes of transport", [("Road", ["Door to door", "Flexible", "Short trips"]), ("Rail", ["Heavy goods", "Cheap", "Fixed route"]), ("Water", ["Very cheap", "Bulky goods", "Slow"]), ("Air", ["Fastest", "Costly", "Light goods"])], w=460), "Modes compared", "Four columns summarising road, rail, water and air transport."),
    [MCQ("Which mode of transport is generally cheapest for bulky goods over long distances?", "water transport", ["air transport", "motorbike", "walking"], "Ships carry large loads at low cost per tonne."),
     TF("Douala is the main seaport of Cameroon.", True, "It handles most sea trade."),
     MATCH("Match each transport mode with its main advantage.", [("Road", "Door-to-door flexibility"), ("Air", "Speed"), ("Rail", "Cheap for heavy loads over long distances")], "Each mode has strengths."),
     MCQ("A rural road that floods in the rainy season is a problem because it", "raises transport costs and isolates farmers", ["lowers prices of food", "reduces rain", "improves trade"], "Farmers cannot reach markets cheaply.", tier="approfondissement"),
     OPEN("Explain three ways in which good roads help the development of Cameroon.", "They lower the cost of moving food and cash crops to markets and ports, link towns and villages to schools and hospitals, bring investment and jobs, and help national unity and trade with neighbours.", "1 mark per well-explained point.", points=3, tier="approfondissement"),
     PROB("A farmer in Bamenda wants to send tomatoes to Douala and also export dried cocoa from the port.",
          [("mcq", "The best mode for tomatoes over a day's journey is", "road transport", ["air transport", "river steamer", "pipeline"], "Flexible and fast enough for short and medium distances.", {}),
           ("mcq", "Exporting cocoa overseas uses", "sea transport", ["pipeline", "bicycle", "telegraph"], "Bulky cargo goes by ship.", {}),
           ("tf", "Rail can carry heavy goods such as timber and fuel cheaply.", True, "Rail suits heavy loads.", {}),
           ("open", "Suggest two causes of road accidents and a solution.", "Bad roads, overloading, speeding, old vehicles and drunk driving; solutions: repairing roads, enforcing rules, inspection of vehicles, driver education.", "1 mark per cause and 1 for a solution.", {})])],
    [("The fastest mode of transport is", "air", ["rail", "road", "water"], "Air is fastest but expensive."),
     ("Pipelines are used to carry", "oil and gas", ["people only", "letters", "dry grain only"], "Pipelines move liquids and gases."),
     ("A landlocked country has", "no coast", ["a long coast", "only islands", "two oceans"], "It must use neighbours' ports."),
     ("The railway links Douala to Yaoundé and", "Ngaoundéré", ["Limbe", "Buea", "Kribi"], "The line runs north to Ngaoundéré."),
     ("Transport helps development by", "moving people and goods", ["stopping trade", "closing markets", "removing roads"], "It links producers and consumers.")],
    ["Teacher to verify the rail route (Douala–Yaoundé–Ngaoundéré), airports and the role of Douala for neighbouring states; the Kribi deep-sea port is not covered because its status should be checked."], tag="Form 4 transport")

c = p.chapter("trade", "Trade and regional links")
L = LS(c, "trade-integration", "Trade, balance of trade and regional groupings",
    ["Define trade, exports and imports", "Calculate the balance of trade", "Name main exports and imports of Cameroon", "Describe regional economic groupings and their purposes"],
    [("text", "**Trade** is the buying and selling of goods and services. **Internal trade** takes place inside a country (markets, shops); **external (international) trade** is between countries. Goods sold abroad are **exports**; goods bought from abroad are **imports**. A country trades because no country has all the resources, skills or climates it needs."),
     ("key", "formule", "Balance of trade", "**Balance of trade = value of exports − value of imports.** If exports are greater, there is a **surplus** (favourable balance); if imports are greater, there is a **deficit** (unfavourable balance). Example: exports 800 billion FCFA, imports 1000 billion FCFA gives 800 − 1000 = −200 billion FCFA, a deficit."),
     ("text", "Cameroon exports mainly **primary products**: crude oil, timber, cocoa, bananas, coffee, cotton, rubber and aluminium. It imports **manufactured goods**: machinery, vehicles, fuel products, medicines, rice, wheat and electronic goods. Selling raw materials usually earns less than selling finished goods, which is why countries try to **process** their products locally."),
     ("key", "retenir", "Regional groupings", "Neighbouring countries form **economic groupings** to trade more easily, for instance by removing duties between them and using a common currency or common rules. Cameroon belongs to **CEMAC** (Central African Economic and Monetary Community) and works with other African bodies such as the **African Union**; West Africa has **ECOWAS**. Benefits: bigger markets and cooperation; difficulties: poor roads, differing rules and border delays."),
     ("key", "pieges", "Common mistakes", "- Exports go out of the country; imports come in.\n- A deficit means imports exceed exports: do not call it a profit.\n- Balance of trade is about goods; the balance of payments also includes services and other flows.")],
    [("Example 1: balance of trade", "A country exports goods worth 350 billion FCFA and imports goods worth 420 billion FCFA. Find the balance of trade.", ["Balance = exports − imports.", "350 − 420 = −70.", "A negative sign means a deficit."], "A deficit of 70 billion FCFA."),
     ("Example 2: why process locally?", "Why is it better for a country to export chocolate rather than raw cocoa beans?", ["Finished goods sell at higher prices.", "Processing creates local jobs and keeps value in the country.", "So exporting chocolate earns more."], "It earns more money and creates jobs.")],
    F(flow("International trade", ["Producer|(export)", "Port or|border", "Foreign|buyer", "Money comes|back"], per_row=4), "Exports bring money into the country", "A chain from producer to port to foreign buyer and money returning."),
    [MCQ("Goods bought from other countries are", "imports", ["exports", "tariffs only", "subsidies"], "Imports come into a country."),
     TF("A trade deficit means imports are greater than exports.", True, "Balance = exports − imports is negative."),
     NUM("A country exports goods worth 900 billion FCFA and imports goods worth 750 billion FCFA. What is the balance of trade in billions of FCFA?", 150, "900 − 750 = 150 (surplus).", unit="billion FCFA"),
     NUM("Exports are 620 billion FCFA and imports 800 billion FCFA. What is the balance of trade in billions (a negative answer means a deficit)?", -180, "620 − 800 = −180.", unit="billion FCFA", tier="approfondissement"),
     OPEN("Explain two advantages and one disadvantage of regional economic groupings like CEMAC.", "Advantages: larger market and easier trade without heavy duties; shared infrastructure and cooperation. Disadvantage: weak transport links and different rules still slow trade, and members may be competing producers.", "1 mark per advantage; 1 mark for a disadvantage; 1 for clarity.", points=3, tier="approfondissement"),
     PROB("In one year a country exports cocoa, timber and oil worth 1200 billion FCFA and imports machines, vehicles and food worth 1500 billion FCFA.",
          [("num", "Find the balance of trade in billions of FCFA.", -300, "1200 − 1500 = −300.", 0, "billion FCFA", {}),
           ("mcq", "This result is a", "trade deficit", ["trade surplus", "tax", "budget"], "Imports are larger than exports.", {}),
           ("tf", "Cocoa, timber and oil are mostly primary products.", True, "They are raw or lightly processed.", {}),
           ("open", "Suggest two ways to improve the balance of trade.", "Process raw materials locally, grow more of the food now imported, diversify exports, reduce waste and improve transport so exports reach markets cheaply.", "1 mark per way.", {})])],
    [("Balance of trade equals", "exports minus imports", ["imports minus exports", "exports plus imports", "exports times imports"], "A surplus means exports are larger."),
     ("An example of a primary export of Cameroon is", "cocoa", ["motor cars", "computers", "refrigerators"], "Cocoa is grown and exported."),
     ("An economic grouping of neighbouring states is", "CEMAC", ["the Moon", "a market stall", "a bank branch"], "CEMAC groups central African states."),
     ("Processing raw materials at home", "creates jobs and adds value", ["lowers all prices to zero", "stops exports", "causes droughts"], "Value stays in the country."),
     ("A trade surplus means", "exports exceed imports", ["imports exceed exports", "no trade took place", "all goods are free"], "The balance is positive.")],
    ["Teacher to verify the list of Cameroon's main exports and imports, the membership and purpose of CEMAC and ECOWAS, and to supply up-to-date trade statistics if required (all figures in the exercises are invented)."], tag="Form 4 trade")

# ------------------------------------------------------------ CH3 tourism
c = p.chapter("tourism", "Tourism and wildlife")
L = LS(c, "tourism-wildlife", "Tourism, national parks and conservation",
    ["Define tourism and its types", "Name the tourist attractions of Cameroon", "Explain benefits and problems of tourism", "Describe the conservation of wildlife"],
    [("text", "**Tourism** is travelling for pleasure, rest, culture or adventure. **Domestic** tourists visit places within their own country; **international** tourists come from abroad. Tourists need **attractions**, **access** (roads, airports), **accommodation** (hotels), **security** and **services** such as guides and restaurants."),
     ("key", "retenir", "Attractions of Cameroon", "- **Natural**: Mount Cameroon and the volcanic highlands; the beaches and the black sand of Limbe and the white sands of Kribi; waterfalls such as the Lobé falls at Kribi; crater lakes.\n- **Wildlife**: national parks and reserves such as **Waza** in the Far North, **Korup** in the South-West, **Dja** in the south-east, and the **Limbe Wildlife Centre**.\n- **Culture**: chiefdoms and palaces (Fon of Bafut, Foumban), festivals, crafts and music."),
     ("key", "retenir", "Benefits and problems", "**Benefits**: income and **foreign exchange**, jobs (guides, drivers, hotels, craft sellers), development of roads and services, and protection of cultural heritage and nature. **Problems**: pollution and litter, damage to wildlife habitats, the spread of crime, loss of local culture, and money leaving the country if hotels are foreign-owned. Insecurity and poor roads discourage visitors."),
     ("text", "**Conservation** is the careful use and protection of wildlife and natural environments. Governments set up **national parks** and **reserves**, ban **poaching** (illegal hunting) and trade in endangered species, use **rangers**, and teach people about nature. Local people must gain from tourism (jobs, shared income) so that they support conservation. Threats to wildlife are poaching, loss of forest to farming and logging, and conflict between humans and animals."),
     ("key", "attention", "Be careful", "- Tourism is not only foreigners: domestic tourism matters too.\n- A national park protects both animals and plants and their habitat.\n- Tourism is beneficial only if it is managed: too many visitors can damage the very sites they come to see.")],
    [("Example 1: benefits", "A new hotel opens near the Limbe beach. Give two ways it helps the local community.", ["It creates jobs for cooks, guides and cleaners.", "Visitors buy local food and crafts, bringing income.", "So jobs and income."], "Jobs and income from visitors."),
     ("Example 2: poaching", "Why is poaching a danger to wildlife and what can be done?", ["Poachers kill animals illegally, sometimes endangered species.", "Numbers fall and species may disappear.", "Rangers, laws and community education help to stop it."], "It reduces animal numbers; rangers, laws and education help.")],
    F(cols("Tourism in Cameroon", [("Coast", ["Limbe", "Kribi", "Lobé falls"]), ("Mountains", ["Mt Cameroon", "Highlands", "Crater lakes"]), ("Wildlife", ["Waza", "Korup", "Dja"])], w=440), "Examples of attractions", "Three columns naming coastal, mountain and wildlife attractions."),
    [MCQ("Illegal hunting of animals is called", "poaching", ["fishing", "gathering", "tourism"], "Poaching harms wildlife."),
     TF("Waza National Park is in the Far North of Cameroon.", True, "It is in the northern savanna."),
     MATCH("Match each attraction with its type.", [("Waza", "Wildlife park"), ("Lobé falls", "Natural scenery"), ("Foumban palace", "Cultural heritage")], "Tourist attractions can be natural or cultural."),
     MCQ("Which is a problem caused by badly managed tourism?", "litter and damage to habitats", ["more rain", "fewer visitors always", "higher mountains"], "Too many visitors can harm sites.", tier="approfondissement"),
     OPEN("Explain how tourism can help the economy of Cameroon and one way to keep it sustainable.", "Tourism brings foreign exchange, jobs and markets for local crafts and food and encourages road and hotel building. To make it sustainable, limit visitor numbers, manage waste, protect habitats and share income with local people.", "2 marks for economic benefits; 1 mark for a sustainable measure.", points=3, tier="approfondissement"),
     PROB("A village near a national park wants to welcome tourists.",
          [("mcq", "Which service would tourists need?", "guides and accommodation", ["no roads", "no water", "noisy waste dumps"], "Basic services attract visitors.", {}),
           ("tf", "The community should share the benefits of tourism to support conservation.", True, "People protect what benefits them.", {}),
           ("mcq", "Which action protects wildlife?", "banning poaching", ["clearing all forest", "allowing unlimited hunting", "dumping waste in streams"], "Laws and rangers protect animals.", {}),
           ("open", "Give two rules visitors should follow in a park.", "Do not feed or disturb animals, do not litter, stay on paths, follow the guide and never buy products from endangered species.", "1 mark per rule.", {})])],
    [("A national park is", "a protected area for wildlife", ["a market", "a factory zone", "a car park"], "It conserves animals and plants."),
     ("Foreign exchange from tourism is", "money from visitors from abroad", ["a kind of rock", "a local tax", "a crop"], "It helps the national economy."),
     ("Conservation means", "protecting and wisely using nature", ["clearing all forest", "hunting all animals", "selling parks"], "It aims to keep resources for the future."),
     ("The Limbe Wildlife Centre cares for", "rescued animals", ["only fish", "only cattle", "factory machines"], "It is a sanctuary open to visitors."),
     ("A cultural attraction is", "a traditional palace or festival", ["a rainstorm", "a swamp", "an earthquake"], "Culture is made by people.")],
    ["Teacher to verify the names and locations of parks and attractions (Waza, Korup, Dja, Limbe Wildlife Centre, Lobé falls, Bafut, Foumban) and the colour of the Limbe and Kribi beaches; check current security conditions before suggesting visits."], tag="Form 4 tourism")

# ------------------------------------------------------------ CH4 Africa
c = p.chapter("africa", "Africa")
afr = shapes([T(220, 18, "Africa: main features (schematic)", size=13, bold=True)] +
             sum([[RECT(10 + 140 * i, 30 + 54 * j, 130, 46, fill=FILLS[(i + j) % 4], radius=4), T(75 + 140 * i, 58 + 54 * j, t, size=12)] for j, row in enumerate([["Atlas (NW)", "Sahara (N)", "Nile (NE)"], ["Niger (W)", "Congo Basin (C)", "Rift Valley (E)"], ["Kalahari (SW)", "Zambezi (S)", "Drakensberg (SE)"]]) for i, t in enumerate(row)], []) +
             [T(220, 202, "Each box is a label placed roughly where the feature lies", size=11)], 440, 214)
L = LS(c, "africa-physical", "Physical features and resources of Africa",
    ["Name the main relief features, rivers and lakes of Africa", "Describe the climatic belts of Africa", "Name important natural resources and where they occur"],
    [("text", "Africa is the second-largest continent and is crossed by the **Equator** near its middle. Much of it is a high **plateau**. The great **Rift Valley** runs from east Africa, with high mountains such as **Kilimanjaro** (the highest in Africa) and **Mount Kenya**, and long lakes. In the north-west are the **Atlas Mountains**; in the south-east the **Drakensberg**. The **Sahara** in the north is the largest hot desert; the **Kalahari** and the **Namib** are in the south-west."),
     ("key", "retenir", "Rivers and lakes", "- **Nile**: flows north to the Mediterranean; one of the longest rivers in the world.\n- **Congo**: flows through the Congo Basin to the Atlantic across the Equator twice.\n- **Niger**: starts in the west highlands and bends through the Sahel to the Gulf of Guinea.\n- **Zambezi**: flows to the Indian Ocean with the Victoria Falls.\n- **Lake Victoria** is the largest lake in Africa; **Lake Chad** borders Cameroon."),
     ("text", "**Climate belts.** Because the Equator crosses the continent, the climates are arranged in belts to its north and south: equatorial in the middle (Congo Basin, southern Cameroon), tropical wet-dry (savanna) on both sides, hot desert further out (the Sahara in the north, the Kalahari in the south), and Mediterranean climates in the far north and south-west tip. High land such as the Ethiopian Highlands and East African mountains is cooler."),
     ("key", "retenir", "Resources", "Africa is rich in **minerals** and **energy**: **crude oil and gas** (Nigeria, Angola, Gabon, Cameroon and others), **gold** and **diamonds** (South Africa, Ghana, Botswana), **copper** (the Copperbelt of Zambia and DR Congo), **iron ore**, **bauxite** and **phosphates**. It also has **fertile farmland**, **forests**, **rivers for hydroelectric power** and great tourist attractions."),
     ("key", "pieges", "Common mistakes", "- The Sahara is a desert in northern Africa, not in Cameroon.\n- The Nile flows north, towards the Mediterranean Sea.\n- Resources do not guarantee wealth: minerals must be processed, transported and fairly managed.")],
    [("Example 1: a river and its sea", "Into which sea or ocean does the Nile flow, and in which general direction?", ["The Nile begins in the highlands near the Equator.", "It flows through Sudan and Egypt.", "It flows north into the Mediterranean Sea."], "North, into the Mediterranean Sea."),
     ("Example 2: climate belts", "Why does Africa have similar climates north and south of the Equator?", ["The Equator crosses the middle of the continent.", "Climate depends strongly on latitude.", "So belts repeat on both sides of the Equator."], "Because climate depends on distance from the Equator, which lies in the middle of Africa.")],
    F(afr, "Main physical features of Africa", "Nine labelled boxes arranged like a rough map of Africa."),
    [MCQ("The highest mountain in Africa is", "Kilimanjaro", ["Mount Cameroon", "Mount Kenya", "Drakensberg"], "Kilimanjaro stands in Tanzania."),
     TF("The Nile flows northwards.", True, "It drains into the Mediterranean."),
     MATCH("Match each feature with its location.", [("Sahara", "North"), ("Kalahari", "South-West"), ("Rift Valley", "East")], "Features in different parts of the continent."),
     MCQ("The Copperbelt is mainly found in", "Zambia and DR Congo", ["Morocco", "Egypt", "Madagascar"], "It is a copper mining region.", tier="approfondissement"),
     OPEN("Describe the arrangement of climate belts in Africa and explain it.", "From the Equator outwards: equatorial, tropical wet and dry, hot desert, and Mediterranean on the northern and south-western edges. This arrangement results from the Equator running through the middle of Africa.", "2 marks for the sequence; 1 mark for explanation.", points=3, tier="approfondissement"),
     PROB("Study the physical map of Africa.",
          [("mcq", "The Congo River flows through", "the Congo Basin", ["the Sahara", "the Kalahari", "the Atlas range"], "It drains equatorial Africa.", {}),
           ("tf", "Lake Chad lies on the border with Cameroon.", True, "It is shared by several countries.", {}),
           ("mcq", "A resource found in the Gulf of Guinea area is", "crude oil", ["glacier ice", "coal under the sea only", "polar bears"], "Several countries produce oil.", {}),
           ("open", "Give two ways Africa could use its rivers for development.", "Build hydroelectric dams, irrigate farms, develop transport and fisheries, and supply towns with water.", "1 mark per way.", {})])],
    [("The largest hot desert in the world is the", "Sahara", ["Kalahari", "Namib", "Atlas"], "It stretches across northern Africa."),
     ("The Victoria Falls are on the", "Zambezi River", ["Niger", "Nile", "Wouri"], "They lie between Zambia and Zimbabwe."),
     ("Africa is crossed by", "the Equator", ["the Arctic Circle", "the Antarctic", "no major line"], "The Equator lies near the middle."),
     ("Bauxite is the ore of", "aluminium", ["iron", "gold", "oil"], "It is used to make aluminium."),
     ("Lake Victoria is the", "largest lake in Africa", ["biggest river", "highest mountain", "deepest desert"], "It is in East Africa.")],
    ["Teacher to verify all names and locations (Kilimanjaro, Lake Victoria, Copperbelt, resource examples); statements like 'longest' and 'largest' should be double-checked against a current atlas."], tag="Form 4 Africa")

# ------------------------------------------------------------ CH5 environment
c = p.chapter("environment", "Environment")
L = LS(c, "environment", "Environmental problems and conservation",
    ["Name the main environmental problems of Cameroon and Africa", "Explain causes and effects of deforestation, soil erosion and desertification", "Describe pollution and global warming", "Describe ways of protecting the environment"],
    [("text", "The **environment** is everything around us: land, water, air, plants and animals. Human activities can damage it. **Deforestation** is the clearing of forests for farmland, firewood, logging, roads and towns. Effects: **soil erosion**, floods, loss of wildlife habitats, less rain locally and more carbon dioxide in the air. In Cameroon it is a concern in the forest regions of the south and east."),
     ("key", "retenir", "Erosion and desertification", "**Soil erosion** is the removal of topsoil by water or wind, made worse by bare ground, overgrazing and farming on slopes. **Desertification** is the spread of desert-like conditions into dry lands, caused by drought, overgrazing, cutting trees and over-cultivation. It affects the Sahel and the Far North of Cameroon, and **Lake Chad** has shrunk strongly in past decades."),
     ("key", "retenir", "Pollution and global warming", "**Pollution** is harmful waste in air, water or soil: smoke from vehicles and burning, industrial waste, plastic waste, oil spills and untreated sewage. Burning fuels and clearing forests add **greenhouse gases** such as carbon dioxide to the air, which trap heat and cause **global warming** and climate change: irregular rains, droughts, floods and rising sea level."),
     ("text", "**Protecting the environment:** plant trees (**afforestation** and **reforestation**), use **terraces**, mulching and crop rotation to stop erosion, avoid bush burning, manage waste (collect, recycle, safe dumps), reduce plastic, protect water sources, use clean energy such as solar, create parks and reserves, and educate people. Laws help, but **everyone** has a part: farmers, industries, councils, schools and families."),
     ("key", "attention", "Be careful", "- Natural hazards (floods, droughts) can be made worse by human action; do not blame nature alone.\n- Climate change is a long-term trend, not a single hot day or storm.\n- Conservation does not mean stopping all use: it means using resources wisely for the future.")],
    [("Example 1: cause and effect", "Farmers clear a steep forested slope to grow maize. Name a likely effect in the next heavy rains.", ["Without tree roots the soil is loose.", "Rain washes the topsoil down the slope.", "So soil erosion and possibly landslides."], "Soil erosion (and landslides)."),
     ("Example 2: solution", "A village is short of firewood because nearby trees have been cut. Suggest two solutions.", ["Plant fast-growing trees for fuel.", "Use fuel-efficient stoves and other energy sources such as gas or solar.", "These reduce pressure on the forest."], "Plant trees for fuel; use efficient stoves or other energy.")],
    F(cols("Environmental problems", [("Cause", ["Tree cutting", "Overgrazing", "Waste dumping"]), ("Effect", ["Soil erosion", "Desert spread", "Dirty water"]), ("Remedy", ["Plant trees", "Rotate pasture", "Recycle waste"])], w=440), "Causes, effects and remedies", "Three columns giving causes, effects and remedies of environmental problems."),
    [MCQ("The clearing of forests on a large scale is", "deforestation", ["afforestation", "irrigation", "conservation"], "Deforestation removes trees."),
     TF("Burning fuels and clearing forests add carbon dioxide to the air.", True, "Carbon dioxide is a greenhouse gas."),
     MATCH("Match each problem with a suitable remedy.", [("Soil erosion on slopes", "Terraces and tree planting"), ("Plastic waste", "Recycling and bans on dumping"), ("Overgrazing", "Rotating pastures and limiting herd size")], "Remedies fit the cause."),
     MCQ("Desertification is mostly a problem in", "the Sahel region", ["the Equatorial rainforest", "polar regions", "the Atlantic Ocean"], "It affects dry lands bordering deserts.", tier="approfondissement"),
     OPEN("Explain three effects of deforestation and propose one way to reduce it.", "Soil erosion and floods, loss of wildlife habitats, and less rainfall and more carbon dioxide in the air. To reduce it: plant trees, control logging, use improved stoves and farm the same land better.", "1 mark per effect; 1 mark for a way.", points=4, tier="approfondissement"),
     PROB("A community near the Far North notices that wells are drying up and sand is covering farms.",
          [("mcq", "This process is most likely", "desertification", ["glaciation", "volcanism", "coastal erosion"], "Dry lands are turning into desert.", {}),
           ("tf", "Planting trees can reduce desertification.", True, "Trees protect soil and keep moisture.", {}),
           ("mcq", "A human cause could be", "cutting trees and overgrazing", ["rain that falls evenly", "ocean waves", "volcanic soil"], "Bare ground blows away.", {}),
           ("open", "Suggest two actions for the community.", "Plant windbreak trees, control grazing, improve water management, use soil-conserving farming and avoid cutting trees for firewood.", "1 mark per action.", {})])],
    [("Planting trees where forests were cut is", "reforestation", ["deforestation", "erosion", "drought"], "It restores forest cover."),
     ("A greenhouse gas is", "carbon dioxide", ["oxygen", "nitrogen", "helium"], "It traps heat in the atmosphere."),
     ("Terracing on slopes helps to prevent", "soil erosion", ["rain", "sunshine", "volcanoes"], "Terraces slow run-off."),
     ("Desertification threatens", "the Sahel and its farms", ["Antarctica", "the Pacific", "city skyscrapers"], "Dry lands face spreading desert."),
     ("Which is a good way to manage waste?", "recycling and safe disposal", ["burning near homes", "dumping in rivers", "leaving it in streets"], "Safe disposal protects health.")],
    ["Teacher to verify statements on Lake Chad shrinking and climate change impacts (kept deliberately general) and the list of conservation measures; no statistics on forest cover are quoted."], tag="Form 4 environment")

# ------------------------------------------------------------ CH6 data skills
c = p.chapter("data", "Data and graph skills")
L = LS(c, "graphs-data", "Using graphs, climate data and photographs",
    ["Draw and read bar graphs and line graphs", "Calculate angles for a pie chart", "Read a climate graph", "Interpret a photograph or sketch in geography"],
    [("text", "Geographers use **graphs** to show data clearly. A **bar graph** compares quantities in separate groups (for example crop production by region). A **line graph** shows change over time (for example monthly temperature). A **pie chart** shows how a total is divided: the whole circle is 360°. Every graph needs a **title**, **labels** on the axes, a suitable **scale** and **units**."),
     ("key", "formule", "Pie chart angles", "Angle for a category = (value ÷ total) × 360°. Example: if cassava is 40 tonnes of a total of 200 tonnes, its angle is 40 ÷ 200 × 360 = **72°**. Check that all angles add up to 360° before drawing with a protractor."),
     ("key", "methode", "Climate graph", "A climate graph shows **temperature** as a line and **rainfall** as bars for each month. Read: (1) the highest and lowest monthly temperature and the **annual range** (highest − lowest); (2) the rainy months and the dry months; (3) the annual rainfall (add the monthly bars); then describe the climate. A hot place with rain all year is equatorial; hot with a long dry season is tropical."),
     ("text", "**Photographs and sketches.** To interpret a photograph, say what is in the **foreground** (near), **middle ground** and **background** (far), name features (relief, vegetation, buildings, rivers, farming), say what they show about the area (climate, human activities) and add a short sketch with labels. Always describe what you can see before explaining why."),
     ("key", "pieges", "Common mistakes", "- Do not start a vertical scale in the middle: begin at zero for bar graphs.\n- Pie chart angles must add up to 360°.\n- Describing a photograph is not the same as inventing facts: write only what the picture shows.")],
    [("Example 1: pie chart angle", "In a village, 30 of the 120 families grow coffee. What angle represents coffee on a pie chart?", ["Fraction = 30 ÷ 120 = 1/4.", "1/4 of 360° = 90°.", "Check: the other categories must give 270°."], "90°."),
     ("Example 2: annual range", "A town has a hottest month of 29 °C and a coolest month of 24 °C. What is the annual temperature range?", ["Range = highest − lowest.", "29 − 24 = 5.", "A small range is typical near the Equator."], "5 °C.")],
    F(bars([("Jan", 40, "blue"), ("Feb", 60, "blue"), ("Mar", 120, "blue"), ("Apr", 160, "blue"), ("May", 200, "blue")], unit="Rain (mm), invented figures", h=260), "Example of a rainfall bar graph", "Bar graph showing rainfall rising from January to May; invented figures."),
    [MCQ("A pie chart is a circle of how many degrees?", "360°", ["180°", "100°", "90°"], "All the categories together form 360°."),
     TF("A line graph is best for showing change over time.", True, "It follows values month by month or year by year."),
     NUM("In a survey of 80 pupils, 20 walk to school. What angle represents walkers in a pie chart? (degrees)", 90, "20 ÷ 80 × 360 = 90.", unit="°"),
     NUM("The total annual rainfall is the sum of the monthly values. Rain in four months is 150, 200, 250 and 100 mm; the other eight months have 0 mm. What is the total, in mm?", 700, "150 + 200 + 250 + 100 = 700.", unit="mm", tier="approfondissement"),
     OPEN("Explain how you would describe the climate of a place from a climate graph.", "State the temperature pattern (highest, lowest and range), then the rainfall pattern (wet months, dry months and annual total) and conclude which climate type it matches, with reasons.", "1 mark temperature; 1 mark rainfall; 1 mark conclusion.", points=3, tier="approfondissement"),
     PROB("Farmers in a division produce 100 tonnes of crops: cassava 50, maize 30 and groundnuts 20.",
          [("num", "Angle for cassava in a pie chart (degrees).", 180, "50 ÷ 100 × 360 = 180.", 0, "°", {}),
           ("num", "Angle for maize (degrees).", 108, "30 ÷ 100 × 360 = 108.", 0, "°", {}),
           ("num", "Angle for groundnuts (degrees).", 72, "20 ÷ 100 × 360 = 72.", 0, "°", {}),
           ("tf", "The three angles together equal 360°.", True, "180 + 108 + 72 = 360.", {})])],
    [("A bar graph needs", "labelled axes and a title", ["no title", "no units", "a pie slice"], "Clear labels make it readable."),
     ("The annual temperature range is the", "difference between the highest and lowest monthly means", ["sum of all months", "average rainfall", "rainy season length"], "Highest minus lowest."),
     ("Foreground in a photograph means", "the part nearest the viewer", ["the sky only", "the horizon", "the caption"], "Foreground is in front."),
     ("In a climate graph, rainfall is usually shown by", "bars", ["a pie", "a map", "a table only"], "Bars show the amount per month."),
     ("The angle for a category that is half the total is", "180°", ["90°", "360°", "50°"], "Half of 360° is 180°.")],
    ["Teacher to verify that the syllabus uses these graph types and conventions; all numbers in the graphs and exercises are invented."], tag="Form 4 graph skills")

p.write()
