import sys
sys.path.insert(0, "/home/user/CastBridge/tools/learn-authoring/anglophone")
from fe_kit import *

p = lit_pack("form4-literature", 4,
    "A fourth-year literature course preparing for the O Level cycle, with original passages, poems and scenes: style and diction, irony and satire, analysing a poem, appreciating an unseen prose passage, dramatic structure and staging, praise poetry and elegy in oral tradition, a review of literary terms and planning an essay under time pressure. Official set texts are not included.",
    "Form 4 Literature in English — general skills only; the official set texts (prose, poetry, drama) must be added by a teacher (to be checked against the official programme)")
REF = "Form 4 Literature in English — transferable reading skills (set texts to be added by a teacher)"

pr = p.chapter("ch-prose", "Prose: style, irony and unseen reading", REF)

LS(pr, "style-diction-syntax", "Style: diction, syntax and tone", 26,
   ["Analyse a writer's choice of words (diction).", "Comment on sentence length and structure (syntax).", "Describe tone and show how style supports meaning."],
   [tx("**Two Descriptions of the Same Road**\n(A) The road to Kumba is a grey ribbon, patient and straight, rolling gently between plantations.\n(B) The road to Kumba is a long wound in the forest, scarred with potholes, spitting dust at every passing truck.\nBoth describe the same road, yet the first feels calm and the second feels angry and damaged. The difference lies in the style."),
    ky("definition", "The tools of style",
       "- **Diction:** the writer's **choice of words**. (A): *ribbon, patient, gently* (soft, positive). (B): *wound, scarred, spitting* (harsh, violent).\n- **Syntax:** the structure and **length of sentences**. Short sentences give speed or shock; long sentences give flow or calm; fragments create emphasis.\n- **Imagery and figures:** similes, metaphors, personification.\n- **Tone:** the attitude revealed by these choices (A: admiring, calm; B: bitter, critical).\n- **Register:** formal or informal, local or standard."),
    ky("methode", "Writing a style comment",
       "1. **Quote** two or three key words.\n2. Say what **kind** of words they are (violent, soft, formal, local, technical).\n3. Explain the **connotation**: the feeling or idea the word carries beyond its meaning.\n4. Link to **tone and purpose**.\n*The verb \"spitting\" gives the road a violent, disgusting quality, so the tone becomes critical and the reader shares the writer's anger.*"),
    fg(cols("Style comment", ["Step", "Example"], [["quote", "\"scarred\", \"spitting\""], ["kind of word", "harsh, violent"], ["connotation", "pain, anger"], ["effect and tone", "bitter, critical"]], w=450),
       "Four steps build a full style comment.", "A table of the four steps of a style comment with examples: quote scarred and spitting; kind of word, harsh and violent; connotation, pain and anger; effect and tone, bitter and critical."),
    ky("pieges", "Common mistakes",
       "- Saying *the writer uses good vocabulary* (vague).\n- Naming a technique without the **effect**.\n- Confusing **tone** (writer's attitude) with **mood** (the reader's feeling).\n- Quoting long passages instead of key words.\n- Ignoring **sentence length**."),
    exm("Example 1: diction", "Compare the diction of (A) and (B) in one sentence.",
        ["(A): ribbon, patient, gently: soft, positive words.", "(B): wound, scarred, spitting: harsh, violent words."], "(A) uses soft, positive words; (B) uses harsh, violent words that show anger."),
    exm("Example 2: connotation", "What is the connotation of the word *wound* in (B)?",
        ["A wound suggests pain, damage and injury.", "The road is described as hurt, so the writer is critical of its condition."], "It suggests pain and damage and shows the writer's critical attitude.")],
   [m("Diction means...", "choice of words", ["number of lines", "rhyme scheme", "plot"], "Diction."),
    m("The tone of passage (B) is...", "bitter and critical", ["calm and admiring", "joyful", "formal and neutral"], "Violent words show anger."),
    t("Short sentences can create speed or shock.", True, "Syntax effect."),
    m("The word *patient* in (A) gives the road a...", "calm, human quality", ["violent quality", "noisy quality", "dirty quality"], "Personification and positive connotation."),
    m("The best style comment is...", "The verb 'spitting' gives the road a violent quality and shows anger.", ["The writer uses good words.", "It is nice.", "I liked passage B."], "Quote, kind, effect."),
    o("Write two short descriptions (2 sentences each) of the same place, such as a market at night, one with a warm, admiring tone and one with a harsh, critical tone. Underline three words that create the tone in each.",
      "Warm: The market at night glows like a lantern, and the sellers hum softly over their gentle fires. Harsh: The market at night is a choking pit of smoke, where angry voices scratch at the dark. Warm words: glows, lantern, gentle. Harsh words: choking, pit, scratch.",
      ["1 mark: warm version with positive diction.", "1 mark: harsh version with negative diction.", "1 mark: three words identified in each.", "1 mark: clear writing."])],
   [sc("Syntax is...", "sentence structure", ["rhyme", "plot", "audience"], "Syntax."),
    sc("Connotation is...", "the feeling a word carries", ["its spelling", "its length", "its page number"], "Connotation."),
    sc("A formal register uses...", "standard, serious language", ["slang", "text spelling", "jokes only"], "Formal."),
    sc("Tone is...", "the writer's attitude", ["the reader's feeling", "the rhyme", "the plot"], "Attitude."),
    sc("When you comment on style you should always...", "explain the effect", ["count words", "write the date", "list rhymes only"], "Effect.")],
   literature=True)

LS(pr, "irony-satire", "Irony and satire", 26,
   ["Recognise verbal, situational and dramatic irony.", "Define satire and explain how it criticises.", "Explain the writer's purpose in a satirical passage."],
   [tx("**The Notice**\nThe Ministry of Roads proudly announces that the new road to Mbanga will be completed by next June. The workers wish to thank the citizens for their patience of the last eleven years. Drivers are advised to keep their wheels, their spare wheels and their hopes in good condition. The Minister will cut the ribbon, if the ribbon arrives on time."),
    ky("definition", "Irony",
       "Irony is a **gap between appearance and reality**.\n- **Verbal irony:** words that mean the opposite of what is said: *thank the citizens for their patience of eleven years*.\n- **Situational irony:** the outcome is the opposite of what is expected (a fire station that burns down).\n- **Dramatic irony:** the audience knows what a character does not.\nIrony needs a **signal**: exaggeration, a tone that does not fit, or facts that contradict the words."),
    ky("definition", "Satire",
       "**Satire** uses humour, exaggeration and irony to **criticise** people, institutions or customs, in order to make the reader **think** and sometimes to **improve** society. Its tools: **parody, understatement, hyperbole, caricature, sarcasm**. A satirist attacks **ideas and behaviour**, not individual private persons. In *The Notice*, the target is **delay and empty promises** in public works."),
    fg(cols("Irony and satire", ["Term", "Meaning"], [["verbal irony", "words say the opposite"], ["situational irony", "outcome opposite to expected"], ["dramatic irony", "audience knows more"], ["satire", "criticism through humour"]], w=450),
       "Satire is the purpose; irony is one of its tools.", "A table of terms and their meanings: verbal irony, words say the opposite; situational irony, outcome opposite to expected; dramatic irony, audience knows more; satire, criticism through humour."),
    ky("pieges", "Common mistakes",
       "- Calling every unlucky event *ironic*.\n- Taking the satirical text literally.\n- Saying satire *is just funny*: it has a **serious purpose**.\n- Forgetting to name the **target** of the satire.\n- Mixing up **sarcasm** (a sharp personal tone) with irony (a gap in meaning)."),
    exm("Example 1: spot the irony", "Explain the irony in *thank the citizens for their patience of the last eleven years*.",
        ["Literally it is polite thanks.", "In reality it admits that the work took eleven years, so it criticises the delay."], "The thanks are polite on the surface but really expose a very long delay."),
    exm("Example 2: the target", "What is the target of the satire in *The Notice*?",
        ["The notice mocks the long delay and the promises made by the Ministry.", "The target is slow, empty public promises."], "slow, empty public promises")],
   [m("Words that mean the opposite of what they say show...", "verbal irony", ["rhyme", "alliteration", "personification"], "Verbal irony."),
    m("A fire station burning down is an example of...", "situational irony", ["dramatic irony", "rhyme", "hyperbole"], "Unexpected opposite."),
    t("Satire only aims to make people laugh and has no serious purpose.", False, "It criticises to make people think."),
    m("What is the target of *The Notice*?", "delay and empty promises in public works", ["students", "teachers", "football"], "The Ministry's delays."),
    m("*Keep their hopes in good condition* is an example of...", "irony and humour", ["a rhyme", "a map", "a stanza"], "It is ironic: hope is not a spare part."),
    o("In 4–5 sentences explain how *The Notice* uses irony to criticise the Ministry. Quote two phrases.",
      "The Notice sounds polite and proud, but its irony exposes the Ministry's failure. It thanks citizens for *their patience of the last eleven years*, which shows the road has taken very long. It advises drivers to keep *their hopes in good condition*, suggesting that hope is the only thing they have. The satire criticises delay and empty promises.",
      ["1 mark: irony identified.", "1 mark: first quotation explained.", "1 mark: second quotation explained.", "1 mark: target of the satire, clear writing."])],
   [sc("Satire aims to...", "criticise through humour", ["only entertain", "only mourn", "only describe"], "Criticise."),
    sc("Dramatic irony occurs when...", "the audience knows more than a character", ["the audience knows less", "nobody knows", "the stage is empty"], "Audience knows more."),
    sc("Sarcasm is...", "a sharp, mocking tone", ["a rhyme", "a stanza", "a setting"], "Sarcasm."),
    sc("The target of a satire is...", "the idea or behaviour it criticises", ["the printer", "the page number", "the date"], "Target."),
    sc("To spot irony look for...", "a gap between words and reality", ["rhyme only", "the title only", "the page number"], "Gap.")],
   notes=["The notice is an invented satirical text; it does not refer to any real ministry, road or person."], literature=True)

LS(pr, "unseen-prose", "Appreciating an unseen prose passage", 28,
   ["Read an unseen passage in layers: subject, speaker, tone, devices.", "Write a structured appreciation.", "Support every point with a quotation."],
   [tx("**Night Duty**\nThe ward was silent except for the fan, which turned slowly and complained at every turn. Nurse Bih walked down the aisle with her torch pointed at the floor, careful not to wake the sleeping. At bed seven an old man was awake, staring at the ceiling. \"Cannot sleep, Papa?\" she whispered. \"Too many memories,\" he answered. She straightened his blanket without another word, and for a moment the whole ward seemed to breathe more gently."),
    ky("methode", "A reading routine",
       "1. **Subject:** what is happening? Who, where, when?\n2. **Speaker / narrator:** who is telling, and what is the point of view?\n3. **Tone and mood:** how does the writer feel; how do we feel?\n4. **Language:** diction, imagery, sentence length, sound.\n5. **Structure:** beginning, change, ending; what is the **effect of the ending**?\n6. **Purpose and message.**\nRead the passage **twice** before writing."),
    ky("methode", "Writing the appreciation",
       "- **Opening:** what the passage is about and its main effect.\n- **Body paragraphs:** language and techniques with **quotation and explanation** (e.g. personification *the fan complained*; the contrast between silence and the old man's wakefulness).\n- **Closing:** the overall effect and the message (here: quiet compassion in small acts).\nWrite in the **present tense**, with **varied connectives**."),
    fg(flow("Reading an unseen passage", ["Subject: who, where, what", "Narrator and tone", "Language and devices", "Structure, effect and message"]),
       "Move from what is said to how it is said and why.", "A flowchart: subject, narrator and tone, language and devices, then structure, effect and message."),
    ky("pieges", "Common mistakes",
       "- Retelling the passage.\n- Spotting devices without effects.\n- A general comment with no quotation.\n- Missing the **ending**, which often carries the main effect.\n- Over-reading: claiming meanings that the text does not support."),
    exm("Example 1: a device and its effect", "Comment on *the fan turned slowly and complained at every turn*.",
        ["Device: personification: a fan cannot complain.", "Effect: the creaking sound emphasises the silence and the tired, sleepy mood of the ward."], "The personification of the fan stresses the silence and the sleepy mood."),
    exm("Example 2: the ending", "What is the effect of *the whole ward seemed to breathe more gently*?",
        ["The nurse's small kind act changes the atmosphere.", "It shows that compassion brings comfort to everyone."], "It shows that a small act of kindness comforts the whole ward.")],
   [m("The mood of the opening of *Night Duty* is...", "quiet and tired", ["noisy and cheerful", "angry", "frightening"], "Silent ward, slow fan."),
    m("The narrator uses the...", "third person", ["first person", "second person", "no person"], "She, he."),
    t("An appreciation should retell the passage line by line.", False, "Analyse, do not retell."),
    m("What does *Too many memories* suggest about the old man?", "He is thinking about the past and may be lonely.", ["He is hungry", "He is angry", "He wants to leave"], "Memories keep him awake."),
    m("The nurse's attitude is shown as...", "gentle and caring", ["rude", "careless", "afraid"], "She whispers and straightens his blanket."),
    o("Write an appreciation of *Night Duty* in about 150 words (subject, two language points with quotations, ending and message).",
      "In *Night Duty* the writer shows quiet compassion in a hospital at night. Personification in *the fan ... complained* emphasises the silence. The nurse's whisper *Cannot sleep, Papa?* shows respect and kindness. The old man's reply *Too many memories* hints at loneliness. The ending, when *the whole ward seemed to breathe more gently*, shows that a small kind act brings comfort. The passage teaches that simple kindness matters.",
      ["2 marks: subject and effect.", "3 marks: language points with quotations and explanation.", "2 marks: ending and message.", "1 mark: clear writing."])],
   [sc("A good appreciation of a passage begins with...", "what it is about and its main effect", ["the date", "a rhyme", "a title only"], "Subject and effect."),
    sc("The structure of a passage includes...", "its beginning, change and ending", ["only the first word", "only the title", "only the rhyme"], "Structure."),
    sc("When reading an unseen passage you should read it...", "twice", ["not at all", "once backwards", "never"], "Twice."),
    sc("Over-reading means...", "inventing meanings the text does not support", ["reading slowly", "reading twice", "using quotations"], "Over-reading."),
    sc("The ending of a passage often...", "carries the main effect", ["is unimportant", "is the title", "has no meaning"], "Often important.")],
   literature=True)

po = p.chapter("ch-poetry", "Poetry: analysis", REF)

LS(po, "poem-analysis", "Analysing a poem step by step", 28,
   ["Follow a method to analyse an unseen poem.", "Combine meaning, form, language and sound in a response.", "Write a clear essay-style response to a poem."],
   [tx("**Homework by Candlelight**\nThe power has gone again. Papa lights the candle\nand the shadows jump up the wall like children.\nI bend over the book, my pencil crawling,\nand count the cost of every little flame.\nMama hums a song from her mother's village.\nThe numbers swim, the letters blur and wink,\nbut the candle burns, small and stubborn,\nand I write on, a bright thing in the dark."),
    ky("methode", "A method for any poem",
       "1. **Title:** what does it suggest?\n2. **First reading:** who is speaking, to whom, about what? What is the situation?\n3. **Meaning by stanza:** how does the thought develop (beginning, change, end)?\n4. **Language:** images, comparisons, word choice, personification (*shadows jump up the wall like children*).\n5. **Sound and form:** rhyme, rhythm, line length, punctuation.\n6. **Tone and mood**, and the **final effect and message**."),
    ky("definition", "Reading this poem",
       "The speaker is a pupil studying in a power cut. The **images**: shadows like children (playful, comforting), the numbers that *swim*, the *small, stubborn* candle. The **tone** shifts from tired (*the power has gone again*) to determined (*I write on, a bright thing in the dark*). The poem has **no regular rhyme** (free verse), which gives a natural, speaking voice. The **message**: determination can shine even in difficult conditions."),
    fg(flow("Analysing a poem", ["Title and situation: who, what, where", "Stanza by stanza: how the thought develops", "Language, sound and form: devices and effects", "Tone, mood and message"]),
       "Never skip the effect of each technique.", "A flowchart of four steps: title and situation, thought developing stanza by stanza, language sound and form, then tone mood and message."),
    ky("pieges", "Common mistakes",
       "- Paraphrasing line by line instead of analysing.\n- Mentioning rhyme in a free-verse poem without saying that it is free verse.\n- Identifying a device (*simile*) but not the **effect**.\n- Ignoring the **ending** and the change of tone.\n- Taking the speaker for the poet without evidence."),
    exm("Example 1: the image of shadows", "Explain the effect of *the shadows jump up the wall like children*.",
        ["Simile and personification: shadows are given children's playful movement.", "Effect: the dark seems friendly and lively; it softens the hardship."], "The simile makes the shadows playful and friendly and eases the difficulty of the power cut."),
    exm("Example 2: the change of tone", "How does the tone change in the poem?",
        ["Beginning: tired and resigned: *the power has gone again*.", "End: proud and determined: *I write on, a bright thing in the dark*."], "from tired and resigned to proud and determined")],
   [m("The speaker of the poem is...", "a pupil studying by candlelight", ["a teacher", "a nurse", "a driver"], "She is doing homework."),
    m("The tone at the end of the poem is...", "determined and proud", ["bitter", "frightened", "careless"], "I write on, a bright thing in the dark."),
    t("The poem has a regular rhyme scheme.", False, "It is free verse."),
    m("*Shadows jump up the wall like children* is a...", "simile", ["metaphor", "rhyme", "onomatopoeia"], "Like."),
    m("The message of the poem is that...", "determination can shine in difficult conditions", ["candles are dangerous", "studying is useless", "homework is easy"], "Stubborn candle and the pupil."),
    o("Write an analysis of *Homework by Candlelight* (about 150 words): situation, two images with effects, the change of tone and the message.",
      "In *Homework by Candlelight* a pupil studies during a power cut. The simile *shadows jump up the wall like children* makes the darkness playful rather than frightening. The numbers that *swim* show her tiredness. At the start the tone is tired (*the power has gone again*), but it becomes determined as she calls the candle *small and stubborn* and herself *a bright thing in the dark*. The poem's message is that determination can light up hard conditions.",
      ["2 marks: situation and speaker.", "3 marks: images with effects.", "2 marks: tone change and message.", "1 mark: clear writing."])],
   [sc("The first step in analysing a poem is to...", "read the title and the whole poem", ["count the lines only", "copy it", "ignore it"], "Title and reading."),
    sc("Free verse is a poem with...", "no regular rhyme or metre", ["strict rhyme", "14 lines", "no words"], "Free."),
    sc("When tone changes in a poem you should...", "describe the change and its cause", ["ignore it", "copy lines", "count words"], "Describe change."),
    sc("An analysis should always...", "explain the effect of techniques", ["list techniques only", "retell the poem", "copy the poem"], "Effect."),
    sc("The speaker of a poem is...", "the voice in the poem", ["always the poet", "the title", "the rhyme"], "Speaker.")],
   literature=True)

dr = p.chapter("ch-drama-oral", "Drama and oral literature", REF)

LS(dr, "drama-structure-staging", "Dramatic structure, language and staging", 28,
   ["Describe the structure of a play: exposition, complication, climax, resolution.", "Comment on dramatic language and staging.", "Explain how a scene contributes to the whole play."],
   [tx("**The Verdict** (extract)\nA village court. The CHIEF sits; two ELDERS beside him. NGUM, a farmer, stands before them.\nCHIEF: (gravely) Ngum, you are accused of taking your neighbour's cow.\nNGUM: (quietly) I took it, Chief, but only to feed my children.\nELDER 1: (rising) A thief is a thief.\nCHIEF: (raising a hand) Sit. (A long silence.) Then who among us has never been hungry?\n(The ELDERS look at the floor. Lights fade slowly.)"),
    ky("definition", "Dramatic structure",
       "Most plays follow this shape (not always strictly):\n- **Exposition:** characters and situation introduced.\n- **Complication (rising action):** conflicts grow.\n- **Climax:** the turning point.\n- **Falling action and resolution (dénouement):** consequences and ending.\nIn a long play each **act** often covers a stage of the structure; a **scene** may build tension or give relief. In the extract above the **climax of the scene** is the Chief's question, which changes the court's attitude."),
    ky("definition", "Language and staging",
       "- **Dialogue:** short lines create tension; long speeches reveal thought.\n- **Register:** the Chief speaks formally and wisely; Ngum speaks simply and honestly.\n- **Silence and pauses:** *(A long silence)* puts weight on the Chief's words.\n- **Staging:** the **setting** (village court), **lighting** (*lights fade slowly* suggests reflection), **movement** (Elder 1 rises, the Chief raises a hand), **costume and props**.\nA playwright writes for the **eye and ear**, not only for the page."),
    fg(shapes([T(210, 22, "Dramatic structure", 15, bold=True), LINE(20, 170, 120, 120, width=3, color="blue"), LINE(120, 120, 210, 50, width=3, color="blue"), LINE(210, 50, 300, 120, width=3, color="orange"), LINE(300, 120, 400, 170, width=3, color="orange"), CIRCLE(210, 50, 6, fill="red", stroke="red"),
               T(70, 192, "Exposition", 12, bold=True), T(130, 150, "Complication", 12, anchor="end"), T(222, 42, "Climax", 13, bold=True, color="red", anchor="start"), T(290, 150, "Falling action", 12, anchor="start"), T(360, 192, "Resolution", 12, bold=True)], 420, 205),
       "Tension builds to a turning point and then resolves.", "A mountain shaped diagram of dramatic structure: exposition, complication rising to the climax at the peak, falling action and resolution."),
    ky("pieges", "Common mistakes",
       "- Discussing a play only as a story and forgetting **performance**.\n- Ignoring stage directions, lighting and silence.\n- Saying the climax is always the last scene.\n- Quoting stage directions as if spoken.\n- Not explaining how a scene fits into the **whole play**."),
    exm("Example 1: the climax of the scene", "Which moment is the climax of the extract?",
        ["The turning point is when the Chief asks who has never been hungry.", "It changes the attitude of the Elders from condemnation to reflection."], "The Chief's question, \"Then who among us has never been hungry?\""),
    exm("Example 2: staging", "What is the effect of *Lights fade slowly* at the end?",
        ["Slow fading suggests reflection and leaves the question hanging.", "The audience is left to think about justice and mercy."], "It encourages reflection and leaves the question of mercy open.")],
   [m("The turning point of a play is the...", "climax", ["exposition", "prologue", "epilogue"], "Climax."),
    m("In the extract the Elders look at the floor because...", "the Chief's question makes them reflect", ["they are bored", "they are angry at Ngum only", "the play is over"], "They have also known hunger."),
    t("Stage directions such as lighting are part of how a play creates meaning.", True, "Lighting is part of staging."),
    m("Ngum's register is...", "simple and honest", ["very formal", "rude", "silly"], "He speaks simply."),
    m("A pause or silence in a play may...", "add weight to what is said", ["end the play", "be a rhyme", "have no effect"], "Silence adds meaning."),
    o("In 4–5 sentences, explain how the writer uses language and staging to make the Chief's question powerful in *The Verdict*.",
      "The Chief first speaks gravely, so that the court feels serious. Ngum's honest reply shows his desperation. After the Elder's harsh remark, the Chief raises a hand and there is *a long silence*, which gives the question weight. The question *who among us has never been hungry?* makes the Elders look at the floor, and the slowly fading lights leave the audience thinking about mercy.",
      ["1 mark: language (register).", "1 mark: silence or stage direction.", "1 mark: effect on characters and audience.", "1 mark: clear writing."])],
   [sc("Dénouement means...", "the resolution", ["the opening", "the rhyme", "the stage"], "Resolution."),
    sc("Lighting in a play can...", "set mood", ["print the script", "write dialogue", "choose the title"], "Mood."),
    sc("A playwright writes for...", "performance as well as reading", ["only reading", "only printing", "only silence"], "Performance."),
    sc("The register of a character shows...", "his or her status and attitude", ["the page number", "the author's age", "the rhyme"], "Register."),
    sc("Complication means...", "the conflict grows", ["the play ends", "the title", "the prologue"], "Complication.")],
   notes=["The scene is original and invented; it does not refer to any real court, person or custom."], literature=True)

LS(dr, "oral-praise-elegy", "Oral poetry: praise poetry, elegy and performance", 26,
   ["Describe praise poetry, the elegy or dirge and the work song as oral forms.", "Identify devices of oral poetry: repetition, parallelism, epithets and call-and-response.", "Compare oral and written poetry."],
   [tx("Poetry existed in speech and song before it was written. In many communities poets perform **praise poems** for leaders and heroes, **dirges** (elegies) at funerals, **work songs** and **satirical songs**. The performer uses voice, rhythm, gesture and sometimes music, and the audience responds. This lesson looks at what these forms have in common, using original examples written for CastBridge."),
    ky("definition", "Devices of oral poetry",
       "- **Repetition:** words or lines repeated for emphasis and memory.\n- **Parallelism:** similar structures in successive lines: *You are the river that feeds us; you are the road that guides us.*\n- **Epithet:** a descriptive name or title: *Father of the Harvest*.\n- **Exaggeration (hyperbole)** in praise: the hero is bigger than the mountain.\n- **Call and response:** a leader calls; the audience answers.\n- **Rhythm and tonal patterns** suited to drum or voice."),
    ky("definition", "Forms and functions",
       "- **Praise poem:** honours a person, group or ancestor, recalling achievements and qualities; it can also gently **advise or criticise** the leader.\n- **Elegy / dirge:** mourns the dead and consoles the living; recalls the dead person's virtues.\n- **Work song:** sets a rhythm for shared labour.\n- **Oral vs written:** oral poetry is **performed, flexible and communal**; written poetry is **fixed, read and individual**, though many poets today use oral techniques."),
    fg(cols("Oral and written poetry", ["Feature", "Oral", "Written"], [["medium", "voice, music", "page"], ["audience", "present, involved", "reader alone"], ["text", "changes", "fixed"]], w=450),
       "Both are literature; they work in different ways.", "A table comparing oral and written poetry: medium voice and music against page; audience present and involved against reader alone; text changing against fixed."),
    ky("pieges", "Common mistakes",
       "- Calling oral poetry *primitive* or *less artistic*.\n- Ignoring performance: voice, rhythm, audience.\n- Reading a written transcription as though it were the whole poem.\n- Using one tradition's practices to describe all of Africa.\n- Quoting a real traditional praise poem from memory without a source: use original or properly credited examples."),
    exm("Example 1: parallelism", "Identify the device in: *You are the river that feeds us; you are the road that guides us.*",
        ["Two lines have the same structure, *You are the ... that ...*.", "That is **parallelism** (with metaphor)."], "parallelism (and metaphor)"),
    exm("Example 2: function of an elegy", "Give two purposes of an elegy performed at a funeral.",
        ["It honours the dead by recalling their virtues.", "It consoles the living and expresses the community's grief together."], "It honours the dead and consoles the living.")],
   [m("A poem that honours a leader or hero is a...", "praise poem", ["riddle", "lullaby", "limerick"], "Praise poem."),
    m("A poem that mourns the dead is an...", "elegy or dirge", ["ode of war", "riddle", "advertisement"], "Elegy."),
    t("Oral poetry depends on voice, rhythm and an audience.", True, "Performance matters."),
    m("*Father of the Harvest* is an example of an...", "epithet", ["epilogue", "prologue", "act"], "Descriptive name."),
    m("One difference between oral and written poetry is that oral poetry is...", "performed and may change", ["never performed", "always fixed", "silent"], "Oral changes."),
    o("Write a short original praise poem (4–6 lines) honouring a teacher, a farmer or a nurse. Use parallelism, an epithet and one metaphor. Then explain each device in one sentence.",
      "Mother of the Healing Hands, you are the lamp in our dark nights; you are the river that washes our fear; you are the shield that guards our children. Devices: epithet (Mother of the Healing Hands), parallelism (you are the ... that ...), metaphor (the lamp, the river, the shield).",
      ["1 mark: original poem.", "1 mark: parallelism and epithet.", "1 mark: metaphor.", "1 mark: devices explained."])],
   [sc("Parallelism is...", "repeated similar structures", ["a rhyme scheme only", "a stage direction", "a title"], "Parallelism."),
    sc("A dirge is sung at...", "a funeral", ["a football match", "a school lesson", "a market"], "Funeral."),
    sc("Call-and-response involves...", "a leader and an answering group", ["a silent audience", "only the writer", "a printed page"], "Leader and group."),
    sc("Praise poems may also...", "advise or criticise gently", ["only insult", "be silent", "have no meaning"], "They advise too."),
    sc("An epithet is...", "a descriptive name or title", ["a rhyme", "a pause", "a stanza"], "Epithet.")],
   notes=["Oral praise poetry and dirges exist in many communities with different conventions; the lesson is general and does not describe any specific tradition. Local examples should be added by a teacher or by speakers of the language."], literature=True)

sk = p.chapter("ch-skills", "Terms and exam technique", REF)

LS(sk, "literary-terms-review", "Literary terms: a working glossary", 24,
   ["Define and recognise the key literary terms of Forms 1-4.", "Match terms to examples.", "Use terms correctly in a short written answer."],
   [tx("Throughout Forms 1 to 4 you have met many literary terms. In this lesson they are grouped by area so that you can revise them quickly. Remember: **knowing a term is not enough**. In every answer you must **name** the device, **quote** it and **explain its effect**."),
    ky("definition", "Prose and drama terms",
       "- **Plot, setting, character, theme, conflict**; **protagonist / antagonist**; **flashback, foreshadowing**.\n- **Narrator, point of view** (first person, third limited, omniscient), **unreliable narrator**.\n- **Climax, resolution, dénouement**.\n- **Act, scene, dialogue, stage directions, soliloquy, aside, dramatic irony, tragedy, comedy**."),
    ky("definition", "Poetry and figures of speech",
       "- **Stanza, line, rhyme, rhythm, refrain, free verse, ballad, sonnet, elegy, ode**.\n- **Simile, metaphor, personification, hyperbole, understatement, irony, symbol, imagery**.\n- **Alliteration, assonance, onomatopoeia, repetition**.\n- **Tone, mood, diction, syntax, connotation, register**.\n- **Oral literature:** folktale, fable, myth, legend, epic, proverb, riddle, praise poem, dirge."),
    fg(cols("Term and example", ["Term", "Example"], [["simile", "like a thief"], ["metaphor", "the sun is a coin"], ["alliteration", "bang, bargains, buzz"], ["hyperbole", "a thousand times"], ["irony", "the best speaker loses"]], w=450),
       "Learn a clear example for each term.", "A table of literary terms with examples: simile like a thief, metaphor the sun is a coin, alliteration bang bargains buzz, hyperbole a thousand times, irony the best speaker loses."),
    ky("pieges", "Common mistakes",
       "- Using a term in the wrong sense (*irony* for bad luck, *myth* for a lie).\n- Listing terms with no examples.\n- Giving examples that do not fit the term.\n- Forgetting the effect.\n- Confusing **tone** and **mood**, **simile** and **metaphor**, **aside** and **soliloquy**."),
    exm("Example 1: name the term", "Name the device in *The old bus groaned up the hill.*",
        ["A bus cannot groan: a human action is given to a thing.", "That is personification (and onomatopoeia in *groaned*)."], "personification"),
    exm("Example 2: use a term in a sentence", "Write a sentence using the term *irony* correctly.",
        ["Show a contrast between expectation and reality.", "A fire station that burns down is an example."], "It is ironic that the fire station burned down.")],
   [m("A comparison with *like* or *as* is a...", "simile", ["metaphor", "irony", "ballad"], "Simile."),
    m("The attitude of the writer is the...", "tone", ["mood", "plot", "stanza"], "Tone."),
    t("A soliloquy is a short remark to the audience while others are on stage.", False, "That is an aside. A soliloquy is a character speaking alone."),
    m("A story about the origin of the world is a...", "myth", ["riddle", "limerick", "act"], "Myth."),
    mt("Match each term to its meaning.", [["foreshadowing", "a hint of what comes later"], ["dirge", "a poem or song of mourning"], ["epithet", "a descriptive name or title"], ["understatement", "making something seem smaller"]], "Definitions."),
    o("Write a short paragraph (5–6 sentences) about a story, poem or play you know, using at least five literary terms correctly. Underline each term.",
      "In the folktale of the tortoise, the protagonist is the tortoise, and the conflict is between his greed and his fear. The setting is a village, and the narrator tells the story in the third person. The climax is when he falls from the sky, and the theme is that greed leads to downfall. The tale is a fable because it ends with a moral.",
      ["1 mark: five terms used correctly.", "1 mark: terms linked to the text.", "1 mark: explanation of at least one effect.", "1 mark: clear writing."])],
   [sc("The central idea of a text is its...", "theme", ["setting", "rhyme", "stanza"], "Theme."),
    sc("A character who is the main one is the...", "protagonist", ["narrator", "foil", "epilogue"], "Protagonist."),
    sc("Exaggeration for effect is...", "hyperbole", ["understatement", "simile", "stanza"], "Hyperbole."),
    sc("An all-knowing narrator is...", "omniscient", ["limited", "first person", "unreliable"], "Omniscient."),
    sc("A repeated line in a poem is a...", "refrain", ["scene", "prologue", "act"], "Refrain.")],
   literature=True)

LS(sk, "essay-planning-timing", "Planning an essay under time pressure", 28,
   ["Analyse an essay question and choose a thesis.", "Make a quick plan and manage time.", "Write a clear essay with evidence in 35-40 minutes."],
   [tx("In the examination you have limited time. A good essay comes from a **quick plan**. Spend the first **5 minutes** reading the question and planning, the next **30 minutes** writing, and the last **5 minutes** checking. Example question on an original text: *How does the writer of 'The Weight of the Basket' show the relationship between mother and daughter?*"),
    ky("methode", "Analysing the question",
       "1. **Circle the key words:** *how*, *show*, *relationship*, *mother and daughter*.\n2. Note the **command word**: *how* = explain the methods; *discuss* = consider more than one view; *compare* = similarities and differences.\n3. Decide your **thesis** in one sentence.\n4. List **three points**, each with one **quotation**.\n5. Order the points: strongest first or building to the strongest."),
    ky("methode", "A five-minute plan",
       "**Thesis:** the relationship is loving but teaches through patience.\n**Point 1:** Mama's calm teaching: *the basket teaches me patience*.\n**Point 2:** Neba's mistake and Mama's silent response: *picked them up one by one, saying nothing*.\n**Point 3:** Neba's change: *Teach me to carry it*.\n**Conclusion:** love shown in actions rather than words.\nWrite the **introduction** with the thesis; then **one paragraph per point** (PEE+link); then the conclusion."),
    fg(cols("Time plan: 40 minutes", ["Task", "Minutes"], [["read and plan", "5"], ["introduction", "4"], ["three paragraphs", "24"], ["conclusion", "3"], ["check", "4"]], w=430),
       "Use your time on purpose.", "A table with the time plan for a 40 minute essay: read and plan 5 minutes, introduction 4, three paragraphs 24, conclusion 3, check 4."),
    ky("pieges", "Common mistakes",
       "- Starting to write without a plan.\n- Misreading the **command word**.\n- Spending too long on the introduction and having no time for a conclusion.\n- Writing everything you know instead of answering the question.\n- Not checking spelling and quotations."),
    exm("Example 1: the command word", "What does the command word *how* in the question ask you to do?",
        ["*How* asks about methods and techniques.", "You must explain the ways in which the writer shows the relationship."], "explain the methods or techniques the writer uses"),
    exm("Example 2: a plan", "Write a quick plan for the question: *How does the writer present Tabi in 'Two Brothers'?*",
        ["Thesis: Tabi is careful but changes.", "Three points with evidence: neat notebooks; his pride; his realisation at the door."], "Thesis: Tabi is careful and proud but learns humility. P1: neat notebooks (pride). P2: he thinks before he speaks (seriousness). P3: he realises his brother has the bigger heart (change). Conclusion: kindness matters most.")],
   [m("The first thing to do in an essay is to...", "read and analyse the question", ["start writing at once", "write the conclusion", "copy the passage"], "Analyse first."),
    m("The command word *how* asks you to explain...", "the methods used by the writer", ["only the plot", "only the date", "only the title"], "Methods."),
    t("A short plan helps you to write a clearer essay.", True, "Plan first."),
    m("What should you do in the last five minutes?", "check spelling and quotations", ["write a new essay", "leave", "retell the story"], "Check."),
    m("A good plan includes...", "a thesis and three points with evidence", ["only a title", "only the conclusion", "only the date"], "Thesis and points."),
    o("Write a plan (thesis, three points with a short quotation or detail each, and a conclusion idea) for the question: *How does the writer create sympathy for the old man in 'Night Duty' (Form 4 literature)?*",
      "Thesis: The writer creates sympathy by showing his loneliness and the nurse's gentleness. Point 1: he is awake and staring at the ceiling (isolation). Point 2: *Too many memories* (sadness of the past). Point 3: the nurse's gentle act and the ward breathing more gently (comfort). Conclusion: small acts of kindness answer loneliness.",
      ["1 mark: thesis.", "2 marks: three points with evidence.", "1 mark: conclusion idea.", "1 mark: clear and ordered."])],
   [sc("The command word *discuss* asks you to...", "consider more than one view", ["list only the date", "write a poem", "copy the passage"], "Discuss."),
    sc("A plan should be made in about...", "five minutes", ["fifty minutes", "no time", "an hour"], "Quick."),
    sc("A conclusion should...", "restate the thesis and close", ["start a new topic", "list new evidence", "be left out"], "Close."),
    sc("The best order of points is...", "strongest first or building to the strongest", ["random", "alphabetical", "shortest first"], "Order."),
    sc("Key words in the question should be...", "circled or underlined", ["ignored", "copied entirely", "erased"], "Underline.")],
   literature=True)

p.write()
