import sys
sys.path.insert(0, "/home/user/CastBridge/tools/learn-authoring/anglophone")
from fe_kit import *

p = lit_pack("form2-literature", 2,
    "A second-year literature course with original stories, poems and scenes: plot and conflict, character development, sound devices in poetry, mood and tone, conflict in drama, riddles, songs and oral performance, irony, hyperbole and symbol, and the point-evidence-explain paragraph. Official set texts are not included.",
    "Form 2 Literature in English — general skills only; the official set texts (prose, poetry, drama) must be added by a teacher (to be checked against the official programme)")
REF = "Form 2 Literature in English — transferable reading skills (set texts to be added by a teacher)"

pr = p.chapter("ch-prose", "Prose: plot and character", REF)

LS(pr, "plot-conflict", "Plot and conflict", 26,
   ["Identify the stages of a plot in a short story.", "Name the types of conflict.", "Explain how the conflict drives the story."],
   [tx("**The Borrowed Bicycle**\nNgwa borrowed his uncle's bicycle to carry cassava to the market and promised to return it before dark. On the way a tyre burst. He pushed the bike for three miles, sold the cassava cheaply and arrived home after night had fallen, tired and afraid. His uncle was standing at the gate with a lamp. \"I was not worried about the bicycle,\" he said quietly. \"I was worried about you.\""),
    ky("definition", "Stages of a plot",
       "- **Exposition:** introduces character and situation (Ngwa borrows the bicycle and promises to return it).\n- **Rising action:** the problem grows (the tyre bursts, he pushes the bike, he is late).\n- **Climax:** the turning point or most tense moment (he reaches the gate; will his uncle be angry?).\n- **Falling action and resolution:** the result (the uncle shows kindness, not anger)."),
    ky("definition", "Types of conflict",
       "A **conflict** is the struggle that drives the plot.\n- **Person against person:** two characters disagree.\n- **Person against nature:** a storm, a flood, a long journey.\n- **Person against society:** one person challenges a rule or tradition.\n- **Person against himself:** an inner struggle (fear, guilt, temptation).\nIn the story the main conflict is **person against circumstances** (the burst tyre, the dark) and a small inner worry about disappointing his uncle."),
    fg(shapes([T(210, 22, "Plot diagram", 15, bold=True), LINE(20, 170, 120, 120, width=3, color="blue"), LINE(120, 120, 210, 50, width=3, color="blue"),
               LINE(210, 50, 300, 120, width=3, color="orange"), LINE(300, 120, 400, 170, width=3, color="orange"), CIRCLE(210, 50, 6, fill="red", stroke="red"),
               T(70, 192, "Exposition", 12, bold=True), T(130, 150, "Rising action", 12, anchor="end"), T(222, 42, "Climax", 13, bold=True, color="red", anchor="start"), T(290, 150, "Falling action", 12, anchor="start"), T(360, 192, "Resolution", 12, bold=True)], 420, 205),
       "The plot rises to a climax and then falls to a resolution.", "A mountain shaped plot diagram labelled exposition, rising action, climax at the peak, falling action and resolution."),
    ky("pieges", "Common mistakes",
       "- Retelling every event instead of naming the **stage**.\n- Confusing the climax with the ending: the climax is the **peak of tension**.\n- Saying a story has no conflict because nobody fights: conflicts can be **inner** or against nature.\n- Giving the setting as the only place.\n- Forgetting to say **how the conflict ends**."),
    exm("Example 1: find the climax", "Which moment is the climax of *The Borrowed Bicycle*?",
        ["The climax is the moment of highest tension.", "It is when Ngwa reaches the gate in the dark and sees his uncle waiting."], "When Ngwa arrives home in the dark and sees his uncle at the gate."),
    exm("Example 2: type of conflict", "What kind of conflict is *the burst tyre and the long walk in the dark*?",
        ["The problem is not another person but the circumstances: distance, darkness, the broken bike.", "That is person against nature / circumstances."], "person against circumstances (nature)")],
   [m("Which stage includes the burst tyre?", "rising action", ["exposition", "resolution", "title"], "The problem grows."),
    m("The moment of greatest tension is the...", "climax", ["exposition", "title", "setting"], "Climax."),
    t("A story can have an inner conflict as well as an outer one.", True, "Characters can struggle with fear or guilt."),
    m("Which conflict type is a farmer fighting a flood?", "person against nature", ["person against person", "person against society", "no conflict"], "Flood = nature."),
    m("The resolution of *The Borrowed Bicycle* is that...", "the uncle shows kindness and is relieved Ngwa is safe", ["the uncle punishes Ngwa", "the bicycle is lost", "Ngwa leaves the village"], "He says he was worried about Ngwa."),
    o("Choose a story or film you know. In five sentences, describe its exposition, main conflict, climax and resolution.",
      "In the story of Cinderella-style tales the exposition shows a kind girl treated badly. The main conflict is between her and her cruel stepsisters. The climax is the moment when the shoe is tried on. The resolution is that she is recognised and lives happily.",
      ["1 mark: exposition.", "1 mark: conflict with its type.", "1 mark: climax.", "1 mark: resolution, clearly written."])],
   [sc("Exposition...", "introduces characters and situation", ["ends the story", "is the climax", "is a poem"], "Exposition."),
    sc("Falling action comes...", "after the climax", ["before the story", "instead of the title", "before the exposition"], "After the climax."),
    sc("Person against self is...", "an inner conflict", ["a storm", "a fight", "a trick"], "Inner."),
    sc("The conflict is...", "the struggle that drives the plot", ["the title", "the rhyme", "the stage direction"], "Conflict."),
    sc("The resolution is...", "how the conflict ends", ["how it begins", "the setting", "the narrator"], "Ending.")],
   literature=True)

LS(pr, "character-development", "Character development and relationships", 26,
   ["Tell round characters from flat ones.", "Show how a character changes during a story.", "Compare two characters (a foil)."],
   [tx("**Two Brothers**\nTabi and Nkem shared a small room. Tabi, the elder, never spoke before thinking; his notebooks were neat and his shoes always cleaned. Nkem laughed loudly, forgot his keys twice a week and could not walk past a football without kicking it. When their mother fell ill, Nkem sat beside her bed all night, singing softly. Tabi, standing at the door, realised for the first time that his careless brother had the bigger heart."),
    ky("definition", "Kinds of character",
       "- **Round** characters are complex and may change (Tabi, who learns something).\n- **Flat** characters have one main trait and stay the same (a greedy chief in a folktale).\n- **Dynamic** characters change; **static** characters do not.\n- **Protagonist** is the main character; **antagonist** is the one who opposes him or her.\n- **Foil:** a character who is a **contrast** to another and so makes his or her qualities stronger (Tabi is careful and neat; Nkem is careless and warm)."),
    ky("methode", "Showing change",
       "To describe how a character develops: 1. Say what he or she is like at the **beginning** (*Tabi is careful, proud of being neat and serious*). 2. Find the **turning point** (his mother falls ill). 3. Say what he is like at the **end** (he respects his brother). 4. Give **evidence** for each stage."),
    fg(cols("Tabi and Nkem compared", ["Tabi", "Nkem"], [["careful", "careless"], ["neat", "forgetful"], ["serious", "loud, cheerful"], ["thinks first", "acts first"], ["learns respect", "shows love"]], w=430),
       "A foil highlights a character's qualities by contrast.", "A table comparing the brothers: Tabi is careful, neat, serious, thinks first and learns respect; Nkem is careless, forgetful, loud and cheerful, acts first and shows love."),
    ky("pieges", "Common mistakes",
       "- Saying a character is *good* or *bad* only.\n- Describing looks, not personality.\n- Forgetting to give **evidence**.\n- Saying a character changes without showing the **turning point**.\n- Mixing up characters' qualities when comparing them."),
    exm("Example 1: a quality with evidence", "What is Nkem like? Give a quality and evidence.",
        ["Quality: loving and warm-hearted.", "Evidence: he sat beside his mother's bed all night, singing softly."], "Nkem is loving: he sat beside his sick mother all night, singing softly."),
    exm("Example 2: character change", "How does Tabi change?",
        ["At first he thinks being careful and neat is what matters.", "After seeing Nkem care for their mother he realises that the careless brother has the bigger heart: he learns humility."], "Tabi starts proud of being neat and learns that kindness matters more.")],
   [m("A character who is a contrast to another is a...", "foil", ["narrator", "stanza", "prop"], "A foil."),
    m("A round character is...", "complex and may change", ["simple and never changes", "always evil", "always silent"], "Round."),
    t("Tabi changes during the story.", True, "He learns to respect his brother."),
    m("Which word describes Nkem?", "warm-hearted", ["cold", "secretive", "greedy"], "He cares for his mother."),
    m("The turning point for Tabi is when...", "his mother falls ill and Nkem cares for her", ["he cleans his shoes", "he loses his notebook", "he plays football"], "That event changes his view."),
    o("Write a short paragraph (4–5 sentences) comparing Tabi and Nkem and saying what the writer wants us to learn from the contrast. Use one quotation or detail for each brother.",
      "Tabi is careful and serious: his notebooks are neat and he thinks before he speaks. Nkem is careless and cheerful: he forgets his keys and kicks every football. The contrast shows that neatness and seriousness are not the same as kindness. When their mother is ill, Nkem sits beside her all night singing, which shows he has the bigger heart. The writer teaches that real goodness is shown in love, not in appearance.",
      ["1 mark: Tabi with detail.", "1 mark: Nkem with detail.", "1 mark: the contrast explained.", "1 mark: the lesson, clear writing."])],
   [sc("A static character...", "does not change", ["always changes", "is a narrator", "is a poem"], "Static."),
    sc("The main character is the...", "protagonist", ["antagonist", "foil", "chorus"], "Protagonist."),
    sc("A foil...", "shows a contrast with another character", ["is the narrator", "is a rhyme", "is a setting"], "Contrast."),
    sc("To show change in a character you need...", "a beginning, a turning point and an end", ["only a title", "a rhyme scheme", "a stage direction"], "Stages of change."),
    sc("Evidence for a quality is...", "a detail or quotation", ["a guess", "your age", "the page number"], "Evidence.")],
   literature=True)

po = p.chapter("ch-poetry", "Poetry: sound, mood and meaning", REF)

LS(po, "poetry-sound-devices", "Sound devices in poetry", 26,
   ["Recognise alliteration, assonance, onomatopoeia, rhyme and repetition.", "Explain the effect of sound devices.", "Read a poem aloud to bring out its sound."],
   [tx("**Market Music**\nBuckets bang and bargains buzz,\nsellers shout and shoppers sway;\nplantain pops in sizzling oil\nwhile the radio hums away.\nClink, clank, clatter, crash,\nhooves and horns and heavy feet:\nthe whole town sings its morning song\nin the music of the street."),
    ky("definition", "Sound devices",
       "- **Alliteration:** repeated **consonant** sounds at the start of nearby words: *Buckets bang and bargains buzz*.\n- **Assonance:** repeated **vowel** sounds: *hooves and horns and heavy feet* (the *h* is also alliteration).\n- **Onomatopoeia:** words that imitate sounds: *bang, buzz, pops, sizzling, clink, clank, clatter, crash*.\n- **Rhyme:** matching end-sounds (*sway / away*, *feet / street*).\n- **Repetition:** repeated words or phrases for emphasis."),
    ky("methode", "Explaining the effect",
       "Do not just list devices. **Quote**, **name** and **explain**: *The alliteration of b in \"Buckets bang and bargains buzz\" imitates the hard, noisy sounds of the market and gives the line a lively rhythm.* Ask: what **sound or feeling** does the device create? Is the rhythm fast (short sounds) or slow (long vowels)?"),
    fg(cols("Sound devices", ["Device", "Example"], [["alliteration", "bang, bargains, buzz"], ["onomatopoeia", "clink, clank, crash"], ["rhyme", "sway / away"], ["repetition", "the same word again"]], w=430),
       "Say the lines aloud: you will hear the devices.", "A table of sound devices with examples: alliteration bang bargains buzz, onomatopoeia clink clank crash, rhyme sway and away, and repetition of the same word."),
    ky("pieges", "Common mistakes",
       "- Confusing **alliteration** (same *consonant* sound) with **rhyme** (same *ending*).\n- Listing devices without explaining their **effect**.\n- Judging alliteration by letters rather than sound (*knife* and *nice* both begin with the sound *n*).\n- Reading a poem silently only: sound devices must be **heard**.\n- Calling any noisy word *onomatopoeia*: it must **imitate** a sound."),
    exm("Example 1: spot the device", "Name the device in *Clink, clank, clatter, crash*.",
        ["The words imitate the sounds of metal and objects.", "That is **onomatopoeia** (with alliteration of *cl*)."], "onomatopoeia"),
    exm("Example 2: explain the effect", "Explain the effect of *Buckets bang and bargains buzz*.",
        ["Device: alliteration of the hard b sound.", "Effect: imitates the noise and energy of the market; the beat is quick and lively."], "The repeated b sound imitates the noisy, lively market.")],
   [m("*Buckets bang and bargains buzz* is an example of...", "alliteration", ["rhyme", "simile", "stanza"], "Repeated b sounds at the start of words."),
    m("*Sizzling* imitates a sound, so it is...", "onomatopoeia", ["simile", "metaphor", "personification"], "It copies a sound."),
    t("Alliteration is the repetition of vowel sounds at the end of lines.", False, "It is repeated consonant sounds, usually at the beginning of words."),
    m("Which pair rhymes?", "sway / away", ["sway / sing", "clink / crash", "feet / hum"], "They have the same ending sound."),
    m("The effect of the many short, hard sounds in the poem is to...", "create a busy, noisy mood", ["create a sleepy mood", "create sadness", "create silence"], "Hard sounds suggest noise."),
    o("Write four lines about a Cameroonian setting (a football match, rain, a school bell) using at least one example each of alliteration, onomatopoeia and rhyme. Underline each device and name it.",
      "The bell begins to clang and ring,\nthe children run, they shout, they sing,\nswift shoes go slap on the sunny road,\nthe school is waking its bright abode. (Models: alliteration swift/shoes, sunny; onomatopoeia clang, slap; rhyme ring/sing.)",
      ["1 mark: alliteration.", "1 mark: onomatopoeia.", "1 mark: rhyme.", "1 mark: devices named and a clear theme."])],
   [sc("Alliteration is the repetition of...", "initial consonant sounds", ["end rhymes", "stanzas", "titles"], "Consonant sounds."),
    sc("*Buzz* and *crash* are examples of...", "onomatopoeia", ["personification", "metaphor", "rhyme scheme"], "Sound words."),
    sc("Assonance repeats...", "vowel sounds", ["consonants only", "whole words only", "stanzas"], "Vowel sounds."),
    sc("To get full marks on a sound device, you should...", "explain its effect", ["only list it", "only quote it", "ignore it"], "Explain effect."),
    sc("A poem is best enjoyed...", "read aloud", ["never read", "read backwards", "only copied"], "Sound matters.")],
   literature=True)

LS(po, "poem-mood-tone", "Mood, tone and imagery in a poem", 26,
   ["Tell mood from tone.", "Identify imagery that appeals to the senses.", "Explain how word choice creates mood."],
   [tx("**After the Funeral**\nThe yard is empty now. The plastic chairs\nstand in rows like a silent class.\nSomeone has left a cup of cold tea\nand the radio, switched low, hums an old song.\nGrandmother sits on the step in her black cloth,\nlooking at the road where nobody walks.\nThe evening wind turns the pages\nof a hymn book nobody will read."),
    ky("definition", "Mood and tone",
       "- **Mood** is the feeling created **in the reader** (here: sad, quiet, lonely).\n- **Tone** is the **attitude of the speaker or poet** (here: gentle, sorrowful, respectful).\nWords such as *empty, silent, cold, low, black, nobody, old* build the mood. A poem can have more than one mood, or change mood at the end."),
    ky("definition", "Imagery",
       "**Imagery** is language that makes us **see, hear, smell, taste or touch** in the imagination. In the poem: **sight** (*plastic chairs in rows, black cloth*), **sound** (*the radio hums*), **touch** (*cold tea, evening wind*). Imagery can use similes and metaphors (*chairs like a silent class*). Ask what the images **suggest** about feelings."),
    fg(tree("What makes a mood?", "Mood", [("Word choice", "empty, cold"), ("Imagery", "senses, pictures"), ("Sound", "slow, soft")], h=185),
       "Choose three or four words that show the mood and explain them.", "A diagram with Mood at the top and three arrows to Word choice (empty, cold), Imagery (senses, pictures) and Sound (slow, soft)."),
    ky("pieges", "Common mistakes",
       "- Mixing up **mood** (reader's feeling) and **tone** (speaker's attitude).\n- Naming the mood with weak words (*bad, nice*): use *sad, lonely, peaceful, tense*.\n- Listing words with no explanation.\n- Saying the poem is *about death* only: say how the speaker **feels** and what the images suggest.\n- Not reading the whole poem: the mood can change at the end."),
    exm("Example 1: mood", "What mood is created by the first two lines of *After the Funeral*?",
        ["Words: *empty*, *rows*, *silent class*.", "The mood is quiet and lonely."], "quiet and lonely"),
    exm("Example 2: imagery", "Explain the image *a cup of cold tea*.",
        ["Image of touch and sight: a cup left behind, no longer warm.", "It suggests that people have gone, and that a loved one is no longer there to drink it."], "The cold tea suggests absence and emptiness after people have left.")],
   [m("The mood of *After the Funeral* is...", "quiet and sad", ["noisy and joyful", "angry and violent", "funny"], "The words show sadness."),
    m("Which word helps to create a lonely mood?", "empty", ["bright", "loud", "dancing"], "Empty."),
    t("Mood is the feeling the poem creates in the reader.", True, "Mood is in the reader; tone is the speaker's attitude."),
    m("*The radio hums* appeals to the sense of...", "hearing", ["taste", "smell", "sight only"], "Hum = sound."),
    m("The tone of the speaker is...", "gentle and sorrowful", ["mocking", "angry", "excited"], "The speaker observes quietly with sympathy."),
    o("In four sentences, explain how two images in *After the Funeral* create a sad, lonely mood. Quote key words.",
      "The image of *plastic chairs in rows like a silent class* shows an empty yard where people were sitting, so we feel the absence. The *cup of cold tea* shows that someone has left and the warmth is gone. Together the images create a quiet, lonely mood.",
      ["1 mark: first image with quotation.", "1 mark: second image with quotation.", "1 mark: explanation of each.", "1 mark: mood named, clear writing."])],
   [sc("Imagery appeals to...", "the senses", ["the rhyme only", "the stanza only", "the title"], "Senses."),
    sc("Tone is the...", "speaker's attitude", ["reader's feeling", "rhyme", "plot"], "Tone."),
    sc("A word that helps build a sad mood is...", "silent", ["cheerful", "bright", "festival"], "Silent."),
    sc("A poem's mood may...", "change at the end", ["never change", "be the title", "be a rhyme"], "It may change."),
    sc("To explain an image you should say...", "what it suggests", ["what colour the page is", "the poet's age", "the number of lines"], "Suggestion.")],
   literature=True)

dr = p.chapter("ch-drama-oral", "Drama and oral literature", REF)

LS(dr, "drama-scene-conflict", "Conflict and character in a scene", 26,
   ["Identify the conflict in a short scene.", "Use stage directions and dialogue to describe character.", "Explain how a scene builds tension."],
   [tx("**The Exam Fee**\nMAMA FORBI is counting a few coins by the lamp. Her son, TABI, enters.\nTABI: Mama, the school wants the exam fee tomorrow.\nMAMA FORBI: (not looking up) How much?\nTABI: (quietly) Fifteen thousand francs.\nMAMA FORBI: (pause) Then we shall find it.\nTABI: (looking at the coins) But we do not have it.\nMAMA FORBI: (gently closing his hand over the coins) I did not say we have it. I said we shall find it."),
    ky("definition", "Conflict in drama",
       "Drama needs **conflict**: a problem or disagreement that creates tension. In *The Exam Fee* the conflict is **person against circumstances**: the family has little money, but the fee is needed tomorrow. The mother's calm reply reveals her **character**: she is determined and loving, unlike her son who is worried."),
    ky("methode", "Reading character in a scene",
       "1. **Dialogue:** what do they say and how (short sentences show tension)?\n2. **Stage directions:** *(not looking up)*, *(pause)*, *(gently closing his hand)* show feelings and movement.\n3. **Pauses and silences** are part of the meaning.\n4. **Reactions:** how one character replies to the other.\nTogether they show: Tabi is anxious and honest; his mother is quiet, strong and wise."),
    fg(shapes([T(210, 22, "The conflict in The Exam Fee", 15, bold=True), RECT(20, 60, 130, 50, fill="lightblue", radius=8), T(85, 90, "Mama Forbi", 13), RECT(270, 60, 130, 50, fill="lightgreen", radius=8), T(335, 90, "Tabi", 13),
               LINE(150, 85, 270, 85, arrow="both", color="red", width=2), T(210, 78, "need money", 12, color="red"), T(210, 150, "Fee: 15 000 FCFA, due tomorrow", 13), T(210, 175, "Little money, a lot of love", 13)], 420, 200),
       "The tension comes from the gap between need and means.", "A diagram of two boxes, Mama Forbi and Tabi, joined by a double arrow marked need money, with the note fee 15000 FCFA due tomorrow and little money but a lot of love."),
    ky("pieges", "Common mistakes",
       "- Ignoring the stage directions when describing character.\n- Describing the plot only, without saying what the scene **shows**.\n- Forgetting that a play is performed: think of **voice, pauses and movement**.\n- Calling any argument *conflict* when there is no real clash.\n- Mixing up what a character **says** with what he or she **means**."),
    exm("Example 1: the conflict", "What is the conflict in the scene?",
        ["Tabi needs the exam fee tomorrow.", "The family has only a few coins: the problem is lack of money."], "The family needs the exam fee but has very little money."),
    exm("Example 2: character from a stage direction", "What does the direction *(gently closing his hand over the coins)* show about Mama Forbi?",
        ["The gesture is soft and protective.", "She comforts her son and shows love and calm confidence."], "She is loving and reassuring.")],
   [m("What does Tabi want?", "money for the exam fee", ["a new bicycle", "a holiday", "a new uniform"], "He needs the fee."),
    m("Which stage direction shows Mama Forbi's calm?", "(gently closing his hand over the coins)", ["(counting coins)", "(enters)", "(looking up)"], "A gentle gesture."),
    t("A pause in a script can be part of the meaning.", True, "Silence can show worry or thought."),
    m("What is Mama Forbi's attitude at the end?", "hopeful and determined", ["angry and hopeless", "bored", "joyful"], "She says they will find it."),
    m("The conflict in the scene is mainly...", "person against circumstances", ["person against person", "person against nature", "person against society"], "Lack of money."),
    o("Write a short scene (8–10 lines) in which two characters disagree about something small (for example who should clean the room or whether to go to a football match). Include a cast list, stage directions and a clear conflict. End with the problem solved or still open.",
      "CHARACTERS: ADA and NGU, a sister and brother.\nSETTING: A living room on Saturday morning.\nADA: (holding a broom) It is your turn to clean the room.\nNGU: (without looking up from his book) I have a test on Monday.\nADA: (hands on hips) And I have a headache. That is not an excuse.\nNGU: (sighing, putting down the book) Fine. But you will help me revise tonight.\nADA: (smiling) Agreed.",
      ["1 mark: cast and setting.", "1 mark: a clear conflict.", "1 mark: stage directions that show feelings.", "1 mark: an ending (solved or open)."])],
   [sc("Drama needs...", "conflict", ["rhyme", "stanzas", "no characters"], "Conflict."),
    sc("A pause in a script usually shows...", "thinking or tension", ["the end of the play", "the title", "a joke"], "A pause."),
    sc("Stage directions are written...", "in brackets", ["in the title", "as rhyme", "in capitals only"], "Brackets."),
    sc("A character's reaction shows...", "feelings and attitude", ["the plot only", "the cast list", "the setting"], "Reaction."),
    sc("A scene builds tension by...", "increasing the problem", ["removing all problems", "adding rhyme", "adding a title"], "Problem grows.")],
   literature=True)

LS(dr, "oral-riddles-songs", "Oral literature: riddles, songs and performance", 24,
   ["Describe riddles, songs and lullabies as forms of oral literature.", "Explain features of oral performance: audience, repetition and rhythm.", "Create and explain a riddle."],
   [tx("In many communities children grow up with **riddles** at the fireside, **lullabies** at bedtime and **work songs** in the fields. These forms share features: **spoken or sung** rather than written, **repetition**, **rhythm**, and an **audience** who takes part. The performer may add new words, so no two performances are exactly the same."),
    ky("definition", "Riddles, songs and chants",
       "- **Riddle:** a puzzle in words: *What has a mouth but never eats? A river.* Riddles train **thinking** and use **metaphor**: the river is described as a body with a mouth.\n- **Lullaby:** a soft song to put children to sleep, with repeated gentle sounds.\n- **Work song:** a rhythm to help people to work together (pounding, paddling, harvesting).\n- **Praise song or chant:** celebrates a person or a group; **call and response**: the leader calls and the group answers."),
    ky("definition", "Oral performance",
       "An oral performance depends on **voice** (loud, soft, fast, slow), **gesture**, **audience participation**, **repetition** and **improvisation** (adding new lines). Because it is **live**, the **audience** shapes the performance. Written versions can only record **words**, not the tone and the movement."),
    fg(cols("Oral forms", ["Form", "When it is used"], [["riddle", "fireside, play"], ["lullaby", "bedtime"], ["work song", "farming, pounding"], ["praise song", "celebrations"]], w=430),
       "Each form has its place in daily life.", "A table of oral forms and when they are used: riddle at the fireside and play, lullaby at bedtime, work song while farming or pounding, and praise song at celebrations."),
    ky("pieges", "Common mistakes",
       "- Saying oral literature is *primitive* or *less important than written literature*.\n- Ignoring the role of the **audience**.\n- Treating a written record as the *only* correct version.\n- Naming a specific community's tradition without knowing its source: use general examples or ask elders.\n- Forgetting that songs and riddles use **figurative language**."),
    exm("Example 1: explain a riddle", "Riddle: *What goes up the hill and down the hill but never moves?* (Answer: the road.) Explain why this is a good riddle.",
        ["It uses a metaphor: the road is described as if it moved.", "It surprises the listener and tests thinking."], "It describes the road as if it moved, so the answer is a surprise."),
    exm("Example 2: call and response", "Why is call-and-response useful in a work song?",
        ["The leader sets the rhythm and the group answers together.", "It keeps everyone working in time and makes the work lighter."], "It sets a common rhythm and unites the workers.")],
   [m("A short puzzle in words is a...", "riddle", ["stanza", "scene", "stage direction"], "Riddle."),
    m("A soft song for putting a child to sleep is a...", "lullaby", ["work song", "chant of war", "riddle"], "Lullaby."),
    t("In an oral performance the audience can take part.", True, "Call and response, clapping, answering."),
    m("Call-and-response means...", "the leader calls and the group answers", ["the poet writes alone", "everyone is silent", "the audience reads"], "That is the pattern."),
    m("Why is no oral performance exactly the same twice?", "It is live and the performer or audience can change it.", ["It is written down", "It is printed", "It is never performed again"], "Live performance varies."),
    o("Write your own riddle (in English) with its answer, and explain in two or three sentences which figure of speech it uses and why it is clever.",
      "Riddle: I have a head but cannot think, a bed but never sleep; what am I? (A river: it has a head, the source, and a bed.) It uses a metaphor and personification: the river is described with human and body parts, which surprises the listener.",
      ["1 mark: original riddle.", "1 mark: answer.", "1 mark: figure of speech named.", "1 mark: explanation of why it works."])],
   [sc("A riddle tests...", "thinking", ["only memory of dates", "spelling", "handwriting"], "Thinking."),
    sc("A work song helps people to...", "work together in rhythm", ["sleep", "write", "read silently"], "Work together."),
    sc("An oral performance depends on...", "voice, gesture and audience", ["only paper", "only printing", "only silence"], "Performance."),
    sc("A lullaby is usually...", "soft and gentle", ["loud and fast", "silent", "angry"], "Gentle."),
    sc("Praise songs celebrate...", "a person or group", ["a rule of grammar", "a poem's title", "a rhyme only"], "They honour.")],
   notes=["Riddles and songs are traditional forms in many communities; those given here are general or original examples and no specific community's tradition is claimed."], literature=True)

sk = p.chapter("ch-skills", "Literary devices and writing about literature", REF)

LS(sk, "irony-hyperbole-symbol", "Irony, hyperbole and symbol", 26,
   ["Recognise irony, hyperbole, understatement and symbol.", "Explain the effect of each in a text.", "Use them in your own writing."],
   [tx("**The Prize**\nAda practised for weeks. On the day of the speech contest she wore her best dress and walked on stage with a smile. She spoke for three minutes without a mistake, and the hall clapped for a full minute. Then the judge announced the winner: Ngu, who had stopped five times. \"It was an easy decision,\" the judge said. Ada folded her speech and walked home beside the dusty road, her smile still painted on her face like a poster."),
    ky("definition", "Figures that add meaning",
       "- **Irony:** a contrast between what is expected and what happens, or between words and meaning. *Situational irony:* Ada gave the best speech and lost. *Verbal irony:* *\"It was an easy decision\"*.\n- **Hyperbole:** deliberate exaggeration: *I have told you a thousand times.*\n- **Understatement:** making something seem smaller: *It was a bit wet* (after a flood).\n- **Symbol:** an object that stands for an idea: a **dove** for peace; Ada's **painted smile** for hiding pain."),
    ky("methode", "Explaining irony and symbols",
       "Say **what is expected**, **what actually happens**, and the **effect** (humour, sadness, criticism): *The irony that the best speaker loses makes us feel the unfairness of the result.* For a symbol: name the object, the **idea** it stands for, and the **reason**: *The smile painted on her face like a poster suggests she is hiding her disappointment.*"),
    fg(cols("Figures of meaning", ["Figure", "Example"], [["irony", "the best speaker loses"], ["hyperbole", "a thousand times"], ["understatement", "a bit wet"], ["symbol", "dove = peace"]], w=430),
       "These figures work by contrast, exaggeration or hidden meaning.", "A table of figures with examples: irony, the best speaker loses; hyperbole, a thousand times; understatement, a bit wet; symbol, a dove for peace."),
    ky("pieges", "Common mistakes",
       "- Calling every unlucky event *ironic*: irony needs a **contrast with expectation**.\n- Taking hyperbole literally.\n- Naming a symbol without saying **what it stands for**.\n- Confusing **simile** (like/as) with **symbol**.\n- Inventing a meaning not supported by the text."),
    exm("Example 1: identify irony", "Why is the result of the contest ironic?",
        ["Expected: the best speaker wins.", "Actual: Ada spoke without a mistake, but Ngu, who stopped five times, wins."], "The best speaker loses, which is the opposite of what we expect."),
    exm("Example 2: symbol", "What does *her smile painted on her face like a poster* suggest?",
        ["A painted smile is not real.", "It suggests Ada pretends to be happy while she is disappointed."], "She is hiding her disappointment behind a false smile.")],
   [m("Ada loses although she was the best speaker. This is...", "situational irony", ["hyperbole", "simile", "alliteration"], "The outcome is the opposite of what is expected."),
    m("*I have told you a thousand times* is an example of...", "hyperbole", ["understatement", "irony", "rhyme"], "Exaggeration."),
    t("A symbol is an object that stands for an idea.", True, "E.g. a dove stands for peace."),
    m("*It was a bit wet* said after a big flood is...", "understatement", ["hyperbole", "metaphor", "onomatopoeia"], "It makes the event seem smaller."),
    m("What is the effect of the irony in *The Prize*?", "It makes the reader feel the unfairness.", ["It makes the story funny only", "It tells us the date", "It ends the story"], "We feel the unfairness."),
    o("Write a short paragraph (4–5 sentences) explaining how the writer uses irony and a symbol in *The Prize*. Quote briefly.",
      "The writer uses irony because Ada, who spoke *without a mistake*, loses to Ngu, who *stopped five times*. The judge's words *it was an easy decision* add verbal irony. The painted smile is a symbol of Ada hiding her pain. Together they make us feel her disappointment and the unfairness of the result.",
      ["1 mark: irony identified with quotations.", "1 mark: verbal irony or the judge's words.", "1 mark: symbol explained.", "1 mark: effect on the reader, clear writing."])],
   [sc("Irony shows a contrast between...", "expectation and reality", ["rhyme and rhythm", "title and author", "act and scene"], "Contrast."),
    sc("Deliberate exaggeration is...", "hyperbole", ["understatement", "simile", "irony"], "Hyperbole."),
    sc("A dove as a symbol of peace shows...", "an object standing for an idea", ["a rhyme", "a character", "a stage direction"], "Symbol."),
    sc("Understatement makes things seem...", "smaller than they are", ["bigger", "funnier", "rhymed"], "Understatement."),
    sc("An explanation of a symbol must say...", "what it stands for", ["the page number", "the poet's name", "the rhyme scheme"], "Meaning.")],
   literature=True)

LS(sk, "pee-paragraph-context", "Writing a paragraph and answering context questions", 26,
   ["Write a well-developed paragraph in response to a question.", "Answer a simple context question (who, where, what, why).", "Use evidence and correct English."],
   [tx("**The Fisherman's Son**\nKum's father mended nets every evening. \"Why do you work so hard?\" Kum asked. \"So that one day you will not have to,\" his father answered, tightening a knot with his teeth. Kum looked at the rough, cracked hands and said nothing. The next morning he was awake before the sun, carrying the nets to the boat without being asked."),
    ky("methode", "A well-built paragraph",
       "1. **Point:** a topic sentence that answers the question.\n2. **Evidence:** a short quotation or detail from the text.\n3. **Explain:** what the evidence shows and **why it matters**.\n4. **Link:** a final sentence that connects to the question or the next idea.\nUse **connectives**: *This shows..., Furthermore..., As a result...*"),
    ky("definition", "A context question",
       "A **context question** gives you a passage and asks about it: *Who is speaking? To whom? Where is the scene? What has just happened? What does this show about the speaker?* Answer **in full sentences** and use the **passage as evidence**. Typical questions: 1. **Locate** (where/when/who); 2. **Understand** (explain a word or action); 3. **Judge** (what it shows about character or theme)."),
    fg(flow("Answering a context question", ["Read the passage and question", "Find the key lines", "Answer in a full sentence with evidence", "Check you have answered every part"]),
       "Answer exactly what is asked, using the passage.", "A flowchart of four steps: read the passage and question, find the key lines, answer in a full sentence with evidence, and check you answered every part."),
    ky("pieges", "Common mistakes",
       "- Answering in single words when a sentence is needed.\n- Quotation with no explanation.\n- Writing about something not in the passage.\n- Forgetting the **second part** of a two-part question.\n- Spelling and grammar mistakes, especially in quotations."),
    exm("Example 1: a context question", "Who is speaking in *So that one day you will not have to*, and what does this show about him?",
        ["The speaker is Kum's father (he answers Kum's question).", "It shows that he works hard out of love, so that his son can have an easier life."], "Kum's father is speaking; the line shows that he works hard out of love for his son."),
    exm("Example 2: a paragraph", "Write a short paragraph on how Kum changes.",
        ["Point, evidence and explain.", "Link to the theme of love and responsibility."], "Kum changes from a curious boy into a responsible one. At first he only asks, but after seeing his father's \"rough, cracked hands\", he carries the nets to the boat \"without being asked\". This shows that he understands his father's sacrifice and wants to help.")],
   [m("A context question asks you to...", "answer using a passage given", ["write a poem", "draw a map", "count syllables"], "Use the passage."),
    m("Who speaks the words *So that one day you will not have to*?", "Kum's father", ["Kum", "the teacher", "the narrator only"], "He answers Kum's question."),
    t("A paragraph should have a point, evidence and an explanation.", True, "PEE."),
    m("What does Kum's early rising show?", "He wants to help his father.", ["He is lazy.", "He is afraid.", "He is angry."], "He carries the nets without being asked."),
    m("Which opening sentence of a paragraph is the best topic sentence about Kum?", "Kum changes from a curious boy into a responsible one.", ["Kum has nets.", "The story is short.", "A fisherman works."], "It answers the question."),
    o("Write a paragraph of 5–6 sentences answering: *What does the passage show about the relationship between Kum and his father?* Use two short quotations and finish with a link sentence.",
      "The passage shows a relationship of love and respect. Kum's father works hard \"so that one day you will not have to\", which shows his sacrifice. Kum sees his father's \"rough, cracked hands\" and says nothing, which suggests he feels respect and gratitude. The next morning he helps without being asked. This shows that the father's example has changed his son, and that love is shown in action.",
      ["1 mark: clear point.", "2 marks: two quotations used well.", "1 mark: explanation of each.", "1 mark: link sentence and clear writing."])],
   [sc("The final sentence of a paragraph is often a...", "link", ["title", "date", "rhyme"], "Link."),
    sc("A context question needs answers that are...", "supported by the passage", ["invented", "very long poems", "one letter"], "Evidence."),
    sc("When a question has two parts you should...", "answer both parts", ["answer only the first", "answer only the second", "skip it"], "Both."),
    sc("A topic sentence...", "answers the question directly", ["introduces a new topic", "is a quotation only", "is the title"], "Direct."),
    sc("Connectives help to...", "link ideas clearly", ["lengthen the title", "add rhyme", "end the passage"], "Connect.")],
   literature=True)

p.write()
