import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _b import *

reset_extension("fslc-english", 4, {"fslc-english-mock-1"})
p = Pack("fslc-english", None, None, None, None, extend=True)
REF = "MINEDUB — Anglophone primary curriculum, Level III (Classes 5 and 6), English Language — to be checked against the official text"

def grid(items, cols=4, cw=92, ch_=62, gap=8, fills=("lightblue", "lightyellow", "lightgreen"), x0=None, y0=14, size=13):
    """boxes with (title, example) text; returns a shapes figure"""
    rows = (len(items) + cols - 1) // cols
    w = 400; x0 = x0 if x0 is not None else (w - cols * cw - (cols - 1) * gap) // 2
    its = []
    for i, (a, b) in enumerate(items):
        r, c = divmod(i, cols); x = x0 + c * (cw + gap); y = y0 + r * (ch_ + gap)
        its += [RECT(x, y, cw, ch_, fill=fills[i % len(fills)], radius=6), T(x + cw / 2, y + 26, a, size, bold=True), T(x + cw / 2, y + 48, b, size - 1)]
    return shapes(its, w, max(110, y0 + rows * (ch_ + gap) + 6))

# =========================================================== chapter 5: parts of speech
ch = p.chapter("word-classes", "Parts of speech", REF)
fig_pos = grid([("noun", "Mary, school"), ("pronoun", "he, they"), ("verb", "run, is"), ("adjective", "tall, red"),
                ("adverb", "quickly"), ("preposition", "on, under"), ("conjunction", "and, but"), ("interjection", "Wow! Oh!")])
build(ch, "parts-of-speech", "Parts of speech", 30,
    ["Name the eight parts of speech and say what each one does.", "Pick out nouns, pronouns, verbs, adjectives and adverbs in a sentence.", "Use the correct part of speech to complete a sentence."],
    [("key", "definition", "The parts of speech", "Every word in a sentence has a job. A **noun** names a person, place, thing or idea (Mary, Douala, mango). A **pronoun** takes the place of a noun (he, she, it, they). A **verb** shows an action or a state (run, eat, is). An **adjective** describes a noun (tall, ripe). An **adverb** tells how, when or where (quickly, today, here)."),
     ("key", "definition", "More parts of speech", "A **preposition** shows position or link (on, under, in, with). A **conjunction** joins words or sentences (and, but, because, or). An **interjection** shows a sudden feeling (Oh! Wow! Ouch!). The words *a*, *an* and *the* are articles: they come before nouns."),
     ("fig", fig_pos, "The eight parts of speech with examples.", "Eight boxes. Each shows a part of speech with examples: noun (Mary, school), pronoun (he, they), verb (run, is), adjective (tall, red), adverb (quickly), preposition (on, under), conjunction (and, but) and interjection (Wow, Oh)."),
     ("key", "methode", "How to find the part of speech", "Ask what the word **does** in the sentence, not how it looks. A word can change its job: in *We play football*, play is a verb; in *We watched a play*, play is a noun. Questions that help: **What** or **who**? (noun) **Which kind**? (adjective) **How**? (adverb)."),
     ("key", "pieges", "Common mistakes", "- Using an adjective instead of an adverb: *She sings beautiful* is wrong; say *She sings beautifully*.\n- Thinking that every word ending in -ly is an adverb (friendly is an adjective).\n- Forgetting that a pronoun replaces a noun: *Ada said that Ada was tired* is better as *Ada said that she was tired*."),
     ("ex", "Example 1", "Name the part of speech of each underlined idea in: The tall boy quickly ate the ripe mango.", ["tall and ripe tell us **what kind**: they are adjectives.", "boy and mango name things: they are nouns.", "ate shows the action: it is a verb. quickly tells how he ate: it is an adverb."], "tall, ripe = adjectives; boy, mango = nouns; ate = verb; quickly = adverb."),
     ("ex", "Example 2", "Choose the correct word: She sings (beautiful / beautifully).", ["The word is describing the verb sings: it tells **how**.", "A word that describes a verb is an adverb, so we use beautifully."], "She sings beautifully.")],
    [M("application", "Which word is a verb in: The children play football on Saturday.?", "play", ["children", "football", "Saturday"], "play shows the action. The other words are nouns."),
     M("application", "Which word is a pronoun in: Ngu lost the book, and he cried.?", "he", ["Ngu", "book", "cried"], "he takes the place of the noun Ngu."),
     M("application", "Which word is an adjective in: She wore a red dress.?", "red", ["wore", "dress", "She"], "red describes the noun dress."),
     MA("approfondissement", "Match each word to its part of speech.", [("quickly", "adverb"), ("under", "preposition"), ("but", "conjunction"), ("Wow!", "interjection")], "quickly tells how; under shows position; but joins ideas; Wow! shows feeling."),
     TF("approfondissement", "The word happily is an adjective.", False, "Happily describes how something is done: it is an adverb. The adjective is happy."),
     P("Read the sentence: Mary quickly ate the sweet mango and she smiled happily.",
       [PM("What part of speech is 'sweet'?", "adjective", ["adverb", "noun", "verb"], "It describes the noun mango."),
        PM("What part of speech is 'and'?", "conjunction", ["preposition", "pronoun", "adverb"], "It joins two ideas."),
        PM("Which word is a pronoun?", "she", ["Mary", "mango", "smiled"], "she replaces Mary.", points=1),
        PM("Which two words are adverbs?", "quickly and happily", ["sweet and mango", "ate and smiled", "Mary and she"], "Both tell how an action was done.", points=2)])],
    [("A word that names a person, place or thing is a...", "noun", ["verb", "adverb", "pronoun"], "Nouns name."),
     ("In the sentence 'The cat sat on the mat', the word 'on' is a...", "preposition", ["conjunction", "noun", "adjective"], "It shows the position of the cat."),
     ("Which word is an adverb: 'The boy ran fast.'?", "fast", ["boy", "ran", "The"], "It tells how the boy ran."),
     ("'Oh! I forgot my book.' The word 'Oh' is an...", "interjection", ["adverb", "article", "adjective"], "It shows a sudden feeling."),
     ("Which sentence uses the right part of speech?", "He speaks clearly.", ["He speaks clear.", "He speak clearly.", "He speaks clearer."], "Clearly (adverb) describes the verb speaks, and speaks agrees with he.")],
    ["Articles are treated as a small group; check whether the syllabus calls them 'determiners' or 'articles'.", "Overlap with the existing Grammar lesson (pronouns, prepositions) is deliberate."],
    prereq=["fslc-english-grammar-main"])

# ---- adjectives and adverbs, comparison
fig_comp = shapes([RECT(40, 150, 90, 50, fill="lightblue"), RECT(155, 105, 90, 95, fill="lightyellow"), RECT(270, 60, 90, 140, fill="lightgreen"),
                   T(85, 180, "tall", 16, bold=True), T(200, 160, "taller", 16, bold=True), T(315, 135, "tallest", 16, bold=True),
                   T(85, 220, "Ada", 13), T(200, 220, "Bih", 13), T(315, 220, "Che", 13),
                   T(200, 30, "Ada is tall. Bih is taller. Che is the tallest.", 13)], 400, 235)
build(ch, "adjectives-adverbs", "Adjectives, adverbs and comparison", 30,
    ["Use adjectives and adverbs correctly.", "Form the comparative and the superlative.", "Use good/well and other easily confused pairs."],
    [("key", "definition", "Adjectives and adverbs", "An **adjective** describes a noun: *a fast bus*. An **adverb** describes a verb, an adjective or another adverb: *The bus goes fast. It is very fast.* Many adverbs of manner end in **-ly**: slow → slowly, careful → carefully, happy → happily. Some adverbs have no -ly: fast, hard, late, early."),
     ("fig", fig_comp, "Comparing three girls: tall, taller, tallest.", "Three bars of growing height. The first is labelled tall (Ada), the second taller (Bih) and the third tallest (Che)."),
     ("key", "retenir", "Comparing", "Short words: add **-er** and **-est** (tall, taller, tallest). Long words: use **more** and **most** (beautiful, more beautiful, most beautiful). We use **than** to compare two things: *Bih is taller than Ada.* Irregular forms: good, better, best; bad, worse, worst; little, less, least; far, farther, farthest."),
     ("key", "pieges", "Common mistakes", "- *more taller* or *most tallest*: use only one way of comparing.\n- *good* and *well*: *good* is an adjective (a good cook), *well* is an adverb (she cooks well).\n- Using *than* with the superlative: say *the tallest in the class*, not *the tallest than*.\n- The spelling change: big, bigger; happy, happier."),
     ("ex", "Example 1", "Complete: Ada is tall. Bih is ...... than Ada. Che is the ...... of the three.", ["Tall is a short word, so we add -er to compare two people: taller.", "For three or more, we add -est: the tallest."], "taller; tallest."),
     ("ex", "Example 2", "Choose good or well: Mama cooks ...... and her ndolé is very ......", ["Cooks is a verb, so we need an adverb: well.", "The word before ndolé is a description of it, so we need an adjective: good."], "Mama cooks well and her ndolé is very good.")],
    [M("application", "Choose the correct word: This road is ...... than that one.", "wider", ["more wider", "widest", "wide"], "We compare two roads with the -er form: wider."),
     M("application", "Choose the correct word: He ran ...... to catch the bus.", "quickly", ["quick", "quicker than", "more quick"], "Ran is a verb, so we need an adverb."),
     M("application", "What is the superlative of 'good'?", "best", ["goodest", "better", "most good"], "Good is irregular: good, better, best."),
     MA("approfondissement", "Match the adjective with its comparative.", [("small", "smaller"), ("bad", "worse"), ("beautiful", "more beautiful"), ("happy", "happier")], "Regular, irregular and long words follow different rules."),
     O("Write two sentences about two animals or two towns. Use a comparative (-er or more) in the first sentence and a superlative (-est or most) in the second.", "An elephant is bigger than a goat. The elephant is the biggest animal in the zoo.", "Full marks: two correct sentences, one comparative and one superlative, correct spelling and punctuation. Half marks if only one is correct.", points=3),
     P("Read: Bih is a good runner. She runs faster than Ada, but Che is the fastest in the school. Che trains hard every morning.",
       [PM("Which word is a comparative?", "faster", ["fastest", "good", "hard"], "Faster compares Bih with Ada."),
        PM("Which word is a superlative?", "fastest", ["faster", "runner", "trains"], "Fastest compares Che with everybody."),
        PM("What is 'hard' in the last sentence?", "adverb", ["adjective", "noun", "pronoun"], "Hard tells how Che trains: it is an adverb with no -ly."),
        PM("Which word is an adjective?", "good", ["runs", "every", "morning"], "Good describes the noun runner.")])],
    [("The comparative of 'tall' is...", "taller", ["tallest", "more tall", "tallier"], "Add -er."),
     ("Choose: She is the ...... girl in the class.", "tallest", ["taller", "more tall", "tall"], "In the class means three or more, so we use the superlative."),
     ("Choose: He speaks English ......", "well", ["good", "goodly", "better good"], "Well is the adverb."),
     ("The comparative of 'bad' is...", "worse", ["badder", "more bad", "worst"], "Bad is irregular: bad, worse, worst."),
     ("Which comparison sentence is correct?", "This mango is sweeter than that one.", ["This mango is more sweeter than that one.", "This mango is sweet than that one.", "This mango is sweetest than that one."], "Use the -er form with than.")],
    ["Spelling rule 'double the consonant' (big, bigger) appears here and again in the spelling lesson."],
    prereq=["fslc-english-parts-of-speech"])

# ---- vocabulary and word families
fig_fam = shapes([CIRCLE(200, 105, 38, fill="lightyellow"), T(200, 111, "help", 18, bold=True),
                  LINE(165, 85, 110, 55), LINE(235, 85, 290, 55), LINE(165, 125, 110, 155), LINE(235, 125, 290, 155),
                  T(75, 55, "helpful", 15, bold=True), T(325, 55, "helpless", 15, bold=True),
                  T(75, 165, "helper", 15, bold=True), T(325, 165, "helping", 15, bold=True),
                  T(200, 205, "one root word, many related words", 13)], 400, 225)
build(ch, "vocabulary-families", "Vocabulary: synonyms, antonyms, prefixes, suffixes and word families", 30,
    ["Find synonyms and antonyms of common words.", "Use prefixes and suffixes to build new words.", "Build a word family from a root word."],
    [("key", "definition", "Synonyms and antonyms", "**Synonyms** are words with nearly the same meaning: big and large, begin and start, glad and happy. **Antonyms** are words with opposite meanings: hot and cold, early and late, generous and mean. Synonyms are not always exactly the same: *tiny* is smaller than *small*. Always check the sentence."),
     ("key", "definition", "Prefixes and suffixes", "A **prefix** goes at the **beginning** of a word and changes its meaning: *un-* (unhappy), *dis-* (disagree), *re-* (rewrite), *in-* (incorrect), *mis-* (misspell). A **suffix** goes at the **end**: *-ful* (helpful), *-less* (helpless), *-ness* (kindness), *-er* (teacher), *-ly* (slowly)."),
     ("fig", fig_fam, "A word family built on the root word 'help'.", "A circle with the word help in the middle. Four lines go out to the words helpful, helpless, helper and helping."),
     ("key", "methode", "Building a word family", "Start with the **root** word. Add prefixes and suffixes and check each new word in a dictionary. Example: *care* → careful, careless, carefully, carelessly. Sometimes the spelling changes: happy → happiness (y becomes i); hope → hopeful (the e stays) but hope → hoping (the e goes)."),
     ("key", "pieges", "Common mistakes", "- Using *dis-* or *un-* with the wrong word: we say *unhappy* and *disagree*, not *dishappy* or *unagree*.\n- Forgetting that a suffix can change the **part of speech**: kind (adjective) → kindness (noun).\n- Choosing a synonym that does not fit the sentence."),
     ("ex", "Example 1", "Write an antonym of each word using a prefix: happy, agree, correct.", ["Happy takes un-: unhappy.", "Agree takes dis-: disagree.", "Correct takes in-: incorrect."], "unhappy, disagree, incorrect."),
     ("ex", "Example 2", "Make words from the root 'care': one with -ful, one with -less, one with -ly.", ["care + ful = careful (a person who takes care).", "care + less = careless (without care).", "careful + ly = carefully (an adverb)."], "careful, careless, carefully.")],
    [M("application", "Which word is a synonym of 'begin'?", "start", ["finish", "stop", "end"], "Begin and start have the same meaning."),
     M("application", "Which word is an antonym of 'early'?", "late", ["soon", "quick", "first"], "Early and late are opposites."),
     M("application", "Which word means 'to write again'?", "rewrite", ["unwrite", "miswrite", "writeful"], "The prefix re- means again."),
     MA("approfondissement", "Match each root word with its new word.", [("kind", "kindness"), ("help", "helpless"), ("teach", "teacher"), ("slow", "slowly")], "Each suffix is added to its root: -ness, -less, -er, -ly."),
     TF("approfondissement", "'Helpful' and 'helpless' have the same meaning.", False, "-ful means full of help; -less means without help. They are opposites."),
     P("Read the sentence: The careless driver was very unhappy after the accident, so he promised to be more careful.",
       [PM("What is the root word of 'careless' and 'careful'?", "care", ["less", "ful", "car"], "Both words are built on care."),
        PM("Which word has a prefix?", "unhappy", ["careless", "careful", "driver"], "un- is a prefix: un + happy."),
        PM("What is an antonym of 'careless' in the passage?", "careful", ["unhappy", "driver", "accident"], "Careless and careful are opposites."),
        PN("How many words in the sentence have the suffix -less or -ful?", 2, "careless and careful.", points=2)])],
    [("An antonym of 'generous' is...", "mean", ["kind", "rich", "happy"], "A generous person gives; a mean person does not."),
     ("The prefix in 'misspell' is...", "mis-", ["spell", "-ell", "m-"], "Mis- means wrongly."),
     ("The suffix in 'kindness' is...", "-ness", ["kind-", "-ess", "-n"], "-ness makes a noun."),
     ("A synonym of 'enormous' is...", "huge", ["tiny", "narrow", "quiet"], "Both mean very big."),
     ("Which word belongs to the family of 'friend'?", "friendship", ["fry", "fiend", "friction"], "Friendship = friend + ship.")],
    ["The lists of prefixes/suffixes are selective, not exhaustive; compare with the syllabus."],
    prereq=["fslc-english-parts-of-speech"])

# ---- spelling rules
fig_sp = grid([("box", "boxes"), ("baby", "babies"), ("leaf", "leaves"), ("child", "children"),
               ("run", "running"), ("make", "making"), ("their", "there"), ("write", "right")], 4, 92, 62)
build(ch, "spelling-rules", "Spelling rules and commonly confused words", 30,
    ["Use the rules for plurals and for adding -ing, -ed and -er.", "Spell common difficult words correctly.", "Tell apart words that sound the same (homophones)."],
    [("key", "retenir", "Plural rules", "Most nouns add **-s**: book, books. Nouns ending in **s, x, z, ch, sh** add **-es**: box, boxes; church, churches. A noun ending in **consonant + y** changes y to **-ies**: baby, babies (but boy, boys). Many nouns in **-f / -fe** change to **-ves**: leaf, leaves; knife, knives. Irregular plurals: child, children; man, men; woman, women; tooth, teeth; foot, feet; mouse, mice."),
     ("fig", fig_sp, "Spelling changes: plurals, adding -ing, and words that sound alike.", "Eight boxes with word pairs: box and boxes, baby and babies, leaf and leaves, child and children, run and running, make and making, their and there, write and right."),
     ("key", "retenir", "Adding endings", "- Short word with one vowel and one consonant: **double** the last letter: run → running, hop → hopped, big → bigger.\n- Word ending in silent **e**: drop the e before -ing: make → making, hope → hoping.\n- Consonant + y: change y to i before -ed, -er, -est: carry → carried, happy → happier. Keep y before -ing: carrying."),
     ("key", "pieges", "Words that sound the same", "- **their** (belongs to them), **there** (a place), **they're** (they are).\n- **to** (towards), **too** (also, very), **two** (the number 2).\n- **write** (with a pen), **right** (correct; the opposite of left).\n- **hear** (with your ears), **here** (in this place).\n- **buy** (pay for), **by** (near), **bye** (goodbye)."),
     ("key", "pieges", "Common mistakes", "- Writing *babys* or *boxs*: follow the plural rule.\n- Forgetting to double: *runing*, *stoped*.\n- *i before e*: believe, receive, field. We write ie, except after c: receive, ceiling. There are a few exceptions, such as weird."),
     ("ex", "Example 1", "Write the plural of: box, baby, leaf.", ["box ends in x, so we add -es: boxes.", "baby ends in consonant + y, so y becomes ies: babies.", "leaf ends in f, so f becomes ves: leaves."], "boxes, babies, leaves."),
     ("ex", "Example 2", "Add -ing to run, make and carry.", ["run: one vowel and one consonant, so double the n: running.", "make: drop the silent e: making.", "carry: keep the y before -ing: carrying."], "running, making, carrying.")],
    [M("application", "What is the plural of 'baby'?", "babies", ["babys", "babyes", "babyies"], "Consonant + y: change y to ies."),
     M("application", "Add -ing to 'swim'.", "swimming", ["swiming", "swimeing", "swimming'"], "Double the last consonant."),
     M("application", "Choose the correct word: They left ...... books at school.", "their", ["there", "they're", "thier"], "Their means belonging to them."),
     MA("approfondissement", "Match the singular with its plural.", [("child", "children"), ("tooth", "teeth"), ("knife", "knives"), ("church", "churches")], "These plurals are irregular or follow the -ves and -es rules."),
     TF("approfondissement", "The correct spelling is 'recieve'.", False, "After c we write ei: receive."),
     P("Correct the mistakes in this sentence: The babys of the two womans were playing in the churchs yard, and they were runing to there mothers.",
       [PM("Which is the correct plural of 'baby'?", "babies", ["babys", "babyes", "babyys"], "Consonant + y gives ies."),
        PM("Which is the correct plural of 'woman'?", "women", ["womans", "womens", "womanes"], "Woman is irregular: women."),
        PM("Which is the correct spelling?", "running", ["runing", "runeing", "runnning"], "Double the n before -ing."),
        PM("Which word is needed in 'they were running to ...... mothers'?", "their", ["there", "they're", "thare"], "The mothers belong to them.")])],
    [("The plural of 'box' is...", "boxes", ["boxs", "boxies", "boxen"], "Words ending in x add -es."),
     ("The plural of 'leaf' is...", "leaves", ["leafs", "leafes", "leavs"], "f changes to ves."),
     ("Choose: I ...... a loud noise.", "heard", ["herd", "hered", "heared"], "Heard (past of hear); herd is a group of animals."),
     ("The -ing form of 'make' is...", "making", ["makeing", "maaking", "makking"], "Drop the silent e."),
     ("Choose: She has ...... sisters.", "two", ["to", "too", "tow"], "Two is the number 2.")],
    ["Spelling follows British English (anglophone Cameroon). The 'i before e' rule has exceptions; the lesson lists only one."],
    prereq=["fslc-english-grammar-main"])

# ---- punctuation
fig_pun = shapes([T(200, 40, "“Where are Ada’s books?” asked Mama.", 20, bold=True),
                  T(200, 80, "capital letter   question mark   apostrophe", 13),
                  T(200, 120, "quotation marks round the exact words spoken", 13),
                  T(200, 165, "Mama bought rice, beans, yams, and oil.", 18, bold=True),
                  T(200, 200, "commas between the items of a list", 13)], 400, 225)
build(ch, "punctuation", "Punctuation and capital letters", 30,
    ["Use capital letters, full stops, question marks and exclamation marks.", "Use commas, apostrophes and quotation marks correctly.", "Punctuate a short passage."],
    [("key", "retenir", "Capital letters and end marks", "Use a **capital letter** for the first word of a sentence, for names of people and places (Ada, Buea, Mount Cameroon), for days and months (Monday, March) and for the word *I*. End a sentence with a **full stop** (.), a **question mark** (?) or an **exclamation mark** (!)."),
     ("fig", fig_pun, "Punctuation marks at work in two sentences.", "Two sentences. The first has quotation marks, a question mark and an apostrophe: Where are Ada's books, asked Mama. The second has commas between rice, beans, yams and oil."),
     ("key", "retenir", "Comma, apostrophe, quotation marks", "- **Comma**: between items in a list, after *yes* / *no*, and after a time word at the start (*In the morning, we sing.*).\n- **Apostrophe**: shows missing letters (don't = do not) and belonging (Ada's book; the boys' books).\n- **Quotation marks**: round the exact words someone says: “I am hungry,” said Ngu."),
     ("key", "pieges", "Common mistakes", "- Using an apostrophe for a plural: *the book's are on the table* is wrong (books).\n- *its* (belongs to it) and *it's* (it is) are different.\n- Putting a comma where a full stop is needed (a comma splice): *I was tired, I went to bed* is better as two sentences or joined with *so*."),
     ("ex", "Example 1", "Punctuate: where are adas books asked mama", ["Mama asks a question, so we need quotation marks and a question mark.", "Names and the first word need capital letters: Ada's has an apostrophe for belonging.", "The sentence becomes: “Where are Ada's books?” asked Mama."], "“Where are Ada's books?” asked Mama."),
     ("ex", "Example 2", "Punctuate: mama bought rice beans yams and oil", ["This is a list of four things, so we put commas between them.", "Mama bought rice, beans, yams and oil."], "Mama bought rice, beans, yams and oil.")],
    [M("application", "Which sentence is punctuated correctly?", "We bought pens, books and rulers.", ["We bought pens books and rulers", "we bought pens, books and rulers", "We bought pens, books, and rulers,"], "A capital letter at the start, commas in the list, one full stop at the end."),
     M("application", "Which is correct?", "Ada's bag is red.", ["Adas' bag is red.", "Adas bag is red.", "Ada,s bag is red."], "The apostrophe goes before the s to show that the bag belongs to one girl."),
     M("application", "What does the apostrophe show in 'don't'?", "Missing letters", ["A plural", "Belonging", "A question"], "Don't = do not: the o is missing."),
     TF("approfondissement", "'It's' means 'it is' (or 'it has').", True, "Its (no apostrophe) shows belonging."),
     O("Write the sentence with correct punctuation and capital letters: on monday ngu asked where is the key", "On Monday, Ngu asked, “Where is the key?”", "Full marks: capital letters for On, Monday, Ngu and Where; a comma after Monday (accept no comma) and after asked; quotation marks; a question mark inside the quotation marks.", points=3),
     P("Punctuate the passage in your head: mama said children come and eat the food is ready ngu shouted yes mama we are coming",
       [PM("What mark goes at the end of 'the food is ready'?", "full stop", ["question mark", "comma", "apostrophe"], "It is a statement.", points=1),
        PM("Which words must start with a capital letter?", "Mama, Ngu, Yes", ["food, ready", "children, come", "shouted, coming"], "Names and the first word of a sentence or speech.", points=2),
        PM("What goes round the words spoken by Mama?", "quotation marks", ["commas", "capital letters", "full stops"], "They show the exact words.", points=1)])],
    [("What mark ends a question?", "?", [".", "!", ","], "A question mark."),
     ("Which sentence needs a capital letter?", "we went to buea.", ["Mount Cameroon is high.", "Ada is my friend.", "I am ten."], "The sentence starts with we, and Buea is a place name."),
     ("'The girl's books' means books belonging to...", "one girl", ["two girls", "no girl", "the girls"], "'s with one owner."),
     ("Where does a comma go in this list: pens pencils and rulers?", "after pens", ["after and", "after rulers", "nowhere"], "Pens, pencils and rulers."),
     ("'Its' without an apostrophe shows...", "belonging", ["it is", "a question", "a list"], "The dog wagged its tail.")],
    ["The Oxford comma (comma before 'and') is shown both ways; the syllabus convention is to be checked. Quotation marks: single or double, to be checked."],
    prereq=["fslc-english-grammar-main"])

# =========================================================== chapter 6: sentence skills
ch = p.chapter("sentence-skills", "Sentences: types, voice, reported speech and conditionals", REF)
fig_types = grid([("statement", "I like fufu."), ("question", "Do you like it?"), ("command", "Eat your food."), ("exclamation", "How tasty it is!")], 2, 150, 62)
build(ch, "sentence-types", "Types of sentences: statements, questions, commands, exclamations; simple and compound", 30,
    ["Name the four kinds of sentence by their purpose.", "Tell a simple sentence from a compound and a complex sentence.", "Join short sentences with and, but, so, because."],
    [("key", "definition", "Four kinds of sentence", "A **statement** tells us something and ends with a full stop: *I like fufu.* A **question** asks something and ends with a question mark: *Do you like it?* A **command** tells someone to do something: *Eat your food.* An **exclamation** shows strong feeling and ends with an exclamation mark: *How tasty it is!*"),
     ("fig", fig_types, "Four kinds of sentence.", "Four boxes: statement (I like fufu), question (Do you like it), command (Eat your food) and exclamation (How tasty it is)."),
     ("key", "definition", "Simple, compound and complex", "A **simple** sentence has one main idea: *It rained.* A **compound** sentence joins two main ideas with **and, but, or, so**: *It rained, so we stayed inside.* A **complex** sentence has a main idea and an extra idea that cannot stand alone, joined with words like **because, when, if, although**: *We stayed inside because it rained.*"),
     ("key", "pieges", "Common mistakes", "- Writing two sentences with only a comma between them (*It rained, we stayed in*): use a full stop, or add a joining word.\n- Starting a sentence with *Because...* and not finishing it (*Because it rained.*). It needs a main idea: *Because it rained, we stayed in.*\n- Using both *although* and *but* in one sentence."),
     ("ex", "Example 1", "Say which kind of sentence each is: (a) Close the door. (b) What a beautiful day!", ["(a) It tells someone to do something and has no exclamation: it is a command.", "(b) It shows strong feeling and ends with an exclamation mark: it is an exclamation."], "(a) command; (b) exclamation."),
     ("ex", "Example 2", "Join the two sentences with a joining word: It was raining. We stayed inside.", ["The second idea is a result of the first, so we can use so: It was raining, so we stayed inside.", "Or we can use because to make a complex sentence: We stayed inside because it was raining."], "It was raining, so we stayed inside.")],
    [M("application", "What kind of sentence is: Where do you live?", "question", ["statement", "command", "exclamation"], "It asks something and ends with ?"),
     M("application", "Which sentence is a command?", "Please sit down.", ["He sat down.", "Why did he sit?", "How tired he is!"], "A command tells someone to do something."),
     M("application", "Which word joins the ideas in: I was tired, but I finished my work.?", "but", ["I", "was", "finished"], "But joins two main ideas that are different."),
     MA("approfondissement", "Match each sentence to its kind.", [("Is it Monday today?", "question"), ("Wash your hands.", "command"), ("Today is Monday.", "statement"), ("What a surprise!", "exclamation")], "Look at the purpose and the end mark."),
     TF("approfondissement", "'We stayed inside because it rained' is a compound sentence.", False, "Because makes it a complex sentence. A compound sentence uses and, but, or, so."),
     P("Read: Ada was hungry, so she bought a puff-puff. She ate it quickly because she was late for school. What a delicious snack!",
       [PM("What kind of sentence is the last sentence?", "exclamation", ["question", "command", "statement"], "It shows strong feeling and ends with !"),
        PM("Which word makes the first sentence compound?", "so", ["Ada", "hungry", "bought"], "So joins two main ideas."),
        PM("Which word makes the second sentence complex?", "because", ["quickly", "ate", "school"], "Because introduces the reason (an idea that cannot stand alone)."),
        PM("Which sentence would be a command?", "Buy a puff-puff.", ["She bought a puff-puff.", "Did she buy a puff-puff?", "What a puff-puff!"], "A command tells someone to do something.", points=2)])],
    [("Which ends with an exclamation mark?", "How cold it is!", ["Is it cold?", "It is cold.", "Put on a coat."], "An exclamation shows strong feeling."),
     ("'Open your books.' is a...", "command", ["question", "statement", "exclamation"], "It tells people what to do."),
     ("Which word makes a compound sentence?", "and", ["because", "if", "when"], "And joins two main ideas of equal importance."),
     ("Which is a question?", "Are you ready?", ["You are ready.", "Be ready.", "How ready you are!"], "It asks and ends with ?"),
     ("'Although it was late, we kept working.' is a...", "complex sentence", ["simple sentence", "compound sentence", "command"], "Although begins a side idea.")],
    ["Simple/compound/complex are introduced at an elementary level; check how far the Class 6 syllabus goes."],
    prereq=["fslc-english-parts-of-speech"])

# ---- active and passive
fig_ap = shapes([RECT(20, 25, 360, 80, fill="lightblue", radius=6), T(200, 48, "Active", 14, bold=True),
                 T(200, 78, "Ada ate the mango.", 18),
                 LINE(200, 108, 200, 130, arrow="end"),
                 RECT(20, 135, 360, 80, fill="lightyellow", radius=6), T(200, 158, "Passive", 14, bold=True),
                 T(200, 188, "The mango was eaten by Ada.", 18)], 400, 230)
build(ch, "active-passive", "Active and passive voice", 30,
    ["Tell an active sentence from a passive sentence.", "Change a simple active sentence into the passive and back.", "Use the passive correctly in the present, past and future."],
    [("key", "definition", "Active and passive", "In an **active** sentence the subject does the action: *Ada ate the mango.* In a **passive** sentence the action is done **to** the subject: *The mango was eaten by Ada.* We use the passive when the doer is not important or not known: *The window was broken.*"),
     ("fig", fig_ap, "The same idea in the active and in the passive.", "Two boxes joined by an arrow. The first says Active: Ada ate the mango. The second says Passive: The mango was eaten by Ada."),
     ("key", "methode", "How to make the passive", "1. Take the **object** of the active sentence: it becomes the new subject.\n2. Use the verb **be** in the same tense + the **past participle**: is/are eaten, was/were eaten, will be eaten.\n3. Add **by** + the doer (if needed).\nPresent: *Mama cooks rice.* → *Rice is cooked by Mama.* Past: *Mama cooked rice.* → *Rice was cooked by Mama.* Future: *Mama will cook rice.* → *Rice will be cooked by Mama.*"),
     ("key", "pieges", "Common mistakes", "- Forgetting the verb **be**: *The mango eaten by Ada* is wrong.\n- Using the wrong past participle: *was ate* (wrong), *was eaten* (right).\n- Not changing the be-verb to match the new subject: *The books was sold* (wrong), *The books were sold* (right).\n- Only verbs that take an object can become passive: we cannot say *The boy was slept*."),
     ("ex", "Example 1", "Change to the passive: The farmer planted maize.", ["The object (maize) becomes the subject.", "The verb is in the past: was + planted.", "Add by + the doer: by the farmer."], "Maize was planted by the farmer."),
     ("ex", "Example 2", "Change to the active: The window was broken by the boy.", ["The doer is the boy: he becomes the subject.", "The verb was broken becomes the simple past: broke.", "The window is the object."], "The boy broke the window.")],
    [M("application", "Which sentence is passive?", "The letter was written by Ngu.", ["Ngu wrote the letter.", "Ngu is writing a letter.", "Ngu will write a letter."], "The letter receives the action: was written."),
     M("application", "Change to the passive: Mama cooks rice.", "Rice is cooked by Mama.", ["Rice was cooked by Mama.", "Rice cooked by Mama.", "Mama is cooked by rice."], "Present simple: is + past participle."),
     M("application", "Change to the active: The ball was kicked by the boy.", "The boy kicked the ball.", ["The boy kicks the ball.", "The ball kicked the boy.", "The boy was kicking the ball."], "Same tense (past) and the doer first."),
     O("Change into the passive: The teacher will mark the books tomorrow.", "The books will be marked by the teacher tomorrow.", "Full marks: the books as subject, will be marked, by the teacher (accept without 'by the teacher'). Half marks for correct tense but wrong word order.", points=3),
     TF("approfondissement", "'The books was sold' is correct.", False, "Books is plural, so we need were: The books were sold."),
     P("Change these sentences. (a) The children sang the song. (b) A thief stole the bag. (c) The shop sells bread.",
       [PM("(a) in the passive:", "The song was sung by the children.", ["The song sang by the children.", "The song was sang by the children.", "The children were sung the song."], "Past: was + past participle sung."),
        PM("(b) in the passive:", "The bag was stolen by a thief.", ["The bag was stole by a thief.", "The bag stolen by a thief.", "A thief was stolen the bag."], "Past participle of steal is stolen."),
        PM("(c) in the passive:", "Bread is sold by the shop.", ["Bread was sold by the shop.", "Bread sells by the shop.", "The shop is sold bread."], "Present simple: is + sold.", points=2)])],
    [("The passive of 'Ada broke the cup' is...", "The cup was broken by Ada.", ["The cup is broken by Ada.", "The cup was break by Ada.", "Ada was broken by the cup."], "Past tense: was + broken."),
     ("Which verb form is used in the passive?", "be + past participle", ["have + base verb", "do + -ing", "can + base verb"], "For example: is cooked, was written."),
     ("Which sentence is active?", "The dog chased the cat.", ["The cat was chased by the dog.", "The cat is chased by the dog.", "The cat will be chased."], "The subject, the dog, does the action."),
     ("'Rice is grown in Cameroon.' The doer is...", "not mentioned", ["rice", "Cameroon", "grown"], "The passive can leave out the doer."),
     ("The passive of 'They will build a bridge' is...", "A bridge will be built.", ["A bridge will build.", "A bridge was built.", "A bridge is building."], "Future passive: will be + past participle.")],
    ["Only the simple present, simple past and simple future are used; check whether the syllabus includes other tenses (present continuous, perfect)."],
    prereq=["fslc-english-tenses-main"])

# ---- direct and indirect speech
fig_ds = grid([("now", "then"), ("today", "that day"), ("tomorrow", "the next day"), ("yesterday", "the day before"),
               ("here", "there"), ("this", "that"), ("I / my", "he, she / his, her"), ("will / can", "would / could")], 4, 92, 62, size=12)
build(ch, "direct-indirect", "Direct and indirect (reported) speech", 35,
    ["Tell direct speech from indirect speech.", "Change statements, questions and commands into indirect speech.", "Change tenses, pronouns and time words correctly."],
    [("key", "definition", "Direct and indirect speech", "**Direct speech** gives the exact words of a speaker, with quotation marks: *Mama said, “I am cooking rice.”* **Indirect (reported) speech** tells what was said, without quotation marks: *Mama said that she was cooking rice.* In reported speech the tense usually moves one step back: am → was, will → would, can → could, cooks → cooked."),
     ("fig", fig_ds, "Words that change in reported speech.", "Eight boxes of word pairs: now becomes then, today becomes that day, tomorrow becomes the next day, yesterday becomes the day before, here becomes there, this becomes that, I and my become he or she, will and can become would and could."),
     ("key", "methode", "Questions and commands", "- **Statement**: use *that* (or nothing): She said, “I am tired.” → She said (that) she was tired.\n- **Question**: use *asked* + **if / whether** (yes-no) or the question word (wh-). Normal word order, no question mark: He asked, “Where do you live?” → He asked where I lived.\n- **Command**: use *told / asked* + person + **to**: The teacher said, “Open your books.” → The teacher told us to open our books."),
     ("key", "pieges", "Common mistakes", "- Keeping the question word order: *He asked where did I live* is wrong; say *where I lived*.\n- Forgetting to change the pronoun (I → he or she) and the time word (tomorrow → the next day).\n- Keeping the quotation marks and the question mark in indirect speech."),
     ("ex", "Example 1", "Change to indirect speech: Ngu said, “I will come tomorrow.”", ["Say that. I becomes he, will becomes would.", "Tomorrow becomes the next day.", "Ngu said that he would come the next day."], "Ngu said that he would come the next day."),
     ("ex", "Example 2", "Change to indirect speech: Bih asked, “Where is my pen?”", ["Use asked and the question word where, with statement word order.", "My becomes her, is becomes was.", "Bih asked where her pen was."], "Bih asked where her pen was.")],
    [M("application", "Change to indirect speech: Mama said, “I am cooking rice.”", "Mama said that she was cooking rice.", ["Mama said that I am cooking rice.", "Mama said that she is cooked rice.", "Mama said, that she was cooking rice?"], "I becomes she; am cooking becomes was cooking."),
     M("application", "Which is the reported form of 'tomorrow'?", "the next day", ["yesterday", "that night", "the day before"], "Tomorrow becomes the next day."),
     M("application", "Change: The teacher said to us, “Open your books.”", "The teacher told us to open our books.", ["The teacher said to open your books.", "The teacher told us that open our books.", "The teacher asked us that we open books."], "A command uses told + person + to + verb."),
     O("Change to indirect speech: Ada asked, “Do you like mangoes?”", "Ada asked if (whether) I liked mangoes.", "Full marks: asked + if/whether, I liked (past tense, statement order), no question mark. Accept 'asked me if/whether I liked mangoes'.", points=3),
     TF("approfondissement", "In indirect speech we keep the quotation marks.", False, "Quotation marks are only for the exact words (direct speech)."),
     P("Change to indirect speech. (a) Che said, “I can swim.” (b) The nurse said to Mary, “Take this medicine today.” (c) Eko asked, “Why are you late?”",
       [PM("(a)", "Che said that he could swim.", ["Che said that he can swim.", "Che said he swimming.", "Che said, “he could swim.”"], "can becomes could; I becomes he."),
        PM("(b)", "The nurse told Mary to take that medicine that day.", ["The nurse told Mary take this medicine today.", "The nurse said Mary to take this medicine today.", "The nurse told Mary that take that medicine."], "A command: told + person + to; this → that, today → that day."),
        PM("(c)", "Eko asked why I was late.", ["Eko asked why was I late.", "Eko asked why you are late?", "Eko asked, why I was late?"], "Question word + normal word order, no question mark.", points=2)])],
    [("Reported speech: tense usually goes...", "one step back", ["one step forward", "to the future", "does not change"], "am → was, will → would."),
     ("He said, “I am happy.” → He said that he ......", "was happy", ["is happy", "am happy", "will be happy"], "Am becomes was and I becomes he."),
     ("Which sentence is in indirect speech?", "She said that she was ready.", ["She said, “I am ready.”", "“I am ready,” she said.", "She said: I am ready."], "No quotation marks, tense changed."),
     ("“Come here,” said the teacher. → The teacher told us ......", "to go there", ["come here", "that we come here", "going there"], "Command: to + verb; here becomes there."),
     ("The question mark disappears in...", "indirect questions", ["direct speech", "all sentences", "commands only"], "He asked where I lived. No question mark.")],
    ["Back-shifting rules are given in simplified form; special cases (reporting a general truth, past perfect) are not covered."],
    prereq=["fslc-english-active-passive", "fslc-english-punctuation"])

# ---- conditionals
fig_cond = shapes([RECT(20, 20, 360, 55, fill="lightblue", radius=6), T(200, 42, "Real: If + present, will + verb", 14, bold=True), T(200, 64, "If it rains, we will stay at home.", 13),
                   RECT(20, 85, 360, 55, fill="lightyellow", radius=6), T(200, 107, "Unreal: If + past, would + verb", 14, bold=True), T(200, 129, "If I had a bike, I would ride to school.", 13),
                   RECT(20, 150, 360, 55, fill="lightgreen", radius=6), T(200, 172, "Always true: If + present, present", 14, bold=True), T(200, 194, "If you heat ice, it melts.", 13)], 400, 220)
build(ch, "conditionals", "Conditional sentences", 30,
    ["Form real conditionals (if + present, will) and unreal conditionals (if + past, would).", "Use the right verb form after if.", "Complete and write conditional sentences."],
    [("key", "definition", "What is a conditional?", "A **conditional** sentence has an **if**-part (the condition) and a main part (the result). *If it rains, we will stay at home.* The if-part can come first (with a comma) or second (no comma): *We will stay at home if it rains.*"),
     ("fig", fig_cond, "Three kinds of conditional sentence.", "Three boxes. The first shows a real condition: if it rains, we will stay at home. The second shows an unreal one: if I had a bike, I would ride to school. The third shows a fact: if you heat ice, it melts."),
     ("key", "methode", "Which form?", "- **Real or possible** (it may happen): **if + present simple, will + verb**. *If you study, you will pass.*\n- **Unreal or unlikely** (it is not true now): **if + past simple, would + verb**. *If I were a bird, I would fly.* We often say *were* for all persons after if (*if I were*, *if he were*).\n- **Always true** (a fact): **if + present, present**. *If you mix red and blue, you get purple.*"),
     ("key", "pieges", "Common mistakes", "- Using will after if: *If it will rain* is wrong; say *If it rains*.\n- Mixing the forms: *If I had money, I will buy a bike* is wrong; say *I would buy*.\n- Forgetting the comma when the if-part comes first.\n- Using *would* in the if-part: *If I would know* is wrong; say *If I knew*."),
     ("ex", "Example 1", "Complete: If it rains tomorrow, we ...... (stay) at home.", ["Rain tomorrow is possible, so this is a real condition.", "The if-part is in the present (rains), so the result takes will + verb."], "we will stay at home."),
     ("ex", "Example 2", "Complete: If I ...... (be) a bird, I would fly over Mount Cameroon.", ["A person cannot be a bird, so this is unreal.", "The if-part is in the past, and we use were: if I were a bird."], "If I were a bird...")],
    [M("application", "Choose: If you ......, you will pass the exam.", "study", ["will study", "studied", "would study"], "Real condition: if + present."),
     M("application", "Choose: If I had a bicycle, I ...... to school on it.", "would ride", ["will ride", "rode", "would rode"], "Unreal condition: if + past, would + verb."),
     M("application", "Choose: If you ...... water to 100 degrees Celsius, it boils.", "heat", ["will heat", "heated", "would heat"], "Always true: if + present, present."),
     MA("approfondissement", "Match the beginning with the best ending.", [("If it rains,", "we will stay at home."), ("If I were rich,", "I would build a school."), ("If you heat ice,", "it melts."), ("If you hurry,", "you will catch the bus.")], "Check the verb forms on both sides."),
     O("Write two conditional sentences: one about something that may happen tomorrow, and one about something that is not true now.", "If it is sunny tomorrow, we will play football. If I were the headmaster, I would build a library.", "Full marks: first sentence if + present, will; second sentence if + past (were), would. Half marks for one correct sentence.", points=3),
     P("Put the verb in brackets in the correct form. (a) If you (practise), you will improve. (b) If Ngu (have) a phone, he would call you. (c) If we (mix) yellow and blue, we get green.",
       [PM("(a)", "practise", ["will practise", "practised", "would practise"], "Real: if + present simple."),
        PM("(b)", "had", ["has", "will have", "would have"], "Unreal: if + past simple."),
        PM("(c)", "mix", ["will mix", "mixed", "would mix"], "Fact: if + present simple.", points=2)])],
    [("If it ...... tomorrow, we will go to the beach.", "does not rain", ["will not rain", "would not rain", "did not rain"], "Real condition uses the present after if."),
     ("If I ...... you, I would ask the teacher.", "were", ["am", "will be", "would be"], "Advice: if I were you."),
     ("Which conditional sentence is correct?", "If he studies, he will pass.", ["If he will study, he will pass.", "If he studied, he will pass.", "If he would study, he will pass."], "No will after if."),
     ("'If you heat ice, it melts' is...", "always true", ["unreal", "in the past", "a command"], "It is a fact."),
     ("We will go if the weather ...... good.", "is", ["will be", "would be", "was"], "Present simple after if.")],
    ["Third conditional (if + past perfect, would have) is NOT covered; zero conditional is included although the syllabus may not name it."],
    prereq=["fslc-english-tenses-main"])

# =========================================================== chapter 7: reading skills
ch = p.chapter("reading-skills", "Reading skills: strategies for comprehension", REF)
PASSAGE1 = ("Market day in Bamenda is the busiest day of the week. Before the sun is up, Mama Joy loads her baskets of tomatoes, onions and green peppers onto a bus. "
            "Her daughter Neba helps her to carry them. At the market the sellers shout the prices, and buyers move slowly between the stalls. "
            "By noon, Mama Joy has sold almost everything. She is tired but happy. With the money, she buys school books for Neba and a bag of rice for the house.")
assert len(PASSAGE1) < 650, len(PASSAGE1)
fig_qw = grid([("Who?", "a person"), ("What?", "a thing, an event"), ("Where?", "a place"), ("When?", "a time"), ("Why?", "a reason"), ("How?", "the way")], 3, 115, 62)
build(ch, "comprehension-strategies", "Reading comprehension: strategies and question types", 35,
    ["Read a passage for the main idea and for details.", "Answer who, what, where, when, why and how questions in full sentences.", "Work out the meaning of a word from its context and make simple inferences."],
    [("key", "methode", "Three steps for comprehension", "1. **Read** the passage once quickly to get the main idea (**skimming**).\n2. **Read the questions**, then go back to the passage and look for the answer (**scanning**).\n3. **Answer** in your own words, in a full sentence, and check the spelling and punctuation. Do not copy long pieces of the passage."),
     ("fig", fig_qw, "The question words tell you what kind of answer to look for.", "Six boxes: Who asks for a person, What for a thing or event, Where for a place, When for a time, Why for a reason and How for the way."),
     ("text", "Read this passage.\n\n" + PASSAGE1),
     ("key", "retenir", "Kinds of questions", "- **Detail** question: the answer is written in the text (*Who helps Mama Joy?*).\n- **Main idea** question: what is the whole passage about? (*A busy market day.*)\n- **Inference**: the text does not say it directly, but you can work it out (*How does Mama Joy feel at the end? She is happy because she sold her goods.*).\n- **Vocabulary in context**: look at the words around the word you do not know."),
     ("key", "pieges", "Common mistakes", "- Answering from your own ideas instead of from the passage.\n- Copying a whole sentence that does not answer the question.\n- Writing a **phrase** when the question asks for a full sentence (follow the instruction).\n- Missing the question word: a *why* question needs a reason (**because**...)."),
     ("ex", "Example 1", "Using the passage on Bamenda market: Why does Mama Joy leave before the sun is up?", ["Look for the sentence about the early start: she loads her baskets and takes the bus before sunrise.", "The passage says market day is the busiest day of the week, so she needs to reach the market early to sell her goods.", "Answer: She leaves early because market day is very busy and she wants to sell her goods."], "She leaves early because market day is very busy and she wants to sell her goods."),
     ("ex", "Example 2", "What does 'stalls' mean in 'buyers move slowly between the stalls'?", ["Look at the words around it: buyers walk between them at the market and sellers stand there.", "A stall is a small table or place where goods are sold."], "A stall is a small place or table in the market where goods are sold.")],
    [M("application", "What is the best title for the passage about Bamenda market?", "A busy market day", ["A new school bag", "A bus journey", "Neba's birthday"], "The whole passage is about market day."),
     M("application", "Who helps Mama Joy to carry the baskets?", "Her daughter Neba", ["The bus driver", "A buyer", "Her husband"], "The passage says her daughter Neba helps her."),
     M("application", "What does Mama Joy buy with the money?", "School books and rice", ["Tomatoes and onions", "A new bus", "Green peppers"], "She buys school books for Neba and a bag of rice."),
     M("approfondissement", "How does Mama Joy feel at the end of the day?", "Tired but happy", ["Angry", "Afraid", "Bored"], "The passage says she is tired but happy (and the reason is that she sold almost everything)."),
     TF("approfondissement", "From the passage we know that Mama Joy sold nothing at the market.", False, "By noon she has sold almost everything."),
     P("Read: Ebai's goat was missing. He looked behind the kitchen and under the mango tree, but he did not find it. At last he heard a soft bleat from the old store. The goat had pushed the door open and was eating the maize. Ebai laughed, then he tied the door carefully so it would not happen again.",
       [PM("What is the main idea?", "Ebai finds his missing goat", ["Ebai grows maize", "A goat is sold", "A kitchen is built"], "The passage tells how Ebai looked for and found the goat."),
        PM("Where was the goat?", "In the old store", ["Behind the kitchen", "Under the mango tree", "In the market"], "He heard a bleat from the old store."),
        PM("What does 'bleat' mean?", "the sound a goat makes", ["a kind of food", "a type of door", "a small hut"], "It is a goat's cry, as the context shows."),
        PM("Why did Ebai tie the door?", "so the goat could not get in again", ["because he was angry", "because he sold the maize", "because the door was old and he liked it"], "He tied it so it would not happen again.", points=2)])],
    [("Skimming means...", "reading quickly for the main idea", ["reading every word slowly", "copying the text", "reading only the title"], "Skimming gives the general idea."),
     ("A 'why' question needs...", "a reason", ["a place", "a time", "a name"], "Use because in your answer."),
     ("To find the meaning of a new word we can...", "look at the words around it", ["skip the passage", "ask a friend only", "guess without reading"], "Context gives clues."),
     ("An inference is...", "an idea you work out from clues", ["a word in the title", "a spelling rule", "the last sentence"], "The text does not say it directly."),
     ("Your answer to a comprehension question should be...", "in your own words, in a full sentence", ["a copy of the whole passage", "only one letter", "your opinion without the text"], "Short, clear and based on the passage.")],
    ["The two passages are original texts written for this lesson. Passage readability for Class 6 should be checked by a teacher."],
    prereq=["fslc-english-reading-comprehension"])

# =========================================================== chapter 8: writing and oral English
ch = p.chapter("writing-oral", "Writing, poetry and oral English", REF)
fig_letter = shapes([RECT(60, 8, 280, 246, fill="white"),
                     T(330, 30, "Your address", 11, anchor="end"), T(330, 46, "Date", 11, anchor="end"),
                     T(72, 70, "The Headmaster", 11, anchor="start"), T(72, 86, "Receiver's address", 11, anchor="start"),
                     T(72, 112, "Dear Sir,", 11, anchor="start", bold=True),
                     T(200, 136, "SUBJECT: REQUEST FOR PERMISSION", 11, bold=True),
                     T(200, 166, "Body: reason, details, request, thanks", 11),
                     T(200, 186, "(short, clear paragraphs)", 11),
                     T(72, 214, "Yours faithfully,", 11, anchor="start", bold=True), T(72, 234, "Your name (signature)", 11, anchor="start")], 400, 262)
build(ch, "letter-writing", "Letter writing: formal and informal letters", 40,
    ["Write an informal letter to a friend or relative.", "Write a formal letter (request, apology, application) with the right layout.", "Use the right opening, closing and tone."],
    [("key", "definition", "Two kinds of letter", "An **informal (friendly) letter** is to a friend or a relative: it can be warm and chatty. A **formal letter** is to a person in authority (the headmaster, a company, an official): it is polite, short and to the point. Use **full forms** (do not, not don't) and no slang in a formal letter."),
     ("fig", fig_letter, "The layout of a formal letter.", "A page showing a formal letter: the sender's address and the date at the top right, the receiver's name and address at the left, Dear Sir, a subject line, the body, Yours faithfully and the sender's name."),
     ("key", "methode", "Layout of a formal letter", "1. Your address (top right), then the date.\n2. The name and address of the person you write to (left).\n3. **Dear Sir / Madam,** (or **Dear Mr Ndi,**).\n4. A **subject line** in capital letters.\n5. The body: why you write, the details, what you ask for, thanks.\n6. **Yours faithfully,** (if you wrote Dear Sir/Madam) or **Yours sincerely,** (if you wrote the person's name), then your name."),
     ("key", "retenir", "Informal letter", "Address and date at the top right, then **Dear Ada,** and a friendly first line (*I hope you are well.*). Write about the news, ask questions, then close with *Your friend,* or *Yours lovingly,* and your first name. There is no subject line and no receiver's address."),
     ("key", "pieges", "Common mistakes", "- Mixing the endings: *Dear Sir ... Yours sincerely* (should be faithfully).\n- Using slang, short forms or a long story in a formal letter.\n- Forgetting the date, the subject line or your name.\n- Writing the whole letter in one paragraph."),
     ("ex", "Example 1", "Which closing do you use after Dear Sir and after Dear Mr Ndi?", ["Dear Sir (the name is not known): Yours faithfully.", "Dear Mr Ndi (the name is known): Yours sincerely."], "Dear Sir ... Yours faithfully; Dear Mr Ndi ... Yours sincerely."),
     ("ex", "Example 2", "Write the first two sentences of a formal letter to your headmaster asking permission to be absent for one day.", ["Start with the reason and the request: I am writing to ask for your permission to be absent from school on Friday, 10 May.", "Give the reason politely: I have to attend my cousin's wedding in Bafoussam. I thank you in advance."], "I am writing to ask for your permission to be absent from school on Friday. I have to attend a family wedding in Bafoussam.")],
    [M("application", "A letter begins 'Dear Madam,'. It ends with...", "Yours faithfully,", ["Yours sincerely,", "Your friend,", "Bye bye,"], "Name not known: faithfully."),
     M("application", "Where does the date go in a letter?", "At the top right", ["At the bottom left", "After the signature", "In the middle"], "The sender's address and the date are at the top right."),
     M("application", "Which opening is suitable for a letter to a friend?", "Dear Neba, I hope you are well.", ["Dear Sir, I am writing to apply for the post of...", "To whom it may concern, I wish to complain.", "Madam, kindly be informed that..."], "Informal letters are friendly."),
     TF("approfondissement", "A formal letter should have a subject line.", True, "It tells the reader at once what the letter is about."),
     O("Write a short informal letter (about 5 to 6 sentences) to a friend in another town. Tell your friend about your school and ask two questions.", "12 Mile Road, Buea\n3 March 2025\nDear Neba,\nI hope you are well. I am writing to tell you about my new school. We have a big library and I like it very much. My favourite subject is science. What is your school like? Do you still play football?\nYour friend,\nBih", "Full marks: correct layout (address, date, Dear..., closing), friendly tone, at least two questions, correct spelling and punctuation, paragraphs.", points=4),
     O("Write a formal letter to the headmaster asking for permission to be absent from school for one day because of a family event. Use the correct layout and a polite tone.", "(Address and date)\nThe Headmaster\nGovernment Primary School\nDear Sir,\nREQUEST FOR PERMISSION TO BE ABSENT\nI am writing to ask for your permission to be absent from school on Friday, 10 May, because I have to attend a family wedding in Bafoussam. I will copy the lessons I miss. I thank you in advance.\nYours faithfully,\nEmma Fon", "Marks (out of 6): layout (2), clear request and reason (2), polite formal language (1), spelling and punctuation (1).", tier="examen", points=6)],
    [("A formal letter to someone whose name you do not know starts with...", "Dear Sir/Madam,", ["Hi,", "Dear friend,", "Hello there,"], "Dear Sir/Madam is the polite form."),
     ("Which ending goes with 'Dear Mr Ndi'?", "Yours sincerely,", ["Yours faithfully,", "See you,", "Love,"], "When the person's name is used we write sincerely."),
     ("What should the subject line of a formal letter do?", "tell what the letter is about", ["greet the reader", "give your address", "thank the teacher"], "It sums up the purpose."),
     ("Which sentence is too informal for a formal letter?", "I can't wait for ya to answer!", ["I thank you in advance.", "I am writing to request a copy.", "Please find my report attached."], "'Ya' and 'can't wait' are not formal."),
     ("A friendly letter closes with...", "Your friend, Ada", ["Yours faithfully", "Respectfully submitted", "Dear Sir"], "Informal closing.")],
    ["Formal letter layout (position of the date, subject line, 'Yours faithfully/sincerely') follows common Cameroonian anglophone practice; check against the FSLC marking scheme. Sample letters use fictional names."],
    prereq=["fslc-english-composition-main"])

fig_mtn = shapes([POLY([30, 200, 120, 120, 200, 45, 285, 120, 370, 200], fill="lightyellow", closed=False),
                  T(45, 222, "Beginning", 13, bold=True), T(115, 105, "Problem", 13, bold=True), T(200, 30, "Climax", 13, bold=True),
                  T(305, 105, "Solution", 13, bold=True), T(355, 222, "Ending", 13, bold=True)], 400, 240)
build(ch, "narrative-descriptive", "Writing a story and describing a person, place or event", 40,
    ["Plan a story with a beginning, a problem, a climax and an ending.", "Use the past tense, paragraphs and linking words in a story.", "Use the five senses and good adjectives in a description."],
    [("key", "methode", "Planning a story", "Before you write, make a short plan: **who** (characters), **where and when** (setting), **what happens** (the problem), **how it ends**. Use one paragraph for each part. Write in the **past tense** and use linking words: first, then, suddenly, after that, at last."),
     ("fig", fig_mtn, "The shape of a story.", "A line goes up like a mountain. The points are marked Beginning, Problem, Climax at the top, Solution and Ending."),
     ("key", "methode", "Writing a description", "To describe a place, a person or an event, use your **five senses**: what you see, hear, smell, taste and feel. Use exact adjectives (*a crowded, noisy market*) and comparisons (*as busy as ants*). Describe in order (from left to right, near to far) so that the reader can picture the scene."),
     ("key", "pieges", "Common mistakes", "- Starting to write without a plan, so that the story has no clear ending.\n- Changing from past to present tense in the middle of the story.\n- Using the same word again and again (*nice*, *good*): choose a more exact word.\n- Writing a long list of events with no paragraphs."),
     ("ex", "Example 1", "Plan a story called 'The Lost Bag'.", ["Beginning: Neba goes to the market with her mother and carries her new school bag.", "Problem and climax: she puts the bag down and it disappears; she searches and cries.", "Solution and ending: a kind seller found it; Neba thanks him and promises to be careful."], "A plan with a beginning, a problem, a climax and an ending."),
     ("ex", "Example 2", "Improve this sentence with a description: The dog was big.", ["Add adjectives that show what you see: huge, brown.", "Add an action and a sound: barked loudly at the gate.", "Together: The huge brown dog barked loudly at the gate."], "The huge brown dog barked loudly at the gate.")],
    [M("application", "A story should be written mainly in the...", "past tense", ["future tense", "present continuous tense", "imperative"], "Stories tell what happened, so we use the past tense."),
     M("application", "Which is the best linking word to show the end of a story?", "At last", ["First", "For example", "However"], "At last signals the ending."),
     M("application", "Which sentence uses the senses best?", "The sweet smell of ripe mangoes filled the noisy market.", ["The market was good.", "There were things in the market.", "I went to the market."], "It uses smell and sound with exact adjectives."),
     TF("approfondissement", "In a description we must only say what we see.", False, "We can also use hearing, smell, taste and touch."),
     O("Write a short descriptive paragraph (5 sentences) about your village, town or school. Use at least four adjectives and one comparison.", "My school stands on a green hill near the main road. The old brown buildings are surrounded by tall mango trees. In the morning the playground is as noisy as a market. The cool air smells of fresh grass. I am proud of my small, friendly school.", "Marks (out of 4): five sentences with good paragraph order (1), at least four adjectives (1), one comparison (1), correct spelling and punctuation (1).", points=4),
     O("Write a story of about 10 to 12 sentences with the title 'A Surprise on the Way to School'. Use the past tense and give your story a beginning, a problem and an ending.", "Last Monday I left home early to go to school. I walked along the dusty road and sang a song. Suddenly I heard a small cry from the bushes. I looked carefully and saw a tiny puppy with a hurt leg. I was afraid, but I picked it up gently. At the school gate my teacher saw me and called a nurse. She cleaned the leg and said it would be fine. At the end of the day my uncle came and took the puppy to the vet. I was happy that I had helped. I learned to be kind to animals.", "Marks (out of 6): plan with beginning, problem, ending (2); past tense (1); linking words and paragraphs (1); interesting detail (1); spelling and punctuation (1).", tier="examen", points=6)],
    [("The most exciting part of a story is the...", "climax", ["beginning", "title", "last word"], "The climax is the high point."),
     ("Which tense do we use for a story?", "past", ["future", "present perfect only", "none"], "Tell what happened."),
     ("The five senses are sight, hearing, smell, taste and...", "touch", ["speech", "memory", "balance"], "Touch completes the five senses."),
     ("'as busy as ants' is a...", "comparison (simile)", ["rhyme", "question", "title"], "It compares two things with 'as ... as'."),
     ("Before writing a story we should...", "make a plan", ["start at once", "copy a story", "write the ending first without thought"], "A plan keeps the story clear.")],
    ["Marking schemes for compositions are examples only; the FSLC scheme and expected length should be checked.", "Sample answers are original and should be proof-read."],
    prereq=["fslc-english-composition-main", "fslc-english-letter-writing"])

fig_poem = shapes([T(200, 30, "When rain drums on our roof at night,", 15), T(200, 62, "The street lamps glow with silver light.", 15),
                   T(200, 94, "The frogs sing out a happy song,", 15), T(200, 126, "And croak the whole night long.", 15),
                   T(375, 30, "A", 18, bold=True, color="blue"), T(375, 62, "A", 18, bold=True, color="blue"),
                   T(375, 94, "B", 18, bold=True, color="red"), T(375, 126, "B", 18, bold=True, color="red"),
                   T(200, 170, "night / light rhyme (A).  song / long rhyme (B).", 13)], 400, 195)
build(ch, "poetry-rhymes", "Poems and rhymes", 30,
    ["Find rhyming words and the rhyme scheme of a poem.", "Name the parts of a poem: line, stanza, rhythm.", "Recognise simile, alliteration and repetition."],
    [("key", "definition", "Parts of a poem", "A poem is written in **lines**. A group of lines is a **stanza** (verse). **Rhyme** is when words end with the same sound: night / light, song / long. **Rhythm** is the beat of the words when we read aloud. The **rhyme scheme** is the pattern of rhymes: we give the same letter to lines that rhyme (A A B B or A B A B)."),
     ("fig", fig_poem, "A four-line poem with the rhyme scheme A A B B.", "The four lines of a poem. The first two lines end with night and light and are marked A. The last two end with song and long and are marked B."),
     ("key", "definition", "Poetry words", "A **simile** compares two things with *like* or *as*: *as brave as a lion*. A **metaphor** says that one thing is another: *the moon is a silver coin*. **Alliteration** repeats the first sound: *Peter picked ripe red plums*. **Repetition** repeats a word or line for effect. To understand a poem: read it aloud, find the topic, find the feeling, and look at the pictures the words make in your mind."),
     ("key", "pieges", "Common mistakes", "- Thinking that rhyming words must be **spelled** alike: they must **sound** alike (light / write).\n- Answering a poem question with a long story: say what the poem is about and how it makes you feel, in your own words.\n- Mixing up simile (like/as) and metaphor (no like/as)."),
     ("ex", "Example 1", "Find the rhyming words in: The frogs sing out a happy song, and croak the whole night long.", ["Look at the last word of each line: song and long.", "They end with the same sound -ong, so they rhyme."], "song / long."),
     ("ex", "Example 2", "Complete the simile: as brave as a ......", ["A simile compares two things with as ... as.", "A lion is a common sign of courage, so: as brave as a lion."], "as brave as a lion.")],
    [M("application", "Which word rhymes with 'light'?", "night", ["lit", "list", "lice"], "light and night end with the same sound."),
     M("application", "Which sentence has alliteration?", "Peter picked ripe red plums.", ["The moon rose slowly.", "We went home at night.", "Ada has a green bag."], "Repeated first sounds: p, r."),
     M("application", "Which sentence contains a simile?", "He is as strong as an ox.", ["He is a lion in the fight.", "He lives in Buea.", "He ran fast."], "It uses as ... as."),
     MA("approfondissement", "Match the poetry word with its meaning.", [("stanza", "a group of lines"), ("rhyme", "words that end with the same sound"), ("simile", "a comparison with like or as"), ("rhythm", "the beat of the words")], "Basic poetry vocabulary."),
     TF("approfondissement", "'The moon is a silver coin' is a simile.", False, "It does not use like or as: it is a metaphor."),
     P("Read the poem: When rain drums on our roof at night, / The street lamps glow with silver light. / The frogs sing out a happy song, / And croak the whole night long.",
       [PM("Which words rhyme in lines 1 and 2?", "night and light", ["rain and roof", "lamps and glow", "silver and street"], "They end with the same sound."),
        PM("What is the rhyme scheme?", "A A B B", ["A B A B", "A B B A", "A B C D"], "Lines 1-2 rhyme and lines 3-4 rhyme."),
        PM("What is the poem about?", "a rainy night with singing frogs", ["a football match", "a market day", "a school lesson"], "It describes the sounds and sights at night in the rain."),
        PM("Which words show a sound?", "drums, sing, croak", ["glow, silver, light", "street, lamps, roof", "night, song, long"], "These words describe sounds.", points=2)])],
    [("A group of lines in a poem is a...", "stanza", ["chapter", "paragraph only", "rhyme"], "Stanza = verse."),
     ("Which pair rhymes?", "cake / lake", ["cat / cut", "pen / pan", "book / back"], "Cake and lake have the same ending sound."),
     ("'as quick as lightning' is a...", "simile", ["metaphor", "rhyme scheme", "stanza"], "As ... as."),
     ("Alliteration is...", "repeating the same first sound", ["a rhyme at the end", "a question", "a joke"], "Sally sells sea shells."),
     ("A rhyme scheme of A B A B means...", "lines 1 and 3 rhyme and lines 2 and 4 rhyme", ["all lines rhyme", "no line rhymes", "only the last line rhymes"], "Same letter, same rhyme.")],
    ["The poem is an original four-line poem written for this lesson. Metaphor is introduced only briefly; check the syllabus."],
    prereq=["fslc-english-vocabulary-families"])

fig_syl = shapes([RECT(35, 40, 60, 40, fill="lightblue"), RECT(105, 40, 60, 40, fill="lightblue"), RECT(175, 40, 60, 40, fill="lightblue"),
                  T(65, 66, "ba", 18, bold=True), T(135, 66, "na", 18, bold=True), T(205, 66, "na", 18, bold=True),
                  T(135, 105, "banana: 3 syllables, ba-NA-na", 12),
                  RECT(35, 135, 90, 40, fill="lightyellow"), RECT(135, 135, 90, 40, fill="lightyellow"),
                  T(80, 161, "man", 18, bold=True), T(180, 161, "go", 18, bold=True),
                  T(130, 195, "mango: 2 syllables, MAN-go", 12)], 400, 215)
L = build(ch, "oral-english-dictation", "Oral English and dictation: sounds, syllables, stress and listening", 30,
    ["Count the syllables in a word and find the stressed syllable.", "Pronounce and spell common difficult words, including silent letters.", "Use polite expressions and prepare a short oral talk; write a dictation correctly."],
    [("key", "definition", "Syllables and stress", "A **syllable** is a beat in a word that has one vowel sound: *pen* (1), *man-go* (2), *ba-na-na* (3), *beau-ti-ful* (3). In words of more than one syllable, one syllable is **stressed**: said louder and longer. *Teacher* is TEA-cher; *Cameroon* is Cam-er-OON; *banana* is ba-NA-na."),
     ("fig", fig_syl, "Syllables are the beats of a word.", "Boxes showing syllables. Banana has three boxes: ba, na and na. Mango has two boxes: man and go. Text says where the stress falls."),
     ("key", "retenir", "Silent letters and sounds", "Some letters are written but not said: **k** in *knife* and *know*; **w** in *write* and *answer*; **b** in *lamb* and *climb*; **h** in *hour* and *honest*; **gh** in *night* and *daughter*. Learn the commonly confused sounds in a list: ship / sheep, bit / beat, pull / pool."),
     ("key", "methode", "Dictation and speaking", "**Dictation**: listen to the whole sentence first, then write it while it is read in small pieces, then listen again and check spelling and punctuation. **Speaking**: greet politely (*Good morning, madam.*), ask politely (*May I come in, please?*), look at your listener, speak clearly and not too fast. For a short talk: introduction, two or three points, conclusion."),
     ("key", "pieges", "Common mistakes", "- Writing a word the way it sounds (*nife*, *rite*): check the silent letters.\n- Counting letters instead of **syllables**.\n- Forgetting capital letters and full stops in a dictation.\n- Speaking too fast, so that the listener cannot follow."),
     ("audio", "Listen and write. The children walked to school in the morning. They were happy, because the teacher had promised a story."),
     ("ex", "Example 1", "How many syllables are in 'beautiful'? Where is the stress?", ["Split into beats: beau-ti-ful: three syllables.", "The first syllable is said louder: BEAU-ti-ful."], "Three syllables; stress on the first: BEAU-ti-ful."),
     ("ex", "Example 2", "Which letters are silent in 'knife' and 'lamb'?", ["In knife the k is not pronounced: we say 'nife'.", "In lamb the b is silent: we say 'lam'."], "k in knife; b in lamb.")],
    [N("application", "How many syllables are in the word 'banana'?", 3, "ba-na-na: 3 syllables."),
     N("application", "How many syllables are in the word 'school'?", 1, "School is said in one beat."),
     M("application", "Which letter is silent in 'knife'?", "k", ["n", "f", "e"], "The k is not said."),
     M("approfondissement", "Which is the stressed syllable in 'Cameroon'?", "the last one (-oon)", ["the first one (Cam-)", "the second one (-er-)", "none"], "We say Cam-er-OON."),
     TF("approfondissement", "In a dictation we should listen to the whole sentence before we begin to write.", True, "Listening first helps us understand the meaning and write correctly."),
     P("Dictation check. The sentence read was: The children walked to school in the morning. Some pupils wrote it like this: The childrens walked to scool in the mourning.",
       [PM("Which word is spelled wrongly?", "scool", ["walked", "school", "children"], "The correct spelling is school (not scool)."),
        PM("Which is the correct spelling of the last word group?", "the morning", ["the mourning", "the morrning", "the mornig"], "Morning (the start of the day) is not mourning (sadness)."),
        PM("What is wrong with 'childrens'?", "children is already plural", ["it needs a capital letter", "it needs -er", "nothing is wrong"], "The plural of child is children; we do not add -s.", points=2),
        PN("How many syllables are in 'children'?", 2, "chil-dren.", points=1)])],
    [("How many syllables does 'mango' have?", "2", ["1", "3", "4"], "man-go."),
     ("Which letter is silent in 'write'?", "w", ["r", "i", "t"], "We say 'rite'."),
     ("In a dictation, the first thing to do is...", "listen to the whole sentence", ["write at once", "close your eyes", "talk to a friend"], "Listen first."),
     ("A polite way to ask permission to enter is...", "May I come in, please?", ["Open the door!", "I'm coming in.", "Let me in."], "Polite and clear."),
     ("The stressed syllable is the one that is...", "louder and longer", ["quieter", "silent", "spelled with a capital"], "Stress makes a syllable stand out.")],
    ["Syllable counts and stress patterns are for British English; the audio block is read by the device text-to-speech voice, so its pronunciation (accent) is not controlled. Dictation of the audio sentence should be checked by a teacher."],
    prereq=["fslc-english-spelling-rules"])

# =========================================================== second mock paper (20 marks)
LM = L
MOCK_PASSAGE = ("Every Saturday, Tabe goes with his grandfather to the family farm outside Bali. They leave early, when the grass is still wet. "
                "Tabe's job is to feed the chickens and to water the small vegetable garden. His grandfather digs the soil and plants cassava. "
                "At noon they sit under a big tree and eat boiled plantain. Tabe loves these days because he learns something new every time.")
assert len(MOCK_PASSAGE) < 600
a = add(LM, P("Read the passage and answer the questions. " + MOCK_PASSAGE,
              [PM("Where is the family farm?", "outside Bali", ["in Douala", "behind the school", "near the sea"], "The passage says the farm is outside Bali.", points=1),
               PM("What is Tabe's job on the farm?", "to feed the chickens and water the garden", ["to dig the soil", "to plant cassava", "to cook plantain"], "His grandfather digs and plants; Tabe feeds and waters.", points=1),
               PM("What does 'noon' mean?", "twelve o'clock in the day", ["early morning", "the evening", "midnight"], "At noon they eat: it is midday.", points=1),
               PM("Why does Tabe love these days?", "he learns something new every time", ["he does not go to school", "he eats cassava", "he plays football"], "The last sentence gives the reason.", points=1),
               PM("What is the best title for the passage?", "A Saturday on the farm", ["A new bicycle", "The market in Bali", "Cooking plantain"], "The whole passage is about Saturdays on the farm.", points=2)]), True)
bs = [add(LM, M("application", q, r, w, e), True) for q, r, w, e in [
    ("Choose the correct word: She sings ......", "beautifully", ["beautiful", "beauty", "more beautiful"], "An adverb describes the verb sings."),
    ("Choose the correct plural: The ...... are playing.", "babies", ["babys", "babyes", "babyies"], "Consonant + y becomes ies."),
    ("Change to the passive: Ada wrote the letter.", "The letter was written by Ada.", ["The letter written by Ada.", "The letter was wrote by Ada.", "Ada was written the letter."], "Past passive: was + written."),
    ("Change to indirect speech: He said, “I am tired.”", "He said that he was tired.", ["He said that I am tired.", "He said that he is tired?", "He said, that he was tired."], "am becomes was; I becomes he."),
    ("Choose: If it ...... tomorrow, we will stay at home.", "rains", ["will rain", "rained", "would rain"], "Present simple after if."),
    ("Which word is an antonym of 'happy'?", "unhappy", ["hungry", "honest", "heavy"], "Un + happy gives the opposite."),
    ("Which sentence is a command?", "Close the door.", ["She closed the door.", "Did you close the door?", "What a heavy door!"], "A command tells someone to do something."),
    ("Which word rhymes with 'night'?", "light", ["lit", "late", "nit"], "Same ending sound.")]]
c1 = add(LM, O("Write a letter of about 8 to 10 sentences to a friend or relative. Tell him or her about a day you enjoyed at school or at home, and invite him or her to visit you.", "12 Church Street, Bali\n5 May 2025\nDear Uncle,\nI hope you are well. Last Saturday we had a sports day at school. I ran in the 100 m race and came second. My friends cheered me and the teacher gave me a small medal. After the race we ate rice and stew. I was very tired but happy. Please come and visit us in the holidays. My mother says you can stay as long as you wish. Write soon.\nYour nephew,\nTabe", "Marks (out of 6): layout of an informal letter (2), content and invitation (2), grammar and tenses (1), spelling and punctuation (1).", points=6, tier="examen"), True)
p.mock("2", "FSLC mock paper 2 — English Language", 90,
       "Time: 1 hour 30 minutes. Marked out of 20. Answer ALL the questions. Read each question carefully and check your spelling. Practice paper written for CastBridge; the format (time, marks, sections) is to be checked against the official texts.",
       [("Section A — Reading comprehension (6 marks)", [a]), ("Section B — Grammar and vocabulary (8 marks)", bs), ("Section C — Composition: informal letter (6 marks)", [c1])])
p.write()
