import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _b import *

p = Pack("fslc-social-studies", "Social Studies — FSLC", level="Class 6", subject="histoire-geo", cursus="primary", exam="FSLC",
         description="Key-point lessons, worked examples, FSLC-style exercises with answers and a mock paper: Cameroon geography, simple history of Cameroon, civic education, Africa and the world, and map skills.",
         programRef="MINEDUB primary school curriculum (English-speaking subsystem), Level III — Social Studies (geography, history, citizenship); to be checked against the official texts",
         wanted="social-studies")
REF = p.programRef
SENS = "Facts about Cameroon are limited to well-established, neutral points; dates and names to be checked by a teacher against the official textbook."

# =========================================================== chapter 1: geography of Cameroon
ch = p.chapter("geography", "Geography of Cameroon", REF)
regions = [("Adamawa", "Ngaoundéré"), ("Centre", "Yaoundé"), ("East", "Bertoua"), ("Far North", "Maroua"), ("Littoral", "Douala"),
           ("North", "Garoua"), ("North-West", "Bamenda"), ("West", "Bafoussam"), ("South", "Ebolowa"), ("South-West", "Buea")]
assert len(regions) == 10
fig_reg = shapes([x for i, (r, c) in enumerate(regions) for x in (
    RECT(8 + (i % 2) * 196, 8 + (i // 2) * 40, 188, 34, fill=("lightblue", "lightyellow", "lightgreen")[i % 3], radius=5),
    T(102 + (i % 2) * 196, 31 + (i // 2) * 40, r + ": " + c, 13, bold=True))], 400, 214)
build(ch, "location-regions", "Where is Cameroon? Regions and regional capitals", 30,
    ["Say where Cameroon is and name its neighbours.", "Name the ten regions of Cameroon and their capitals.", "Name the capital city and the two official languages."],
    [("key", "definition", "Location", "Cameroon is in **Central Africa**, just north of the **Equator**. It has a coast on the **Atlantic Ocean** (the Gulf of Guinea). Its neighbours are **Nigeria** (west), **Chad** (north-east), the **Central African Republic** (east), the **Republic of the Congo**, **Gabon** and **Equatorial Guinea** (south). The area is about 475,000 square kilometres."),
     ("key", "definition", "Capital and languages", "The political capital is **Yaoundé**. **Douala** is the biggest city and the main port. The two official languages are **English** and **French**, and there are also many national languages. Cameroon is often called **Africa in miniature** because it has forests, mountains, savanna, a coast and a desert edge."),
     ("fig", fig_reg, "The ten regions of Cameroon and their capitals.", "Ten boxes. Each shows a region and its capital: Adamawa, Ngaoundéré; Centre, Yaoundé; East, Bertoua; Far North, Maroua; Littoral, Douala; North, Garoua; North-West, Bamenda; West, Bafoussam; South, Ebolowa; South-West, Buea."),
     ("key", "retenir", "Remembering the regions", "There are **10 regions**. Three are in the **north** (Far North, North, Adamawa). Two are **English-speaking** regions in the west (North-West and South-West). The others are Centre, East, Littoral, South and West. Learn them with the capitals in pairs: Littoral-Douala, West-Bafoussam, South-West-Buea."),
     ("key", "pieges", "Common mistakes", "- Mixing up the **capital of Cameroon** (Yaoundé) and the **biggest city** (Douala).\n- Confusing a region with its capital (the Littoral is the region; Douala is its capital).\n- Writing *North West* and *Northwest* in different ways: use *North-West* and *South-West*.\n- Saying that Cameroon is in West Africa only."),
     ("ex", "Example 1", "Give the capital of the South-West Region and the capital of the Far North Region.", ["South-West: the regional capital is Buea.", "Far North: the regional capital is Maroua."], "Buea and Maroua."),
     ("ex", "Example 2", "Name three neighbours of Cameroon and say in which direction each one lies.", ["Nigeria is to the west.", "Chad is to the north-east, and Gabon is to the south."], "Nigeria (west), Chad (north-east), Gabon (south).")],
    [M("application", "What is the capital of the West Region?", "Bafoussam", ["Bamenda", "Bertoua", "Buea"], "Bafoussam is the capital of the West Region."),
     N("application", "How many regions does Cameroon have?", len(regions), "There are ten regions."),
     M("application", "Which country is a neighbour of Cameroon to the west?", "Nigeria", ["Gabon", "Chad", "Equatorial Guinea"], "Nigeria is on the west side."),
     MA("approfondissement", "Match the region with its capital.", [("Littoral", "Douala"), ("North-West", "Bamenda"), ("East", "Bertoua"), ("South", "Ebolowa")], "Learn the regions and capitals in pairs."),
     TF("approfondissement", "Douala is the political capital of Cameroon.", False, "Yaoundé is the political capital. Douala is the biggest city and main port."),
     P("A teacher shows pupils the regions on a map. Eko lives in Buea, Ada lives in Maroua and Neba lives in Bamenda.",
       [PM("In which region does Eko live?", "South-West", ["North-West", "Littoral", "West"], "Buea is the capital of the South-West Region."),
        PM("In which region does Ada live?", "Far North", ["North", "Adamawa", "East"], "Maroua is the capital of the Far North Region."),
        PM("Which two regions are English-speaking?", "North-West and South-West", ["West and Littoral", "East and South", "North and Far North"], "Bamenda and Buea are the capitals of the two English-speaking regions.", points=2)])],
    [("The political capital of Cameroon is...", "Yaoundé", ["Douala", "Garoua", "Limbe"], "Yaoundé is the capital."),
     ("Cameroon is on the coast of the...", "Atlantic Ocean", ["Indian Ocean", "Pacific Ocean", "Red Sea"], "Cameroon is on the Gulf of Guinea."),
     ("What is the capital of the North Region?", "Garoua", ["Maroua", "Ngaoundéré", "Bertoua"], "Garoua is the capital of the North."),
     ("The two official languages are...", "English and French", ["English and Spanish", "French and Arabic", "Fulfulde and Ewondo"], "English and French are the official languages."),
     ("Cameroon is called 'Africa in miniature' because it has...", "many kinds of landscapes and climates", ["only forests", "only deserts", "no mountains"], "It has coast, forest, mountains and savanna.")],
    [SENS, "Area (about 475,000 km²) and regional capitals are standard facts; check against the textbook. 'Africa in miniature' is a common nickname."],
    prereq=[])

fig_relief = shapes([POLY([20, 190, 90, 190, 110, 150, 150, 150, 170, 110, 210, 110, 230, 75, 250, 40, 270, 75, 295, 110, 330, 110, 380, 190], fill="lightgreen", closed=True),
                     T(60, 215, "coast", 13, bold=True), T(250, 25, "Mount Cameroon area", 12), T(190, 215, "plateaus and highlands", 13, bold=True), T(335, 215, "northern plains", 13, bold=True)], 400, 235)
build(ch, "relief-rivers", "Relief, rivers and lakes of Cameroon", 30,
    ["Describe the main relief regions: coastal plain, plateaus, highlands, northern plains.", "Name Mount Cameroon, the main rivers and two lakes.", "Say why rivers and mountains are useful."],
    [("key", "definition", "Relief", "**Relief** means the shape of the land. Cameroon has: the low **coastal plain** on the Atlantic; the **Southern plateau** (the forest zone); the **Western highlands** (the Grassfields, with high hills and volcanic mountains); the **Adamawa plateau** in the centre; and the flat **northern plains** towards Lake Chad and the River Benue."),
     ("fig", fig_relief, "A simple profile of the land from the coast to the north.", "A green hill-shaped profile. The land is low at the coast, rises to a highest peak near Mount Cameroon, falls over plateaus and highlands, and is low again in the northern plains."),
     ("key", "retenir", "Mount Cameroon", "**Mount Cameroon** (also called **Fako**) is the highest mountain in Cameroon, about 4,000 metres high. It is an **active volcano** near Buea and Limbe, in the South-West Region. People climb it for sport, and farmers use the fertile volcanic soil around it."),
     ("key", "retenir", "Rivers and lakes", "Important rivers: the **Sanaga** (the longest river wholly in Cameroon), the **Wouri** (flows into the sea near Douala), the **Benue** (flows north-west to Nigeria) and the **Logone** (flows toward Lake Chad). **Lake Chad** is in the far north and is shared with other countries. **Lake Nyos** is a small crater lake in the North-West. Rivers give water, fish, transport and **hydroelectric power**."),
     ("key", "pieges", "Common mistakes", "- Saying that Mount Cameroon is in the North or in the West: it is in the **South-West**.\n- Thinking that all rivers flow to the same sea: some flow to the Atlantic, some to the Niger and some to Lake Chad.\n- Mixing up **relief** (shape of the land) with **climate** (weather)."),
     ("ex", "Example 1", "In which region is Mount Cameroon, and what kind of mountain is it?", ["Mount Cameroon stands near Buea and Limbe.", "Buea and Limbe are in the South-West Region, and the mountain is an active volcano."], "In the South-West Region; it is an active volcano."),
     ("ex", "Example 2", "Give two uses of a river such as the Sanaga.", ["People use river water for farming and fishing.", "Dams on the Sanaga produce electricity, and rivers can also carry boats."], "Fishing and electricity (also water for farming, transport).")],
    [M("application", "What is the highest mountain in Cameroon?", "Mount Cameroon", ["Mount Kilimanjaro", "Mount Oku", "Mount Manengouba"], "Mount Cameroon (Fako) is the highest in Cameroon."),
     M("application", "Which river flows into the sea near Douala?", "the Wouri", ["the Benue", "the Logone", "the Nile"], "The Wouri estuary is at Douala."),
     M("application", "Which lake is in the far north of Cameroon?", "Lake Chad", ["Lake Nyos", "Lake Victoria", "Lake Malawi"], "Lake Chad is in the far north."),
     TF("approfondissement", "The coastal plain of Cameroon is low land.", True, "It is low land next to the Atlantic Ocean."),
     MA("approfondissement", "Match the feature with its place.", [("Mount Cameroon", "South-West Region"), ("Lake Chad", "far north"), ("River Wouri", "near Douala"), ("Adamawa plateau", "centre of Cameroon")], "These are well-known features."),
     P("A group of pupils from Bamenda plans a school trip. They want to see a volcano, a big river port and a lake.",
       [PM("Which mountain can they visit near Buea?", "Mount Cameroon", ["Mount Oku", "Mount Kilimanjaro", "Mount Kenya"], "Mount Cameroon is an active volcano near Buea."),
        PM("Which river is near the big port city of Douala?", "the Wouri", ["the Benue", "the Logone", "the Sanaga's source"], "The Wouri river meets the sea at Douala."),
        PM("Which feature is a lake?", "Lake Nyos", ["Mount Cameroon", "the Sanaga", "the Wouri"], "Lake Nyos is a crater lake.", points=2)])],
    [("Relief means...", "the shape of the land", ["the weather", "the people", "the farming"], "Hills, plains and mountains."),
     ("The Sanaga is...", "a river", ["a lake", "a mountain", "a town"], "It is the longest river wholly in Cameroon."),
     ("Mount Cameroon is a...", "volcano", ["lake", "desert", "plain"], "It is an active volcano."),
     ("Which region has the coast and Mount Cameroon?", "South-West", ["North", "East", "Adamawa"], "Buea and Limbe are in the South-West."),
     ("A use of rivers is...", "producing electricity", ["making clouds", "making soil", "growing mountains"], "Dams on rivers produce electricity.")],
    [SENS, "Height of Mount Cameroon is given as 'about 4,000 m' because books give slightly different figures (e.g. 4,040 m).", "Relief profile is schematic, not a real map."],
    prereq=["fslc-social-studies-location-regions"])

fig_clim = shapes([RECT(60, 20, 280, 40, fill="lightyellow"), T(200, 46, "North: Sahel and savanna, one rainy season", 13, bold=True),
                   RECT(60, 70, 280, 40, fill="lightgreen"), T(200, 96, "Centre: savanna and highlands", 13, bold=True),
                   RECT(60, 120, 280, 40, fill="green"), T(200, 146, "South: rainforest, two rainy seasons", 13, bold=True, color="white"),
                   LINE(35, 25, 35, 155, arrow="end", width=3), T(20, 90, "wetter", 11, anchor="end")], 400, 185)
build(ch, "climate-vegetation", "Climate and vegetation of Cameroon", 30,
    ["Describe the two main climates of Cameroon and the seasons.", "Name the vegetation zones and some plants and animals of each.", "Explain why the north is drier than the south."],
    [("key", "definition", "Climate", "**Climate** is the usual weather of a place over many years. The **south** of Cameroon has a **hot, wet equatorial climate** with **two rainy seasons and two dry seasons**. The **north** is **hotter and drier** with **one rainy season** (about May to October) and a long dry season. The **highlands** are cooler. Weather also changes with height: it is cooler on mountains."),
     ("fig", fig_clim, "Rainfall gets less from the south to the north.", "Three bands. The northern band says Sahel and savanna with one rainy season. The middle band says savanna and highlands. The southern band says rainforest with two rainy seasons. An arrow points to the south for wetter."),
     ("key", "retenir", "Vegetation zones", "- **Equatorial rainforest** (south and east): tall trees, thick leaves, many animals (monkeys, elephants, gorillas in reserves). Korup and Dja are forest reserves.\n- **Savanna** (centre, Adamawa, Grassfields): grass with scattered trees.\n- **Sahel / dry savanna** (far north): short grass, thorny trees; Waza National Park protects lions and elephants.\n- **Mangroves** grow along the coast."),
     ("key", "retenir", "Harmattan", "In the dry season a dry, dusty wind called the **Harmattan** blows from the Sahara. It makes the air dusty and cool at night, and lips and skin dry. Wearing warm clothes at night and drinking water helps. People in the north feel it most."),
     ("key", "pieges", "Common mistakes", "- Saying that the whole country has the same climate.\n- Thinking that rainforest means it is raining all day: it has dry months too.\n- Mixing **weather** (today) and **climate** (over many years).\n- Forgetting that the highlands (West, North-West) are cooler than the lowlands."),
     ("ex", "Example 1", "Why does the south grow cocoa and the north grow cotton?", ["Cocoa needs a lot of rain and heat: the south is wet.", "Cotton needs a long sunny dry season: the north has one rainy season and a long dry one."], "Cocoa likes the wet, warm south; cotton likes the drier north."),
     ("ex", "Example 2", "Name two differences between the climate of Douala and of Maroua.", ["Douala is on the coast: hot, very wet, with two rainy seasons.", "Maroua is in the far north: hot, much drier, with one short rainy season."], "Douala is wetter with two rainy seasons; Maroua is drier with one.")],
    [M("application", "Which climate does the south of Cameroon have?", "hot and wet (equatorial)", ["cold and dry", "hot desert", "cold and wet"], "The south is hot and wet."),
     M("application", "How many rainy seasons does the far north have?", "one", ["two", "three", "none"], "The north has one rainy season."),
     M("application", "Which vegetation grows in the south of Cameroon?", "rainforest", ["Sahel", "desert", "snow"], "The south has tropical rainforest."),
     TF("approfondissement", "The Harmattan is a dry, dusty wind from the Sahara.", True, "It blows in the dry season."),
     MA("approfondissement", "Match the zone with an example.", [("rainforest", "Korup"), ("savanna", "the Grassfields"), ("Sahel", "the far north"), ("mangroves", "the coast")], "These are standard examples."),
     P("Mary's family lives in Bafoussam in the West Region. Her cousin lives in Maroua. Mary says: 'It is cooler here in the highlands than where my cousin lives.'",
       [PM("Is Mary right?", "Yes, highlands are cooler", ["No, the highlands are hotter", "No, it is exactly the same", "Only in the rainy season"], "Height makes places cooler."),
        PM("Which place is drier?", "Maroua", ["Bafoussam", "both are equal", "neither"], "The far north is drier."),
        PM("Which crop is likely to be grown near Maroua?", "cotton", ["cocoa", "oil palm", "rubber"], "Cotton likes the drier north.", points=2)])],
    [("The wet season in the north lasts about...", "May to October", ["all year", "January only", "December to February"], "The north has one long dry season."),
     ("The Harmattan is a...", "dry dusty wind", ["cold rain", "type of fruit", "mountain"], "It comes from the Sahara."),
     ("Which zone is wettest?", "the rainforest in the south", ["the Sahel", "the highlands only", "Lake Chad"], "The south is wettest."),
     ("Waza National Park is in the...", "Far North", ["South-West", "East", "Centre"], "It protects savanna animals."),
     ("It is cooler in the highlands because...", "they are high above sea level", ["they are near the Equator only", "they are in the north", "they have no rain"], "Temperature falls with height.")],
    [SENS, "Exact months of the seasons vary by region and year: given loosely. Reserves named (Korup, Dja, Waza) are well known; wildlife examples simplified."],
    prereq=["fslc-social-studies-relief-rivers"])

fig_eco = grid([("Primary", "farming, fishing, mining"), ("Secondary", "factories, processing"), ("Tertiary", "trade, transport, schools")], 3, 120, 70, gap=8, size=12)
build(ch, "economy-transport", "Economic activities and transport", 35,
    ["Name the main economic activities and the regions where they are important.", "Tell primary, secondary and tertiary activities apart.", "Name the main means of transport and a few ports, railways and airports."],
    [("key", "definition", "Economic activities", "People work to earn money and to produce what we need. **Primary** activities take things from nature: farming, fishing, herding, forestry and mining. **Secondary** activities change them into other goods: factories, food processing, sawmills. **Tertiary** activities are services: trade, transport, banks, teaching, health care and tourism."),
     ("fig", fig_eco, "Primary, secondary and tertiary activities.", "Three boxes: primary (farming, fishing, mining), secondary (factories, processing) and tertiary (trade, transport, schools)."),
     ("key", "retenir", "Farming and other activities", "- **Cash crops**: cocoa (Centre, South, South-West), coffee (West, South-West, Littoral), cotton (North), bananas, oil palm, rubber and tea.\n- **Food crops**: cassava, plantain, maize, yams, groundnuts, beans.\n- **Livestock**: cattle in the Adamawa, North and North-West.\n- **Fishing** on the coast, rivers and Lake Chad.\n- **Timber** from the forests of the East and South.\n- **Petroleum** from the sea near the coast; **tourism** and **trade**."),
     ("key", "retenir", "Transport", "Cameroon uses **roads** (the most used), **railways** (Douala-Yaoundé and Yaoundé-Ngaoundéré), **rivers and the sea** (the ports of **Douala** and **Kribi**), and **air** (international airports at Douala and Yaoundé, and others). Good transport helps farmers to sell their crops and brings goods to the towns. Neighbouring countries such as Chad and the Central African Republic also use Cameroon's roads, railway and port."),
     ("key", "pieges", "Common mistakes", "- Placing cocoa in the dry north or cotton in the rainforest.\n- Calling a factory a primary activity: it is **secondary**.\n- Thinking that only farming is work: teaching, driving and trading are also important activities.\n- Forgetting that food processing (making oil from palm nuts) adds value to crops."),
     ("ex", "Example 1", "Classify as primary, secondary or tertiary: (a) growing cocoa, (b) making chocolate in a factory, (c) selling chocolate in a shop.", ["(a) Growing cocoa takes a product from the land: primary.", "(b) Making chocolate changes cocoa into a new product: secondary.", "(c) Selling is a service: tertiary."], "(a) primary; (b) secondary; (c) tertiary."),
     ("ex", "Example 2", "Why are roads important for farmers in the West Region?", ["Farmers need to carry maize, vegetables and coffee to markets in towns.", "Good roads make the journey faster and the goods stay fresh."], "They carry crops to markets quickly and cheaply, so farmers earn more.")],
    [M("application", "Which is a cash crop grown mainly in the north of Cameroon?", "cotton", ["cocoa", "oil palm", "rubber"], "Cotton likes the drier north."),
     M("application", "Fishing and farming are...", "primary activities", ["secondary activities", "tertiary activities", "not work"], "They take products from nature."),
     M("application", "Which is the biggest port of Cameroon?", "Douala", ["Garoua", "Bamenda", "Maroua"], "Douala is the main port."),
     TF("approfondissement", "A teacher is working in a tertiary activity.", True, "Teaching is a service."),
     MA("approfondissement", "Match the activity with its type.", [("growing maize", "takes a product from the land"), ("making palm oil in a factory", "changes raw materials into goods"), ("driving a taxi", "gives a service"), ("fishing", "takes a product from the water")], "Think about what the person does with the product."),
     P("A farmer in the Centre Region grows cocoa. A company buys the cocoa, dries it and makes cocoa butter in a factory in Douala. Shops sell chocolate to people.",
       [PM("Which activity is primary?", "growing the cocoa", ["making cocoa butter", "selling chocolate", "driving a lorry only"], "Growing takes a product from the land."),
        PM("Which activity is secondary?", "making cocoa butter in a factory", ["growing cocoa", "selling chocolate", "going to school"], "A factory changes raw materials into products."),
        PM("Which service helps the cocoa reach Douala?", "transport", ["farming", "mining", "forestry"], "Lorries and roads carry the cocoa.", points=2)])],
    [("Cattle are mainly reared in...", "Adamawa and the North", ["the coast", "the cities only", "the sea"], "Open grassland suits cattle."),
     ("A factory that makes biscuits is a...", "secondary activity", ["primary activity", "tertiary activity", "farm"], "It changes raw materials into goods."),
     ("Which crop is a food crop?", "cassava", ["cotton", "rubber", "cocoa"], "Cassava is eaten by families."),
     ("Which is a means of air transport?", "aeroplane", ["lorry", "canoe", "train"], "Planes fly."),
     ("Timber is mainly obtained from...", "forests", ["deserts", "lakes", "mountains of ice"], "Trees grow in forests.")],
    [SENS, "Regions named for each crop are simplified (several crops grow in several regions). Port of Kribi and railway lines are well known but their details (dates, capacity) are not given.", "Petroleum is mentioned in general terms only; no production figures."],
    prereq=["fslc-social-studies-climate-vegetation"])

# =========================================================== chapter 2: history
ch = p.chapter("history", "A simple history of Cameroon", REF)
assert 1916 - 1884 == 32 and 1972 - 1960 == 12 and 1961 - 1960 == 1 and 1884 - 1472 == 412
fig_t1 = timeline(1450, 1930, [(1472, "Portuguese on the coast"), (1884, "German protectorate"), (1916, "Britain and France")], [], 480, 230)
build(ch, "history-early-colonial", "From early times to colonial rule", 35,
    ["Say who the first peoples and kingdoms of Cameroon were and how Cameroon got its name.", "Describe the German period and the division between Britain and France.", "Put the main events in order on a timeline."],
    [("key", "definition", "Early times and the name Cameroon", "Many peoples have lived in the land of Cameroon for a very long time, for example forest peoples such as the Baka, farming peoples and the peoples of the Grassfields, with kingdoms and chiefdoms such as the **Bamum** in the West and the **Duala** chiefs on the coast. In about **1472** Portuguese sailors arrived at the River Wouri and called it the *river of prawns* (*Rio dos Camarões*). The name **Cameroon** comes from this."),
     ("fig", fig_t1, "Three important dates before independence.", "A timeline from 1450 to 1930 with three events: Portuguese arrive about 1472, German protectorate 1884, Britain and France take over in 1916."),
     ("key", "retenir", "German rule", "In **1884** the Duala chiefs signed treaties with Germany, and the country became a German **protectorate** called *Kamerun*. The Germans built roads, railways and plantations. Many Cameroonians were made to work for them, and some people resisted. German rule lasted until the First World War."),
     ("key", "retenir", "Britain and France", "In the First World War, British and French forces took Kamerun. By **1916** the Germans had left. The country was **divided** between **Britain** (a smaller part in the west, the British Cameroons) and **France** (a larger part, French Cameroun). The League of Nations gave them **mandates** to rule, and after 1945 the United Nations gave them **trusteeship**. This is why Cameroon has two official languages today."),
     ("key", "pieges", "Common mistakes", "- Saying that Cameroon was always one country: it was divided in 1916.\n- Mixing up the dates: 1472 (Portuguese), 1884 (German protectorate), 1916 (Britain and France).\n- Thinking that the Portuguese ruled Cameroon: they only traded on the coast.\n- Giving opinions as facts; in history we use sources and dates."),
     ("ex", "Example 1", "How did Cameroon get its name?", ["About 1472 Portuguese sailors reached the River Wouri.", "They found many prawns and named it the river of prawns, Rio dos Camarões. Later the name became Cameroon."], "From Rio dos Camarões, the Portuguese name for the River Wouri (the river of prawns)."),
     ("ex", "Example 2", "How many years passed between the German treaties (1884) and the division between Britain and France (1916)?", ["Subtract the dates: 1916 − 1884.", "1916 − 1884 = 32."], "32 years.")],
    [M("application", "Which European country made Cameroon a protectorate in 1884?", "Germany", ["Britain", "France", "Portugal"], "Germany signed treaties with the Duala chiefs in 1884."),
     M("application", "What does 'Rio dos Camarões' mean?", "river of prawns", ["river of gold", "river of fish and boats", "red river"], "Camarões means prawns."),
     N("application", "How many years are there between 1884 and 1916?", 1916 - 1884, "1916 − 1884 = 32."),
     TF("approfondissement", "After 1916 the whole of Cameroon was ruled only by France.", False, "It was divided between Britain (smaller part) and France (larger part)."),
     MA("approfondissement", "Match the date with the event.", [("about 1472", "Portuguese sailors reach the Wouri"), ("1884", "German protectorate begins"), ("1916", "Germans leave; Britain and France divide the land"), ("1945 onwards", "United Nations trusteeship")], "These are the main events in order."),
     P("Read: In 1884 the Duala chiefs and Germany signed treaties. German rule built a railway and plantations. In 1916, after the First World War, Britain and France divided Cameroon.",
       [PM("Which country ruled Cameroon first, after the Portuguese traders?", "Germany", ["Britain", "France", "Nigeria"], "Germany ruled from 1884."),
        PM("In what year did Britain and France divide Cameroon?", "1916", ["1884", "1960", "1472"], "After the First World War, in 1916."),
        PM("Which is a reason why Cameroon has two official languages?", "it was ruled by Britain and France", ["the Portuguese taught English", "the Bamum brought French", "there is no reason"], "British and French rule left English and French.", points=2)])],
    [("The Portuguese reached the Wouri in about...", "1472", ["1884", "1916", "1960"], "That is the date usually given."),
     ("A protectorate is...", "a country controlled by a stronger country", ["a free country", "a kind of school", "a forest"], "The protecting power controls the land."),
     ("The name Cameroon comes from the Portuguese word for...", "prawns", ["mountains", "chiefs", "forest"], "Camarões = prawns."),
     ("Who ruled the larger part of Cameroon after 1916?", "France", ["Germany", "Portugal", "Nigeria"], "French Cameroun was the larger part."),
     ("The Bamum kingdom is in the...", "West", ["Far North", "East", "South-West"], "Bamum is in the West Region (Foumban).")],
    [SENS, "Dates (1472, 1884, 1916) are those commonly given in school textbooks; 1472 is approximate. Mention of resistance and forced labour is deliberately brief; textbook wording to be checked.", "The slave trade era is not covered."],
    prereq=["fslc-social-studies-location-regions"])

fig_t2 = shapes([LINE(40, 100, 360, 100, width=3, arrow="end"),
                 CIRCLE(70, 100, 7, fill="red"), T(70, 70, "1960", 15, bold=True), T(70, 140, "French Cameroun", 12), T(70, 156, "independent", 12),
                 CIRCLE(190, 100, 7, fill="red"), T(190, 70, "1961", 15, bold=True), T(190, 140, "Southern Cameroons", 12), T(190, 156, "joins; federation", 12),
                 CIRCLE(310, 100, 7, fill="red"), T(310, 70, "1972", 15, bold=True), T(310, 140, "United Republic", 12), T(310, 156, "(20 May)", 12)], 400, 190)
build(ch, "history-independence", "Independence, reunification and the nation today", 35,
    ["Explain how French Cameroun and the British Cameroons became independent.", "Describe the 1961 plebiscite and reunification.", "Say what 20 May, 11 February and 1 October celebrate."],
    [("key", "definition", "Independence", "French Cameroun became **independent** on **1 January 1960**, with **Ahmadou Ahidjo** as its first president. **Nigeria** became independent on 1 October 1960. The British Cameroons (Northern and Southern) were still under British trusteeship, so the United Nations arranged a **plebiscite** (a vote of the people) there."),
     ("fig", fig_t2, "Independence, reunification and the United Republic.", "A timeline arrow with three dates: 1960, French Cameroun becomes independent; 1961, Southern Cameroons joins and a federation is formed; 1972, the United Republic of Cameroon on 20 May."),
     ("key", "retenir", "The 1961 plebiscite", "On **11 February 1961** the people of the British Cameroons voted. **Northern Cameroons** chose to join **Nigeria**. **Southern Cameroons** chose to join the Republic of **Cameroon**. On **1 October 1961** Southern Cameroons joined, and the country became the **Federal Republic of Cameroon**, with two federated states (East and West). This is called **reunification**."),
     ("key", "retenir", "Later changes and national days", "On **20 May 1972** a referendum created the **United Republic of Cameroon**, one state instead of two federated states; in 1984 it was renamed the **Republic of Cameroon**. Ahidjo was president until 1982, and **Paul Biya** has been president since 1982. National days: **11 February** (Youth Day), **20 May** (National Day) and **1 October** (reunification of the two Cameroons, celebrated in some places)."),
     ("key", "pieges", "Common mistakes", "- Mixing 1960 (independence of French Cameroun) and 1961 (joining of Southern Cameroons).\n- Saying that all the British Cameroons joined Cameroon: the Northern part chose Nigeria.\n- Mixing 11 February (Youth Day) and 20 May (National Day).\n- Giving opinions about politics: in this subject we learn the facts and dates."),
     ("ex", "Example 1", "How many years passed from independence (1960) to the United Republic (1972)?", ["Subtract the dates: 1972 − 1960.", "1972 − 1960 = 12."], "12 years."),
     ("ex", "Example 2", "What did the people of the Southern Cameroons decide in the 1961 plebiscite?", ["The vote was on 11 February 1961.", "They chose to join the Republic of Cameroon, while Northern Cameroons chose Nigeria."], "They chose to join the Republic of Cameroon.")],
    [M("application", "On which date did French Cameroun become independent?", "1 January 1960", ["1 October 1961", "20 May 1972", "11 February 1961"], "It became independent on 1 January 1960."),
     M("application", "What do we call a vote of the people on an important question?", "a plebiscite (or referendum)", ["a census", "a market", "a parade"], "A plebiscite is a direct vote."),
     N("application", "How many years are there between 1960 and 1972?", 12, "1972 − 1960 = 12."),
     TF("approfondissement", "In 1961 Northern Cameroons chose to join Nigeria.", True, "It voted to join Nigeria; Southern Cameroons voted to join Cameroon."),
     MA("approfondissement", "Match the date with what we celebrate.", [("11 February", "Youth Day"), ("20 May", "National Day"), ("1 January 1960", "independence of French Cameroun"), ("1 October 1961", "reunification and the Federal Republic")], "These dates are well known."),
     P("Neba's grandmother tells her: 'In 1960 French Cameroun became independent. In 1961 the Southern Cameroons joined it.'",
       [PM("In which year did French Cameroun become independent?", "1960", ["1961", "1972", "1884"], "1960."),
        PM("Which part of the British Cameroons joined Cameroon in 1961?", "Southern Cameroons", ["Northern Cameroons", "Nigeria", "the Far North"], "Southern Cameroons joined; Northern Cameroons chose Nigeria."),
        PM("What was the country called after 1 October 1961?", "Federal Republic of Cameroon", ["Kamerun", "French Cameroun", "United Kingdom"], "It was a federation of East and West.", points=2)])],
    [("The first president of independent Cameroon was...", "Ahmadou Ahidjo", ["Paul Biya", "Fon Njoya", "King Bell"], "Ahidjo was president from 1960 to 1982."),
     ("The plebiscite in the British Cameroons took place in...", "February 1961", ["January 1960", "May 1972", "October 1884"], "11 February 1961."),
     ("20 May is...", "National Day", ["Youth Day", "Christmas", "Independence of Nigeria"], "It remembers 20 May 1972."),
     ("Which part chose to join Nigeria in 1961?", "Northern Cameroons", ["Southern Cameroons", "Douala", "Littoral"], "Northern Cameroons voted for Nigeria."),
     ("The United Republic of Cameroon was created in...", "1972", ["1884", "1960", "1916"], "After the referendum of 20 May 1972.")],
    [SENS, "Dates are standard facts (1 Jan 1960, 11 Feb 1961, 1 Oct 1961, 20 May 1972, name change 1984, Ahidjo to 1982, Biya from 1982); the political situation after 1990 and debates about the 1961 union are deliberately NOT covered. Wording about 1 October should be checked against the textbook (it is not celebrated in the same way everywhere).", "Neutral tone required: a teacher should check that no opinion has entered."],
    prereq=["fslc-social-studies-history-early-colonial"])

# =========================================================== chapter 3: civic education
ch = p.chapter("civics", "Civic education", REF)
fig_rd = grid([("Rights", "what you may have"), ("Duties", "what you must do")], 2, 170, 70, gap=20, size=15)
build(ch, "rights-duties", "Rights and duties of the child and the citizen", 30,
    ["Name important rights of children and the duties that go with them.", "Explain that every right brings a responsibility.", "Give examples of good behaviour at school and at home."],
    [("key", "definition", "Rights and duties", "A **right** is something that every person should have or may do. A **duty** is something we must do. Rights and duties go together: if I have a right, I must respect the same right of others. Children's rights are protected by the **Convention on the Rights of the Child** of the United Nations."),
     ("fig", fig_rd, "Rights and duties go together.", "Two boxes side by side. The first says Rights: what you may have. The second says Duties: what you must do."),
     ("key", "retenir", "Rights of the child", "Children have the right to: **life** and a **name**; **education**; **health care**; **food, clean water and a home**; **protection** from harm and from work that damages their health or school; **rest and play**; to be **heard** and to **practise their religion**; and to be treated **equally** whatever their sex, tribe or religion."),
     ("key", "retenir", "Duties of a pupil and a citizen", "A pupil must: **respect** teachers, parents and other pupils; **obey** school rules; come **on time**; do homework; **look after** school property and keep the school clean. A citizen must: **obey the laws**, **respect** others and their property, **pay taxes** (adults), protect public property, and help to keep the community safe and clean."),
     ("key", "pieges", "Common mistakes", "- Thinking that rights mean we can do anything we like: my rights end where the rights of others begin.\n- Thinking that only adults have rights.\n- Forgetting that children also have duties.\n- Breaking public property (a desk, a tap, a road sign): it belongs to everybody."),
     ("ex", "Example 1", "Right or duty? (a) Going to school. (b) Obeying the school rules.", ["(a) Every child has the right to education.", "(b) Obeying the rules is a duty of every pupil."], "(a) a right; (b) a duty."),
     ("ex", "Example 2", "A pupil writes on the desk with a pen. Which duty is broken, and what should he do?", ["The duty to look after school property.", "He should say sorry, clean the desk and not do it again."], "He broke the duty to look after school property; he should say sorry and clean the desk.")],
    [M("application", "Which is a right of every child?", "education", ["to break the rules", "to hit other children", "to come late"], "Education is a right."),
     M("application", "Which is a duty of a pupil?", "to obey the school rules", ["to eat in class", "to shout at teachers", "to leave early"], "Obeying rules is a duty."),
     M("application", "Who should keep the school clean?", "everybody", ["only the teacher", "only the cleaner", "nobody"], "Every pupil has a duty to help."),
     TF("approfondissement", "Because I have rights, I can do anything I want.", False, "My rights end where the rights of others begin."),
     MA("approfondissement", "Match the right with an example.", [("right to health care", "going to the clinic when sick"), ("right to education", "going to school"), ("right to play", "playing in the break"), ("right to a name", "having a birth certificate")], "Each right has a practical example."),
     P("Ako sees some pupils throwing stones at a school window and a child who wants to play football being sent away because he is 'too small'.",
       [PM("Which duty are the pupils who throw stones forgetting?", "to respect school property", ["to pay taxes", "to vote", "to travel"], "A window belongs to the school."),
        PM("Which right is the small child denied?", "the right to play and to be treated equally", ["the right to vote", "the right to drive", "the right to work"], "All children have the right to play."),
        PM("What should Ako do?", "tell a teacher politely and set a good example", ["throw stones too", "laugh and walk away", "break another window"], "Responsible pupils help the community.", points=2)])],
    [("A right is something that...", "everyone should have", ["nobody should have", "only adults have", "is a punishment"], "Rights belong to everyone."),
     ("Which is a duty?", "respecting others", ["breaking rules", "wasting water", "hurting animals"], "Respect is a duty."),
     ("Children's rights are protected by...", "the Convention on the Rights of the Child", ["a school rule only", "a football law", "nothing"], "It was adopted by the United Nations."),
     ("Public property is...", "owned by everybody", ["owned by nobody", "owned by one pupil", "free to destroy"], "We must look after it."),
     ("Every right is linked to a...", "responsibility", ["holiday", "colour", "price"], "Rights and duties go together.")],
    [SENS, "Child rights are listed in simplified form from the UN Convention; check that they match the wording of the official civic education syllabus. Mention of taxes applies to adults only."],
    prereq=[])

fig_flag = shapes([RECT(120, 40, 50, 100, fill="green"), RECT(170, 40, 50, 100, fill="red"), RECT(220, 40, 50, 100, fill="yellow"), RECT(120, 40, 150, 100, stroke="ink"),
                   POLY([195, 70, 200, 85, 215, 85, 203, 95, 208, 110, 195, 100, 182, 110, 187, 95, 175, 85, 190, 85], fill="yellow", stroke="ink", width=1),
                   T(145, 165, "green", 13), T(195, 165, "red", 13), T(245, 165, "yellow", 13),
                   T(200, 25, "Flag of Cameroon: three vertical stripes and a star", 13, bold=True)], 400, 190)
build(ch, "national-symbols", "National symbols and institutions", 30,
    ["Describe the flag, the motto and the anthem of Cameroon.", "Name the three branches of government in a simple way.", "Say who leads local communities and what a mayor does."],
    [("key", "definition", "National symbols", "The **flag** has three vertical stripes, **green, red and yellow**, with a **yellow star** in the middle of the red stripe. The **motto** is **Peace – Work – Fatherland**. The **anthem** in English begins *O Cameroon, Cradle of Our Forefathers*. The **coat of arms** shows a shield with scales of justice and the motto. We show **respect** for the symbols: we stand when the anthem is played and when the flag is raised."),
     ("fig", fig_flag, "The flag of Cameroon.", "A flag with three vertical stripes, green on the left, red in the middle and yellow on the right. A yellow star is in the centre of the red stripe."),
     ("key", "retenir", "Meaning of the colours", "Textbooks usually say: **green** stands for the forests and hope, **red** for unity, and **yellow** for the sun and the savanna of the north. The **star** stands for unity. The country uses the FCFA as its currency. Yaoundé is the capital."),
     ("key", "retenir", "How the country is governed", "Government has three parts. The **executive** (the **President** and the ministers) runs the country. The **legislature** (the **National Assembly** and the **Senate**) makes the laws. The **judiciary** (the **courts** and judges) applies the laws. Locally, towns and villages have **councils** led by a **mayor** or a **chief** (fon, lamido) who looks after the community and its roads, markets and public places."),
     ("key", "pieges", "Common mistakes", "- Putting the stripes in the wrong order or forgetting the star.\n- Mixing the three branches: the courts do not make laws and the National Assembly does not judge cases.\n- Showing disrespect to the flag or anthem as a joke.\n- Thinking that the mayor and the President do the same job."),
     ("ex", "Example 1", "Describe the flag of Cameroon.", ["It has three vertical stripes: green, red, yellow (left to right).", "A yellow star is in the middle of the red stripe."], "Three vertical stripes (green, red, yellow) with a yellow star on the red stripe."),
     ("ex", "Example 2", "Who makes laws and who applies them to settle cases?", ["The National Assembly (and the Senate) makes laws.", "The courts and judges apply them."], "Parliament makes the laws; the courts apply them.")],
    [M("application", "What colours are the stripes of the flag of Cameroon, from left to right?", "green, red, yellow", ["red, green, yellow", "yellow, red, green", "green, yellow, red"], "Green, red, yellow."),
     M("application", "What is the motto of Cameroon?", "Peace – Work – Fatherland", ["Unity – Strength – Hope", "Freedom – Justice – Work", "Faith – Hope – Charity"], "Peace, Work, Fatherland."),
     M("application", "Which body makes the laws?", "the National Assembly and the Senate", ["the courts", "the police", "the school"], "Parliament makes laws."),
     TF("approfondissement", "The star on the flag is blue.", False, "The star is yellow and stands on the red stripe."),
     MA("approfondissement", "Match the word with its meaning.", [("executive", "runs the country"), ("legislature", "makes the laws"), ("judiciary", "applies the laws in courts"), ("mayor", "leads a local council")], "These are the main parts of government."),
     P("In class the teacher says: 'We are going to raise the flag and sing the anthem.' Eko starts to talk and laugh during the anthem.",
       [PM("How should pupils behave when the anthem is sung?", "stand quietly and show respect", ["talk to friends", "laugh", "run away"], "We show respect to the national symbols."),
        PM("What is the colour of the middle stripe of the flag?", "red", ["green", "yellow", "blue"], "The star is on the red stripe."),
        PM("What is the English opening of the anthem?", "O Cameroon, Cradle of Our Forefathers", ["God Save the Queen", "Arise, O Compatriots", "We are the champions"], "That is the opening line.", points=2)])],
    [("The star on the flag is...", "yellow", ["green", "red", "white"], "It is a yellow star."),
     ("The capital of Cameroon is...", "Yaoundé", ["Douala", "Buea", "Bamenda"], "Yaoundé."),
     ("Who judges cases?", "the courts", ["the National Assembly", "the pupils", "the market"], "Courts and judges."),
     ("A local council is led by a...", "mayor", ["pilot", "judge only", "teacher only"], "A mayor leads the council."),
     ("A motto is...", "a short saying that guides a group", ["a kind of flag", "a river", "a coin"], "Peace, Work, Fatherland is the motto.")],
    [SENS, "Colour meanings and the coat of arms description follow common school textbooks; check wording. Institutions (Senate, National Assembly, councils, courts) described in the simplest way. Anthem line is the English version's first words."],
    prereq=["fslc-social-studies-history-independence"])

fig_tl = shapes([RECT(150, 15, 70, 175, fill="grey", radius=10), CIRCLE(185, 52, 20, fill="red"), CIRCLE(185, 103, 20, fill="orange"), CIRCLE(185, 154, 20, fill="green"),
                 T(235, 58, "red: STOP", 15, bold=True, anchor="start"), T(235, 109, "amber: get ready", 15, bold=True, anchor="start"), T(235, 160, "green: GO when safe", 15, bold=True, anchor="start")], 400, 205)
build(ch, "road-safety-community", "Road safety and living together in the community", 30,
    ["Follow the rules for crossing the road and for being a passenger.", "Know the meaning of the traffic lights and common road signs.", "Describe how people live and work together in a community."],
    [("key", "methode", "Crossing the road safely", "1. Stop at the **edge of the pavement**, not on the road.\n2. Look **left, right and left again**; listen for vehicles.\n3. Cross at a **zebra crossing** or a footbridge if there is one.\n4. Walk straight across, do **not run**, and do not use your phone.\n5. Never play football or other games on the road. Walk on the pavement or, if there is none, on the side facing the traffic."),
     ("fig", fig_tl, "The traffic light.", "A grey traffic light with three lights. The red light means stop, the amber light means get ready, and the green light means go when it is safe."),
     ("key", "retenir", "Signs and passengers", "**Triangle** signs warn (a school ahead, a bend). **Round** signs give an order or forbid something (stop, no entry). **Square or rectangular** signs give information (a hospital, a parking place). **Passengers**: fasten the seat belt, do not put your head or arm out of the window, and do not get in an overloaded vehicle. **Motorbike riders** must wear a helmet."),
     ("key", "retenir", "The community", "A **community** is a group of people who live in the same place and help one another: a family, a school, a village or a town. People do different jobs: farmers, traders, teachers, nurses, drivers, builders, police. We keep our community clean, safe and peaceful by obeying rules, respecting chiefs and elders, helping neighbours, and sharing communal work."),
     ("key", "pieges", "Common mistakes", "- Running across the road after a ball.\n- Crossing between parked vehicles where drivers cannot see you.\n- Thinking that a green light means 'go' even if a car is still coming: look first.\n- Riding a motorbike without a helmet 'because the trip is short'."),
     ("ex", "Example 1", "You want to cross a road at a zebra crossing. Say what you do, in order.", ["Stop at the edge of the pavement, look left, right and left again.", "When the road is clear, walk straight across without running."], "Stop, look left-right-left, then walk across without running."),
     ("ex", "Example 2", "Why must a motorbike rider wear a helmet?", ["In an accident the head can be badly hurt.", "A helmet protects the head and can save a life."], "A helmet protects the head and can save a life.")],
    [M("application", "What does a red traffic light mean?", "stop", ["go", "get ready to go fast", "turn left"], "Red means stop."),
     M("application", "Where should you cross the road?", "at a zebra crossing", ["between parked cars", "on a bend", "anywhere you like"], "Zebra crossings are the safest places."),
     M("application", "A triangular road sign usually gives a...", "warning", ["order to stop only", "price", "hotel name"], "Triangles warn."),
     TF("approfondissement", "A motorbike rider only needs a helmet on long journeys.", False, "A helmet is needed on every journey."),
     MA("approfondissement", "Match the sign shape with its meaning.", [("triangle", "warning"), ("round", "an order"), ("rectangle", "information"), ("zebra stripes", "a place to cross")], "Shapes help us to know the message quickly."),
     P("Neba is walking to school with her little brother. They see their friends on the other side of the road. There is a zebra crossing a short distance away and some cars are coming.",
       [PM("Where should they cross?", "at the zebra crossing", ["between parked cars", "straight across at once", "behind a bus"], "Use the safe crossing place."),
        PM("What should they do before stepping onto the road?", "look left, right and left again", ["close their eyes", "run", "call to their friends and cross"], "Check that the road is clear."),
        PM("What is a good way to look after the little brother?", "hold his hand", ["let him run in front", "let him cross alone", "leave him on the road"], "Hold a young child's hand.", points=2)])],
    [("Green traffic light means...", "go when it is safe", ["stop", "turn off the engine", "park"], "Check the road first."),
     ("When you cross, you look...", "left, right and left again", ["only up", "only at your feet", "at your phone"], "Check both ways."),
     ("Passengers should...", "fasten the seat belt", ["put their head out of the window", "stand in the vehicle", "sit on the roof"], "Seat belts save lives."),
     ("A community is...", "people who live and help each other in a place", ["a kind of car", "only a market", "a road sign"], "A village or a town is a community."),
     ("Where should children play?", "in the playground", ["on the road", "near a river bridge", "on the railway"], "Roads and railways are dangerous.")],
    [SENS, "Road safety rules are general; local rules (helmet law, signs) should be checked by a teacher or the road safety authority. 'Look left, right and left again' is used because Cameroon drives on the right; some books say 'right then left'."],
    prereq=["fslc-social-studies-rights-duties"])

# =========================================================== chapter 4: Africa, the world and maps
ch = p.chapter("world-maps", "Africa, the world and map skills", REF)
fig_cont = grid([("Africa", "Cameroon"), ("Asia", "largest"), ("Europe", "France, UK"), ("N. America", "Canada, USA"), ("S. America", "Brazil"), ("Oceania", "Australia"), ("Antarctica", "ice")], 4, 92, 62, size=12)
build(ch, "africa-world", "Africa and the world", 35,
    ["Name the seven continents and the five oceans.", "Describe Africa: its regions, big rivers, mountains and lakes.", "Name organisations that Cameroon belongs to."],
    [("key", "definition", "Continents and oceans", "There are **seven continents**: Africa, Asia, Europe, North America, South America, Oceania (Australia) and Antarctica. There are **five oceans**: the Pacific (the biggest), the Atlantic, the Indian, the Southern and the Arctic. Cameroon is in **Africa**, on the Atlantic coast."),
     ("fig", fig_cont, "The seven continents.", "Seven boxes with the continents Africa, Asia, Europe, North America, South America, Oceania and Antarctica, each with one example."),
     ("key", "retenir", "Africa", "Africa is the **second biggest continent**. The **Equator** crosses it. It has about **54 countries** and five regions: North, West, Central, East and Southern Africa. Cameroon is in **Central Africa**. Famous features: the **Sahara** (the biggest hot desert), the **River Nile** (the longest river in Africa), the **Congo River**, **Mount Kilimanjaro** (the highest mountain in Africa) and **Lake Victoria** (the biggest lake in Africa)."),
     ("key", "retenir", "Cameroon and other countries", "Cameroon belongs to the **United Nations**, the **African Union**, the **Commonwealth** and the **Francophonie** (it is a member of both because it has English and French). It is a member of **CEMAC**, a group of six Central African countries that share the FCFA currency: Cameroon, Chad, the Central African Republic, the Republic of the Congo, Gabon and Equatorial Guinea. These groups help countries to trade, keep peace and share ideas."),
     ("key", "pieges", "Common mistakes", "- Calling Africa a country: it is a **continent** with many countries.\n- Saying that Cameroon is in North Africa or East Africa.\n- Mixing continents and oceans.\n- Saying that all Africans speak the same language: Africa has hundreds of languages."),
     ("ex", "Example 1", "Name the ocean next to Cameroon and the continent where Cameroon is.", ["Cameroon has a coast on the Atlantic Ocean.", "It is in the continent of Africa, in Central Africa."], "The Atlantic Ocean; the continent of Africa (Central Africa)."),
     ("ex", "Example 2", "Name one great river, one mountain and one desert in Africa.", ["River: the Nile (or the Congo).", "Mountain: Kilimanjaro. Desert: the Sahara."], "The Nile, Mount Kilimanjaro and the Sahara.")],
    [N("application", "How many continents are there?", 7, "Africa, Asia, Europe, North America, South America, Oceania and Antarctica."),
     M("application", "In which part of Africa is Cameroon?", "Central Africa", ["North Africa", "East Africa", "Southern Africa"], "Cameroon is in Central Africa."),
     M("application", "Which is the longest river in Africa?", "the Nile", ["the Wouri", "the Sanaga", "the Benue"], "The Nile is the longest river in Africa."),
     TF("approfondissement", "Africa is a country.", False, "Africa is a continent with about 54 countries."),
     MA("approfondissement", "Match the feature with its type.", [("Sahara", "desert"), ("Kilimanjaro", "mountain"), ("Victoria", "lake"), ("Atlantic", "ocean")], "Each is a physical feature."),
     P("Eko looks at a map of the world. He wants to know where Cameroon is and to which groups it belongs.",
       [PM("On which continent is Cameroon?", "Africa", ["Asia", "Europe", "Oceania"], "It is in Africa."),
        PM("Which currency does Cameroon share with its CEMAC neighbours?", "FCFA", ["Euro", "Naira", "Dollar"], "The FCFA is used in six Central African countries."),
        PM("Why is Cameroon in both the Commonwealth and the Francophonie?", "it has English and French as official languages", ["it is very big", "it has a coast", "it is in Asia"], "History and languages explain this.", points=2)])],
    [("The biggest ocean is the...", "Pacific", ["Atlantic", "Indian", "Arctic"], "The Pacific is the largest."),
     ("The biggest hot desert in the world is the...", "Sahara", ["Kalahari", "Namib", "Gobi"], "The Sahara is in North Africa."),
     ("The highest mountain in Africa is...", "Kilimanjaro", ["Mount Cameroon", "Mount Kenya", "Mount Everest"], "Kilimanjaro, in Tanzania."),
     ("Which continent has no permanent population and is covered by ice?", "Antarctica", ["Europe", "Asia", "Oceania"], "Antarctica is icy."),
     ("The African Union is a group of...", "African countries", ["only rivers", "only deserts", "schools"], "AU members are African states.")],
    [SENS, "Number of African countries (54) is the number of UN-recognised states and some books give a different number; 'longest river' and 'highest mountain' are standard textbook facts. CEMAC membership and the FCFA are well known; some details of membership are simplified."],
    prereq=["fslc-social-studies-location-regions"])

fig_comp = shapes([LINE(200, 30, 200, 210, color="grey"), LINE(110, 120, 290, 120, color="grey"),
                   LINE(137, 57, 263, 183, color="lightgrey"), LINE(137, 183, 263, 57, color="lightgrey"),
                   POLY([200, 38, 193, 120, 207, 120], fill="red"), POLY([200, 202, 193, 120, 207, 120], fill="lightblue"),
                   T(200, 20, "N", 18, bold=True), T(200, 232, "S", 18, bold=True), T(310, 126, "E", 18, bold=True), T(90, 126, "W", 18, bold=True),
                   T(275, 50, "NE", 14), T(125, 50, "NW", 14), T(275, 205, "SE", 14), T(125, 205, "SW", 14)], 400, 240)
fig_gridmap = shapes([RECT(60 + 70 * c, 40 + 40 * r, 70, 40, fill="white", stroke="grey", width=1) for c in range(4) for r in range(4)] +
                     [T(95 + 70 * c, 30, "ABCD"[c], 15, bold=True) for c in range(4)] + [T(42, 66 + 40 * r, str(r + 1), 15, bold=True) for r in range(4)] +
                     [CIRCLE(165, 106, 8, fill="red"), T(165, 126, "school", 11), CIRCLE(235, 186, 8, fill="blue"), T(235, 206, "market", 11)], 400, 225)
assert 4.5 * 20 == 90 and 150 / 20 == 7.5 and 6 * 5 == 30 and 12 * 25 == 300
L = build(ch, "map-skills", "Map skills: direction, symbols, scale and grid references", 35,
    ["Use the eight points of the compass.", "Read a map key (symbols) and a simple scale.", "Give and read a grid reference."],
    [("key", "definition", "Compass directions", "The four main directions are **North, East, South and West**. Between them are North-East (NE), South-East (SE), South-West (SW) and North-West (NW). On most maps **North is at the top**. A **compass** shows the direction: its needle points to the north. To remember the order, say: **N**ever **E**at **S**oggy **W**affles (clockwise)."),
     ("fig", fig_comp, "The eight points of the compass.", "A compass rose with eight arms. The labels are N at the top, E at the right, S at the bottom, W at the left, and NE, SE, SW, NW between them."),
     ("key", "retenir", "Map key and scale", "A **map key** (legend) explains the **symbols** on a map: a blue line for a river, a black line for a road, a dot for a town. The **scale** tells how real distances are shown on the map. If the scale is **1 cm to 20 km**, then 1 cm on the map is 20 km on the ground. To find the real distance: **measure on the map, then multiply** by the scale."),
     ("key", "methode", "Grid references", "A grid map is divided into squares. The columns have **letters** (A, B, C, D) and the rows have **numbers** (1, 2, 3, 4). To give a **grid reference**, say the **letter first and then the number**: B2. A **physical map** shows relief and water; a **political map** shows countries, regions and towns; latitudes run east-west and longitudes north-south."),
     ("key", "pieges", "Common mistakes", "- Forgetting that north is at the **top** of a map.\n- Multiplying by the wrong number, or forgetting to use the scale.\n- Giving the number before the letter in a grid reference.\n- Measuring a distance from the edge of the ruler instead of from the 0 mark."),
     ("ex", "Example 1", "On a map with a scale of 1 cm to 20 km, two towns are 4.5 cm apart. What is the real distance?", ["Each centimetre stands for 20 km.", "4.5 × 20 = 90 km."], "90 km."),
     ("ex", "Example 2", "In the grid picture, in which square is the school?", ["The school is in the second column (B) and the second row.", "The reference is B2."], "B2.", fig_gridmap)],
    [M("application", "Which direction is opposite to north-east?", "south-west", ["north-west", "south-east", "east"], "NE and SW are opposite."),
     N("application", "Scale: 1 cm to 20 km. Two towns are 4.5 cm apart on the map. How far apart are they (km)?", 90, "4.5 × 20 = 90 km.", unit="km"),
     M("application", "On a map, what does the map key explain?", "the symbols", ["the age of the map", "the colour of the paper", "the name of the artist"], "The key shows what each symbol means."),
     N("approfondissement", "Scale: 1 cm to 20 km. The real distance between two villages is 150 km. How many cm apart are they on the map?", 7.5, "150 ÷ 20 = 7.5 cm.", tol=0.01, unit="cm"),
     TF("approfondissement", "In a grid reference we write the number first and then the letter.", False, "The letter comes first: B2, not 2B."),
     P("A map has the scale 1 cm to 5 km. The distance from Ada's village to the market is 6 cm on the map, and the school is 2 cm north of the village.",
       [PN("What is the real distance from the village to the market?", 30, "6 × 5 = 30 km.", unit="km", points=2),
        PN("What is the real distance from the village to the school?", 10, "2 × 5 = 10 km.", unit="km"),
        PM("In which direction is the school from the village?", "north", ["south", "east", "west"], "North is at the top of the map.", points=1)])],
    [("North is usually shown at the...", "top of the map", ["bottom of the map", "left of the map", "right of the map"], "North is at the top."),
     ("The scale 1 cm to 10 km means 3 cm on the map is...", "30 km", ["13 km", "3 km", "300 km"], "3 × 10 = 30."),
     ("In the grid reference C3 the letter C shows the...", "column", ["row", "scale", "key"], "Letters are for columns."),
     ("A compass needle points to the...", "north", ["south", "east", "west"], "Magnetic north."),
     ("A blue line on a map usually shows a...", "river", ["road", "border", "railway"], "Check the key to be sure.")],
    [SENS, "Mnemonic 'Never Eat Soggy Waffles' is a common memory aid, not a fact; the teacher may replace it. A blue line = river is the usual convention; check the map key each time."],
    prereq=["fslc-social-studies-africa-world"])

# =========================================================== mock paper (20 marks)
LM = L
a = [add(LM, M("application", q, r, w, e), True) for q, r, w, e in [
    ("What is the capital of the North-West Region?", "Bamenda", ["Buea", "Bafoussam", "Bertoua"], "Bamenda is the capital of the North-West."),
    ("Which mountain is an active volcano in the South-West Region?", "Mount Cameroon", ["Mount Oku", "Kilimanjaro", "Mount Kenya"], "Mount Cameroon (Fako)."),
    ("Which vegetation grows in the south of Cameroon?", "rainforest", ["Sahel", "desert", "snow"], "The south is hot and wet."),
    ("Which is the main port of Cameroon?", "Douala", ["Maroua", "Garoua", "Bafoussam"], "Douala is on the Wouri estuary.")]]
a.append(add(LM, MA("application", "Match the region with its capital.", [("Littoral", "Douala"), ("North", "Garoua"), ("South", "Ebolowa"), ("East", "Bertoua")], "Learn the regions and capitals in pairs.", points=2), True))
b = add(LM, P("Read: French Cameroun became independent on 1 January 1960. On 11 February 1961 the people of the British Cameroons voted: Northern Cameroons chose to join Nigeria and Southern Cameroons chose to join Cameroon. The union took place on 1 October 1961.",
              [PM("In which year did French Cameroun become independent?", "1960", ["1884", "1916", "1972"], "1960.", points=1),
               PM("What is the name of the vote of the people?", "plebiscite", ["census", "parade", "journey"], "A plebiscite is a vote.", points=1),
               PM("Which part chose to join Nigeria?", "Northern Cameroons", ["Southern Cameroons", "Littoral", "French Cameroun"], "Northern Cameroons voted for Nigeria.", points=1),
               PN("How many years are there between 1960 and 1972?", 12, "1972 − 1960 = 12.", points=2)]), True)
c1 = add(LM, M("application", "Which is a duty of a pupil?", "to obey the school rules", ["to break desks", "to come late", "to shout in class"], "Obeying rules is a duty."), True)
c2 = add(LM, M("application", "What does a red traffic light mean?", "stop", ["go", "turn left", "park"], "Red means stop."), True)
c3 = add(LM, O("Give THREE rules to cross the road safely.", "1. Stop at the edge of the pavement. 2. Look left, right and left again. 3. Cross at a zebra crossing and walk, do not run.", "1 mark for each correct rule (stop at the edge, look both ways, use a safe crossing, do not run, hold a young child's hand).", points=3), True)
d1 = add(LM, N("application", "A map has the scale 1 cm to 20 km. Two towns are 4.5 cm apart. How far apart are they in km?", 90, "4.5 × 20 = 90 km.", unit="km", points=2), True)
d2 = add(LM, M("application", "On which continent is Cameroon?", "Africa", ["Asia", "Europe", "Oceania"], "Cameroon is in Central Africa."), True)
d3 = add(LM, M("application", "In a grid reference we write...", "the letter first, then the number", ["the number first, then the letter", "only letters", "only numbers"], "For example B2."), True)
p.mock("1", "FSLC mock paper — Social Studies", 60,
       "Answer ALL the questions. Total: 20 marks. Section A: geography (6 marks); Section B: history (5 marks); Section C: civic education (5 marks); Section D: Africa and maps (4 marks). This is an original practice paper: its format is to be checked against the official texts.",
       [("Section A — Geography of Cameroon (6 marks)", a), ("Section B — History (5 marks)", [b]), ("Section C — Civic education (5 marks)", [c1, c2, c3]), ("Section D — Africa and maps (4 marks)", [d1, d2, d3])])
p.write()
