import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _b import *

reset_extension("fslc-science", 4, {"fslc-science-mock-1"})
p = Pack("fslc-science", None, None, None, None, extend=True)
REF = "MINEDUB primary school curriculum (English-speaking subsystem), Level III — Elementary Science and Technology; to be checked against the official texts"
HEALTH = "Health and nutrition content is kept at a basic, conservative level; to be checked by a teacher or a health worker."

# =========================================================== chapter 5: living things
ch = p.chapter("living-things", "Living things: characteristics, plants and animals", REF)
fig_life = grid([("Movement", "move"), ("Respiration", "breathe"), ("Sensitivity", "feel"), ("Growth", "grow"), ("Reproduction", "have young"), ("Excretion", "get rid of waste"), ("Nutrition", "feed")], 4, 92, 62, size=12)
build(ch, "living-nonliving", "Living and non-living things", 25,
    ["List the seven characteristics of living things.", "Sort things into living, non-living and once-living.", "Explain why a car or a river is not a living thing."],
    [("key", "definition", "Living things", "All **living things** do seven things (remember MRS GREN): **M**ove, **R**espire (breathe), be **S**ensitive (feel and react), **G**row, **R**eproduce (have young), **E**xcrete (get rid of waste) and take in **N**utrition (food). Plants, animals and tiny living things like bacteria are all living. Stones, water, plastic and cars are **non-living**."),
     ("fig", fig_life, "The seven characteristics of living things.", "Seven boxes: movement, respiration, sensitivity, growth, reproduction, excretion and nutrition, each with a short explanation."),
     ("key", "retenir", "Once-living things", "Some things are not alive now but **were** alive: dry wood, a dead leaf, a bone, cotton cloth and leather. We call them **once-living** (or dead) things. A thing that is alive must show **all** seven signs, not only one: a car moves but it does not grow, feed or reproduce, so it is non-living."),
     ("key", "pieges", "Common mistakes", "- Saying that a thing is alive because it **moves** (a car, a river, the wind).\n- Saying that plants are not alive because they do not move from place to place: they grow, feed, reproduce and react to light.\n- Forgetting that seeds are alive: they are resting and can grow when they get water and warmth."),
     ("ex", "Example 1", "Sort into living, non-living and once-living: a goat, a stone, a dry leaf.", ["A goat moves, breathes, feeds, grows and has young: living.", "A stone does none of these: non-living.", "A dry leaf came from a plant that was alive: once-living."], "goat: living; stone: non-living; dry leaf: once-living."),
     ("ex", "Example 2", "Why is a motorbike not a living thing?", ["It moves, but only when someone starts it with fuel.", "It does not grow, reproduce, breathe or react like a living thing."], "A motorbike moves, but it does not grow, breathe, feed or reproduce, so it is not alive.")],
    [M("application", "Which of these is a living thing?", "a mango tree", ["a river", "a stone", "a motorbike"], "A mango tree grows, feeds, reproduces and reacts to its surroundings."),
     N("application", "How many characteristics of living things do we study (M R S G R E N)?", 7, "Movement, respiration, sensitivity, growth, reproduction, excretion and nutrition: 7."),
     M("application", "Which one is a once-living thing?", "a dry piece of wood", ["a hen", "a stone", "water"], "Wood comes from a tree that was alive."),
     TF("approfondissement", "A river is alive because it moves.", False, "Moving is only one sign. A river does not grow, feed or reproduce."),
     MA("approfondissement", "Match the characteristic with its meaning.", [("Respiration", "taking in oxygen and giving out carbon dioxide"), ("Excretion", "getting rid of waste"), ("Reproduction", "having young"), ("Sensitivity", "reacting to light, heat or touch")], "These are four of the seven characteristics."),
     P("A pupil put seeds of maize in wet soil near a window. After a week small green shoots appeared and they bent towards the light. Later the plant became taller.",
       [PM("Which characteristic is shown when the plant becomes taller?", "growth", ["excretion", "respiration", "movement from place to place"], "Getting taller is growth."),
        PM("Which characteristic is shown when the shoots bend towards the light?", "sensitivity", ["reproduction", "nutrition", "excretion"], "The plant reacts to light."),
        PM("Is a maize seed a living thing?", "Yes, it is alive but resting", ["No, because it does not move", "No, because it is small", "Only after it has flowers"], "A seed is alive; it grows when it gets water and warmth.", points=2)])],
    [("Which is a non-living thing?", "a stone", ["a goat", "a mushroom", "a mango tree"], "A stone has no signs of life."),
     ("Taking in food is called...", "nutrition", ["excretion", "respiration", "reproduction"], "Nutrition = feeding."),
     ("Getting rid of waste is called...", "excretion", ["growth", "nutrition", "sensitivity"], "Excretion removes waste."),
     ("A dead leaf is...", "once-living", ["living", "non-living only", "a seed"], "It came from a plant that was alive."),
     ("What do all living things do?", "reproduce", ["fly", "swim", "make noise"], "Living things have young of their kind.")],
    ["Whether fire and viruses count as living is not discussed; keep to the classic classification. MRS GREN word list should match the syllabus wording."],
    prereq=[])

# ---- plants
fig_plant = shapes([LINE(20, 150, 380, 150, color="brown", width=3),
                    LINE(200, 150, 200, 60, color="green", width=5),
                    POLY([200, 110, 140, 90, 190, 125], fill="lightgreen"), POLY([200, 90, 262, 70, 210, 105], fill="lightgreen"),
                    CIRCLE(200, 48, 14, fill="pink"),
                    LINE(200, 150, 170, 190, color="brown", width=3), LINE(200, 150, 200, 200, color="brown", width=3), LINE(200, 150, 235, 190, color="brown", width=3),
                    T(230, 40, "flower", 14, bold=True, anchor="start"), T(278, 76, "leaf", 14, bold=True, anchor="start"), T(115, 100, "leaf", 14, bold=True, anchor="end"),
                    T(215, 128, "stem", 14, bold=True, anchor="start"), T(255, 192, "roots", 14, bold=True, anchor="start"), T(30, 142, "ground", 12, anchor="start")], 400, 215)
build(ch, "plants-parts", "Plants: parts and their jobs", 30,
    ["Name the main parts of a flowering plant and say what each part does.", "Explain how a green plant makes its food.", "Give examples of plant parts that we eat."],
    [("key", "definition", "Parts of a plant", "- **Roots**: hold the plant in the soil and take in water and minerals.\n- **Stem**: holds up the plant and carries water and food up and down.\n- **Leaves**: make food for the plant.\n- **Flower**: makes seeds.\n- **Fruit**: grows from the flower and protects the seeds.\n- **Seeds**: can grow into new plants."),
     ("fig", fig_plant, "The parts of a flowering plant.", "A drawing of a plant. Below the ground line are the brown roots. A green stem rises from the ground with two leaves and a pink flower on top. The parts are labelled flower, leaf, stem and roots."),
     ("key", "retenir", "How a plant makes food", "A green plant makes its own food in its leaves. This is called **photosynthesis**. The leaf uses **sunlight**, **water** (from the roots) and **carbon dioxide** (from the air) to make food (sugar), and it gives out **oxygen**. Because plants make food, they are the first link in every food chain: they are **producers**."),
     ("key", "retenir", "Plant parts we eat", "- Roots: cassava, carrot.\n- Stem: sugar cane.\n- Leaves: eru, bitter leaf, cabbage.\n- Fruits: mango, tomato, pawpaw.\n- Seeds: maize, beans, groundnuts, rice.\nA balanced diet uses several of these."),
     ("key", "pieges", "Common mistakes", "- Saying that plants feed on soil. They take **water and minerals** from the soil, but they make their **food** in the leaves.\n- Thinking that photosynthesis happens at night: it needs light.\n- Mixing up the stem (holds the plant) and the roots (take in water)."),
     ("ex", "Example 1", "A plant is kept in a dark cupboard for two weeks. It becomes pale and weak. Explain why.", ["Leaves make food by photosynthesis, and this needs sunlight.", "In the dark the plant cannot make food, so it becomes pale and weak."], "Without sunlight the leaves cannot make food, so the plant becomes pale and weak."),
     ("ex", "Example 2", "Name the part of the plant that we eat in: cassava, eru, maize.", ["Cassava is a thick root.", "Eru is a leaf. Maize grains are seeds."], "cassava: root; eru: leaves; maize: seeds.")],
    [M("application", "Which part of a plant takes in water from the soil?", "roots", ["leaves", "flower", "fruit"], "Roots take in water and minerals."),
     M("application", "Where does a plant make its food?", "in the leaves", ["in the roots", "in the soil", "in the fruit"], "Photosynthesis happens mostly in the green leaves."),
     M("application", "What does a plant give out during photosynthesis?", "oxygen", ["carbon dioxide", "smoke", "nitrogen only"], "Oxygen is released."),
     MA("approfondissement", "Match the plant part with its job.", [("roots", "hold the plant and take in water"), ("stem", "holds up the plant"), ("leaf", "makes food"), ("flower", "makes seeds")], "Each part has its job."),
     TF("approfondissement", "Photosynthesis needs sunlight, water and carbon dioxide.", True, "These three are used by the leaf to make food."),
     P("A pupil planted three beans in pots. Pot A was kept in light and watered. Pot B was in light without water. Pot C was watered but kept in a dark cupboard. After two weeks only plant A was green and healthy.",
       [PM("What does plant B lack?", "water", ["light", "soil", "seeds"], "Plant B was not watered."),
        PM("What does plant C lack?", "light", ["water", "roots", "air"], "It was in the dark."),
        PM("What do we learn from the test?", "a plant needs light and water to grow well", ["a plant needs nothing", "plants only need soil", "light is harmful to beans"], "Only A had both and stayed healthy.", points=2)])],
    [("Which part carries water up the plant?", "stem", ["flower", "fruit", "seed"], "The stem carries water and food."),
     ("Which gas do plants take from the air to make food?", "carbon dioxide", ["oxygen", "nitrogen", "hydrogen"], "Plants use carbon dioxide."),
     ("A green plant is called a producer because it...", "makes its own food", ["eats animals", "gives milk", "makes noise"], "Producers make food."),
     ("A seed grows into...", "a new plant", ["a stone", "a root only", "an animal"], "A seed contains a baby plant."),
     ("Which plant part is the cassava that we eat?", "root", ["stem", "leaf", "flower"], "Cassava is a thick root.")],
    ["Cassava is described as a root (storage root); yam/cocoyam are left out as botanical classification is more complex. Photosynthesis is simplified."],
    prereq=["fslc-science-living-nonliving"])

# ---- animals
fig_anim = grid([("Mammals", "goat, human"), ("Birds", "hen, eagle"), ("Reptiles", "lizard, snake"), ("Amphibians", "frog, toad"), ("Fish", "tilapia, catfish"), ("Invertebrates", "ant, snail")], 3, 115, 62)
build(ch, "animals-habitats", "Animals and their habitats", 30,
    ["Sort animals into vertebrates and invertebrates.", "Name the five groups of vertebrates and one feature of each.", "Say where some animals live (habitats) and what they eat."],
    [("key", "definition", "Vertebrates and invertebrates", "**Vertebrates** have a backbone. **Invertebrates** have no backbone. Vertebrates: **mammals**, **birds**, **reptiles**, **amphibians** and **fish**. Invertebrates include insects, spiders, snails, worms and crabs. Most animals on Earth are invertebrates."),
     ("fig", fig_anim, "Groups of animals with examples.", "Six boxes: mammals (goat, human), birds (hen, eagle), reptiles (lizard, snake), amphibians (frog, toad), fish (tilapia, catfish) and invertebrates (ant, snail)."),
     ("key", "retenir", "The five groups of vertebrates", "- **Mammals**: have hair or fur, give birth to live young and feed them milk (goat, human, bat).\n- **Birds**: have feathers and wings, lay eggs with hard shells (hen, eagle).\n- **Reptiles**: dry scaly skin, most lay eggs (lizard, snake, crocodile).\n- **Amphibians**: moist skin, young live in water and adults on land and in water (frog).\n- **Fish**: live in water, breathe with gills, have fins and scales (tilapia)."),
     ("key", "retenir", "Habitats and feeding", "A **habitat** is the place where an animal lives: forest, savanna, river, sea, soil, a pond. Animals that eat only plants are **herbivores** (goat, cow); animals that eat other animals are **carnivores** (lion, snake); animals that eat both are **omnivores** (human, chicken). An insect has **6 legs** and 3 body parts; a spider has **8 legs**, so a spider is not an insect."),
     ("key", "pieges", "Common mistakes", "- Saying that a bat is a bird because it flies: it has fur and feeds its young with milk, so it is a mammal.\n- Saying that a whale or a dolphin is a fish: they are mammals.\n- Saying that all animals that live in water are fish: a frog is an amphibian."),
     ("ex", "Example 1", "Say which group of animals each belongs to: a frog, a hen, a goat.", ["A frog has moist skin and lays eggs in water: amphibian.", "A hen has feathers and wings: bird.", "A goat has hair and feeds its kids with milk: mammal."], "frog: amphibian; hen: bird; goat: mammal."),
     ("ex", "Example 2", "A creature has 8 legs and no backbone. Is it an insect?", ["Insects have 6 legs. This animal has 8 legs.", "It has no backbone, so it is an invertebrate, but it is not an insect (it is like a spider)."], "No. It is an invertebrate with 8 legs, like a spider.")],
    [M("application", "Which animal is a mammal?", "bat", ["hen", "frog", "tilapia"], "A bat has fur and feeds its young with milk."),
     N("application", "How many legs has an insect?", 6, "An insect has 3 pairs of legs: 6 legs."),
     M("application", "Animals with no backbone are called...", "invertebrates", ["vertebrates", "mammals", "reptiles"], "In = without, vertebra = backbone."),
     MA("approfondissement", "Match the animal with its group.", [("eagle", "bird"), ("crocodile", "reptile"), ("frog", "amphibian"), ("tilapia", "fish")], "Check the body covering and where the animal lives."),
     TF("approfondissement", "A snail is a vertebrate.", False, "A snail has no backbone: it is an invertebrate."),
     P("Mary made a table of four animals. Animal W: feathers, lays eggs. Animal X: hair, gives milk to its young. Animal Y: scales, breathes with gills. Animal Z: 6 legs, no backbone.",
       [PM("Animal W is a...", "bird", ["mammal", "fish", "reptile"], "Feathers and eggs show a bird."),
        PM("Animal X is a...", "mammal", ["bird", "amphibian", "insect"], "Hair and milk show a mammal."),
        PM("Animal Y is a...", "fish", ["reptile", "mammal", "bird"], "Scales and gills show a fish."),
        PM("Animal Z is a...", "insect", ["spider", "fish", "reptile"], "6 legs and no backbone: an insect.", points=2)])],
    [("Which is an amphibian?", "frog", ["lizard", "hen", "goat"], "Amphibians live partly in water and partly on land."),
     ("An animal that eats only plants is a...", "herbivore", ["carnivore", "omnivore", "vertebrate"], "Herbivores eat plants."),
     ("Which animal is an invertebrate?", "snail", ["snake", "tilapia", "goat"], "Snails have no backbone."),
     ("A habitat is...", "the place where an animal lives", ["the food an animal eats", "an animal's baby", "a kind of skin"], "For example a forest or a river."),
     ("A spider has...", "8 legs", ["6 legs", "4 legs", "10 legs"], "Spiders have eight legs.")],
    ["The animals named are common in Cameroon; classifications (bat, whale, spider) are standard textbook facts."],
    prereq=["fslc-science-living-nonliving"])

# =========================================================== chapter 6: senses, teeth and nutrition
ch = p.chapter("senses-nutrition", "The senses, teeth and nutrition", REF)
fig_sen = grid([("Sight", "eyes"), ("Hearing", "ears"), ("Smell", "nose"), ("Taste", "tongue"), ("Touch", "skin")], 5, 70, 62, gap=6, size=12)
build(ch, "senses", "The five senses", 25,
    ["Name the five senses and the organs for each.", "Explain how the senses keep us safe.", "Describe simple ways to protect the eyes and the ears."],
    [("key", "definition", "Senses", "We have **five senses**. **Sight**: we see with our **eyes**. **Hearing**: we hear with our **ears**. **Smell**: we smell with the **nose**. **Taste**: we taste with the **tongue** (sweet, sour, salty, bitter). **Touch**: we feel with the **skin** (hot, cold, soft, rough, pain). **Nerves** carry messages from the sense organs to the brain."),
     ("fig", fig_sen, "The five senses and their organs.", "Five boxes: sight with eyes, hearing with ears, smell with nose, taste with tongue and touch with skin."),
     ("key", "retenir", "Senses keep us safe", "The senses warn us of danger: we see a car, hear a horn, smell smoke, taste food that has gone bad and feel a hot pot. The brain tells our muscles to react. People who cannot see or hear use other senses, and tools such as glasses, white canes or hearing aids help them."),
     ("key", "methode", "Protecting the eyes and ears", "- Never look straight at the sun.\n- Read and write with enough light; sit properly.\n- Do not put objects (sticks, pins) in your eyes or ears.\n- Do not listen to very loud music or stay near very loud noise.\n- Tell a teacher or parent if you cannot see the board or hear well."),
     ("key", "pieges", "Common mistakes", "- Thinking that the tongue only tastes: the **nose** helps us taste (when we have a cold, food has less taste).\n- Thinking that touch is only in the hands: the **skin** covers the whole body.\n- Tasting an unknown substance to find out what it is: this can be dangerous."),
     ("ex", "Example 1", "Which sense do we use to know that a pot is hot? Which organ?", ["We feel heat and pain.", "That is the sense of touch and the organ is the skin."], "Touch; the skin."),
     ("ex", "Example 2", "You smell smoke at night. Which sense warns you, and what should you do?", ["The nose (smell) detects the smoke.", "Wake others, leave the house calmly and call for help."], "The sense of smell; you should warn others and leave the house at once.")],
    [M("application", "Which organ do we use to hear?", "ear", ["eye", "nose", "skin"], "Ears are the organs of hearing."),
     M("application", "Which sense do we use to tell that a mango is sweet?", "taste", ["touch", "hearing", "sight"], "The tongue tastes sweet, sour, salty and bitter."),
     N("application", "How many senses do human beings have (in this lesson)?", 5, "Sight, hearing, smell, taste and touch."),
     MA("approfondissement", "Match the sense organ with what it detects.", [("eyes", "light and colours"), ("ears", "sounds"), ("tongue", "sweet and sour tastes"), ("skin", "heat and pain")], "Each organ detects different things."),
     TF("approfondissement", "It is safe to look straight at the sun for a short time.", False, "Looking at the sun can damage the eyes."),
     P("Neba cannot see the board clearly. She often screws up her eyes, and her head aches after reading.",
       [PM("Which sense organ may have a problem?", "eyes", ["ears", "nose", "tongue"], "She cannot see clearly."),
        PM("What should her mother do?", "take her to a health worker for an eye test", ["tell her to stop going to school", "give her any medicine", "do nothing"], "A health worker can test the eyes and advise glasses."),
        PM("Which is a good habit for protecting the eyes?", "reading with enough light", ["looking at the sun", "rubbing the eyes with dirty hands", "reading in the dark"], "Good light helps the eyes.", points=2)])],
    [("Which sense organ is the skin?", "touch", ["sight", "smell", "taste"], "The skin is the organ of touch."),
     ("We smell with the...", "nose", ["ear", "tongue", "eye"], "The nose is the organ of smell."),
     ("Which is NOT a basic taste?", "loud", ["sweet", "sour", "bitter"], "Loud describes a sound."),
     ("What carries messages from sense organs to the brain?", "nerves", ["bones", "teeth", "hair"], "Nerves carry messages."),
     ("How can we protect our ears?", "avoid very loud noise", ["push sticks inside", "listen to loud music all day", "shout in them"], "Loud noise can harm hearing.")],
    [HEALTH + " The four basic tastes are used (some books add a fifth, umami)."],
    prereq=["fslc-science-human-body"])

fig_food = grid([("Energy", "rice, cassava, plantain"), ("Body-building", "beans, fish, eggs"), ("Protective", "fruits, vegetables"), ("Water + fibre", "water, whole grains")], 2, 170, 62, size=13)
fig_teeth = grid([("Incisors", "cut"), ("Canines", "tear"), ("Premolars", "crush"), ("Molars", "grind")], 4, 92, 62)
build(ch, "teeth-nutrition", "Teeth and a balanced diet", 30,
    ["Name the four kinds of teeth and their jobs.", "Explain how to prevent tooth decay.", "List the food groups and plan a balanced meal."],
    [("key", "definition", "Teeth", "Children first have **20 milk teeth**. They fall out and are replaced by **permanent teeth**; an adult has up to **32**. There are four kinds: **incisors** (at the front, they cut), **canines** (pointed, they tear), **premolars** and **molars** (at the back, they crush and grind food). A tooth has a hard white **enamel** on the outside."),
     ("fig", fig_teeth, "The four kinds of teeth and their jobs.", "Four boxes: incisors cut, canines tear, premolars crush and molars grind."),
     ("key", "methode", "Caring for teeth", "Sugar and bits of food left on the teeth feed bacteria, which make an acid that makes holes in the teeth (**tooth decay**). To keep the teeth healthy: brush them **twice a day** (morning and before bed), eat **less sugar** and sweets, drink water, eat fruits and vegetables, and see a **dentist or health worker** when you have toothache."),
     ("key", "definition", "A balanced diet", "A **balanced diet** has food from every group, in the right amounts. **Energy foods** give energy (rice, cassava, plantain, maize, oil). **Body-building foods** (proteins) help us grow and repair the body (beans, fish, eggs, meat, groundnuts). **Protective foods** (vitamins and minerals) keep us healthy (fruits, vegetables). We also need **water** and **fibre** (vegetables, whole grains)."),
     ("fig", fig_food, "The food groups.", "Four boxes: energy foods (rice, cassava, plantain), body-building foods (beans, fish, eggs), protective foods (fruits, vegetables) and water and fibre."),
     ("key", "pieges", "Common mistakes", "- Thinking that only one food group is enough: a child who eats only rice lacks proteins and vitamins.\n- Brushing teeth only when they hurt.\n- Eating sweets just before bed.\n- Thinking that more expensive food is always better: many cheap local foods (beans, groundnuts, vegetables) are very good."),
     ("ex", "Example 1", "Say which food group each food mostly belongs to: rice, beans, oranges.", ["Rice gives energy (a starchy food).", "Beans help the body to grow: body-building (protein).", "Oranges give vitamins: protective."], "rice: energy; beans: body-building; oranges: protective."),
     ("ex", "Example 2", "Make a balanced meal from: plantain, fish, eru leaves, a banana, water.", ["Plantain gives energy; fish gives protein for growth.", "Eru leaves and the banana give vitamins; water completes the meal."], "Plantain (energy), fish (body-building), eru and a banana (protective), with water.")],
    [M("application", "Which teeth are used to cut food?", "incisors", ["molars", "canines", "premolars"], "Incisors are the sharp flat teeth at the front."),
     N("application", "How many milk teeth does a child have?", 20, "The set of milk teeth has 20 teeth."),
     M("application", "Which food gives energy?", "cassava", ["fish", "oranges", "water"], "Cassava is rich in starch."),
     M("approfondissement", "Which habit helps to prevent tooth decay?", "brushing twice a day", ["eating sweets all day", "never visiting a dentist", "chewing sticks of sugar cane all day"], "Brushing removes food and bacteria."),
     TF("approfondissement", "A balanced diet needs foods from all the food groups.", True, "Each group does a different job for the body."),
     P("Ako's lunch was only a big plate of boiled cassava every day. After some weeks he looked thin and tired.",
       [PM("Which group of food was his lunch mostly?", "energy foods", ["body-building foods", "protective foods", "water"], "Cassava is an energy food."),
        PM("What did his meal lack?", "proteins and vitamins", ["only water", "only salt", "energy"], "He needs beans, fish and fruits or vegetables too."),
        PM("Which addition would improve his meal best?", "beans and vegetables", ["sweets", "more cassava", "a soft drink"], "They give protein and vitamins.", points=2)])],
    [("The teeth at the back that grind food are the...", "molars", ["incisors", "canines", "milk teeth"], "Molars grind."),
     ("The pointed teeth that tear food are the...", "canines", ["molars", "incisors", "premolars"], "Canines are pointed."),
     ("Which food is body-building?", "beans", ["rice", "oil", "water"], "Beans are rich in protein."),
     ("What causes tooth decay?", "sugar and bacteria", ["drinking water", "eating vegetables", "brushing"], "Bacteria turn sugar into an acid."),
     ("A balanced diet has...", "all the food groups", ["only meat", "only sweets", "only rice"], "It has a mix of foods.")],
    [HEALTH + " Number of teeth (20 milk, 32 permanent) is the usual textbook figure.", "Food examples are local, but nutritional claims are simplified."],
    prereq=["fslc-science-human-body"])

# =========================================================== chapter 7: soil, farming, air, water, weather
ch = p.chapter("earth-farming", "Soil, farming, air, water and weather", REF)
fig_soil = grid([("Sandy soil", "big grains"), ("Clay soil", "tiny grains"), ("Loam", "sand + clay + humus")], 3, 115, 62)
build(ch, "soil-farming", "Soil and farming", 30,
    ["Say what soil is made of and name three types of soil.", "Explain why loam is the best soil for most crops.", "Describe good farming practices and how to stop soil erosion."],
    [("key", "definition", "What is soil?", "Soil is made of tiny pieces of broken **rock**, **humus** (decayed plants and animals), **air**, **water** and living things such as worms and bacteria. Plants take water and minerals from the soil. Humus makes the soil dark and rich."),
     ("fig", fig_soil, "Three types of soil.", "Three boxes: sandy soil has big grains, clay soil has tiny grains, and loam is a mixture of sand, clay and humus."),
     ("key", "retenir", "Types of soil", "- **Sandy soil**: big grains, water passes through quickly, it is dry and poor.\n- **Clay soil**: very small grains, sticky when wet, holds a lot of water, water drains slowly.\n- **Loam**: a mixture of sand, clay and humus; it holds enough water and air, so it is **best for most crops**."),
     ("key", "methode", "Good farming", "Farmers **clear** the land, **plant** at the right time, **weed**, protect crops from pests and **harvest**. To keep the soil fertile they add **manure or compost**, use **crop rotation** (growing different crops in turn, for example maize then beans), and cover the soil with leaves (**mulching**). Crops can be **food crops** (maize, cassava, plantain) or **cash crops** (cocoa, coffee, cotton, bananas for export)."),
     ("key", "pieges", "Soil erosion", "**Erosion** is when rain and wind carry the good topsoil away. It happens when trees and grass are cut or burned and the soil is left bare, especially on slopes. To stop it: plant trees and grass, make ridges across the slope, use mulch, and avoid bush burning."),
     ("ex", "Example 1", "A farmer's soil is sandy and dries quickly. Give two ways to improve it.", ["Add compost or manure: humus holds water.", "Cover the soil with mulch to reduce drying."], "Add compost or manure and use mulch."),
     ("ex", "Example 2", "Why do farmers grow maize and beans in turn on the same field?", ["Beans add nutrients to the soil, and maize uses them.", "This keeps the soil fertile and reduces some pests and diseases."], "Crop rotation keeps the soil fertile and reduces pests.")],
    [M("application", "Which soil is best for most crops?", "loam", ["sandy soil", "clay soil", "rock"], "Loam holds water and air and has humus."),
     M("application", "Humus is made from...", "decayed plants and animals", ["broken rocks only", "plastic", "sand"], "Humus comes from dead plants and animals."),
     M("application", "Which is a cash crop?", "cocoa", ["cassava", "plantain", "beans"], "Cocoa is grown mainly to be sold (export)."),
     MA("approfondissement", "Match the soil with its feature.", [("sandy soil", "water drains very fast"), ("clay soil", "sticky and holds water"), ("loam", "best for crops"), ("humus", "decayed plants and animals")], "These are the main features."),
     TF("approfondissement", "Burning the bush leaves the soil bare and helps erosion.", True, "Bare soil is easily washed away by rain."),
     P("On a hill a farmer cuts all the trees and plants maize in straight rows going down the slope. After heavy rain, the topsoil is washed away and the maize is weak.",
       [PM("What is the problem?", "soil erosion", ["pollution of air", "too much humus", "drought"], "Rain carried the topsoil away."),
        PM("Which action would help most?", "plant ridges across the slope and trees", ["cut more trees", "burn the field", "plant in straight rows down the slope"], "Ridges and trees slow the water."),
        PM("Which soil holds water best?", "clay soil", ["sandy soil", "stones", "dry sand"], "Clay holds water; but loam is the best overall.", points=2)])],
    [("Which soil has the biggest grains?", "sandy soil", ["clay soil", "loam", "humus"], "Sand grains are big."),
     ("A farmer grows maize, then beans, then maize. This is...", "crop rotation", ["erosion", "mulching", "harvesting"], "Different crops in turn."),
     ("Soil erosion happens when...", "rain washes the topsoil away", ["plants grow tall", "the soil is rich", "farmers plant trees"], "Bare soil is carried away."),
     ("Compost is made from...", "rotting plant waste", ["plastic bags", "stones", "metal"], "Plant waste decays into compost."),
     ("Which is a food crop?", "cassava", ["cocoa", "coffee", "cotton"], "Cassava is grown mainly to be eaten.")],
    ["Crop classification (food/cash) is simplified: some crops (banana, maize) are both."],
    prereq=["fslc-science-living-environment"])

assert 12 + 0 + 8 + 20 == 40 and 40 / 4 == 10
fig_wx = grid([("Thermometer", "temperature °C"), ("Rain gauge", "rainfall in mm"), ("Wind vane", "wind direction")], 3, 115, 62, size=12)
build(ch, "air-water-weather", "Air, water and weather", 30,
    ["Describe air as a mixture of gases and say what it is used for.", "Name the instruments used to measure weather.", "Read a simple weather record and describe the seasons."],
    [("key", "definition", "Air", "**Air** is all around us. It is a **mixture of gases**: about four-fifths **nitrogen** and about one-fifth **oxygen**, with small amounts of carbon dioxide and water vapour. We need oxygen to breathe and fires need it to burn. Air takes up space and moving air is **wind**. Air is not visible, but we can feel wind and see a balloon grow when we blow into it."),
     ("key", "retenir", "Water", "Water is used for drinking, cooking, washing and farming. Water exists as ice (solid), liquid water and water vapour (gas). To make water **safe to drink**, boil it, filter it, or treat it as advised by a health worker. Do not drink water from dirty ponds or streams without treating it."),
     ("fig", fig_wx, "Weather instruments.", "Three boxes: the thermometer measures temperature in degrees Celsius, the rain gauge measures rainfall in millimetres and the wind vane shows the wind direction."),
     ("key", "retenir", "Weather and seasons", "**Weather** is the state of the air at a place and time: temperature, rainfall, wind, clouds and sunshine. **Climate** is the usual weather over many years. Most of Cameroon has a **dry season** and a **rainy season**, but the length and the details differ from region to region (for example, the north is drier than the south)."),
     ("key", "pieges", "Common mistakes", "- Saying that air is empty: it is a mixture of gases.\n- Confusing **weather** (today) with **climate** (the usual pattern).\n- Reading a thermometer from the wrong end of the liquid: read where the top of the liquid is.\n- Saying that boiled water is not needed if the water looks clear: clear water can still carry germs."),
     ("ex", "Example 1", "In four days the rain gauge shows 12 mm, 0 mm, 8 mm and 20 mm. Find the total and the mean rainfall per day.", ["Total: 12 + 0 + 8 + 20 = 40 mm.", "Mean: 40 ÷ 4 = 10 mm per day."], "40 mm in all; the mean is 10 mm a day."),
     ("ex", "Example 2", "Which instrument would you use to find which way the wind blows?", ["The thermometer measures temperature and the rain gauge rainfall.", "The wind vane turns to show the direction of the wind."], "A wind vane.")],
    [M("application", "Which gas in the air do we need to breathe?", "oxygen", ["nitrogen", "carbon dioxide", "smoke"], "We breathe in oxygen."),
     M("application", "Which instrument measures temperature?", "thermometer", ["rain gauge", "wind vane", "ruler"], "A thermometer shows temperature in °C."),
     N("application", "A rain gauge shows 12 mm, 0 mm, 8 mm and 20 mm on four days. What is the total rainfall in mm?", 40, "12 + 0 + 8 + 20 = 40 mm."),
     TF("approfondissement", "Air is a mixture of gases.", True, "Nitrogen, oxygen and small amounts of other gases."),
     M("approfondissement", "How can we make drinking water safer at home?", "boil it", ["add sand and drink it", "leave it in the sun for a minute", "stir it with a stick"], "Boiling kills germs."),
     P("Weather record for one week in a town: Monday 28 °C sunny; Tuesday 27 °C cloudy; Wednesday 24 °C rain 15 mm; Thursday 25 °C rain 5 mm; Friday 29 °C sunny.",
       [PN("What was the total rainfall in the week (mm)?", 20, "15 + 5 = 20 mm.", unit="mm"),
        PM("Which day was the hottest?", "Friday", ["Monday", "Wednesday", "Thursday"], "29 °C is the highest temperature."),
        PM("Which instrument measured the rainfall?", "rain gauge", ["thermometer", "wind vane", "compass"], "A rain gauge measures rain.", points=2)])],
    [("About how much of the air is oxygen?", "one-fifth", ["one-half", "nine-tenths", "none"], "Oxygen is about 21%."),
     ("Wind is...", "moving air", ["still air", "water vapour only", "clouds"], "Air in motion."),
     ("Which instrument shows the wind direction?", "wind vane", ["thermometer", "rain gauge", "clock"], "It points into the wind."),
     ("The usual weather of a place over many years is its...", "climate", ["wind", "season", "rainfall record for one day"], "Climate is the long-term pattern."),
     ("Rainfall is measured in...", "millimetres", ["degrees", "kilograms", "seconds"], "mm of rain collected.")],
    ["Air composition given as 'about 4/5 nitrogen, 1/5 oxygen' (standard approximation). Seasons of Cameroon are stated in a very general way; regional differences exist. Water treatment advice is general and should be reviewed by a health worker.", "The water cycle is in the existing 'Matter and energy' lesson."],
    prereq=["fslc-science-matter-energy"])

# =========================================================== chapter 8: light, heat, sound, forces, electricity
ch = p.chapter("energy-forces", "Light, heat, sound, magnets, forces and electricity", REF)
fig_light = shapes([CIRCLE(50, 105, 22, fill="yellow"), T(50, 150, "lamp", 13, bold=True),
                    LINE(75, 95, 175, 85, arrow="end", color="orange"), LINE(75, 105, 175, 105, arrow="end", color="orange"), LINE(75, 115, 175, 125, arrow="end", color="orange"),
                    RECT(180, 70, 22, 70, fill="grey"), T(190, 160, "object", 13, bold=True),
                    RECT(260, 70, 90, 70, fill="lightgrey"), T(305, 160, "shadow", 13, bold=True),
                    T(200, 35, "Light travels in straight lines", 14, bold=True)], 400, 190)
build(ch, "light-heat-sound", "Light, heat and sound", 35,
    ["Explain why shadows form and tell transparent, translucent and opaque materials apart.", "Describe how heat moves and name good conductors and insulators of heat.", "Explain that sound is made by vibrations and travels through materials."],
    [("key", "definition", "Light", "We see things when light from a **source** (the sun, a lamp, a fire) or **reflected** by an object (like the moon) enters our eyes. **Light travels in straight lines.** **Transparent** materials let light through (clear glass, clean water). **Translucent** ones let some light through (frosted glass, tissue paper). **Opaque** ones block light (wood, metal). A **shadow** forms when an opaque object blocks light."),
     ("fig", fig_light, "A shadow forms behind an opaque object.", "A lamp on the left sends three rays to the right. A grey object blocks the rays. Behind it there is a grey shadow."),
     ("key", "definition", "Heat", "**Heat** moves from a **hotter** place to a **colder** one. In **solids** (metals) it moves by conduction: a metal spoon in hot tea becomes hot. In **liquids and air** hot parts rise (convection). The **sun's heat** reaches us across space (radiation). **Conductors** (metals) let heat pass easily; **insulators** (wood, plastic, cloth) do not. Temperature is measured with a thermometer in **degrees Celsius (°C)**."),
     ("key", "definition", "Sound", "**Sound** is made when things **vibrate** (move quickly to and fro): a drum skin, a guitar string, our vocal cords. Sound travels through air, water and solids, but **not through empty space**. A **high pitch** comes from fast vibrations, a **loud** sound from big vibrations. An **echo** is sound that bounces off a hard surface. Light travels much faster than sound, so we see lightning before we hear thunder."),
     ("key", "pieges", "Common mistakes", "- Saying that a metal pot handle is made of metal because it is a good **insulator**: metal is a conductor, so handles are made of wood or plastic.\n- Saying that the moon is a source of light: it **reflects** the sun's light.\n- Saying that sound needs no material to travel through.\n- Looking at the sun directly or with sunglasses only: it can damage the eyes."),
     ("ex", "Example 1", "Why do cooking pots have handles of wood or plastic?", ["The metal of the pot is a good conductor, so the heat travels to the handle.", "Wood and plastic are insulators, so the handle stays cool and we can hold it."], "Because wood and plastic are insulators: they do not let the heat pass, so the handle stays cool."),
     ("ex", "Example 2", "You see lightning and hear thunder a few seconds later. Why?", ["Light travels much faster than sound.", "The light reaches us almost at once; the sound takes longer."], "Light travels faster than sound.")],
    [M("application", "Which material is opaque?", "wood", ["clear glass", "clean water", "clear plastic"], "Opaque materials block light."),
     M("application", "Sound is made when something...", "vibrates", ["is cold", "is still", "is transparent"], "Vibrations make sound."),
     M("application", "Which is a good conductor of heat?", "a metal spoon", ["a wooden spoon", "a plastic cup", "a cloth"], "Metals conduct heat well."),
     TF("approfondissement", "Sound can travel through water.", True, "Sound travels through solids, liquids and gases."),
     MA("approfondissement", "Match the word with its meaning.", [("transparent", "lets light pass through"), ("opaque", "blocks light"), ("conductor", "lets heat pass easily"), ("echo", "sound that bounces back")], "These are the key words."),
     P("Mary holds a metal spoon in a pot of hot soup. After a minute the end she is holding is hot. She changes to a wooden spoon and her hand stays cool.",
       [PM("Why did the metal spoon become hot?", "metal is a good conductor of heat", ["metal is an insulator", "metal is transparent", "the spoon was shiny"], "Heat moves along metal."),
        PM("Why did the wooden spoon stay cool?", "wood is a poor conductor (an insulator)", ["wood is opaque", "wood makes sound", "wood is a liquid"], "Wood does not let heat pass easily."),
        PM("How does heat move along the spoon?", "from the hot end to the cold end", ["from the cold end to the hot end", "it does not move", "only upwards in air"], "Heat flows from hot to cold.", points=2)])],
    [("A shadow is formed when light is blocked by an...", "opaque object", ["transparent object", "clear glass", "mirror only"], "Opaque things block light."),
     ("Which travels fastest?", "light", ["sound", "a bicycle", "wind"], "Light is much faster than sound."),
     ("Heat moves from...", "hot to cold", ["cold to hot", "nowhere", "up only"], "From the hotter place to the colder place."),
     ("Which material is an insulator of heat?", "plastic", ["copper", "iron", "aluminium"], "Plastic is a poor conductor."),
     ("Sound cannot travel through...", "empty space", ["water", "air", "wood"], "It needs a material.")],
    ["Standard textbook facts only; temperature of boiling/freezing and speeds of light and sound are deliberately left out."],
    prereq=["fslc-science-matter-energy"])

fig_lever = shapes([LINE(60, 120, 340, 150, width=5), POLY([200, 135, 180, 175, 220, 175], fill="lightyellow"),
                    RECT(70, 85, 40, 35, fill="lightblue"), T(90, 70, "load", 14, bold=True),
                    LINE(320, 60, 320, 140, arrow="end", color="red", width=3), T(320, 40, "effort (push down)", 13, bold=True, color="red"),
                    T(200, 195, "pivot", 14, bold=True)], 400, 215)
build(ch, "magnets-forces-machines", "Magnets, forces and simple machines", 35,
    ["Say which materials a magnet attracts and what poles do.", "Describe push and pull forces, friction and gravity.", "Name simple machines and say how they make work easier."],
    [("key", "definition", "Magnets", "A **magnet** attracts objects made of **iron** and **steel** (they are called **magnetic**). It does not attract wood, plastic, glass or most other metals such as copper and aluminium. A magnet has two **poles**, **north** and **south**. **Unlike poles attract** (north and south). **Like poles repel** (north and north push apart)."),
     ("key", "definition", "Forces", "A **force** is a push or a pull. A force can start or stop an object, make it go faster or slower, change its direction or change its shape. **Gravity** pulls everything towards the centre of the Earth: it makes things fall and gives them **weight**. **Friction** is a force that slows moving things when two surfaces rub. It is useful for brakes and for walking, but it wears machines, so oil is used to reduce it."),
     ("fig", fig_lever, "A lever: a small effort on one side lifts a load on the other.", "A long bar rests on a triangle called the pivot. A blue load sits on the left end. A red arrow pushes down on the right end."),
     ("key", "retenir", "Simple machines", "A **simple machine** makes work easier (less effort, or a better direction). Examples: **lever** (see-saw, scissors, wheelbarrow, crowbar), **pulley** (raising water from a well, a flag), **inclined plane** (a ramp or a sloping road), **wheel and axle** (bicycle, cart), **wedge** (axe, knife) and **screw** (a bottle top, a jack)."),
     ("key", "pieges", "Common mistakes", "- Saying that a magnet attracts all metals. Only some metals (iron, steel) are magnetic.\n- Saying that like poles attract.\n- Believing that a machine **creates** energy: it only makes the work easier.\n- Mixing up weight (a force, from gravity) and mass (how much matter)."),
     ("ex", "Example 1", "A magnet is held near a nail, a coin made of copper, and a plastic ruler. Which will it attract?", ["The nail is made of iron (or steel): magnetic.", "Copper and plastic are not magnetic."], "Only the iron nail."),
     ("ex", "Example 2", "Why is it easier to push a heavy barrel up a ramp than to lift it?", ["A ramp is an inclined plane: it spreads the work over a longer distance.", "We need a smaller force, but we must push over a longer distance."], "A ramp (inclined plane) needs a smaller force, but over a longer distance.")],
    [M("application", "Which object will a magnet attract?", "an iron nail", ["a plastic ruler", "a wooden pencil", "a glass marble"], "Iron is magnetic."),
     M("application", "What happens when two north poles are brought together?", "they repel", ["they attract", "nothing happens", "they stick forever"], "Like poles repel."),
     M("application", "Which is a lever?", "a see-saw", ["a window", "a stone", "a rope only"], "A see-saw turns on a pivot."),
     TF("approfondissement", "Friction is a force that slows moving objects.", True, "Rubbing surfaces slow motion."),
     MA("approfondissement", "Match the machine with an example.", [("lever", "scissors"), ("inclined plane", "a ramp"), ("wheel and axle", "a bicycle wheel"), ("pulley", "raising a flag")], "Each is a simple machine."),
     P("A farmer wants to load heavy sacks of cocoa onto a truck. A boy suggests using a long wooden plank as a ramp.",
       [PM("What simple machine is the plank?", "inclined plane", ["pulley", "wedge", "lever"], "A sloping surface is an inclined plane."),
        PM("What is the advantage?", "less effort is needed", ["no effort is needed", "the sacks become lighter", "the truck gets bigger"], "A ramp reduces the force needed."),
        PM("Which force makes the sacks slide down the plank when released?", "gravity", ["magnetism", "friction only", "wind"], "Gravity pulls the sacks down.", points=2)])],
    [("A magnet has...", "two poles", ["one pole", "three poles", "no pole"], "North and south."),
     ("The force that pulls things to the ground is...", "gravity", ["friction", "magnetism", "wind"], "Gravity pulls towards the Earth."),
     ("Oil helps machines because it reduces...", "friction", ["gravity", "weight", "magnetism"], "Oil makes surfaces slide."),
     ("Which of these is NOT magnetic?", "copper", ["iron", "steel", "an iron nail"], "Copper is not attracted by a magnet."),
     ("A force is a...", "push or pull", ["colour", "sound", "kind of metal"], "That is the definition.")],
    ["Weight vs mass is only mentioned; unit of force (newton) is not covered. Check whether gravity/friction are in the Class 6 syllabus."],
    prereq=["fslc-science-matter-energy"])

fig_circ = shapes([LINE(80, 70, 320, 70, width=3), LINE(320, 70, 320, 170, width=3), LINE(320, 170, 80, 170, width=3), LINE(80, 170, 80, 70, width=3),
                   RECT(70, 100, 20, 40, fill="lightyellow"), T(110, 120, "cell", 14, bold=True, anchor="start"),
                   CIRCLE(200, 70, 22, fill="yellow"), T(200, 40, "bulb", 14, bold=True),
                   RECT(190, 160, 20, 20, fill="lightgrey"), T(200, 205, "switch", 14, bold=True)], 400, 225)
build(ch, "electricity-safety", "Electricity and electrical safety", 30,
    ["Describe a simple electric circuit and what a switch does.", "Tell conductors from insulators of electricity.", "Follow the safety rules for electricity."],
    [("key", "definition", "A simple circuit", "A **circuit** is a closed path for electricity. A simple circuit has a **cell** (or battery) that pushes the electricity, **wires** and a **bulb**. A **switch** opens or closes the path: when the switch is **closed** the bulb lights; when it is **open** the circuit is broken and the bulb goes out."),
     ("fig", fig_circ, "A simple circuit with a cell, a bulb and a switch.", "A rectangle of wire. On the left side there is a cell. At the top is a bulb. At the bottom is a switch."),
     ("key", "definition", "Conductors and insulators", "**Conductors** let electricity pass: copper, iron, aluminium and other metals. **Insulators** do not: plastic, rubber, dry wood, glass and cloth. Wires are made of metal (conductor) covered with plastic (insulator). **Water that is not pure** and the **human body** also conduct electricity, so they are dangerous near electricity."),
     ("key", "methode", "Safety rules", "- Never touch bare wires, sockets or switches with **wet hands**.\n- Never put fingers, pins or metal into a socket.\n- Do not play with electric wires, and **stay away from fallen power lines**: tell an adult at once.\n- Do not fly kites near power lines or climb electricity poles.\n- Do not plug too many things into one socket.\n- Let an adult unplug broken equipment. During a storm, stay inside and do not shelter under a tall tree."),
     ("key", "pieges", "Common mistakes", "- Thinking a bulb lights with only one wire connected: the circuit must be a **complete loop**.\n- Using a pin or knife to take out a plug.\n- Saying that all metals are magnetic or that all materials conduct: plastic and rubber are insulators.\n- Using a damaged cable because it 'still works'."),
     ("ex", "Example 1", "A bulb does not light in a circuit with a cell, wires and a switch. Give two possible reasons.", ["The switch is open, so the circuit is not complete.", "A wire is loose or broken, or the cell is flat."], "The switch may be open, or a wire may be loose or the cell flat."),
     ("ex", "Example 2", "Why are electric wires covered with plastic?", ["The wire inside is metal and carries the electricity.", "Plastic is an insulator, so it protects us from the electricity."], "Plastic is an insulator, so it protects us from shock.")],
    [M("application", "Which material is an electrical insulator?", "rubber", ["copper", "iron", "aluminium"], "Rubber does not let electricity pass."),
     M("application", "What does a closed switch do?", "completes the circuit so the bulb lights", ["breaks the circuit", "turns off the cell", "makes the wire insulating"], "The path is complete."),
     M("application", "Which action is SAFE?", "unplug a device with dry hands only after an adult has switched off", ["touch a fallen wire", "put a pin in a socket", "fly a kite near power lines"], "Dry hands and adult supervision are safe."),
     TF("approfondissement", "Water is a good insulator, so it is safe to touch a switch with wet hands.", False, "Water with impurities conducts electricity: wet hands near electricity are dangerous."),
     MA("approfondissement", "Match each item with its job.", [("copper wire", "carries electricity"), ("plastic cover", "protects us from shock"), ("cell", "pushes the electricity round"), ("switch", "opens and closes the circuit")], "Each part of a circuit has its own job."),
     P("Ngu sees a broken electric wire lying on the road after a storm. A small child is walking toward it.",
       [PM("What should Ngu do first?", "warn the child to stay away and call an adult", ["pick up the wire with a stick", "touch it to see if it is live", "ignore it"], "Stay away and get help."),
        PM("Why is the wire dangerous?", "it can carry electricity that gives a shock", ["it is heavy", "it makes noise", "it is wet only"], "Electricity can seriously hurt people."),
        PM("Who should repair it?", "the electricity company technicians", ["any child", "a neighbour with a knife", "nobody"], "Only trained people.", points=2)])],
    [("A bulb lights when the circuit is...", "complete", ["broken", "open", "cold"], "A closed path lets electricity flow."),
     ("Which is a good conductor of electricity?", "copper", ["rubber", "plastic", "dry wood"], "Copper is a metal."),
     ("Which should we NEVER do?", "touch a socket with wet hands", ["switch off before cleaning", "ask an adult for help", "keep water away"], "Wet hands are dangerous."),
     ("The part that opens and closes a circuit is the...", "switch", ["cell", "bulb", "plastic"], "The switch controls the path."),
     ("Wires are covered with plastic because plastic is...", "an insulator", ["a conductor", "magnetic", "heavy"], "It protects us.")],
    ["The existing 'Matter and energy' lesson also covers simple circuits; this lesson stresses conductors, insulators and safety. Safety rules are generic and should be reviewed by a qualified person (e.g. an electrician or teacher)."],
    prereq=["fslc-science-matter-energy"])

# =========================================================== chapter 9: materials, environment
ch = p.chapter("materials-environment", "Materials, environment and waste", REF)
fig_mat = grid([("Wood", "hard, burns"), ("Metal", "conducts heat"), ("Plastic", "waterproof"), ("Glass", "transparent"), ("Cloth", "soft, flexible"), ("Rubber", "stretches")], 3, 115, 62)
build(ch, "materials-properties", "Materials and their properties", 30,
    ["Name common materials and their properties.", "Choose a suitable material for a job and give the reason.", "Tell natural from man-made materials and reversible from irreversible changes."],
    [("key", "definition", "Materials", "Everything is made of **materials**. **Natural** materials come from plants, animals or the earth: wood, cotton, wool, leather, clay, stone. **Man-made** materials are made by people: plastic, glass, nylon, cement. Every material has **properties**: hard or soft, rigid or flexible, strong or weak, rough or smooth, waterproof or absorbent, transparent or opaque, conductor or insulator, magnetic or not."),
     ("fig", fig_mat, "Common materials and one property of each.", "Six boxes: wood is hard and burns, metal conducts heat, plastic is waterproof, glass is transparent, cloth is soft and flexible and rubber stretches."),
     ("key", "methode", "Choosing a material", "Ask: what must the object **do**? Then pick the material with the right property. An umbrella needs a **waterproof** cover. A window needs **transparent** glass. A cooking pot needs a **conductor** of heat (metal), but its handle needs an **insulator** (wood or plastic). A towel needs an **absorbent** cloth."),
     ("key", "retenir", "Changes in materials", "In a **reversible** change the material can come back: ice melts to water and water freezes to ice. In an **irreversible** change a **new** material is made and we cannot go back: burning wood, cooking an egg, rusting iron, baking a cake. Heating, cooling and mixing can all cause changes."),
     ("key", "pieges", "Common mistakes", "- Giving a reason that does not match the job (a window made of wood because wood is strong, when we need to see through it).\n- Thinking that all plastics are the same: they differ in strength and flexibility.\n- Saying that melting wax is irreversible: it can go solid again when it cools, so it is reversible."),
     ("ex", "Example 1", "Which material is best for the handle of a kettle: metal, wood or glass? Give a reason.", ["The kettle becomes very hot.", "The handle must not let the heat pass, so we need an insulator.", "Wood (or plastic) is an insulator; metal is a conductor."], "Wood (or plastic), because it is an insulator and stays cool."),
     ("ex", "Example 2", "Say whether each change is reversible or irreversible: (a) ice melting, (b) wood burning.", ["(a) Water can freeze again into ice: reversible.", "(b) Burning wood makes ash and smoke, new materials: irreversible."], "(a) reversible; (b) irreversible.")],
    [M("application", "Which material is waterproof?", "plastic", ["paper", "cotton cloth", "a sponge"], "Plastic does not let water through."),
     M("application", "Which is a natural material?", "cotton", ["plastic", "nylon", "cement"], "Cotton comes from a plant."),
     M("application", "Which property makes glass suitable for windows?", "transparent", ["opaque", "rough", "magnetic"], "We can see through transparent glass."),
     TF("approfondissement", "Burning wood is a reversible change.", False, "Burning makes ash and smoke: new materials that cannot be turned back."),
     MA("approfondissement", "Match the object with the best material.", [("raincoat", "waterproof plastic"), ("window", "clear glass"), ("saucepan", "metal"), ("towel", "absorbent cotton")], "Choose according to the property needed."),
     P("A school needs to make a cover for a notice board that stands outside. The cover must let people read the notice, keep rain out and be strong.",
       [PM("Which property is needed so that people can read the notice?", "transparent", ["opaque", "flexible", "magnetic"], "They must see through the cover."),
        PM("Which property keeps the rain out?", "waterproof", ["absorbent", "soft", "heavy"], "It must not let water through."),
        PM("Which material is the best choice?", "clear plastic or glass", ["cardboard", "cloth", "wood"], "It is transparent and waterproof.", points=2)])],
    [("Which material is flexible?", "rubber", ["stone", "glass", "iron"], "Rubber bends and stretches."),
     ("Which material conducts heat well?", "metal", ["wood", "plastic", "wool"], "Metals are conductors."),
     ("Ice melting is...", "reversible", ["irreversible", "burning", "rusting"], "Water can freeze again."),
     ("Which is a man-made material?", "plastic", ["wool", "wood", "stone"], "Plastic is made in factories."),
     ("An absorbent material...", "soaks up water", ["keeps water out", "is transparent", "is hard"], "A sponge is absorbent.")],
    ["Rusting and egg cooking are given as irreversible changes (standard examples). Floating/sinking and density are intentionally left out."],
    prereq=["fslc-science-matter-energy"])

fig_3r = shapes([RECT(20, 40, 100, 60, fill="lightblue", radius=6), T(70, 76, "Reduce", 16, bold=True),
                 RECT(150, 40, 100, 60, fill="lightyellow", radius=6), T(200, 76, "Reuse", 16, bold=True),
                 RECT(280, 40, 100, 60, fill="lightgreen", radius=6), T(330, 76, "Recycle", 16, bold=True),
                 LINE(122, 70, 148, 70, arrow="end"), LINE(252, 70, 278, 70, arrow="end"),
                 T(200, 140, "Buy less. Use again. Make into new things.", 13)], 400, 170)
build(ch, "environment-waste", "Protecting the environment: pollution and waste", 30,
    ["Name the kinds of pollution and give their causes and effects.", "Use the three Rs: reduce, reuse and recycle.", "Say how to manage waste and protect trees, water and soil."],
    [("key", "definition", "Pollution", "**Pollution** is adding harmful things to the air, water or soil. **Air pollution**: smoke from burning rubbish, old vehicles and factories. **Water pollution**: rubbish, oil, soap or chemicals in rivers and streams. **Soil pollution**: dumped waste, plastic and chemicals. **Noise pollution**: very loud sounds. Pollution harms people (coughs, stomach illnesses), animals and plants."),
     ("fig", fig_3r, "The three Rs: reduce, reuse, recycle.", "Three boxes joined by arrows: Reduce, Reuse and Recycle. A line of text says buy less, use again, make into new things."),
     ("key", "methode", "Managing waste", "**Biodegradable** waste rots and goes back to the soil (food scraps, leaves, paper, banana peel). Put it in a compost heap. **Non-biodegradable** waste does not rot easily (plastic bags, bottles, tins). **Reduce** what you throw away, **reuse** bottles and bags, **recycle** where possible. Put rubbish in bins and never in drains or rivers: blocked drains cause floods and breed mosquitoes."),
     ("key", "retenir", "Protecting nature", "Plant trees: they give shade, food and oxygen, hold the soil and give homes to animals. **Deforestation** (cutting trees without planting) causes erosion and destroys habitats. Save water: close the tap, collect rain, do not waste. Keep rivers and the school compound clean. Washing hands after handling rubbish keeps us healthy."),
     ("key", "pieges", "Common mistakes", "- Burning plastic: it makes poisonous smoke.\n- Throwing rubbish into drains or streams, thinking that the rain will carry it away.\n- Thinking that one person cannot help: a clean school compound begins with each pupil.\n- Mixing biodegradable and non-biodegradable waste in one heap."),
     ("ex", "Example 1", "Sort into biodegradable and non-biodegradable: banana peel, plastic bag, dry leaves, tin.", ["Banana peel and dry leaves rot in the soil: biodegradable.", "A plastic bag and a tin do not rot easily: non-biodegradable."], "Biodegradable: banana peel, dry leaves. Non-biodegradable: plastic bag, tin."),
     ("ex", "Example 2", "A school wants to reduce its waste. Give three ideas using the three Rs.", ["Reduce: use both sides of the paper.", "Reuse: refill water bottles and use cloth bags.", "Recycle: make compost from leaves and food scraps."], "Use both sides of paper (reduce), refill bottles (reuse) and compost leaves (recycle).")],
    [M("application", "Which waste is biodegradable?", "banana peel", ["plastic bag", "glass bottle", "tin can"], "It rots and goes back to the soil."),
     M("application", "What does 'reuse' mean?", "use something again", ["throw away", "buy more", "burn"], "Reuse = use again."),
     M("application", "Which causes air pollution?", "burning rubbish", ["planting trees", "washing clothes", "composting"], "Smoke pollutes the air."),
     TF("approfondissement", "Throwing rubbish into drains can cause floods.", True, "Blocked drains cannot carry rainwater away."),
     MA("approfondissement", "Match the problem with a good solution.", [("too much plastic waste", "reuse bags and bottles"), ("cut trees", "plant new trees"), ("dirty river", "do not throw rubbish in it"), ("food scraps", "make compost")], "Each solution tackles its problem."),
     P("The compound of a school is covered with plastic bags and food scraps. Pupils want to clean it and keep it clean.",
       [PM("What should they do with food scraps and leaves?", "make compost", ["burn them with plastic", "throw them in the stream", "leave them"], "Compost returns nutrients to the soil."),
        PM("What should they do with the plastic bags?", "collect them in bins and reuse or recycle them", ["burn them in the open", "bury them near the well", "throw them in the drain"], "Burning gives poisonous smoke."),
        PM("Which pupil habit helps most?", "everyone using the bins every day", ["leaving the cleaning to the teacher", "burning everything", "throwing rubbish on the road"], "Clean habits start with each pupil.", points=2)])],
    [("The three Rs are reduce, reuse and...", "recycle", ["remove", "repeat", "return"], "Recycle means making old things into new ones."),
     ("Which is non-biodegradable?", "plastic bottle", ["dry leaves", "banana peel", "paper"], "Plastic does not rot easily."),
     ("Trees help the environment by...", "holding the soil and giving oxygen", ["causing erosion", "making smoke", "polluting the air"], "Trees are very useful."),
     ("Deforestation means...", "cutting down forests", ["planting trees", "cleaning rivers", "making compost"], "Cutting without replanting harms the environment."),
     ("Rubbish should be put...", "in a bin", ["in a river", "in a drain", "in the road"], "Bins keep places clean.")],
    ["Statements that plastic 'does not rot easily' are kept general. Local rules on waste (burning, sorting) differ; to be checked by the school or a health worker."],
    prereq=["fslc-science-living-environment"])

# =========================================================== second mock paper (20 marks)
LM = ch.lessons[-1]
a = [add(LM, M("application", q, r, w, e), True) for q, r, w, e in [
    ("Which of these is a living thing?", "a goat", ["a stone", "water", "a motorbike"], "A goat shows all the signs of life."),
    ("Which part of a plant makes food?", "the leaves", ["the roots", "the stem", "the seeds"], "Photosynthesis happens in the leaves."),
    ("Which animal is a mammal?", "a bat", ["a hen", "a frog", "a lizard"], "A bat has fur and feeds its young with milk."),
    ("Which sense organ do we use to hear?", "the ear", ["the eye", "the nose", "the skin"], "The ear is the organ of hearing."),
    ("Which food mostly gives energy?", "cassava", ["fish", "oranges", "water"], "Cassava is rich in starch."),
    ("Which soil is best for most crops?", "loam", ["sandy soil", "clay soil", "gravel"], "Loam holds water and air and has humus."),
    ("Which material is an insulator of electricity?", "rubber", ["copper", "iron", "aluminium"], "Rubber does not let electricity pass."),
    ("Which of these is biodegradable?", "banana peel", ["plastic bag", "tin can", "glass bottle"], "It rots and returns to the soil.")]]
b1 = add(LM, P("Mrs Nji plants three beans in pots. Pot 1 has soil, water and light. Pot 2 has soil and light, but no water. Pot 3 has soil and water, but is kept in a dark cupboard. After two weeks only the beans in pot 1 are healthy.",
               [PM("What is missing in pot 2?", "water", ["light", "soil", "seeds"], "Pot 2 was not watered.", points=1),
                PM("What is missing in pot 3?", "light", ["water", "soil", "seeds"], "Pot 3 was in the dark.", points=1),
                PM("What does the experiment show?", "plants need water and light to grow well", ["plants need only soil", "plants grow best in the dark", "water harms beans"], "Only pot 1 had everything.", points=2)]), True)
b2 = add(LM, P("A school kitchen cooks for the pupils. The cook uses a metal pot with a plastic handle. After cooking, the pot is washed and left in the sun.",
               [PM("Why is the pot made of metal?", "metal conducts heat well", ["metal is transparent", "metal floats", "metal is an insulator"], "Heat passes through metal to the food.", points=1),
                PM("Why is the handle plastic?", "plastic is an insulator, so it stays cool", ["plastic is a conductor", "plastic is magnetic", "plastic is heavy"], "It does not let the heat pass.", points=1),
                PM("Which food group does rice mostly belong to?", "energy foods", ["body-building foods", "protective foods", "water"], "Rice is rich in starch.", points=2)]), True)
c1 = add(LM, O("Write a balanced meal for a Class 6 pupil using local foods. Say which food gives energy, which helps the body to grow and which gives vitamins, and give one rule of food hygiene.", "Boiled plantain with fish and eru leaves, and an orange. Plantain gives energy. Fish helps the body to grow (protein). Eru leaves and the orange give vitamins. Drink clean, safe water. Rule: wash your hands with soap before eating.", "Marks (out of 4): one food for energy (1), one for growth (1), one for vitamins (1), one correct hygiene rule (1).", points=4, tier="examen"), True)
p.mock("2", "FSLC mock paper 2 — Science", 60,
       "Answer all the questions. Part A has 8 short questions (1 mark each); Part B has two problems (4 marks each); Part C is one written question (4 marks). Total: 20 marks. This is an original practice paper: its format is to be checked against the official texts.",
       [("Part A — Short questions (8 marks)", a), ("Part B — Problems (8 marks)", [b1, b2]), ("Part C — Written answer (4 marks)", [c1])])
p.write()
