from biolib import *


def add(p):
    # ------------------------------------------------------------------ living things
    ch = p.chapter("living", "Characteristics and classification of living things",
                   "GCE O Level Biology — Characteristics of living organisms; classification; keys (to be checked against the official syllabus)")
    build(ch, "characteristics", "Characteristics of living things", 20,
          ["List the seven characteristics shared by all living things.",
           "Explain each characteristic with an example from plants and animals.",
           "Decide whether an object is living or non-living and justify the answer."],
          [("key", "definition", "Living organisms",
            "A **living organism** is a thing that carries out all the life processes. Biologists remember seven of them with the words **MRS GREN**:\n\n- **M**ovement\n- **R**espiration\n- **S**ensitivity\n- **G**rowth\n- **R**eproduction\n- **E**xcretion\n- **N**utrition"),
           ("fig", grid(["Movement|change of position|or of parts", "Respiration|energy released|from food", "Sensitivity|detects and responds|to changes", "Growth|permanent increase|in size", "Reproduction|makes new|individuals", "Excretion|removes waste|made by cells", "Nutrition|takes in food|for energy"], cols=4, bh=58, size=11),
            "The seven characteristics of living things (MRS GREN).", "Seven rounded boxes, one for each life process: movement, respiration, sensitivity, growth, reproduction, excretion and nutrition, each with a short meaning."),
           ("key", "retenir", "What each word means",
            "- **Movement**: an action by an organism or part of it that changes its position or place. Most plants do not travel, but their stems and leaves move towards light.\n- **Respiration**: chemical reactions in cells that release energy from food. It is *not* the same as breathing.\n- **Sensitivity**: detecting stimuli (changes in the surroundings) and responding to them.\n- **Growth**: a permanent increase in size and dry mass."),
           ("key", "retenir", "The rest of MRS GREN",
            "- **Reproduction**: producing new individuals of the same kind.\n- **Excretion**: removal from the body of the waste products of metabolism (for example carbon dioxide and urea) and of substances in excess.\n- **Nutrition**: taking in materials (food) for energy, growth and repair. Plants make their own food by photosynthesis; animals eat other organisms."),
           ("key", "pieges", "Common mistakes",
            "- Plants *do* move (a sunflower head turns, the sensitive plant *Mimosa pudica* folds its leaves) and they *do* respond to stimuli.\n- Breathing is only the movement of air in and out of the lungs; respiration happens in every living cell.\n- Excretion is not egestion: faeces are undigested food that never entered the body cells."),
           ("example", "Is it alive?", "A student says that a motorbike taxi (okada) is alive because it moves, uses petrol and gives out waste gases. Decide if she is right.",
            ["List what the okada does: it moves, takes in fuel and releases exhaust gases.", "Check the other characteristics: it does not grow, it cannot reproduce and it does not sense and respond by itself.", "A living thing must show ALL seven characteristics; the engine only imitates a few of them."],
            "No. An okada is non-living because it does not grow, reproduce or show sensitivity."),
           ("example", "Life processes in a cassava plant", "Name the life process shown by each observation: (a) leaves bend towards a window, (b) a stem becomes 20 cm taller in a month, (c) a cassava plant makes starch in its leaves in the sunlight.",
            ["(a) A response to the stimulus of light: sensitivity (a growth movement).", "(b) A permanent increase in size: growth.", "(c) Making food from carbon dioxide and water using light energy: nutrition (photosynthesis)."],
            "(a) sensitivity, (b) growth, (c) nutrition.")],
          [("mcq", "A sensitive plant (*Mimosa pudica*) folds its leaves when touched. Which characteristic does this show?", "sensitivity", ["reproduction", "excretion", "nutrition"], "Touch is a stimulus and the folding is a response: this is sensitivity."),
           ("match", "Match each characteristic to a correct example.", [("Excretion", "a person loses urea in urine"), ("Nutrition", "a goat eats grass"), ("Growth", "a maize seedling gets taller and heavier"), ("Reproduction", "a hen sits on eggs that will hatch")], "Each example is a standard illustration of the process named on the left."),
           ("tf", "Plants are not living things because they cannot move from place to place.", False, "Plants show all seven characteristics. They move parts of their bodies (for example by growth movements) even if they do not travel."),
           ("mcq", "A car moves, uses fuel and releases gases. Why is it not a living organism?", "It does not grow, reproduce or sense and respond by itself", ["It does not move", "It does not give out any waste", "It is made of metal"], "A living thing shows all seven characteristics; the car imitates only some of them."),
           ("open", "Explain the difference between breathing and respiration.", "Breathing is the movement of air into and out of the lungs (ventilation). Respiration is the series of chemical reactions in every living cell that release energy from food, usually using oxygen and producing carbon dioxide and water.", ["1 mark: breathing = air moves in/out of the lungs", "1 mark: respiration = chemical reactions releasing energy from food", "1 mark: in all cells / uses oxygen, gives CO2 and water"]),
           ("prob", "A farmer in Bafoussam observes a tomato plant for three weeks.", [("mcq", "The plant gets taller each week. This is:", "growth", ["excretion", "movement only", "respiration only"], "A permanent increase in size is growth."), ("mcq", "The plant produces flowers and then fruits with seeds. This is:", "reproduction", ["nutrition", "sensitivity", "excretion"], "Seeds will give new plants of the same kind: reproduction."), ("open", "Give two ways in which the plant shows sensitivity.", "It grows towards light (phototropism) and its roots grow downwards in response to gravity (gravitropism).", ["1 mark each correct stimulus and response, maximum 2"], 2)])],
          [("Which pair are both characteristics of living things?", "growth and reproduction", ["rusting and melting", "burning and evaporation", "moving and being heavy"], "Growth and reproduction are two of the seven characteristics."),
           ("Removal of metabolic waste from the body is called:", "excretion", ["egestion", "nutrition", "ingestion"], "Excretion removes the waste products of metabolism."),
           ("Which of these is a stimulus?", "a change in temperature", ["a muscle contraction", "a hormone", "a response"], "A stimulus is a change in the environment; a response is the reaction to it."),
           ("Respiration is best described as:", "the release of energy from food in cells", ["taking air into the lungs", "making food from carbon dioxide", "removal of urea"], "Respiration releases energy in cells; breathing is a different process."),
           ("A permanent increase in size and dry mass is called:", "growth", ["movement", "sensitivity", "nutrition"], "That is the definition of growth.")],
          ["Whether the syllabus lists seven or six characteristics (some books group nutrition and excretion differently) is to be checked."],
          more=["Viruses show some life processes only inside a host cell; many textbooks discuss them as a borderline case."])

    build(ch, "classification", "Classification: kingdoms and major groups", 25,
          ["Explain why living things are classified and name the five kingdoms.",
           "State the main features of the vertebrate classes and the main arthropod groups.",
           "Write a scientific name using the binomial system."],
          [("key", "definition", "Classification",
            "**Classification** is the sorting of organisms into groups according to the features they share. It makes the huge variety of life easier to study. The groups go from large to small: **kingdom, phylum, class, order, family, genus, species**.\n\nA **species** is a group of organisms that can breed together and produce fertile offspring."),
           ("key", "retenir", "Five kingdoms",
            "- **Animals**: many cells without walls; feed on other organisms.\n- **Plants**: many cells with cellulose walls and chloroplasts; make food by photosynthesis.\n- **Fungi** (mushrooms, moulds, yeast): walls not made of cellulose; no chloroplasts; feed on dead or living matter.\n- **Protoctista**: mostly single-celled organisms with a nucleus, such as *Amoeba* and *Plasmodium*.\n- **Prokaryotae** (bacteria): no true nucleus; very small."),
           ("fig", flow(["Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"], w=480, size=10, bh=38, gap=12),
            "The levels of classification from the largest group to the smallest.", "Seven boxes joined by arrows in the order kingdom, phylum, class, order, family, genus, species."),
           ("key", "retenir", "Vertebrate classes",
            "- **Fish**: gills, scales, fins; lay eggs in water; cold-blooded.\n- **Amphibians**: moist skin, lungs and skin for gas exchange; eggs laid in water (frog).\n- **Reptiles**: dry scaly skin, eggs with leathery shells laid on land (lizard, snake).\n- **Birds**: feathers, beak, wings, hard-shelled eggs; warm-blooded.\n- **Mammals**: hair or fur, mammary glands that produce milk, most give birth to live young; warm-blooded."),
           ("key", "retenir", "Arthropods",
            "Arthropods have a hard **exoskeleton** and jointed legs.\n\n- **Insects**: 3 body parts, **6 legs**, one pair of antennae, usually wings (housefly, mosquito).\n- **Arachnids**: 2 body parts, **8 legs**, no antennae (spider, tick).\n- **Crustaceans**: many legs, two pairs of antennae (crab, shrimp).\n- **Myriapods**: long body with many segments (centipede, millipede)."),
           ("key", "methode", "Scientific names",
            "Each species has a two-part Latin name (**binomial system**): the **genus** (capital letter) then the **species** (small letter). In print it is in italics; written by hand it is underlined. Example: the human is *Homo sapiens*; the maize plant is *Zea mays*."),
           ("key", "pieges", "Common mistakes",
            "- A spider is *not* an insect: it has 8 legs, not 6.\n- A whale or a bat is a mammal, even though one lives in water and the other flies.\n- In *Homo sapiens* only the genus starts with a capital letter."),
           ("example", "Which class?", "An animal has feathers, a beak and lays hard-shelled eggs. Name its class and one more feature.",
            ["Feathers are found only in birds.", "Birds are warm-blooded and have wings (forelimbs adapted for flight in most species)."],
            "Class Aves (birds); warm-blooded."),
           ("example", "Insect or spider?", "A small animal has 8 legs and two body parts. Name the group and say why it is not an insect.",
            ["Count legs: 8, so not 6 legs.", "Body parts: 2 (a head-and-chest part plus an abdomen); insects have 3.", "No antennae are present, which fits arachnids."],
            "It is an arachnid (like a spider) because insects have 6 legs and 3 body parts.")],
          [("mcq", "Which kingdom contains organisms with cellulose cell walls and chloroplasts?", "Plants", ["Animals", "Fungi", "Prokaryotae"], "Only plants have cellulose walls and chloroplasts."),
           ("match", "Match the animal to its vertebrate class.", [("frog", "amphibian"), ("lizard", "reptile"), ("hen", "bird"), ("goat", "mammal")], "Frog = amphibian, lizard = reptile, hen = bird, goat = mammal."),
           ("tf", "In the binomial system *Zea mays* the first word is the species name.", False, "The first word is the genus (capital letter); the second is the species."),
           ("mcq", "A crab has many legs and two pairs of antennae. It belongs to the:", "crustaceans", ["insects", "arachnids", "myriapods"], "Crustaceans have two pairs of antennae and many legs; insects have only 6 legs and one pair of antennae."),
           ("open", "State three features that distinguish mammals from other vertebrates.", "Mammals have hair or fur on the skin, mammary glands that produce milk to feed the young, and most give birth to live young (a few lay eggs). They are warm-blooded.", ["1 mark each for: hair/fur; mammary glands/milk; live birth, maximum 3"]),
           ("prob", "A student collects four animals around Limbe: a crab, a housefly, a spider and a lizard.", [("mcq", "Which two are arthropods with 8 or more legs?", "the crab and the spider", ["the housefly and the lizard", "the lizard and the crab", "the housefly and the spider"], "The crab and the spider have 8 or more legs; the housefly has 6 and the lizard is a vertebrate."), ("mcq", "The housefly belongs to the:", "insects", ["arachnids", "crustaceans", "reptiles"], "Three body parts and six legs: insect."), ("open", "Name the vertebrate and its class, with one feature.", "The lizard is a reptile: it has dry scaly skin and lays eggs with leathery shells on land.", ["1 mark for lizard = reptile", "1 mark for a correct feature"], 2)])],
          [("The smallest group in classification is the:", "species", ["genus", "kingdom", "family"], "The order is kingdom, phylum, class, order, family, genus, species."),
           ("Which group has hair and mammary glands?", "mammals", ["birds", "reptiles", "amphibians"], "These are the features of mammals."),
           ("A spider has:", "8 legs and 2 body parts", ["6 legs and 3 body parts", "8 legs and 3 body parts", "10 legs and 2 body parts"], "Arachnids have 8 legs and 2 body parts."),
           ("*Plasmodium*, which causes malaria, is placed in the kingdom:", "Protoctista", ["Fungi", "Animals", "Plants"], "*Plasmodium* is a single-celled organism with a nucleus: Protoctista."),
           ("Which organisms feed on dead matter and have no chloroplasts?", "fungi such as moulds", ["flowering plants", "ferns", "mosses"], "Fungi are not photosynthetic and often feed on dead matter.")],
          ["Five-kingdom scheme is used; some syllabi use other groupings (check the official list of groups).", "Egg-laying mammals (platypus) are a known exception; mention only if the syllabus does."])

    build(ch, "keys", "Using keys to identify organisms", 20,
          ["Explain what a dichotomous key is.",
           "Use a key to identify an organism.",
           "Construct a simple dichotomous key for a set of organisms."],
          [("key", "definition", "Dichotomous key",
            "A **dichotomous key** is a series of paired statements. At each step you pick the statement that fits the specimen. It leads you either to another step or to the name of the organism. 'Dichotomous' means 'divided in two'."),
           ("key", "methode", "How to build a key",
            "1. Choose a feature that clearly splits the group in two (yes/no, present/absent).\n2. Write two statements, each leading to a name or to the next question.\n3. Repeat with the remaining organisms until each has its own name.\n4. Use features that can be seen, not size or colour, which vary."),
           ("fig", shapes([RECT(160, 8, 160, 34, fill="lightyellow", radius=8, width=1.5), T(240, 30, "Has wings?", size=13),
                           LINE(190, 42, 100, 80, arrow="end"), LINE(290, 42, 380, 80, arrow="end"), T(130, 58, "yes", size=12), T(350, 58, "no", size=12),
                           RECT(30, 82, 140, 34, fill="lightgreen", radius=8, width=1.5), T(100, 104, "Has 6 legs?", size=13),
                           RECT(310, 82, 140, 34, fill="lightblue", radius=8, width=1.5), T(380, 104, "Has 8 legs?", size=13),
                           LINE(60, 116, 40, 150, arrow="end"), LINE(140, 116, 160, 150, arrow="end"),
                           LINE(340, 116, 320, 150, arrow="end"), LINE(420, 116, 440, 150, arrow="end"),
                           T(40, 172, "insect", size=13), T(160, 172, "bird", size=13), T(320, 172, "spider", size=13), T(440, 172, "snail", size=13)], 480, 190),
            "A branching key: each question has two answers.", "A tree diagram: the first question 'Has wings?' splits into yes and no; each branch asks about the number of legs and ends at insect, bird, spider or snail."),
           ("key", "attention", "Pitfalls",
            "- Every step must have exactly two choices and they must exclude each other.\n- Use *observable* features of the organism, not 'is small' or 'is dangerous'.\n- Always end with a name; each organism must appear once."),
           ("example", "Using a key", "Key: 1a Has legs - go to 2. 1b No legs - go to 4. 2a Six legs - insect. 2b More than six legs - go to 3. 3a Eight legs - spider. 3b More - crab. 4a Has a shell - snail. 4b No shell - earthworm. Identify an animal with 8 legs and no shell.",
            ["The animal has legs, so choose 1a and go to 2.", "It does not have six legs: 2b, go to 3.", "It has eight legs: 3a."],
            "A spider."),
           ("example", "Writing a key", "Make a key for a goat, a hen and a fish using one feature at each step.",
            ["Choose a clear first feature: 1a Has feathers - hen. 1b No feathers - go to 2.", "Second feature to separate goat and fish: 2a Has fur and four legs - goat. 2b Has fins and scales - fish.", "Check: each animal appears once and each step has two exclusive choices."],
            "1a feathers: hen; 1b no feathers: 2a fur and legs: goat; 2b fins and scales: fish.")],
          [("mcq", "In a dichotomous key each step gives:", "two choices", ["one choice", "three choices", "as many choices as there are species"], "Dichotomous means divided in two."),
           ("tf", "A good key uses features like 'is big' or 'looks dangerous'.", False, "Such features are subjective and vary; use clear structural features."),
           ("mcq", "Using the key in Example 1 (1a legs, 1b no legs; 4a shell, 4b no shell), an animal with no legs and a shell is a:", "snail", ["spider", "earthworm", "crab"], "1b (no legs), 4a (shell): snail."),
           ("mcq", "Which feature is best for the first step of a key for a hen, a goat and a lizard?", "feathers present or absent", ["is it brown", "is it tasty", "is it tall"], "Feathers are a clear, observable structural feature that splits the group."),
           ("open", "Write a short key to separate a mosquito, a spider and a crab.", "1a Has 6 legs - mosquito. 1b More than 6 legs - go to 2. 2a Has 8 legs and 2 body parts - spider. 2b Has more than 8 legs and two pairs of antennae - crab.", ["1 mark: uses leg number at the first step", "1 mark: second step separates spider and crab", "1 mark: every statement leads to a name or a step"]),
           ("prob", "A key for four trees reads: 1a Leaf divided into leaflets - go to 2. 1b Single leaf blade - go to 3. 2a Leaflets in pairs along a stalk - flamboyant. 2b Leaflets spread like a hand - kapok. 3a Leaf edge smooth - mango. 3b Leaf edge toothed - orange.", [("mcq", "A tree has single leaves with smooth edges. It is:", "mango", ["flamboyant", "kapok", "orange"], "1b then 3a."), ("mcq", "How many steps are used to reach 'kapok'?", "2", ["1", "3", "4"], "1a then 2b: two steps."), ("open", "Why must every statement be 'either-or'?", "So that the user is never unsure which way to go: exactly one statement fits each specimen.", ["1 mark: reason about exclusive choices", "1 mark: clear explanation"], 2)])],
          [("A dichotomous key is used to:", "identify organisms", ["measure temperature", "see cells", "test food"], "Keys identify organisms."),
           ("At each step of a dichotomous key you choose between:", "two statements", ["three statements", "four statements", "one statement"], "Paired statements."),
           ("Which feature is most suitable in a key?", "number of legs", ["happiness", "tastiness", "size of the family"], "Observable and countable."),
           ("The number of organisms that each end-point of a key names is:", "one", ["two", "three", "none"], "Each end-point names one organism."),
           ("A key goes from:", "general features to specific features", ["specific to general", "names to features", "species to kingdoms"], "It narrows down step by step.")],
          ["The keys here are invented for teaching; the leaf descriptions of the trees are simplified and are not a real field key."])
