from biolib import *


def add(p):
    # ------------------------------------------------------------------ human transport
    ch = p.chapter("circulation", "Transport in humans",
                   "GCE O Level Biology — Transport in humans: heart, blood vessels, blood (to be checked against the official syllabus)")
    heart = shapes([
        RECT(150, 80, 90, 60, fill="lightblue", stroke="blue", width=2, radius=10), RECT(250, 80, 90, 60, fill="pink", stroke="red", width=2, radius=10),
        RECT(150, 148, 90, 80, fill="lightblue", stroke="blue", width=2, radius=10), RECT(250, 148, 90, 80, fill="pink", stroke="red", width=3, radius=10),
        T(195, 114, "right atrium", size=11), T(295, 114, "left atrium", size=11), T(195, 192, "right ventricle", size=11), T(295, 192, "left ventricle", size=11),
        LINE(180, 25, 180, 78, arrow="end", color="blue", width=3), T(172, 20, "vena cava", size=11, anchor="end"), T(172, 34, "from body", size=11, anchor="end"),
        LINE(310, 25, 310, 78, arrow="end", color="red", width=3), T(318, 20, "pulmonary vein", size=11, anchor="start"), T(318, 34, "from lungs", size=11, anchor="start"),
        LINE(180, 230, 180, 262, arrow="end", color="blue", width=3), T(172, 262, "pulmonary artery", size=11, anchor="end"), T(172, 276, "to lungs", size=11, anchor="end"),
        LINE(310, 230, 310, 262, arrow="end", color="red", width=3), T(318, 262, "aorta", size=11, anchor="start"), T(318, 276, "to body", size=11, anchor="start"),
        LINE(160, 144, 230, 144, width=3, color="grey", dash=True), LINE(260, 144, 330, 144, width=3, color="grey", dash=True), T(245, 144, "valves", size=10)], 480, 285)
    cardiac = 70 * 72
    assert cardiac == 5040
    build(ch, "heart", "The heart and blood circulation", 30,
          ["Describe the structure of the heart and the path of blood through it.",
           "Compare arteries, veins and capillaries.",
           "Explain double circulation and calculate pulse or cardiac output."],
          [("key", "definition", "Double circulation",
            "Blood passes through the heart **twice** on each complete circuit of the body: the **pulmonary circulation** (heart to lungs and back) and the **systemic circulation** (heart to body and back). This keeps oxygenated and deoxygenated blood separate and allows high pressure to the body."),
           ("fig", heart, "Schematic heart (the right side of the body is on the left of the page).", "Four chambers: blue right atrium and right ventricle on the left, pink left atrium and left ventricle on the right, with the vena cava and pulmonary vein entering the top and the pulmonary artery and aorta leaving the bottom."),
           ("key", "retenir", "Path of blood",
            "Body → **vena cava** → right atrium → (tricuspid valve) → right ventricle → **pulmonary artery** → lungs → **pulmonary vein** → left atrium → (bicuspid valve) → left ventricle → **aorta** → body.\n\nThe **left ventricle** has the thickest wall because it pumps blood to the whole body. **Valves** stop backflow. The heart muscle is supplied by the **coronary arteries**."),
           ("key", "retenir", "Blood vessels",
            "- **Arteries**: carry blood away from the heart; thick, muscular, elastic walls; narrow lumen; blood at high pressure; pulse felt.\n- **Veins**: carry blood to the heart; thin walls; wide lumen; **valves**; low pressure.\n- **Capillaries**: walls one cell thick, very narrow; exchange of materials between blood and cells.\n\nPulmonary vessels are the exception: the pulmonary artery carries deoxygenated blood, the pulmonary vein oxygenated blood."),
           ("key", "attention", "Heart health (flag for health review)",
            "Risk factors for coronary heart disease include smoking, a diet rich in saturated fat and salt, lack of exercise and stress. Regular exercise, a balanced diet and not smoking lower the risk. Anyone with chest pain should seek medical help."),
           ("example", "Cardiac output", "A resting heart pumps 70 cm³ of blood per beat and beats 72 times per minute. Calculate the volume pumped per minute (cardiac output).",
            ["Cardiac output = stroke volume × heart rate.", "70 × 72 = 5040 cm³ per minute (about 5 litres)."],
            "5040 cm³ per minute"),
           ("example", "Following a blood cell", "Trace a red blood cell from the left ventricle to a muscle in the leg and back to the heart.",
            ["Left ventricle → aorta → arteries → capillaries in the leg muscle (oxygen is released).", "Deoxygenated blood → veins → vena cava → right atrium."],
            "Left ventricle → aorta → artery → muscle capillary → vein → vena cava → right atrium.")],
          [("mcq", "Which vessel carries blood from the heart to the lungs?", "pulmonary artery", ["pulmonary vein", "aorta", "vena cava"], "The pulmonary artery carries deoxygenated blood to the lungs."),
           ("match", "Match each blood vessel with a feature.", [("artery", "thick muscular wall"), ("vein", "valves"), ("capillary", "wall one cell thick"), ("aorta", "leaves the left ventricle")], "Standard features."),
           ("num", "Stroke volume is 60 cm³ and heart rate is 75 beats per minute. Calculate cardiac output in cm³ per minute.", 4500, "60 × 75 = 4500 cm³ per minute.", 0, "cm³/min"),
           ("mcq", "The left ventricle has a thicker wall than the right ventricle because it:", "pumps blood around the whole body at higher pressure", ["pumps blood only to the lungs", "receives blood from the body", "contains valves"], "It must overcome the resistance of the systemic circuit."),
           ("open", "Explain how the structure of a vein makes it suited to its function.", "Veins have valves that prevent backflow, since blood is at low pressure; they have wide lumen so blood flows easily; thin walls because the pressure is low. Muscles squeezing the veins push blood on towards the heart.", ["1 mark: valves prevent backflow", "1 mark: wide lumen / low pressure", "1 mark: link to returning blood to heart"]),
           ("prob", "A student studies the heart of a mammal.", [("mcq", "Blood in the right atrium is:", "deoxygenated", ["oxygenated", "free of carbon dioxide", "full of oxygen"], "Blood from the body returns by the vena cava deoxygenated."), ("mcq", "The valve between the left atrium and ventricle is the:", "bicuspid valve", ["tricuspid valve", "semilunar valve of the pulmonary artery", "coronary valve"], "The left atrioventricular valve has two flaps."), ("open", "Explain why blood must pass through the heart twice in one circuit of the body.", "After passing through the lungs the blood loses pressure, so it returns to the heart to be pumped again at high pressure round the body; it also keeps oxygenated and deoxygenated blood separate.", ["1 mark: pressure restored", "1 mark: keeps blood types separate"], 2)])],
          [("Blood is pumped to the body through the:", "aorta", ["vena cava", "pulmonary vein", "coronary vein"], "The aorta leaves the left ventricle."),
           ("Veins have valves to:", "stop backflow of blood", ["increase pressure", "make blood red", "carry oxygen"], "Valves keep blood moving in one direction."),
           ("Exchange of materials between blood and cells takes place in:", "capillaries", ["arteries", "veins", "the aorta"], "Capillary walls are one cell thick."),
           ("The coronary arteries supply:", "the heart muscle", ["the lungs", "the brain", "the kidneys"], "They bring oxygen to the heart muscle."),
           ("Blood in the pulmonary vein is:", "oxygenated", ["deoxygenated", "mostly plasma only", "full of urea"], "It comes from the lungs.")],
          ["Heart diagram is schematic; valves drawn as dashed lines. Check whether the syllabus asks for the names tricuspid/bicuspid.", "Health advice is general and must be reviewed by a health worker."])

    blood = shapes([CIRCLE(60, 90, 30, fill="red", width=2), CIRCLE(60, 90, 12, fill="pink", width=1),
                    CIRCLE(190, 90, 36, fill="lightyellow", width=2), POLY([(170, 80), (190, 70), (210, 85), (200, 105), (175, 100)], fill="purple", width=1),
                    CIRCLE(320, 90, 28, fill="lightyellow", width=2), CIRCLE(322, 90, 20, fill="purple", width=1),
                    CIRCLE(420, 90, 6, fill="orange", width=1), CIRCLE(436, 100, 5, fill="orange", width=1), CIRCLE(408, 104, 5, fill="orange", width=1),
                    T(60, 150, "red blood cell", size=11), T(60, 166, "no nucleus", size=11),
                    T(190, 150, "phagocyte", size=11), T(190, 166, "lobed nucleus", size=11),
                    T(320, 150, "lymphocyte", size=11), T(320, 166, "large round nucleus", size=11),
                    T(425, 150, "platelets", size=11), T(425, 166, "fragments", size=11)], 500, 185)
    pl = round(5.5 / 10 * 100)
    assert pl == 55
    build(ch, "blood", "Blood: composition and functions", 25,
          ["Name the components of blood and state the function of each.",
           "Explain how red cells, white cells and platelets are adapted to their roles.",
           "Describe how blood clotting and antibodies protect the body."],
          [("key", "definition", "Components of blood",
            "Blood is a tissue made of **plasma** (about 55 % of the volume) and **blood cells**. Plasma is a pale yellow liquid, mostly water, that carries dissolved glucose, amino acids, mineral ions, hormones, urea, plasma proteins and carbon dioxide (as hydrogencarbonate ions), and distributes heat."),
           ("fig", blood, "The cells of the blood.", "Four drawings: a red blood cell with a pale centre and no nucleus, a phagocyte with a lobed nucleus, a lymphocyte with a large round nucleus and some small platelets."),
           ("key", "retenir", "Cells and their jobs",
            "- **Red blood cells**: biconcave discs without a nucleus, full of **haemoglobin**. In the lungs haemoglobin combines with oxygen to form **oxyhaemoglobin**; in the tissues it releases it.\n- **White blood cells**: **phagocytes** engulf and digest microbes (phagocytosis); **lymphocytes** make **antibodies**.\n- **Platelets**: fragments of cells that help the blood **clot**, sealing a wound."),
           ("key", "retenir", "Defence",
            "Antibodies are made by lymphocytes in response to **antigens** (molecules on microbes). Each antibody fits one antigen, sticks microbes together or marks them for destruction. After an infection, some lymphocytes remain as **memory cells** that respond fast if the same microbe returns: this is the basis of **immunity**."),
           ("key", "pieges", "Common mistakes",
            "- Red blood cells have *no nucleus*; white cells do.\n- Haemoglobin is in the red cells, not in the plasma.\n- Platelets are cell fragments, not full cells.\n- Blood is not always 'blue' inside the body: deoxygenated blood is dark red."),
           ("example", "Percentage plasma", "A 10 cm³ sample of blood is spun in a centrifuge and 5.5 cm³ of clear yellow liquid separates from the cells. Calculate the percentage of plasma.",
            ["Plasma volume ÷ total volume = 5.5 ÷ 10.", "5.5 ÷ 10 × 100 = 55 %."],
            "55 % plasma"),
           ("example", "A cut on the knee", "A boy falls in Buea and cuts his knee. Describe how the blood protects him.",
            ["Platelets help form a clot of fibres that seals the wound and stops bleeding.", "Phagocytes engulf microbes that enter; lymphocytes make specific antibodies against them."],
            "Clotting stops blood loss and microbes entering; white cells destroy microbes that get in.")],
          [("mcq", "Which part of the blood carries oxygen?", "red blood cells", ["plasma", "platelets", "phagocytes"], "Haemoglobin in red cells carries oxygen."),
           ("match", "Match each blood component with its function.", [("red blood cell", "carries oxygen"), ("phagocyte", "engulfs microbes"), ("lymphocyte", "makes antibodies"), ("platelet", "helps clotting")], "Standard functions."),
           ("num", "A 20 cm³ sample of blood contains 11 cm³ of plasma. What percentage is plasma?", 55, "11 ÷ 20 × 100 = 55 %.", 0.1, "%"),
           ("mcq", "Why is a red blood cell biconcave and without a nucleus?", "to have a large surface area and more room for haemoglobin", ["to digest microbes", "to make antibodies", "to clot blood"], "The shape gives a large surface area; no nucleus leaves room for haemoglobin."),
           ("open", "Explain how vaccination gives immunity.", "A vaccine contains a weakened or dead microbe or its antigens. The lymphocytes make antibodies and memory cells. If the real microbe enters later, memory cells respond quickly with a large amount of antibodies, so the person does not become ill.", ["1 mark: vaccine contains harmless antigens", "1 mark: antibodies and memory cells made", "1 mark: fast response on later infection"]),
           ("prob", "A pale sample of blood from a person in Maroua is examined under a microscope.", [("tf", "Mature red blood cells contain a nucleus.", False, "They lose the nucleus."), ("mcq", "A cell that ingests a bacterium is a:", "phagocyte", ["red blood cell", "platelet", "plasma cell"], "Phagocytes engulf microbes."), ("open", "Name two substances transported by plasma.", "Any two of: glucose, amino acids, urea, carbon dioxide, hormones, mineral ions, heat.", ["1 mark each, maximum 2"], 2)])],
          [("Plasma is mostly:", "water", ["haemoglobin", "platelets", "red cells"], "Plasma is about 90 % water."),
           ("Haemoglobin combines with oxygen to form:", "oxyhaemoglobin", ["glycogen", "fibrinogen", "antibody"], "Oxyhaemoglobin in the lungs."),
           ("Cells that make antibodies are:", "lymphocytes", ["red blood cells", "platelets", "phagocytes"], "Lymphocytes make antibodies."),
           ("Platelets are involved in:", "clotting", ["transport of oxygen", "making antibodies", "phagocytosis"], "They help the blood clot."),
           ("Memory cells give:", "faster response when the same microbe returns", ["more red cells", "a clotting factor", "a higher body temperature"], "They provide immunity.")],
          ["Percentage of plasma (about 55 %) and water in plasma (about 90 %) are commonly quoted textbook values - check.", "Vaccination wording is conservative and must be reviewed by a health worker."])

    # ------------------------------------------------------------------ gas exchange
    ch = p.chapter("breathing", "Breathing, gas exchange and respiration",
                   "GCE O Level Biology — Gas exchange in humans; respiration (to be checked against the official syllabus)")
    alv = shapes([CIRCLE(160, 110, 70, fill="lightblue", width=3), CIRCLE(160, 110, 62, fill="paper", width=1),
                  RECT(240, 70, 60, 80, fill="pink", radius=20, stroke="red", width=2),
                  LINE(60, 110, 20, 110, width=1.2),
                  LINE(230, 100, 250, 100, arrow="end", color="blue", width=3), LINE(250, 125, 230, 125, arrow="end", color="red", width=3),
                  T(160, 105, "air", size=13), T(160, 122, "(alveolus)", size=11),
                  T(270, 105, "blood", size=12), T(270, 122, "capillary", size=11),
                  T(240, 40, "oxygen in", size=11, color="blue"), T(240, 180, "CO₂ out", size=11, color="red"),
                  LINE(240, 46, 240, 62, width=1, arrow="end", color="blue"), LINE(240, 164, 240, 150, width=1, arrow="end", color="red"),
                  T(375, 100, "thin wall:", size=11), T(375, 116, "one cell thick", size=11)], 480, 205)
    comp = bars([("O₂ in", 21, "blue"), ("O₂ out", 16, "lightblue"), ("CO₂ in", 0.04, "red"), ("CO₂ out", 4, "orange")], unit="% of the air", w=420, h=230)
    build(ch, "gas-exchange", "Breathing and gas exchange", 30,
          ["Describe the structure of the breathing system and the mechanism of ventilation.",
           "Explain how alveoli are adapted for gas exchange.",
           "Compare inhaled and exhaled air and describe the effects of smoking."],
          [("key", "definition", "Gas exchange",
            "**Gas exchange** is the diffusion of oxygen into the blood and carbon dioxide out of it. It takes place in the **alveoli** of the lungs. Air passes through the nose, **trachea** (held open by rings of cartilage), **bronchi** and **bronchioles** to the alveoli. The **ciliated cells** and **mucus** of the airways trap dust and microbes."),
           ("fig", alv, "One alveolus and its capillary.", "An alveolus drawn as a circle containing air next to a blood capillary: oxygen diffuses into the blood and carbon dioxide diffuses out; the wall is one cell thick."),
           ("key", "retenir", "Adaptations of alveoli",
            "- Very **large total surface area** (millions of alveoli).\n- **Thin walls** (one cell thick) so the diffusion distance is short.\n- A rich network of **capillaries** that carries oxygen away and brings carbon dioxide, keeping the concentration gradient steep.\n- A **moist** lining in which gases dissolve.\n- Fresh air from **ventilation** keeps a high oxygen concentration."),
           ("key", "retenir", "Mechanism of breathing",
            "**Inhalation**: intercostal muscles contract and raise the ribs up and out; the **diaphragm** contracts and flattens; the volume of the chest increases, the pressure falls and air enters.\n\n**Exhalation**: the intercostal muscles and diaphragm relax; the ribs fall and the diaphragm rises; the volume decreases, the pressure rises and air is forced out."),
           ("fig", comp, "Approximate composition of inhaled and exhaled air.", "A bar chart: oxygen about 21 percent in and 16 percent out; carbon dioxide about 0.04 percent in and 4 percent out."),
           ("key", "attention", "Smoking and health (flag for health review)",
            "Tobacco smoke contains **tar** (which damages the airways and can cause lung cancer), **nicotine** (an addictive drug), and **carbon monoxide**, which combines with haemoglobin and reduces the oxygen carried. Smoking is linked with bronchitis, emphysema and heart disease. Stopping smoking improves health; seek advice from a health worker."),
           ("example", "Volume of air breathed per minute", "A resting boy takes 16 breaths per minute and inhales about 500 cm³ of air with each breath. Calculate the volume of air breathed per minute.",
            ["Volume per minute = volume per breath × breaths per minute.", "500 × 16 = 8000 cm³."],
            "8000 cm³ (8 dm³) per minute"),
           ("example", "Limewater test", "Exhaled air is bubbled through limewater and it turns milky. Air from a pump does so only after a long time. What does this show?",
            ["Limewater turns milky in the presence of carbon dioxide.", "Exhaled air has more carbon dioxide than inhaled air."],
            "Exhaled air contains more carbon dioxide than inhaled air.")],
          [("mcq", "Gas exchange in the lungs occurs in the:", "alveoli", ["trachea", "bronchi", "diaphragm"], "Alveoli are the exchange surface."),
           ("tf", "During inhalation the diaphragm relaxes and moves up.", False, "During inhalation the diaphragm contracts and flattens."),
           ("num", "A girl takes 18 breaths per minute, each of 450 cm³. What volume of air does she breathe in one minute (cm³)?", 8100, "450 × 18 = 8100 cm³.", 0, "cm³"),
           ("mcq", "Which is NOT an adaptation of the alveoli?", "walls made of thick cartilage", ["thin walls", "rich blood supply", "large surface area"], "Cartilage rings are found in the trachea, not the alveolar wall."),
           ("open", "Explain why exhaled air contains less oxygen and more carbon dioxide than inhaled air.", "Cells use oxygen in aerobic respiration and release carbon dioxide; oxygen diffuses from alveoli into the blood and carbon dioxide diffuses from the blood into the alveoli.", ["1 mark: oxygen absorbed into blood", "1 mark: carbon dioxide made in respiration", "1 mark: carbon dioxide diffuses into the alveoli"]),
           ("prob", "A student measures the breathing rate of a classmate at rest and after running on the spot in Kumba.", [("num", "At rest 15 breaths in one minute; after running 33 breaths in one minute. By how many breaths per minute did the rate increase?", 18, "33 − 15 = 18.", 0, "breaths/min"), ("mcq", "The best explanation of the increase is that:", "muscles respire faster and need more oxygen and must remove more CO₂", ["the lungs get smaller", "the diaphragm stops working", "blood loses haemoglobin"], "The increased respiration increases the CO₂ level, detected by the brain, which increases the breathing rate."), ("open", "Suggest one way to make the investigation fair.", "Use the same person, same exercise duration and measure for the same length of time.", ["1 mark for a control variable"], 1)])],
          [("Which structure keeps the trachea open?", "rings of cartilage", ["bone", "muscle", "cellulose"], "C-shaped cartilage rings."),
           ("Air entering the lungs is cleaned by:", "mucus and cilia", ["alveoli", "the diaphragm", "haemoglobin"], "They trap dust and microbes."),
           ("Carbon monoxide in smoke:", "reduces oxygen carried by haemoglobin", ["is a source of energy", "makes cilia grow", "is used in respiration"], "It binds to haemoglobin."),
           ("When the ribs move up and out the pressure in the chest:", "falls", ["rises", "stays the same", "doubles"], "The volume increases."),
           ("Which gas turns limewater milky?", "carbon dioxide", ["oxygen", "nitrogen", "hydrogen"], "That is the test for CO₂.")],
          ["Composition values of air are approximate; check the figures required (16–17 % O₂, about 4 % CO₂ in exhaled air).", "Tidal volume of 450-500 cm³ assumed typical for a resting person.", "Smoking content is for review by a health worker."])

    chem = shapes([RECT(30, 40, 130, 44, fill="lightorange", radius=8, width=1.5), T(95, 67, "glucose", size=14), T(180, 67, "+", size=18), RECT(200, 40, 130, 44, fill="lightblue", radius=8, width=1.5), T(265, 67, "oxygen", size=14),
                   LINE(335, 62, 370, 62, arrow="end", width=3), RECT(375, 40, 100, 44, fill="lightyellow", radius=8, width=1.5), T(425, 67, "energy", size=14),
                   T(240, 120, "+ carbon dioxide + water", size=14),
                   RECT(30, 150, 130, 44, fill="lightorange", radius=8, width=1.5), T(95, 177, "glucose", size=14),
                   LINE(165, 172, 215, 172, arrow="end", width=3), RECT(220, 150, 110, 44, fill="lightyellow", radius=8, width=1.5), T(275, 177, "lactic acid", size=13),
                   T(405, 172, "(muscles)", size=13), T(240, 230, "with only a little energy", size=13)], 480, 250)
    ferm = shapes([RECT(60, 90, 90, 100, fill="lightyellow", width=2, radius=6), T(105, 140, "yeast +", size=12), T(105, 156, "glucose", size=12),
                   LINE(105, 90, 105, 45, width=2), LINE(105, 45, 250, 45, width=2), LINE(250, 45, 250, 130, width=2),
                   RECT(200, 120, 100, 80, fill="lightblue", stroke="blue", width=2, radius=4), T(250, 168, "limewater", size=12),
                   T(105, 215, "flask", size=12), T(250, 220, "turns milky", size=12), T(400, 125, "CO₂ given off", size=12), LINE(300, 60, 360, 110, width=1.2, arrow="end")], 480, 240)
    r1, r2 = 24 / 2, 54 / 2
    build(ch, "respiration", "Respiration: aerobic and anaerobic", 30,
          ["Write the word and chemical equations for aerobic respiration.",
           "Describe anaerobic respiration in muscles and in yeast and explain oxygen debt.",
           "Interpret simple respiration experiments."],
          [("key", "definition", "Respiration",
            "**Respiration** is the chemical process in living cells that releases **energy from food** (usually glucose). Energy is used for muscle contraction, growth, active transport, making proteins and keeping a constant body temperature.\n\n**Aerobic respiration** uses oxygen. It takes place in the **mitochondria**."),
           ("formula", "\\text{C}_6\\text{H}_{12}\\text{O}_6 + 6\\text{O}_2 \\to 6\\text{CO}_2 + 6\\text{H}_2\\text{O} + \\text{energy}", "Aerobic respiration: glucose + oxygen gives carbon dioxide + water + energy"),
           ("key", "retenir", "Anaerobic respiration",
            "**Anaerobic respiration** releases energy from glucose **without oxygen**. It releases much *less* energy per glucose molecule.\n\n- In **muscles** (hard exercise): glucose → **lactic acid** + a little energy.\n- In **yeast** (fermentation): glucose → **ethanol** + **carbon dioxide** + a little energy.\n\nYeast fermentation is used to make bread (CO₂ makes dough rise), palm wine and beer."),
           ("fig", chem, "Aerobic and anaerobic (muscle) respiration.", "Two rows of boxes: glucose plus oxygen gives energy with carbon dioxide and water; and glucose gives lactic acid with only a little energy in muscles."),
           ("key", "retenir", "Oxygen debt",
            "During sprinting the muscles respire anaerobically and **lactic acid** builds up, causing fatigue. After the exercise we go on breathing hard and the heart beats fast: extra oxygen is needed to break down the lactic acid. This extra oxygen is called the **oxygen debt**."),
           ("fig", ferm, "Yeast fermentation produces carbon dioxide.", "A flask of yeast and glucose joined by a delivery tube to a tube of limewater, which turns milky."),
           ("key", "pieges", "Common mistakes",
            "- Respiration is *not* breathing, and it is not the same as photosynthesis.\n- Plants respire all the time, not only at night.\n- Anaerobic respiration releases some energy; it does not release none.\n- Energy is *released* from glucose, it is not 'made'."),
           ("example", "Rate of fermentation", "Yeast in warm sugar solution gives 24 bubbles of gas in 2 minutes at 20 °C, and 54 bubbles in 2 minutes at 35 °C. Calculate the rates in bubbles per minute.",
            ["At 20 °C: 24 ÷ 2 = 12 bubbles/min.", "At 35 °C: 54 ÷ 2 = 27 bubbles/min.", "Enzymes work faster at the warmer temperature (below the optimum)."],
            "12 and 27 bubbles per minute"),
           ("example", "After a 100 m race", "A boy runs the 100 m race in Bamenda and keeps breathing hard for several minutes. Explain.",
            ["His muscles respired partly anaerobically and made lactic acid.", "He needs extra oxygen to break the lactic acid down: he repays the oxygen debt by deep, fast breathing."],
            "To repay the oxygen debt and remove lactic acid.")],
          [("mcq", "Which of these is a product of anaerobic respiration in yeast?", "ethanol", ["lactic acid", "oxygen", "glucose"], "Yeast makes ethanol and carbon dioxide."),
           ("match", "Match each item to its role.", [("mitochondria", "site of aerobic respiration"), ("lactic acid", "made in muscles without oxygen"), ("limewater", "test for carbon dioxide"), ("yeast", "ferments sugar")], "Standard definitions."),
           ("num", "A yeast culture gives 45 bubbles in 3 minutes. What is the rate in bubbles per minute?", 15, "45 ÷ 3 = 15.", 0, "bubbles/min"),
           ("mcq", "Why does anaerobic respiration release less energy than aerobic respiration?", "glucose is only partly broken down", ["no glucose is used", "oxygen is made", "cells are dead"], "The products still contain energy (lactic acid or ethanol)."),
           ("open", "Explain what is meant by oxygen debt.", "It is the extra oxygen needed after vigorous exercise to break down the lactic acid formed during anaerobic respiration in the muscles.", ["1 mark: extra oxygen after exercise", "1 mark: to remove lactic acid made anaerobically"]),
           ("prob", "A student sets up a flask of germinating bean seeds with a thermometer and another flask of boiled seeds.", [("mcq", "The temperature of the flask with living seeds:", "rises", ["falls", "stays the same", "becomes zero"], "Respiration releases heat energy."), ("mcq", "The flask of boiled seeds acts as a:", "control", ["variable", "test", "source of oxygen"], "Dead seeds do not respire, so any change is due to respiration."), ("open", "State the word equation for the reaction that raises the temperature.", "Glucose + oxygen → carbon dioxide + water + energy.", ["1 mark: reactants", "1 mark: products including energy"], 2)])],
          [("Aerobic respiration needs:", "oxygen", ["light", "chlorophyll", "limewater"], "Aerobic means with oxygen."),
           ("Muscles in hard exercise make:", "lactic acid", ["ethanol", "glycogen", "starch"], "Anaerobic respiration in muscles."),
           ("Organelle of aerobic respiration:", "mitochondrion", ["ribosome", "vacuole", "chloroplast"], "Mitochondria release energy."),
           ("Which test shows CO₂ is given off by yeast?", "limewater turns milky", ["glowing splint relights", "iodine turns blue-black", "litmus turns red"], "Limewater test for CO₂."),
           ("Respiration occurs in:", "all living cells", ["only animal cells", "only plant leaves", "only at night"], "Every living cell respires.")],
          ["Mitochondria 'site of aerobic respiration' is as in the existing cell lesson.", "The formula uses LaTeX subscripts; checked by the validator.", "Experimental values are invented for practice."])
