from biolib import *


def add(p):
    # ------------------------------------------------------------------ excretion & homeostasis
    ch = p.chapter("homeostasis", "Excretion and homeostasis",
                   "GCE O Level Biology — Excretion; the kidney; homeostasis: temperature and blood sugar (to be checked against the official syllabus)")
    nephron = shapes([
        CIRCLE(90, 70, 34, fill="lightyellow", width=2), CIRCLE(90, 70, 15, fill="red", width=1),
        LINE(90, 104, 90, 170, width=3), LINE(90, 170, 240, 170, width=3), LINE(240, 170, 240, 60, width=3),
        LINE(240, 60, 330, 60, width=3), LINE(330, 20, 330, 220, width=5, color="orange"),
        LINE(125, 70, 160, 40, width=1.2), T(164, 38, "Bowman's capsule", size=11, anchor="start"),
        LINE(80, 82, 50, 120, width=1.2), T(10, 134, "glomerulus", size=11, anchor="start"),
        T(165, 190, "kidney tubule (reabsorption)", size=11), T(335, 235, "collecting duct", size=11, anchor="end"),
        T(332, 12, "urine", size=11, anchor="start"), T(400, 90, "to the ureter", size=11, anchor="end")], 440, 245)
    n1 = 180; filt = 125
    build(ch, "excretion", "Excretion and the kidney", 30,
          ["Name the excretory organs and their excretory products.",
           "Describe filtration and selective reabsorption in the kidney.",
           "Explain what happens when the kidneys fail."],
          [("key", "definition", "Excretion in humans",
            "**Excretion** is the removal of the waste products of metabolism from the body.\n\n- **Lungs**: carbon dioxide and water vapour.\n- **Kidneys**: **urea** (made in the liver from excess amino acids), excess water and mineral ions, in the urine.\n- **Skin**: water, salts and a little urea in sweat.\n- The **liver** breaks down haemoglobin; bile pigments leave in the faeces."),
           ("key", "retenir", "How the kidney works",
            "Each kidney contains about a million tiny tubes called **nephrons**.\n\n1. **Ultrafiltration**: blood from the **renal artery** is filtered under pressure in the **glomerulus**; water, glucose, urea and salts enter the capsule; blood cells and large proteins stay in the blood.\n2. **Selective reabsorption** in the tubule: **all the glucose**, most of the water and the needed salts go back into the blood.\n3. The remainder (**urine**: water, urea, extra salts) passes to the ureter, bladder and urethra."),
           ("fig", nephron, "A nephron (schematic).", "A ball of capillaries (glomerulus) inside Bowman's capsule, followed by a long tubule where reabsorption occurs and a collecting duct that carries urine to the ureter."),
           ("key", "retenir", "Controlling water: ADH",
            "The amount of water in the blood is controlled by the hormone **ADH** from the pituitary gland. If the blood is too concentrated (after sweating, little drinking), more ADH is released, the kidneys reabsorb more water and a small volume of concentrated urine is made. If there is too much water, less ADH is released and a large volume of dilute urine is produced."),
           ("key", "attention", "Kidney failure (flag for health review)",
            "If the kidneys fail, urea and water build up in the blood. Treatment is **dialysis** (a machine filters the blood) or a kidney **transplant**. Drinking enough clean water and avoiding harmful medicines help protect the kidneys; people with symptoms should see a health worker."),
           ("example", "What reaches the urine?", "Glucose, urea, proteins and red blood cells are all in the blood entering a kidney. Which are filtered out into the capsule, and which appear in the urine of a healthy person?",
            ["Ultrafiltration lets small molecules pass: glucose and urea are filtered; red cells and proteins are too large.", "All the filtered glucose is reabsorbed, but urea stays in the tubule.", "So healthy urine has urea but no glucose, proteins or red cells."],
            "Urea only (with water and salts)."),
           ("example", "A hot day in Garoua", "A farmer works in the heat and drinks little. Describe how his urine changes and why.",
            ["He loses water in sweat, so the blood becomes more concentrated.", "The pituitary releases more ADH; the kidneys reabsorb more water.", "The urine is small in volume and dark (concentrated)."],
            "Little concentrated urine because ADH increases water reabsorption.")],
          [("mcq", "Urea is made in the:", "liver", ["kidney", "lungs", "bladder"], "The liver converts excess amino acids to urea; the kidney removes it."),
           ("match", "Match the organ with its excretory product.", [("lungs", "carbon dioxide"), ("kidney", "urea"), ("skin", "sweat"), ("liver", "bile pigments")], "Each organ removes the product shown."),
           ("tf", "In a healthy person glucose is present in the urine.", False, "All glucose is reabsorbed in the kidney tubule."),
           ("mcq", "What remains in the blood after ultrafiltration in the glomerulus?", "red blood cells and large proteins", ["glucose and urea", "water and salts", "all small molecules"], "Large particles cannot cross the filter."),
           ("open", "Explain how the kidney helps to keep the water content of the blood constant.", "When the blood is too concentrated the pituitary releases more ADH, which makes the kidney reabsorb more water so urine is concentrated and less water is lost. When there is too much water, less ADH is released and a lot of dilute urine is made.", ["1 mark: ADH from the pituitary", "1 mark: more water reabsorbed when blood concentrated", "1 mark: dilute urine when water in excess"]),
           ("prob", "A urine test is done on three patients. Patient A: glucose present. Patient B: protein present. Patient C: normal.", [("mcq", "Glucose in the urine of patient A may indicate:", "diabetes", ["a normal diet", "kidney reabsorbing too much", "a healthy kidney"], "The blood glucose is so high that the tubule cannot reabsorb all of it (a possible sign of diabetes: the person should see a health worker)."), ("mcq", "Protein in urine of patient B suggests:", "damaged filtration in the glomerulus", ["a normal kidney", "excess water", "too much salt"], "Proteins are normally too large to be filtered."), ("open", "Name three substances found in normal urine.", "Water, urea and mineral ions (salts).", ["1 mark each, maximum 3"], 3)])],
          [("The filtering unit of the kidney is the:", "nephron", ["alveolus", "villus", "neurone"], "Each nephron filters blood."),
           ("The hormone that controls water reabsorption is:", "ADH", ["insulin", "adrenaline", "oestrogen"], "ADH acts on the kidney."),
           ("Which is NOT normally found in urine?", "glucose", ["urea", "water", "mineral ions"], "Glucose is reabsorbed."),
           ("Urine passes from the kidney to the bladder through the:", "ureter", ["urethra", "aorta", "vena cava"], "The ureter links kidney and bladder."),
           ("A machine that cleans the blood of a patient is:", "a dialysis machine", ["a microscope", "a potometer", "a thermometer"], "Dialysis replaces kidney function.")],
          ["Kidney tubule details (loop of Henle) deliberately omitted; check syllabus scope.", "Medical content (kidney failure, diabetes sign) to be reviewed by a health worker."])

    ncirc = shapes([RECT(160, 20, 160, 50, fill="lightyellow", radius=10, width=2), T(240, 40, "Hypothalamus", size=13), T(240, 58, "(control centre)", size=11),
                    LINE(240, 70, 240, 105, arrow="end", width=2), RECT(130, 105, 220, 40, fill="lightgreen", radius=10, width=2), T(240, 130, "Effectors: skin, muscles", size=13),
                    LINE(130, 125, 60, 125, width=2), LINE(60, 125, 60, 45, width=2), LINE(60, 45, 155, 45, arrow="end", width=2),
                    T(60, 160, "receptors in skin", size=11), T(60, 175, "detect temperature", size=11),
                    T(240, 170, "body temperature returns to about 37 °C", size=12)], 480, 200)
    # blood glucose curve: after meal and recovery (time min, mmol/dm3) invented teaching values
    g = [(0, 4.5), (30, 7.5), (60, 6.0), (90, 5.0), (120, 4.6)]
    gx = lambda t: 70 + t * 2.7
    gy = lambda v: 200 - (v - 3) * 24
    gfig = shapes(axes(70, 200, 420, 30, xl="time after meal (min)", yl="glucose (mmol/dm³)",
                       ticks_x=[(gx(t), str(t)) for t in (0, 30, 60, 90, 120)], ticks_y=[(gy(v), str(v)) for v in (4, 6, 8)]) +
                  [polyline([(gx(t), gy(v)) for t, v in g])] + [CIRCLE(gx(t), gy(v), 3, fill="red", stroke="red") for t, v in g], 480, 250)
    build(ch, "homeostasis", "Homeostasis: temperature and blood sugar", 30,
          ["Define homeostasis and negative feedback.",
           "Explain how the body keeps its temperature at about 37 °C.",
           "Explain the control of blood glucose by insulin and the nature of diabetes."],
          [("key", "definition", "Homeostasis",
            "**Homeostasis** is the maintenance of a constant internal environment (temperature, water content, blood glucose, carbon dioxide). It works by **negative feedback**: a change away from the normal level is detected and the body responds to bring it back."),
           ("fig", ncirc, "Temperature control uses a feedback loop.", "A loop: receptors in the skin send information to the hypothalamus; it sends instructions to effectors in the skin and muscles; body temperature returns to about 37 degrees Celsius."),
           ("key", "retenir", "Temperature control",
            "The **hypothalamus** in the brain monitors blood temperature.\n\n- **Too hot**: sweat glands make **sweat** (evaporation cools the skin); blood vessels near the surface **widen** (vasodilation) so more heat is lost; body hairs lie flat.\n- **Too cold**: less sweat; surface vessels **narrow** (vasoconstriction); hairs stand up; **shivering** (muscle respiration) releases heat."),
           ("key", "retenir", "Blood glucose",
            "After a meal glucose in the blood rises. The **pancreas** secretes **insulin**; the liver turns glucose into **glycogen** and cells take up glucose, so the level falls. When the glucose level is low, the pancreas releases **glucagon**, and the liver changes glycogen back into glucose."),
           ("fig", gfig, "Blood glucose after a meal (illustrative data).", "A line graph: glucose rises from 4.5 to a peak of 7.5 mmol per dm cubed at 30 minutes, then falls back to about 4.6 by 120 minutes."),
           ("key", "attention", "Diabetes (flag for health review)",
            "In **type 1 diabetes** the pancreas does not make enough insulin, so blood glucose stays high. It is controlled by regular insulin and careful diet and exercise. Warning signs (great thirst, frequent urination, weight loss) need a health worker's attention; do not give advice on treatment."),
           ("key", "pieges", "Common mistakes",
            "- Sweating *cools* the body only because the sweat *evaporates*.\n- Vasodilation does not move blood vessels closer to the skin; they widen.\n- Insulin *lowers* blood glucose; glucagon raises it."),
           ("example", "Reading a graph", "Using the glucose graph (0 min: 4.5, 30 min: 7.5, 60 min: 6.0), calculate the rise in glucose in the first 30 minutes and the fall between 30 and 60 minutes.",
            ["Rise = 7.5 − 4.5 = 3.0 mmol/dm³.", "Fall = 7.5 − 6.0 = 1.5 mmol/dm³.", "Insulin is released after the peak and brings the level down."],
            "Rise 3.0 and fall 1.5 mmol/dm³"),
           ("example", "Cold morning in Bamenda", "A girl shivers and her skin looks pale in the cold. Explain both observations.",
            ["Shivering is rapid muscle contraction; respiration in the muscle releases heat.", "Blood vessels near the skin narrow so less blood flows there and less heat is lost, making the skin look pale."],
            "Shivering produces heat and vasoconstriction reduces heat loss.")],
          [("mcq", "Which organ monitors the temperature of the blood?", "hypothalamus", ["pancreas", "kidney", "liver"], "The hypothalamus is the temperature centre in the brain."),
           ("match", "Match the term to its effect.", [("sweating", "cools the skin by evaporation"), ("vasoconstriction", "reduces heat loss"), ("insulin", "lowers blood glucose"), ("glucagon", "raises blood glucose")], "Standard functions."),
           ("num", "Blood glucose peaks at 7.5 mmol/dm³ and normal is 4.5. By how much is it above normal at the peak?", 3.0, "7.5 − 4.5 = 3.0.", 0.01, "mmol/dm³"),
           ("mcq", "Negative feedback means that a change is:", "reversed to bring the level back to normal", ["increased further", "ignored", "stopped by the skin"], "Negative feedback restores the normal level."),
           ("open", "Describe how the body responds when the temperature of the surroundings rises.", "Sweat glands make more sweat, which evaporates and cools the skin; blood vessels near the skin widen (vasodilation) so more heat is lost by radiation; hairs lie flat.", ["1 mark: more sweat/evaporation", "1 mark: vasodilation", "1 mark: hairs flat or reduced shivering"]),
           ("prob", "A person has high blood glucose after a meal.", [("mcq", "Which organ detects it and releases insulin?", "pancreas", ["liver", "kidney", "heart"], "The pancreas makes insulin."), ("mcq", "Which organ stores the excess glucose as glycogen?", "liver", ["stomach", "lungs", "brain"], "The liver stores glycogen."), ("open", "Explain why a person with untreated diabetes has glucose in the urine.", "The blood glucose is so high that the kidney tubules cannot reabsorb all of the filtered glucose, so some passes out in the urine.", ["1 mark: glucose too high / not all reabsorbed", "1 mark: some passes into the urine"], 2)])],
          [("Normal human body temperature is about:", "37 °C", ["25 °C", "30 °C", "45 °C"], "About 37 °C."),
           ("Insulin is made in the:", "pancreas", ["liver", "kidney", "stomach"], "Pancreas."),
           ("When we are cold, surface blood vessels:", "narrow", ["widen", "burst", "stay fixed"], "Vasoconstriction."),
           ("Excess glucose is stored in the liver as:", "glycogen", ["starch", "cellulose", "fat only"], "Glycogen."),
           ("Homeostasis keeps:", "the internal environment constant", ["the external weather constant", "the pulse zero", "the diet constant"], "The internal environment.")],
          ["Glucose curve is invented for teaching, not measured.", "Normal glucose ranges vary by source; only relative changes are used.", "Diabetes content must be reviewed by a health worker."])

    # ------------------------------------------------------------------ coordination
    ch = p.chapter("coordination", "Coordination and response",
                   "GCE O Level Biology — Nervous system, sense organs, hormones, tropisms (to be checked against the official syllabus)")
    arc = flow(["Stimulus|(hot object)", "Receptor|(skin)", "Sensory|neurone", "Relay neurone|(spinal cord)", "Motor|neurone", "Effector|(arm muscle)", "Response|(hand pulled away)"], vertical=True, w=300, size=12, bh=34, gap=14)
    build(ch, "nervous", "The nervous system and reflex actions", 25,
          ["Name the parts of the nervous system and the three types of neurone.",
           "Describe the path of a reflex arc.",
           "Distinguish a reflex action from a voluntary action."],
          [("key", "definition", "The nervous system",
            "The **central nervous system (CNS)** is the **brain** and **spinal cord**. **Nerves** carry electrical impulses between the CNS and the rest of the body. **Receptors** detect stimuli; **effectors** (muscles and glands) carry out the response.\n\nThree types of **neurone**: **sensory** (receptor to CNS), **relay** (inside the CNS) and **motor** (CNS to effector). The gap between two neurones is a **synapse**, crossed by chemical transmitter."),
           ("key", "definition", "Reflex action",
            "A **reflex action** is a fast, automatic response to a stimulus that does not need thought. It protects the body (pulling the hand from a hot pot, blinking, the pupil narrowing). The path it follows is the **reflex arc**."),
           ("fig", arc, "The reflex arc, step by step.", "A vertical flow of seven boxes: stimulus, receptor, sensory neurone, relay neurone in the spinal cord, motor neurone, effector muscle and response."),
           ("key", "retenir", "Reflex versus voluntary action",
            "- **Reflex**: automatic, very fast, involves the spinal cord (or brainstem), not learned.\n- **Voluntary**: you decide; the brain is involved; slower; can be learned (writing, walking, kicking a ball).\n\nThe brain's **cerebrum** controls thought and voluntary action; the **cerebellum** controls balance and coordination; the **medulla** controls breathing and heart rate."),
           ("key", "pieges", "Common mistakes",
            "- A reflex is quick because there are few neurones and no decision, *not* because impulses are faster.\n- Sensory neurones carry impulses *to* the CNS; motor neurones carry them *away*.\n- The effector is the muscle or gland, not the nerve."),
           ("example", "Name the path", "Describe the reflex arc when a person in Buea touches a very hot cooking pot.",
            ["Receptors in the skin detect the heat and send impulses along a sensory neurone to the spinal cord.", "A relay neurone passes the impulse to a motor neurone, which carries it to the arm muscle (effector); the muscle contracts and the hand is pulled away."],
            "Receptor, sensory neurone, relay neurone, motor neurone, effector."),
           ("example", "Reflex or voluntary?", "Classify: (a) blinking when dust enters the eye, (b) writing a letter, (c) saliva when smelling frying plantain.",
            ["(a) automatic and protective: reflex.", "(b) a decision of the brain: voluntary.", "(c) automatic, not thought out: reflex."],
            "(a) reflex, (b) voluntary, (c) reflex.")],
          [("mcq", "Which neurone carries impulses from the receptor to the spinal cord?", "sensory neurone", ["motor neurone", "relay neurone", "effector"], "Sensory neurones go into the CNS."),
           ("match", "Match the part to its function.", [("cerebrum", "voluntary action and thinking"), ("cerebellum", "balance"), ("medulla", "controls breathing rate"), ("motor neurone", "carries impulse to a muscle")], "Standard functions."),
           ("tf", "A reflex action needs a decision by the cerebrum.", False, "Reflexes are automatic and do not need the cerebrum."),
           ("mcq", "The effector in the reflex of pulling a hand from a flame is the:", "arm muscle", ["skin", "spinal cord", "sensory neurone"], "The muscle carries out the response."),
           ("open", "Explain why a reflex action protects the body.", "It is very fast and automatic: few neurones are involved and no thinking is needed, so the body moves away from danger before damage becomes severe.", ["1 mark: fast/automatic", "1 mark: few neurones/no thought", "1 mark: protects from harm"]),
           ("prob", "A doctor taps below a patient's knee and the leg jerks forward.", [("mcq", "The leg movement is a:", "reflex action", ["voluntary action", "hormone response", "growth movement"], "It is automatic."), ("mcq", "The effector is:", "the thigh muscle", ["the knee skin", "the brain", "the sensory neurone"], "The thigh muscle contracts."), ("open", "Describe the path of the impulse.", "Receptor in the tendon, sensory neurone, spinal cord (relay neurone), motor neurone, effector muscle.", ["1 mark: receptor and sensory neurone", "1 mark: spinal cord and motor neurone to effector"], 2)])],
          [("The CNS consists of:", "brain and spinal cord", ["nerves and muscles", "brain and heart", "spinal cord and glands"], "CNS = brain + spinal cord."),
           ("A synapse is:", "a gap between two neurones", ["a type of muscle", "a sense organ", "a hormone"], "Chemical transmitters cross it."),
           ("Which is a reflex?", "blinking in bright light", ["playing football", "reading", "singing"], "Automatic response."),
           ("Which part controls balance?", "cerebellum", ["medulla", "cerebrum", "pancreas"], "Cerebellum."),
           ("Muscles and glands are:", "effectors", ["receptors", "relay neurones", "stimuli"], "They carry out the response.")],
          ["Parts of the brain are given at textbook level only; check the syllabus depth."])

    eye = shapes([CIRCLE(200, 110, 80, fill="lightyellow", width=3), PATH("M 250 48 A 80 80 0 0 1 250 172", stroke="red", width=5),
                  POLY([(135, 110), (145, 85), (155, 110), (145, 135)], fill="lightblue", stroke="blue", width=2),
                  LINE(150, 50, 150, 88, width=5, color="brown"), LINE(150, 132, 150, 170, width=5, color="brown"),
                  RECT(278, 104, 50, 12, fill="orange", stroke="orange", width=1),
                  LINE(122, 110, 60, 110, width=1.2), T(56, 114, "cornea", size=12, anchor="end"),
                  LINE(150, 60, 120, 28, width=1.2), T(116, 28, "iris", size=12, anchor="end"),
                  LINE(150, 90, 100, 60, width=1.2), T(96, 64, "lens", size=12, anchor="end"),
                  LINE(268, 150, 330, 190, width=1.2), T(334, 194, "retina", size=12, anchor="start"),
                  LINE(325, 110, 400, 110, width=1.2), T(404, 114, "optic nerve", size=12, anchor="start")], 500, 215)
    build(ch, "senses", "Sense organs: the eye and the ear", 30,
          ["Label the main parts of the eye and state their functions.",
           "Explain the pupil reflex and accommodation.",
           "Describe the main parts of the ear and how we hear and balance."],
          [("key", "definition", "The eye",
            "- **Cornea**: transparent front; refracts (bends) light.\n- **Iris**: coloured muscle that controls the size of the **pupil**.\n- **Lens**: changes shape to focus light on the retina.\n- **Retina**: contains light receptors: **rods** (dim light) and **cones** (colour, bright light).\n- **Optic nerve**: carries impulses to the brain.\n- **Ciliary muscles** and **suspensory ligaments** hold and change the lens."),
           ("fig", eye, "Section through the eye (schematic).", "A round eyeball with a transparent cornea at the front, a lens behind the pupil, the iris above and below the pupil, a red retina on the back wall and an optic nerve leaving the back."),
           ("key", "retenir", "Pupil reflex and accommodation",
            "**Pupil reflex**: in bright light the circular muscles of the iris contract and the pupil gets smaller (protects the retina); in dim light the radial muscles contract and the pupil widens.\n\n**Accommodation** (focusing):\n- **Near object**: ciliary muscles contract, ligaments slacken, lens becomes thicker and more curved.\n- **Distant object**: ciliary muscles relax, ligaments are taut, lens is thin."),
           ("key", "retenir", "The ear",
            "Sound waves are collected by the **pinna** and travel along the ear canal to the **eardrum**, which vibrates. Three small bones (**ossicles**) pass and increase the vibrations to the **cochlea**, where receptor cells send impulses along the **auditory nerve** to the brain. The **semicircular canals** detect head movement for **balance**. The **Eustachian tube** equalises air pressure."),
           ("key", "pieges", "Common mistakes",
            "- The *retina*, not the lens, contains the light receptors.\n- A *thick* lens focuses *near* objects.\n- The cochlea is for hearing; the semicircular canals are for balance.\n- Do not push objects into the ear; loud noise can damage hearing (health review)."),
           ("example", "Bright light", "You walk out of a dark room into the sun at noon in Douala. Describe what happens to your pupils and why.",
            ["Bright light is the stimulus; receptors in the retina send impulses to the brain and then to the iris.", "The circular muscles of the iris contract, making the pupil smaller, so less light reaches the retina."],
            "The pupils narrow to protect the retina."),
           ("example", "Reading a book", "You look from the blackboard to your notebook. How does the lens change?",
            ["The notebook is a near object.", "The ciliary muscles contract and the suspensory ligaments slacken, so the lens becomes thicker and bends light more to focus it on the retina."],
            "The lens becomes thicker (more curved).")],
          [("mcq", "Which part of the eye contains rods and cones?", "retina", ["cornea", "lens", "iris"], "The retina holds the light receptors."),
           ("match", "Match each part to its function.", [("iris", "controls pupil size"), ("optic nerve", "carries impulses to the brain"), ("cochlea", "converts vibrations into impulses"), ("semicircular canals", "detect head movement")], "Each part is matched to its job."),
           ("tf", "To look at a distant object the lens becomes thicker.", False, "A distant object needs a thin lens."),
           ("mcq", "In bright light the pupil:", "gets smaller", ["gets larger", "stays the same", "turns red"], "The circular muscles of the iris contract."),
           ("open", "Describe how sound is transmitted from the air to the brain.", "The pinna collects sound; the eardrum vibrates; the ossicles pass the vibrations to the cochlea; receptor cells in the cochlea send impulses along the auditory nerve to the brain.", ["1 mark: eardrum vibrates", "1 mark: ossicles/cochlea", "1 mark: impulses along auditory nerve"]),
           ("prob", "A boy at a football match in Bamenda looks at the ball and then at his watch.", [("mcq", "Which muscles change the shape of the lens?", "ciliary muscles", ["iris muscles", "eyelid muscles", "optic muscles"], "Ciliary muscles act on the suspensory ligaments."), ("mcq", "When he looks at his watch the lens:", "becomes thicker", ["becomes thinner", "stops working", "moves backwards"], "A near object needs a thicker lens."), ("open", "Why do cones work only in bright light?", "Cones are less sensitive than rods and need more light; rods work in dim light.", ["1 mark: cones need bright light", "1 mark: rods are more sensitive"], 2)])],
          [("The transparent part at the front of the eye is the:", "cornea", ["retina", "iris", "lens"], "Cornea."),
           ("The structure that detects sound vibrations is the:", "cochlea", ["eardrum", "pinna", "lens"], "Cochlea."),
           ("Rods work best in:", "dim light", ["bright light", "colour", "darkness only"], "Rods are sensitive."),
           ("The eardrum:", "vibrates when sound arrives", ["makes sound", "detects balance", "controls light"], "It vibrates."),
           ("A thick lens is used to see:", "near objects", ["distant objects", "colours", "dark objects"], "Near objects.")],
          ["Eye and ear diagrams are schematic (not to scale).", "Hearing-protection comment must be reviewed by a health worker."])

    tropism = shapes([LINE(80, 190, 80, 90, width=6, color="green"), T(80, 215, "no light", size=12),
                      LINE(250, 190, 250, 140, width=6, color="green"), LINE(250, 140, 280, 100, width=6, color="green"), T(250, 215, "light from the right", size=12),
                      LINE(400, 60, 340, 60, arrow="end", width=3, color="orange"), LINE(400, 80, 340, 80, arrow="end", width=3, color="orange")], 480, 230)
    build(ch, "hormones", "Hormones and plant responses", 25,
          ["Define a hormone and compare nervous and hormonal control.",
           "Name important hormones and their effects.",
           "Explain phototropism and gravitropism using auxins."],
          [("key", "definition", "Hormones",
            "A **hormone** is a chemical substance made in an **endocrine gland** and carried by the **blood** to **target organs**, where it changes their activity. Examples: **insulin** and glucagon (pancreas), **adrenaline** (adrenal glands), **ADH** (pituitary), **testosterone** (testes), **oestrogen** and progesterone (ovaries)."),
           ("key", "retenir", "Nerves compared with hormones",
            "- **Nerves**: electrical impulses along neurones; very fast; short-lasting effect; to a precise place.\n- **Hormones**: chemicals in the blood; slower; longer-lasting effect; may act on several organs.\n\n**Adrenaline** prepares the body for 'fight or flight': the heart beats faster, breathing increases, pupils widen and the liver releases glucose."),
           ("fig", grid(["NERVES|impulses along neurones|fast, short effect", "HORMONES|chemicals in blood|slower, longer effect"], cols=1, w=300, bh=60, size=12), "Nerves and hormones compared.", "Two boxes: nerves with fast electrical impulses and a short effect; hormones with chemicals in the blood, slower and longer lasting."),
           ("key", "retenir", "Plant responses (tropisms)",
            "A **tropism** is a growth response of a plant to a directional stimulus. Plant hormones called **auxins**, made at the shoot tip, control it.\n\n- **Phototropism**: shoots grow towards light. Auxin moves to the shaded side, making cells there elongate more, so the shoot bends towards the light.\n- **Gravitropism**: roots grow downwards (positive); shoots grow upwards (negative)."),
           ("fig", tropism, "A shoot grows towards the light.", "A straight shoot in no light and a second shoot that bends to the right towards arrows representing light coming from the right."),
           ("key", "pieges", "Common mistakes",
            "- Hormones do *not* travel in nerves; they travel in the *blood*.\n- Auxin makes cells on the *shaded* side grow *longer*; it does not make the lit side shrink.\n- Plants have no nerves or glands; their hormones move from cell to cell."),
           ("example", "Fight or flight", "A boy meets a barking dog and his heart pounds. Name the hormone and two effects.",
            ["The adrenal glands release adrenaline into the blood.", "Heart rate and breathing rate increase; the liver releases glucose for energy."],
            "Adrenaline; faster heart rate and more glucose in the blood."),
           ("example", "Seedling on a window", "A maize seedling on a window sill in Limbe leans towards the window. Explain.",
            ["Light from one side is the stimulus (phototropism).", "Auxin collects on the shaded side, cells there elongate faster, so the stem bends towards the light."],
            "Unequal auxin distribution causes bending towards the light.")],
          [("mcq", "A hormone is carried from a gland to its target organ by the:", "blood", ["nerves", "xylem", "bones"], "Hormones travel in the blood."),
           ("match", "Match the gland to its hormone.", [("pancreas", "insulin"), ("pituitary", "ADH"), ("ovary", "oestrogen"), ("testis", "testosterone")], "Standard gland-hormone pairs."),
           ("tf", "Auxin accumulates on the lit side of a shoot.", False, "It accumulates on the shaded side."),
           ("mcq", "Which is an effect of adrenaline?", "faster heart rate", ["lower blood glucose", "slower breathing", "narrower airways"], "Adrenaline increases heart rate."),
           ("open", "Give three differences between nervous and hormonal control.", "Nerves use electrical impulses, hormones use chemicals in the blood; nervous effects are fast and short-lived, hormonal effects slower and longer-lasting; nerves act on a precise target, hormones may affect many organs.", ["1 mark each, maximum 3"]),
           ("prob", "Seedlings are grown in three conditions: A in the dark, B with light from one side, C with light from above.", [("mcq", "Seedling B will:", "bend towards the light", ["bend away from the light", "not grow", "grow downwards"], "Phototropism."), ("mcq", "Seedling C will grow:", "straight upwards", ["sideways", "downwards", "in a spiral"], "Equal light on all sides means equal auxin."), ("open", "Explain the result for B using auxin.", "Auxin moves to the shaded side, where cells elongate more, so the shoot bends towards the light.", ["1 mark: auxin on the shaded side", "1 mark: cells there grow faster so shoot bends"], 2)])],
          [("The plant hormone for growth responses is:", "auxin", ["insulin", "adrenaline", "ADH"], "Auxin."),
           ("Roots grow:", "towards gravity", ["towards light", "against gravity", "randomly"], "Positive gravitropism."),
           ("Hormones are made in:", "endocrine glands", ["muscles", "nerves", "xylem"], "Endocrine glands."),
           ("Which control is fastest?", "nervous", ["hormonal", "auxin", "digestive"], "Nerve impulses are fast."),
           ("A tropism is:", "a growth response to a stimulus from one direction", ["a movement of the whole animal", "a hormone", "a nerve"], "Definition.")],
          ["Auxin explanation is the standard simplified one (shaded-side elongation).", "Check syllabus scope for gibberellins etc.; not included."])
