from biolib import *


def add(p):
    # ------------------------------------------------------------------ support and movement
    ch = p.chapter("movement", "Support and movement",
                   "GCE O Level Biology — Skeleton, joints and muscles (to be checked against the official syllabus)")
    arm = S([LINE(60, 100, 200, 100, width=10, color="brown"), CIRCLE(205, 100, 14, fill="lightyellow", width=2), LINE(210, 100, 330, 140, width=8, color="brown"),
             PATH("M 90 90 C 120 55 170 55 195 92", stroke="red", width=6), PATH("M 90 112 C 120 135 170 135 195 110", stroke="blue", width=5),
             lab(140, 60, 120, 22, "biceps (contracts to bend)", anchor="start", size=12), lab(140, 130, 120, 175, "triceps (relaxes)", anchor="start", size=12),
             lab(205, 114, 300, 190, "elbow (hinge joint)", anchor="start", size=12), T(40, 100, "humerus", size=12, anchor="end")], 480, 205)
    build(ch, "skeleton", "Skeleton, joints and muscles", 25,
          ["State the functions of the skeleton.",
           "Describe the structure of a synovial joint and the types of joint.",
           "Explain how antagonistic muscles move a limb."],
          [("key", "definition", "Functions of the skeleton",
            "The skeleton gives **support**, **protection** (the skull protects the brain, the ribs protect the heart and lungs), **movement** (bones act as levers), makes **blood cells** in the red bone marrow and **stores minerals** such as calcium and phosphate."),
           ("key", "retenir", "Joints",
            "A **joint** is where two bones meet. In a **synovial joint** (such as the knee) the bone ends are covered with smooth **cartilage**, enclosed in a capsule that makes **synovial fluid** to lubricate the joint. **Ligaments** join bone to bone; **tendons** join muscle to bone.\n\n- **Ball-and-socket** (shoulder, hip): movement in all directions.\n- **Hinge** (elbow, knee): movement in one plane only."),
           ("fig", arm, "The arm: antagonistic muscles at the elbow.", "A drawing of the upper arm and forearm meeting at the elbow, with the biceps above and the triceps below the humerus."),
           ("key", "retenir", "Antagonistic muscles",
            "Muscles can only **pull** (contract) and never push. They work in pairs that do opposite jobs: **antagonistic muscles**.\n\n- To **bend** the arm: the **biceps contracts** and the triceps relaxes.\n- To **straighten** it: the **triceps contracts** and the biceps relaxes.\n\nMuscle tissue needs a good supply of oxygen and glucose for respiration."),
           ("key", "pieges", "Common mistakes",
            "- Ligaments join *bone to bone*; tendons join *muscle to bone*.\n- Muscles do not push: the opposite muscle pulls the bone back.\n- Cartilage is not bone: it is smooth, flexible and covers bone ends."),
           ("example", "Bend and straighten", "A girl lifts a bag of cassava from the ground with a bent arm and then lowers it with a straight arm. Which muscle contracts in each case?",
            ["Bending the arm: the biceps contracts and the triceps relaxes.", "Straightening the arm: the triceps contracts and the biceps relaxes."],
            "Biceps to bend, triceps to straighten."),
           ("example", "Why the joint slides easily", "A footballer's knee moves smoothly for years. Name two features of the joint that allow this.",
            ["Smooth cartilage covers the ends of the bones, reducing friction.", "Synovial fluid lubricates the joint."],
            "Cartilage and synovial fluid.")],
          [("mcq", "Which structure joins muscle to bone?", "tendon", ["ligament", "cartilage", "marrow"], "Tendons connect muscle to bone."),
           ("match", "Match each part to its function.", [("ligament", "joins bone to bone"), ("synovial fluid", "lubricates the joint"), ("cartilage", "reduces friction at bone ends"), ("red bone marrow", "makes blood cells")], "Standard functions."),
           ("tf", "A hinge joint such as the knee allows movement in all directions.", False, "Only the ball-and-socket joint moves in all directions."),
           ("mcq", "When the triceps contracts the arm:", "straightens", ["bends", "rotates", "shortens"], "The triceps extends the elbow."),
           ("open", "Explain why muscles are arranged in antagonistic pairs.", "Muscles can only pull when they contract, so one muscle is needed to move a bone in one direction and a second muscle to pull it back the other way.", ["1 mark: muscles only pull", "1 mark: second muscle pulls bone back", "1 mark: example e.g. biceps and triceps"]),
           ("prob", "A student studies the elbow and the hip.", [("mcq", "The hip joint is a:", "ball-and-socket joint", ["hinge joint", "fixed joint", "pivot only"], "The hip allows wide movement."), ("mcq", "The ribs mainly:", "protect the heart and lungs", ["make blood", "store cartilage", "produce hormones"], "The ribs protect the organs in the chest."), ("open", "Give one function of the skeleton not related to movement.", "Support of the body, protection of organs, making blood cells or storing minerals.", ["1 mark for any correct function"], 1)])],
          [("Which pair are antagonistic muscles?", "biceps and triceps", ["biceps and humerus", "triceps and ligament", "tendon and bone"], "They have opposite actions."),
           ("Ligaments connect:", "bone to bone", ["muscle to bone", "muscle to muscle", "skin to bone"], "Ligaments hold the joint."),
           ("Synovial fluid:", "lubricates joints", ["makes blood", "is a hormone", "carries oxygen"], "It reduces friction."),
           ("The skull protects the:", "brain", ["lungs", "heart", "kidney"], "Skull = brain."),
           ("Red blood cells are made in the:", "red bone marrow", ["liver only", "kidney", "lungs"], "Bone marrow.")],
          ["Arm drawing is schematic; muscle shapes are indicative."])

    # ------------------------------------------------------------------ reproduction in plants
    ch = p.chapter("plant-repro", "Reproduction in flowering plants",
                   "GCE O Level Biology — Flower structure, pollination, fertilisation, seeds, vegetative propagation (to be checked against the official syllabus)")
    flower = S([POLY([(172, 215), (115, 150), (120, 80), (165, 160)], fill="pink", stroke="red", width=2), POLY([(228, 215), (285, 150), (280, 80), (235, 160)], fill="pink", stroke="red", width=2),
                CIRCLE(200, 195, 28, fill="lightgreen", stroke="green", width=2), CIRCLE(192, 195, 6, fill="orange", width=1), CIRCLE(208, 195, 6, fill="orange", width=1),
                LINE(200, 167, 200, 96, width=3, color="green"), CIRCLE(200, 90, 8, fill="yellow", width=2),
                LINE(184, 190, 176, 115, width=2), RECT(168, 98, 16, 18, fill="orange", width=1.5), LINE(216, 190, 224, 115, width=2), RECT(216, 98, 16, 18, fill="orange", width=1.5),
                lab(208, 88, 330, 40, "stigma", size=12), lab(202, 130, 330, 80, "style", size=12), lab(222, 190, 330, 130, "ovary", size=12), lab(210, 198, 330, 170, "ovule", size=12),
                lab(168, 106, 105, 40, "anther", size=12), lab(178, 150, 105, 80, "filament", size=12), lab(135, 120, 105, 120, "petal", size=12), lab(172, 213, 105, 190, "sepal", size=12)], 460, 235)
    build(ch, "flower", "The flower and pollination", 30,
          ["Name the parts of a flower and their functions.",
           "Define pollination and compare insect- and wind-pollinated flowers.",
           "Describe fertilisation in a flowering plant."],
          [("key", "definition", "Parts of a flower",
            "- **Sepals**: protect the bud. **Petals**: attract insects (in insect-pollinated flowers).\n- **Stamen** (male): **anther** makes **pollen grains** (male gametes inside); **filament** holds it up.\n- **Carpel** (female): **stigma** receives pollen; **style** joins stigma to **ovary**; the ovary contains **ovules** (each holds an egg cell)."),
           ("fig", flower, "Longitudinal section of a flower (schematic).", "A flower with two pink petals, a green ovary with two ovules, a style topped by a yellow stigma and two stamens, each with an anther on a filament; leader lines label each part."),
           ("key", "definition", "Pollination",
            "**Pollination** is the transfer of pollen from an **anther** to a **stigma** of a flower of the same species. **Self-pollination**: on the same plant. **Cross-pollination**: to a different plant of the same species; this gives more variation.\n\nAgents of pollination are insects (bees) and wind."),
           ("key", "retenir", "Insect- and wind-pollinated flowers",
            "- **Insect-pollinated**: large, brightly coloured petals, scent and **nectar**; small amounts of sticky or spiny pollen; stigma sticky and inside the flower.\n- **Wind-pollinated** (maize, grasses): small, dull flowers without nectar or scent; anthers hang outside; huge amounts of **light, smooth pollen**; **feathery** stigmas outside to catch pollen."),
           ("key", "retenir", "Fertilisation",
            "A pollen grain lands on a compatible stigma and grows a **pollen tube** down the style to the ovary and into an ovule. The **male nucleus** fuses with the **egg nucleus** in the ovule: this is **fertilisation** and it forms a **zygote**.\n\nAfter fertilisation the **ovule becomes the seed** and the **ovary becomes the fruit**; the petals and other parts wither."),
           ("key", "pieges", "Common mistakes",
            "- Pollination is *not* fertilisation: pollination is transfer of pollen; fertilisation is the fusion of nuclei.\n- Pollen is made in the *anther*, not the filament.\n- Wind-pollinated flowers do not need bright petals."),
           ("example", "Which kind of flower?", "A flower has small green petals, long stamens hanging out of the flower and feathery stigmas. How is it pollinated and why?",
            ["Small dull petals give no attraction for insects.", "Hanging anthers release pollen easily to the wind, and feathery stigmas trap airborne pollen."],
            "By wind."),
           ("example", "From flower to fruit", "In a pawpaw flower fertilisation has taken place. State what the ovule and ovary become.",
            ["After fertilisation the ovule develops into the seed.", "The ovary wall develops into the fruit."],
            "Ovule to seed; ovary to fruit.")],
          [("mcq", "Which part of the flower receives the pollen?", "stigma", ["anther", "ovule", "filament"], "The stigma receives pollen."),
           ("match", "Match each part to its function.", [("anther", "makes pollen"), ("stigma", "receives pollen"), ("ovary", "contains ovules"), ("petal", "attracts insects")], "Standard functions."),
           ("tf", "Pollination and fertilisation mean the same thing.", False, "Pollination is the transfer of pollen; fertilisation is fusion of gametes."),
           ("mcq", "A feature of a wind-pollinated flower is:", "feathery stigmas", ["bright petals", "nectar", "sticky pollen"], "Feathery stigmas catch pollen from the wind."),
           ("open", "Describe what happens from the arrival of a pollen grain on the stigma to fertilisation.", "The pollen grain grows a pollen tube down the style to the ovary and into the ovule; the male nucleus travels down the tube and fuses with the egg nucleus to form a zygote.", ["1 mark: pollen tube grows down style", "1 mark: reaches the ovule", "1 mark: male nucleus fuses with egg nucleus"]),
           ("prob", "A student compares a hibiscus flower (large, red petals) and a maize flower (small, dull).", [("mcq", "The hibiscus is likely to be pollinated by:", "insects or birds", ["wind", "water", "rain"], "Large coloured petals attract animals."), ("mcq", "Which flower makes more pollen?", "maize", ["hibiscus", "both equally", "neither"], "Wind pollination is wasteful so large amounts of pollen are made."), ("open", "Explain why cross-pollination is an advantage.", "It produces offspring with a mixture of genes from two parents, increasing variation and the chance that some survive changes.", ["1 mark: gives variation", "1 mark: advantage in survival"], 2)])],
          [("The male part of the flower is the:", "stamen", ["carpel", "sepal", "stigma"], "Stamen = anther + filament."),
           ("After fertilisation the ovule becomes the:", "seed", ["fruit", "flower", "pollen"], "Ovule to seed."),
           ("Nectar attracts:", "insects", ["wind", "water", "soil"], "Insect-pollinated."),
           ("The pollen tube grows down the:", "style", ["filament", "petal", "sepal"], "Style."),
           ("Transfer of pollen from anther to stigma is:", "pollination", ["fertilisation", "germination", "transpiration"], "Pollination.")],
          ["Flower diagram is schematic.", "Petal count/shape is not typical of any single species."])

    germ = bars([("A water+air+warm", 18, "green"), ("B no water", 0, "red"), ("C no air (under water)", 1, "orange"), ("D cold (fridge)", 2, "blue")], unit="seeds germinated out of 20 (teaching data)", w=460, h=240)
    build(ch, "seeds", "Seeds, germination and vegetative propagation", 25,
          ["Describe seed and fruit dispersal.",
           "State the conditions needed for germination and design an experiment.",
           "Describe asexual reproduction (vegetative propagation) and compare it with sexual reproduction."],
          [("key", "definition", "Seed dispersal",
            "**Dispersal** carries seeds away from the parent plant, which reduces competition for light, water and minerals and spreads the species. Methods: **wind** (winged or feathery seeds); **animals** (hooked fruits stick to fur; fleshy fruits are eaten and seeds pass out in faeces); **water** (coconut); **explosive** (pods dry and split open, throwing seeds away)."),
           ("key", "retenir", "Conditions for germination",
            "Seeds need **water** (to activate enzymes), **oxygen** (for respiration), and a suitable **temperature** (warm). Light is *not* needed for most seeds. Stored food in the cotyledons or endosperm feeds the embryo until the leaves can photosynthesise."),
           ("fig", germ, "An experiment on germination (teaching data).", "A bar chart: 18 seeds out of 20 germinate with water, air and warmth; 0 with no water; 1 without air; 2 in the cold."),
           ("key", "retenir", "Vegetative propagation",
            "**Asexual reproduction** produces new plants from **one parent** without gametes; the offspring are genetically identical (**clones**). Examples: **cassava stem cuttings**, **banana and plantain suckers**, **yam setts** (pieces of tuber), sugar-cane cuttings.\n\nAdvantages: fast, keeps good qualities, no pollination needed. Disadvantage: no variation, so a disease can affect the whole crop."),
           ("key", "pieges", "Common mistakes",
            "- Germination needs *oxygen*; seeds under water-logged soil may rot.\n- Light and soil are *not* necessary for germination.\n- Clones are identical; sexual reproduction gives variation."),
           ("example", "Experiment design", "Design a fair test to show that seeds need water to germinate.",
            ["Set up two dishes with 20 identical bean seeds each: one with damp cotton wool (test) and one with dry cotton wool (control).", "Keep temperature, air supply and time the same, so water is the only difference; count germinated seeds after a few days."],
            "Only water is changed; the damp dish germinates and the dry dish does not."),
           ("example", "Percent germinated", "In a farm in Mbouda, 18 of 20 bean seeds germinate in the warm damp dish and 2 of 20 in a cold dish. Calculate percentage germination in each.",
            ["Warm dish: 18 ÷ 20 × 100 = 90 %.", "Cold dish: 2 ÷ 20 × 100 = 10 %."],
            "90 % and 10 %")],
          [("mcq", "Which of these is NOT needed for germination?", "light", ["water", "oxygen", "warmth"], "Most seeds do not need light."),
           ("num", "In a germination test 36 of 40 seeds germinate. What is the percentage germination?", 90, "36 ÷ 40 × 100 = 90 %.", 0.1, "%"),
           ("match", "Match the plant to its method of reproduction.", [("cassava", "stem cuttings"), ("plantain", "suckers"), ("maize", "seeds from pollination by wind"), ("coconut", "water dispersal of fruit")], "Standard examples."),
           ("mcq", "Why is vegetative propagation used for cassava?", "the new plants are identical to the good parent", ["it creates new varieties", "it needs pollination", "it makes seeds"], "It maintains desirable characteristics."),
           ("open", "Give three advantages of seed dispersal for a plant species.", "Less competition with the parent for light, water and nutrients; spreads the species to new areas; reduces the spread of disease from the parent.", ["1 mark each, maximum 3"]),
           ("prob", "Three dishes of 20 seeds: A has wet cotton wool in a warm room, B has dry cotton wool in a warm room, C has wet cotton wool in a fridge.", [("mcq", "Which dishes show that water is needed?", "A and B", ["A and C", "B and C", "A only"], "A and B differ only in water."), ("mcq", "Which dishes show the effect of temperature?", "A and C", ["A and B", "B and C", "B only"], "A and C differ only in temperature."), ("open", "Why must the number of seeds be the same in each dish?", "So the results are comparable and the test is fair.", ["1 mark: fair test / comparison"], 2)])],
          [("Which gas do germinating seeds need?", "oxygen", ["nitrogen", "helium", "methane"], "For respiration."),
           ("A clone is:", "genetically identical to its parent", ["different from its parent", "a seed", "a pollen grain"], "Asexual reproduction."),
           ("Coconuts are mainly dispersed by:", "water", ["wind", "explosion", "insects"], "Floating fruit."),
           ("Which organ stores food for the seed embryo?", "cotyledon", ["petal", "stigma", "root hair"], "Cotyledons or endosperm."),
           ("An advantage of cassava cuttings is:", "faster than seeds", ["more variation", "needs pollen", "needs insects"], "Cuttings are quick.")],
          ["Germination bar-chart values are invented teaching data.", "Plant examples (cassava, plantain, yam) are common in Cameroon; check which the syllabus prefers."])

    # ------------------------------------------------------------------ human reproduction
    ch = p.chapter("human-repro", "Reproduction in humans",
                   "GCE O Level Biology — Human reproduction, menstrual cycle, pregnancy, STIs and HIV (to be checked against the official syllabus; for health review)")
    fem = S([POLY([(160, 80), (240, 80), (210, 140), (190, 140)], fill="pink", stroke="red", width=2),
             LINE(160, 82, 100, 70, width=3), LINE(240, 82, 300, 70, width=3), CIRCLE(90, 72, 14, fill="lightorange", stroke="orange", width=2), CIRCLE(310, 72, 14, fill="lightorange", stroke="orange", width=2),
             RECT(192, 140, 16, 20, fill="lightyellow", width=2), RECT(188, 160, 24, 55, fill="lightyellow", stroke="brown", width=2),
             lab(90, 60, 40, 22, "ovary", size=12, anchor="start"), lab(130, 76, 60, 50, "oviduct", size=12, anchor="start"),
             lab(220, 100, 320, 125, "uterus", size=12), lab(208, 150, 320, 160, "cervix", size=12), lab(212, 190, 320, 195, "vagina", size=12)], 420, 225)
    build(ch, "reproductive-system", "The human reproductive systems and fertilisation", 30,
          ["Name the parts of the male and female reproductive systems and their functions.",
           "Describe the structure of sperm and egg cells.",
           "Describe fertilisation and implantation."],
          [("key", "retenir", "Male reproductive system",
            "- **Testes** (in the scrotum, slightly cooler than the body): make **sperm** and the hormone **testosterone**.\n- **Sperm duct**: carries sperm to the urethra; **glands** (including the prostate) add fluid to form **semen**.\n- **Urethra** inside the **penis**: carries semen (and urine, never at the same time) out of the body."),
           ("key", "retenir", "Female reproductive system",
            "- **Ovaries**: make **egg cells (ova)** and the hormones **oestrogen** and **progesterone**.\n- **Oviducts** (fallopian tubes): carry eggs to the uterus; **fertilisation** takes place here.\n- **Uterus** (womb): lining receives the embryo; **cervix**: ring of muscle at the base of the uterus; **vagina**: receives semen."),
           ("fig", fem, "Female reproductive system (schematic, front view).", "A pear-shaped uterus with two oviducts reaching to round ovaries, a short cervix below and the vagina leading out."),
           ("key", "retenir", "Gametes",
            "- **Sperm**: small, with a **tail** to swim, a head containing the nucleus and an **acrosome** with enzymes that digest the egg's coat, and many **mitochondria** for energy.\n- **Egg**: much larger, contains a food store (yolk-like cytoplasm), a jelly layer and the nucleus; it cannot move by itself.\n\nBoth contain half the normal number of chromosomes (23)."),
           ("key", "definition", "Fertilisation and implantation",
            "**Fertilisation** is the fusion of the nucleus of a sperm with the nucleus of an egg to form a **zygote** (46 chromosomes) in the oviduct. The zygote divides repeatedly to form a ball of cells (**embryo**) that moves to the uterus. **Implantation** is the sinking of the embryo into the thick uterus lining."),
           ("key", "pieges", "Common mistakes",
            "- The urethra carries both urine and semen in males, but not at the same time.\n- Fertilisation happens in the oviduct, not the uterus.\n- The sex of the baby depends on the sperm: X gives a girl, Y a boy (see genetics)."),
           ("example", "Fertilised egg chromosomes", "A human sperm cell has 23 chromosomes and an egg has 23. How many chromosomes does the zygote have and why?",
            ["Each gamete has half the full number.", "At fertilisation the two nuclei fuse: 23 + 23 = 46."],
            "46 chromosomes, restoring the full number."),
           ("example", "Where does it happen?", "Name the place where (a) eggs are made, (b) fertilisation occurs, (c) the embryo develops.",
            ["(a) Eggs are made in the ovaries.", "(b) Fertilisation occurs in the oviduct.", "(c) The embryo implants and develops in the uterus."],
            "(a) ovary, (b) oviduct, (c) uterus")],
          [("mcq", "Where does fertilisation normally occur?", "oviduct", ["uterus", "vagina", "ovary"], "The sperm meets the egg in the oviduct."),
           ("match", "Match each organ to its function.", [("testis", "makes sperm"), ("ovary", "makes eggs"), ("uterus", "holds the developing baby"), ("sperm duct", "carries sperm to the urethra")], "Standard functions."),
           ("num", "The zygote has 46 chromosomes. How many chromosomes are in each human sperm cell?", 23, "Gametes are haploid: 46 ÷ 2 = 23.", 0),
           ("mcq", "The acrosome of a sperm contains:", "enzymes that digest the egg's outer layer", ["a food store", "mitochondria only", "hormones"], "The enzymes let the sperm enter the egg."),
           ("open", "Explain two ways in which a sperm cell is adapted to its function.", "It has a tail for swimming to the egg; many mitochondria release energy for movement; the acrosome has enzymes to penetrate the egg; the small size allows movement.", ["1 mark each, maximum 2, with the function explained"], 2),
           ("prob", "A diagram of the female reproductive system is labelled A (ovary), B (oviduct), C (uterus) and D (vagina).", [("mcq", "Where does the embryo implant?", "C", ["A", "B", "D"], "The uterus lining."), ("mcq", "Where are eggs released from?", "A", ["B", "C", "D"], "The ovary."), ("open", "State what happens in B.", "Fertilisation, and cilia and muscles move the egg or embryo towards the uterus.", ["1 mark: fertilisation", "1 mark: transport to uterus"], 2)])],
          [("Sperm are made in the:", "testes", ["prostate", "bladder", "urethra"], "Testes."),
           ("The fusion of male and female nuclei is:", "fertilisation", ["ovulation", "menstruation", "implantation"], "Fertilisation."),
           ("The zygote has:", "46 chromosomes", ["23 chromosomes", "92 chromosomes", "12 chromosomes"], "Diploid."),
           ("The uterus lining receives the:", "embryo", ["sperm", "urine", "hormone"], "Implantation."),
           ("Which hormone is made by the testes?", "testosterone", ["oestrogen", "insulin", "ADH"], "Testosterone.")],
          ["Content is anatomical and factual; to be reviewed by a health worker/teacher for age-appropriateness.", "Chromosome number 46 / 23 is standard."])

    # menstrual cycle & pregnancy
    x = lambda d: 30 + d * 14.2
    cyc = S([RECT(x(0), 70, x(5) - x(0), 40, fill="pink", stroke="red"), RECT(x(5), 70, x(14) - x(5), 40, fill="lightorange", stroke="orange"), RECT(x(14), 70, x(28) - x(14), 40, fill="lightyellow", stroke="orange"),
             T(x(2.5), 95, "period", size=11), T(x(9.5), 95, "lining rebuilds", size=11), T(x(21), 95, "lining maintained", size=11),
             LINE(x(14), 50, x(14), 70, arrow="end", width=2, color="red"), T(x(14), 42, "ovulation (about day 14)", size=12),
             T(x(0), 130, "day 1", size=11, anchor="start"), T(x(28), 130, "day 28", size=11, anchor="end")], 440, 150)
    preg = S([CIRCLE(160, 105, 85, fill="pink", stroke="red", width=2), CIRCLE(150, 105, 30, fill="lightyellow", width=2), CIRCLE(150, 105, 55, fill="none", stroke="blue", width=1.5),
              RECT(230, 80, 30, 50, fill="red", stroke="red", radius=6), LINE(180, 110, 230, 105, width=3, color="orange"),
              lab(150, 76, 330, 25, "baby (fetus)", size=12), lab(150, 50, 330, 55, "amniotic fluid", size=12), lab(245, 105, 330, 105, "placenta", size=12), lab(205, 108, 330, 150, "umbilical cord", size=12)], 480, 210)
    build(ch, "pregnancy", "The menstrual cycle, pregnancy and birth", 30,
          ["Describe the menstrual cycle and the roles of oestrogen and progesterone.",
           "Describe the development of the embryo, the placenta and birth.",
           "State the importance of antenatal care and breast-feeding."],
          [("key", "definition", "Menstrual cycle",
            "The **menstrual cycle** is a cycle of about **28 days** (it varies between women). Around **day 14** an egg is released from an ovary: **ovulation**. The uterus lining thickens in preparation for an embryo. If no embryo implants, the lining breaks down and leaves the body through the vagina in the **period** (menstruation, about days 1-5)."),
           ("fig", cyc, "A 28-day cycle (average).", "A bar over 28 days: a pink period of about days 1 to 5, an orange phase when the lining rebuilds to day 14 with an arrow marking ovulation, and a yellow phase when the lining is maintained until day 28."),
           ("key", "retenir", "Hormones and pregnancy",
            "**Oestrogen** (from the ovary) helps rebuild the lining and triggers ovulation; **progesterone** maintains the lining. If the egg is fertilised and implants, progesterone stays high, the lining is kept and the periods stop. A missed period can be an early sign of pregnancy."),
           ("fig", preg, "A baby in the uterus (schematic).", "A uterus containing a baby surrounded by amniotic fluid, joined by an umbilical cord to the placenta on the uterus wall."),
           ("key", "retenir", "Placenta, birth and care",
            "The **placenta** brings the mother's and baby's blood very close so that **oxygen, glucose, amino acids and antibodies** pass to the baby and **carbon dioxide and urea** pass to the mother. The two bloods do **not** mix. The **umbilical cord** joins baby to placenta. **Amniotic fluid** protects the baby from knocks.\n\nPregnancy lasts about **40 weeks**. At birth the uterus muscles contract (labour), the cervix widens and the baby is born."),
           ("key", "attention", "Antenatal care and breast-feeding (flag for health review)",
            "Pregnant women should visit a clinic regularly, eat a balanced diet and avoid smoking, alcohol and untested medicines, which can harm the baby. **Breast milk** contains the right nutrients and **antibodies**; health services recommend exclusive breast-feeding for the first six months. HIV-positive mothers should follow the advice of their health worker."),
           ("example", "Fertile days", "A cycle is 28 days long and ovulation occurs on day 14. If a period started on 1 March, on which date does ovulation occur, and when does the next period start?",
            ["Day 14 counted from 1 March (day 1) is 14 March.", "The next period starts on day 29, which is 29 March (1 March + 28 days)."],
            "Ovulation about 14 March; next period about 29 March."),
           ("example", "Why the blood does not mix", "Explain why it is important that the blood of the mother and the baby do not mix.",
            ["The mother's blood pressure is too high for the baby's delicate capillaries, and the blood groups of mother and baby may differ.", "Exchange occurs by diffusion and active transport across thin walls instead."],
            "Exchange across thin walls protects the baby without mixing the bloods.")],
          [("mcq", "Ovulation occurs about:", "day 14 of a 28-day cycle", ["day 1", "day 28", "day 5"], "Ovulation is mid-cycle."),
           ("match", "Match each structure to its role in pregnancy.", [("placenta", "exchange of food and oxygen"), ("umbilical cord", "joins baby to placenta"), ("amniotic fluid", "protects from knocks"), ("progesterone", "maintains the uterus lining")], "Standard roles."),
           ("num", "Pregnancy lasts about 40 weeks. How many days is this?", 280, "40 × 7 = 280 days.", 0, "days"),
           ("mcq", "Which substance passes from the baby's blood to the mother's in the placenta?", "carbon dioxide", ["glucose", "oxygen", "antibodies"], "Waste passes to the mother; nutrients and oxygen go the other way."),
           ("open", "Describe how the placenta is adapted for exchange between mother and baby.", "It has a large surface area (many villi), thin walls so substances diffuse quickly and a good blood supply from the mother and baby; the bloods do not mix.", ["1 mark: large surface area", "1 mark: thin wall / short distance", "1 mark: rich blood supply"]),
           ("prob", "A woman's cycles are regular at 28 days. Her last period began on 5 June.", [("num", "On which day of June will ovulation be expected (day 14 counted from 5 June as day 1)?", 18, "5 + 13 = 18 June.", 0), ("num", "Her next period is expected 28 days after 5 June. June has 30 days: on which day of July is it expected?", 3, "5 June + 28 days = 33 June = 3 July.", 0), ("open", "State one sign that she may be pregnant if the next period does not come.", "A missed period (also tiredness, nausea); she should see a health worker to confirm.", ["1 mark for missed period"], 1)])],
          [("Menstruation is:", "breakdown of the uterus lining", ["release of an egg", "fusion of gametes", "making sperm"], "The lining leaves the body."),
           ("The placenta allows the transfer of:", "oxygen and food", ["blood cells", "urine", "faeces"], "Exchange of materials."),
           ("The hormone that maintains the uterus lining is:", "progesterone", ["insulin", "ADH", "adrenaline"], "Progesterone."),
           ("The baby is protected from knocks by:", "amniotic fluid", ["placenta", "cord", "ovary"], "Fluid cushion."),
           ("Normal human pregnancy lasts about:", "40 weeks", ["10 weeks", "20 weeks", "60 weeks"], "About 9 months.")],
          ["Cycle length (28 days) and ovulation day (14) are averages; the exercise stresses this.", "Antenatal and breast-feeding advice must be reviewed by a health worker against Cameroon MINSANTE guidance.", "Date calculation uses a fixed 28-day cycle."])

    sti = grid(["Bacterial STIs|gonorrhoea, syphilis|treated with antibiotics", "Viral STIs|HIV, herpes, hepatitis B|no simple cure for HIV", "Prevention|abstinence, faithfulness,|condoms, testing"], cols=1, w=300, bh=52, size=11, colors=["lightorange", "pink", "lightgreen"])
    build(ch, "stis-hiv", "Sexually transmitted infections and HIV/AIDS", 25,
          ["Name examples of sexually transmitted infections (STIs) and how they spread.",
           "Explain how HIV affects the body and how it is and is not transmitted.",
           "Describe ways to prevent STIs and why stigma is harmful."],
          [("key", "definition", "STIs",
            "**Sexually transmitted infections** are diseases passed from one person to another during unprotected sexual contact. Examples: **gonorrhoea** and **syphilis** (caused by bacteria and treated with antibiotics) and **HIV** (a virus). Some STIs show no signs, so people can pass them on without knowing."),
           ("fig", sti, "Types of STI and prevention.", "Three coloured boxes: bacterial STIs treated with antibiotics, viral STIs including HIV without a simple cure, and prevention by abstinence, faithfulness, condoms and testing."),
           ("key", "retenir", "HIV and AIDS",
            "**HIV** (human immunodeficiency virus) infects and destroys **lymphocytes** (white blood cells), so the immune system becomes weak. Without treatment, a person may develop **AIDS**: they get many infections that a healthy body would fight off.\n\n**HIV is spread by**: unprotected sex; infected blood (shared needles or razors, unscreened blood); from an infected mother to her baby during pregnancy, birth or breast-feeding."),
           ("key", "attention", "How HIV is NOT spread",
            "HIV is **not** spread by hugging, shaking hands, sharing plates, cups or toilets, coughing, or **mosquito bites**. People living with HIV deserve respect and care. **Stigma** and discrimination discourage people from being tested and treated."),
           ("key", "retenir", "Prevention and treatment",
            "- **Abstinence** from sex until adulthood, and **faithfulness** to one uninfected partner.\n- Correct and consistent use of **condoms** reduces the risk.\n- Never share needles, razors or blades; blood for transfusion is screened.\n- **Testing** and early treatment: **antiretroviral drugs** (ART) keep the virus under control, allow a long healthy life and greatly reduce passing the virus to others or to a baby; they are **not a cure**. Treatment is available at health centres."),
           ("example", "True or false", "Decide whether HIV can pass between two friends who (a) share a plate of ndolé, (b) share a razor blade.",
            ["(a) Sharing food or plates does not transmit HIV.", "(b) Razors or blades can carry blood: sharing them can spread HIV if one person is infected."],
            "(a) No risk; (b) risk, so never share."),
           ("example", "Mother and baby", "A pregnant woman learns she is HIV-positive. Name two actions that can protect her baby.",
            ["She should attend antenatal clinics and take antiretroviral treatment as prescribed.", "She should follow the health worker's advice on delivery and feeding the baby."],
            "Take ART and follow clinic advice for birth and feeding.")],
          [("mcq", "HIV attacks and destroys:", "lymphocytes (white blood cells)", ["red blood cells", "platelets", "kidney cells"], "This weakens the immune system."),
           ("tf", "HIV can be passed by mosquito bites.", False, "HIV is not spread by mosquitoes."),
           ("mcq", "Which is a way to avoid HIV infection?", "never sharing needles or razor blades", ["hugging people", "avoiding all handshakes", "using the same cup"], "Blood contact is a route of transmission."),
           ("mcq", "Antiretroviral drugs:", "control HIV but do not cure it", ["cure HIV completely", "prevent all STIs", "are antibiotics"], "ART controls the virus."),
           ("open", "Explain why it is wrong to reject a person with HIV.", "HIV is not spread by everyday contact, so there is no danger; rejection (stigma) discourages testing and treatment and harms health; people with HIV can live long, healthy lives with treatment.", ["1 mark: not spread by normal contact", "1 mark: stigma stops testing and treatment", "1 mark: respect and rights"]),
           ("prob", "In a health club in Bafoussam students discuss HIV.", [("mcq", "Which body fluid is NOT a way to catch HIV?", "tears", ["blood", "semen", "breast milk of an infected mother"], "Blood, certain sexual fluids and breast milk can carry the virus; casual contact with tears is not a route."), ("tf", "A person who looks healthy cannot have HIV.", False, "HIV may cause no visible signs for years; testing is the only way to know."), ("open", "State two ways to reduce the risk of HIV.", "Abstinence or being faithful to one tested partner; using condoms; not sharing needles or blades; mother-to-child prevention with treatment.", ["1 mark each, maximum 2"], 2)])],
          [("AIDS is the stage when:", "the immune system is weak and infections appear", ["a cut does not bleed", "a person gets cold", "red cells burst"], "Immune deficiency."),
           ("HIV is caused by a:", "virus", ["bacterium", "fungus", "mosquito"], "A virus."),
           ("Syphilis is treated with:", "antibiotics", ["vaccines only", "hand washing", "antimalarials"], "It is bacterial."),
           ("HIV is not spread by:", "shaking hands", ["sharing needles", "unprotected sex", "an infected mother to baby"], "Casual contact is safe."),
           ("Early testing helps because:", "treatment can start early", ["it cures HIV", "it kills the virus", "it prevents tests"], "Early treatment protects health.")],
          ["HEALTH CONTENT: facts are conservative; MUST be reviewed by a health worker; check Cameroon MINSANTE guidance on testing, ART and prevention of mother-to-child transmission.", "Syllabus may require different STIs (e.g. chlamydia, hepatitis B)."])

    # ------------------------------------------------------------------ growth
    ch = p.chapter("growth", "Growth and development", "GCE O Level Biology — Growth, development, puberty and life cycles (to be checked against the official syllabus)")
    ages = [(0, 3), (2, 12), (4, 28), (6, 52), (8, 72), (10, 84), (12, 90), (14, 92), (16, 92.5)]
    gx = lambda t: 70 + t * 20
    gy = lambda v: 210 - v * 1.9
    growth = S(axes(70, 210, 410, 20, xl="time", yl="size", ticks_x=[(gx(t), str(t)) for t in (0, 4, 8, 12, 16)]) + [polyline([(gx(t), gy(v)) for t, v in ages])] +
               [T(130, 160, "slow start", size=11), T(220, 100, "rapid growth", size=11, anchor="start"), T(330, 50, "levels off", size=11)], 480, 250)
    build(ch, "growth", "Growth and development", 25,
          ["Define growth and development and describe how growth is measured.",
           "Describe the S-shaped growth curve and the changes at puberty.",
           "Describe the life cycle of an insect with complete metamorphosis."],
          [("key", "definition", "Growth and development",
            "**Growth** is a permanent increase in size and dry mass produced by cell division and cell enlargement. **Development** is the increase in complexity of an organism (new organs and structures formed). Growth is measured by height, length or mass; **dry mass** is the best measure for plants (water content varies). In plants, cell division is concentrated in **meristems** at the tips of shoots and roots."),
           ("fig", growth, "An S-shaped (sigmoid) growth curve (illustrative).", "A line graph of size against time: slow at first, then a steep rapid-growth phase, then levelling off."),
           ("key", "retenir", "Puberty",
            "At **puberty** (usually between about 10 and 16 years) the sex hormones cause secondary sexual characteristics.\n\n- **Boys** (testosterone): voice breaks, facial and body hair, broader shoulders, sperm production starts.\n- **Girls** (oestrogen): breasts develop, hips widen, periods begin, ovulation starts.\n\nBoth sexes: pubic hair, a growth spurt and emotional changes. Everyone develops at their own rate."),
           ("key", "retenir", "Metamorphosis",
            "Many insects change form completely: **complete metamorphosis**: **egg → larva → pupa → adult** (housefly, mosquito, butterfly). The larva feeds and grows; the adult reproduces. Insects such as cockroaches and grasshoppers have **incomplete metamorphosis**: egg → nymph (a small version of the adult) → adult, with no pupa.\n\nThe *Anopheles* mosquito's larvae live in still water, which is why draining stagnant water helps control malaria."),
           ("key", "pieges", "Common mistakes",
            "- Growth is a *permanent* increase; a meal that increases body mass does not count.\n- Fresh mass is a poor measure of growth in plants; use dry mass.\n- The pupa stage is missing in incomplete metamorphosis."),
           ("example", "Growth rate from data", "On the growth curve above the size is 12 units at time 2 and 52 units at time 6. Calculate the average growth rate between these two times.",
            ["Increase in size = 52 − 12 = 40 units.", "Time interval = 6 − 2 = 4 units; rate = 40 ÷ 4 = 10 units per time unit."],
            "10 units per time unit"),
           ("example", "Mosquito life cycle", "Place these in order: pupa, egg, adult, larva. Say in which habitat the first three stages live in the mosquito.",
            ["Complete metamorphosis: egg → larva → pupa → adult.", "Egg, larva and pupa live in still water; only the adult flies."],
            "egg, larva, pupa, adult; the first three in water.")],
          [("mcq", "The best measure of growth in a plant is:", "dry mass", ["fresh mass", "number of leaves only", "colour"], "Fresh mass includes variable water."),
           ("num", "A seedling grows from 12 cm to 52 cm in 4 days. What is the average growth rate in cm per day?", 10, "(52 − 12) ÷ 4 = 10.", 0, "cm/day"),
           ("match", "Match the change to the sex hormone.", [("voice breaks", "testosterone"), ("periods start", "oestrogen"), ("pupa stage", "complete metamorphosis"), ("nymph", "incomplete metamorphosis")], "Standard facts."),
           ("mcq", "Which insect stage feeds and grows most?", "larva", ["pupa", "egg", "adult"], "The larva eats."),
           ("open", "Explain the difference between growth and development.", "Growth is a permanent increase in size and mass; development is the change in complexity, e.g. the formation of organs and structures.", ["1 mark: growth = increase in size/mass", "1 mark: development = new structures/complexity"]),
           ("prob", "A student plots the height of a sunflower each week.", [("mcq", "The S-shaped curve levels off because:", "the plant reaches its full size or resources run out", ["the plant stops respiring", "light is not needed", "water has no effect"], "Genetic limits and resources limit growth."), ("mcq", "Where does cell division in the roots occur?", "root tip meristem", ["root hair", "xylem", "epidermis"], "Meristems at tips."), ("open", "Name two life processes needed for growth.", "Nutrition (photosynthesis) and respiration (also water uptake).", ["1 mark each, maximum 2"], 2)])],
          [("Growth involves:", "cell division and enlargement", ["only movement", "only reproduction", "digestion"], "Growth."),
           ("Complete metamorphosis includes a:", "pupa", ["nymph only", "tail", "spore"], "Pupa stage."),
           ("The hormone for breast development is:", "oestrogen", ["testosterone", "insulin", "ADH"], "Oestrogen."),
           ("Meristems are found at the:", "shoot and root tips", ["leaf veins", "flower petals", "bark"], "Growth regions."),
           ("Mosquito larvae live in:", "still water", ["dry soil", "trees", "fast rivers"], "Water breeding sites.")],
          ["Growth curve is illustrative; puberty ages are approximate ranges; to be checked.", "Puberty content is factual only and should be reviewed by a teacher for age-appropriateness."])
