import sys
sys.path.insert(0, "/home/user/CastBridge/tools/learn-authoring/anglophone")
from _gl import *

p = Pack("gceal-history", "History — GCE A Level", level="Upper Sixth", subject="histoire-geo", cursus="secondary",
         exam="GCE-AL", series=[], wanted="history",
         description="GCE Advanced Level History revision: nationalism and decolonisation, independence and reunification of Cameroon, Pan-Africanism, the OAU and the AU, post-independence challenges, the Second World War, the Cold War, the Commonwealth and La Francophonie, with source and essay skills and a mock paper.",
         programRef="Cameroon GCE Board, Advanced Level History syllabus (Upper Sixth) — to be checked against the official text")

# =================================================== DECOLONISATION
ch = p.chapter("decolonisation", "Nationalism, decolonisation and the independence of Cameroon")
tl1 = timeline(1945, 1995, events=[(1957, "Ghana"), (1960, "Year of Africa"), (1962, "Algeria"), (1975, "Angola, Mozambique"), (1980, "Zimbabwe"), (1994, "South Africa vote")], w=480, h=240)
L = lesson(ch, "nationalism", "African nationalism and decolonisation",
    ["Explain the internal and external causes of decolonisation", "Compare peaceful and violent routes to independence", "Place the independence of Ghana, Algeria and southern Africa in sequence"],
    [("definition", "Causes", "**Internal:** educated elites, nationalist parties and newspapers, growing towns and trade unions, ex-servicemen who fought in the Second World War, and resentment of forced labour, taxes and discrimination. **External:** the weakening of Britain and France by the war, the Atlantic Charter (1941) and its language of self-determination, the stance of the UN, the USA and the USSR, and the independence of India and other Asian countries from 1947."),
     ("retenir", "Routes to independence", "Many colonies became independent by **negotiation and elections**, led by parties such as Nkrumah’s in the Gold Coast, which became **Ghana in 1957**, the first sub-Saharan colony to gain independence from Britain. In **1960**, often called the ‘Year of Africa’, about seventeen states became independent, including Cameroon (French Cameroun), Nigeria, Senegal and the Congo."),
     ("retenir", "Armed struggles", "Where settlers or colonial governments resisted, independence involved conflict: the **Algerian war** (1954–62) ended with independence in 1962; Portuguese colonies such as Angola and Mozambique became independent in **1975** after wars; Zimbabwe in **1980**; Namibia in **1990**; in South Africa apartheid ended with the first multiracial elections in **1994**."),
     ("pieges", "Be careful", "- Decolonisation was not simply ‘given’: African movements pushed for it.\n- ‘Peaceful’ does not mean there was no repression or suffering in the earlier years.\n- Do not give 1960 as the independence date of every African state: look up each one.")],
    [("Example 1 — Internal or external?", "Classify these causes: (a) formation of a nationalist party, (b) the Atlantic Charter, (c) returning soldiers’ demands.",
      ["(a) Within the colony: internal.", "(b) A statement by Britain and the USA: external.", "(c) Veterans in the colony: internal."], "(a) internal, (b) external, (c) internal."),
     ("Example 2 — Compare Ghana and Algeria", "Briefly compare how Ghana and Algeria gained independence.",
      ["Ghana: political campaigns and elections; independence by agreement in 1957.", "Algeria: a long armed struggle (1954–62) against a state that treated the territory as part of France.", "Both show the effect of nationalist organisation, but circumstances differed."], "Negotiated versus armed struggle.")],
    [M("Which country became independent in 1957 as the first in sub-Saharan Africa from British rule?", "Ghana", ["Nigeria", "Kenya", "Cameroon"], "March 1957."),
     N("The Algerian war began in 1954 and ended in 1962. How many years did it last?", 8, "1962 − 1954 = 8.", 0, "years"),
     TF("Angola and Mozambique became independent in 1975.", True, "After the end of Portuguese rule."),
     M("An external cause of decolonisation was", "Weakening of European powers after the Second World War", ["A rise in rain", "A new railway", "A harvest"], "Britain and France were exhausted."),
     MT("Match the country to its independence year.", [("Ghana", "1957"), ("Algeria", "1962"), ("Zimbabwe", "1980"), ("Namibia", "1990")], "Standard dates."),
     O("Assess the importance of the Second World War as a cause of decolonisation in Africa.", "The war weakened Britain and France financially and militarily, so they were less able to hold colonies. African soldiers returned with new ideas and expectations, wartime demand and inflation fuelled grievances, and statements like the Atlantic Charter raised hopes. But nationalism already existed and the USA, the USSR and the UN also pushed for change. The war was a major but not the only cause.", "War effects (2); other causes (2); judgement (1).")],
    [("The Atlantic Charter dates from", "1941", ["1884", "1960", "1975"], "Statement by Churchill and Roosevelt."),
     ("The ‘Year of Africa’ is", "1960", ["1945", "1884", "1990"], "Many states became independent."),
     ("Namibia became independent in", "1990", ["1957", "1960", "1980"], "After South African rule ended."),
     ("Apartheid ended with multiracial elections in", "1994", ["1960", "1975", "1980"], "April 1994."),
     ("A nationalist party seeks", "Self-government and independence", ["More taxes", "Colonial expansion", "Foreign missions"], "Its aim.")],
    (tl1, "Decolonisation milestones in Africa.", "Timeline from 1945 to 1995 with Ghana 1957, the Year of Africa 1960, Algeria 1962, Angola and Mozambique 1975, Zimbabwe 1980 and South Africa 1994."),
    ["Verify: Ghana 6 March 1957; ‘Year of Africa’ 1960 — number of states (about 17); Algeria 1962; Portuguese colonies 1975; Zimbabwe 1980; Namibia 1990; South Africa 1994; Atlantic Charter 1941.", "Check which case studies the syllabus requires."])

tl2 = timeline(1946, 1984, events=[(1946, "Trusteeship"), (1960, "French Cameroun free"), (1961, "Plebiscites, Federation"), (1972, "United Republic"), (1984, "Republic of Cameroon")], w=480, h=250)
L = lesson(ch, "cameroon-independence", "Independence and reunification of Cameroon (general outline)",
    ["Outline the road to independence of French Cameroun and the British Cameroons", "Describe the 1961 plebiscites and the federation", "Describe the later constitutional changes (1972, 1984)"],
    [("definition", "French Cameroun", "French Cameroun was a UN trust territory from 1946. Political movements demanded autonomy, reunification and independence, among them the Union des Populations du Cameroun (UPC, founded in 1948). Self-government was introduced in stages in the 1950s. **French Cameroun became independent on 1 January 1960** as the Republic of Cameroun, with Ahmadou Ahidjo as first president."),
     ("retenir", "British Cameroons", "Nigeria became independent on **1 October 1960**. The UN organised **plebiscites in the British Cameroons in February 1961**. The northern part (**Northern Cameroons**) voted to join Nigeria. The southern part (**Southern Cameroons**) voted to join the Republic of Cameroun. Constitutional discussions in Foumban in July 1961 followed."),
     ("retenir", "Federation and later changes", "The **Federal Republic of Cameroon** was created on **1 October 1961**, with two federated states, East and West Cameroon. After a referendum in **May 1972** the federation became a unitary state, the **United Republic of Cameroon**. In **1984** the name became the **Republic of Cameroon**. Different views exist today about some of these arrangements; students should state facts and attribute opinions."),
     ("attention", "Neutral writing", "- Use dates and documented decisions; attribute views (‘supporters argued…’).\n- Do not confuse independence of French Cameroun (1960) with the union of 1961.\n- The plebiscite concerned the British-administered territory only.\n- Avoid emotive language: describe, explain, assess.")],
    [("Example 1 — Sequence", "Put in order: plebiscites, independence of French Cameroun, federation, UN trusteeship, unitary state.",
      ["Trusteeship was set up in 1946.", "French Cameroun became independent on 1 January 1960.", "Plebiscites were held in February 1961 and the federation was created in October 1961.", "The unitary state followed in 1972."], "1946, 1960, 1961 (plebiscites), 1961 (federation), 1972."),
     ("Example 2 — Plebiscite results explained", "Explain the outcome of the 1961 plebiscites in general terms.",
      ["Voters in Northern Cameroons chose to join Nigeria.", "Voters in Southern Cameroons chose to join the Republic of Cameroun.", "The choices reflected differing links, interests and political campaigns in each area."], "A divided result: north to Nigeria, south to Cameroun.")],
    [N("French Cameroun became independent in 1960 and the federation began in 1961. How many years apart?", 1, "1961 − 1960 = 1.", 0, "years"),
     M("In which year did the plebiscites in the British Cameroons take place?", "1961", ["1946", "1972", "1984"], "February 1961."),
     TF("The United Republic of Cameroon was created after a referendum in 1972.", True, "May 1972."),
     M("Which of these became independent on 1 October 1960?", "Nigeria", ["Ghana", "Kenya", "French Cameroun"], "Nigeria’s independence day."),
     MT("Match the date to the event.", [("1 January 1960", "Independence of French Cameroun"), ("February 1961", "UN plebiscites in the British Cameroons"), ("1 October 1961", "Federal Republic created"), ("1984", "Name changed to Republic of Cameroon")], "Standard dates."),
     O("Explain why the UN held plebiscites in the British Cameroons.", "The territory was a UN trust territory, so the UN, as supervising body, organised the vote to let the inhabitants decide their future. Trusteeship required that inhabitants be consulted, and the plebiscites were a way to choose between the options put forward.", "Trust territory (1); supervision (1); inhabitants’ consent (1); options (1).")],
    [("The federation of Cameroon began in", "1961", ["1946", "1984", "1972"], "1 October 1961."),
     ("The two federated states were", "East and West Cameroon", ["North and South only", "Douala and Yaoundé", "Chad and Niger"], "Federal structure."),
     ("The unitary state was created in", "1972", ["1946", "1960", "1961"], "After a referendum."),
     ("Northern Cameroons voted to join", "Nigeria", ["Chad", "Gabon", "Ghana"], "1961."),
     ("Foumban is", "Where talks took place in July 1961", ["A port", "A river", "A UN office"], "Constitutional talks.")],
    (tl2, "Key dates in Cameroon’s unification and constitutional history.", "Timeline from 1946 to 1984 with trusteeship, independence of French Cameroun, plebiscites and federation, unitary state and name change."),
    ["Verify: trusteeship 1946; 1 Jan 1960; Nigeria 1 Oct 1960; plebiscites 11 Feb 1961 (date often given); Foumban talks July 1961; 1 Oct 1961 federation; 20 May 1972 referendum; 1984 name change.", "Politically sensitive: keep neutral and follow the official syllabus; the plebiscite options and later debates must be presented as the syllabus requires."])

# =================================================== PAN-AFRICANISM, OAU, AU
ch = p.chapter("unity", "Pan-Africanism, the OAU and the AU")
tl3 = timeline(1895, 2005, events=[(1900, "London conference"), (1945, "Manchester"), (1963, "OAU founded"), (2002, "AU launched")], w=480, h=240)
L = lesson(ch, "panafricanism", "Pan-Africanism",
    ["Define Pan-Africanism and describe its origins", "Describe the main congresses and leading figures", "Explain differing views on how to achieve unity"],
    [("definition", "Meaning and origins", "**Pan-Africanism** is the idea that people of African descent share a common history and interests and should unite to defend their rights and, later, to free and unite Africa. It began in the African diaspora, notably in the USA and the Caribbean, in the late 19th century. The first Pan-African Conference met in London in **1900**, organised with the help of Henry Sylvester Williams."),
     ("retenir", "Congresses and figures", "W. E. B. Du Bois led a series of Pan-African Congresses from **1919**. Marcus Garvey promoted racial pride. The Fifth Congress in **Manchester in 1945**, with George Padmore, Kwame Nkrumah and others, called for an end to colonial rule and marked a turn towards African leadership. Related currents: **Négritude** (cultural pride, Senghor, Césaire) and Nkrumah’s call for a ‘United States of Africa’."),
     ("retenir", "Disagreement on unity", "After independence, African leaders disagreed. The **Casablanca group** (1961), including Ghana, wanted rapid political union. The **Monrovia group** preferred cooperation among sovereign states. A compromise at Addis Ababa in 1963 created the Organisation of African Unity, favouring cooperation rather than a federation."),
     ("pieges", "Avoid these errors", "- Pan-Africanism began among people of African descent abroad, not only in Africa.\n- Pan-Africanism and the OAU are linked but not the same.\n- Leaders differed: unity could mean a political union or looser cooperation.")],
    [("Example 1 — Manchester 1945", "Explain the importance of the 1945 Manchester Pan-African Congress.",
      ["It demanded an end to colonial rule at a time when many colonies were changing.", "African leaders such as Nkrumah took a leading role.", "It linked Pan-Africanism to the nationalist movements that won independence."], "It turned Pan-Africanism towards independence led by Africans."),
     ("Example 2 — Two approaches", "Contrast the Casablanca and Monrovia groups.",
      ["Casablanca: rapid political union under strong central authority.", "Monrovia: gradual cooperation among independent states, with respect for sovereignty.", "The OAU combined elements, favouring the Monrovia approach."], "Rapid union versus gradual cooperation.")],
    [M("The first Pan-African Conference was held in", "London in 1900", ["Berlin in 1884", "Accra in 1957", "Addis Ababa in 1963"], "Organised with Henry Sylvester Williams."),
     TF("The Fifth Pan-African Congress met in Manchester in 1945.", True, "That is the standard record."),
     MT("Match the figure with the idea or role.", [("W. E. B. Du Bois", "Led Pan-African Congresses"), ("Kwame Nkrumah", "Called for a United States of Africa"), ("Marcus Garvey", "Promoted racial pride and unity"), ("Léopold Senghor", "Négritude")], "Standard associations."),
     N("Between the first conference (1900) and Manchester (1945), how many years passed?", 45, "1945 − 1900 = 45.", 0, "years"),
     O("Describe the aims of Pan-Africanism.", "To unite people of African descent, to defend their rights and dignity, to end colonial rule and racial discrimination, and to promote unity and cooperation among African states.", "One mark per aim, max 3."),
     O("To what extent did Pan-Africanism contribute to the independence of African states?", "Pan-Africanism provided ideas, a network of leaders and international pressure, especially after the 1945 congress, helping Nkrumah and others organise movements. But local nationalism, economic and political change after the war and the pressure of other powers also drove independence. Pan-Africanism was an important influence, not the only one.", "Contribution (2); other factors (2); judgement (1).")],
    [("Négritude emphasised", "Cultural pride in African identity", ["Trade only", "Military union", "Colonial law"], "A cultural movement."),
     ("The Casablanca group wanted", "Rapid political union", ["No cooperation", "Colonial rule", "Independence of the UN"], "A faster federation."),
     ("George Padmore was", "A leading Pan-Africanist", ["A German governor", "A UN official", "A Duala king"], "He helped organise the 1945 congress."),
     ("Pan-Africanism started mainly among", "People of African descent in the diaspora", ["German missionaries", "French colonial officers", "UN diplomats"], "Late 19th century."),
     ("The OAU compromise favoured", "Cooperation among sovereign states", ["Immediate federation", "Colonial federation", "No organisation"], "Closer to the Monrovia view.")],
    (tl3, "Pan-Africanism from 1900 to the AU.", "Timeline from 1895 to 2005 with the London conference 1900, Manchester 1945, OAU founded 1963 and AU launched 2002."),
    ["Verify: London conference 1900; Congresses from 1919; Manchester 1945; Casablanca and Monrovia groups 1961; OAU 1963; AU 2002; names and roles of figures.", "Confirm the numbering of congresses (Fifth in 1945)."])

L = lesson(ch, "oau-au", "The Organisation of African Unity and the African Union",
    ["Describe the founding, aims and principles of the OAU", "Assess its achievements and limitations", "Describe the AU and how it differs from the OAU"],
    [("definition", "The OAU", "The **Organisation of African Unity (OAU)** was founded at Addis Ababa on **25 May 1963** by thirty-two independent African states. Aims: promote unity and solidarity, defend sovereignty and territorial integrity, end colonialism and apartheid, and promote cooperation. Principles: sovereign equality, **non-interference** in internal affairs and peaceful settlement of disputes. A 1964 resolution accepted inherited colonial borders."),
     ("retenir", "Record of the OAU", "**Achievements:** supported liberation movements through its Liberation Committee, helped end colonial rule in southern Africa, mediated some disputes and gave Africa a voice at the UN. **Weaknesses:** no power to enforce, the principle of non-interference limited action against abuses and civil wars, lack of money, divisions among members."),
     ("retenir", "The AU", "The **African Union (AU)** replaced the OAU, launched in **2002** (the Constitutive Act was adopted in 2000). It has a stronger structure: an Assembly of heads of state, a Commission, the **Peace and Security Council**, and the Pan-African Parliament. It allows intervention in member states in grave circumstances such as genocide and war crimes. It also promotes development through programmes such as NEPAD and **Agenda 2063**."),
     ("pieges", "Common errors", "- The OAU did not accept the right to interfere in members’ internal affairs; the AU’s Act recognises a limited right of intervention.\n- Headquarters are in Addis Ababa (Ethiopia) for both.\n- Do not state the AU’s success or failure without evidence: assess both.")],
    [("Example 1 — OAU versus AU", "State two differences between the OAU and the AU.",
      ["The AU has a Peace and Security Council and a Pan-African Parliament; the OAU had no such bodies.", "The AU’s Act permits intervention in grave circumstances; the OAU stressed non-interference."], "Stronger institutions and a limited right of intervention."),
     ("Example 2 — Why accept colonial borders?", "Why did the OAU accept the borders inherited from colonial rule?",
      ["Changing borders could cause many disputes and wars.", "New states wanted stability and recognition of their territory.", "It avoided arguments over which groups should belong to which state."], "To avoid conflict and protect stability.")],
    [M("Where was the OAU founded?", "Addis Ababa", ["Accra", "Yaoundé", "Berlin"], "May 1963."),
     N("The OAU started in 1963 and the AU in 2002. How many years later?", 39, "2002 − 1963 = 39.", 0, "years"),
     TF("The OAU’s principles included non-interference in members’ internal affairs.", True, "This limited its action."),
     M("Which body of the AU deals with conflict?", "Peace and Security Council", ["Trusteeship Council", "Security Council of the UN", "Liberation Committee"], "The AU’s own body."),
     MT("Match the item to its description.", [("Liberation Committee", "OAU body supporting liberation movements"), ("Agenda 2063", "AU development vision"), ("NEPAD", "Programme for African development"), ("Pan-African Parliament", "AU body of representatives")], "General descriptions."),
     O("Evaluate the achievements and limitations of the OAU.", "The OAU gave Africa a collective voice and supported liberation struggles, helping end colonial rule and apartheid, and it handled some disputes through mediation. Its non-interference principle, lack of enforcement powers, financial weakness and divisions limited its ability to stop civil wars and human rights abuses. It achieved much on decolonisation but less on internal conflicts.", "Achievements (2); limitations (2); judgement (1).")],
    [("OAU founding members numbered about", "Thirty-two", ["Five", "One hundred", "Two"], "Thirty-two states in 1963."),
     ("The AU was launched in", "2002", ["1963", "1884", "1945"], "In Durban."),
     ("A weakness of the OAU was", "Lack of enforcement power", ["Too much power", "Too many funds", "No members"], "It could not impose decisions."),
     ("Agenda 2063 is", "A long-term development vision of the AU", ["A treaty of Berlin", "A UN agency", "A peace conference"], "Adopted in 2015."),
     ("The AU’s Act allows intervention in", "Grave circumstances like genocide", ["Any trade dispute", "All elections", "School exams"], "A limited right.")],
    (table(["Feature", "OAU", "AU"], [["Founded", "1963", "2002"], ["Seat", "Addis Ababa", "Addis Ababa"], ["Principle", "Non-interference", "Limited intervention"]], 440, 13, 32),
     "OAU and AU compared.", "A table comparing foundation date, headquarters and main principle of the OAU and the AU."),
    ["Verify: OAU 25 May 1963, thirty-two founding states; 1964 resolution on borders; AU Constitutive Act 2000, launch 2002 (Durban); NEPAD 2001; Agenda 2063 adopted 2015.", "Check which AU institutions the syllabus requires."])

L = lesson(ch, "post-independence", "Post-independence Africa: challenges and responses",
    ["Describe political, economic and social challenges after independence", "Explain the causes of instability and conflict", "Assess responses and progress"],
    [("definition", "Political challenges", "New states had borders from colonial times, many ethnic and language groups and weak national institutions. **Nation-building** meant creating a common identity. In many countries early multiparty systems gave way to **one-party states** and **military coups** in the 1960s–80s; in the 1990s many states returned to multiparty politics. Conflicts and weak governance harmed development."),
     ("retenir", "Economic and social challenges", "Economies depended on **exporting a few primary products**, so falling world prices hurt incomes. Colonial infrastructure linked mines and farms to ports, not to each other. Debt, poverty, limited industry, rapid population growth, shortages in education, health and skilled workers, and disease posed further problems. Some argue that external economic influence continued (**neo-colonialism**); others stress internal factors."),
     ("retenir", "Responses and progress", "Governments expanded schools and health services, built roads and dams, and set up regional organisations. Since the 1990s many states have held multiparty elections and economic reforms. The AU and regional communities try to manage conflict and promote trade. Progress is uneven: some countries have grown steadily, while others face conflict and poverty."),
     ("attention", "Write with balance", "- Avoid blaming only colonialism or only African leaders: weigh both internal and external factors.\n- Do not treat Africa as uniform: experiences differ widely.\n- Present contested political questions neutrally and attribute opinions.")],
    [("Example 1 — Internal or external?", "Classify as internal or external: (a) weak institutions, (b) falling cocoa prices on the world market, (c) a coup, (d) debt owed to foreign lenders.",
      ["(a) internal; (b) external; (c) internal; (d) mainly external.", "Many problems combine both kinds of causes."], "(a) internal, (b) external, (c) internal, (d) external."),
     ("Example 2 — Why diversify?", "Explain why dependence on one export is risky for a new state.",
      ["World prices vary, so income falls when prices fall.", "Little industry means few jobs and little added value.", "Diversification and processing spread the risk."], "Price instability and limited jobs.")],
    [M("Dependence on exporting a few primary products makes economies", "Vulnerable to price changes", ["Immune to price changes", "Industrialised", "Self-sufficient"], "World prices fluctuate."),
     TF("In the 1990s many African states moved towards multiparty politics.", True, "A widespread trend."),
     MT("Match the term to its meaning.", [("One-party state", "Only one party allowed to govern"), ("Coup", "Seizure of power by force"), ("Nation-building", "Creating a shared national identity"), ("Neo-colonialism", "Continued external economic influence")], "Basic terms."),
     M("A cause of instability was", "Weak institutions and ethnic divisions that were unmanaged", ["Excess of doctors", "Over-abundance of capital", "Good roads only"], "Both internal factors."),
     O("Explain two economic problems facing African states after independence.", "Dependence on a few exports exposed income to price falls. Debt payments reduced spending on health and schools. Lack of industry meant few jobs and imports of manufactured goods. Poor transport links limited internal trade.", "Two problems (2); explanation (2)."),
     O("Assess the view that the main cause of Africa’s post-independence problems was the legacy of colonial rule.", "Colonial rule left artificial borders, economies built around exports, little investment in education and weak institutions, which made later problems more severe. But decisions after independence, such as governance, corruption, conflict and policy choices, and outside factors like prices and debt, also mattered. The legacy was important but was not the only cause, and the balance varies from country to country.", "Colonial legacy (2); other factors (2); judgement (1).")],
    [("Nation-building means", "Creating a common national identity", ["Building houses only", "Starting wars", "Ending trade"], "Uniting diverse groups."),
     ("The 1990s saw", "Movement towards multiparty politics in many states", ["End of all elections", "Return to colonial rule", "New empires"], "A trend."),
     ("A country that exports mainly primary products sells", "Raw materials and agricultural goods", ["Computers", "Cars", "Medicines"], "Little processed."),
     ("Neo-colonialism refers to", "Continued economic influence from outside", ["Colonial rule by force", "Independence", "UN mandates"], "A debated concept."),
     ("A coup is", "A sudden seizure of power", ["An election", "A trade fair", "A census"], "Often by the military.")],
    (boxes(["Weak institutions", "Ethnic divisions", "Export dependence", "Debt", "Conflict", "Limited education and health"], 440, "red", 13, 2, 38, 10),
     "Common challenges after independence.", "Six boxes listing institutions, divisions, export dependence, debt, conflict and education and health."),
    ["Verify general claims about coups and one-party states in the 1960s–80s and the 1990s democratisation; avoid listing countries unless sure of facts.", "Contested topic: neutral tone; follow the syllabus’s case studies."])

# =================================================== WORLD HISTORY
ch = p.chapter("world", "World history: the Second World War and the Cold War")
tl4 = timeline(1919, 1946, events=[(1919, "Versailles"), (1929, "Depression"), (1933, "Hitler chancellor"), (1939, "War begins"), (1945, "War ends")], periods=[(1939, 1945, "WWII", "red")], w=480, h=240)
L = lesson(ch, "ww2", "Causes and outline of the Second World War",
    ["Explain the long-term and immediate causes of the Second World War", "Outline the main stages of the war", "Describe Africa’s part in the war"],
    [("definition", "Causes", "**Treaty of Versailles (1919):** many Germans felt it was harsh. **Great Depression** (from 1929): unemployment helped extreme parties. **Dictators:** Mussolini in Italy, **Hitler** (Chancellor from 1933) and aggressive expansion by Japan. **Weakness of the League of Nations:** failures over Manchuria (1931) and Abyssinia (1935). **Appeasement:** Britain and France made concessions, such as at Munich in 1938."),
     ("retenir", "Outbreak and course", "Germany invaded Poland on **1 September 1939**; Britain and France declared war two days later. Germany conquered much of Europe in 1939–41. In 1941 Germany invaded the Soviet Union, and Japan attacked Pearl Harbor (7 December), bringing in the USA. Germany surrendered in **May 1945**. Japan surrendered in **August–September 1945**, after atomic bombs were dropped on Hiroshima and Nagasaki."),
     ("retenir", "Africa", "North Africa and the Horn were battlefields. Africans served as soldiers and labourers in Allied armies and supplied raw materials. In August 1940 French Cameroun and other parts of French Equatorial Africa declared for Free France under General de Gaulle. The war strengthened demands for change and weakened European powers, helping decolonisation."),
     ("pieges", "Avoid errors", "- The Treaty of Versailles was one cause among several: do not blame it alone.\n- Appeasement was not simple cowardice; it had domestic and strategic reasons.\n- The war began in 1939 in Europe; for China and Japan, it began earlier.")],
    [("Example 1 — Long-term versus short-term", "Classify as long-term cause or immediate trigger: (a) Treaty of Versailles, (b) invasion of Poland.",
      ["(a) Signed in 1919, twenty years before: long-term.", "(b) The event of 1 September 1939 led directly to Britain and France declaring war: immediate trigger."], "(a) long-term, (b) immediate."),
     ("Example 2 — League failure", "Explain how the League’s failure over Abyssinia encouraged aggression.",
      ["Italy invaded Abyssinia (Ethiopia) in 1935.", "The League’s sanctions were limited and did not stop Italy.", "Dictators concluded that the League would not act firmly."], "Weak response encouraged further aggression.")],
    [N("Versailles was signed in 1919 and the war began in 1939. How many years between?", 20, "1939 − 1919 = 20.", 0, "years"),
     M("Which event led Britain and France to declare war in 1939?", "Germany’s invasion of Poland", ["Fall of Berlin", "Pearl Harbor", "The Berlin Conference"], "1 September 1939."),
     TF("The Great Depression helped extremist parties gain support in Germany.", True, "Mass unemployment."),
     M("Appeasement means", "Giving concessions to avoid war", ["Attacking first", "Joining an alliance", "Ending trade"], "A policy of Britain and France in the 1930s."),
     MT("Match the year to the event.", [("1933", "Hitler becomes Chancellor"), ("1938", "Munich Agreement"), ("1941", "Attack on Pearl Harbor"), ("1945", "End of the war")], "Standard dates."),
     O("Assess the importance of the Treaty of Versailles as a cause of the Second World War.", "Versailles caused resentment in Germany over losses of territory, reparations and the loss of colonies, which Nazi propaganda used. But the Great Depression, the rise of dictators, the failures of the League and the policy of appeasement were also important. Versailles was a contributory cause, not the only one.", "Role of Versailles (2); other causes (2); judgement (1).")],
    [("The Munich Agreement was in", "1938", ["1919", "1945", "1960"], "Britain and France accepted German demands on Czechoslovakia."),
     ("Germany surrendered in", "May 1945", ["1939", "1914", "1960"], "In Europe."),
     ("Italy invaded", "Abyssinia (Ethiopia) in 1935", ["Cameroon in 1914", "Kenya in 1960", "Egypt in 1884"], "The League failed to stop it."),
     ("Free France was led by", "General de Gaulle", ["Hitler", "Mussolini", "Stalin"], "French Equatorial Africa rallied to it."),
     ("Pearl Harbor was attacked by", "Japan", ["Germany", "Italy", "France"], "7 December 1941.")],
    (tl4, "From Versailles to the end of the Second World War.", "Timeline from 1919 to 1946 with 1919 Versailles, 1929 Depression, 1933 Hitler chancellor, 1939 war begins and 1945 war ends."),
    ["Verify: Versailles 1919; Wall Street Crash/Depression 1929; Hitler Chancellor January 1933; Munich 1938; invasion of Poland 1 Sept 1939; Pearl Harbor 7 Dec 1941; German surrender May 1945; Japan August–September 1945; Free France and Cameroon August 1940.", "Teach Africa’s role according to the syllabus."])

cw_fig = table(["Bloc", "Leader", "Alliance"], [["West", "USA", "NATO (1949)"], ["East", "USSR", "Warsaw Pact (1955)"]], 440, 13, 36)
L = lesson(ch, "cold-war", "The Cold War in outline",
    ["Define the Cold War and its origins", "Describe key crises and the arms race", "Explain the impact on Africa and the end of the Cold War"],
    [("definition", "What was the Cold War?", "The **Cold War** (about 1945–1991) was a rivalry between the **USA and its allies** (capitalism and liberal democracy) and the **USSR and its allies** (communism), fought without direct war between the two superpowers. It was waged by an **arms race**, alliances, propaganda, economic aid and **proxy wars** in other countries."),
     ("retenir", "Main events", "Truman Doctrine and Marshall Plan (1947), Berlin blockade (1948–49), **NATO** (1949), Korean War (1950–53), **Warsaw Pact** (1955), the building of the Berlin Wall (1961), the **Cuban Missile Crisis** (1962), the Vietnam War, détente in the 1970s, the fall of the Berlin Wall (1989) and the dissolution of the USSR (December 1991)."),
     ("retenir", "Africa and the Cold War", "Both superpowers competed for influence in Africa, giving aid and arms and backing different sides in conflicts such as in Angola after 1975. Many new states joined the **Non-Aligned Movement** (the Bandung conference of 1955 for Asia and Africa; Belgrade in 1961). The end of the Cold War ended some superpower support and contributed to political change in the 1990s."),
     ("pieges", "Common mistakes", "- The two superpowers did not fight each other directly; the wars were proxy conflicts.\n- NATO (1949) and the Warsaw Pact (1955) are different alliances.\n- Non-alignment means not joining either bloc; it does not mean isolation.")],
    [("Example 1 — Explain a proxy war", "Explain what a proxy war is, with an example from Africa.",
      ["Two powers support opposing sides in another country’s conflict instead of fighting each other.", "Example: Angola after 1975, where outside powers backed different groups.", "This prolonged conflict and brought arms into the region."], "A conflict where superpowers back local sides."),
     ("Example 2 — Why non-alignment?", "Why did many new African and Asian states choose non-alignment?",
      ["They wanted to avoid dependence on one superpower.", "They hoped to receive aid from both sides.", "They prioritised development and independence."], "To keep independence of action and gain aid.")],
    [M("The Cold War was mainly a rivalry between", "USA and USSR", ["France and Germany", "Britain and Egypt", "Cameroon and Nigeria"], "The two superpowers."),
     N("The Cold War began roughly in 1945 and ended in 1991. About how many years is that?", 46, "1991 − 1945 = 46.", 0, "years"),
     TF("NATO was formed in 1949.", True, "A Western alliance."),
     M("The Cuban Missile Crisis took place in", "1962", ["1914", "1945", "1975"], "October 1962."),
     MT("Match the item with its description.", [("NATO", "Western military alliance"), ("Warsaw Pact", "Eastern bloc alliance"), ("Proxy war", "Conflict where powers back local sides"), ("Non-Aligned Movement", "States not joining either bloc")], "Standard terms."),
     O("Assess the impact of the Cold War on Africa.", "The rivalry brought arms and aid and prolonged conflicts such as in Angola, as the superpowers backed different groups. It also encouraged non-alignment, and the pressure of both superpowers against colonial rule helped decolonisation. After 1991 reduced support contributed to political change but also left some states without aid. The effects were mixed.", "Negative effects (2); positive/other effects (2); judgement (1).")],
    [("The Berlin Wall was built in", "1961", ["1914", "1945", "1989"], "It fell in 1989."),
     ("The USSR was dissolved in", "1991", ["1945", "1962", "1975"], "End of the Cold War."),
     ("The Warsaw Pact was formed in", "1955", ["1949", "1914", "1884"], "Eastern bloc."),
     ("Bandung in 1955 was a conference of", "Asian and African states", ["European powers", "Latin American states only", "The League of Nations"], "A step towards non-alignment."),
     ("Détente means", "Easing of tensions", ["Open war", "A new empire", "A trade ban"], "The 1970s.")],
    (cw_fig, "The two blocs in the Cold War.", "A table with the West led by the USA with NATO 1949 and the East led by the USSR with the Warsaw Pact 1955."),
    ["Verify: Truman Doctrine and Marshall Plan 1947; Berlin blockade 1948–49; NATO 1949; Warsaw Pact 1955; Berlin Wall 1961; Cuban Missile Crisis Oct 1962; Bandung 1955; Belgrade 1961; USSR dissolved December 1991.", "Present ideologies neutrally."])

# =================================================== INTERNATIONAL ORGANISATIONS
ch = p.chapter("organisations", "The Commonwealth, La Francophonie and historical skills")
cmn_fig = flow(["British Empire", "Statute of Westminster, 1931", "London Declaration, 1949: republics may join", "Harare Declaration, 1991: democracy and human rights"], 440, "blue", 13, 380)
L = lesson(ch, "commonwealth", "The Commonwealth of Nations",
    ["Describe the origin and evolution of the Commonwealth", "Describe its aims, institutions and activities", "Explain Cameroon’s membership"],
    [("definition", "Origin and evolution", "The Commonwealth grew out of the British Empire. The **Statute of Westminster (1931)** recognised the self-governing dominions as equal and autonomous. After the Second World War, the **London Declaration (1949)** allowed republics such as India to remain members, and the Commonwealth later expanded as colonies became independent. Today it is a voluntary association of independent states with equal status."),
     ("retenir", "Aims and activities", "The Commonwealth promotes **democracy, human rights, development and cooperation**, set out in declarations such as the **Harare Declaration (1991)**. It has a secretariat in London, a Secretary-General, meetings of heads of government, and programmes in education, trade and young people. The **Commonwealth Games** are held every four years. It can suspend members that seriously violate its principles."),
     ("retenir", "Cameroon", "Cameroon joined the Commonwealth in **1995**, together with Mozambique. Cameroon’s membership reflects the English-speaking heritage of the former British Cameroons. It is also a member of La Francophonie, one of a small number of countries in both. Membership allows access to scholarships, training and diplomatic networks."),
     ("attention", "Do not confuse", "- The Commonwealth is not an empire; members are equal and independent.\n- Membership is voluntary: states choose to join and can leave.\n- Cameroon is a member of both the Commonwealth and La Francophonie.")],
    [("Example 1 — The shift in 1949", "Explain the importance of the London Declaration of 1949.",
      ["India wished to become a republic while remaining in the Commonwealth.", "The declaration allowed republics to remain members, recognising the Crown only as a symbol of association.", "This allowed the organisation to grow as other colonies became independent."], "It made the Commonwealth open to republics."),
     ("Example 2 — Benefits of membership", "Give two benefits of Commonwealth membership for a country like Cameroon.",
      ["Access to education and training programmes, such as scholarships.", "A forum for diplomacy and cooperation with a worldwide network of states."], "Education and training; diplomatic networks.")],
    [M("In what year did Cameroon join the Commonwealth?", "1995", ["1960", "1961", "1884"], "Together with Mozambique."),
     TF("The Commonwealth is an empire ruled from London.", False, "It is a voluntary association of equal states."),
     MT("Match the item to its date.", [("Statute of Westminster", "1931"), ("London Declaration", "1949"), ("Harare Declaration", "1991"), ("Cameroon joins", "1995")], "Standard dates."),
     N("How many years after the London Declaration (1949) did Cameroon join (1995)?", 46, "1995 − 1949 = 46.", 0, "years"),
     O("Describe three activities of the Commonwealth.", "It holds meetings of heads of government, runs education and training programmes, promotes trade and development, supports democracy and human rights, and organises the Commonwealth Games.", "One mark each, max 3."),
     O("Assess the importance of the Commonwealth for its African members.", "It provides access to scholarships, training, trade links, diplomatic support and a platform for small states. It promotes democratic values and can use pressure through suspension. But it has little enforcement power and limited funds compared with other bodies, and its influence varies. It is useful but not decisive.", "Benefits (2); limitations (2); judgement (1).")],
    [("The Statute of Westminster dates from", "1931", ["1949", "1995", "1884"], "Dominions became autonomous."),
     ("The Commonwealth Games take place", "Every four years", ["Every year", "Every ten years", "Once only"], "A major event."),
     ("The Harare Declaration is about", "Democracy and human rights", ["Trade tariffs", "Space travel", "War plans"], "1991."),
     ("The Commonwealth secretariat is in", "London", ["Yaoundé", "Addis Ababa", "Paris"], "Its headquarters."),
     ("Cameroon joined along with", "Mozambique", ["Egypt", "Gabon", "Chad"], "In 1995.")],
    (cmn_fig, "Stages in the development of the Commonwealth.", "Four boxes in a chain: British Empire, Statute of Westminster 1931, London Declaration 1949 and Harare Declaration 1991."),
    ["Verify: Statute of Westminster 1931; London Declaration April 1949; Harare Declaration 1991; Cameroon joined 1995 (with Mozambique); Secretariat in London.", "Check how the syllabus presents the Head of the Commonwealth and membership numbers (not given here)."])

fr_fig = table(["Aim", "Example of action"], [["Language", "Promoting French"], ["Culture", "Diversity and exchange"], ["Education", "Scholarships, training"], ["Democracy", "Observers, dialogue"]], 440, 13, 32)
L = lesson(ch, "francophonie", "La Francophonie",
    ["Define La Francophonie and describe its origins", "Describe its aims and institutions", "Evaluate its importance for Cameroon and Africa"],
    [("definition", "Meaning and origins", "**La Francophonie** is the community of countries and governments that share the French language and values. African leaders such as Léopold Senghor of Senegal and Habib Bourguiba of Tunisia were among its early promoters. An intergovernmental agency for cultural and technical cooperation was founded in **1970**, and the first summit of heads of state took place in **1986**. It later became the **Organisation internationale de la Francophonie (OIF)**."),
     ("retenir", "Aims", "To promote the **French language** and cultural diversity, **education** and research, **peace, democracy and human rights**, and economic cooperation. The OIF organises summits, supports schools and universities, runs cultural programmes and sends election observers. Members include states in Africa, Europe, Asia and the Americas; countries may be full members, associate members or observers."),
     ("retenir", "Cameroon", "Cameroon, with French and English as official languages, is a member of both the Francophonie and the Commonwealth. Membership offers scholarships, training, cultural exchange and diplomacy. Some people criticise the Francophonie as a form of continued French influence, while others value its multilateral cooperation and its support for languages and culture; students should present both views."),
     ("pieges", "Avoid these errors", "- La Francophonie is not just France: it has many members and its own institutions.\n- Cameroon’s official bilingualism allows membership in both bodies.\n- Do not present the debates on influence as settled; attribute arguments.")],
    [("Example 1 — Aims", "State two aims of La Francophonie.",
      ["Promotion of the French language and cultural diversity.", "Cooperation in education, democracy and development."], "Language promotion and cooperation."),
     ("Example 2 — Two views", "Give one argument for and one against the claim that La Francophonie is mainly beneficial to African members.",
      ["For: scholarships, training and support for cultural projects.", "Against: critics argue that it keeps strong links with the former colonial power."], "Benefits in cooperation versus concerns about influence.")],
    [M("When was the first Francophonie summit held?", "1986", ["1884", "1945", "1995"], "Held at Versailles."),
     TF("Cameroon is a member of both La Francophonie and the Commonwealth.", True, "Both English and French are official languages."),
     MT("Match each activity with a Francophonie aim.", [("Scholarships", "Education"), ("Election observers", "Democracy"), ("Promotion of French", "Language"), ("Summit of leaders", "Political cooperation")], "General links."),
     M("The OIF stands for", "Organisation internationale de la Francophonie", ["Organisation of Independent France", "Office for International Finance", "Overseas Industrial Fund"], "The current name."),
     O("Describe three activities of La Francophonie.", "It holds summits of heads of state, supports French-language education and universities, offers scholarships, organises cultural events, and sends observers to elections.", "One mark each, max 3."),
     O("Assess the importance of the Commonwealth and La Francophonie for Cameroon.", "Membership of both gives Cameroon access to education and training opportunities, a wide diplomatic network and recognition of its bilingual character. It can balance relationships and cultural links. However, the bodies have limited power and funding and some critics see them as extensions of former colonial influence. Their value depends on how actively the country uses them.", "Benefits (2); limitations (2); judgement (1).")],
    [("Léopold Senghor was a leader of", "Senegal", ["Cameroon", "Chad", "Nigeria"], "An early promoter of the Francophonie."),
     ("The OIF was founded as an agency in", "1970", ["1884", "1945", "1995"], "Agency for cultural and technical cooperation."),
     ("A Francophonie aim is", "Promoting French language and diversity", ["Building empires", "Banning languages", "Closing schools"], "Language and culture."),
     ("Observers can be sent to", "Elections", ["Football matches only", "Weddings", "Harvests"], "Part of the democracy work."),
     ("Cameroon is described as", "Officially bilingual", ["Monolingual", "Without official languages", "Spanish-speaking"], "French and English.")],
    (fr_fig, "Aims of La Francophonie.", "A table with four aims, language, culture, education and democracy, each with an example of action."),
    ["Verify: agency founded 1970 (Niamey); first summit 1986 (Versailles); OIF name and structure; Cameroon’s membership; names of early promoters.", "Neutral treatment of criticism: attribute arguments, give no personal opinion."])

L = lesson(ch, "essay-sources", "Source questions and essay planning (advanced)",
    ["Answer source-based questions using inference, cross-reference and evaluation", "Plan an extended essay with a clear judgement", "Use command words and manage time"],
    [("methode", "Source questions", "**Inference:** what can you work out that is not stated? **Cross-reference:** do two sources agree or differ, and why? **Usefulness:** a source is useful for a specific enquiry; judge by origin, purpose and content, and say what it cannot tell us. Always support your points with short quotations or details and link them to your own knowledge."),
     ("methode", "Essay planning", "Spend 5 minutes planning. Write a one-sentence answer, then 3–4 paragraphs with a **point, evidence (dates, names), explanation, link**. Include an alternative view and a conclusion that gives a **judgement** and explains which factor mattered most. Command words: *describe*, *explain*, *assess*, *to what extent*, *compare*, *how far*."),
     ("pieges", "Common mistakes", "- Narrating events rather than analysing.\n- Quoting a source without commenting on it.\n- Making a judgement in the conclusion that was not argued in the essay.\n- Writing precise dates and numbers you are unsure about: use approximate wording or omit.")],
    [("Example 1 — Using two sources", "Imaginary extracts for practice. A: (a colonial official, 1920s) ‘The people accept our rule willingly.’ B: (an elder’s account recorded decades later) ‘We paid taxes we did not understand and left our farms for the roads.’ Compare them.",
      ["They disagree about African attitudes: A claims acceptance; B describes burdens.", "A is an official with a purpose to present success; B is later memory, but gives the viewpoint of an ordinary person.", "Together they suggest that official reports do not show the full picture."], "Different viewpoints explained by origin and purpose."),
     ("Example 2 — Build a judgement", "Question: ‘How far was the UN responsible for the unification of the Cameroons?’ Plan the conclusion.",
      ["State the UN’s role: trusteeship, supervision, organising plebiscites.", "State other factors: local political parties, the administering powers, and the choices of voters.", "Judgement: the UN provided the framework, but local actors and the administering powers shaped the outcome."], "A reasoned, balanced judgement.")],
    [M("‘Cross-referencing’ sources means", "Comparing them with each other", ["Copying one source", "Ignoring the date", "Using only the longest one"], "It tests reliability."),
     TF("A good conclusion should include a judgement supported by the essay.", True, "A conclusion explains which factor mattered most."),
     MT("Match the command word to what it asks for.", [("Describe", "Say what happened"), ("Explain", "Say why"), ("Assess", "Weigh up and judge"), ("Compare", "Show similarities and differences")], "Standard meaning."),
     M("Which is an inference?", "Working out an attitude not directly stated", ["Copying a date", "Counting words", "Retyping a quotation"], "Reading between the lines."),
     O("Explain why a government report might be less useful than a private diary for studying the daily life of ordinary people.", "A government report is written for officials and may stress policy and order, so ordinary people’s experiences may be missing. A diary records personal daily experience and feelings, though it reflects one person’s view. For daily life the diary may give richer detail, but the two can be used together.", "Report limits (1); diary strength (1); diary limit (1); combined use (1)."),
     O("Write a plan (not a full essay) for: ‘To what extent was the First World War the main reason for the end of colonial rule in Africa?’", "Introduction: war was important but not the only reason. Para 1: war weakened Europe, trained African soldiers and raised expectations. Para 2: African nationalism and organisation (parties, Pan-Africanism). Para 3: external pressures (UN, USA, USSR). Para 4: the Second World War as a bigger turning point than the First. Conclusion: judgement that several factors combined and the Second World War mattered more than the First.", "Clear thesis (1); at least three relevant factors (2); evidence mentioned (1); counter-view and judgement (1).")],
    [("A primary source is", "From the period studied", ["Written yesterday", "A textbook", "A modern film"], "First-hand evidence."),
     ("In an essay each paragraph should have", "Point, evidence, explanation and link", ["Only a date", "Only a quotation", "Only a list"], "PEEL-style structure."),
     ("‘How far’ calls for", "A judgement of extent", ["A date list", "A definition", "Copying a source"], "Evaluation."),
     ("Time spent planning the essay should be about", "Five minutes", ["No time", "Half the exam", "Two hours"], "A short plan helps."),
     ("Usefulness depends on", "The question being asked", ["The font of the source", "The length only", "The page number"], "A source is useful for something.")],
    (flow(["Read the question; underline the command word", "Plan: thesis, 3–4 paragraphs, counter-view", "Write: point, evidence, explanation, link", "Conclude with a judgement"], 440, "blue", 13, 340),
     "Planning and writing an essay.", "Four boxes in a chain from reading the question to writing a conclusion."),
    ["Command words and mark schemes should follow the official GCE Board guidance.", "The extracts in this lesson are imaginary and written for practice."])

# =================================================== MOCK
q = mock_fill(L, [
    (M("Which year saw the independence of French Cameroun?", "1960", ["1884", "1961", "1972"], "1 January 1960."), 1),
    (M("Which body supervised mandates after the First World War?", "The League of Nations", ["The African Union", "NATO", "The Commonwealth"], "Through the Permanent Mandates Commission."), 1),
    (M("The OAU was founded in", "1963", ["1945", "1884", "2002"], "At Addis Ababa."), 1),
    (M("Who hosted the Berlin Conference?", "Otto von Bismarck", ["Winston Churchill", "Nelson Mandela", "Kwame Nkrumah"], "German chancellor."), 1),
    (M("Which was the first sub-Saharan colony to gain independence from Britain?", "Ghana (1957)", ["Nigeria (1960)", "Kenya (1963)", "Cameroon (1961)"], "6 March 1957."), 1),
    (M("The Cold War was mainly between", "USA and USSR", ["Britain and France", "Germany and Italy", "Egypt and Libya"], "Two superpowers."), 1),
    (TF("The United Nations replaced the League of Nations after the Second World War.", True, "The UN was founded in 1945."), 1),
    (TF("African rulers were invited to the Berlin Conference.", False, "No African ruler attended."), 1),
    (MT("Match the date to the event.", [("1884", "Treaty with Duala chiefs"), ("1916", "Anglo-French partition of Kamerun"), ("1946", "UN trusteeship for the Cameroons"), ("1972", "United Republic of Cameroon")], "Standard dates."), 2),
    (N("The Federal Republic of Cameroon was created in 1961 and replaced by a unitary state in 1972. How many years did the federation last?", 11, "1972 − 1961 = 11.", 0, "years"), 2),
    (P("Imaginary extract for practice: ‘Under our rule trade has grown and the people are content.’ (a colonial official, 1920s).", [pm("The origin of this source suggests it is probably", "Biased towards the colonial authorities", ["A neutral summary", "Written by a farmer", "A modern textbook"], "An official has a purpose to present success.", 1), pm("To judge its reliability a historian should", "Compare it with other sources such as African accounts", ["Accept it fully", "Ignore it", "Use only this source"], "Cross-referencing.", 1)]), None),
    (O("Explain the causes of decolonisation in Africa after 1945 and compare two routes to independence.", "Causes: the weakening of Britain and France, returning soldiers, rising nationalism and parties, Pan-Africanism, pressure from the UN, USA and USSR. Routes: Ghana gained independence by negotiation and elections in 1957; Algeria through an armed struggle ending in 1962. Circumstances such as settler presence and colonial policy explain the difference.", "Causes (1); comparison of two routes (1); explanation of difference (1)."), 3),
    (O("To what extent was Cold War rivalry beneficial to Africa?", "Benefits: rivalry gave aid and support to anti-colonial movements and encouraged non-alignment. Costs: proxy wars such as in Angola prolonged conflict, and arms flowed into the continent. After 1991 the end of the rivalry reduced support but allowed political change. The effect was mixed and varied by country.", "Benefits (1); costs (1); balanced judgement (1)."), 3),
])
p.mock("1", "GCE A Level mock — History", 150,
       "Answer ALL the questions. Marks are shown for each question (total 20). This mock paper is a CastBridge practice paper: its format is simplified and is to be checked against the official texts of the Cameroon GCE Board.",
       [("Section A — Short questions (10 marks)", q[0:9]), ("Section B — Calculation and sources (4 marks)", q[9:11]), ("Section C — Structured questions (6 marks)", q[11:13])])
p.write()
