"""Generates form4-food-science (Form 4, non-exam) and gceol-food-science (Form 5, GCE-OL)."""
import sys
sys.path.insert(0, "/home/user/CastBridge/tools/learn-authoring/anglophone")
from _cs import *

HEALTH = "Nutrition and health statements are general, textbook-level and conservative: a dietitian or health worker must review them before release."
KJ = {"carbohydrate": 17, "protein": 17, "fat": 37}   # kJ per gram used in this pack (flagged for review)
def energy(c, p_, f): return c * KJ["carbohydrate"] + p_ * KJ["protein"] + f * KJ["fat"]
assert energy(60, 20, 10) == 1730 and round(10 * 37 / 1730 * 100, 1) == 21.4 and round(1730 / 4.2) == 412
assert round(3500 / 10000 * 100) == 35 and 2 ** 6 == 64

def mkpack(pid, title, level, exam, ref, desc):
    return Pack(pid, title, level=level, subject="sciences", cursus="secondary", exam=exam, wanted="food-science", programRef=ref, description=desc)

# ============================================================================= FORM 4
REF4 = "Cameroon secondary (general education) Food Science and Nutrition programme, Form 4 — to be checked against the official programme"
p = mkpack("form4-food-science", "Food Science and Nutrition — Form 4", "Form 4", None, REF4,
           "Nutrients, a balanced diet and meal planning with Cameroonian foods, food hygiene and kitchen safety, cooking methods and food preservation.")
c = p.chapter("nutrition", "Food and nutrients", REF4)

lesson(c, "nutrients-macro", "Carbohydrates, fats and proteins",
  ["Name the main nutrients and say why we need them", "Give Cameroonian food sources of carbohydrates, fats and proteins", "State the main function of each", "Say which nutrients provide energy"],
  [("definition", "Nutrients", "**Nutrients** are the substances in food that the body uses. The main groups are **carbohydrates**, **fats**, **proteins**, **vitamins**, **minerals**, **water** and **fibre**. Carbohydrates, fats and proteins are needed in larger amounts and are called **macronutrients**."),
   ("retenir", "Carbohydrates and fats", "**Carbohydrates** (starches and sugars) give energy. Sources: cassava, plantain, maize, rice, yams, cocoyam, bread. **Fats and oils** give a concentrated supply of energy, protect organs and carry some vitamins. Sources: palm oil, groundnut oil, groundnuts, butter, fatty fish."),
   ("retenir", "Proteins", "**Proteins** are for **growth and repair** of the body (they can also give energy). Sources: fish, meat, eggs, milk, beans, groundnuts, soya, crayfish. Proteins from animals and plants can be combined in a meal, for example beans with maize or plantain."),
   ("attention", "Be careful", "- 'Energy foods' means mainly carbohydrates and fats.\n- Too much sugar and fat is not healthy; keep a balance.\n- Do not say a single food gives everything the body needs. " + "Health information here is general and flagged for review.")],
  ("Nutrient table", cols("Main nutrients, jobs and foods", ["Nutrient", "Main job", "Example"], [["Carbohydrate", "Energy", "Cassava, rice"], ["Fat / oil", "Energy store", "Palm oil"], ["Protein", "Growth, repair", "Beans, fish"]], w=440, size=12),
   "A table with carbohydrate, fat and protein, their main job and an example food.", "Table of three nutrients with their job and a food example."),
  [("Example 1", "Classify these local foods by their main nutrient: plantain, beans, palm oil.", ["Plantain is mainly starch, a carbohydrate.", "Beans give protein; palm oil is a fat/oil."], "Carbohydrate, protein, fat"),
   ("Example 2", "A child in Buea is growing fast. Which nutrient is especially important and which foods could supply it?", ["Growth needs protein.", "Examples: fish, eggs, beans, groundnuts (according to what the family can afford)."], "Protein: fish, eggs, beans, groundnuts")],
  [M("Which nutrient is needed mainly for growth and repair?", "Protein", ["Fibre", "Water", "Sugar only"], "Protein."),
   M("Cassava and plantain are mainly sources of", "carbohydrate", ["protein", "vitamin C only", "fibre only"], "Starch."),
   TF("Palm oil is a source of fat.", True, "Oils are fats.")],
  [MT("Match the food to the nutrient it mostly gives.", [("Beans", "Protein"), ("Rice", "Starch (carbohydrate)"), ("Groundnut oil", "Fat"), ("Orange", "Vitamin C")], "General food-group knowledge."),
   O("Explain why a person who eats only cassava every day may not be well nourished.", "Cassava is mainly carbohydrate. It gives energy but little protein, fat, vitamins and minerals, so the diet is not balanced; other foods such as beans, fish and vegetables are needed.", "1 mark: mainly carbohydrate; 1 mark: lacks other nutrients; 1 mark: suggests other foods.")],
  P("A school canteen sells garri and beans, fried plantain with fish, and rice and vegetable stew.",
    [pm("Which food in these meals is the main protein source?", "Beans or fish", ["Garri", "Rice", "Plantain"], "Beans and fish."),
     pm("Which food mainly gives energy?", "Garri, plantain or rice", ["Fish", "Beans only", "None"], "Starchy foods."),
     po("Suggest one addition to make the plantain-and-fish meal more balanced.", "Add a vegetable or fruit (such as green leaves or oranges) for vitamins and fibre.", "1 mark each.")]),
  [("Carbohydrates mainly give", "energy", ["growth only", "water", "colour"], "Energy."),
   ("Eggs are a good source of", "protein", ["fibre only", "starch", "sugar"], "Protein."),
   ("Groundnuts give protein and", "fat", ["no nutrients", "only water", "only fibre"], "Both."),
   ("Macronutrients are", "needed in large amounts", ["found only in water", "not needed", "poisonous"], "Large amounts."),
   ("Which is a fat?", "Palm oil", ["Rice", "Water", "Salt"], "Oil.")],
  notes=[HEALTH], minutes=20)

lesson(c, "vitamins-minerals", "Vitamins, minerals, water and fibre",
  ["Name important vitamins and minerals and their functions", "Give food sources", "Explain why water and fibre are needed", "Say what happens when a nutrient is lacking (in general terms)"],
  [("definition", "Vitamins and minerals", "**Vitamins** and **minerals** are needed in small amounts to keep the body healthy. **Vitamin A** helps sight and the skin; **vitamin C** helps the body heal and resist infection; **vitamin D** helps bones (the body also makes it with sunlight); **iron** helps make blood; **calcium** builds bones and teeth; **iodine** helps the thyroid gland."),
   ("retenir", "Sources", "Vitamin A: orange and green leafy vegetables, red palm oil, liver, eggs. Vitamin C: oranges, guavas, mangoes, pawpaw, tomatoes and fresh vegetables. Iron: meat, fish, beans, green leaves. Calcium: milk, small fish eaten with bones, green leaves. Iodine: fish and iodised salt."),
   ("retenir", "Water and fibre", "**Water** is needed for blood, digestion, removing waste and keeping body temperature steady: drink clean, safe water. **Fibre** (from whole grains, fruits, vegetables, beans) is not digested but helps food move through the gut and helps prevent constipation."),
   ("pieges", "Be careful", "- Overcooking vegetables can destroy some vitamin C.\n- Peeling and washing after cutting loses vitamins.\n- Taking large doses of supplements is not a replacement for a varied diet; ask a health worker.\n- " + HEALTH)],
  ("Sources", cols("Vitamins, minerals and foods", ["Nutrient", "Food"], [["Vitamin A", "Palm oil, green leaves"], ["Vitamin C", "Orange, guava"], ["Iron", "Beans, fish, meat"], ["Calcium", "Milk, small fish"]]),
   "A table pairing four nutrients with food sources.", "Table: vitamin A with palm oil and green leaves, vitamin C with orange and guava, iron with beans, fish and meat, calcium with milk and small fish."),
  [("Example 1", "Which foods in the market can give vitamin C?", ["Fresh fruit and vegetables are the main source.", "Examples: oranges, guavas, pawpaw, tomatoes."], "Oranges, guavas, pawpaw, tomatoes"),
   ("Example 2", "Why should vegetables not be boiled for a very long time?", ["Some vitamins, such as vitamin C, are damaged by heat and dissolve in the water.", "Cook briefly, use little water and use any cooking water in the sauce."], "To keep their vitamins")],
  [M("Which food is a good source of vitamin C?", "Orange", ["Rice only", "Salt", "Sugar"], "Citrus fruit."),
   M("Calcium is needed for", "bones and teeth", ["only the eyes", "only the skin", "only the nails"], "Calcium."),
   TF("Fibre helps food to move through the gut.", True, "Yes.")],
  [M("Why is drinking safe water important?", "Water is needed in the body and unsafe water spreads disease", ["Water gives energy like sugar", "Water makes bones", "It is not important"], "Water."),
   O("Give two foods that give iron and say why iron is needed.", "Beans, fish and meat give iron. Iron is needed to make red blood cells that carry oxygen.", "1 mark each food, 1 mark function.")],
  P("A teenager in Garoua eats mostly rice and no fruit or vegetables.",
    [pm("Which group of nutrients might be low?", "Vitamins and fibre", ["Starch", "Water only", "Salt"], "No fruit or vegetables."),
     pt("Adding green leaves and fruit would help.", True, "They give vitamins and fibre."),
     po("Suggest two foods to add.", "Green vegetables such as leaves and a fruit such as orange or pawpaw.", "1 mark each.")]),
  [("Vitamin A helps", "sight and skin", ["only the teeth", "digestion of fats only", "nothing"], "Vitamin A."),
   ("Iodised salt provides", "iodine", ["vitamin C", "fibre", "fat"], "Iodine."),
   ("Fibre comes from", "plant foods", ["only meat", "only milk", "only sugar"], "Plant foods."),
   ("A mineral for bones is", "calcium", ["fat", "starch", "sugar"], "Calcium."),
   ("Water helps", "remove waste and carry nutrients", ["nothing in the body", "only taste", "only colour"], "Water.")],
  notes=[HEALTH, "Food sources are general examples; local composition tables should be used for precise claims."], minutes=20)

lesson(c, "balanced-diet", "A balanced diet and meal planning",
  ["Define a balanced diet", "Use the plate or pyramid idea", "Plan a simple balanced meal with local foods", "Name factors that affect food choices"],
  [("definition", "Balanced diet", "A **balanced diet** contains all the nutrients in the right amounts for a person's age, sex, activity and health. It includes **energy foods** (staples), **body-building foods** (proteins), **protective foods** (fruit and vegetables) and enough water and fibre."),
   ("retenir", "Plate idea", "A simple guide: fill about **half the plate** with vegetables and fruit, about **a quarter** with starchy staple foods (cassava, plantain, maize, rice) and about **a quarter** with protein foods (fish, beans, eggs, meat), and use only a little oil, sugar and salt. These proportions are a general teaching guide, flagged for review."),
   ("methode", "Planning a meal", "1. Choose a staple (e.g. fufu corn, plantain). 2. Add a protein (fish, beans, groundnuts). 3. Add a vegetable or fruit (eru, green leaves, tomatoes, mango). 4. Use little oil and salt. 5. Check cost and what is in season."),
   ("attention", "Be careful", "- Different people need different amounts: children, pregnant women and manual workers have special needs.\n- A cheap meal can still be balanced with beans, groundnuts and vegetables.\n- " + HEALTH)],
  ("Plate", stackbar("A balanced plate (guide)", [("Vegetables, fruit", 50, "lightgreen"), ("Staple foods", 25, "lightyellow"), ("Protein foods", 25, "lightorange")], w=420, h=150),
   "A single bar showing half vegetables and fruit, a quarter staple foods and a quarter protein foods.", "Stacked bar guide: 50 percent vegetables and fruit, 25 percent staple foods, 25 percent protein foods."),
  [("Example 1", "Plan a balanced lunch with ndolé (a bitterleaf and groundnut dish) and plantain. What is missing?", ["Ndolé is a leafy dish with groundnuts (and often fish or meat): protein and vegetable. Plantain is the staple (carbohydrate).", "A fruit such as pawpaw or orange could be added for vitamin C."], "Add a fruit and water"),
   ("Example 2", "A family has little money. Suggest a balanced and cheap dinner.", ["Staple: maize or cassava. Protein: beans or groundnuts.", "Vegetable: green leaves or tomato; use little oil."], "Maize/cassava + beans + vegetable")],
  [M("A balanced diet contains", "all nutrients in suitable amounts", ["only sugar", "only meat", "only water"], "Balanced."),
   M("Fruit and vegetables are mainly", "protective foods", ["only energy foods", "only body-building foods", "poisonous"], "Vitamins and fibre."),
   TF("A cheap meal cannot be balanced.", False, "Beans, groundnuts and vegetables are low-cost and nutritious.")],
  [M("Which meal is best balanced?", "Cassava, beans and green vegetables", ["Only cassava", "Only bread and sugar", "Only soft drinks"], "Staple, protein and vegetable."),
   O("List four factors that affect the food a family chooses.", "Income, availability and season, culture and tastes, health and age, knowledge, time for cooking.", "1 mark each, 4 factors.")],
  P("Ngozi plans a meal: rice, fried fish, and a salad of tomato and cabbage.",
    [pm("The rice is mainly", "carbohydrate", ["protein", "vitamin", "water"], "Staple."),
     pm("The fish is mainly", "protein", ["carbohydrate", "fibre", "sugar"], "Protein."),
     po("Suggest one drink and one fruit to add.", "Water and an orange (or other fruit).", "1 mark each.")]),
  [("Staple foods are", "main energy foods", ["only vitamins", "only fats", "only spices"], "Staples."),
   ("A guide plate has about half", "vegetables and fruit", ["sugar", "oil", "salt"], "Guide."),
   ("A pregnant woman usually needs", "a varied diet with enough of all nutrients", ["no food", "only sugar", "only salt"], "General."),
   ("Beans are a source of", "protein", ["only fat", "only water", "none"], "Protein."),
   ("Planning meals helps to", "balance nutrients and cost", ["waste food", "avoid fruit", "skip meals"], "Planning.")],
  notes=[HEALTH, "Plate proportions (50/25/25) are a common teaching guide, not an official national recommendation: check the national food-based dietary guidelines."], minutes=20)

c = p.chapter("hygiene", "Food hygiene, cooking and preservation", REF4)
lesson(c, "hygiene-safety", "Food hygiene and kitchen safety",
  ["Explain why food hygiene matters", "List personal, food and kitchen hygiene rules", "Describe how germs spread to food", "Apply kitchen safety rules"],
  [("definition", "Food hygiene", "**Food hygiene** means keeping food safe to eat. Germs (**bacteria**, viruses, moulds) on hands, surfaces, flies, dirty water or raw meat can contaminate food and cause **food poisoning** with stomach pain, vomiting and diarrhoea."),
   ("methode", "Rules", "- **Wash hands** with soap and clean water before cooking and after using the toilet or touching raw meat or fish.\n- Keep long hair tied and nails clean; cover cuts.\n- Wash fruit and vegetables.\n- Keep raw and cooked food **separate**; use different knives and boards.\n- Cook food thoroughly and keep it covered; store leftovers safely and heat them well.\n- Use clean (boiled or treated) water."),
   ("methode", "Kitchen safety", "Turn pan handles inwards; keep children away from fire; do not leave cooking unattended; dry hands before touching electrical items; keep knives sharp and cut away from your body; clean up spills; store gas cylinders safely and check for leaks as taught by a qualified person."),
   ("pieges", "Be careful", "- Food left in warm conditions for hours can make people ill even if it smells normal.\n- A cloth used for everything spreads germs.\n- First aid advice must come from a trained person. " + HEALTH)],
  ("Rules", cols("Hygiene: do and do not", ["Do", "Do not"], [["Wash hands", "Cook with dirty hands"], ["Cover food", "Leave food open to flies"], ["Separate raw / cooked", "Use one board for all"], ["Use safe water", "Use dirty water"]]),
   "A table of four hygiene actions to do and to avoid.", "Table of do and do-not food hygiene rules."),
  [("Example 1", "Raw chicken was cut on a board. Then the same board was used for salad. What is wrong and what should be done?", ["Germs from raw chicken can pass to the salad (cross-contamination).", "Use separate boards or wash the board well with hot soapy water before using it for ready-to-eat food."], "Cross-contamination: separate boards or wash well"),
   ("Example 2", "Bacteria may double about every 20 minutes in warm conditions (an illustration). How many times larger is one group after 2 hours?", ["2 hours = 120 minutes = 6 periods of 20 minutes.", "Each period doubles: 2^6 = 64 times."], "About 64 times")],
  [M("Before cooking you should", "wash your hands with soap and clean water", ["rub them with oil", "do nothing", "wipe on your clothes"], "Hand washing."),
   M("Cross-contamination means", "germs passing from one food to another", ["cooking twice", "freezing food", "adding salt"], "Definition."),
   TF("Pan handles should stick out over the edge of the stove.", False, "Turn them inwards.")],
  [M("Which is the best way to store cooked food for a few hours in a hot kitchen?", "Covered and kept cool or in a fridge if available", ["Uncovered on the table", "Near the fire", "In the sun"], "Cover and keep cool."),
   O("Give four rules of personal hygiene for people who prepare food.", "Wash hands; wear clean clothes or an apron; tie long hair; keep nails short and clean; cover cuts; do not cough over food.", "1 mark each, 4 marks.")],
  P("At a school feeding programme in Kumba, cooks prepare rice and stew for 200 pupils.",
    [pm("Which action prevents food poisoning?", "Washing hands and cooking thoroughly", ["Leaving food open", "Using dirty plates", "Not washing vegetables"], "Hygiene."),
     pn("Bacteria double every 20 minutes (illustration). How many times larger after 1 hour?", 8, "3 periods: 2^3 = 8."),
     po("Suggest one rule for serving leftovers.", "Reheat thoroughly until very hot throughout and eat the same day, or throw away if unsure.", "1 mark.")]),
  [("Food poisoning is commonly caused by", "germs in food", ["vitamins", "fibre", "water only"], "Germs."),
   ("Flies can spread germs to food if food is", "left uncovered", ["covered", "in a closed container", "in a fridge"], "Cover food."),
   ("Raw and cooked foods should be kept", "separate", ["together", "in the same bowl", "on the same board"], "Separate."),
   ("Safe drinking water can be made by", "boiling or proper treatment", ["adding sugar", "adding oil", "leaving it in the sun uncovered"], "Boil or treat."),
   ("A spill on the kitchen floor should be", "cleaned up at once", ["ignored", "left overnight", "covered with paper"], "Safety.")],
  notes=[HEALTH, "20-minute doubling time is illustrative (it varies by organism and conditions). Safe-water treatment methods follow local health guidance."], minutes=20)

lesson(c, "cooking-methods", "Cooking methods",
  ["Name the main methods of cooking", "Give examples with local foods", "State reasons for cooking food", "Choose a method for a purpose"],
  [("definition", "Why cook?", "Cooking makes food **safer** (kills many germs), **easier to chew and digest**, **tastier** and sometimes longer-lasting. But cooking can also **reduce some vitamins**, so use suitable methods and times."),
   ("retenir", "Methods", "**Boiling** in bubbling water (cassava, plantain, eggs). **Steaming** over water (moin-moin, vegetables). **Frying** in hot oil (puff-puff, fried plantain, fish). **Roasting/grilling** by dry heat (corn, plantain, fish). **Baking** in an oven (bread, cakes). **Stewing** slowly in a sauce (ndolé, stews)."),
   ("retenir", "Choosing a method", "Boiling and steaming add no fat; steaming keeps more vitamins than boiling in a lot of water. Frying adds fat and energy; use fresh oil and do not reuse it many times. Grilling can be a lighter method if food is not burnt."),
   ("pieges", "Be careful", "- Burnt or blackened food should not be eaten often.\n- Keep fat for frying at a safe temperature; hot oil can cause serious burns.\n- Cassava (especially bitter types) must be well processed and cooked as traditionally done. " + HEALTH)],
  ("Methods", cols("Methods and local examples", ["Method", "Example"], [["Boiling", "Cassava, eggs"], ["Steaming", "Moin-moin"], ["Frying", "Puff-puff, fish"], ["Roasting", "Corn, plantain"]]),
   "A table of four cooking methods with local examples.", "Table: boiling cassava and eggs, steaming moin-moin, frying puff-puff and fish, roasting corn and plantain."),
  [("Example 1", "Which method is best to cook green vegetables to keep their vitamins?", ["Long boiling in much water loses vitamins.", "Steaming or cooking quickly with little water keeps more of them."], "Steam or cook quickly with little water"),
   ("Example 2", "Name the cooking method for each: (a) puff-puff, (b) boiled plantain, (c) roasted corn.", ["(a) Puff-puff is deep-fried in oil.", "(b) Boiling in water. (c) Roasting over heat."], "Frying, boiling, roasting")],
  [M("Cooking food in bubbling water is", "boiling", ["frying", "baking", "roasting"], "Boiling."),
   M("Which method uses a lot of oil?", "Frying", ["Steaming", "Boiling", "Soaking"], "Frying."),
   TF("Cooking can make food safer by killing many germs.", True, "Heat kills many germs.")],
  [M("Which cooking method adds no fat?", "Steaming", ["Deep frying", "Frying in oil", "Roasting in oil"], "Steaming."),
   O("Give three reasons for cooking food.", "To kill germs; to make food easier to chew and digest; to improve taste and smell; to make some foods safe (such as cassava).", "1 mark each, 3.")],
  P("Mama Rose cooks for her family: she steams moin-moin, boils plantain and fries fish.",
    [pm("Which dish uses steam?", "Moin-moin", ["Plantain", "Fish", "None"], "Steamed."),
     pm("Which dish adds the most fat?", "Fried fish", ["Boiled plantain", "Steamed moin-moin", "None"], "Frying uses oil."),
     po("Suggest a healthier way to cook the fish.", "Grill or steam or boil it instead of frying.", "1 mark.")]),
  [("Baking is cooking in", "an oven", ["water", "oil only", "the sun only"], "Baking."),
   ("Boiling uses", "bubbling water", ["hot oil", "an oven", "no heat"], "Boiling."),
   ("Re-using oil many times is", "not advisable", ["recommended", "needed", "healthy"], "Avoid."),
   ("Stewing means cooking", "slowly in a sauce", ["quickly in oil", "without heat", "frozen"], "Stew."),
   ("Cooking can reduce some", "vitamins", ["minerals only", "water", "salt only"], "Heat-sensitive vitamins.")],
  notes=[HEALTH], minutes=20)

lesson(c, "preservation-basics", "Food preservation",
  ["Explain why food is preserved", "Describe drying, smoking, salting, refrigeration, freezing and canning", "Give local examples", "Say how each method slows spoilage"],
  [("definition", "Why preserve?", "Food spoils because of **microorganisms** (bacteria, yeasts, moulds) and **enzymes**. Preservation **slows or stops spoilage** so food lasts longer, reduces waste, keeps food available out of season and helps trade."),
   ("retenir", "Methods", "**Drying** removes water (dried fish, crayfish, maize, beans). **Smoking** dries and adds protective substances (smoked fish and meat). **Salting** draws out water (salted fish). **Refrigeration** (cold) slows growth of germs; **freezing** nearly stops it. **Canning** heats food in sealed containers. **Sugar** and **pickling** (vinegar) are also used."),
   ("methode", "How they work", "Microorganisms need **water, warmth, food, time and (often) air**. Preservation takes away one or more of these: drying removes water; cold removes warmth; canning kills germs and seals out air; salt and sugar make water unavailable."),
   ("pieges", "Be careful", "- Preserved food can still spoil if stored badly (damp, hot).\n- Do not eat swollen or leaking cans or food with mould.\n- Dry grains and groundnuts well and store them dry to avoid harmful moulds. " + HEALTH)],
  ("Methods", cols("Preservation methods", ["Method", "Removes / does", "Example"], [["Drying", "Water", "Dried fish"], ["Smoking", "Dries + smoke", "Smoked fish"], ["Cold", "Warmth", "Fridge"], ["Canning", "Germs, air", "Tinned fish"]], w=440, size=12),
   "A table of four preservation methods, what each removes or does, and an example.", "Table: drying removes water, smoking dries with smoke, cold removes warmth, canning removes germs and air."),
  [("Example 1", "Why does dried fish last longer than fresh fish?", ["Microorganisms need water to grow.", "Drying removes most of the water, so germs cannot grow."], "Removing water stops growth"),
   ("Example 2", "Name a method to keep milk for several days in a home with a fridge and explain.", ["Refrigeration keeps milk cold.", "Low temperature slows the growth of germs; it does not make milk last forever."], "Refrigeration slows growth")],
  [M("Drying preserves food by", "removing water", ["adding water", "adding germs", "heating oil"], "Drying."),
   M("Smoked fish is an example of", "preservation", ["spoilage only", "fertiliser", "a drink"], "Smoking."),
   TF("Freezing nearly stops the growth of microorganisms.", True, "Cold slows or stops growth.")],
  [M("Which food is preserved by canning?", "Tinned sardines", ["Fresh tomatoes", "Eggs only", "Raw meat on a table"], "Canning."),
   O("Explain two ways of preserving fish.", "Drying in the sun or in a smoker removes water; smoking also adds protection; salting draws out water; freezing slows microorganisms.", "1 mark each method, 1 mark explanation.")],
  P("A fish seller in Limbe wants to keep her fish for several days without a fridge.",
    [pm("Which method is suitable?", "Smoking or drying", ["Leaving it in the sun uncovered at the market", "Washing only", "Covering with sugar only"], "Drying/smoking."),
     pm("Why does this work?", "It removes water so germs cannot grow", ["It adds vitamins", "It makes the fish sweet", "It cools the fish"], "Water removal."),
     po("Give one safety rule for storing the smoked fish.", "Keep it dry, covered and away from flies; check for mould or bad smell before use.", "1 mark.")]),
  [("Canning heats food and", "seals it in a container", ["adds water", "adds oil", "dries it"], "Canning."),
   ("Salting helps preserve because it", "draws out water", ["adds water", "adds sugar", "heats food"], "Salt."),
   ("Microorganisms need", "water, warmth and food", ["only light", "only salt", "only cold"], "Needs."),
   ("A refrigerator", "slows spoilage", ["stops all spoilage", "kills all germs", "makes food sterile"], "Slows."),
   ("A swollen tin should be", "thrown away", ["eaten at once", "heated and eaten", "given to children"], "Safety.")],
  notes=[HEALTH, "Smoking fish: health concerns about smoke compounds exist; wording is simplified and should be reviewed."], minutes=20)
write(p)

# ============================================================================= GCE O LEVEL
REF = "Cameroon GCE Board — Ordinary Level Food Science and Nutrition syllabus — to be checked against the official text"
p = mkpack("gceol-food-science", "Food Science and Nutrition — GCE O Level", "Form 5", "GCE-OL", REF,
           "Nutrients, balanced diet, energy needs with calculations, digestion, cooking, hygiene, preservation and spoilage, deficiency diseases, additives, consumer education and budgeting, with a mock paper.")
c1 = p.chapter("nutrients", "Nutrients and diet", REF)

L1 = lesson(c1, "macronutrients", "Carbohydrates, fats and proteins",
  ["Classify carbohydrates as sugars and starch", "Describe functions and sources of fats and proteins", "Distinguish saturated and unsaturated fats in outline", "Name examples of complete and incomplete proteins in simple terms"],
  [("definition", "Carbohydrates", "**Carbohydrates** are made of carbon, hydrogen and oxygen. **Sugars** (glucose, sucrose, lactose) are sweet and dissolve in water; **starch** is in cassava, plantain, maize, rice and yams. Starch is digested to glucose, the body's main fuel. **Cellulose** is a carbohydrate in plant walls that humans cannot digest; it forms part of dietary fibre."),
   ("definition", "Fats and oils", "**Fats** (solid at room temperature) and **oils** (liquid) are made of **fatty acids** and **glycerol**. They give a concentrated source of energy, insulate and protect organs, and carry **vitamins A, D, E and K**. **Saturated** fats are mostly from animals (butter, fat on meat); **unsaturated** fats are mostly from plants and fish (groundnut oil, fish oil). Palm oil is a plant oil that has a fairly high saturated fat content; a little is enough."),
   ("definition", "Proteins", "**Proteins** are made of **amino acids**. They are needed for growth, repair of tissue, and for enzymes and hormones. Foods with all the **essential amino acids** in good amounts (eggs, milk, fish, meat) are called **first-class** (or complete); many plant proteins (beans, maize) are lower in one or more essential amino acids, but **mixing** them (for example beans with maize) improves the balance."),
   ("attention", "Be careful", "- Fat is not 'bad': the body needs some; too much, especially saturated fat, is a health concern.\n- Sugar gives energy but no other nutrients ('empty' energy).\n- Excess protein is used for energy or stored as fat; it is not 'saved' as muscle. " + HEALTH)],
  ("Food pyramid", pyramid("Eating pyramid (guide)", ["Fats, oils, sugar (little)", "Protein foods", "Fruit and vegetables", "Staple foods (largest)"]),
   "A pyramid with staple foods at the base, then fruit and vegetables, protein foods, and a small top for fats, oils and sugar.", "Food pyramid from staples at the bottom to fats, oils and sugar at the top."),
  [("Example 1 - Classify", "Classify: cassava, groundnut oil, beans, honey.", ["Cassava is rich in starch (carbohydrate); honey is mostly sugar (carbohydrate).", "Groundnut oil is a fat/oil; beans are a protein food."], "Starch, fat, protein, sugar"),
   ("Example 2 - Mixing proteins", "Why is beans eaten with maize better than either alone?", ["Maize and beans are each lower in some essential amino acids.", "Together they supply a better balance of amino acids."], "They complement each other")],
  [M("Starch is found in", "plantain and cassava", ["fish oil", "salt", "water"], "Starchy foods."),
   M("Fats carry the vitamins", "A, D, E and K", ["only C", "B and C only", "none"], "Fat-soluble vitamins."),
   TF("Cellulose is digested by humans.", False, "Humans cannot digest cellulose; it is fibre.")],
  [M("Which is a first-class protein food?", "Egg", ["Sugar", "Cassava", "Salt"], "Eggs contain all essential amino acids."),
   O("Explain what is meant by 'complementary proteins' and give an example.", "Plant proteins that are low in different essential amino acids can be eaten together so that the mixture is better balanced, for example beans with maize.", "1 mark meaning, 1 mark explanation, 1 mark example.")],
  P("A meal contains: boiled plantain (starchy), fried fish, a small amount of palm oil and green vegetables.",
    [pm("The main source of starch is", "plantain", ["fish", "palm oil", "vegetables"], "Plantain."),
     pm("The main source of protein is", "fish", ["plantain", "oil", "water"], "Fish."),
     po("Name the nutrient provided by the palm oil and one function.", "Fat (oil); a concentrated source of energy (or carrying fat-soluble vitamins).", "1 mark nutrient, 1 mark function.")]),
  [("Proteins are made of", "amino acids", ["fatty acids", "starch", "fibre"], "Amino acids."),
   ("Fats are made of", "fatty acids and glycerol", ["amino acids", "glucose only", "water"], "Fats."),
   ("A main function of carbohydrate is", "energy", ["making enzymes only", "insulating only", "digesting"], "Energy."),
   ("Sugar mostly gives", "energy only", ["all vitamins", "all minerals", "growth only"], "Empty energy."),
   ("Unsaturated fats are mostly from", "plants and fish", ["only butter", "only fat of meat", "only milk"], "General statement.")],
  notes=[HEALTH, "Palm oil: statement about saturated fat content is general; check local nutrition tables. 'Empty energy' is a textbook phrase."], minutes=25)

L2 = lesson(c1, "micronutrients", "Vitamins, minerals, water and fibre",
  ["Describe functions of vitamins A, B group, C, D and K in general terms", "Describe functions of calcium, iron, iodine, phosphorus and sodium", "Explain the importance of water and fibre", "Give Cameroonian food sources"],
  [("definition", "Vitamins", "**Fat-soluble** vitamins (A, D, E, K) are stored in the body; **water-soluble** vitamins (B group, C) are not stored in large amounts and are easily lost in cooking water. A: sight, skin and resistance to infection. B group: release of energy from food and healthy nerves. C: healing and healthy gums and blood vessels. D: absorption of calcium for bones. K: blood clotting."),
   ("definition", "Minerals", "**Calcium** and **phosphorus**: bones and teeth. **Iron**: part of haemoglobin in red blood cells. **Iodine**: thyroid hormones. **Sodium** and **potassium**: water balance and nerve function. **Fluoride**: strong teeth. Too much salt (sodium) is linked with high blood pressure, so use salt moderately."),
   ("retenir", "Sources", "A: red palm oil, dark green leaves, orange fruits, liver, eggs. B group: whole grains, beans, groundnuts, meat, fish. C: guava, orange, mango, pawpaw, tomatoes, fresh leaves. D: oily fish, eggs, and sunlight on skin. Iron: meat, fish, beans, green leaves. Calcium: milk, small fish with bones, green leaves. Iodine: fish and iodised salt."),
   ("retenir", "Water and fibre", "**Water** is a solvent, helps digestion, carries nutrients and wastes in blood and controls body temperature (sweating). **Dietary fibre** (cellulose in vegetables, fruits, whole grains, beans) adds bulk, helps peristalsis and prevents constipation."),
   ("pieges", "Be careful", "- Vitamin C is destroyed by long cooking and lost in the water.\n- Iron from plant foods is absorbed less well than iron from meat; vitamin C in the same meal helps.\n- Do not give supplements without health-worker advice. " + HEALTH)],
  ("Table", cols("Nutrient, function, source", ["Nutrient", "Function", "Source"], [["Iron", "Blood", "Beans, fish"], ["Calcium", "Bones", "Milk, small fish"], ["Vit C", "Healing", "Guava, orange"], ["Vit A", "Sight", "Palm oil, leaves"]], w=440, size=12),
   "A table giving the function and food sources of iron, calcium, vitamin C and vitamin A.", "Table of four nutrients with function and local food sources."),
  [("Example 1", "A girl has pale skin and tires easily. Which mineral may be low, and which foods help? (General information only.)", ["Pale skin and tiredness can be signs of a shortage of iron (anaemia); a health worker should check.", "Iron-rich foods: meat, fish, beans, green leaves, with a vitamin C source."], "Iron; a health worker should be consulted"),
   ("Example 2", "Why is it better to cook leafy vegetables briefly?", ["Vitamin C and some B vitamins are water-soluble and heat-sensitive.", "Brief cooking with little water loses fewer vitamins."], "Less vitamin loss")],
  [M("Which vitamin helps blood to clot?", "Vitamin K", ["Vitamin C", "Vitamin A", "Vitamin D"], "K."),
   M("Which mineral is part of haemoglobin?", "Iron", ["Calcium", "Sodium", "Iodine"], "Iron."),
   TF("Fibre is digested into glucose in the body.", False, "Fibre is not digested.")],
  [MT("Match the nutrient with its main function.", [("Calcium", "Bones and teeth"), ("Iodine", "Thyroid hormones"), ("Vitamin D", "Absorption of calcium"), ("Vitamin A", "Sight")], "Standard functions."),
   O("Explain why water is essential for the body. Give three functions.", "It acts as a solvent for chemical reactions; carries nutrients and waste in the blood; helps cool the body by sweating; helps digestion.", "1 mark each, 3.")],
  P("Mama Eto eats mostly cassava with little other food. A health worker advises adding beans, green leaves and fruit.",
    [pm("Beans mainly add", "protein and iron", ["only fat", "only sugar", "only salt"], "General."),
     pm("Green leaves add", "vitamins, minerals and fibre", ["only fat", "only starch", "nothing"], "General."),
     po("Why might a fruit rich in vitamin C help when eating beans?", "Vitamin C helps the body absorb iron from plant foods.", "1 mark each.")]),
  [("Water-soluble vitamins include", "C and B group", ["A and D", "K and E", "none"], "Water-soluble."),
   ("Vitamin D helps the body absorb", "calcium", ["iodine", "fibre", "sugar"], "D and calcium."),
   ("Too much salt is linked to", "high blood pressure", ["strong bones", "better sight", "no effect"], "General statement."),
   ("Fibre helps prevent", "constipation", ["thirst", "hunger", "sleep"], "Peristalsis."),
   ("Iodised salt is used to supply", "iodine", ["iron", "calcium", "vitamin C"], "Iodine.")],
  notes=[HEALTH], minutes=25)

L3 = lesson(c1, "balanced-diet", "Balanced diet and meal planning",
  ["Define a balanced diet and list factors that affect dietary needs", "Plan meals for different people using local foods", "Evaluate a menu", "Use the food groups"],
  [("definition", "Balanced diet", "A **balanced diet** supplies all nutrients, fibre and water in suitable amounts for the person. Needs vary with **age**, **sex**, **activity (occupation)**, **climate**, **health** and special conditions such as **pregnancy** and **breastfeeding**. Growing children need relatively more protein, calcium and iron for their size."),
   ("retenir", "Food groups", "Staples (cassava, plantain, maize, rice, yam, cocoyam, bread) for energy; legumes, nuts and animal foods (beans, groundnuts, fish, eggs, meat, milk) for protein; fruit and vegetables (eru, bitterleaf, huckleberry leaves, tomatoes, mango, pawpaw) for vitamins, minerals and fibre; oils (palm oil, groundnut oil) in small amounts."),
   ("methode", "Planning a day", "Include a staple, a protein food and a vegetable or fruit in the main meals; snacks from fruit or groundnuts; vary foods through the week; consider cost, season, cooking time and the family's tastes; use different colours. Check that the day is not too rich in fat, sugar or salt."),
   ("attention", "Be careful", "- 'Balanced' is judged over the day or week, not on one meal.\n- A pregnant or breastfeeding woman needs advice from a health worker.\n- Food taboos and beliefs should be respected while giving correct health information. " + HEALTH)],
  ("Menu bars", stackbar("Share of a day's menu (illustrative)", [("Staples", 45, "lightyellow"), ("Fruit, veg", 30, "lightgreen"), ("Protein", 20, "lightorange"), ("Oil, sugar", 5, "lightblue")], w=440, h=150),
   "A bar showing an illustrative day's menu: staples 45 percent, fruit and vegetables 30, protein foods 20, oil and sugar 5.", "Stacked bar of an illustrative menu: staples 45, fruit and vegetables 30, protein foods 20, oil and sugar 5 percent."),
  [("Example 1 - Evaluate a menu", "Menu for a day: breakfast: tea with sugar and bread; lunch: rice and fried plantain; supper: garri and sugar water. Comment on balance.", ["The menu is high in starch and sugar and low in protein, vegetables and fruit.", "Improve it: add eggs or beans, a vegetable sauce (eru, tomatoes), and fruit; reduce sugar."], "Unbalanced: add protein, vegetables and fruit"),
   ("Example 2 - Plan", "Plan a balanced supper for a growing child using local foods.", ["Staple: boiled plantain or cassava. Protein: fish or beans.", "Vegetable: green leaves (e.g. eru) with a little oil; fruit such as pawpaw."], "Plantain, fish, eru, pawpaw")],
  [M("A balanced diet depends on a person's", "age, sex and activity", ["shoe size", "hair colour", "name"], "Needs differ."),
   M("Fruit and vegetables mainly give", "vitamins, minerals and fibre", ["only starch", "only protein", "only fat"], "Protective foods."),
   TF("A single meal must contain every nutrient in exact proportions.", False, "Balance is judged over the day or week.")],
  [M("Which person is likely to need more energy?", "A farmer doing heavy work", ["A person resting in bed all day", "A sleeping baby", "A person sitting all day"], "Activity increases need."),
   O("Plan a balanced day's meals for a Form 5 student using local foods and say why it is balanced.", "Breakfast: pap with groundnuts and fruit. Lunch: rice, beans, vegetable sauce. Supper: boiled plantain with fish and green leaves. It has staples (energy), protein (beans, fish, groundnuts) and vegetables/fruit (vitamins, minerals, fibre).", "1 mark each meal with all groups; 1 mark explanation.")],
  P("Esther is 15 and active in sport. Her daily food: white bread and tea for breakfast, rice and stew for lunch, rice again for supper. She eats no fruit.",
    [pm("What is missing most?", "Vegetables and fruit, and enough protein variety", ["Starch", "Salt", "Water only"], "Repetitive starch diet."),
     pm("Which change would help?", "Add beans or eggs and a fruit", ["Remove all food", "Add sugar", "Add more rice"], "Protein, vitamins."),
     po("Suggest an inexpensive protein food.", "Beans or groundnuts.", "1 mark.")]),
  [("Staple foods are mainly", "energy foods", ["protein foods", "vitamin foods", "water"], "Staples."),
   ("Pregnant women should", "get advice from a health worker", ["avoid all food", "eat only sugar", "ignore diet"], "Safe advice."),
   ("Variety in the diet helps", "supply all nutrients", ["increase waste", "waste money", "cause deficiencies"], "Variety."),
   ("Which is a protein food?", "Beans", ["Cassava", "Sugar", "Palm oil"], "Legume."),
   ("A menu high in sugar and starch and low in other foods is", "unbalanced", ["balanced", "ideal", "healthy"], "Unbalanced.")],
  notes=[HEALTH, "Percentages in the figure are illustrative; do not present them as recommendations."], minutes=25)

L4 = lesson(c1, "energy", "Energy values and energy needs",
  ["State the energy values per gram used in this course", "Calculate the energy in a meal", "Compare energy intake with energy needs", "Convert kilojoules and kilocalories (approximately)"],
  [("definition", "Units and values", "Energy is measured in **kilojoules (kJ)** (and often in **kilocalories (kcal)**; 1 kcal is about 4.2 kJ). In this course we use: **carbohydrate 17 kJ/g, protein 17 kJ/g, fat 37 kJ/g** (about 4, 4 and 9 kcal/g). These are standard rounded values used in school; tables may differ slightly."),
   ("methode", "Energy of a meal", "Energy (kJ) = grams of carbohydrate x 17 + grams of protein x 17 + grams of fat x 37. Example: 60 g carbohydrate, 20 g protein and 10 g fat give 60 x 17 + 20 x 17 + 10 x 37 = 1020 + 340 + 370 = 1730 kJ. **Percentage of energy from fat** = (fat energy / total energy) x 100."),
   ("retenir", "Energy needs", "Energy needs depend on **age, sex, body size, activity and climate**. The **basal metabolic rate (BMR)** is the energy needed at rest for breathing, heartbeat, and keeping warm. Active people and growing children need more energy for their size. If intake is greater than use over a long time, the extra is stored as fat; if less, the body loses weight."),
   ("pieges", "Be careful", "- Fat has more than twice the energy per gram of carbohydrate or protein.\n- Water, vitamins, minerals and fibre have no useful energy value.\n- Do not use these calculations to diagnose or give personal advice; a dietitian must do that. " + HEALTH)],
  ("Energy bars", bars([("Carbohydrate", 17, "orange"), ("Protein", 17, "blue"), ("Fat", 37, "red")], unit="kJ per gram", w=400, h=240),
   "A bar chart: carbohydrate 17 kJ per gram, protein 17 and fat 37.", "Bar chart of energy values per gram: carbohydrate 17, protein 17 and fat 37 kilojoules."),
  [("Example 1 - Energy of a meal", "A meal of rice and stew contains 80 g carbohydrate, 15 g protein and 12 g fat (illustrative values). Find the energy.", ["Carbohydrate: 80 x 17 = 1360 kJ. Protein: 15 x 17 = 255 kJ. Fat: 12 x 37 = 444 kJ.", "Total = 1360 + 255 + 444 = 2059 kJ."], "2059 kJ"),
   ("Example 2 - Percentage from fat", "In the meal of 60 g carbohydrate, 20 g protein and 10 g fat (1730 kJ), what percentage of the energy comes from fat?", ["Fat energy = 10 x 37 = 370 kJ.", "(370 / 1730) x 100 = 21.4 %."], "About 21 %")],
  [N("Energy from 50 g of carbohydrate (17 kJ/g) in kJ", 850, "50 x 17 = 850."),
   N("Energy from 10 g of fat (37 kJ/g) in kJ", 370, "10 x 37 = 370."),
   M("Which nutrient gives the most energy per gram?", "Fat", ["Carbohydrate", "Protein", "Water"], "37 kJ/g.")],
  [N("A snack has 30 g carbohydrate, 5 g protein and 20 g fat. Energy in kJ", 1335, "30x17=510; 5x17=85; 20x37=740; total 1335."),
   O("Explain why a farmer needs more energy than an office worker of the same size.", "The farmer does heavy physical work, so more energy is used by the muscles; energy intake must match to avoid loss of weight and tiredness.", "1 mark each point (2) plus 1 for BMR/activity link.")],
  P("A lunch contains 70 g carbohydrate, 25 g protein and 15 g fat (illustrative).",
    [pn("Energy from carbohydrate (kJ)", 1190, "70 x 17 = 1190."),
     pn("Total energy (kJ)", 2170, "1190 + 25x17 (425) + 15x37 (555) = 2170."),
     pn("Fat's percentage of total energy (to the nearest whole number)", 26, "555 / 2170 = 25.6 per cent, about 26.", tol=1)]),
  [("The energy value of protein used here is", "17 kJ per gram", ["37 kJ per gram", "0 kJ per gram", "100 kJ per gram"], "Protein."),
   ("BMR is the energy needed", "at rest", ["during sport only", "only during sleep", "only in hot weather"], "Basal."),
   ("1 kcal is about", "4.2 kJ", ["42 kJ", "0.42 kJ", "420 kJ"], "Conversion."),
   ("If energy intake is much greater than energy use over a long time", "weight tends to increase", ["weight drops", "nothing happens", "bones grow"], "Stored fat."),
   ("Nutrients with no useful energy value include", "water and fibre", ["fat", "protein", "starch"], "No energy.")],
  notes=[HEALTH, "Energy values per gram (17, 17, 37 kJ/g) are rounded textbook values; the syllabus may use 16/16/37 or kcal values. Meal compositions in examples are illustrative, not real analyses."], minutes=30)
assert 80 * 17 + 15 * 17 + 12 * 37 == 2059 and 30 * 17 + 5 * 17 + 20 * 37 == 1335 and 70 * 17 + 25 * 17 + 15 * 37 == 2170 and round(555 / 2170 * 100) == 26

L5 = lesson(c1, "digestion", "Digestion and absorption",
  ["Describe the parts of the digestive system and their functions", "Describe the digestion of starch, protein and fat in outline", "Explain absorption", "Describe the role of enzymes"],
  [("definition", "Digestion", "**Digestion** breaks large food molecules into small soluble ones that can be absorbed into the blood. **Mechanical** digestion (chewing, churning) breaks food into pieces; **chemical** digestion uses **enzymes**. The path: mouth, oesophagus, stomach, small intestine, large intestine, rectum, anus. The liver, gall bladder and pancreas help."),
   ("retenir", "Where and how", "**Mouth**: chewing; amylase in saliva starts digesting starch. **Stomach**: churning, acid, protease (pepsin) starts protein digestion. **Small intestine**: bile (from liver) helps fat digestion; enzymes from the pancreas and the gut finish digestion of starch (to glucose), protein (to amino acids) and fat (to fatty acids and glycerol); **absorption** into the blood through villi. **Large intestine**: absorbs water."),
   ("methode", "Enzymes", "**Enzymes** are biological catalysts made of protein. Each works on a specific food: **amylase** on starch, **protease** on protein, **lipase** on fats. They work best at about body temperature and the right pH; they are destroyed by high temperatures."),
   ("pieges", "Be careful", "- Absorption mainly takes place in the **small** intestine, not the stomach.\n- Bile does not contain enzymes; it breaks fat into droplets (emulsifies).\n- Fibre is not digested but is needed. " + HEALTH)],
  ("Digestive path", flow("Path of food", ["Mouth: chewing, amylase", "Stomach: acid, protease", "Small intestine: digestion + absorption", "Large intestine: water absorbed"], colors=["lightyellow", "lightorange", "lightgreen", "lightblue"]),
   "Four boxes showing the path of food from mouth to large intestine and what happens in each.", "Flow of digestion: mouth, stomach, small intestine, large intestine."),
  [("Example 1 - End products", "What are the end products of digestion of starch, protein and fat?", ["Starch is digested to glucose; protein to amino acids.", "Fat to fatty acids and glycerol."], "Glucose; amino acids; fatty acids and glycerol"),
   ("Example 2 - Why chew?", "Why is chewing food well helpful?", ["Chewing breaks food into small pieces: a larger surface area for enzymes.", "Saliva (with amylase) mixes with the food."], "Larger surface area; saliva begins starch digestion")],
  [M("Starch digestion begins in the", "mouth", ["stomach", "large intestine", "liver"], "Saliva amylase."),
   M("Most absorption of food takes place in the", "small intestine", ["stomach", "mouth", "anus"], "Villi."),
   TF("Bile contains digestive enzymes.", False, "Bile emulsifies fat but has no enzymes.")],
  [MT("Match the enzyme to the food it digests.", [("Amylase", "Starch"), ("Protease", "Protein"), ("Lipase", "Fat"), ("None (not digested)", "Fibre")], "Enzymes are specific."),
   O("Describe how the small intestine is adapted for absorption.", "It is long, with a lining folded into many villi that give a large surface area; the villi have thin walls and a rich blood supply so digested food passes quickly into the blood.", "1 mark each of: long/large surface area, villi, thin wall, blood supply (3 marks).")],
  P("A student chews a piece of cooked cassava for several minutes and notices a slightly sweet taste.",
    [pm("Which enzyme is responsible?", "Amylase", ["Protease", "Lipase", "None"], "Saliva amylase starts breaking starch to sugar."),
     pm("The sweet taste is from", "sugar produced from starch", ["fat", "protein", "water"], "Maltose/sugar."),
     po("Why does the enzyme not work well if the food is very hot when swallowed?", "High temperature can destroy the enzyme (denature it) so it no longer works.", "1 mark.")]),
  [("Digestion makes food molecules", "small enough to be absorbed", ["bigger", "hotter", "colder"], "Absorption."),
   ("The stomach contains", "acid and protease", ["only water", "only bile", "only amylase"], "Stomach."),
   ("Villi are found in the", "small intestine", ["mouth", "stomach", "liver"], "Surface area."),
   ("The large intestine mainly absorbs", "water", ["fat", "protein", "vitamins A only"], "Water."),
   ("Enzymes are", "biological catalysts", ["vitamins", "minerals", "fibres"], "Catalysts.")],
  notes=[HEALTH, "Anatomical detail kept at O Level; check the diagram expectations for the paper."], minutes=25)

c2 = p.chapter("preparation", "Food preparation, safety and preservation", REF)
L6 = lesson(c2, "cooking-methods", "Cooking and food preparation",
  ["Explain why food is cooked", "Compare cooking methods and their effect on nutrients", "Describe changes to starch, protein and fat on heating", "Choose a suitable method"],
  [("definition", "Why we cook", "Cooking makes food **safe** (kills many germs), **palatable** (flavour, texture, appearance) and **easier to digest**. Methods using **water**: boiling, simmering, steaming, stewing. Methods using **fat**: frying (shallow and deep). Methods using **dry heat**: roasting, grilling, baking."),
   ("retenir", "Changes on heating", "**Starch** grains absorb water and burst (**gelatinisation**), thickening a sauce. **Proteins** **coagulate** (set) as an egg white turns solid; over-cooking makes them tough. **Fats** melt; very high heat makes oil smoke and break down. **Vitamin C** and some B vitamins are lost in cooking, mostly into the water."),
   ("methode", "Keeping nutrients", "Wash before cutting; do not soak; cook in a small amount of water for a short time; use the cooking water; do not add bicarbonate of soda (it destroys some vitamins); serve soon after cooking; fry in moderate amounts of fresh oil; avoid burning."),
   ("pieges", "Be careful", "- Deep-frying adds a lot of energy from fat.\n- Never leave hot oil unattended: fat fires need a lid, not water.\n- Cassava products must be prepared properly (peeling, soaking, fermenting, drying and cooking as traditionally done) to be safe. " + HEALTH)],
  ("Methods", cols("Methods of cooking", ["Medium", "Methods"], [["Water", "Boil, steam, stew"], ["Fat", "Fry"], ["Dry heat", "Roast, grill, bake"]]),
   "A table grouping cooking methods by water, fat and dry heat.", "Table of cooking methods by medium: water, fat and dry heat."),
  [("Example 1", "Why does a sauce thicken when flour or cornflour is heated in it?", ["Starch grains absorb water and swell.", "They burst and the starch forms a thick gel (gelatinisation)."], "Gelatinisation of starch"),
   ("Example 2", "Choose a method for each aim: (a) low fat, (b) crisp texture, (c) soft tender meat cooked slowly.", ["(a) Steaming or grilling adds little fat. (b) Frying or roasting gives crispness.", "(c) Stewing in liquid softens meat."], "(a) steaming/grilling, (b) frying/roasting, (c) stewing")],
  [M("Heating starch with water makes it", "swell and thicken", ["disappear", "become fat", "turn to protein"], "Gelatinisation."),
   M("Which method adds fat?", "Frying", ["Steaming", "Boiling", "Stewing without oil"], "Frying."),
   TF("Egg white coagulates when heated.", True, "Protein sets.")],
  [M("Which advice helps keep vitamin C in vegetables?", "Cook briefly in a small amount of water", ["Boil for a long time in a lot of water", "Add bicarbonate of soda", "Soak overnight before cooking"], "Reduce losses."),
   O("Explain what happens to protein when an egg is boiled.", "Heat denatures and coagulates the protein so the liquid white and yolk set into a solid.", "1 mark each of denature/coagulate and solid result (2) plus 1 for example.")],
  P("Mama Judith cooks eru with water leaf, fish and a little palm oil on a low fire for 20 minutes.",
    [pm("This method is called", "stewing", ["roasting", "deep-frying", "baking"], "Slow cooking in liquid."),
     pm("Which vitamins may be reduced?", "Heat-sensitive and water-soluble ones such as vitamin C", ["Calcium", "Fibre", "Iron only"], "General."),
     po("Suggest how to reduce vitamin loss.", "Cook for a shorter time, avoid too much water, serve soon.", "1 mark each.")]),
  [("Coagulation refers to", "protein setting on heating", ["starch dissolving", "water boiling", "fibre digesting"], "Protein."),
   ("Grilling uses", "dry heat", ["only water", "only steam", "cold"], "Grilling."),
   ("Cooking water from vegetables can be", "used in the sauce", ["always thrown away", "poured on the stove", "ignored"], "Vitamins."),
   ("Fat fires should be put out by", "covering with a lid or damp cloth, not with water", ["pouring water", "fanning", "adding oil"], "Safety."),
   ("Simmering is", "cooking just below boiling", ["frying", "baking", "grilling"], "Simmer.")],
  notes=[HEALTH, "Fire-safety advice must be confirmed by a trained instructor."], minutes=25)

L7 = lesson(c2, "hygiene-safety", "Food hygiene and kitchen safety",
  ["Explain how food becomes contaminated", "Describe personal, kitchen and food hygiene", "Describe safe storage temperatures in general terms", "Describe common kitchen accidents and prevention"],
  [("definition", "Contamination and food poisoning", "Food can be contaminated by **bacteria**, **viruses**, **moulds**, chemicals or physical objects. Sources: hands, raw meat and fish, flies and pests, dirty water, unwashed utensils, soil. **Food poisoning** may cause vomiting, diarrhoea and fever. Young children, the elderly and sick people are at greater risk."),
   ("retenir", "Bacteria and temperature", "Bacteria multiply fastest in warm, moist, protein-rich foods, roughly between 5 °C and 60 °C (the 'danger zone', flagged for review). They may double in number about every 20 minutes in good conditions (illustration only). Keep cold food cold (fridge below about 5 °C), hot food hot, and cook food until very hot all the way through (about 70 °C or more in the centre)."),
   ("methode", "Hygiene rules", "**Personal**: wash hands with soap, clean clothes or apron, tie hair back, cover cuts, do not cough over food. **Food**: buy fresh food, wash fruit and vegetables, separate raw and cooked, cover food, cool and store leftovers promptly. **Kitchen**: clean surfaces, wash cloths, dispose of waste, control flies and rats, safe water."),
   ("methode", "Kitchen safety", "Prevent burns (handles in, careful with hot oil), cuts (sharp knives used properly), electric shocks (dry hands, no damaged wires), slips (wipe spills), gas hazards (check cylinders and connections). Keep a first-aid kit and know basic first aid; learn from a trained person."),
   ("pieges", "Be careful", "- Food may look and smell normal and still be unsafe.\n- Leftovers should not be reheated many times.\n- Temperature values here are general; local food safety authorities give exact limits. " + HEALTH)],
  ("Bacteria growth", bars([("0 min", 1, "green"), ("20 min", 2, "green"), ("40 min", 4, "orange"), ("60 min", 8, "orange"), ("80 min", 16, "red")], unit="number of bacteria (illustration)", w=420, h=250),
   "A bar chart showing bacteria doubling every 20 minutes from 1 to 16 in 80 minutes.", "Bar chart: 1, 2, 4, 8 and 16 bacteria at 0, 20, 40, 60 and 80 minutes, an illustration of doubling."),
  [("Example 1 - Growth", "One bacterium doubles every 20 minutes in warm food (illustration). How many are there after 2 hours?", ["120 minutes / 20 = 6 doublings.", "2^6 = 64 bacteria."], "64"),
   ("Example 2 - Spot the faults", "A cook handles raw fish, wipes hands on her apron and chops salad on the same board. List the faults.", ["She did not wash her hands with soap after raw fish.", "Cross-contamination: raw fish board used for salad, and a dirty apron."], "No hand-wash; same board; dirty apron")],
  [N("Bacteria doubling every 20 minutes: how many after 1 hour from 1 bacterium?", 8, "2^3 = 8."),
   M("Food poisoning bacteria grow best in", "warm, moist, protein-rich food", ["dry flour", "dry rice stored in a sealed jar", "boiling water"], "Conditions."),
   TF("Raw and cooked foods should be stored together.", False, "Keep separate.")],
  [N("Starting with 5 bacteria that double every 20 minutes, how many after 80 minutes?", 80, "80 min = 4 doublings, 5 x 16 = 80."),
   O("Give four rules of kitchen hygiene.", "Clean surfaces; wash cloths; cover food; dispose of waste; control pests; use clean water.", "1 mark each, 4.")],
  P("A cook in Bafoussam prepared stew at 7 a.m. and left it covered on the table in the warm kitchen until 5 p.m., then served it.",
    [pm("What is the main risk?", "Bacteria multiplying while the food was warm", ["The stew became cold", "The vitamins increased", "The salt disappeared"], "Warm storage."),
     pn("From 1 bacterium doubling every 20 minutes, how many doublings happen in 2 hours?", 6, "120/20."),
     po("Suggest two ways to make the food safer.", "Cool and store it in a fridge or keep it very hot; reheat thoroughly; or cook only what is needed.", "1 mark each.")]),
  [("The 'danger zone' for bacterial growth is roughly", "5 to 60 degrees Celsius", ["-20 to 0", "100 to 200", "0 to 4"], "General value."),
   ("Cross-contamination is", "spread of germs from raw to cooked food", ["mixing two spices", "freezing", "adding salt"], "Spread."),
   ("To prevent burns, pan handles should be", "turned inwards", ["turned outwards", "removed", "heated"], "Safety."),
   ("Wiping spills prevents", "slips", ["hunger", "thirst", "weight gain"], "Safety."),
   ("A group at greater risk from food poisoning is", "young children", ["no one", "only athletes", "only cooks"], "Vulnerable.")],
  notes=[HEALTH, "Temperatures (5-60 degrees danger zone, about 70 degrees core temperature) are widely used guidance values; check national guidance. Doubling time 20 min is illustrative."], minutes=25)
assert 5 * 2 ** 4 == 80

L8 = lesson(c2, "spoilage-preservation", "Food spoilage and preservation",
  ["Explain causes of spoilage: microorganisms and enzymes", "Describe conditions for microbial growth", "Describe drying, smoking, salting, sugar, refrigeration, freezing and canning", "Give advantages and limitations"],
  [("definition", "Spoilage", "**Spoilage** is the process that makes food unfit to eat. Causes: **microorganisms** (bacteria, yeasts and moulds) and **enzymes** in the food itself (for example ripening and browning). Signs: bad smell, slime, mould, change of colour and taste, swelling of cans."),
   ("retenir", "Conditions for growth", "Microorganisms need **food**, **moisture**, **warmth**, **suitable pH** and (for many) **oxygen**, and time. Preservation works by removing, reducing or blocking one or more of these, or by killing the microorganisms."),
   ("retenir", "Methods", "**Drying/smoking** (dried fish, crayfish, smoked meat): removes water. **Salting and sugar**: draw out water. **Refrigeration** (about 0-5 °C) slows growth; **freezing** (about -18 °C) stops growth, but does not kill all germs. **Canning**: heat in sealed cans. **Pickling**: acid (vinegar). **Fermentation**: useful microorganisms make acid (e.g. yoghurt, fermented cassava products)."),
   ("pieges", "Be careful", "- Freezing does not kill all bacteria; they can grow again after thawing.\n- Do not refreeze thawed food.\n- Moulds on groundnuts and maize can produce toxins (aflatoxins); dry well and store properly; discard mouldy or shrivelled nuts.\n- " + HEALTH)],
  ("Methods table", cols("Preservation", ["Method", "Principle"], [["Drying", "Removes water"], ["Refrigeration", "Cold slows growth"], ["Canning", "Heat + seal"], ["Salting", "Draws out water"]]),
   "A table of four preservation methods with the principle behind each.", "Table: drying removes water, refrigeration uses cold, canning uses heat and sealing, salting draws out water."),
  [("Example 1 - Principle", "Explain why smoked and dried fish keeps for longer than fresh fish.", ["Microorganisms need moisture to grow.", "Drying and smoking remove most of the water, so growth is stopped."], "Little water: no microbial growth"),
   ("Example 2 - Choose", "A farmer in Bamenda has a large harvest of groundnuts. How can he store them safely?", ["Dry them well in the sun on a clean surface.", "Store in clean, dry, ventilated containers off the ground; check for mould and discard bad nuts."], "Dry well; store dry; sort")],
  [M("Spoilage is caused by", "microorganisms and enzymes", ["only vitamins", "only salt", "only water"], "Two main causes."),
   M("Freezing", "stops growth but does not kill all bacteria", ["kills all germs", "makes food sterile", "adds water"], "Freezing."),
   TF("Microorganisms need moisture to grow.", True, "Yes.")],
  [M("Canning preserves food by", "killing microorganisms with heat and sealing out air", ["adding water", "adding bacteria", "drying only"], "Canning."),
   O("Explain why salt can preserve fish.", "Salt draws water out of the fish and of microorganisms by osmosis, so they cannot grow.", "1 mark each of water removed, microbes cannot grow, link to salt.")],
  P("A grocer in Limbe sells fresh fish, smoked fish and canned sardines.",
    [pm("Which has had most water removed?", "Smoked fish", ["Fresh fish", "Canned sardines in oil", "None"], "Drying/smoking."),
     pm("Which relies on heating and sealing?", "Canned sardines", ["Smoked fish", "Fresh fish", "Dried pepper"], "Canning."),
     po("State one sign that a can should not be used.", "A swollen, leaking or badly dented can.", "1 mark.")]),
  [("Mould is a kind of", "microorganism", ["vitamin", "mineral", "fibre"], "Fungus."),
   ("Pickling uses", "acid", ["sugar only", "oil only", "light"], "Vinegar."),
   ("A refrigerator", "slows microbial growth", ["stops all", "kills all", "adds salt"], "Cold."),
   ("Thawed food should", "not be refrozen", ["be refrozen at once", "be left for days", "be dried"], "Safety."),
   ("Moulds on groundnuts can produce", "harmful toxins", ["vitamins", "extra protein", "nothing"], "Aflatoxins.")],
  notes=[HEALTH, "Temperatures (0-5 degrees, -18 degrees) are standard guidance values. Aflatoxin comment is a general food-safety statement."], minutes=25)

c3 = p.chapter("health", "Diet, health and the consumer", REF)
L9 = lesson(c3, "malnutrition-deficiency", "Malnutrition and deficiency diseases",
  ["Define malnutrition (undernutrition and overnutrition)", "Describe protein-energy malnutrition in outline", "Name common deficiency diseases, causes and prevention", "Describe obesity and diet-related risks in outline"],
  [("definition", "Malnutrition", "**Malnutrition** means a poor state of nutrition: **undernutrition** (too little food or too few nutrients) or **overnutrition** (too much food, leading to overweight). Causes include poverty, poor food choices, infections, lack of knowledge, famine and some illnesses. Children, pregnant women and the elderly are especially vulnerable."),
   ("definition", "Protein-energy malnutrition", "In children, a lack of protein and energy can cause **marasmus** (severe wasting, very thin) or **kwashiorkor** (swollen feet and belly, changes in hair and skin). These need **medical treatment**. Prevention: enough varied food, breastfeeding for infants, good weaning foods and prevention and treatment of infections."),
   ("retenir", "Deficiency diseases", "**Vitamin A**: poor sight in dim light, infections. **Vitamin C**: scurvy (bleeding gums, slow healing). **Vitamin D** (and calcium): rickets (soft bones) in children. **Iron**: anaemia (tiredness, pale). **Iodine**: goitre (swollen neck). **Vitamin B1 (thiamine)**: beriberi. **Niacin**: pellagra. Prevention: a varied diet, fortified foods and supplements where recommended by health services."),
   ("retenir", "Overnutrition", "Eating more energy than the body uses, with little exercise, can lead to **obesity**, which increases the risk of conditions such as high blood pressure and diabetes. Healthy habits: balanced diet, less sugar, fat and salt, more fruit and vegetables, regular physical activity."),
   ("pieges", "Be careful", "- Diagnosis and treatment belong to health workers, not to a textbook.\n- Not every swollen belly is kwashiorkor.\n- Supplements are not a substitute for food.\n- " + HEALTH)],
  ("Table", cols("Deficiency and disease", ["Lacking", "Disease"], [["Vitamin C", "Scurvy"], ["Vitamin D", "Rickets"], ["Iron", "Anaemia"], ["Iodine", "Goitre"]]),
   "A table pairing four nutrient deficiencies with their diseases.", "Table: vitamin C scurvy, vitamin D rickets, iron anaemia, iodine goitre."),
  [("Example 1", "Which nutrient shortage is linked to goitre, and what is a simple prevention?", ["Goitre is linked to a shortage of iodine.", "Use iodised salt and eat fish; follow health-service advice."], "Iodine; iodised salt"),
   ("Example 2", "A health worker sees a very thin child with little muscle. Which condition could this be, and who should treat it?", ["Severe wasting from lack of food energy and protein suggests marasmus.", "It must be treated by trained health workers."], "Marasmus; medical treatment")],
  [M("Scurvy is caused by lack of", "vitamin C", ["iron", "vitamin D", "iodine"], "Scurvy."),
   M("Rickets in children is linked to lack of", "vitamin D and calcium", ["vitamin C", "protein only", "fibre"], "Soft bones."),
   TF("Kwashiorkor needs medical treatment.", True, "Yes.")],
  [MT("Match the condition with its main nutrient cause.", [("Anaemia", "Iron"), ("Goitre", "Iodine"), ("Scurvy", "Vitamin C"), ("Night blindness", "Vitamin A")], "General links."),
   O("Explain how the diet of a child can be improved to prevent protein-energy malnutrition.", "Give enough energy foods (staples), protein foods (beans, groundnuts, fish, eggs, milk), add oil for energy, continue breastfeeding for infants, give regular meals and seek health care for illness.", "1 mark each of: energy, protein, breastfeeding/weaning, health care (up to 3).")],
  P("A health talk in a village explains: obesity, anaemia, goitre and scurvy.",
    [pm("Which is a form of overnutrition?", "Obesity", ["Anaemia", "Goitre", "Scurvy"], "Excess energy."),
     pm("Which is linked to iron?", "Anaemia", ["Goitre", "Scurvy", "Rickets"], "Iron."),
     po("Suggest two healthy habits to prevent obesity.", "Eat less sugar and fat, eat more fruit and vegetables, be physically active.", "1 mark each.")]),
  [("Undernutrition means", "too little food or nutrients", ["too much food", "no water", "high fibre only"], "Definition."),
   ("Goitre is a swelling in the", "neck", ["leg", "foot", "hand"], "Thyroid."),
   ("Anaemia is linked to", "iron lack", ["vitamin C only", "sugar", "fat"], "Iron."),
   ("A child with possible severe malnutrition should see", "a health worker", ["nobody", "a friend only", "a hairdresser"], "Medical help."),
   ("Obesity increases the risk of", "high blood pressure", ["strong bones only", "better sight", "no risk"], "General statement.")],
  notes=[HEALTH, "Disease descriptions are deliberately brief and non-diagnostic; a dietitian or doctor should review wording, especially for kwashiorkor/marasmus."], minutes=25)

L10 = lesson(c3, "additives-consumer", "Food additives, labels and consumer education",
  ["Name types of food additive and their purposes", "Read a food label", "Compare value for money using unit prices", "State consumer rights and good buying habits"],
  [("definition", "Additives", "**Food additives** are substances added to food for a purpose: **preservatives** (keep food longer), **antioxidants** (stop fats going rancid), **colourings**, **flavourings** and **flavour enhancers**, **sweeteners**, **emulsifiers and stabilisers** (keep oil and water mixed or the texture steady) and **thickeners**. Approved additives are controlled by law; some people are sensitive to certain additives."),
   ("retenir", "Labels", "A food label usually shows the **name** of the food, the **ingredients** (listed from the largest amount to the smallest), the **net weight**, **nutrition information** (if provided), the **date mark** (best before / use by or expiry), the **producer or importer**, and storage instructions. 'Best before' is about quality; 'use by' / 'expiry' is about safety."),
   ("methode", "Unit price", "To compare prices, find the price per unit of weight: price / quantity. Example: 5 kg of rice for 3500 FCFA costs 700 FCFA per kg; 1 kg for 800 FCFA costs 800 FCFA per kg, so the large pack is cheaper per kg (if the family can use it before it spoils)."),
   ("retenir", "Consumer", "A good consumer reads labels, checks dates and packaging, compares prices, buys from clean sellers and keeps receipts. Consumers have rights to safe products, true information and fair treatment, and may complain to the seller or the competent consumer-protection authority."),
   ("pieges", "Be careful", "- Never buy cans that are swollen, leaking or badly dented.\n- A cheaper price per kg is not a saving if food is wasted.\n- Colours and flavours do not show nutritional value.\n- " + HEALTH)],
  ("Label", shapes([T(210, 20, "A food label (example)", 15, bold=True), RECT(80, 36, 260, 140, fill="white", stroke="ink", width=2),
     T(210, 58, "Groundnut paste", 14, bold=True), T(210, 80, "Ingredients: groundnuts, salt", 12), T(210, 100, "Net weight: 500 g", 12), T(210, 120, "Best before: see lid", 12), T(210, 142, "Store in a cool, dry place", 12), T(210, 164, "Packed in Cameroon", 12)], 420, 190),
   "An example food label with name, ingredients, net weight, date mark, storage and place of packing.", "Example label of groundnut paste showing the name, ingredients, weight, date mark, storage advice and origin."),
  [("Example 1 - Unit price", "Cooking oil: 1 litre costs 1500 FCFA; 5 litres cost 6500 FCFA. Which is cheaper per litre?", ["5 litres: 6500 / 5 = 1300 FCFA per litre.", "1 litre: 1500 FCFA per litre, so the 5-litre can is cheaper per litre."], "The 5-litre can (1300 FCFA per litre)"),
   ("Example 2 - Label", "A label lists: sugar, water, flavouring, colour. Which ingredient is present in the largest amount?", ["Ingredients are listed in order from largest to smallest amount.", "The first one listed, sugar."], "Sugar")],
  [M("Antioxidants in food are added to", "stop fats going rancid", ["add colour", "add protein", "make food hot"], "Purpose."),
   N("Unit price: 4 kg of rice costs 3200 FCFA. Price per kg", 800, "3200 / 4 = 800."),
   TF("Ingredients are listed from the smallest to the largest amount.", False, "From the largest to the smallest.")],
  [M("Which date mark is mainly about safety?", "Use by / expiry date", ["Best before", "Packed on a Monday", "Weight"], "Safety."),
   O("Give four pieces of information normally found on a food label.", "Name of food; ingredients; net weight; date mark; producer; storage instructions; nutrition information.", "1 mark each, 4.")],
  P("A shopper compares two packs of sugar: 1 kg for 700 FCFA and 3 kg for 1950 FCFA.",
    [pn("Price per kg of the 3 kg pack", 650, "1950 / 3 = 650."),
     pn("Saving per kg compared with the 1 kg pack", 50, "700 - 650 = 50."),
     po("State one reason why the larger pack might not be the best choice for every family.", "The family may not use it before it spoils or may not afford the larger payment at one time.", "1 mark.")]),
  [("Emulsifiers help", "oil and water stay mixed", ["colour food", "kill germs", "add vitamins"], "Emulsifier."),
   ("A net weight shows", "the weight of the food without packaging", ["the cost", "the producer", "the date"], "Net."),
   ("A swollen can should", "not be bought or used", ["be heated and eaten", "be given to children", "be stored"], "Safety."),
   ("Unit price helps to", "compare value for money", ["increase the weight", "colour food", "preserve food"], "Unit price."),
   ("A consumer has the right to", "safe products and true information", ["free food always", "nothing", "only advertising"], "Rights.")],
  notes=[HEALTH, "Consumer-protection institutions and legal references for Cameroon are not cited; add names after review."], minutes=25)
assert 6500 / 5 == 1300 and 1950 / 3 == 650 and 3200 / 4 == 800 and 3500 / 5 == 700

L11 = lesson(c3, "budgeting-meal-costs", "Budgeting and meal costing",
  ["Plan a food budget", "Calculate the cost of meals and of a week's food", "Suggest ways to save money without lowering nutrition", "Explain the effect of seasonal buying"],
  [("definition", "Food budget", "A **budget** is a plan for spending a limited income. Food is often the largest part of a household budget. Steps: list the family's income, decide how much goes to food, plan meals, make a shopping list, buy, and record spending."),
   ("methode", "Costing a meal", "Add the cost of each ingredient used (cost of the part used, not the whole pack). Cost per person = total cost / number of people. Example: for 5 people the ingredients cost 2250 FCFA, so each portion costs 2250 / 5 = 450 FCFA."),
   ("retenir", "Saving money", "Buy staples and vegetables **in season** and from local markets; compare prices; buy beans, groundnuts and eggs as cheaper proteins; avoid waste (cook the right amount, use leftovers safely); grow vegetables if possible; avoid expensive packaged snacks and soft drinks; plan before shopping."),
   ("pieges", "Be careful", "- The cheapest food is not always the best value; nutrition matters.\n- Buying much more than you can store leads to waste and spoilage.\n- Prices in examples are illustrative, not current market prices.")],
  ("Budget bars", bars([("Staples", 1200, "orange"), ("Protein", 900, "red"), ("Vegetables", 500, "green"), ("Oil, spice", 300, "blue")], unit="FCFA", w=420, h=250),
   "A bar chart of an illustrative meal cost: staples 1200 FCFA, protein 900, vegetables 500, oil and spices 300.", "Bar chart of illustrative meal costs in FCFA: staples 1200, protein 900, vegetables 500, oil and spices 300."),
  [("Example 1 - Cost per person", "Ingredients for a meal for 5 people (illustrative): staples 1200, protein 900, vegetables 500, oil and spices 300 FCFA. Find the total and the cost per person.", ["Total = 1200 + 900 + 500 + 300 = 2900 FCFA.", "Per person = 2900 / 5 = 580 FCFA."], "2900 FCFA; 580 FCFA each"),
   ("Example 2 - Weekly budget", "A family can spend 12 000 FCFA a week on food. They have spent 7 500 FCFA on staples and protein. How much is left for vegetables, fruit and oil? What fraction (as a percentage) is already spent?", ["Left = 12000 - 7500 = 4500 FCFA.", "Spent = 7500 / 12000 x 100 = 62.5 %."], "4500 FCFA left; 62.5 % spent")],
  [N("Cost of a meal: rice 800, fish 1200, vegetables 400 FCFA. Total", 2400, "800 + 1200 + 400 = 2400."),
   N("A meal costs 2400 FCFA for 6 people. Cost per person", 400, "2400 / 6 = 400."),
   TF("Buying foods in season is usually cheaper.", True, "Greater supply lowers prices.")],
  [N("A budget of 15 000 FCFA is used as: staples 6 000, protein 5 000, vegetables and fruit 2 500, other 1 500. What percentage is spent on protein?", 33.3, "5000/15000 x 100 = 33.3 %.", tol=0.1),
   O("Suggest four ways a family on a low income can eat well and save money.", "Buy seasonal foods; use beans, groundnuts and eggs for protein; plan meals and shop with a list; avoid waste; grow vegetables; avoid expensive snacks.", "1 mark each, 4.")],
  P("The Njoh family (6 people) has 18 000 FCFA a week for food. Plan: staples 7 200, protein 5 400, vegetables and fruit 3 600, oil and spices 1 800 FCFA (illustrative).",
    [pn("Total of the plan", 18000, "7200 + 5400 + 3600 + 1800 = 18000."),
     pn("Cost per person per week", 3000, "18000 / 6 = 3000."),
     pn("Percentage of the budget spent on vegetables and fruit", 20, "3600 / 18000 x 100 = 20 %.")]),
  [("A budget is", "a plan for spending income", ["a kind of food", "a recipe", "a tax"], "Budget."),
   ("Cost per person is", "total cost divided by number of people", ["total cost times people", "price of one item", "none"], "Division."),
   ("Cheaper protein foods include", "beans and groundnuts", ["only imported meat", "only sweets", "only drinks"], "Low-cost proteins."),
   ("Planning meals helps to", "avoid waste", ["increase waste", "buy more snacks", "skip nutrients"], "Planning."),
   ("Vegetables bought in season are", "usually cheaper", ["always more expensive", "never available", "not nutritious"], "Seasonality.")],
  notes=[HEALTH, "All prices are invented for practice; replace with current local prices after review."], minutes=25)
assert 1200 + 900 + 500 + 300 == 2900 and 2900 / 5 == 580 and 12000 - 7500 == 4500 and 7500 / 12000 * 100 == 62.5 and round(5000 / 15000 * 100, 1) == 33.3
assert 7200 + 5400 + 3600 + 1800 == 18000 and 3600 / 18000 * 100 == 20

mock(p, "1", "GCE O Level mock — Food Science and Nutrition", 90,
  "Answer all questions. The paper is marked out of 20. This is an original practice paper; its format is to be checked against the official texts of the Cameroon GCE Board. Energy values: carbohydrate 17 kJ/g, protein 17 kJ/g, fat 37 kJ/g.",
  [("Section A - Short questions (6 marks)", [
      (L1, M("Which nutrient is needed mainly for growth and repair?", "Protein", ["Carbohydrate", "Fibre", "Water"], "Protein.", points=1)),
      (L2, M("Lack of iodine is linked to", "goitre", ["scurvy", "rickets", "anaemia"], "Goitre.", points=1)),
      (L4, N("The energy in 20 g of fat (kJ)", 740, "20 x 37 = 740.", points=1)),
      (L5, M("Where does most absorption of digested food take place?", "Small intestine", ["Stomach", "Mouth", "Large intestine"], "Villi.", points=1)),
      (L7, TF("Raw meat and cooked food should be stored together.", False, "Keep them separate.", points=1)),
      (L8, M("Drying preserves food by", "removing water", ["adding water", "adding fat", "cooling it"], "Microbes need water.", points=1))]),
   ("Section B - Structured questions (10 marks)", [
      (L4, P("A meal contains 80 g carbohydrate, 20 g protein and 15 g fat (illustrative).",
         [pn("Energy from carbohydrate (kJ)", 1360, "80 x 17.", pts=1), pn("Total energy (kJ)", 2255, "1360 + 20 x 17 (340) + 15 x 37 (555) = 2255.", pts=2),
          pn("Percentage of energy from fat (nearest whole number)", 25, "555 / 2255 = 24.6, about 25 per cent.", tol=1, pts=2)])),
      (L10, P("Rice: 1 kg costs 800 FCFA, a 5 kg bag costs 3 500 FCFA.",
         [pn("Price per kg of the 5 kg bag", 700, "3500 / 5.", pts=2), pn("Saving per kg compared with buying 1 kg", 100, "800 - 700.", pts=1),
          po("Give one reason a family might still buy 1 kg.", "They may not afford the larger payment or may not be able to store rice safely.", "1 mark each of two reasons.", pts=2)]))]),
   ("Section C - Essay (4 marks)", [
      (L3, O("Plan a balanced day's menu for a Form 5 student using local foods and explain why it is balanced.", "Breakfast: pap with groundnuts and a fruit. Lunch: rice and beans with a vegetable sauce. Supper: boiled plantain with fish and green leaves. It supplies energy (staples), protein (beans, groundnuts, fish) and vitamins, minerals and fibre (vegetables, fruit).", "1 mark each for three suitable meals using food groups; 1 mark for explanation (4 marks).", points=4))])])
assert 80 * 17 + 20 * 17 + 15 * 37 == 2255 and round(555 / 2255 * 100) == 25 and 20 * 37 == 740
write(p)
