import sys
sys.path.insert(0, "/home/user/CastBridge/tools/learn-authoring/anglophone")
from _cs import *

REF = "Cameroon GCE Board — Ordinary Level Computer Science / ICT syllabus — to be checked against the official text"
p = Pack("gceol-computer", "Computer Studies / ICT — GCE O Level", level="Form 5", subject="sciences", cursus="secondary",
         exam="GCE-OL", wanted="computer-science", programRef=REF,
         description="Hardware and software, devices, number systems, data representation, operating systems, office applications, networks, security, algorithms, programming and ICT in Cameroon — with worked examples, exercises and a mock paper.")
SRC = "Original exercise written for CastBridge, in the style of GCE O Level Computer Studies"

# ------------------------------------------------------------------ computed values
def tobin(n, w=0): return bin(n)[2:].zfill(w)
assert tobin(77) == "1001101" and tobin(156) == "10011100" and int("11010110", 2) == 214 and hex(214) == "0xd6"
assert int("2F", 16) == 47 and oct(229) == "0o345" and int("1011", 2) + int("0110", 2) == 17 and tobin(17) == "10001"
assert 45 - 19 == 26 and tobin(45, 8) == "00101101" and tobin(19, 8) == "00010011"
twos19 = tobin((256 - 19), 8); assert twos19 == "11101101"
assert int(tobin(45, 8), 2) + int(twos19, 2) == 45 + 237 == 282 and 282 - 256 == 26 and tobin(26, 8) == "00011010"
img = 800 * 600 * 24 // 8; assert img == 1440000
snd = 44100 * 16 * 10 * 2 // 8; assert snd == 1764000
assert ord("A") == 65 and ord("a") == 97 and ord("0") == 48 and chr(ord("C") + 1) == "D" and tobin(65, 8) == "01000001"
assert 24 * 8 / 8 == 24

# ================================================================== CH1 hardware
c1 = p.chapter("hardware", "Computers: hardware, software and devices", REF)

L_hw = lesson(c1, "hardware-software", "Hardware, software and the computer system",
  ["Define a computer and name its four basic functions", "Distinguish hardware from software", "Classify software as system or application software", "Name the main parts inside the system unit"],
  [("definition", "What a computer is", "A **computer** is an electronic machine that accepts **input**, **processes** it following stored instructions, produces **output** and can **store** results. The cycle is often written *Input - Process - Output - Storage*."),
   ("retenir", "Hardware and software", "**Hardware** is every physical part you can touch: keyboard, monitor, CPU, memory chips, disks. **Software** is the set of programs (instructions) that tell the hardware what to do. A computer without software cannot do useful work; software without hardware cannot run."),
   ("methode", "Types of software", "- **System software** manages the computer: operating system, utility programs (antivirus, disk cleaner), device drivers.\n- **Application software** does tasks for the user: word processor, spreadsheet, browser, games.\n- **Programming software** (compilers, interpreters) is used to create other programs."),
   ("pieges", "Common mistakes", "- A file, a photo or a program is **not** hardware: it is data or software stored *on* hardware.\n- The **CPU** is not the whole computer; the *system unit* (case) holds the motherboard, CPU, RAM, storage and power supply.\n- Windows, Linux and Android are operating systems, **not** application programs.")],
  ("Input - Process - Output - Storage", hflow("The information processing cycle", ["Input|keyboard", "Processing|CPU", "Output|screen", "Storage|disk"]),
   "A computer takes input, processes it with the CPU, gives output and can store the result.", "Four boxes joined by arrows: input, processing, output and storage."),
  [("Example 1 - Classify", "A school bursar in Bamenda uses a spreadsheet to total fees, an antivirus to protect the PC and a laser printer. Classify each item.",
    ["Spreadsheet: it does a user task (totals) so it is application software.", "Antivirus: it protects and maintains the system so it is system (utility) software.", "Laser printer: a physical device so it is hardware (an output device)."],
    "Spreadsheet = application software; antivirus = system software; printer = hardware."),
   ("Example 2 - IPO", "Identify the input, process and output when a student types 12 and 8 and the computer displays 20.",
    ["Input: the numbers 12 and 8 typed on the keyboard.", "Process: the CPU adds them (12 + 8).", "Output: 20 displayed on the monitor; it may be saved to disk (storage)."],
    "Input 12 and 8; process addition; output 20.")],
  [M("Which of the following is **hardware**?", "A monitor", ["A word processor", "An operating system", "An antivirus program"], "A monitor is a physical device. The other three are software."),
   M("Microsoft Word, a browser or a game are examples of", "application software", ["system software", "hardware", "firmware chips only"], "They help the user do a task, so they are application software."),
   TF("A photograph stored on a flash drive is hardware.", False, "The flash drive is hardware; the photo is data stored on it.")],
  [M("Which pair is correctly matched?", "Device driver - system software", ["Spreadsheet - system software", "Keyboard - software", "Compiler - hardware"], "Drivers help the OS control devices, so they are system software. Keyboards are hardware; compilers are software."),
   O("Explain why a computer needs both hardware and software. Give one example of each.", "Hardware provides the physical parts that carry out operations (e.g. the CPU or the keyboard). Software gives the instructions that tell the hardware what to do (e.g. an operating system). Without software the hardware does nothing useful; without hardware the software has nothing to run on.", "1 mark each: role of hardware, role of software, one correct example of each (3 marks).")],
  P("A small business in Douala has a desktop PC, a printer, an operating system, a spreadsheet and a flash drive.",
    [pm("Which item is application software?", "The spreadsheet", ["The operating system", "The printer", "The flash drive"], "Spreadsheets perform a user task."),
     pm("Which item is system software?", "The operating system", ["The spreadsheet", "The printer", "The flash drive"], "The OS manages the computer."),
     po("Name two hardware items from the list and say whether each is input, output or storage.", "Printer - output device; flash drive - storage device.", "1 mark per correct item with its type.")]),
  [("Which of these is NOT a basic function of a computer?", "Cooking", ["Input", "Processing", "Output"], "Input, processing, output (and storage) are the basic functions."),
   ("The physical parts of a computer are called", "hardware", ["software", "firmware only", "data"], "Hardware means the physical parts."),
   ("An operating system is a kind of", "system software", ["application software", "output device", "storage medium"], "It manages the computer."),
   ("Which component carries out the instructions of a program?", "The CPU", ["The monitor", "The keyboard", "The speaker"], "The Central Processing Unit executes instructions."),
   ("An antivirus program is best described as", "a utility (system) program", ["an input device", "a spreadsheet", "a programming language"], "It maintains and protects the system.")],
  notes=["Classification of software (system / application / programming) follows the usual textbook split; check the exact wording used by the syllabus."])

L_dev = lesson(c1, "devices", "Input, output and storage devices",
  ["Give examples of input, output and storage devices", "Match devices to uses", "Compare RAM and ROM and primary and secondary storage", "Convert between storage units"],
  [("definition", "Three kinds of device", "- **Input devices** send data in: keyboard, mouse, scanner, microphone, digital camera, touch screen, barcode reader.\n- **Output devices** present results: monitor, printer, speakers, projector.\n- **Storage devices** keep data: hard disk, solid-state drive, flash drive, memory card, optical disc."),
   ("retenir", "Memory and storage", "**RAM** (random access memory) holds programs and data in use; it is fast and **volatile** (it loses its contents when power is off). **ROM** (read-only memory) holds start-up instructions and keeps them without power. **Secondary storage** (disks, flash drives) keeps files permanently but is slower than RAM."),
   ("methode", "Storage units", "A **bit** is 0 or 1. **8 bits = 1 byte**. In school computing we use 1 KB = 1024 bytes, 1 MB = 1024 KB, 1 GB = 1024 MB, 1 TB = 1024 GB. (Some makers use 1000; this lesson uses 1024.)"),
   ("pieges", "Common mistakes", "- A touch screen is **both** input and output.\n- RAM is not permanent storage: unsaved work is lost in a power cut (a real risk in many towns).\n- Do not confuse *memory* (RAM) with *storage* (disk), even though both are measured in bytes.")],
  ("Devices", cols("Examples of devices", ["Input", "Output", "Storage"], [["Keyboard", "Monitor", "Hard disk"], ["Mouse", "Printer", "Flash drive"], ["Scanner", "Speaker", "Memory card"]]),
   "A table with three columns listing example input, output and storage devices.", "Table: input devices keyboard, mouse, scanner; output devices monitor, printer, speaker; storage devices hard disk, flash drive, memory card."),
  [("Example 1 - Which device?", "A shop in Kumba wants to (a) read product codes at the till, (b) print receipts, (c) back up daily sales. Choose a device for each.",
    ["(a) Reading product codes is input: a barcode reader.", "(b) Printing receipts is output: a printer.", "(c) Backing up needs storage: an external disk or flash drive."],
    "Barcode reader, printer, external disk or flash drive."),
   ("Example 2 - Units", "How many bytes are in 3 KB, and how many MB are in 5 GB?",
    ["3 KB x 1024 = 3072 bytes.", "5 GB x 1024 = 5120 MB."], "3072 bytes; 5120 MB.")],
  [M("Which one is an **output** device?", "Speaker", ["Scanner", "Microphone", "Mouse"], "Speakers produce sound output."),
   N("How many bytes are in 2 KB? (use 1 KB = 1024 bytes)", 2048, "2 x 1024 = 2048."),
   TF("ROM loses its contents when the computer is switched off.", False, "ROM is non-volatile. RAM is the volatile memory.")],
  [N("A file is 4096 KB. How many MB is that? (1 MB = 1024 KB)", 4, "4096 / 1024 = 4 MB."),
   MT("Match each device to its type.", [("Barcode reader", "Input"), ("Projector", "Output"), ("Memory card", "Storage"), ("Touch screen", "Input and output")], "A touch screen takes touches (input) and shows pictures (output).")],
  P("A computer has 4 GB of RAM and a 500 GB hard disk. Use 1 GB = 1024 MB.",
    [pn("How many MB of RAM is 4 GB?", 4096, "4 x 1024 = 4096 MB."),
     pm("What happens to unsaved work in RAM during a power cut?", "It is lost", ["It is copied to ROM", "It is saved to the keyboard", "It is kept in the monitor"], "RAM is volatile."),
     po("Give two differences between RAM and a hard disk.", "RAM is fast, temporary and volatile; the hard disk is slower, permanent and usually much larger.", "1 mark per correct difference.")]),
  [("A device that converts printed pages into digital images is a", "scanner", ["printer", "plotter", "speaker"], "A scanner is an input device for images."),
   ("8 bits make", "1 byte", ["1 KB", "1 MB", "1 nibble only"], "8 bits = 1 byte."),
   ("Which memory is volatile?", "RAM", ["ROM", "A hard disk", "A flash drive"], "RAM loses its data without power."),
   ("A flash drive is mainly used for", "storing and carrying files", ["displaying output", "typing text", "cooling the CPU"], "It is a portable storage device."),
   ("Which is secondary storage?", "Solid-state drive", ["RAM", "CPU cache only", "Monitor"], "SSDs keep data permanently.")],
  notes=["1 KB = 1024 bytes convention is stated in the lesson; the exam may use 1000 - check the official guidance."])

# ================================================================== CH2 numbers
c2 = p.chapter("numbers", "Number systems and data representation", REF)

L_ns = lesson(c2, "number-systems", "Binary, octal and hexadecimal",
  ["Explain why computers use binary", "Convert between binary and denary", "Convert between binary and hexadecimal / octal", "Use place values correctly"],
  [("definition", "Number bases", "Computers use **binary** (base 2, digits 0 and 1) because electronic circuits have two states: off and on. **Denary** is base 10. **Octal** is base 8 (digits 0-7). **Hexadecimal** is base 16: digits 0-9 and A-F, where A=10, B=11, C=12, D=13, E=14, F=15."),
   ("methode", "Binary to denary", "Write the place values 128, 64, 32, 16, 8, 4, 2, 1 above the bits and add the values where the bit is 1. Example: 01001101 = 64 + 8 + 4 + 1 = 77."),
   ("methode", "Denary to binary and hex", "Denary to binary: repeatedly divide by 2 and read the remainders upwards, or subtract place values. Binary to hex: group bits in **fours** from the right; each group is one hex digit. Binary to octal: group in **threes**."),
   ("pieges", "Common mistakes", "- Read remainders from **bottom to top**.\n- Group bits from the **right**, padding the left with zeros.\n- Hex letters are digits: **D6** is 13x16 + 6 = 214, not 'D times 6'.")],
  ("Place values for 01001101", boxrow("Place values: 01001101 = 77", ["128", "64", "32", "16", "8", "4", "2", "1"], sub=["0", "1", "0", "0", "1", "1", "0", "1"], colors=["lightgrey", "lightgreen", "lightgrey", "lightgrey", "lightgreen", "lightgreen", "lightgrey", "lightgreen"]),
   "Eight binary place values with the bits of 77 under them; the 1 bits are green.", "Row of boxes 128, 64, 32, 16, 8, 4, 2, 1 with bits 0,1,0,0,1,1,0,1 beneath."),
  [("Example 1 - Denary to binary", "Convert 156 to binary (8 bits).",
    ["156 = 128 + 16 + 8 + 4 (128+16=144, +8=152, +4=156).", "Place a 1 at 128, 16, 8 and 4, and 0 elsewhere: 1 0 0 1 1 1 0 0."], tobin(156)),
   ("Example 2 - Binary to hex", "Convert 11010110 to hexadecimal and to denary.",
    ["Split in fours: 1101 | 0110. 1101 = 13 = D; 0110 = 6.", "So the hex number is D6. Denary: 13 x 16 + 6 = 208 + 6 = 214."], "D6 hex = 214")],
  [N("Convert the binary number 1011 to denary.", 11, "8 + 2 + 1 = 11."),
   M("The hexadecimal digit F represents", "15", ["16", "10", "14"], "A=10 ... F=15."),
   N("Convert 2F (hex) to denary.", 47, "2 x 16 + 15 = 47.")],
  [M("Binary 10100110 written in hexadecimal is", "A6", ["6A", "B6", "A9"], "1010 = A, 0110 = 6, so A6."),
   N("Convert 77 to binary and give the number of 1 bits.", 4, "77 = 1001101, which has four 1s.")],
  P("Work with the number 214.",
    [pm("214 in binary (8 bits) is", "11010110", ["11010011", "10110110", "11100110"], "128+64+16+4+2 = 214."),
     pm("214 in hexadecimal is", "D6", ["6D", "D4", "C6"], "214 = 13 x 16 + 6."),
     po("Give two reasons why computers use binary rather than denary.", "Circuits have two reliable states (on/off), which map to 1 and 0; binary is easy to build and less error-prone with electronic components.", "1 mark per valid reason.")]),
  [("Binary uses the digits", "0 and 1", ["0 to 7", "0 to 9", "0 to F"], "Base 2 has two digits."),
   ("Binary 1111 equals", "15", ["8", "16", "14"], "8+4+2+1."),
   ("In 8-bit binary, the leftmost place value is", "128", ["256", "64", "8"], "The places are 128 down to 1."),
   ("Hexadecimal 'C' equals", "12", ["11", "13", "10"], "A=10, B=11, C=12."),
   ("To change binary to hexadecimal we group the bits in", "fours", ["twos", "threes", "eights"], "One hex digit = four bits.")],
  notes=["Octal is only in outline here; check whether the current syllabus requires octal."])

L_ba = lesson(c2, "binary-arithmetic", "Binary arithmetic",
  ["Add binary numbers using the carry rules", "Subtract using two's complement (outline)", "Multiply and divide by powers of 2 using shifts", "Recognise overflow"],
  [("definition", "Binary addition rules", "0+0=0; 0+1=1; 1+0=1; 1+1=10 (write 0, **carry 1**); 1+1+1=11 (write 1, carry 1). Add column by column from the right, like denary addition."),
   ("methode", "Two's complement (8 bits)", "To represent a negative number: write the positive number in 8 bits, **flip every bit**, then **add 1**. To compute A - B, add A to the two's complement of B and ignore the carry out of the 8th bit."),
   ("retenir", "Shifts", "Shifting all bits **left** by one place multiplies by 2; shifting **right** by one divides by 2 (whole numbers). Overflow happens when a result needs more bits than are available (e.g. more than 255 in 8-bit unsigned numbers)."),
   ("pieges", "Common mistakes", "- Forgetting the carry in the next column.\n- In two's complement, flipping the bits but **forgetting to add 1**.\n- Counting the ninth bit of the sum as part of an 8-bit answer.")],
  ("1011 + 0110", shapes([T(210, 24, "Adding 1011 + 0110", 15, bold=True), T(120, 52, "carry", 12), T(215, 52, "1 1 1 0", 14),
     T(120, 82, "A", 13), T(215, 82, "0 1 0 1 1", 16), T(120, 108, "B", 13), T(215, 108, "0 0 1 1 0", 16),
     LINE(150, 120, 290, 120, width=2), T(120, 146, "A+B", 13), T(215, 146, "1 0 0 0 1", 16, bold=True), T(210, 180, "11 + 6 = 17", 13)], 420, 200),
   "Column addition of 1011 and 0110 giving 10001 with carries shown.", "Binary addition layout: 01011 plus 00110 equals 10001, with carries."),
  [("Example 1 - Addition", "Add 1011 and 0110.",
    ["Right to left: 1+0=1; 1+1=0 carry 1; 0+1+1=0 carry 1; 1+0+1=0 carry 1; the last carry gives 1.", "Result 10001. Check: 11 + 6 = 17 and 10001 = 16 + 1 = 17."], "10001"),
   ("Example 2 - Subtraction", "Calculate 45 - 19 using 8-bit two's complement.",
    ["45 = 00101101. 19 = 00010011; flip: 11101100; add 1: 11101101 (this is -19).", "Add: 00101101 + 11101101 = 1 00011010. Ignore the ninth bit: 00011010 = 16+8+2 = 26."], "26 (00011010)")],
  [N("Add binary 101 and 11 and give the answer in denary.", 8, "5 + 3 = 8 (1000 in binary)."),
   M("1 + 1 in binary gives", "10 (write 0, carry 1)", ["2 written as the digit 2", "11", "0 with no carry"], "Binary has no digit 2; 1+1 = 10."),
   N("Shift 00001100 left by one place. What is the denary result?", 24, "12 x 2 = 24 (00011000).")],
  [N("The largest number that fits in 8 bits (unsigned) is", 255, "11111111 = 128+64+32+16+8+4+2+1 = 255."),
   O("What is overflow? Give an example with 8 bits.", "Overflow occurs when a result is too large for the available bits. Example: 200 + 100 = 300, which needs 9 bits, but an 8-bit unsigned store can only hold up to 255.", "1 mark definition, 1 mark correct example, 1 mark mention of the extra bit being lost.")],
  P("Binary arithmetic checks.",
    [pn("Add 01100100 (100) and 00010100 (20). Give the result in denary.", 120, "100 + 20 = 120 = 01111000."),
     pm("The 8-bit two's complement of 00000101 (5) is", "11111011", ["11111010", "10000101", "00000101"], "Flip: 11111010; add 1: 11111011."),
     po("Explain how a left shift by 2 places changes a number.", "It multiplies the number by 4 (2 x 2), as long as no bits are lost off the left end.", "1 mark multiply by 4, 1 mark overflow condition.")]),
  [("0 + 1 + 1 (no carry in) in binary equals", "10", ["2", "11", "01 with carry"], "1+1 = 10."),
   ("Shifting a binary number right by one place", "halves it", ["doubles it", "adds 1", "negates it"], "Right shift divides by 2."),
   ("Flipping all the bits of a number is the first step in", "two's complement", ["binary addition", "hex conversion", "ASCII coding"], "Then add 1."),
   ("An 8-bit unsigned store cannot hold", "300", ["200", "255", "0"], "300 > 255."),
   ("1011 + 0001 in binary equals", "1100", ["1010", "1101", "1111"], "11 + 1 = 12 = 1100.")],
  notes=["Two's complement may go beyond O Level; check the syllabus. Hand-checked: 45-19=26."])

L_dr = lesson(c2, "data-representation", "Representing characters, images and sound",
  ["Explain how text is stored as codes (ASCII)", "Describe how images are stored as pixels", "Describe how sound is sampled", "Calculate simple file sizes"],
  [("definition", "Characters", "Each character is stored as a number. **ASCII** uses 7 bits (128 codes): for example A = 65, B = 66, a = 97, 0 = 48. Capital and small letters have different codes. **Unicode** uses more bits and covers letters of many languages."),
   ("retenir", "Images", "A **bitmap image** is a grid of **pixels**. **Resolution** is the number of pixels (e.g. 800 x 600). **Colour depth** is the number of bits per pixel (24 bits for full colour). Image size in bits = width x height x colour depth."),
   ("retenir", "Sound", "Sound is **sampled**: the wave is measured many times per second (the **sample rate**, in Hz), each measurement stored with a number of bits (the **bit depth**). More samples and bits give better quality and bigger files."),
   ("pieges", "Common mistakes", "- Divide by **8** to change bits to bytes.\n- A higher resolution or sample rate improves quality **and** increases file size.\n- 'A' (65) and 'a' (97) are different codes.")],
  ("Size of an image", shapes([T(210, 24, "Pixels in a bitmap image", 15, bold=True)] + [RECT(110 + i * 40, 50 + j * 40, 40, 40, fill=("ink" if (i + j) % 2 == 0 else "white"), stroke="grey", width=1) for i in range(4) for j in range(3)] + [T(210, 200, "4 x 3 = 12 pixels", 13)], 420, 220),
   "A grid of 4 by 3 pixels, some black and some white.", "A small grid of 12 pixels coloured black and white."),
  [("Example 1 - Image size", "An image is 800 x 600 pixels with 24 bits per pixel. How many bytes does it need?",
    ["Pixels: 800 x 600 = 480000.", "Bits: 480000 x 24 = 11520000; bytes: 11520000 / 8 = 1440000."], "1 440 000 bytes (about 1.4 MB)"),
   ("Example 2 - Sound size", "Stereo sound (2 channels), 44100 samples per second, 16 bits per sample, lasts 10 seconds. File size in bytes?",
    ["Bits = 44100 x 16 x 2 x 10 = 14112000.", "Bytes = 14112000 / 8 = 1764000."], "1 764 000 bytes")],
  [M("In ASCII the code for 'A' is", "65", ["97", "48", "1"], "A = 65; a = 97."),
   N("How many bytes are needed for a 100 x 100 image with 8 bits per pixel?", 10000, "100 x 100 x 8 / 8 = 10000 bytes."),
   TF("Increasing the sample rate usually makes a sound file larger.", True, "More samples per second means more data.")],
  [M("What is a pixel?", "The smallest dot of an image", ["A unit of sound", "A type of printer", "A storage device"], "Images are grids of pixels."),
   N("Using ASCII, the code for 'C' is 67 (A=65). What is the code for 'F'?", 70, "F is 3 letters after C: 67 + 3 = 70.")],
  P("A student scans a photograph at 1000 x 500 pixels, 24-bit colour.",
    [pn("How many pixels does the image contain?", 500000, "1000 x 500 = 500000."),
     pn("How many bytes (use 24 bits = 3 bytes per pixel)?", 1500000, "500000 x 3 = 1500000 bytes."),
     po("Suggest one way to reduce the file size and its effect on quality.", "Reduce the resolution or colour depth, or use compression; this lowers quality (less detail or fewer colours).", "1 mark method, 1 mark effect.")]),
  [("ASCII uses how many bits per character (standard version)?", "7", ["2", "24", "64"], "Standard ASCII has 128 codes (7 bits)."),
   ("Colour depth means", "bits used per pixel", ["number of colours on a monitor only", "image width", "printer speed"], "More bits mean more colours."),
   ("The sample rate is measured in", "hertz (Hz)", ["pixels", "bytes", "volts"], "Samples per second."),
   ("Bitmap images are made of", "pixels", ["words", "waves", "bytes only"], "A pixel grid."),
   ("To convert bits to bytes we", "divide by 8", ["multiply by 8", "divide by 1024 only", "add 8"], "8 bits = 1 byte.")],
  notes=["File-size formulas are textbook-level; ignore headers and compression. ASCII standard is 7-bit; extended ASCII is 8-bit."])

# ================================================================== CH3 software
c3 = p.chapter("software", "Operating systems and office applications", REF)

L_os = lesson(c3, "operating-systems", "Operating systems and files",
  ["State the functions of an operating system", "Compare user interfaces (GUI, command-line)", "Use files, folders and file extensions", "Explain basic maintenance"],
  [("definition", "What an OS does", "An **operating system (OS)** manages the hardware and runs the other programs. Main functions: **memory management**, **file management**, **managing input/output devices**, **multitasking** (running several programs), **security** (user accounts and passwords) and providing a **user interface**."),
   ("retenir", "User interfaces", "A **GUI** (graphical user interface) uses windows, icons, menus and a pointer; it is easy for beginners. A **command-line interface (CLI)** uses typed commands; it is fast for experts but harder to learn. Examples of OS: Windows, Linux, macOS, Android."),
   ("methode", "Files and folders", "A **file** holds data and has a name and an **extension** that shows its type (.docx document, .xlsx spreadsheet, .jpg image, .mp3 sound, .txt plain text). A **folder** (directory) groups files. A **path** like Documents/School/Maths.docx shows where a file is stored."),
   ("pieges", "Common mistakes", "- Deleting a file in a folder does not always delete it permanently (the recycle bin may keep it).\n- Changing a file extension does not change the file's real content.\n- Closing a window is not the same as shutting down the computer: always use shut down.")],
  ("Folder structure", shapes([T(210, 24, "A folder tree", 15, bold=True), RECT(160, 40, 100, 30, fill="lightblue", radius=4), T(210, 60, "Documents", 13),
     LINE(185, 70, 100, 110, arrow="end"), LINE(235, 70, 320, 110, arrow="end"),
     RECT(40, 110, 120, 30, fill="lightgreen", radius=4), T(100, 130, "School", 13), RECT(260, 110, 120, 30, fill="lightgreen", radius=4), T(320, 130, "Family", 13),
     LINE(100, 140, 100, 170, arrow="end"), RECT(40, 170, 120, 30, fill="lightyellow", radius=4), T(100, 190, "Maths.docx", 12)], 420, 215),
   "A tree with the folder Documents containing School and Family; School holds the file Maths.docx.", "Folder tree: Documents splits into School and Family; School contains Maths.docx."),
  [("Example 1 - Extensions", "Name the type of file for budget.xlsx, song.mp3 and notes.txt.",
    ["budget.xlsx: the extension .xlsx is a spreadsheet.", "song.mp3: sound; notes.txt: plain text."], "Spreadsheet, sound, plain text."),
   ("Example 2 - Path", "A file Report.docx is in the folder Term1, inside the folder School, inside Documents. Write its path.",
    ["Start from the outer folder and go inward: Documents, then School, then Term1.", "Add the file name at the end."], "Documents/School/Term1/Report.docx")],
  [M("Which is a function of an operating system?", "File management", ["Making spreadsheets", "Printing on paper", "Scanning photos"], "File management is an OS task; the others are application or hardware tasks."),
   M("Windows, Linux and Android are examples of", "operating systems", ["word processors", "browsers", "storage devices"], "They are operating systems."),
   TF("A GUI uses icons and windows.", True, "That is the definition of a GUI.")],
  [MT("Match the extension to the file type.", [(".jpg", "Image"), (".mp3", "Sound"), (".docx", "Word-processed document"), (".txt", "Plain text")], "Extensions show how the file is encoded."),
   O("Give two advantages of a GUI over a command-line interface.", "A GUI is easier to learn and use because actions are shown as icons and menus; users do not need to remember commands, and multiple windows can be viewed at once.", "1 mark per correct advantage.")],
  P("Maria saves her homework in a folder named Homework on a flash drive.",
    [pm("What do we call the name's last part after the dot (e.g. .docx)?", "The file extension", ["The path", "The folder", "The driver"], "It shows the file type."),
     pt("Moving a file to another folder changes its path.", True, "The path includes the folder names."),
     po("State two good habits for managing files.", "Use meaningful names, group files in folders, make backups, delete old files carefully.", "1 mark each.")]),
  [("Running several programs at the same time is called", "multitasking", ["formatting", "booting", "scanning"], "The OS shares the CPU."),
   ("Which interface uses typed commands?", "Command-line", ["GUI", "Touch only", "Voice only"], "CLI means typed commands."),
   ("A folder is used to", "group files", ["print files", "scan files", "erase RAM"], "It organises files."),
   ("A password on a user account is part of the OS function of", "security", ["printing", "formatting text", "drawing"], "OS controls access."),
   ("The extension .xlsx usually shows a", "spreadsheet file", ["sound file", "image file", "video file"], "Excel-style spreadsheet.")],
  notes=["Names of operating systems/programs are given as examples only."])

L_ss = lesson(c3, "spreadsheets", "Spreadsheets: formulas, references and charts",
  ["Identify cells, rows and columns", "Write formulas with +, -, *, / and functions", "Distinguish relative and absolute references", "Choose a suitable chart"],
  [("definition", "Cells and formulas", "A spreadsheet is a grid of **columns** (A, B, C...) and **rows** (1, 2, 3...). A **cell** is named by its column and row, e.g. B3. A **formula** starts with = and calculates a value, e.g. =B2*C2. When a cell changes, formulas update automatically."),
   ("retenir", "Common functions", "=SUM(B2:B6) adds the range B2 to B6. =AVERAGE(B2:B6) gives the mean. =MAX() and =MIN() give the largest and smallest. =COUNT() counts numbers. =IF(B2>=50,\"Pass\",\"Fail\") chooses between two results."),
   ("methode", "Relative and absolute references", "When a formula is copied, a **relative reference** (B2) changes with the new position. An **absolute reference** ($B$2) stays fixed. Use it for a single value used by many rows, such as a tax rate in cell $E$1."),
   ("pieges", "Common mistakes", "- Typing the result instead of a formula: it will not update.\n- Forgetting the = sign: the cell shows text.\n- Copying a formula that needs $ and getting wrong answers.\n- Choosing a pie chart for data that is not parts of a whole.")],
  ("A small sheet", cols("Spreadsheet: item, qty, price, total", ["A: Item", "B: Qty", "C: Price", "D: =B*C"], [["Rice", "3", "600", "1800"], ["Oil", "2", "1500", "3000"], ["Total", "-", "-", "4800"]]),
   "A table with items rice and oil, quantities, prices in FCFA and totals, 4800 in total.", "Spreadsheet table with columns item, quantity, price and total; rice 3 x 600 = 1800, oil 2 x 1500 = 3000, total 4800."),
  [("Example 1 - Formulas", "Rice: 3 bags at 600 FCFA each in B2 and C2. Write the formula for the total in D2, and a formula to total D2:D3.",
    ["D2 = B2*C2 = 3 x 600 = 1800.", "If D3 is 3000, the grand total is =SUM(D2:D3) = 4800."], "=B2*C2 ; =SUM(D2:D3)"),
   ("Example 2 - Absolute reference", "Prices are in C2:C4 and a discount rate of 10% is in E1. Write the formula for the discounted price in D2 that can be copied down.",
    ["Use the price C2 and the rate E1: =C2*(1-$E$1).", "$E$1 is absolute so it stays on E1 when copied to D3 and D4; C2 becomes C3, C4."], "=C2*(1-$E$1)")],
  [M("The cell in column C, row 5 is called", "C5", ["5C", "C-5 row", "CC5"], "Column letter first, then row number."),
   N("What is =SUM(B2:B4) if B2=10, B3=20, B4=30?", 60, "10 + 20 + 30 = 60."),
   TF("A formula normally begins with the = sign.", True, "Yes, otherwise the entry is text.")],
  [M("Which chart best shows how a monthly budget is divided into parts of a whole?", "Pie chart", ["Line chart of time", "Scatter chart of two variables", "No chart suits"], "A pie chart shows shares of a total."),
   N("A1 = 50. B1 = A1*2 + 10. What is B1?", 110, "50 x 2 = 100; + 10 = 110.")],
  P("A trader records sales of three days: Mon 12000, Tue 18000, Wed 15000 FCFA in B2:B4.",
    [pn("Value of =SUM(B2:B4)", 45000, "12000 + 18000 + 15000."),
     pn("Value of =AVERAGE(B2:B4)", 15000, "45000 / 3 = 15000."),
     pm("Which chart type shows how the sales change over days?", "A line chart", ["A pie chart", "A table of text", "A word cloud"], "Line charts show trends over time.")]),
  [("The formula to add cells A1 and A2 is", "=A1+A2", ["A1+A2", "SUM A1 A2", "=A1A2"], "Start with =."),
   ("An absolute reference is written with", "$ signs", ["# signs", "brackets", "quotes"], "$A$1."),
   ("=MAX(B2:B6) returns the", "largest value in the range", ["total", "average", "number of cells"], "MAX = largest."),
   ("When a formula with relative references is copied down one row", "the row numbers change", ["nothing changes", "it turns into text", "it is deleted"], "Relative references move."),
   ("A bar chart is best for", "comparing categories", ["showing a whole as slices only", "typing text", "printing"], "Bars compare groups.")],
  notes=["Function names are the common English ones; some programs use ; instead of , in formulas."])

L_wp = lesson(c3, "wordprocessing-database", "Word processing and databases",
  ["List word-processing features and formatting", "Explain field, record, table and primary key", "Describe simple database queries and sorting", "Choose the right tool for a task"],
  [("definition", "Word processing", "A **word processor** creates and edits documents. Features: **formatting** (font, size, bold, alignment), **editing** (copy, cut, paste, find and replace), page layout (margins, columns, page numbers), tables, **spell check**, headers/footers and mail merge (sending the same letter to many people)."),
   ("definition", "Database basics", "A **database** is an organised collection of data. A **table** has **fields** (columns, e.g. Name) and **records** (rows, one per person or item). A **primary key** is a field whose value is unique for each record (e.g. a student ID)."),
   ("methode", "Searching and sorting", "A **query** finds records that match a condition, e.g. Town = \"Buea\" AND Age > 15. **Sorting** puts records in order (alphabetical or numerical, ascending or descending). A **report** presents selected data neatly."),
   ("pieges", "Common mistakes", "- A name is not a good primary key: two people can share it.\n- Data types matter: store a phone number as text, an age as a number.\n- A query shows records; it does not delete them unless asked.")],
  ("A database table", cols("Student table", ["ID", "Name", "Town", "Age"], [["S01", "Ada", "Buea", "15"], ["S02", "Paul", "Limbe", "16"], ["S03", "Nina", "Buea", "14"]]),
   "A table with fields ID, Name, Town and Age and three records.", "Database table with four fields and three student records."),
  [("Example 1 - Query", "In the student table, which records satisfy Town = \"Buea\" AND Age >= 15?",
    ["Check Town = Buea: S01 (Ada) and S03 (Nina).", "Now Age >= 15: Ada is 15 (yes), Nina is 14 (no)."], "Only record S01 (Ada)."),
   ("Example 2 - Fields and records", "In that table, how many fields and records are there, and which is the primary key?",
    ["Fields are columns: ID, Name, Town, Age = 4. Records are rows = 3.", "ID is unique for every student, so it is the primary key."], "4 fields, 3 records, key = ID")],
  [M("A row in a database table is a", "record", ["field", "query", "report"], "Rows are records."),
   M("A word processing feature to send one letter to many people is", "mail merge", ["spell check", "pie chart", "sort"], "Mail merge combines a letter with a list."),
   TF("Two records should have the same primary key.", False, "A primary key must be unique.")],
  [M("Which field is the best primary key for a school database?", "Student ID number", ["First name", "Town", "Class"], "It is unique."),
   O("Explain the difference between a field and a record.", "A field is one column holding one kind of data (e.g. Name). A record is one row containing all the fields about one person or item.", "1 mark each definition, 1 mark example.")],
  P("A library database has fields BookID, Title, Author, Year.",
    [pm("Best primary key?", "BookID", ["Title", "Author", "Year"], "Titles and authors can repeat."),
     pm("Which operation lists books in order of Year?", "Sorting", ["Querying by name only", "Spell check", "Mail merge"], "Sorting orders records."),
     po("Write a condition to find books by author \"Smith\" published after 2000.", "Author = \"Smith\" AND Year > 2000", "1 mark each condition, 1 mark AND.", pts=3)]),
  [("Making text bold is called", "formatting", ["sorting", "querying", "booting"], "Formatting changes appearance."),
   ("A column in a database table is a", "field", ["record", "report", "key"], "Fields are columns."),
   ("A query is used to", "find records matching a condition", ["delete the table", "change the font", "print paper"], "It searches the data."),
   ("Find and replace is an", "editing feature", ["storage device", "input device", "network"], "Used to change words."),
   ("A header appears", "at the top of each page", ["inside a table cell only", "only on page 1 always", "in RAM only"], "Headers repeat on pages.")],
  notes=["Mail merge and query syntax vary by software; keep generic."])

# ================================================================== CH4 networks & security
c4 = p.chapter("networks", "Networks, the Internet and security", REF)

L_net = lesson(c4, "networks-internet", "Networks and the Internet",
  ["Define LAN and WAN and name topologies", "State the benefits of networks", "Explain Internet, web, browser, URL and email", "Calculate download time"],
  [("definition", "Networks", "A **network** is a group of computers connected to share data and resources. A **LAN** covers a small area (a school lab). A **WAN** covers a large area (towns, countries); the **Internet** is a worldwide network of networks. Parts: **router**, **switch**, network cable or **Wi-Fi**, **network interface card**."),
   ("retenir", "Topologies", "**Star**: every computer connects to a central switch (easy to add/remove; if the centre fails everything stops). **Bus**: one shared cable. **Ring**: computers joined in a loop. The star is the most common in schools and offices."),
   ("retenir", "Internet and web", "The **Internet** is the network; the **World Wide Web** is the collection of web pages on it. A **browser** shows pages. A **URL** is the address of a page. An **ISP** gives Internet access. **Email** sends messages using an address such as name@example.com."),
   ("methode", "Download time", "Data rates are in **bits** per second (bps); files are in **bytes**. Time (s) = file size in bits / speed in bits per second. 1 byte = 8 bits."),
   ("pieges", "Common mistakes", "- The Internet is **not** the same as the Web.\n- Mbps (megabits per second) is not MB/s (megabytes per second): divide Mbps by 8 to get MB/s.\n- In a star network the failure of one cable affects only that computer.")],
  ("Star network", shapes([T(210, 22, "Star network", 15, bold=True), RECT(170, 90, 80, 36, fill="lightyellow", radius=6), T(210, 113, "Switch", 14)] +
      [x for (cx, cy, nm) in [(60, 60, "PC 1"), (360, 60, "PC 2"), (60, 170, "PC 3"), (360, 170, "Printer")] for x in
       (RECT(cx - 35, cy - 16, 70, 32, fill="lightblue", radius=6), T(cx, cy + 5, nm, 13), LINE(cx + (35 if cx < 200 else -35), cy, 210 + (-40 if cx < 200 else 40), 108, width=2))], 420, 205),
   "Four devices each connected to a central switch.", "Star topology: PC 1, PC 2, PC 3 and a printer all connected to a central switch."),
  [("Example 1 - Download time", "A 24 MB file is downloaded at 8 Mbps (megabits per second). How long does it take?",
    ["24 MB x 8 = 192 megabits.", "Time = 192 / 8 = 24 seconds."], "24 seconds"),
   ("Example 2 - Choose a network", "A school with two buildings in Bafoussam wants to link its labs. Name the network type for one lab and for the link to a bank across town.",
    ["One lab in one building is a small area: LAN.", "A link over a larger distance between sites/organisations is a WAN."], "LAN for the lab; WAN for the long link.")],
  [M("A network covering one school computer room is a", "LAN", ["WAN", "Internet", "ISP"], "Local Area Network."),
   N("How many bits are in 5 bytes?", 40, "5 x 8 = 40."),
   TF("The World Wide Web and the Internet mean exactly the same thing.", False, "The web is a service on the Internet.")],
  [N("How many seconds to download a 10 MB file at 20 Mbps? (1 byte = 8 bits)", 4, "10 x 8 = 80 megabits; 80 / 20 = 4 s."),
   O("Give two benefits and one drawback of networking computers in a school.", "Benefits: sharing printers and files, shared Internet connection, central backup. Drawback: if the network or server fails many users are affected; security risks such as viruses spread.", "1 mark per benefit, 1 for a drawback.")],
  P("A cyber cafe in Limbe has 10 computers connected to a switch and one router to the Internet.",
    [pm("What topology is this?", "Star", ["Bus", "Ring", "Mesh only"], "All computers connect to a central switch."),
     pm("Which device connects the café to the Internet?", "Router", ["Scanner", "Speaker", "Mouse"], "A router joins networks."),
     pn("A video is 40 MB. At 16 Mbps, how many seconds to download? (use 8 bits = 1 byte)", 20, "40 x 8 = 320 Mb; 320/16 = 20 s.", unit="s")]),
  [("A URL is", "the address of a web page", ["a type of virus", "a router", "a printer"], "It locates a page."),
   ("The device that directs data between networks is the", "router", ["monitor", "scanner", "keyboard"], "Routers forward data."),
   ("An ISP", "provides Internet access", ["makes monitors", "repairs printers", "sells spreadsheets"], "Internet Service Provider."),
   ("In a star network, a central", "switch connects all the computers", ["printer prints all pages", "monitor stores files", "speaker sends email"], "Switch or hub."),
   ("Speed 8 Mbps means", "8 megabits per second", ["8 megabytes per second", "8 minutes", "8 pixels"], "Bits not bytes.")],
  notes=["Wi-Fi/hub/switch distinctions are simplified. Download-time ignores overheads."])

L_sec = lesson(c4, "security-ethics", "Computer security, email safety and ethics",
  ["Describe threats such as viruses, phishing and hacking", "Apply protection measures", "Use email safely", "Explain copyright and responsible use"],
  [("definition", "Threats", "**Malware** is harmful software: **viruses** attach to files and spread; **worms** spread by themselves; **spyware** secretly collects information. **Phishing** uses fake emails or messages to trick people into giving passwords or money. **Hacking** is unauthorised access to a system."),
   ("methode", "Protection", "Use **strong passwords** (long, mixed letters, numbers and symbols, different for each account), keep software **updated**, install **antivirus**, use a **firewall**, **back up** files regularly, and do not open unknown attachments or links. Log out on shared computers."),
   ("retenir", "Email safety and ethics", "Do not share passwords or personal details; check the sender before you click; do not forward chain messages. **Copyright** protects creators: you may not copy or sell others' work without permission. Be respectful online; **cyberbullying** is harmful."),
   ("pieges", "Common mistakes", "- Antivirus does not remove the need to be careful.\n- Using the same password everywhere is dangerous.\n- Being offered easy money by email is a typical sign of fraud.\n- A backup stored only on the same computer is not safe.")],
  ("Layers of protection", cols("Threat and protection", ["Threat", "Protection"], [["Virus", "Antivirus"], ["Hacking", "Passwords, firewall"], ["Phishing", "Check sender"], ["Data loss", "Backups"]]),
   "A two-column table matching each threat to a protection measure.", "Table: virus - antivirus; hacking - passwords and firewall; phishing - check the sender; data loss - backups."),
  [("Example 1 - Spot the phishing", "An email says: Your account will close! Send your password to keep it. What should you do?",
    ["The message creates fear and asks for a password: signs of phishing.", "Never reply; do not click links; delete it and report to the real service by its official contact."], "Treat it as phishing and do not respond."),
   ("Example 2 - Strong password", "Which is stronger: buea123 or T7#mQ!2rv9? Explain.",
    ["buea123 is short and easy to guess (a town plus numbers).", "T7#mQ!2rv9 is long with mixed upper and lower case, digits and symbols."], "T7#mQ!2rv9 is stronger.")],
  [M("Fake emails that try to steal passwords are called", "phishing", ["backup", "formatting", "spooling"], "Phishing tricks users."),
   M("Software that detects and removes viruses is", "antivirus", ["a compiler", "a spreadsheet", "a router"], "Antivirus."),
   TF("Copying a student's project and selling it without permission is a copyright issue.", True, "Copyright protects creators' work.")],
  [M("Which is the best protection against losing files in a fire or theft?", "A backup kept in a different place", ["A second copy on the same disk", "A longer password", "A bigger screen"], "Offsite backup survives local damage."),
   O("Give three rules for using email safely.", "Do not open unknown attachments; never share passwords; check the sender's address; do not click suspicious links; use a strong password.", "1 mark per rule, up to 3.")],
  P("Joel receives an email promising a prize if he sends his bank details.",
    [pm("This is most likely", "a phishing attempt", ["a software update", "a backup", "a spreadsheet"], "It asks for sensitive data to offer a prize."),
     pt("Joel should reply with his details to claim the prize.", False, "Never send private details."),
     po("List two protection measures for his computer.", "Antivirus, firewall, regular updates, strong passwords, backups.", "1 mark each.")]),
  [("A program that spreads by attaching to files is a", "virus", ["router", "browser", "monitor"], "Malware."),
   ("A firewall", "controls network traffic into and out of a computer", ["makes screens brighter", "edits photos", "stores email"], "It filters traffic."),
   ("Which is the strongest password?", "R8!pz4Qk#2", ["password", "12345", "joel2010"], "Long and mixed."),
   ("Hacking means", "unauthorised access to a computer system", ["typing quickly", "formatting a disk", "printing a page"], "It is illegal."),
   ("Copyright protects", "the rights of creators", ["only paper books", "computer hardware cases", "keyboards"], "Creators own their work.")],
  notes=["Legal statements are general; Cameroon's cybersecurity/cybercriminality law is not cited - add reference after review."])

# ================================================================== CH5 problem solving
c5 = p.chapter("problem-solving", "Algorithms, flowcharts and programming", REF)

L_alg = lesson(c5, "algorithms-flowcharts", "Algorithms and flowcharts",
  ["Define an algorithm", "Recognise flowchart symbols", "Trace an algorithm with a trace table", "Write simple algorithms in pseudocode"],
  [("definition", "Algorithm", "An **algorithm** is a finite, step-by-step set of instructions to solve a problem. Good algorithms are **clear**, **ordered**, and **finish** after a limited number of steps. They can be written in plain words, **pseudocode**, or as a **flowchart**."),
   ("retenir", "Flowchart symbols", "**Oval**: start or end. **Rectangle**: process (a calculation or action). **Parallelogram**: input or output. **Diamond**: decision (yes/no question). **Arrows** show the order."),
   ("methode", "Tracing", "A **trace table** has one column per variable. Follow the algorithm line by line and write the new value each time a variable changes. It helps you find errors and see the final output."),
   ("pieges", "Common mistakes", "- A decision diamond needs **two** exits labelled Yes and No.\n- Do not mix input/output with process boxes.\n- An algorithm with no end (an infinite loop) is not valid.")],
  ("Flowchart", shapes([RECT(150, 10, 120, 30, fill="lightgreen", radius=15), T(210, 30, "Start", 13), LINE(210, 40, 210, 55, arrow="end"),
     POLY([(130, 55), (290, 55), (270, 85), (110, 85)], fill="lightblue"), T(200, 75, "Input mark", 13), LINE(210, 85, 210, 100, arrow="end"),
     POLY([(210, 100), (290, 130), (210, 160), (130, 130)], fill="lightyellow"), T(210, 135, "mark >= 50?", 12),
     LINE(290, 130, 330, 130, arrow="end"), T(310, 122, "No", 12), LINE(210, 160, 210, 178, arrow="end"), T(224, 172, "Yes", 12),
     RECT(150, 178, 120, 30, fill="lightorange", radius=4), T(210, 198, "Output Pass", 13),
     RECT(332, 115, 80, 30, fill="lightorange", radius=4), T(372, 135, "Output Fail", 12)], 420, 220),
   "A flowchart: start, input mark, decision mark at least 50, then output Pass or Fail.", "Flowchart with start oval, input, a decision diamond and two outputs Pass and Fail."),
  [("Example 1 - Pseudocode", "Write an algorithm to read two numbers and output their average.",
    ["INPUT a, b", "average = (a + b) / 2 then OUTPUT average. For a = 8 and b = 12 the output is 10."], "INPUT a, b; average = (a+b)/2; OUTPUT average"),
   ("Example 2 - Trace table", "Trace: total = 0; FOR n = 1 TO 4: total = total + n; OUTPUT total. What is printed?",
    ["n=1: total=1; n=2: total=3; n=3: total=6; n=4: total=10.", "After the loop ends the output is 10."], "10")],
  [M("In a flowchart, a decision is drawn as a", "diamond", ["oval", "rectangle", "parallelogram"], "A diamond asks a question."),
   TF("An algorithm must end after a finite number of steps.", True, "Otherwise it is not a valid algorithm."),
   N("Trace: x = 5; x = x * 2; x = x - 3. What is x?", 7, "5 x 2 = 10; 10 - 3 = 7.")],
  [M("The symbol for INPUT or OUTPUT is the", "parallelogram", ["diamond", "oval", "arrow"], "Parallelogram = input/output."),
   O("Write pseudocode to input a number and output whether it is positive, negative or zero.", "INPUT n; IF n > 0 THEN OUTPUT \"positive\" ELSE IF n < 0 THEN OUTPUT \"negative\" ELSE OUTPUT \"zero\" ENDIF.", "1 mark input, 1 mark correct tests, 1 mark outputs.")],
  P("Algorithm: INPUT price, qty; total = price * qty; IF total > 5000 THEN total = total - 500; OUTPUT total.",
    [pn("Output when price = 1200 and qty = 5?", 5500, "1200 x 5 = 6000 > 5000 so 6000 - 500 = 5500."),
     pn("Output when price = 800 and qty = 4?", 3200, "800 x 4 = 3200, not > 5000, so no discount."),
     po("State what the algorithm does in words.", "It calculates a total and takes 500 FCFA off when the total is greater than 5000.", "1 mark each part.")]),
  [("An algorithm is", "a step-by-step solution to a problem", ["a kind of computer", "a printer", "a virus"], "A procedure."),
   ("A rectangle in a flowchart shows a", "process", ["start", "decision", "end only"], "Calculation/action."),
   ("A trace table is used to", "follow variable values step by step", ["draw pictures", "store files", "send email"], "It checks algorithms."),
   ("Pseudocode is", "an informal way to write an algorithm", ["a real compiled program only", "a spreadsheet", "a network"], "Plain-language code."),
   ("The oval shape marks", "start or end", ["input", "decision", "output"], "Terminators.")],
  notes=["Pseudocode keywords follow common textbook style (INPUT, OUTPUT, IF/THEN/ELSE, FOR, WHILE); the GCE Board may prefer a specific style - check."])

L_prog = lesson(c5, "programming", "Programming concepts: variables, selection and loops",
  ["Define variable, constant and data type", "Write selection with IF", "Write loops with FOR and WHILE", "Trace and debug simple pseudocode"],
  [("definition", "Variables and types", "A **variable** is a named place in memory whose value can change; a **constant** does not change. Common **data types**: **integer** (whole numbers), **real** (decimals), **string** (text), **Boolean** (TRUE/FALSE). Assignment is written x = 5 (pseudocode may use an arrow)."),
   ("retenir", "Selection", "**Selection** chooses between actions with a condition: IF mark >= 50 THEN OUTPUT \"Pass\" ELSE OUTPUT \"Fail\" ENDIF. Conditions use =, <>, <, >, <=, >= and can be combined with AND, OR, NOT."),
   ("retenir", "Iteration", "**FOR i = 1 TO 5 ... NEXT i** repeats a known number of times. **WHILE condition ... ENDWHILE** repeats while the condition is true and may run zero times. **REPEAT ... UNTIL** runs at least once."),
   ("pieges", "Common mistakes", "- A WHILE loop whose condition never becomes false runs forever.\n- Off-by-one errors: FOR 1 TO 5 runs 5 times, not 4.\n- Using = for comparison and assignment confusingly; this course writes assignment as x = value and comparison in IF as =.")],
  ("Loop flow", flow("A WHILE loop", ["total = 0, n = 1", "n <= 3 ?", "total = total + n; n = n + 1", "OUTPUT total"], colors=["lightgreen", "lightyellow", "lightblue", "lightorange"]),
   "A flow of four steps showing a loop that adds the numbers 1 to 3.", "Vertical flow: set total and n, test n at most 3, add and increase, output total."),
  [("Example 1 - Selection", "Write pseudocode that outputs Adult if age >= 18 otherwise Minor.",
    ["INPUT age", "IF age >= 18 THEN OUTPUT \"Adult\" ELSE OUTPUT \"Minor\" ENDIF. For age 17 the output is Minor."], "IF age >= 18 ..."),
   ("Example 2 - Loop trace", "Trace: total = 0; n = 1; WHILE n <= 3: total = total + n; n = n + 1; ENDWHILE; OUTPUT total.",
    ["n=1: total=1, n=2; n=2: total=3, n=3; n=3: total=6, n=4.", "n=4 fails the test, loop stops, OUTPUT 6."], "6")],
  [M("Which data type stores text?", "String", ["Integer", "Real", "Boolean"], "Text is a string."),
   N("How many times does FOR i = 1 TO 6 repeat?", 6, "i takes 1,2,3,4,5,6."),
   TF("A variable's value can change while the program runs.", True, "That is why it is called a variable.")],
  [N("Trace: s = 0; FOR i = 1 TO 5: s = s + 2. What is s at the end?", 10, "Five additions of 2."),
   O("What is the difference between a FOR loop and a WHILE loop?", "FOR repeats a fixed, known number of times; WHILE repeats as long as a condition is true, so the number of repeats may not be known and may be zero.", "1 mark each description, 1 mark contrast.")],
  P("Program: count = 0; FOR n = 1 TO 10: IF n MOD 2 = 0 THEN count = count + 1 ENDIF NEXT n; OUTPUT count (MOD = remainder).",
    [pn("What is output?", 5, "Even numbers 2,4,6,8,10 = 5."),
     pm("Which data type is count?", "Integer", ["String", "Boolean", "Real"], "It holds whole numbers."),
     po("Change the program so it counts numbers divisible by 5 in 1..20.", "Use FOR n = 1 TO 20 and IF n MOD 5 = 0; the count will be 4.", "1 mark each change, 1 mark answer.")]),
  [("The Boolean data type stores", "TRUE or FALSE", ["decimal numbers", "text", "images"], "Two values."),
   ("Selection in a program uses", "IF", ["FOR", "PRINT only", "NEXT"], "Conditions."),
   ("Which loop may run zero times?", "WHILE", ["REPEAT-UNTIL", "Both always run once", "None"], "WHILE tests first."),
   ("7 MOD 2 equals", "1", ["0", "3", "2"], "7 = 3x2 + 1."),
   ("A constant", "keeps the same value", ["changes every line", "is always text", "is a loop"], "Fixed value.")],
  notes=["MOD operator is common; check whether the exam uses MOD or %. Assignment symbol conventions vary."])

# ================================================================== CH6 impact
c6 = p.chapter("impact", "ICT in society", REF)
L_ict = lesson(c6, "ict-cameroon", "The impact of ICT in Cameroon",
  ["Describe uses of ICT in education, health, business and government", "Discuss advantages and disadvantages", "Explain the digital divide and responsible use", "Name careers in ICT"],
  [("definition", "ICT", "**ICT** (information and communication technology) means technology for storing, processing and communicating information: computers, phones, networks and the Internet. It affects almost every area of life."),
   ("retenir", "Uses", "- **Education**: e-learning, online research, school computer labs.\n- **Health**: electronic records, telemedicine (advice at a distance), health information.\n- **Business**: online shopping, mobile money services, accounting software, social-media marketing.\n- **Government**: online information and forms (e-government)."),
   ("retenir", "Advantages and challenges", "Advantages: speed, access to information, new jobs, lower communication costs. Challenges: cost of equipment and data, **unreliable electricity**, limited network coverage in some areas, **digital divide** (unequal access), job changes, health issues from long screen use, misinformation, and cybercrime."),
   ("pieges", "Common mistakes", "- Not all ICT problems are 'technical': cost, training and access matter too.\n- ICT does not remove the need for teachers, doctors or farmers; it supports them.\n- Avoid giving statistics you cannot source in an exam answer.")],
  ("Two sides", cols("ICT: advantages and challenges", ["Advantages", "Challenges"], [["Fast communication", "Cost of data"], ["Access to information", "Power cuts"], ["New jobs", "Digital divide"], ["Online learning", "Cybercrime"]]),
   "A table pairing four advantages with four challenges of ICT.", "Two-column table: advantages and challenges of ICT."),
  [("Example 1 - Argue", "Give two advantages of mobile money services for a market trader in Bafoussam.",
    ["Money can be sent or received quickly without travelling.", "Less need to carry cash, which reduces the risk of theft."], "Speed and safety."),
   ("Example 2 - Challenge", "A rural school has a computer lab but frequent power cuts. Suggest two practical solutions.",
    ["Use a power source that does not depend only on the grid (e.g. solar with battery) if the budget allows.", "Teach frequent saving and use laptops with batteries; keep backups."], "Alternative power; save often; laptops with batteries.")],
  [M("ICT stands for", "information and communication technology", ["internal computer technology", "internet and cable transfer", "input and computer tools"], "Standard meaning."),
   TF("Telemedicine can give medical advice at a distance.", True, "It uses communication technology."),
   M("The 'digital divide' is", "unequal access to ICT between groups or places", ["a broken screen", "a network cable", "two files with the same name"], "Access gap.")],
  [O("Give three ways ICT has changed how businesses work.", "Online sales and advertising; electronic payments; faster communication with customers and suppliers; record keeping on computers.", "1 mark each, up to 3."),
   O("Describe two problems ICT can cause and one way to reduce each.", "Cybercrime - use strong passwords and antivirus. Long screen time - take breaks and limit use.", "1 mark per problem, 1 per matching solution.")],
  P("A town clinic plans to store patient records on a computer.",
    [pm("One advantage of electronic records is", "records can be found quickly", ["they never need backup", "they cannot be copied", "they remove the need for staff"], "Searching is fast."),
     pm("One risk is", "unauthorised access to private information", ["better handwriting", "paper cuts", "less typing"], "Privacy is a risk."),
     po("State two measures to protect the records.", "Passwords, access rights, backups, antivirus, training staff.", "1 mark each.")]),
  [("Which is an example of e-learning?", "Taking a lesson on a computer or phone", ["Writing on a blackboard only", "Repairing a road", "Farming without tools"], "Learning via ICT."),
   ("A problem that affects ICT in many places is", "unreliable electricity", ["too many teachers", "free equipment for all", "no need for training"], "Power cuts."),
   ("Mobile money is used mainly to", "send and receive money by phone", ["print photos", "repair computers", "design flowcharts"], "Financial service."),
   ("A career linked to ICT is", "network technician", ["only farmer", "only driver", "none"], "Technicians, programmers, etc."),
   ("The statement 'ICT removes all jobs' is", "false - it changes jobs and creates new ones", ["completely true", "true for teachers only", "true for all farmers"], "Jobs change.")],
  notes=["No statistics are given on purpose; add current Cameroonian data after teacher review. Mobile money is mentioned generically."])

# ================================================================== MOCK
mock(p, "1", "GCE O Level mock — Computer Studies / ICT", 90,
  "Answer all questions. The paper is marked out of 20. This is an original practice paper; its format is to be checked against the official texts of the Cameroon GCE Board.",
  [("Section A - Short questions (6 marks)", [
      (L_hw, M("Which one is **application** software?", "A spreadsheet program", ["An operating system", "A device driver", "A printer"], "It does a user task.", points=1)),
      (L_dev, M("Which memory loses its contents when the power is switched off?", "RAM", ["ROM", "A hard disk", "A flash drive"], "RAM is volatile.", points=1)),
      (L_ns, N("Convert the binary number 101101 to denary.", 45, "32+8+4+1 = 45.", points=1)),
      (L_ss, M("What is the correct formula to add A1 and B1?", "=A1+B1", ["A1+B1", "=A1B1", "ADD A1 B1"], "Formulas start with =.", points=1)),
      (L_sec, TF("It is safe to send your password to someone who emails you asking for it.", False, "Never do this: it is phishing.", points=1)),
      (L_net, M("A network that covers only one school building is a", "LAN", ["WAN", "ISP", "URL"], "LAN.", points=1))]),
   ("Section B - Structured questions (10 marks)", [
      (L_ba, P("Binary and data.", [pn("Add 1010 and 0111 and give the answer in denary.", 17, "10 + 7 = 17 (10001).", pts=2), pn("An image is 100 x 50 pixels at 8 bits per pixel. How many bytes?", 5000, "100 x 50 x 8 / 8 = 5000.", pts=2), pm("ASCII code for 'a' is", "97", ["65", "48", "1"], "a = 97.", pts=1)])),
      (L_alg, P("Algorithm: total = 0; FOR n = 1 TO 5: total = total + n * 2; OUTPUT total.", [pn("What is output?", 30, "2+4+6+8+10 = 30.", pts=2), pm("Which flowchart symbol is used for the test in an IF statement?", "Diamond", ["Oval", "Parallelogram", "Rectangle"], "Decision.", pts=1), po("Name the type of loop used.", "A FOR loop (count-controlled iteration).", "1 mark for FOR, 1 for count-controlled.", pts=2)]))]),
   ("Section C - Essay (4 marks)", [
      (L_ict, O("Discuss two benefits and two challenges of ICT in Cameroon.", "Benefits: faster communication and access to information; mobile payments and online services. Challenges: unreliable electricity and the cost of data; the digital divide and cybercrime.", "1 mark per correct, well-explained point (4 marks).", points=4))])])
write(p)
