from lit_prose import *


def oral(p):
    ch = p.chapter("ch-oral", "African oral literature and literary terms", "O Level Literature in English — African oral literature (general knowledge) and literary terms")

    B(ch, slug="african-oral-literature", title="African and Cameroonian oral literature", min=26,
      obj=["Name the main forms of oral literature.", "Explain the features of performance and the functions of oral literature.", "Analyse a short original fable and original proverbs."],
      notes=["Only general knowledge about African oral traditions is given; no specific ethnic group, storyteller or text is described. The fable and sayings are ORIGINAL: they are not traditional texts of any Cameroonian community. A teacher with local knowledge should add examples from the communities the learners know."],
      blocks=[
          ("text", "**The Cricket Who Would Not Share Its Song** (an original fable)\nLong ago the Cricket sang so sweetly that all the animals gathered at dusk to listen. The Cricket grew proud. \"My song belongs to me,\" it said, and sang only inside its hole. The nights became silent and sad. When the rains came, the Cricket's hole flooded and it cried for help. Not one animal answered, for no one had heard its voice for a long time. At last it understood: a gift that is not shared is a gift that is lost."),
          ("fig", tree("Forms of oral literature", "Oral literature", [("folktales", "stories"), ("proverbs", "wise sayings"), ("songs", "praise, work"), ("riddles", "puzzles")], h=185),
           "Oral literature is spoken, sung or chanted and handed from one generation to the next.", "A diagram with Oral literature at the top and four boxes: folktales (stories), proverbs (wise sayings), songs (praise and work) and riddles (puzzles)."),
          ("key", "definition", "What is oral literature?",
           "**Oral literature** (orature) is literature composed, performed and passed on **by word of mouth**, not first written down. It exists in the many languages of Africa, including the many languages of Cameroon. Main forms: **folktales** (animal tales, human tales, tales explaining how things began), **myths and legends**, **proverbs**, **riddles**, **songs** (praise songs for chiefs and heroes, work songs, lullabies, funeral songs) and **epics**."),
          ("key", "definition", "Features of performance",
           "- A live **storyteller** and an **audience** who may take part.\n- **Call and response:** the audience answers the storyteller.\n- **Repetition** and **songs** inside the story.\n- **Formulas:** a fixed opening (*Long ago…*) and ending.\n- **Gesture, voice and music** (drums, clapping).\n- The same tale may change slightly each time it is told."),
          ("key", "definition", "Functions",
           "- **Entertain** the community, often in the evening.\n- **Teach** values and good behaviour: fables end with a **moral**.\n- **Preserve** history, names and customs.\n- **Praise** or criticise people and encourage community spirit.\n- **Train** the young in language, memory and wit: proverbs and riddles are tests of wisdom.\nToday oral stories are also recorded, written and broadcast."),
          ("key", "definition", "Proverbs (original examples)",
           "A **proverb** is a short, wise saying that expresses a general truth, often with an image. Examples written for this lesson, in the style of such sayings:\n- *The bird that shares its fruit finds the tree full again.* (generosity pays)\n- *A path is made by many feet.* (progress needs many people)\nMeaning is **figurative**: the bird and the tree are images for people and life."),
          ("key", "pieges", "Common mistakes",
           "- Calling all oral literature « primitive » or « old-fashioned »: it is a living art.\n- Saying it has **no** author: the original author is often unknown, but every performer is a creator.\n- Explaining a proverb **literally**.\n- Mixing up **myth** (about gods or origins) and **folktale** (everyday or animal characters).\n- Forgetting the **moral** and the **audience**."),
          ("ex", "Example 1: the moral", "What is the moral of the fable of the Cricket?",
           ["The Cricket kept its song to itself and lost the animals' help.", "So the lesson: gifts or talents should be shared, otherwise we lose their value."], "A gift that is not shared is lost."),
          ("ex", "Example 2: a proverb's meaning", "Explain *A path is made by many feet.*",
           ["Literal: a path appears because many people walk the same way.", "Figurative: progress and success come from the efforts of many people together."], "Great things are achieved by many people working together."),
      ],
      ex=[
          ("mcq", "Literature passed from generation to generation by word of mouth is...", "oral literature", ["a diary", "a novel", "a script"], "Oral literature is spoken or sung."),
          ("mcq", "*Long ago…* at the start of a tale is an example of...", "an opening formula", ["a riddle", "an elegy", "an epilogue"], "A fixed opening."),
          ("tf", "A fable usually ends with a moral lesson.", True, "The moral is the lesson of the story."),
          ("mcq", "In the fable, the Cricket's pride leads to...", "loneliness and loss of help", ["a prize", "a wedding", "a journey"], "It sang only in its hole and no one answered when it needed help."),
          ("match", "Match each form with its description.", [("proverb", "a short wise saying"), ("riddle", "a puzzle to be solved"), ("praise song", "words that honour a person"), ("lullaby", "a song to soothe a baby")], "These forms differ in purpose and length."),
          ("open", "Write a short **explanation** (4–5 sentences) of two functions of oral literature in a village community. Use examples from the fable or from proverbs.",
           "Oral literature teaches values: the fable of the Cricket teaches that talents should be shared. It also entertains and brings the community together, since people gather at dusk to listen and may sing or respond. Proverbs, which compress wisdom into one image, help young people to learn how to behave and to speak wisely.",
           ["1 mark: first function named (teach, entertain, preserve history…).", "1 mark: a relevant example.", "1 mark: second function named and explained.", "1 mark: clear, well-organised writing."]),
      ],
      sc=[("A riddle is...", "a puzzle in words", ["a funeral song", "a sad poem", "a letter"], "Riddles test wit."),
          ("Call and response means...", "the audience answers the performer", ["the story is written", "only the narrator speaks", "silence"], "A feature of performance."),
          ("A proverb's meaning is usually...", "figurative", ["literal", "unknown", "funny only"], "It uses an image."),
          ("A praise song is for...", "honouring a person", ["selling goods", "sleeping", "farming only"], "It celebrates qualities."),
          ("Oral literature today...", "is still performed and also recorded", ["has disappeared", "is only written", "is forbidden"], "It is living.")])

    B(ch, slug="literary-terms", title="A glossary of literary terms", min=24,
      obj=["Define the most useful literary terms.", "Tell the three kinds of irony apart.", "Match terms with short examples."],
      blocks=[
          ("text", "Examiners reward the **accurate use of terms** when you comment on a text. Learn each term with a short example of your own. This lesson gives the most useful ones for prose, poetry and drama."),
          ("fig", spokes("Three kinds of irony", "irony", ["verbal", "situational", "dramatic", "(the gap)"]),
           "In all kinds of irony there is a gap between appearance and reality.", "A centre box with the word irony and arrows to verbal, situational, dramatic and the gap."),
          ("key", "definition", "Terms for prose and drama (1)",
           "- **Protagonist / antagonist:** the main character / the one who opposes.\n- **Narrator:** the voice telling the story.\n- **Plot, setting, theme, tone, mood:** see earlier lessons (tone = the writer's attitude; mood = the feeling the reader gets).\n- **Flashback, foreshadowing, suspense.**\n- **Symbol:** a thing that stands for an idea.\n- **Motif:** a repeated image or idea that supports the theme.\n- **Allegory:** a story whose characters and events stand for ideas (often moral or political)."),
          ("key", "definition", "Terms of language (2)",
           "- **Irony:** *verbal* (says the opposite), *situational* (the outcome is the opposite of what is expected), *dramatic* (the audience knows more than the character).\n- **Satire:** criticising by ridicule. **Parody:** a funny imitation of a style.\n- **Paradox:** a statement that seems contradictory but contains truth (*less is more*). **Oxymoron:** two opposite words together (*bitter-sweet, deafening silence*).\n- **Understatement:** saying less than is meant. **Euphemism:** a gentle word for something unpleasant (*passed away*)."),
          ("key", "definition", "Terms of sound and poetry (3)",
           "- **Alliteration, assonance, onomatopoeia, rhyme, rhythm, refrain** (see the sound lesson).\n- **Imagery, simile, metaphor, personification, hyperbole.**\n- **Pun:** a joke using a word with two meanings. **Apostrophe:** addressing an absent person or thing directly (*O sea, why are you so cruel?*).\n- **Genre:** the kind of text (novel, poem, play, short story, fable)."),
          ("key", "pieges", "Common mistakes",
           "- Using a term without a **quotation and an effect**.\n- Mixing **tone** and **mood**.\n- Calling any sad ending **ironic**: irony needs a gap between expectation and result.\n- Calling any comparison a **metaphor**: check for *like / as* (simile).\n- Using **allegory** for any story with a lesson (that is a fable or parable)."),
          ("ex", "Example 1: situational irony", "A fire station burns down. What kind of irony is this?",
           ["The place that should stop fires is destroyed by one: the opposite of what we expect.", "No one is speaking ironically and no audience knows more than a character, so it is **situational**."], "situational irony"),
          ("ex", "Example 2: oxymoron or paradox", "Which term fits *deafening silence*?",
           ["It puts two opposite words together: *deafening* (very loud) and *silence*.", "That is an **oxymoron**."], "oxymoron"),
      ],
      ex=[
          ("match", "Match each term with its meaning.", [("euphemism", "a gentle word for something unpleasant"), ("oxymoron", "two opposite words together"), ("pun", "a joke on a word with two meanings"), ("motif", "a repeated image or idea")], "Learn each term with an example."),
          ("mcq", "Saying *What a lovely day!* in a violent storm is...", "verbal irony", ["situational irony", "dramatic irony", "a simile"], "The words mean the opposite of the situation."),
          ("tf", "Tone is the feeling the reader gets from a text; mood is the writer's attitude.", False, "Reversed: tone = writer's attitude; mood = the feeling created."),
          ("mcq", "*The thief called the police because someone had stolen his bag.* This is...", "situational irony", ["an oxymoron", "personification", "a pun"], "Unexpected and opposite to what we expect."),
          ("mcq", "A story where characters and events stand for deeper ideas is an...", "allegory", ["elegy", "epic", "ode"], "Allegory."),
          ("open", "Choose **three** terms from the glossary. For each, write one original sentence which shows its meaning (for example, a sentence with a simile or an oxymoron).",
           "Simile: The new teacher was as calm as a still pond. Oxymoron: The audience fell into a deafening silence. Euphemism: Our old neighbour passed away last year.",
           ["1 mark per correct sentence with the right term.", "1 mark for variety and clarity."]),
      ],
      sc=[("A deafening silence is an...", "oxymoron", ["simile", "allegory", "ode"], "Two opposites."),
          ("A euphemism is...", "a gentle word for something unpleasant", ["an exaggeration", "a rhyme", "a refrain"], "e.g. passed away."),
          ("A motif is...", "a repeated idea or image", ["the title", "the climax", "a character"], "Repeated."),
          ("Dramatic irony means...", "the audience knows more than the character", ["the writer is angry", "the play is funny", "it is a poem"], "Audience knowledge."),
          ("A parody is...", "a funny imitation", ["a funeral song", "a map", "a lesson"], "Imitates to amuse.")])
    return ch
