import sys
sys.path.insert(0, "/home/user/CastBridge/tools/learn-authoring/anglophone")
from _gl import *

NOTE = "Official set texts are NOT covered: an expert must add lessons on the texts prescribed by the GCE Board. All poems, passages and scenes in this pack are original, written for practice."
p = Pack("lower6-literature", "Literature in English — Lower Sixth", level="Lower Sixth", subject="english", cursus="secondary",
         wanted="literature",
         description="Transferable literature skills for Lower Sixth with original practice texts: prose analysis, poetry form, imagery, sound and tone, unseen appreciation, drama and tragedy, oral tradition, context questions and essay planning. Official set texts are not included.",
         programRef="Cameroon GCE Board, Advanced Level Literature in English syllabus (Lower Sixth) — skills only; set texts to be added by an expert")

# ======================================================== PROSE
ch = p.chapter("prose", "Prose: narrative, character and setting")
L = lesson(ch, "prose-analysis", "Analysing a prose passage",
    ["Identify narrator, point of view and tone", "Analyse characterisation, setting and language", "Write a short, evidence-based commentary"],
    [("definition", "Narrator and point of view", "The **narrator** tells the story. **First person** (‘I’) gives a personal, limited view. **Third person limited** follows one character’s thoughts. **Omniscient** narration knows everything about all characters. The point of view controls what we know and how far we trust it."),
     ("retenir", "Character, setting, language", "**Characterisation** can be **direct** (the narrator tells us) or **indirect** (through actions, speech, thoughts, other characters’ reactions). **Setting** includes place, time and atmosphere. Look at **diction** (word choice), **imagery**, **sentence length** and **tone**, and always ask: what effect does this have on the reader?"),
     ("methode", "A commentary in four steps", "1. State what is happening and who is speaking. 2. Pick a detail and quote a few words. 3. Name the technique (for example personification). 4. Explain the **effect**: what it shows about character, mood or theme. This is the **point, quotation, technique, effect** method."),
     ("pieges", "Common mistakes", "- Retelling the story instead of analysing the writing.\n- Naming a technique without explaining its effect.\n- Quoting long chunks: use short, precise quotations.\n- Confusing the author with the narrator.")],
    [("Example 1 — Point of view", "Original passage: ‘Mama Enow set out her tomatoes in the grey light, one red pyramid at a time. Across the lane the cloth seller’s radio was already arguing with itself. When her son’s footsteps came she did not look up; she knew them by their hesitation. A boy with something to confess walks as if the road were cold water.’ Identify the point of view.",
      ["The narrator uses ‘she’ and ‘her’: third person.", "We learn what Mama Enow knows (‘she knew them by their hesitation’).", "So it is third-person limited, close to Mama Enow’s perception."], "Third-person limited, close to Mama Enow."),
     ("Example 2 — Effect of language", "Use the same passage: comment on ‘the cloth seller’s radio was already arguing with itself’.",
      ["Technique: personification; the radio is given a human action.", "It suggests overlapping stations and noise, so the market is busy and a little chaotic.", "‘Already’ shows the day has only just begun, and contrasts with Mama’s calm."], "Personification creates noisy market atmosphere and contrasts with her calm.")],
    [M("In third-person limited narration, the narrator", "Follows the thoughts of one character", ["Knows everything about everyone", "Speaks as ‘I’", "Never describes thoughts"], "Limited means access to one mind."),
     TF("Indirect characterisation reveals character through actions and speech.", True, "Direct characterisation is when the narrator simply tells us."),
     MT("Match the term to its meaning.", [("Diction", "Choice of words"), ("Setting", "Place, time and atmosphere"), ("Narrator", "Voice telling the story"), ("Tone", "Writer’s or speaker’s attitude")], "Basic prose terms."),
     M("‘The road were cold water’ is an example of", "Metaphor/simile-like comparison", ["Alliteration only", "Rhyme", "A stage direction"], "It compares walking to entering cold water to show reluctance."),
     O("Original sentence: ‘The old mango tree leaned over the compound as if it wanted to hear the family’s secrets.’ Name the technique and explain its effect.", "Personification: the tree is given the human wish to listen. The effect is to make the compound feel intimate and watchful, suggesting that secrets are present and creating a slightly mysterious atmosphere.", "Technique (1); effect on atmosphere (2); use of quotation (1)."),
     O("Original passage: ‘Mr Tabot straightened his tie in the window of the closed bank, though no one was awake to see. His shoes were polished, his cuffs frayed.’ Write a short paragraph on what the details suggest about his character.", "The straightened tie and polished shoes suggest pride and a wish to look respectable even when unobserved. The frayed cuffs contrast with this, suggesting that he is not wealthy and perhaps struggling. Together these indirect details show a dignified man hiding hardship.", "Quoted detail (1); effect on character (2); contrast noted (1).")],
    [("The narrator of a first-person story uses", "‘I’", ["‘He’ only", "‘They’ only", "No pronouns"], "First-person narrator is part of the story."),
     ("Diction refers to", "Word choice", ["Punctuation", "Rhyme scheme", "Stage design"], "The words the writer selects."),
     ("An omniscient narrator", "Knows all characters’ thoughts", ["Only knows one character", "Is absent", "Is always lying"], "All-knowing."),
     ("Effect means", "What the technique does to the reader or meaning", ["Name of the technique", "A quotation", "A summary"], "Always explain effect."),
     ("A good quotation is", "Short and relevant", ["A whole page", "Unrelated", "Invented"], "Brief evidence.")],
    (flow(["Point: make a claim", "Quotation: short evidence", "Technique: name it", "Effect: explain what it shows"], 440, "blue", 13, 320),
     "The four steps of a commentary.", "Four boxes joined by arrows: point, quotation, technique and effect."),
    [NOTE, "Terminology varies slightly between textbooks (for example ‘limited omniscient’): follow the syllabus."])

# ======================================================== POETRY
ch = p.chapter("poetry", "Poetry: form, imagery, sound and tone")
L = lesson(ch, "poetry-form", "Poetic form: stanza, rhyme and rhythm",
    ["Describe line, stanza, rhyme scheme and metre", "Recognise the sonnet, ballad and free verse", "Explain how form supports meaning"],
    [("definition", "Building blocks", "A **line** is one row of verse; a **stanza** is a group of lines (couplet 2, tercet 3, quatrain 4). A **rhyme scheme** labels end sounds with letters (ABAB). **Metre** is the pattern of stressed and unstressed syllables; the **iambic** foot is unstressed–stressed (da-DUM) and **pentameter** has five feet per line (about ten syllables)."),
     ("retenir", "Common forms", "A **sonnet** has 14 lines in a fixed pattern. A **ballad** tells a story in short stanzas, often quatrains with a simple rhyme. **Free verse** has no regular rhyme or metre. **Haiku** is a short, three-line form. An **elegy** mourns; an **ode** praises; a **lyric** expresses personal feeling."),
     ("retenir", "Form and meaning", "A strict form can suggest order, control, or tradition; broken rhythm or free verse can suggest freedom, disruption or speech-like honesty. **Enjambment** (a sentence running over the line end) creates flow; a **caesura** (pause within a line) creates emphasis. Always link a formal feature to its effect."),
     ("attention", "Do not forget", "- A rhyme scheme describes the END sounds only.\n- Free verse is not ‘without rules’: poets still choose line breaks and rhythm.\n- Do not just count syllables: explain what the pattern does.")],
    [("Example 1 — Rhyme scheme", "Original poem: ‘The harmattan has dusted every tree, / A grey sun hangs above the market lane; / The children chase a tyre and shout with glee, / While old men count the days until the rain.’ Find the rhyme scheme.",
      ["Line 1 ends tree, line 3 ends glee: same sound (A).", "Line 2 ends lane, line 4 ends rain: same sound (B).", "Pattern: A B A B."], "ABAB."),
     ("Example 2 — Form and meaning", "In the same poem, what effect does the regular ABAB rhyme have?",
      ["The steady rhyme gives a settled, rhythmic feel like a song or chant.", "It suits the repeating annual pattern of dry season and rain.", "The final line’s ‘count the days’ adds a quiet sense of waiting."], "Regular rhyme suggests a stable, cyclical, song-like scene.")],
    [M("A stanza of four lines is called a", "Quatrain", ["Couplet", "Tercet", "Sonnet"], "Quatrain = 4 lines."),
     TF("A sonnet has 14 lines.", True, "Standard definition."),
     MT("Match the form to its description.", [("Ballad", "Story told in short stanzas"), ("Elegy", "Poem of mourning"), ("Haiku", "Very short three-line poem"), ("Free verse", "No fixed rhyme or metre")], "Standard definitions."),
     M("Iambic pentameter has", "Five iambs per line", ["Four trochees", "Three dactyls", "Fourteen feet"], "Five da-DUM feet."),
     O("Original lines: ‘The bell rang once. / The road went empty.’ Comment on the effect of the short lines.", "The short lines slow the reader and create pauses. The single ring of the bell and the emptiness of the road feel stark, giving an atmosphere of silence and loneliness. The line break after ‘once’ emphasises the finality of the sound.", "Short lines identified (1); effect on pace (1); atmosphere (1); use of quotation (1)."),
     O("Original quatrain: ‘We came with songs, we left with none; / The river heard, the river knew; / The drum kept time till night was done, / And dawn forgot the songs we drew.’ Identify the rhyme scheme and comment on how the form supports the mood.", "The scheme is ABAB: none/done and knew/drew. The regular rhyme and repeated ‘river’ give a chant-like rhythm which suits a ritual or farewell. The softly falling ending, ‘dawn forgot’, adds a feeling of loss, which the neat rhyme makes quietly resigned rather than angry.", "Rhyme scheme (1); chant-like effect (1); link to mood (2).")],
    [("A couplet is", "Two lines", ["Three lines", "Four lines", "Fourteen lines"], "Couplet = 2 lines."),
     ("Enjambment means", "A sentence runs over the line end", ["Rhyme in the middle", "A pause in the middle", "A stanza break"], "No pause at the line end."),
     ("A rhyme scheme AABB means", "Lines 1–2 rhyme, lines 3–4 rhyme", ["Alternate lines rhyme", "No rhyme", "All four rhyme"], "Paired rhymes."),
     ("A caesura is", "A pause within a line", ["End of poem", "Title", "Refrain"], "Often marked by punctuation."),
     ("Free verse", "Has no regular rhyme or metre", ["Has to rhyme", "Is always funny", "Must have 14 lines"], "Poets choose rhythm freely.")],
    (table(["Form", "Typical feature"], [["Sonnet", "14 lines"], ["Ballad", "Story in quatrains"], ["Haiku", "3 short lines"], ["Free verse", "No fixed pattern"]], 440, 13, 32),
     "Common poetic forms.", "A table of four poetic forms and a typical feature of each."),
    [NOTE, "Syllable counts and metre names are simplified: confirm what the syllabus requires (scansion, other forms)."])

L = lesson(ch, "imagery", "Imagery and figurative language",
    ["Identify simile, metaphor, personification, hyperbole and symbol", "Distinguish types of imagery", "Explain the effects of figurative language"],
    [("definition", "Figures of speech", "A **simile** compares using ‘like’ or ‘as’. A **metaphor** says one thing *is* another. **Personification** gives human qualities to non-human things. **Hyperbole** is deliberate exaggeration. **Oxymoron** joins contradictory words (‘bitter sweet’). A **symbol** is an object or image standing for an idea (a river for time or change)."),
     ("retenir", "Imagery", "**Imagery** is language that appeals to the senses: **visual** (sight), **auditory** (sound), **tactile** (touch), **olfactory** (smell), **gustatory** (taste) and **kinaesthetic** (movement). Poets often combine images to build a mood or an idea."),
     ("methode", "How to comment", "Quote the image, name the device, say what is being compared, and explain the effect: what does the comparison make us see, feel or understand? Then link it to the poem’s theme. Avoid ‘it paints a picture’ on its own: say which picture and why it matters."),
     ("pieges", "Pitfalls", "- Do not call every comparison a metaphor: check for ‘like’ or ‘as’ (simile).\n- Imagery is not only visual.\n- A symbol needs explanation: what does it stand for in this text?")],
    [("Example 1 — Name the device", "Original lines: ‘The night was a black cloth pulled over the town, and the generators coughed like old men.’ Name the two devices.",
      ["‘The night was a black cloth’ states one thing is another: metaphor.", "‘Coughed like old men’ uses ‘like’: simile (and the generators also receive a human action, personification)."], "Metaphor, simile (with personification)."),
     ("Example 2 — Effect of an image", "Explain the effect of ‘The night was a black cloth pulled over the town’.",
      ["The cloth suggests darkness covering everything evenly.", "‘Pulled over’ suggests that someone has covered the town on purpose: protection or concealment.", "The effect is a quiet, slightly secretive atmosphere."], "It creates a hushed, concealed atmosphere.")],
    [M("‘Her voice was honey’ is a", "Metaphor", ["Simile", "Oxymoron", "Onomatopoeia"], "It states directly that the voice is honey."),
     TF("Personification gives human qualities to objects or ideas.", True, "The definition."),
     MT("Match the device to the example.", [("Simile", "As quiet as a stone"), ("Hyperbole", "I have told you a million times"), ("Oxymoron", "Deafening silence"), ("Personification", "The wind whispered")], "Standard examples."),
     M("Which is auditory imagery?", "The drum thundered through the compound", ["The wall was rough and cold", "The sky was red", "The mango smelled sweet"], "It appeals to hearing."),
     O("Original line: ‘Hope is a small lamp that the wind keeps testing.’ Name the device and comment on its effect.", "A metaphor comparing hope to a small lamp. The lamp suggests something fragile but bright, and ‘the wind keeps testing’ gives the wind a challenging role, so hope is shown as precious and under constant threat but still alive.", "Device (1); meaning of lamp (1); effect of ‘testing’ (1); link to theme (1)."),
     O("Original poem: ‘The river is a long road for the rain, / its bridges stitches in green cloth; / the fishermen are patient clocks, / and the sun stirs the water like soup.’ Write a paragraph on how the poet uses metaphor to present the river.", "The poet builds a series of metaphors that make the river familiar. Calling it a road suggests a journey for the rain, the bridges as stitches shows human work joining the land, and fishermen as patient clocks links time with calm waiting. The final comparison to stirred soup makes the sunlit water warm and domestic. Together they present the river as a living, welcoming part of daily life.", "At least three metaphors identified (2); effect explained (2); overall impression (1).")],
    [("A simile uses", "‘Like’ or ‘as’", ["No comparison", "A rhyme only", "A symbol only"], "Explicit comparison."),
     ("Hyperbole is", "Exaggeration", ["Understatement", "A rhyme", "A rhythm"], "For emphasis."),
     ("‘Bitter sweet’ is an example of", "Oxymoron", ["Simile", "Alliteration", "Ballad"], "Contradictory terms."),
     ("A symbol", "Stands for an idea beyond itself", ["Is always a person", "Is a rhyme", "Is a stage direction"], "E.g. a river for change."),
     ("Tactile imagery appeals to", "Touch", ["Taste", "Smell", "Hearing"], "Feeling.")],
    (table(["Device", "Example"], [["Simile", "like a drum"], ["Metaphor", "life is a road"], ["Personification", "the sun smiled"], ["Hyperbole", "a mountain of work"]], 440, 13, 32),
     "Figures of speech with examples.", "A table listing simile, metaphor, personification and hyperbole with a short example each."),
    [NOTE, "All example lines are original."])

L = lesson(ch, "sound-tone", "Sound, tone and the unseen poem",
    ["Identify sound devices and explain their effects", "Describe tone and mood", "Use a method to approach an unseen poem"],
    [("definition", "Sound devices", "**Alliteration:** repeated consonant sounds at the start of words. **Assonance:** repeated vowel sounds. **Consonance:** repeated consonants within or at the end of words. **Onomatopoeia:** words that imitate sounds (buzz, clatter). **Rhythm** is the beat of the lines; **repetition** and **refrain** stress ideas."),
     ("retenir", "Tone and mood", "**Tone** is the speaker’s attitude (tender, angry, ironic, nostalgic, humorous); **mood** is the atmosphere created for the reader. Tone comes from diction, imagery, rhythm and punctuation. Words like ‘murmured’ and ‘hushed’ suggest softness; harsh sounds such as ‘k’ and ‘t’ can suggest sharpness."),
     ("methode", "Approaching an unseen poem", "1. Read twice; read the title. 2. Who is speaking, to whom, about what? (**speaker and subject**) 3. What is the **theme**? 4. Look at **form** (stanzas, rhyme, rhythm). 5. Identify **imagery and sound**. 6. Decide the **tone** and any change (a **turn**). 7. Write a focused appreciation, using quotations."),
     ("pieges", "Common errors", "- Listing devices without explaining effect.\n- Ignoring the title or the ending.\n- Deciding the theme from the first line only: poems often turn.")],
    [("Example 1 — Sound devices", "Original lines: ‘The slow sun slips on the silent street, / and soft sandals whisper by.’ Identify the dominant sound and its effect.",
      ["The repeated ‘s’ sound is sibilance, a form of alliteration and consonance.", "‘Whisper’ is also onomatopoeic.", "Effect: a soft, hushed mood like quiet evening movement."], "Sibilance creating a hushed mood."),
     ("Example 2 — Identify tone", "Original lines: ‘They said the road would be ready by June; / we are still waiting, and it is nearly June again.’ Describe the tone.",
      ["The speaker repeats the promise and the delay with calm words.", "The ironic ‘nearly June again’ suggests the year has passed.", "Tone: wry, tired, gently mocking the broken promise."], "Wry and ironic.")],
    [M("‘Clatter’ and ‘buzz’ are examples of", "Onomatopoeia", ["Simile", "Hyperbole", "Oxymoron"], "They imitate sounds."),
     TF("Tone is the speaker’s attitude; mood is the atmosphere created.", True, "Distinguish the two."),
     MT("Match the term to its meaning.", [("Alliteration", "Repeated initial consonant sounds"), ("Assonance", "Repeated vowel sounds"), ("Refrain", "A repeated line or phrase"), ("Turn", "A shift in thought or tone")], "Standard terms."),
     M("Which is the first step in approaching an unseen poem?", "Read it carefully and consider the title", ["Write the conclusion", "Count the words", "Quote the last line only"], "Begin by reading and noticing the title."),
     O("Original lines: ‘The kettle muttered, the clock ticked slow, / and Grandma hummed the morning in.’ Comment on the sound and mood.", "Onomatopoeic and verb choices such as ‘muttered’, ‘ticked’ and ‘hummed’ create a gentle domestic sound world. The slow rhythm, with its soft consonants, gives a calm, comforting mood, as if Grandma’s humming brings the day in with care.", "Sound devices identified (1); explanation (1); mood (1); quotation (1)."),
     O("Original poem: ‘Market closed. The scales are still. / A single orange rolls away / and no one runs to catch it. / Rain begins.’ Write an appreciation covering subject, tone and technique.", "The poem pictures a market at the end of the day. Short sentences and full stops give a stark, still tone. The rolling orange, which nobody chases, symbolises neglect or the end of activity, and the final short sentence, ‘Rain begins’, adds a sense of quiet melancholy and closing. The form is irregular and free verse, which suits the natural, unforced observation.", "Subject (1); tone (1); technique with example (1); form/ending (1).")],
    [("Alliteration is", "Repeated initial consonant sounds", ["Repeated vowel sounds", "Exaggeration", "A comparison"], "Starting sounds."),
     ("A refrain is", "A repeated line or group of lines", ["A stage direction", "A title", "A rhyme scheme"], "It reinforces an idea."),
     ("Mood is", "The atmosphere created for the reader", ["The writer’s age", "The rhyme scheme", "The title"], "Feeling created."),
     ("A ‘turn’ in a poem is", "A shift in thought or tone", ["An end rhyme", "The title", "A refrain"], "Common near the end."),
     ("Sibilance is repeated", "’s’ sounds", ["’k’ sounds", "’p’ sounds", "Vowel sounds only"], "Soft hissing effect.")],
    (flow(["Read twice; note the title", "Speaker, subject, theme", "Form, imagery, sound", "Tone and turn; write with quotations"], 440, "blue", 13, 320),
     "A method for unseen poems.", "Four boxes: read and title, speaker subject theme, form imagery sound, and tone then writing."),
    [NOTE, "All poems are original; unseen method steps can vary between teachers."])

# ======================================================== DRAMA
ch = p.chapter("drama", "Drama: structure, tragedy and comedy")
plot_fig = shapes([
    PATH("M 30 190 L 120 120 L 210 40 L 310 120 L 400 190", stroke="blue", width=3),
    T(75, 150, "Rising action", 12), T(210, 24, "Climax", 12, bold=True), T(345, 150, "Falling action", 12),
    T(30, 215, "Exposition", 12, anchor="start"), T(400, 215, "Resolution", 12, anchor="end"),
], 440, 235)
L = lesson(ch, "drama-structure", "Dramatic structure and the language of drama",
    ["Describe the elements and structure of a play", "Explain soliloquy, aside, dialogue and stage directions", "Analyse an original scene"],
    [("definition", "Elements of drama", "A play has **plot**, **characters**, **dialogue**, **setting**, **theme** and **stagecraft**. It is divided into **acts** and **scenes**. A **soliloquy** is a character speaking thoughts alone; an **aside** is a remark to the audience; **stage directions** tell actors and directors how to move, speak and use the stage. **Dramatic irony** occurs when the audience knows more than the characters."),
     ("retenir", "Structure", "A traditional plot has **exposition** (setting up), **rising action** (growing conflict), **climax** (turning point), **falling action** and **resolution** or **denouement**. A play may use **subplots**, **foreshadowing** and **flashbacks**. Tension grows through conflict between characters, desires, or values."),
     ("methode", "Analysing a scene", "Ask: What is the situation? What does each character want? How does the dialogue show power, emotion or conflict (interruptions, short lines, silence)? What do stage directions add? How does the scene move the plot forward and develop theme? Then explain the effect on an audience."),
     ("pieges", "Common mistakes", "- Treating a play as a novel: remember it is written to be performed.\n- Ignoring stage directions and silences.\n- Confusing an aside (to the audience) with a soliloquy (alone on stage).")],
    [("Example 1 — Analyse a short scene", "Original scene. MADAM FORCHA (folding a letter, not looking up): ‘You are late.’ TABE (at the door): ‘The bus—’ MADAM FORCHA: ‘The bus is always the bus.’ (She puts the letter into a drawer and locks it.) Comment on the dramatic effect.",
      ["Short lines and interruption show Madam Forcha’s control over Tabe.", "Not looking up is a physical sign of power.", "Locking the letter creates mystery and tension for the audience."], "Power, control and suspense through short lines and action."),
     ("Example 2 — Placing a scene in the structure", "In a play, a young teacher discovers that the school fees are being misused; later he decides to confront the headmaster. Place these moments in the plot structure.",
      ["Discovery: rising action (the conflict develops).", "Decision to confront: probably the turning point, or climax, if it changes everything.", "The consequences would be the falling action and resolution."], "Discovery rises; confrontation is the climax; consequences resolve.")],
    [M("A soliloquy is", "A character speaking thoughts aloud, alone", ["A remark to another actor", "A scene change", "A stage light"], "A soliloquy reveals inner thoughts."),
     TF("Dramatic irony occurs when the audience knows more than the character.", True, "Definition."),
     MT("Match the term to the meaning.", [("Aside", "Brief remark to the audience"), ("Exposition", "Introduction of situation and characters"), ("Climax", "Turning point of the action"), ("Stage direction", "Instruction on how to perform")], "Standard terms."),
     M("The resolution of a play is also called the", "Denouement", ["Exposition", "Soliloquy", "Prologue"], "The ending where things are settled."),
     O("Original stage direction: ‘(Long pause. He picks up the cup, puts it down, and looks at the door.)’ Explain what it adds to a scene.", "The pause and the small actions show hesitation and nervousness without words. The audience sees the character’s unspoken thoughts, creating tension and suggesting that something important is about to happen.", "Pause and gestures identified (1); inner state (1); tension (1); audience effect (1)."),
     O("Original dialogue: A: ‘We agreed.’ B: ‘You agreed.’ A: ‘Then it is settled.’ B: ‘Nothing is settled.’ Write a paragraph on how the dialogue conveys conflict.", "The dialogue uses very short lines and repetition, which creates tension. B’s echoing of A’s words changes ‘We agreed’ into ‘You agreed’, rejecting shared responsibility. The final refusal, ‘Nothing is settled’, escalates the conflict. The rhythm of quick exchange suggests growing anger or defiance.", "Short lines (1); echoing/change of pronoun (1); escalation (1); effect (1).")],
    [("Acts are divided into", "Scenes", ["Poems", "Chapters", "Stanzas"], "Standard structure."),
     ("A prologue is", "An introduction before the main action", ["The final line", "A scene change", "A rhyme"], "It opens the play."),
     ("Foreshadowing is", "Hints of future events", ["A flashback", "A pun", "A rhyme"], "A device to build expectation."),
     ("Dialogue is", "Conversation between characters", ["A narrator’s summary", "A stage light", "A prop"], "Characters speaking."),
     ("The climax is", "The turning point", ["The first line", "The title", "The curtain"], "Peak of conflict.")],
    (plot_fig, "A traditional plot structure.", "A rising and falling line labelled exposition, rising action, climax, falling action and resolution."),
    [NOTE, "Terminology (denouement, dramatic irony) is standard; check the syllabus list of terms."])

L = lesson(ch, "tragedy-comedy", "Tragedy and comedy",
    ["Describe the features of tragedy and of comedy", "Explain terms such as hamartia, hubris and catharsis", "Discuss tragicomedy and modern tragedy"],
    [("definition", "Tragedy", "In tragedy a central character, often of high status, falls from fortune to disaster. **Aristotle**, the ancient Greek thinker, described tragedy as arousing **pity and fear**, ending in **catharsis** (emotional release). Key terms: **tragic hero**, **hamartia** (an error or flaw), **hubris** (excessive pride), **peripeteia** (reversal of fortune) and **anagnorisis** (moment of recognition)."),
     ("retenir", "Comedy and tragicomedy", "**Comedy** usually has a happy or hopeful ending, ordinary characters, humour, misunderstandings, disguise and **satire** of social behaviour. Types include romantic comedy, **comedy of manners** and farce. **Tragicomedy** mixes serious and comic elements. Modern writers often present tragedies of **ordinary people**, not only kings."),
     ("retenir", "Writing about tragedy", "Discuss the hero’s qualities, their choices, the causes of the fall (flaw, fate, society) and the audience’s response. Distinguish **what happens** from **why it matters**. Compare a hero’s **responsibility** and the role of circumstances."),
     ("pieges", "Pitfalls", "- Tragedy does not simply mean ‘sad’: it follows a pattern of downfall and recognition.\n- Comedy does not mean ‘only funny’: it can address serious social themes.\n- Do not apply Aristotle’s ideas as a rigid checklist.")],
    [("Example 1 — Apply the terms", "Original outline: a respected village headman refuses to listen to advice, sells communal land to a stranger, and loses the trust of his people, recognising too late what he has done. Identify hamartia, hubris, anagnorisis.",
      ["Hamartia: the poor decision to sell the land.", "Hubris: refusing to listen to advice out of pride.", "Anagnorisis: recognising too late the harm done."], "Hamartia (selling), hubris (pride), anagnorisis (recognition)."),
     ("Example 2 — Comic features", "Original outline: two market traders swap hats by mistake, and each is taken for the other at a wedding. List comic devices.",
      ["Mistaken identity.", "Misunderstandings and farcical situations.", "Likely resolution in laughter and reconciliation."], "Mistaken identity, farce and a happy resolution.")],
    [M("Hamartia is", "An error or flaw leading to downfall", ["The final scene", "A song", "A stage light"], "A key term."),
     TF("Catharsis refers to an emotional release felt by the audience.", True, "Aristotle’s term."),
     MT("Match the term to the meaning.", [("Hubris", "Excessive pride"), ("Peripeteia", "Reversal of fortune"), ("Anagnorisis", "Recognition"), ("Tragicomedy", "Mixes tragic and comic elements")], "Terms."),
     M("Comedy typically", "Ends in a happy or hopeful resolution", ["Always ends in death", "Has no humour", "Has no characters"], "Typical pattern."),
     O("Explain the difference between tragedy and tragicomedy.", "Tragedy centres on a serious downfall with a sad outcome and arouses pity and fear. Tragicomedy blends serious themes with comic moments, so the audience laughs and feels sadness and the ending is mixed or ambiguous rather than purely catastrophic.", "Tragedy (1); tragicomedy (1); contrast (1); effect on audience (1)."),
     O("Using the original outline of the village headman (he ignores advice, sells communal land, loses trust and recognises his error too late), discuss whether he is responsible for his own downfall.", "He is largely responsible: he refuses advice out of pride (hubris) and makes the choice to sell. But circumstances, such as pressure from the stranger or lack of other income, may have influenced him. His recognition of his error suggests moral understanding, which invites pity as well as judgement. A balanced reading sees both responsibility and circumstances.", "Responsibility (2); circumstances (1); audience response (1).")],
    [("Pity and fear are linked with", "Tragedy", ["Farce", "Satire only", "Haiku"], "Aristotle’s idea."),
     ("A ‘tragic hero’ usually", "Suffers a downfall", ["Never changes", "Is always happy", "Is a narrator"], "A central character’s fall."),
     ("Farce relies on", "Exaggerated, chaotic situations", ["Quiet reflection", "Rhyme only", "Silence only"], "A kind of comedy."),
     ("Satire in comedy", "Criticises society through humour", ["Praises everyone", "Ends the play", "Is a stage prop"], "Humour with a point."),
     ("Modern tragedy often features", "Ordinary people", ["Only kings", "No people", "Only animals"], "Broadened focus.")],
    (table(["Feature", "Tragedy", "Comedy"], [["Ending", "Disaster", "Happy"], ["Hero", "Falls", "Ordinary"], ["Effect", "Pity and fear", "Laughter"]], 440, 13, 32),
     "Tragedy and comedy compared.", "A table comparing ending, hero and effect in tragedy and comedy."),
    [NOTE, "Aristotle’s terms (Poetics) are given in outline only: confirm the terms required by the syllabus."])

# ======================================================== ORAL AND ESSAYS
ch = p.chapter("oral-essay", "Oral tradition, context questions and essay planning")
L = lesson(ch, "oral-tradition", "Oral tradition and African storytelling",
    ["Describe forms of oral literature", "Explain functions and features of performance", "Compare oral and written literature"],
    [("definition", "Forms", "**Oral literature** is composed and passed on by speech and performance, often with music and dance. Forms include **folktales** (often with animal or trickster characters), **myths**, **legends**, **proverbs**, **riddles**, **praise poems**, **songs**, **epics** and **lullabies**. It exists in many African languages and is still alive."),
     ("retenir", "Functions and features", "Oral literature **entertains**, **teaches** values, **preserves history**, praises or criticises leaders and marks events. Features of performance: a storyteller who uses voice, gesture and pace, **call and response** with the audience, repetition, songs inside the tale, formulaic openings and closings, and adaptation to each audience."),
     ("retenir", "Oral and written", "Oral works change with each telling and depend on memory and audience; written works are fixed on the page and can be read alone. Writers may draw on oral forms, using proverbs, folk-tale structure, rhythm and storytelling voice. Neither form is superior: each has its own strengths."),
     ("attention", "Respect and care", "- Do not call oral literature ‘primitive’: it is sophisticated art.\n- Avoid generalising about ‘all Africa’: traditions differ by people and language.\n- Always cite the community or storyteller when using a real tale; here the examples are original.")],
    [("Example 1 — Analyse a folktale opening", "Original opening: ‘Listen, listen! Long ago, when the river still talked, there lived a tortoise who loved the drum more than his dinner.’ Identify oral features.",
      ["‘Listen, listen!’ is a call to the audience.", "‘Long ago’ is a formulaic opening.", "‘when the river still talked’ is fantasy/personification setting a magical world.", "The tortoise trickster-type character suggests a moral tale."], "Audience address, formulaic opening, fantasy and a trickster-type character."),
     ("Example 2 — Function of a proverb", "Original proverb: ‘A hand that hides the seed cannot complain of an empty field.’ Explain its function.",
      ["It uses a farming image to teach a moral lesson.", "It means that someone who withholds effort or resources cannot blame the result.", "Proverbs give short, memorable advice in speech."], "A short, vivid image teaching responsibility.")],
    [M("A trickster character is typically", "Clever and mischievous", ["Always a king", "Always silent", "Always a ghost"], "Common in folktales."),
     TF("Call and response is a feature of oral performance.", True, "The audience takes part."),
     MT("Match the form to its meaning.", [("Proverb", "Short saying with a lesson"), ("Riddle", "Puzzle in question form"), ("Praise poem", "Poem honouring a person"), ("Folktale", "Traditional story")], "Basic forms."),
     M("A function of oral literature is to", "Teach values and preserve history", ["Replace all writing", "Avoid audiences", "Prevent language"], "Core functions."),
     O("Give three ways in which a storyteller keeps an audience engaged.", "The storyteller can use voice, gesture and pace; ask questions and use call and response; include songs and repeated phrases; use humour and suspense; and adapt the tale to the audience.", "One mark per valid way, max 3."),
     O("Original tale in outline: a hare refuses to share his harvest, then asks neighbours for help in a drought and is refused. Write a paragraph on the moral and the oral devices you would use in telling it.", "The moral is that selfishness has consequences: those who refuse help cannot expect help. In telling the tale I would use repetition for each refusal, a refrain song the audience can join, vivid animal voices and a clear closing formula. Humour and a pause before the ending add suspense.", "Moral (1); devices (2); effect (1).")],
    [("Oral literature is passed on by", "Speech and performance", ["Printing only", "Email only", "Television only"], "Spoken tradition."),
     ("A praise poem", "Honours a person or group", ["Insults everyone", "Is a riddle", "Is a prose novel"], "Often performed."),
     ("Formulaic openings such as ‘Long ago…’", "Signal the start of a tale", ["End the tale", "Are a rhyme scheme", "Are stage directions"], "Conventional markers."),
     ("Oral tales", "Can change with each telling", ["Never change", "Are always written", "Are always silent"], "Depends on memory and audience."),
     ("Written literature differs from oral literature because it", "Is fixed on the page", ["Cannot be read", "Has no author", "Has no style"], "Fixed text.")],
    (table(["Form", "Purpose"], [["Folktale", "Teach and entertain"], ["Proverb", "Brief wisdom"], ["Praise poem", "Honour a leader"], ["Riddle", "Test wit"]], 440, 13, 32),
     "Forms of oral literature and their purposes.", "A table of four oral forms and their purposes."),
    [NOTE, "Oral forms discussed in general terms: choose local examples with community permission."])

L = lesson(ch, "context-questions", "Answering context questions",
    ["Explain what a context question asks", "Place an extract in the wider text and comment on its significance", "Use a structured model answer"],
    [("definition", "What is a context question?", "A **context question** gives an extract and asks you to explain what is happening, where it occurs in the text, its **significance** and how the writer uses language. You show that you know both the extract and the whole work. In this pack we practise with original extracts; with a set text you use your own reading."),
     ("methode", "A four-part answer", "1. **Locate:** who is speaking, where in the text, what has just happened. 2. **Explain** what the extract says or shows. 3. **Analyse** language, form or technique with short quotations. 4. **Link** to a theme, a character’s development or what follows. Keep the answer proportionate to the marks."),
     ("pieges", "Common mistakes", "- Retelling the whole plot.\n- Saying only ‘this shows the theme’ without explaining how.\n- Forgetting to locate the extract.\n- Quoting without comment.")],
    [("Example 1 — Plan an answer", "Original extract from an imaginary novel: ‘Ndi folded the scholarship letter and slid it into his schoolbag. At supper he spoke only about football.’ Question: What does this extract show about Ndi? (4 marks)",
      ["Locate: Ndi has just received a scholarship letter.", "Explain: he hides the letter and avoids the subject.", "Analyse: ‘slid’ and ‘spoke only about football’ suggest secrecy and avoidance.", "Link: he may fear leaving home or disappointing his family; this may anticipate conflict."], "He hides important news; his behaviour suggests worry or divided loyalties."),
     ("Example 2 — Write the answer", "Write a model four-mark answer for the extract above.",
      ["The extract shows Ndi concealing his scholarship letter from his family.", "The verb ‘slid’ suggests secrecy, and ‘spoke only about football’ shows he is avoiding the subject.", "This suggests that he is anxious about the opportunity, perhaps because it means leaving home.", "The detail builds tension about the news that will have to come out."], "A concise answer: location, explanation, language, significance.")],
    [M("A context question asks you to", "Explain an extract and link it to the whole text", ["Retell the whole plot", "Write a new story", "List all characters"], "It combines extract and context."),
     TF("In a context answer you should quote briefly and comment.", True, "Quotations support comments."),
     MT("Match each part of the answer to its purpose.", [("Locate", "Say where the extract comes from"), ("Explain", "Say what it shows"), ("Analyse", "Comment on language"), ("Link", "Relate to theme or plot")], "Four parts."),
     M("A good opening sentence for a context answer would", "State the situation and who is speaking", ["Be a long quotation", "Be about the author’s life only", "Ignore the extract"], "Orientation first."),
     O("Original extract: ‘The generator died. In the dark the family moved closer, and for once nobody reached for a phone.’ Write a short context-style comment on the effect of this moment.", "The power cut removes the usual distractions. ‘Moved closer’ suggests a rediscovered closeness, and ‘for once’ implies that they are normally absorbed by phones. The moment may be used to show the value of simple family togetherness.", "Situation (1); language (1); implication (1); link to theme (1)."),
     O("Original extract: ‘Auntie Mbong counted the notes twice and then once more, though the amount did not change.’ Explain what this reveals and how it might connect to the wider story.", "The repeated counting shows anxiety and a lack of money; she hopes the amount will somehow grow. It reveals the tension of limited resources and may point to a decision she has to make, such as postponing a purchase or asking for help. In the wider story this might link to themes of economic pressure and family responsibility.", "Meaning of repetition (1); emotion (1); link to theme/plot (2).")],
    [("‘Significance’ means", "Why the moment matters to the whole text", ["How long it is", "Where it is printed", "Its page number"], "Importance."),
     ("You should locate the extract by", "Saying what has just happened", ["Copying the title", "Guessing", "Skipping it"], "Give context."),
     ("A short quotation is", "Better than a long one", ["Worse than a long one", "Forbidden", "Required to be a page"], "Precise evidence."),
     ("Marks for a question suggest", "How much to write", ["The font", "The page limit", "Nothing"], "Allocate time."),
     ("The last step is to", "Link to theme or plot", ["Retell the story", "Add a new character", "Write a poem"], "Significance.")],
    (flow(["Locate: where and who", "Explain: what it shows", "Analyse: language and technique", "Link: theme, character, plot"], 440, "blue", 13, 320),
     "A four-part context answer.", "Four boxes: locate, explain, analyse and link."),
    [NOTE, "Extracts are original. For set texts, replace with extracts and local context from teachers."])

L = lesson(ch, "essay-planning", "Planning a critical essay",
    ["Unpack an essay question and write a thesis", "Plan paragraphs using point-evidence-explain-link", "Write an introduction and conclusion"],
    [("methode", "Unpack the question", "Underline the **command words** (discuss, how far, to what extent, compare) and the **key terms** (for example ‘presentation of women’). Decide your **line of argument** in one sentence (the **thesis**). Note 3–4 points that support it and one complication or alternative view."),
     ("retenir", "Paragraph structure", "Each paragraph: **Point** (topic sentence), **Evidence** (short quotation or reference), **Explanation** (how it proves the point, with technique), **Link** (back to the question). Use connectives to move the argument along (‘furthermore’, ‘however’, ‘this suggests’). Keep a balance between plot and analysis."),
     ("retenir", "Opening and ending", "The **introduction** answers the question directly and signals the line of argument; it does not retell the plot. The **conclusion** gives a reasoned judgement, ties the points together and avoids new evidence. Time: about 5 minutes planning, the rest writing and a final check."),
     ("pieges", "Frequent errors", "- Writing everything known about a text instead of answering the question.\n- Listing techniques without effects.\n- No judgement in the conclusion.\n- Unfinished essay: plan to finish.")],
    [("Example 1 — Write a thesis", "Question: ‘Discuss the importance of setting in a story of your choice.’ Write a thesis for an imaginary story set in a village during a drought.",
      ["Key terms: importance, setting.", "Thesis: the drought setting is not just a backdrop but drives the characters’ choices and symbolises their struggle.", "Plan: setting and mood; setting and conflict; setting and symbolism."], "A thesis linking setting to action and symbol."),
     ("Example 2 — Plan a paragraph", "Plan one paragraph for the thesis above: setting shaping choices.",
      ["Point: the drought forces the villagers to choose between staying and leaving.", "Evidence: short quotation about empty wells (imaginary).", "Explanation: the image of dry wells shows lack of resources and pushes characters towards difficult decisions.", "Link: so the setting directly shapes the plot."], "Point, evidence, explanation and link.")],
    [M("A thesis is", "Your main argument in one sentence", ["A quotation", "A plot summary", "A title"], "The line of argument."),
     TF("The introduction should retell the whole story.", False, "It should answer the question and outline the argument."),
     MT("Match the part of the paragraph to its role.", [("Point", "States the idea"), ("Evidence", "Quotation or reference"), ("Explanation", "Shows how it proves the point"), ("Link", "Returns to the question")], "PEEL."),
     M("A strong conclusion", "Gives a reasoned judgement", ["Introduces new evidence", "Repeats the plot", "Ends mid-sentence"], "Judgement and synthesis."),
     O("Question: ‘How far is the opening of a novel important in establishing its themes?’ Write a one-sentence thesis and list two points.", "Thesis: the opening is vital because it sets the tone and introduces the central tensions, though themes develop later. Points: (1) setting and atmosphere in the opening hint at themes; (2) introduction of a character’s conflict or desire.", "Thesis (1); two relevant points (2); line to the question (1)."),
     O("Plan (not a full essay) for: ‘Compare the ways in which two poems present nature.’ Use two imaginary poems: one in which nature is peaceful, one in which it is threatening.", "Introduction: both poems use nature to express human feelings but differ in tone. Para 1: imagery (soft, gentle verbs versus violent verbs). Para 2: form and sound (regular rhyme versus broken rhythm). Para 3: speaker’s attitude (comfort versus fear). Conclusion: the contrast shows nature as a mirror of human emotion.", "Thesis (1); structured comparison (2); links to technique (1).")],
    [("A topic sentence states", "The main point of the paragraph", ["The conclusion", "A quotation only", "The title"], "Point."),
     ("The command word ‘discuss’ asks for", "Several viewpoints and a judgement", ["A definition", "A list", "A copy"], "Balanced argument."),
     ("Planning time should be about", "5 minutes", ["None", "An hour", "The whole exam"], "Short plan."),
     ("Connectives help", "Move the argument along", ["Hide evidence", "Replace quotations", "Make essays shorter"], "Such as ‘however’."),
     ("A conclusion should not", "Introduce completely new evidence", ["Summarise", "Judge", "Link to the question"], "New points belong in the body.")],
    (flow(["Unpack question; underline key words", "Thesis and 3–4 points", "Write paragraphs: point, evidence, explanation, link", "Conclude with a judgement"], 440, "blue", 13, 340),
     "Essay planning steps.", "Four boxes in a chain from unpacking the question to a final judgement."),
    [NOTE, "Command-word wording can differ between boards: check the GCE Board’s guidance."])

p.write()
