"""Cameroun : histoire et institutions (royaumes précoloniaux, période allemande, mandat et tutelle, nationalisme,
indépendance, réunification, constitutions, institutions, symboles, organisations régionales, diplomatie).
Faits rédigés à la main, statut `review` : aucun titulaire de poste actuel n'est cité."""
from .cult_kit import rows, table, theme

theme("cm-hist2", "Cameroun : histoire et institutions (2e fiche)",
      "Comparer avec un manuel d'histoire du Cameroun (programme MINESEC), la Constitution du 18 janvier 1996, "
      "une encyclopédie (Larousse, Britannica) et les sites des organisations citées (ONU, CEMAC, BEAC, CEEAC, Commonwealth).")

# ------------------------------------------------------------------ peuplement et royaumes précoloniaux
rows("cm-hist2", "CM", "Histoire du Cameroun", [
    (1, "Quel mot portugais, qui désigne des crevettes, est à l'origine du nom « Cameroun » ?", "Camarões",
     ["Caminhos", "Camelos", "Cabeças", "Canoas", "Camisas"],
     "Les navigateurs portugais ont appelé l'estuaire du Wouri « Rio dos Camarões », la rivière des crevettes."),
    (1, "Quel nom les Allemands donnaient-ils à leur colonie du Cameroun ?", "Kamerun",
     ["Kameroon", "Kamerunia", "Kamerland", "Deutsch-Kamerun-Land", "Kamerounien"],
     "Le Kamerun fut un protectorat allemand de 1884 à 1916."),
    (3, "Quel peuple de chasseurs-cueilleurs est considéré comme l'un des plus anciens occupants des forêts du Sud et de l'Est du Cameroun ?",
     "Les Baka", ["Les Peuls", "Les Bamoun", "Les Mafa", "Les Douala", "Les Toupouri"],
     "Les Baka, souvent rangés parmi les peuples dits « pygmées », vivent dans la forêt équatoriale depuis des temps très anciens."),
    (4, "Dans quelle région la grande expansion des peuples de langues bantoues a-t-elle probablement commencé, il y a plusieurs millénaires ?",
     "À la frontière entre le Cameroun et le Nigeria",
     ["Autour des Grands Lacs", "Dans le bassin du Zambèze", "Dans le désert du Kalahari", "Sur la côte de l'océan Indien", "Dans la vallée du Nil"],
     "Les linguistes situent le foyer d'origine des langues bantoues dans les hautes terres du Cameroun et du sud-est du Nigeria."),
    (3, "Quelle civilisation ancienne, connue pour ses statuettes en terre cuite, s'est développée au sud du lac Tchad, dans l'actuel Extrême-Nord ?",
     "La civilisation sao", ["La civilisation nok", "La civilisation toucouleur", "La civilisation ashanti", "La civilisation zoulou", "La civilisation swahilie"],
     "Les Sao ont laissé des figurines de terre cuite et des objets de bronze, retrouvés notamment à Mdaga et à Logone-Birni."),
    (4, "Quelle cité, sur le fleuve Logone, fut la capitale du royaume kotoko ?", "Logone-Birni",
     ["Maroua", "Mora", "Kousséri", "Yagoua", "Waza"],
     "Logone-Birni, entourée de remparts en terre, était le centre politique des Kotoko."),
    (3, "Dans quelle région du Cameroun se situent les anciens royaumes kotoko ?", "L'Extrême-Nord",
     ["Le Sud-Ouest", "Le Littoral", "L'Adamaoua", "Le Centre", "L'Est"],
     "Les cités kotoko s'étendent le long du Logone et du Chari, près du lac Tchad."),
    (4, "Quel ancien royaume, centré près de Mora, était établi dans les monts Mandara ?", "Le royaume du Wandala (Mandara)",
     ["Le royaume du Bamoun", "Le royaume du Kanem", "Le royaume de Kongo", "Le royaume d'Abomey", "Le royaume du Baguirmi"],
     "Le Wandala, aussi appelé royaume du Mandara, a dominé le nord des monts du même nom pendant plusieurs siècles."),
    (3, "Quel est le nom du fondateur légendaire du royaume bamoun ?", "Nchare Yen",
     ["Njoya", "Mbombo Njoya", "Ibrahim Njoya", "Mfon", "Fonyonga"],
     "Nchare Yen aurait fondé le royaume bamoun, avec Foumban pour capitale, vers la fin du XIVe siècle."),
    (2, "Quelle ville est la capitale du royaume bamoun ?", "Foumban",
     ["Bafoussam", "Bamenda", "Dschang", "Garoua", "Ebolowa"],
     "Foumban, dans le département du Noun, abrite le palais royal et un musée."),
    (4, "En quelle année Ibrahim Njoya, roi des Bamoun, est-il mort en exil à Yaoundé ?", "1933",
     ["1914", "1923", "1945", "1960", "1901"],
     "Njoya, écarté du pouvoir par l'administration française en 1931, est mort à Yaoundé en 1933."),
    (3, "Quel roi bamoun a fait construire le grand palais de Foumban, achevé dans les années 1920 ?", "Njoya",
     ["Nchare Yen", "Mbouombouo", "Mama", "Mfon", "Ngouoh"],
     "Le palais de Njoya, de style mêlé, accueille aujourd'hui un musée d'objets royaux."),
    (3, "Quel système d'écriture le roi Njoya a-t-il fait mettre au point pour la langue bamoun ?", "Le Shü-mom",
     ["Le N'ko", "Le tifinagh", "Le ge'ez", "Le vaï", "Le nsibidi"],
     "Le Shü-mom a été créé à partir de 1896 avec l'aide de collaborateurs du roi ; il a évolué en plusieurs versions."),
    (2, "Comment appelle-t-on le chef d'une chefferie traditionnelle bamiléké ?", "Un fo (ou fon)",
     ["Un lamido", "Un sultan-émir", "Un nana", "Un ardo", "Un pharaon"],
     "Dans les hautes terres de l'Ouest, les chefs traditionnels portent le titre de fo ou fon."),
    (2, "Quel peuple est traditionnellement organisé en chefferies comme Bandjoun, Baham et Bangangté ?", "Les Bamiléké",
     ["Les Peuls", "Les Kotoko", "Les Béti", "Les Baka", "Les Mousgoum"],
     "Les chefferies de l'Ouest sont connues pour leurs cases ornées de sculptures sur bois."),
    (4, "Quelle chefferie de l'Ouest est célèbre pour sa grande case à toit pointu et à poteaux sculptés, aujourd'hui site culturel ?", "Bandjoun",
     ["Foumban", "Bafut", "Rey-Bouba", "Kumbo", "Dizangué"],
     "La chefferie de Bandjoun, dans les hautes terres de l'Ouest, abrite un ensemble de cases sculptées."),
    (3, "Quel titre portent les chefs des anciens royaumes de la région de Bafut et de Nso, dans le Nord-Ouest ?", "Fon",
     ["Lamido", "Sultan-roi", "Mfumu", "Ardo", "Mbombo"],
     "Dans les Grassfields (Nord-Ouest et Ouest), le chef traditionnel s'appelle fon ou fo."),
    (4, "Quel chef peul a lancé, à partir de 1806, le mouvement qui a fondé l'émirat de l'Adamaoua (Fombina) ?", "Modibo Adama",
     ["Usman dan Fodio", "Rabih", "Lamy", "Hamman Gabdo", "Ibrahim Njoya"],
     "Modibo Adama, envoyé par Usman dan Fodio, a bâti l'émirat dont les lamidats du Nord Cameroun sont issus."),
    (2, "Quel titre portent les chefs des lamidats peuls du nord du Cameroun ?", "Lamido",
     ["Fon", "Nana", "Mbombo", "Pharaon", "Mfumu"],
     "Un lamido dirige un lamidat, par exemple celui de Ngaoundéré ou de Rey-Bouba."),
    (4, "Quel lamidat du département du Mayo-Rey, dans la région du Nord, est l'un des plus importants du Cameroun ?", "Rey-Bouba",
     ["Bafut", "Foumban", "Bandjoun", "Douala", "Édéa"],
     "Le lamidat de Rey-Bouba est une chefferie peule influente du Nord."),
    (3, "Dans quelle ville de l'Adamaoua siège un grand lamidat peul ?", "Ngaoundéré",
     ["Bertoua", "Kribi", "Bafang", "Limbé", "Mbalmayo"],
     "Ngaoundéré est à la fois chef-lieu de l'Adamaoua et siège d'un lamidat."),
    (5, "En quelle année l'explorateur allemand Heinrich Barth a-t-il atteint l'Adamaoua, au nord du Cameroun ?", "1851",
     ["1801", "1884", "1912", "1830", "1869"],
     "Barth fut le premier Européen à rapporter une description de la région de Yola et de l'Adamaoua."),
    (2, "Quel peuple de la côte, dont le nom a été donné à une grande ville portuaire, a signé le traité de 1884 avec les Allemands ?", "Les Douala",
     ["Les Mafa", "Les Gbaya", "Les Tikar", "Les Baka", "Les Mousgoum"],
     "Les chefs douala, dont Bell et Akwa, ont signé le traité de 1884 qui ouvrit la période allemande."),
    (2, "À quelle reine britannique les chefs douala ont-ils écrit pour demander une protection avant l'arrivée des Allemands ?", "Victoria",
     ["Élisabeth Ire", "Anne", "Marie Stuart", "Élisabeth II", "Charlotte"],
     "Plusieurs lettres des chefs de la côte demandèrent la protection britannique, sans résultat avant 1884."),
])

# ------------------------------------------------------------------ explorations, missions, Kamerun allemand
rows("cm-hist2", "CM", "Histoire du Cameroun", [
    (3, "En quel mois de 1884 le traité germano-douala a-t-il été signé ?", "En juillet",
     ["En janvier", "En mars", "En octobre", "En décembre", "En septembre"],
     "Le traité fut signé en juillet 1884 ; Nachtigal proclama ensuite le protectorat allemand."),
    (3, "Quels chefs douala sont les principaux signataires du traité avec les Allemands en 1884 ?", "Bell et Akwa",
     ["Njoya et Mbombo", "Bell et Njoya", "Akwa et Ngando", "Manga et Ekwala", "Samba et Dominik"],
     "Les rois Bell et Akwa dirigeaient deux grands groupes douala sur l'estuaire du Wouri."),
    (5, "Sur les rives de quelle baie le missionnaire Alfred Saker a-t-il fondé Victoria (Limbé) en 1858 ?",
     "La baie d'Ambas", ["La baie de Rio del Rey", "La baie de Biafra", "La baie de Guinée", "La baie de Corisco", "La baie de Mondoni"],
     "Alfred Saker, missionnaire baptiste, fonda Victoria en 1858 ; elle prit le nom de Limbé en 1982."),
    (4, "Quelle ville a été fondée en 1858 par le missionnaire Alfred Saker et rebaptisée Limbé en 1982 ?", "Victoria",
     ["Buea", "Kribi", "Tiko", "Mamfé", "Idenau"],
     "Le premier nom de Limbé rappelait la reine britannique."),
    (4, "Quel missionnaire jamaïcain est arrivé à Douala en 1843 pour fonder une mission baptiste ?", "Joseph Merrick",
     ["Alfred Saker", "David Livingstone", "Gustav Nachtigal", "Eugen Zintgraff", "Hans Dominik"],
     "Joseph Merrick a appris le douala et traduit des textes dans cette langue."),
    (4, "Qui fut le premier gouverneur du Kamerun allemand, à partir de 1885 ?", "Julius von Soden",
     ["Jesko von Puttkamer", "Gustav Nachtigal", "Hans Dominik", "Karl Ebermaier", "Eugen Zintgraff"],
     "Julius von Soden dirigea la colonie jusqu'en 1891 environ."),
    (4, "Quel gouverneur allemand a dirigé le Kamerun de 1895 à 1907 ?", "Jesko von Puttkamer",
     ["Julius von Soden", "Karl Ebermaier", "Otto von Bismarck", "Rudolf Duala Manga Bell", "Martin-Paul Samba"],
     "Jesko von Puttkamer a gouverné la colonie douze ans, jusqu'en 1907."),
    (4, "Quel Allemand a fondé en 1889 le poste qui est à l'origine de la ville de Yaoundé ?", "Georg Zenker",
     ["Gustav Nachtigal", "Hans Dominik", "Eugen Zintgraff", "Heinrich Barth", "Julius von Soden"],
     "Georg Zenker, un naturaliste allemand, installa la station de Jaunde en 1889."),
    (3, "Quel nom les Allemands donnaient-ils à la ville de Yaoundé ?", "Jaunde",
     ["Kamerunstadt", "Bonn", "Neukamerun", "Kribi-Hafen"],
     "« Jaunde » est la transcription allemande du nom de la ville."),
    (3, "Dans quelle ville du pied du mont Cameroun les Allemands ont-ils installé le siège de leur gouvernement au début des années 1900 ?", "Buea",
     ["Douala", "Edéa", "Kribi", "Garoua", "Bertoua"],
     "Buea, plus fraîche que la côte, fut choisie comme résidence du gouverneur."),
    (4, "Quelle ligne ferroviaire allemande, ouverte en 1911, reliait Douala à Nkongsamba ?", "Le Nordbahn (chemin de fer du Nord)",
     ["Le Transcamerounais", "Le Mittellandbahn", "Le Bénoué-Express", "Le Kribi-Express", "Le Tchad-Express"],
     "Le Nordbahn desservait les plantations et les cultures commerciales du Moungo."),
    (4, "Quel accord franco-allemand de 1911 a permis à l'Allemagne d'agrandir le Kamerun vers le Congo et l'Oubangui ?", "L'accord Maroc-Congo",
     ["Le traité de Berlin", "Le traité d'Utrecht", "Le pacte de Fachoda", "L'accord Sykes-Picot", "La convention de Brazzaville"],
     "En échange de la liberté d'action de la France au Maroc, l'Allemagne reçut le « Neukamerun »."),
    (3, "Comment appelle-t-on l'agrandissement du Kamerun obtenu par l'Allemagne en 1911 ?", "Le Neukamerun (Nouveau Cameroun)",
     ["Le Grand Kamerun", "Le Kamerun-Süd", "L'Afrique-Orientale allemande", "Le Togo-Cameroun", "L'Ober-Kamerun"],
     "Le Neukamerun comprenait des terres cédées par la France."),
    (5, "En quelle année le chef douala Rudolf Duala Manga Bell est-il pendu par les autorités allemandes avec son secrétaire Ngosso Din ?", "1914",
     ["1884", "1911", "1916", "1919", "1900"],
     "Les deux hommes ont été exécutés le 8 août 1914 pour avoir résisté à l'expropriation."),
    (4, "Quel quartier de Douala était concerné par la politique allemande d'expropriation à laquelle Rudolf Duala Manga Bell s'opposait ?", "Joss",
     ["Bonanjo", "Akwa-Nord", "Bonapriso", "Makepe", "Deïdo-Est"],
     "Les Allemands voulaient séparer les quartiers européens et africains en déplaçant les Douala."),
    (5, "Quel chef bulu, qui avait servi dans l'armée coloniale allemande, a été exécuté en 1914 à Ebolowa ?", "Martin-Paul Samba",
     ["Rudolf Duala Manga Bell", "Ngosso Din", "Ruben Um Nyobè", "Charles Atangana", "Mbombo Njoya"],
     "Martin-Paul Samba, accusé de conspiration, fut exécuté en août 1914."),
    (4, "Quel chef ewondo, proche des Allemands puis des Français, a été chef supérieur des Ewondo et des Bané ?", "Charles Atangana",
     ["Martin-Paul Samba", "Rudolf Duala Manga Bell", "Nchare Yen", "Hamman Gabdo", "Njoya"],
     "Charles Atangana fut chef supérieur à Yaoundé de l'époque allemande jusqu'aux années 1930."),
    (3, "Quel chef de guerre soudanais, battu à Kousséri en 1900, avait fondé un empire autour du lac Tchad ?", "Rabih",
     ["Samory Touré", "El Hadj Omar", "Usman dan Fodio", "Béhanzin", "Lat Dior"],
     "Rabih az-Zubayr fut tué lors de la bataille de Kousséri, face aux troupes françaises."),
    (5, "En quelle année la bataille de Kousséri, où Rabih et le commandant Lamy ont trouvé la mort, a-t-elle eu lieu ?", "1900",
     ["1884", "1893", "1905", "1914", "1889"],
     "La bataille de Kousséri s'est déroulée le 22 avril 1900."),
    (3, "Quelle ville africaine a d'abord été appelée Fort-Lamy en hommage à un officier tué à Kousséri ?", "N'Djamena",
     ["Bangui", "Brazzaville", "Libreville", "Yaoundé", "Niamey"],
     "N'Djamena a pris son nom actuel en 1973."),
])

# ------------------------------------------------------------------ Première Guerre mondiale, mandat, tutelle
rows("cm-hist2", "CM", "Histoire du Cameroun", [
    (1, "Quelle guerre mondiale a mis fin à la présence allemande au Cameroun ?", "La Première Guerre mondiale",
     ["La Seconde Guerre mondiale", "La guerre de Crimée", "La guerre de Sécession", "La guerre froide", "La guerre franco-prussienne"],
     "Les troupes alliées (françaises, britanniques et belges) ont chassé les Allemands entre 1914 et 1916."),
    (3, "Quelle grande ville du Kamerun les Alliés ont-ils prise le 27 septembre 1914 ?", "Douala",
     ["Yaoundé", "Garoua", "Buea", "Ebolowa", "Bamenda"],
     "La chute de Douala, port principal, fut une étape clé de la campagne du Cameroun."),
    (5, "Quel fort du nord du Cameroun fut le dernier bastion allemand, tombé en février 1916 ?", "Mora",
     ["Garoua", "Maroua", "Ngaoundéré", "Kousséri", "Foumban"],
     "La garnison allemande de Mora, assiégée, se rendit en février 1916."),
    (4, "Vers quelle colonie voisine les troupes allemandes se sont-elles réfugiées début 1916 ?", "La Guinée espagnole (Rio Muni)",
     ["Le Gabon français", "Le Nigeria britannique", "Le Congo belge", "L'Angola portugais", "Le Tchad"],
     "Neutre, la colonie espagnole accueillit et interna les soldats allemands et leurs auxiliaires."),
    (3, "Quelle expression désigne le partage du Cameroun entre deux puissances alliées après 1916 ?", "Un condominium franco-britannique",
     ["Une fédération germano-belge", "Un protectorat portugais", "Une république associée", "Un royaume uni", "Un grand-duché"],
     "Dès 1916, la France et le Royaume-Uni se partagent le territoire ; le partage est confirmé en 1919."),
    (3, "Quelle part du Cameroun est tombée sous administration française après 1919 ?", "La plus grande partie du territoire",
     ["Seulement la zone côtière", "Seulement le Nord", "Seulement les îles", "Aucune partie", "Seulement l'Ouest"],
     "Le Cameroun français (Cameroun oriental) représentait environ quatre cinquièmes du territoire."),
    (3, "Comment appelait-on les deux zones du Cameroun britannique ?", "Northern Cameroons et Southern Cameroons",
     ["East Cameroon et West Cameroon", "Upper Cameroons et Lower Cameroons", "Coastal Cameroons et Inland Cameroons", "Neukamerun et Altkamerun", "Cameroon-Nord et Cameroon-Sud"],
     "Les deux régions étaient gérées depuis le Nigeria voisin."),
    (3, "Depuis quel pays voisin le Cameroun britannique était-il administré ?", "Le Nigeria",
     ["Le Ghana", "Le Gabon", "Le Soudan", "Le Tchad", "La Sierra Leone"],
     "Le Cameroun britannique était rattaché administrativement à la colonie et au protectorat du Nigeria."),
    (5, "Quelle catégorie de mandat de la Société des Nations a été attribuée au Cameroun en 1922 ?", "Un mandat de type B",
     ["Un mandat de type A", "Un mandat de type C", "Un mandat de type D", "Un mandat de type Z", "Un protectorat de type E"],
     "Les mandats B concernaient des territoires d'Afrique centrale et occidentale, comme le Cameroun et le Togo."),
    (2, "Quelle organisation a remplacé la Société des Nations après 1945 ?", "L'Organisation des Nations unies",
     ["L'Organisation de l'unité africaine", "L'Union africaine", "Le Commonwealth", "La Francophonie", "L'Union européenne"],
     "Le mandat devint tutelle ONU en 1946."),
    (2, "Quelle organisation a mis le Cameroun sous tutelle de la France et du Royaume-Uni en 1946 ?", "L'ONU",
     ["La SDN", "L'OTAN", "La CEMAC", "L'UA", "L'OUA"],
     "L'ONU a approuvé les accords de tutelle en décembre 1946."),
    (4, "En quelle année la France a-t-elle promulgué la loi-cadre dite « Defferre » qui élargit l'autonomie des territoires d'outre-mer ?", "1956",
     ["1946", "1950", "1960", "1936", "1970"],
     "La loi-cadre de 1956 a donné plus de pouvoir aux assemblées locales."),
])

# ------------------------------------------------------------------ nationalisme, UPC, figures décédées
rows("cm-hist2", "CM", "Histoire du Cameroun", [
    (3, "Dans quelle ville l'Union des populations du Cameroun a-t-elle été fondée en 1948 ?", "Douala",
     ["Yaoundé", "Buea", "Maroua", "Ebolowa", "Bafoussam"],
     "L'UPC est née à Douala le 10 avril 1948."),
    (4, "Quel jour et mois de 1948 l'UPC a-t-elle été créée ?", "Le 10 avril",
     ["Le 1er janvier", "Le 20 mai", "Le 11 février", "Le 12 juillet", "Le 1er octobre"],
     "Ruben Um Nyobè en devint rapidement le secrétaire général."),
    (3, "Quelle fonction Ruben Um Nyobè a-t-il occupée à la tête de l'UPC ?", "Secrétaire général",
     ["Président de la République", "Gouverneur", "Premier ministre", "Maire de Douala", "Ministre des Finances"],
     "Il prit la tête du parti dès 1948 et parla à l'ONU en 1952."),
    (3, "Devant quelle institution Ruben Um Nyobè a-t-il plaidé pour l'unification et l'indépendance en 1952 ?", "L'ONU (Conseil de tutelle)",
     ["La Société des Nations", "L'Assemblée nationale française", "Le Commonwealth", "L'Union africaine", "La Ligue arabe"],
     "Um Nyobè s'est exprimé à New York devant la Quatrième Commission de l'ONU."),
    (3, "Quel est le surnom donné à Ruben Um Nyobè en langue bassa ?", "Mpodol",
     ["Mbombo", "Ngondo", "Lamido", "Mfumu", "Nkukuma"],
     "Mpodol signifie « celui qui porte la parole des siens »."),
    (3, "En quelle année Ruben Um Nyobè a-t-il été tué par l'armée française ?", "1958",
     ["1948", "1955", "1960", "1971", "1962"],
     "Il fut abattu le 13 septembre 1958 près de Boumnyébel."),
    (5, "Dans quelle région du Cameroun Ruben Um Nyobè est-il né et a-t-il été tué ?", "Dans le pays bassa",
     ["Dans le pays bamoun", "Dans le Nord peul", "Dans le pays kotoko", "Dans l'Adamaoua", "Dans le Sud-Ouest"],
     "Le maquis de l'UPC se situait dans la Sanaga-Maritime, pays bassa."),
    (4, "En quelle année l'UPC a-t-elle été interdite par l'administration française ?", "1955",
     ["1948", "1946", "1960", "1952", "1965"],
     "L'UPC fut interdite en juillet 1955 après des troubles."),
    (3, "Dans quelle ville suisse Félix-Roland Moumié est-il mort empoisonné en 1960 ?", "Genève",
     ["Berne", "Zurich", "Lausanne", "Bâle", "Lugano"],
     "Moumié est mort le 3 novembre 1960, victime d'un empoisonnement au thallium."),
    (5, "Quel poison a tué Félix-Roland Moumié ?", "Le thallium",
     ["Le cyanure", "L'arsenic", "Le mercure", "La strychnine", "Le plomb"],
     "L'enquête a identifié le thallium dans l'organisme du dirigeant de l'UPC."),
    (4, "Quel dirigeant de l'UPC a été exécuté en 1971 à Bafoussam ?", "Ernest Ouandié",
     ["Ruben Um Nyobè", "Félix-Roland Moumié", "Abel Kingué", "Martin-Paul Samba", "André-Marie Mbida"],
     "Ernest Ouandié a été fusillé le 15 janvier 1971 à Bafoussam."),
    (4, "Quel dirigeant a été le premier Premier ministre du Cameroun sous tutelle française, en 1957 ?", "André-Marie Mbida",
     ["Ahmadou Ahidjo", "Ruben Um Nyobè", "Félix-Roland Moumié", "Charles Assalé", "Ernest Ouandié"],
     "André-Marie Mbida dirigea le premier gouvernement camerounais en 1957, avant Ahmadou Ahidjo."),
    (3, "Quel dirigeant a succédé à André-Marie Mbida comme Premier ministre en 1958 ?", "Ahmadou Ahidjo",
     ["Ruben Um Nyobè", "John Ngu Foncha", "Félix-Roland Moumié", "Ernest Ouandié", "Charles Atangana"],
     "Ahidjo devint Premier ministre en février 1958."),
    (3, "Dans quelle ville est né Ahmadou Ahidjo, premier président du Cameroun ?", "Garoua",
     ["Douala", "Yaoundé", "Foumban", "Ebolowa", "Bamenda"],
     "Ahmadou Ahidjo est né à Garoua en 1924."),
    (3, "En quelle année Ahmadou Ahidjo a-t-il démissionné de la présidence ?", "1982",
     ["1960", "1972", "1975", "1984", "1990"],
     "Ahidjo a annoncé son départ le 4 novembre 1982."),
    (4, "Dans quel pays Ahmadou Ahidjo est-il mort en 1989 ?", "Au Sénégal",
     ["En France", "Au Gabon", "Au Nigeria", "En Algérie", "Au Maroc"],
     "Ahidjo est mort à Dakar, en exil, le 30 novembre 1989."),
])

# ------------------------------------------------------------------ indépendance, réunification, États fédéral puis unitaire
rows("cm-hist2", "CM", "Histoire du Cameroun", [
    (1, "En quelle année le Cameroun français est-il devenu indépendant ?", "1960",
     ["1945", "1957", "1961", "1972", "1984"],
     "L'indépendance a été proclamée le 1er janvier 1960."),
    (2, "Quel jour de 1960 le Cameroun français a-t-il acquis l'indépendance ?", "Le 1er janvier",
     ["Le 20 mai", "Le 11 février", "Le 1er mai", "Le 1er octobre", "Le 25 décembre"],
     "Le 1er janvier 1960 marque la fin de la tutelle française."),
    (3, "Quelle institution de l'ONU a voté en 1959 la fin de la tutelle française sur le Cameroun ?", "L'Assemblée générale",
     ["Le Conseil de sécurité", "La Cour internationale de justice", "Le Conseil économique et social", "L'UNESCO", "L'OMS"],
     "L'Assemblée générale a mis fin à la tutelle le 13 mars 1959, avec effet au 1er janvier 1960."),
    (5, "En quel mois de 1960 Ahmadou Ahidjo a-t-il été élu président de la République ?", "En mai",
     ["En janvier", "En mars", "En août", "En octobre", "En décembre"],
     "L'Assemblée l'a élu le 5 mai 1960."),
    (1, "Quelle ville est devenue la capitale du Cameroun indépendant ?", "Yaoundé",
     ["Douala", "Buea", "Garoua", "Bafoussam", "Limbé"],
     "Yaoundé est la capitale politique ; Douala est la capitale économique."),
    (3, "Quelle partie de l'ancien Cameroun britannique a choisi de rejoindre le Nigeria en 1961 ?", "Le Northern Cameroons",
     ["Le Southern Cameroons", "Le Neukamerun", "Le Cameroun français", "Le Wandala", "L'Adamaoua français"],
     "Le Nord britannique a voté pour le rattachement au Nigeria."),
    (2, "Quelle partie de l'ancien Cameroun britannique a choisi de rejoindre le Cameroun en 1961 ?", "Le Southern Cameroons",
     ["Le Northern Cameroons", "Le Neukamerun", "Le Tchad", "Le Bornou", "Le Nord-Mandara"],
     "Le plébiscite du 11 février 1961 a donné la majorité à l'unification avec le Cameroun."),
    (3, "Quel dirigeant du Southern Cameroons, fondateur du KNDP, a défendu l'union avec le Cameroun ?", "John Ngu Foncha",
     ["Emmanuel Endeley", "Solomon Tandeng Muna", "Augustine Ngom Jua", "Ahmadou Ahidjo", "André-Marie Mbida"],
     "Foncha est devenu vice-président de la République fédérale en 1961."),
    (5, "Quelle conférence de juillet 1961 a préparé la future constitution fédérale ?", "La conférence de Foumban",
     ["La conférence de Berlin", "La conférence de Brazzaville", "La conférence d'Addis-Abeba", "La conférence de Yaoundé", "La conférence de Buea"],
     "Des délégués du Cameroun et du Southern Cameroons s'y sont rencontrés du 17 au 21 juillet 1961."),
    (3, "Quelle ville est devenue la capitale du Cameroun occidental (West Cameroon) pendant la fédération ?", "Buea",
     ["Bamenda", "Limbé", "Kumba", "Mamfé", "Douala"],
     "Buea, au pied du mont Cameroun, était la capitale de l'État fédéré anglophone."),
    (3, "Quels États formaient la République fédérale du Cameroun de 1961 à 1972 ?", "Le Cameroun oriental et le Cameroun occidental",
     ["Le Nord et le Sud", "Le Littoral et l'Adamaoua", "Le Cameroun français et le Nigeria", "Le Sud-Ouest et le Nord-Ouest seuls", "L'Est et le Centre"],
     "Chaque État fédéré avait son gouvernement et son assemblée."),
    (3, "Quel jour de 1961 la République fédérale du Cameroun est-elle officiellement née ?", "Le 1er octobre",
     ["Le 1er janvier", "Le 11 février", "Le 20 mai", "Le 17 juillet", "Le 12 juillet"],
     "Le 1er octobre 1961 marque la réunification du Cameroun."),
    (3, "Quel événement du 11 février 1961 est commémoré chaque 11 février ?", "Le plébiscite du Southern Cameroons",
     ["La proclamation de l'indépendance", "La fondation de l'UPC", "L'élection d'Ahidjo", "La fin de la Première Guerre mondiale", "La signature du traité de 1884"],
     "Le 11 février est la fête de la Jeunesse, établie par la suite."),
    (3, "Que commémore la fête nationale du 20 mai ?", "Le référendum de 1972 instaurant l'État unitaire",
     ["La proclamation de l'indépendance", "Le traité germano-douala", "Le plébiscite de 1961", "La création de l'UPC", "Le début de la tutelle"],
     "Depuis 1972, la fête nationale rappelle le passage de la fédération à l'État unitaire."),
    (2, "Quel jour du calendrier est la fête nationale du Cameroun ?", "Le 20 mai",
     ["Le 1er janvier", "Le 11 février", "Le 1er octobre", "Le 12 juillet", "Le 15 août"],
     "Le 20 mai 1972, les Camerounais ont approuvé la fin de la fédération."),
    (3, "Quel nom l'État a-t-il porté de 1972 à 1984 ?", "République unie du Cameroun",
     ["République fédérale du Cameroun", "Royaume uni du Cameroun", "République démocratique du Cameroun", "République populaire du Cameroun", "Union camerounaise"],
     "Le nom « République du Cameroun » est revenu en 1984."),
    (4, "Combien de provinces comptait le Cameroun au moment de l'État unitaire de 1972 ?", "7",
     ["4", "5", "8", "10", "12"],
     "Le pays est passé à dix provinces en 1983, puis ces provinces sont devenues des régions."),
    (4, "Quelles provinces ont été créées en 1983 en divisant le Nord et le Centre-Sud ?", "L'Adamaoua, l'Extrême-Nord, le Centre et le Sud",
     ["Le Littoral et le Nord-Ouest", "L'Ouest et le Sud-Ouest", "L'Est et le Nord-Ouest", "Le Littoral et l'Ouest", "La Lékié et le Mbam"],
     "La réforme a fait passer le pays de sept à dix unités."),
    (4, "Quel parti unique est né en 1966 de la fusion de plusieurs formations ?", "L'Union nationale camerounaise (UNC)",
     ["Le RDPC", "L'UPC", "Le KNDP", "Le SDF", "L'Union camerounaise des travailleurs"],
     "L'UNC fut créée en 1966 ; elle prit le nom de RDPC en 1985."),
    (3, "Dans quelle ville le congrès de 1985 a-t-il rebaptisé l'UNC en RDPC ?", "Bamenda",
     ["Yaoundé", "Douala", "Bafoussam", "Garoua", "Buea"],
     "Le congrès de Bamenda a adopté le nom de Rassemblement démocratique du peuple camerounais."),
])

# ------------------------------------------------------------------ Southern Cameroons, fédération, compléments
rows("cm-hist2", "CM", "Histoire du Cameroun", [
    (5, "Quel parti John Ngu Foncha a-t-il fondé en 1955 ?", "Le KNDP",
     ["Le CPNC", "Le RDPC", "L'UPC", "Le SDF", "L'UNC"],
     "Le Kamerun National Democratic Party gouverna le Southern Cameroons à partir de 1959."),
    (5, "Quel dirigeant, rival de Foncha, fut Premier ministre du Southern Cameroons de 1954 à 1959 ?", "Emmanuel Endeley",
     ["John Ngu Foncha", "Solomon Tandeng Muna", "Augustine Ngom Jua", "Ahmadou Ahidjo", "Ernest Ouandié"],
     "Endeley, favorable à une association avec le Nigeria, fut battu par Foncha aux élections de 1959."),
    (4, "Quel texte a aboli le travail forcé dans les colonies françaises en 1946 ?", "La loi Houphouët-Boigny",
     ["La loi Lamine Guèye", "La loi Defferre", "Le code de l'indigénat de 1946", "La loi Jules Ferry", "La loi Cadre Foccart"],
     "Cette loi du 11 avril 1946 s'appliqua aussi au Cameroun sous tutelle française."),
    (5, "En quelle année la ligne de chemin de fer Douala-Yaoundé a-t-elle été achevée sous administration française ?", "1927",
     ["1911", "1905", "1950", "1974", "1960"],
     "Le « Transcamerounais » a ensuite été prolongé jusqu'à Ngaoundéré."),
    (4, "En quelle année le chemin de fer a-t-il atteint Ngaoundéré ?", "1974",
     ["1927", "1911", "1960", "1990", "1938"],
     "Cette extension permit de relier le Nord à la côte par le rail."),
    (4, "Quel explorateur allemand a atteint les hautes terres de Bali et de Bafut vers 1889-1891 ?", "Eugen Zintgraff",
     ["Heinrich Barth", "Gustav Nachtigal", "David Livingstone", "Georg Zenker", "Mungo Park"],
     "Zintgraff explora les Grassfields de l'Ouest et du Nord-Ouest."),
    (4, "Quel grand rassemblement culturel bamoun a lieu à Foumban ?", "Le Nguon",
     ["Le Ngondo", "Le Lela", "Le Medumba", "Le Mbapé", "Le Tabaski"],
     "Le Nguon rassemble les Bamoun autour du roi."),
    (5, "Quel texte de 1975, signé à Maroua, a tracé une frontière maritime entre le Cameroun et le Nigeria ?", "La déclaration de Maroua",
     ["La déclaration de Yaoundé", "L'accord de Calabar", "Le traité de Fort-Lamy", "La charte de Lagos", "La convention de Garoua"],
     "La déclaration de Maroua, signée le 1er juin 1975, concernait la frontière maritime."),
    (1, "Quelle langue le Cameroun a-t-il ajoutée au français comme langue officielle, notamment à partir de 1961 ?", "L'anglais",
     ["L'allemand", "Le portugais", "L'espagnol", "L'arabe", "Le bamoun"],
     "L'État reconnaît deux langues officielles d'égale valeur."),
    (2, "Quelle ville est surnommée « la ville aux sept collines » ?", "Yaoundé",
     ["Douala", "Bamenda", "Garoua", "Kribi", "Maroua"],
     "Yaoundé est bâtie sur plusieurs collines de la région du Centre."),
    (2, "Quelle ville est considérée comme la capitale économique du Cameroun ?", "Douala",
     ["Yaoundé", "Buea", "Bafoussam", "Garoua", "Ngaoundéré"],
     "Douala abrite le premier port du pays."),
])

# ------------------------------------------------------------------ chronologie : lequel est arrivé en premier ?
rows("cm-hist2", "CM", "Histoire du Cameroun", [
    (2, "Parmi ces événements, lequel est le plus ancien ?", "Le traité germano-douala",
     ["La création de l'UPC", "L'indépendance du Cameroun français", "Le plébiscite du Southern Cameroons", "Le référendum de 1972"],
     "Le traité date de 1884, bien avant les autres événements (1948, 1960, 1961, 1972)."),
    (3, "Parmi ces événements, lequel est le plus récent ?", "Le référendum de 1972",
     ["La création de l'UPC", "L'indépendance du Cameroun français", "Le plébiscite du Southern Cameroons", "La mise sous tutelle de l'ONU"],
     "Le référendum du 20 mai 1972 vient après les événements de 1946, 1948, 1960 et 1961."),
    (3, "Lequel de ces événements s'est produit en premier ?", "Le mandat de la Société des Nations",
     ["La tutelle de l'ONU", "La naissance de l'UPC", "La loi-cadre Defferre", "L'indépendance"],
     "Mandat 1922, tutelle 1946, UPC 1948, loi-cadre 1956, indépendance 1960."),
    (3, "Lequel de ces événements s'est produit en dernier ?", "L'installation du Sénat",
     ["Le référendum de 1972", "La révision constitutionnelle de 1996", "Le multipartisme de 1990", "L'indépendance de 1960"],
     "Le Sénat a été installé en 2013, longtemps après la Constitution de 1996 qui le prévoyait."),
    (2, "Quel est l'ordre chronologique correct ?", "Indépendance puis réunification",
     ["Réunification puis indépendance", "Tutelle ONU puis mandat SDN", "Fédération puis traité germano-douala", "État unitaire puis fédération"],
     "L'indépendance (1960) précède la réunification (1961)."),
    (2, "Quel événement vient juste après la fin de la tutelle française au Cameroun ?", "La réunification avec le Southern Cameroons",
     ["La Première Guerre mondiale", "La création de l'UPC", "Le traité de Versailles", "Le mandat SDN"],
     "L'indépendance de 1960 est suivie en 1961 par la réunification."),
])

# ------------------------------------------------------------------ constitutions, États, institutions
rows("cm-hist2", "CM", "Institutions du Cameroun", [
    (1, "Comment appelle-t-on la loi fondamentale d'un pays ?", "La Constitution",
     ["Le décret", "L'ordonnance", "Le règlement intérieur", "Le code civil", "L'arrêté municipal"],
     "La Constitution fixe l'organisation des pouvoirs publics."),
    (3, "Quelle Constitution a créé les régions décentralisées, le Sénat et le Conseil constitutionnel ?", "Celle du 18 janvier 1996",
     ["Celle du 1er octobre 1961", "Celle du 4 mars 1960", "Celle du 20 mai 1972", "Celle du 11 février 1961", "Celle du 1er janvier 1960"],
     "La loi du 18 janvier 1996 a profondément révisé la Constitution de 1972."),
    (4, "Quel texte du 2 juin 1972 a organisé l'État unitaire ?", "La Constitution de la République unie du Cameroun",
     ["La charte de la Fédération", "Le code de la tutelle", "Le statut de l'État associé", "La déclaration d'indépendance", "La loi-cadre"],
     "Elle fut adoptée après le référendum du 20 mai 1972."),
    (2, "Quel type d'État la Constitution actuelle dit-elle que le Cameroun est ?", "Un État unitaire décentralisé",
     ["Une fédération", "Une confédération", "Un empire", "Une monarchie", "Un protectorat"],
     "Le premier article de la Constitution de 1996 qualifie le pays d'État unitaire décentralisé."),
    (2, "Combien de régions compte le Cameroun ?", "10",
     ["7", "8", "9", "12", "15"],
     "Les dix régions ont remplacé les provinces, dont le nom a changé en 2008."),
    (5, "En quelle année les provinces du Cameroun ont-elles été officiellement rebaptisées régions ?", "2008",
     ["1972", "1983", "1996", "2013", "2018"],
     "La réforme est liée à la décentralisation voulue par la Constitution de 1996."),
    (1, "Dans quelle ville siège l'Assemblée nationale du Cameroun ?", "Yaoundé",
     ["Douala", "Buea", "Bafoussam", "Garoua", "Limbé"],
     "Le Parlement a son siège dans la capitale."),
    (2, "De combien de chambres le Parlement camerounais est-il composé ?", "Deux",
     ["Une", "Trois", "Quatre", "Cinq", "Aucune"],
     "Il comprend l'Assemblée nationale et le Sénat."),
    (4, "Combien de sénateurs chaque région envoie-t-elle au Sénat ?", "10",
     ["5", "7", "12", "15", "20"],
     "Chaque région compte dix sénateurs, dont sept élus et trois nommés."),
    (4, "En quelle année les premières élections sénatoriales ont-elles eu lieu au Cameroun ?", "2013",
     ["1996", "2001", "2008", "2018", "2020"],
     "Le Sénat, prévu par la Constitution de 1996, n'a été installé qu'en 2013."),
    (4, "Qui élit les sénateurs élus ?", "Des conseillers municipaux",
     ["Les élèves", "Les pasteurs", "Les chefs d'État étrangers", "Les juges de paix", "Les ministres"],
     "Les sénateurs élus le sont au suffrage indirect, par des conseillers municipaux."),
    (3, "Quelle institution contrôle la constitutionnalité des lois et des élections ?", "Le Conseil constitutionnel",
     ["Le Sénat", "L'Assemblée nationale", "La Cour des comptes de l'Union africaine", "La Commission de la CEMAC", "Le Conseil économique et social"],
     "Prévu en 1996, le Conseil constitutionnel n'a été mis en place qu'en 2018."),
    (5, "En quelle année le Conseil constitutionnel du Cameroun a-t-il été installé ?", "2018",
     ["1996", "2001", "2008", "2013", "2020"],
     "Il a siégé pour la première fois en février 2018."),
    (3, "Comment s'appelle la plus haute juridiction de l'ordre judiciaire au Cameroun ?", "La Cour suprême",
     ["Le tribunal de première instance", "La cour d'appel du Littoral", "Le tribunal criminel spécial", "La justice de paix", "La chambre des notaires"],
     "La Cour suprême siège à Yaoundé."),
    (3, "Quels deux systèmes juridiques coexistent au Cameroun ?", "Le droit civil d'origine française et la common law",
     ["Le droit romain et le droit scandinave", "Le droit allemand et le droit portugais", "Le droit coutumier et le droit nordique", "Le droit civil et le droit chinois", "Le droit canon et le droit anglais"],
     "Le pays est dit bijuridique, héritage des tutelles française et britannique."),
    (4, "Quel traité signé en 1993 à Port-Louis a créé un droit commun des affaires en Afrique, dont le Cameroun est membre ?", "Le traité de l'OHADA",
     ["Le traité de Rome", "Le traité de Lomé", "Le traité d'Abuja", "Le traité de Maastricht", "Le traité de Brazzaville"],
     "L'OHADA harmonise le droit des affaires dans plusieurs pays d'Afrique."),
    (3, "Quels types de collectivités territoriales décentralisées existent au Cameroun ?", "Les régions et les communes",
     ["Les villages et les clans", "Les provinces et les départements", "Les lamidats et les chefferies", "Les ministères et les cours", "Les ports et les gares"],
     "Les collectivités territoriales décentralisées sont les régions et les communes."),
    (2, "Qui dirige une commune au Cameroun ?", "Un maire",
     ["Un préfet", "Un gouverneur", "Un sénateur", "Un sous-préfet", "Un lamido"],
     "Le maire est élu par le conseil municipal."),
    (5, "En quelle année ont eu lieu les premières élections régionales au Cameroun ?", "2020",
     ["1996", "2007", "2013", "2018", "2024"],
     "Les conseils régionaux ont été élus pour la première fois le 6 décembre 2020."),
    (4, "Quel mode de scrutin est prévu pour l'élection présidentielle camerounaise ?", "Un tour, à la majorité simple",
     ["Deux tours", "Tirage au sort", "Vote par les chefs", "Vote du Sénat seul", "Vote du conseil des ministres"],
     "L'élection a lieu au suffrage universel direct, à un tour."),
    (2, "Quel mot désigne le choix des citoyens par vote direct sur un texte, comme en 1972 ?", "Un référendum",
     ["Un plébiscite royal", "Un décret", "Un manifeste", "Un recensement", "Une ordonnance"],
     "Le référendum du 20 mai 1972 a institué l'État unitaire."),
    (3, "Quelle institution administre un département au Cameroun ?", "La préfecture",
     ["Le gouvernorat", "La mairie", "Le lamidat", "L'ambassade", "La sous-préfecture"],
     "Un préfet dirige le département ; le sous-préfet, l'arrondissement."),
])

# ------------------------------------------------------------------ symboles nationaux et fêtes
rows("cm-hist2", "CM", "Symboles et fêtes du Cameroun", [
    (2, "Quelle est la devise du Cameroun en anglais ?", "Peace - Work - Fatherland",
     ["Unity - Work - Progress", "Freedom - Equality - Brotherhood", "God - Country - Liberty", "Peace - Faith - Union", "Work - Family - Nation"],
     "La devise « Paix - Travail - Patrie » figure sur les armoiries."),
    (3, "Quel instrument de justice figure sur les armoiries du Cameroun ?", "Une balance",
     ["Une clepsydre", "Un sablier", "Une horloge", "Une boussole", "Un compas"],
     "Les armoiries comprennent une balance, une épée et une carte du pays."),
    (1, "Quelle disposition ont les couleurs du drapeau du Cameroun ?", "Trois bandes verticales",
     ["Trois bandes horizontales", "Deux bandes en diagonale", "Une croix centrale", "Un cercle sur fond uni", "Quatre bandes verticales"],
     "Vert, rouge, jaune de gauche à droite, avec une étoile sur la bande rouge."),
    (4, "En quelle année le drapeau actuel, avec une seule étoile jaune au centre, a-t-il été adopté ?", "1975",
     ["1960", "1961", "1972", "1984", "1996"],
     "Le drapeau fédéral de 1961 comptait deux étoiles ; après 1972, une seule étoile fut conservée."),
    (3, "Combien d'étoiles comptait le drapeau de la République fédérale en 1961 ?", "2",
     ["1", "3", "4", "5", "0"],
     "Les deux étoiles symbolisaient les deux États fédérés, le Cameroun oriental et le Cameroun occidental."),
    (3, "Que symbolise l'étoile jaune du drapeau camerounais ?", "L'unité du pays",
     ["La richesse du pétrole", "Le soleil du désert", "Les dix régions", "La monarchie", "Le colonialisme"],
     "L'étoile d'or rappelle l'unité nationale."),
    (3, "Quel autre nom l'hymne national du Cameroun porte-t-il ?", "Chant de ralliement",
     ["Hymne à la joie", "Chant des partisans", "Chant du départ", "Hymne de la liberté", "Chant des Bamiléké"],
     "Le « Chant de ralliement » est le titre sous lequel on désigne souvent l'hymne."),
    (1, "Quelle fête est célébrée le 1er mai ?", "La fête du Travail",
     ["La fête nationale", "La fête de la Jeunesse", "La fête de l'Indépendance", "La fête des Mères", "La fête de l'Assomption"],
     "Le 1er mai est un jour férié dans de nombreux pays, dont le Cameroun."),
    (2, "Quelle fête religieuse, le 15 août, est un jour férié au Cameroun ?", "L'Assomption",
     ["La Pentecôte", "Noël", "L'Épiphanie", "La Toussaint", "La Saint-Jean"],
     "L'Assomption est célébrée chaque 15 août."),
    (3, "Quel jour férié, le 1er janvier, rappelle aussi l'indépendance du Cameroun français ?", "Le Jour de l'An",
     ["La fête du Travail", "La fête nationale", "La fête de la Jeunesse", "L'Assomption", "Noël"],
     "La proclamation de l'indépendance eut lieu le 1er janvier 1960."),
])

# ------------------------------------------------------------------ organisations régionales et diplomatie
rows("cm-hist2", "CM", "Organisations et diplomatie", [
    (3, "Quelle organisation a succédé à l'UDEAC avec le traité de 1994 ?", "La CEMAC",
     ["La CEEAC", "La CEDEAO", "L'UEMOA", "La SADC", "Le COMESA"],
     "L'UDEAC, créée en 1964, a cédé la place à la CEMAC (traité de N'Djamena, 1994, effectif en 1999)."),
    (3, "Quel pays est membre de la CEMAC ?", "Le Gabon",
     ["Le Nigeria", "Le Niger", "Le Rwanda", "L'Angola", "Le Bénin"],
     "Cameroun, Centrafrique, Congo, Gabon, Guinée équatoriale et Tchad composent la CEMAC."),
    (4, "Quel pays est membre de la CEEAC sans faire partie de la CEMAC ?", "L'Angola",
     ["Le Tchad", "Le Gabon", "Le Congo", "Le Cameroun", "La Guinée équatoriale"],
     "La CEEAC regroupe plus de pays que la CEMAC, par exemple l'Angola et la RDC."),
    (5, "Quelle organisation regroupe le Cameroun, le Nigeria, le Niger et le Tchad autour d'un grand lac partagé ?", "La Commission du bassin du lac Tchad",
     ["La CEDEAO", "La SADC", "L'OPEP", "La CEEAC", "L'IGAD"],
     "Fondée en 1964, elle a son siège à N'Djamena."),
    (2, "En quelle année le Cameroun a-t-il rejoint l'ONU ?", "1960",
     ["1945", "1957", "1961", "1972", "1984"],
     "Le Cameroun a été admis à l'ONU le 20 septembre 1960."),
    (5, "Quel autre pays a rejoint le Commonwealth en 1995, en même temps que le Cameroun ?", "Le Mozambique",
     ["Le Nigeria", "Le Ghana", "La Tanzanie", "L'Ouganda", "Le Kenya"],
     "Le sommet d'Auckland de novembre 1995 a admis le Cameroun et le Mozambique."),
    (3, "Dans quelle ville a été signée la première convention d'association entre la CEE et des États africains en 1963 ?", "Yaoundé",
     ["Lomé", "Dakar", "Paris", "Bruxelles", "Abuja"],
     "La convention de Yaoundé est signée le 20 juillet 1963 à Yaoundé."),
    (5, "Quelle ville a accueilli le sommet de l'OUA de 1996 ?", "Yaoundé",
     ["Addis-Abeba", "Lomé", "Tunis", "Harare", "Alger"],
     "Le sommet de l'Organisation de l'unité africaine s'est tenu en juillet 1996 à Yaoundé."),
    (5, "Quelle juridiction internationale a tranché en 2002 le litige frontalier entre le Cameroun et le Nigeria ?", "La Cour internationale de justice",
     ["La Cour pénale internationale", "La Cour africaine des droits de l'homme", "Le Tribunal pour le Rwanda", "L'OMC", "La Cour de la CEDEAO"],
     "La Cour internationale de justice a rendu son arrêt le 10 octobre 2002."),
    (3, "Quelle presqu'île de l'Atlantique, disputée avec le Nigeria, est revenue au Cameroun ?", "Bakassi",
     ["Kribi", "Ambas", "Rio del Rey", "Manoka", "Ndian"],
     "Bakassi a été remise au Cameroun en 2008 après l'arrêt de la Cour internationale de justice."),
    (5, "En quelle année la souveraineté du Cameroun sur Bakassi a-t-elle été effectivement transférée ?", "2008",
     ["1975", "1994", "2002", "2006", "2012"],
     "Le Nigeria a retiré son administration le 14 août 2008."),
    (2, "Dans quelle ville néerlandaise siège la Cour internationale de justice ?", "La Haye",
     ["Amsterdam", "Rotterdam", "Bruxelles", "Genève", "Berne"],
     "La CIJ, organe judiciaire de l'ONU, est installée au Palais de la Paix."),

])

# ------------------------------------------------------------------ compléments : gouverneurs, guerre, Union française, plébiscite
rows("cm-hist2", "CM", "Histoire du Cameroun", [
    (5, "Quel gouverneur a dirigé le Kamerun juste après Jesko von Puttkamer, de 1907 à 1910 ?", "Theodor Seitz",
     ["Julius von Soden", "Karl Ebermaier", "Gustav Nachtigal", "Otto Gleim", "Eugen Zintgraff"],
     "Theodor Seitz a gouverné le Kamerun avant de partir pour le Sud-Ouest africain allemand."),
    (5, "Quel fut le dernier gouverneur allemand du Kamerun, en poste jusqu'en 1916 ?", "Karl Ebermaier",
     ["Theodor Seitz", "Julius von Soden", "Jesko von Puttkamer", "Hans Dominik", "Gustav Nachtigal"],
     "Karl Ebermaier gouverna le territoire de 1912 à la défaite allemande."),
    (5, "Quel armateur et commerçant de Hambourg, très actif à Douala, a poussé Berlin à agir au Cameroun en 1884 ?", "Adolph Woermann",
     ["Otto von Bismarck", "Gustav Nachtigal", "Julius von Soden", "Carl Peters", "Alfred Krupp"],
     "La maison Woermann commerçait sur la côte de Guinée et soutenait l'idée d'un protectorat."),
    (5, "Quelle déclaration de juillet 1919 a fixé la frontière entre les parties française et britannique du Cameroun ?", "La déclaration Milner-Simon",
     ["La déclaration Balfour", "La déclaration Defferre", "La déclaration de Maroua", "La déclaration d'Atlantic City", "La déclaration Wilson"],
     "Alfred Milner (Royaume-Uni) et Henry Simon (France) ont signé le partage le 10 juillet 1919."),
    (4, "En quelle année le Cameroun, sous mandat français, s'est-il rallié à la France libre du général de Gaulle ?", "1940",
     ["1914", "1936", "1945", "1958", "1960"],
     "Fin août 1940, Leclerc est arrivé à Douala, qui s'est rallié à la France libre."),
    (3, "Quel officier de la France libre est arrivé à Douala en août 1940 ?", "Philippe Leclerc de Hauteclocque",
     ["Pierre Savorgnan de Brazza", "Hubert Lyautey", "Joseph Gallieni", "Henri Gouraud", "Louis Faidherbe"],
     "Leclerc contribua au ralliement du Cameroun à la France libre."),
    (4, "Dans quel ensemble politique, créé en 1946, le Cameroun sous tutelle française était-il associé à la France ?", "L'Union française",
     ["La Communauté européenne", "L'Union africaine", "L'Empire colonial allemand", "Le Commonwealth", "L'Alliance atlantique"],
     "L'Union française fut établie par la Constitution de la IVe République, en 1946."),
    (3, "Quel choix était proposé aux électeurs du Southern Cameroons lors du plébiscite de 1961 ?", "Rejoindre le Nigeria ou rejoindre la République du Cameroun",
     ["Rejoindre le Tchad ou le Gabon", "Rester colonie britannique ou devenir allemand", "Devenir un royaume ou une république", "Rejoindre le Ghana ou le Bénin", "Entrer dans le Commonwealth ou en sortir"],
     "L'option d'un État indépendant séparé n'était pas proposée."),
    (3, "Quelle organisation a supervisé le plébiscite de 1961 dans le Cameroun britannique ?", "L'ONU",
     ["L'OUA", "La CEMAC", "Le Commonwealth", "L'UNESCO", "La Banque mondiale"],
     "Le plébiscite du 11 février 1961 a eu lieu sous l'égide des Nations unies."),
    (5, "Quel parti Ahmadou Ahidjo a-t-il fondé en 1958 ?", "L'Union camerounaise (UC)",
     ["Le KNDP", "L'UPC", "Le RDPC", "Le SDF", "Le Mouvement démocratique camerounais"],
     "L'UC fut le principal parti du Cameroun oriental à l'indépendance."),
    (5, "En quelle année la réforme qui a créé six universités d'État au Cameroun a-t-elle été lancée ?", "1993",
     ["1962", "1972", "1984", "2001", "2010"],
     "Les universités de Yaoundé I et II, Douala, Dschang, Ngaoundéré et Buea sont issues de la réforme de 1993."),
    (3, "Quelle ville anglophone a reçu en 1993 une université d'État ?", "Buea",
     ["Bamenda", "Limbé", "Kumba", "Mamfé", "Kribi"],
     "L'université de Buea fait partie des six universités d'État créées en 1993."),
])

# ------------------------------------------------------------------ sigles et organisations
rows("cm-hist2", "CM", "Organisations et diplomatie", [
    (3, "Que signifie CEEAC ?", "Communauté économique des États de l'Afrique centrale",
     ["Conseil économique des États d'Afrique centrale", "Commission environnementale de l'Afrique centrale", "Coalition économique des États d'Afrique côtière", "Comité européen de l'Afrique centrale"],
     "La CEEAC rassemble plusieurs pays d'Afrique centrale."),
    (4, "Que signifie UDEAC ?", "Union douanière et économique de l'Afrique centrale",
     ["Union des diplomates et experts de l'Afrique centrale", "Union des droits et échanges de l'Afrique centrale", "Union douanière des États d'Afrique de l'Est", "Union démocratique des États africains"],
     "L'UDEAC a précédé la CEMAC."),
    (4, "Que signifie OHADA ?", "Organisation pour l'harmonisation en Afrique du droit des affaires",
     ["Organisation des hommes d'affaires d'Afrique", "Office pour l'habitat et le développement en Afrique", "Observatoire de l'huile et de l'agriculture", "Organisation d'harmonisation des armées africaines"],
     "L'OHADA vise un droit des affaires commun à ses États membres."),
    (4, "Que signifie BDEAC ?", "Banque de développement des États de l'Afrique centrale",
     ["Banque des dépôts des États d'Afrique côtière", "Banque de défense de l'Europe et de l'Afrique centrale", "Bureau de développement des États du Cameroun", "Banque des devises de l'Europe centrale"],
     "La BDEAC finance le développement des pays de la CEMAC."),
    (5, "Que signifie COMIFAC ?", "Commission des forêts d'Afrique centrale",
     ["Commission des finances d'Afrique centrale", "Comité de l'industrie forestière d'Afrique du Congo", "Conseil des mines et forêts d'Afrique centrale", "Comité minier de la CEMAC"],
     "La COMIFAC coordonne la gestion des forêts du bassin du Congo."),
    (5, "Que signifie COBAC ?", "Commission bancaire de l'Afrique centrale",
     ["Conseil bancaire de l'Afrique centrale", "Comité de la banque d'Afrique du Cameroun", "Commission du bois d'Afrique centrale", "Centre bancaire de l'Afrique commune"],
     "La COBAC supervise les banques de la zone CEMAC."),
    (3, "Que signifie RDPC ?", "Rassemblement démocratique du peuple camerounais",
     ["Régime démocratique du parti camerounais", "Rassemblement des députés du Cameroun", "Rencontre du développement du peuple camerounais", "Réunion des partis camerounais"],
     "Le RDPC a pris la suite de l'UNC en 1985."),
    (5, "Que signifie KNDP ?", "Kamerun National Democratic Party",
     ["Kamerun National Defence Party", "King's National Democratic Party", "Kumba National Development Plan", "Kamerun New Democratic Platform"],
     "Fondé en 1955, le KNDP était le parti de John Ngu Foncha."),
    (4, "Dans quelle capitale africaine l'ancêtre de l'Organisation internationale de la Francophonie a-t-il été fondé en 1970 ?", "Niamey",
     ["Dakar", "Abidjan", "Yaoundé", "Tunis", "Kigali"],
     "L'Agence de coopération culturelle et technique est née à Niamey, au Niger."),
    (3, "Dans quelle ville se trouve le siège de l'Organisation internationale de la Francophonie ?", "Paris",
     ["Bruxelles", "Montréal", "Genève", "Dakar", "Kinshasa"],
     "L'OIF a son siège à Paris et regroupe de nombreux États et gouvernements."),
    (3, "Dans quelle ville se trouve le siège du Commonwealth ?", "Londres",
     ["Ottawa", "Canberra", "Nairobi", "New Delhi", "Auckland"],
     "Le secrétariat du Commonwealth est installé à Marlborough House, à Londres."),
])

# ------------------------------------------------------------------ mandats et titres
rows("cm-hist2", "CM", "Institutions du Cameroun", [
    (1, "Comment appelle-t-on les membres de l'Assemblée nationale ?", "Les députés",
     ["Les sénateurs", "Les préfets", "Les gouverneurs", "Les juges", "Les maires"],
     "L'Assemblée nationale est composée de députés élus."),
    (3, "Quelle est la durée normale du mandat d'un député au Cameroun ?", "5 ans",
     ["3 ans", "4 ans", "6 ans", "7 ans", "10 ans"],
     "Le mandat est de cinq ans, selon la Constitution."),
    (3, "Quelle est la durée normale du mandat d'un sénateur ?", "5 ans",
     ["3 ans", "4 ans", "7 ans", "9 ans", "10 ans"],
     "Le mandat sénatorial est de cinq ans."),
    (3, "Qui nomme les gouverneurs de région au Cameroun ?", "Le président de la République",
     ["Les maires", "Les sénateurs", "Les électeurs", "Le Conseil constitutionnel", "Les chefs traditionnels"],
     "Les gouverneurs représentent l'État dans les régions."),
])

# ------------------------------------------------------------------ tableaux de faits
table("cm-hist2", "CM", "Institutions du Cameroun", [
    ("la première Constitution du Cameroun indépendant", "1960", 3),
    ("la Constitution de la République fédérale du Cameroun", "1961", 3),
    ("la Constitution de l'État unitaire (République unie du Cameroun)", "1972", 3),
    ("la grande révision constitutionnelle qui prévoit le Sénat et les régions", "1996", 3),
    ("le Code général des collectivités territoriales décentralisées", "2019", 5),
], "En quelle année a été adopté(e) {a} ?", "Quel texte camerounais date de {b} ?", diff=3,
      expl="{a} : {b}.", extra_b=("1958", "1966", "1984", "1990", "2008"), extra_a=("l'ordonnance sur le multipartisme", "la loi sur les lamidats"))

table("cm-hist2", "CM", "Organisations et diplomatie", [
    ("la BEAC", "Yaoundé", 3),
    ("la CEEAC", "Libreville", 4),
    ("la BDEAC", "Brazzaville", 4),
    ("la Commission du bassin du lac Tchad", "N'Djamena", 5),
], "Dans quelle ville se trouve le siège de {a} ?", "Quelle organisation régionale a son siège à {b} ?", diff=4,
      expl="Le siège de {a} est à {b}.", extra_b=("Bangui", "Douala", "Abuja", "Malabo"), extra_a=("la CEDEAO", "l'UEMOA"))

table("cm-hist2", "CM", "Organisations et diplomatie", [
    ("la BEAC (convention de 1972)", "1972", 4),
    ("la CEMAC (traité de N'Djamena)", "1994", 4),
    ("l'OHADA (traité de Port-Louis)", "1993", 4),
    ("la Commission du bassin du lac Tchad", "1964", 5),
    ("la Convention de Yaoundé (association avec la CEE)", "1963", 5),
], "En quelle année a été créée ou signée {a} ?", None, diff=4, expl="{a} : {b}.",
      extra_b=("1960", "1975", "1983", "1990", "2002"))

table("cm-hist2", "CM", "Histoire du Cameroun", [
    ("le lamidat de Ngaoundéré", "l'Adamaoua", 3),
    ("le lamidat de Banyo", "l'Adamaoua", 4),
    ("le lamidat de Tibati", "l'Adamaoua", 4),
    ("le lamidat de Rey-Bouba", "le Nord", 4),
    ("le royaume bamoun de Foumban", "l'Ouest", 2),
    ("la chefferie de Bandjoun", "l'Ouest", 3),
    ("la chefferie de Baham", "l'Ouest", 4),
    ("la chefferie de Bangangté", "l'Ouest", 3),
    ("la chefferie de Bafut", "le Nord-Ouest", 3),
    ("le royaume nso de Kumbo", "le Nord-Ouest", 4),
    ("la cité kotoko de Logone-Birni", "l'Extrême-Nord", 4),
    ("la ville de Mora, ancien centre du royaume du Wandala", "l'Extrême-Nord", 4),
], "Dans quelle région du Cameroun se situe {a} ?", None, diff=3, expl="{a} se trouve dans {b}.",
      extra_b=("le Littoral", "le Sud-Ouest", "l'Est", "le Sud", "le Centre"))

table("cm-hist2", "CM", "Histoire du Cameroun", [
    ("Gustav Nachtigal", "l'explorateur allemand qui a proclamé le protectorat de 1884", 2),
    ("Rudolf Duala Manga Bell", "le chef douala pendu par les Allemands en 1914", 3),
    ("Ruben Um Nyobè", "le secrétaire général de l'UPC tué en 1958", 3),
    ("Félix-Roland Moumié", "le dirigeant de l'UPC mort empoisonné à Genève en 1960", 4),
    ("Ahmadou Ahidjo", "le premier président du Cameroun indépendant", 2),
    ("John Ngu Foncha", "le chef du KNDP devenu vice-président de la fédération en 1961", 4),
    ("André-Marie Mbida", "le premier Premier ministre du Cameroun sous tutelle, en 1957", 4),
    ("Charles Atangana", "le chef supérieur des Ewondo sous les Allemands puis les Français", 5),
    ("Rabih", "le chef de guerre vaincu à Kousséri en 1900", 4),
    ("Modibo Adama", "le fondateur de l'émirat peul de l'Adamaoua", 4),
    ("Joseph Merrick", "le missionnaire jamaïcain arrivé à Douala en 1843", 5),
    ("Ibrahim Njoya", "le roi bamoun créateur de l'écriture Shü-mom", 3),
], "Quel est le rôle historique de {a} ?", "Quel personnage est décrit ainsi : {b} ?", diff=3, expl="{a} est {b}.",
      extra_a=("Samory Touré", "Pierre Savorgnan de Brazza", "Léopold Sédar Senghor"))

table("cm-hist2", "CM", "Histoire du Cameroun", [
    ("la fusion des partis donnant naissance à l'UNC", "1966", 4),
    ("le congrès de Bamenda qui crée le RDPC", "1985", 4),
    ("la création de dix provinces à partir de sept", "1983", 5),
    ("l'exécution d'Ernest Ouandié à Bafoussam", "1971", 5),
    ("la mort d'Ahmadou Ahidjo à Dakar", "1989", 4),
    ("l'interdiction de l'UPC par l'administration française", "1955", 4),
    ("la conférence constitutionnelle de Foumban", "1961", 4),
    ("la loi Houphouët-Boigny abolissant le travail forcé", "1946", 4),
    ("le ralliement du Cameroun à la France libre", "1940", 4),
    ("l'accord franco-allemand dit Maroc-Congo", "1911", 4),
    ("l'arrêt de la CIJ sur la frontière Cameroun-Nigeria", "2002", 5),
    ("la déclaration de Maroua sur la frontière maritime", "1975", 5),
    ("la fondation de Victoria (Limbé) par Alfred Saker", "1858", 5),
    ("la création du poste de Yaoundé par Georg Zenker", "1889", 5),
], "En quelle année a eu lieu ou a été signé(e) : {a} ?", None, diff=4, expl="{a} : {b}.",
      extra_b=("1884", "1900", "1914", "1922", "1948", "1960", "1972", "1990", "1996", "2008"))

# ------------------------------------------------------------------ vocabulaire d'histoire et d'instruction civique
rows("cm-hist2", "CM", "Histoire et institutions : vocabulaire", [
    (1, "Que veut dire « devenir indépendant » pour un pays ?", "Se gouverner soi-même, sans dépendre d'un autre État",
     ["Être dirigé par une puissance étrangère", "Changer de capitale", "Adopter une nouvelle monnaie seulement", "Entrer en guerre contre ses voisins"],
     "Le Cameroun français est devenu indépendant le 1er janvier 1960."),
    (2, "Qu'est-ce qu'un protectorat ?", "Un territoire placé sous le contrôle d'une puissance étrangère qui prétend le « protéger »",
     ["Un parc naturel", "Une région sans gouvernement", "Un pays qui gouverne ses voisins", "Une alliance militaire de villages"],
     "Le Kamerun fut un protectorat allemand de 1884 à 1916."),
    (2, "Qu'est-ce qu'une colonie ?", "Un territoire dominé et administré par un autre pays",
     ["Un groupe d'oiseaux migrateurs", "Un quartier d'une capitale", "Un pays membre de l'ONU", "Une ancienne région indépendante"],
     "Avant 1960, le Cameroun fut un territoire dominé par des puissances européennes."),
    (3, "Qu'est-ce qu'un plébiscite ?", "Un vote où les habitants se prononcent sur le sort politique d'un territoire",
     ["Une loi votée par le Sénat", "Un traité signé entre deux rois", "Une fête traditionnelle", "Un décret du gouverneur"],
     "Le 11 février 1961, les habitants du Southern Cameroons ont voté lors d'un plébiscite."),
    (3, "Qu'est-ce que la réunification du Cameroun ?", "Le rattachement du Southern Cameroons au Cameroun en 1961",
     ["La fusion du Cameroun et du Nigeria", "La fin de la guerre de 1914", "Le retour des Allemands", "L'union avec le Tchad"],
     "Elle a donné naissance à la République fédérale du Cameroun le 1er octobre 1961."),
    (3, "Qu'est-ce qu'un État fédéral ?", "Un État composé de plusieurs États fédérés qui gardent une part d'autonomie",
     ["Un État dirigé par un seul roi", "Un État sans gouvernement central", "Un État qui n'a pas de lois", "Un État sans frontières"],
     "Le Cameroun fut un État fédéral de 1961 à 1972."),
    (3, "Qu'est-ce qu'un État unitaire ?", "Un État où le pouvoir est organisé à partir d'un seul centre politique",
     ["Un État composé de plusieurs États autonomes", "Un État sans frontières", "Un État dirigé par deux présidents", "Un empire de plusieurs royaumes"],
     "Le Cameroun est un État unitaire depuis 1972."),
    (3, "Que signifie « décentraliser » ?", "Confier des pouvoirs à des collectivités locales élues",
     ["Déplacer la capitale", "Supprimer les lois", "Fermer les frontières", "Interdire les partis"],
     "La Constitution de 1996 a prévu la décentralisation au profit des régions et des communes."),
    (2, "Qu'est-ce qu'un lamidat ?", "Un royaume ou une chefferie traditionnelle peule dirigée par un lamido",
     ["Un parti politique", "Une université du Nord", "Un tribunal colonial", "Un marché de bétail"],
     "Ngaoundéré et Rey-Bouba sont des exemples de lamidats."),
    (3, "Qu'est-ce qu'un mandat de la Société des Nations ?", "La charge d'administrer un territoire sous contrôle international",
     ["Un emprunt d'État", "Un passeport pour voyager", "Une élection de chefs", "Une convention douanière"],
     "Le Cameroun fut confié à la France et au Royaume-Uni en 1922."),
    (2, "Quelle est la mission principale du Sénat ?", "Voter les lois avec l'Assemblée nationale",
     ["Fabriquer la monnaie", "Gérer les écoles", "Organiser les championnats sportifs", "Commander l'armée"],
     "Le Parlement camerounais est formé de deux chambres qui participent à la loi."),
    (2, "Qui vote les lois au Cameroun ?", "Le Parlement",
     ["Les préfets", "Les chefs traditionnels", "Les maires seuls", "Les ambassadeurs"],
     "Le Parlement, composé de l'Assemblée nationale et du Sénat, vote les lois."),
    (3, "Quelle autorité promulgue les lois votées par le Parlement ?", "Le président de la République",
     ["Le président du Sénat seul", "Le préfet", "Le gouverneur", "Le maire de Yaoundé"],
     "La promulgation rend la loi exécutoire."),
    (1, "Que veut dire le sigle ONU ?", "Organisation des Nations unies",
     ["Organisation nationale universelle", "Office des Nations d'Union", "Organisation nordique unie", "Observatoire des nations unies"],
     "L'ONU a été créée en 1945 ; le Cameroun y est entré en 1960."),
    (2, "Que veut dire le sigle OUA ?", "Organisation de l'unité africaine",
     ["Organisation universelle africaine", "Office de l'union des États africains", "Organisation des universités d'Afrique", "Observatoire de l'unité d'Afrique"],
     "L'OUA fut créée en 1963 et remplacée par l'Union africaine en 2002."),
    (1, "Combien de bandes de couleur a le drapeau du Cameroun ?", "3",
     ["2", "4", "5", "6", "7"],
     "Le drapeau est vert, rouge et jaune."),
    (1, "Combien d'étoiles figurent sur le drapeau actuel du Cameroun ?", "1",
     ["2", "3", "4", "5", "0"],
     "Une étoile jaune se trouve au centre de la bande rouge."),
    (2, "Sur quel fleuve, dont l'estuaire est large, se trouve la ville de Douala ?", "Le Wouri",
     ["Le Logone", "La Bénoué", "Le Nyong", "La Sanaga", "Le Dja"],
     "Les Portugais y virent des crevettes : c'est l'origine du mot « Cameroun »."),
    (3, "Quel navigateur portugais est associé à l'exploration de l'estuaire du Wouri vers 1472 ?", "Fernão do Pó",
     ["Vasco de Gama", "Bartolomeu Dias", "Christophe Colomb", "Magellan", "Pedro Álvares Cabral"],
     "Une île du golfe de Guinée a longtemps porté son nom, Fernando Pó."),
    (3, "Quel chancelier allemand a joué un rôle central dans la politique coloniale de 1884 ?", "Otto von Bismarck",
     ["Konrad Adenauer", "Willy Brandt", "Angela Merkel", "Helmut Kohl", "Frédéric II"],
     "Bismarck a accueilli la conférence de Berlin de 1884-1885, qui fixa les règles du partage de l'Afrique."),
    (2, "Quelle conférence de 1884-1885 a fixé les règles de la colonisation en Afrique ?", "La conférence de Berlin",
     ["La conférence de Bandung", "La conférence de Yalta", "La conférence de Paris", "La conférence de Brazzaville", "La conférence de Londres"],
     "Les puissances européennes se sont mises d'accord sur les règles de l'occupation en Afrique."),
    (1, "Quelle ville du Littoral a longtemps été le principal port du Cameroun ?", "Douala",
     ["Kribi", "Limbé", "Édéa", "Yaoundé", "Bafoussam"],
     "Douala est le premier port du pays et sa capitale économique."),
    (2, "Quel mot, utilisé par la Constitution, désigne l'égalité des deux langues officielles ?", "Le bilinguisme",
     ["Le monolinguisme", "Le multiculturalisme seulement", "L'unilatéralisme", "Le fédéralisme", "Le polyglottisme"],
     "L'État camerounais favorise le bilinguisme en français et en anglais."),
])
