"""Cameroun, culture générale du programme scolaire : système éducatif, éducation civique et morale, géographie,
économie, sciences appliquées, langues et peuples. Faits stables, sans chiffres changeants."""
from .cult_kit import rows, table, theme

theme("cm-ecole", "Cameroun : culture générale du programme scolaire",
      "Comparer avec les programmes officiels (MINEDUB, MINESEC), les manuels de géographie, d'éducation à la citoyenneté et de sciences "
      "du Cameroun, un atlas du Cameroun et les textes sur la décentralisation ; ne garder que des faits stables.")

# ------------------------------------------------------------------------------------------ système éducatif
rows("cm-ecole", "CM", "Système éducatif", [
    (1, "Combien de classes compte le cycle primaire francophone, du SIL au CM2 ?", "Six", ["Quatre", "Cinq", "Sept", "Huit"],
     "Le primaire francophone comprend le SIL, le CP, le CE1, le CE2, le CM1 et le CM2."),
    (3, "Que signifie le sigle SIL, nom de la toute première classe du primaire francophone ?", "Section d'initiation au langage",
     ["Service d'instruction locale", "Section d'initiation à la lecture", "Système d'instruction libre"],
     "Le SIL accueille les petits avant le cours préparatoire (CP)."),
    (1, "Quelle est la première classe du secondaire général francophone ?", "La sixième (6e)", ["La seconde", "La cinquième", "La troisième", "Le CM2"],
     "Après le CM2, on entre en 6e, première classe du secondaire."),
    (2, "Quelle classe suit la 3e dans le secondaire général francophone ?", "La seconde", ["La première", "La 4e", "La terminale", "La 6e"],
     "On passe de la 3e (fin du premier cycle) à la seconde (début du second cycle)."),
    (3, "Quelles classes forment le second cycle du secondaire général francophone ?", "La seconde, la première et la terminale",
     ["La 6e, la 5e, la 4e et la 3e", "Le CM2, la 6e et la 5e", "La 3e, la seconde et la première"],
     "Le second cycle dure trois ans et se termine par le baccalauréat."),
    (4, "Dans le sous-système francophone, quelle série du baccalauréat général est la série littéraire ?", "La série A", ["La série C", "La série D", "La série E"],
     "La série A met l'accent sur les lettres, les langues et la philosophie."),
    (4, "Quelle série du baccalauréat général francophone est centrée sur les mathématiques et les sciences physiques ?", "La série C",
     ["La série A", "La série D", "La série G"],
     "La série C est la série scientifique à dominante mathématiques et physique."),
    (4, "Quel organisme public est chargé d'organiser le baccalauréat au Cameroun ?", "L'Office du baccalauréat du Cameroun",
     ["La Commission nationale des examens", "L'Institut national de la statistique", "Le Conseil national de la jeunesse"],
     "On désigne souvent cet organisme par le sigle OBC."),
    (2, "Quels sont les deux sous-systèmes éducatifs du Cameroun ?", "Le sous-système francophone et le sous-système anglophone",
     ["Le sous-système public et le sous-système coutumier", "Le sous-système urbain et le sous-système rural", "Le sous-système laïc et le sous-système confessionnel"],
     "Ils reflètent l'héritage des administrations française et britannique et les deux langues officielles."),
    (2, "Quelle est la première classe du secondaire dans le sous-système anglophone ?", "Form One", ["Class One", "Lower Sixth", "Form Five", "Class Six"],
     "Le secondaire anglophone va de la Form One à la Form Five, puis à la Lower et à l'Upper Sixth."),
    (3, "Après quelle classe passe-t-on le GCE Ordinary Level dans le sous-système anglophone ?", "Après la Form Five",
     ["Après la Form One", "Après la Lower Sixth", "Après l'Upper Sixth", "Après la Class Six"],
     "Le GCE O Level clôt le premier cycle du secondaire anglophone."),
    (3, "Quelle classe anglophone vient juste avant l'Upper Sixth ?", "La Lower Sixth", ["La Form Five", "La Form Four", "La Class Six", "La Form Three"],
     "Les deux années Lower Sixth et Upper Sixth préparent le GCE Advanced Level."),
    (2, "Quel examen passe-t-on à la fin de l'Upper Sixth dans le sous-système anglophone ?", "Le GCE Advanced Level",
     ["Le First School Leaving Certificate", "Le BEPC", "Le Probatoire", "Le GCE Ordinary Level"],
     "Le GCE A Level ouvre l'accès à l'enseignement supérieur, comme le baccalauréat côté francophone."),
    (3, "Dans quelle ville se trouve le siège du GCE Board, qui organise les examens du sous-système anglophone ?", "Buea",
     ["Bamenda", "Limbé", "Kumba", "Yaoundé"], "Le Cameroon GCE Board a son siège à Buea, dans le Sud-Ouest."),
    (4, "Comment appelle-t-on le concours d'admission en Form One dans le sous-système anglophone ?", "Le Common Entrance",
     ["Le GCE Advanced Level", "Le Probatoire", "Le BEPC", "Le Cameroon Bar Test"],
     "Les élèves sortis de la Class Six peuvent le passer pour entrer au secondaire."),
    (2, "Dans quelle ville se trouve le lycée général Leclerc, établissement bien connu du secondaire ?", "Yaoundé", ["Douala", "Garoua", "Bafoussam", "Ebolowa"],
     "Le lycée général Leclerc est l'un des grands établissements de la capitale politique."),
    (3, "Dans quelle ville se trouve le lycée de Joss ?", "Douala", ["Yaoundé", "Limbé", "Édéa", "Nkongsamba"],
     "Joss est un quartier de Douala."),
    (4, "Dans quelle ville se trouve le collège Libermann, établissement connu du secondaire ?", "Douala", ["Yaoundé", "Garoua", "Ebolowa", "Bamenda"],
     "Le collège Libermann est un établissement de Douala."),
    (4, "Dans quelle ville se trouve le collège Vogt, établissement privé catholique connu ?", "Yaoundé", ["Douala", "Bafoussam", "Maroua", "Kribi"],
     "Le collège Vogt est un établissement de la capitale, Yaoundé."),
    (4, "Dans quelle ville se trouve le Saint Joseph's College de Sasse, établissement de la région anglophone ?", "Buea", ["Bamenda", "Kumba", "Limbé", "Mamfe"],
     "Sasse est un quartier de Buea, au pied du mont Cameroun."),
    (1, "En quel mois commence normalement l'année scolaire au Cameroun ?", "En septembre", ["En janvier", "En mars", "En juin", "En novembre"],
     "La rentrée des classes a lieu au début de septembre."),
    (2, "Quelle école est destinée à former les enseignants du secondaire ?", "L'École normale supérieure", ["L'École nationale d'administration et de magistrature", "L'École des douanes", "Le collège d'enseignement technique"],
     "L'École normale supérieure, ou ENS, forme des professeurs de lycée et de collège."),
    (5, "Que signifie le sigle ENIEG, nom d'écoles de formation du Cameroun ?", "École normale d'instituteurs de l'enseignement général",
     ["École nationale des ingénieurs et des experts généraux", "École nationale d'initiation à l'économie générale", "École normale d'inspecteurs de l'éducation de base"],
     "Les ENIEG forment les instituteurs de l'enseignement primaire."),
    (2, "Combien d'années faut-il pour obtenir une licence dans le système LMD ?", "Trois ans", ["Deux ans", "Cinq ans", "Huit ans", "Un an"],
     "La licence s'obtient en trois ans, le master en deux ans de plus."),
    (3, "Que signifient les lettres du sigle LMD, en usage dans l'enseignement supérieur ?", "Licence, Master, Doctorat",
     ["Lycée, Maîtrise, Diplôme", "Licence, Mention, Diplôme", "Lettres, Mathématiques, Droit"],
     "Ce système organise les études supérieures en trois grades."),
    (3, "Quelle institution de l'ONU est consacrée à l'éducation, à la science et à la culture ?", "L'UNESCO", ["L'UNICEF", "La FAO", "L'OMS", "L'OIT"],
     "Le siège de l'UNESCO est à Paris."),
    (2, "Dans quelle ville se trouve le siège de l'UNESCO ?", "Paris", ["Genève", "New York", "Nairobi", "Addis-Abeba"],
     "L'UNESCO est installée à Paris depuis sa création après la Seconde Guerre mondiale."),
])

table("cm-ecole", "CM", "Système éducatif", [
    ("la Journée mondiale des enseignants", "le 5 octobre", 2),
    ("la Journée internationale de l'alphabétisation", "le 8 septembre", 3),
    ("la Journée internationale de la langue maternelle", "le 21 février", 3),
    ("la Journée internationale de l'éducation", "le 24 janvier", 4),
    ("la Journée mondiale du livre et du droit d'auteur", "le 23 avril", 3),
    ("la Journée de l'Afrique", "le 25 mai", 3),
], "À quelle date célèbre-t-on {a} ?", "Quelle journée célèbre-t-on {b} ?", diff=3, expl="{a} a lieu {b}.")

# ------------------------------------------------------------------------------------------ éducation civique
rows("cm-ecole", "CM", "Éducation civique", [
    (2, "Comment appelle-t-on l'assemblée d'élus qui gère les affaires d'une commune ?", "Le conseil municipal", ["Le conseil de discipline", "Le conseil des ministres", "Le conseil constitutionnel"],
     "Les conseillers municipaux sont élus par les habitants de la commune."),
    (4, "Qui élit le maire d'une commune au Cameroun ?", "Les conseillers municipaux", ["Le préfet", "Le gouverneur de la région", "Le président de la République"],
     "Le maire est élu par le conseil municipal, parmi ses membres."),
    (3, "Qui peut remplacer le maire quand il est absent ?", "Un adjoint au maire", ["Le sous-préfet", "Le chef de quartier", "Le délégué du personnel"],
     "Les adjoints au maire assistent le maire et le suppléent."),
    (2, "Parmi ces services, lequel relève principalement de la commune ?", "L'état civil (naissances, mariages, décès)",
     ["La délivrance du baccalauréat", "La frappe de la monnaie", "Le commandement de l'armée", "La justice pénale"],
     "La mairie tient les registres d'état civil et délivre les actes."),
    (1, "Où célèbre-t-on un mariage civil au Cameroun ?", "À la mairie", ["À l'école", "À la préfecture", "Au marché", "Au commissariat"],
     "Le mariage civil est célébré par l'officier d'état civil, c'est-à-dire par le maire ou l'un de ses adjoints."),
    (4, "Quelle est la durée normale du mandat des conseillers municipaux ?", "Cinq ans", ["Deux ans", "Trois ans", "Sept ans", "Dix ans"],
     "Le mandat des conseillers municipaux est de cinq ans."),
    (4, "En combien de degrés les chefferies traditionnelles sont-elles classées au Cameroun ?", "Trois", ["Deux", "Quatre", "Cinq", "Six"],
     "On distingue les chefferies de premier, deuxième et troisième degrés."),
    (4, "Pour l'administration, que sont les chefs traditionnels ?", "Des auxiliaires de l'administration",
     ["Des juges de la Cour suprême", "Des maires de droit", "Des gouverneurs", "Des sénateurs de droit"],
     "Ils aident l'administration à encadrer les populations (information, recensement, collecte)."),
    (3, "Que veut dire qu'un État est « laïc » ?", "Qu'il reste neutre à l'égard des religions",
     ["Qu'il impose une religion officielle", "Qu'il interdit toute religion", "Qu'il ne reconnaît qu'une seule Église", "Qu'il réserve les emplois publics aux croyants"],
     "La Constitution camerounaise affirme que l'État est laïc et neutre envers toutes les religions."),
    (3, "Quel magistrat représente la société et requiert l'application de la loi dans un procès pénal ?", "Le procureur de la République",
     ["Le greffier", "L'huissier", "Le notaire", "L'expert comptable"],
     "Le procureur fait partie du ministère public et poursuit les infractions."),
    (2, "Quel professionnel défend une personne devant un tribunal ?", "L'avocat", ["L'huissier", "Le greffier", "Le notaire"],
     "L'avocat conseille et défend ses clients devant la justice."),
    (3, "Quel agent du tribunal tient les écritures et conserve les dossiers ?", "Le greffier", ["Le procureur", "Le bâtonnier", "Le maire", "L'avocat général"],
     "Le greffier authentifie les actes de la juridiction et garde les archives."),
    (3, "Quelle administration délivre le passeport camerounais ?", "La Sûreté nationale (la police)",
     ["La mairie", "Le tribunal de première instance", "Le Sénat", "L'ambassade du pays visité"],
     "Les passeports sont délivrés par les services de la police nationale, après un dossier complet."),
    (1, "Que doit faire un élève avant de prendre la parole en classe ?", "Lever la main et attendre qu'on la lui donne",
     ["Crier pour se faire entendre", "Se lever et quitter la salle", "Interrompre l'enseignant", "Parler à voix basse à son voisin"],
     "Respecter les tours de parole fait partie des règles du vivre-ensemble."),
    (2, "Quelle valeur consiste à dire la vérité, même quand c'est difficile ?", "L'honnêteté", ["La rancune", "La paresse", "L'orgueil", "La rivalité"],
     "Une personne honnête ne ment pas, ne triche pas et ne vole pas."),
    (2, "Quelle valeur consiste à respecter les différences de langue, d'origine ou d'opinion des autres ?", "La tolérance", ["L'intolérance", "La jalousie", "La vengeance"],
     "Au Cameroun, pays aux nombreuses langues et cultures, la tolérance est essentielle."),
    (1, "Comment appelle-t-on l'entraide entre personnes qui font face à une difficulté commune ?", "La solidarité", ["La rivalité", "L'égoïsme", "La concurrence", "L'indifférence"],
     "Aider les voisins, les camarades ou les familles en difficulté est un acte de solidarité."),
    (3, "Que signifie le mot « civisme » ?", "Le respect des règles et du bien commun", ["La crainte de la police", "Le goût du pouvoir", "Le refus des lois", "L'amour de la compétition"],
     "Le civisme se manifeste en respectant la loi, les autres et les biens publics."),
    (2, "Quel droit permet à chacun d'exprimer librement ses idées, dans le respect des lois ?", "La liberté d'expression", ["Le droit de vote", "Le droit à la propriété", "Le droit au repos"],
     "La liberté d'expression est l'une des libertés fondamentales."),
    (3, "Que désigne l'« exode rural » ?", "Le départ d'habitants des campagnes vers les villes", ["La fuite des habitants vers l'étranger", "Le retour des citadins au village", "La construction de routes rurales"],
     "L'exode rural contribue à la croissance rapide des villes comme Douala et Yaoundé."),
])

# ------------------------------------------------------------------------------------------ géographie
rows("cm-ecole", "CM", "Géographie du Cameroun", [
    (4, "Combien de grands bassins versants, ou bassins hydrographiques, distingue-t-on classiquement au Cameroun ?", "Quatre",
     ["Deux", "Trois", "Cinq", "Six"],
     "Ce sont les bassins de l'Atlantique, du Congo, du Niger et du lac Tchad."),
    (4, "Comment appelle-t-on le climat du Sud forestier, avec quatre saisons ?", "Le climat équatorial de type guinéen",
     ["Le climat désertique", "Le climat sahélien", "Le climat tropical soudanien", "Le climat méditerranéen"],
     "Il se caractérise par deux saisons des pluies et deux saisons sèches."),
    (4, "Dans le Sud du Cameroun, quelle saison suit la grande saison sèche ?", "La petite saison des pluies",
     ["La grande saison des pluies", "La petite saison sèche", "La saison de l'harmattan", "La saison des moussons"],
     "Le cycle va de la grande saison sèche à la petite saison des pluies (mars à juin), puis à la petite saison sèche, enfin à la grande saison des pluies."),
    (4, "À quelle période tombe à peu près la grande saison des pluies dans le Sud ?", "De septembre à novembre",
     ["De décembre à février", "De mars à juin", "De juillet à août"],
     "Cette période est la plus arrosée dans le Sud équatorial."),
    (3, "Comment appelle-t-on les arbres de la mangrove dont les racines en échasses plongent dans l'eau salée ?", "Les palétuviers",
     ["Les baobabs", "Les acajous", "Les kapokiers", "Les ébéniers"],
     "Les palétuviers fixent la vase et abritent poissons, crabes et crevettes."),
    (4, "Comment appelle-t-on le vaste plateau forestier ondulé qui occupe le Centre, le Sud et l'Est du Cameroun ?", "Le plateau sud-camerounais",
     ["Le plateau de l'Adamaoua", "Les hauts plateaux de l'Ouest", "La plaine du lac Tchad", "La cuvette de la Bénoué"],
     "Ce plateau dépasse en général les 500 mètres d'altitude et porte la forêt dense."),
    (5, "Quelle rivière marque la limite occidentale de la presqu'île de Bakassi, du côté du Nigeria ?", "L'Akwayafé",
     ["Le Mungo", "Le Nyong", "La Dibamba", "Le Ntem"],
     "L'Akwayafé longe Bakassi à l'ouest, vers le golfe de Guinée, tandis que le Rio del Rey la limite à l'est."),
    (4, "Entre quelles latitudes nord le Cameroun se situe-t-il, à peu près ?", "Entre 2° et 13° de latitude nord",
     ["Entre 10° et 30° de latitude nord", "Entre 5° de latitude sud et 5° de latitude nord", "Entre 15° et 25° de latitude nord", "Entre 40° et 50° de latitude nord"],
     "Le Cameroun s'étire de la zone équatoriale jusqu'au Sahel, au bord du lac Tchad."),
    (3, "Pourquoi la durée du jour varie-t-elle très peu au cours de l'année au Cameroun ?", "Parce que le pays est proche de l'équateur",
     ["Parce que le pays est près du pôle Nord", "Parce que le pays est très montagneux", "Parce que le pays est près de l'océan Indien", "Parce que le pays est un désert"],
     "Près de l'équateur, jours et nuits durent environ douze heures toute l'année."),
    (2, "Pourquoi fait-il plus frais à Bamenda qu'à Douala ?", "Parce que Bamenda est située à plus haute altitude",
     ["Parce que Bamenda est plus proche de l'équateur", "Parce que Bamenda est au bord de la mer", "Parce que Bamenda est dans le désert", "Parce que Bamenda est plus au sud"],
     "La température baisse quand l'altitude augmente."),
    (5, "Quelles deux rivières se rejoignent pour former la Sangha, qui longe le Sud-Est du Cameroun ?", "La Kadéï et la Mambéré",
     ["La Sanaga et le Mbam", "Le Ntem et le Nyong", "Le Logone et le Chari", "Le Lom et le Djérem"],
     "La Sangha naît à Nola, en Centrafrique, de la réunion de la Kadéï et de la Mambéré."),
    (4, "Quel département de l'Est tire son nom de la rivière Kadéï ?", "Le Kadey",
     ["Le Boumba-et-Ngoko", "Le Haut-Nyong", "Le Lom-et-Djérem"],
     "Le Kadey a pour chef-lieu Batouri."),
    (2, "Quel instrument d'une station météorologique mesure la quantité de pluie tombée ?", "Le pluviomètre", ["Le thermomètre", "Le baromètre", "L'anémomètre", "La girouette"],
     "La pluie se mesure en millimètres."),
    (3, "Quel instrument mesure la vitesse du vent ?", "L'anémomètre", ["Le pluviomètre", "Le thermomètre", "Le baromètre", "Le chronomètre"],
     "L'anémomètre tourne plus vite quand le vent est plus fort."),
    (3, "Que mesure la latitude d'un lieu ?", "Sa distance angulaire au nord ou au sud de l'équateur",
     ["Sa hauteur au-dessus du niveau de la mer", "Sa distance à la capitale", "Son éloignement du méridien de Greenwich", "Sa température moyenne"],
     "Douala est à environ 4° de latitude nord, Maroua à plus de 10°."),
    (3, "Quelles sont les deux villes les plus peuplées du Cameroun ?", "Douala et Yaoundé", ["Garoua et Maroua", "Bafoussam et Bamenda", "Limbé et Kribi", "Ngaoundéré et Bertoua"],
     "Douala est la capitale économique et Yaoundé la capitale politique."),
    (3, "Quel problème apparaît souvent dans les villes qui s'étendent très vite sans plan d'urbanisme ?", "L'habitat spontané dans des quartiers mal équipés",
     ["Le manque de soleil", "L'absence totale de circulation", "Le recul des immeubles", "La baisse de la température"],
     "Il en résulte des difficultés d'accès à l'eau, aux routes et à l'assainissement."),
    (5, "Quel organisme camerounais est chargé des recensements généraux de la population et de l'habitat ?", "Le BUCREP",
     ["Le CNPS", "ELECAM", "La CONAC"],
     "Le BUCREP est le Bureau central des recensements et des études de population."),
    (2, "Qu'est-ce qu'un recensement de la population ?", "Le dénombrement des habitants d'un pays", ["La liste des élèves d'une école", "Le choix d'un président", "Le calcul de la température moyenne"],
     "Il permet de connaître la population et ses besoins en écoles, en routes et en hôpitaux."),
])

# ------------------------------------------------------------------------------------------ cartes, eau, relief (notions)
rows("cm-ecole", "CM", "Géographie du Cameroun", [
    (1, "Comment appelle-t-on l'instrument dont l'aiguille aimantée indique le nord ?", "La boussole", ["Le thermomètre", "Le compas à pointes", "La règle graduée", "Le baromètre"],
     "La boussole sert à s'orienter sur le terrain et sur une carte."),
    (2, "À quoi sert la légende d'une carte ?", "À expliquer les signes et les couleurs utilisés", ["À donner le nom du dessinateur", "À indiquer l'heure de la prise de vue", "À mesurer la hauteur des montagnes"],
     "Sans légende, on ne peut pas lire correctement une carte de géographie."),
    (2, "Que représente l'échelle d'une carte ?", "Le rapport entre les distances sur la carte et les distances réelles",
     ["La hauteur des montagnes", "Le nombre d'habitants des villes", "La date de réalisation de la carte"],
     "Une échelle de 1/100 000 signifie que 1 cm sur la carte représente 1 km sur le terrain."),
    (4, "Que sont les courbes de niveau sur une carte ?", "Des lignes qui relient les points situés à la même altitude",
     ["Des routes qui suivent les montagnes", "Des lignes qui séparent deux pays", "Des fleuves dessinés en bleu", "Des limites de régions"],
     "Plus les courbes sont serrées, plus la pente est forte."),
    (2, "Comment appelle-t-on un cours d'eau, comme le Mbam pour la Sanaga, qui se jette dans un fleuve plus grand ?", "Un affluent",
     ["Un estuaire", "Un delta", "Une source", "Un barrage"],
     "Le Mbam est un affluent de la Sanaga."),
    (2, "Comment appelle-t-on l'endroit où un fleuve se jette dans la mer ?", "L'embouchure", ["La source", "Le confluent", "Le barrage", "Le gué"],
     "Le Wouri a son embouchure dans l'estuaire du Cameroun, au fond du golfe de Guinée."),
    (2, "Qu'est-ce qu'un lac de retenue ?", "Un lac artificiel formé par un barrage", ["Un lac au fond d'un cratère", "Un lac salé du désert", "Un lac né d'un glacier"],
     "Les lacs de Lagdo ou de Bamendjing sont des lacs de retenue."),
    (2, "Qu'est-ce qu'un plateau ?", "Une surface élevée, assez plane, souvent entaillée par les rivières", ["Une montagne pointue", "Une plaine inondée", "Une vallée étroite"],
     "L'Adamaoua et le plateau sud-camerounais sont des plateaux."),
    (2, "Qu'est-ce qu'une savane ?", "Une formation d'herbes hautes avec des arbres plus ou moins espacés", ["Une forêt toujours dense", "Un désert de sable", "Une plantation de bananiers"],
     "La savane couvre en grande partie l'Adamaoua et le Nord."),
    (4, "Qu'est-ce qu'une forêt-galerie ?", "Une bande de forêt le long d'un cours d'eau, au milieu de la savane",
     ["Une forêt plantée en rangs réguliers", "Une forêt de montagne située au-dessus des nuages", "Une forêt vivant dans une grotte"],
     "L'eau du fleuve permet aux arbres de pousser même en savane."),
    (3, "Quelle différence y a-t-il entre la météo et le climat ?", "La météo décrit le temps d'un moment, le climat le temps moyen sur de nombreuses années",
     ["La météo décrit le sol, le climat décrit le ciel", "La météo est toujours plus chaude que le climat", "Il n'y a aucune différence entre les deux"],
     "On parle de climat quand on décrit le temps qu'il fait, en moyenne, sur de longues périodes."),
    (3, "Quel instrument mesure la pression atmosphérique ?", "Le baromètre", ["Le pluviomètre", "L'anémomètre", "Le thermomètre", "Le compteur Geiger"],
     "Une baisse de pression annonce souvent un changement de temps."),
    (4, "Comment appelle-t-on les pluies provoquées par la montée de l'air humide le long d'un relief ?", "Les pluies de relief (orographiques)",
     ["Les pluies cycloniques", "Les pluies acides", "Les pluies artificielles"],
     "Le versant exposé au vent humide du mont Cameroun reçoit ainsi des pluies très abondantes."),
    (4, "Que signifie le mot arabe « sahel », qui a donné son nom à la région ?", "Le rivage, le bord", ["Le désert", "La savane", "Le soleil", "La pluie"],
     "Le Sahel est le « rivage » du Sahara, la bande qui borde le désert."),
    (2, "Comment appelle-t-on le passage de l'eau liquide à l'état de vapeur sous l'effet de la chaleur ?", "L'évaporation", ["La condensation", "La congélation", "La précipitation"],
     "Le soleil fait évaporer l'eau des mers, des lacs et des fleuves."),
    (3, "Comment appelle-t-on le passage de la vapeur d'eau à l'état de petites gouttes qui forment les nuages ?", "La condensation", ["L'évaporation", "La congélation", "La fusion"],
     "L'air chargé de vapeur se refroidit en montant et forme des nuages."),
])

# ------------------------------------------------------------------------------------------ économie, énergie, sciences appliquées
rows("cm-ecole", "CM", "Économie et ressources", [
    (2, "Quelle est la principale source d'électricité au Cameroun ?", "L'énergie de l'eau des fleuves (hydroélectricité)",
     ["Les centrales nucléaires", "Le charbon", "Les éoliennes", "La géothermie"],
     "Les barrages, notamment sur la Sanaga, fournissent l'essentiel de l'électricité."),
    (3, "Quelle machine, mise en mouvement par l'eau d'un barrage, entraîne l'alternateur d'une centrale hydroélectrique ?", "La turbine",
     ["Le transformateur", "Le condensateur", "Le piston", "La batterie"],
     "L'eau qui tombe fait tourner la turbine ; l'alternateur transforme ce mouvement en électricité."),
    (4, "Pourquoi construit-on un barrage-réservoir en amont comme celui de Lom Pangar ?", "Pour stocker l'eau des pluies et soutenir le débit du fleuve en saison sèche",
     ["Pour empêcher le fleuve d'atteindre la mer", "Pour fabriquer du sel", "Pour irriguer le désert du Sahara", "Pour refroidir le climat de la région"],
     "Le réservoir de Lom Pangar sert à régulariser le débit de la Sanaga, ce qui profite aux centrales situées en aval."),
    (2, "Quelle énergie renouvelable est particulièrement adaptée au Nord, très ensoleillé ?", "L'énergie solaire", ["L'énergie des marées", "L'énergie nucléaire", "Le charbon", "L'énergie des volcans"],
     "Des panneaux solaires peuvent alimenter écoles, centres de santé et pompes à eau."),
    (2, "Qu'est-ce qu'une énergie renouvelable ?", "Une énergie qui se reconstitue naturellement, comme le soleil, l'eau ou le vent",
     ["Une énergie qui ne s'épuise jamais mais pollue", "Une énergie fabriquée uniquement en usine", "Une énergie issue du pétrole ou du charbon"],
     "Le soleil, le vent, l'eau et la biomasse sont des énergies renouvelables."),
    (2, "Quelle source d'énergie domestique contribue au recul des forêts autour des grandes villes ?", "Le bois de chauffe et le charbon de bois",
     ["Le gaz butane en bouteille", "L'électricité des barrages", "Les panneaux solaires"],
     "Couper des arbres pour cuisiner sans les replanter appauvrit les forêts."),
    (2, "Quel combustible, vendu en bouteille, sert à cuisiner dans de nombreux foyers urbains ?", "Le gaz butane", ["L'uranium", "L'hydrogène", "Le charbon de bois", "Le kérosène"],
     "Le gaz domestique est issu du pétrole ou du gaz naturel."),
    (3, "Qu'appelle-t-on « hydrocarbures » dans l'économie d'un pays ?", "Le pétrole et le gaz naturel", ["Les fleuves et les lacs", "Les minerais de fer", "Les produits de la pêche", "Les cultures de rente"],
     "Les hydrocarbures sont des composés de carbone et d'hydrogène."),
    (3, "En quoi consiste le raffinage du pétrole ?", "À transformer le pétrole brut en produits utilisables, comme l'essence et le gasoil",
     ["À puiser le pétrole en mer", "À transporter le pétrole par oléoduc", "À stocker le pétrole sous terre"],
     "Le pétrole brut est trié et transformé dans une raffinerie comme celle de Limbé."),
    (3, "Comment appelle-t-on les cultures destinées surtout à nourrir les familles qui les produisent ?", "Les cultures vivrières", ["Les cultures de rente", "Les cultures de loisirs", "Les cultures sous verre"],
     "Le manioc, le plantain, le maïs et le macabo sont des cultures vivrières."),
    (3, "Comment appelle-t-on les cultures destinées surtout à la vente et à l'exportation ?", "Les cultures de rente", ["Les cultures vivrières", "Les cultures de loisirs", "Les cultures sous verre"],
     "Le cacao, le café, le coton et l'hévéa sont des cultures de rente."),
    (1, "Quel tubercule, que l'on transforme en bâton, en farine ou en gari, est cultivé presque partout au Cameroun ?", "Le manioc", ["La pomme de terre", "La betterave", "Le navet", "La carotte"],
     "Le manioc est une base de l'alimentation dans de nombreuses régions."),
    (3, "Quelles céréales traditionnelles sont cultivées dans l'Extrême-Nord pour préparer des boules et des bouillies ?", "Le mil et le sorgho",
     ["Le blé et l'orge", "Le seigle et l'avoine", "Le riz et le quinoa"],
     "Ces céréales résistent bien à la chaleur et à la sécheresse du Sahel."),
    (4, "Quelle ville du Centre est connue pour sa grande sucrerie et ses champs de canne à sucre ?", "Mbandjock", ["Obala", "Bafia", "Monatélé", "Eséka"],
     "La Société sucrière du Cameroun (Sosucam) est installée à Mbandjock."),
    (4, "Dans quelle région se trouve Ndu, connue pour ses plantations de thé ?", "Le Nord-Ouest", ["Le Sud-Ouest", "L'Ouest", "L'Adamaoua", "Le Littoral"],
     "Le thé pousse sur les hautes terres fraîches du Nord-Ouest."),
    (4, "Quelle ville du Nord est connue pour son calcaire et sa cimenterie ?", "Figuil", ["Pitoa", "Lagdo", "Guider", "Rey-Bouba"],
     "Le calcaire de Figuil sert à fabriquer du ciment."),
    (4, "Quelle étape de la préparation des fèves de cacao, avant le séchage, développe l'arôme du chocolat ?", "La fermentation", ["La congélation", "Le salage", "La torréfaction en usine seulement", "La distillation"],
     "Les fèves sont mises à fermenter quelques jours sous des feuilles ou dans des caisses, puis séchées au soleil."),
    (4, "Quel produit tire-t-on de l'amande de la noix de palme, différent de l'huile de palme issue de la pulpe ?", "L'huile de palmiste", ["L'huile d'olive", "L'huile de coton", "Le beurre de karité", "La margarine de soja"],
     "L'huile de palme vient de la pulpe du fruit, l'huile de palmiste de son amande."),
    (4, "Quelle opération sépare la fibre de coton de ses graines ?", "L'égrenage", ["Le tissage", "La filature", "Le teintage", "Le battage"],
     "Les usines d'égrenage des régions cotonnières du Nord préparent le coton avant sa filature."),
    (3, "Quel produit alimentaire extrait-on des graines de coton après l'égrenage ?", "De l'huile", ["Du sucre", "Du sel", "De la farine de blé", "Du beurre de vache"],
     "Le coton fournit à la fois la fibre et, avec ses graines, de l'huile et des tourteaux."),
    (5, "Quel arbre de montagne, dont l'écorce sert à fabriquer des médicaments, est protégé à cause de son exploitation excessive ?", "Le prunier d'Afrique (Prunus africana)",
     ["Le baobab", "L'iroko", "Le fromager", "L'hévéa"],
     "On le trouve surtout sur les hauts plateaux de l'Ouest et du Nord-Ouest et sur le mont Cameroun."),
    (4, "Quel type de sol rougeâtre, riche en fer et en aluminium, domine dans la zone forestière du Sud ?", "Le sol ferralitique", ["Le podzol", "Le tchernoziom", "Le lœss", "Le sol salin"],
     "Il est épais mais pauvre en éléments nutritifs : la forêt les recycle."),
    (3, "Quelle est l'origine de la fertilité des sols de l'Ouest et des pentes du mont Cameroun ?", "L'origine volcanique de la roche",
     ["Le passage des glaciers", "Le sel de la mer", "Le sable du désert", "Les cendres des feux de brousse"],
     "Les roches volcaniques s'altèrent en sols riches en minéraux."),
    (3, "Quelle technique protège un champ en pente contre l'érosion ?", "Cultiver en suivant les courbes de niveau, ou en terrasses",
     ["Cultiver de haut en bas de la pente", "Enlever toute la végétation", "Brûler le champ à chaque saison"],
     "Les sillons qui suivent les courbes de niveau ralentissent l'eau de ruissellement."),
    (2, "Qu'appelle-t-on la jachère ?", "Une période pendant laquelle on laisse la terre au repos sans la cultiver", ["Une récolte abondante", "Un engrais chimique", "Un outil agricole", "Un marché de vivres"],
     "La jachère permet au sol de retrouver sa fertilité."),
    (3, "Comment appelle-t-on la technique qui consiste à brûler la végétation pour cultiver, puis à changer de parcelle ?", "L'agriculture itinérante sur brûlis",
     ["L'agriculture sous serre", "L'élevage intensif", "La culture hors-sol"],
     "Trop pratiquée, elle contribue à la dégradation des forêts."),
    (3, "Comment appelle-t-on les rangées d'arbres plantées pour freiner le vent et l'avancée du désert ?", "Des brise-vent", ["Des paratonnerres", "Des digues", "Des remblais"],
     "Dans l'Extrême-Nord, les haies d'arbres protègent les champs de l'érosion éolienne."),
    (3, "Quel rôle important joue la mangrove le long de la côte ?", "Elle protège les rives et abrite la reproduction de nombreux poissons",
     ["Elle produit de l'électricité", "Elle fournit du pétrole", "Elle arrête les pluies"],
     "Les racines des palétuviers retiennent la vase et servent d'abri aux jeunes poissons."),
    (3, "Quel gaz, produit notamment par la combustion du bois et des carburants, contribue le plus au réchauffement climatique ?", "Le dioxyde de carbone", ["L'oxygène", "L'azote", "L'hélium"],
     "Le dioxyde de carbone (CO2) est le principal gaz à effet de serre rejeté par les activités humaines."),
    (1, "Quelle embarcation les pêcheurs artisanaux utilisent-ils sur la côte et sur les fleuves ?", "La pirogue", ["Le paquebot", "Le sous-marin", "Le chalutier à vapeur", "Le voilier de course"],
     "La pirogue est creusée dans un tronc ou construite en planches."),
    (2, "Qu'est-ce qu'un bien public ?", "Un bien qui appartient à tous, comme une route, une école ou un pont", ["Un bien volé", "Un bien qui appartient à un seul voisin", "Un objet de collection"],
     "Chacun doit respecter et protéger les biens publics."),
    (3, "Qu'est-ce qu'un service public ?", "Une activité d'intérêt général assurée pour tous, comme l'école, l'eau ou la santé",
     ["Une entreprise qui vend ses produits au plus offrant", "Un club privé", "Un marché de quartier"],
     "Les services publics sont financés en grande partie par les impôts."),
    (3, "Qu'est-ce qu'une association ?", "Un groupe de personnes réunies pour un but commun, sans chercher à partager des bénéfices",
     ["Une société qui partage ses bénéfices entre actionnaires", "Une administration de l'État", "Un tribunal"],
     "Clubs, comités de quartier ou groupes d'entraide sont des associations."),
    (2, "Comment appelle-t-on l'action d'aider la communauté ou une association sans être payé ?", "Le bénévolat", ["Le salariat", "L'héritage", "Le troc", "La spéculation"],
     "Un bénévole donne de son temps gratuitement."),
])

# ------------------------------------------------------------------------------------------ langues, peuples, patrimoine
rows("cm-ecole", "CM", "Langues et peuples", [
    (2, "Environ combien de langues locales parle-t-on au Cameroun ?", "Plus de deux cents", ["Une dizaine", "Une cinquantaine", "Plus de mille"],
     "En plus du français et de l'anglais, le pays compte plus de deux cents langues."),
    (3, "Quelle langue, parlée par les Peuls, sert de langue de communication dans une grande partie du Nord ?", "Le fulfulde", ["L'ewondo", "Le douala", "Le bamoun", "Le bassa"],
     "Le fulfulde (ou peul) est largement utilisé dans l'Adamaoua et le Nord comme langue véhiculaire."),
    (3, "Comment appelle-t-on le parler urbain des jeunes qui mélange français, anglais et langues locales ?", "Le camfranglais", ["Le pidgin-fon", "Le sango", "Le latin populaire"],
     "Le camfranglais s'entend surtout dans les villes comme Douala et Yaoundé."),
    (4, "Parmi ces langues du Cameroun, laquelle est une langue bantoue ?", "L'ewondo", ["Le fulfulde", "Le haoussa", "Le kanuri", "L'arabe choa"],
     "L'ewondo, comme le douala ou le bassa, appartient à la grande famille bantoue."),
    (4, "Dans le découpage classique des aires culturelles du Cameroun, à quelle aire l'Extrême-Nord appartient-il ?", "L'aire soudano-sahélienne",
     ["L'aire côtière", "L'aire des grassfields", "L'aire forestière Fang-Beti"],
     "Cette aire regroupe des peuples d'éleveurs et de cultivateurs des savanes et du Sahel."),
])

table("cm-ecole", "CM", "Langues et peuples", [
    ("les Bakweri", "le Sud-Ouest", 3), ("les Toupouri", "l'Extrême-Nord", 4), ("les Bulu", "le Sud", 3),
    ("les Bamoun", "l'Ouest", 2), ("les Kotoko", "l'Extrême-Nord", 4), ("les Bafut", "le Nord-Ouest", 4),
    ("les Ewondo", "le Centre", 2), ("les Mousgoum", "l'Extrême-Nord", 4), ("les Nso", "le Nord-Ouest", 4),
], "Dans quelle région vit principalement le peuple dont le nom est {a} ?", None, diff=3, expl="{a} vivent surtout dans {b}.")

rows("cm-ecole", "CM", "Patrimoine", [
    (4, "Dans quel bâtiment de Yaoundé le Musée national est-il installé ?", "Dans l'ancien palais présidentiel", ["Dans l'ancienne gare ferroviaire", "Dans une ancienne cathédrale", "Dans le palais des congrès", "Dans l'ancien palais de justice"],
     "Le Musée national occupe un ancien palais présidentiel de la capitale."),
    (3, "Quel quartier de Yaoundé abrite le palais présidentiel ?", "Etoudi", ["Bastos", "Mokolo", "Essos", "Mvog-Mbi"],
     "Le palais de l'Unité se trouve à Etoudi."),
    (3, "Quel quartier de Douala, ancien siège de l'administration coloniale, concentre administrations et banques ?", "Bonanjo", ["Akwa-Nord", "New Bell", "Deïdo", "Bonabéri"],
     "Bonanjo, au bord du Wouri, est le quartier administratif et d'affaires de Douala."),
])

rows("cm-ecole", "CM", "Système éducatif", [
    (1, "Quel instrument sert à mesurer la température ?", "Le thermomètre", ["Le baromètre", "Le pluviomètre", "La boussole", "Le chronomètre"],
     "Le thermomètre donne la température de l'air, du corps ou de l'eau."),
    (1, "Comment appelle-t-on l'enseignant qui tient une classe du primaire ?", "Un instituteur", ["Un proviseur", "Un greffier", "Un percepteur", "Un maire"],
     "Les instituteurs sont formés dans des écoles normales."),
    (2, "Comment appelle-t-on le chef d'établissement d'un lycée ?", "Le proviseur", ["L'instituteur", "Le sous-préfet", "Le greffier", "Le receveur"],
     "Le proviseur dirige le lycée ; une école primaire est dirigée par un directeur ou une directrice."),
    (1, "Qui dirige une école primaire ?", "Le directeur ou la directrice d'école", ["Le maire", "Le gouverneur", "Le chef de canton", "Le député"],
     "Le directeur ou la directrice organise la vie de l'école et supervise les enseignants."),
    (1, "Quel élève représente ses camarades auprès des enseignants dans une classe ?", "Le délégué de classe", ["Le surveillant général", "Le proviseur", "Le gardien", "L'inspecteur"],
     "Le délégué de classe porte la parole de la classe."),
])

rows("cm-ecole", "CM", "Géographie du Cameroun", [
    (4, "Dans quelle direction souffle principalement l'harmattan sur le Cameroun ?", "Du nord-est vers le sud-ouest",
     ["Du sud-ouest vers le nord-est", "Du sud vers le nord", "De l'ouest vers l'est"],
     "Ce vent sec et poussiéreux vient du Sahara, à l'inverse de la mousson humide."),
    (4, "D'où vient la mousson humide qui apporte la pluie au Cameroun ?", "Du sud-ouest, de l'océan Atlantique",
     ["Du nord-est, du Sahara", "Du nord, du lac Tchad", "De l'est, de l'océan Indien"],
     "La mousson souffle de l'océan Atlantique vers l'intérieur des terres."),
    (5, "Parmi ces centrales hydroélectriques, laquelle est la plus proche de l'embouchure de la Sanaga ?", "Édéa", ["Song Loulou", "Nachtigal", "Lagdo"],
     "Édéa se trouve dans le Littoral, à quelques dizaines de kilomètres de l'embouchure de la Sanaga."),
])
