"""Afrique : cultures, arts, sport, nature (peuples et langues, musiques, instruments, littérature, cinéma, cuisines,
patrimoine, faune et flore, football, athlétisme, Jeux olympiques). Faits datés ou intemporels uniquement."""
from .cult_kit import rows, table, theme

theme("af-culture", "Afrique : cultures, arts, sport et nature",
      "Comparer avec l'UNESCO (patrimoine mondial et immatériel), les sites de la CAF, de la FIFA et du CIO pour les palmarès, "
      "les éditions des œuvres littéraires et un atlas ; ne garder que les faits datés.")

# ------------------------------------------------------------------------------------------- peuples et langues
rows("af-culture", "AF", "Afrique : peuples et langues", [
    (1, "Quelle langue bantoue, riche en mots d'origine arabe, sert de langue de communication dans une grande partie de l'Afrique de l'Est ?",
     "Le swahili", ["Le haoussa", "Le zoulou", "L'amharique", "Le wolof"],
     "Le nom « swahili » vient de l'arabe « sawāḥil », les côtes : cette langue s'est formée sur le littoral de l'océan Indien."),
    (2, "Que signifie l'expression swahili « hakuna matata », popularisée par le film Le Roi lion (1994) ?",
     "Pas de problème", ["Bonne chance", "À bientôt", "Bienvenue chez nous", "Merci beaucoup"],
     "Littéralement « il n'y a pas de soucis » : la formule est courante en Afrique de l'Est."),
    (2, "Que désigne à l'origine le mot « safari », emprunté au swahili ?",
     "Un voyage", ["Un lion", "Une savane", "Une tente", "Un marché"],
     "Le mot vient de l'arabe « safar » (voyage) par le swahili ; il a pris ensuite le sens d'expédition d'observation."),
    (3, "Quel mot wolof désigne l'hospitalité qui vaut au Sénégal le surnom de « pays de la teranga » ?",
     "Teranga", ["Ubuntu", "Harambee", "Ujamaa", "Akwaaba"],
     "La teranga est une valeur d'accueil et de partage très présente dans la culture sénégalaise."),
    (3, "Quelle langue européenne a donné naissance à l'afrikaans, parlé en Afrique du Sud et en Namibie ?",
     "Le néerlandais", ["L'anglais", "Le portugais", "L'allemand", "Le français"],
     "L'afrikaans s'est formé à partir du néerlandais des colons installés au Cap à partir du XVIIe siècle."),
    (3, "Quelle particularité sonore caractérise le xhosa et le zoulou, deux langues d'Afrique du Sud ?",
     "Des consonnes à clic", ["Des voyelles uniquement nasales", "L'absence totale de consonnes sourdes", "Des sons sifflés exclusivement",
                              "Une écriture sans voyelles"],
     "Ces langues ont emprunté des clics aux langues khoisan voisines : on les entend dans le nom même « Xhosa »."),
    (3, "Quel système d'écriture sert à noter l'amharique, langue de travail de l'Éthiopie ?",
     "L'écriture éthiopienne (ge'ez)", ["L'alphabet arabe", "L'alphabet cyrillique", "Les hiéroglyphes", "L'alphabet latin"],
     "C'est un abugida : chaque signe note une consonne accompagnée d'une voyelle."),
    (4, "Quel alphabet sert à écrire les langues berbères, notamment le touareg ?",
     "Le tifinagh", ["Le ge'ez", "Le n'ko", "L'adinkra", "Le cunéiforme"],
     "Le tifinagh est l'écriture traditionnelle des Touareg ; une version modernisée est utilisée au Maroc pour l'amazighe."),
    (5, "Quel Guinéen a inventé en 1949 l'alphabet n'ko pour écrire les langues mandingues ?",
     "Solomana Kanté", ["Camara Laye", "Cheikh Anta Diop", "Amadou Hampâté Bâ", "Ousmane Sembène"],
     "Le n'ko (« je dis » en mandingue) s'écrit de droite à gauche."),
    (4, "À quelle famille de langues appartient le malgache, langue de Madagascar ?",
     "Austronésienne", ["Bantoue", "Afro-asiatique", "Indo-européenne", "Nilo-saharienne"],
     "Le malgache est proche de langues d'Indonésie, héritage d'anciennes migrations à travers l'océan Indien."),
    (4, "Quelle ville du sud-ouest du Nigeria est considérée comme le centre spirituel et le berceau du peuple yoruba ?",
     "Ilé-Ifè", ["Kano", "Enugu", "Maiduguri", "Calabar"],
     "Selon la tradition yoruba, Ifè est le lieu où le monde fut créé ; la ville est aussi célèbre pour ses têtes en terre cuite et en laiton."),
    (3, "Quel roi zoulou a bâti un puissant royaume au début du XIXe siècle ?",
     "Shaka", ["Moshoeshoe", "Mzilikazi", "Lobengula", "Sobhuza"],
     "Shaka a régné d'environ 1816 à 1828 et réorganisé l'armée zouloue."),
    (3, "Dans quel pays vivent les Dogons, connus pour leurs masques et leurs villages le long de la falaise de Bandiagara ?",
     "Au Mali", ["Au Ghana", "Au Tchad", "Au Sénégal", "Au Bénin"],
     "La falaise de Bandiagara est inscrite au patrimoine mondial de l'UNESCO depuis 1989."),
    (2, "Quel peuple d'éleveurs du Kenya et de la Tanzanie est reconnaissable à ses étoffes rouges, les shúkà ?",
     "Les Maasaï", ["Les Zoulous", "Les Touareg", "Les Peuls", "Les Ashanti"],
     "Les Maasaï parlent le maa et sont aussi connus pour leur danse de saut, l'adumu."),
    (2, "Quel peuple du Sahara est surnommé « les hommes bleus » à cause de ses voiles teints à l'indigo ?",
     "Les Touareg", ["Les Maasaï", "Les Zoulous", "Les Dogons", "Les Bambaras"],
     "Les hommes touareg portent le chèche, ou tagelmust, teint à l'indigo qui déteint parfois sur la peau."),
    (4, "Quel objet sacré symbolise l'âme du peuple ashanti, au Ghana ?",
     "Le tabouret d'or", ["La couronne de plumes", "Le sceptre de bronze", "Le masque royal", "Le tambour parlant"],
     "Selon la tradition, le tabouret d'or serait descendu du ciel dans les bras du prêtre Okomfo Anokye."),
    (2, "Quelle étoffe tissée en bandes colorées est emblématique des Ashanti et des Éwé du Ghana ?",
     "Le kente", ["Le bogolan", "Le tissu kuba", "Le batik", "Le shuka"],
     "Les bandes de kente sont tissées sur de petits métiers puis cousues entre elles."),
    (4, "Quelle étoffe malienne est décorée avec une boue fermentée appliquée sur du coton ?",
     "Le bogolan", ["Le kente", "Le kanga", "Le shuka", "Le pagne wax"],
     "Le bogolan (ou tissu de boue) est traditionnellement associé aux Bambara."),
    (4, "Quel peuple d'Afrique du Sud est célèbre pour décorer ses maisons de motifs géométriques très colorés ?",
     "Les Ndebele", ["Les Zoulous", "Les Xhosas", "Les Pedis", "Les Vendas"],
     "Les femmes ndebele peignent les murs de leurs maisons de grands motifs aux couleurs vives."),
    (4, "Quel peuple utilise des symboles appelés adinkra, imprimés sur des tissus et porteurs de proverbes ?",
     "Les Akan (Ashanti) du Ghana", ["Les Yoruba du Nigeria", "Les Dogons du Mali", "Les Maasaï du Kenya", "Les Zoulous d'Afrique du Sud"],
     "Chaque symbole adinkra représente une idée ou un proverbe, comme la sagesse ou la persévérance."),
    (4, "Que signifie le radical « -ntu » de « bantu » dans plusieurs langues d'Afrique centrale et australe ?",
     "Être humain, personne", ["Montagne", "Ancêtre", "Voyageur", "Rivière"],
     "Avec le préfixe « ba- » du pluriel, « bantu » signifie « les gens » : de là le nom de la grande famille de langues."),
    (3, "Quelle philosophie d'Afrique australe est résumée par la formule « je suis parce que nous sommes » ?",
     "L'ubuntu", ["La négritude", "L'ujamaa", "Le panafricanisme", "L'harambee"],
     "L'ubuntu insiste sur les liens qui unissent les personnes entre elles ; la formule vient des langues nguni."),
    (3, "Quelle devise du Kenya, inscrite sur ses armoiries, signifie « tirons tous ensemble » ?",
     "Harambee", ["Uhuru", "Ubuntu", "Teranga", "Ujamaa"],
     "« Harambee » est un mot swahili qui désigne l'effort collectif ; il figure sur les armoiries du Kenya."),
    (2, "Dans quel pays le haoussa est-il la langue de communication du Nord, avec un grand nombre de locuteurs ?",
     "Au Nigeria", ["En Côte d'Ivoire", "Au Sénégal", "En Guinée", "Au Libéria"],
     "Le haoussa est aussi parlé au Niger et sert de langue de commerce dans une grande partie de l'Afrique de l'Ouest."),
    (2, "Quelle langue est parlée comme langue véhiculaire au Sénégal, notamment à Dakar ?",
     "Le wolof", ["Le haoussa", "Le lingala", "Le swahili", "Le bambara"],
     "Le wolof est parlé aussi en Gambie et en Mauritanie."),
    (3, "Dans quelle langue sont chantés la plupart des morceaux de rumba congolaise ?",
     "En lingala", ["En haoussa", "En amharique", "En zoulou", "En wolof"],
     "Le lingala est parlé à Kinshasa, à Brazzaville et dans une grande partie du nord-ouest du bassin du Congo."),
])

# langues de salutation : mêmes mots dans les deux sens
table("af-culture", "AF", "Afrique : peuples et langues",
      [("le zoulou", "sawubona", 3), ("le xhosa", "molo", 4), ("le lingala", "mbote", 3), ("le swahili", "jambo", 2),
       ("le haoussa", "sannu", 4), ("l'amharique", "selam", 4)],
      "Quel mot sert à dire bonjour en {a} ?", "Dans quelle langue dit-on « {b} » pour saluer ?",
      diff=3, expl="« {b} » est une salutation en {a}.", extra_b=["bonjour", "salut"])

# mots swahilis
table("af-culture", "AF", "Afrique : peuples et langues",
      [("lion", "simba", 2), ("éléphant", "tembo", 2), ("girafe", "twiga", 3), ("buffle", "nyati", 4), ("hippopotame", "kiboko", 4),
       ("léopard", "chui", 4), ("rhinocéros", "faru", 5), ("eau", "maji", 3), ("ami", "rafiki", 2), ("merci", "asante", 2),
       ("bienvenue", "karibu", 2), ("liberté", "uhuru", 3), ("paix", "amani", 4), ("maison", "nyumba", 4),
       ("un", "moja", 3), ("deux", "mbili", 3), ("trois", "tatu", 3), ("cinq", "tano", 5)],
      "Comment dit-on « {a} » en swahili ?", "Que signifie le mot swahili « {b} » ?",
      diff=3, expl="En swahili, « {a} » se dit « {b} ».")

# ------------------------------------------------------------------------------------------- instruments
rows("af-culture", "AF", "Afrique : instruments", [
    (2, "Quel instrument d'Afrique de l'Ouest, à calebasse et vingt et une cordes environ, est joué par les griots mandingues ?",
     "La kora", ["Le balafon", "Le djembé", "La mbira", "Le tama"],
     "La kora est une harpe-luth : ses cordes sont pincées avec les pouces et les index."),
    (2, "Quel tambour en forme de calice, joué à mains nues, est lié aux peuples mandingues d'Afrique de l'Ouest ?",
     "Le djembé", ["Le tama", "L'udu", "La darbouka", "Le bongo"],
     "Le djembé est taillé dans un tronc et recouvert d'une peau de chèvre."),
    (2, "Quel instrument ressemble à un xylophone de bois dont chaque lame a sa calebasse résonante ?",
     "Le balafon", ["La kora", "La mbira", "Le ngoni", "Le krar"],
     "Le balafon est joué dans toute l'Afrique de l'Ouest, notamment chez les Mandingues et les Sénoufo."),
    (3, "Quel instrument, composé de lames métalliques fixées sur une caisse de résonance, se joue avec les pouces ?",
     "La mbira", ["La kora", "Le balafon", "Le krar", "Le sintir"],
     "La mbira (ou sanza, kalimba) est notamment liée à la musique des Shona du Zimbabwe."),
    (4, "Quel peuple du Zimbabwe est particulièrement associé à la mbira ?",
     "Les Shona", ["Les Ndebele", "Les Zoulous", "Les Herero", "Les Ashanti"],
     "La mbira occupe une grande place dans la musique et les cérémonies shona."),
    (2, "Comment appelle-t-on les conteurs et musiciens traditionnels d'Afrique de l'Ouest, gardiens de la mémoire orale ?",
     "Les griots", ["Les forgerons", "Les marabouts", "Les devins", "Les pêcheurs"],
     "Dans les langues mandingues, ils s'appellent aussi djeli ou jali ; ils chantent généalogies et épopées."),
    (3, "Quel tambour yoruba, tenu sous le bras et dont on modifie la hauteur en serrant ses cordes, est appelé « tambour parlant » ?",
     "Le dùndún", ["Le djembé", "L'udu", "Le bongo", "Le tabla"],
     "Il imite les tons de la langue yoruba, ce qui permet de « parler » avec le tambour."),
    (4, "Quel est le nom de la lyre traditionnelle d'Éthiopie et d'Érythrée ?",
     "Le krar", ["La kora", "L'oud", "Le mvet", "Le ngoni"],
     "Le krar a cinq ou six cordes et accompagne les chanteurs, les azmaris."),
    (5, "Comment s'appelle le violon à une seule corde joué par les azmaris d'Éthiopie ?",
     "Le masenqo", ["Le krar", "Le sintir", "Le rebab", "Le goje"],
     "Le masenqo est un instrument à archet dont la caisse en losange est recouverte de peau."),
    (4, "Quel instrument à trois cordes, sorte de luth-basse, accompagne le chant des gnawa du Maroc ?",
     "Le guembri (sintir)", ["La kora", "Le krar", "Le balafon", "Le violon"],
     "Les gnawa jouent aussi des karkabou, de grandes castagnettes en métal."),
    (1, "Quel instrument à vent en plastique a fait vibrer les stades pendant la Coupe du monde de football 2010 ?",
     "La vuvuzela", ["La corne de brume", "Le sifflet", "La flûte de pan", "Le didgeridoo"],
     "La vuvuzela est devenue le symbole sonore du tournoi organisé en Afrique du Sud."),
    (5, "Quel instrument de percussion igbo est une jarre en terre cuite percée d'un trou latéral ?",
     "L'udu", ["Le djembé", "Le shekere", "Le balafon", "Le tama"],
     "On joue de l'udu en frappant la jarre ; le trou sert d'évent et donne de profondes notes graves."),
    (5, "Quel instrument d'Afrique de l'Ouest est une calebasse enveloppée d'un filet de perles ou de coquillages ?",
     "Le shekere", ["La kora", "Le balafon", "Le ngoni", "La sanza"],
     "On le secoue ou on le frappe : les perles du filet frottent la calebasse."),
])

# ------------------------------------------------------------------------------------------- musiques et danses
rows("af-culture", "AF", "Afrique : musiques et danses", [
    (3, "En 2021, quelle musique partagée par Kinshasa et Brazzaville a été inscrite au patrimoine culturel immatériel de l'UNESCO ?",
     "La rumba congolaise", ["Le highlife", "Le mbalax", "Le raï", "Le kwaito"],
     "La rumba congolaise s'est développée dans les années 1940-1950 sur les deux rives du fleuve Congo."),
    (4, "Quel art marocain mêlant musique, chants et rituels a été inscrit à l'UNESCO en 2019 ?",
     "Le gnawa", ["Le mbalax", "Le highlife", "Le makossa", "Le kwaito"],
     "Les gnawa sont héritiers de communautés venues d'Afrique subsaharienne ; Essaouira leur consacre un festival."),
    (4, "Quel genre musical né à Oran et inscrit à l'UNESCO en 2022 a rendu célèbres Cheikha Rimitti et Khaled ?",
     "Le raï", ["Le chaâbi", "Le gnawa", "Le mbalax", "Le malouf"],
     "Le raï, chant d'abord populaire et contestataire, est devenu un genre mondialement connu dans les années 1980-1990."),
    (3, "Quel chanteur algérien a connu un succès mondial en 1996 avec la chanson « Aïcha » ?",
     "Khaled", ["Cheb Mami", "Faudel", "Rachid Taha", "Cheb Hasni"],
     "« Aïcha » a été écrite pour lui par Jean-Jacques Goldman."),
    (3, "Dans quelle ville le raï est-il né ?",
     "À Oran", ["À Alger", "À Constantine", "À Annaba", "À Tlemcen"],
     "Oran, grande ville de l'ouest algérien, est le berceau du raï."),
    (3, "Quel genre musical, né sur la côte du Ghana au début du XXe siècle, mêle rythmes locaux et orchestres de cuivres ?",
     "Le highlife", ["Le raï", "Le mbalax", "Le kwaito", "Le zouglou"],
     "Le highlife s'est ensuite répandu au Nigeria et dans toute l'Afrique de l'Ouest anglophone."),
    (5, "Quel musicien ghanéen est surnommé le « roi du highlife » ?",
     "E. T. Mensah", ["Fela Kuti", "King Sunny Adé", "Hugh Masekela", "Ali Farka Touré"],
     "Emmanuel Tettey Mensah a popularisé le highlife dans les années 1950."),
    (4, "Quel batteur nigérian, compagnon de route de Fela Kuti, est considéré comme l'un des pères de l'afrobeat ?",
     "Tony Allen", ["Femi Kuti", "Manu Dibango", "Hugh Masekela", "Babatunde Olatunji"],
     "Fela disait que sans Tony Allen il n'y aurait pas eu d'afrobeat."),
    (4, "Dans quelle ville Fela Kuti a-t-il installé sa « Kalakuta Republic » et son club le Shrine ?",
     "À Lagos", ["À Abuja", "À Ibadan", "À Accra", "À Kano"],
     "Fela Kuti est mort à Lagos en 1997 ; une foule immense a suivi son cortège."),
    (5, "Comment s'appelait le groupe de Fela Kuti au début des années 1970 ?",
     "Africa 70", ["TPOK Jazz", "Les Ambassadeurs", "Osibisa", "Orchestre Baobab"],
     "Fela a formé Africa 70 après son séjour aux États-Unis, puis a fondé plus tard Egypt 80."),
    (3, "Quel genre sénégalais, fondé sur des percussions, a été popularisé dans le monde par Youssou N'Dour ?",
     "Le mbalax", ["Le coupé-décalé", "Le soukous", "Le zouglou", "Le kizomba"],
     "Le mbalax est né à Dakar dans les années 1970-1980, en mêlant rythmes sérères et sons modernes."),
    (4, "Quel tambour sénégalais, joué avec une main et une baguette, est au cœur du mbalax ?",
     "Le sabar", ["Le balafon", "La kora", "Le ngoni", "L'udu"],
     "Le sabar rythme aussi les fêtes et les lutteurs sénégalais."),
    (3, "Quel guitariste congolais, chef de l'orchestre TPOK Jazz, était surnommé « le sorcier de la guitare » ?",
     "Franco", ["Papa Wemba", "Tabu Ley Rochereau", "Manu Dibango", "Koffi Olomidé"],
     "François Luambo Makiadi, dit Franco (1938-1989), est l'une des plus grandes figures de la rumba congolaise."),
    (5, "En quelle année l'orchestre OK Jazz, futur TPOK Jazz, a-t-il été fondé à Léopoldville ?",
     "1956", ["1948", "1960", "1965", "1972"],
     "Franco est devenu son chef peu après la création de l'orchestre."),
    (4, "Quel chanteur congolais est l'auteur d'« Indépendance Cha Cha » (1960), devenu l'hymne des indépendances africaines ?",
     "Grand Kallé", ["Franco", "Papa Wemba", "Pépé Kallé", "Koffi Olomidé"],
     "Joseph Kabasele, dit Grand Kallé, dirigeait l'orchestre African Jazz."),
    (3, "Quel succès de Miriam Makeba, enregistré aux États-Unis dans les années 1960, est devenu son plus grand tube international ?",
     "Pata Pata", ["Wimoweh", "Waka Waka", "Soul Makossa", "Jerusalema"],
     "Pata Pata a été popularisé dans une version enregistrée en 1967."),
    (5, "Quelle chanteuse sud-africaine est morte en novembre 2008 après avoir donné un concert en Italie ?",
     "Miriam Makeba", ["Brenda Fassie", "Angélique Kidjo", "Cesária Évora", "Oum Kalthoum"],
     "Elle s'est effondrée à Castel Volturno après un concert en soutien à l'écrivain Roberto Saviano."),
    (4, "Quel trompettiste sud-africain (1939-2018) a placé « Grazing in the Grass » en tête du classement américain en 1968 ?",
     "Hugh Masekela", ["Abdullah Ibrahim", "Manu Dibango", "Mulatu Astatke", "Fela Kuti"],
     "Hugh Masekela fut aussi un fervent opposant à l'apartheid."),
    (5, "Quel musicien sud-africain a enregistré en 1939 « Mbube », à l'origine de « The Lion Sleeps Tonight » ?",
     "Solomon Linda", ["Joseph Shabalala", "Johnny Clegg", "Hugh Masekela", "Miriam Makeba"],
     "La chanson a ensuite été reprise sous le titre « Wimoweh » puis dans le monde entier."),
    (3, "Avec quel chanteur américain Ladysmith Black Mambazo a-t-il collaboré sur l'album Graceland (1986) ?",
     "Paul Simon", ["Sting", "Peter Gabriel", "Bob Dylan", "Stevie Wonder"],
     "Graceland mêle pop américaine et musiques sud-africaines."),
    (5, "Quel style de chant a cappella zoulou est pratiqué par Ladysmith Black Mambazo ?",
     "L'isicathamiya", ["Le mbalax", "Le kwaito", "Le soukous", "Le highlife"],
     "Le nom vient d'un verbe zoulou qui évoque une marche légère sur la pointe des pieds."),
    (4, "Quel guitariste malien, mort en 2006, est une grande figure du blues du fleuve Niger ?",
     "Ali Farka Touré", ["Habib Koité", "Boubacar Traoré", "Amadou et Mariam", "Tinariwen"],
     "Il a enregistré avec le joueur de kora Toumani Diabaté l'album In the Heart of the Moon."),
    (3, "Quelle chanteuse égyptienne, surnommée « l'Astre de l'Orient », est morte en 1975 ?",
     "Oum Kalthoum", ["Fairouz", "Asmahan", "Dalida", "Cesária Évora"],
     "Ses funérailles au Caire ont rassemblé une foule immense."),
    (4, "Quel artiste est célèbre pour son tube « Yéké Yéké », sorti en 1987 ?",
     "Mory Kanté", ["Youssou N'Dour", "Salif Keïta", "Papa Wemba", "Alpha Blondy"],
     "Mory Kanté, chanteur et joueur de kora, a mêlé musique mandingue et sons électroniques."),
    (4, "Quel genre sud-africain, né dans les townships de Johannesburg dans les années 1990, mêle house et rythmes locaux ?",
     "Le kwaito", ["Le mbalax", "Le highlife", "Le zouglou", "Le raï"],
     "Le kwaito a accompagné les années qui ont suivi la fin de l'apartheid."),
    (4, "Quel genre festif né à Paris au début des années 2000 dans la diaspora ivoirienne s'est répandu en Afrique ?",
     "Le coupé-décalé", ["Le mbalax", "Le kwaito", "Le highlife", "Le raï"],
     "Il est associé à Douk Saga et à l'ambiance des soirées parisiennes avant de gagner Abidjan."),
    (5, "Quel genre ivoirien est né dans les années 1990 sur les campus universitaires d'Abidjan ?",
     "Le zouglou", ["Le coupé-décalé", "Le mapouka", "Le highlife", "Le makossa"],
     "Le zouglou, chanté par des étudiants, est apparu en 1990 avec le groupe Les Parents du Campus."),
    (4, "Quel musicien éthiopien est considéré comme le père de l'éthio-jazz ?",
     "Mulatu Astatke", ["Tilahun Gessesse", "Manu Dibango", "Hugh Masekela", "Fela Kuti"],
     "Il a mêlé jazz, musiques latines et gammes éthiopiennes."),
    (3, "Comment s'appelle la danse maasaï où les jeunes guerriers sautent le plus haut possible ?",
     "L'adumu", ["L'azonto", "Le gumboot", "Le mapouka", "Le kizomba"],
     "On l'appelle aussi la danse du saut ; elle fait partie d'une cérémonie de passage."),
    (3, "Quelle danse sud-africaine, née chez les mineurs, se pratique avec des bottes en caoutchouc ?",
     "Le gumboot", ["L'adumu", "L'azonto", "Le coupé-décalé", "Le kizomba"],
     "Dans les mines, des ouvriers ont fait des bottes un instrument de rythme."),
    (4, "Quel pays est le berceau du kizomba et du semba ?",
     "L'Angola", ["Le Mozambique", "Le Cap-Vert", "La Guinée-Bissau", "Le Congo"],
     "Le semba est une musique angolaise populaire ; le kizomba s'en est inspiré dans les années 1980."),
])

# ------------------------------------------------------------------------------------------- littérature
rows("af-culture", "AF", "Afrique : littérature", [
    (4, "En quelle année Chinua Achebe a-t-il publié « Le monde s'effondre » (Things Fall Apart) ?",
     "1958", ["1948", "1962", "1966", "1975"],
     "Le roman, qui se passe chez les Igbo à l'arrivée des colons britanniques, est l'un des livres africains les plus lus au monde."),
    (3, "Quel roman de Chimamanda Ngozi Adichie, paru en 2003, a pour titre en français « L'Hibiscus pourpre » ?",
     "Purple Hibiscus", ["Americanah", "Half of a Yellow Sun", "Things Fall Apart", "Nervous Conditions"],
     "C'est le premier roman de l'autrice nigériane."),
    (4, "Quel roman de Chimamanda Ngozi Adichie, publié en 2006, se déroule pendant la guerre du Biafra ?",
     "L'Autre Moitié du soleil (Half of a Yellow Sun)", ["Americanah", "L'Hibiscus pourpre", "Autour de ton cou", "Nous sommes tous des féministes"],
     "La guerre du Biafra a opposé le Nigeria à la région sécessionniste de 1967 à 1970."),
    (3, "Quel poète sénégalais est entré à l'Académie française en 1983, premier Africain à y siéger ?",
     "Léopold Sédar Senghor", ["Aimé Césaire", "Birago Diop", "Cheikh Hamidou Kane", "Ousmane Sembène"],
     "Il fut aussi le premier président du Sénégal, de 1960 à 1980."),
    (3, "Quel écrivain égyptien est le premier auteur de langue arabe à avoir reçu le prix Nobel de littérature, en 1988 ?",
     "Naguib Mahfouz", ["Taha Hussein", "Tawfiq al-Hakim", "Albert Cossery", "Tahar Ben Jelloun"],
     "Sa Trilogie du Caire décrit trois générations d'une famille de la capitale."),
    (3, "Quelle romancière sud-africaine a reçu le prix Nobel de littérature en 1991 ?",
     "Nadine Gordimer", ["Doris Lessing", "Toni Morrison", "Olive Schreiner", "Bessie Head"],
     "Ses romans ont dénoncé les effets de l'apartheid."),
    (4, "Quel romancier sud-africain a reçu le prix Nobel de littérature en 2003 ?",
     "J. M. Coetzee", ["André Brink", "Alan Paton", "Breyten Breytenbach", "Wole Soyinka"],
     "Il est l'auteur de Disgrâce, publié en 1999."),
    (2, "Dans quel pays d'Afrique est né Albert Camus, prix Nobel de littérature en 1957 ?",
     "En Algérie", ["En Tunisie", "Au Maroc", "En Égypte", "Au Sénégal"],
     "Il est né en 1913 à Mondovi (aujourd'hui Dréan), dans l'est de l'Algérie."),
    (4, "Quel écrivain né à Zanzibar a reçu le prix Nobel de littérature en 2021 ?",
     "Abdulrazak Gurnah", ["Ngũgĩ wa Thiong'o", "Wole Soyinka", "J. M. Coetzee", "Chinua Achebe"],
     "Il écrit en anglais ; son roman Paradis (1994) se déroule en Afrique de l'Est au début du XXe siècle."),
    (4, "Quel romancier kényan a choisi d'écrire désormais en kikuyu plutôt qu'en anglais, à la fin des années 1970 ?",
     "Ngũgĩ wa Thiong'o", ["Chinua Achebe", "Meja Mwangi", "Wole Soyinka", "Nuruddin Farah"],
     "Il a défendu l'usage des langues africaines dans la littérature, notamment dans l'essai Décoloniser l'esprit."),
    (5, "Quel auteur malien a reçu le prix Renaudot en 1968 pour « Le Devoir de violence » ?",
     "Yambo Ouologuem", ["Ahmadou Kourouma", "Amadou Hampâté Bâ", "Seydou Badian", "Moussa Konaté"],
     "Il fut le premier écrivain africain à recevoir le Renaudot."),
    (4, "Quel romancier algérien a signé « Nedjma » (1956) ?",
     "Kateb Yacine", ["Mohammed Dib", "Mouloud Feraoun", "Albert Camus", "Assia Djebar"],
     "Ce roman éclaté est devenu l'un des textes majeurs de la littérature maghrébine francophone."),
    (4, "Quel écrivain marocain a reçu le prix Goncourt en 1987 pour « La Nuit sacrée » ?",
     "Tahar Ben Jelloun", ["Driss Chraïbi", "Abdellatif Laâbi", "Mohamed Choukri", "Fouad Laroui"],
     "« La Nuit sacrée » prolonge le roman « L'Enfant de sable » (1985)."),
    (4, "Quelle romancière franco-marocaine a reçu le prix Goncourt 2016 pour « Chanson douce » ?",
     "Leïla Slimani", ["Fouad Laroui", "Maryse Condé", "Marie NDiaye", "Yasmina Reza"],
     "Le roman a pour point de départ un fait divers new-yorkais."),
    (5, "Quel roman d'Alan Paton, publié en 1948, est un classique de la littérature sud-africaine ?",
     "Pleure, ô pays bien-aimé", ["Disgrâce", "Le Conservateur", "Le Monde s'effondre", "Nervous Conditions"],
     "Son titre anglais est Cry, the Beloved Country."),
    (5, "Quel recueil, publié en 1945, est le premier recueil de poèmes de Léopold Sédar Senghor ?",
     "Chants d'ombre", ["Hosties noires", "Éthiopiques", "Nocturnes", "Lettres d'hivernage"],
     "Senghor a publié ensuite Hosties noires (1948) puis Éthiopiques (1956)."),
    (5, "Quelle autrice zimbabwéenne a publié le roman « Nervous Conditions » en 1988 ?",
     "Tsitsi Dangarembga", ["Chimamanda Ngozi Adichie", "Nadine Gordimer", "Bessie Head", "Doris Lessing"],
     "C'est le premier roman en anglais publié par une femme noire du Zimbabwe."),
    (3, "Quel mouvement littéraire et culturel, lancé dans les années 1930 par Senghor, Césaire et Damas, affirme la fierté noire ?",
     "La négritude", ["L'ubuntu", "Le panafricanisme", "L'ujamaa", "Le surréalisme"],
     "Le mot est apparu sous la plume d'Aimé Césaire dans Cahier d'un retour au pays natal (1939)."),
])

# œuvres et auteurs
table("af-culture", "AF", "Afrique : littérature",
      [("Mariama Bâ", "Une si longue lettre", 3), ("Cheikh Hamidou Kane", "L'Aventure ambiguë", 4),
       ("Ousmane Sembène", "Les Bouts de bois de Dieu", 4), ("Ahmadou Kourouma", "Les Soleils des indépendances", 4),
       ("Albert Camus", "L'Étranger", 2), ("Mohammed Dib", "La Grande Maison", 5), ("Mouloud Feraoun", "Le Fils du pauvre", 5),
       ("Naguib Mahfouz", "Impasse des deux palais", 5), ("Tayeb Salih", "Saison de la migration vers le nord", 5),
       ("Yasmina Khadra", "Ce que le jour doit à la nuit", 5), ("Camara Laye", "L'Enfant noir", 3),
       ("Abdulrazak Gurnah", "Paradis", 5), ("J. M. Coetzee", "Disgrâce", 4), ("Amadou Hampâté Bâ", "Amkoullel, l'enfant peul", 5)],
      "Laquelle de ces œuvres a été écrite par {a} ?", "Qui est l'auteur ou l'autrice de l'œuvre « {b} » ?",
      diff=4, expl="« {b} » est une œuvre de {a}.")

# ------------------------------------------------------------------------------------------- cinéma
rows("af-culture", "AF", "Afrique : cinéma", [
    (2, "Dans quelle ville se tient tous les deux ans le FESPACO, grand festival du cinéma africain ?",
     "À Ouagadougou", ["À Dakar", "À Abidjan", "À Tunis", "À Cotonou"],
     "Le FESPACO, né en 1969, est le Festival panafricain du cinéma et de la télévision de Ouagadougou."),
    (3, "Comment s'appelle le grand prix du FESPACO, du nom d'une princesse légendaire ?",
     "L'Étalon de Yennenga", ["Le Tanit d'or", "Le Lion d'or", "Le Baobab d'or", "La Palme d'or africaine"],
     "Selon la légende, la princesse Yennenga est l'ancêtre des Mossi du Burkina Faso."),
    (5, "En quelle année la première Semaine du cinéma africain, ancêtre du FESPACO, a-t-elle eu lieu à Ouagadougou ?",
     "1969", ["1960", "1975", "1980", "1990"],
     "Le festival a pris son nom actuel, FESPACO, en 1972."),
    (3, "Quel réalisateur sénégalais est souvent surnommé « le père du cinéma africain » ?",
     "Ousmane Sembène", ["Souleymane Cissé", "Djibril Diop Mambéty", "Idrissa Ouédraogo", "Youssef Chahine"],
     "Il est aussi romancier : il a adapté lui-même plusieurs de ses livres."),
    (5, "Quel film de 1966 d'Ousmane Sembène est souvent considéré comme le premier long métrage de fiction réalisé par un cinéaste d'Afrique subsaharienne ?",
     "La Noire de…", ["Touki Bouki", "Yeelen", "Borom Sarret", "Xala"],
     "Le film raconte l'histoire d'une jeune Sénégalaise employée de maison en France."),
    (5, "Quel réalisateur sénégalais a signé « Touki Bouki » (1973) ?",
     "Djibril Diop Mambéty", ["Ousmane Sembène", "Souleymane Cissé", "Moussa Sene Absa", "Safi Faye"],
     "Le titre signifie « Le Voyage de la hyène » en wolof."),
    (5, "Quel réalisateur malien a reçu le prix du jury à Cannes en 1987 pour « Yeelen » (« la lumière ») ?",
     "Souleymane Cissé", ["Ousmane Sembène", "Abderrahmane Sissako", "Idrissa Ouédraogo", "Mahamat-Saleh Haroun"],
     "Yeelen est ancré dans les traditions bambara."),
    (5, "Quel réalisateur burkinabè a reçu le Grand Prix du jury à Cannes en 1990 pour « Tilaï » ?",
     "Idrissa Ouédraogo", ["Gaston Kaboré", "Souleymane Cissé", "Ousmane Sembène", "Abderrahmane Sissako"],
     "Tilaï, tourné en langue mooré, a aussi remporté l'Étalon de Yennenga au FESPACO."),
    (5, "Quel réalisateur égyptien a reçu en 1997 le prix du cinquantenaire du festival de Cannes pour l'ensemble de son œuvre ?",
     "Youssef Chahine", ["Ousmane Sembène", "Abderrahmane Sissako", "Merzak Allouache", "Nouri Bouzid"],
     "Cette année-là, il présentait son film « Le Destin »."),
    (4, "Quel réalisateur mauritanien a signé « Timbuktu » (2014), film nommé aux Oscars ?",
     "Abderrahmane Sissako", ["Souleymane Cissé", "Mahamat-Saleh Haroun", "Gaston Kaboré", "Idrissa Ouédraogo"],
     "Le film a remporté sept Césars en 2015."),
    (4, "Quel film sud-africain a remporté l'Oscar du meilleur film en langue étrangère en 2006 ?",
     "Tsotsi", ["Timbuktu", "District 9", "Yeelen", "Invictus"],
     "Réalisé par Gavin Hood, le film se passe dans un township de Johannesburg."),
    (1, "Comment appelle-t-on l'industrie cinématographique du Nigeria, l'une des plus prolifiques au monde ?",
     "Nollywood", ["Afrowood", "Lagoswood", "Nigeriawood", "Abujawood"],
     "Nollywood produit surtout des films tournés rapidement, souvent distribués en vidéo, depuis les années 1990."),
    (2, "Quel film réalisé par Clint Eastwood en 2009 raconte la Coupe du monde de rugby de 1995 en Afrique du Sud ?",
     "Invictus", ["Gran Torino", "Million Dollar Baby", "Cry Freedom", "Hotel Rwanda"],
     "Morgan Freeman y joue Nelson Mandela, Matt Damon le capitaine François Pienaar."),
])

# ------------------------------------------------------------------------------------------- cuisines
rows("af-culture", "AF", "Afrique : cuisines", [
    (3, "Quelle céréale à très petits grains sert traditionnellement à préparer l'injera éthiopienne ?",
     "Le teff", ["Le blé", "Le maïs", "Le riz", "Le manioc"],
     "La pâte de teff est laissée à fermenter avant d'être cuite en une grande galette spongieuse."),
    (2, "Quelle galette spongieuse sert à la fois d'assiette et de couvert dans la cuisine éthiopienne ?",
     "L'injera", ["Le fufu", "Le couscous", "Le pain pita", "L'ugali"],
     "On la découpe avec les doigts pour saisir les ragoûts."),
    (4, "Quel plat éthiopien est un ragoût de poulet épicé, accompagné d'œufs durs ?",
     "Le doro wat", ["Le kitfo", "Le shiro", "Le tibs", "Le koshari"],
     "Il est préparé avec du berbéré et du beurre clarifié."),
    (4, "Comment s'appelle le mélange d'épices pimenté à la base de nombreux plats éthiopiens ?",
     "Le berbéré", ["Le ras el-hanout", "La harissa", "Le garam masala", "Le dukkah"],
     "Il associe piments, ail, gingembre et épices."),
    (2, "Quel pays est considéré comme le berceau du caféier, selon la légende du berger Kaldi ?",
     "L'Éthiopie", ["Le Kenya", "L'Ouganda", "La Tanzanie", "La Côte d'Ivoire"],
     "Le caféier est originaire des hauts plateaux éthiopiens ; la cérémonie du café y est un moment de partage."),
    (2, "Quel plat sénégalais associe riz, poisson et légumes dans une même marmite ?",
     "Le thiéboudienne", ["Le mafé", "Le yassa", "Le fufu", "L'attiéké"],
     "Le « ceebu jën » a été inscrit au patrimoine culturel immatériel de l'UNESCO en 2021."),
    (3, "Quel plat ouest-africain est un riz mijoté dans une sauce tomate épicée, objet d'une rivalité amicale entre plusieurs pays ?",
     "Le riz jollof", ["Le fufu", "Le couscous", "Le bobotie", "Le koshari"],
     "Le nom vient peut-être des Wolofs, d'où le Sénégal est parfois cité comme berceau du plat."),
    (4, "Quels pays ont fait inscrire ensemble le couscous au patrimoine immatériel de l'UNESCO en 2020 ?",
     "L'Algérie, le Maroc, la Mauritanie et la Tunisie", ["L'Égypte, la Libye, le Soudan et l'Éthiopie", "Le Sénégal, le Mali, le Niger et le Tchad",
                                                          "Le Maroc, l'Algérie, la Tunisie et la Libye", "L'Égypte, le Maroc, la Tunisie et l'Algérie"],
     "La candidature était portée conjointement par ces quatre pays."),
    (2, "De quoi le couscous maghrébin est-il traditionnellement fait ?",
     "De semoule de blé dur", ["De farine de manioc", "De riz concassé", "De pommes de terre", "De lentilles"],
     "La semoule est roulée à la main, humidifiée, puis cuite à la vapeur."),
    (2, "Quelle pâte élastique, obtenue en pilant du manioc, de l'igname ou de la banane plantain, accompagne les sauces d'Afrique de l'Ouest et centrale ?",
     "Le fufu", ["L'injera", "Le couscous", "Le tajine", "Le bobotie"],
     "On la forme en boule et on la trempe dans la sauce."),
    (3, "Quel plat sud-africain d'origine cap-malaise associe de la viande hachée épicée et un nappage d'œufs battus cuit au four ?",
     "Le bobotie", ["Le bunny chow", "Le boerewors", "Le biltong", "Le pap"],
     "Le bobotie est très lié à la cuisine des Malais du Cap."),
    (4, "Dans quelle ville est né le bunny chow, pain évidé rempli de curry ?",
     "Durban", ["Le Cap", "Johannesburg", "Pretoria", "Port Elizabeth"],
     "Ce plat a été popularisé par la communauté d'origine indienne de Durban."),
    (3, "Que désigne le « biltong » sud-africain ?",
     "De la viande séchée et assaisonnée", ["Une saucisse grillée", "Une bière de maïs", "Un pain sucré", "Un ragoût de légumes"],
     "Le biltong se prépare avec du bœuf ou du gibier, souvent salé et épicé."),
    (3, "Comment les Sud-Africains appellent-ils le barbecue en afrikaans ?",
     "Le braai", ["Le biltong", "Le pap", "Le boerewors", "Le potjie"],
     "Le braai est un moment de rencontre très populaire."),
    (3, "Quel plat égyptien très populaire mêle riz, lentilles, pâtes et sauce tomate ?",
     "Le koshari", ["Le ful medames", "Le tajine", "Le mafé", "Le doro wat"],
     "Il est souvent présenté comme le plat national égyptien."),
    (3, "Quelle tourte feuilletée marocaine associe traditionnellement volaille, amandes et cannelle ?",
     "La pastilla", ["La brik", "Le bobotie", "Le mafé", "Le koshari"],
     "Elle mêle le salé et le sucré, parfois saupoudrée de sucre glace."),
    (3, "Quel beignet fin tunisien est garni d'œuf, de thon et de persil, puis frit ?",
     "La brik", ["La chakchouka", "La harira", "Le tajine", "Le couscous"],
     "La brik à l'œuf est un classique de la cuisine tunisienne."),
    (2, "Quelle pâte de piment, d'ail et d'épices est un condiment emblématique de la Tunisie ?",
     "La harissa", ["Le berbéré", "Le tahini", "Le pili pili", "Le chakalaka"],
     "La harissa se sert avec de l'huile d'olive, en accompagnement de nombreux plats."),
    (3, "Quelle soupe épaisse marocaine, riche en tomates, lentilles et pois chiches, est un plat de saison froide très apprécié ?",
     "La harira", ["La chorba frik", "La brik", "Le koshari", "Le mafé"],
     "On la sert souvent avec des dattes et du pain."),
    (1, "Quelle boisson est un symbole de l'hospitalité marocaine ?",
     "Le thé à la menthe", ["Le rooibos", "Le bissap", "Le café turc", "Le karkadé"],
     "Il se verse de haut dans de petits verres, ce qui crée un peu de mousse."),
    (3, "À base de quoi est fait l'attiéké, spécialité ivoirienne ?",
     "De manioc râpé et fermenté", ["De banane plantain", "D'igname pilée", "De maïs", "De riz"],
     "On le sert avec du poisson grillé ou du poulet."),
    (3, "Quel plat d'Afrique de l'Ouest se prépare avec une sauce à base de pâte d'arachide ?",
     "Le mafé", ["Le yassa", "Le thiéboudienne", "L'attiéké", "Le kedjenou"],
     "Le mafé est répandu au Mali, au Sénégal et dans les pays voisins."),
    (3, "Quel plat sénégalais, originaire de Casamance, marine du poulet dans une sauce d'oignons et de citron ?",
     "Le poulet yassa", ["Le mafé", "Le thiéboudienne", "Le domoda", "Le foutou"],
     "Le citron et l'oignon cuit longuement donnent au yassa son goût acidulé."),
    (3, "Quelle bouillie de maïs ferme est un aliment de base en Afrique de l'Est, notamment au Kenya et en Tanzanie ?",
     "L'ugali", ["Le fufu", "Le couscous", "L'attiéké", "Le bobotie"],
     "On la façonne à la main pour prendre la sauce ou les légumes."),
    (4, "Comment appelle-t-on la bouillie de maïs de base au Zimbabwe ?",
     "La sadza", ["L'ugali", "La nshima", "Le fufu", "L'injera"],
     "On la mange avec de la viande, des légumes ou une sauce."),
    (2, "Comment appelle-t-on en Afrique de l'Ouest la boisson rouge à base de fleurs d'hibiscus ?",
     "Le bissap", ["Le gnamakoudji", "Le tchoukoutou", "Le dolo", "Le rooibos"],
     "On la sert bien fraîche, souvent parfumée à la menthe ou à la vanille."),
    (4, "Quel pain de manioc fermenté, cuit à la vapeur dans des feuilles, est typique d'Afrique centrale ?",
     "La chikwangue", ["L'attiéké", "Le gari", "Le fufu", "L'injera"],
     "On l'appelle aussi bâton de manioc."),
    (4, "Quel plat d'Afrique centrale est cuisiné avec une sauce à la noix de palme ?",
     "Le poulet à la moambé", ["Le mafé", "Le yassa", "Le kedjenou", "Le thiéboudienne"],
     "La moambé est consommée notamment au Gabon et au Congo."),
    (2, "Quel arbre d'Afrique de l'Ouest donne un beurre utilisé en cuisine et en cosmétique ?",
     "Le karité", ["Le baobab", "Le kolatier", "Le palmier à huile", "L'acacia"],
     "Le beurre de karité est tiré des noix de l'arbre, récoltées surtout par des femmes."),
    (3, "Dans quel pays pousse presque exclusivement le rooibos, infusion rouge sans théine ?",
     "En Afrique du Sud", ["Au Kenya", "Au Maroc", "En Éthiopie", "En Namibie"],
     "Il vient de la région montagneuse du Cederberg, dans l'ouest du pays."),
    (4, "Quel bouton floral séché a fait la renommée historique de Zanzibar, surnommée l'île aux épices ?",
     "Le clou de girofle", ["Le safran", "Le poivre noir", "La cannelle", "La vanille"],
     "Le sultanat de Zanzibar en a fait une grande culture au XIXe siècle."),
])

# ------------------------------------------------------------------------------------------- patrimoine
rows("af-culture", "AF", "Afrique : patrimoine", [
    (2, "Quelle est la plus grande des pyramides de Gizeh ?",
     "La pyramide de Khéops", ["La pyramide de Khéphren", "La pyramide de Mykérinos", "La pyramide de Djéser", "La pyramide de Snefrou"],
     "Elle a été construite vers 2560 av. J.-C. pour le pharaon Khéops."),
    (2, "Quelle est la seule des sept merveilles du monde antique encore debout ?",
     "La grande pyramide de Khéops", ["Le phare d'Alexandrie", "Le colosse de Rhodes", "Les jardins suspendus de Babylone", "Le temple d'Artémis"],
     "Les six autres ont disparu, détruites par des séismes, des incendies ou la guerre."),
    (4, "Quel pharaon a fait ériger la pyramide à degrés de Saqqara, première grande construction en pierre taillée d'Égypte ?",
     "Djéser", ["Khéops", "Ramsès II", "Toutânkhamon", "Akhenaton"],
     "Son architecte, Imhotep, est resté célèbre."),
    (3, "Quel temple égyptien a été déplacé dans les années 1960 pour échapper à la montée des eaux du haut barrage d'Assouan ?",
     "Abou Simbel", ["Karnak", "Louxor", "Deir el-Bahari", "Edfou"],
     "Le déplacement, soutenu par l'UNESCO, s'est déroulé de 1964 à 1968."),
    (3, "Quel pharaon a fait bâtir le grand temple d'Abou Simbel ?",
     "Ramsès II", ["Toutânkhamon", "Khéops", "Akhenaton", "Thoutmosis III"],
     "Les quatre statues colossales de la façade le représentent."),
    (3, "En quelle année Howard Carter a-t-il découvert la tombe de Toutânkhamon ?",
     "1922", ["1799", "1869", "1905", "1946"],
     "Les fouilles de la tombe, dans la Vallée des Rois, ont duré dix ans."),
    (4, "En quelle année la pierre de Rosette a-t-elle été découverte par des soldats de l'expédition de Bonaparte ?",
     "1799", ["1789", "1798", "1812", "1830"],
     "Elle a permis à Champollion de déchiffrer les hiéroglyphes en 1822."),
    (2, "Qui a déchiffré les hiéroglyphes égyptiens en 1822 ?",
     "Jean-François Champollion", ["Auguste Mariette", "Howard Carter", "Vivant Denon", "Napoléon Bonaparte"],
     "Il s'est appuyé sur la pierre de Rosette, qui porte le même texte en trois écritures."),
    (3, "Quel monument d'Alexandrie, élevé au IIIe siècle av. J.-C., comptait parmi les sept merveilles du monde antique ?",
     "Le phare de Pharos", ["Le temple de Sérapis", "La colonne de Pompée", "Le mausolée de Cléopâtre", "Le Sphinx"],
     "Il s'est effondré à la suite de plusieurs séismes entre le Xe et le XIVe siècle."),
    (3, "Quelle ville du Mali, centre de savoir avec ses manuscrits anciens et l'université de Sankoré, est inscrite à l'UNESCO ?",
     "Tombouctou", ["Gao", "Ségou", "Mopti", "Kayes"],
     "Les manuscrits de Tombouctou couvrent des siècles de sciences, de droit et de poésie."),
    (3, "Avec quel matériau la Grande Mosquée de Djenné est-elle construite ?",
     "De la terre crue (banco)", ["De la pierre calcaire", "Du marbre", "De la brique cuite", "Du bois"],
     "Chaque année, les habitants la recrépissent à la main, lors d'une fête collective."),
    (3, "Quel pays doit son nom à la cité de pierre du Grand Zimbabwe ?",
     "Le Zimbabwe", ["La Zambie", "Le Botswana", "Le Mozambique", "Le Malawi"],
     "« Zimbabwe » vient d'une expression shona qui désigne des maisons de pierre."),
    (4, "Quel emblème, retrouvé sculpté dans la pierre au Grand Zimbabwe, figure sur le drapeau du pays ?",
     "Un oiseau", ["Un lion", "Un éléphant", "Un serpent", "Un crocodile"],
     "Les oiseaux de pierre du Grand Zimbabwe sont devenus le symbole national."),
    (4, "Quelle ancienne ville d'Éthiopie est célèbre pour ses grandes stèles de pierre ?",
     "Aksoum", ["Gondar", "Harar", "Lalibela", "Dessie"],
     "Aksoum fut la capitale d'un puissant royaume entre l'Antiquité et le haut Moyen Âge."),
    (5, "Quelle ville d'Éthiopie est célèbre pour ses châteaux du XVIIe siècle, construits à partir de 1636 par l'empereur Fasilidas ?",
     "Gondar", ["Aksoum", "Harar", "Lalibela", "Dessie"],
     "Le complexe de Fasil Ghebbi est inscrit au patrimoine mondial."),
    (4, "Quelle ville du Maroc abrite l'université Al Quaraouiyine, fondée en 859 ?",
     "Fès", ["Marrakech", "Rabat", "Meknès", "Tanger"],
     "Elle fut fondée par Fatima al-Fihri, et passe pour l'une des plus anciennes universités encore en activité."),
    (3, "Quelle place de Marrakech est animée par des conteurs, des musiciens et des étals de jus d'orange ?",
     "La place Jemaa el-Fna", ["La place Tahrir", "La place des Martyrs", "La place de l'Indépendance", "La place Bourguiba"],
     "Elle est inscrite au patrimoine culturel immatériel de l'UNESCO depuis 2008."),
    (4, "Quel ksar fortifié en terre, près de Ouarzazate, a servi de décor à de nombreux films ?",
     "Aït-Ben-Haddou", ["Chinguetti", "Ghadamès", "Ghardaïa", "Tiébélé"],
     "Il est inscrit au patrimoine mondial depuis 1987."),
    (4, "Quelle ville tunisienne abrite la Grande Mosquée fondée en 670 ?",
     "Kairouan", ["Sousse", "Sfax", "Tunis", "Djerba"],
     "Kairouan fut l'une des premières villes fondées par les Arabes en Afrique du Nord."),
    (5, "Dans quelle ville se trouvait le palais du royaume du Bénin, dont de nombreux bronzes furent emportés par les Britanniques en 1897 ?",
     "Benin City, au Nigeria", ["Cotonou, au Bénin", "Porto-Novo, au Bénin", "Abomey, au Bénin", "Lagos, au Nigeria"],
     "Aujourd'hui, ces œuvres sont au cœur de débats sur la restitution du patrimoine."),
    (3, "Dans quel pays a été découvert en 1974 le squelette d'australopithèque surnommé « Lucy » ?",
     "En Éthiopie", ["Au Kenya", "En Tanzanie", "En Afrique du Sud", "Au Tchad"],
     "Lucy a été trouvée dans la région de l'Afar par une équipe dirigée par Donald Johanson."),
    (4, "Dans quelle gorge de Tanzanie la famille Leakey a-t-elle découvert de nombreux fossiles d'ancêtres de l'humain ?",
     "Olduvai", ["Ngorongoro", "Turkana", "Sterkfontein", "Fish River"],
     "Les fouilles d'Olduvai ont permis de découvrir plusieurs espèces d'hominidés."),
    (5, "Comment est surnommé le site des grottes de Sterkfontein, près de Johannesburg, classé à l'UNESCO ?",
     "Le berceau de l'humanité", ["La vallée des Rois", "Le toit de l'Afrique", "Le jardin d'Éden", "La terre des pharaons"],
     "Des fossiles d'hominidés y ont été mis au jour dès 1936."),
])

table("af-culture", "AF", "Afrique : patrimoine et parcs",
      [("le temple d'Abou Simbel", "L'Égypte", 2), ("le temple de Karnak", "L'Égypte", 3),
       ("le site du Grand Zimbabwe", "Le Zimbabwe", 3), ("les palais royaux d'Abomey", "Le Bénin", 4),
       ("les ruines romaines de Volubilis", "Le Maroc", 3), ("les ruines romaines de Timgad", "L'Algérie", 4),
       ("les ruines de Leptis Magna", "La Libye", 4), ("l'amphithéâtre d'El Jem", "La Tunisie", 4),
       ("la vieille ville de Ghadamès", "La Libye", 5), ("le site de Kilwa Kisiwani", "La Tanzanie", 5),
       ("les peintures rupestres du Tassili n'Ajjer", "L'Algérie", 5), ("le site de Mapungubwe", "L'Afrique du Sud", 5),
       ("le parc national de Kruger", "L'Afrique du Sud", 2), ("la réserve du Masai Mara", "Le Kenya", 3),
       ("le parc national d'Amboseli, au pied du Kilimandjaro", "Le Kenya", 3), ("le cratère du Ngorongoro", "La Tanzanie", 3),
       ("le parc national d'Etosha", "La Namibie", 3), ("les dunes de Sossusvlei", "La Namibie", 4),
       ("le parc national de Chobe, réputé pour ses éléphants", "Le Botswana", 4), ("le parc national de Hwange", "Le Zimbabwe", 5),
       ("le parc national des Volcans, où vivent des gorilles de montagne", "Le Rwanda", 4),
       ("la forêt impénétrable de Bwindi", "L'Ouganda", 4), ("le parc national de Virunga", "La République démocratique du Congo", 4),
       ("le parc national de la Lopé", "Le Gabon", 5), ("le parc national de la Pendjari", "Le Bénin", 5),
       ("les monts Simien", "L'Éthiopie", 4), ("le parc national du Djoudj, refuge d'oiseaux migrateurs", "Le Sénégal", 5),
       ("le delta du Saloum", "Le Sénégal", 5)],
      "Dans quel pays se trouve {a} ?", None, diff=3, expl="{a} : {b}.")

# ------------------------------------------------------------------------------------------- géographie et nature
rows("af-culture", "AF", "Afrique : nature", [
    (2, "Quels animaux forment les « Big Five » de la savane africaine ?",
     "Le lion, le léopard, l'éléphant, le buffle et le rhinocéros",
     ["Le lion, la girafe, le zèbre, le guépard et l'hippopotame", "Le lion, le léopard, la hyène, le zèbre et le gnou",
      "Le guépard, la girafe, l'éléphant, le buffle et le crocodile", "Le lion, le léopard, l'éléphant, le zèbre et la girafe"],
     "L'expression vient des chasseurs, qui jugeaient ces cinq animaux les plus dangereux à pied."),
    (2, "Lequel de ces animaux fait partie des « Big Five » ?",
     "Le rhinocéros", ["La girafe", "Le guépard", "L'hippopotame", "Le zèbre"],
     "Aujourd'hui, les Big Five sont surtout un repère pour les safaris photographiques."),
    (1, "Quel félin d'Afrique est le plus rapide des animaux terrestres ?",
     "Le guépard", ["Le lion", "Le léopard", "Le lynx", "Le serval"],
     "Il peut dépasser 100 km/h sur de courtes distances."),
    (1, "Quel est le plus haut de tous les animaux terrestres ?",
     "La girafe", ["L'éléphant", "Le rhinocéros", "L'autruche", "Le zèbre"],
     "Son long cou compte, comme le nôtre, sept vertèbres."),
    (1, "Quel est le plus grand animal terrestre actuel ?",
     "L'éléphant d'Afrique", ["Le rhinocéros blanc", "L'hippopotame", "La girafe", "Le buffle"],
     "L'éléphant de savane d'Afrique peut dépasser six tonnes."),
    (3, "Quel fleuve les gnous traversent-ils lors de leur grande migration entre le Serengeti et le Masai Mara ?",
     "La Mara", ["La Tana", "Le Zambèze", "Le Limpopo", "La Galana"],
     "La traversée de la Mara est l'un des grands spectacles de la migration."),
    (4, "Que fait le delta de l'Okavango, au Botswana ?",
     "Il se perd dans le désert du Kalahari sans atteindre la mer", ["Il se jette dans l'Atlantique", "Il alimente le lac Victoria", "Il rejoint le Zambèze",
                                                                       "Il s'assèche complètement chaque année"],
     "Les crues, venues d'Angola, s'étalent chaque année dans la zone sèche."),
    (4, "Quel animal forestier de la RDC, aux pattes rayées comme celles d'un zèbre, est le plus proche parent de la girafe ?",
     "L'okapi", ["Le bongo", "Le sitatunga", "Le gnou", "Le zèbre de Grévy"],
     "L'okapi est resté inconnu des scientifiques jusqu'au début du XXe siècle."),
    (4, "Dans quel pays vivent les bonobos à l'état sauvage ?",
     "En République démocratique du Congo", ["Au Cameroun", "Au Gabon", "En Tanzanie", "En Ouganda"],
     "Les bonobos vivent au sud du fleuve Congo, seulement dans ce pays."),
    (2, "Sur quelle grande île africaine vivent naturellement les lémuriens ?",
     "À Madagascar", ["À Zanzibar", "À Maurice", "À Bioko", "À Sao Tomé"],
     "Ces primates ont évolué isolés à Madagascar depuis des millions d'années."),
    (4, "Quel animal d'Afrique est surnommé « cochon de terre » en afrikaans ?",
     "L'oryctérope", ["Le pangolin", "Le phacochère", "Le daman", "Le suricate"],
     "Il se nourrit de termites et de fourmis qu'il capture avec sa longue langue."),
    (2, "Quel petit renard du Sahara est reconnaissable à ses très grandes oreilles ?",
     "Le fennec", ["Le chacal", "Le renard polaire", "Le coyote", "Le dingo"],
     "Ses oreilles l'aident à repérer les proies et à évacuer la chaleur."),
    (1, "Quel animal des caravanes sahariennes ne possède qu'une seule bosse ?",
     "Le dromadaire", ["Le chameau de Bactriane", "Le lama", "L'alpaga", "Le zébu"],
     "Le chameau de Bactriane, lui, en a deux."),
    (3, "Quel parc national de la RDC, créé en 1925 sous le nom de parc Albert, abrite des gorilles de montagne ?",
     "Le parc des Virunga", ["Le parc de Kruger", "Le parc du Serengeti", "Le parc de Chobe", "Le parc d'Etosha"],
     "C'est l'un des plus anciens parcs nationaux d'Afrique."),
    (5, "Quel président de la République sud-africaine (Transvaal) a créé en 1898 la réserve qui deviendra le parc national Kruger ?",
     "Paul Kruger", ["Cecil Rhodes", "Louis Botha", "Jan Smuts", "Piet Retief"],
     "Le parc Kruger a été officiellement créé en 1926."),
    (3, "Pourquoi appelle-t-on le baobab « l'arbre à l'envers » ?",
     "Ses branches nues ressemblent à des racines", ["Il pousse la tête en bas dans le sable", "Ses fruits poussent sous terre",
                                                      "Ses racines sortent chaque saison", "Il tourne avec le soleil"],
     "Le baobab perd ses feuilles une grande partie de l'année : sa cime paraît faite de racines."),
    (3, "Quel arbre figure sur les armoiries du Sénégal ?",
     "Le baobab", ["Le karité", "Le palmier", "L'acacia", "Le fromager"],
     "Le baobab y symbolise la force et la longévité."),
    (5, "Sur les huit espèces de baobabs (Adansonia) connues, combien ne se trouvent naturellement qu'à Madagascar ?",
     "Six", ["Deux", "Trois", "Huit", "Une"],
     "Une espèce vit en Afrique continentale et une autre en Australie."),
    (5, "Quelle plante du Namib, qui ne porte que deux feuilles, peut vivre plusieurs siècles ?",
     "La welwitschia", ["Le baobab", "L'aloès", "Le protée", "Le lithops"],
     "Ses deux feuilles continuent de pousser toute sa vie, en se déchirant en lanières."),
    (3, "Quelle fleur est l'emblème national de l'Afrique du Sud ?",
     "Le protée royal", ["L'orchidée", "Le lotus bleu", "Le jacaranda", "L'hibiscus"],
     "Le protée royal pousse dans la région florale du Cap."),
    (2, "Quel animal est l'emblème de l'équipe nationale sud-africaine de rugby ?",
     "Le springbok", ["Le gnou", "Le léopard", "L'éléphant", "Le zèbre"],
     "On appelle les joueurs les Springboks, du nom d'une antilope."),
    (4, "Quel massif, à la frontière entre l'Ouganda et la RDC, était surnommé « montagnes de la Lune » ?",
     "Le Ruwenzori", ["Le Drakensberg", "Le Haut Atlas", "Les monts Simien", "Le mont Cameroun"],
     "Le nom « montagnes de la Lune » remonte à l'Antiquité."),
    (4, "Quel est le plus haut sommet d'Afrique du Nord, situé dans le Haut Atlas ?",
     "Le Toubkal", ["Le Tahat", "Le Chelia", "Le Ras Dashen", "Le mont Kenya"],
     "Le Toubkal, au Maroc, culmine à 4 167 mètres."),
    (5, "Quel est le plus haut sommet d'Éthiopie, dans les monts Simien ?",
     "Le Ras Dashen", ["Le Kilimandjaro", "Le mont Kenya", "Le Toubkal", "Le mont Stanley"],
     "Ras Dashen est l'un des plus hauts sommets d'Afrique."),
    (5, "Quel lac de Djibouti est le point le plus bas d'Afrique ?",
     "Le lac Assal", ["Le lac Abbé", "Le lac Turkana", "Le lac Natron", "Le lac Tana"],
     "Il se trouve à environ 155 mètres sous le niveau de la mer."),
    (5, "Quelle dépression d'Éthiopie, l'une des régions les plus chaudes de la planète, abrite le volcan Erta Ale ?",
     "Le Danakil", ["Le Ténéré", "Le Kalahari", "Le désert de Libye", "Le Rift de Turkana"],
     "Ses paysages colorés de sel et de soufre attirent des voyageurs."),
    (3, "Quel projet africain lancé en 2007 vise à planter des arbres à travers le Sahel pour freiner la désertification ?",
     "La Grande Muraille verte", ["Le Grand Barrage de la Renaissance", "Le corridor de Lobito", "Le Transsaharien", "Le Grand Canal du Sahel"],
     "Il a été lancé sous l'égide de l'Union africaine."),
    (4, "Quel cap sud-africain marque le point le plus méridional du continent africain ?",
     "Le cap des Aiguilles", ["Le cap de Bonne-Espérance", "Le cap Vert", "Le cap Guardafui", "Le cap Bon"],
     "Il est situé à l'est du cap de Bonne-Espérance, où se rencontrent l'Atlantique et l'océan Indien."),
    (4, "Quel point proche de Dakar est le plus occidental de l'Afrique continentale ?",
     "La pointe des Almadies", ["Le cap Bojador", "Le cap Spartel", "Le cap Blanc", "Le cap Lopez"],
     "Il se trouve sur la presqu'île du Cap-Vert."),
    (3, "Comment s'appelle le lac sénégalais dont les eaux salées peuvent paraître roses ?",
     "Le lac Rose (lac Retba)", ["Le lac de Guiers", "Le lac Tchad", "Le lac Nasser", "Le lac Bosumtwi"],
     "Sa couleur vient de micro-organismes qui prospèrent dans l'eau très salée."),
    (4, "Quel est le nom local des chutes Victoria, qui signifie « la fumée qui gronde » ?",
     "Mosi-oa-Tunya", ["Kalambo", "Murchison", "Tugela", "Ruacana"],
     "Les embruns sont visibles à des kilomètres."),
    (3, "Quel explorateur britannique a donné son nom aux chutes Victoria en 1855 ?",
     "David Livingstone", ["Henry Morton Stanley", "Mungo Park", "Richard Burton", "John Speke"],
     "Il les a baptisées en l'honneur de la reine Victoria."),
])

# ------------------------------------------------------------------------------------------- football : CAN et Coupes du monde
rows("af-culture", "AF", "Afrique : football", [
    (3, "En quelle année a eu lieu la première Coupe d'Afrique des nations de football ?",
     "1957", ["1950", "1960", "1963", "1970"],
     "Elle s'est jouée à Khartoum avec seulement trois équipes : l'Égypte, le Soudan et l'Éthiopie."),
    (4, "Quel pays a remporté la première Coupe d'Afrique des nations, en 1957 ?",
     "L'Égypte", ["Le Soudan", "L'Éthiopie", "Le Ghana", "Le Nigeria"],
     "L'Égypte a battu l'Éthiopie 4-0 en finale."),
    (4, "Dans quelle ville s'est jouée la première Coupe d'Afrique des nations, en 1957 ?",
     "Khartoum", ["Le Caire", "Addis-Abeba", "Accra", "Alger"],
     "L'Afrique du Sud devait participer mais n'a pas pu en raison de l'apartheid."),
    (3, "Quel pays a gagné trois Coupes d'Afrique des nations consécutives en 2006, 2008 et 2010 ?",
     "L'Égypte", ["Le Cameroun", "Le Ghana", "La Côte d'Ivoire", "Le Nigeria"],
     "L'Égypte détient le record de victoires dans la compétition."),
    (4, "Quelle équipe a remporté la CAN 1992, au Sénégal, après une séance de tirs au but face au Ghana ?",
     "La Côte d'Ivoire", ["Le Sénégal", "Le Nigeria", "Le Cameroun", "L'Algérie"],
     "Les Éléphants l'ont emporté 11 tirs au but à 10 après un 0-0 : c'était leur premier titre."),
    (3, "Quelle équipe a battu la Côte d'Ivoire aux tirs au but en finale de la CAN 2012, à Libreville ?",
     "La Zambie", ["Le Ghana", "Le Mali", "Le Sénégal", "Le Burkina Faso"],
     "La Zambie a gagné le seul titre de son histoire, 8 tirs au but à 7."),
    (4, "Quel pays a organisé et gagné la CAN 1990 ?",
     "L'Algérie", ["Le Maroc", "La Tunisie", "L'Égypte", "Le Cameroun"],
     "L'Algérie a battu le Nigeria 1-0 en finale à Alger."),
    (4, "Quel pays a remporté la CAN 1996, disputée chez lui peu après sa réintégration dans le football international ?",
     "L'Afrique du Sud", ["La Tunisie", "Le Nigeria", "Le Ghana", "La Zambie"],
     "Les Bafana Bafana ont battu la Tunisie 2-0 en finale."),
    (4, "Quelle équipe a gagné la CAN 2013 en Afrique du Sud, face au Burkina Faso ?",
     "Le Nigeria", ["Le Ghana", "Le Mali", "Le Cameroun", "L'Égypte"],
     "Le but de Sunday Mba a donné la victoire 1-0 aux Super Eagles."),
    (4, "Quelle équipe a remporté la CAN 2015 en Guinée équatoriale, face au Ghana, aux tirs au but ?",
     "La Côte d'Ivoire", ["Le Sénégal", "L'Algérie", "Le Mali", "Le Nigeria"],
     "La finale s'est conclue 9-8 aux tirs au but."),
    (4, "Quelle équipe a remporté sa première CAN en 1984, en Côte d'Ivoire, face au Nigeria ?",
     "Le Cameroun", ["Le Ghana", "L'Algérie", "L'Égypte", "La Côte d'Ivoire"],
     "Les Lions indomptables l'ont emporté 3-1."),
    (5, "Quel pays a remporté la CAN en 1968 et 1974 sous les noms de Congo-Kinshasa puis de Zaïre ?",
     "La République démocratique du Congo", ["Le Congo-Brazzaville", "Le Cameroun", "Le Ghana", "La Guinée"],
     "Le Congo-Brazzaville, lui, a gagné la CAN en 1972."),
    (4, "Quel pays a gagné les CAN 1963 et 1965 ?",
     "Le Ghana", ["L'Égypte", "Le Soudan", "Le Nigeria", "Le Cameroun"],
     "Les Black Stars ont ajouté deux titres, en 1978 et 1982."),
    (5, "Quel pays a remporté la CAN 1970, au Soudan ?",
     "Le Soudan", ["L'Égypte", "L'Éthiopie", "Le Ghana", "La Guinée"],
     "C'est le seul titre du Soudan dans la compétition."),
    (4, "Quel pays a remporté la CAN 1976, en Éthiopie ?",
     "Le Maroc", ["La Guinée", "Le Nigeria", "L'Égypte", "La Tunisie"],
     "Le tournoi s'est terminé sans finale : le Maroc a gagné une poule finale."),
    (4, "Quel pays a organisé et gagné la CAN 2004 ?",
     "La Tunisie", ["Le Maroc", "L'Algérie", "L'Égypte", "Le Sénégal"],
     "La Tunisie a battu le Maroc 2-1 en finale à Radès."),
    (3, "Quelle sélection africaine est la première à avoir participé à une Coupe du monde de football, en 1934 ?",
     "L'Égypte", ["Le Maroc", "La Tunisie", "L'Algérie", "Le Zaïre"],
     "Elle a perdu 4-2 contre la Hongrie, à Naples."),
    (5, "Quelle sélection d'Afrique subsaharienne a participé pour la première fois à une Coupe du monde, en 1974 ?",
     "Le Zaïre", ["Le Ghana", "Le Nigeria", "Le Cameroun", "La Côte d'Ivoire"],
     "Le Zaïre est aussi resté célèbre pour un lourd 0-9 contre la Yougoslavie."),
    (5, "Quelle sélection africaine a gagné, la première, un match de Coupe du monde, en 1978, face au Mexique ?",
     "La Tunisie", ["Le Maroc", "L'Égypte", "Le Zaïre", "L'Algérie"],
     "La Tunisie l'a emporté 3-1 en Argentine."),
    (4, "Quelle sélection africaine a battu l'Allemagne de l'Ouest 2-1 lors de la Coupe du monde 1982 ?",
     "L'Algérie", ["Le Cameroun", "Le Maroc", "L'Égypte", "La Tunisie"],
     "Ce match de Gijón reste célèbre : l'Algérie a pourtant été éliminée au bénéfice d'un autre résultat du groupe."),
    (5, "Quelle sélection africaine a été la première à terminer première de son groupe en Coupe du monde, en 1986 ?",
     "Le Maroc", ["L'Algérie", "Le Cameroun", "Le Nigeria", "La Tunisie"],
     "Le Maroc a devancé l'Angleterre, la Pologne et le Portugal, avant d'être éliminé par l'Allemagne de l'Ouest en huitièmes."),
    (3, "Quel attaquant camerounais, âgé de 38 ans, a marqué quatre buts à la Coupe du monde 1990 et dansé autour du poteau de corner ?",
     "Roger Milla", ["Samuel Eto'o", "Thomas N'Kono", "Rigobert Song", "Patrick M'Boma"],
     "Le Cameroun a été la première sélection africaine à atteindre les quarts de finale, battue par l'Angleterre."),
    (3, "Quelle équipe a battu la France, championne du monde en titre, lors du match d'ouverture de la Coupe du monde 2002 ?",
     "Le Sénégal", ["Le Cameroun", "Le Nigeria", "Le Ghana", "Le Maroc"],
     "Papa Bouba Diop a marqué l'unique but ; le Sénégal a ensuite atteint les quarts de finale."),
    (4, "Quel joueur uruguayen a arrêté de la main un but ghanéen sur la ligne, en quart de finale de la Coupe du monde 2010 ?",
     "Luis Suárez", ["Diego Forlán", "Edinson Cavani", "Diego Godín", "Sebastián Abreu"],
     "Le Ghana a manqué le penalty, puis perdu aux tirs au but."),
    (5, "Avant 2022, quelles sont les trois sélections africaines à avoir atteint les quarts de finale d'une Coupe du monde ?",
     "Le Cameroun, le Sénégal et le Ghana", ["Le Cameroun, le Nigeria et le Ghana", "Le Maroc, le Sénégal et la Tunisie",
                                              "Le Nigeria, l'Algérie et le Sénégal", "Le Ghana, la Côte d'Ivoire et le Cameroun"],
     "C'était en 1990, 2002 et 2010 respectivement."),
    (3, "Quel pays a accueilli la première Coupe du monde de football organisée en Afrique, en 2010 ?",
     "L'Afrique du Sud", ["Le Maroc", "L'Égypte", "Le Nigeria", "Le Cameroun"],
     "L'ouverture a eu lieu à Johannesburg, au stade Soccer City, qui accueillait aussi la finale."),
    (2, "Quelle équipe a gagné la Coupe du monde 2010, en Afrique du Sud ?",
     "L'Espagne", ["Les Pays-Bas", "L'Allemagne", "L'Uruguay", "Le Ghana"],
     "L'Espagne a battu les Pays-Bas 1-0 après prolongation, avec un but d'Iniesta."),
    (4, "Comment s'appelait le ballon officiel de la Coupe du monde 2010 ?",
     "Jabulani", ["Teamgeist", "Brazuca", "Tango", "Fevernova"],
     "Le nom signifie « célébrer » en zoulou."),
    (4, "Quelle était la mascotte de la Coupe du monde 2010, un léopard aux cheveux verts ?",
     "Zakumi", ["Footix", "Goleo VI", "Fuleco", "Striker"],
     "Le nom associe « ZA », pour l'Afrique du Sud, et « kumi », dix en plusieurs langues africaines."),
    (2, "Quelle chanteuse a signé la chanson « Waka Waka (This Time for Africa) », hymne de la Coupe du monde 2010 ?",
     "Shakira", ["Beyoncé", "Rihanna", "Jennifer Lopez", "Alicia Keys"],
     "Le refrain reprend un chant d'origine camerounaise."),
    (5, "Quel joueur a marqué le premier but de la Coupe du monde 2010, lors d'un 1-1 entre l'Afrique du Sud et le Mexique ?",
     "Siphiwe Tshabalala", ["Katlego Mphela", "Steven Pienaar", "Bernard Parker", "Benni McCarthy"],
     "Le but, d'une frappe lointaine, a déclenché la fête dans tout le pays."),
    (3, "Quelle sélection le Maroc a-t-il affrontée en demi-finale de la Coupe du monde 2022 ?",
     "La France", ["L'Argentine", "La Croatie", "Le Portugal", "L'Espagne"],
     "La France l'a emporté 2-0 ; le Maroc a ensuite terminé quatrième."),
    (3, "Quelle sélection le Maroc a-t-il éliminée aux tirs au but en huitièmes de finale de la Coupe du monde 2022 ?",
     "L'Espagne", ["La Belgique", "Le Portugal", "Le Brésil", "L'Allemagne"],
     "Le score était de 0-0 après prolongation, puis 3-0 aux tirs au but."),
])

# ------------------------------------------------------------------------------------------- CAN : année -> vainqueur
table("af-culture", "AF", "Afrique : football",
      [("en 1962", "L'Éthiopie", 5), ("en 1978", "Le Ghana", 5), ("en 1980", "Le Nigeria", 4), ("en 1982", "Le Ghana", 5),
       ("en 1988", "Le Cameroun", 4), ("en 1994", "Le Nigeria", 4), 
       ("en 2000", "Le Cameroun", 4), ("en 2002", "Le Cameroun", 4), ("en 1972", "Le Congo-Brazzaville", 5)],
      "Quel pays a remporté la Coupe d'Afrique des nations de football {a} ?", None, diff=4, expl="Vainqueur de la CAN {a} : {b}.")

# ------------------------------------------------------------------------------------------- rugby 1995 et Mandela
rows("af-culture", "AF", "Afrique : sport et société", [
    (3, "Contre quelle équipe l'Afrique du Sud a-t-elle gagné la finale de la Coupe du monde de rugby 1995 ?",
     "La Nouvelle-Zélande", ["L'Australie", "L'Angleterre", "La France", "L'Argentine"],
     "Les Springboks l'ont emporté 15-12 après prolongation, à Johannesburg."),
    (4, "Quel capitaine sud-africain a reçu le trophée des mains de Nelson Mandela en 1995 ?",
     "François Pienaar", ["Joost van der Westhuizen", "Os du Randt", "Chester Williams", "Siya Kolisi"],
     "Mandela portait le maillot vert et or des Springboks, floqué du numéro 6 de Pienaar."),
    (3, "Quel capitaine est devenu en 2019 le premier capitaine noir des Springboks à soulever la Coupe du monde de rugby ?",
     "Siya Kolisi", ["François Pienaar", "Bryan Habana", "Duane Vermeulen", "Eben Etzebeth"],
     "L'Afrique du Sud a battu l'Angleterre en finale, à Yokohama."),
    (2, "Quel acteur joue le rôle de Nelson Mandela dans le film Invictus (2009) ?",
     "Morgan Freeman", ["Denzel Washington", "Samuel L. Jackson", "Idris Elba", "Forest Whitaker"],
     "Matt Damon y interprète François Pienaar."),
    (2, "En quelle année Nelson Mandela a-t-il été libéré de prison ?",
     "1990", ["1985", "1988", "1992", "1994"],
     "Il est sorti de la prison Victor Verster le 11 février 1990."),
    (3, "Combien d'années Nelson Mandela a-t-il passé en prison ?",
     "27", ["18", "20", "25", "30"],
     "Il fut détenu de 1962 à 1990, dont dix-huit ans sur l'île de Robben Island."),
    (4, "En quelle année Nelson Mandela a-t-il reçu le prix Nobel de la paix, avec Frederik de Klerk ?",
     "1993", ["1990", "1991", "1994", "1995"],
     "Le prix récompensait leur rôle dans la fin pacifique de l'apartheid."),
    (4, "Quel jour célèbre-t-on la Journée internationale Nelson Mandela ?",
     "Le 18 juillet", ["Le 5 décembre", "Le 11 février", "Le 27 avril", "Le 16 juin"],
     "Le 18 juillet est la date de naissance de Mandela, en 1918."),
    (4, "En quelle année l'Afrique du Sud a-t-elle fait son retour aux Jeux olympiques, après des décennies d'exclusion ?",
     "1992", ["1980", "1984", "1988", "1996"],
     "L'exclusion, liée à l'apartheid, avait suivi les Jeux de Rome en 1960."),
    (3, "Dans quelle ville a eu lieu en 1974 le combat de boxe Ali-Foreman, appelé « Rumble in the Jungle » ?",
     "À Kinshasa", ["À Lagos", "À Accra", "À Brazzaville", "À Nairobi"],
     "Le combat s'est déroulé au Zaïre ; Muhammad Ali a battu George Foreman par K.-O. au huitième round."),
    (4, "Qui a créé le rallye Paris-Dakar, après s'être perdu dans le désert libyen lors d'un rallye en 1977 ?",
     "Thierry Sabine", ["Jean-Claude Killy", "Hubert Auriol", "Cyril Neveu", "Jacky Ickx"],
     "Il en a organisé la première édition à la fin de 1978."),
    (4, "Quelle ville a accueilli en 1966 le premier Festival mondial des arts nègres, voulu par Léopold Sédar Senghor ?",
     "Dakar", ["Lagos", "Accra", "Abidjan", "Alger"],
     "Lagos a accueilli une édition en 1977, le FESTAC."),
    (5, "Quelle ville a accueilli en 1969 le premier Festival culturel panafricain ?",
     "Alger", ["Dakar", "Lagos", "Tunis", "Accra"],
     "Le festival a réuni de nombreux pays d'Afrique et des artistes de la diaspora."),
    (2, "Quelle ville sénégalaise accueille la biennale d'art contemporain Dak'Art ?",
     "Dakar", ["Saint-Louis", "Thiès", "Kaolack", "Ziguinchor"],
     "Dak'Art est l'un des grands rendez-vous d'art contemporain africain."),
    (3, "Dans quelle ville côtière du Maroc se tient chaque année le festival Gnaoua et musiques du monde ?",
     "Essaouira", ["Agadir", "Casablanca", "Tanger", "Safi"],
     "Le festival a été créé en 1998."),
    (4, "Quelle ville sénégalaise accueille un célèbre festival de jazz depuis 1993 ?",
     "Saint-Louis", ["Dakar", "Thiès", "Ziguinchor", "Kaolack"],
     "La ville, ancienne capitale coloniale, est inscrite à l'UNESCO."),
    (3, "Quelles couleurs, inspirées du drapeau éthiopien, sont dites panafricaines ?",
     "Le vert, le jaune et le rouge", ["Le bleu, le blanc et le rouge", "L'orange, le blanc et le vert", "Le rouge, le blanc et le noir", "Le bleu, le jaune et le noir"],
     "Beaucoup de pays africains ont repris ces couleurs sur leur drapeau après leur indépendance."),
    (3, "Quel jour célèbre-t-on la Journée de l'Afrique, anniversaire de la création de l'OUA en 1963 ?",
     "Le 25 mai", ["Le 1er mai", "Le 21 mars", "Le 12 juin", "Le 14 juillet"],
     "L'OUA a été créée à Addis-Abeba en 1963 ; elle est devenue l'Union africaine en 2002."),
])

# ------------------------------------------------------------------------------------------- Jeux olympiques et athlétisme
rows("af-culture", "AF", "Afrique : athlétisme et Jeux olympiques", [
    (4, "Quel exploit Abebe Bikila a-t-il réalisé aux Jeux de Tokyo en 1964 ?",
     "Il a gagné un deuxième marathon olympique d'affilée", ["Il a gagné le 10 000 m", "Il a terminé deuxième du marathon", "Il a gagné le 5 000 m",
                                                              "Il a abandonné après trente kilomètres"],
     "Il a remporté le marathon de Rome en 1960 pieds nus, puis celui de Tokyo en 1964, avec un nouveau record du monde."),
    (5, "Quel Éthiopien a remporté le marathon olympique de 1968, à Mexico ?",
     "Mamo Wolde", ["Haile Gebrselassie", "Kipchoge Keino", "Abebe Bikila", "Miruts Yifter"],
     "Bikila avait dû abandonner sur blessure."),
    (4, "Quel coureur kényan a gagné le 1 500 m aux Jeux de Mexico en 1968, devant l'Américain Jim Ryun ?",
     "Kipchoge Keino", ["Eliud Kipchoge", "Henry Rono", "Wilson Kipketer", "Paul Tergat"],
     "Il a aussi gagné le steeple en 1972."),
    (3, "Quel Kényan a gagné le marathon olympique en 2016 à Rio puis en 2021 à Tokyo ?",
     "Eliud Kipchoge", ["Kenenisa Bekele", "Haile Gebrselassie", "Geoffrey Mutai", "Wilson Kipsang"],
     "Il a ainsi gagné deux marathons olympiques d'affilée, comme Abebe Bikila."),
    (3, "Quel Éthiopien a gagné le 10 000 m olympique en 1996 et en 2000 ?",
     "Haile Gebrselassie", ["Kenenisa Bekele", "Abebe Bikila", "Miruts Yifter", "Paul Tergat"],
     "En 2000, à Sydney, il a devancé le Kényan Paul Tergat d'un cheveu."),
    (4, "Quel Éthiopien a réussi le doublé 5 000 m - 10 000 m aux Jeux olympiques de Pékin, en 2008 ?",
     "Kenenisa Bekele", ["Haile Gebrselassie", "Eliud Kipchoge", "Hicham El Guerrouj", "Mo Farah"],
     "Il avait déjà gagné le 10 000 m à Athènes en 2004."),
    (4, "Quelle Éthiopienne a été la première femme noire africaine à remporter l'or olympique, sur 10 000 m, en 1992 ?",
     "Derartu Tulu", ["Tirunesh Dibaba", "Fatuma Roba", "Maria Mutola", "Nawal El Moutawakel"],
     "Elle a gagné à Barcelone, devant la Sud-Africaine Elana Meyer."),
    (4, "Quelle athlète marocaine a gagné le 400 m haies aux Jeux de Los Angeles en 1984 ?",
     "Nawal El Moutawakel", ["Hassiba Boulmerka", "Maria Mutola", "Derartu Tulu", "Nezha Bidouane"],
     "Elle est devenue la première championne olympique d'un pays arabe et musulman."),
    (5, "Quelle Algérienne a gagné le 1 500 m olympique à Barcelone en 1992 ?",
     "Hassiba Boulmerka", ["Nawal El Moutawakel", "Derartu Tulu", "Maria Mutola", "Nezha Bidouane"],
     "Elle était déjà championne du monde de la distance en 1991."),
    (4, "Quel Marocain a réussi en 2004, à Athènes, le doublé 1 500 m - 5 000 m ?",
     "Hicham El Guerrouj", ["Saïd Aouita", "Noureddine Morceli", "Kenenisa Bekele", "Rashid Ramzi"],
     "Il avait échoué en 1996 et en 2000 avant de remporter l'or."),
    (5, "Quel Algérien a gagné le 1 500 m olympique à Atlanta en 1996 ?",
     "Noureddine Morceli", ["Hicham El Guerrouj", "Saïd Aouita", "Rashid Ramzi", "Hassiba Boulmerka"],
     "Il a aussi été trois fois champion du monde de la distance."),
    (5, "Quelle Mozambicaine a remporté le 800 m olympique à Sydney, en 2000 ?",
     "Maria Mutola", ["Derartu Tulu", "Hassiba Boulmerka", "Nawal El Moutawakel", "Tirunesh Dibaba"],
     "Elle a aussi été plusieurs fois championne du monde de la distance."),
    (4, "Quelle équipe a été la première d'Afrique à remporter le tournoi olympique de football, en 1996 à Atlanta ?",
     "Le Nigeria", ["Le Cameroun", "Le Ghana", "L'Égypte", "Le Maroc"],
     "Les Super Eagles ont battu l'Argentine 3-2 en finale."),
    (5, "Quelle équipe a remporté le tournoi olympique de football en 2000, à Sydney, aux tirs au but contre l'Espagne ?",
     "Le Cameroun", ["Le Nigeria", "Le Ghana", "Le Sénégal", "Le Chili"],
     "Le Cameroun est devenu le deuxième pays africain champion olympique de football."),
])

# ------------------------------------------------------------------------------------------- surnoms des sélections (facile)
table("af-culture", "AF", "Afrique : football",
      [("le Cameroun", "Les Lions indomptables", 1), ("la Côte d'Ivoire", "Les Éléphants", 1), ("le Sénégal", "Les Lions de la Teranga", 2),
       ("l'Égypte", "Les Pharaons", 2), ("l'Algérie", "Les Fennecs", 2), ("le Ghana", "Les Black Stars", 2),
       ("le Nigeria", "Les Super Eagles", 2), ("le Maroc", "Les Lions de l'Atlas", 2), 
       ("la Tunisie", "Les Aigles de Carthage", 3), ("le Burkina Faso", "Les Étalons", 3), ("la République démocratique du Congo", "Les Léopards", 3)],
      "Quel est le surnom de la sélection nationale de football de {a} ?", "Quelle sélection nationale de football est surnommée « {b} » ?",
      diff=2, expl="La sélection de football de {a} est surnommée « {b} ».")

rows("af-culture", "AF", "Afrique : culture générale", [
    (3, "Quel surnom, qui signifie « les garçons » en zoulou, porte la sélection nationale de football d'Afrique du Sud ?",
     "Bafana Bafana", ["Les Springboks", "Les Proteas", "Les Chipolopolo", "Les Lions de l'Atlas"],
     "Les Springboks jouent au rugby, les Proteas au cricket : le football a ses Bafana Bafana."),
    (1, "Quel animal, symbole de la savane, est le plus grand félin d'Afrique ?",
     "Le lion", ["Le léopard", "Le guépard", "Le serval", "Le caracal"],
     "Le lion vit surtout en Afrique subsaharienne ; une petite population subsiste en Inde."),
    (1, "Quel arbre géant, au tronc très large, est l'un des symboles de la savane africaine ?",
     "Le baobab", ["Le chêne", "Le sapin", "Le saule", "Le peuplier"],
     "Certains baobabs ont un tronc de plus de dix mètres de diamètre."),
    (1, "Quel animal à rayures noires et blanches vit dans les savanes d'Afrique ?",
     "Le zèbre", ["Le lion", "Le rhinocéros", "Le buffle", "Le phacochère"],
     "Les rayures de chaque zèbre sont uniques, comme des empreintes digitales."),
    (1, "Que signifient les lettres « CAN » dans le monde du football africain ?",
     "Coupe d'Afrique des nations", ["Championnat africain national", "Coupe des athlètes du Nil", "Compétition d'Afrique du Nord",
                                      "Coupe des associations nationales"],
     "La CAN est organisée par la Confédération africaine de football (CAF)."),
    (1, "Quelle célèbre figure sud-africaine est surnommée « Madiba », du nom de son clan ?",
     "Nelson Mandela", ["Desmond Tutu", "Thabo Mbeki", "Steve Biko", "Oliver Tambo"],
     "Madiba est le nom de son clan, que beaucoup de Sud-Africains utilisent par affection."),
    (2, "De quelles couleurs est le maillot des Springboks, l'équipe nationale de rugby d'Afrique du Sud ?",
     "Vert et or", ["Bleu et blanc", "Noir", "Rouge et blanc", "Orange"],
     "Le vert et l'or sont les couleurs du sport sud-africain."),
    (2, "Quel sport traditionnel très populaire au Sénégal oppose deux lutteurs dans une arène de sable ?",
     "La lutte sénégalaise", ["Le sumo", "La capoeira", "Le kendo", "Le pancrace"],
     "Appelée « laamb » en wolof, elle attire des foules immenses dans les stades."),
])
