"""Cameroun : personnalités célèbres et sport (Lions Indomptables, CAN, JO, basket, combat, lettres, arts, histoire).
Faits écrits à la main d'après la connaissance générale : tous `review`. Seuls des faits datés ou intemporels."""
from .cult_kit import rows, table, theme

theme("cm-pers", "Cameroun : personnalités célèbres et sport",
      "Comparer avec les sites officiels de la FIFA, de la CAF et du CIO (résultats datés), les biographies publiées "
      "(Wikipédia FR/EN, Britannica, Larousse) et les catalogues d'éditeurs pour les dates de parution et les prix.")

# ------------------------------------------------------------------ Lions Indomptables : Coupes du monde
rows("cm-pers", "CM", "Sport", [
    (1, "Quelle couleur domine traditionnellement le maillot des Lions Indomptables ?", "Le vert",
     ["Le bleu", "Le blanc", "L'orange", "Le noir"], "Le vert, le rouge et le jaune du drapeau camerounais sont ceux de l'équipe nationale."),
    (1, "Comment s'appelle l'équipe nationale féminine de football du Cameroun ?", "Les Lionnes Indomptables",
     ["Les Super Falcons", "Les Black Queens", "Les Éléphantes", "Les Panthères"],
     "Les Super Falcons sont les Nigérianes, les Black Queens les Ghanéennes."),
    (1, "Quel poste occupait Thomas N'Kono, héros des Mondiaux 1982 et 1990 ?", "Gardien de but",
     ["Attaquant", "Défenseur central", "Milieu offensif", "Ailier droit"], "N'Kono a gardé les buts des Lions Indomptables pendant plus d'une décennie."),
    (1, "Dans quel sport Francis Ngannou s'est-il fait connaître dans le monde entier ?", "Les arts martiaux mixtes (MMA)",
     ["Le basket-ball", "La natation", "Le tennis", "Le cyclisme"], "Né à Batié, il est devenu champion poids lourds de l'UFC en 2021."),
    (1, "Dans quel sport Joel Embiid, né à Yaoundé, brille-t-il en Amérique du Nord ?", "Le basket-ball",
     ["Le football", "Le handball", "Le baseball", "Le hockey sur glace"], "Joel Embiid joue en NBA, à Philadelphie."),
    (2, "Dans quel pays le Cameroun a-t-il remporté sa première CAN, en 1984 ?",
     "En Côte d'Ivoire", ["Au Ghana", "Au Sénégal", "Au Maroc", "Au Nigeria"], "Le Cameroun a battu le Nigeria 3-1 en finale à Abidjan en 1984."),
    (2, "Quel pays d'Afrique centrale a accueilli la CAN jouée en janvier-février 2022 (édition 2021) ?", "Le Cameroun",
     ["Le Gabon", "Le Tchad", "Le Congo", "La Guinée équatoriale", "Le Nigeria"], "La Coupe d'Afrique des nations 2021 a été reportée d'un an et jouée au Cameroun du 9 janvier au 6 février 2022."),
    (2, "Entre 1984 et 2017, combien de Coupes d'Afrique des nations le Cameroun a-t-il remportées ?", "Cinq",
     ["Deux", "Trois", "Quatre", "Six"], "Titres en 1984, 1988, 2000, 2002 et 2017."),
    (2, "Contre quelle sélection les Lions Indomptables ont-ils joué le match d'ouverture de la CAN 2021, au stade d'Olembe ?",
     "Le Burkina Faso", ["Le Cap-Vert", "L'Éthiopie", "Les Comores", "La Gambie"], "Le Cameroun s'est imposé 2-1 le 9 janvier 2022 à Yaoundé."),
    (2, "Quel pays a remporté la CAN 2021 en finale à Yaoundé, en février 2022 ?", "Le Sénégal",
     ["L'Égypte", "Le Cameroun", "Le Burkina Faso", "Le Maroc"], "Le Sénégal a battu l'Égypte aux tirs au but : c'était son premier titre continental."),
    (2, "Dans quelle ville se trouve le stade d'Olembe, où a été jouée la finale de la CAN 2021 ?", "Yaoundé",
     ["Douala", "Garoua", "Bafoussam", "Limbé"], "Le stade d'Olembe est situé à Yaoundé et a accueilli l'ouverture et la finale."),
    (2, "Quelle compétition mondiale le Cameroun a-t-il gagnée en football masculin en 2000, à Sydney ?", "Le tournoi olympique",
     ["La Coupe des confédérations", "La Coupe du monde des moins de 17 ans", "La Coupe du monde", "La Coupe des moins de 20 ans"],
     "L'or olympique de 2000 est le premier titre olympique de l'histoire du Cameroun."),
    (2, "Quelle est la première discipline où le Cameroun a remporté un titre olympique, en 2000 ?", "Le football",
     ["L'athlétisme", "La boxe", "Le judo", "La lutte"], "Sydney 2000 : victoire aux tirs au but contre l'Espagne."),
    (2, "Combien de titres olympiques Françoise Mbango Etone a-t-elle gagnés au triple saut ?", "Deux",
     ["Un seul", "Trois", "Quatre", "Aucun"], "Athènes 2004 et Pékin 2008."),
    (2, "Quelle ville a vu Françoise Mbango Etone remporter son premier titre olympique en 2004 ?", "Athènes",
     ["Sydney", "Pékin", "Atlanta", "Londres"], "Elle a conservé son titre quatre ans plus tard à Pékin."),
    (2, "Quel footballeur camerounais a marqué en finale de la Ligue des champions 2009, à Rome ?", "Samuel Eto'o",
     ["Alex Song", "Geremi", "Rigobert Song", "Marc-Vivien Foé"], "Barcelone a battu Manchester United 2-0 ; Eto'o a ouvert le score."),
    (2, "Quel ancien joueur a été élu à la tête de la Fédération camerounaise de football (Fecafoot) en décembre 2021 ?", "Samuel Eto'o",
     ["Roger Milla", "Rigobert Song", "Thomas N'Kono", "Patrick Mboma"], "L'ancien capitaine des Lions a été élu président de la Fecafoot en décembre 2021."),
    (2, "Contre quelle équipe le Cameroun a-t-il perdu en finale de la CAN 1986, aux tirs au but ?", "L'Égypte",
     ["Le Nigeria", "La Côte d'Ivoire", "Le Maroc", "L'Algérie"], "Finale au Caire : 0-0, puis victoire égyptienne aux tirs au but."),
])

# ------------------------------------------------------------------ Coupes du monde masculines
rows("cm-pers", "CM", "Sport", [
    (3, "Quel fut le bilan des Lions Indomptables lors de leur premier Mondial, en Espagne en 1982 ?", "Trois matches nuls, aucune défaite",
     ["Deux victoires et une défaite", "Une victoire et deux nuls", "Trois défaites", "Un nul et deux défaites"],
     "0-0 contre le Pérou, 0-0 contre la Pologne et 1-1 contre l'Italie : invaincus mais éliminés."),
    (4, "Quelle sélection a devancé le Cameroun au Mondial 1982 grâce à un but marqué en plus, avant de gagner le titre ?", "L'Italie",
     ["L'Allemagne de l'Ouest", "L'Argentine", "Le Brésil", "La France"], "Italie et Cameroun avaient trois nuls, mais l'Italie avait marqué deux buts contre un."),
    (5, "Dans quelle ville espagnole le Cameroun a-t-il tenu l'Italie en échec 1-1 en 1982 ?", "Vigo",
     ["Madrid", "Séville", "Valence", "Barcelone", "Saragosse"], "Le match a eu lieu à Vigo ; les deux autres matches de poule se sont joués à La Corogne."),
    (3, "Dans quelle ville italienne s'est joué le match d'ouverture du Mondial 1990, remporté par le Cameroun contre l'Argentine ?", "Milan",
     ["Rome", "Naples", "Turin", "Bari", "Florence"], "Victoire 1-0 au stade San Siro, le 8 juin 1990, grâce à un but de François Omam-Biyik."),
    (3, "Combien de joueurs camerounais restaient sur le terrain à la fin de la victoire contre l'Argentine, en 1990 ?", "Neuf",
     ["Dix", "Huit", "Onze", "Sept"], "André Kana-Biyik puis Benjamin Massing ont été expulsés : les Lions ont fini à neuf."),
    (4, "Quel gardien argentin a été battu par la tête de François Omam-Biyik lors du match d'ouverture du Mondial 1990 ?", "Nery Pumpido",
     ["Sergio Goycochea", "Ubaldo Fillol", "Hugo Gatti", "Luis Islas"], "Le ballon lui a échappé des mains ; Goycochea l'a remplacé dans la suite du tournoi."),
    (3, "Contre quelle équipe Roger Milla, entré en jeu, a-t-il inscrit un doublé en phase de poule au Mondial 1990 ?", "La Roumanie",
     ["L'Argentine", "L'URSS", "La Colombie", "L'Angleterre"], "Victoire 2-1 à Bari ; Milla a aussi marqué deux fois contre la Colombie en huitième de finale."),
    (3, "Quel gardien colombien s'est fait dribbler par Roger Milla en huitième de finale du Mondial 1990 ?", "René Higuita",
     ["Faryd Mondragón", "Óscar Córdoba", "Carlos Valderrama", "Freddy Rincón"], "Milla a récupéré le ballon et marqué dans le but vide pour le 2-0, à Naples."),
    (4, "Quel attaquant anglais a transformé deux penaltys contre le Cameroun en quart de finale du Mondial 1990 ?", "Gary Lineker",
     ["Paul Gascoigne", "David Platt", "Peter Beardsley", "Chris Waddle"], "L'Angleterre l'a emporté 3-2 après prolongation, à Naples."),
    (5, "Quel milieu anglais a ouvert le score contre le Cameroun en quart de finale du Mondial 1990 ?", "David Platt",
     ["Gary Lineker", "Paul Gascoigne", "Bryan Robson", "Chris Waddle"], "Platt a marqué de la tête à la 25e minute, avant la remontée camerounaise."),
    (5, "Quel joueur a transformé le penalty de l'égalisation camerounaise (1-1) contre l'Angleterre en 1990 ?", "Emmanuel Kundé",
     ["Roger Milla", "François Omam-Biyik", "Eugène Ekéké", "Cyrille Makanaky"], "Kundé a égalisé sur penalty, puis Eugène Ekéké a donné l'avantage aux Lions."),
    (5, "Quel attaquant a donné l'avantage 2-1 au Cameroun contre l'Angleterre en quart de finale du Mondial 1990 ?", "Eugène Ekéké",
     ["Roger Milla", "François Omam-Biyik", "Emmanuel Kundé", "Louis-Paul M'Fédé"], "L'Angleterre a ensuite égalisé puis gagné grâce à deux penaltys."),
    (4, "Quel entraîneur dirigeait le Cameroun lors du Mondial 1990, en Italie ?", "Valeri Nepomniachi",
     ["Claude Le Roy", "Jean Vincent", "Pierre Lechantre", "Winfried Schäfer"], "Le technicien soviétique a mené les Lions jusqu'en quart de finale, une première pour l'Afrique."),
    (5, "Quel score les Lions Indomptables ont-ils subi contre l'URSS lors du Mondial 1990 ?", "0-4",
     ["0-3", "1-3", "0-5", "1-4"], "Cette défaite est survenue après leurs deux victoires, quand la qualification était déjà acquise."),
    (5, "Qui était le capitaine du Cameroun lors du Mondial 1990 ?", "Stephen Tataw",
     ["Rigobert Song", "Roger Milla", "Thomas N'Kono", "Samuel Eto'o"], "Le défenseur Stephen Tataw portait le brassard en Italie."),
    (3, "Contre quelle équipe le Cameroun a-t-il perdu 3-0 au Mondial 1994 ?", "Le Brésil",
     ["La Suède", "La Russie", "L'Italie", "La Norvège"], "Brésil 3-0 Cameroun, à Stanford (Californie)."),
    (4, "Quelle équipe a tenu le Cameroun en échec (2-2) au Mondial 1994, aux États-Unis ?", "La Suède",
     ["Le Brésil", "La Russie", "La Norvège", "La Bulgarie"], "Les Lions ont arraché le nul 2-2, au Rose Bowl de Pasadena."),
    (3, "Quel joueur russe a inscrit cinq buts dans un même match contre le Cameroun, en 1994 ?", "Oleg Salenko",
     ["Dmitri Radchenko", "Igor Dobrovolski", "Valeri Karpine", "Igor Kolyvanov"], "Russie 6-1 Cameroun : Salenko a marqué cinq fois, Milla a inscrit le but camerounais."),
    (4, "Quel âge avait Rigobert Song quand il a été expulsé contre le Brésil en 1994, devenant le plus jeune joueur expulsé en Coupe du monde ?", "17 ans",
     ["19 ans", "21 ans", "23 ans", "15 ans"], "Né en juillet 1976, il n'avait pas encore 18 ans lors de ce match de juin 1994."),
    (4, "Contre quelle équipe Rigobert Song a-t-il été expulsé lors du Mondial 1998 ?", "Le Chili",
     ["L'Italie", "L'Autriche", "Le Brésil", "La Norvège"], "Cameroun-Chili 1-1 : sa seconde expulsion en Coupe du monde, après celle de 1994."),
    (4, "Quelle sélection a battu le Cameroun 3-0 au Mondial 1998, en France ?", "L'Italie",
     ["L'Autriche", "Le Chili", "La Norvège", "Le Danemark"], "Italie 3-0 Cameroun, à Montpellier."),
    (4, "Quelle équipe a battu le Cameroun 2-0 lors du Mondial 2002, en Corée du Sud et au Japon ?", "L'Allemagne",
     ["L'Irlande", "L'Arabie saoudite", "Le Japon", "La Corée du Sud"], "Le Cameroun avait gagné contre l'Arabie saoudite mais a manqué la qualification."),
    (4, "Quel entraîneur allemand dirigeait le Cameroun lors de la CAN 2002 et du Mondial 2002 ?", "Winfried Schäfer",
     ["Otto Pfister", "Hugo Broos", "Volker Finke", "Berti Vogts"], "Schäfer a mené les Lions à leur quatrième titre africain en 2002."),
    (4, "Quel entraîneur français dirigeait le Cameroun lors de la Coupe du monde 2010, en Afrique du Sud ?", "Paul Le Guen",
     ["Claude Le Roy", "Hervé Renard", "Jean Vincent", "Raymond Domenech"], "Le Cameroun a perdu ses trois matches de poule en 2010."),
    (4, "Quelle sélection a battu le Cameroun 1-0 lors de son premier match du Mondial 2010 ?", "Le Japon",
     ["Le Danemark", "Les Pays-Bas", "L'Italie", "La Corée du Sud"], "Honda a marqué pour le Japon, à Bloemfontein."),
    (5, "Quel joueur a inscrit l'unique but camerounais du Mondial 2014, au Brésil ?", "Joël Matip",
     ["Alex Song", "Eric Maxim Choupo-Moting", "Benjamin Moukandjo", "Vincent Aboubakar"], "Le but est tombé contre le Brésil (défaite 4-1), après deux matches sans marquer."),
    (5, "Quel Camerounais a été expulsé contre la Croatie en 2014 pour un coup de coude sur Mario Mandžukić ?", "Alex Song",
     ["Nicolas Nkoulou", "Stéphane Mbia", "Joël Matip", "Benoît Assou-Ekotto"], "La Croatie a gagné 4-0 à Manaus."),
    (3, "Quel joueur né à Yaoundé a marqué pour la Suisse contre le Cameroun, en 2022 ?", "Breel Embolo",
     ["Xherdan Shaqiri", "Granit Xhaka", "Haris Seferovic", "Ricardo Rodríguez"], "Embolo, né à Yaoundé en 1997, n'a pas célébré son but contre son pays de naissance."),
    (3, "Quelle équipe a fait match nul 3-3 avec le Cameroun lors du Mondial 2022, au Qatar ?", "La Serbie",
     ["La Suisse", "Le Brésil", "La Croatie", "Le Ghana"], "Les Lions ont remonté trois buts d'écart face aux Serbes."),
    (3, "Quel Camerounais a été expulsé après avoir ôté son maillot pour célébrer son but contre le Brésil en 2022 ?", "Vincent Aboubakar",
     ["Eric Maxim Choupo-Moting", "Karl Toko Ekambi", "Bryan Mbeumo", "Jean-Charles Castelletto"], "Il avait marqué le but de la victoire 1-0 dans le temps additionnel."),
    (3, "Quel ancien capitaine entraînait les Lions Indomptables au Mondial 2022 ?", "Rigobert Song",
     ["Samuel Eto'o", "Roger Milla", "Thomas N'Kono", "Patrick Mboma"], "Song a pris la sélection en 2022, avant la Coupe du monde du Qatar."),
])

table("cm-pers", "CM", "Sport", [
    ("1982", "en Espagne", 2), ("1990", "en Italie", 2), ("1994", "aux États-Unis", 3), ("1998", "en France", 2),
    ("2002", "au Japon et en Corée du Sud", 3), ("2010", "en Afrique du Sud", 2), ("2014", "au Brésil", 2), ("2022", "au Qatar", 2),
], "Dans quel pays s'est jouée la Coupe du monde de football {a}, à laquelle le Cameroun a participé ?",
   "Quelle Coupe du monde de football, à laquelle le Cameroun a pris part, a été organisée {b} ?",
   diff=2, expl="La Coupe du monde {a} s'est jouée {b}.", rev_expl="La Coupe du monde organisée {b} date de {a}.")

# ------------------------------------------------------------------ CAN, JO, clubs, Lionnes
rows("cm-pers", "CM", "Sport", [
    (4, "Contre quel pays le Cameroun a-t-il disputé trois finales de CAN victorieuses (1984, 1988 et 2000) ?", "Le Nigeria",
     ["L'Égypte", "Le Ghana", "Le Sénégal", "La Côte d'Ivoire"], "3-1 en 1984, 1-0 en 1988, puis victoire aux tirs au but en 2000 à Lagos."),
    (3, "Quel adversaire le Cameroun a-t-il battu aux tirs au but en finale de la CAN 2002, à Bamako ?", "Le Sénégal",
     ["Le Mali", "Le Nigeria", "L'Égypte", "Le Ghana"], "Après 0-0, les Lions ont gagné 3-2 aux tirs au but."),
    (3, "Quel adversaire le Cameroun a-t-il battu 2-1 en finale de la CAN 2017 ?", "L'Égypte",
     ["Le Ghana", "Le Burkina Faso", "Le Sénégal", "Le Maroc"], "Victoire à Libreville, après avoir été mené."),
    (3, "Quel attaquant a marqué le but vainqueur en finale de la CAN 2017, à la 88e minute ?", "Vincent Aboubakar",
     ["Karl Toko Ekambi", "Christian Bassogog", "Benjamin Moukandjo", "Eric Maxim Choupo-Moting"], "Il a donné au Cameroun son cinquième titre continental."),
    (5, "Quel défenseur a égalisé pour le Cameroun en finale de la CAN 2017 face à l'Égypte ?", "Nicolas Nkoulou",
     ["Michael Ngadeu-Ngadjui", "Adolphe Teikeu", "Ambroise Oyongo", "Collins Fai"], "Nkoulou a égalisé à l'heure de jeu, avant le but d'Aboubakar."),
    (3, "Quel entraîneur belge a mené le Cameroun au titre à la CAN 2017 ?", "Hugo Broos",
     ["Clarence Seedorf", "Volker Finke", "Paul Le Guen", "Alain Giresse"], "Hugo Broos a gagné avec une équipe sans plusieurs cadres habituels."),
    (3, "Dans quelle ville s'est jouée la finale de la CAN 2017, remportée par le Cameroun ?", "Libreville",
     ["Franceville", "Port-Gentil", "Oyem", "Yaoundé"], "La CAN 2017 était organisée au Gabon."),
    (4, "Quel entraîneur français a conduit le Cameroun au titre africain de 1988 ?", "Claude Le Roy",
     ["Pierre Lechantre", "Jean Vincent", "Hervé Renard", "Philippe Troussier"], "Le Cameroun a battu le Nigeria 1-0 en finale, au Maroc."),
    (5, "Quel entraîneur français dirigeait le Cameroun lors de la CAN 2000 remportée à Lagos ?", "Pierre Lechantre",
     ["Claude Le Roy", "Paul Le Guen", "Alain Giresse", "Winfried Schäfer"], "Les Lions ont battu le Nigeria aux tirs au but, en 2000, pays co-hôte avec le Ghana."),
    (4, "Dans quelle ville ghanéenne s'est jouée la finale de la CAN 2008, perdue par le Cameroun ?", "Accra",
     ["Kumasi", "Tamale", "Sekondi-Takoradi", "Tema"], "L'Égypte l'a emporté 1-0 face au Cameroun."),
    (5, "Quel pays a remporté la CAN 1972, organisée à Yaoundé ?", "Le Congo",
     ["Le Mali", "Le Cameroun", "Le Ghana", "Le Zaïre"], "Le Congo l'a emporté 3-2 face au Mali en finale."),
    (4, "Pour quelle compétition le titre « Soul Makossa » de Manu Dibango a-t-il été enregistré en 1972, comme face B d'un hymne ?", "La Coupe d'Afrique des nations de football",
     ["Les Jeux olympiques de Munich", "La Coupe du monde 1974", "Les Jeux africains", "Le festival FESTAC"], "L'hymne de la CAN 1972, jouée à Yaoundé, a lancé le tube mondial."),
    (4, "Quel pays a accueilli la CAN 2019, alors que le Cameroun avait d'abord été désigné hôte ?", "L'Égypte",
     ["Le Maroc", "L'Afrique du Sud", "L'Algérie", "Le Gabon", "Le Sénégal"], "La CAF a retiré l'organisation au Cameroun en 2018 et lui a confié l'édition 2021."),
    (4, "Quelle mascotte, un lion, représentait la CAN 2021 organisée au Cameroun ?", "Mola",
     ["Simba", "Kiko", "Zakumi", "Footix"], "Mola est le lion mascotte de la CAN 2021."),
    (3, "Quelle place le Cameroun a-t-il obtenue à la CAN 2021, qu'il organisait ?", "Troisième",
     ["Deuxième", "Quatrième", "Vainqueur", "Éliminé en quarts de finale"], "Les Lions ont battu le Burkina Faso aux tirs au but pour la médaille de bronze."),
    (3, "Quel pays a éliminé le Cameroun en demi-finale de la CAN 2021, aux tirs au but ?", "L'Égypte",
     ["Le Sénégal", "Le Burkina Faso", "La Gambie", "Les Comores"], "0-0 après prolongation, puis victoire égyptienne aux tirs au but."),
    (4, "Quelle sélection, novice en CAN, le Cameroun a-t-il battue 2-0 en quart de finale de la CAN 2021 ?", "La Gambie",
     ["Les Comores", "Le Cap-Vert", "La Guinée équatoriale", "Madagascar"], "La Gambie découvrait la phase finale d'une CAN et a atteint les quarts."),
    (4, "Pourquoi les Comores ont-elles aligné un joueur de champ dans les buts face au Cameroun, en huitième de finale de la CAN 2021 ?", "Leurs gardiens étaient indisponibles",
     ["Leur gardien avait été exclu au match précédent", "Une règle de la CAF l'exigeait", "Le gardien avait été oublié sur la feuille de match", "Ils voulaient surprendre l'adversaire"],
     "Entre la Covid-19 et une blessure, l'équipe n'avait plus de gardien ; le Cameroun a gagné 2-1."),
    (4, "Quel stade de Yaoundé, inauguré en 1972, a été construit pour la CAN de cette année-là ?", "Le stade Ahmadou-Ahidjo",
     ["Le stade de la Réunification", "Le stade de Japoma", "Le stade de Kouekong", "Le stade Roumdé-Adjia"], "Le Cameroun accueillait alors sa première CAN."),
    (3, "Quel pays africain avait remporté l'or olympique de football en 1996, avant le Cameroun en 2000 ?", "Le Nigeria",
     ["Le Ghana", "L'Égypte", "Le Maroc", "L'Algérie"], "Le Nigeria avait gagné à Atlanta contre l'Argentine."),
    (4, "Quel entraîneur camerounais dirigeait l'équipe championne olympique de football en 2000 ?", "Jean-Paul Akono",
     ["Pierre Lechantre", "Claude Le Roy", "Winfried Schäfer", "Jean Manga-Onguéné"], "Le Cameroun a battu l'Espagne aux tirs au but (2-2, 5-3)."),
    (3, "Quel club de Douala a remporté la première Coupe d'Afrique des clubs champions, en 1964 ?", "Oryx Douala",
     ["Union Douala", "Canon Yaoundé", "Dynamo Douala", "Tonnerre Yaoundé"], "Oryx Douala est le premier vainqueur de la compétition africaine."),
    (5, "Quel club de Douala a été champion d'Afrique des clubs en 1979 ?", "Union Douala",
     ["Oryx Douala", "Dynamo Douala", "Canon Yaoundé", "Coton Sport"], "Canon Yaoundé avait gagné en 1978 puis en 1980."),
    (3, "Quelle sélection a battu le Cameroun en finale de la Coupe des confédérations 2003, à Paris ?", "La France",
     ["Le Brésil", "La Turquie", "L'Argentine", "La Colombie"], "Thierry Henry a marqué le but en or."),
    (3, "Quel attaquant français a marqué le but en or contre le Cameroun en finale de la Coupe des confédérations 2003 ?", "Thierry Henry",
     ["Zinédine Zidane", "David Trezeguet", "Sylvain Wiltord", "Patrick Vieira"], "Le but a été marqué en prolongation, au Stade de France."),
    (3, "Quel footballeur camerounais est décédé en juin 2003 lors d'une demi-finale de la Coupe des confédérations, à Lyon ?", "Marc-Vivien Foé",
     ["Patrick Mboma", "Geremi", "Pierre Womé", "Lauren"], "Foé avait joué à Lens, à West Ham et à Lyon ; le Cameroun a joué la finale en son hommage."),
    (4, "Quel Camerounais, champion olympique en 2000, était titulaire dans l'Arsenal invaincu de la saison 2003-2004 ?", "Lauren",
     ["Alex Song", "Geremi", "Pierre Womé", "Marc-Vivien Foé"], "L'arrière droit Lauren a remporté la Premier League sans défaite avec Arsenal."),
    (3, "Avec quel club Geremi a-t-il gagné la Ligue des champions en 2000 et 2002 ?", "Le Real Madrid",
     ["Chelsea", "Newcastle", "Middlesbrough", "Valence"], "Il a aussi été champion d'Angleterre avec Chelsea."),
    (4, "Quel club espagnol a vu Thomas N'Kono jouer dans les années 1980 ?", "L'Espanyol de Barcelone",
     ["Le FC Barcelone", "L'Atlético de Madrid", "L'Athletic Bilbao", "Valence"], "Le gardien camerounais a été une idole de l'Espanyol."),
    (4, "Quel gardien italien a donné à son fils le prénom Thomas en hommage à N'Kono ?", "Gianluigi Buffon",
     ["Dino Zoff", "Walter Zenga", "Gianluca Pagliuca", "Angelo Peruzzi"], "Buffon a dit avoir été marqué par le gardien camerounais lors du Mondial 1990."),
    (3, "Quelle danse Roger Milla a-t-il rendue célèbre à chaque but de la Coupe du monde 1990 ?", "Une danse autour du drapeau de corner",
     ["Un salto arrière", "Une glissade à genoux", "Un salut militaire", "Une chorégraphie en ligne"], "Cette célébration a marqué le Mondial 1990."),
    (4, "En quelle année Roger Milla a-t-il été élu joueur africain de l'année pour la seconde fois, après 1976 ?", "1990",
     ["1986", "1988", "1992", "1994"], "Il avait 38 ans lors du Mondial 1990."),
    (4, "En quelle année Samuel Eto'o a-t-il été élu joueur africain de l'année pour la première fois ?", "2003",
     ["2000", "2002", "2006", "2001"], "Il l'a été en 2003, 2004, 2005 et 2010."),
    (4, "Quel trophée de meilleur buteur du championnat d'Espagne Samuel Eto'o a-t-il remporté en 2005-2006 ?", "Le Pichichi",
     ["Le trophée Zamora", "Le Soulier d'or", "Le Ballon d'or africain", "Le trophée Di Stéfano"], "Eto'o jouait alors au FC Barcelone."),
    (4, "Dans quelle ville s'est jouée la finale de la Ligue des champions 2006, où Samuel Eto'o a égalisé contre Arsenal ?", "Paris",
     ["Rome", "Londres", "Athènes", "Madrid"], "Barcelone a gagné 2-1 au Stade de France."),
    (3, "Quel entraîneur portugais a dirigé Samuel Eto'o à l'Inter Milan lors du triplé 2010 ?", "José Mourinho",
     ["Rafael Benítez", "Carlo Ancelotti", "Pep Guardiola", "Luiz Felipe Scolari"], "L'Inter a gagné le championnat, la coupe et la Ligue des champions."),
    (4, "Quel gardien camerounais a joué la finale de la Ligue des champions 2023 avec l'Inter Milan ?", "André Onana",
     ["Carlos Kameni", "Fabrice Ondoa", "Joseph-Antoine Bell", "Thomas N'Kono"], "L'Inter a perdu 1-0 contre Manchester City, à Istanbul."),
])

rows("cm-pers", "CM", "Sport", [
    (3, "Quel pays a battu les Lionnes Indomptables en finale de la Coupe d'Afrique des nations féminine en 2014 et en 2016 ?", "Le Nigeria",
     ["Le Ghana", "L'Afrique du Sud", "La Côte d'Ivoire", "L'Algérie"], "Le Cameroun a organisé l'édition 2016."),
    (3, "En quelle année les Lionnes Indomptables ont-elles disputé leur première Coupe du monde féminine ?", "2015",
     ["2007", "2011", "2019", "2003"], "La compétition s'est jouée au Canada."),
    (3, "Dans quel pays se jouait la Coupe du monde féminine 2015, première du Cameroun ?", "Au Canada",
     ["En Allemagne", "En Suède", "En France", "Aux États-Unis"], "Les Lionnes ont atteint les huitièmes de finale."),
    (4, "Quelle sélection a éliminé le Cameroun en huitième de finale de la Coupe du monde féminine 2015 ?", "La Chine",
     ["Le Japon", "La Suisse", "L'Allemagne", "L'Angleterre"], "Défaite 1-0 des Lionnes."),
    (3, "Quelle sélection a éliminé le Cameroun en huitième de finale de la Coupe du monde féminine 2019 ?", "L'Angleterre",
     ["La Chine", "Le Canada", "La Suède", "L'Australie"], "L'Angleterre l'a emporté 3-0 ; le tournoi se jouait en France."),
    (5, "Quelle attaquante camerounaise a marqué dans le temps additionnel contre la Nouvelle-Zélande, en 2019, après consultation de la VAR ?", "Ajara Nchout",
     ["Gaëlle Enganamouit", "Gabrielle Onguéné", "Christine Manie", "Henriette Akaba"], "Ce but a qualifié les Lionnes pour les huitièmes."),
])

# ------------------------------------------------------------------ basket, combat, tennis, autres sportifs
rows("cm-pers", "CM", "Sport", [
    (2, "Dans quelle ville du Cameroun est né Joel Embiid ?", "Yaoundé",
     ["Douala", "Garoua", "Bafoussam", "Bamenda"], "Il a commencé le basket tard, vers l'âge de quinze ans."),
    (3, "Quelle franchise NBA a choisi Joel Embiid à la draft de 2014 ?", "Les Philadelphia 76ers",
     ["Les Cleveland Cavaliers", "Les Milwaukee Bucks", "Les Los Angeles Lakers", "Les Boston Celtics"], "Il a été choisi en troisième position."),
    (3, "Quelle université américaine Joel Embiid a-t-il fréquentée avant la NBA ?", "Kansas",
     ["Duke", "Kentucky", "Gonzaga", "UCLA"], "Il a joué une saison pour les Jayhawks de Kansas."),
    (3, "Quelle distinction individuelle Joel Embiid a-t-il obtenue au terme de la saison NBA 2022-2023 ?", "Joueur le plus utile (MVP)",
     ["Meilleur défenseur", "Meilleure progression", "Meilleur sixième homme", "Meilleur débutant"], "Il a succédé à Nikola Jokić au palmarès."),
    (4, "Quel ancien joueur NBA camerounais a invité Joel Embiid à son camp de basket à Yaoundé en 2011 ?", "Luc Mbah a Moute",
     ["Pascal Siakam", "Serge Ibaka", "Hakeem Olajuwon", "Dikembe Mutombo"], "Embiid y a été repéré, avant de partir aux États-Unis."),
    (4, "Quelle équipe nationale Joel Embiid a-t-il rejointe pour les Jeux olympiques de Paris 2024 ?", "Les États-Unis",
     ["La France", "Le Cameroun", "Le Canada", "L'Espagne"], "Les États-Unis ont gagné la médaille d'or."),
    (3, "Dans quelle ville du Cameroun est né Pascal Siakam, champion NBA en 2019 ?", "Douala",
     ["Yaoundé", "Garoua", "Bafoussam", "Limbé"], "Il a joué à l'université de New Mexico State."),
    (3, "Avec quelle franchise Pascal Siakam a-t-il été champion NBA en 2019 ?", "Les Toronto Raptors",
     ["Les Golden State Warriors", "Le Miami Heat", "Les Boston Celtics", "Les Philadelphia 76ers"], "Toronto a battu Golden State en finale, une première pour une équipe canadienne."),
    (4, "Quel trophée individuel Pascal Siakam a-t-il reçu en 2019 ?", "Joueur ayant le plus progressé",
     ["Meilleur débutant", "Meilleur sixième homme", "Meilleur défenseur", "MVP de la saison régulière"], "Il a été élu joueur ayant le plus progressé de la saison NBA 2018-2019."),
    (4, "Quelle université américaine Luc Mbah a Moute, né à Yaoundé, a-t-il fréquentée avant la NBA ?", "UCLA",
     ["Kansas", "Duke", "Kentucky", "Gonzaga"], "Il a été choisi par Milwaukee à la draft de 2008."),
    (4, "Dans quel village de l'Ouest du Cameroun est né Francis Ngannou ?", "Batié",
     ["Bafang", "Dschang", "Foumban", "Bangangté", "Mbouda"], "Il a travaillé dans des carrières de sable avant de rejoindre l'Europe."),
    (3, "Quel combattant américain Francis Ngannou a-t-il battu pour devenir champion UFC des poids lourds en mars 2021 ?", "Stipe Miocic",
     ["Derrick Lewis", "Junior dos Santos", "Daniel Cormier", "Curtis Blaydes"], "Il l'a battu par K.-O. au deuxième round, à UFC 260."),
    (4, "Quel combattant français Francis Ngannou a-t-il battu à UFC 270, en janvier 2022, pour conserver son titre ?", "Ciryl Gane",
     ["Derrick Lewis", "Curtis Blaydes", "Alistair Overeem", "Tom Aspinall"], "Victoire aux points, à Anaheim, en Californie."),
    (4, "Quel boxeur britannique a battu Francis Ngannou par décision partagée lors du combat de boxe d'octobre 2023 à Riyad ?", "Tyson Fury",
     ["Anthony Joshua", "Deontay Wilder", "Oleksandr Usyk", "Dillian Whyte"], "Ngannou avait envoyé Fury au tapis lors de la troisième reprise."),
    (3, "Quel tennisman, dont le père camerounais était footballeur, a remporté Roland-Garros en 1983 ?", "Yannick Noah",
     ["Henri Leconte", "Guy Forget", "Jo-Wilfried Tsonga", "Gaël Monfils"], "Yannick Noah a grandi en partie à Yaoundé."),
    (4, "Quel champion américain a repéré le jeune Yannick Noah à Yaoundé, en 1971 ?", "Arthur Ashe",
     ["Jimmy Connors", "John McEnroe", "Stan Smith", "Rod Laver"], "Ashe, en tournée en Afrique, a recommandé le garçon à la Fédération française."),
    (3, "Quel sport pratiquait Zacharie Noah, le père camerounais de Yannick Noah ?", "Le football",
     ["La boxe", "Le basket-ball", "L'athlétisme", "Le handball"], "Zacharie Noah a joué en France, à Sedan."),
    (3, "Quel dirigeant camerounais a présidé la Confédération africaine de football de 1988 à 2017 ?", "Issa Hayatou",
     ["Samuel Eto'o", "Joseph-Antoine Bell", "Ahmad Ahmad", "Patrice Motsepe"], "Né à Garoua, il est resté près de trente ans à la tête de la CAF."),
    (4, "Quelle course annuelle de montagne, née en 1973, gravit le mont Cameroun depuis Buea ?", "La Course de l'Espoir",
     ["Le Marathon du Wouri", "Le Tour du Cameroun", "La Course du Noun", "Le Semi-marathon de Garoua"], "La Mount Cameroon Race of Hope attire des coureurs du monde entier."),
])

# CAN : le Cameroun a gagné ces éditions
table("cm-pers", "CM", "Sport", [
    ("1984", "en Côte d'Ivoire", 2), ("1988", "au Maroc", 3), ("2000", "au Ghana et au Nigeria", 4),
    ("2002", "au Mali", 3), ("2017", "au Gabon", 2),
], "Dans quel pays se jouait la CAN {a}, remportée par les Lions Indomptables ?",
   "En quelle année les Lions Indomptables ont-ils gagné la CAN organisée {b} ?",
   diff=3, expl="La CAN {a} s'est jouée {b} et a été gagnée par le Cameroun.", rev_expl="La CAN organisée {b} est celle de {a}.")

# ------------------------------------------------------------------ figures historiques et nationalistes
rows("cm-pers", "CM", "Personnalités", [
    (3, "En quelle année le roi douala Rudolf Duala Manga Bell a-t-il été exécuté par l'administration coloniale allemande ?", "1914",
     ["1884", "1905", "1919", "1922"], "Il a été pendu le 8 août 1914, accusé de trahison au début de la Première Guerre mondiale."),
    (4, "Quel projet colonial allemand a déclenché la résistance de Rudolf Duala Manga Bell ?", "L'expropriation de terres douala pour créer un quartier européen",
     ["La construction d'un chemin de fer vers Yaoundé", "L'instauration d'un impôt sur le cacao", "Le transfert de la capitale à Buea", "L'interdiction de la langue douala"],
     "Le plateau de Joss devait être réservé aux Européens ; Manga Bell a protesté par la voie du droit."),
    (5, "Quel proche collaborateur de Rudolf Duala Manga Bell a été exécuté avec lui à Douala en 1914 ?", "Ngosso Din",
     ["Martin-Paul Samba", "Charles Atangana", "Ruben Um Nyobè", "Ernest Ouandié"], "Ngosso Din, son secrétaire, a été pendu le même jour."),
    (5, "Quel officier camerounais de l'armée coloniale allemande a été exécuté à Ebolowa en août 1914 ?", "Martin-Paul Samba",
     ["Ngosso Din", "Charles Atangana", "Ruben Um Nyobè", "Ernest Ouandié"], "Accusé de complot contre les Allemands, il a été exécuté en août 1914."),
    (4, "Quel surnom en langue bassa, signifiant « celui qui porte la parole des siens », désignait Ruben Um Nyobè ?", "Mpodol",
     ["Ngondo", "Lamido", "Fon", "Mfon"], "Le secrétaire général de l'UPC était appelé Mpodol par ses partisans."),
    (4, "En quelle année Ruben Um Nyobè a-t-il été tué par l'armée près de Boumnyébel ?", "1958",
     ["1955", "1956", "1960", "1961"], "Il est mort le 13 septembre 1958, dans le maquis de la Sanaga-Maritime."),
    (5, "Dans quelle ville Ernest Ouandié a-t-il été exécuté en janvier 1971 ?", "Bafoussam",
     ["Douala", "Yaoundé", "Bamenda", "Ebolowa"], "Dernier grand chef de l'UPC en maquis, il a été exécuté publiquement à Bafoussam."),
    (3, "Dans quelle ville du Nord est né Ahmadou Ahidjo, premier président du Cameroun indépendant ?", "Garoua",
     ["Maroua", "Ngaoundéré", "Bertoua", "Yaoundé"], "Il a dirigé le pays de 1960 à 1982."),
    (4, "Dans quelle ville Ahmadou Ahidjo est-il mort en 1989 ?", "Dakar",
     ["Yaoundé", "Paris", "Garoua", "Abidjan"], "Il a démissionné de la présidence en novembre 1982 et a vécu en exil."),
    (4, "Quel poste André-Marie Mbida a-t-il occupé en 1957, dans le Cameroun sous tutelle française ?", "Premier ministre",
     ["Président de la République", "Haut-commissaire", "Président de l'Assemblée", "Ministre des Finances"], "Il fut le premier chef de gouvernement camerounais, avant Ahmadou Ahidjo (1958)."),
    (3, "Dans quelle ville a eu lieu la conférence constitutionnelle de juillet 1961 sur la future fédération ?", "Foumban",
     ["Buea", "Yaoundé", "Douala", "Bamenda"], "Les délégués du Cameroun français et du Southern Cameroons s'y sont réunis du 17 au 21 juillet 1961."),
    (3, "Quel dirigeant du Southern Cameroons a défendu la réunification en 1961 avec le Kamerun National Democratic Party ?", "John Ngu Foncha",
     ["Emmanuel Endeley", "John Fru Ndi", "André-Marie Mbida", "Ruben Um Nyobè"], "Foncha est devenu vice-président de la République fédérale."),
    (5, "Quel parti dirigeait John Ngu Foncha avant la réunification de 1961 ?", "Le KNDP",
     ["Le CPNC", "L'UPC", "Le SDF", "L'UDC"], "Le Kamerun National Democratic Party, rival du parti d'Endeley."),
    (4, "Dans quelle ville a été lancé le Social Democratic Front (SDF) en mai 1990 ?", "Bamenda",
     ["Buea", "Douala", "Yaoundé", "Bafoussam"], "Le lancement a eu lieu le 26 mai 1990, au moment de la réforme du multipartisme."),
    (5, "En quelle année le sultan Njoya, souverain des Bamoun, est-il mort ?", "1933",
     ["1925", "1940", "1945", "1950"], "Le roi inventeur de l'écriture bamoun est mort à Yaoundé, loin de Foumban."),
    (4, "Quel missionnaire baptiste britannique a fondé Victoria, aujourd'hui Limbé, en 1858 ?", "Alfred Saker",
     ["Gustav Nachtigal", "Eugen Zintgraff", "David Livingstone", "Kurt von Morgen"], "La ville a été fondée pour accueillir des Africains libérés de l'esclavage."),
    (5, "Quel philosophe camerounais est l'auteur de « La Crise du Muntu » (1977) ?", "Fabien Eboussi Boulaga",
     ["Achille Mbembe", "Marcien Towa", "Cheikh Anta Diop", "Paulin Hountondji"], "Cet essai discute l'authenticité africaine et la philosophie."),
    (4, "Quel penseur camerounais est l'auteur de « Critique de la raison nègre » (2013) ?", "Achille Mbembe",
     ["Fabien Eboussi Boulaga", "Cheikh Anta Diop", "Valentin-Yves Mudimbe", "Souleymane Bachir Diagne"], "Mbembe a aussi écrit « De la postcolonie » (2000)."),
    (5, "Quelle revue culturelle bilingue a été fondée en 1963 par Bernard Fonlon ?", "Abbia",
     ["Présence africaine", "Peuples noirs-Peuples africains", "Jeune Afrique", "Cameroon Tribune"], "Abbia a publié des écrits en français et en anglais."),
    (4, "Quel journaliste camerounais a fondé le journal « Le Messager » en 1979 ?", "Pius Njawé",
     ["Célestin Monga", "Mongo Beti", "René Philombe", "Jean-Baptiste Sipa"], "Pius Njawé est devenu une figure de la presse indépendante."),
])

# ------------------------------------------------------------------ écrivains
rows("cm-pers", "CM", "Littérature", [
    (4, "En quelle année « Une vie de boy » et « Le Vieux Nègre et la médaille » de Ferdinand Oyono ont-ils paru ?", "1956",
     ["1950", "1954", "1958", "1960"], "Deux romans anticolonialistes publiés la même année."),
    (4, "Comment s'appelle le jeune narrateur de « Une vie de boy » de Ferdinand Oyono ?", "Toundi Ondoua",
     ["Meka", "Denis", "Banda", "Mor-Zamba"], "Toundi tient un journal sur sa vie de domestique chez un commandant."),
    (5, "Quel roman de Ferdinand Oyono, paru en 1960, suit un jeune Camerounais parti en Europe ?", "Chemin d'Europe",
     ["Ville cruelle", "Mission terminée", "Temps de chien", "Le Fils d'Agatha Moudio"], "Le titre évoque l'attrait de l'Europe pour la jeunesse africaine."),
    (4, "Quel prix littéraire français a récompensé « Mission terminée » de Mongo Beti en 1958 ?", "Le prix Sainte-Beuve",
     ["Le prix Goncourt", "Le prix Renaudot", "Le prix Médicis", "Le prix Femina"], "Le roman met en scène un jeune bachelier de retour au village."),
    (4, "Quel essai de Mongo Beti, publié en 1972, dénonçait le régime camerounais et fut interdit en France ?", "Main basse sur le Cameroun",
     ["Remember Ruben", "Perpétue et l'habitude du malheur", "Le Roi miraculé", "Ville cruelle"], "Le livre a été interdit en France peu après sa parution."),
    (5, "Quelle revue Mongo Beti a-t-il fondée en 1978 ?", "Peuples noirs-Peuples africains",
     ["Présence africaine", "Abbia", "Jeune Afrique", "Bingo"], "Cette revue d'opposition et de réflexion était publiée en France."),
    (4, "Dans quelle ville normande Mongo Beti a-t-il enseigné au lycée Corneille ?", "Rouen",
     ["Caen", "Le Havre", "Évreux", "Dieppe"], "Professeur de lettres en France, il a vécu en exil jusqu'à son retour au Cameroun."),
    (5, "En quelle année Mongo Beti est-il rentré au Cameroun après plus de trente ans d'exil ?", "1991",
     ["1980", "1985", "1996", "2000"], "Il s'est ensuite installé à Yaoundé."),
    (4, "Quel prix de l'Académie française Calixthe Beyala a-t-elle reçu en 1996 pour « Les Honneurs perdus » ?", "Le Grand prix du roman",
     ["Le prix Goncourt", "Le prix Femina", "Le prix Renaudot", "Le prix Médicis"], "Elle est née à Douala en 1961."),
    (3, "Quelle romancière camerounaise est l'auteure du « Petit Prince de Belleville » (1992) ?", "Calixthe Beyala",
     ["Léonora Miano", "Werewere Liking", "Mariama Bâ", "Aminata Sow Fall"], "Le roman se passe dans un quartier populaire de Paris."),
    (4, "Quel prix a reçu Léonora Miano en 2006 pour « Contours du jour qui vient » ?", "Le prix Goncourt des lycéens",
     ["Le prix Goncourt", "Le prix Renaudot", "Le prix Femina", "Le prix Médicis"], "Elle est née à Douala en 1973."),
    (5, "Quel est le premier roman de Léonora Miano, publié en 2005 ?", "L'Intérieur de la nuit",
     ["Contours du jour qui vient", "Tels des astres éteints", "Blues pour Élise", "Afropean Soul"], "Ce premier roman a fait connaître l'auteure."),
    (4, "Quel est le narrateur du roman « Temps de chien » de Patrice Nganang ?", "Un chien nommé Mboudjak",
     ["Un chat nommé Simba", "Un enfant des rues", "Un vieux griot", "Un perroquet"], "Le roman suit la vie d'un quartier de Yaoundé vue par un chien."),
    (5, "Quelle récompense « Temps de chien » a-t-il reçue en 2003 ?", "Le Grand prix littéraire d'Afrique noire",
     ["Le prix Goncourt", "Le prix Renaudot", "Le prix Femina", "Le prix Médicis"], "Ce premier grand succès de Nganang est paru en 2001."),
    (4, "Quel roman d'Imbolo Mbue, paru en 2016, raconte la vie d'un couple camerounais à New York ?", "Behold the Dreamers",
     ["Homegoing", "Americanah", "Half of a Yellow Sun", "Purple Hibiscus"], "Le livre a reçu le prix PEN/Faulkner en 2017."),
    (5, "Dans quelle ville du Cameroun est née la romancière Imbolo Mbue ?", "Limbé",
     ["Douala", "Yaoundé", "Bamenda", "Garoua"], "Elle vit aux États-Unis."),
    (4, "Quel Grand prix a couronné « Le Fils d'Agatha Moudio » de Francis Bebey en 1968 ?", "Le Grand prix littéraire d'Afrique noire",
     ["Le prix Goncourt", "Le prix Renaudot", "Le prix Sainte-Beuve", "Le Grand prix du roman de l'Académie française"], "Ce roman est paru en 1967."),
    (5, "En quelle année « Le Fils d'Agatha Moudio » de Francis Bebey est-il paru ?", "1967",
     ["1960", "1965", "1970", "1972"], "Le héros est un pêcheur douala qui élève un enfant qui n'est pas le sien."),
    (5, "Quel ouvrage de Francis Bebey, paru en 1969, est un essai sur les musiques africaines ?", "Musique de l'Afrique",
     ["Le Roi Albert d'Effidi", "Embarras et Cie", "La Poupée ashanti", "Le Fils d'Agatha Moudio"], "Bebey était lui-même guitariste et flûtiste."),
])

table("cm-pers", "CM", "Littérature", [
    ("Ville cruelle", "1954", 5), ("Le Pauvre Christ de Bomba", "1956", 5), ("Mission terminée", "1957", 5), ("Le Roi miraculé", "1958", 5),
    ("Main basse sur le Cameroun", "1972", 5), ("Perpétue et l'habitude du malheur", "1974", 5),
    ("C'est le soleil qui m'a brûlée", "1987", 5), ("Temps de chien", "2001", 5), ("L'Intérieur de la nuit", "2005", 5),
], "En quelle année est paru « {a} » ?", None, diff=5, expl="« {a} » est paru en {b}.")

# ------------------------------------------------------------------ musique, cinéma, arts visuels
rows("cm-pers", "CM", "Arts et musique", [
    (3, "Dans quelle ville du Cameroun est né Manu Dibango, en 1933 ?", "Douala",
     ["Yaoundé", "Garoua", "Bafoussam", "Kribi"], "Il a vécu en France dès l'adolescence avant de devenir une star mondiale."),
    (3, "En quelle année Manu Dibango est-il décédé ?", "2020",
     ["2017", "2018", "2019", "2021"], "Le saxophoniste est mort à Paris en mars 2020, à 86 ans."),
    (3, "Quelle star américaine a repris le refrain de « Soul Makossa » dans « Wanna Be Startin' Somethin' » (1983) ?", "Michael Jackson",
     ["Prince", "Stevie Wonder", "James Brown", "Lionel Richie"], "Un procès a été réglé ensuite avec Manu Dibango."),
    (5, "Quel est le titre de l'album de 1994 de Manu Dibango réunissant de nombreux invités, dont Youssou N'Dour et Peter Gabriel ?", "Wakafrika",
     ["Soul Makossa", "Africadelic", "Big Blow", "Electric Africa"], "Cet album est un manifeste de collaborations entre artistes africains et internationaux."),
    (5, "Quel chef d'orchestre congolais Manu Dibango a-t-il rejoint à Léopoldville à la fin des années 1950 ?", "Joseph Kabasele, dit Grand Kallé",
     ["Franco Luambo", "Tabu Ley Rochereau", "Papa Wemba", "Docteur Nico"], "Dibango a joué dans l'orchestre African Jazz."),
    (5, "Quel est le premier album de Richard Bona, paru en 1999 ?", "Scenes from My Life",
     ["Reverence", "Munia: The Tale", "Tiki", "Bonafied"], "Le bassiste est né à Minta, dans l'Est du Cameroun."),
    (4, "Quel groupe de bikutsi des années 1980, mené par le guitariste Zanzibar, électrifia ce rythme beti ?", "Les Têtes Brûlées",
     ["Les Camerounais", "Los Camaroes", "Les Vétérans", "Les Mangoustes"], "Leur style et leurs maquillages ont marqué une génération."),
    (5, "Quel réalisateur camerounais a signé le film « Quartier Mozart » (1992) ?", "Jean-Pierre Bekolo",
     ["Jean-Marie Teno", "Jean-Pierre Dikongué Pipa", "Ousmane Sembène", "Souleymane Cissé"], "Une comédie sur un quartier de Yaoundé."),
    (5, "Quel réalisateur camerounais a signé le documentaire « Afrique, je te plumerai » (1992) ?", "Jean-Marie Teno",
     ["Jean-Pierre Bekolo", "Jean-Pierre Dikongué Pipa", "Ousmane Sembène", "Idrissa Ouédraogo"], "Le film critique l'héritage colonial au Cameroun."),
    (5, "Quel réalisateur camerounais a signé le film « Muna Moto » (1975) ?", "Jean-Pierre Dikongué Pipa",
     ["Jean-Marie Teno", "Jean-Pierre Bekolo", "Ousmane Sembène", "Souleymane Cissé"], "Ce film est un classique du cinéma africain."),
    (5, "Quel artiste camerounais a créé le centre d'art Bandjoun Station, dans l'Ouest du pays ?", "Barthélémy Toguo",
     ["Pascale Marthine Tayou", "Samuel Fosso", "Joseph-Francis Sumégné", "Ousmane Sow"], "Toguo est né à Mbalmayo, au Cameroun."),
    (5, "Dans quelle capitale africaine le photographe camerounais Samuel Fosso a-t-il ouvert son studio dans les années 1970 ?", "Bangui",
     ["Douala", "Lagos", "Libreville", "Brazzaville"], "Ses autoportraits costumés l'ont rendu célèbre."),
    (5, "Dans quelle ville belge vit l'artiste plasticien camerounais Pascale Marthine Tayou ?", "Gand",
     ["Bruxelles", "Liège", "Anvers", "Bruges"], "Il est connu pour ses installations colorées."),
])

# ------------------------------------------------------------------ stades de la CAN 2021 et divers
rows("cm-pers", "CM", "Sport", [
    (2, "Dans quelle ville se trouve le stade Ahmadou-Ahidjo, utilisé lors de la CAN 2021 ?", "Yaoundé",
     ["Douala", "Garoua", "Bafoussam", "Limbé"], "Ce grand stade omnisports a été construit pour la CAN 1972."),
    (3, "Dans quelle ville se trouve le stade de Japoma, qui a accueilli des matches de la CAN 2021 ?", "Douala",
     ["Yaoundé", "Garoua", "Bafoussam", "Limbé"], "Le stade a été construit dans la banlieue de Douala."),
    (3, "Dans quelle ville du Nord se trouve le stade Roumdé-Adjia, site de la CAN 2021 ?", "Garoua",
     ["Maroua", "Ngaoundéré", "Bertoua", "Bamenda"], "Garoua est le chef-lieu de la région du Nord."),
    (4, "Dans quelle ville de l'Ouest se trouve le stade de Kouekong, site de la CAN 2021 ?", "Bafoussam",
     ["Dschang", "Bamenda", "Foumban", "Bangangté"], "Bafoussam est le chef-lieu de la région de l'Ouest."),
    (3, "Dans quelle ville côtière se trouve le stade omnisports utilisé lors de la CAN 2021, au pied du mont Cameroun ?", "Limbé",
     ["Kribi", "Douala", "Buea", "Édéa"], "Limbé s'appelait Victoria à l'époque coloniale."),
    (4, "Dans quelle ville se trouve le stade de la Réunification, l'un des grands stades de football du Cameroun ?", "Douala",
     ["Yaoundé", "Bafoussam", "Garoua", "Bamenda"], "Il se trouve dans le quartier de Bepanda."),
    (4, "En quelle année le Cameroun a-t-il organisé sa première CAN ?", "1972",
     ["1968", "1976", "1984", "1992"], "L'édition de 1972 s'est jouée à Yaoundé et à Douala."),
    (3, "Quel pays a organisé la Coupe d'Afrique des nations féminine 2016, finale perdue par les Lionnes contre le Nigeria ?", "Le Cameroun",
     ["Le Nigeria", "Le Ghana", "La Namibie", "L'Afrique du Sud"], "La finale s'est jouée à Yaoundé."),
    (3, "Quel est le surnom de Francis Ngannou dans le monde des arts martiaux mixtes ?", "The Predator",
     ["The Hammer", "The Spider", "Bones", "The Notorious"], "Il est né à Batié, dans l'Ouest."),
    (2, "Dans quelle ville se sont déroulés les Jeux olympiques de 2008, où Françoise Mbango Etone a gagné son second titre ?", "Pékin",
     ["Athènes", "Sydney", "Londres", "Atlanta"], "Elle a conservé son titre au triple saut."),
    (1, "Dans quel pays se sont déroulés les Jeux olympiques de 2000, remportés par le Cameroun en football ?", "En Australie",
     ["En Grèce", "Aux États-Unis", "En Chine", "Au Royaume-Uni"], "La finale s'est jouée à Sydney."),
    (3, "Dans quelle ville du Cameroun est né Roger Milla ?", "Yaoundé",
     ["Douala", "Garoua", "Bafoussam", "Limbé"], "Il a joué en France, notamment à Bastia, à Saint-Étienne et à Montpellier."),
    (1, "Quel est le sport de Samuel Eto'o ?", "Le football",
     ["Le basket-ball", "L'athlétisme", "Le tennis", "La boxe"], "Il a marqué le football camerounais et africain."),
    (1, "Quel poste occupait Roger Milla ?", "Attaquant",
     ["Gardien de but", "Défenseur central", "Arrière latéral", "Milieu défensif"], "Milla marquait par ses buts décisifs en 1990 et 1994."),
    (1, "De quel pays Joel Embiid est-il originaire ?", "Le Cameroun",
     ["Le Nigeria", "Le Gabon", "Le Tchad", "Le Congo"], "Il est né à Yaoundé en 1994."),
    (2, "Quel Camerounais joue au basket-ball et a été champion NBA avec Toronto ?", "Pascal Siakam",
     ["Joel Embiid", "Luc Mbah a Moute", "Serge Ibaka", "Dikembe Mutombo"], "Il a été sacré en 2019."),
    (2, "Quel pays était le rival du Sénégal en finale de la CAN 2021 ?", "L'Égypte",
     ["Le Cameroun", "Le Burkina Faso", "Le Maroc", "Le Nigeria"], "Le Sénégal l'a emporté aux tirs au but."),
])

# ------------------------------------------------------------------ compléments
rows("cm-pers", "CM", "Sport", [
    (5, "Quel joueur a inscrit l'unique but camerounais du Mondial 1982, contre l'Italie ?", "Grégoire M'Bida",
     ["Roger Milla", "Théophile Abega", "Jean-Pierre Tokoto", "Emmanuel Kundé"], "M'Bida a marqué lors du 1-1 à Vigo ; les Lions n'ont pas perdu un match."),
    (3, "Dans quelle ville s'est joué le quart de finale Cameroun-Angleterre au Mondial 1990 ?", "Naples",
     ["Rome", "Milan", "Turin", "Bari"], "Le match a eu lieu au stade San Paolo, le 1er juillet 1990."),
    (4, "Dans quelle ville nigériane s'est jouée la finale de la CAN 2000, remportée par le Cameroun ?", "Lagos",
     ["Abuja", "Kano", "Ibadan", "Enugu"], "Score de 2-2, puis victoire aux tirs au but contre le Nigeria."),
    (3, "Dans quelle ville du Mali s'est jouée la finale de la CAN 2002 ?", "Bamako",
     ["Ségou", "Sikasso", "Kayes", "Mopti"], "Le Cameroun a battu le Sénégal aux tirs au but."),
    (4, "Dans quelle ville du Maroc le Cameroun a-t-il battu le Nigeria en finale de la CAN 1988 ?", "Casablanca",
     ["Rabat", "Marrakech", "Fès", "Tanger"], "Victoire 1-0 sur penalty."),
    (4, "Quel club londonien a éliminé l'Ajax d'André Onana en demi-finale de la Ligue des champions 2019 ?", "Tottenham",
     ["Arsenal", "Chelsea", "West Ham", "Fulham"], "Tottenham s'est qualifié pour la finale après un retour spectaculaire."),
    (2, "Quel pays a organisé la Coupe du monde féminine 2019, deuxième participation du Cameroun ?", "La France",
     ["Le Canada", "L'Allemagne", "La Suède", "Les États-Unis"], "Le Cameroun a atteint les huitièmes de finale."),
])

rows("cm-pers", "CM", "Personnalités", [
    (5, "Quel poison a tué le dirigeant de l'UPC Félix-Roland Moumié à Genève en 1960 ?", "Le thallium",
     ["L'arsenic", "Le cyanure", "La strychnine", "Le polonium"], "Moumié est mort le 3 novembre 1960 des suites d'un empoisonnement."),
    (3, "De quel mouvement nationaliste Ruben Um Nyobè était-il le secrétaire général ?", "L'UPC",
     ["Le SDF", "Le RDPC", "Le KNDP", "L'UNC"], "L'Union des populations du Cameroun réclamait l'indépendance et la réunification."),
    (4, "Quel roi bamoun a fait construire à Foumban, au début du XXe siècle, un palais devenu musée ?", "Njoya",
     ["Rudolf Duala Manga Bell", "Charles Atangana", "Ahmadou Ahidjo", "Alfred Saker"], "Le palais des rois bamoun, achevé vers 1922, abrite un musée."),
    (4, "En quelle année est mort l'écrivain Mongo Beti ?", "2001",
     ["1996", "1998", "2003", "2005"], "Il est mort à Douala, après son retour d'exil."),
    (5, "Quel prix a obtenu « Assèze l'Africaine » de Calixthe Beyala en 1994 ?", "Le Grand prix littéraire d'Afrique noire",
     ["Le prix Goncourt", "Le prix Renaudot", "Le prix Femina", "Le prix Médicis"], "Beyala a reçu ensuite le Grand prix du roman de l'Académie française (1996)."),
    (3, "En quelle année est sorti « Soul Makossa » de Manu Dibango ?", "1972",
     ["1968", "1970", "1975", "1980"], "Le titre est devenu l'un des premiers tubes africains aux États-Unis."),
])
