"""L2 droit : droit administratif général et droit pénal général / procédure pénale (principes seulement, sans chiffres)."""
from .sup_kit import *  # source, table, classify, mcq, fq, pairs, pick, cap

C = "l2-droit"
source("sup-adm", "Droit administratif général : principes", "cours de L2 droit", "Comparer avec un manuel de droit administratif général (organisation, actes, contrats, contentieux, responsabilité) et les textes camerounais ou français selon le cas.")
source("sup-pen", "Droit pénal général et procédure pénale : principes", "cours de L2 droit", "Comparer avec un manuel de droit pénal général et de procédure pénale, et le Code pénal et le Code de procédure pénale applicables dans le pays étudié.")

# ====================================================================== DROIT ADMINISTRATIF
CA = "Droit administratif"

table(C, "adm-notions", [
    ("l'administration au sens organique", "l'ensemble des autorités et des services chargés de gérer les affaires publiques", 2),
    ("le service public", "une activité d'intérêt général assurée par une personne publique ou sous son contrôle", 2),
    ("l'intérêt général", "l'intérêt de la collectivité, qui justifie l'action de l'administration", 2),
    ("les prérogatives de puissance publique", "les pouvoirs exorbitants du droit commun dont l'administration dispose pour agir", 3),
    ("la personne publique", "un groupement doté de la personnalité juridique de droit public, comme l'État ou une commune", 2),
    ("l'établissement public", "une personne publique spécialisée, autonome, chargée d'une mission précise de service public", 3),
    ("le pouvoir discrétionnaire", "la liberté d'appréciation laissée à l'administration pour choisir la décision opportune", 3),
    ("la compétence liée", "la situation où l'administration doit décider d'une façon précise si les conditions sont réunies", 4),
    ("le principe de légalité administrative", "l'obligation pour l'administration de respecter les règles de droit qui lui sont supérieures", 2),
    ("les circonstances exceptionnelles", "une crise grave permettant à l'administration de s'écarter temporairement de la légalité ordinaire", 4),
    ("le droit administratif", "la branche du droit public qui régit l'organisation et l'activité de l'administration", 1),
    ("la collectivité territoriale décentralisée", "une personne publique locale, dotée d'organes élus, qui gère ses propres affaires", 3),
], cat=CA, src="sup-adm", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "adm-sp", [
    ("le principe de continuité du service public", "le service doit fonctionner de façon régulière, sans interruption injustifiée", 2),
    ("le principe d'égalité devant le service public", "les usagers placés dans une situation identique doivent être traités de la même façon", 2),
    ("le principe de mutabilité du service public", "le service doit pouvoir s'adapter aux besoins nouveaux et à l'évolution de l'intérêt général", 3),
    ("la neutralité du service public", "le service ne tient pas compte des opinions ou convictions des usagers", 3),
    ("la gestion en régie", "le mode d'exploitation où la personne publique assure elle-même le service avec ses propres moyens", 3),
    ("la concession de service public", "le contrat où un concessionnaire exploite le service à ses risques, rémunéré par l'exploitation", 4),
    ("l'affermage", "le contrat où un fermier exploite un ouvrage fourni par la personne publique contre redevance", 4),
    ("la délégation de service public", "le contrat confiant un service public à un tiers rémunéré selon les résultats de l'exploitation", 4),
    ("le service public administratif", "un service dont l'activité relève de la puissance publique et, en principe, du droit public", 4),
    ("le service public industriel et commercial", "un service dont l'activité ressemble à celle d'une entreprise, largement régi par le droit privé", 4),
], cat=CA, src="sup-adm", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "adm-police", [
    ("la police administrative", "l'activité préventive qui vise à maintenir l'ordre public par des mesures générales ou individuelles", 2),
    ("la police judiciaire", "l'activité répressive : constater les infractions, réunir les preuves, chercher les auteurs", 2),
    ("la tranquillité publique", "l'absence de troubles et de nuisances dans la vie collective", 2),
    ("la sécurité publique", "la prévention des accidents, des dangers et des atteintes aux personnes et aux biens", 2),
    ("la salubrité publique", "la protection de la santé collective contre les épidémies et les pollutions", 2),
    ("la police générale", "la compétence d'une autorité pour maintenir l'ordre public sur l'ensemble de son territoire", 3),
    ("la police spéciale", "un régime de police confié par un texte à une autorité pour une activité ou un domaine déterminé", 3),
    ("le principe de proportionnalité de la mesure de police", "la mesure doit être adaptée et nécessaire, sans restreindre les libertés plus qu'il n'est utile", 4),
    ("la liberté comme principe en matière de police", "la règle selon laquelle la restriction de police est l'exception, justifiée par l'ordre public", 4),
    ("l'ordre public matériel et extérieur", "l'objet classique de la police administrative, qui ne vise pas à régir les convictions intimes", 5),
], cat=CA, src="sup-adm", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "adm-actes", [
    ("l'acte administratif unilatéral", "un acte de l'administration modifiant l'ordre juridique sans le consentement des destinataires", 2),
    ("la décision individuelle", "un acte administratif dont les destinataires sont nommément désignés", 2),
    ("l'acte réglementaire", "un acte administratif à portée générale et impersonnelle qui pose des règles", 2),
    ("la circulaire", "un document par lequel un supérieur donne des instructions aux services qui lui sont subordonnés", 3),
    ("la mesure d'ordre intérieur", "une mesure mineure d'organisation du service, qui n'est en principe pas susceptible de recours", 4),
    ("le retrait de l'acte", "la disparition de l'acte avec effet rétroactif, comme s'il n'avait jamais existé", 4),
    ("l'abrogation de l'acte", "la disparition de l'acte pour l'avenir seulement", 4),
    ("l'acte créateur de droits", "un acte qui confère un avantage à son bénéficiaire, ce qui limite son retrait", 4),
    ("le privilège du préalable", "la faculté de l'administration d'imposer sa décision exécutoire sans passer d'abord par le juge", 4),
    ("l'acte préparatoire", "un acte intermédiaire qui prépare la décision finale et ne peut en principe être attaqué séparément", 4),
    ("la décision faisant grief", "un acte qui modifie la situation juridique de l'intéressé et peut donc être contesté devant le juge", 3),
    ("l'acte de gouvernement", "un acte relatif aux rapports entre pouvoirs publics ou internationaux, soustrait au juge", 5),
], cat=CA, src="sup-adm", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "adm-contrat", [
    ("le contrat administratif", "un contrat d'une personne publique lié à un service public ou comportant des clauses exorbitantes", 3),
    ("la clause exorbitante du droit commun", "une clause inhabituelle dans un contrat privé, qui donne des prérogatives à l'administration", 4),
    ("le pouvoir de modification unilatérale", "la faculté d'imposer des changements au contrat, sous réserve d'indemniser le cocontractant", 4),
    ("le pouvoir de sanction de l'administration contractante", "la faculté de sanctionner les manquements du cocontractant sans passer d'abord par le juge", 4),
    ("la résiliation pour motif d'intérêt général", "la rupture du contrat par l'administration pour l'intérêt public, avec indemnisation", 4),
    ("l'équilibre financier du contrat", "l'exigence que le cocontractant conserve une rémunération en rapport avec ses charges initiales", 4),
    ("la théorie de l'imprévision", "l'indemnisation partielle du cocontractant face à un événement imprévisible bouleversant le contrat", 5),
    ("le fait du prince", "l'indemnisation intégrale du cocontractant dont les charges croissent par une mesure extérieure", 5),
    ("les sujétions imprévues", "des difficultés matérielles exceptionnelles et imprévisibles rencontrées en exécutant un marché", 5),
    ("le marché public", "un contrat par lequel une personne publique commande des travaux, fournitures ou services", 2),
    ("la mise en concurrence", "la procédure qui garantit l'égalité des candidats et le bon emploi des deniers publics", 3),
    ("le cocontractant de l'administration", "la personne qui contracte avec la personne publique et participe à l'exécution de la mission", 2),
], cat=CA, src="sup-adm", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "adm-recours", [
    ("le recours pour excès de pouvoir", "un recours qui tend à faire annuler une décision administrative illégale", 2),
    ("le recours de plein contentieux", "un recours où le juge peut annuler, modifier la décision ou condamner l'administration à réparer", 3),
    ("le recours en interprétation", "une demande adressée au juge pour qu'il précise le sens d'un acte administratif", 4),
    ("l'exception d'illégalité", "un moyen de défense contestant, dans un litige, la légalité d'un acte sans en demander l'annulation", 5),
    ("le recours gracieux", "la demande adressée à l'auteur de l'acte pour qu'il le retire ou le modifie", 2),
    ("le recours hiérarchique", "la demande adressée au supérieur de l'auteur de l'acte pour qu'il le réforme", 2),
    ("le sursis à exécution", "la demande tendant à suspendre provisoirement l'exécution d'une décision en attendant le jugement", 3),
    ("l'intérêt pour agir", "la condition de recevabilité exigeant que le requérant soit affecté par l'acte attaqué", 3),
    ("l'effet rétroactif de l'annulation", "le fait que l'acte annulé est réputé n'avoir jamais existé à l'égard de tous", 5),
    ("la recevabilité du recours", "l'ensemble des conditions à remplir pour que le juge examine le fond de la demande", 3),
    ("le recours contentieux", "la saisine d'un juge pour trancher le litige, par opposition au recours adressé à l'administration", 2),
], cat=CA, src="sup-adm", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "adm-ouvertures", [
    ("l'incompétence", "le cas d'ouverture tenant à ce que l'auteur de l'acte n'avait pas le pouvoir de le prendre", 2),
    ("le vice de forme", "la méconnaissance d'une formalité de présentation de l'acte, comme la motivation ou la signature", 3),
    ("le vice de procédure", "l'irrégularité dans l'élaboration de l'acte, par exemple une consultation obligatoire omise", 3),
    ("le détournement de pouvoir", "l'usage d'un pouvoir légal dans un but autre que celui pour lequel il a été conféré", 3),
    ("la violation de la loi", "la contrariété du contenu de l'acte avec une règle de droit supérieure", 3),
    ("l'erreur manifeste d'appréciation", "l'erreur grossière d'appréciation des faits, sanctionnée même si l'administration choisit librement", 5),
    ("l'erreur de droit", "l'application d'une règle inexacte ou l'interprétation erronée d'un texte par l'administration", 4),
    ("l'inexactitude matérielle des faits", "le défaut de la décision fondée sur des faits qui ne se sont pas produits", 4),
    ("la légalité externe", "le contrôle de la compétence, de la forme et de la procédure de l'acte", 4),
    ("la légalité interne", "le contrôle du contenu de l'acte, de son but et de ses motifs", 4),
], cat=CA, src="sup-adm", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "adm-resp", [
    ("la faute de service", "la faute commise dans l'exercice du service, qui engage la responsabilité de l'administration", 2),
    ("la faute personnelle de l'agent", "la faute détachable du service, révélant une intention ou une gravité étrangère à la mission", 3),
    ("la responsabilité pour risque", "le fondement sans faute lié à une activité dangereuse créant un danger exceptionnel pour les tiers", 4),
    ("la rupture d'égalité devant les charges publiques", "le fondement sans faute quand un particulier supporte, pour tous, un dommage anormal et spécial", 5),
    ("le cumul de fautes", "la situation où une faute personnelle et une faute de service concourent au même dommage", 5),
    ("l'action récursoire", "l'action par laquelle l'administration qui a indemnisé la victime se retourne contre l'agent fautif", 5),
    ("le lien de causalité", "le rapport direct entre le fait générateur et le dommage, sans lequel il n'y a pas de réparation", 2),
    ("le préjudice anormal et spécial", "le dommage excédant les charges normales de la vie en société et touchant un groupe restreint", 4),
    ("la faute de la victime", "la cause qui peut atténuer ou exclure la responsabilité de l'administration", 3),
    ("le dommage de travaux publics", "le dommage causé à un tiers par l'exécution ou l'existence d'un ouvrage public", 4),
], cat=CA, src="sup-adm", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "adm-domaine", [
    ("le domaine public", "les biens publics affectés à l'usage du public ou à un service public, sous un régime protecteur", 3),
    ("le domaine privé", "les biens publics non affectés à un usage public, régis pour l'essentiel par le droit commun", 3),
    ("l'inaliénabilité du domaine public", "l'impossibilité de vendre un bien du domaine public tant qu'il n'a pas été déclassé", 4),
    ("l'imprescriptibilité du domaine public", "l'impossibilité d'acquérir un bien du domaine public par une longue possession", 4),
    ("l'insaisissabilité du domaine public", "l'impossibilité pour les créanciers de saisir les biens du domaine public", 4),
    ("le déclassement", "la décision faisant sortir un bien du domaine public pour l'intégrer au domaine privé", 4),
    ("l'affectation d'un bien", "le fait de consacrer un bien à l'usage du public ou à un service public", 3),
    ("l'autorisation d'occupation du domaine public", "le titre précaire et révocable permettant d'occuper à titre privatif le domaine public", 4),
    ("la redevance d'occupation", "la contrepartie financière due par celui qui occupe privativement le domaine public", 3),
    ("la précarité de l'occupation du domaine public", "le caractère révocable de l'autorisation, que l'administration peut retirer pour l'intérêt général", 5),
], cat=CA, src="sup-adm", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "adm-fp", [
    ("le fonctionnaire", "un agent public nommé dans un emploi permanent, placé dans une situation statutaire", 2),
    ("la situation statutaire et réglementaire", "la situation fixée par des textes, modifiables unilatéralement dans l'intérêt du service", 3),
    ("l'agent contractuel", "un agent public lié à l'administration par un contrat plutôt que par un statut", 3),
    ("le concours", "un mode de recrutement fondé sur la comparaison et le classement des candidats selon leur mérite", 2),
    ("le grade", "le titre qui donne au fonctionnaire vocation à certains emplois et lui appartient en propre", 4),
    ("l'emploi", "la fonction concrète exercée par l'agent, modifiable dans l'intérêt du service", 4),
    ("l'obligation d'obéissance hiérarchique", "le devoir d'exécuter les ordres du supérieur, sauf ordre manifestement illégal et très dommageable", 4),
    ("le secret professionnel", "l'obligation de ne pas révéler les informations confidentielles connues par ses fonctions", 3),
    ("l'obligation de neutralité du fonctionnaire", "le devoir de traiter tous les usagers de la même façon, sans manifester ses opinions dans le service", 3),
    ("le détachement", "la position où le fonctionnaire exerce hors de son corps d'origine en gardant son avancement", 5),
    ("la sanction disciplinaire", "la mesure répressive prise contre l'agent fautif, après respect des droits de la défense", 3),
    ("la règle du service fait", "le principe selon lequel la rémunération n'est due que pour le travail effectivement accompli", 4),
    ("la révocation", "la sanction disciplinaire mettant fin aux fonctions de l'agent", 3),
], cat=CA, src="sup-adm", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "adm-orga", [
    ("la centralisation", "la concentration du pouvoir de décision entre les mains des autorités centrales de l'État", 2),
    ("la déconcentration", "le transfert de pouvoirs de décision à des agents locaux de l'État restant soumis à la hiérarchie", 3),
    ("la décentralisation", "le transfert de compétences à des personnes publiques distinctes de l'État, sous tutelle", 3),
    ("la tutelle administrative", "le contrôle de l'État sur les collectivités décentralisées, limité aux cas prévus par les textes", 3),
    ("le pouvoir hiérarchique", "le pouvoir du supérieur de donner des ordres et d'annuler ou réformer les actes de ses subordonnés", 3),
    ("le pouvoir de substitution", "la faculté de la tutelle d'agir à la place d'une collectivité qui néglige une obligation légale", 5),
    ("la délégation de signature", "l'autorisation donnée à un subordonné de signer à la place de son chef, sans transfert de compétence", 4),
    ("la délégation de pouvoir", "le transfert de compétence au délégataire, qui décide en son nom propre", 5),
    ("le contrôle de légalité", "la vérification de la conformité au droit des actes pris par les collectivités locales", 3),
    ("l'État unitaire", "l'État qui ne possède qu'un seul pouvoir politique, même s'il est décentralisé", 3),
], cat=CA, src="sup-adm", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

classify(C, "adm-cl-acte", {
    "une décision individuelle": ["la nomination d'un fonctionnaire désigné", "le permis de construire délivré à un particulier", "la sanction disciplinaire infligée à un agent précis", "l'autorisation d'ouvrir un commerce accordée à une personne", "la révocation d'un agent nommément visé"],
    "un acte réglementaire": ["le décret qui organise un ministère", "l'arrêté interdisant le stationnement dans toute une rue", "le règlement fixant les conditions d'accès d'un service à tous les usagers", "l'arrêté du maire interdisant à tous la baignade sur une plage communale", "le décret fixant les règles générales d'un concours"],
    "un contrat de l'administration": ["le marché de travaux conclu avec une entreprise", "la convention de concession d'un service public", "le contrat d'affermage d'un réseau d'eau", "le marché de fournitures informatiques d'une université publique", "la convention de délégation du marché communal"],
    "une opération matérielle": ["la démolition effective d'un immeuble menaçant ruine", "le travail de balayage de la voirie par les agents communaux", "le transport d'un blessé par un véhicule de secours public", "la pose physique de panneaux de signalisation", "l'intervention effective des pompiers sur un incendie"],
}, cat=CA, src="sup-adm", fwd="À quelle catégorie appartient {item} ?", rev="Lequel de ces éléments correspond à cette catégorie : {group} ?", diff=3, expl="{item} : {group}.")

classify(C, "adm-cl-ouv", {
    "l'incompétence": ["un ministre prend une décision qui relève exclusivement d'un autre ministre", "un agent signe un acte sans avoir reçu de délégation", "un maire édicte une règle qui appartient au pouvoir central", "une autorité nomme un agent alors que le pouvoir de nomination appartient à une autre autorité"],
    "le vice de forme ou de procédure": ["une décision qui devait être motivée et ne l'est pas", "une consultation obligatoire d'un organe qui a été omise", "une sanction prononcée sans que l'agent ait pu présenter sa défense", "un acte pris sans respect de la signature exigée par les textes"],
    "le détournement de pouvoir": ["un maire interdit un spectacle pour écarter un opposant politique", "une mesure de police prise pour remplir les caisses de la commune", "une mutation d'office décidée pour punir un agent sous couvert d'intérêt du service", "un acte pris pour avantager un proche de l'autorité"],
    "la violation de la loi": ["un règlement contraire à une loi supérieure", "une décision fondée sur une règle abrogée", "une décision qui méconnaît un principe général du droit", "un arrêté dont le contenu contredit un décret de portée supérieure"],
}, cat=CA, src="sup-adm", fwd="Dans un recours pour excès de pouvoir, quel moyen d'annulation correspond à ce cas : {item} ?", rev="Quel cas relève de « {group} » ?", diff=4, expl="{item} : cela relève de {group}.")

classify(C, "adm-cl-orga", {
    "la centralisation": ["le ministre décide seul de toutes les affaires locales sans aucun relais", "toutes les décisions remontent obligatoirement au sommet de l'État", "aucun agent local ne dispose de pouvoir propre de décision", "les autorités centrales conservent l'ensemble des décisions sans transfert"],
    "la déconcentration": ["le préfet reçoit le pouvoir de décider dans son département sans consulter le ministre", "un chef de service local de l'État signe des actes qui relevaient du ministre", "des services de l'État sont implantés localement avec un pouvoir de décision délégué", "le gouverneur nommé par l'État décide sur une affaire locale en tant qu'agent de l'État"],
    "la décentralisation": ["le conseil municipal élu règle les affaires de la commune", "la région gère ses propres compétences par ses organes élus", "une collectivité dotée de la personnalité juridique vote son budget", "un établissement public autonome gère sa mission avec ses propres organes"],
    "la tutelle": ["l'État annule ou approuve un acte d'une commune dans les cas prévus par un texte", "l'autorité de contrôle saisit le juge contre un acte illégal d'une collectivité", "l'État agit à la place d'une commune qui refuse d'inscrire une dépense obligatoire", "l'autorité de contrôle vérifie la légalité des actes d'une collectivité"],
}, cat=CA, src="sup-adm", fwd="À quelle notion se rattache cette situation : {item} ?", rev="Quelle situation correspond à {group} ?", diff=3, expl="{item} : {group}.")

classify(C, "adm-cl-resp", {
    "une faute de service": ["un retard anormal dans l'envoi des secours", "le fonctionnement défectueux d'un service public", "une erreur d'appréciation commise par l'administration dans une décision illégale", "l'absence d'entretien normal d'une voie publique"],
    "une faute personnelle de l'agent": ["l'agent insulte un usager par rancune personnelle", "l'agent commet une infraction intentionnelle sans lien avec le service", "l'agent agit dans un but purement privé en utilisant sa fonction", "l'agent agit avec une intention de nuire à un usager"],
    "une responsabilité sans faute": ["un dommage anormal et spécial résultant d'une mesure légale prise dans l'intérêt général", "un accident subi par un collaborateur occasionnel du service public", "le dommage causé à un tiers par l'usage d'armes dangereuses par la police", "un dommage causé par une activité de l'administration créant un risque exceptionnel pour les tiers"],
    "une responsabilité contractuelle": ["l'administration n'exécute pas son obligation de payer son cocontractant", "l'administration manque aux clauses d'un marché qu'elle a signé", "le cocontractant obtient réparation pour le non-respect du contrat par la personne publique", "l'administration modifie illégalement les clauses d'un contrat et doit indemniser"],
}, cat=CA, src="sup-adm", fwd="Quel fondement de responsabilité correspond à ce cas : {item} ?", rev="Quel cas correspond à {group} ?", diff=4, expl="{item} : {group}.")

mcq(C, "adm-mcq", [
    ("Quel principe veut qu'un service public ne puisse être interrompu sans motif valable ?", "La continuité", ["La mutabilité", "L'imprescriptibilité", "La neutralité fiscale"], "La continuité garantit un fonctionnement régulier du service.", 1),
    ("Qu'est-ce qui distingue la police administrative de la police judiciaire ?", "La première prévient les atteintes à l'ordre public, la seconde réprime les infractions commises", ["La première punit, la seconde prévient", "La première relève du juge pénal, la seconde du maire", "Elles ont exactement le même but"], "La police administrative agit avant, la police judiciaire après l'infraction.", 2),
    ("Dans le recours pour excès de pouvoir, que demande le requérant au juge ?", "L'annulation d'un acte administratif illégal", ["L'allocation de dommages-intérêts uniquement", "La rédaction d'un nouvel acte à la place de l'administration", "La condamnation pénale de l'auteur de l'acte"], "Le recours pour excès de pouvoir est un recours en annulation.", 2),
    ("Le juge saisi d'un recours pour excès de pouvoir peut-il, en principe, réformer lui-même la décision attaquée ?", "Non, il l'annule ou la rejette sans la modifier", ["Oui, il la remplace librement", "Oui, mais seulement pour augmenter une sanction", "Oui, il doit toujours la réformer"], "Le juge de l'excès de pouvoir annule sans réformer, contrairement au plein contentieux.", 4),
    ("Quelle est la différence essentielle entre la décision individuelle et l'acte réglementaire ?", "La première vise des personnes désignées, le second pose des règles générales et impersonnelles", ["La première est écrite, le second est toujours oral", "La première est un contrat, le second est une loi", "La première émane d'un juge, le second d'un ministre"], "C'est la portée de l'acte qui les distingue.", 2),
    ("Quel est l'effet de l'annulation d'un acte par le juge de l'excès de pouvoir ?", "L'acte est réputé n'avoir jamais existé", ["L'acte disparaît seulement pour l'avenir", "L'acte reste valable pour les actes passés", "L'acte devient un contrat"], "L'annulation contentieuse est rétroactive.", 4),
    ("Quelle proposition complète correctement cette phrase : « La différence entre le retrait et l'abrogation porte surtout sur … » ?", "L'effet dans le temps de la disparition de l'acte", ["L'auteur qui peut les prononcer", "La langue de rédaction", "Le fait que l'acte soit signé ou non"], "Le retrait agit rétroactivement, l'abrogation seulement pour l'avenir.", 4),
    ("Quelle proposition complète correctement cette phrase : « dans la répartition classique des cas d'ouverture, le détournement de pouvoir relève … » ?", "De la légalité interne", ["De la légalité externe", "De la compétence juridictionnelle", "Du droit civil"], "Il porte sur le but poursuivi, donc sur le contenu de l'acte.", 4),
    ("Quelle proposition complète correctement cette phrase : « L'incompétence relève, parmi les moyens d'annulation, de … » ?", "La légalité externe", ["La légalité interne", "Le plein contentieux", "La responsabilité sans faute"], "Compétence, forme et procédure relèvent de la légalité externe.", 4),
    ("Un maire interdit un cortège pour limiter l'influence d'un adversaire politique. Quel vice est le plus probable ?", "Le détournement de pouvoir", ["L'incompétence", "Le vice de forme", "La force majeure"], "Le but poursuivi est étranger à l'ordre public.", 3),
    ("Qu'est-ce qu'un acte administratif créateur de droits ?", "Un acte qui confère un avantage à son bénéficiaire", ["Un acte qui crée une nouvelle commune", "Un acte qui punit un agent", "Un acte qui crée une infraction"], "Le retrait de tels actes est strictement encadré.", 3),
    ("Que signifie qu'une décision administrative est exécutoire ?", "Elle produit effet par elle-même, sans que l'administration doive d'abord saisir un juge", ["Elle doit être confirmée par un tribunal", "Elle ne peut jamais être contestée", "Elle n'est valable que pour une personne"], "C'est le privilège du préalable.", 3),
    ("Quelle proposition complète correctement cette phrase : « Une circulaire interprétative est en principe … » ?", "Un document donnant l'interprétation des textes aux services subordonnés", ["Un jugement du tribunal administratif", "Un contrat entre deux communes", "Une loi votée par le parlement"], "Elle s'adresse aux services et n'ajoute pas, en principe, de règle nouvelle.", 3),
    ("Quelle proposition complète correctement cette phrase : « Un contrat conclu entre une commune et une entreprise pour exécuter une mission de service public est le plus probablement … » ?", "Un contrat administratif", ["Un contrat de travail privé", "Un contrat de mariage", "Un acte réglementaire"], "L'objet de service public et la personne publique orientent vers le droit administratif.", 3),
    ("Quel pouvoir de l'administration dans un contrat administratif est le plus exorbitant du droit commun ?", "La modification unilatérale du contrat dans l'intérêt général", ["Le paiement du prix", "La signature du contrat", "La possibilité de négocier"], "Un contractant privé ne peut imposer seul des changements à son partenaire.", 4),
    ("Quelle proposition complète correctement cette phrase : « L'imprévision dans un contrat administratif suppose … » ?", "Un événement imprévisible et extérieur bouleversant temporairement l'économie du contrat", ["Une faute grave du cocontractant", "Une mesure prise par le juge", "Un défaut de paiement de l'usager"], "Elle donne lieu à une indemnité partielle.", 5),
    ("Quelle différence y a-t-il entre imprévision et force majeure ?", "L'imprévision laisse l'exécution possible avec aide financière, la force majeure la rend impossible", ["Il n'y en a aucune", "La force majeure donne toujours droit à indemnité, l'imprévision jamais", "L'imprévision est un délit, la force majeure un contrat"], "Dans l'imprévision, le cocontractant doit continuer et reçoit une aide partielle.", 5),
    ("Quel est l'objet du recours de plein contentieux le plus fréquent en matière de responsabilité ?", "Obtenir la condamnation de l'administration à réparer un dommage", ["Obtenir l'annulation d'une loi", "Obtenir la révision d'une peine pénale", "Obtenir la dissolution d'une commune"], "Le juge peut condamner l'administration à payer.", 3),
    ("Quelle proposition complète correctement cette phrase : « Le principe de mutabilité implique que … » ?", "Le service puisse évoluer pour mieux répondre à l'intérêt général", ["Les usagers puissent exiger l'immutabilité du service", "Le service ne change jamais ses règles", "Le service soit exploité sans personnel"], "Nul n'a de droit acquis au maintien d'un service tel quel.", 3),
    ("Un usager peut-il, en principe, exiger le maintien indéfini d'une règle d'organisation du service public ?", "Non, car le service doit pouvoir s'adapter", ["Oui, par le principe de continuité", "Oui, par le principe d'égalité", "Oui, grâce à la neutralité"], "La mutabilité permet de modifier les règles d'organisation.", 4),
    ("Quel principe est méconnu si une administration traite différemment, sans motif d'intérêt général, deux usagers dans une situation identique ?", "L'égalité devant le service public", ["La continuité", "La mutabilité", "L'imprescriptibilité"], "Des situations semblables appellent des traitements semblables.", 2),
    ("Une différence de traitement entre usagers est-elle toujours interdite par le principe d'égalité ?", "Non, elle est admise si les situations diffèrent ou si l'intérêt général le justifie", ["Oui, toujours", "Oui, mais seulement entre agents", "Non, jamais"], "L'égalité n'interdit pas de traiter différemment des situations différentes.", 4),
    ("Quelle proposition complète correctement cette phrase : « La faute de service est en principe … » ?", "Une faute de l'administration, dont elle doit répondre", ["Une faute dont seul l'agent répond sur ses biens dans tous les cas", "Une infraction pénale obligatoire", "Une faute de la victime"], "Elle est imputée à l'administration.", 2),
    ("Quelle proposition complète correctement cette phrase : « La responsabilité pour risque suppose … » ?", "Aucune faute de l'administration", ["Une faute lourde obligatoire", "Une infraction pénale", "Un contrat préalable"], "Le risque est un fondement de responsabilité sans faute.", 3),
    ("Quelle est la logique de la faute personnelle détachable du service ?", "Elle justifie que l'agent en réponde personnellement", ["Elle exonère toujours l'agent", "Elle rend l'acte administratif légal", "Elle supprime le dommage"], "Faute grave ou intentionnelle, étrangère à la mission.", 4),
    ("Quelle condition NE fait PAS partie des conditions classiques de la responsabilité administrative pour faute ?", "Une condamnation pénale préalable de l'agent", ["Un fait générateur fautif", "Un préjudice", "Un lien de causalité"], "La responsabilité administrative n'exige pas de condamnation pénale.", 3),
    ("Quelle proposition complète correctement cette phrase : « Un bien affecté à l'usage direct du public et aménagé à cet effet appartient en principe … » ?", "Au domaine public", ["Au domaine privé de l'État dans tous les cas", "Au patrimoine d'un particulier", "À aucune catégorie"], "L'affectation à l'usage du public est un critère du domaine public.", 3),
    ("Que se passe-t-il quand un bien du domaine public est déclassé ?", "Il peut entrer dans le domaine privé et devenir aliénable", ["Il devient inaliénable pour toujours", "Il disparaît juridiquement", "Il revient à son ancien propriétaire privé"], "Le déclassement lève la protection du domaine public.", 4),
    ("Un particulier peut-il acquérir par prescription un bien du domaine public ?", "Non, car le domaine public est imprescriptible", ["Oui, après une longue occupation", "Oui, s'il paie une redevance", "Oui, s'il y construit"], "L'imprescriptibilité protège le domaine public.", 3),
    ("Quelle proposition complète correctement cette phrase : « Le titre d'occupation du domaine public est en principe … » ?", "Précaire et révocable", ["Perpétuel et irrévocable", "Transmissible sans condition", "Gratuit dans tous les cas"], "Le domaine public ne peut être aliéné par le biais d'une occupation.", 4),
    ("Quelle proposition complète correctement cette phrase : « Un fonctionnaire est en principe … » ?", "Dans une situation légale et réglementaire", ["Dans une situation purement contractuelle", "Dans une situation de droit civil", "Hors de toute règle"], "Son statut est fixé par des textes.", 2),
    ("Qu'exprime la règle du service fait ?", "La rémunération correspond au travail effectivement accompli", ["Le fonctionnaire est payé à la tâche", "Le fonctionnaire est payé par l'usager", "Le fonctionnaire ne peut être payé"], "Pas de service accompli, pas de rémunération.", 4),
    ("Le devoir d'obéissance du fonctionnaire connaît-il une limite ?", "Oui, l'ordre manifestement illégal et gravement dommageable à l'intérêt public", ["Non, il est absolu", "Oui, tout ordre qui lui déplaît", "Oui, tout ordre oral"], "L'obéissance n'est pas aveugle.", 4),
    ("Quelle proposition complète correctement cette phrase : « dans la déconcentration, les agents locaux de l'État … » ?", "Disposent d'un pouvoir de décision mais restent sous l'autorité hiérarchique", ["Sont élus et indépendants", "N'ont aucun pouvoir", "Forment une personne publique distincte"], "La déconcentration est un aménagement de la centralisation.", 3),
    ("Quelle est la différence essentielle entre déconcentration et décentralisation ?", "La décentralisation crée des personnes publiques distinctes de l'État, pas la déconcentration", ["La décentralisation est contrôlée par la hiérarchie, la déconcentration par la tutelle", "La déconcentration suppose des élections, pas la décentralisation", "Aucune, ce sont des synonymes"], "La déconcentration reste interne à l'État.", 4),
    ("Quelle proposition complète correctement cette phrase : « Le pouvoir hiérarchique s'exerce … » ?", "À l'intérieur d'une même personne publique", ["Entre l'État et les communes", "Entre deux États", "Entre un juge et un justiciable"], "La tutelle, elle, s'exerce sur des personnes distinctes.", 4),
    ("Quelle règle encadre la tutelle sur les collectivités décentralisées ?", "Pas de tutelle sans texte", ["La tutelle est illimitée", "La tutelle est exercée par le juge pénal", "La tutelle n'existe jamais"], "L'autonomie est la règle, la tutelle l'exception encadrée.", 4),
    ("En droit camerounais, comment qualifie-t-on la forme de l'État ?", "Un État unitaire décentralisé", ["Un État fédéral", "Une confédération", "Une monarchie absolue"], "L'organisation territoriale comprend notamment des régions et des communes.", 2),
    ("Quelles sont deux catégories de collectivités territoriales décentralisées au Cameroun ?", "Les régions et les communes", ["Les cantons et les empires", "Les tribunaux et les prisons", "Les ambassades et les consulats"], "Elles sont les collectivités territoriales de l'État unitaire décentralisé.", 2),
    ("Quelle proposition complète correctement cette phrase : « Une délégation de signature entraîne … » ?", "Pas de transfert de compétence", ["Un transfert total de compétence", "La disparition du délégant", "La création d'une collectivité"], "Le délégant reste compétent et responsable.", 4),
    ("Quelle est la conséquence principale d'un défaut de motivation lorsque la motivation est exigée ?", "L'acte est exposé à l'annulation pour vice de forme", ["L'acte est automatiquement un contrat", "L'acte devient pénal", "L'acte est valide sans condition"], "La motivation est une formalité de forme.", 3),
    ("Quel est l'effet d'un acte réglementaire illégal sur un acte individuel qui en fait application ?", "L'acte individuel peut être attaqué en invoquant par exception l'illégalité du règlement", ["L'acte individuel est toujours définitivement valable", "L'acte individuel devient un règlement", "Rien, jamais"], "C'est le mécanisme de l'exception d'illégalité.", 5),
    ("Quelle autorité juridictionnelle tranche en principe les litiges relatifs à l'activité de l'administration dans un système à dualité de juridictions ?", "Le juge administratif", ["Le juge de paix en matière civile uniquement", "Le chef de service", "La police judiciaire"], "La dualité de juridictions confie le contentieux administratif à un ordre spécialisé.", 3),
    ("Qu'est-ce que la compétence liée ?", "L'obligation de prendre une décision déterminée quand les conditions sont réunies", ["La liberté totale de choisir", "Le fait de lier deux administrations", "Une alliance entre deux communes"], "L'administration n'a pas de marge de choix.", 4),
    ("Dans la compétence liée, quel moyen est le plus inopérant ?", "Contester l'opportunité du choix, puisque l'administration n'en avait pas", ["Contester la légalité de la compétence", "Contester l'existence des conditions", "Contester la forme"], "Si l'administration n'avait pas de choix, critiquer son choix est sans portée.", 5),
    ("Quelle proposition complète correctement cette phrase : « Le principe de légalité signifie que l'administration … » ?", "Est soumise au droit, y compris aux règles qu'elle édicte elle-même", ["Peut ignorer la loi", "Est juge de ses propres actes", "N'est tenue que par ses circulaires"], "L'administration agit dans le cadre juridique.", 3),
    ("Quel est l'effet des circonstances exceptionnelles sur la légalité ?", "Elles élargissent temporairement les pouvoirs de l'administration", ["Elles suppriment tout contrôle du juge", "Elles abrogent la Constitution", "Elles privent l'administration de ses pouvoirs"], "Le juge continue de contrôler ces mesures.", 4),
    ("Quelle proposition complète correctement cette phrase : « La neutralité du service public interdit … » ?", "De traiter les usagers selon leurs convictions", ["D'exercer une activité", "De percevoir une redevance", "D'être géré par une commune"], "Le service est le même pour tous.", 3),
    ("Quelle proposition complète correctement cette phrase : « Un établissement public se distingue d'un simple service de l'État par … » ?", "Sa personnalité juridique et son autonomie", ["Son absence de mission", "Son caractère toujours privé", "Son financement exclusivement par les usagers"], "Il est une personne publique spécialisée.", 3),
    ("Quelle proposition complète correctement cette phrase : « dans la gestion déléguée d'un service public, la personne publique reste en principe … » ?", "Responsable de l'organisation et du contrôle du service", ["Étrangère au service", "Titulaire de aucune prérogative", "Tenue de supprimer le service"], "Elle ne se décharge pas de sa mission.", 4),
    ("Quelle est la différence entre concession et affermage ?", "Dans l'affermage, la personne publique fournit l'ouvrage au fermier, qui lui verse une redevance", ["La concession est toujours gratuite", "L'affermage est un contrat privé", "Il n'y en a aucune"], "Le concessionnaire finance souvent l'ouvrage lui-même.", 5),
    ("Quelle proposition complète correctement cette phrase : « L'acte de gouvernement se caractérise traditionnellement par … » ?", "L'absence de contrôle du juge administratif sur lui", ["Son caractère toujours réglementaire", "Sa conclusion avec un particulier", "Son caractère exclusivement local"], "Il touche aux relations entre pouvoirs publics ou internationales.", 5),
    ("Quel est l'intérêt de la distinction entre décision exécutoire et décision exécutée ?", "Une décision peut produire effet sans qu'un juge ait à l'autoriser, mais elle reste attaquable", ["Une décision exécutée ne peut plus jamais être attaquée", "Une décision exécutoire est toujours légale", "Aucun, c'est la même chose"], "L'exécution ne couvre pas l'illégalité.", 5),
    ("En l'absence de texte, l'administration doit-elle motiver une décision défavorable ?", "Cela dépend des textes applicables, le principe général étant l'absence d'obligation sauf texte", ["Toujours sans exception", "Jamais, même si un texte l'exige", "Seulement si le juge pénal le demande"], "Le principe est la liberté de ne pas motiver, sauf texte.", 5),
    ("Qu'est-ce qu'une mesure d'ordre intérieur ?", "Une mesure d'organisation mineure, non attaquable en principe", ["Une décision de justice", "Une mesure de police générale", "Un contrat public"], "Elle ne fait en principe pas grief.", 4),
    ("Quelle est la finalité de la mise en concurrence dans les marchés publics ?", "Garantir l'égalité des candidats et le bon usage des fonds publics", ["Éliminer toute règle", "Favoriser l'entreprise la plus proche du pouvoir", "Fixer des prix identiques"], "Elle garantit la transparence.", 3),
    ("Quelle proposition complète correctement cette phrase : « Un contrat conclu entre deux personnes privées sans lien avec un service public est en principe … » ?", "Un contrat de droit privé", ["Un contrat administratif", "Un acte réglementaire", "Un acte de gouvernement"], "Aucune personne publique n'y participe.", 3),
    ("Quelle proposition complète correctement cette phrase : « La responsabilité sans faute pour rupture d'égalité devant les charges publiques suppose notamment … » ?", "Un préjudice anormal et spécial", ["Une faute lourde de l'agent", "Un contrat", "Une infraction pénale"], "Le dommage doit dépasser les charges normales.", 5),
    ("En cas de faute de service, qui répond en principe devant la victime ?", "L'administration", ["Uniquement l'agent sur ses biens propres", "Le juge", "Un tiers désigné par la victime"], "La faute est imputée au service.", 3),
    ("Quelle proposition complète correctement cette phrase : « Un recours gracieux est adressé à … » ?", "L'auteur de l'acte contesté", ["Au juge pénal", "À un tribunal arbitral", "Au Parlement"], "Il s'agit d'un recours administratif, non juridictionnel.", 2),
    ("Quelle proposition complète correctement cette phrase : « Un recours hiérarchique est adressé à … » ?", "Le supérieur hiérarchique de l'auteur de l'acte", ["À l'auteur de l'acte", "À un juge civil", "À la police judiciaire"], "Le supérieur dispose d'un pouvoir de réformation.", 2),
    ("Peut-on contester devant le juge administratif un acte purement préparatoire isolé ?", "En principe non, il n'est pas détachable de la décision finale", ["Toujours oui", "Oui, même s'il n'a aucun effet", "Seulement par le procureur"], "On attaque la décision finale.", 5),
    ("La personne morale de droit public a-t-elle la personnalité juridique ?", "Oui, elle peut avoir des droits et obligations propres", ["Non, jamais", "Oui, mais seulement en droit pénal", "Seulement si elle est une entreprise"], "L'État et les communes en sont des exemples.", 2),
    ("L'élection des organes dirigeants est-elle un trait de la décentralisation territoriale ?", "Oui, les organes sont en principe élus", ["Non, ils sont nommés par le ministre", "Non, ils sont tirés au sort", "Non, ils sont héréditaires"], "L'élection manifeste l'autonomie locale.", 3),
], cat=CA, src="sup-adm")

# ====================================================================== DROIT PÉNAL ET PROCÉDURE PÉNALE
CP = "Droit pénal"
CPP = "Procédure pénale"

table(C, "pen-principes", [
    ("le principe de légalité criminelle", "nul ne peut être poursuivi ni puni que pour des faits et selon des peines prévus par la loi", 2),
    ("la non-rétroactivité de la loi pénale plus sévère", "une loi qui crée une infraction ou aggrave une peine ne s'applique pas aux faits antérieurs", 3),
    ("la rétroactivité de la loi pénale plus douce", "la loi nouvelle moins sévère s'applique aux faits non encore jugés définitivement", 4),
    ("l'interprétation stricte de la loi pénale", "le juge ne peut étendre une incrimination à des cas non prévus par analogie", 3),
    ("la personnalité des peines", "nul n'est puni que pour son propre fait", 3),
    ("la nécessité des peines", "la loi ne doit prévoir que des peines strictement nécessaires", 4),
    ("la territorialité de la loi pénale", "la loi pénale s'applique aux infractions commises sur le territoire de l'État", 3),
    ("l'individualisation de la peine", "l'adaptation de la sanction à la personnalité de l'auteur et aux circonstances de l'infraction", 3),
    ("la règle non bis in idem", "nul ne peut être poursuivi deux fois pour les mêmes faits après un jugement définitif", 4),
    ("la présomption d'innocence", "toute personne poursuivie est tenue pour innocente tant que sa culpabilité n'est pas établie", 2),
    ("l'autorité de la chose jugée au pénal", "le caractère définitif d'une décision qui interdit de nouvelles poursuites pour les mêmes faits", 4),
], cat=CP, src="sup-pen", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "pen-elements", [
    ("l'infraction", "le comportement interdit par la loi pénale et sanctionné par une peine", 1),
    ("l'élément légal de l'infraction", "le texte qui incrimine et réprime le comportement", 2),
    ("l'élément matériel de l'infraction", "la manifestation extérieure de l'infraction : acte, omission ou résultat", 2),
    ("l'élément moral de l'infraction", "l'attitude psychologique de l'auteur : intention ou faute", 2),
    ("l'infraction intentionnelle", "l'infraction commise par une personne qui veut l'acte en connaissant son caractère interdit", 3),
    ("l'infraction non intentionnelle", "l'infraction résultant d'une imprudence ou d'une négligence sans volonté de causer le résultat", 3),
    ("le mobile", "la raison qui pousse l'auteur à agir, en principe indifférente à l'existence de l'infraction", 4),
    ("le dol spécial", "l'intention de produire un résultat particulier, exigée pour certaines infractions seulement", 5),
    ("le résultat dommageable", "la conséquence de l'acte, nécessaire pour certaines infractions et sans portée pour d'autres", 4),
    ("le lien de causalité pénale", "le rapport entre le comportement de l'auteur et le résultat qui justifie l'infraction", 4),
], cat=CP, src="sup-pen", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "pen-classif", [
    ("le crime", "l'infraction de la catégorie la plus grave", 1),
    ("le délit", "l'infraction de gravité intermédiaire", 1),
    ("la contravention", "l'infraction de la catégorie la moins grave", 1),
    ("l'infraction instantanée", "l'infraction consommée en un trait de temps", 3),
    ("l'infraction continue", "l'infraction dont l'exécution se prolonge dans le temps", 3),
    ("l'infraction d'habitude", "l'infraction qui suppose la répétition d'actes de même nature", 4),
    ("l'infraction formelle", "l'infraction consommée par le seul comportement, sans exigence d'un résultat", 4),
    ("l'infraction matérielle", "l'infraction dont la consommation suppose un résultat dommageable", 4),
    ("l'infraction d'omission", "l'infraction consistant à ne pas accomplir l'acte exigé par la loi", 3),
    ("l'infraction de commission", "l'infraction consistant à accomplir un acte interdit par la loi", 3),
    ("l'infraction politique", "l'infraction portant atteinte à l'organisation ou au fonctionnement de l'État", 4),
    ("l'infraction de droit commun", "l'infraction qui n'est pas de nature politique ni militaire", 4),
], cat=CP, src="sup-pen", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "pen-participation", [
    ("la tentative punissable", "le commencement d'exécution interrompu par une cause indépendante de la volonté de l'auteur", 3),
    ("le commencement d'exécution", "l'acte qui tend directement à commettre l'infraction, au-delà des préparatifs", 3),
    ("le désistement volontaire", "la renonciation spontanée de l'auteur avant la fin de l'acte, qui exclut la tentative", 4),
    ("l'acte préparatoire", "l'acte qui précède le commencement d'exécution et n'est en principe pas punissable", 3),
    ("la complicité", "la participation consistant à aider, assister ou provoquer l'auteur de l'infraction", 3),
    ("l'auteur principal", "la personne qui commet matériellement les actes constitutifs de l'infraction", 2),
    ("la coaction", "la situation où plusieurs personnes accomplissent ensemble les éléments constitutifs de l'infraction", 4),
    ("l'instigateur", "la personne qui pousse ou provoque autrui à commettre l'infraction", 3),
    ("l'emprunt de criminalité", "le fait que la punissabilité du complice dépend de l'existence d'un fait principal punissable", 5),
    ("l'infraction manquée", "la tentative qui échoue alors que l'auteur a accompli tous les actes nécessaires", 5),
], cat=CP, src="sup-pen", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "pen-resp", [
    ("la responsabilité pénale", "l'obligation de répondre de ses actes devant la justice répressive et de subir la peine encourue", 2),
    ("l'imputabilité", "l'aptitude de l'auteur, conscient et libre, à se voir attribuer l'infraction", 4),
    ("la légitime défense", "la riposte nécessaire et proportionnée à une atteinte injustifiée et actuelle contre soi ou autrui", 3),
    ("l'état de nécessité", "l'acte nécessaire et proportionné pour écarter un danger actuel ou imminent grave", 4),
    ("la contrainte", "la force irrésistible qui prive l'auteur de sa liberté de choix", 3),
    ("le trouble mental", "l'abolition du discernement ou du contrôle des actes au moment des faits", 3),
    ("la minorité pénale", "l'âge de l'auteur qui justifie des règles spéciales, avec priorité aux mesures éducatives", 3),
    ("l'ordre de la loi", "le texte qui prescrit ou autorise l'acte, ce qui le prive de caractère infractionnel", 4),
    ("le fait justificatif", "la circonstance objective qui retire à l'acte son caractère infractionnel", 4),
    ("la cause de non-imputabilité", "la circonstance subjective qui supprime la responsabilité de l'auteur sans effacer l'infraction", 5),
    ("l'erreur de droit invincible", "la croyance légitime et inévitable d'agir licitement, qui peut supprimer la responsabilité", 5),
    ("la responsabilité pénale des personnes morales", "la possibilité, dans les cas prévus par la loi, de poursuivre une société ou un groupement", 4),
], cat=CP, src="sup-pen", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "pen-peines", [
    ("la peine principale", "la sanction prononcée à titre principal, pouvant être appliquée seule", 2),
    ("la peine complémentaire", "la sanction qui s'ajoute à la peine principale, souvent facultative", 3),
    ("la mesure de sûreté", "la mesure préventive tournée vers la dangerosité de la personne plus que vers sa culpabilité", 4),
    ("l'emprisonnement", "la peine privative de liberté exécutée dans un établissement pénitentiaire", 1),
    ("l'amende pénale", "la peine pécuniaire versée à l'État", 2),
    ("la confiscation", "la dépossession, au profit de l'État, des biens liés à l'infraction", 3),
    ("la déchéance de droits", "la privation de certains droits civiques, civils ou professionnels", 3),
    ("le sursis", "la suspension de l'exécution de la peine sous condition de bonne conduite", 3),
    ("la grâce", "la mesure individuelle de clémence qui remet tout ou partie de la peine prononcée", 4),
    ("l'amnistie", "la mesure prévue par une loi qui efface le caractère délictueux de faits ou leurs condamnations", 4),
    ("le casier judiciaire", "le fichier qui recense les condamnations pénales", 2),
    ("la réhabilitation", "l'effacement des effets d'une condamnation, accordé ou acquis dans les conditions légales", 5),
    ("le principe de légalité des peines", "la règle selon laquelle seule une peine prévue par la loi peut être prononcée", 3),
], cat=CP, src="sup-pen", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "pen-recidive", [
    ("la récidive", "la nouvelle infraction commise après une condamnation définitive, dans les conditions légales", 3),
    ("le concours réel d'infractions", "la pluralité d'infractions distinctes commises avant une condamnation définitive pour l'une d'elles", 4),
    ("le concours idéal d'infractions", "un fait unique qui tombe sous plusieurs qualifications pénales", 5),
    ("le non-cumul des peines", "la règle limitant, en principe, l'exécution à la peine la plus forte", 4),
    ("la prescription de l'action publique", "l'extinction du droit de poursuivre l'auteur par l'écoulement du temps", 3),
    ("la prescription de la peine", "l'impossibilité d'exécuter une peine prononcée après un temps déterminé", 4),
    ("l'interruption de la prescription", "l'acte qui fait recommencer le délai à zéro", 4),
    ("la suspension de la prescription", "l'obstacle qui arrête temporairement le cours du délai sans l'effacer", 5),
    ("le délai de prescription de l'action publique", "le temps variable selon la gravité de l'infraction, au terme duquel on ne peut plus poursuivre", 4),
    ("la dispense de peine", "la déclaration de culpabilité sans peine quand les conditions légales de la dispense sont réunies", 5),
], cat=CP, src="sup-pen", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "pen-proc-acteurs", [
    ("l'action publique", "l'action tendant à l'application des peines, exercée au nom de la société", 2),
    ("l'action civile", "l'action en réparation du dommage causé par l'infraction, ouverte à la victime", 2),
    ("le ministère public", "les magistrats chargés de défendre les intérêts de la société et de requérir l'application de la loi", 2),
    ("le juge d'instruction", "le magistrat qui recherche, à charge et à décharge, les preuves dans l'information judiciaire", 3),
    ("l'officier de police judiciaire", "l'agent habilité à constater les infractions, recevoir les plaintes et mener les enquêtes", 2),
    ("la partie civile", "la victime qui se joint à la procédure pour demander réparation", 2),
    ("l'enquête préliminaire", "l'investigation de la police judiciaire visant à établir les faits avant d'éventuelles poursuites", 3),
    ("l'enquête de flagrance", "l'investigation menée dans les suites immédiates d'une infraction qui vient de se commettre", 3),
    ("l'information judiciaire", "la phase d'investigation du juge d'instruction, qui s'achève par un renvoi ou un non-lieu", 3),
    ("l'ordonnance de non-lieu", "la décision du juge d'instruction mettant fin à la procédure faute de charges suffisantes", 4),
    ("l'ordonnance de renvoi", "la décision par laquelle le juge d'instruction envoie l'affaire devant la juridiction de jugement", 4),
    ("le classement sans suite", "la décision du ministère public de ne pas engager de poursuites", 3),
    ("la citation directe", "l'acte qui saisit la juridiction de jugement sans passer par l'instruction", 4),
    ("la juridiction de jugement", "l'organe qui statue sur la culpabilité et prononce la peine", 2),
], cat=CPP, src="sup-pen", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "pen-droits", [
    ("la garde à vue", "la mesure par laquelle un officier de police judiciaire retient un suspect pour l'enquête", 3),
    ("la détention provisoire", "l'incarcération avant jugement d'une personne présumée innocente, mesure exceptionnelle", 3),
    ("le droit à l'assistance d'un avocat", "le droit pour la personne poursuivie de se faire assister par un conseil", 2),
    ("le droit de se taire", "la faculté de ne pas contribuer à sa propre incrimination", 3),
    ("le principe du contradictoire", "le droit pour chaque partie de discuter les éléments présentés par l'autre", 3),
    ("l'égalité des armes", "l'équilibre des moyens procéduraux entre l'accusation et la défense", 4),
    ("la publicité des débats", "le principe selon lequel les audiences sont ouvertes au public, sauf exceptions", 3),
    ("la loyauté de la preuve", "l'exigence que les preuves soient obtenues sans fraude ni violence", 4),
    ("la liberté de la preuve", "le principe selon lequel les infractions peuvent être prouvées par tout moyen légal", 4),
    ("la nullité de procédure", "la sanction qui écarte du dossier un acte irrégulier", 4),
    ("l'intime conviction", "la libre appréciation du juge pénal de la valeur des preuves débattues", 5),
    ("le droit d'être informé des charges", "le droit de connaître les faits reprochés dans une langue comprise", 3),
], cat=CPP, src="sup-pen", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "pen-recours", [
    ("l'appel", "la voie ordinaire pour faire rejuger l'affaire en fait et en droit par une juridiction supérieure", 2),
    ("l'opposition", "la voie ordinaire ouverte à celui jugé par défaut pour faire rejuger devant la même juridiction", 4),
    ("le pourvoi en cassation", "la voie extraordinaire qui contrôle l'application du droit sans rejuger les faits", 3),
    ("la révision", "la voie extraordinaire remettant en cause une condamnation définitive après un élément nouveau", 5),
    ("l'effet suspensif du recours", "le fait que le recours ordinaire arrête en principe l'exécution de la décision", 4),
    ("l'effet dévolutif de l'appel", "le transfert de l'affaire devant la juridiction du second degré", 5),
    ("le double degré de juridiction", "la possibilité de faire examiner le fond de l'affaire deux fois", 3),
    ("la cassation avec renvoi", "l'annulation d'une décision, suivie d'un nouveau jugement par une autre juridiction", 5),
    ("le jugement par défaut", "la décision rendue contre une partie absente alors qu'elle était régulièrement citée", 4),
], cat=CPP, src="sup-pen", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

classify(C, "pen-cl-elem", {
    "l'élément légal": ["le texte qui incrimine le comportement", "la prévision d'une peine par la loi", "la définition de l'infraction par un texte en vigueur", "la base textuelle exigée par la légalité criminelle"],
    "l'élément matériel": ["l'acte positif de soustraction d'un bien", "l'omission de porter secours", "le résultat dommageable causé à la victime", "la tentative de passer à l'acte arrêtée par un tiers"],
    "l'élément moral": ["l'intention de commettre l'acte interdit", "l'imprudence ou la négligence fautive", "la conscience et la volonté d'enfreindre la loi", "la volonté de produire un résultat précis exigé par le texte"],
    "un acte de procédure": ["la plainte déposée par la victime", "la convocation devant le tribunal", "l'audition d'un témoin par un enquêteur", "le procès-verbal d'audition rédigé par la police"],
}, cat=CP, src="sup-pen", fwd="À quelle catégorie appartient {item} ?", rev="Lequel de ces éléments correspond à cette catégorie : {group} ?", diff=3, expl="{item} : {group}.")

classify(C, "pen-cl-cause", {
    "un fait justificatif": ["la légitime défense", "l'ordre de la loi", "l'état de nécessité", "l'autorisation de la loi"],
    "une cause de non-imputabilité": ["le trouble mental abolissant le discernement", "la contrainte irrésistible", "la minorité de l'auteur", "l'erreur de droit invincible"],
    "une cause d'extinction de l'action publique": ["la mort de l'auteur", "l'amnistie", "la prescription", "la chose jugée"],
    "une peine complémentaire": ["la déchéance de certains droits", "la confiscation d'un bien ayant servi à l'infraction", "l'interdiction d'exercer une activité liée à l'infraction", "la fermeture d'un établissement ayant servi à l'infraction"],
}, cat=CP, src="sup-pen", fwd="À quelle catégorie appartient {item} ?", rev="Lequel de ces éléments correspond à cette catégorie : {group} ?", diff=4, expl="{item} : {group}.")

classify(C, "pen-cl-acteur", {
    "le ministère public": ["exercer l'action publique au nom de la société", "requérir l'application de la loi à l'audience", "diriger l'activité de la police judiciaire", "décider du classement sans suite d'une plainte"],
    "le juge d'instruction": ["instruire à charge et à décharge", "rendre une ordonnance de renvoi ou de non-lieu", "entendre les témoins dans l'information judiciaire", "ordonner des expertises durant l'instruction"],
    "l'officier de police judiciaire": ["recevoir les plaintes et dénonciations", "constater les infractions et recueillir les preuves", "procéder à une enquête préliminaire", "placer une personne en garde à vue dans les conditions légales"],
    "la juridiction de jugement": ["statuer sur la culpabilité du prévenu", "prononcer la peine après les débats", "rendre un jugement après l'audience", "apprécier la valeur des preuves débattues contradictoirement"],
}, cat=CPP, src="sup-pen", fwd="Qui accomplit cet acte : {item} ?", rev="Lequel de ces actes revient à {group} ?", diff=3, expl="{item} : cela revient à {group}.")

classify(C, "pen-cl-recours", {
    "une voie de recours ordinaire": ["l'appel", "l'opposition"],
    "une voie de recours extraordinaire": ["le pourvoi en cassation", "la révision"],
    "une cause d'extinction de la peine": ["la grâce", "la prescription de la peine"],
    "un acte du ministère public": ["la citation directe", "le classement sans suite"],
}, cat=CPP, src="sup-pen", fwd="À quelle catégorie appartient {item} ?", rev="Lequel de ces éléments correspond à cette catégorie : {group} ?", diff=4, expl="{item} : {group}.")

mcq(C, "pen-mcq", [
    ("Que signifie la formule « pas de peine sans loi » ?", "Une peine ne peut être prononcée que si la loi la prévoit", ["Le juge crée librement les peines", "La coutume suffit à punir", "Seul le chef de l'État fixe les peines"], "C'est l'expression de la légalité des peines.", 2),
    ("Quelle loi s'applique en principe à un fait commis avant l'entrée en vigueur d'une loi plus sévère ?", "L'ancienne loi", ["La loi nouvelle plus sévère", "La loi la plus sévère des deux", "Aucune loi"], "La loi pénale plus sévère ne rétroagit pas.", 3),
    ("Une loi nouvelle supprime une infraction. Quel est l'effet pour les faits antérieurs non jugés définitivement ?", "Ils ne peuvent plus être poursuivis ou punis", ["Ils restent punis comme avant", "Ils sont punis plus sévèrement", "Ils sont jugés par un autre pays"], "La loi plus douce s'applique rétroactivement.", 4),
    ("Une infraction suppose en principe la réunion de combien d'éléments constitutifs classiques ?", "Trois : légal, matériel et moral", ["Un seul : le résultat", "Deux : le juge et la victime", "Quatre : la peine, la prison, l'avocat, le témoin"], "L'élément légal, l'élément matériel et l'élément moral.", 2),
    ("Dans la distinction des infractions selon la gravité, laquelle est la plus grave ?", "Le crime", ["Le délit", "La contravention", "L'incident de procédure"], "La tripartition classe crimes, délits et contraventions par gravité décroissante.", 1),
    ("Quelle proposition complète correctement cette phrase : « La contravention est … » ?", "L'infraction la moins grave", ["L'infraction la plus grave", "Un crime de sang", "Une peine d'emprisonnement"], "C'est la catégorie inférieure de la tripartition.", 1),
    ("Quelle proposition complète correctement cette phrase : « Un étudiant prépare l'achat du matériel d'un cambriolage sans passer à l'acte. Il s'agit en principe … » ?", "D'un acte préparatoire, non punissable en tant que tentative", ["D'une tentative punissable de cambriolage", "D'un crime consommé", "D'une cause de non-imputabilité"], "Il n'y a pas de commencement d'exécution.", 3),
    ("Quelle condition distingue la tentative punissable du simple acte préparatoire ?", "Le commencement d'exécution", ["La signature d'un contrat", "L'âge de l'auteur", "La plainte de la victime"], "La tentative suppose un acte tendant directement à l'infraction.", 3),
    ("Un auteur renonce spontanément avant d'achever l'infraction. Que dire de sa tentative ?", "Elle n'est pas punissable si la renonciation est volontaire", ["Elle est toujours punissable", "Elle devient un crime", "Elle est punie plus sévèrement"], "Le désistement volontaire exclut la tentative.", 4),
    ("Quelle proposition complète correctement cette phrase : « Un échec dû à l'intervention d'un passant, indépendante de la volonté de l'auteur, laisse la tentative … » ?", "Punissable", ["Non punissable", "Éteinte par le désistement", "Transformée en contravention"], "Elle est interrompue par une cause extérieure.", 4),
    ("Quelle proposition complète correctement cette phrase : « celui qui fournit sciemment les moyens de commettre une infraction est en principe … » ?", "Complice", ["Victime", "Magistrat", "Témoin neutre"], "L'aide ou l'assistance caractérise la complicité.", 3),
    ("Quelle proposition complète correctement cette phrase : « La complicité suppose en principe … » ?", "Un fait principal punissable", ["Aucun acte de l'auteur", "Un jugement civil préalable", "L'accord de la victime"], "C'est l'emprunt de criminalité.", 4),
    ("Deux personnes tirent ensemble sur la victime. Quelle qualification est la plus naturelle ?", "Coaction", ["Complicité par aide ou assistance", "Légitime défense", "Récidive"], "Chacune accomplit les actes constitutifs.", 4),
    ("Quelle proposition complète correctement cette phrase : « celui qui reste en dehors de l'acte mais aide à le préparer est … » ?", "Un complice", ["Un coauteur", "Un auteur principal obligatoire", "Un magistrat"], "Il n'accomplit pas les éléments constitutifs lui-même.", 3),
    ("Quelle est la condition de la légitime défense relative à la riposte ?", "Elle doit être nécessaire et proportionnée", ["Elle doit être préméditée", "Elle doit être plus grave que l'attaque", "Elle doit être différée"], "Une riposte disproportionnée ne bénéficie pas du fait justificatif.", 3),
    ("Quelle est la condition relative à l'atteinte dans la légitime défense ?", "Elle doit être actuelle et injustifiée", ["Elle doit être passée", "Elle doit être légale", "Elle doit être future et hypothétique"], "On ne se défend pas contre une atteinte déjà achevée ou licite.", 4),
    ("Quelle proposition complète correctement cette phrase : « L'état de nécessité suppose en principe … » ?", "Un danger actuel ou imminent et un acte nécessaire et proportionné", ["Un danger imaginaire", "Une simple gêne économique", "Un ordre de la victime"], "Il faut sauvegarder un intérêt face à un danger réel.", 4),
    ("Quelle proposition complète correctement cette phrase : « La contrainte, cause de non-imputabilité, suppose … » ?", "Une force irrésistible", ["Une simple tentation", "Un conseil d'ami", "Un défaut d'argent"], "L'auteur n'avait pas de liberté de choix.", 3),
    ("Quelle proposition complète correctement cette phrase : « Le trouble mental irresponsabilise l'auteur lorsqu'il … » ?", "Abolit son discernement ou le contrôle de ses actes au moment des faits", ["Existe depuis l'enfance sans effet sur l'acte", "A été invoqué après les faits sans lien", "Résulte d'un simple désaccord"], "Il s'apprécie au moment de l'infraction.", 3),
    ("Quelle proposition complète correctement cette phrase : « La légitime défense est un fait justificatif, ce qui signifie que … » ?", "L'acte perd son caractère infractionnel", ["L'auteur reste coupable mais n'est pas puni", "L'infraction existe mais la peine est réduite", "La victime paie une amende"], "Le fait justificatif agit sur l'acte, non sur l'auteur.", 5),
    ("Quelle proposition complète correctement cette phrase : « Une cause de non-imputabilité, à la différence d'un fait justificatif, agit … » ?", "Sur la personne de l'auteur, sans effacer le caractère infractionnel du fait", ["Sur tous les participants de la même façon", "Sur la loi pénale elle-même", "Sur la juridiction seulement"], "Elle est subjective.", 5),
    ("Si un fait justificatif supprime l'infraction, quelle conséquence pour un complice ?", "Il n'est pas punissable, faute de fait principal punissable", ["Il reste puni comme auteur", "Il est puni plus sévèrement", "Il devient coauteur"], "L'infraction n'existe pas, donc la complicité non plus.", 5),
    ("Quelle différence y a-t-il entre peine principale et peine complémentaire ?", "La peine complémentaire s'ajoute à la principale, qui peut être prononcée seule", ["La complémentaire est toujours plus lourde", "La principale est facultative et la complémentaire obligatoire", "Aucune, ce sont des synonymes"], "La principale peut exister sans l'autre, non l'inverse en principe.", 4),
    ("Quelle proposition complète correctement cette phrase : « La mesure de sûreté repose avant tout sur … » ?", "La dangerosité de la personne", ["La vengeance de la victime", "La gravité de l'amende", "La décision du témoin"], "Elle est préventive.", 4),
    ("Quel est le critère distinctif classique entre peine et mesure de sûreté ?", "La peine sanctionne une faute, la mesure de sûreté vise à prévenir un danger", ["La mesure de sûreté est toujours plus longue", "La peine est toujours pécuniaire", "La mesure de sûreté est prononcée par la victime"], "Fonction rétributive contre fonction préventive.", 5),
    ("Quelle proposition complète correctement cette phrase : « L'internement d'un auteur irresponsable pour trouble mental mais dangereux illustre … » ?", "Une mesure de sûreté", ["Une peine principale", "Une amende", "Un fait justificatif"], "Il vise la dangerosité et non la punition.", 4),
    ("Quelle proposition complète correctement cette phrase : « La récidive suppose notamment … » ?", "Une première condamnation définitive suivie d'une nouvelle infraction", ["Deux infractions simultanées", "Une plainte classée sans suite", "Une simple suspicion antérieure"], "Il faut un premier terme définitif.", 3),
    ("Quelle différence y a-t-il entre récidive et concours d'infractions ?", "Dans le concours, aucune condamnation définitive n'est intervenue entre les infractions", ["Aucune différence", "Dans la récidive, l'auteur n'est jamais condamné", "Le concours suppose un seul fait"], "La condamnation définitive est le point de séparation.", 4),
    ("Quelle proposition complète correctement cette phrase : « dans le concours idéal, on a … » ?", "Un seul fait qui tombe sous plusieurs qualifications", ["Plusieurs faits distincts", "Un fait sans qualification", "Aucune infraction"], "La pluralité tient aux qualifications, non aux faits.", 5),
    ("Quelle règle limite en principe l'exécution des peines en cas de concours ?", "Le non-cumul des peines", ["L'addition systématique", "L'aggravation au double", "La suppression de toutes les peines"], "En principe seule la peine la plus forte s'exécute.", 4),
    ("Quelle proposition complète correctement cette phrase : « La prescription de l'action publique éteint … » ?", "Le droit d'exercer des poursuites", ["Le droit de la victime d'exister", "La loi pénale", "Le casier judiciaire d'autrui"], "Le temps écoulé empêche de poursuivre.", 3),
    ("Quelle est la différence entre prescription de l'action publique et prescription de la peine ?", "La première empêche de poursuivre, la seconde d'exécuter une peine déjà prononcée", ["La première concerne les civils, la seconde les pénaux", "Elles interviennent au même moment", "La seconde empêche de juger"], "L'une précède, l'autre suit la condamnation.", 4),
    ("Qu'est-ce qui fait recommencer le délai de prescription ?", "Un acte interruptif", ["Un acte suspensif", "Une lettre amicale", "Un mensonge de la victime"], "L'interruption efface le délai écoulé.", 4),
    ("Qui exerce l'action publique ?", "Le ministère public", ["La victime exclusivement", "Le greffier", "Le témoin"], "Elle est exercée au nom de la société, même si la victime peut parfois la mettre en mouvement.", 2),
    ("À quoi sert l'action civile exercée devant la justice pénale ?", "À obtenir la réparation du dommage causé par l'infraction", ["À obtenir la condamnation pénale seule", "À obtenir la libération du prévenu", "À fixer le taux de la peine"], "Elle est exercée par la victime.", 2),
    ("L'action publique peut-elle être exercée par la victime seule dans tous les cas ?", "Non, elle appartient au ministère public, la victime pouvant parfois la mettre en mouvement", ["Oui, toujours", "Oui, mais seulement en appel", "Non, elle appartient à l'avocat de la défense"], "La victime peut déclencher mais ne détient pas l'action publique.", 5),
    ("Que fait le ministère public s'il décide de ne pas poursuivre ?", "Il classe l'affaire sans suite", ["Il rend un jugement", "Il ordonne la détention", "Il condamne la victime"], "Le classement n'a pas l'autorité de la chose jugée.", 3),
    ("Un classement sans suite a-t-il l'autorité de la chose jugée ?", "Non, l'affaire peut en principe être rouverte tant que l'action publique n'est pas éteinte", ["Oui, définitivement", "Oui, pour dix ans", "Il équivaut à un acquittement"], "C'est une décision d'opportunité, non un jugement.", 5),
    ("Quelle proposition complète correctement cette phrase : « Le principe d'opportunité des poursuites signifie que le parquet … » ?", "Apprécie s'il y a lieu de poursuivre", ["Doit toujours poursuivre", "Ne peut jamais poursuivre", "Laisse le choix à la victime seulement"], "C'est le système de nombreux États, dont la France.", 4),
    ("Quel est le rôle du juge d'instruction ?", "Rechercher les preuves à charge et à décharge", ["Juger l'affaire au fond", "Représenter la victime", "Défendre le prévenu"], "Il instruit dans l'information judiciaire.", 2),
    ("Le juge d'instruction est-il celui qui prononce la condamnation ?", "Non, il instruit et la juridiction de jugement statue", ["Oui, toujours", "Oui, pour les contraventions", "Oui, sur demande de la victime"], "Les fonctions d'instruction et de jugement sont séparées.", 3),
    ("Qu'est-ce qu'un non-lieu ?", "Une décision mettant fin à la procédure faute de charges suffisantes ou d'infraction", ["Une condamnation avec sursis", "Un renvoi devant le tribunal", "Une mise en liberté sous caution"], "L'instruction s'achève sans poursuite devant le juge du fond.", 3),
    ("Quelle proposition complète correctement cette phrase : « L'officier de police judiciaire agit en principe … » ?", "Sous la direction du ministère public", ["Sous les ordres de l'avocat", "Sans aucun contrôle", "Sous les ordres de la victime"], "Le parquet dirige et contrôle la police judiciaire.", 3),
    ("Que fait l'officier de police judiciaire à la réception d'une plainte ?", "Il enregistre et mène des investigations", ["Il juge l'auteur", "Il prononce la peine", "Il blâme la victime"], "Il peut constater les infractions et rassembler les preuves.", 2),
    ("Quelle proposition complète correctement cette phrase : « La garde à vue vise avant tout … » ?", "Les nécessités de l'enquête", ["Punir le suspect", "Remplacer le procès", "Protéger l'avocat"], "C'est une mesure de contrainte encadrée.", 3),
    ("La garde à vue est-elle une peine ?", "Non, c'est une mesure de procédure", ["Oui, une peine principale", "Oui, une peine complémentaire", "Oui, une amende"], "Elle précède tout jugement.", 3),
    ("Pourquoi la garde à vue est-elle strictement encadrée ?", "Elle porte atteinte à la liberté d'une personne présumée innocente", ["Elle remplace le procès", "Elle sert à exécuter la peine", "Elle est réservée aux avocats"], "Les droits de la personne doivent être garantis.", 3),
    ("Quel droit fondamental la personne gardée à vue peut-elle invoquer ?", "L'assistance d'un avocat", ["Le choix de son juge", "La suppression du dossier", "Le paiement d'une indemnité"], "Il fait partie des droits de la défense.", 2),
    ("Quelle proposition complète correctement cette phrase : « La présomption d'innocence implique que la charge de la preuve incombe en principe … » ?", "À l'accusation", ["Au prévenu", "À son avocat", "Au greffier"], "Le doute profite à l'accusé.", 3),
    ("Que signifie le principe selon lequel le doute profite à l'accusé ?", "En cas de doute sérieux sur la culpabilité, l'acquittement ou la relaxe s'impose", ["Il faut condamner par prudence", "Le juge peut ordonner une peine réduite", "L'accusé doit prouver son innocence"], "C'est une conséquence de la présomption d'innocence.", 4),
    ("Quelle proposition complète correctement cette phrase : « La détention provisoire est … » ?", "Une mesure exceptionnelle prise avant jugement", ["La peine d'emprisonnement normale", "Une mesure obligatoire pour tout suspect", "Un recours contre la peine"], "La personne reste présumée innocente.", 3),
    ("Quelle proposition complète correctement cette phrase : « Le principe du contradictoire garantit … » ?", "À chaque partie la possibilité de discuter les éléments présentés contre elle", ["Que le juge choisisse la preuve à sa place", "Que la partie adverse soit exclue", "Que le dossier soit secret pour la défense"], "Il est un pilier des droits de la défense.", 3),
    ("Quelle proposition complète correctement cette phrase : « L'égalité des armes implique … » ?", "Un équilibre des droits entre l'accusation et la défense", ["Le droit de porter une arme à l'audience", "L'égalité des peines pour tous", "L'identité des juges"], "Aucune partie ne doit être placée dans une situation de net désavantage.", 4),
    ("Quelle proposition complète correctement cette phrase : « Le droit de se taire protège contre … » ?", "L'auto-incrimination contrainte", ["Toute question d'identité", "Toute audition par le juge", "Toute décision de justice"], "Nul ne peut être contraint de s'accuser.", 3),
    ("Quelle proposition complète correctement cette phrase : « La preuve obtenue par violence ou fraude est en principe … » ?", "Irrecevable ou écartée de la procédure", ["Toujours valable", "Préférée aux autres preuves", "Admise sans discussion"], "La loyauté de la preuve est une exigence de procès équitable.", 4),
    ("Si un acte de procédure est annulé, que devient-il ?", "Il est retiré du dossier et ne peut fonder la décision", ["Il est maintenu pour information", "Il devient une décision de justice", "Il est transmis à la victime"], "La nullité écarte l'acte irrégulier.", 4),
    ("Quelle proposition complète correctement cette phrase : « La liberté de la preuve en matière pénale signifie que … » ?", "Les infractions peuvent être prouvées par tout moyen légal", ["Seul l'aveu est une preuve", "Seul l'écrit est admis", "Seul un témoin peut prouver"], "Le juge apprécie librement.", 4),
    ("Quelle proposition complète correctement cette phrase : « L'appel est une voie de recours … » ?", "Ordinaire", ["Extraordinaire", "Non juridictionnelle", "Pénale et jamais civile"], "Il permet de rejuger l'affaire.", 2),
    ("Quelle proposition complète correctement cette phrase : « Le pourvoi en cassation contrôle principalement … » ?", "L'application du droit", ["Les faits seulement", "L'opportunité de la peine", "La moralité du juge"], "La Cour de cassation ne rejuge pas les faits.", 3),
    ("Au Cameroun, quelle juridiction suprême existe parmi les institutions judiciaires ?", "La Cour suprême", ["La Cour des empires", "Le Conseil des maires", "Le Tribunal des familles"], "La Cour suprême figure dans l'organisation judiciaire camerounaise.", 2),
    ("Quelle proposition complète correctement cette phrase : « La révision d'une condamnation est une voie de recours … » ?", "Extraordinaire", ["Ordinaire", "Administrative", "Policière"], "Elle suppose un élément nouveau.", 4),
    ("Quelle proposition complète correctement cette phrase : « L'opposition est ouverte à … » ?", "La personne jugée par défaut", ["La victime absente à l'audience seulement", "Le juge d'instruction", "L'avocat général"], "Elle permet de faire rejuger devant la même juridiction.", 4),
    ("Quelle proposition complète correctement cette phrase : « L'effet suspensif d'un recours ordinaire signifie que … » ?", "L'exécution de la décision est en principe suspendue", ["Le délai de prescription est supprimé", "La peine est doublée", "Le juge est remplacé"], "La décision n'est pas exécutée tant que le recours est pendant, en principe.", 4),
    ("Qu'est-ce que la chose jugée au pénal ?", "L'impossibilité de poursuivre à nouveau les mêmes faits après jugement définitif", ["La peine exécutée", "Le recours en cours", "Le dossier de l'instruction"], "C'est la règle non bis in idem.", 4),
    ("Quelle proposition complète correctement cette phrase : « Un mineur auteur d'une infraction relève en principe … » ?", "De règles spéciales privilégiant les mesures éducatives", ["Des mêmes règles que l'adulte sans distinction", "D'une absence totale d'intervention", "Du seul juge d'instruction de droit commun"], "La minorité pénale justifie un régime adapté.", 3),
    ("Quelle proposition complète correctement cette phrase : « La responsabilité pénale est en principe … » ?", "Personnelle", ["Collective et automatique", "Héréditaire", "Transmissible par contrat"], "Nul n'est puni que pour son propre fait.", 2),
    ("Quelle proposition complète correctement cette phrase : « La grâce est une mesure … » ?", "De clémence individuelle", ["De législation collective", "De procédure d'instruction", "De prescription"], "Elle remet tout ou partie de la peine prononcée.", 4),
    ("Quelle différence y a-t-il entre grâce et amnistie ?", "L'amnistie est prévue par une loi, la grâce est une mesure individuelle", ["Aucune", "La grâce efface l'infraction pour tous", "L'amnistie est prononcée par le juge d'instruction"], "L'amnistie efface le caractère délictueux, la grâce dispense de la peine.", 5),
    ("Quelle proposition complète correctement cette phrase : « L'amnistie agit principalement sur … » ?", "Le caractère infractionnel des faits ou leurs condamnations", ["La personnalité de la victime", "La compétence du juge", "La liberté du ministère public"], "Elle est décidée par la loi.", 4),
    ("Quelle proposition complète correctement cette phrase : « La mort de l'auteur éteint en principe … » ?", "L'action publique", ["L'action civile en toutes circonstances", "La loi pénale", "La juridiction"], "Les peines sont personnelles.", 3),
    ("Quelle proposition complète correctement cette phrase : « Le mobile d'un auteur est en principe … » ?", "Indifférent à l'existence de l'infraction", ["Un élément légal obligatoire", "Un fait justificatif automatique", "Une cause de prescription"], "Il peut en revanche influer sur la peine ou la qualification.", 4),
    ("Que sont les circonstances atténuantes en principe ?", "Des éléments permettant au juge d'adoucir la peine dans les limites légales", ["Des causes de suppression de l'infraction", "Des actes de la victime sans effet", "Des délais de prescription"], "Elles agissent sur la peine.", 4),
    ("Une personne morale peut-elle être pénalement responsable ?", "Oui, dans les cas prévus par la loi selon les systèmes qui l'admettent", ["Non, dans aucun système", "Oui, sans aucune condition", "Seulement si elle est publique"], "Elle est admise par plusieurs systèmes, selon des conditions précises.", 4),
    ("Que décide la juridiction de jugement lorsqu'elle estime la culpabilité non établie ?", "Elle acquitte ou relaxe le prévenu", ["Elle ordonne un non-lieu", "Elle ouvre une instruction", "Elle condamne à une amende"], "Le terme dépend de la nature de l'infraction.", 3),
    ("Quelle proposition complète correctement cette phrase : « La partie civile peut en principe demander … » ?", "Des dommages-intérêts", ["La peine de prison de l'auteur à elle seule", "Le remplacement du juge", "Le classement sans suite"], "Elle agit en réparation.", 3),
    ("Quelle proposition complète correctement cette phrase : « L'enquête de flagrance se caractérise par … » ?", "La proximité temporelle avec l'infraction", ["L'absence totale de procédure", "Le rôle exclusif de la victime", "Le jugement immédiat sans débat"], "L'infraction vient de se commettre ou s'est commise récemment.", 3),
    ("Quelle proposition complète correctement cette phrase : « La citation directe permet … » ?", "De saisir la juridiction de jugement sans instruction préalable", ["De classer sans suite", "De reporter la prescription", "De supprimer la garde à vue"], "Elle est utilisée pour les affaires simples.", 4),
    ("Qui assure en principe la défense du prévenu à l'audience ?", "Son avocat", ["Le procureur", "Le greffier", "L'officier de police judiciaire"], "La défense est assurée par le conseil.", 1),
    ("Quelle institution fait appliquer la loi pénale en défendant l'intérêt de la société dans le procès ?", "Le ministère public", ["La défense", "La victime exclusivement", "Le témoin"], "Il représente la société.", 2),
    ("Un juge peut-il condamner pour un comportement qu'aucun texte n'interdit, par simple analogie ?", "Non, l'interprétation de la loi pénale est stricte", ["Oui, s'il y a un grave dommage", "Oui, sur demande de la victime", "Oui, en cas d'urgence"], "L'analogie défavorable est exclue.", 3),
    ("Quelle proposition complète correctement cette phrase : « La légalité criminelle protège surtout … » ?", "La liberté individuelle contre l'arbitraire", ["Les intérêts du juge", "La victime seule", "L'administration pénitentiaire"], "Elle impose que la loi précède la répression.", 3),
    ("Qui, parmi ces personnes, relève des acteurs de la phase d'enquête ?", "L'officier de police judiciaire", ["Le notaire", "Le conseil municipal", "Le directeur d'école"], "Il mène les investigations sous contrôle.", 1),
    ("Quelle autorité contrôle la garde à vue effectuée par les officiers de police judiciaire ?", "Le ministère public ou un magistrat compétent", ["Le maire", "Le préfet de police uniquement", "Un témoin"], "Le contrôle judiciaire est une garantie.", 4),
    ("Que garantit la publicité des débats ?", "La transparence de la justice, sous réserve d'exceptions comme le huis clos", ["Le secret de tous les procès", "L'absence d'avocat", "La suppression de l'appel"], "Elle est un attribut du procès équitable.", 3),
    ("Quelle proposition complète correctement cette phrase : « Le huis clos est … » ?", "Une exception à la publicité des débats", ["La règle absolue de tous les procès", "Un recours contre la peine", "Une peine complémentaire"], "Il peut être ordonné pour protéger certains intérêts.", 4),
    ("Quelle proposition complète correctement cette phrase : « Un fait est qualifié de « délit continu » lorsque … » ?", "Sa consommation se prolonge dans le temps", ["Il est commis par un mineur", "Il est jugé en appel", "Il est puni d'une amende"], "L'infraction continue dure tant que l'état délictueux persiste.", 4),
    ("Quelle proposition complète correctement cette phrase : « pour une infraction matérielle, l'élément matériel inclut notamment … » ?", "Le résultat", ["La plainte de la victime", "La peine prévue", "La qualité du juge"], "Le résultat est constitutif.", 4),
    ("Quelle proposition complète correctement cette phrase : « pour une infraction formelle, la consommation intervient … » ?", "Par le seul comportement, sans exigence de résultat", ["Quand la victime porte plainte", "Après la condamnation", "Quand le juge prononce la peine"], "Le résultat est indifférent.", 4),
    ("Quelle proposition complète correctement cette phrase : « La différence entre intention et mobile est que l'intention porte sur … » ?", "L'acte et son résultat, tandis que le mobile est la raison d'agir", ["La peine, tandis que le mobile est la victime", "Le juge, tandis que le mobile est le témoin", "La loi, tandis que le mobile est le procureur"], "On peut vouloir l'acte sans se soucier de sa raison.", 5),
    ("Une imprudence suffit-elle à constituer une infraction ?", "Oui, lorsque la loi punit l'infraction non intentionnelle", ["Non, jamais", "Oui, toujours pour tout texte", "Seulement pour les mineurs"], "Certaines infractions n'exigent pas l'intention.", 4),
    ("Quelle proposition complète correctement cette phrase : « La peine d'amende pénale est versée … » ?", "À l'État", ["À la victime", "Au juge", "À l'avocat"], "La victime reçoit des dommages-intérêts, non l'amende pénale.", 3),
    ("Que signifie qu'une peine complémentaire est parfois obligatoire ?", "Le juge doit la prononcer dans les cas prévus par la loi", ["Elle peut se passer de la peine principale", "Elle est choisie par la victime", "Elle remplace le jugement"], "Certains textes l'imposent.", 5),
    ("Quelle proposition complète correctement cette phrase : « La confiscation est en principe … » ?", "Une dépossession au profit de l'État", ["Un prêt entre deux particuliers", "Un impôt sur les revenus", "Un recours de la victime"], "Elle vise des biens liés à l'infraction.", 3),
    ("Qu'est-ce que le casier judiciaire ?", "Un fichier des condamnations", ["Un dossier médical", "Un registre de naissances", "Un répertoire d'avocats"], "Il consigne les condamnations pénales.", 2),
    ("Quelle proposition complète correctement cette phrase : « Le sursis à l'exécution d'une peine implique … » ?", "La suspension conditionnelle de l'exécution", ["La suppression définitive de l'infraction", "L'augmentation de la peine", "L'annulation du jugement"], "Il est assorti d'une condition de bonne conduite.", 3),
    ("Une contrainte morale simple, comme une pression économique, constitue-t-elle automatiquement une contrainte irresponsabilisante ?", "Non, la contrainte exige une force irrésistible", ["Oui, toujours", "Oui, si l'auteur le dit", "Oui, pour tous les crimes"], "Le simple embarras n'enlève pas la liberté de choix.", 5),
    ("Quelle proposition complète correctement cette phrase : « si un auteur se défend après l'attaque pour se venger, la légitime défense est en principe … » ?", "Écartée, car l'atteinte n'est plus actuelle", ["Admise sans condition", "Admise s'il a prévenu la police", "Admise uniquement s'il y a un témoin"], "La riposte différée est une vengeance.", 4),
    ("La responsabilité pénale suppose-t-elle un auteur doté de discernement ?", "Oui, en principe, l'auteur doit pouvoir comprendre et vouloir ses actes", ["Non, jamais", "Oui, mais seulement pour les contraventions", "Non, sauf pour les mineurs"], "L'imputabilité est une condition de la responsabilité.", 3),
    ("Parmi ces acteurs, lequel n'est PAS un magistrat ?", "L'officier de police judiciaire", ["Le procureur", "Le juge d'instruction", "Le juge du siège"], "Il appartient à la police ou à la gendarmerie.", 3),
    ("Parmi ces éléments, lequel n'est PAS un élément constitutif de l'infraction ?", "La plainte de la victime", ["L'élément légal", "L'élément matériel", "L'élément moral"], "La plainte déclenche parfois les poursuites sans constituer l'infraction.", 3),
    ("Parmi ces voies de recours, laquelle est ordinaire ?", "L'appel", ["La révision", "Le pourvoi en cassation", "La grâce"], "La révision et le pourvoi sont extraordinaires.", 3),
    ("Parmi ces mesures, laquelle n'est PAS une peine ?", "La garde à vue", ["L'amende", "L'emprisonnement", "La confiscation"], "C'est une mesure d'enquête.", 3),
    ("Un parquetier requiert à l'audience. Que fait-il ?", "Il soumet ses demandes d'application de la loi au tribunal", ["Il prononce la peine lui-même", "Il défend le prévenu", "Il rédige le jugement"], "Le tribunal décide.", 3),
    ("Qui rend le jugement ?", "La juridiction de jugement", ["Le ministère public", "L'officier de police judiciaire", "La partie civile"], "Elle statue après les débats.", 1),
    ("Dans quel sens la présomption d'innocence s'applique-t-elle avant condamnation définitive ?", "La personne est considérée comme innocente", ["La personne est considérée comme coupable", "La personne est considérée comme dangereuse", "La personne est considérée comme condamnée"], "Elle persiste jusqu'à la condamnation définitive.", 2),
    ("Quelle proposition complète correctement cette phrase : « L'infraction d'omission est punissable … » ?", "Quand la loi impose d'agir et que l'auteur ne le fait pas", ["Jamais", "Toujours, sans texte", "Seulement pour les mineurs"], "Il faut une obligation d'agir prévue par la loi.", 4),
    ("Quelle proposition complète correctement cette phrase : « Le fait de ne pas porter secours à une personne en danger est un exemple d'infraction … » ?", "D'omission", ["De commission", "Politique", "Instantanée toujours"], "On sanctionne l'abstention.", 3),
    ("Quelle différence y a-t-il entre infraction instantanée et continue ?", "L'instantanée est consommée en un temps, la continue se prolonge dans le temps", ["L'instantanée est un crime et la continue un délit", "L'instantanée est civile", "La continue est toujours involontaire"], "Elle a des effets sur la prescription.", 4),
    ("Quelle proposition complète correctement cette phrase : « dans une infraction continue, la prescription commence en principe … » ?", "À la cessation de l'état délictueux", ["Dès le premier jour sans exception", "À la plainte", "Au moment du jugement"], "L'infraction dure tant que l'état persiste.", 5),
    ("Quelle proposition complète correctement cette phrase : « dans le cas de l'infraction instantanée, la prescription commence en principe … » ?", "À la commission de l'infraction", ["À la condamnation", "À l'exécution de la peine", "À la grâce"], "C'est le principe, sous réserve de règles particulières.", 4),
], cat=CP, src="sup-pen")
