"""Science politique (L2 droit) ; relations internationales, droit international public, organisations internationales (L3 droit).
Texte original. Tout est `review` : relecture par un enseignant de science politique / de droit international conseillée."""
from .sup_kit import *  # noqa: F401,F403

PO, RI = "l2-droit", "l3-droit"

source("sup-po", "Science politique : pouvoir, régimes, partis, élections, auteurs classiques", "cours de L2 droit",
       "Comparer avec un manuel de science politique / de droit constitutionnel et les œuvres citées (Weber, Montesquieu, Tocqueville, Rousseau, Hobbes, Locke, Machiavel).")
source("sup-ri", "Relations internationales : théories, concepts, histoire", "cours de L3 droit",
       "Comparer avec un manuel de relations internationales (théories, guerre froide, décolonisation, panafricanisme).")
source("sup-dip", "Droit international public : sources, sujets, traités, immunités, différends, juridictions", "cours de L3 droit",
       "Comparer avec un manuel de droit international public, le Statut de la CIJ, les Conventions de Vienne, le Statut de Rome.")
source("sup-oi", "Organisations internationales : ONU, Union africaine, organisations régionales et spécialisées", "cours de L3 droit",
       "Comparer avec la Charte de l'ONU, l'Acte constitutif de l'Union africaine et les sites officiels des organisations.")

# =====================================================================================================================
# SCIENCE POLITIQUE (l2-droit)
# =====================================================================================================================
table(PO, "pol-concepts", [
    ("l'autorité", "le pouvoir de commander dont le bien-fondé est reconnu par ceux qui obéissent", 2),
    ("la légitimité", "la croyance des gouvernés que le pouvoir est justifié et mérite obéissance", 2),
    ("la légalité", "la conformité d'un acte ou d'un pouvoir aux règles de droit en vigueur", 2),
    ("la souveraineté", "le pouvoir suprême de décider sans être soumis à une puissance supérieure", 2),
    ("l'État", "une organisation politique qui exerce son pouvoir sur un territoire et une population", 1),
    ("la nation", "une communauté humaine qui se pense unie par une histoire ou un projet commun", 2),
    ("le régime politique", "l'ensemble des institutions et des règles qui organisent l'exercice du pouvoir dans un État", 2),
    ("la citoyenneté", "le statut qui confère à l'individu des droits et des devoirs dans une communauté politique", 2),
    ("la société civile", "l'ensemble des associations et des groupes organisés qui existent en dehors de l'État", 2),
    ("le pluralisme politique", "la coexistence légale de plusieurs partis et courants qui se font concurrence", 2),
    ("la socialisation politique", "le processus par lequel un individu acquiert ses attitudes et ses valeurs politiques", 3),
    ("la participation politique", "l'ensemble des activités par lesquelles les citoyens cherchent à influencer la vie politique", 2),
], cat="Science politique : concepts", src="sup-po", fwd="Qu'est-ce que {a} en science politique ?", rev="Quelle notion désigne {b} ?")

table(PO, "pol-partis", [
    ("le bipartisme", "un système où deux grands partis se partagent l'essentiel des suffrages et alternent au pouvoir", 2),
    ("le multipartisme", "un système où de nombreux partis concourent sans qu'aucun ne domine seul durablement", 2),
    ("le parti unique", "un système où un seul parti est autorisé à exercer le pouvoir", 2),
    ("le système à parti dominant", "un système où plusieurs partis existent mais un seul gagne durablement les élections", 3),
    ("un parti de masse", "un parti qui cherche à encadrer un grand nombre d'adhérents par une organisation permanente", 3),
    ("un parti de cadres", "un parti structuré autour de notables et d'élus plutôt que d'adhérents nombreux", 4),
    ("un parti attrape-tout", "un parti qui élargit son programme pour séduire des électeurs de tous milieux", 4),
    ("une coalition", "une alliance de plusieurs partis pour gouverner ou pour concourir ensemble", 2),
    ("l'opposition", "l'ensemble des forces qui critiquent le pouvoir en place et veulent le remplacer", 2),
    ("une majorité parlementaire", "le groupe de partis qui détient le plus de sièges à l'assemblée et soutient le gouvernement", 2),
], cat="Science politique : partis", src="sup-po", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(PO, "pol-scrutins", [
    ("le scrutin majoritaire à un tour", "un mode de scrutin où est élu le candidat arrivé en tête, même sans majorité absolue", 2),
    ("le scrutin majoritaire à deux tours", "un mode de scrutin où un second tour a lieu si personne n'atteint la majorité requise d'emblée", 2),
    ("la représentation proportionnelle", "un mode de scrutin où les sièges sont répartis entre les listes en proportion de leurs voix", 2),
    ("le scrutin uninominal", "un scrutin où l'électeur choisit un seul candidat dans sa circonscription", 2),
    ("le scrutin de liste", "un scrutin où l'électeur vote pour un ensemble de candidats présentés ensemble", 2),
    ("le référendum", "la consultation directe des citoyens sur une question ou un texte", 1),
    ("le quotient électoral", "le nombre de voix qui donne droit à un siège dans certains systèmes proportionnels", 4),
    ("la méthode du plus fort reste", "une façon d'attribuer à la proportionnelle les sièges non pourvus par le quotient", 5),
    ("le découpage électoral", "le tracé des circonscriptions dans lesquelles les électeurs votent", 2),
    ("le gerrymandering", "un découpage de circonscriptions manipulé pour avantager un camp politique", 4),
    ("l'abstention", "le fait de ne pas voter alors qu'on est inscrit sur les listes électorales", 1),
    ("le suffrage censitaire", "un droit de vote réservé à ceux qui paient un certain niveau d'impôt", 3),
    ("le suffrage direct", "un mode de vote où les électeurs désignent eux-mêmes leurs élus sans intermédiaire", 2),
    ("le suffrage indirect", "un mode de vote où des grands électeurs, eux-mêmes élus, désignent à leur tour les représentants", 3),
], cat="Science politique : élections et modes de scrutin", src="sup-po", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(PO, "pol-pression", [
    ("un groupe de pression", "une organisation qui défend des intérêts particuliers auprès des décideurs sans viser le pouvoir", 3),
    ("le lobbying", "l'activité qui consiste à faire valoir des intérêts auprès des décideurs publics", 2),
    ("un syndicat", "une organisation de défense des intérêts professionnels de ses membres", 1),
    ("un mouvement social", "une action collective durable de contestation portée par des revendications communes", 3),
    ("l'opinion publique", "l'ensemble des jugements portés par les citoyens sur les questions d'intérêt public", 2),
    ("un sondage d'opinion", "une enquête menée auprès d'un échantillon censé représenter la population", 2),
    ("la propagande", "une communication systématique qui cherche à imposer des idées ou des comportements", 2),
    ("l'agenda politique", "l'ensemble des problèmes jugés dignes d'attention par les gouvernants à un moment donné", 4),
    ("le plaidoyer", "l'action visant à convaincre les décideurs de changer une politique en faveur d'une cause", 3),
    ("une ONG", "une organisation privée, non lucrative, indépendante des gouvernements et engagée pour une cause", 2),
], cat="Science politique : groupes d'intérêt et opinion", src="sup-po", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(PO, "pol-ideo", [
    ("le libéralisme politique", "une doctrine qui défend les libertés individuelles et la limitation du pouvoir de l'État", 2),
    ("le socialisme", "une doctrine qui cherche plus d'égalité par une action collective ou publique sur l'économie", 2),
    ("le conservatisme", "une orientation attachée à la préservation des institutions et des traditions héritées", 2),
    ("le nationalisme", "une idéologie qui fait de la nation la référence centrale de la légitimité politique", 2),
    ("l'anarchisme", "une doctrine qui rejette toute autorité étatique contraignante", 3),
    ("le communisme", "un courant qui vise l'abolition de la propriété privée des moyens de production", 2),
    ("l'écologisme politique", "une idéologie qui place la protection de l'environnement au cœur du projet politique", 2),
    ("le populisme", "un discours qui oppose un « peuple » vertueux à des élites jugées corrompues", 3),
    ("le totalitarisme", "un système qui prétend contrôler toute la société par un parti-État, une idéologie et la terreur", 4),
    ("le fascisme", "un mouvement autoritaire qui exalte la nation et le chef et rejette le pluralisme", 4),
], cat="Science politique : idéologies", src="sup-po", fwd="Qu'est-ce que {a} ?", rev="Quelle notion désigne {b} ?")

table(PO, "pol-formes", [
    ("un État unitaire", "un État où le pouvoir politique est centralisé autour d'un seul ordre institutionnel principal", 2),
    ("un État fédéral", "un État composé d'entités fédérées autonomes qui participent aussi au pouvoir fédéral", 2),
    ("une confédération", "une association d'États qui restent souverains et créent une structure commune par traité", 3),
    ("la décentralisation", "le transfert de compétences à des collectivités dotées de la personnalité juridique et élues", 3),
    ("la déconcentration", "le transfert de pouvoir de décision à des agents de l'État installés sur le territoire", 3),
    ("une monarchie constitutionnelle", "un régime où le roi règne dans le cadre d'une constitution qui limite ses pouvoirs", 2),
    ("une république", "un régime où le chef de l'État n'est pas héréditaire mais désigné ou élu", 2),
    ("une démocratie représentative", "un régime où les citoyens désignent des représentants qui décident à leur place", 2),
    ("une démocratie directe", "un régime où les citoyens décident eux-mêmes des lois, sans intermédiaire", 2),
    ("une dictature", "un régime où le pouvoir est concentré sans contrôle effectif ni alternance possible", 2),
    ("une théocratie", "un régime où le pouvoir est exercé au nom d'une autorité religieuse", 2),
    ("une oligarchie", "un régime où le pouvoir est exercé par un petit nombre de personnes", 2),
    ("la cohabitation", "la situation où le chef de l'État et la majorité parlementaire appartiennent à des camps opposés", 4),
], cat="Science politique : formes d'État et régimes", src="sup-po", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(PO, "pol-droit", [
    ("l'État de droit", "un État dont les gouvernants sont eux-mêmes soumis au droit et au contrôle de juges indépendants", 2),
    ("la séparation des pouvoirs", "la répartition des fonctions législative, exécutive et judiciaire entre organes distincts", 2),
    ("le contrôle de constitutionnalité", "la vérification de la conformité des lois à la Constitution", 3),
    ("l'alternance", "le remplacement pacifique d'une majorité par une autre à la suite d'élections", 2),
    ("la responsabilité politique", "l'obligation pour les gouvernants de répondre de leur action devant le Parlement ou le peuple", 3),
    ("la motion de censure", "le vote par lequel l'assemblée peut renverser le gouvernement", 2),
    ("la dissolution", "le pouvoir de mettre fin avant son terme au mandat de l'assemblée élue", 2),
    ("le bicamérisme", "l'organisation du Parlement en deux chambres", 2),
    ("la transition démocratique", "le passage d'un régime autoritaire à un régime pluraliste", 3),
    ("le constitutionnalisme", "l'idée que le pouvoir doit être encadré par une constitution qui protège les droits", 4),
], cat="Science politique : démocratie et État de droit", src="sup-po", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(PO, "pol-auteurs", [
    ("Machiavel", "il traite la politique comme art de conquérir et de garder le pouvoir, hors de la morale ordinaire", 3),
    ("Hobbes", "il voit dans l'état de nature une guerre de chacun contre chacun, que seul un souverain fort apaise", 3),
    ("Locke", "il soutient que des droits naturels limitent le pouvoir et que le gouvernement repose sur l'accord", 3),
    ("Rousseau", "il fonde la souveraineté sur la volonté générale du peuple, qui ne peut être aliénée", 3),
    ("Montesquieu", "il affirme que la liberté exige que le pouvoir arrête le pouvoir par la séparation des pouvoirs", 3),
    ("Tocqueville", "il analyse la marche de l'égalité des conditions et les risques de la tyrannie de la majorité", 4),
    ("Max Weber", "il définit l'État par le monopole de la violence physique légitime", 3),
    ("Robert Michels", "il énonce la loi d'airain de l'oligarchie dans les organisations, même démocratiques", 5),
    ("Joseph Schumpeter", "il définit la démocratie comme une compétition des dirigeants pour obtenir les suffrages", 5),
    ("Hannah Arendt", "elle analyse le totalitarisme comme une domination inédite par l'idéologie et la terreur", 4),
    ("Antonio Gramsci", "il développe l'hégémonie culturelle, domination par le consentement autant que par la force", 5),
    ("Maurice Duverger", "il relie les modes de scrutin aux systèmes de partis dans des lois sociologiques célèbres", 4),
    ("Robert Dahl", "il emploie le terme de polyarchie pour désigner les régimes proches de l'idéal démocratique", 5),
    ("David Easton", "il modélise le système politique par des demandes et des soutiens transformés en décisions", 5),
], cat="Science politique : auteurs et idées", src="sup-po", fwd="Quelle idée associe-t-on à {a} ?", rev="Quel auteur correspond à cette idée : {b} ?",
      expl="{A} : {b}.", min_rows=5)

table(PO, "pol-oeuvres", [
    ("le livre Le Prince", "Machiavel", 2),
    ("le livre Le Léviathan", "Thomas Hobbes", 2),
    ("le livre De l'esprit des lois", "Montesquieu", 2),
    ("le livre De la démocratie en Amérique", "Alexis de Tocqueville", 3),
    ("la conférence Le Savant et le politique", "Max Weber", 4),
    ("le livre Les Origines du totalitarisme", "Hannah Arendt", 4),
    ("le livre Capitalisme, socialisme et démocratie", "Joseph Schumpeter", 5),
    ("les Cahiers de prison", "Antonio Gramsci", 5),
    ("l'essai De la liberté", "John Stuart Mill", 4),
    ("l'ouvrage Du contrat social", "Jean-Jacques Rousseau", 2),
    ("le pamphlet de 1789 consacré au tiers état", "Emmanuel-Joseph Sieyès", 4),
    ("le livre Théorie de la justice", "John Rawls", 4),
], cat="Science politique : œuvres classiques", src="sup-po", fwd="Qui est l'auteur de {a} ?", rev="Laquelle de ces œuvres est de {b} ?",
      expl="{A} est de {b}.")

classify(PO, "pol-reg", {
    "un régime parlementaire": [
        "le gouvernement est politiquement responsable devant l'assemblée",
        "l'exécutif peut dissoudre l'assemblée élue",
        "le chef de l'État et le chef du gouvernement sont deux personnes distinctes",
        "l'assemblée peut renverser le gouvernement par une motion de censure"],
    "un régime présidentiel": [
        "le chef de l'État est aussi le chef du gouvernement",
        "le chef de l'exécutif est élu séparément du Parlement pour une durée fixe",
        "les ministres dépendent du président et non de la confiance du Parlement",
        "le Parlement ne peut pas renverser le gouvernement par une simple motion de censure"],
    "un régime d'assemblée": [
        "l'exécutif est subordonné à l'assemblée qui peut le révoquer à tout moment",
        "l'assemblée concentre l'essentiel du pouvoir politique",
        "le gouvernement n'est qu'un comité chargé d'appliquer les décisions de l'assemblée"],
    "un régime autoritaire": [
        "l'opposition est empêchée ou réprimée lorsqu'elle veut concourir aux élections",
        "le pouvoir n'est pas contrôlé par une justice indépendante",
        "les élections, quand elles existent, ne permettent pas une véritable alternance"],
}, cat="Science politique : régimes politiques", src="sup-po",
    fwd="À quel type de régime correspond ce trait : {item} ?", rev="Lequel de ces traits caractérise {group} ?", diff=3,
    expl="Ce trait caractérise {group}.")

classify(PO, "pol-pens", {
    "Hobbes": ["la guerre de chacun contre chacun à l'état de nature", "le souverain absolu issu du pacte", "le Léviathan"],
    "Locke": ["le droit de résistance à la tyrannie", "la propriété comme droit naturel", "le gouvernement fondé sur le consentement"],
    "Rousseau": ["la volonté générale", "la critique de la représentation politique", "le Discours sur l'origine de l'inégalité"],
    "Montesquieu": ["la théorie des climats", "les principes des gouvernements : vertu, honneur, crainte", "De l'esprit des lois"],
    "Machiavel": ["la virtù face à la fortune", "Le Prince", "les Discours sur la première décade de Tite-Live"],
    "Tocqueville": ["l'égalité des conditions", "la tyrannie de la majorité", "L'Ancien Régime et la Révolution"],
    "Max Weber": ["la domination charismatique", "l'éthique de responsabilité", "le monopole de la violence physique légitime"],
}, cat="Science politique : auteurs classiques", src="sup-po",
    fwd="À quel auteur associe-t-on : {item} ?", rev="Lequel de ces éléments est associé à {group} ?", diff=3,
    expl="{item} : idée ou œuvre associée à {group}.")

mcq(PO, "pol-mcq", [
    ("Selon Weber, sur quoi repose la domination légale-rationnelle ?",
     "Sur la croyance en la validité de règles impersonnelles et en la compétence de leurs agents",
     ["Sur le caractère sacré de coutumes transmises depuis toujours", "Sur les qualités exceptionnelles d'un chef", "Sur la seule crainte de la sanction"],
     "C'est le type de domination propre à l'État moderne et à la bureaucratie.", 3),
    ("Les fidèles d'un fondateur de mouvement lui obéissent parce qu'ils le jugent doté de qualités extraordinaires. Quel type de domination légitime (Weber) cela illustre-t-il ?",
     "La domination charismatique", ["La domination traditionnelle", "La domination légale-rationnelle", "La domination oligarchique"],
     "Le charisme repose sur le dévouement à la personne du chef.", 2),
    ("Selon Weber, quelle caractéristique distingue l'État ?",
     "Le monopole de la violence physique légitime sur un territoire",
     ["Le monopole de la production économique", "Le monopole de l'information publique", "Le monopole de la représentation nationale"],
     "Weber définit l'État par ce monopole, revendiqué avec succès sur un territoire.", 2),
    ("Que privilégie l'éthique de responsabilité, par opposition à l'éthique de conviction chez Weber ?",
     "La prise en compte des conséquences prévisibles de l'action",
     ["L'application de principes sans souci de leurs effets", "L'obéissance aveugle au chef", "La recherche exclusive du profit"],
     "L'homme politique responsable répond des conséquences de ses actes.", 4),
    ("Laquelle de ces caractéristiques est typique de la bureaucratie moderne selon Weber ?",
     "Des compétences définies par des règles impersonnelles dans une hiérarchie",
     ["La transmission héréditaire des charges", "La confusion entre biens de l'administration et biens personnels du fonctionnaire", "Une obéissance fondée sur le lien personnel avec le chef"],
     "Les trois autres propositions correspondent à des logiques patrimoniales.", 4),
    ("Un gouvernement agit dans le respect des règles en vigueur, mais la population ne croit plus qu'il soit justifié. Que peut-on dire ?",
     "Il est légal mais sa légitimité est contestée",
     ["Il est illégal mais légitime", "Il est à la fois illégal et illégitime", "Il est légitime par définition puisqu'il est légal"],
     "Légalité et légitimité ne se confondent pas.", 3),
    ("Quels sont les trois types de gouvernement distingués par Montesquieu dans De l'esprit des lois ?",
     "La république, la monarchie et le despotisme",
     ["La démocratie, l'aristocratie et l'oligarchie", "Le parlementaire, le présidentiel et l'assemblée", "Le fédéral, l'unitaire et le confédéral"],
     "La république comprend la démocratie et l'aristocratie.", 4),
    ("Selon Montesquieu, quel est le principe du despotisme ?",
     "La crainte", ["La vertu", "L'honneur", "La tolérance"],
     "Vertu pour la république, honneur pour la monarchie, crainte pour le despotisme.", 5),
    ("Quelle idée résume la thèse de Montesquieu sur la liberté politique ?",
     "Il faut que le pouvoir arrête le pouvoir",
     ["Le peuple doit tout posséder en commun", "Le souverain doit être absolu pour éviter le chaos", "La liberté consiste à obéir à la volonté générale"],
     "La séparation des pouvoirs vise à empêcher l'abus.", 3),
    ("Pourquoi, selon Hobbes, les individus acceptent-ils de se soumettre à un souverain ?",
     "Pour échapper à la guerre de chacun contre chacun qui règne à l'état de nature",
     ["Parce que le souverain a été désigné par Dieu par héritage", "Pour participer ensemble à l'expression de la volonté générale", "Parce qu'ils sont naturellement sociables et n'ont besoin d'aucune autorité"],
     "La peur de la mort violente fonde le pacte chez Hobbes.", 3),
    ("Quel droit Locke reconnaît-il au peuple face à un gouvernement qui viole les droits naturels ?",
     "Le droit de résistance", ["L'obligation d'obéir en toutes circonstances", "Le droit de désigner un souverain absolu", "Le droit de supprimer la propriété privée"],
     "Chez Locke, le pouvoir est limité et le peuple peut résister à la tyrannie.", 4),
    ("Qui défend un gouvernement fondé sur le consentement et limité par des droits naturels antérieurs à lui ?",
     "Locke", ["Hobbes", "Machiavel", "Bossuet"],
     "Locke fonde le pouvoir sur le consentement et les droits naturels.", 3),
    ("Que désigne la volonté générale chez Rousseau ?",
     "La volonté tournée vers l'intérêt commun, distincte de la simple somme des intérêts particuliers",
     ["La simple addition des volontés particulières", "La volonté du gouvernement en place", "La décision de la majorité des juges"],
     "Rousseau la distingue de la volonté de tous.", 4),
    ("Selon Rousseau, comment la souveraineté est-elle caractérisée ?",
     "Elle est inaliénable et indivisible", ["Elle est partageable entre le roi et le Parlement", "Elle se transmet définitivement à des représentants", "Elle est fondée sur le droit divin"],
     "Pour Rousseau, la souveraineté ne peut être ni cédée ni représentée.", 4),
    ("Dans la théorie de la souveraineté nationale (Sieyès), à qui appartient la souveraineté ?",
     "À la nation, entité collective distincte des individus qui la composent",
     ["À chaque citoyen pour une fraction égale", "Au monarque seul", "À l'administration permanente"],
     "La souveraineté populaire, elle, est fractionnée entre les citoyens.", 4),
    ("Quel type de mandat correspond à la souveraineté nationale ?",
     "Le mandat représentatif, où l'élu représente la nation entière", ["Le mandat impératif, strictement lié aux instructions des électeurs", "Le mandat de tutelle", "Le mandat judiciaire"],
     "Le mandat impératif est associé à la souveraineté populaire.", 4),
    ("Quel danger Tocqueville associe-t-il à la démocratie dans De la démocratie en Amérique ?",
     "La tyrannie de la majorité et l'individualisme", ["La domination d'une aristocratie héréditaire", "L'impossibilité d'établir l'égalité", "La guerre civile permanente"],
     "Il craint un despotisme doux, né du repli individuel et de la pression de la majorité.", 3),
    ("Quel rôle Tocqueville attribue-t-il aux associations civiles dans une démocratie ?",
     "Un contrepoids à l'individualisme et à l'emprise de l'État", ["Un obstacle à l'égalité", "Un relais obligatoire de l'administration", "Un substitut aux élections"],
     "Les associations apprennent aux citoyens à agir ensemble.", 4),
    ("Dans Le Prince de Machiavel, que désigne la virtù ?",
     "La capacité du prince à agir avec énergie et habileté face à la fortune", ["La vertu morale chrétienne", "La pureté des intentions", "L'obéissance aux lois divines"],
     "La virtù n'est pas la vertu morale ordinaire.", 4),
    ("Qu'est-ce qui distingue l'approche de Machiavel ?",
     "Il analyse la politique comme un domaine autonome, jugé à son efficacité", ["Il fonde le pouvoir sur le droit divin", "Il défend la démocratie directe", "Il condamne toute ruse en politique"],
     "On y voit une naissance de la pensée politique moderne.", 3),
    ("Quel mécanisme permet au Parlement de renverser le gouvernement dans un régime parlementaire ?",
     "La motion de censure", ["La dissolution", "Le droit de grâce", "Le référendum d'initiative populaire"],
     "La motion de censure engage la responsabilité politique du gouvernement.", 2),
    ("Quel mécanisme permet à l'exécutif de mettre fin avant terme au mandat de l'assemblée dans un régime parlementaire ?",
     "La dissolution", ["La motion de censure", "L'amnistie", "La navette parlementaire"],
     "La dissolution est le contrepoids de la censure.", 2),
    ("Comment décrit-on la séparation des pouvoirs du régime parlementaire ?",
     "Comme une séparation souple, avec collaboration et moyens d'action réciproques",
     ["Comme une séparation étanche sans aucun moyen d'action réciproque", "Comme une confusion totale des pouvoirs", "Comme une subordination de l'exécutif au pouvoir judiciaire"],
     "Censure et dissolution sont ces moyens d'action réciproques.", 4),
    ("Dans un régime présidentiel classique, comment le chef de l'exécutif est-il désigné ?",
     "Par le corps électoral, séparément de l'élection du Parlement", ["Par le Parlement, après un vote de confiance", "Par héritage", "Par le chef du parti majoritaire"],
     "L'élection séparée garantit son indépendance vis-à-vis du Parlement.", 3),
    ("Quel est le trait du régime semi-présidentiel ?",
     "Un président élu au suffrage direct coexiste avec un gouvernement responsable devant le Parlement",
     ["Un président non élu dirige seul un gouvernement irresponsable", "Une assemblée unique désigne et révoque le président", "Un roi héréditaire nomme librement le Parlement"],
     "Il combine éléments présidentiels et parlementaires.", 4),
    ("Selon l'observation de Duverger, quel mode de scrutin favorise tendanciellement le bipartisme ?",
     "Le scrutin majoritaire à un tour", ["La représentation proportionnelle", "Le scrutin majoritaire à deux tours", "Le scrutin indirect"],
     "Le vote utile pousse vers deux grands partis.", 4),
    ("Quel système de partis Duverger associe-t-il surtout à la représentation proportionnelle ?",
     "Le multipartisme", ["Le bipartisme", "Le parti unique", "L'absence de partis"],
     "La proportionnelle permet à de nombreux partis d'avoir des sièges.", 4),
    ("Que dit la loi d'airain de l'oligarchie de Michels ?",
     "Toute organisation, même démocratique, tend à être dominée par une petite élite dirigeante",
     ["Les élites finissent toujours par être renversées par la base", "Seuls les régimes autoritaires sont oligarchiques", "Les partis de masse restent toujours démocratiques"],
     "Michels a étudié les partis socialistes pour la formuler.", 5),
    ("Qu'est-ce que le problème du passager clandestin dans l'action collective (Olson) ?",
     "Chacun peut profiter d'un bien collectif sans contribuer, ce qui freine la mobilisation",
     ["Un électeur vote toujours pour le candidat gagnant", "Un militant change fréquemment de parti", "Un fonctionnaire détourne des fonds publics"],
     "Les groupes doivent offrir des incitations sélectives pour mobiliser.", 4),
    ("Qu'est-ce qui distingue le lobbying légitime de la corruption ?",
     "Le lobbying influence par l'information et l'argumentation, sans contrepartie illicite",
     ["Le lobbying est toujours interdit", "La corruption est une forme de plaidoyer public", "Il n'y a aucune différence juridique"],
     "La corruption suppose un échange illicite d'avantages.", 3),
    ("Que soutient Bourdieu dans son article « L'opinion publique n'existe pas » ?",
     "Les sondages fabriquent une opinion en supposant que tous ont un avis et que tous se valent",
     ["Les citoyens n'ont jamais d'avis politique", "Les sondages sont toujours parfaitement exacts", "La presse est une institution neutre"],
     "Il critique les présupposés de la technique du sondage.", 5),
    ("Que désigne l'effet d'agenda (agenda-setting) des médias ?",
     "Les médias influencent la hiérarchie des sujets que le public juge importants",
     ["Les médias imposent à chacun ses opinions sur tout", "Les médias n'ont aucune influence sur le public", "Les médias fixent les dates des élections"],
     "Ils disent moins aux gens quoi penser que sur quoi penser.", 4),
    ("Que décrit la spirale du silence (Noelle-Neumann) ?",
     "Ceux qui se croient minoritaires hésitent à parler, ce qui renforce l'opinion dominante",
     ["La disparition progressive des partis politiques", "Le refus de tout vote par les jeunes électeurs", "Le silence imposé par la censure officielle"],
     "La peur de l'isolement amplifie l'opinion jugée majoritaire.", 5),
    ("Que décrit le modèle du « two-step flow » de Lazarsfeld ?",
     "Les messages des médias atteignent souvent le public par des leaders d'opinion",
     ["Les électeurs votent en deux temps", "Les lois sont adoptées en deux lectures", "Les partis se financent en deux étapes"],
     "Les relais interpersonnels jouent un rôle clef dans l'influence.", 5),
    ("Que désigne la polyarchie chez Robert Dahl ?",
     "Un régime réel proche de l'idéal démocratique, fondé sur la compétition et la participation",
     ["Le gouvernement d'un seul", "Un régime d'aristocratie héréditaire", "Un régime où les partis sont interdits"],
     "Dahl distingue la polyarchie de la démocratie idéale.", 5),
    ("Comment Schumpeter définit-il la démocratie ?",
     "Comme une méthode où des dirigeants concourent pour obtenir les suffrages du peuple",
     ["Comme le gouvernement direct du peuple par lui-même", "Comme un régime où tous les citoyens sont égaux en richesse", "Comme la dictature de la majorité"],
     "Sa conception est dite « élitiste » ou procédurale.", 5),
    ("Dans la classification d'Aristote, quel nom porte le gouvernement du grand nombre exercé en vue du bien commun ?",
     "La politie", ["La tyrannie", "L'oligarchie", "La démocratie"],
     "Pour Aristote, la démocratie est la déviation de la politie.", 5),
    ("Quel élément distingue le totalitarisme d'une dictature classique selon Arendt ?",
     "L'ambition de contrôler toute la vie sociale au nom d'une idéologie, avec terreur et parti-État",
     ["L'absence de toute police politique", "L'ouverture au pluralisme partisan", "Le recours exclusif à des élections libres"],
     "Le totalitarisme vise à transformer la société entière.", 4),
    ("Dans le modèle de Easton, que sont les « inputs » du système politique ?",
     "Les demandes et les soutiens adressés au système", ["Les décisions rendues par le système", "Les lois votées chaque année", "Les recettes fiscales de l'État"],
     "Les décisions et actions sont les « outputs ».", 5),
    ("Qu'entend Gramsci par hégémonie culturelle ?",
     "La domination d'un groupe par le consentement obtenu par sa culture, pas seulement par la force",
     ["La domination d'un seul État sur d'autres", "Le contrôle de l'armée par un parti", "L'interdiction de toute culture étrangère"],
     "Elle s'exerce par l'école, les médias, les idées dominantes.", 5),
    ("Selon Benjamin Constant, en quoi consiste surtout la liberté des Modernes ?",
     "Dans la jouissance paisible de l'indépendance privée, garantie par des droits",
     ["Dans la participation collective et directe à tous les actes de souveraineté", "Dans l'obéissance aux dieux de la cité", "Dans l'appartenance à un ordre social héréditaire"],
     "La liberté des Anciens, elle, était surtout participation directe.", 5),
    ("Quel principe de J. S. Mill limite la liberté individuelle ?",
     "Elle ne peut être restreinte que pour empêcher de nuire à autrui", ["Elle peut être restreinte pour le bien moral de chacun", "Elle est illimitée en toutes circonstances", "Elle dépend de l'opinion de la majorité"],
     "C'est le principe du tort causé à autrui (harm principle).", 4),
    ("Un référendum d'initiative citoyenne relève davantage de quel modèle ?",
     "De la démocratie directe ou semi-directe", ["De la monarchie absolue", "De l'oligarchie", "De la théocratie"],
     "Il permet aux citoyens de décider eux-mêmes sur un sujet.", 2),
    ("Quel principe est au cœur de l'État de droit ?",
     "Les gouvernants sont eux-mêmes soumis au droit", ["Le chef de l'État fait la loi à lui seul", "La loi ne s'applique qu'aux gouvernés", "Les juges dépendent de l'exécutif"],
     "L'État de droit suppose des juges indépendants et le respect de la hiérarchie des normes.", 2),
    ("Qu'est-ce qui distingue l'État du gouvernement ?",
     "L'État est permanent, le gouvernement est l'équipe qui exerce le pouvoir à un moment donné",
     ["L'État change à chaque élection, le gouvernement est permanent", "Ils désignent exactement la même chose", "Le gouvernement est un organe du pouvoir judiciaire"],
     "Les gouvernements passent, l'État demeure.", 2),
    ("Quelle est la différence essentielle entre une fédération et une confédération ?",
     "La fédération forme un État ; la confédération reste une association d'États souverains",
     ["La fédération reste une association d'États souverains ; la confédération forme un État", "Il n'y a aucune différence juridique", "La fédération n'a pas de constitution"],
     "Dans la confédération, les États gardent leur souveraineté.", 3),
    ("Un préfet nommé par l'État reçoit un pouvoir de décision pour son département. De quel mécanisme s'agit-il ?",
     "La déconcentration", ["La décentralisation", "La fédéralisation", "La privatisation"],
     "Il s'agit d'un agent de l'État, non d'une collectivité autonome.", 3),
    ("Une région dotée de la personnalité juridique et d'organes élus gère ses propres affaires. De quel mécanisme s'agit-il ?",
     "La décentralisation", ["La déconcentration", "L'annexion", "Le centralisme"],
     "La décentralisation suppose l'autonomie juridique et des organes élus.", 3),
    ("De quelles chambres le Parlement du Cameroun est-il composé ?",
     "De l'Assemblée nationale et du Sénat", ["D'une chambre unique appelée Congrès", "De la Chambre des lords et de la Chambre des communes", "Du Sénat et de la Cour suprême"],
     "Le Parlement camerounais est bicaméral.", 2),
    ("Qu'est-ce que le pouvoir constituant dérivé ?",
     "Le pouvoir de réviser la Constitution selon les procédures qu'elle prévoit",
     ["Le pouvoir d'établir la première Constitution sans cadre juridique antérieur", "Le pouvoir de voter les lois ordinaires", "Le pouvoir de juger la constitutionnalité des lois"],
     "Le pouvoir constituant originaire, lui, crée la Constitution sans être lié.", 4),
    ("Qu'est-ce qu'une Constitution rigide ?",
     "Une Constitution dont la révision exige une procédure plus lourde que celle des lois ordinaires",
     ["Une Constitution jamais révisée", "Une Constitution non écrite", "Une Constitution modifiée par simple décret"],
     "Elle est protégée contre les modifications trop faciles.", 3),
    ("Qu'est-ce que le contrôle de constitutionnalité a priori ?",
     "Un contrôle exercé avant la promulgation de la loi", ["Un contrôle exercé après plusieurs années d'application", "Un contrôle exercé uniquement par les citoyens", "Un contrôle exercé sur les décisions de justice"],
     "Le contrôle a posteriori intervient sur une loi déjà en vigueur.", 4),
    ("Quel effet est fréquemment associé à la représentation proportionnelle ?",
     "Une meilleure représentation des petits partis, avec davantage de coalitions",
     ["Un bipartisme quasi automatique", "Une surreprésentation systématique du premier parti", "L'absence de listes de candidats"],
     "La proportionnelle fragmente souvent le paysage politique.", 3),
    ("Quel reproche adresse-t-on souvent au scrutin majoritaire à un tour ?",
     "Il sous-représente les petits partis et écarte les voix des candidats battus",
     ["Il oblige à organiser un second tour coûteux", "Il rend toute victoire impossible", "Il interdit les candidatures indépendantes"],
     "Le gagnant peut l'emporter avec une minorité des voix.", 3),
    ("Quel est l'objectif du modèle séquentiel du cycle d'une politique publique à sa première étape ?",
     "Faire reconnaître un problème et le mettre à l'agenda", ["Évaluer les résultats", "Mettre en œuvre le programme", "Mettre fin à la politique"],
     "La mise à l'agenda précède la décision et la mise en œuvre.", 4),
    ("Que désigne le clientélisme en science politique ?",
     "L'échange de faveurs ou de ressources contre un soutien politique", ["Le vote obligatoire", "Le financement public des partis", "Le sondage préélectoral"],
     "Il repose sur des liens personnels de dépendance.", 3),
    ("Que désigne le néopatrimonialisme ?",
     "Un système où les ressources publiques se confondent avec celles des dirigeants",
     ["Un système de retraites par capitalisation", "La gestion transparente des biens de l'État", "L'héritage obligatoire de la fonction de chef d'État"],
     "Le concept sert à analyser nombre de régimes, notamment en Afrique.", 5),
    ("Au début des années 1990, quels forums ont joué un rôle important dans les transitions politiques de plusieurs États francophones d'Afrique ?",
     "Les conférences nationales", ["Les congrès panafricains", "Les sommets des non-alignés", "Les conférences de Bandung"],
     "Elles ont rassemblé forces politiques et société civile pour fixer de nouvelles règles.", 3),
    ("Qui a défini la souveraineté comme puissance absolue et perpétuelle d'une république ?",
     "Jean Bodin", ["Thomas Hobbes", "Jean-Jacques Rousseau", "Nicolas Machiavel"],
     "Bodin publie Les Six livres de la République en 1576.", 4),
    ("Qu'est-ce qu'un plébiscite au sens courant du terme en science politique ?",
     "Un vote perçu surtout comme un vote de confiance envers une personne au pouvoir",
     ["Un vote sur une loi de finances", "Une élection indirecte du Parlement", "Un sondage privé"],
     "On distingue souvent le plébiscite du référendum par cette personnalisation.", 4),
], cat="Science politique : cas et distinctions", src="sup-po")

# =====================================================================================================================
# RELATIONS INTERNATIONALES (l3-droit)
# =====================================================================================================================
table(RI, "ri-theories", [
    ("le réalisme", "un courant pour lequel les États, en système anarchique, cherchent d'abord sécurité et puissance", 2),
    ("le libéralisme en relations internationales", "un courant qui insiste sur la coopération, les institutions et l'interdépendance entre acteurs", 3),
    ("le constructivisme", "un courant pour lequel les idées, les normes et les identités façonnent les intérêts des acteurs", 3),
    ("l'idéalisme wilsonien", "une approche de l'entre-deux-guerres qui croit à la paix par le droit et la sécurité collective", 4),
    ("la théorie de la dépendance", "une approche qui explique le sous-développement par l'inégalité entre centre et périphérie", 4),
    ("l'école anglaise", "un courant qui parle d'une société internationale d'États partageant règles et institutions", 5),
    ("le néofonctionnalisme", "une théorie de l'intégration régionale fondée sur les effets d'engrenage d'un secteur à l'autre", 5),
    ("le féminisme en relations internationales", "un courant qui étudie le rôle du genre dans les rapports de pouvoir et de sécurité", 4),
], cat="Relations internationales : théories", src="sup-ri", fwd="Qu'est-ce que {a} ?", rev="Quelle approche correspond à cette description : {b} ?")

table(RI, "ri-concepts", [
    ("l'anarchie internationale", "l'absence d'autorité centrale supérieure aux États", 2),
    ("la puissance", "la capacité d'un acteur à influencer autrui ou à lui imposer sa volonté", 2),
    ("le soft power", "la capacité d'influencer par l'attractivité et la persuasion plutôt que par la contrainte", 3),
    ("le hard power", "la capacité d'influencer par la contrainte militaire ou économique", 3),
    ("l'équilibre des puissances", "la situation où aucun État ne peut dominer les autres", 3),
    ("le dilemme de sécurité", "le fait que les mesures de sécurité d'un État inquiètent les autres et les poussent à s'armer", 4),
    ("la sécurité collective", "un système où les États s'engagent à réagir ensemble contre l'agresseur de l'un d'eux", 3),
    ("la dissuasion", "la menace de représailles destinée à décourager une agression", 2),
    ("l'interdépendance", "la dépendance mutuelle des acteurs, qui augmente le coût d'un conflit", 3),
    ("l'hégémonie", "la prépondérance d'un État sur les autres dans le système international", 3),
    ("la diplomatie", "l'ensemble des moyens pacifiques par lesquels un État conduit ses relations extérieures", 1),
    ("le multilatéralisme", "la conduite coordonnée des relations entre trois États ou plus selon des principes communs", 4),
    ("la géopolitique", "l'étude des rapports entre l'espace géographique et les rivalités de pouvoir", 3),
    ("l'acteur transnational", "un acteur non étatique, comme une entreprise multinationale, qui agit au-delà des frontières", 3),
], cat="Relations internationales : concepts", src="sup-ri", fwd="Qu'est-ce que {a} ?", rev=None)

table(RI, "ri-guerrefroide", [
    ("la guerre froide", "l'affrontement des blocs américain et soviétique après 1945, sans guerre directe généralisée", 2),
    ("l'endiguement", "la politique américaine visant à empêcher l'expansion de l'influence soviétique", 3),
    ("la détente", "une période d'apaisement relatif des tensions entre les deux blocs", 3),
    ("le plan Marshall", "l'aide économique américaine à la reconstruction de l'Europe occidentale", 3),
    ("le pacte de Varsovie", "l'alliance militaire du bloc soviétique en Europe", 3),
    ("l'OTAN", "l'alliance militaire occidentale fondée autour des États-Unis", 2),
    ("le non-alignement", "le refus d'adhérer à l'un des deux blocs de la guerre froide", 2),
    ("la course aux armements", "la compétition des deux blocs pour accroître leurs arsenaux, notamment nucléaires", 2),
    ("le rideau de fer", "l'expression désignant la frontière idéologique entre Europe de l'Ouest et Europe de l'Est", 3),
    ("l'équilibre de la terreur", "la dissuasion nucléaire mutuelle entre les deux superpuissances", 3),
], cat="Relations internationales : guerre froide", src="sup-ri", fwd="Qu'est-ce que {a} ?", rev=None)

table(RI, "ri-dates", [
    ("la signature des traités de Westphalie", "1648", 3),
    ("l'ouverture de la conférence de Berlin sur l'Afrique", "1884", 4),
    ("la signature du traité de Versailles", "1919", 2),
    ("la conférence de Bretton Woods", "1944", 4),
    ("la fondation de l'ONU", "1945", 2),
    ("la création de l'OMS", "1948", 4),
    ("la création de l'OTAN", "1949", 3),
    ("la conférence de Bandung", "1955", 4),
    ("la signature du traité de Rome instituant la CEE", "1957", 4),
    ("l'année dite de l'Afrique, marquée par de nombreuses indépendances", "1960", 3),
    ("le premier sommet des non-alignés à Belgrade", "1961", 5),
    ("la crise des missiles de Cuba", "1962", 3),
    ("la création de l'OUA à Addis-Abeba", "1963", 3),
    ("l'adoption de la Convention de Vienne sur le droit des traités", "1969", 5),
    ("la création de la CEDEAO par le traité de Lagos", "1975", 5),
    ("la chute du mur de Berlin", "1989", 2),
    ("la dissolution de l'URSS", "1991", 2),
    ("la signature du traité de Maastricht", "1992", 4),
    ("la création de l'OMC", "1995", 4),
    ("l'adoption du Statut de Rome de la CPI", "1998", 4),
    ("le lancement officiel de l'Union africaine, qui remplace l'OUA", "2002", 4),
], cat="Relations internationales : repères chronologiques", src="sup-ri", fwd="En quelle année date {a} ?", rev=None,
      expl="{A} : {b}.")

table(RI, "ri-decol", [
    ("le droit des peuples à disposer d'eux-mêmes", "le droit de choisir librement leur statut politique et de poursuivre leur développement", 2),
    ("le néocolonialisme", "la persistance d'une domination économique ou politique après l'indépendance formelle", 3),
    ("la négritude", "un mouvement littéraire et culturel d'affirmation de l'identité noire", 3),
    ("le panafricanisme", "un mouvement qui affirme la solidarité et l'unité des peuples africains et de la diaspora", 2),
    ("l'apartheid", "un régime de ségrégation raciale institutionnalisée en Afrique du Sud", 2),
    ("le mandat de la SDN", "un système de gestion de territoires de puissances vaincues sous contrôle de la SDN", 4),
    ("la tutelle des Nations unies", "le régime qui a succédé aux mandats pour certains territoires non autonomes", 4),
    ("le protectorat", "un statut où un État garde une existence internationale limitée sous la protection d'un autre", 4),
    ("l'uti possidetis", "le principe selon lequel les frontières coloniales deviennent celles des nouveaux États", 4),
], cat="Relations internationales : décolonisation et panafricanisme", src="sup-ri", fwd="Qu'est-ce que {a} ?", rev="Quelle notion désigne {b} ?")

table(RI, "ri-personnes", [
    ("Kwame Nkrumah", "premier chef du Ghana indépendant et partisan d'un gouvernement continental africain", 3),
    ("W. E. B. Du Bois", "intellectuel afro-américain lié aux congrès panafricains", 4),
    ("Marcus Garvey", "militant jamaïcain du mouvement de retour en Afrique", 4),
    ("Léopold Sédar Senghor", "poète et premier président du Sénégal indépendant", 3),
    ("Aimé Césaire", "poète martiniquais, auteur du Cahier d'un retour au pays natal", 4),
    ("Julius Nyerere", "premier président de la Tanzanie, défenseur de l'ujamaa", 4),
    ("Patrice Lumumba", "premier chef de gouvernement du Congo indépendant", 3),
    ("Ahmed Sékou Touré", "premier président de la Guinée indépendante après le « non » de 1958", 4),
    ("Gamal Abdel Nasser", "dirigeant égyptien qui nationalise le canal de Suez", 4),
    ("Josip Broz Tito", "dirigeant yougoslave, cofondateur du mouvement des non-alignés", 4),
    ("Ruben Um Nyobè", "dirigeant nationaliste camerounais, secrétaire général de l'UPC", 3),
    ("Ahmadou Ahidjo", "premier président du Cameroun indépendant", 2),
], cat="Relations internationales : personnalités de la décolonisation", src="sup-ri", fwd="Qui était {a} ?", rev="De quelle personnalité s'agit-il : {b} ?",
      expl="{A} : {b}.")

classify(RI, "ri-acteurs", {
    "un État souverain": ["le Cameroun", "le Brésil", "le Japon"],
    "une organisation intergouvernementale à vocation universelle": ["l'ONU", "l'OMS", "l'UNESCO", "l'OMC", "le FMI", "la FAO", "l'OIT"],
    "une organisation intergouvernementale régionale africaine": ["l'Union africaine", "la CEMAC", "la CEEAC", "la CEDEAO", "la SADC", "l'IGAD"],
    "une organisation non gouvernementale": ["Amnesty International", "Médecins sans frontières", "Greenpeace", "Human Rights Watch", "Oxfam", "Transparency International"],
}, cat="Relations internationales : acteurs", src="sup-ri", fwd="Quel type d'acteur est {item} ?", rev="Lequel de ces acteurs est {group} ?", diff=2,
    expl="{item} est {group}.", diffs={"la SADC": 3, "l'IGAD": 4, "la FAO": 3, "l'OIT": 3, "Transparency International": 3})

classify(RI, "ri-onu-systeme", {
    "un organe principal de l'ONU": ["l'Assemblée générale", "le Conseil de sécurité", "le Conseil économique et social", "le Secrétariat", "la Cour internationale de justice", "le Conseil de tutelle"],
    "une institution spécialisée du système des Nations unies": ["l'OMS", "l'UNESCO", "la FAO", "l'OIT", "le FMI", "la Banque mondiale", "l'Organisation de l'aviation civile internationale", "l'Union postale universelle"],
    "un programme ou fonds de l'ONU": ["le PNUD", "l'UNICEF", "le PNUE", "le Fonds des Nations unies pour la population"],
    "une organisation extérieure au système onusien": ["l'OTAN", "l'Union africaine", "la CEMAC", "le Commonwealth", "l'Union européenne", "la CEDEAO"],
}, cat="Organisations internationales : système des Nations unies", src="sup-oi", fwd="Dans quelle catégorie classe-t-on {item} ?", rev="Lequel de ces éléments est {group} ?", diff=3,
    expl="{item} est {group}.", diffs={"le Conseil de tutelle": 4, "le FMI": 4, "la Banque mondiale": 4, "le PNUE": 4, "le Fonds des Nations unies pour la population": 5,
                                     "l'Organisation de l'aviation civile internationale": 5, "l'Union postale universelle": 5})

mcq(RI, "ri-mcq", [
    ("Pour le réalisme classique, quel est le moteur principal du comportement des États ?",
     "La recherche de la puissance et de l'intérêt national", ["La solidarité entre les peuples", "L'application spontanée du droit international", "L'identité culturelle partagée"],
     "Les États sont d'abord guidés par leurs intérêts dans un système sans autorité supérieure.", 2),
    ("Quel apport Kenneth Waltz fait-il avec le néoréalisme ?",
     "Il explique le comportement des États par la structure anarchique du système, non la nature humaine",
     ["Il réfute l'existence de l'anarchie internationale", "Il fait de la nature humaine la cause unique de la guerre", "Il affirme que seules les normes forment les intérêts"],
     "Waltz déplace l'explication de la nature humaine vers la structure du système.", 5),
    ("Quel auteur de Politics Among Nations est associé au réalisme classique ?",
     "Hans Morgenthau", ["Alexander Wendt", "Robert Keohane", "Emmanuel Kant"], "Morgenthau a systématisé le réalisme classique.", 4),
    ("Qui est associé à la formule « l'anarchie est ce que les États en font » ?",
     "Alexander Wendt", ["Kenneth Waltz", "Joseph Nye", "Raymond Aron"], "Wendt illustre l'approche constructiviste.", 5),
    ("Quel courant s'appuie sur la notion d'interdépendance complexe de Keohane et Nye ?",
     "Le libéralisme (néolibéralisme institutionnel)", ["Le réalisme classique", "Le constructivisme", "L'école anglaise"],
     "Ils insistent sur la multiplicité des liens et le rôle des institutions.", 4),
    ("À qui doit-on la notion de soft power ?",
     "Joseph Nye", ["Henry Kissinger", "Kenneth Waltz", "Samuel Huntington"], "Nye l'oppose au hard power.", 3),
    ("Quelle œuvre de Kant propose un projet de paix fondé sur une fédération d'États libres ?",
     "Projet de paix perpétuelle", ["Critique de la raison pure", "Le Léviathan", "Du contrat social"], "Kant y expose les conditions d'une paix durable.", 4),
    ("Que soutient la thèse de la paix démocratique ?",
     "Les démocraties se font rarement la guerre entre elles", ["Les démocraties ne font jamais la guerre", "Seules les monarchies font la guerre", "Les démocraties s'allient toujours"],
     "C'est une régularité empirique discutée, non une loi absolue.", 4),
    ("Qui est souvent considéré comme père du droit international moderne pour son ouvrage de 1625 ?",
     "Hugo Grotius", ["Jean Bodin", "Montesquieu", "Nicolas Machiavel"], "Il a écrit De jure belli ac pacis.", 3),
    ("Quel historien grec, auteur de La Guerre du Péloponnèse, est cité comme précurseur du réalisme ?",
     "Thucydide", ["Platon", "Aristote", "Cicéron"], "Il y analyse le rôle de la puissance et de la peur.", 4),
    ("Que symbolise la paix de Westphalie dans la pensée des relations internationales ?",
     "L'émergence d'un système d'États souverains", ["La naissance de l'ONU", "La fin de la guerre froide", "La création d'un gouvernement mondial"],
     "On la présente souvent comme l'origine de la souveraineté étatique moderne.", 3),
    ("Qu'implique le principe d'égalité souveraine des États ?",
     "Une même capacité juridique pour tous, quelle que soit leur puissance",
     ["Un même poids pour tous dans le Conseil de sécurité", "Une même puissance militaire pour tous", "Une même richesse pour tous"],
     "L'égalité est juridique, non matérielle.", 3),
    ("Que signifie la souveraineté externe d'un État ?",
     "Son indépendance à l'égard de toute autorité extérieure supérieure", ["Son pouvoir de commander à ses citoyens", "Sa capacité à conquérir ses voisins", "Son appartenance obligatoire à une alliance"],
     "La souveraineté interne concerne le pouvoir sur le territoire.", 3),
    ("Quelle attitude illustre une politique d'équilibre des puissances ?",
     "S'allier pour contrebalancer l'État le plus puissant", ["Se rallier systématiquement à l'État le plus puissant", "Renoncer à toute armée", "Refuser toute alliance par principe"],
     "L'équilibre cherche à empêcher une domination.", 4),
    ("Comment appelle-t-on le fait de se rallier à l'État le plus puissant plutôt que de s'y opposer ?",
     "Le bandwagoning", ["Le balancing", "L'endiguement", "La neutralité"], "Le balancing est l'attitude inverse.", 5),
    ("Quelle différence distingue la sécurité collective d'une alliance militaire classique ?",
     "La sécurité collective vise tout agresseur du système, l'alliance une menace désignée",
     ["La sécurité collective vise un seul ennemi désigné, l'alliance tout agresseur", "Elles sont identiques", "L'alliance est universelle, la sécurité collective toujours bilatérale"],
     "Le Conseil de sécurité relève de la sécurité collective, l'OTAN de l'alliance.", 5),
    ("Quelle organisation de maintien de la paix par la sécurité collective a précédé l'ONU ?",
     "La Société des Nations", ["L'OUA", "L'OTAN", "Le Commonwealth"], "La SDN fut fondée après la Première Guerre mondiale.", 2),
    ("Quel président américain est associé aux « quatorze points » et à l'idée de la SDN ?",
     "Woodrow Wilson", ["Franklin Roosevelt", "Harry Truman", "Dwight Eisenhower"], "Wilson incarne l'idéalisme de l'entre-deux-guerres.", 3),
    ("Quels États étaient les deux superpuissances de la guerre froide ?",
     "Les États-Unis et l'URSS", ["La France et le Royaume-Uni", "La Chine et l'Inde", "L'Allemagne et le Japon"], "Le monde était dit bipolaire.", 1),
    ("Quel est le principe central du mouvement des non-alignés ?",
     "Ne pas s'inscrire dans l'un des blocs militaires de la guerre froide", ["S'allier à l'URSS contre les États-Unis", "Défendre l'unité politique de l'Europe", "Créer une monnaie commune mondiale"],
     "Il s'agissait de préserver l'indépendance de décision.", 2),
    ("Quel principe de la Charte des Nations unies a soutenu les revendications d'indépendance ?",
     "Le droit des peuples à disposer d'eux-mêmes", ["Le droit de veto des membres permanents", "Le principe de non-rétroactivité", "La clause de la nation la plus favorisée"],
     "L'autodétermination est un principe de la Charte.", 2),
    ("Quelle déclaration de l'Assemblée générale de 1960 a proclamé la nécessité de mettre fin rapidement au colonialisme ?",
     "La Déclaration sur l'octroi de l'indépendance aux pays et aux peuples coloniaux",
     ["La Déclaration universelle des droits de l'homme", "La Déclaration de Rio", "Le Pacte de la Société des Nations"],
     "Elle est un texte majeur de la décolonisation.", 4),
    ("Quel statut international avait le Cameroun sous administration française et britannique après 1945 ?",
     "Le régime de tutelle des Nations unies", ["Un protectorat de l'OUA", "Un territoire fédéral des États-Unis", "Un condominium germano-britannique"],
     "La tutelle a succédé au mandat de la SDN.", 3),
    ("Comment le Cameroun, ancienne colonie allemande, a-t-il été administré après la Première Guerre mondiale ?",
     "Sous mandat de la SDN confié à la France et au Royaume-Uni", ["Sous souveraineté de la Belgique", "Comme État indépendant dès 1919", "Sous mandat confié à l'Allemagne"],
     "Le territoire fut partagé entre deux puissances mandataires.", 3),
    ("Quelle consultation a permis en 1961 aux populations du Cameroun sous administration britannique de choisir leur rattachement ?",
     "Un plébiscite", ["Un coup d'État", "Un arbitrage de la CIJ", "Une conférence nationale"],
     "Le nord a rejoint le Nigeria, le sud le Cameroun.", 3),
    ("Quelle exigence la conférence de Berlin (1884-1885) a-t-elle posée pour reconnaître la prise de possession de territoires sur les côtes africaines ?",
     "Une occupation effective", ["Le consentement écrit de tous les chefs locaux", "L'interdiction de toute présence européenne", "Une annexion sans aucune notification"],
     "Le principe d'occupation effective a encadré le partage de l'Afrique.", 5),
    ("Quel principe l'OUA a-t-elle posé au sujet des frontières héritées de la colonisation ?",
     "Leur respect, ou intangibilité", ["Leur révision systématique", "Leur suppression progressive", "Leur gestion par l'ONU"],
     "L'objectif était d'éviter des conflits territoriaux.", 3),
    ("Quelle innovation majeure l'Acte constitutif de l'Union africaine apporte-t-il par rapport à la Charte de l'OUA ?",
     "Un droit d'intervention de l'Union dans un État membre en cas de génocide ou de crimes graves",
     ["L'interdiction de toute coopération militaire", "La création immédiate d'une monnaie unique", "La suppression de toute référence aux droits de l'homme"],
     "L'UA admet l'intervention en cas de crimes de guerre, génocide et crimes contre l'humanité.", 5),
    ("Que désigne l'Agenda 2063 de l'Union africaine ?",
     "Un cadre stratégique de développement du continent à long terme", ["Un traité de désarmement nucléaire", "Une réforme du Conseil de sécurité", "Un calendrier électoral commun"],
     "Il fixe une vision à long terme pour l'Afrique.", 3),
    ("Que désigne le NEPAD ?",
     "Le Nouveau partenariat pour le développement de l'Afrique, programme associé à l'Union africaine",
     ["Une banque centrale africaine", "Une force militaire de l'ONU", "Un tribunal arbitral africain"],
     "C'est un programme de développement continental.", 4),
    ("Quel est l'objectif de la zone de libre-échange continentale africaine (ZLECAf) ?",
     "Créer un marché continental en libéralisant les échanges de biens et de services", ["Créer une armée africaine commune", "Imposer une langue unique au continent", "Supprimer toutes les monnaies nationales"],
     "Elle vise à renforcer le commerce intra-africain.", 3),
    ("Quel est le rapport entre la CEMAC et la CEEAC en Afrique centrale ?",
     "La CEEAC est plus large et réunit tous les États de la CEMAC avec d'autres", ["La CEEAC est un sous-ensemble de la CEMAC", "Elles réunissent exactement les mêmes États", "Elles n'ont aucun membre commun"],
     "Les six États de la CEMAC sont aussi membres de la CEEAC.", 4),
    ("Quelle banque centrale émet la monnaie commune des États de la CEMAC ?",
     "La BEAC", ["La BCEAO", "La Banque africaine de développement", "La Banque mondiale"], "La BCEAO émet la monnaie de l'UEMOA.", 3),
    ("Qu'est-ce que le Commonwealth ?",
     "Une association volontaire d'États, pour la plupart anciens territoires de l'Empire britannique", ["Une alliance militaire occidentale", "Une organisation de pays francophones", "Une union monétaire africaine"],
     "Il rassemble des États de plusieurs continents.", 2),
    ("À quelles organisations le Cameroun appartient-il à la fois ?",
     "Au Commonwealth et à la Francophonie", ["À la Francophonie seulement", "Au Commonwealth seulement", "Ni à l'un ni à l'autre"],
     "Le Cameroun est membre des deux, en raison de son histoire bilingue.", 2),
    ("Qu'est-ce que le droit de tirage spécial (DTS) du FMI ?",
     "Un actif de réserve international dont la valeur repose sur un panier de monnaies", ["Une pièce de monnaie physique", "Un titre de la Banque mondiale", "Une taxe prélevée sur les États"],
     "Le DTS complète les réserves officielles des membres.", 4),
    ("Quelle est la mission de l'IDA, entité du groupe de la Banque mondiale ?",
     "Aider les pays les plus pauvres par des prêts à conditions très favorables et des dons", ["Garantir les dépôts des banques commerciales", "Financer le budget de l'ONU", "Arbitrer les différends commerciaux"],
     "L'Association internationale de développement cible les pays à faible revenu.", 5),
    ("Quelle phrase distingue le mieux le FMI de la Banque mondiale ?",
     "Le FMI traite de stabilité macroéconomique et monétaire, la Banque mondiale de développement",
     ["Le FMI finance surtout des écoles, la Banque mondiale surveille les taux de change", "Le FMI est une organisation régionale africaine", "Ce sont deux juridictions internationales"],
     "Leurs missions sont complémentaires.", 3),
    ("Que prévoit la clause de la nation la plus favorisée dans le droit de l'OMC ?",
     "Tout avantage commercial accordé à un membre doit être étendu aux autres membres", ["Un État doit favoriser ses propres produits", "Un État doit interdire les importations", "Un État peut choisir librement ses partenaires privilégiés"],
     "Elle interdit la discrimination entre partenaires commerciaux.", 4),
    ("Que signifie le principe du traitement national à l'OMC ?",
     "Les produits importés, une fois entrés, ne sont pas traités moins bien que les produits nationaux",
     ["Les produits nationaux doivent être plus taxés que les importés", "Les importations sont toujours interdites", "Chaque État doit adopter le même tarif douanier"],
     "Il concerne le traitement interne, après le passage de la frontière.", 5),
    ("Quel accord a précédé l'OMC ?", "Le GATT", ["Le plan Marshall", "Le traité de Rome", "L'Acte unique"], "Le GATT date de 1947.", 3),
    ("Quel organe de l'OMC traite des litiges commerciaux entre membres ?",
     "L'Organe de règlement des différends", ["Le Conseil de sécurité", "La Cour pénale internationale", "Le Conseil de tutelle"], "C'est le mécanisme de règlement des litiges de l'OMC.", 3),
    ("Quel organisme de l'ONU établit la Liste du patrimoine mondial ?",
     "L'UNESCO", ["L'OMS", "La FAO", "Le HCR"], "La Convention du patrimoine mondial relève de l'UNESCO.", 2),
    ("Dans quelle ville la Charte des Nations unies a-t-elle été signée ?",
     "San Francisco", ["New York", "Genève", "Yalta"], "La conférence de San Francisco a adopté la Charte.", 3),
    ("Comment un nouvel État est-il admis à l'ONU ?",
     "Par décision de l'Assemblée générale sur recommandation du Conseil de sécurité", ["Par décision de la CIJ", "Par le Secrétaire général seul", "Par vote du Conseil de tutelle"],
     "Le Conseil de sécurité recommande, l'Assemblée décide.", 4),
    ("Combien de votes affirmatifs faut-il au moins pour une décision de fond du Conseil de sécurité, sans veto d'un membre permanent ?",
     "Neuf", ["Cinq", "Sept", "Quinze"], "Il faut neuf voix, dont aucune voix négative d'un membre permanent.", 5),
    ("Que se passe-t-il lorsqu'un membre permanent du Conseil de sécurité s'abstient lors d'un vote de fond ?",
     "La décision peut être adoptée si elle recueille assez de votes favorables", ["La décision est automatiquement bloquée", "Le vote est annulé", "La décision passe à l'Assemblée générale sans vote"],
     "L'abstention n'est pas un veto dans la pratique reconnue.", 5),
    ("Quelle est en principe la portée des résolutions de l'Assemblée générale de l'ONU ?",
     "Ce sont des recommandations, sauf dans certaines matières internes", ["Elles lient tous les États comme des lois", "Elles remplacent les traités", "Elles s'imposent aux juges nationaux"],
     "Seul le Conseil de sécurité peut prendre des décisions obligatoires pour les États membres.", 4),
    ("À quelle majorité l'Assemblée générale tranche-t-elle les questions importantes ?",
     "Aux deux tiers des membres présents et votants", ["À l'unanimité", "À la majorité simple de tous les membres", "À la majorité des membres permanents"],
     "Les autres questions se décident à la majorité simple des présents et votants.", 5),
    ("Qui nomme le Secrétaire général de l'ONU ?",
     "L'Assemblée générale, sur recommandation du Conseil de sécurité", ["La Cour internationale de justice", "Le Conseil de tutelle", "Les membres permanents seuls"], "Il est le plus haut fonctionnaire de l'Organisation.", 4),
    ("Que permet le chapitre VII de la Charte de l'ONU ?",
     "Au Conseil de sécurité de décider de mesures coercitives face à une menace contre la paix", ["Aux États de modifier la Charte", "À la CIJ de juger les individus", "Au Secrétaire général de dissoudre l'Assemblée"],
     "Sanctions et usage de la force sont prévus par ce chapitre.", 4),
    ("Que prévoit le chapitre VI de la Charte de l'ONU ?",
     "Le règlement pacifique des différends", ["Les sanctions militaires obligatoires", "L'admission des nouveaux membres", "Le régime des territoires sous tutelle"],
     "Il vise négociations, enquêtes, médiation et autres moyens pacifiques.", 4),
    ("Que prévoit le droit de légitime défense reconnu par la Charte ?",
     "Un droit naturel de répondre à une agression armée, en attendant le Conseil de sécurité",
     ["Une interdiction absolue de toute riposte", "Un droit de représailles après toute agression passée", "Une autorisation préalable obligatoire de la CIJ"],
     "C'est une exception à l'interdiction de la force.", 4),
    ("Quel est l'un des principes traditionnels des opérations de maintien de la paix de l'ONU ?",
     "Le consentement des parties", ["L'usage offensif de la force", "Le choix libre du camp à soutenir", "L'absence de mandat du Conseil de sécurité"],
     "Les autres principes sont l'impartialité et le non-recours à la force sauf légitime défense et défense du mandat.", 4),
    ("Que protège le principe de domaine réservé (compétence nationale) dans la Charte ?",
     "Les affaires relevant de la compétence interne des États, contre l'intervention de l'ONU", ["Les biens des Nations unies", "Les frontières maritimes", "Les droits des organisations non gouvernementales"],
     "Il admet l'exception des mesures coercitives du chapitre VII.", 4),
    ("Quelle mesure non militaire le Conseil de sécurité peut-il décider ?",
     "Des sanctions économiques comme un embargo", ["La dissolution du Parlement d'un État", "La nomination d'un chef d'État", "L'abrogation d'une loi nationale"],
     "L'article sur les mesures non militaires les mentionne.", 3),
    ("Qu'est-ce que la responsabilité de protéger ?",
     "L'idée que l'État doit protéger sa population des atrocités, sinon la communauté internationale agit",
     ["Le droit de tout État d'envahir son voisin", "Le devoir des citoyens de protéger l'État", "Le principe de neutralité permanente"],
     "Notion adoptée par l'ONU en 2005.", 5),
], cat="Relations internationales et organisations : cas et distinctions", src="sup-ri")

# =====================================================================================================================
# DROIT INTERNATIONAL PUBLIC (l3-droit)
# =====================================================================================================================
table(RI, "dip-sources", [
    ("un traité", "un accord écrit conclu entre sujets de droit international et régi par ce droit", 2),
    ("la coutume internationale", "une pratique générale acceptée comme étant le droit", 3),
    ("les principes généraux de droit", "des principes communs aux grands systèmes juridiques, reconnus par les nations", 4),
    ("l'opinio juris", "la conviction qu'une pratique est exigée par le droit", 4),
    ("le jus cogens", "des normes impératives auxquelles aucune dérogation par traité n'est admise", 4),
    ("un acte unilatéral", "une manifestation de volonté d'un seul sujet produisant des effets juridiques", 4),
    ("les obligations erga omnes", "des obligations dues à l'ensemble de la communauté internationale", 5),
    ("le droit souple (soft law)", "des instruments non contraignants mais influents sur le comportement des États", 4),
    ("la jurisprudence internationale", "les décisions des juridictions, moyen auxiliaire de détermination des règles", 4),
    ("la doctrine des publicistes", "les travaux des juristes les plus qualifiés, moyen auxiliaire de détermination des règles", 4),
], cat="Droit international public : sources", src="sup-dip", fwd="Qu'est-ce que {a} en droit international ?", rev="Quelle notion désigne {b} ?")

table(RI, "dip-traites", [
    ("la signature", "un acte qui, pour un traité soumis à ratification, ne lie pas encore définitivement l'État", 3),
    ("la ratification", "l'acte par lequel un État exprime au plan international son consentement à être lié", 3),
    ("l'adhésion", "l'acte par lequel un État devient partie à un traité qu'il n'a pas signé", 3),
    ("la réserve", "une déclaration unilatérale qui exclut ou modifie l'effet de dispositions du traité", 4),
    ("l'entrée en vigueur", "le moment à partir duquel le traité produit ses effets obligatoires", 3),
    ("la dénonciation", "la notification par laquelle une partie manifeste son retrait d'un traité", 4),
    ("le dépositaire", "l'entité chargée de conserver le texte du traité et de recevoir les notifications", 4),
    ("la clause rebus sic stantibus", "l'idée très encadrée qu'un changement fondamental de circonstances peut mettre fin à un traité", 5),
    ("l'accord en forme simplifiée", "un accord qui lie l'État dès sa signature, sans ratification", 5),
], cat="Droit international public : droit des traités", src="sup-dip", fwd="Qu'est-ce que {a} ?", rev="Quelle notion désigne {b} ?")

table(RI, "dip-immunites", [
    ("l'inviolabilité des locaux diplomatiques", "l'interdiction pour l'État d'accueil d'y pénétrer sans le consentement du chef de mission", 3),
    ("la déclaration de persona non grata", "le refus par l'État d'accueil d'un diplomate, sans obligation de motiver", 3),
    ("l'agrément", "l'accord préalable de l'État d'accueil à la nomination d'un chef de mission", 4),
    ("l'exequatur", "l'autorisation donnée par l'État d'accueil à un consul d'exercer ses fonctions", 5),
    ("la valise diplomatique", "le courrier officiel qui ne peut être ni ouvert ni retenu", 3),
    ("l'immunité de juridiction", "l'impossibilité de poursuivre un État ou un agent devant les tribunaux d'un autre État", 3),
    ("la levée d'immunité", "la renonciation expresse de l'État d'envoi à l'immunité de son agent", 4),
    ("l'immunité fonctionnelle", "la protection attachée aux actes accomplis dans l'exercice officiel des fonctions", 5),
    ("l'immunité personnelle", "la protection attachée à la fonction de certains hauts dirigeants tant qu'ils l'exercent", 5),
    ("le consul", "l'agent chargé surtout de protéger les ressortissants de l'État d'envoi et des formalités", 3),
    ("l'ambassadeur", "le chef de la mission diplomatique représentant l'État d'envoi auprès de l'État d'accueil", 2),
], cat="Droit international public : relations diplomatiques et immunités", src="sup-dip", fwd="Qu'est-ce que {a} ?", rev="Quelle notion désigne {b} ?")

table(RI, "dip-differends", [
    ("la négociation", "la discussion directe entre les parties au différend", 1),
    ("les bons offices", "l'intervention d'un tiers qui facilite le contact sans proposer de solution", 3),
    ("la médiation", "l'intervention d'un tiers qui propose lui-même des bases de règlement non obligatoires", 3),
    ("l'enquête internationale", "l'établissement impartial des faits controversés par un organe indépendant", 4),
    ("la conciliation", "l'examen du différend par une commission qui propose un règlement sans force obligatoire", 4),
    ("l'arbitrage", "le règlement par des juges choisis par les parties, qui rendent une sentence obligatoire", 3),
    ("le règlement judiciaire", "le règlement par une juridiction permanente dont l'arrêt est obligatoire", 3),
    ("le compromis d'arbitrage", "l'accord conclu après la naissance du différend pour le soumettre à l'arbitrage", 4),
    ("la clause compromissoire", "la clause d'un traité soumettant à l'arbitrage les différends futurs", 4),
    ("la déclaration facultative de juridiction obligatoire", "la déclaration reconnaissant la compétence de la CIJ envers tout État qui l'accepte aussi", 5),
], cat="Droit international public : règlement pacifique des différends", src="sup-dip", fwd="Qu'est-ce que {a} ?", rev="Quelle notion désigne {b} ?")

table(RI, "dip-juridictions", [
    ("la Cour internationale de justice", "l'organe judiciaire principal de l'ONU, qui statue sur des différends entre États", 2),
    ("la Cour pénale internationale", "une juridiction permanente qui juge des individus pour les crimes les plus graves", 2),
    ("la Cour permanente d'arbitrage", "une institution de La Haye qui facilite l'arbitrage et d'autres modes de règlement", 5),
    ("le Tribunal international du droit de la mer", "la juridiction créée par la Convention de Montego Bay pour les litiges maritimes", 5),
    ("la Cour africaine des droits de l'homme et des peuples", "la juridiction régionale africaine chargée d'assurer la protection des droits de l'homme", 4),
    ("la Cour européenne des droits de l'homme", "la juridiction du Conseil de l'Europe qui contrôle le respect de la Convention européenne", 4),
    ("l'Organe de règlement des différends", "l'instance de l'OMC chargée de traiter les litiges commerciaux entre membres", 4),
], cat="Droit international public : juridictions et organes", src="sup-dip", fwd="Quel est le rôle de {a} ?", rev="Quelle institution correspond à cette description : {b} ?",
      expl="{A} : {b}.")

table(RI, "dip-reparation", [
    ("la restitution", "la remise en l'état antérieur à l'acte illicite, lorsque c'est possible", 4),
    ("l'indemnisation", "le paiement d'une somme couvrant le dommage non réparé par la restitution", 4),
    ("la satisfaction", "la reconnaissance de la violation, des excuses ou une autre forme symbolique de réparation", 5),
    ("la cessation", "l'obligation de mettre fin à un comportement illicite qui se poursuit", 5),
    ("les contre-mesures", "des mesures non armées d'un État lésé pour obtenir que l'État fautif respecte ses obligations", 5),
], cat="Droit international public : responsabilité internationale", src="sup-dip", fwd="Qu'est-ce que {a} en droit de la responsabilité internationale ?", rev="Quelle notion désigne {b} ?",
      min_rows=5)

table(RI, "oi-sigles", [
    ("la CEMAC", "la Communauté économique et monétaire de l'Afrique centrale", 1),
    ("la CEEAC", "la Communauté économique des États de l'Afrique centrale", 2),
    ("la CEDEAO", "la Communauté économique des États de l'Afrique de l'Ouest", 2),
    ("l'UEMOA", "l'Union économique et monétaire ouest-africaine", 3),
    ("la SADC", "la Communauté de développement de l'Afrique australe", 3),
    ("l'IGAD", "l'Autorité intergouvernementale pour le développement", 5),
    ("le COMESA", "le Marché commun de l'Afrique orientale et australe", 4),
    ("l'OUA", "l'Organisation de l'unité africaine", 1),
    ("l'OMC", "l'Organisation mondiale du commerce", 1),
    ("le FMI", "le Fonds monétaire international", 1),
    ("l'OMS", "l'Organisation mondiale de la santé", 1),
    ("l'UNESCO", "l'Organisation des Nations unies pour l'éducation, la science et la culture", 2),
    ("l'OTAN", "l'Organisation du traité de l'Atlantique Nord", 1),
    ("l'OIF", "l'Organisation internationale de la Francophonie", 2),
    ("la CNUCED", "la Conférence des Nations unies sur le commerce et le développement", 4),
    ("le HCR", "le Haut-Commissariat des Nations unies pour les réfugiés", 3),
    ("l'OIT", "l'Organisation internationale du travail", 2),
    ("la FAO", "l'Organisation des Nations unies pour l'alimentation et l'agriculture", 2),
    ("le PNUD", "le Programme des Nations unies pour le développement", 2),
    ("la CIJ", "la Cour internationale de justice", 1),
    ("la CPI", "la Cour pénale internationale", 1),
], cat="Organisations internationales : sigles", src="sup-oi", fwd="Que signifie {a} ?", rev=None, expl="{A} désigne {b}.")

table(RI, "oi-roles", [
    ("le FMI", "il surveille le système monétaire international et aide les États en déséquilibre de paiements", 3),
    ("la Banque mondiale", "elle finance des projets et programmes de développement et de réduction de la pauvreté", 2),
    ("l'OMC", "elle gère les règles du commerce entre ses membres et règle leurs différends commerciaux", 3),
    ("l'UNESCO", "elle agit dans l'éducation, la science et la culture, dont la protection du patrimoine mondial", 2),
    ("l'OMS", "elle coordonne l'action sanitaire internationale au sein du système des Nations unies", 2),
    ("l'OIT", "elle élabore des normes internationales du travail dans un cadre tripartite", 4),
    ("la FAO", "elle lutte contre la faim et améliore l'agriculture et l'alimentation", 2),
    ("le HCR", "il protège les réfugiés et cherche des solutions durables pour eux", 2),
    ("le PNUD", "il soutient le développement humain et la lutte contre la pauvreté dans les pays partenaires", 3),
    ("l'OIF", "elle rassemble des États et gouvernements qui ont en commun l'usage du français", 2),
    ("le Commonwealth", "il rassemble des États, pour la plupart d'anciens territoires de l'Empire britannique", 2),
], cat="Organisations internationales : rôles", src="sup-oi", fwd="Quel est le rôle général de {a} ?", rev="Quelle organisation correspond à cette description : {b} ?",
      expl="{A} : {b}.")

table(RI, "oi-onu-organes", [
    ("l'Assemblée générale", "l'organe plénier où tous les États membres sont représentés, chacun avec une voix", 2),
    ("le Conseil de sécurité", "l'organe principalement responsable du maintien de la paix et de la sécurité internationales", 2),
    ("le Conseil économique et social", "l'organe qui coordonne l'action économique et sociale des Nations unies", 3),
    ("le Conseil de tutelle", "l'organe chargé de superviser les territoires sous tutelle, aujourd'hui sans activité", 4),
    ("la Cour internationale de justice", "l'organe judiciaire principal de l'ONU", 2),
    ("le Secrétariat", "l'organe administratif dirigé par le Secrétaire général", 2),
], cat="Organisations internationales : organes de l'ONU", src="sup-oi", fwd="Quel est le rôle de {a} ?", rev="Quel organe de l'ONU correspond à cette description : {b} ?",
      expl="{A} : {b}.")

table(RI, "oi-ua-organes", [
    ("la Conférence de l'Union", "l'organe suprême, composé des chefs d'État et de gouvernement", 3),
    ("le Conseil exécutif", "l'organe de ministres qui prépare et suit les décisions de la Conférence", 4),
    ("la Commission de l'Union africaine", "le secrétariat de l'Union, qui administre et exécute ses décisions", 3),
    ("le Conseil de paix et de sécurité", "l'organe permanent de prévention, de gestion et de règlement des conflits", 3),
    ("le Parlement panafricain", "l'organe de représentation des peuples africains, aux pouvoirs surtout consultatifs", 4),
    ("le Comité des représentants permanents", "l'organe d'ambassadeurs qui prépare les travaux du Conseil exécutif", 5),
], cat="Organisations internationales : organes de l'Union africaine", src="sup-oi", fwd="Quel est le rôle de {a} ?", rev="Quel organe de l'UA correspond à cette description : {b} ?",
      expl="{A} : {b}.")

table(RI, "oi-sieges", [
    ("l'Union africaine", "Addis-Abeba", 2),
    ("le FMI", "Washington", 2),
    ("l'UNESCO", "Paris", 2),
    ("l'OMC", "Genève", 2),
    ("la Cour pénale internationale", "La Haye", 2),
    ("la CEMAC", "Bangui", 4),
    ("la CEEAC", "Libreville", 4),
    ("la CEDEAO", "Abuja", 4),
    ("le Secrétariat du Commonwealth", "Londres", 3),
], cat="Organisations internationales : sièges", src="sup-oi", fwd="Où se situe le siège de {a} ?", rev="Quelle organisation a son siège à {b} ?",
      expl="Siège de {a} : {b}.", region="AF")

classify(RI, "oi-membres", {
    "la CEMAC": ["le Cameroun", "le Gabon", "le Tchad", "le Congo", "la République centrafricaine", "la Guinée équatoriale"],
    "la CEDEAO": ["le Sénégal", "la Côte d'Ivoire", "le Ghana", "le Nigeria", "le Togo", "le Bénin"],
    "la SADC": ["le Botswana", "la Namibie", "le Zimbabwe", "la Zambie", "le Malawi", "le Mozambique", "l'Afrique du Sud"],
    "la Communauté d'Afrique de l'Est (EAC)": ["le Kenya", "l'Ouganda", "le Rwanda", "le Burundi"],
}, cat="Organisations internationales : intégration africaine", src="sup-oi", region="AF",
    fwd="Dans quelle organisation régionale africaine se trouve {item} ?", rev="Lequel de ces États est membre de {group} ?", diff=3,
    expl="{item} est membre de {group}.", diffs={"le Rwanda": 4, "le Burundi": 4, "le Malawi": 4, "le Togo": 3, "la République centrafricaine": 3})

mcq(RI, "dip-mcq", [
    ("Selon le Statut de la CIJ, quel est le rôle de la doctrine des publicistes ?",
     "Un moyen auxiliaire de détermination des règles de droit", ["Une source principale obligatoire", "Une source supérieure aux traités", "Aucun rôle"],
     "Jurisprudence et doctrine sont des moyens auxiliaires.", 4),
    ("Quels sont les deux éléments de la coutume internationale ?",
     "Une pratique générale et la conviction qu'elle est obligatoire", ["Un traité signé et une ratification", "Une décision de justice et une opinion doctrinale", "Une déclaration de l'ONU et un vote à l'unanimité"],
     "Pratique (élément matériel) et opinio juris (élément psychologique).", 3),
    ("Qu'est-ce qu'un objecteur persistant en droit international ?",
     "Un État qui s'oppose constamment à une règle coutumière en formation et peut ne pas se voir lié",
     ["Un État qui refuse de payer sa contribution à l'ONU", "Un État qui contourne toutes les sanctions", "Un juge qui exprime une opinion dissidente"],
     "L'opposition doit être constante et exprimée dès la formation de la règle.", 5),
    ("Quelle est la conséquence d'un traité contraire à une norme de jus cogens ?",
     "Il est nul", ["Il est valide mais révisable", "Il est simplement suspendu", "Il ne s'applique qu'entre deux États"],
     "Le jus cogens prime sur les stipulations contraires.", 4),
    ("Que prévoit le principe de l'effet relatif des traités ?",
     "Un traité ne crée en principe ni obligations ni droits pour les États tiers sans accord", ["Un traité s'impose à tous les États dès son adoption", "Un traité ne lie jamais ses propres parties", "Un traité n'a d'effet qu'entre nationaux"],
     "Pacta tertiis nec nocent nec prosunt.", 4),
    ("Un État peut-il invoquer son droit interne pour justifier l'inexécution d'un traité ?",
     "Non, en principe", ["Oui, toujours", "Oui, si la loi est postérieure au traité", "Oui, après avis de la CIJ"],
     "Le droit interne n'est pas une excuse, sauf cas très limités de vice du consentement.", 4),
    ("Quel effet a une réserve valide à un traité ?",
     "Elle exclut ou modifie pour son auteur l'effet de certaines dispositions", ["Elle annule le traité pour tous", "Elle dispense l'État de tout le traité", "Elle transforme le traité en coutume"],
     "La réserve rend l'engagement partiel pour l'État qui la formule.", 3),
    ("Quel texte codifie le droit des traités entre États ?",
     "La Convention de Vienne de 1969", ["La Convention de Genève de 1949", "La Convention de Montego Bay", "Le Statut de Rome"], "Elle fixe les règles de conclusion, d'interprétation et d'extinction.", 3),
    ("Quelle convention de Vienne codifie les relations diplomatiques ?",
     "La Convention de 1961", ["La Convention de 1969", "La Convention de 1978", "La Convention de 1986"], "La Convention de 1963 traite des relations consulaires.", 4),
    ("Quelle convention de Vienne porte sur les relations consulaires ?",
     "La Convention de 1963", ["La Convention de 1961", "La Convention de 1969", "La Convention de 1978"], "La Convention de 1961 concerne les relations diplomatiques.", 5),
    ("Quelle convention de 1982 fixe le régime juridique des mers et des océans ?",
     "La Convention de Montego Bay", ["La Convention de Vienne", "La Convention de Genève", "La Convention de Rome"], "Elle traite aussi de la zone économique exclusive.", 3),
    ("Quelle est la largeur maximale de la mer territoriale selon la Convention de Montego Bay ?",
     "12 milles marins", ["3 milles marins", "50 milles marins", "200 milles marins"], "La zone économique exclusive peut aller jusqu'à 200 milles.", 5),
    ("Quel principe gouverne la haute mer ?",
     "La liberté de la haute mer, qui n'est soumise à la souveraineté d'aucun État", ["La souveraineté de l'État riverain le plus proche", "La propriété de l'ONU", "Le partage entre tous les États côtiers"], "La haute mer est ouverte à tous.", 3),
    ("Dans la zone économique exclusive, quels droits l'État côtier a-t-il ?",
     "Des droits souverains sur l'exploitation des ressources, sans souveraineté pleine sur la zone", ["Une souveraineté identique à celle sur son territoire terrestre", "Aucun droit sur les ressources", "Le droit d'interdire toute navigation"],
     "La navigation reste libre dans la ZEE.", 5),
    ("Quels éléments un fait internationalement illicite suppose-t-il ?",
     "Un comportement attribuable à l'État qui viole une obligation internationale",
     ["Un dommage matériel prouvé et une faute intentionnelle du chef de l'État", "Une condamnation préalable par le Conseil de sécurité", "Un traité signé par plus de dix États"],
     "Le dommage n'est pas, en principe, un élément constitutif général.", 5),
    ("Quelle forme de réparation consiste à rétablir la situation antérieure à l'acte illicite ?",
     "La restitution", ["La satisfaction", "L'indemnisation", "La sanction pénale"], "Si elle est impossible, l'indemnisation prend le relais.", 4),
    ("Selon la théorie déclarative, que fait la reconnaissance d'un État ?",
     "Elle constate un État qui existe déjà du fait de ses éléments constitutifs", ["Elle crée l'État", "Elle est une condition de sa souveraineté", "Elle remplace son territoire"],
     "La théorie constitutive soutient l'inverse.", 5),
    ("Quels sont les éléments constitutifs de l'État en droit international ?",
     "Un territoire, une population et une autorité politique organisée", ["Un territoire, une armée et une monnaie propre", "Une population, une langue officielle et une religion commune", "Des frontières reconnues par tous et un siège à l'ONU"],
     "La reconnaissance par les autres États n'est pas un élément constitutif.", 3),
    ("Que dit le principe de l'uti possidetis appliqué à l'Afrique ?",
     "Les frontières héritées de la colonisation deviennent les frontières des États indépendants", ["Les frontières coloniales doivent être supprimées", "Chaque ethnie a droit à son État", "Les frontières sont fixées par l'ONU à chaque indépendance"],
     "L'OUA a consacré ce principe.", 4),
    ("Quelle juridiction a rendu en 2002 l'arrêt sur la frontière terrestre et maritime entre le Cameroun et le Nigeria ?",
     "La Cour internationale de justice", ["La Cour pénale internationale", "La Cour africaine des droits de l'homme", "Le Tribunal international du droit de la mer"],
     "La CIJ statue sur les différends entre États.", 3),
    ("Dans l'arrêt de 2002 de la CIJ entre le Cameroun et le Nigeria, à quel État la souveraineté sur la presqu'île de Bakassi a-t-elle été reconnue ?",
     "Au Cameroun", ["Au Nigeria", "À la Guinée équatoriale", "À l'ONU"],
     "La CIJ a reconnu la souveraineté du Cameroun sur Bakassi.", 4),
    ("Dans quelle affaire la CIJ a-t-elle reconnu en 1949 la personnalité juridique de l'ONU ?",
     "Réparation des dommages subis au service des Nations Unies", ["Détroit de Corfou", "Barcelona Traction", "Activités militaires au Nicaragua"],
     "L'avis consultatif a reconnu à l'ONU une personnalité objective.", 5),
    ("Que signifie le principe de spécialité pour une organisation internationale ?",
     "Elle ne dispose que des compétences que ses États membres lui ont attribuées", ["Elle dispose de toutes les compétences d'un État", "Elle ne peut conclure aucun traité", "Elle n'a aucune personnalité juridique"],
     "Les organisations agissent dans le cadre de leurs compétences d'attribution.", 4),
    ("Un diplomate commet une infraction grave dans l'État d'accueil. Que peut faire cet État ?",
     "Le déclarer persona non grata", ["L'emprisonner immédiatement", "Fouiller l'ambassade", "Saisir la valise diplomatique"],
     "L'immunité protège le diplomate mais ne l'empêche pas d'être renvoyé.", 3),
    ("Selon la CIJ (affaire du mandat d'arrêt, 2002), de quoi un ministre des Affaires étrangères en exercice bénéficie-t-il devant les tribunaux étrangers ?",
     "D'une immunité de juridiction pénale", ["D'aucune immunité", "D'une immunité limitée aux actes privés", "D'une immunité valable seulement après son départ"],
     "Cette immunité est liée à sa fonction.", 5),
    ("Quelle branche du droit international régit la conduite des hostilités et la protection des victimes de guerre ?",
     "Le droit international humanitaire", ["Le droit de la mer", "Le droit diplomatique", "Le droit des organisations internationales"],
     "Les Conventions de Genève en sont le cœur.", 4),
    ("Quelle distinction oppose jus ad bellum et jus in bello ?",
     "Le premier concerne la licéité du recours à la force, le second la conduite des hostilités",
     ["Le premier concerne les traités, le second les coutumes", "Le premier concerne les États, le second les ONG", "Le premier concerne la paix, le second les sanctions"],
     "Le DIH relève du jus in bello.", 4),
    ("Que protègent les Conventions de Genève de 1949 ?",
     "Les blessés, les malades, les prisonniers de guerre et les civils en temps de conflit armé", ["Les brevets d'invention", "Les frontières maritimes", "Les investissements étrangers"],
     "Elles forment le cœur du droit humanitaire.", 3),
    ("Quel principe du droit humanitaire impose de distinguer combattants et civils ?",
     "Le principe de distinction", ["Le principe de réciprocité", "Le principe de non-rétroactivité", "Le principe de subsidiarité"],
     "Les attaques ne doivent viser que des objectifs militaires.", 3),
    ("Lequel de ces textes est un traité contraignant plutôt qu'une simple déclaration ?",
     "Le Pacte international relatif aux droits civils et politiques", ["La Déclaration universelle des droits de l'homme", "La Déclaration de 1960 sur l'indépendance des peuples coloniaux", "La Déclaration de Rio"],
     "Le Pacte de 1966 est un traité ; la DUDH est une résolution.", 4),
    ("Que signifie le principe de non-refoulement ?",
     "L'interdiction de renvoyer une personne vers un pays où elle risque la persécution", ["L'obligation d'expulser tout étranger en situation irrégulière", "Le droit de fermer ses frontières aux marchandises", "L'obligation de livrer les criminels à tout État"],
     "Il est central en droit des réfugiés.", 3),
    ("Qu'est-ce que l'extradition ?",
     "La remise d'une personne par un État à un autre qui la réclame pour la juger ou la punir", ["L'expulsion d'un diplomate", "L'arbitrage d'un différend", "La naturalisation d'un étranger"],
     "Elle repose sur des traités ou la réciprocité.", 3),
    ("Qu'est-ce que la compétence universelle ?",
     "La faculté pour un État de poursuivre certains crimes graves, où qu'ils aient été commis", ["La compétence de la CIJ sur tous les États", "L'obligation de juger tous les crimes", "La compétence exclusive de l'ONU"],
     "Elle s'applique à des crimes comme le génocide, selon les législations.", 4),
    ("Qui peut être partie à un différend contentieux devant la CIJ ?",
     "Les États", ["Les particuliers", "Les ONG", "Les entreprises multinationales"], "Seuls les États peuvent être parties à la procédure contentieuse.", 3),
    ("Sur quoi repose la compétence de la CIJ dans un différend entre États ?",
     "Sur le consentement des États concernés", ["Sur une décision du Conseil de sécurité", "Sur la gravité de l'affaire", "Sur la demande d'un particulier"],
     "Nul État ne peut être contraint de comparaître sans y avoir consenti.", 4),
    ("Qui peut demander un avis consultatif à la CIJ ?",
     "Des organes de l'ONU et des institutions spécialisées autorisées", ["Un État seul, à titre individuel", "Un particulier", "Une ONG"], "Les États ne peuvent pas la saisir pour avis.", 5),
    ("Combien de juges siègent à la CIJ ?", "Quinze", ["Neuf", "Onze", "Vingt et un"], "Ils sont élus par l'Assemblée générale et le Conseil de sécurité.", 4),
    ("Par quels organes les juges de la CIJ sont-ils élus ?",
     "Par l'Assemblée générale et le Conseil de sécurité, chacun votant de son côté", ["Par le Secrétaire général seul", "Par les États parties à son Statut seuls", "Par le Conseil de tutelle"],
     "Il faut la majorité absolue dans les deux organes.", 5),
    ("Quelle est la portée d'un arrêt de la CIJ ?",
     "Il est obligatoire pour les parties et sans appel", ["Il est un simple avis", "Il peut être réformé par le Conseil de sécurité", "Il s'impose à tous les États du monde"],
     "Il n'a force obligatoire qu'entre les parties et pour l'affaire.", 3),
    ("Que peut faire le Conseil de sécurité si une partie n'exécute pas un arrêt de la CIJ ?",
     "Faire des recommandations ou décider de mesures pour faire exécuter l'arrêt", ["Annuler l'arrêt", "Rejuger l'affaire", "Dissoudre la Cour"],
     "La Charte lui confie ce rôle si une partie saisit le Conseil.", 5),
    ("Lequel de ces crimes relève de la compétence de la CPI ?",
     "Le génocide", ["Le trafic de stupéfiants", "La fraude fiscale", "Le vol à main armée"],
     "Elle juge génocide, crimes contre l'humanité, crimes de guerre et crime d'agression.", 2),
    ("Que signifie le principe de complémentarité de la CPI ?",
     "La CPI n'intervient que si les juridictions nationales ne veulent ou ne peuvent pas poursuivre", ["La CPI remplace toujours les juridictions nationales", "La CPI juge les États", "La CPI se limite aux affaires civiles"],
     "La priorité reste aux juridictions nationales.", 4),
    ("Qui la CPI poursuit-elle ?", "Des individus", ["Des États", "Des organisations internationales", "Des entreprises seulement"], "La CPI engage la responsabilité pénale individuelle.", 2),
    ("Qui peut déclencher une enquête de la CPI ?",
     "Un État partie, le Conseil de sécurité ou le Procureur avec autorisation judiciaire", ["Toute victime directement", "L'Assemblée générale", "La CIJ"],
     "Ce sont les trois modes de saisine prévus par le Statut de Rome.", 5),
    ("Quelle différence essentielle oppose la CIJ à la CPI ?",
     "La CIJ tranche des différends entre États, la CPI juge des individus", ["La CIJ juge des individus, la CPI des États", "Elles jugent toutes deux les mêmes crimes", "La CPI est un organe de l'ONU, la CIJ non"],
     "Les deux sont à La Haye mais ont des compétences distinctes.", 3),
    ("Que prévoit la responsabilité de l'État pour l'acte d'un organe agissant dans l'exercice de ses fonctions ?",
     "L'acte est en principe attribuable à l'État", ["L'acte n'engage que la personne physique", "L'acte relève uniquement du droit interne", "L'acte est attribuable à l'ONU"],
     "Le comportement d'un organe de l'État est imputable à celui-ci.", 4),
    ("Qu'est-ce qu'un sujet de droit international ?",
     "Une entité titulaire de droits et d'obligations en droit international", ["Une personne qui étudie le droit international", "Un État seulement", "Un traité en vigueur"],
     "Les États sont les sujets originaires ; les organisations en sont des sujets dérivés.", 3),
    ("Quelle est la nature de la personnalité juridique des organisations internationales ?",
     "Elle est dérivée, fondée sur la volonté des États membres", ["Elle est originaire comme celle des États", "Elle n'existe jamais", "Elle est créée par chaque juge"],
     "Les États restent les sujets originaires.", 4),
], cat="Droit international public : cas et distinctions", src="sup-dip")

mcq(RI, "oi-mcq", [
    ("Quel principe de la Charte de l'ONU interdit aux États de recourir à la force ?",
     "L'interdiction de la menace ou de l'emploi de la force contre un autre État",
     ["Le principe de rétroactivité", "Le droit de veto", "La clause facultative de juridiction obligatoire"],
     "Les exceptions sont la légitime défense et l'action autorisée par le Conseil.", 4),
    ("Quelle institution financière régionale est consacrée au développement de l'Afrique ?",
     "La Banque africaine de développement", ["La Banque centrale européenne", "La Banque des règlements internationaux", "La Banque asiatique de développement"],
     "Elle finance des projets de développement sur le continent.", 2),
    ("Où et par quel texte l'Union africaine a-t-elle été fondée ?",
     "Par un Acte constitutif adopté à Lomé", ["Par une Charte adoptée à New York", "Par un Statut adopté à Rome", "Par un traité adopté à Yaoundé"],
     "L'Acte constitutif a été adopté à Lomé avant le lancement de l'Union.", 4),
    ("Quelle est la mission du Conseil de paix et de sécurité de l'Union africaine ?",
     "Prévenir, gérer et régler les conflits sur le continent", ["Émettre la monnaie commune africaine", "Juger les crimes de guerre", "Organiser les élections nationales"],
     "Il est l'organe permanent de décision de l'UA en matière de paix et de sécurité.", 3),
    ("Quel organe de l'ONU peut décider de sanctions obligatoires pour les États membres ?",
     "Le Conseil de sécurité", ["L'Assemblée générale", "Le Conseil économique et social", "Le Secrétariat"],
     "Ses décisions sous le chapitre VII lient les États membres.", 3),
    ("Quelle institution de l'ONU est chargée de la protection des réfugiés ?",
     "Le HCR", ["La FAO", "L'OMS", "L'UNESCO"], "Le Haut-Commissariat des Nations unies pour les réfugiés.", 2),
    ("Quelle organisation internationale élabore des normes du travail avec représentants des gouvernements, employeurs et travailleurs ?",
     "L'OIT", ["L'OMC", "L'UNESCO", "Le FMI"], "Son fonctionnement est tripartite.", 4),
], cat="Organisations internationales : cas et distinctions", src="sup-oi")
