"""L1 droit : introduction générale au droit (notions, sources, personnes, famille, biens, preuve, organisation judiciaire).
Faits rédigés par l'assistant, tous `review` : relecture par un juriste ou un enseignant indispensable.
Sauf mention contraire, les énoncés portent sur les principes généraux de tradition civiliste (français / OHADA / Cameroun) ;
aucun article, délai, seuil ni montant n'est cité."""
from .sup_kit import *      # source, table, classify, mcq, fq, pairs, pick, cap

C = "l1-droit"
_mcq = mcq


def mcq(course, tpl, rows, *, cat, src, region="WORLD"):
    """Comme le mcq du kit, avec majuscule initiale sur chaque réponse (les énoncés sont des questions complètes)."""
    _mcq(course, tpl, [(q, cap(r), [cap(w) for w in ws], e, d) for q, r, ws, e, d in rows], cat=cat, src=src, region=region)

source("sup-droit-intro", "Introduction générale au droit : notion, sources, personnes, famille, biens, preuve", "cours de L1 droit",
       "Comparer avec un manuel d'introduction générale au droit (droit civil de tradition romano-germanique) et avec les textes camerounais en vigueur.")
source("sup-droit-just", "Organisation judiciaire et procédure : principes généraux", "cours de L1 droit",
       "Comparer avec un manuel d'organisation judiciaire / de procédure et avec la loi camerounaise sur l'organisation judiciaire en vigueur.")

# ---------------------------------------------------------------------------------------------------------------------------------
# 1. NOTION DE DROIT, RÈGLE DE DROIT
# ---------------------------------------------------------------------------------------------------------------------------------
table(C, "di-notions", [
    ("le droit objectif", "l'ensemble des règles qui organisent la vie en société, sous la garantie de la contrainte publique", 2),
    ("un droit subjectif", "une prérogative reconnue à une personne, qu'elle peut faire respecter", 2),
    ("une règle de droit", "une règle générale, abstraite et obligatoire, dont le respect est garanti par une sanction", 2),
    ("le droit positif", "le droit effectivement en vigueur dans un État à un moment donné", 2),
    ("le droit naturel", "l'idée d'un droit supérieur, fondé sur la nature ou la raison, indépendant des textes", 3),
    ("le droit commun", "les règles générales applicables à défaut de règle spéciale écartant leur application", 3),
    ("une règle supplétive", "une règle qui s'applique seulement si les parties n'ont pas prévu autre chose", 3),
    ("une règle impérative", "une règle à laquelle les particuliers ne peuvent pas déroger par leur volonté", 3),
    ("la codification", "le regroupement des règles d'une même matière dans un code organisé", 2),
    ("la promulgation", "l'acte par lequel l'autorité compétente atteste l'adoption de la loi et la rend exécutoire", 3),
    ("la publication de la loi", "la formalité qui porte la loi à la connaissance de ses destinataires", 2),
    ("l'usage", "une pratique habituelle dans un milieu, dépourvue du sentiment d'obligation propre à la coutume", 3),
    ("un règlement", "un acte de portée générale émanant d'une autorité exécutive", 2),
    ("la sanction", "la mesure destinée à faire respecter une règle ou à réparer sa violation", 2),
    ("la contrainte publique", "le recours à la force de l'État pour imposer l'application du droit", 3),
    ("la justice", "la vertu qui consiste à rendre à chacun ce qui lui revient", 2),
], cat="Notion de droit", src="sup-droit-intro", fwd="En droit, qu'est-ce que {a} ?", rev="Quelle notion désigne {b} ?")

table(C, "di-sources", [
    ("la Constitution", "la norme suprême qui organise les pouvoirs publics et garantit les droits fondamentaux", 1),
    ("un traité international", "un accord conclu entre sujets du droit international et soumis à ratification", 2),
    ("un décret", "un acte réglementaire signé par le chef de l'exécutif ou le chef du gouvernement", 2),
    ("un arrêté", "un acte réglementaire pris par un ministre, un préfet ou un maire", 2),
    ("une circulaire", "une instruction écrite d'une autorité à ses services sur la façon d'appliquer un texte", 3),
    ("une ordonnance", "un acte pris par l'exécutif dans le domaine de la loi, sur habilitation du Parlement", 3),
    ("un code", "un recueil organisé de textes relatifs à une même matière", 1),
    ("un principe général du droit", "une règle fondamentale non écrite que le juge dégage et applique même en l'absence de texte", 4),
    ("la doctrine", "l'ensemble des travaux des juristes qui commentent le droit sans créer de règle obligatoire", 2),
    ("un arrêt de principe", "une décision de justice qui tranche une question de droit importante et sert de référence", 4),
    ("la jurisprudence constante", "une même solution adoptée de manière répétée par les juridictions sur une question de droit", 3),
], cat="Sources du droit", src="sup-droit-intro", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "di-adages", [
    ("nemo auditur propriam turpitudinem allegans", "nul ne peut invoquer sa propre turpitude pour fonder une prétention", 4),
    ("fraus omnia corrumpit", "la fraude corrompt tout et prive l'acte de ses effets", 4),
    ("error communis facit jus", "l'erreur commune et invincible peut produire les effets du droit", 5),
    ("nemo plus juris ad alium transferre potest quam ipse habet", "nul ne peut transmettre à autrui plus de droits qu'il n'en a lui-même", 4),
    ("accessorium sequitur principale", "l'accessoire suit le sort du principal", 3),
    ("infans conceptus pro nato habetur quoties de commodis ejus agitur", "l'enfant conçu est tenu pour né chaque fois que son intérêt l'exige", 4),
    ("non bis in idem", "nul ne peut être poursuivi ou jugé deux fois pour les mêmes faits", 3),
    ("nemo judex in causa sua", "nul ne peut être juge dans sa propre cause", 3),
    ("audi alteram partem", "chaque partie doit pouvoir être entendue avant que le juge ne statue", 3),
    ("locus regit actum", "la forme d'un acte est régie par la loi du lieu où il est passé", 4),
    ("ubi lex non distinguit, nec nos distinguere debemus", "là où la loi ne distingue pas, il n'y a pas lieu de distinguer", 4),
    ("mater semper certa est", "la mère est toujours certaine", 3),
    ("ubi societas, ibi jus", "partout où il y a une société, il y a du droit", 3),
], cat="Adages juridiques", src="sup-droit-intro", fwd="Que signifie l'adage « {a} » ?", rev="Quel adage latin exprime l'idée suivante : {b} ?",
      expl="L'adage « {a} » signifie : {b}.")

# ---------------------------------------------------------------------------------------------------------------------------------
# 2. SANCTIONS
# ---------------------------------------------------------------------------------------------------------------------------------
table(C, "di-sanctions", [
    ("la nullité", "l'anéantissement d'un acte juridique irrégulier, en principe de façon rétroactive", 2),
    ("l'inopposabilité", "la sanction qui empêche d'invoquer un acte à l'égard d'un tiers, sans l'anéantir entre les parties", 4),
    ("la réparation par dommages et intérêts", "la somme d'argent allouée à la victime pour compenser le préjudice subi", 2),
    ("la peine", "la sanction pénale infligée à l'auteur d'une infraction", 1),
    ("la déchéance", "la perte d'un droit prononcée à titre de sanction", 3),
    ("l'exécution forcée en nature", "la contrainte employée pour obtenir du débiteur la prestation même qui était promise", 3),
    ("l'astreinte", "la somme due par jour de retard pour contraindre le débiteur à exécuter", 3),
    ("la résolution du contrat", "l'anéantissement d'un contrat pour inexécution d'une obligation par l'une des parties", 3),
    ("la caducité", "la disparition d'un acte valablement formé, faute d'un élément nécessaire à son maintien", 5),
], cat="Sanction de la règle de droit", src="sup-droit-intro", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

# ---------------------------------------------------------------------------------------------------------------------------------
# 3. BRANCHES DU DROIT ET CLASSIFICATIONS
# ---------------------------------------------------------------------------------------------------------------------------------
classify(C, "di-branches", {
    "le droit constitutionnel": ["l'élection du chef de l'État", "la révision de la Constitution", "le contrôle de constitutionnalité des lois", "la séparation des pouvoirs", "le statut des assemblées parlementaires"],
    "le droit administratif": ["le service public", "le recours pour excès de pouvoir", "la responsabilité de la puissance publique", "le contrat de marché public", "le pouvoir réglementaire d'un maire"],
    "le droit commercial": ["le fonds de commerce", "la lettre de change", "le registre du commerce", "le bail commercial", "la qualité de commerçant"],
    "le droit du travail": ["le licenciement d'un salarié", "la convention collective", "le règlement intérieur d'entreprise", "le contrat de travail", "le délégué du personnel"],
    "le droit pénal": ["la légitime défense", "la tentative d'infraction", "la complicité", "la récidive", "la circonstance aggravante"],
    "le droit civil": ["le contrat de vente", "le régime matrimonial", "la responsabilité du fait des choses", "la filiation", "la propriété d'un terrain"],
}, cat="Branches du droit", src="sup-droit-intro", fwd="De quelle branche du droit relève {item} ?", rev="Lequel de ces éléments relève de {group} ?",
         expl="{item} relève de {group}.")

classify(C, "di-matieres-civ", {
    "le droit des personnes et de la famille": ["le nom de famille", "le mariage", "la filiation", "la tutelle d'un mineur", "l'autorité parentale", "la capacité juridique"],
    "le droit des biens": ["l'usufruit", "la servitude de passage", "la possession", "la copropriété", "la propriété d'un immeuble", "la nue-propriété"],
    "le droit des obligations": ["la responsabilité civile délictuelle", "le contrat", "le paiement d'une dette", "la gestion d'affaires", "la novation", "la résolution pour inexécution"],
    "le droit des successions et libéralités": ["le testament", "le legs", "l'acceptation d'une succession", "la donation entre vifs", "l'indignité successorale", "le partage entre cohéritiers"],
}, cat="Grandes matières du droit civil", src="sup-droit-intro", fwd="À quelle grande matière du droit civil se rattache {item} ?", rev="Lequel de ces éléments relève de {group} ?",
         expl="{item} se rattache à {group}.")

classify(C, "di-droits", {
    "un droit réel": ["le droit de propriété", "l'usufruit", "la servitude", "l'hypothèque", "le droit d'usage d'un bien"],
    "un droit personnel (droit de créance)": ["le droit du vendeur d'être payé du prix", "le droit du bailleur de percevoir son loyer", "le droit du salarié à son salaire", "le droit du prêteur d'être remboursé", "le droit de la victime à une indemnité"],
    "un droit intellectuel": ["le droit d'auteur sur un roman", "le brevet d'invention", "le droit sur une marque", "le droit sur un dessin ou modèle"],
    "un droit de la personnalité": ["le droit à l'image", "le droit au respect de la vie privée", "le droit à l'honneur", "le droit à l'intégrité physique"],
}, cat="Classification des droits subjectifs", src="sup-droit-intro", fwd="Dans la classification des droits subjectifs, à quelle catégorie appartient {item} ?", rev="Lequel de ces droits est classé parmi {group} ?",
         expl="{item} est classé parmi {group}.")

# ---------------------------------------------------------------------------------------------------------------------------------
# 4. PREUVE
# ---------------------------------------------------------------------------------------------------------------------------------
table(C, "di-preuve", [
    ("un acte sous seing privé", "un écrit établi et signé par les parties elles-mêmes, sans intervention d'un officier public", 3),
    ("le témoignage", "la déclaration d'une personne qui relate ce qu'elle a personnellement vu ou entendu", 2),
    ("une présomption", "une conséquence que la loi ou le juge tire d'un fait connu pour établir un fait inconnu", 3),
    ("une présomption irréfragable", "une présomption qui n'admet pas la preuve contraire", 4),
    ("une présomption simple", "une présomption que l'on peut combattre par la preuve contraire", 3),
    ("l'aveu", "la déclaration par laquelle une partie reconnaît l'exactitude d'un fait qui lui est défavorable", 3),
    ("le serment décisoire", "le serment qu'une partie défère à l'autre pour faire dépendre de sa prestation l'issue du litige", 5),
    ("l'expertise", "la mesure d'instruction confiée à un technicien pour éclairer le juge sur une question technique", 2),
    ("la preuve libre", "le régime dans lequel tous les modes de preuve sont admis et laissés à l'appréciation du juge", 3),
    ("la preuve légale", "le régime dans lequel la loi impose les modes de preuve admissibles et leur force", 3),
    ("le commencement de preuve par écrit", "un écrit de l'adversaire qui rend vraisemblable le fait allégué, à compléter par d'autres preuves", 5),
    ("la charge de la preuve", "l'obligation pesant sur une partie de démontrer les faits qu'elle invoque", 2),
    ("l'objet de la preuve", "les faits juridiquement pertinents que le plaideur doit établir", 3),
], cat="La preuve", src="sup-droit-intro", fwd="En matière de preuve, qu'est-ce que {a} ?", rev="En matière de preuve, comment appelle-t-on {b} ?")

# ---------------------------------------------------------------------------------------------------------------------------------
# 5. PERSONNES PHYSIQUES
# ---------------------------------------------------------------------------------------------------------------------------------
table(C, "di-pers-phys", [
    ("le nom", "le signe qui désigne et identifie une personne dans la société", 1),
    ("le domicile", "le lieu du principal établissement d'une personne", 2),
    ("la résidence", "le lieu où une personne vit effectivement, même de façon provisoire", 3),
    ("le patrimoine", "l'ensemble des droits et obligations d'une personne, évaluables en argent", 3),
    ("la nationalité", "le lien juridique d'appartenance d'une personne à un État", 2),
    ("l'état des personnes", "l'ensemble des éléments qui identifient une personne : âge, sexe, filiation, mariage", 3),
    ("l'officier d'état civil", "l'agent public qui reçoit et rédige les actes de naissance, de mariage et de décès", 2),
    ("le pseudonyme", "un nom d'emprunt choisi par une personne, notamment dans une activité artistique ou littéraire", 3),
    ("l'émancipation", "l'acte qui rend un mineur capable avant la majorité, dans les conditions fixées par la loi", 4),
    ("la majorité", "l'âge à partir duquel une personne devient pleinement capable d'exercer ses droits", 1),
    ("la curatelle", "un régime de protection du majeur qui doit être assisté ou conseillé pour les actes importants", 4),
    ("l'absence", "la situation d'une personne qui n'est plus apparue à son domicile et dont on n'a plus de nouvelles", 4),
    ("la possession d'état", "le fait de se comporter comme l'enfant ou l'époux de telle personne et d'être ainsi considéré", 5),
    ("l'acte de naissance", "l'acte d'état civil qui constate la naissance et sert à établir l'identité d'une personne", 2),
], cat="Personnes physiques", src="sup-droit-intro", fwd="En droit civil, qu'est-ce que {a} ?", rev="En droit civil, comment appelle-t-on {b} ?")

table(C, "di-pers-morale", [
    ("une association", "un groupement de personnes qui mettent en commun leur activité sans but de partage de bénéfices", 2),
    ("une société", "un groupement dont les membres font des apports pour exercer une activité et en partager le résultat", 2),
    ("la dénomination sociale", "le nom d'une personne morale, qui l'identifie", 3),
    ("le siège social", "le domicile juridique d'une personne morale", 3),
    ("l'objet social", "l'activité en vue de laquelle une personne morale est constituée", 3),
    ("le principe de spécialité", "la règle selon laquelle une personne morale n'a de capacité que pour réaliser son objet", 5),
    ("la dissolution", "l'événement ou la décision qui met fin à l'existence d'une personne morale", 3),
    ("la liquidation", "l'ensemble des opérations qui règlent les dettes et les créances d'une personne morale dissoute", 4),
    ("la fusion de sociétés", "l'opération par laquelle plusieurs sociétés se réunissent en une seule", 4),
    ("le représentant légal d'une personne morale", "la personne qui l'engage à l'égard des tiers et agit en son nom", 3),
    ("une personne morale de droit public", "un groupement tel que l'État, une région ou une commune, titulaire de prérogatives publiques", 3),
    ("une fondation", "l'affectation irrévocable de biens à une œuvre d'intérêt général", 4),
    ("un syndicat professionnel", "un groupement qui défend les intérêts professionnels de ses membres", 3),
], cat="Personnes morales", src="sup-droit-intro", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

# ---------------------------------------------------------------------------------------------------------------------------------
# 6. FAMILLE
# ---------------------------------------------------------------------------------------------------------------------------------
table(C, "di-famille", [
    ("le divorce", "la rupture du mariage prononcée par un juge du vivant des époux", 2),
    ("la séparation de corps", "le régime qui dispense les époux de vivre ensemble sans rompre le lien du mariage", 4),
    ("la nullité du mariage", "l'anéantissement du mariage pour défaut d'une condition de validité", 4),
    ("la filiation", "le lien juridique qui unit un enfant à son père ou à sa mère", 2),
    ("la reconnaissance d'enfant", "l'acte par lequel une personne déclare être le père ou la mère de l'enfant", 3),
    ("l'adoption", "la création d'un lien de filiation fondé sur la volonté et prononcé par une autorité", 3),
    ("l'autorité parentale", "l'ensemble des droits et devoirs des parents sur l'enfant mineur, dans l'intérêt de celui-ci", 2),
    ("l'obligation alimentaire", "le devoir de fournir à certains proches dans le besoin ce qui est nécessaire à leur vie", 3),
    ("la parenté", "le lien qui unit des personnes descendant l'une de l'autre ou d'un auteur commun", 3),
    ("l'alliance", "le lien qui unit un époux aux parents de son conjoint", 4),
    ("le conseil de famille", "l'assemblée de proches qui participe au contrôle d'une tutelle", 4),
    ("la dot coutumière", "dans de nombreuses coutumes africaines, les biens remis à la famille de l'épouse lors du mariage", 3),
    ("l'acte de mariage", "l'acte d'état civil dressé par l'officier d'état civil lors de la célébration du mariage", 2),
], cat="Droit de la famille", src="sup-droit-intro", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "di-regimes", [
    ("le régime matrimonial", "l'ensemble des règles qui organisent les rapports pécuniaires des époux entre eux et avec les tiers", 3),
    ("le régime de la communauté de biens", "un régime dans lequel certains biens acquis pendant le mariage appartiennent aux deux époux", 3),
    ("le régime de la séparation de biens", "un régime dans lequel chaque époux conserve la propriété et la gestion de ses biens", 3),
    ("le contrat de mariage", "la convention par laquelle les futurs époux choisissent leur régime matrimonial", 3),
    ("le bien propre", "le bien qui reste la propriété personnelle d'un époux sous un régime de communauté", 4),
    ("le bien commun", "le bien qui appartient à la communauté des époux", 4),
    ("la liquidation du régime matrimonial", "les opérations qui déterminent les droits de chaque époux lors de la dissolution du régime", 5),
], cat="Régimes matrimoniaux", src="sup-droit-intro", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

# ---------------------------------------------------------------------------------------------------------------------------------
# 7. SUCCESSIONS
# ---------------------------------------------------------------------------------------------------------------------------------
table(C, "di-succ", [
    ("la succession", "la transmission du patrimoine d'une personne décédée à ses héritiers ou légataires", 2),
    ("le de cujus", "la personne décédée dont la succession est ouverte", 3),
    ("l'héritier", "la personne appelée par la loi à recueillir tout ou partie de la succession", 2),
    ("le légataire", "la personne qui reçoit un bien en vertu d'un testament", 2),
    ("le testament", "l'acte unilatéral par lequel une personne dispose de ses biens pour le temps où elle ne sera plus", 2),
    ("la succession ab intestat", "la succession réglée par la loi à défaut de testament", 3),
    ("l'indignité successorale", "la déchéance du droit de succéder encourue pour une faute grave envers le défunt", 4),
    ("la renonciation à la succession", "le refus de l'héritier de recueillir la succession", 3),
    ("l'acceptation pure et simple", "l'option par laquelle l'héritier recueille la succession avec son actif et son passif", 4),
    ("l'indivision successorale", "la situation de cohéritiers titulaires ensemble de droits sur les biens du défunt avant partage", 3),
    ("le partage", "l'opération qui met fin à l'indivision en attribuant à chacun des biens en propre", 3),
    ("la représentation successorale", "le mécanisme qui permet à des descendants de venir à la succession à la place de leur parent décédé", 5),
    ("la réserve héréditaire", "la part de la succession garantie à certains héritiers, dans les systèmes qui la prévoient", 5),
    ("la dévolution successorale", "la détermination des personnes appelées à recueillir la succession et de leurs parts", 4),
    ("la donation entre vifs", "l'acte par lequel on se dépouille de son vivant et irrévocablement d'un bien au profit d'autrui", 3),
], cat="Successions et libéralités", src="sup-droit-intro", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

# ---------------------------------------------------------------------------------------------------------------------------------
# 8. BIENS ET PROPRIÉTÉ
# ---------------------------------------------------------------------------------------------------------------------------------
table(C, "di-biens", [
    ("un meuble", "un bien qui peut être déplacé ou que la loi qualifie ainsi", 2),
    ("un immeuble par nature", "un bien fixé au sol, comme un terrain ou un bâtiment", 2),
    ("un immeuble par destination", "un meuble que le propriétaire affecte au service et à l'exploitation de son immeuble", 4),
    ("un bien corporel", "un bien qui a une existence matérielle", 2),
    ("un bien incorporel", "un bien sans existence matérielle, comme une créance ou une marque", 3),
    ("une chose fongible", "une chose interchangeable avec une autre de même espèce et de même quantité", 3),
    ("une chose consomptible", "une chose qui se détruit par le premier usage", 3),
    ("une chose hors commerce", "une chose qui ne peut pas faire l'objet d'une appropriation ou d'une convention", 4),
    ("une chose sans maître", "une chose qui n'appartient à personne et peut être appropriée", 4),
    ("les fruits", "les produits périodiques d'une chose, qui ne l'altèrent pas dans sa substance", 3),
    ("un bien du domaine public", "un bien public affecté à l'usage du public ou à un service public, en principe inaliénable", 4),
], cat="Classification des biens", src="sup-droit-intro", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

table(C, "di-propriete", [
    ("la propriété", "le droit de jouir et de disposer d'une chose de la façon la plus complète, dans les limites légales", 2),
    ("l'usus", "le droit d'utiliser la chose", 3),
    ("le fructus", "le droit d'en percevoir les fruits", 3),
    ("l'abusus", "le droit d'en disposer, en la vendant, en la donnant ou en la détruisant", 3),
    ("l'usufruit", "le droit d'user du bien d'autrui et d'en percevoir les fruits, sans pouvoir en disposer", 3),
    ("la nue-propriété", "la propriété d'un bien dont un autre a l'usufruit", 4),
    ("la servitude", "une charge imposée à un fonds au profit d'un autre fonds appartenant à un autre propriétaire", 3),
    ("la possession", "le fait de détenir une chose en se comportant comme son propriétaire", 3),
    ("la détention précaire", "le fait de tenir une chose pour le compte d'autrui, comme le fait un locataire", 4),
    ("la prescription acquisitive", "l'acquisition d'un droit par une possession prolongée et paisible", 4),
    ("l'hypothèque", "une sûreté réelle qui grève un immeuble sans en priver le débiteur", 4),
    ("l'accession", "le droit du propriétaire d'une chose sur ce qui s'y unit ou s'y incorpore", 5),
    ("la copropriété", "la propriété d'un même bien partagée entre plusieurs propriétaires", 3),
    ("l'expropriation pour cause d'utilité publique", "le transfert forcé de propriété à une personne publique moyennant une juste indemnité", 4),
], cat="Propriété et droits réels", src="sup-droit-intro", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

# ---------------------------------------------------------------------------------------------------------------------------------
# 9. ORGANISATION JUDICIAIRE ET PROCÉDURE
# ---------------------------------------------------------------------------------------------------------------------------------
table(C, "dj-roles", [
    ("le ministère public", "défendre l'intérêt de la société et requérir l'application de la loi", 2),
    ("l'expert judiciaire", "éclairer le juge sur une question technique que celui-ci ne maîtrise pas", 2),
    ("le bâtonnier", "présider l'ordre des avocats et veiller au respect de la déontologie", 3),
    ("le juge des référés", "ordonner rapidement des mesures urgentes ou provisoires", 3),
    ("le juge de l'exécution", "trancher les difficultés qui naissent de l'exécution forcée des décisions et des titres", 4),
    ("le juge du siège", "juger les litiges en toute indépendance, sans être soumis à une hiérarchie dans ses décisions", 3),
    ("la juridiction de cassation", "contrôler la bonne application du droit par les juges du fond, sans rejuger les faits", 3),
    ("le juge d'appel", "réexaminer en fait et en droit une affaire déjà jugée en première instance", 3),
    ("le greffe", "assister les juges, conserver les minutes et authentifier les actes de procédure", 3),
    ("l'huissier de justice", "signifier les actes de procédure et mettre à exécution les décisions", 2),
    ("le notaire", "recevoir les actes auxquels les parties veulent conférer l'authenticité", 2),
], cat="Acteurs de la justice", src="sup-droit-just", fwd="Quel est le rôle principal de {a} ?", rev="Qui a pour rôle de {b} ?")

table(C, "dj-procedure", [
    ("l'assignation", "l'acte d'huissier par lequel on cite une personne à comparaître devant un tribunal", 3),
    ("la compétence d'attribution", "la répartition des litiges entre juridictions selon leur nature ou leur importance", 4),
    ("la compétence territoriale", "la répartition des litiges entre juridictions de même nature selon le lieu", 3),
    ("le double degré de juridiction", "la faculté de soumettre l'affaire à un second examen en fait et en droit", 3),
    ("le jugement en dernier ressort", "le jugement qui n'est pas susceptible d'appel", 4),
    ("le jugement en premier ressort", "le jugement qui peut être attaqué par la voie de l'appel", 4),
    ("l'exécution provisoire", "la faculté d'exécuter une décision malgré l'exercice d'une voie de recours", 4),
    ("la tierce opposition", "le recours d'un tiers lésé par un jugement auquel il n'était pas partie", 5),
    ("le défaut de comparution", "la situation du défendeur régulièrement cité qui ne se présente pas devant le juge", 3),
    ("le délibéré", "la phase où les juges décident entre eux avant de rendre la décision", 3),
    ("le dispositif", "la partie du jugement qui contient la décision proprement dite", 3),
    ("les motifs d'un jugement", "la partie qui expose les raisons de fait et de droit de la décision", 3),
    ("l'intérêt à agir", "l'avantage que procurerait le succès de la demande, condition de recevabilité de l'action", 4),
    ("la qualité pour agir", "le titre en vertu duquel une personne exerce l'action en justice", 4),
    ("la partie civile", "la victime qui demande réparation devant la juridiction pénale", 3),
    ("la fin de non-recevoir", "le moyen qui tend à faire déclarer la demande irrecevable sans examen au fond", 5),
], cat="Procédure et voies de recours", src="sup-droit-just", fwd="Qu'est-ce que {a} ?", rev="Comment appelle-t-on {b} ?")

# ---------------------------------------------------------------------------------------------------------------------------------
# 10. MCQ : NOTION DE DROIT, RÈGLE DE DROIT, MORALE ET USAGES
# ---------------------------------------------------------------------------------------------------------------------------------
mcq(C, "di-m-regle", [
    ("Qu'est-ce qui distingue avant tout une règle de droit d'une règle de morale ?", "La règle de droit est sanctionnée par la contrainte de l'autorité publique",
     ["La règle de droit n'est jamais écrite", "La règle morale ne vise que les actes publics", "La règle de droit ne concerne que les crimes"],
     "Seule la règle juridique est garantie par la force publique ; la sanction de la morale est la conscience ou la réprobation sociale.", 2),
    ("Pourquoi dit-on qu'une règle de droit est générale ?", "elle s'applique à toutes les personnes placées dans la situation qu'elle prévoit",
     ["elle ne s'applique qu'à une seule personne nommément désignée", "elle est connue de tous sans avoir besoin d'être publiée", "elle a été votée à l'unanimité des assemblées"],
     "La généralité s'oppose aux mesures individuelles : la règle vise une catégorie de personnes.", 3),
    ("Pourquoi dit-on qu'une règle de droit est abstraite ?", "elle est formulée sans viser un cas concret ou une affaire particulière",
     ["elle est rédigée en termes obscurs", "elle ne s'applique qu'à une époque révolue", "elle ne relève que de la philosophie"],
     "L'abstraction signifie que la règle prévoit des situations types, non une espèce déterminée.", 3),
    ("Parmi ces règles, laquelle est une règle de droit ?", "L'obligation de réparer le dommage causé à autrui par sa faute",
     ["L'usage de céder sa place à une personne âgée", "Le devoir de dire bonjour en entrant dans une salle", "L'habitude de se serrer la main en se rencontrant"],
     "L'obligation de réparer est imposée et sanctionnée par le juge ; les autres sont des règles de politesse.", 2),
    ("Quelle est la sanction normale du non-respect d'une règle de politesse ?", "Une réprobation sociale, sans contrainte de l'État",
     ["Une amende prononcée par le juge", "L'annulation de l'acte concerné", "Des dommages et intérêts automatiques"],
     "La politesse est une règle sociale non juridique : sa sanction est diffuse.", 2),
    ("Une même conduite peut être à la fois contraire à la morale et au droit. Quel exemple l'illustre ?", "Le vol",
     ["Le mensonge entre amis, sans conséquence", "Le fait de ne pas remercier quelqu'un", "L'ingratitude envers un bienfaiteur"],
     "Le vol viole une norme morale et une norme pénale.", 2),
    ("Quel est le fondement de l'obligation d'une règle religieuse pour le croyant ?", "Sa conviction personnelle et l'autorité de sa religion",
     ["La seule menace d'une peine prononcée par un tribunal", "Le vote d'une loi par le Parlement", "L'ordre d'un huissier de justice"],
     "La règle religieuse n'est pas, comme telle, une règle de droit : sa force vient de la foi.", 2),
    ("Dans un État laïc, que devient une règle religieuse ?", "Elle n'a de valeur juridique que si l'ordre juridique l'a reprise",
     ["Elle s'impose à tous comme une loi", "Elle prime sur la Constitution", "Elle est automatiquement abrogée"],
     "Une norme religieuse ne devient juridique que par son incorporation dans le droit de l'État.", 3),
    ("Qu'appelle-t-on le droit objectif ?", "Le droit considéré comme ensemble de règles s'imposant à tous",
     ["Le droit reconnu à une personne sur une chose", "Le droit d'agir en justice", "Un droit qui ne souffre aucune contestation"],
     "Le droit objectif est le droit comme système de règles ; le droit subjectif est la prérogative d'une personne.", 2),
    ("De quelle nature est le droit de propriété que Paul exerce sur sa maison ?", "un droit subjectif",
     ["le droit objectif", "une règle de morale", "un usage professionnel"],
     "C'est une prérogative individuelle reconnue par le droit objectif.", 2),
    ("Quelle est la relation entre droit objectif et droit subjectif ?", "Le droit objectif fonde et délimite les droits subjectifs des personnes",
     ["Les droits subjectifs précèdent toujours toute règle", "Le droit subjectif est une règle générale", "Il s'agit d'une seule et même notion"],
     "C'est parce qu'une règle objective le reconnaît qu'une personne détient un droit subjectif.", 3),
    ("Que signifie l'expression « droit positif » ?", "Le droit en vigueur à un moment donné dans un État",
     ["Le droit qui garantit seulement des avantages", "Le droit idéal imaginé par les philosophes", "Le droit de l'Antiquité romaine"],
     "Le droit positif s'oppose au droit idéal ou naturel.", 2),
    ("À qui les règles de droit s'adressent-elles d'abord ?", "à des personnes vivant en société",
     ["aux seuls juristes", "aux seuls juges", "aux seules administrations"],
     "Le droit organise les rapports sociaux ; il s'impose à tous.", 1),
    ("Selon la maxime « ubi societas, ibi jus », où y a-t-il du droit ?", "Partout où existe une société",
     ["Uniquement là où existent des tribunaux", "Uniquement dans les États modernes", "Là où il n'y a pas de coutume"],
     "Toute vie sociale suppose des règles.", 2),
    ("Quelle est la fonction essentielle du droit dans une société ?", "Organiser les rapports sociaux et assurer l'ordre et la justice",
     ["Supprimer tous les conflits entre personnes", "Remplacer la morale individuelle", "Garantir l'égalité des richesses"],
     "Le droit prévient et règle les conflits en vue de l'ordre et de la justice, sans prétendre les supprimer.", 2),
    ("Que désigne la sécurité juridique ?", "La stabilité et la prévisibilité des règles applicables aux justiciables",
     ["La protection policière des tribunaux", "L'obligation de souscrire une assurance", "L'inviolabilité de toute décision de justice"],
     "Les règles doivent être claires, accessibles et stables pour que chacun puisse prévoir leurs effets.", 3),
    ("Un usage conventionnel devient-il obligatoire du seul fait qu'il est répandu dans une profession ?", "Non, il lie en principe les parties seulement si elles s'y réfèrent ou si la loi y renvoie",
     ["Oui, dès qu'il est suivi par la majorité des professionnels", "Oui, il prime toujours sur la loi", "Non, il est toujours interdit par le juge"],
     "L'usage n'a pas, par lui-même, la force obligatoire de la coutume.", 4),
    ("Quelle différence y a-t-il entre l'usage et la coutume ?", "La coutume est ressentie comme obligatoire, l'usage n'est qu'une pratique habituelle",
     ["La coutume est toujours écrite, l'usage ne l'est jamais", "L'usage est une source de l'État, la coutume non", "Il n'y en a aucune"],
     "La coutume suppose l'élément psychologique (conviction d'obligation) que l'usage n'a pas.", 3),
    ("De quels éléments se compose la coutume, selon la doctrine classique ?", "d'un élément matériel (pratique constante) et d'un élément psychologique (conviction d'obligation)",
     ["d'un vote du Parlement et d'une promulgation", "d'une décision de justice et d'une publication", "d'un traité et d'une ratification"],
     "La conviction d'obligation est souvent appelée opinio juris.", 3),
    ("Qu'est-ce que l'opinio juris ?", "La conviction que la pratique suivie est juridiquement obligatoire",
     ["Une opinion du ministère public", "Un avis consultatif de la doctrine", "Une mesure d'instruction ordonnée par le juge"],
     "C'est l'élément psychologique de la coutume.", 4),
    ("Quelle est la différence entre une coutume « praeter legem » et une coutume « contra legem » ?", "La première complète la loi silencieuse, la seconde la contredit",
     ["La première est écrite, la seconde orale", "La première est locale, la seconde nationale", "La première est pénale, la seconde civile"],
     "Praeter legem : en marge de la loi ; contra legem : contre la loi.", 5),
    ("Que désigne la coutume « secundum legem » ?", "est conforme à la loi et s'applique conformément à elle",
     ["contredit la loi en vigueur", "n'existe qu'à l'état de projet", "ne vaut que pour les étrangers"],
     "Secundum legem : conforme à la loi.", 5),
    ("Quelle est la place générale de la coutume dans un système de tradition romano-germanique ?", "Une source d'appoint, subordonnée à la loi",
     ["La source unique du droit", "Une source supérieure à la Constitution", "Une source interdite"],
     "La loi y occupe la première place ; la coutume la complète ou s'applique là où la loi la reconnaît.", 3),
    ("Au Cameroun, comment la coexistence du droit écrit et du droit coutumier peut-elle se décrire ?", "Coexistence : la coutume s'applique dans les matières et limites que la loi admet",
     ["Seul le droit coutumier est applicable", "Seul le droit écrit est applicable, la coutume est interdite", "La coutume l'emporte toujours sur la loi"],
     "L'ordre juridique camerounais conserve une place à la coutume, sous réserve de l'ordre public et des lois.", 3),
    ("Au Cameroun, une coutume contraire à l'ordre public peut-elle être appliquée par le juge ?", "En principe non, le juge l'écarte",
     ["Oui, elle prime toujours sur la loi", "Oui, si elle est plus ancienne que la loi", "Oui, si le chef traditionnel le demande"],
     "L'application de la coutume est limitée par l'ordre public.", 4),
    ("Qu'est-ce que l'ordre public ?", "L'ensemble des principes essentiels dont les particuliers ne peuvent écarter l'application",
     ["Le maintien de la paix par la seule police", "L'ordre dans lequel les affaires sont jugées", "Les règles de la hiérarchie administrative"],
     "Une convention contraire à l'ordre public est nulle.", 3),
    ("Pourquoi une convention contraire à l'ordre public ne peut-elle pas produire d'effet ?", "Parce que les particuliers ne peuvent pas déroger à ces règles essentielles",
     ["Parce qu'elle n'a pas été signée par un notaire", "Parce qu'elle n'a pas été publiée au journal officiel", "Parce qu'elle a été conclue entre étrangers"],
     "L'ordre public limite la liberté contractuelle.", 3),
    ("Que désignent les « bonnes mœurs » en droit ?", "les exigences morales fondamentales que la société juge nécessaires",
     ["les usages de la bonne société", "les règles de la politesse", "les opinions du juge"],
     "Un contrat contraire aux bonnes mœurs est sanctionné.", 4),
    ("Quelle est la différence entre règle impérative et règle supplétive pour les parties à un contrat ?", "Elles peuvent écarter la seconde, mais pas la première",
     ["Elles peuvent écarter la première, mais pas la seconde", "Elles peuvent écarter les deux", "Elles ne peuvent écarter aucune des deux"],
     "Les règles supplétives ne jouent qu'à défaut de volonté contraire.", 3),
    ("Qu'est-ce que le droit naturel dans la pensée juridique ?", "une conception d'un droit supérieur fondé sur la nature ou la raison",
     ["l'ensemble des lois sur l'environnement", "le droit en vigueur dans les États d'Afrique", "le droit des animaux seulement"],
     "Il s'oppose au positivisme, qui ne reconnaît que le droit posé par l'État.", 3),
    ("Que soutient le positivisme juridique ?", "seul le droit posé par l'autorité compétente est du droit",
     ["la seule règle de droit est la morale", "la nature impose les règles de droit", "la religion crée le droit"],
     "Le droit se définit par sa production selon les procédures de l'État.", 4),
    ("Qui est associé à la théorie de la hiérarchie des normes sous la forme d'une pyramide ?", "Hans Kelsen",
     ["Montesquieu", "Portalis", "Jean Domat"],
     "Kelsen, théoricien du normativisme, a décrit l'ordre juridique comme une hiérarchie de normes.", 4),
    ("Que signifie l'expression « ordre juridique » ?", "L'ensemble des règles de droit en vigueur dans une société déterminée",
     ["La police des audiences", "La liste des avocats", "L'ordre d'inscription des affaires au rôle"],
     "L'ordre juridique forme un système cohérent de normes.", 3),
    ("Sur quoi le droit se concentre-t-il davantage que la morale ?", "le droit se préoccupe surtout des comportements extérieurs",
     ["la morale est toujours écrite", "le droit ne vise que les intentions", "le droit n'a aucune finalité sociale"],
     "Le droit régit les comportements ; la morale s'attache davantage à l'intention.", 3),
    ("Parmi les adjectifs suivants, lequel ne caractérise pas la règle de droit ?", "facultative",
     ["générale", "obligatoire", "sanctionnée"],
     "La règle de droit est générale, abstraite, obligatoire et assortie d'une sanction.", 2),
    ("Que signifie qu'une règle de droit est « permanente » ?", "Elle vaut jusqu'à ce qu'elle soit modifiée ou abrogée",
     ["Elle ne peut jamais être modifiée", "Elle est valable un an", "Elle est appliquée chaque jour par le juge"],
     "La loi n'est pas faite pour une occasion précise.", 3),
    ("Pourquoi la sanction est-elle liée à la règle de droit ?", "Elle donne à la règle son effectivité en contraignant ou réparant",
     ["Elle sert à rendre la règle plus ancienne", "Elle empêche toute interprétation de la règle", "Elle est facultative pour le juge dans tous les cas"],
     "Sans sanction, une règle risquerait de rester lettre morte.", 3),
    ("Laquelle de ces sanctions est de nature civile ?", "L'annulation d'un contrat conclu en violation d'une règle de validité",
     ["La peine d'amende prononcée par le juge pénal", "La peine d'emprisonnement", "La confiscation prononcée à titre de peine"],
     "La nullité est une sanction civile ; les autres sont des peines pénales.", 2),
    ("Que distingue la sanction civile de la sanction pénale ?", "La première vise à rétablir ou réparer, la seconde à punir au nom de la société",
     ["La première est prononcée par l'huissier", "La seconde ne peut jamais être une amende", "La première est toujours une peine privative de liberté"],
     "La finalité de la sanction pénale est répressive.", 3),
    ("Qu'est-ce qu'une sanction disciplinaire ?", "Une sanction frappant un membre d'un corps ou d'une profession qui a manqué à ses obligations",
     ["Une sanction infligée par le juge pénal à tous les citoyens", "Une sanction réservée aux mineurs", "Une sanction exclusivement financière"],
     "Elle relève d'un ordre professionnel ou d'un employeur, selon les cas.", 3),
], cat="Notion de droit et règle de droit", src="sup-droit-intro")

# ---------------------------------------------------------------------------------------------------------------------------------
# 11. MCQ : SOURCES, HIÉRARCHIE DES NORMES, APPLICATION DE LA LOI DANS LE TEMPS
# ---------------------------------------------------------------------------------------------------------------------------------
mcq(C, "di-m-sources", [
    ("Dans la pyramide des normes, pourquoi un décret ne peut-il pas contredire une loi ?", "Parce que la loi lui est supérieure dans la hiérarchie",
     ["Parce que le décret n'est pas publié", "Parce que le décret est toujours plus ancien", "Parce que la loi est votée par référendum"],
     "Une norme inférieure doit respecter la norme supérieure.", 2),
    ("Quelle conséquence peut avoir un règlement contraire à la loi ?", "Il peut être annulé par le juge compétent",
     ["Il devient une loi", "Il est automatiquement validé", "Il s'applique seulement aux étrangers"],
     "Le contrôle de légalité des actes réglementaires assure le respect de la hiérarchie.", 3),
    ("Quelle autorité contrôle, par définition, la conformité des lois à la Constitution dans les systèmes qui ont une juridiction constitutionnelle ?", "Le juge constitutionnel",
     ["Le juge d'instruction", "Le notaire", "Le greffier en chef"],
     "Le contrôle de constitutionnalité est exercé par une juridiction ou un conseil spécialisé.", 3),
    ("Au Cameroun, quelle institution a pour mission de se prononcer sur la constitutionnalité des lois ?", "Le Conseil constitutionnel",
     ["Le Conseil des ministres", "Le tribunal de première instance", "Le Sénat seul"],
     "La Constitution de 1996 a prévu le Conseil constitutionnel, chargé notamment du contrôle de constitutionnalité.", 3),
    ("Au Cameroun, quels traités ont, sous condition de réciprocité, une autorité supérieure à celle des lois ?", "Ceux qui ont été régulièrement ratifiés ou approuvés",
     ["Les traités signés par un ministre, même sans ratification", "Aucun traité, la loi interne prime toujours", "Uniquement les traités conclus avant l'indépendance"],
     "La Constitution camerounaise donne aux traités régulièrement ratifiés une autorité supérieure à celle des lois.", 4),
    ("Qu'est-ce que le bloc de légalité ?", "L'ensemble des normes que l'administration doit respecter dans son action",
     ["Un recueil de lois d'une même année", "Un groupe de juges d'une même chambre", "L'ensemble des décisions annulées"],
     "L'administration est soumise à la Constitution, aux traités, à la loi et aux principes généraux.", 4),
    ("Quelle est la valeur de la jurisprudence dans la tradition romano-germanique, selon la conception classique ?", "Elle interprète et complète la loi, sans lier en droit les juges futurs",
     ["Elle lie obligatoirement tous les juges comme un précédent", "Elle a une valeur supérieure à la Constitution", "Elle n'existe pas"],
     "Les juges ne sont pas formellement tenus par les décisions antérieures, mais elles ont une grande autorité.", 4),
    ("Dans un système de common law, qu'appelle-t-on la règle du précédent ?", "L'obligation pour les juges de suivre les solutions déjà retenues par les juridictions supérieures",
     ["La règle selon laquelle le Parlement doit voter deux fois la loi", "L'interdiction de citer des décisions anciennes", "L'obligation d'appliquer uniquement la loi écrite"],
     "Le principe porte le nom de stare decisis dans les systèmes de common law.", 4),
    ("Quelle est la principale source de formation du droit dans les systèmes de common law traditionnels ?", "La décision de justice (le précédent)",
     ["Le Code civil", "La doctrine seule", "Le règlement intérieur de l'administration"],
     "La common law s'est construite par les décisions des juges, complétées par des lois.", 3),
    ("Qu'est-ce qui caractérise d'abord le système de droit civil (romano-germanique) ?", "La place centrale de la loi écrite et des codes",
     ["La seule autorité des précédents judiciaires", "L'absence de toute loi écrite", "La primauté de la coutume non écrite"],
     "Les systèmes de droit civil reposent sur des textes généraux, souvent codifiés.", 2),
    ("Quelle est l'origine du bijuridisme du Cameroun ?", "L'héritage laissé par la France et le Royaume-Uni, qui ont administré le territoire",
     ["Un choix récent de la Cour suprême", "L'application du seul droit coutumier", "L'adoption du droit allemand"],
     "Le Cameroun a hérité de la tradition civiliste d'inspiration française et de la common law anglaise.", 3),
    ("Au Cameroun, quelle expression désigne la coexistence de la common law et du droit civil d'inspiration française ?", "Le bijuridisme",
     ["Le dualisme monétaire", "Le bicamérisme", "La bipartition territoriale"],
     "Le bijuridisme est la cohabitation de deux systèmes juridiques dans un même État.", 2),
    ("Que désigne la « loi » au sens formel ?", "L'acte voté par le Parlement selon la procédure législative, quel que soit son contenu",
     ["Tout acte contenant une règle générale, même pris par l'exécutif", "Un jugement de la Cour suprême", "Une coutume reconnue par le juge"],
     "La loi formelle se définit par son auteur et sa procédure, non par son contenu.", 4),
    ("Que désigne la « loi » au sens matériel ?", "Tout acte contenant une règle générale et impersonnelle, quelle que soit l'autorité qui l'édicte",
     ["Seulement l'acte voté par le Parlement", "Seulement l'acte signé par le chef de l'État", "Seulement un code"],
     "La loi matérielle se définit par son contenu : générale et impersonnelle.", 5),
    ("Qu'est-ce que le domaine de la loi ?", "L'ensemble des matières que la Constitution réserve au Parlement",
     ["L'ensemble des lois d'un siècle", "Les terres appartenant à l'État", "L'ensemble des affaires jugées par la Cour suprême"],
     "La Constitution distingue le domaine de la loi et celui du règlement.", 4),
    ("Dans quel cas l'exécutif peut-il prendre une ordonnance dans le domaine de la loi ?", "Lorsque le Parlement l'a habilité à le faire pour un temps limité",
     ["Quand le juge l'y invite", "Chaque fois qu'il le juge utile, sans condition", "Quand un citoyen le lui demande"],
     "L'ordonnance suppose une habilitation par le législateur.", 4),
    ("Que peut-on dire d'une loi qui n'a pas été promulguée ni publiée ?", "Elle ne peut pas encore s'imposer aux citoyens",
     ["Elle s'applique mais seulement aux juristes", "Elle s'applique rétroactivement", "Elle est abrogée"],
     "La publication permet de présumer que les destinataires peuvent connaître la loi.", 3),
    ("Que fait l'adage « nul n'est censé ignorer la loi » ?", "Il établit une fiction : la loi publiée est présumée connue de tous",
     ["Il oblige chacun à lire tous les codes", "Il interdit toute erreur de droit au juge", "Il dispense le juge de motiver"],
     "Une fiction juridique : l'ignorance de la loi ne dispense pas de l'appliquer.", 4),
    ("Quel est le principe d'application de la loi dans le temps ?", "La loi nouvelle s'applique immédiatement pour l'avenir, sans rétroactivité",
     ["La loi nouvelle s'applique toujours aux faits passés", "La loi ancienne ne cesse jamais de s'appliquer", "La loi nouvelle s'applique après dix ans"],
     "La loi dispose pour l'avenir ; ses effets sur le passé sont exceptionnels.", 3),
    ("En matière pénale, quelle est la règle de principe pour la loi pénale plus douce ?", "Elle s'applique aux faits antérieurs qui n'ont pas encore été définitivement jugés",
     ["Elle ne s'applique jamais aux faits antérieurs", "Elle s'applique uniquement aux étrangers", "Elle exige une nouvelle plainte de la victime"],
     "La loi pénale plus douce rétroagit : c'est la règle de la rétroactivité in mitius.", 5),
    ("Quel est le sort, en principe, de la loi pénale plus sévère ?", "ne s'applique en principe qu'aux faits commis après son entrée en vigueur",
     ["s'applique à tous les faits antérieurs", "s'applique seulement aux mineurs", "n'est jamais applicable"],
     "La non-rétroactivité de la loi pénale plus sévère protège contre l'arbitraire.", 3),
    ("Qu'est-ce qu'une loi interprétative ?", "Une loi qui précise le sens d'une loi antérieure et qui est, en principe, rétroactive",
     ["Une loi votée à titre expérimental", "Une loi traduite en plusieurs langues", "Une loi qui abroge toute la matière"],
     "Elle fait corps avec la loi qu'elle interprète et s'applique donc depuis l'entrée en vigueur de celle-ci.", 5),
    ("Qu'est-ce que l'effet immédiat de la loi nouvelle ?", "Son application aux situations en cours et aux effets futurs de celles-ci",
     ["Son application aux seuls faits passés", "Son application après un délai de grâce légal", "Son application aux seuls contrats nouveaux"],
     "L'effet immédiat concerne les situations en cours, sans rétroactivité.", 5),
    ("En matière contractuelle, quelle règle de principe vaut pour un contrat conclu avant la loi nouvelle ?", "Il reste en principe régi par la loi en vigueur au moment de sa conclusion",
     ["Il est automatiquement annulé", "Il est régi par la loi de l'année suivante", "Il est interprété par le notaire"],
     "La survie de la loi ancienne protège la prévisibilité des contrats.", 5),
    ("Que signifie « abroger » une loi ?", "Y mettre fin pour l'avenir par un acte postérieur de même niveau ou supérieur",
     ["La rendre rétroactive", "La traduire dans une autre langue", "La publier au journal officiel"],
     "L'abrogation est expresse ou tacite, et ne vaut que pour l'avenir.", 3),
    ("Que se passe-t-il lorsqu'une loi nouvelle est incompatible avec une loi plus ancienne sans la mentionner ?", "L'ancienne est abrogée tacitement dans la mesure de l'incompatibilité",
     ["Elles restent applicables avec un contenu identique", "La nouvelle est automatiquement annulée", "Le juge doit attendre un nouveau vote"],
     "Lex posterior derogat priori : la loi postérieure l'emporte, à égalité de niveau.", 4),
    ("Que dit la règle « lex posterior derogat priori » ?", "La loi postérieure l'emporte sur la loi antérieure de même rang",
     ["La loi antérieure l'emporte toujours", "La loi étrangère l'emporte sur la loi nationale", "La loi spéciale l'emporte sur la Constitution"],
     "Elle règle les conflits de lois dans le temps entre normes de même niveau.", 3),
    ("Qu'est-ce que la « désuétude » d'une loi ?", "Le fait qu'elle cesse d'être appliquée en pratique sans avoir été formellement abrogée",
     ["Son abrogation expresse", "Sa promulgation tardive", "Sa traduction"],
     "En principe, la désuétude ne suffit pas à l'abroger dans un système de droit écrit.", 5),
    ("Quelle différence y a-t-il entre l'abrogation et l'annulation d'un acte ?", "L'abrogation vaut pour l'avenir, l'annulation efface en principe l'acte rétroactivement",
     ["L'abrogation efface l'acte rétroactivement, l'annulation vaut pour l'avenir", "Aucune différence", "L'abrogation concerne les contrats, l'annulation les lois"],
     "L'annulation fait disparaître l'acte dès l'origine ; l'abrogation y met fin pour l'avenir.", 4),
    ("Que signifie la territorialité de la loi ?", "La loi s'applique à toutes les personnes et situations sur le territoire de l'État",
     ["La loi ne s'applique qu'aux nationaux, où qu'ils soient", "La loi ne s'applique qu'aux étrangers", "La loi ne s'applique qu'au chef-lieu"],
     "Le principe de territorialité est la règle de base en droit pénal et en droit public.", 3),
    ("Que signifie la personnalité des lois ?", "La loi suit la personne, notamment à raison de sa nationalité, même à l'étranger",
     ["La loi ne s'applique qu'aux personnes morales", "La loi s'applique à une personne nommée", "La loi ne concerne que les juges"],
     "Elle s'oppose à la territorialité.", 4),
    ("Que recouvre, en droit international privé, le « statut personnel » ?", "Les règles relatives à l'état et à la capacité des personnes et à leur famille",
     ["Les règles relatives à la propriété immobilière", "Les règles relatives aux impôts", "Les règles relatives aux marchés publics"],
     "Le statut personnel est rattaché, selon les pays, à la nationalité ou au domicile.", 4),
    ("Que traite le droit international privé ?", "Les rapports de droit privé comportant un élément d'extranéité",
     ["Les rapports entre États seulement", "Les crimes de guerre", "Les marchés publics nationaux"],
     "Il détermine notamment la loi applicable et le juge compétent dans les situations internationales.", 3),
    ("Qu'est-ce que le droit international public ?", "Le droit qui régit principalement les relations entre États et organisations internationales",
     ["Le droit qui régit les contrats entre particuliers étrangers", "Le droit qui régit le commerce de détail", "Le droit des sociétés étrangères"],
     "Il a pour sujets principaux les États et les organisations internationales.", 2),
], cat="Sources et hiérarchie des normes", src="sup-droit-intro")

# ---------------------------------------------------------------------------------------------------------------------------------
# 12. MCQ : BRANCHES, DROIT PUBLIC / PRIVÉ, CLASSIFICATION DES DROITS
# ---------------------------------------------------------------------------------------------------------------------------------
mcq(C, "di-m-branches", [
    ("Quel critère est classiquement utilisé pour distinguer le droit public du droit privé ?", "La présence de la puissance publique ou de l'intérêt général dans le rapport régi",
     ["La longueur des textes applicables", "L'ancienneté des règles", "Le nombre de parties au procès"],
     "Le droit public régit l'État et les personnes publiques ; le droit privé les rapports entre particuliers.", 3),
    ("Que régit principalement le droit commercial ?", "les commerçants, les actes de commerce et les sociétés commerciales",
     ["les rapports entre l'État et les citoyens", "les infractions graves", "l'organisation des élections"],
     "C'est une branche du droit privé qui régit les activités commerciales.", 2),
    ("Quels rapports le droit du travail régit-il principalement ?", "les rapports entre employeurs et salariés",
     ["les rapports entre États", "les règles de nationalité", "les rapports entre époux"],
     "Il est une branche du droit privé, avec une forte part de règles protectrices.", 2),
    ("Quel est l'objet du droit pénal ?", "définir les infractions et fixer les peines qui leur sont applicables",
     ["réparer tout préjudice par la seule volonté des parties", "organiser l'état civil", "fixer les règles de la propriété"],
     "Le droit pénal est l'ensemble des règles qui définissent et répriment les infractions.", 2),
    ("Que régit principalement le droit administratif ?", "l'organisation de l'administration, ses activités et ses rapports avec les administrés",
     ["les contrats entre particuliers", "les règles de succession", "la hiérarchie entre époux"],
     "C'est une branche du droit public.", 2),
    ("Quel est l'objet du droit fiscal ?", "les règles relatives aux impôts et à leur recouvrement",
     ["les règles relatives aux élections", "les règles relatives aux contrats de travail", "les règles relatives au nom des personnes"],
     "Il est généralement rattaché au droit public financier.", 2),
    ("Qu'est-ce que le droit civil ?", "Le droit commun du droit privé, qui régit les personnes, la famille, les biens et les obligations",
     ["Le droit propre aux fonctionnaires", "Le droit de la guerre", "Le droit des sociétés commerciales seulement"],
     "Le droit civil est la branche centrale du droit privé.", 2),
    ("Que signifie le « droit des affaires » ?", "L'ensemble des règles applicables aux activités économiques et commerciales",
     ["L'ensemble des règles applicables aux affaires de famille", "L'ensemble des règles de procédure pénale", "L'ensemble des règles de l'état civil"],
     "Le droit des affaires regroupe droit commercial, des sociétés, des sûretés et des procédures collectives, notamment.", 3),
    ("Que règle le droit judiciaire privé ?", "L'organisation des juridictions civiles et la procédure applicable aux litiges privés",
     ["Les impôts des particuliers", "Le statut des fonctionnaires", "Les règles de la guerre"],
     "On parle aussi de procédure civile.", 3),
    ("À quelle branche appartient le droit de la famille ?", "au droit civil, branche du droit privé",
     ["au droit fiscal", "au droit pénal exclusivement", "au droit international public"],
     "Il régit mariage, filiation, autorité parentale, notamment.", 1),
    ("Quelle branche régit le fonctionnement des institutions politiques et les rapports entre les pouvoirs publics ?", "Le droit constitutionnel",
     ["Le droit du travail", "Le droit commercial", "Le droit des biens"],
     "Le droit constitutionnel est le droit de l'organisation de l'État.", 1),
    ("À quoi sert le droit international privé pour un litige entre un Camerounais et un étranger ?", "À déterminer la loi applicable et la juridiction compétente",
     ["À remplacer tout contrat par un traité", "À fixer le montant de la peine", "À supprimer la compétence des tribunaux nationaux"],
     "Il traite des conflits de lois et de juridictions.", 4),
    ("Que désigne le droit processuel ?", "l'ensemble des règles de procédure applicables devant les juridictions",
     ["l'ensemble des règles sur les successions", "l'ensemble des règles de la propriété intellectuelle", "l'ensemble des règles sur l'état civil"],
     "Il regroupe les règles de procédure civile, pénale et administrative.", 4),
    ("Quelle est la différence entre droit commun et droit spécial ?", "Le droit commun pose les règles générales, le droit spécial des règles propres à une matière",
     ["Le droit spécial s'applique à tous, le commun à quelques-uns", "Le droit commun est toujours coutumier", "Le droit spécial est toujours international"],
     "Le droit spécial l'emporte sur le droit commun dans son domaine : specialia generalibus derogant.", 3),
    ("Quelle branche du droit est parfois qualifiée de droit commun du droit privé ?", "Le droit civil",
     ["Le droit des assurances", "Le droit maritime", "Le droit des brevets"],
     "Les règles générales du droit civil s'appliquent à défaut de règle spéciale.", 2),
    ("De quel droit relève un contrat de vente conclu entre deux particuliers ?", "du droit privé",
     ["du droit public", "du droit constitutionnel", "du droit fiscal international"],
     "C'est un rapport entre personnes privées.", 1),
    ("De quel droit relève le recours d'un citoyen contre une décision d'un maire ?", "du droit public (droit administratif)",
     ["du droit de la famille", "du droit des successions", "du droit commercial"],
     "La décision d'une autorité administrative est contrôlée par le juge administratif.", 2),
    ("De quelle branche du droit relève un licenciement contesté devant une juridiction ?", "droit du travail",
     ["droit constitutionnel", "droit fiscal", "droit international public"],
     "Le contrat de travail et sa rupture sont régis par le droit du travail.", 1),
    ("Laquelle de ces sources relève du droit international public ?", "Une convention conclue entre États",
     ["Un règlement d'une société", "Un contrat de bail", "Un testament"],
     "Les conventions entre États sont des traités.", 2),
    ("Qu'est-ce qu'un acte juridique ?", "Une manifestation de volonté destinée à produire des effets de droit",
     ["Un événement matériel qui produit des effets de droit", "Un acte accompli par un juge", "Un acte réalisé dans un lieu public"],
     "Le contrat et le testament sont des actes juridiques.", 2),
    ("Qu'est-ce qu'un fait juridique ?", "Un événement, volontaire ou non, auquel la loi attache des effets de droit",
     ["Une manifestation de volonté destinée à créer des droits", "Une règle votée par le Parlement", "Une décision du ministère public"],
     "La naissance, la mort ou un accident sont des faits juridiques.", 2),
    ("Lequel de ces événements est un fait juridique ?", "Un accident de la circulation causant un dommage",
     ["La signature d'un contrat de bail", "La rédaction d'un testament", "La conclusion d'un mariage devant l'officier d'état civil"],
     "L'accident est un fait ; les autres sont des actes juridiques.", 2),
    ("Lequel de ces éléments est un acte juridique ?", "Un testament",
     ["Un décès", "Une naissance", "Un incendie accidentel"],
     "Le testament est une manifestation de volonté destinée à produire des effets.", 2),
    ("Quelle est la différence essentielle entre un acte juridique et un fait juridique quant à la preuve ?", "En principe l'acte exige un écrit au-delà d'un certain seuil, le fait se prouve librement",
     ["L'acte se prouve par tous moyens, le fait seulement par écrit", "Le fait exige toujours un notaire", "Ils se prouvent exactement de la même manière"],
     "La preuve d'un fait juridique est libre ; celle d'un acte est plus formaliste, notamment en matière civile.", 4),
    ("De quoi résulte un acte juridique unilatéral ?", "de la volonté d'une seule personne",
     ["de la volonté de deux personnes au moins", "d'une décision de justice", "d'un fait de la nature"],
     "Le testament est un acte unilatéral ; le contrat un acte bilatéral ou multilatéral.", 3),
    ("Quelle est la nature de l'acte juridique qu'est le contrat ?", "conventionnel, qui suppose l'accord de deux ou plusieurs volontés",
     ["unilatéral par nature", "toujours gratuit", "toujours verbal"],
     "Le contrat est un accord de volontés destiné à créer des obligations.", 2),
    ("Dans quel cas un acte est-il dit « à titre gratuit » ?", "Lorsqu'une partie procure un avantage à l'autre sans contrepartie",
     ["Lorsque chaque partie reçoit un avantage équivalent", "Lorsqu'il est établi sans notaire", "Lorsqu'il est écrit à la main"],
     "La donation est un acte à titre gratuit ; la vente un acte à titre onéreux.", 2),
    ("Lequel de ces actes est un acte à titre onéreux ?", "Un contrat de vente",
     ["Une donation", "Un legs", "Un prêt consenti sans intérêt à un ami"],
     "Chaque partie obtient une contrepartie de l'autre.", 2),
    ("Qu'est-ce qu'un droit patrimonial ?", "Un droit évaluable en argent, qui entre dans le patrimoine",
     ["Un droit attaché à l'état de la personne et sans valeur pécuniaire", "Un droit qui ne concerne que les successions", "Un droit exclusif de l'État"],
     "Les droits réels, personnels et intellectuels sont patrimoniaux.", 2),
    ("Qu'est-ce qu'un droit extrapatrimonial ?", "Un droit hors du patrimoine, non évaluable en argent, attaché à la personne",
     ["Un droit sur un immeuble situé à l'étranger", "Un droit de créance à long terme", "Un droit consacré par un contrat"],
     "Les droits de la personnalité et certains droits de famille sont extrapatrimoniaux.", 3),
    ("Quelle est la principale caractéristique d'un droit réel ?", "Il porte directement sur une chose, sans intermédiaire",
     ["Il oblige une personne à une prestation", "Il est toujours temporaire", "Il ne peut pas être transmis"],
     "Le titulaire d'un droit réel exerce son pouvoir immédiatement sur la chose.", 3),
    ("Quelle est la principale caractéristique d'un droit personnel ?", "Il confère à son titulaire un pouvoir sur une personne, le débiteur",
     ["Il porte directement sur une chose", "Il est opposable à tous sans exception", "Il s'éteint à la mort du créancier toujours"],
     "Le créancier ne peut agir que contre son débiteur.", 3),
    ("Que permet le droit de suite, attribut du droit réel ?", "au titulaire de suivre la chose entre les mains de tout détenteur",
     ["de poursuivre le débiteur en dehors de son domicile", "de suivre une affaire d'une juridiction à l'autre", "d'exiger la prolongation d'un contrat"],
     "Le droit de suite est l'une des prérogatives du droit réel.", 4),
    ("Que permet le droit de préférence, attribut de certains droits réels accessoires ?", "au titulaire d'être payé avant les autres créanciers sur le prix du bien",
     ["de choisir son débiteur", "de préférer une juridiction", "d'écarter toute prescription"],
     "Le titulaire d'une sûreté réelle (comme l'hypothèque) est payé par préférence.", 5),
    ("De quelle nature est le droit que le bail confère au locataire ?", "personnel, de créance contre le bailleur",
     ["réel de propriété", "de la personnalité", "intellectuel"],
     "Le locataire est créancier de la jouissance de la chose ; la chose appartient au bailleur.", 4),
    ("Que protège le droit d'auteur ?", "Les œuvres de l'esprit originales",
     ["Les inventions techniques brevetables", "Les signes distinctifs d'un commerçant", "Les droits des héritiers"],
     "Le droit d'auteur protège les créations originales (littéraires, artistiques…).", 2),
    ("Quel est l'objet d'une marque ?", "Distinguer les produits ou services d'une entreprise de ceux de ses concurrents",
     ["Protéger une œuvre littéraire", "Désigner un lieu de naissance", "Authentifier un acte notarié"],
     "La marque est un signe distinctif de propriété industrielle.", 3),
    ("À quoi sert un brevet d'invention ?", "À protéger une invention nouvelle par un monopole d'exploitation temporaire",
     ["À protéger une œuvre musicale", "À constater un décès", "À fixer le nom d'un enfant"],
     "Le brevet est un titre de propriété industrielle d'une durée limitée.", 3),
    ("Parmi ces droits, lequel est un droit réel accessoire ?", "L'hypothèque",
     ["L'usufruit", "La propriété", "La servitude"],
     "L'hypothèque garantit une créance : elle est dite accessoire. L'usufruit, la propriété et la servitude sont des droits réels principaux.", 4),
    ("Qu'est-ce qu'un droit réel principal ?", "Un droit réel qui existe par lui-même, comme la propriété ou l'usufruit",
     ["Un droit qui garantit une créance", "Un droit propre à l'État", "Un droit éteint par la naissance de l'enfant"],
     "Par contraste, le droit réel accessoire garantit une créance.", 4),
    ("Qu'est-ce qu'un droit potestatif ?", "un droit permettant de modifier une situation juridique par sa seule volonté",
     ["un droit qui exige l'accord de toutes les parties", "un droit sans aucune sanction", "un droit réservé aux autorités"],
     "Exemple : le droit de résilier un contrat à durée indéterminée ou de révoquer un mandat.", 5),
    ("Qu'est-ce qu'une créance ?", "le droit pour une personne d'exiger une prestation d'une autre",
     ["le droit d'exiger la propriété d'une chose", "le droit d'être jugé", "le droit à un nom"],
     "Le créancier peut exiger du débiteur l'exécution de l'obligation.", 2),
    ("Que comprend le patrimoine d'une personne ?", "l'actif et le passif, c'est-à-dire ses droits et ses dettes",
     ["ses seuls droits réels", "ses seuls droits extrapatrimoniaux", "ses seuls biens immeubles"],
     "Le patrimoine est une universalité de droits et d'obligations évaluables en argent.", 3),
    ("Selon la théorie classique, combien de patrimoines une personne peut-elle avoir ?", "Un seul, qui est indivisible et attaché à la personne",
     ["Un par bien possédé", "Un par membre de la famille", "Un seul, mais détenu par l'État"],
     "La théorie classique d'Aubry et Rau repose sur l'unité et l'indivisibilité du patrimoine.", 5),
    ("Quel est le principe de la responsabilité civile de droit commun ?", "Celui qui cause un dommage à autrui par sa faute doit le réparer",
     ["Toute personne est responsable de tout dommage, même sans lien avec elle", "Seule l'administration répond des dommages", "Le dommage est toujours supporté par la victime"],
     "La faute, le dommage et le lien de causalité fondent la responsabilité civile délictuelle.", 3),
], cat="Branches du droit et classification des droits", src="sup-droit-intro")

# ---------------------------------------------------------------------------------------------------------------------------------
# 13. MCQ : PREUVE
# ---------------------------------------------------------------------------------------------------------------------------------
mcq(C, "di-m-preuve", [
    ("Que signifie l'adage « actori incumbit probatio » ?", "La preuve incombe à celui qui allègue un fait",
     ["Le juge doit prouver ce qu'il décide", "Le défendeur doit toujours prouver son innocence", "Le témoin doit prouver sa bonne foi"],
     "Le demandeur doit établir le fondement de sa prétention.", 3),
    ("Selon le principe général, que doit faire le défendeur qui oppose une exception à la demande ?", "Prouver les faits qui fondent son exception",
     ["Rien, jamais", "S'en remettre au greffier", "Solliciter l'avis de la doctrine"],
     "« Reus in excipiendo fit actor » : le défendeur qui invoque un fait nouveau doit le prouver.", 5),
    ("Qu'est-ce que l'office du juge en matière de preuve en procédure civile ?", "Apprécier les preuves des parties et, au besoin, ordonner des mesures d'instruction",
     ["Rechercher seul tous les faits de l'affaire", "Remplacer les parties dans la charge de la preuve", "Ne jamais examiner les preuves"],
     "Le juge tranche selon les preuves ; il peut compléter l'instruction.", 4),
    ("Quel acte a, en principe, une force probante particulière du fait de l'intervention d'un officier public ?", "L'acte authentique",
     ["L'acte sous seing privé", "La lettre missive", "Le témoignage d'un voisin"],
     "L'acte authentique fait foi jusqu'à inscription de faux de ce que l'officier public a personnellement constaté.", 3),
    ("Comment peut-on contester les constatations personnelles de l'officier public dans un acte authentique ?", "Par une procédure d'inscription de faux",
     ["Par un simple témoignage", "Par une simple déclaration orale", "Par un simple courrier au notaire"],
     "L'acte authentique fait foi jusqu'à inscription de faux.", 5),
    ("Que doit comporter un acte sous seing privé pour valoir comme preuve ?", "La signature des personnes qui s'obligent",
     ["Le sceau de l'État", "L'intervention d'un huissier", "La présence d'un notaire"],
     "La signature est essentielle à l'acte sous seing privé.", 3),
    ("À l'égard des tiers, quand la date d'un acte sous seing privé leur devient-elle opposable ?", "Lorsqu'elle est rendue certaine par une formalité, comme l'enregistrement",
     ["Dès que les parties l'ont signé, sans aucune formalité", "Jamais, car la date n'a aucun effet juridique", "Seulement quand le juge la fixe d'office dans tous les cas"],
     "La date certaine protège les tiers contre les antidates.", 5),
    ("Qu'est-ce que la « date certaine » ?", "Une date que les tiers ne peuvent pas contester parce qu'elle résulte d'une formalité",
     ["La date du dernier jour de l'année", "La date de naissance du signataire", "La date d'un jour férié"],
     "Elle est fixée notamment par l'enregistrement de l'acte.", 5),
    ("Pour prouver un acte juridique d'une certaine importance, quelle règle de principe pose le droit civil de tradition française ?", "Il faut en principe un écrit, la preuve par témoignage seul étant écartée",
     ["La preuve par tous moyens est toujours admise", "La preuve par témoin est obligatoire", "Seule la preuve par expertise est possible"],
     "Le seuil est fixé par la loi de chaque pays ; la règle d'une preuve écrite en matière d'actes est classique.", 4),
    ("Quelle exception à l'exigence d'un écrit existe en matière commerciale ?", "La preuve est libre entre commerçants pour les actes de commerce",
     ["Un écrit notarié est toujours obligatoire", "Seul un aveu est recevable", "Seul un serment est recevable"],
     "Le principe de la liberté de la preuve en matière commerciale facilite les affaires.", 3),
    ("Dans quelle matière la preuve est-elle, en principe, libre ?", "En matière pénale, où les faits peuvent être prouvés par tous moyens",
     ["En matière de ventes immobilières seulement", "En matière d'état civil seulement", "En aucune matière"],
     "Le juge pénal forme sa conviction à partir de tous les éléments légalement obtenus.", 3),
    ("Qu'est-ce que le principe de loyauté de la preuve ?", "Les preuves doivent être obtenues sans fraude ni violence ni stratagème déloyal",
     ["Les preuves doivent toujours être écrites", "Les preuves doivent être apportées par le juge", "Les preuves doivent être gratuites"],
     "Un moyen de preuve obtenu par un procédé déloyal peut être écarté.", 4),
    ("À quoi sert une présomption légale ?", "À dispenser celui qu'elle favorise de prouver le fait présumé",
     ["À interdire de prouver quoi que ce soit", "À remplacer le juge", "À fixer la peine"],
     "Elle déplace l'objet de la preuve.", 3),
    ("Que signifie la règle « pater is est quem nuptiae demonstrant » ?", "Le père de l'enfant est le mari de la mère",
     ["Le mari est toujours le tuteur", "La mère est toujours inconnue", "L'enfant est toujours majeur"],
     "C'est une présomption de paternité attachée au mariage.", 4),
    ("Que signifie le caractère irréfragable d'une présomption ?", "ne peut pas être détruite par la preuve contraire",
     ["peut être détruite par tout moyen", "ne vaut qu'en matière pénale", "n'est valable que devant le juge de l'exécution"],
     "À l'inverse, la présomption simple admet la preuve contraire.", 4),
    ("Qu'est-ce que l'autorité de la chose jugée comme présomption ?", "La décision définitive est tenue pour la vérité entre les parties sur ce qu'elle a tranché",
     ["La décision peut toujours être remise en cause", "La décision n'est valable que si elle est unanime", "La décision n'engage que le juge"],
     "Elle fait obstacle à ce que le litige soit rejugé entre les mêmes parties pour la même cause.", 4),
    ("En droit civil, que vaut l'aveu extrajudiciaire ?", "Il est apprécié par le juge, alors que l'aveu judiciaire a en principe force irrévocable",
     ["Il n'a jamais aucune valeur", "Il est plus fort que l'aveu judiciaire", "Il engage seulement l'huissier"],
     "L'aveu judiciaire est fait devant le juge ; l'extrajudiciaire est laissé à son appréciation.", 5),
    ("Qu'est-ce qu'une fiction juridique ?", "Un procédé qui tient pour vrai un fait que l'on sait faux, pour atteindre un résultat juridique",
     ["Une fausse déclaration punie par la loi", "Un roman publié par un juriste", "Un acte rédigé en secret"],
     "Exemple : l'enfant simplement conçu est réputé né quand son intérêt l'exige.", 5),
    ("Quelle différence y a-t-il entre une fiction et une présomption ?", "La fiction tient pour vrai ce qu'on sait faux, la présomption déduit le probable d'un fait connu",
     ["La fiction est écrite, la présomption orale", "La fiction est pénale, la présomption civile", "Il n'y en a aucune"],
     "La présomption est fondée sur la vraisemblance ; la fiction ignore volontairement la réalité.", 5),
    ("Qu'est-ce que la preuve par témoignage ?", "La preuve par la déclaration de personnes qui ont connaissance personnelle des faits",
     ["La preuve par l'avis d'un technicien", "La preuve par l'aveu écrit", "La preuve par une copie de loi"],
     "Le témoin rapporte ce qu'il a perçu.", 2),
    ("Que doit faire un témoin entendu en justice ?", "Dire la vérité et prêter serment si la loi le prévoit",
     ["de ne répondre qu'au procureur", "de ne parler que par écrit", "de choisir la partie qu'il soutient"],
     "Le faux témoignage est sanctionné pénalement.", 3),
    ("Qui désigne en principe l'expert chargé d'une expertise judiciaire ?", "Le juge qui ordonne la mesure d'instruction",
     ["L'huissier de justice", "Le greffier", "Le bâtonnier"],
     "L'expert est un technicien choisi par le juge pour l'éclairer.", 3),
    ("Que vaut l'avis de l'expert pour le juge ?", "Il l'éclaire mais ne le lie pas",
     ["Il le lie toujours", "Il vaut jugement", "Il remplace le ministère public"],
     "Le juge reste maître de la décision.", 3),
    ("Qu'appelle-t-on « inscription de faux » ?", "La procédure pour contester l'authenticité ou la sincérité d'un acte authentique ou d'un écrit",
     ["La procédure d'immatriculation d'une société", "La procédure d'inscription d'une hypothèque", "La procédure de consignation d'un témoin"],
     "Elle vise à faire déclarer un écrit faux.", 5),
    ("Qu'est-ce qu'un constat d'huissier ?", "Un acte par lequel l'huissier relate des constatations purement matérielles",
     ["Un jugement rendu par l'huissier", "Un avis sur le fond de l'affaire", "Un contrat de bail"],
     "L'huissier constate sans apprécier ni donner d'avis sur les conséquences juridiques.", 3),
    ("Que signifie la règle « testis unus, testis nullus » ?", "Un seul témoin ne suffit pas pour établir un fait",
     ["Un témoin est toujours suffisant", "Le témoin est dispensé de serment", "Le témoin doit être l'huissier"],
     "C'est une règle ancienne de preuve légale, aujourd'hui souvent relativisée.", 5),
    ("Qu'est-ce que le serment supplétoire ?", "Un serment déféré d'office par le juge à l'une des parties pour compléter sa conviction",
     ["Un serment prêté seulement par l'huissier", "Un serment déféré par le greffier", "Un serment sans effet"],
     "Il est déféré par le juge, alors que le décisoire l'est par une partie à l'autre.", 5),
], cat="La preuve", src="sup-droit-intro")

# ---------------------------------------------------------------------------------------------------------------------------------
# 14. MCQ : PERSONNES PHYSIQUES ET MORALES
# ---------------------------------------------------------------------------------------------------------------------------------
mcq(C, "di-m-personnes", [
    ("Qu'est-ce que la personnalité juridique ?", "L'aptitude à être titulaire de droits et d'obligations",
     ["L'aptitude à voter des lois", "La capacité à juger les litiges", "Le caractère d'une personne"],
     "Elle est reconnue aux personnes physiques et aux personnes morales.", 2),
    ("Qui possède la personnalité juridique ?", "Les personnes physiques et les personnes morales",
     ["Les seuls adultes", "Les seuls nationaux", "Les seuls commerçants"],
     "Tout être humain, et les groupements auxquels la loi l'attribue.", 1),
    ("Les animaux ont-ils la personnalité juridique en droit civil classique ?", "Non, ce sont des biens ou des êtres protégés par des lois spéciales",
     ["Oui, comme les mineurs", "Oui, comme les sociétés", "Oui, dès leur naissance"],
     "La personnalité juridique est réservée aux personnes physiques et morales ; les animaux sont l'objet de protections.", 3),
    ("Un enfant né sans vie a-t-il la personnalité juridique ?", "Non, elle suppose en principe de naître vivant",
     ["Oui, depuis sa conception", "Oui, mais seulement s'il est reconnu", "Oui, s'il a un nom"],
     "La naissance vivante et viable est la condition classique pour acquérir la personnalité.", 4),
    ("Que signifie l'adage « infans conceptus pro nato habetur » dans son application ?", "L'enfant conçu peut hériter ou recevoir une libéralité s'il naît vivant et viable",
     ["Un enfant peut être jugé avant sa naissance", "Un enfant conçu est majeur", "Un enfant n'a droit à aucun nom"],
     "Il s'applique chaque fois que l'intérêt de l'enfant le demande, à condition qu'il naisse viable.", 5),
    ("Que signifie qu'une personne est « incapable » en droit ?", "Elle ne peut pas exercer seule certains de ses droits",
     ["Elle n'a aucun droit", "Elle ne peut pas être poursuivie", "Elle ne vit plus en société"],
     "L'incapacité d'exercice est une mesure de protection, non une absence de droits.", 2),
    ("Quelle est la règle de principe quant à la capacité ?", "La capacité est la règle et l'incapacité l'exception",
     ["L'incapacité est la règle", "Seuls les nationaux sont capables", "La capacité n'existe qu'après le mariage"],
     "Toute personne est capable, sauf si la loi en dispose autrement.", 3),
    ("Qui est incapable d'exercice en raison de son âge ?", "Le mineur non émancipé",
     ["Le chef de famille", "Le commerçant", "Le fonctionnaire"],
     "Le mineur est protégé : il est représenté pour les actes importants.", 1),
    ("Qu'est-ce qu'une incapacité de jouissance ?", "l'impossibilité d'être titulaire de certains droits",
     ["l'impossibilité d'exercer ses droits soi-même", "l'impossibilité d'agir en justice contre l'État", "l'impossibilité de changer de nom"],
     "Elle est rare et exceptionnelle ; l'incapacité d'exercice est la règle pour les mineurs.", 3),
    ("Quelle est la sanction typique d'un acte accompli par un incapable sans respecter les règles de protection ?", "La nullité de l'acte, relative et invocable par le protégé",
     ["Une peine de prison pour l'incapable", "La confiscation immédiate de l'acte", "La disparition du patrimoine du tiers"],
     "La nullité relative protège la personne incapable.", 4),
    ("Comment un mineur est-il, en principe, protégé dans les actes de la vie juridique ?", "Par la représentation de ses parents ou de son tuteur",
     ["Par l'interdiction de vivre en société", "Par la mise sous scellés de ses biens", "Par la perte automatique de son nom"],
     "L'administration légale ou la tutelle organise la représentation.", 2),
    ("Quelle est la différence entre représentation et assistance ?", "Le représentant agit à la place de l'incapable, l'assistant l'accompagne et l'autorise à agir",
     ["Le représentant est un juge, l'assistant un huissier", "L'assistance est pénale, la représentation civile", "Il n'y en a aucune"],
     "La tutelle est un régime de représentation, la curatelle un régime d'assistance.", 4),
    ("Dans quel cas la tutelle d'un mineur est-elle en principe ouverte ?", "lorsque les père et mère sont décédés ou privés de l'autorité parentale",
     ["dès la naissance de l'enfant", "à la demande du directeur d'école", "après la majorité de l'enfant"],
     "La tutelle remplace l'autorité parentale défaillante.", 3),
    ("Quel est le rôle du tuteur ?", "Représenter la personne protégée et gérer ses biens en bon administrateur",
     ["Juger les litiges de la personne protégée", "Percevoir les revenus pour lui-même", "Décider à sa place de tous ses choix personnels"],
     "Le tuteur agit dans l'intérêt du protégé et sous contrôle.", 2),
    ("Quelle est la finalité des régimes de protection des majeurs ?", "Protéger les personnes dont les facultés personnelles sont altérées",
     ["Punir les personnes âgées", "Priver certaines personnes de leurs droits civiques", "Réduire leur patrimoine"],
     "Le juge ordonne la mesure en fonction de l'altération constatée.", 3),
    ("Qui peut généralement prononcer l'ouverture d'une mesure de protection d'un majeur ?", "Le juge, au vu de l'altération de ses facultés",
     ["L'officier d'état civil", "L'huissier de justice", "Le conseil de quartier"],
     "Les mesures de protection sont prononcées par décision de justice.", 3),
    ("En quoi consiste l'émancipation d'un mineur ?", "Elle lui confère la capacité d'exercice dans les conditions que la loi fixe",
     ["Elle le rend majeur pour tout, sans exception", "Elle supprime son nom", "Elle le prive de tout droit"],
     "L'émancipation met fin à l'incapacité du mineur, avec parfois des limites.", 3),
    ("Quelle est la nature du nom de famille, en principe ?", "un attribut de la personne, transmis par la filiation",
     ["un bien librement négociable", "une marque protégée", "un droit réel"],
     "Le nom est attaché à l'état de la personne.", 3),
    ("Que signifie le principe d'immutabilité du nom ?", "le nom ne peut en principe être changé qu'à travers une procédure légale",
     ["le nom ne peut jamais être changé", "le nom est librement modifiable par déclaration", "le nom disparaît à la majorité"],
     "Le changement de nom est encadré par la loi et soumis à l'autorité.", 4),
    ("Un nom est-il cessible comme un bien ?", "Non, le nom est indisponible",
     ["Oui, par acte notarié", "Oui, à titre onéreux seulement", "Oui, avec l'accord de l'État seul"],
     "Le nom n'est pas dans le commerce : il est indisponible.", 4),
    ("Qu'est-ce que le domicile d'une personne physique, en principe ?", "le lieu de son principal établissement",
     ["le lieu de sa naissance", "le lieu de travail uniquement", "le lieu de sa dernière vacance"],
     "Le domicile s'apprécie selon le centre des intérêts de la personne.", 2),
    ("Quelle est la différence entre domicile et résidence ?", "Le domicile est le principal établissement, la résidence le lieu de vie effectif, même provisoire",
     ["Ils sont toujours identiques", "La résidence est le lieu de naissance", "Le domicile est le lieu de travail seul"],
     "On peut avoir plusieurs résidences, mais un seul domicile, en principe.", 3),
    ("Quel est l'intérêt du domicile en procédure ?", "Il détermine souvent le tribunal territorialement compétent",
     ["Il détermine la nationalité", "Il détermine la peine", "Il détermine le prix des actes"],
     "En principe, le défendeur est assigné devant la juridiction de son domicile.", 3),
    ("Quel est le domicile d'un mineur non émancipé, en principe ?", "Celui de ses parents ou de son tuteur",
     ["Celui de son école", "Celui qu'il choisit seul", "Celui de son voisin"],
     "C'est un domicile légal.", 3),
    ("Qu'est-ce que le domicile élu ?", "Le domicile choisi par les parties pour l'exécution d'un acte ou d'une procédure",
     ["Le domicile attribué par les parents", "Le domicile du mineur", "Le lieu de naissance de l'élu"],
     "Il se distingue du domicile réel.", 4),
    ("Qu'est-ce que le domicile légal ?", "Un domicile fixé par la loi pour certaines catégories de personnes",
     ["Le domicile d'une personne morale seulement", "Un domicile choisi librement", "Un domicile sans valeur"],
     "Exemples classiques : celui du mineur ou du majeur protégé.", 4),
    ("À quoi sert l'état civil ?", "À constater officiellement la naissance, le mariage, le décès et les autres faits d'état",
     ["À fixer l'impôt sur le revenu", "À juger les litiges de voisinage", "À attribuer les terrains publics"],
     "Les actes d'état civil prouvent l'identité et la situation familiale.", 2),
    ("Quelle autorité reçoit en principe les déclarations de naissance ?", "L'officier d'état civil",
     ["Le préfet", "Le greffier du tribunal de commerce", "Le notaire"],
     "L'officier d'état civil dresse les actes de naissance, de mariage et de décès.", 2),
    ("Qu'est-ce qu'une mention marginale dans un acte d'état civil ?", "Une indication portée en marge de l'acte pour signaler un événement ultérieur",
     ["Un commentaire du juge", "Un impôt prélevé sur l'acte", "Une traduction de l'acte"],
     "Exemple : la mention du mariage ou du divorce en marge de l'acte de naissance.", 4),
    ("Au Cameroun, quelle décision judiciaire peut suppléer l'acte de naissance lorsque la naissance n'a pas été déclarée dans le délai ?", "Le jugement supplétif d'acte de naissance",
     ["Un arrêt de la Cour suprême", "Un arrêté du préfet", "Un décret du président"],
     "Le juge ordonne l'établissement de l'acte par jugement supplétif, procédure courante au Cameroun.", 4),
    ("Qu'est-ce que le droit à l'image ?", "Le droit de s'opposer à la reproduction ou à la diffusion de son image sans son accord",
     ["Le droit de publier toute photo", "Le droit de percevoir un salaire", "Le droit d'être candidat"],
     "C'est un droit de la personnalité.", 2),
    ("Quel est le caractère commun des droits de la personnalité ?", "Ils sont attachés à la personne : indisponibles et non évaluables en argent",
     ["Ils sont librement cessibles", "Ils sont toujours des droits réels", "Ils appartiennent aux seules entreprises"],
     "Ils sont extrapatrimoniaux et incessibles.", 3),
    ("Que protège le droit au respect de la vie privée ?", "l'intimité de la vie personnelle et familiale",
     ["l'activité commerciale d'une entreprise", "la liberté de circulation", "les affaires jugées publiquement"],
     "Il fait partie des droits de la personnalité.", 2),
    ("En droit OHADA, à compter de quand une société commerciale acquiert-elle la personnalité juridique ?", "de son immatriculation au registre du commerce et du crédit mobilier",
     ["de la rédaction de ses statuts seulement", "de la première réunion des associés", "du paiement du premier impôt"],
     "L'Acte uniforme sur les sociétés commerciales rattache la personnalité à l'immatriculation.", 4),
    ("Que signifie qu'une personne morale a un patrimoine propre ?", "Que ses biens sont distincts de ceux de ses membres",
     ["Qu'elle ne peut pas avoir de dettes", "Qu'elle appartient à l'État", "Qu'elle n'a pas de siège"],
     "Cette autonomie du patrimoine est une conséquence de la personnalité morale.", 3),
    ("Comment une personne morale s'exprime-t-elle juridiquement ?", "Par ses organes ou ses représentants légaux",
     ["Par un jugement du tribunal", "Par ses seuls fondateurs décédés", "Par un acte de l'état civil"],
     "Une personne morale agit par l'intermédiaire de personnes physiques désignées par ses statuts.", 3),
    ("Qu'est-ce qui limite la capacité d'une personne morale ?", "Son objet défini dans ses statuts (principe de spécialité)",
     ["Son âge", "Sa nationalité seulement", "Le nom de ses membres"],
     "Elle ne peut agir que dans les limites de son objet.", 4),
    ("Qu'est-ce qui distingue une association d'une société ?", "l'absence de but lucratif de partage de bénéfices entre ses membres",
     ["son absence de statuts", "l'obligation d'avoir un capital", "son caractère toujours public"],
     "L'association poursuit un but autre que le partage de bénéfices.", 3),
    ("Qu'est-ce qu'un groupement sans personnalité juridique ?", "Un groupe qui ne peut pas, en son nom propre, être titulaire de droits ou d'obligations",
     ["Un groupe qui paye des impôts", "Un groupe qui possède un siège", "Une administration publique"],
     "Faute de personnalité, ce sont les membres qui agissent.", 4),
    ("Quel est le sort d'une personne morale lorsqu'elle est dissoute ?", "Elle entre en liquidation pour régler ses dettes et créances, puis disparaît",
     ["Elle subsiste indéfiniment", "Elle devient une personne physique", "Elle devient l'État"],
     "La personnalité subsiste le temps nécessaire à la liquidation.", 4),
    ("Qu'est-ce qu'une personne morale de droit privé ?", "Un groupement créé par des particuliers, comme une société ou une association",
     ["L'État", "Une commune", "Une région"],
     "Les collectivités publiques sont des personnes morales de droit public.", 2),
    ("Lequel de ces groupements est une personne morale de droit public ?", "Une commune",
     ["Une société anonyme", "Une association de quartier", "Un syndicat de salariés"],
     "La commune est une collectivité territoriale.", 2),
    ("Que signifie la personnalité morale de l'État ?", "que l'État est titulaire de droits et d'obligations, en tant que tel",
     ["que l'État n'est pas soumis au droit", "que l'État n'a pas de patrimoine", "que l'État est un être humain"],
     "L'État est la personne morale par excellence.", 3),
], cat="Personnes physiques et morales", src="sup-droit-intro")
