"""L3 droit : cas pratiques et qualifications en droit du travail (principes généraux).

Mises en situation fictives : qualification du contrat, pouvoirs de l'employeur, rupture, représentation, grève, conflits, sécurité.
"""
from .sup_kit import *  # noqa: F401,F403

source("sup-cas-l3a", "Droit du travail : cas pratiques et qualifications", "cours de L3 droit",
       "Comparer avec un manuel de droit du travail (Code du travail applicable, conventions de l'OIT) ; les solutions précises varient selon les pays, d'où les mentions « en droit français » ou « de façon générale ».")

C = "Droit du travail (cas pratiques)"
CRS = "l3-droit"


def M(base, rows, cat=C, size=18):
    """Découpe les questions en lots (un modèle par lot) pour que chaque tpl reste petit."""
    for i in range(0, len(rows), size):
        mcq(CRS, "cas-l3a-%s%d" % (base, i // size + 1), rows[i:i + size], cat=cat, src="sup-cas-l3a")


# ---------------------------------------------------------------- 1. Qualification du contrat de travail
M("qual", [
    ("Mme Ngono répare le matériel d'une société, aux horaires imposés, avec les outils fournis et sous le contrôle d'un chef d'atelier. Comment qualifier la relation ?", "Un contrat de travail, car elle travaille sous la subordination de la société", ["Un contrat d'entreprise, car elle réalise une tâche précise", "Un mandat, car elle agit pour le compte de la société", "Un contrat de société, car elle apporte son travail", "Un bénévolat, car elle ne choisit pas ses outils"], "Horaires imposés, direction et contrôle caractérisent le lien de subordination.", 2),
    ("Un artisan s'engage à livrer un meuble sur commande, choisit ses horaires et ses méthodes, et facture son client. Quelle qualification est la plus plausible ?", "Un contrat d'entreprise, faute de subordination", ["Un contrat de travail à durée indéterminée", "Un contrat d'apprentissage", "Un contrat de travail à durée déterminée", "Un contrat de société en participation"], "Sans ordres ni contrôle de l'exécution, il n'y a pas de lien de subordination.", 2),
    ("Les parties ont intitulé leur accord « contrat de prestation de services », mais la personne reçoit des ordres quotidiens et peut être sanctionnée. Que décidera le juge ?", "Il requalifiera en contrat de travail d'après la réalité des faits", ["Il respectera le titre choisi par les parties", "Il déclarera le contrat inexistant", "Il le qualifiera de contrat de société", "Il laissera l'employeur choisir la qualification"], "Les faits priment sur la dénomination donnée par les parties.", 3),
    ("Quel élément est, de façon générale, décisif pour qualifier un contrat de travail ?", "Le lien de subordination juridique", ["Le versement d'une somme d'argent, quelle qu'elle soit", "L'existence d'un écrit signé", "L'appartenance du travailleur à un syndicat", "La durée de la relation de travail"], "Travail, rémunération et subordination sont requis ; la subordination est l'élément distinctif.", 2),
    ("M. Tchoumi aide ponctuellement son voisin à construire sa clôture, sans rien recevoir ni être dirigé. Existe-t-il un contrat de travail ?", "Non, il manque la rémunération et la subordination", ["Oui, car un travail a été accompli", "Oui, car l'aide a été utile au voisin", "Oui, mais seulement à durée déterminée", "Oui, car la clôture appartient au voisin"], "Un service gratuit rendu sans direction n'est pas un contrat de travail.", 2),
    ("Une association fait distribuer des tracts par des personnes qui ne reçoivent aucune rémunération et participent librement. De quoi s'agit-il en principe ?", "De bénévolat, faute de rémunération et de subordination", ["D'un contrat de travail à durée indéterminée", "D'un contrat d'apprentissage", "D'un contrat de travail temporaire", "D'un contrat de société civile"], "La gratuité et la liberté d'engagement caractérisent le bénévolat.", 2),
    ("Un travailleur est dit « indépendant » sur le papier, mais il dépend d'un seul donneur d'ordre qui fixe ses tournées et le sanctionne. Que révèle ce faisceau d'indices ?", "Un possible contrat de travail déguisé", ["Un contrat de bail commercial", "Un contrat de vente de marchandises", "Une société de fait entre les deux parties", "Un contrat de dépôt"], "Le juge recherche, par un faisceau d'indices, l'existence d'une subordination réelle.", 4),
    ("Dans la méthode du « faisceau d'indices », que cherche à établir le juge ?", "Les conditions réelles d'exécution du travail, pour savoir s'il y a subordination", ["La seule volonté exprimée dans le contrat", "La nationalité des parties", "Le montant des impôts payés par le travailleur", "L'ancienneté de l'entreprise sur le marché"], "Le juge examine les circonstances concrètes de l'exécution, pas l'étiquette.", 3),
    ("Un étudiant effectue un stage prévu par sa formation, encadré par une convention avec son établissement, avec un objectif pédagogique. Quelle est la logique de ce stage ?", "Une finalité de formation, distincte d'un emploi ordinaire", ["Un emploi salarié normal sans particularité", "Un mandat donné à l'étudiant", "Une société entre l'étudiant et l'entreprise", "Un prêt de main-d'œuvre entre entreprises"], "Le stage vise l'apprentissage ; s'il masque un vrai poste, il peut être requalifié.", 3),
    ("Un « stagiaire » occupe durablement un poste de travail, remplace un salarié absent et reçoit des ordres comme les autres. Quel risque cela fait-il courir à l'entreprise ?", "La requalification du stage en contrat de travail", ["La transformation du stage en contrat de société", "L'obligation de dissoudre l'entreprise", "La nullité de tous les contrats de l'entreprise", "La perte automatique de la personnalité morale"], "Un stage détourné de sa finalité pédagogique peut être requalifié en contrat de travail.", 4),
    ("Un employeur engage un travailleur sans écrit, mais lui donne chaque jour des consignes et lui verse un salaire. Le contrat de travail existe-t-il ?", "Oui, en principe l'accord peut résulter des faits même sans écrit", ["Non, un contrat de travail exige toujours un écrit notarié", "Non, seul un contrat écrit protège le travailleur", "Oui, mais seulement après un an de relation", "Non, tant que le syndicat n'a pas été consulté"], "Le contrat de travail se prouve par tous moyens ; l'écrit n'est pas, en principe, une condition d'existence.", 3),
    ("Dans un contrat de travail, que doit à l'employeur le salarié, de façon générale ?", "Sa prestation de travail exécutée sous la direction de l'employeur", ["Une part des bénéfices de l'entreprise", "La propriété de ses outils personnels", "Une garantie bancaire sur son salaire", "L'obligation de financer l'entreprise"], "Le salarié fournit un travail ; l'employeur paie le salaire.", 1),
    ("Un livreur utilise son propre véhicule, fixe librement ses horaires, peut refuser des courses et travaille aussi pour d'autres clients. Quel indice milite contre le contrat de travail ?", "Son autonomie dans l'organisation et la pluralité de clients", ["Le fait qu'il reçoive une somme d'argent", "Le fait qu'il livre des marchandises", "Le fait qu'il connaisse l'adresse de l'entreprise", "Le fait qu'il utilise un véhicule"], "L'autonomie et l'absence d'exclusivité révèlent plutôt une activité indépendante.", 3),
    ("Un avocat plaide pour un client qui lui verse des honoraires, sans recevoir d'ordres sur la manière de plaider. Cette relation est plutôt de quel ordre ?", "D'un mandat ou d'une prestation libérale, sans subordination", ["D'un contrat de travail à durée indéterminée", "D'un contrat d'apprentissage", "D'un contrat de travail temporaire", "D'une société entre l'avocat et son client"], "L'indépendance dans la conduite de la mission exclut la subordination.", 3),
    ("Un salarié est détaché dans une autre entreprise pendant quelques mois, mais son employeur d'origine continue de le payer et reste son employeur. Que reste-t-il, en principe ?", "Le contrat avec l'employeur d'origine", ["Un nouveau contrat avec l'entreprise d'accueil, automatiquement", "L'absence de tout contrat pendant le détachement", "Un contrat de société avec l'entreprise d'accueil", "Un contrat d'apprentissage"], "Le détachement ne rompt pas le contrat ; l'employeur d'origine demeure l'employeur.", 4),
    ("Un travailleur est mis à disposition d'une entreprise utilisatrice par une agence de travail temporaire. Qui est, en principe, son employeur juridique ?", "L'agence de travail temporaire", ["L'entreprise utilisatrice", "L'État", "Le syndicat des intérimaires", "Le client de l'entreprise utilisatrice"], "L'intérimaire est lié par contrat de travail à l'agence, qui le met à disposition.", 3),
    ("Le contrat de travail à durée indéterminée est, en principe, quelle forme de relation ?", "La forme normale et générale de la relation de travail", ["Une forme réservée aux cadres supérieurs seulement", "Une forme interdite sauf autorisation du juge", "Une forme réservée aux entreprises publiques", "Une forme limitée aux travailleurs saisonniers"], "Le CDD est une exception encadrée à cette forme normale.", 2),
    ("Une entreprise conclut des CDD successifs pour pourvoir un poste durable et permanent, sans motif légitime. Quelle sanction est classique en droit français ?", "La requalification en contrat à durée indéterminée", ["La nullité de l'entreprise", "La transformation du poste en mandat", "La rupture automatique sans indemnité", "La conversion en contrat d'apprentissage"], "Le recours au CDD ne peut avoir pour objet de pourvoir durablement un emploi permanent.", 4),
    ("En droit français, un contrat à durée déterminée peut être conclu en principe pour quoi ?", "Une tâche précisée et temporaire, dans les cas prévus", ["N'importe quel emploi sans condition de motif", "Un emploi durable lié à l'activité normale", "Uniquement les emplois de direction", "Uniquement les travaux de nuit"], "Le CDD est ouvert dans des cas limités liés au caractère temporaire de la tâche.", 3),
    ("Que permet, en principe, la période d'essai ?", "Évaluer les capacités du salarié et vérifier que l'emploi convient aux deux parties", ["Priver le salarié de toute rémunération", "Supprimer pour toujours l'obligation de sécurité", "Dispenser l'employeur de toute règle de discrimination", "Remplacer le contrat de travail"], "L'essai sert à tester la collaboration ; les droits fondamentaux du salarié subsistent.", 2),
    ("Pendant la période d'essai, un employeur met fin au contrat pour un motif discriminatoire. Que peut-on dire ?", "La liberté de rompre n'autorise pas une rupture discriminatoire", ["La rupture est toujours valable pendant l'essai", "La rupture devient valable après le préavis", "La discrimination est permise si l'essai n'est pas payé", "Seul le salarié peut agir devant le juge"], "Même libre, la rupture ne peut reposer sur un motif illicite.", 4),
    ("Que reste, en principe, un salarié à temps partiel ?", "Un salarié comme les autres, avec un horaire inférieur à l'horaire de l'entreprise", ["Un travailleur indépendant", "Un bénévole", "Un stagiaire en formation", "Un associé de l'entreprise"], "Le temps partiel est une modalité du contrat de travail, pas une absence de contrat.", 2),
    ("Une société qui change de forme juridique continue d'employer ses salariés. Que devient, de façon générale, le contrat de travail ?", "Il se poursuit avec le nouvel employeur", ["Il est automatiquement rompu", "Il devient un contrat d'entreprise", "Il est suspendu jusqu'à décision du juge", "Il devient un contrat à durée déterminée"], "En cas de modification dans la situation juridique de l'employeur, les contrats en cours subsistent.", 4),
    ("Dans un contrat de travail, de quoi la rémunération est-elle la contrepartie ?", "Du travail fourni au profit de l'employeur", ["De la fidélité du salarié à son syndicat", "Du capital apporté par le salarié", "De l'ancienneté de l'entreprise", "De la nationalité du salarié"], "Le salaire est la contrepartie du travail accompli.", 1),
    ("Un travailleur à domicile reçoit des matières de l'entreprise, fabrique des pièces selon ses consignes précises et les rend en échange d'une paie. Quelle conclusion est plausible ?", "La subordination peut exister même sans présence dans les locaux", ["Il n'y a jamais de contrat de travail hors des locaux", "Il est associé de l'entreprise", "Il est un bénévole", "Il est un client de l'entreprise"], "La subordination se mesure à la direction du travail, pas au lieu d'exécution.", 4),
    ("Un salarié exécute ses tâches en télétravail, mais l'employeur fixe les objectifs, contrôle les résultats et peut sanctionner. Quel est l'effet sur la qualification ?", "Le contrat de travail demeure, la subordination subsistant à distance", ["Il devient un contrat d'entreprise", "Il devient un mandat", "Il perd sa nature de contrat de travail", "Il se transforme en société"], "Le lieu d'exécution n'efface pas le pouvoir de direction.", 3),
    ("Un employé qui exerce une grande autonomie technique (par exemple un ingénieur) peut-il être salarié ?", "Oui, l'autonomie technique n'exclut pas la subordination juridique", ["Non, un salarié doit toujours exécuter des gestes imposés", "Non, seuls les ouvriers peuvent être salariés", "Oui, mais seulement à temps partiel", "Non, il serait nécessairement associé"], "La subordination est juridique, non technique : l'employeur garde le pouvoir de direction.", 4),
    ("Qu'est-ce qui distingue le salarié du mandataire qui agit pour le compte d'un mandant ?", "Le salarié est subordonné, le mandataire accomplit des actes juridiques pour autrui", ["Le salarié choisit seul ses missions, le mandataire non", "Le salarié est toujours bénévole", "Le mandataire est toujours payé en nature", "Il n'y a aucune différence"], "Le mandat porte sur des actes juridiques accomplis pour le mandant, sans subordination nécessaire.", 5),
    ("Un travailleur est engagé pour une durée fixée à l'avance, à l'expiration de laquelle le contrat s'achève sauf renouvellement. Quel type de contrat est-ce ?", "Un contrat à durée déterminée", ["Un contrat à durée indéterminée", "Un contrat d'entreprise", "Un contrat de société", "Un contrat de bail"], "Le terme fixé à l'avance est le critère du contrat à durée déterminée.", 1),
    ("Dans l'apprentissage, quel élément caractérise le contrat, de façon générale ?", "L'alternance entre la formation et le travail en entreprise", ["L'absence de toute formation", "L'absence de toute rémunération", "La direction du travail par l'apprenti", "L'exclusion du droit du travail"], "L'apprenti est formé en travaillant, sous l'autorité d'un maître d'apprentissage.", 2),
    ("Le gérant d'une boutique gère librement l'établissement et se rémunère sur les résultats, sans recevoir d'instructions, en payant une redevance au propriétaire. Quel indice joue contre le contrat de travail ?", "L'absence de direction et le risque économique supporté", ["Le fait que la boutique soit ouverte au public", "Le fait que le gérant soit rémunéré", "Le fait que la boutique ait un propriétaire", "Le fait que le gérant travaille régulièrement"], "L'indépendance de gestion et le risque économique sont des indices d'indépendance.", 5),
    ("En cas de doute sur la nature de la relation, qui tranche si les parties ne s'accordent pas ?", "Le juge compétent, selon les faits établis", ["Le seul employeur, qui impose sa qualification", "Le seul travailleur, qui choisit sa qualification", "Le syndicat de l'entreprise", "Le tirage au sort"], "La qualification juridique est une question relevant du juge.", 2),
    ("Une personne exerce un travail pour une entreprise, dissimulé et non déclaré, pour ne pas payer de cotisations. Comment appelle-t-on cette situation, de façon générale ?", "Le travail dissimulé", ["Le travail à temps partiel", "Le travail saisonnier", "Le détachement", "L'apprentissage"], "Le travail dissimulé consiste à éluder les obligations déclaratives liées à l'emploi.", 3),
    ("Un salarié exerce son activité dans une entreprise sans que son employeur l'ait déclaré. Que signifie cela pour l'existence de son contrat ?", "Le contrat existe malgré l'absence de déclaration, qui constitue un manquement", ["Le contrat n'existe pas", "Le contrat est nul pour l'avenir seulement", "Le contrat devient un contrat d'entreprise", "Le salarié devient associé"], "Le défaut de déclaration n'efface pas l'existence du contrat de travail.", 4),
    ("Quelle est la conséquence pour l'employeur qui a fait travailler une personne en dehors de toute déclaration ?", "Il s'expose à des sanctions pour travail dissimulé", ["Il devient le débiteur de ses concurrents", "Il peut réduire librement le salaire", "Il est dispensé de toute obligation envers le salarié", "Il peut rompre le contrat sans motif"], "Le travail dissimulé est sanctionné, notamment par des peines et des indemnités.", 3),
    ("Le critère du « pouvoir de sanction » est un indice de quoi ?", "De l'existence d'une subordination juridique", ["De l'existence d'un contrat de vente", "De l'absence de contrat", "De la qualité d'associé", "De la nature civile de l'entreprise"], "Le pouvoir de sanctionner les manquements est l'un des attributs de l'employeur.", 3),
    ("Parmi ces éléments, lequel est un indice de subordination ?", "L'obligation de suivre des horaires fixés par le donneur d'ordre", ["Le fait d'être payé en fin de mois", "Le fait d'avoir un compte bancaire", "Le fait de travailler en équipe avec des collègues", "Le fait de travailler dans une ville"], "L'imposition des horaires est un indice classique de direction.", 2),
    ("Parmi ces éléments, lequel est plutôt un indice d'indépendance ?", "Le fait de fixer librement ses tarifs et de prospecter sa clientèle", ["Le fait de suivre un règlement intérieur", "Le fait d'être sanctionné par un supérieur", "Le fait de recevoir des instructions détaillées", "Le fait d'utiliser le matériel fourni par le donneur d'ordre"], "La liberté de clientèle et de tarif est caractéristique de l'indépendance.", 3),
    ("Un cadre dirigeant d'une entreprise peut-il être lié par un contrat de travail ?", "Oui, s'il demeure subordonné à l'organe qui dirige la société", ["Non, un dirigeant n'est jamais salarié", "Oui, mais seulement si le contrat n'est pas écrit", "Non, car il possède l'entreprise", "Oui, mais jamais avec rémunération"], "Un dirigeant peut cumuler contrat de travail et fonction si une réelle subordination existe.", 5),
    ("Le contrat de travail est-il un contrat à titre onéreux ?", "Oui, chaque partie reçoit un avantage en contrepartie de ce qu'elle donne", ["Non, c'est toujours un contrat gratuit", "Non, il est unilatéral", "Oui, mais seul l'employeur en retire un avantage", "Non, il est réel"], "Travail et salaire sont échangés : le contrat est synallagmatique et onéreux.", 3),
    ("Parmi ces contrats, lequel n'est pas un contrat de travail ?", "Le contrat d'entreprise", ["Le contrat à durée indéterminée", "Le contrat à durée déterminée", "Le contrat d'apprentissage", "Le contrat de travail à temps partiel"], "Le contrat d'entreprise est un contrat de prestation indépendante.", 2),
    ("Un employeur conteste l'existence d'un contrat de travail en soutenant que la personne était indépendante. Sur qui pèse, en principe, la charge de prouver le contrat de travail ?", "Sur celui qui s'en prévaut, c'est-à-dire en général le travailleur", ["Sur l'employeur dans tous les cas", "Sur l'inspecteur du travail", "Sur le syndicat", "Sur aucune des parties"], "Celui qui invoque l'existence d'un contrat de travail doit en prouver les éléments.", 4),
    ("Le prêt de main-d'œuvre à but lucratif entre entreprises est, de façon générale, traité comment ?", "Encadré, voire interdit hors des cadres prévus par la loi", ["Toujours libre sans condition", "Obligatoire pour tout employeur", "Réservé aux associations", "Ouvert seulement aux étrangers"], "Le marchandage et le prêt illicite de main-d'œuvre sont combattus pour protéger les salariés.", 5),
    ("Un salarié accepte un poste ; l'employeur lui présente ensuite un contrat contenant une clause le privant de tout droit de contester son licenciement. Que penser de cette clause ?", "Elle est sans effet, car on ne peut renoncer par avance à ses droits d'ordre public", ["Elle est valable car le salarié a signé", "Elle est valable si l'employeur est de bonne foi", "Elle est valable si le poste est qualifié", "Elle est valable seulement pour les cadres"], "Les règles protectrices d'ordre public ne souffrent pas de renonciation anticipée.", 4),
    ("Un contrat de travail est conclu avec un mineur, avec l'accord de son représentant légal, pour un travail dangereux. Quel principe général s'applique ?", "Le travail des jeunes est encadré et certains travaux leur sont interdits", ["Le mineur est libre de tout travail", "L'accord du représentant légal valide tout travail", "Seule la rémunération importe", "Le mineur est traité comme un adulte sur tout"], "Les mineurs bénéficient de règles protectrices spécifiques.", 3),
    ("L'employeur a le droit de choisir son salarié. Quelle limite générale s'impose à ce choix ?", "L'interdiction de toute discrimination illégitime", ["L'obligation de choisir le plus âgé", "L'obligation de recruter un parent d'un salarié", "L'obligation d'obtenir l'accord des syndicats", "L'obligation de recruter par tirage au sort"], "Le recrutement doit reposer sur des critères professionnels, non discriminatoires.", 3),
], size=15)
# ---------------------------------------------------------------- 2. Pouvoirs de l'employeur
M("pouv", [
    ("Un employeur impose un nouveau logiciel de facturation à tous ses employés. Quel pouvoir exerce-t-il ?", "Son pouvoir de direction", ["Son pouvoir de représenter légalement les salariés", "Son pouvoir de juger les litiges entre salariés", "Son pouvoir de fixer les lois du travail", "Son pouvoir de négocier une convention collective de branche"], "Le pouvoir de direction permet d'organiser le travail et de donner des instructions.", 2),
    ("Une entreprise adopte un règlement intérieur fixant les horaires d'accès, les règles d'hygiène et les sanctions. Quel pouvoir est en jeu ?", "Le pouvoir réglementaire de l'employeur", ["Le pouvoir législatif de l'État dans l'entreprise", "Le pouvoir de contrôle exercé par l'inspecteur du travail", "Le pouvoir de juger donné au conseil d'administration", "Le pouvoir de négociation reconnu aux syndicats"], "L'employeur édicte des règles générales applicables dans l'entreprise.", 2),
    ("Un employeur inflige un avertissement à un salarié arrivé en retard de façon répétée. Quel pouvoir exerce-t-il ?", "Son pouvoir disciplinaire", ["Son pouvoir de direction sur les congés payés", "Son pouvoir de représentation de l'entreprise", "Son pouvoir de contrôle des comptes du syndicat", "Son pouvoir d'arbitrage entre salariés"], "Sanctionner une faute relève du pouvoir disciplinaire.", 2),
    ("Un employeur sanctionne un salarié deux fois pour le même retard : un avertissement, puis une mise à pied. Quelle règle est méconnue ?", "Une même faute ne peut être sanctionnée deux fois", ["Le salarié doit toujours être sanctionné trois fois", "L'employeur ne peut jamais prononcer d'avertissement", "La mise à pied est réservée au syndicat", "Le retard ne peut jamais être une faute"], "Le principe non bis in idem s'applique au pouvoir disciplinaire.", 3),
    ("Avant de prononcer une sanction disciplinaire, l'employeur ne fait pas entendre le salarié. Quel principe général est violé ?", "Le respect des droits de la défense", ["Le principe de la liberté d'entreprendre", "Le principe de l'autonomie de la volonté", "Le principe de la hiérarchie des normes", "Le principe de la séparation des pouvoirs"], "Le salarié doit pouvoir s'expliquer avant d'être sanctionné.", 3),
    ("Un employeur sanctionne par une mise à pied sévère un retard de quelques minutes, sans antécédent. Quel principe est en cause ?", "La proportionnalité de la sanction à la faute", ["La liberté syndicale du salarié sanctionné", "Le principe du contradictoire devant le juge", "L'obligation de reclassement du salarié", "L'obligation de sécurité de l'employeur"], "La sanction doit être proportionnée à la gravité de la faute.", 3),
    ("L'employeur décide de modifier l'heure de début du travail de son équipe d'une demi-heure, sans changer le reste. De quoi s'agit-il en principe, en droit français ?", "D'un simple changement des conditions de travail", ["D'une modification du contrat exigeant l'accord", "D'un licenciement déguisé", "D'une sanction disciplinaire", "D'une rupture conventionnelle"], "Un ajustement mineur de l'horaire relève du pouvoir de direction.", 4),
    ("L'employeur réduit significativement la rémunération contractuelle d'un salarié sans son accord. Quelle est la règle de principe en droit français ?", "La rémunération contractuelle ne peut être modifiée sans l'accord du salarié", ["L'employeur peut toujours la réduire librement", "Seul le syndicat peut l'accepter à la place du salarié", "Elle peut être modifiée si l'inspecteur le demande", "Elle peut être modifiée si l'entreprise est ancienne"], "La rémunération est un élément essentiel du contrat, qui ne peut être changé unilatéralement.", 4),
    ("Un salarié refuse une modification de son contrat proposée par l'employeur. Que peut faire l'employeur ?", "Renoncer à la modification ou en tirer les conséquences par un licenciement fondé", ["Imposer la modification en toute hypothèse", "Sanctionner le refus comme une faute grave dans tous les cas", "Faire modifier le contrat par l'inspecteur", "Supprimer le contrat de travail sans motif"], "Le refus d'une modification du contrat n'est pas en soi une faute.", 5),
    ("Un employeur mute un salarié dans un autre service du même lieu géographique, pour la même fonction et la même rémunération. Dans la logique habituelle, de quoi s'agit-il ?", "D'un changement des conditions de travail relevant du pouvoir de direction", ["D'une modification du contrat exigeant l'accord", "D'un licenciement économique", "D'une démission du salarié", "D'une sanction obligatoire"], "Sans toucher à un élément essentiel, l'employeur peut décider de façon unilatérale.", 4),
    ("Qu'est-ce qu'une clause de mobilité, de façon générale ?", "Une clause qui permet à l'employeur de changer le lieu de travail dans des limites prévues", ["Une clause qui interdit tout déplacement du salarié", "Une clause qui garantit un salaire maximal", "Une clause qui interdit de travailler pour des concurrents", "Une clause qui réserve le poste à un syndicalisé"], "Elle autorise un changement de lieu, qui doit être mis en œuvre de bonne foi.", 3),
    ("Qu'est-ce qu'une clause de non-concurrence dans un contrat de travail ?", "Une clause qui limite la liberté du salarié d'exercer une activité concurrente après son départ", ["Une clause qui interdit à l'employeur de recruter", "Une clause qui garantit l'exclusivité du salaire", "Une clause qui interdit de se syndiquer", "Une clause qui fixe l'horaire du salarié"], "Elle protège les intérêts légitimes de l'entreprise après la rupture.", 3),
    ("En droit français, quelle condition est exigée pour la validité d'une clause de non-concurrence post-contractuelle ?", "Elle doit être limitée dans le temps et l'espace et être indispensable à l'entreprise", ["Elle doit viser tous les emplois sans limite", "Elle doit être imposée sans aucune contrepartie", "Elle doit être valable pour toute la vie du salarié", "Elle doit être décidée par le syndicat"], "La clause ne doit pas empêcher le salarié de retrouver un emploi ; une contrepartie financière est exigée.", 5),
    ("Un employeur surveille en secret par caméra cachée les salariés, sans les en informer. Quel principe général est méconnu ?", "La loyauté et la transparence dans le contrôle des salariés", ["La liberté d'entreprendre du salarié", "Le droit de grève des salariés", "La liberté syndicale", "Le droit à un salaire minimal"], "Un dispositif de contrôle doit être porté à la connaissance des salariés.", 4),
    ("Un employeur consulte les messages strictement privés d'un salarié sur son téléphone personnel, sans son accord. Quel principe est atteint ?", "Le respect de la vie privée du salarié", ["Le droit de grève du salarié", "La liberté de réunion syndicale", "Le droit à la formation du salarié", "Le principe d'égalité de rémunération"], "Le salarié conserve sa vie privée au temps et au lieu de travail.", 3),
    ("Un employeur interdit à ses salariés de porter des signes religieux discrets, sans justification liée à la tâche ni règle générale. En principe, que peut-on dire ?", "Les restrictions aux libertés doivent être justifiées par la nature de la tâche et proportionnées", ["L'employeur peut tout interdire sans justification", "Le salarié perd ses libertés en signant le contrat", "Seul un syndicat peut décider des restrictions", "Les libertés n'existent pas dans l'entreprise"], "Les limites aux libertés individuelles doivent être justifiées et proportionnées.", 5),
    ("Un salarié perçoit une prime depuis plusieurs années, de manière constante, générale et fixe. L'employeur décide de la supprimer d'un coup. Quel concept est susceptible de s'appliquer ?", "L'usage d'entreprise", ["Le lock-out", "La grève perlée", "La clause de mobilité", "La prise d'acte"], "Un usage constant, général et fixe crée des droits que l'employeur doit dénoncer régulièrement.", 5),
    ("Un employeur annonce de sa seule volonté une prime à tout le personnel à la fin de l'année. De quoi relève cet acte ?", "D'un engagement unilatéral de l'employeur", ["D'une convention collective de branche", "D'une sentence arbitrale", "D'un accord d'entreprise négocié", "D'un usage imposé par la loi"], "Une promesse unilatérale précise peut créer des droits pour les salariés.", 5),
    ("Un salarié estime qu'on lui impose une tâche étrangère à sa qualification, sans accord. Quelle est la règle de principe ?", "Un changement de qualification est une modification substantielle du contrat", ["L'employeur peut changer librement la qualification", "Le salarié doit se taire car il est subordonné", "Seul l'inspecteur peut modifier la qualification", "Il n'y a jamais de qualification contractuelle"], "La qualification professionnelle est un élément essentiel du contrat.", 4),
    ("Un salarié reçoit un ordre manifestement illégal de son supérieur, par exemple falsifier des documents officiels. Quel principe général protège sa position ?", "L'obligation d'obéissance ne s'étend pas aux ordres manifestement illicites", ["Il doit toujours obéir aux ordres sans exception", "Il commet une faute s'il refuse l'ordre illicite", "L'employeur peut ordonner n'importe quoi", "Le contrat de travail supprime sa responsabilité pénale"], "La subordination n'impose pas de commettre une infraction.", 4),
    ("Un employeur fait pratiquer des fouilles individuelles de sacs de façon arbitraire sur certains salariés seulement. Quelle exigence est en cause ?", "Les atteintes aux libertés doivent être justifiées, proportionnées et non discriminatoires", ["La nécessité d'obtenir l'accord du juge pour toute surveillance", "L'interdiction de toute règle intérieure", "Le droit de l'employeur de faire ce qu'il veut", "L'obligation pour les salariés de se syndiquer"], "Un contrôle doit reposer sur des règles connues et être non arbitraire.", 4),
    ("Qu'implique le devoir de loyauté du salarié, de façon générale ?", "Qu'il ne nuise pas aux intérêts de l'entreprise pendant l'exécution du contrat", ["Qu'il renonce à tout syndicat pendant le contrat", "Qu'il accepte toute modification de son salaire", "Qu'il ne demande jamais de congés", "Qu'il informe l'employeur de sa vie privée"], "La loyauté interdit notamment de concurrencer son employeur pendant le contrat.", 3),
    ("Un salarié exerce en cachette une activité concurrente de celle de son employeur pendant son contrat. Quelle obligation méconnaît-il ?", "Son obligation de loyauté envers l'employeur", ["Son obligation de sécurité à l'égard de l'employeur", "Son obligation de reclassement", "Son obligation de reprendre le travail après la grève", "Son obligation de verser des cotisations syndicales"], "La concurrence déloyale pendant le contrat est un manquement à l'obligation de loyauté.", 3),
    ("Un employeur refuse de fournir du travail au salarié, tout en continuant à le payer. Que peut-on dire, de façon générale ?", "L'employeur doit en principe fournir le travail convenu", ["L'employeur n'a jamais à fournir de travail", "Le salarié doit fournir le travail à l'employeur", "Seul le syndicat peut fournir du travail", "Le juge fournit le travail au salarié"], "Fournir du travail est une obligation essentielle de l'employeur, à côté du paiement du salaire.", 3),
    ("Un employeur retarde chaque mois de plusieurs semaines le paiement du salaire. Quelle obligation fondamentale n'est pas respectée ?", "Le paiement régulier de la rémunération", ["L'obligation de loyauté du salarié", "L'obligation de reclassement", "Le devoir de non-concurrence", "L'obligation d'affiliation syndicale"], "Le salaire est la principale obligation de l'employeur.", 2),
    ("Un employeur impose à un salarié d'exécuter des tâches dangereuses sans aucun équipement de protection. Quel pouvoir dépasse-t-il ?", "Son pouvoir de direction, borné par l'obligation de sécurité", ["Son pouvoir de négociation, borné par le syndicat", "Son pouvoir de représentation, borné par le juge", "Son pouvoir législatif, borné par la constitution", "Son pouvoir de nomination, borné par l'État"], "Le pouvoir de direction s'exerce dans le respect de la santé et de la sécurité.", 3),
    ("Un employeur accorde un meilleur salaire à des hommes qu'à des femmes, à poste et compétences équivalents. Quel principe est violé ?", "Le principe d'égalité de rémunération à travail égal", ["Le principe de liberté syndicale", "Le principe de la hiérarchie des normes", "Le principe de la clause de mobilité", "Le principe du préavis"], "À travail de valeur égale, la rémunération doit être égale, sans discrimination.", 3),
    ("Un employeur ne promeut jamais un salarié parce qu'il est syndicaliste, malgré ses qualités. Comment qualifier ce comportement ?", "Une discrimination syndicale", ["Un exercice ordinaire du pouvoir disciplinaire", "Une clause de mobilité", "Un usage d'entreprise", "Un lock-out"], "Prendre en compte l'appartenance syndicale pour décider est interdit.", 3),
    ("Un employeur adopte seul un règlement intérieur qui contient une clause contraire à la loi. Quelle est la valeur de cette clause ?", "Elle est sans effet, le règlement ne pouvant pas déroger aux règles supérieures", ["Elle est valable car l'employeur est maître chez lui", "Elle est valable si elle est affichée", "Elle est valable après un an d'application", "Elle prime sur la loi car elle est plus récente"], "Le règlement intérieur respecte la hiérarchie des normes.", 4),
    ("À qui le règlement intérieur s'impose-t-il, en principe ?", "À tous les salariés de l'entreprise", ["À l'employeur seul, et pas aux salariés", "Aux syndicats uniquement, et pas aux salariés", "Aux seuls salariés signataires d'un écrit spécial", "Aux salariés après approbation du ministre"], "Il fixe des règles générales applicables à toute l'entreprise.", 2),
    ("Peut-on, par le règlement intérieur, prévoir une sanction qui n'est prévue par aucune règle supérieure, par exemple l'amende sur salaire ?", "En principe non, les sanctions pécuniaires sont interdites en droit français", ["Oui, sans aucune limite", "Oui si l'inspecteur est absent", "Oui si le salarié est cadre", "Oui si le délégué du personnel est d'accord"], "Les amendes et sanctions pécuniaires sont prohibées par le droit français du travail.", 5),
    ("Un employeur privilégie une pratique générale favorable aux salariés, durablement appliquée, puis la supprime sans prévenir personne. Qu'aurait-il dû faire ?", "Dénoncer l'usage régulièrement, avec information préalable des intéressés", ["Rien, car il peut la supprimer à tout moment", "Attendre la prochaine grève", "Saisir le tribunal de l'ordre judiciaire pénal", "Obtenir l'autorisation de l'inspecteur du travail"], "Un usage ne peut être supprimé qu'à l'issue d'une dénonciation régulière.", 5),
    ("Quelle est la différence entre pouvoir de direction et pouvoir disciplinaire ?", "Le premier organise le travail, le second sanctionne les fautes", ["Le premier sanctionne les fautes, le second organise le travail", "Le premier appartient aux salariés, le second à l'État", "Le premier concerne les cadres, le second les ouvriers", "Il n'y a aucune différence"], "Organisation du travail d'un côté, sanction des manquements de l'autre.", 2),
    ("Un employeur sanctionne un salarié pour un fait fautif connu depuis très longtemps, sans enquête ni urgence. Quelle règle de principe est méconnue ?", "Le caractère tardif de la sanction", ["La liberté syndicale", "La clause de mobilité", "Le principe de reclassement", "Le principe de non-concurrence"], "Les faits fautifs doivent être sanctionnés dans un délai raisonnable ; sinon l'employeur est réputé les avoir tolérés.", 5),
    ("En cas de faute, l'employeur écarte immédiatement le salarié de l'entreprise le temps de décider. Comment appelle-t-on cette mesure ?", "Une mise à pied conservatoire", ["Un lock-out", "Un préavis", "Une clause de mobilité", "Une prise d'acte"], "Elle est provisoire et précède la décision définitive.", 3),
    ("Quelle est la nature de l'avertissement adressé par l'employeur à un salarié fautif ?", "Une sanction disciplinaire légère", ["Un licenciement", "Une démission déguisée", "Une grève de l'employeur", "Un congé forcé"], "L'avertissement est la sanction la plus légère, sans effet sur la présence du salarié.", 2),
    ("Un employeur impose de façon permanente un travail de nuit à un salarié engagé de jour, sans son accord. Quelle analyse est la plus probable en droit français ?", "Un changement important du contrat qui requiert son accord", ["Un changement des conditions de travail ordinaire", "Une sanction licite sans condition", "Un simple droit de l'employeur sans effet", "Une rupture amiable acquise"], "Passer de jour à nuit bouleverse l'économie du contrat.", 5),
    ("Quelle obligation pèse sur l'employeur à propos de l'égalité de traitement entre salariés placés dans la même situation ?", "Il doit justifier toute différence par des raisons objectives et pertinentes", ["Il peut traiter chacun à sa convenance", "Il doit accorder le même salaire à tous, quelle que soit la fonction", "Il doit consulter chaque salarié avant toute décision", "Il doit éviter de payer les cadres plus que les ouvriers"], "Une différence de traitement doit reposer sur des éléments objectifs et vérifiables.", 5),
    ("Un employeur adopte un code de conduite pour ses salariés mais ne l'affiche nulle part et ne le communique pas. Que peut-on soulever ?", "Son inopposabilité faute d'avoir été porté à la connaissance des salariés", ["Sa validité absolue dès la signature", "Sa nullité automatique de l'entreprise", "Son remplacement par la loi du pays voisin", "Sa transformation en convention collective"], "Un règlement doit être porté à la connaissance de ceux auxquels on l'oppose.", 4),
    ("Un employeur impose la mutation d'un salarié protégé dans un autre établissement sans son accord. Quel principe particulier s'applique en droit français ?", "Le changement des conditions de travail d'un salarié protégé exige son accord", ["Le salarié protégé est traité comme tout autre salarié", "Le salarié protégé est muté d'office par l'inspecteur", "Le salarié protégé est exclu de l'entreprise", "Le salarié protégé n'a aucun droit particulier"], "Les mandats sont protégés : on ne peut leur imposer une modification sans accord.", 5),
    ("Un employeur subordonne l'embauche à la réponse du candidat à des questions sans lien avec le poste (vie intime, opinions). Que peut-on dire ?", "Les questions doivent avoir un lien direct avec l'emploi et l'aptitude professionnelle", ["Toutes les questions sont permises en entretien", "Le candidat doit répondre sous peine de sanction pénale", "L'employeur peut les consigner dans un fichier public", "Le candidat n'a aucun droit en entretien"], "Le recrutement ne peut utiliser que des informations liées à l'aptitude professionnelle.", 3),
    ("Peut-on soutenir qu'un employeur dépasse ses pouvoirs en imposant au salarié de lui remettre les clés de sa vie privée (identifiants de comptes personnels) ?", "Oui, car la vie privée limite le pouvoir de direction", ["Non, le contrat donne tout pouvoir à l'employeur", "Non, car il paie un salaire", "Oui, car le syndicat l'interdit toujours", "Non, car le salarié est subordonné en tout"], "La subordination est limitée à l'exécution du travail.", 4),
    ("Un employeur muni de preuves limitées licencie un salarié en l'accusant de vol, sans enquête sérieuse. Quelle question juridique se pose ?", "Celle du caractère réel et sérieux du motif invoqué", ["Celle de la liberté d'entreprendre de l'employeur", "Celle de la compétence du ministre de l'intérieur", "Celle de la validité de la clause de mobilité", "Celle de l'existence d'une convention collective"], "Le motif doit être réel (existant) et sérieux (suffisamment grave) en droit français.", 4),
    ("Qui supporte, de façon générale, la charge du risque économique de l'entreprise dans une relation de travail salariée ?", "L'employeur, non le salarié", ["Le salarié, qui perd son salaire en cas de pertes", "Le syndicat de l'entreprise", "L'inspecteur du travail", "Le juge des affaires du travail"], "Le salarié est payé même si l'entreprise n'est pas bénéficiaire ; le risque est à la charge de l'employeur.", 3),
    ("Quelle est la conséquence juridique d'un changement de lieu de travail imposé qui reste dans le même secteur géographique, sans clause de mobilité ?", "Il peut relever du pouvoir de direction de l'employeur", ["Il est nécessairement nul", "Il équivaut toujours à un licenciement", "Il est réservé au juge du travail", "Il exige toujours l'accord du syndicat"], "Dans le même secteur, le changement est en principe un simple changement des conditions de travail.", 5),
    ("Un employeur reproche à un salarié des propos tenus dans un cadre privé, sans lien avec son travail ni préjudice à l'entreprise. Quelle est la règle de principe ?", "Un fait de la vie privée n'est pas en principe une cause de sanction", ["Tout fait de la vie privée peut être sanctionné librement", "L'employeur peut toujours licencier pour la vie privée", "Le salarié ne peut pas avoir de vie privée", "Le contrat de travail couvre toute la vie du salarié"], "La vie personnelle ne peut fonder une sanction que si elle cause un trouble caractérisé à l'entreprise.", 4),
    ("L'employeur est lié par un accord d'entreprise plus favorable aux salariés que sa décision. Que doit-il faire ?", "Appliquer l'accord d'entreprise, plus favorable", ["Appliquer sa décision, qui est plus récente", "Appliquer ce que décide le syndicat", "Attendre la décision du juge dans tous les cas", "Ignorer l'accord"], "Une décision unilatérale ne peut remettre en cause un accord plus favorable.", 4),
], size=15)
