"""L1 droit, seconde vague : cas pratiques et qualifications (introduction, personnes, famille, successions, biens,
organisation judiciaire, preuve). Situations fictives, principes généraux de tradition civiliste (français / OHADA / Cameroun).
Aucun article, délai, seuil ni montant : tout est `review`, relecture par un juriste indispensable."""
from .sup_kit import *      # source, table, classify, mcq, fq, pairs, pick, cap

C = "l1-droit"
_mcq = mcq


def mcq(course, tpl, rows, *, cat, src, region="WORLD"):
    _mcq(course, tpl, [(q, cap(r), [cap(w) for w in ws], e, d) for q, r, ws, e, d in rows], cat=cat, src=src, region=region)


source("sup-cas-l1a", "Cas pratiques et qualifications : introduction, personnes, famille, successions, biens, justice, preuve",
       "cours de L1 droit", "Comparer avec un manuel d'introduction générale au droit, de droit des personnes, de la famille, des biens et d'organisation judiciaire.")
S = "sup-cas-l1a"

# =================================================================================================================================
# 1. INTRODUCTION : règle de droit, sources, hiérarchie, application des lois, qualification
# =================================================================================================================================
mcq(C, "cas-l1a-intro", [
    ("Ngono promet à une amie de l'accompagner au marché samedi, puis l'oublie. De quel type de règle relève surtout cette promesse ?",
     "D'une règle de courtoisie ou de morale, sans sanction juridique",
     ["D'une règle pénale, car toute promesse non tenue est punie", "D'une règle de droit administratif régissant les services publics", "D'une règle de droit commercial relative aux dettes"],
     "Sans intention de s'engager juridiquement ni sanction publique, une telle promesse reste en dehors du droit.", 2),
    ("Un automobiliste brûle un feu rouge. Qu'est-ce qui distingue surtout la règle violée d'une simple règle de politesse ?",
     "Son respect est garanti par une sanction imposée par l'autorité publique",
     ["Elle est enseignée dès l'enfance dans toutes les familles", "Elle n'existe que dans les grandes villes du pays", "Elle ne vise que les personnes ayant fait des études"],
     "La règle de droit se reconnaît à sa sanction organisée par l'État.", 2),
    ("Une loi interdit à toute personne de fumer dans un hôpital public, sans viser personne en particulier. Quel caractère de la règle de droit illustre cette formulation ?",
     "Le caractère général et abstrait",
     ["Le caractère facultatif", "Le caractère purement moral", "Le caractère individuel et ponctuel"],
     "La règle s'adresse à tous, pour un nombre indéterminé de situations.", 2),
    ("Dans un contrat de vente, les parties n'ont rien prévu sur le lieu de livraison, et la loi fixe une règle applicable à défaut de clause. Quelle est la nature de cette règle ?",
     "Supplétive",
     ["Impérative", "D'ordre public", "Pénale"],
     "Une règle supplétive ne joue que si les parties n'ont pas décidé autrement.", 2),
    ("Les parties à un bail décident qu'aucune règle de protection du locataire ne s'appliquera, alors que cette protection est d'ordre public. Que vaut cette clause ?",
     "Elle est écartée, car on ne peut pas déroger à une règle impérative",
     ["Elle est valable, car le contrat fait la loi des parties en tout", "Elle est valable si le locataire signe en présence d'un témoin", "Elle est valable mais seulement pour le premier loyer"],
     "Les règles impératives s'imposent aux volontés individuelles.", 3),
    ("Un juge refuse de statuer en disant que la loi est obscure et ne dit rien sur le cas qui lui est soumis. Quelle est en principe sa situation ?",
     "Il commet un déni de justice et doit trancher le litige",
     ["Il agit normalement, car le silence de la loi dispense de juger", "Il doit attendre qu'un nouveau texte soit voté", "Il peut renvoyer les plaideurs vers le chef de l'exécutif"],
     "Le juge ne peut refuser de juger sous prétexte du silence ou de l'obscurité de la loi.", 3),
    ("Dans une commune, depuis très longtemps, les bergers laissent passer leurs bêtes par un même chemin, et chacun pense que c'est obligatoire. Quel élément est présent pour parler de coutume ?",
     "Une pratique ancienne et constante accompagnée de la conviction qu'elle est obligatoire",
     ["Un texte voté par le parlement", "Une décision isolée d'un maire", "Un simple avantage financier tiré de la pratique"],
     "La coutume associe un élément matériel (pratique constante) et un élément psychologique (sentiment d'obligation).", 3),
    ("Dans un marché, il est habituel d'ajouter un petit fruit par achat, sans que personne s'y sente tenu juridiquement. De quoi s'agit-il ?",
     "D'un simple usage",
     ["D'une loi non écrite", "D'une règle constitutionnelle", "D'une jurisprudence de la cour suprême"],
     "L'usage est une pratique répandue, sans le sentiment d'obligation propre à la coutume.", 3),
    ("Un décret du gouvernement entre en contradiction avec une loi votée par le parlement. Quelle règle l'emporte en principe ?",
     "La loi, qui occupe un rang supérieur dans la hiérarchie des normes",
     ["Le décret, car il est plus récent et plus précis", "Ni l'un ni l'autre, car elles s'annulent mutuellement", "Celle que le tribunal préfère selon l'équité"],
     "Un acte réglementaire doit respecter la loi, qui lui est hiérarchiquement supérieure.", 2),
    ("Une loi ordinaire contredit la constitution du pays. Selon la hiérarchie des normes, que doit-on penser de cette loi ?",
     "Elle est irrégulière et peut être censurée par le juge constitutionnel compétent",
     ["Elle est régulière, car elle est plus précise que la constitution", "Elle devient la nouvelle constitution", "Elle est valable pour dix ans puis expire"],
     "La constitution est au sommet de la hiérarchie interne des normes.", 3),
    ("Un arrêté municipal contredit un décret national. Lequel doit être appliqué ?",
     "Le décret, car l'acte local ne peut contredire un acte national supérieur",
     ["L'arrêté, car il est plus proche des citoyens", "Chacun à moitié, en les combinant", "Aucun, jusqu'à la prochaine élection"],
     "Les actes des autorités locales sont subordonnés aux normes nationales.", 2),
    ("Un tribunal refuse d'appliquer un règlement qui viole une loi dans l'affaire dont il est saisi. Quelle fonction exerce-t-il ?",
     "Il écarte le texte inférieur illégal pour faire respecter la hiérarchie des normes",
     ["Il légifère à la place du parlement", "Il révise la constitution", "Il se prononce sur sa propre compétence territoriale"],
     "Le juge peut écarter un acte inférieur contraire à une norme supérieure.", 4),
    ("Une loi nouvelle est publiée aujourd'hui. Un contrat avait été conclu hier. En principe, à quoi la loi nouvelle s'applique-t-elle ?",
     "Aux situations nées après son entrée en vigueur, sans toucher en principe aux situations passées",
     ["À tous les contrats déjà conclus, qui sont refaits", "Seulement aux étrangers vivant dans le pays", "Seulement aux situations à venir portant sur des biens immeubles"],
     "Principe de non-rétroactivité de la loi nouvelle.", 3),
    ("Une loi pénale nouvelle supprime une infraction. Un prévenu est poursuivi pour des faits commis avant cette loi mais non encore jugés. Quelle solution est généralement admise ?",
     "La loi pénale plus douce s'applique, donc les poursuites tombent",
     ["Il est jugé selon l'ancienne loi, plus sévère", "Il doit payer une amende symbolique", "L'affaire est renvoyée à la prochaine législature"],
     "Rétroactivité de la loi pénale plus douce, exception admise au principe de non-rétroactivité.", 4),
    ("Une loi pénale nouvelle crée une infraction. Fotso a commis un acte la veille, qui n'était pas interdit. Peut-il être puni ?",
     "Non, car nul ne peut être puni pour un fait non incriminé au moment où il a été commis",
     ["Oui, car l'acte est contraire à la nouvelle loi", "Oui, mais avec une peine réduite de moitié", "Oui, si le juge estime l'acte dangereux"],
     "Principe de légalité des délits et des peines et non-rétroactivité de la loi pénale plus sévère.", 3),
    ("Abena est de nationalité camerounaise et séjourne à l'étranger. La question de son état et de sa capacité relève en principe de quelle idée en droit international privé ?",
     "Du rattachement à sa loi nationale selon la tradition de nombreux pays civilistes",
     ["De la loi du lieu où elle a acheté ses vêtements", "De la loi de la ville où elle est née, quel que soit le cas", "De la loi du premier pays qu'elle a visité"],
     "Le statut personnel est souvent rattaché à la loi nationale, mais cela varie selon les systèmes.", 5),
    ("Une loi promulguée est à publier. Pourquoi la publication est-elle indispensable ?",
     "Pour que la loi soit connue et opposable aux citoyens",
     ["Pour que le président du tribunal puisse la rédiger", "Pour que chaque citoyen donne son accord", "Pour supprimer les lois plus anciennes sur le même sujet"],
     "Nul n'est censé ignorer la loi suppose que celle-ci ait été publiée.", 2),
    ("Mbarga affirme qu'il ne savait pas qu'une loi publiée interdisait son comportement et demande à ne pas être sanctionné. Quel adage lui est opposé ?",
     "Nul n'est censé ignorer la loi",
     ["Le criminel tient le civil en l'état", "Specialia generalibus derogant", "Actori incumbit probatio"],
     "Une fois publiée, la loi est présumée connue de tous.", 2),
    ("Un texte général interdit la vente d'une substance, un texte spécial en autorise la vente par les pharmaciens. Quel adage guide la solution pour le pharmacien ?",
     "Le spécial déroge au général",
     ["La fraude corrompt tout", "Nul ne plaide par procureur", "L'accessoire suit le principal"],
     "Specialia generalibus derogant : la règle spéciale écarte la règle générale dans son domaine.", 3),
    ("Deux lois de même rang régissent le même sujet, la plus récente contredisant l'ancienne. Quelle règle de conflit dans le temps joue en principe ?",
     "La loi postérieure abroge la loi antérieure qui lui est contraire",
     ["La loi antérieure reste applicable pour toujours", "La plus longue des deux l'emporte", "Le juge choisit celle qu'il préfère"],
     "La loi nouvelle abroge expressément ou tacitement la loi ancienne incompatible.", 3),
    ("Une jeune juriste doit identifier la juridiction compétente avant de rédiger une demande. Elle procède donc à quelle opération ?",
     "Une qualification de la situation pour trouver la règle applicable",
     ["Une codification du droit local", "Une promulgation d'un texte", "Une abrogation d'une loi ancienne"],
     "Qualifier, c'est rattacher des faits à une catégorie juridique pour déterminer le régime applicable.", 3),
    ("Tchoumi remet son vélo à Ngono pour trois jours, et Ngono doit le lui rendre, sans paiement. Comment qualifier le plus exactement cette opération ?",
     "Un prêt à usage, contrat gratuit avec restitution de la chose",
     ["Une vente, transfert définitif de propriété contre un prix", "Un bail, car il y a toujours un loyer", "Une donation, car le vélo change de propriétaire"],
     "Le prêt à usage est gratuit et oblige à restituer la chose prêtée.", 3),
    ("Fotso remet de l'argent à Abena, qui doit lui rendre la même somme plus tard, sans que ce soit le même billet. Quelle qualification convient ?",
     "Un prêt de consommation, car l'emprunteur devient propriétaire et rend des choses équivalentes",
     ["Un prêt à usage, car la chose est rendue identique", "Un dépôt, car on garde l'argent à l'identique", "Une location, car l'argent sert un temps limité"],
     "Dans le prêt de consommation, on rend la même quantité de choses fongibles, non la chose elle-même.", 4),
    ("Le droit de vote est reconnu aux citoyens, le droit de propriété aux propriétaires. Comment qualifier ces prérogatives ?",
     "Des droits subjectifs",
     ["Des règles impératives", "Des sanctions pénales", "Des sources du droit objectif"],
     "Un droit subjectif est une prérogative attachée à une personne.", 2),
    ("Dans la phrase « Le droit encadre la vente », de quel droit parle-t-on ?",
     "Du droit objectif, ensemble de règles",
     ["D'un droit subjectif, prérogative d'une personne", "D'un droit naturel exclusivement", "D'un droit de créance"],
     "Le droit objectif est l'ensemble des règles ; le droit subjectif est la prérogative qui en découle.", 2),
    ("Une loi autorise un ministre à prendre des mesures détaillées pour l'appliquer. Quelle forme prennent ces mesures ?",
     "D'actes réglementaires, subordonnés à la loi",
     ["D'une révision de la constitution", "D'une coutume", "D'un jugement"],
     "Les règlements d'application détaillent les lois sans pouvoir les contredire.", 3),
    ("Les tribunaux d'un pays tranchent régulièrement un même problème de la même façon, sans qu'aucun texte l'impose. Comment appelle-t-on cette source possible du droit ?",
     "La jurisprudence",
     ["La doctrine", "La codification", "La promulgation"],
     "La jurisprudence est l'ensemble des solutions des juridictions ; son autorité varie selon les systèmes.", 2),
    ("Des professeurs de droit publient un commentaire critique d'un arrêt. À quoi correspond cette production ?",
     "De la doctrine",
     ["De la jurisprudence", "Une loi organique", "Une coutume"],
     "La doctrine est l'opinion des auteurs ; elle n'est pas obligatoire mais peut influencer.", 2),
    ("Un tribunal rend un jugement qui ne concerne que Mbarga et Fotso. Pourquoi ne s'agit-il pas d'une règle de droit générale ?",
     "Il ne vaut que pour les parties au litige jugé, et non pour toute situation semblable",
     ["Parce qu'un jugement n'est jamais écrit", "Parce qu'il est rendu en dehors du pays", "Parce qu'il dépend du bon vouloir du greffier"],
     "Le jugement est une décision individuelle, à la différence de la loi, générale et abstraite.", 3),
    ("Un traité international régulièrement ratifié et publié est invoqué contre une loi interne. Dans la logique de nombreux États civilistes, que dit en principe la hiérarchie ?",
     "Il prime la loi, souvent sous condition de réciprocité",
     ["Le traité est toujours inférieur aux décrets", "Le traité est supérieur à la constitution dans tous les cas", "Le traité est sans effet dans l'ordre interne"],
     "Beaucoup de constitutions placent les traités ratifiés au-dessus des lois, mais sous la constitution.", 4),
    ("Dans un manuel, on lit : « le droit privé règle les rapports entre particuliers ». Quel exemple relève bien du droit privé ?",
     "Un litige entre deux voisins au sujet d'un mur mitoyen",
     ["La procédure de vote du budget par le parlement", "L'organisation du ministère de la Défense", "Le recensement fait par l'administration"],
     "Le droit civil encadre les rapports entre particuliers.", 2),
    ("Lequel de ces faits relève du droit public ?",
     "Un maire prend un arrêté pour réglementer la circulation dans sa commune",
     ["Deux associés fixent la répartition de leurs bénéfices", "Un locataire négocie son loyer avec son bailleur", "Un père reconnaît son enfant"],
     "Le droit public régit l'organisation de l'État et des collectivités et leurs rapports avec les particuliers.", 2),
    ("Une société vend des produits à un client et refuse de livrer. Le litige relève surtout de quelle branche ?",
     "Du droit privé, droit des contrats et droit commercial",
     ["Du droit constitutionnel", "Du droit administratif exclusivement", "Du droit international public"],
     "Il s'agit d'un rapport entre personnes privées.", 2),
    ("Qu'est-ce qui différencie surtout le droit pénal du droit civil dans un litige ?",
     "Le pénal punit une atteinte à l'ordre public, le civil règle des intérêts privés",
     ["Le droit pénal ne concerne que les entreprises", "Le droit civil ne prévoit aucune sanction", "Le droit pénal n'existe que pour les mineurs"],
     "Le pénal protège l'intérêt de la société, le civil protège surtout les intérêts particuliers.", 3),
    ("Une personne cause un dommage à sa voisine par imprudence et doit l'indemniser. Quelle est la nature de cette sanction ?",
     "Une sanction civile, visant à réparer le préjudice",
     ["Une sanction disciplinaire", "Une sanction administrative de police", "Une sanction constitutionnelle"],
     "La responsabilité civile a pour but de réparer.", 2),
    ("Un commerçant est condamné à une peine de prison pour avoir volé. Quelle sanction est ici en cause ?",
     "Une sanction pénale, qui punit l'auteur d'une infraction",
     ["Une réparation civile uniquement", "Une nullité de contrat", "Une sanction fiscale"],
     "Les peines privatives de liberté sont des sanctions pénales.", 2),
    ("Un contrat est déclaré nul par le juge parce qu'une condition de validité manquait. De quelle sorte de sanction s'agit-il ?",
     "Une sanction civile consistant à anéantir l'acte",
     ["Une peine d'emprisonnement", "Une amende pénale", "Une sanction disciplinaire du barreau"],
     "La nullité efface l'acte irrégulier.", 3),
    ("Un officier public refuse de rédiger un acte sans motif légitime. Quelle sanction viserait le plus directement à contraindre l'exécution de l'obligation d'agir ?",
     "Une mesure d'exécution forcée ou une astreinte, selon les cas",
     ["Un divorce", "Une adoption", "Une tutelle"],
     "Le droit prévoit des moyens d'obtenir l'exécution forcée d'une obligation.", 4),
    ("Lequel de ces éléments est un exemple de source écrite et formelle du droit ?",
     "Une loi votée et publiée",
     ["Une habitude locale non reconnue", "Un conseil donné par un voisin", "Une rumeur de quartier"],
     "La loi est la source écrite principale dans les systèmes civilistes.", 1),
    ("Dans un pays civiliste, quelle est traditionnellement la source principale du droit ?",
     "La loi écrite",
     ["La seule coutume orale", "Le précédent d'un seul juge", "Les opinions personnelles des avocats"],
     "Les systèmes de tradition romano-germanique accordent la primauté à la loi écrite.", 2),
    ("À l'inverse, dans un système de common law, quelle source joue un rôle central ?",
     "Le précédent judiciaire",
     ["Le code unique de la matière", "L'avis des conseillers municipaux", "Les règlements de copropriété"],
     "Dans la common law, la règle du précédent oblige les juges à suivre les décisions antérieures.", 3),
    ("Un acte uniforme de l'OHADA s'applique dans les États membres. Quelle particularité présente-t-il en général ?",
     "Il est directement applicable et prime les règles internes contraires",
     ["Il n'a d'effet qu'après vote d'une loi nationale distincte", "Il ne concerne que les affaires pénales", "Il ne vaut que pour les ressortissants du pays le plus peuplé"],
     "Les actes uniformes sont directement applicables et obligatoires dans les États parties de l'OHADA.", 4),
    ("Un étudiant doit retrouver la règle applicable à une situation de fait précise. Quelle est l'ordre logique habituel d'un raisonnement juridique ?",
     "Établir les faits, qualifier, identifier la règle, l'appliquer, conclure",
     ["Conclure, puis chercher les faits, puis la règle", "Appliquer la règle, puis qualifier les faits", "Citer la jurisprudence, puis ignorer la règle"],
     "Le syllogisme juridique va des faits et de leur qualification à la conclusion.", 3),
    ("Dans un syllogisme juridique, que représente la majeure ?",
     "La règle de droit applicable",
     ["Les faits de l'espèce", "La conclusion du juge", "L'avis d'un témoin"],
     "La majeure pose la règle, la mineure les faits, la conclusion la solution.", 3),
    ("Un juge applique la règle « le vendeur doit délivrer la chose » à la situation de Ngono, qui n'a pas livré. Quelle est la mineure du raisonnement ?",
     "Ngono, vendeur, n'a pas livré la chose vendue",
     ["Le vendeur doit délivrer la chose vendue", "Ngono doit donc être condamné à exécuter", "La vente est un contrat consensuel"],
     "La mineure est le constat de fait qui relève de la règle.", 4),
], cat="Introduction au droit : cas et qualifications", src=S)

# =================================================================================================================================
# 2. PERSONNES PHYSIQUES ET MORALES
# =================================================================================================================================
mcq(C, "cas-l1a-pers", [
    ("Un bébé naît vivant et viable, puis décède quelques heures plus tard. A-t-il pu acquérir des droits pendant ce temps ?",
     "Oui, la personnalité juridique naît avec la naissance vivante et viable",
     ["Non, car il faut avoir vécu plusieurs années pour avoir des droits", "Non, la personnalité ne s'acquiert qu'à la majorité", "Oui, mais seulement des droits d'ordre pénal"],
     "La personnalité juridique est acquise dès la naissance vivante et viable, et dure jusqu'au décès.", 3),
    ("Une femme enceinte décède, laissant un legs à l'enfant qu'elle porte. À la naissance, l'enfant naît vivant et viable. Que peut-on dire ?",
     "L'enfant conçu peut bénéficier du legs, car on le considère comme né quand son intérêt l'exige",
     ["Le legs est nul, car il n'existait pas au décès de la testatrice", "Le legs est caduc, car l'enfant n'avait pas d'état civil", "Le legs profite à la famille, jamais à l'enfant"],
     "L'adage infans conceptus permet de faire bénéficier l'enfant conçu des droits qui lui sont favorables.", 4),
    ("Ngono, 12 ans, achète seule un cahier avec son argent de poche. Cette vente est-elle en principe valable ?",
     "Oui, c'est un acte de la vie courante que l'usage permet au mineur d'accomplir",
     ["Non, tout acte d'un mineur est nul de plein droit sans exception", "Non, car un mineur ne peut jamais détenir d'argent", "Oui, mais seulement si le juge a donné son autorisation"],
     "Les actes courants de faible importance faits par un mineur sont valables selon l'usage (droit français).", 3),
    ("Un mineur de 14 ans vend seul le terrain de ses parents à un voisin, sans autorisation. Quel est le sort probable de cet acte ?",
     "Il est annulable, car le mineur n'a pas la capacité de disposer d'un tel bien",
     ["Il est valable, car le voisin était de bonne foi", "Il est valable, car le terrain appartient à la famille", "Il est inexistant pour toute la procédure à venir"],
     "Un mineur ne peut pas accomplir seul un acte de disposition ; de plus, le terrain ne lui appartient pas.", 3),
    ("Une personne atteinte d'une altération grave de ses facultés est placée sous tutelle. Que fait en principe le tuteur ?",
     "Il la représente dans les actes de la vie civile",
     ["Il l'assiste en signant à côté d'elle sur chaque acte", "Il décide seulement de ses loisirs", "Il remplace le juge pour trancher ses litiges"],
     "La tutelle est un régime de représentation continue, la curatelle un régime d'assistance.", 3),
    ("Fotso, placé sous curatelle, veut vendre un bien important. Quel est le rôle du curateur ?",
     "L'assister, c'est-à-dire l'accompagner pour valider l'acte",
     ["Agir seul et à sa place pour tout acte", "Rester spectateur sans pouvoir intervenir", "Rendre un jugement sur la vente"],
     "En curatelle, la personne agit elle-même mais avec l'assistance de son curateur pour les actes graves.", 3),
    ("Quelle mesure de protection est temporaire et destinée à une personne dont les facultés sont gênées de façon passagère ?",
     "La sauvegarde de justice",
     ["La tutelle ordinaire", "L'émancipation", "L'adoption plénière"],
     "La sauvegarde de justice est une protection provisoire (droit français).", 4),
    ("Que peut en principe accomplir seul un mineur émancipé ?",
     "Les actes de la vie civile qu'un majeur peut faire, avec quelques limites légales",
     ["Aucun acte, car l'émancipation est une punition", "Seulement les actes de son propre mariage", "Uniquement des actes devant le tribunal"],
     "L'émancipation donne au mineur une capacité proche de celle du majeur, avec des exceptions.", 4),
    ("Tchoumi change de ville pour s'installer durablement avec sa famille et y a son principal établissement. Où est son domicile, en règle générale ?",
     "Au lieu de son principal établissement, c'est-à-dire sa nouvelle ville",
     ["Dans la ville où elle est née, quoi qu'elle fasse", "Au lieu où elle passe ses vacances", "À l'adresse de son employeur uniquement"],
     "Le domicile est le lieu du principal établissement de la personne.", 2),
    ("Un étudiant loue une chambre loin de chez ses parents pour la durée de l'année et y vit, mais garde son principal établissement chez eux. Comment qualifier cette chambre ?",
     "Sa résidence, simple lieu où il habite",
     ["Son domicile légal exclusif", "Son siège social", "Son état civil"],
     "La résidence est le lieu où l'on vit de fait, distincte du domicile.", 3),
    ("Dans un contrat, Abena choisit pour recevoir les notifications l'adresse de son avocat. De quoi s'agit-il ?",
     "D'un domicile élu",
     ["D'un domicile légal", "D'une résidence habituelle", "D'un siège social"],
     "Le domicile élu est choisi par les parties pour l'exécution d'un acte.", 3),
    ("Un officier d'état civil dresse un acte pour constater une naissance. Quelle est la fonction principale de cet acte ?",
     "Prouver officiellement la naissance et certains éléments de l'identité",
     ["Fixer le salaire de l'enfant", "Organiser la succession des parents", "Désigner le tuteur pour toute la vie"],
     "Les actes d'état civil constatent les événements qui concernent l'état des personnes.", 2),
    ("Une erreur matérielle a été faite sur l'orthographe d'un nom dans un acte de naissance. Que faut-il faire en règle générale ?",
     "Demander la rectification de l'acte, le plus souvent par une décision de justice",
     ["Rien, car les actes d'état civil ne sont jamais modifiables", "Changer de nom librement sans aucune formalité", "Effacer le registre soi-même"],
     "La rectification passe par l'autorité compétente, en général judiciaire.", 3),
    ("On dit que le nom est indisponible. Que signifie cette idée ?",
     "On ne peut pas le vendre ni en faire commerce librement",
     ["On peut le céder à n'importe quel acheteur", "On peut le perdre par simple oubli", "On peut le fixer à sa guise chaque année"],
     "Le nom est un attribut de la personnalité, hors du commerce, protégé par la loi.", 4),
    ("Un journal publie sans autorisation la photo d'Abena en gros plan, accompagnée d'un article sans rapport avec elle. Quel droit est atteint ?",
     "Son droit à l'image, droit de la personnalité",
     ["Son droit de propriété sur un meuble", "Son droit de créance sur le journal", "Son droit de vote"],
     "Toute personne a un droit sur son image, sauf justification légitime.", 3),
    ("Un voisin filme à travers sa fenêtre l'intérieur de la maison de Mbarga et diffuse la vidéo. Quel principe est méconnu ?",
     "Le respect de la vie privée",
     ["Le principe de non-rétroactivité", "L'autorité de la chose jugée", "Le principe de l'oralité des débats"],
     "La vie privée est protégée au titre des droits de la personnalité.", 2),
    ("Quelle différence y a-t-il entre la capacité de jouissance et la capacité d'exercice ?",
     "La première est l'aptitude à avoir des droits, la seconde à les exercer soi-même",
     ["La première concerne les mineurs, la seconde les majeurs uniquement", "La première est volontaire, la seconde est forcée", "La première est pénale, la seconde est fiscale"],
     "La personne protégée garde la jouissance de ses droits mais peut ne pas pouvoir les exercer seule.", 3),
    ("Une loi interdit à un tuteur d'acheter les biens de la personne qu'il protège. Que vise surtout cette interdiction ?",
     "Protéger la personne placée sous tutelle contre un conflit d'intérêts",
     ["Punir le tuteur pour une infraction passée", "Empêcher la personne protégée de vendre", "Réduire les impôts de la famille"],
     "Il s'agit d'une incapacité de défiance : on soupçonne un conflit d'intérêts.", 5),
    ("Un mineur est assisté par un représentant légal pour accepter une succession. Comment qualifie-t-on l'intervention du parent ou du tuteur ?",
     "Une représentation, car il agit au nom et pour le compte du mineur",
     ["Une usurpation d'identité, car il parle en son nom", "Une adoption, car il lui donne un nom", "Une novation, car il change la dette"],
     "Le représentant légal fait l'acte à la place du mineur.", 3),
    ("Une personne disparaît sans nouvelles depuis très longtemps, sans qu'on sache si elle est en vie. Quelle procédure est prévue pour régler la situation de ses biens ?",
     "La constatation judiciaire de l'absence, puis éventuellement de la mort présumée",
     ["La vente de tous ses biens par ses voisins", "Le partage immédiat entre ses amis", "La saisie par la police de tout son patrimoine"],
     "Le droit encadre l'absence : présomption d'absence, déclaration d'absence, puis jugement déclaratif de décès.", 4),
    ("Dans quel cas la personnalité juridique d'une personne physique prend-elle fin ?",
     "Au décès constaté de la personne",
     ["Au départ de la personne à l'étranger", "À la perte de son emploi", "À son divorce"],
     "La mort met fin à la personnalité ; l'absence prolongée ne suffit qu'à certaines conditions.", 2),
    ("Une association est déclarée selon les règles de la loi et possède un patrimoine, un nom, un siège. Que peut-on dire de ses actes juridiques ?",
     "Elle peut contracter et agir en justice, car elle est une personne morale",
     ["Elle ne peut agir qu'à travers chacun de ses membres sans exception", "Elle ne peut jamais posséder d'argent", "Elle n'a pas de responsabilité juridique"],
     "La personne morale est titulaire de droits et d'obligations distincts de ceux de ses membres.", 3),
    ("Le patrimoine d'une société commerciale est distinct de celui de ses associés. D'où résulte cette séparation ?",
     "De la personnalité morale",
     ["De la nationalité des associés", "De l'état civil des dirigeants", "Du domicile des clients"],
     "L'autonomie patrimoniale découle de la personnalité morale.", 3),
    ("Selon le droit des sociétés de l'OHADA, à partir de quel moment une société commerciale acquiert-elle en principe la personnalité morale ?",
     "À compter de son immatriculation au registre du commerce et du crédit mobilier",
     ["Dès que l'un des associés en a l'idée", "Dès la rédaction d'un brouillon de statuts", "À la première réunion informelle des associés"],
     "L'immatriculation donne la personnalité juridique à la société (droit OHADA).", 4),
    ("Une commune camerounaise signe un marché avec une entreprise. Quel type de personne est-elle ?",
     "Une personne morale de droit public",
     ["Une personne physique", "Une société commerciale", "Une association de fait"],
     "Les collectivités territoriales décentralisées sont des personnes morales de droit public.", 2),
    ("Un tribunal dissout une association qui poursuivait un but contraire à la loi. Que devient en principe sa personnalité morale ?",
     "Elle prend fin, et on procède à la liquidation de son patrimoine",
     ["Elle passe aux membres sous forme de nom commun", "Elle se maintient indéfiniment", "Elle se transforme en personne physique"],
     "La dissolution entraîne la liquidation puis la disparition de la personne morale.", 3),
    ("Un dirigeant signe, au nom d'une société et dans les limites de ses pouvoirs, un contrat de fourniture. Qui est en principe engagé ?",
     "La société, personne morale représentée par son dirigeant",
     ["Le dirigeant seul, à titre personnel et pour toujours", "Les clients de la société", "Le notaire du dirigeant"],
     "La personne morale agit par ses organes, qui engagent la société dans la limite de leurs pouvoirs.", 3),
    ("Un groupe de voisins se réunit régulièrement pour organiser des fêtes, sans aucune déclaration ni statut. Quelle est la situation juridique la plus probable ?",
     "Un groupement de fait, sans personnalité morale",
     ["Une société anonyme cotée", "Une collectivité territoriale", "Une juridiction populaire"],
     "Sans formalités de constitution, le groupe n'a pas la personnalité morale.", 4),
    ("Lequel de ces groupements a pour but de partager des bénéfices entre associés ?",
     "Une société",
     ["Une association à but non lucratif", "Une commune", "Un syndicat de salariés"],
     "La société est constituée en vue de partager les bénéfices ou de profiter de l'économie réalisée.", 2),
    ("Lequel de ces groupements n'a pas, en principe, pour objet de partager des bénéfices entre ses membres ?",
     "Une association",
     ["Une société en nom collectif", "Une société anonyme", "Une société à responsabilité limitée"],
     "L'association poursuit un but autre que le partage de bénéfices.", 2),
    ("Une personne pense qu'elle peut être poursuivie parce qu'elle a la personnalité juridique mais refuse de comparaître au prétexte qu'elle est mineure. Que peut-on lui répondre ?",
     "Le mineur peut être partie à un procès, représenté par ses parents ou un tuteur",
     ["Le mineur ne peut jamais être partie à un procès", "Le mineur est jugé sans aucune représentation", "Le mineur doit attendre sa majorité pour toute procédure"],
     "Le mineur a la jouissance de ses droits ; il agit en justice par son représentant légal.", 4),
    ("Dans un acte, un mari et une femme sont désignés comme époux. Quelle information appartient à l'état de la personne ?",
     "Sa situation matrimoniale",
     ["Son salaire du mois", "Son adresse de messagerie", "La couleur de sa voiture"],
     "L'état des personnes recouvre la nationalité, la filiation, la situation matrimoniale, etc.", 3),
    ("Lequel de ces éléments fait partie de l'état d'une personne ?",
     "Sa filiation",
     ["Son niveau de revenus", "Son nombre d'abonnés en ligne", "Sa marque de téléphone"],
     "La filiation est un élément de l'état, qui échappe en principe à la volonté privée.", 2),
    ("Les actions relatives à l'état des personnes, comme la nationalité ou la filiation, peuvent-elles faire l'objet d'une simple transaction entre particuliers ?",
     "Non, l'état des personnes est en principe indisponible",
     ["Oui, en échange d'une somme d'argent", "Oui, mais seulement le dimanche", "Oui, devant témoin sans formalité"],
     "L'état est indisponible : on ne peut ni le vendre ni y renoncer librement.", 4),
    ("Que se passe-t-il, en principe, lorsqu'un mineur non émancipé contracte un prêt important sans que son représentant ne l'ait autorisé ?",
     "L'acte peut être annulé pour incapacité, à la demande du mineur ou de son représentant",
     ["L'acte est valable car le prêteur a fait confiance au mineur", "L'acte est valable si le mineur dit avoir l'âge", "L'acte est annulé uniquement par le procureur"],
     "La nullité pour incapacité protège le mineur ; elle est dite relative.", 4),
    ("Un homme change fréquemment de nom d'usage selon ses besoins dans ses affaires, sans aucune démarche. Quelle règle fondamentale du nom cette pratique méconnaît-elle ?",
     "Le nom est fixé par la filiation et ne se change que par une procédure légale",
     ["Le nom est fixé chaque année par le maire", "Le nom est libre de changement en tout cas", "Le nom dépend du métier de la personne"],
     "Le principe est l'immutabilité du nom, sauf procédure de changement.", 4),
    ("Dans une famille, l'enfant de Mbarga porte le nom de son père. Quel lien le nom manifeste-t-il en priorité ?",
     "Le lien de filiation",
     ["Le lien de propriété", "Le lien de créance", "Le lien de voisinage"],
     "Le nom a pour fonction principale d'identifier la personne et de signaler sa filiation.", 2),
    ("Un tuteur vend un bien du mineur protégé sans autorisation du conseil de famille ou du juge, alors qu'elle est exigée. Que risque l'acte ?",
     "Il peut être annulé pour défaut d'autorisation",
     ["Il est valable car le tuteur est le représentant légal", "Il est valable si l'acheteur le dit", "Il est inexistant dans l'ordre pénal"],
     "Certains actes graves nécessitent l'autorisation d'un organe de contrôle.", 5),
    ("En droit des personnes, quel est le but de l'incapacité de protection ?",
     "Protéger la personne qui en est atteinte contre ses propres erreurs",
     ["Punir la personne pour un comportement répréhensible", "Protéger les créanciers contre la personne", "Réserver certains actes aux seuls avocats"],
     "L'incapacité de protection est mise en place dans l'intérêt de la personne protégée.", 3),
    ("Un enfant a sa résidence habituelle chez sa mère mais ses parents vivent séparés. Où est en règle générale son domicile légal ?",
     "Chez ses parents, ou chez celui qui exerce l'autorité parentale de façon principale",
     ["Dans l'école qu'il fréquente", "Au tribunal de sa ville", "Dans la mairie de naissance"],
     "Le domicile légal du mineur se rattache à ses parents ou à son représentant.", 5),
    ("Un homme conteste son identité devant l'administration. Quelle pièce est le premier moyen de prouver officiellement sa naissance ?",
     "Une copie de l'acte de naissance délivrée par l'officier d'état civil",
     ["Une photo de lui enfant", "Une attestation de son voisin", "Un contrat de bail"],
     "L'acte de naissance fait foi de la naissance et des mentions qu'il porte.", 2),
    ("Une personne morale de droit privé peut-elle être titulaire d'un droit de propriété ?",
     "Oui, elle peut posséder des biens, dont le patrimoine est distinct de celui de ses membres",
     ["Non, seuls les êtres humains peuvent être propriétaires", "Non, sauf si elle est une commune", "Oui, mais seulement des biens immeubles"],
     "La personnalité morale permet d'être propriétaire.", 3),
    ("Une société est condamnée à payer des dommages et intérêts. Qui supporte en principe la dette sur son patrimoine ?",
     "La société, sur son propre patrimoine",
     ["Chaque salarié sur ses propres biens", "Le juge qui a prononcé la peine", "Le registre du commerce"],
     "La dette de la personne morale est d'abord payée sur son patrimoine propre.", 3),
    ("Un syndicat de salariés agit en justice pour défendre l'intérêt collectif de la profession. Quelle qualité lui permet d'agir ?",
     "Sa personnalité morale, qui lui donne qualité pour agir",
     ["Sa qualité de juge en matière de travail", "Sa nationalité étrangère", "Son rang dans la hiérarchie des normes"],
     "Les groupements dotés de la personnalité morale peuvent agir en justice pour défendre leurs intérêts collectifs.", 4),
    ("Quelle différence essentielle entre une fondation et une association ?",
     "La fondation affecte des biens à une œuvre, l'association réunit des personnes",
     ["La fondation n'a jamais de patrimoine, l'association en a toujours un", "La fondation partage ses bénéfices, l'association non", "La fondation est une personne physique"],
     "Une fondation affecte un patrimoine à un but d'intérêt général ; une association regroupe des personnes.", 5),
    ("Une personne morale peut-elle se marier ?",
     "Non, certains droits sont attachés à la personne humaine et lui sont réservés",
     ["Oui, avec une autre société seulement", "Oui, si le tribunal l'autorise toujours", "Oui, si elle est une commune"],
     "La personne morale n'a pas les droits liés à la nature de l'être humain, comme le mariage.", 3),
    ("Dans le cadre d'une tutelle, qui contrôle le plus souvent le tuteur ?",
     "Un juge ou un organe de contrôle, comme le conseil de famille",
     ["Le plus proche voisin du tuteur", "Un huissier désigné au hasard", "Le dernier banquier consulté"],
     "La tutelle est placée sous le contrôle de la justice ou d'un organe familial.", 4),
    ("Que protège principalement la présomption d'innocence ?",
     "Toute personne soupçonnée, tenue pour non coupable tant que sa culpabilité n'est pas établie",
     ["Les seuls magistrats dans leurs fonctions", "Les victimes d'une infraction", "Les témoins en cours d'audition"],
     "La présomption d'innocence est un droit fondamental de la personne poursuivie.", 2),
], cat="Personnes : cas et qualifications", src=S)

# =================================================================================================================================
# 3. FAMILLE
# =================================================================================================================================
mcq(C, "cas-l1a-fam", [
    ("Abena a été contrainte d'accepter un mariage sous la menace de sa famille. Quelle est en principe la conséquence juridique ?",
     "Le mariage est annulable, car le consentement n'a pas été libre",
     ["Le mariage est valable, car la menace vient de proches du couple", "Le mariage est sans effet, comme une simple promesse sans suite", "Le mariage est valable mais doit être renouvelé chaque année"],
     "Le consentement libre des époux est une condition de fond du mariage ; la violence le vicie.", 3),
    ("Un homme et une femme vivent ensemble depuis longtemps sans s'être mariés. Quel terme désigne cette situation ?",
     "Le concubinage, union de fait sans les effets du mariage",
     ["Le mariage coutumier de plein droit pour tous les États", "L'adoption réciproque, valable devant un notaire", "La séparation de corps, décidée par le juge"],
     "Le concubinage est une union de fait, qui ne produit pas les effets du mariage.", 2),
    ("Deux époux vivent séparés par décision de justice, mais restent mariés et ne peuvent se remarier. De quoi s'agit-il ?",
     "D'une séparation de corps",
     ["D'un divorce prononcé", "D'une nullité du mariage", "D'une émancipation des époux"],
     "La séparation de corps relâche les devoirs de vie commune mais maintient le lien conjugal.", 3),
    ("Quelle différence essentielle entre divorce et nullité du mariage ?",
     "Le divorce dissout un mariage valable, la nullité sanctionne un vice de formation",
     ["Le divorce efface le mariage depuis son début, la nullité ne vaut que pour l'avenir", "Le divorce concerne les enfants, la nullité les biens", "Le divorce est célébré à la mairie, la nullité au tribunal"],
     "Le divorce met fin pour l'avenir à un mariage régulier ; la nullité vise un mariage entaché d'un défaut originel.", 4),
    ("Ngono et Tchoumi sont mariés et Ngono dissimule ses revenus à Tchoumi, qui subvient seule aux charges. Quel devoir du mariage est le plus directement en cause ?",
     "Le devoir de contribuer aux charges du ménage",
     ["Le devoir de porter le même nom", "Le devoir de cohabiter dans une même ville", "Le devoir d'élever des enfants ensemble"],
     "Les époux contribuent aux charges du mariage selon leurs facultés.", 3),
    ("Un époux abandonne durablement sa famille sans aucune justification, laissant l'autre sans ressources. Quel devoir du mariage méconnaît-il ?",
     "Le devoir de secours et d'assistance",
     ["Le devoir de mémoire familiale", "Le devoir de publicité du mariage", "Le devoir de neutralité"],
     "Le secours et l'assistance sont des devoirs matériels et moraux entre époux.", 3),
    ("Des époux mariés sous le régime de la séparation de biens : Fotso achète une maison avec ses seuls revenus. À qui appartient-elle en principe ?",
     "À Fotso seul, car chaque époux conserve ses biens personnels",
     ["Aux deux époux à parts égales dans tous les cas", "À leurs enfants nés du mariage", "À l'État tant que les époux sont mariés"],
     "Dans la séparation de biens, chaque époux garde la propriété et la gestion de ses biens.", 3),
    ("Dans un régime de communauté réduite aux acquêts (droit français), Mbarga possédait avant le mariage un terrain. Quel est son statut après le mariage ?",
     "Un bien propre de Mbarga",
     ["Un bien commun aux deux époux d'office", "Un bien de l'État conjugal", "Un bien indivis avec les parents de Mbarga"],
     "Les biens possédés avant le mariage restent propres dans ce régime.", 4),
    ("Dans ce même régime, deux époux achètent pendant le mariage un véhicule avec le salaire de l'un. Quel est en principe son caractère ?",
     "Un bien commun, car acquis pendant le mariage avec des gains",
     ["Un bien propre de l'époux qui l'utilise le plus souvent", "Un bien appartenant au créancier du salarié", "Un bien indivis avec les voisins"],
     "Les gains et les acquisitions faites pendant le mariage tombent dans la communauté.", 4),
    ("Une femme met au monde un enfant pendant son mariage. Quel mari est en principe présumé père, selon les règles civilistes ?",
     "Son mari, en vertu de la présomption de paternité",
     ["L'homme qui habite le plus près", "Le mari de sa sœur", "Le père de la mère"],
     "Pater is est quem nuptiae demonstrant : le mari de la mère est présumé le père.", 3),
    ("Un homme déclare volontairement devant l'officier d'état civil qu'il est le père d'un enfant né hors mariage. Quel est ce mode d'établissement de la filiation ?",
     "La reconnaissance volontaire",
     ["L'adoption plénière", "La légitimation par la loi", "La tutelle officieuse"],
     "La reconnaissance est un acte unilatéral et volontaire établissant la filiation.", 3),
    ("Quel est l'effet principal d'une adoption plénière en droit français ?",
     "Rompre en principe le lien avec la famille d'origine pour créer un lien complet avec l'adoptant",
     ["Maintenir tous les liens avec la famille d'origine sans rien ajouter", "Créer un simple lien alimentaire temporaire", "Éteindre la personnalité de l'enfant"],
     "L'adoption plénière substitue une filiation nouvelle à la filiation d'origine ; la simple s'y ajoute.", 4),
    ("En droit français, quelle est la différence entre adoption simple et adoption plénière quant aux liens d'origine ?",
     "Dans l'adoption simple, l'adopté conserve ses liens avec sa famille d'origine",
     ["Dans l'adoption simple, l'adopté coupe tout lien avec ses parents d'origine", "Dans l'adoption plénière, l'adopté garde deux familles juridiques", "Il n'existe aucune différence entre elles"],
     "L'adoption simple s'ajoute à la filiation d'origine ; la plénière la remplace.", 4),
    ("Dans le divorce de ses parents, un juge doit statuer sur l'organisation de la vie de l'enfant. Quel critère guide sa décision avant tout ?",
     "L'intérêt supérieur de l'enfant",
     ["Le souhait de l'époux le plus riche", "L'ancienneté du mariage", "Le choix du voisinage"],
     "L'intérêt de l'enfant est le principe directeur des décisions relatives à l'autorité parentale.", 2),
    ("Qu'est-ce que l'autorité parentale ?",
     "Un ensemble de droits et de devoirs des parents pour protéger l'enfant et assurer son éducation",
     ["Un pouvoir absolu et discrétionnaire sur la personne de l'enfant", "Un droit propre à l'État de choisir l'école", "Un droit de succession réservé aux parents"],
     "Elle est conçue comme une fonction exercée dans l'intérêt de l'enfant.", 3),
    ("Un père, même séparé de la mère, refuse de contribuer à l'entretien de son enfant. Quel devoir est violé ?",
     "L'obligation d'entretien et d'éducation de l'enfant",
     ["L'obligation de publicité du mariage", "L'obligation de dot", "L'obligation de domicile conjugal"],
     "Les parents doivent entretenir et éduquer leurs enfants, même séparés.", 2),
    ("Un adulte en grande difficulté demande une pension à son fils majeur qui en a les moyens. Sur quelle règle repose la demande ?",
     "L'obligation alimentaire entre parents en ligne directe",
     ["La réserve héréditaire", "La communauté légale", "La garde de l'enfant"],
     "L'obligation alimentaire joue entre certains parents ; elle dépend des besoins et des ressources.", 3),
    ("Comment est en principe fixée la pension alimentaire ?",
     "Selon les besoins de celui qui la demande et les ressources de celui qui la doit",
     ["Selon la seule volonté du débiteur", "Selon la valeur du domicile du créancier", "Selon un tarif identique pour tous"],
     "L'obligation alimentaire s'adapte aux besoins du créancier et aux ressources du débiteur.", 3),
    ("Un officier d'état civil apprend qu'un candidat au mariage est déjà marié, en régime monogamique. Quelle est la conséquence en principe ?",
     "Le mariage ne peut pas être célébré, car un lien conjugal antérieur subsiste",
     ["Il est célébré, puis le premier mariage est annulé", "Il est célébré mais sera annulé par les voisins", "Il est célébré si le futur conjoint est d'accord"],
     "Dans un système monogamique, la bigamie est un empêchement au mariage.", 4),
    ("Deux frères et sœurs veulent se marier. Que dit en principe le droit civil général ?",
     "Le mariage est prohibé en raison de la parenté trop proche",
     ["Le mariage est autorisé si leurs parents sont d'accord", "Le mariage est autorisé après un an de vie commune", "Le mariage est autorisé si l'un d'eux émigre"],
     "La prohibition de l'inceste interdit le mariage entre proches parents.", 3),
    ("Avant un mariage, la mairie affiche une publication. Quel est le but principal de cette formalité ?",
     "Permettre à ceux qui connaissent un empêchement de le faire savoir",
     ["Fixer le montant de la dot", "Préparer la liste des invités", "Désigner l'héritier du couple"],
     "La publicité du mariage permet de signaler un empêchement avant la célébration.", 3),
    ("Un homme conteste sa paternité, au motif qu'il n'est pas le père biologique. Que doit-il engager ?",
     "Une action en contestation de paternité devant le tribunal compétent",
     ["Une demande de divorce", "Une action en partage", "Une action en revendication de meuble"],
     "La filiation établie ne se détruit que par une action en justice dans les cas prévus.", 4),
    ("Un enfant né hors mariage veut faire établir qu'un homme est son père, qui refuse de le reconnaître. Quelle voie existe ?",
     "Une action en recherche de paternité, conduite en justice",
     ["Une adoption forcée par le père", "Une procédure de liquidation de communauté", "Une simple demande à la mairie du père"],
     "La filiation peut être établie judiciairement lorsqu'elle n'est pas reconnue volontairement.", 4),
    ("Une enfant mineure vit chez sa tante depuis plusieurs années, sans décision de justice. Cette tante a-t-elle automatiquement l'autorité parentale ?",
     "Non, l'autorité parentale appartient aux parents sauf décision contraire",
     ["Oui, la durée suffit à la lui donner", "Oui, par simple déclaration au voisin", "Oui, dès que l'enfant le souhaite"],
     "L'autorité parentale ne se transfère pas par le seul fait de la cohabitation.", 3),
    ("Deux époux divorcent. Ils sont mariés sous la communauté de biens. Quelle opération est nécessaire à la fin du régime ?",
     "La liquidation puis le partage de la communauté",
     ["La reconnaissance de la communauté", "La publication des bans", "L'adoption de l'un par l'autre"],
     "La dissolution du régime entraîne la liquidation des intérêts patrimoniaux.", 4),
    ("Un couple non marié veut sécuriser certains aspects de leur vie commune. En droit français, quel contrat spécifique existe ?",
     "Le pacte civil de solidarité (PACS)",
     ["Le contrat de mariage coutumier", "Le testament authentique", "L'acte de notoriété"],
     "Le PACS est un contrat entre deux personnes pour organiser leur vie commune (droit français).", 3),
    ("Dans quel acte le choix d'un régime matrimonial est-il constaté avant le mariage ?",
     "Un contrat de mariage, souvent passé devant notaire",
     ["Un testament olographe", "Un bail d'habitation", "Un mandat de gestion"],
     "Les futurs époux peuvent choisir leur régime par contrat de mariage.", 3),
    ("Quel est le rôle de l'officier d'état civil lors du mariage civil ?",
     "Recevoir le consentement des époux et constater l'union",
     ["Juger le litige entre les familles", "Fixer le montant de la dot", "Désigner les héritiers"],
     "L'officier d'état civil célèbre le mariage et en dresse acte.", 2),
    ("Un époux vend seul le logement de la famille sans que son conjoint le sache. Quelle protection prévoit souvent le droit pour le logement familial ?",
     "Le consentement des deux époux est exigé pour disposer du logement familial",
     ["Chaque époux peut vendre ce qu'il veut sans limites", "Le logement ne peut jamais être vendu", "Seul le maire peut le vendre"],
     "Beaucoup de systèmes protègent le logement de la famille contre un acte unilatéral (droit français).", 5),
    ("Qu'est-ce qu'une filiation adoptive ?",
     "Un lien de filiation créé par jugement ou acte légal, en dehors de la naissance",
     ["Un lien biologique entre l'enfant et un oncle", "Un lien contractuel révocable à volonté", "Un lien de tutelle sans autorité parentale"],
     "L'adoption crée un lien de filiation par décision de justice.", 3),
    ("Une mère décède et son enfant mineur n'a plus de parents vivants. Quelle institution est en principe mise en place pour le protéger ?",
     "La tutelle, avec un tuteur chargé de le représenter",
     ["La curatelle, sans représentant", "Le divorce de ses grands-parents", "L'émancipation automatique"],
     "En l'absence de parents exerçant l'autorité parentale, la tutelle protège le mineur.", 3),
    ("Un époux manque à l'obligation de fidélité. Quelle conséquence juridique peut en découler, dans les systèmes où le divorce peut être fondé sur une faute ?",
     "Cette faute peut fonder une demande de divorce pour faute",
     ["Elle entraîne automatiquement une peine de mort civile", "Elle supprime le droit de vote de l'époux", "Elle ouvre la succession de l'époux"],
     "Le manquement grave aux devoirs du mariage peut être une cause de divorce pour faute.", 4),
    ("Qu'est-ce que le droit de visite et d'hébergement ?",
     "La faculté pour le parent chez qui l'enfant ne vit pas habituellement de le voir et l'accueillir",
     ["Le droit de décider seul du lieu de scolarité", "Le droit de percevoir les allocations", "Le droit de succéder à l'enfant"],
     "Il maintient les liens de l'enfant avec le parent chez qui il ne réside pas.", 3),
    ("Qu'est-ce qu'un acte de notoriété en matière familiale ?",
     "Un acte qui constate, sur déclarations concordantes, une qualité comme celle d'héritier",
     ["Un acte de mariage conclu en secret", "Un jugement de divorce", "Un testament public"],
     "Il sert à établir une situation de fait ou de droit à partir d'éléments concordants.", 5),
    ("Un enfant est traité comme tel par un homme depuis sa naissance, porte son nom et est connu comme son fils dans le voisinage. Cet ensemble de faits évoque quelle notion ?",
     "La possession d'état",
     ["La prescription acquisitive", "L'usucapion", "L'adoption plénière"],
     "La possession d'état est un faisceau de faits révélant le lien de filiation.", 4),
], cat="Famille : cas et qualifications", src=S)

# =================================================================================================================================
# 4. SUCCESSIONS
# =================================================================================================================================
mcq(C, "cas-l1a-succ", [
    ("Mbarga décède à Douala, où il était domicilié depuis longtemps. À quel moment s'ouvre sa succession ?",
     "Au jour de son décès",
     ["Au jour où ses héritiers en prennent connaissance", "Au jour de la lecture de son testament en public", "Au jour de la vente de ses biens"],
     "La succession s'ouvre par la mort, au dernier domicile du défunt.", 2),
    ("Le défunt a laissé un testament désignant Ngono pour recevoir sa maison. Quel nom donne-t-on à Ngono dans cette situation ?",
     "Légataire, bénéficiaire d'un legs",
     ["Donataire, car elle reçoit entre vifs", "Débitrice, car elle doit payer des dettes", "Tutrice, car elle gère les biens"],
     "Le légataire reçoit un bien en vertu d'un testament.", 2),
    ("Le testament est dit un acte unilatéral et révocable. Que signifie cette seconde qualité ?",
     "Le testateur peut le modifier ou l'annuler tant qu'il est vivant",
     ["Les héritiers peuvent le modifier après le décès sans formalité", "Le juge peut le remplacer à sa guise avant le décès", "Le notaire peut le rompre à tout moment"],
     "Le testateur garde jusqu'à son décès la liberté de changer d'avis.", 3),
    ("Fotso rédige à la main un testament, le date et le signe, sans notaire. De quelle forme de testament s'agit-il, en droit français ?",
     "D'un testament olographe",
     ["D'un testament authentique", "D'un testament international", "D'un legs verbal"],
     "Le testament olographe est écrit, daté et signé de la main du testateur.", 3),
    ("Un testament est dicté à un notaire en présence de personnes requises par la loi. De quel type de testament s'agit-il ?",
     "Authentique, reçu par un officier public",
     ["Olographe, rédigé à la main", "Verbal, reçu oralement", "Mystique par défaut"],
     "Le testament authentique est reçu par un notaire.", 3),
    ("Abena meurt sans testament. Comment sont déterminés ses héritiers ?",
     "Par la loi, selon l'ordre de ses parents ou de son conjoint",
     ["Par ses voisins, selon l'usage du quartier", "Par le juge, au choix des plus proches amis", "Par le fisc, selon les impôts payés"],
     "En l'absence de testament, la dévolution légale désigne les héritiers.", 2),
    ("Tchoumi hérite de son père, mais ne veut pas de la succession car elle est lourdement endettée. Que peut-il faire ?",
     "Y renoncer, car nul n'est obligé d'accepter une succession",
     ["L'accepter forcément, car il est de la famille", "La transmettre à son voisin sans formalité", "L'ignorer, car les dettes s'éteignent au décès"],
     "L'héritier est libre d'accepter ou de renoncer.", 3),
    ("Un héritier accepte purement et simplement une succession dont le passif dépasse l'actif. Que se passe-t-il pour lui ?",
     "Il peut être tenu des dettes même au-delà de ce qu'il a reçu",
     ["Il n'est jamais tenu que par les biens reçus", "Il est libéré par le seul fait de l'acceptation", "Il est tenu seulement des frais d'obsèques"],
     "L'acceptation pure et simple confond les patrimoines et expose aux dettes.", 4),
    ("Un héritier craint des dettes cachées dans la succession. Quelle option limite sa responsabilité à l'actif reçu, en droit français ?",
     "L'acceptation à concurrence de l'actif net",
     ["La renonciation à la personnalité", "La reconnaissance de dette", "La clause pénale"],
     "L'héritier n'est alors tenu que dans la limite des biens de la succession.", 4),
    ("Un père décède avant son propre père. Son fils vient ensuite à la succession de son grand-père, à la place du père décédé. Quel mécanisme joue ?",
     "La représentation successorale",
     ["L'indivision forcée", "La saisine du notaire", "La réserve du conjoint"],
     "La représentation permet aux descendants de prendre la place d'un héritier prédécédé.", 3),
    ("Un héritier a volontairement tué le défunt. Quelle conséquence successorale en principe ?",
     "Il est écarté de la succession pour indignité",
     ["Il hérite deux fois plus", "Il hérite après les autres héritiers", "Il garde sa part sous tutelle"],
     "L'indignité exclut de la succession celui qui a commis une faute très grave contre le défunt.", 3),
    ("Qu'est-ce que la réserve héréditaire en droit français ?",
     "Une part de la succession que le défunt ne peut pas retirer à certains héritiers",
     ["Une somme d'argent gardée par le notaire", "Un fonds de garantie des banques", "Un droit de visite des héritiers"],
     "La réserve protège certains héritiers contre les libéralités excessives.", 4),
    ("Dans un système avec réserve, un père donne tous ses biens à un ami, laissant ses enfants sans rien. Que peuvent faire les enfants ?",
     "Demander la réduction de la libéralité qui dépasse la quotité disponible",
     ["Rien, car la libéralité est toujours définitive", "Annuler le testament pour absence de notaire", "Réclamer les dettes à l'ami"],
     "Les libéralités qui entament la réserve peuvent être réduites.", 5),
    ("Qu'est-ce que la quotité disponible ?",
     "La part des biens dont le défunt peut librement disposer par libéralité",
     ["La part réservée aux héritiers", "La part des dettes de la succession", "La part réservée à l'État"],
     "C'est la partie du patrimoine qui n'est pas réservée.", 4),
    ("Un homme promet à son neveu, par contrat, de lui donner un bien précis à son décès, ce qui engage sa propre succession. Que dit en principe le droit français des conventions sur succession future ?",
     "Ces pactes sont en principe prohibés, sauf exceptions prévues par la loi",
     ["Ils sont toujours valables entre membres de la famille", "Ils sont toujours valables devant un tribunal", "Ils sont obligatoires pour les héritiers"],
     "Le principe de prohibition des pactes sur succession future est un principe classique.", 5),
    ("Plusieurs héritiers reçoivent ensemble une maison sans l'avoir encore partagée. Quelle situation les relie ?",
     "L'indivision successorale",
     ["La copropriété d'un immeuble par étages", "La société en nom collectif", "L'usufruit conjoint"],
     "Tant que le partage n'a pas eu lieu, les héritiers sont en indivision sur les biens.", 3),
    ("Un héritier veut sortir de l'indivision, mais les autres s'y opposent. Quel principe général est souvent invoqué en droit français ?",
     "Nul ne peut être contraint de demeurer dans l'indivision",
     ["Nul ne peut quitter l'indivision sans l'accord de tous", "L'indivision est perpétuelle de plein droit", "L'indivision cesse seulement au décès du dernier héritier"],
     "Le partage peut être demandé à tout moment, sous réserve de règles particulières.", 4),
    ("Dans une succession, comment appelle-t-on ce qu'un défunt devait à ses créanciers ?",
     "Le passif successoral",
     ["L'actif successoral", "La réserve", "La quotité"],
     "La succession transmet un actif et un passif.", 2),
    ("Dans une succession, comment appelle-t-on les biens et créances du défunt ?",
     "L'actif successoral",
     ["Le passif successoral", "Le legs particulier", "L'usufruit"],
     "L'actif regroupe les biens, l'argent et les créances du défunt.", 2),
    ("Le testament d'un père lègue \"toute sa fortune\" à un ami. Quel type de legs est-ce ?",
     "Un legs universel",
     ["Un legs particulier", "Un legs à titre universel", "Un legs d'usufruit uniquement"],
     "Le legs universel porte sur l'ensemble des biens.", 3),
    ("Un père lègue \"son tracteur\" à son neveu. Quel type de legs est-ce ?",
     "Un legs particulier",
     ["Un legs universel", "Un legs à titre universel", "Un legs de tous ses meubles"],
     "Le legs particulier porte sur un ou plusieurs biens déterminés.", 3),
    ("Un père lègue \"tous ses biens meubles\" à sa fille. Quel type de legs est-ce ?",
     "Un legs à titre universel",
     ["Un legs particulier", "Un legs universel", "Une donation entre vifs"],
     "Il porte sur une fraction du patrimoine ou une catégorie de biens.", 4),
    ("Un défunt a rédigé un testament où il lègue sa voiture à son voisin, puis a détruit ce testament avant son décès. Que vaut le legs ?",
     "Il disparaît en principe, car le testateur a révoqué sa volonté",
     ["Il demeure, car la voiture existe", "Il est dû par les héritiers au voisin", "Il est transformé en donation"],
     "Le testament peut être révoqué, notamment en le détruisant volontairement.", 4),
    ("Un homme décédé n'a ni famille connue ni testament. Quel sort pour sa succession, selon le principe général ?",
     "Elle est dite vacante ou en déshérence et revient à l'État selon les règles applicables",
     ["Elle est partagée librement entre voisins", "Elle est détruite par décision du juge", "Elle reste en suspens sans limite"],
     "À défaut d'héritier, l'État peut recueillir la succession.", 4),
    ("Entre quelles personnes une donation entre vifs a-t-elle lieu ?",
     "Entre un donateur vivant et un donataire qui accepte",
     ["Entre un défunt et un héritier", "Entre un juge et un notaire", "Entre un vendeur et un acheteur"],
     "La donation est un acte irrévocable de transfert gratuit entre vivants.", 2),
    ("Quelle différence essentielle entre donation entre vifs et testament ?",
     "La donation dessaisit tout de suite le donateur, le testament ne produit effet qu'au décès",
     ["La donation est révocable à volonté, le testament ne l'est pas", "La donation exige un notaire, le testament jamais", "La donation concerne les dettes, le testament les créances"],
     "Donner et retenir ne vaut : la donation est irrévocable, le legs prend effet à la mort.", 4),
    ("Que signifie la saisine des héritiers ?",
     "Ils acquièrent de plein droit les biens du défunt dès son décès",
     ["Ils doivent attendre l'autorisation du juge", "Ils sont obligés de vendre les biens", "Ils sont propriétaires seulement après un an"],
     "Les héritiers sont saisis de plein droit du patrimoine du défunt (droit français).", 4),
    ("Un enfant a reçu de son vivant une importante donation de son père. À la succession, qu'invoquent les autres enfants ?",
     "Le rapport, qui vise à rétablir l'égalité entre héritiers",
     ["La nullité du mariage", "La prescription de la donation", "Le droit de visite"],
     "Le rapport des libéralités tend à assurer l'égalité entre héritiers.", 5),
    ("En régime de communauté, au décès d'un époux, quelle opération précède le partage de la succession ?",
     "La liquidation du régime matrimonial pour distinguer les biens du défunt et ceux du survivant",
     ["Le jugement de divorce", "L'adoption du conjoint", "La déclaration de nationalité"],
     "On sépare d'abord la part du conjoint survivant de celle du défunt.", 5),
    ("Un notaire reçoit les héritiers pour établir qui sont les héritiers et dresser l'inventaire. Quel est son rôle principal ?",
     "Dresser les actes de la succession et conseiller les héritiers",
     ["Rendre un jugement sur la succession", "Percevoir l'héritage à leur place", "Remplacer le tribunal en cas de conflit pénal"],
     "Le notaire, officier public, règle juridiquement la succession.", 2),
    ("Un enfant reconnu, né hors mariage, peut-il en principe hériter de son père ?",
     "Oui, la filiation établie lui donne vocation à hériter",
     ["Non, il ne peut jamais hériter", "Non, sauf si le père le choisit un jour", "Oui, mais seulement des dettes"],
     "Une fois la filiation établie, l'enfant a des droits dans la succession.", 3),
    ("Un légataire meurt avant le testateur. Que devient le legs, en principe ?",
     "Il est en principe caduc, faute de bénéficiaire existant",
     ["Il passe à l'État en tout cas", "Il reste à la charge de ses héritiers", "Il se transforme en dette"],
     "Le legs devient caduc si le légataire ne survit pas au testateur, sauf stipulation contraire.", 4),
    ("Que peut-on dire de la volonté du défunt exprimée dans un testament contraire à l'ordre public, par exemple faisant obstacle à une règle protectrice impérative ?",
     "La clause est inefficace dans cette mesure, car elle viole une règle impérative",
     ["La clause l'emporte sur la loi", "La clause est valable pour dix ans", "La clause est valable entre voisins"],
     "La liberté testamentaire est limitée par l'ordre public et la réserve.", 5),
    ("Dans une succession, quel est le rôle d'un exécuteur testamentaire ?",
     "Veiller à l'exécution des volontés du défunt exprimées dans son testament",
     ["Juger les litiges entre héritiers", "Percevoir les impôts de l'héritage", "Représenter les créanciers du défunt"],
     "Il est désigné par le testateur pour assurer l'exécution du testament.", 4),
], cat="Successions : cas et qualifications", src=S)

# =================================================================================================================================
# 5. BIENS (principes)
# =================================================================================================================================
mcq(C, "cas-l1a-biens", [
    ("Une maison, un terrain nu, un bâtiment construit : quelle qualification commune ?",
     "Des immeubles par nature",
     ["Des meubles par nature", "Des biens incorporels par destination", "Des choses sans maître"],
     "Le sol et ce qui y est incorporé de façon durable sont des immeubles.", 2),
    ("Un tracteur, un ordinateur, un véhicule : de quelle catégorie de biens relèvent-ils ?",
     "Des meubles par nature, car ils se déplacent ou peuvent être déplacés",
     ["Des immeubles par nature, car ils pèsent lourd", "Des biens publics par principe", "Des droits réels immobiliers"],
     "Sont meubles par nature les choses qui peuvent se transporter d'un lieu à un autre.", 2),
    ("Un agriculteur possède un matériel affecté à l'exploitation de son champ. Selon la théorie classique du droit français, comment peut-on qualifier ce matériel ?",
     "Un immeuble par destination, car il est affecté au service du fonds",
     ["Un immeuble par nature, car il est lourd", "Un meuble par détermination de la loi", "Un bien sans valeur patrimoniale"],
     "Les objets mis par le propriétaire au service d'un fonds peuvent être immeubles par destination.", 4),
    ("Une créance de somme d'argent, un brevet, une marque : de quel type de biens s'agit-il ?",
     "Des biens incorporels",
     ["Des biens corporels", "Des immeubles par nature", "Des choses communes"],
     "Les biens incorporels n'ont pas de réalité matérielle : créances, droits de propriété intellectuelle.", 2),
    ("Une denrée comme le riz, qui disparaît au premier usage, est-elle consomptible ?",
     "Oui, car elle se consomme par le premier usage qu'on en fait",
     ["Non, car elle est immeuble par destination", "Non, car elle est un bien incorporel", "Oui, car elle appartient à l'État"],
     "Une chose consomptible se détruit ou se transforme dès le premier usage.", 3),
    ("Un prêt de consommation porte sur une quantité de sacs de maïs. Quelle qualité du bien explique qu'on puisse rendre des sacs équivalents et non les mêmes ?",
     "Sa fongibilité",
     ["Son caractère immobilier", "Son caractère incorporel", "Son appartenance au domaine public"],
     "Une chose fongible est remplaçable par une autre de même espèce et quantité.", 3),
    ("Peut-on vendre une partie du corps humain comme un bien dans le commerce ordinaire ?",
     "Non, le corps humain est hors commerce, indisponible",
     ["Oui, si le prix est équitable", "Oui, si le vendeur est majeur", "Oui, devant un notaire"],
     "Le principe d'indisponibilité du corps humain interdit d'en faire un objet de commerce.", 3),
    ("Un propriétaire utilise sa maison, la loue et pourrait la vendre. Quels attributs du droit de propriété exerce-t-il ?",
     "L'usage, la jouissance des fruits et la libre disposition",
     ["La seule jouissance, sans disposition", "Le seul droit de la vendre, sans usage", "L'usage et la jouissance sans pouvoir la louer"],
     "La propriété confère usus, fructus et abusus.", 3),
    ("Quelle différence entre usus, fructus et abusus ?",
     "Usage de la chose, perception de ses fruits, pouvoir d'en disposer",
     ["Fruits, vente, location dans l'ordre", "Pouvoir de juger, de punir, de récompenser", "Droits de l'enfant, du parent, de l'État"],
     "Ce sont les trois attributs classiques de la propriété.", 3),
    ("Un père lègue l'usufruit de sa maison à sa femme et la nue-propriété à ses enfants. Que peut faire l'épouse ?",
     "Habiter la maison ou la louer et en percevoir les loyers, sans pouvoir la vendre en pleine propriété",
     ["La vendre librement sans leur accord", "Léguer à sa mort la maison à ses amis", "Raser la maison pour reconstruire"],
     "L'usufruitier a l'usage et les fruits, non le pouvoir de disposer de la propriété.", 4),
    ("Dans un démembrement de propriété, que détient le nu-propriétaire ?",
     "Le droit de disposer du bien, sans en avoir l'usage ni les fruits tant que dure l'usufruit",
     ["L'usage et les fruits, sans pouvoir disposer", "Seulement une dette envers l'usufruitier", "Le droit de louer sans limite"],
     "Le nu-propriétaire retrouvera la pleine propriété à l'extinction de l'usufruit.", 4),
    ("Que devient en principe l'usufruit à la mort de l'usufruitier ?",
     "Il s'éteint, et le nu-propriétaire retrouve la pleine propriété",
     ["Il passe automatiquement à ses héritiers", "Il se transforme en bail", "Il devient une servitude"],
     "L'usufruit viager s'éteint au plus tard au décès de l'usufruitier.", 3),
    ("Un voisin a le droit de traverser le champ de Ngono pour accéder à la route, au bénéfice de son propre champ. Quelle notion est en jeu ?",
     "Une servitude de passage",
     ["Un usufruit sur le champ", "Un bail à ferme", "Une donation entre vifs"],
     "Une servitude est une charge pesant sur un fonds (servant) au profit d'un autre (dominant).", 3),
    ("Dans l'exemple d'un passage sur le champ voisin, quel fonds supporte la charge ?",
     "Le fonds servant",
     ["Le fonds dominant", "Le fonds commun", "Le fonds indivis"],
     "Le fonds servant supporte la servitude, le dominant en profite.", 3),
    ("Quelle différence entre un droit réel et un droit personnel ?",
     "Le droit réel porte directement sur une chose, le droit personnel est un lien entre deux personnes",
     ["Le droit réel est temporaire, le droit personnel est perpétuel", "Le droit réel est gratuit, le droit personnel est onéreux", "Le droit réel est écrit, le droit personnel est oral"],
     "Propriété, usufruit, hypothèque sont des droits réels ; la créance est un droit personnel.", 3),
    ("Une locataire occupe un appartement en vertu d'un contrat. Quelle nature a son droit selon la conception classique ?",
     "Un droit personnel contre son bailleur",
     ["Un droit réel de propriété", "Un droit de servitude", "Un droit d'usufruit légal"],
     "Le bail crée une créance de jouissance à l'égard du bailleur (qualification classique).", 4),
    ("Ngono occupe un terrain en se comportant comme un propriétaire depuis longtemps, sans titre. Comment appelle-t-on cet état de fait ?",
     "La possession, qui peut conduire à acquérir par prescription",
     ["La détention précaire, qui ne mène à rien", "Le gage, sûreté réelle", "La servitude de passage"],
     "La possession réunit l'élément matériel et l'intention de se comporter en propriétaire.", 3),
    ("Un locataire qui occupe un logement et reconnaît le droit de son bailleur comment le qualifie-t-on ?",
     "Détenteur précaire",
     ["Possesseur de bonne foi", "Propriétaire par prescription", "Nu-propriétaire"],
     "Il détient pour le compte d'autrui et ne se comporte pas en propriétaire.", 3),
    ("Que désigne l'usucapion, ou prescription acquisitive ?",
     "Un mode d'acquérir la propriété par une possession prolongée et utile",
     ["La perte d'un droit par la mort du titulaire", "L'extinction d'une dette par paiement", "Le transfert de propriété par contrat de vente"],
     "La possession utile prolongée peut faire acquérir la propriété.", 4),
    ("Quelles qualités doit avoir une possession pour conduire à l'usucapion, selon la théorie classique ?",
     "Elle doit être continue, paisible, publique et non équivoque",
     ["Elle doit être secrète, discontinue et violente", "Elle doit être précaire, occasionnelle et gratuite", "Elle doit être orale, locale et provisoire"],
     "Ces qualités rendent la possession utile.", 4),
    ("Un acquéreur reçoit un bien de bonne foi auprès d'un vendeur qui n'en était pas propriétaire. Pour les meubles corporels, quelle maxime a-t-on parfois en droit français ?",
     "En fait de meubles, la possession vaut titre",
     ["La possession est toujours inefficace", "Le titre n'a aucune valeur", "L'acquéreur est toujours un voleur"],
     "Pour les meubles corporels, la possession de bonne foi protège l'acquéreur, sous certaines réserves.", 5),
    ("Un arbre planté chez Mbarga donne des fruits que ses voisins ramassent sans permission. À qui appartiennent en principe ces fruits ?",
     "À Mbarga, propriétaire de l'arbre, par droit sur les fruits",
     ["Aux voisins, qui les ramassent", "À l'État, par principe", "À celui qui les mange en premier"],
     "Les fruits appartiennent au propriétaire de la chose qui les produit.", 2),
    ("Quels fruits sont les loyers d'un immeuble ?",
     "Des fruits civils",
     ["Des fruits naturels", "Des fruits industriels", "Des produits de la terre"],
     "Les loyers et intérêts sont des fruits civils.", 3),
    ("Le blé, les fruits d'un arbre, le lait : de quel type de fruits parle-t-on ?",
     "Des fruits naturels",
     ["Des fruits civils", "Des fruits industriels exclusivement", "Des sûretés réelles"],
     "Les fruits naturels sont ceux que produit spontanément la chose.", 3),
    ("Que prévoit le principe de l'accession en droit civil classique ?",
     "La propriété du sol emporte en principe la propriété de ce qui s'y unit et de ce qu'il produit",
     ["Le propriétaire perd son terrain si on y bâtit", "Les voisins sont propriétaires des constructions", "Les fruits appartiennent à ceux qui les cueillent"],
     "Le propriétaire du sol est en principe propriétaire du dessus et du dessous.", 4),
    ("Un constructeur bâtit de bonne foi sur le terrain d'autrui. Quel principe sert de point de départ au règlement du conflit ?",
     "L'accession : le propriétaire du sol devient en principe propriétaire de la construction",
     ["Le constructeur devient propriétaire sans condition", "La construction appartient à l'État", "La construction est détruite d'office"],
     "L'accession immobilière attribue la construction au propriétaire du sol, sous réserve d'indemniser le constructeur.", 5),
    ("Le propriétaire d'un fonds subit des nuisances sonores excessives venant de l'atelier voisin. Quel type de troubles est invoqué ?",
     "Un trouble anormal de voisinage",
     ["Une usucapion de bruit", "Une servitude légale de bruit", "Une expropriation pour utilité publique"],
     "Les troubles excédant les inconvénients normaux du voisinage peuvent donner lieu à réparation.", 4),
    ("Une commune doit construire une route et veut acquérir une partie du terrain de Fotso. Quel principe protège le propriétaire en cas d'expropriation pour utilité publique ?",
     "Le droit à une indemnisation juste et préalable",
     ["Le droit de refuser toute vente quoi qu'il arrive", "Le droit de percevoir une rente à vie sans limite", "Le droit de choisir librement le montant"],
     "L'expropriation exige une cause d'utilité publique et une indemnité.", 3),
    ("Une place publique, une route nationale, un port appartiennent à une collectivité publique et sont affectés à l'usage de tous. À quel ensemble appartiennent-ils ?",
     "Au domaine public",
     ["Au domaine privé des particuliers", "À l'indivision successorale", "Au patrimoine d'une société commerciale"],
     "Les biens affectés à l'usage du public ou à un service public font partie du domaine public.", 3),
    ("Selon un principe classique du droit administratif des biens, comment sont les biens du domaine public ?",
     "Inaliénables et imprescriptibles tant qu'ils restent affectés",
     ["Librement vendus à tout moment", "Acquis par usucapion après une longue possession", "Soumis au droit de préemption des voisins"],
     "On ne peut les vendre ni les acquérir par prescription tant qu'ils relèvent du domaine public.", 5),
    ("Un emprunteur donne en garantie à sa banque un immeuble sans s'en dessaisir. De quelle sûreté s'agit-il ?",
     "Une hypothèque",
     ["Un gage avec dépossession", "Un cautionnement", "Un droit d'usufruit"],
     "L'hypothèque est une sûreté réelle immobilière qui n'exige pas de dessaisissement.", 3),
    ("Un emprunteur remet à son créancier un bijou en garantie du prêt, jusqu'au remboursement. De quelle sûreté s'agit-il ?",
     "Un gage avec dépossession",
     ["Une hypothèque", "Un cautionnement", "Une servitude"],
     "Le gage porte sur un meuble ; la remise de la chose le caractérise.", 3),
    ("Un tiers s'engage envers la banque à payer la dette de l'emprunteur si celui-ci ne paie pas. De quelle sûreté s'agit-il ?",
     "Un cautionnement, sûreté personnelle",
     ["Une hypothèque, sûreté réelle", "Un gage sans dépossession", "Un usufruit"],
     "Dans une sûreté personnelle, une personne s'engage pour la dette d'autrui.", 3),
    ("Quelle est la différence fondamentale entre sûreté réelle et sûreté personnelle ?",
     "La réelle affecte un bien déterminé, la personnelle engage le patrimoine d'un tiers",
     ["La réelle est écrite, la personnelle est orale", "La réelle est gratuite, la personnelle onéreuse", "La réelle concerne l'État, la personnelle les entreprises"],
     "Hypothèque et gage portent sur un bien ; la caution engage une personne.", 4),
    ("Un créancier hypothécaire peut en cas de non-paiement faire saisir l'immeuble même entre les mains d'un acquéreur. Quel attribut de l'hypothèque est en jeu ?",
     "Le droit de suite",
     ["Le droit de visite", "Le droit d'accession", "Le droit de rétractation"],
     "Le droit de suite permet de poursuivre le bien en quelque main qu'il passe.", 5),
    ("Quel avantage a un créancier titulaire d'une hypothèque par rapport à un créancier ordinaire ?",
     "Il est payé par préférence sur le prix de l'immeuble",
     ["Il est payé le premier sur tous les biens du débiteur", "Il peut se faire propriétaire sans formalité", "Il peut ignorer la procédure d'exécution"],
     "Le droit de préférence permet d'être payé avant les créanciers chirographaires sur le bien affecté.", 4),
    ("Au Cameroun, quel document constitue la preuve de la propriété d'un immeuble immatriculé ?",
     "Le titre foncier",
     ["Le permis de conduire", "L'acte de naissance du propriétaire", "Le bail commercial"],
     "L'immatriculation foncière aboutit à la délivrance d'un titre foncier.", 3),
    ("Une œuvre littéraire est créée par Abena. À quelle condition formelle bénéficie-t-elle de la protection du droit d'auteur, selon le principe général ?",
     "À aucune formalité : la protection naît de la création originale",
     ["Après un dépôt obligatoire auprès du juge", "Après une longue période d'exploitation commerciale", "Après vote d'une loi spéciale"],
     "Le droit d'auteur naît de la création, sans dépôt obligatoire (principe issu de la convention de Berne).", 4),
    ("Fotso invente un procédé industriel nouveau et veut un monopole d'exploitation. Quelle voie de protection est la plus adaptée ?",
     "Le brevet d'invention, accordé après demande",
     ["Le droit d'auteur automatique sur toute idée", "La possession de l'objet", "L'usucapion"],
     "Un brevet exige une demande ; la simple idée n'est pas protégée par le droit d'auteur.", 4),
    ("Un commerçant possède une clientèle, une enseigne, un droit au bail dans un local. Quel ensemble de biens forme-t-il ?",
     "Un fonds de commerce, bien incorporel",
     ["Un immeuble par nature", "Un patrimoine d'affectation immobilière", "Un bien du domaine public"],
     "Le fonds de commerce est un ensemble de biens incorporels, centré sur la clientèle.", 4),
    ("Une copropriété par appartements comporte une cage d'escalier partagée. Comment qualifie-t-on cette partie ?",
     "Une partie commune de l'immeuble",
     ["Une partie privative", "Un fonds servant", "Un bien vacant"],
     "Dans une copropriété, les parties communes servent à l'usage de tous les copropriétaires.", 3),
    ("Un copropriétaire est seul propriétaire de son appartement et copropriétaire des couloirs. Comment appelle-t-on son appartement ?",
     "Sa partie privative",
     ["Une partie commune", "Un bien vacant", "Une servitude"],
     "La partie privative appartient à un seul copropriétaire.", 3),
    ("Une chose que personne ne possède et que nul ne revendique, comme un animal sauvage libre, comment la qualifie-t-on ?",
     "Chose sans maître",
     ["Bien du domaine public exclusif", "Servitude", "Sûreté réelle"],
     "Une chose sans maître n'appartient à personne et peut en principe s'acquérir par occupation.", 4),
    ("Trois frères et sœurs détiennent ensemble un champ reçu en héritage sans l'avoir partagé. Quelle est la nature de cette propriété ?",
     "Une propriété indivise",
     ["Une propriété démembrée", "Un domaine public", "Une sûreté réelle"],
     "Plusieurs personnes ont des droits de même nature sur le même bien, sans division matérielle.", 3),
    ("Dans l'indivision, que peut en principe faire un indivisaire avec sa part ?",
     "La vendre ou demander le partage, selon les règles du droit civil",
     ["La vendre sans qu'elle soit remplacée", "Occuper seul tout le bien à titre gratuit", "Détruire le bien en entier"],
     "L'indivisaire a un droit sur sa quote-part, avec des règles particulières pour la gestion.", 4),
    ("Comment un acheteur d'immeuble peut-il rendre son droit opposable aux tiers, en principe, dans un système de publicité foncière ?",
     "En accomplissant les formalités de publicité à la conservation foncière ou au registre prévu",
     ["En le gardant secret", "En le faisant connaître par oral", "En le déclarant à la mairie de naissance"],
     "La publicité foncière rend les droits sur immeubles opposables aux tiers.", 4),
    ("Un propriétaire peut-il faire de sa chose tout ce qu'il veut, sans aucune limite ?",
     "Non, il doit respecter les lois, les droits des voisins et l'ordre public",
     ["Oui, le droit de propriété est illimité en tout", "Oui, sauf devant un notaire", "Oui, sauf en matière de meubles seulement"],
     "Le droit de propriété est protégé mais limité par la loi et les droits d'autrui.", 3),
    ("La propriété est dite perpétuelle. Que signifie ce caractère ?",
     "Elle ne s'éteint pas par le non-usage, mais par un acte ou une disposition légale",
     ["Elle s'éteint quand le propriétaire cesse d'utiliser le bien", "Elle ne dure qu'une génération", "Elle ne peut jamais être transmise"],
     "Le droit de propriété dure tant que le bien existe et n'est pas transféré.", 4),
    ("On dit que la propriété est exclusive. Qu'est-ce que cela signifie ?",
     "Le propriétaire est seul à pouvoir user de la chose, sauf règle contraire",
     ["Plusieurs personnes peuvent toujours l'utiliser librement", "L'État est toujours copropriétaire", "Le propriétaire doit la partager"],
     "L'exclusivité empêche les tiers de s'en servir sans l'accord du propriétaire.", 3),
    ("Une personne trouve un portefeuille perdu dans la rue. Quelle attitude est conforme aux principes généraux ?",
     "Chercher à le restituer ou le déclarer aux autorités, car la chose reste à son propriétaire",
     ["Le garder, car il est sans maître", "Le vendre, car il est trouvé", "Le détruire pour éviter les problèmes"],
     "Une chose perdue n'est pas sans maître ; la garder peut constituer une infraction.", 3),
    ("Qu'est-ce que le droit d'usage ou d'habitation ?",
     "Un droit réel limité de se servir d'un bien ou d'y habiter, sans en percevoir tous les fruits",
     ["Un droit de propriété complet", "Un droit de préemption public", "Un droit de gage mobilier"],
     "C'est un démembrement plus restreint que l'usufruit.", 5),
    ("Un ouvrier qui a réparé un meuble le garde jusqu'au paiement de sa facture. Quel mécanisme exerce-t-il ?",
     "Un droit de rétention",
     ["Une hypothèque", "Une usucapion", "Un usufruit"],
     "Le droit de rétention permet de garder la chose tant que la dette liée n'est pas payée.", 5),
], cat="Biens : cas et qualifications", src=S)
