package castbridge.core.lots

import castbridge.core.net.JsonLite
import castbridge.core.net.JsonLite.long
import castbridge.core.net.JsonLite.str

/** A purchasable bundle: a set of FULL lots ("learn:cm2", "quiz:cm2", "langues:zh-a0"…). Generated by tools/trial-edition from the lot registry. */
data class Bundle(val id: String, val type: String, val lots: Set<String>, val title: String = "", val rawBytes: Long = 0)

class BundleCatalog(val bundles: List<Bundle>) {
    private val byId = bundles.associateBy { it.id }
    fun find(id: String): Bundle? = byId[id]
    fun lotsOf(ids: Collection<String>): Set<LotId> = ids.flatMap { byId[it]?.lots.orEmpty() }.mapNotNull(LotNames::parseKey).toSet()
    /** Bundles whose lots include [id]; used to explain "this lot belongs to…" and to choose between overlapping bundles. */
    fun containing(id: LotId): List<Bundle> = bundles.filter { LotNames.key(id) in it.lots }.sortedBy { it.id }

    companion object {
        /** Reads the "bundles" array of TRIAL-MANIFEST.json (or a file holding just that array under "bundles"). */
        fun parse(json: String): BundleCatalog {
            val arr = JsonLite.obj(json)["bundles"] as? List<*> ?: throw JsonLite.ParseError("missing \"bundles\"")
            return BundleCatalog(arr.map { e ->
                @Suppress("UNCHECKED_CAST") val m = e as? Map<String, Any?> ?: throw JsonLite.ParseError("bad bundle")
                Bundle(m.str("id") ?: throw JsonLite.ParseError("bundle id"), m.str("type") ?: "", (m["lots"] as? List<*>).orEmpty().map { it.toString() }.toSet(),
                    m.str("title") ?: "", m.long("rawBytes") ?: 0L)
            })
        }
    }
}

/**
 * What each edition may hold, and how one turns into the other (pure, tested). The TRIAL is the floor: every "-trial" lot is always
 * allowed. A FULL lot is allowed only through a bundle the device owns or subscribes to ([Access]). The trial lots are a coherent
 * subset of the bundles: a trial lot belongs to the bundles that contain its full lot, and its identifiers do not change when the
 * full lot replaces it.
 *
 * This is the CLIENT side. The real protection is the server, which only serves a full lot to a device whose token covers it
 * (docs/TRIAL-EDITION.md § Sécurité): a check in the app can be bypassed, content already delivered cannot be taken back.
 */
object EditionPolicy {
    fun allowedFull(access: Access, bundles: BundleCatalog): Set<LotId> = bundles.lotsOf(access.granted)

    fun isAllowed(m: LotMeta, access: Access, bundles: BundleCatalog): Boolean = m.edition == Edition.TRIAL || m.id in allowedFull(access, bundles)

    /**
     * What the phone should hold from [catalog]: every trial lot, plus the full lots the device may open; a trial lot whose full
     * twin is allowed (and listed) is dropped: never both (no duplicates on the TV, whose budget is 10 Mo).
     */
    fun offered(catalog: Collection<LotMeta>, access: Access, bundles: BundleCatalog): List<LotMeta> {
        val allowed = allowedFull(access, bundles)
        val fulls = catalog.filter { it.edition == Edition.FULL && it.id in allowed }
        val fullIds = fulls.map { it.id }.toSet()
        val trials = catalog.filter { it.edition == Edition.TRIAL && LotEditions.fullOf(it.id) !in fullIds }
        return (fulls + trials).sortedWith(compareBy({ it.id.feature }, { it.id.scope }))
    }

    /**
     * Needs are expressed on FULL lot ids (a class, a Quiz pack): map each to what the device may really have. Allowed and on the
     * phone: the full lot. Allowed but not downloaded yet: the trial twin meanwhile (the TV keeps something until the full lot arrives).
     * Not allowed: the trial twin.
     */
    fun adaptNeeds(needs: List<Need>, onPhone: Collection<LotMeta>, access: Access, bundles: BundleCatalog): List<Need> {
        val allowed = allowedFull(access, bundles)
        val phone = onPhone.map { it.id }.toSet()
        return needs.map { n ->
            val full = LotEditions.fullOf(n.id)
            val trial = LotEditions.trialOf(full)
            Need(when {
                full in allowed && full in phone -> full
                trial in phone -> trial
                else -> if (full in allowed) full else trial
            }, n.priority)
        }
    }

    data class TvPlan(val plan: LotPlanner.Plan, /** Trial lots the TV may drop now: their full twin is already there. */ val dropTrials: List<LotId>)

    /** [LotPlanner] with the edition rules: same deterministic plan, trial vs full decided by the rights, never both on the TV. */
    fun planForTv(needs: List<Need>, onPhone: Collection<LotMeta>, onTv: Collection<LotMeta>, starterBytes: Long, access: Access, bundles: BundleCatalog,
                  budget: Long = LotBudget.TV_MAX_BYTES): TvPlan {
        val usable = offered(onPhone, access, bundles)
        val plan = LotPlanner.plan(adaptNeeds(needs, usable, access, bundles), usable, onTv, starterBytes, budget)
        return TvPlan(plan, LotEditions.supersededTrials(onTv.map { it.id }))
    }

    data class Demotion(val lot: LotMeta, val trialTwin: LotId, val message: String)
    data class Reconciliation(
        /** Full lots still allowed (purchases, active or grace subscription). */
        val keep: List<LotMeta>,
        /** Trial lots made redundant by a full lot held: safe to remove, nothing is lost. */
        val dropTrials: List<LotId>,
        /** Full lots the device no longer may hold: they are KEPT until the user has been told ([acknowledged]), then they go back to the trial. */
        val demotions: List<Demotion>,
        val removableNow: List<LotId>,
        val notices: List<String>,
    )

    /**
     * What to do with the lots [held] when the rights change (expiry, refund, other device). Nothing is deleted without warning:
     * a lot that is no longer allowed is listed in [Reconciliation.demotions] with a French message and only appears in
     * [Reconciliation.removableNow] once its id is in [acknowledged] (the user saw the notice).
     */
    fun reconcile(held: Collection<LotMeta>, access: Access, bundles: BundleCatalog, acknowledged: Set<LotId> = emptySet()): Reconciliation {
        val allowed = allowedFull(access, bundles)
        val fullHeld = held.filter { it.edition == Edition.FULL }
        val keep = fullHeld.filter { it.id in allowed }
        val lost = fullHeld.filter { it.id !in allowed }.sortedWith(compareBy({ it.id.feature }, { it.id.scope }))
        val demotions = lost.map {
            Demotion(it, LotEditions.trialOf(it.id), "« ${it.title} » n'est plus inclus dans vos droits : il repasse en version d'essai." +
                if (access.inGrace) " Reconnectez-vous pour renouveler l'abonnement." else " Vos achats restent disponibles.")
        }
        return Reconciliation(keep, LotEditions.supersededTrials(held.map { it.id }), demotions,
            lost.map { it.id }.filter { it in acknowledged }, demotions.map { it.message })
    }

    enum class LotStatus { OWNED, IN_SUBSCRIPTION, PURCHASABLE }
    data class LotQuote(val lot: LotId, val status: LotStatus, val bytes: Long)
    data class Quote(val bundleId: String, val lots: List<LotQuote>) {
        /** Lots to bill if the user buys the bundle to keep them for good: never an owned lot (no double billing for overlapping bundles). */
        val billable: List<LotId> get() = lots.filter { it.status != LotStatus.OWNED }.map { it.lot }
        /** Lots that only need the purchase to survive the end of the subscription (the choice « déjà couvert par mon abonnement »). */
        val coveredBySubscription: List<LotId> get() = lots.filter { it.status == LotStatus.IN_SUBSCRIPTION }.map { it.lot }
        val newlyUnlocked: List<LotId> get() = lots.filter { it.status == LotStatus.PURCHASABLE }.map { it.lot }
        val billableBytes: Long get() = lots.filter { it.status != LotStatus.OWNED }.sumOf { it.bytes }
    }

    /** Bundle [bundleId] seen from the rights: what is already owned for good, what an active subscription covers, what is really new. */
    fun quote(bundleId: String, access: Access, bundles: BundleCatalog, catalog: Collection<LotMeta>): Quote? {
        val b = bundles.find(bundleId) ?: return null
        val owned = bundles.lotsOf(access.purchased)
        val subscribed = bundles.lotsOf(access.subscribed)
        val size = catalog.filter { it.edition == Edition.FULL }.associate { it.id to it.bytes }
        return Quote(bundleId, bundles.lotsOf(listOf(bundleId)).sortedWith(compareBy({ it.feature }, { it.scope })).map {
            LotQuote(it, when { it in owned -> LotStatus.OWNED; it in subscribed -> LotStatus.IN_SUBSCRIPTION; else -> LotStatus.PURCHASABLE }, size[it] ?: 0L)
        }).takeIf { b.lots.isNotEmpty() }
    }

    data class ExpiryImpact(val atEnd: Long, val lostLots: List<LotId>, val lostBytes: Long, /** Bundles, fewest first, that would keep what is lost. */ val suggestedBundles: List<String>)

    /**
     * Switching from a subscription to purchases: what the subscription alone gives (it goes back to the trial at [SubStatus.right] end)
     * and which bundles keep it. Greedy and deterministic: the bundle covering the most lost lots first, then the smallest.
     */
    fun expiryImpact(access: Access, bundles: BundleCatalog, catalog: Collection<LotMeta>): ExpiryImpact? {
        val sub = access.subscriptions.filter { it.state == SubState.ACTIVE || it.state == SubState.GRACE }.minByOrNull { it.right.endsAt } ?: return null
        val lost = (bundles.lotsOf(access.subscribed) - bundles.lotsOf(access.purchased)).toMutableSet()
        val size = catalog.associate { it.id to it.bytes }
        val bytes = lost.sumOf { size[it] ?: 0L }
        val picks = ArrayList<String>()
        val left = lost.toMutableSet()
        while (left.isNotEmpty()) {
            val best = bundles.bundles.filter { it.type != "tout" }
                .map { it to (bundles.lotsOf(listOf(it.id)) intersect left) }
                .filter { it.second.isNotEmpty() }
                .sortedWith(compareBy({ -it.second.size }, { it.first.rawBytes }, { it.first.id })).firstOrNull() ?: break
            picks += best.first.id
            left -= best.second
        }
        return ExpiryImpact(sub.right.endsAt, lost.sortedWith(compareBy({ it.feature }, { it.scope })), bytes, picks)
    }
}
