package castbridge.core.learn

import java.io.File

/**
 * Review report per lot (docs/LEARN-REVIEW.md, generated by `LearnTool review`): what a teacher must check before any lesson
 * can leave the « draft » status — the points the authors flagged (« à vérifier »), pack by pack, lot by lot.
 * Nothing becomes « reviewed » or « validated » by itself: only a human edits the `status` of a pack/lesson.
 */
object LearnReview {
    class Item(val where: String, val what: String)

    fun report(content: File): String {
        val table = File(content, "scopes.txt").takeIf { it.isFile }?.let { LearnScopes.parseTable(it.readText()) } ?: LearnScopes.Table(emptyMap())
        val dirs = LearnTool.packDirs(content).associateBy { it.name }
        val packs = dirs.mapValues { (_, d) -> LessonJson.parsePack(PackBuilder.sources(d).filterKeys { it.endsWith(".json") }.mapValues { String(it.value, Charsets.UTF_8) }) }
        val sb = StringBuilder()
        sb.append("# Apprendre — rapport de relecture par lot\n\n")
        sb.append("Généré par `tools/build-learn-lots --review` — ne pas modifier à la main. Tout le contenu est au statut **brouillon** : ")
        sb.append("rien n'est « relu » ni « certifié » sans l'avis d'un enseignant. Pour chaque lot : les fiches et les points que les auteurs ")
        sb.append("ont signalés comme **à vérifier** (fait, date, formule, barème, corrigé). Une fois vérifié, l'enseignant corrige la source ")
        sb.append("(`content/learn/<pack>/`), retire le signalement et fait passer le `status` du pack à `reviewed`.\n\n")
        sb.append("| Lot | Packs | Fiches | Exercices | Statut | Points à vérifier |\n|---|---|---|---|---|---|\n")
        val perLot = LinkedHashMap<String, Map<String, List<Item>>>()
        for (lot in table.lots.values) {
            perLot[lot.scope] = lot.packs.mapNotNull { packs[it] }.associate { it.id to flagged(it) }
            val ps = lot.packs.mapNotNull { packs[it] }
            sb.append("| ${lot.scope} (${lot.title}) | ${ps.size} | ${ps.sumOf { it.lessons.size }} | ${ps.sumOf { it.exercises.size }} | ${ps.map { it.status.key }.distinct().joinToString(", ")} | ${perLot.getValue(lot.scope).values.sumOf { it.size }} |\n")
        }
        val total = perLot.values.sumOf { m -> m.values.sumOf { it.size } }
        sb.append("\n**Total : $total point(s) à vérifier.**\n")
        for (lot in table.lots.values) {
            sb.append("\n## ${lot.scope} — ${lot.title}\n")
            for (id in lot.packs) {
                val p = packs[id] ?: continue
                val items = perLot.getValue(lot.scope)[id].orEmpty()
                sb.append("\n### $id — ${p.title}\n\nStatut : ${p.status.label} · référence : ${p.programRef ?: "—"} · ${p.lessons.size} fiches, ${p.exercises.size} exercices, ${p.mockExams.size} épreuve(s) blanche(s)\n\n")
                val lessonsDraft = p.lessons.filter { it.status != ReviewStatus.VALIDATED }.size
                sb.append("Fiches non certifiées : $lessonsDraft / ${p.lessons.size}. ")
                if (items.isEmpty()) sb.append("Aucun point signalé (relecture complète tout de même nécessaire).\n") else {
                    sb.append("${items.size} point(s) signalé(s) :\n\n")
                    items.forEach { sb.append("- `${it.where}` — ${it.what}\n") }
                }
            }
        }
        return sb.toString()
    }

    private fun clip(s: String?, n: Int = 160): String = (s ?: "").replace(Regex("\\s+"), " ").replace("|", "¦").let { if (it.length > n) it.take(n - 1) + "…" else it }

    fun flagged(p: Pack): List<Item> {
        val out = ArrayList<Item>()
        for (l in p.lessons) {
            l.reviewNotes.forEach { out += Item(l.id, clip(it)) }
            l.blocks.forEachIndexed { k, b -> if (b.review) out += Item("${l.id} bloc ${k + 1}", clip(blockText(b))) }
        }
        for (x in p.exercises) if (x.review || x.parts.any { it.review }) out += Item(x.id, clip(x.reviewNote ?: x.parts.firstNotNullOfOrNull { it.reviewNote } ?: x.prompt))
        return out
    }

    private fun blockText(b: Block): String = when (b) {
        is Block.Text -> b.md; is Block.Key -> b.md.ifBlank { b.title ?: "" }; is Block.Formula -> b.caption ?: b.tex
        is Block.Example -> b.title; is Block.Illustration -> b.alt; else -> b.toString()
    }
}
